### ISSUE TITLE
How can I disable bounce effect while swiping from screen's left and right side?

### ISSUE THREAD

**Issue by amitchoubey** [nolimits4web/Swiper#1002]
How can I disable bounce effect while swiping, if slide is first or last pls help!

**Comment by DareDevil73** [comment]
It doesn't work for Swiper 3, why?

Ref: https://github.com/nolimits4web/Swiper/issues/1698 .

**Comment by DareDevil73** [comment]
**Solved**:

- resistance : true
- resistanceRatio : 0

**Comment by HenryTacuchi** [comment]
Thank you DareDevil73!
