### ISSUE TITLE
Error with document.element.blur() on Windows Phone

### ISSUE THREAD

**Issue by lcrodriguez** [nolimits4web/Swiper#1027]
I'm using angular on my app, when the page is open the first time it works great.
I go to another tab, and I get this error only in Windows Phone 8.1 emulator when I try to swipe again.

document.activeElement.blur()

Unhandled exception at line 15, column 4825 in ms-appx://com.phonegap.helloworld/www/components/idangerous.swiper/idangerous.swiper.min.js
0x80004005 - JavaScript runtime error: Incorrect function.

Anyone can help me?
I've fixed it removing the code for now :s

**Comment by nolimits4web** [comment]
This should be fixed in dev version
