### ISSUE TITLE
Issues with scroll bar in Safari

### ISSUE THREAD

**Issue by psychicpotato** [nolimits4web/Swiper#1032]
Hi there,

Firstly, thanks so much for developing a robust slider for web and mobile interfaces.

We're trying to develop medical imaging viewers that utilizes the iDangero.us swiper and scrollbar. A demo of this can be viewed on our development server (click on CT scans to open up the module).

http://opennet-32-70.uhnres.utoronto.ca/~albertf/localSite/TVASurg_new/TVASurg_content/surg/PT_segment67Donor.html

What we've essentially done is to utilize a vertical scrollbar to transverse through a series of 55 images, with 0 transition time between them. If you drag the scrollbar up and down, the slides will show up according to their place in sequence.

We wrote this in our scrollbar options:

    onScrollbarDrag : function(CTswiper){
    CTswiper.swipeNext();
    if (CTswiper.activeIndex == 1 && CTswiper.previousIndex == 0 )
    {CTswiper.swipePrev();}
    }

We've also set the 'speed' option in the swiper to be 0.

This all works well in Chrome and Firefox, but Safari doesn't seem to tolerate this well. Would anyone be kind to suggest what is causing this? I have a feeling that Safari's 'drag detection' might have something to do with this...

Thanks in advance, and seasons greetings.

Albert

**Comment by nolimits4web** [comment]
You may try to add the following css rules to swiper slides or to swiper images to prevent flickering:
```
-webkit-backface-visibility: hidden;
-moz-backface-visibility: hidden;
backface-visibility: hidden;
