### ISSUE TITLE
[IOS]   {prependSlide} It's  move to  the slide.     It's Bug ?   {appendSlide}  It's not move! 

### ISSUE THREAD

**Issue by raymondZhong** [nolimits4web/Swiper#1034]
In ios
appendSlide
mySwiper.appendSlide(html);     It's not move!    it's ok!

prependSlide
mySwiper.prependSlide(html);     It's  move to  the slide.     It's Bug ?

**Comment by nolimits4web** [comment]
No, it is by design. You may use .swipePrev(0) after prepending new slide

**Comment by raymondZhong** [comment]
when   swiper  changeSilder to 0,   it's  preload  3 images .  
But  swiper must  stany by 0 silder.

**Comment by raymondZhong** [comment]
Link:
http://www.zebramedia.cn/project/test/converse/lookbook-preview.html

**Comment by raymondZhong** [comment]
hi，please pay attention to here .
Thanks!
