### ISSUE TITLE
I am facing the span active class issue in pagination

### ISSUE THREAD

**Issue by muhammad-adnan** [nolimits4web/Swiper#1035]
Hi All

Hopefully everything fine, I am new to using this swiper and i used the simple app demo from demo apps folder for swipe the pages,   from last two days i read all api and tried all experiment but span
active class is not working and when i  changed the pages by swipe or click through pagination then its not make active.  Kindly guide me how i will make active class and kindly guide me in the steps.
Check below link and you see on hover green color come but on active slide this not keep

http://muhammadadnan.com/demo/

Thanks

**Comment by nolimits4web** [comment]
There is no any pagination in this app. There are two different swipers. You need to use callbacks on pages swiper and set active class on top nav-swiper, like:
```
var pages = $('.swiper-pages').swiper({
  onSlideChangeStart: function (s){
    var activeIndex = s.activeIndex;
    $('.swiper-nav .active-slide').removeClass('active-slide');
    $('.swiper-nav .swiper-slide').eq(activeIndex).addClass('active-slide');
  }
})
```
And add appropriate CSS styles for "active-slide" class
