### ISSUE TITLE
Is the swiper api lastest in the official website?

### ISSUE THREAD

**Issue by Hedgehogking** [nolimits4web/Swiper#1036]
I find that some of those are not work, and some in demo I have never seen in APIs

## never seen
<pre>
      mySwiper.updateActiveSlide(0)
</pre>

**Comment by nolimits4web** [comment]
Yes, it latest. This method is not documented because it is not for public usage, it is mostly the hack

**Comment by Hedgehogking** [comment]
But some of APIs are not work, such as 'reInit'. I use it  after I dynamically add slides, but the slide maximum is not refresh
