### ISSUE TITLE
Swiper pages have extremely long scrollbars without visible div content 

### ISSUE THREAD

**Issue by rafic20** [nolimits4web/Swiper#1039]
Hi, 

I'm running into a problem where pages with Swiper slides become very long in length (see attached GIF). My page uses a full-screen background image, which becomes very stretched due to the length of the page. 

http://i.imgur.com/AwutN4p.gif

What I noticed is that when I edit the Swiper CSS file to something like:
.swiper-container {
	/* Specify Swiper's Size: */
	width:60%;
        height: 900px;
}

the slide height is locked to 900px, but setting it to 100% means that I still see the very long page length. Obviously I would like to set it to height=100% as my site is responsive. 

I didn't see this issue in the existing threads, so maybe I am doing something very obviously wrong (I am a web dev noob). Take a look at the GIF. I can provide my page code but I don't know if JSFiddle without the backround images and other assets will be of use to you. Thanks,

**Comment by nolimits4web** [comment]
You may try to set in CSS:
```
.swiper-wrapper{
  width:100000px;
}
```
Or also try to add this option: 
```
cssWidthAndHeight: 'height'
```

**Comment by jaydombroski** [comment]
Adding `cssWidthAndHeight: 'height'` fixed the inline style height that was added to the swiper-container.
