### ISSUE TITLE
Slides per view 'auto', but force slider to show full width image on small screens

### ISSUE THREAD

**Issue by geekyme** [nolimits4web/Swiper#1041]
Hi there, 

Check out my jsfiddle. I have tried to use some CSS classes to force .swiper-wrapper, .swiper-slide and .swiper img to all be ```width:100%``` on small screens so that the slider slides 1 image at a time. 

But it doesn't appear to be working. Please help

http://jsfiddle.net/XMV2r/84/

**Comment by nolimits4web** [comment]
What do you expect? Your CSS which is "not working" is wrong. In this case you should limit your images manually using CSS or JS, for example in CSS:
```
.swiper-slide img {
  max-width:100wv;
}
