### ISSUE TITLE
onSlideChangeEnd could not work

### ISSUE THREAD

**Issue by Hedgehogking** [nolimits4web/Swiper#1042]
when I drag the slider, if warpper's offset left bigger than 0, or smaller than -1 * Maximum ,onSlideChangeEnd could not work

**Comment by nolimits4web** [comment]
Try to also use onSlideReset callback for that case

**Comment by Hedgehogking** [comment]
Both are not work...

**Comment by nolimits4web** [comment]
Then it would be nice to see JSFiddle with not working example

**Comment by Hedgehogking** [comment]
En, onSlideReset can work properly but not onSlideChangeEnd  on JSFiddle. Thx.
