### ISSUE TITLE
Direction issue

### ISSUE THREAD

**Issue by sodayg** [nolimits4web/Swiper#1044]
hi.
i'm trying to use your script in a website i develop. 
is there a way to tell the slide container to start on the right?
you can see what i did in this url: http://sodasites.co.il/bilderish/
its in Hebrew so look for the section that has some vertical stripes with numbers on it  :)
i want the slider to start with the stripe number one on the right.
right now it starts with stripe number 6 on the left  
any help will be appreciated,
thanks

**Comment by sodayg** [comment]
i'm using  scrollContainer: true
will it work?

**Comment by nolimits4web** [comment]
In this case not. You may use then setWrapperTranslate method:
```
mySwiper.setWrapperTranslate($(window).width() - $('.swiper-slide').width());
```
But use appropriate selector instead of $('.swiper-slide') for this current slide

**Comment by sodayg** [comment]
thanks!   i'll check it

**Comment by sodayg** [comment]
it worked great
thank you!
