### ISSUE TITLE
 How to reduce the memory footprint

### ISSUE THREAD

**Issue by kslr** [nolimits4web/Swiper#1046]
Page uses 200M memory on restart PLUS occasionally encounter problems, by reducing the 1/10 occupied useCSS3Transforms option, is there any way to reduce the number of memory the best practices?

**Comment by yogie89** [comment]
how to check the memory usage on iphone browser?

**Comment by kslr** [comment]
Oh, this is two words, I see chrome Task Manager.
I guess the reason is the memory footprint too, want to know what treatment approaches
