### ISSUE TITLE
How fully initialized Swiper ( all attributes )

### ISSUE THREAD

**Issue by zwlcoding** [nolimits4web/Swiper#1050]
div # box

var mySwiper;
ajax ({
   success: function () {
     ...
     $ ("# box") html (dom).;
     mySwiper = new Swiper ({...})
   }
})

When I insert the contents of the ajax when I re-initialize swiper;
However. I need to read the contents of multiple uses ajax and inserted into #box in. (Each will be replaced with the latest ajax content, length is not fixed), pagination will be a problem, and the slide will remain on a number (for example, the last time there are three pages, the second  is correct 5, but it is still only a sliding 3).

I guess reinit not fully initialized data, or whether there are ways to completely destroy Swiper?

Sorry. My English is not good.

**Comment by meivin123** [comment]
mySwiper.destroy()
For more info take a look in the API docs.
