### ISSUE TITLE
Bug on iPhone

### ISSUE THREAD

**Issue by guillaumebaeriswyl** [nolimits4web/Swiper#1051]
Hi there,

The mobile scroll (only on iPhone) is a bit stiff...
Unfortunately, I don't have any iPhone and the dev toolbar doesn't simulate this bug.

You can see the live website here (but you won't notice the bug if you aren't on a iPhone 4) : www.peterwatkins.co.uk
(If you are not on a mobile, please go to this url : http://www.peterwatkins.co.uk/homepagemobile.html)

Can someone notice the bug and help me to improve the scroll ?

Thanks a lot.

**Comment by DusanMilko** [comment]
This plugin uses translate3d which is sluggish now on ios 7 and up
http://indiegamr.com/ios6-html-hardware-acceleration-changes-and-how-to-fix-them/

**Comment by nolimits4web** [comment]
@DusanMilko using translate2d just make things slower, those articles are very outdated

@guillaumebaeriswyl Just add the following CSS rule to swiper-slide:
```
.swiper-slide {
  ...
  overflow:auto;
  -webkit-overflow-scrolling: touch;
}

**Comment by guillaumebaeriswyl** [comment]
Thanks a lot, that's perfect !
