### ISSUE TITLE
swiper not working after ajax load .

### ISSUE THREAD

**Issue by mkkmail** [nolimits4web/Swiper#1053]
Hi. thank you for your great slider. i have a problem. i use jquery 1.11 and this code to ajax load wordpress post content in sidebar . everything is good but jquery functions of swiper not work and swiper slider in post content not work. however if i refresh the post without ajax everything is good. whats the problem? 

ajaxify code to load post content:

	jQuery(document).ready(function($){
		$.ajaxSetup({cache:false});
		$(document).on('click', ".post-link", function () {
			$( ".sidebar" ).toggleClass( "sidebar-slide" );
			$( ".content-wrap" ).toggleClass( "content-slide" );
            var post_link = $(this).attr("href")+' #content';
            $("#single-post-container").html("<div class='loader'></div><span class='tload'>بارگذاری ...</span>");
			$("#single-post-container").load($(this).attr("href")+' #content', function(response, status, xhr) { // complete callback

					// create a empty div
					var div = document.createElement('div');
					// fill div with response
					div.innerHTML = response;
					// take correct part of the response
					var ref = $($(div).find('#content').html());
					// filter response for script tags
					ref.filter('script').each(function () {
						// execute the scripts
						$.globalEval(this.text || this.textContent || this.innerHTML || '');
					});
				
			});

			
			
			
        return false;
        });
    });

initialize swiper code: 

       document.addEventListener('DOMContentLoaded', function(){
       var mySwiper = $('.swiper-container').swiper({
       mode:'horizontal',
       loop: true
      });
      }, false)

**Comment by nolimits4web** [comment]
You should init Swiper after Ajax request:
```
jQuery(document).ready(function($){
    $.ajaxSetup({cache:false});
    $(document).on('click', ".post-link", function () {
        $( ".sidebar" ).toggleClass( "sidebar-slide" );
        $( ".content-wrap" ).toggleClass( "content-slide" );
        var post_link = $(this).attr("href")+' #content';
        $("#single-post-container").html("<div class='loader'></div><span class='tload'>بارگذاری ...</span>");
        $("#single-post-container").load($(this).attr("href")+' #content', function(response, status, xhr) { // complete callback

                // create a empty div
                var div = document.createElement('div');
                // fill div with response
                div.innerHTML = response;
                // take correct part of the response
                var ref = $($(div).find('#content').html());
                // filter response for script tags
                ref.filter('script').each(function () {
                    // execute the scripts
                    $.globalEval(this.text || this.textContent || this.innerHTML || '');
                });
                var mySwiper = $('.swiper-container').swiper({
                  mode: 'horizontal',
                  loop: true
                })

        });




    return false;
    });
});

**Comment by mkkmail** [comment]
Thanks nolimits4web for reply.
it Works.
