### ISSUE TITLE
set shortSwipes false,and then onSlideChangeEnd doesn't work.

### ISSUE THREAD

**Issue by xlkit456852** [nolimits4web/Swiper#1054]
I want to prevent small swipes from moving the current slide to left or right .So I set shortSwipes true and I find onSlideChangeEnd didn't work when sliding to the next/prev slide . How can I resolve this ?

**Comment by nolimits4web** [comment]
Try to use onSlideRest callback instead

**Comment by xlkit456852** [comment]
Thanks so much.
