### ISSUE TITLE
Hash functionality not working well.

### ISSUE THREAD

**Issue by myuseringithub** [nolimits4web/Swiper#1056]
Hi, thanks for the great product. I have searched for a product that will do the same effect as in Google movies search: http://goo.gl/G9GTEI  As you may see it allows swipe and also automatically directs to the element that was selected and scrolls to it. Your plugin was closest to what I am looking for.

the website I'm having issue with: http://dentrist.com/ swiper is active only on mobile platforms.
If you will visit the website the top menu Swiper does work, but the Hash Navigation plugin is problematic. It doesn't work well. I couldn't find why. 

Swiper JS loader:
![1](https://cloud.githubusercontent.com/assets/7758497/5793938/68225886-9f61-11e4-8bca-0e447831454b.PNG)

HTML from chrome inspector:
![2](https://cloud.githubusercontent.com/assets/7758497/5793969/75a13b02-9f62-11e4-87ff-82ffc62ae422.PNG)

**Comment by nolimits4web** [comment]
I see it works fine, but you have a links on that menu, so with page reload it looses hash

**Comment by myuseringithub** [comment]
Oh, That was a fast response. 

If I try to visit: http://dentrist.com/quize/#slide1075
It should focus on the last one from the right, but on mobile it doesn't (and neither desktop).

**Comment by myuseringithub** [comment]
I added "centeredSlides: true" to the JS loader so it will be more visible. It doesn't center the item if hashtag is added to the visited URL ( e.g. http://dentrist.com/quize/#slide1075).

**Comment by myuseringithub** [comment]
Am I doing anything wrong ?

What it does:
![screenshot 10-50pm jan 18 2015](https://cloud.githubusercontent.com/assets/7758497/5794027/930452c2-9f64-11e4-9588-c3006d8b5906.png)

What I want it to do: when adding #slide1286 (for the articles hash number)
![screenshot 10-53pm jan 18 2015](https://cloud.githubusercontent.com/assets/7758497/5794035/e03d0caa-9f64-11e4-87c7-3ba66135f4de.png)

**Comment by nolimits4web** [comment]
I see you have errors in console. Can you try to disable `pagination` parameter on Swiper, you don't have it

**Comment by myuseringithub** [comment]
disabled both:
    pagination: '.pagination',
    paginationClickable: true,
(deleted them)

**Comment by myuseringithub** [comment]
Oh great now it work like a charm. Thank you so much. 

I have last request:

**Comment by myuseringithub** [comment]
Is there a way to activate an item without the use of hash ?

**Comment by myuseringithub** [comment]
Ya, I found that it also fixed the " initialSlide " functionality. i think this is what I will use. 
Thank you very much !
