### ISSUE TITLE
innerhtml not working when setting loop:true

### ISSUE THREAD

**Issue by tim7004** [nolimits4web/Swiper#1059]
Dear all,
here is my setting:
var mySwiper = new Swiper('.swiper-container',{
    loop:true,
    grabCursor: true,
    initialSlide: 1,
    paginationClickable: true
 });

I want to update the content inside my slide after ajax call:
$("body").on("click",".button",function(){
			var data = {
				control: "get-node-list"
			};
				data = $(this).serialize() + "&" + $.param(data);
			 $.ajax({
			  type: "POST",
			  dataType: "json",
			  url: "http://example.com/example.php",
			  data: data,
			  success: function(data) {
					document.getElementById('node_list').innerHTML = data.node_row;
					alert(document.getElementById('node_list').innerHTML);//the data is correct
				}
				});
});
the data inside node_list can be change when I set loop:false, but after setting loop: true, the data inside node_list doesn't be updated and it still show the old data...Please help! Thank you.

**Comment by nolimits4web** [comment]
Loop mode uses duplicated slides, so change your element ID to class and use like `$('.node_list').html(...)`

**Comment by tim7004** [comment]
Thx nolimits4web ~ It works!
