### ISSUE TITLE
Set container height to that of visible slide only

### ISSUE THREAD

**Issue by marfire** [nolimits4web/Swiper#1060]
I have a feeling that Swiper can't currently accommodate my use case, but let me see.

I have a horizontal Swiper containing full-width slides of varying heights. What I would like is for the swiper container's height to be dynamically updated to be the height of the currently visible slide (ignoring the height of any offscreen slides).

If I use `calculateHeight=true`, then the container will be set to the maximum height of any slide, potentially leaving lots of empty space below the visible slide.

If I instead set the height of the container (as in #1014), the scrollbar will appear on the div, rather than on the entire page. Whereas what I want is for the height of the page to change with each slide, so that just the main scrollbar is used.

I figure I can do this myself by listening to `slideChangeEnd` and manually setting the height of the container. But maybe I'm missing something. Do you see any problems with this approach? Is this something you'd consider for Swiper?

(Thanks for the great work.)

**Comment by nolimits4web** [comment]
There is no problems with your approach with setting height using onSlideChangeEnd. It is correct
