### ISSUE TITLE
Callback for showing last slide

### ISSUE THREAD

**Issue by jeremypbeasley** [nolimits4web/Swiper#1061]
I'm using:

$('.swiper-container').on('click', function(e){
  e.preventDefault();
  mySwiper.swipeNext();
});

to allow for desktop users to easily click through a series of slides and I would like to fire an animation if they continue clicking once it's reached the last slide. Obviously I have no loop enabled.

Is this possible somehow?

**Comment by nolimits4web** [comment]
You may use onSlideChangeEnd callback:
```
onSlideChangeEnd: function(s) {
  var endPosition = -($('.swiper-wrapper').width() - $('.swiper-container').width());
  if (s.getWrapperTranslate() <= endPosition) {
    //do something
  }
}

**Comment by jeremypbeasley** [comment]
Thanks!
