### ISSUE TITLE
reinit and resizefix are not working in mobile but work in browser.

### ISSUE THREAD

**Issue by hosing** [nolimits4web/Swiper#1065]
I load dynamic number of  photo from Flickr. So I need to reinit in order to scoll down. And the code is working in chrome. but it doesnt work when I embed to a mobile app.

 function reinitSwiper(swiper) {
  setTimeout(function () {
   swiper.reInit();
  }, 1000);
}

**Comment by nolimits4web** [comment]
Why you use setTimeout, what does it means? You probably need to do reinit after your Flickr images being loaded, you may use some plugin to know when they are loaded, for example https://github.com/desandro/imagesloaded
