### ISSUE TITLE
Is it possible to add event like pinch and spread ? 

### ISSUE THREAD

**Issue by xlkit456852** [nolimits4web/Swiper#1066]
I want to listen the pinch and spread event on mobile device , so I can use this finger movements to  zoom the size of images . And I also find a plugin zTouch.js and I want to use it into my project with Swiper . Unfortunately this plugin is incompatible with Swiper and I must use Swipert(you know it's awesome) in my project. So I think if it's possible that Swiper can own pinch and spread event and that will be perfect . 
![2015-01-23_161544](https://cloud.githubusercontent.com/assets/7323450/5871622/6d1f02b8-a31b-11e4-9160-71e6e5c9a14c.jpg)

**Comment by nolimits4web** [comment]
You may try to use Hammer.js http://hammerjs.github.io/
