### ISSUE TITLE
onSlideChangeEnd not called when speed 0

### ISSUE THREAD

**Issue by sbrauer** [nolimits4web/Swiper#1067]
I've found that when calling swiper.swipeTo() with the speed parameter set to zero, the onSlideChangeEnd callback doesn't occur (but onSlideChangeStart does).

Is this a bug or intentional?

If it's intentional, is there some other callback that is fired every time a slide becomes active?

**Comment by nolimits4web** [comment]
Because there is no transition. You may use onSlideChangeStart in this case

**Comment by sbrauer** [comment]
That makes sense. Thank you!
