### ISSUE TITLE
Document onAutoplayStop/onAutoplayStart

### ISSUE THREAD

**Issue by thenewguy** [nolimits4web/Swiper#1069]
https://github.com/nolimits4web/Swiper/issues/584 added onAutoplayStop/onAutoplayStart but they do not seem to be documented.

Also, the documentation lists the default autoplay value at 5000, but it seems that the default is disabled

**Comment by nolimits4web** [comment]
Yes, there is a error in docs, it is disabled by default. Can't promise that i will update docs, because i prepare Swiper3 to release which is already done, and it will have new website

**Comment by thenewguy** [comment]
No problem.  I'm enjoying swiper!
