### ISSUE TITLE
Horizontal sliding doesn't work in portrait mode

### ISSUE THREAD

**Issue by l4zl0w** [nolimits4web/Swiper#1070]
I'm trying to get this work in portrait mode but it only seems to be working in vertical mode.

My html:
```
<div class="swiper-container">
	    <div class="swiper-wrapper" style="width: 960px; height: 960px; transition-duration: 0.3s; -webkit-transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px); -webkit-transform: translate3d(0px, 0px, 0px);">
		<div class="swiper-slide swiper-slide-visible swiper-slide-active" style="width: 320px; height: 960px;">
		       <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1...">
		</div>
		<div class="swiper-slide" style="width: 320px; height: 960px;">
		       <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1...">
		</div>
		<div class="swiper-slide" style="width: 320px; height: 960px;">
		       <img src="https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xpf1...">
		</div>
	</div>
</div>
```
JS:
```
var mySwiper = $(".swiper-container").swiper({
		    mode: "horizontal"
		});
```

Note, this is called by another function after the above HTML is dynamically inserted to the DOM. 

Note that the images are not full screen, there are other elements in the window outside of the swiper-container.

When I swipe left, the swipe happens, the html element gets activated but the images are not shown but whitespace instead.

**Comment by nolimits4web** [comment]
Do you have a live link so i can take a look?

**Comment by l4zl0w** [comment]
Unfortunately no, but when I scroll to the left my HTML is like this:

'''
<div class="swiper-container">
	<div class="swiper-wrapper" style="width: 960px; height: 960px; transition-duration: 0.3s; -webkit-transition-duration: 0.3s; transform: translate3d(-320px, 0px, 0px); -webkit-transform: translate3d(-320px, 0px, 0px);">
	   	<div class="swiper-slide" style="width: 320px; height: 960px;">
		       <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1...">
		</div>
		<div class="swiper-slide swiper-slide-visible swiper-slide-active" style="width: 320px; height: 960px;">
		      <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1...">
		 </div>
		 <div class="swiper-slide" style="width: 320px; height: 960px;">
		       <img src="https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-...">
		 </div>
	</div>
</div>
'''

So the active marker moves to the second swiper-slide element and the first picture moves out of the window, but the second picture is not shown. There is only whitespace there.

If I swipe back, the first picture comes back.

Any idea?

**Comment by l4zl0w** [comment]
It looks like the pictures are stacked up on top of each other rather than next to each other.

**Comment by nolimits4web** [comment]
I guess problem could be in CSS, but sorry, can't say much without live example or jsfiddle. Closing for now
