### ISSUE TITLE
change speed for autoplay and pagination but NOT for touch

### ISSUE THREAD

**Issue by lucasdidthis** [nolimits4web/Swiper#1071]
Is it possible to change the speed for the autoplay animation and the animations triggered by the pagination without changing the speed for the touch interactions? Or is their only the speed parameter?

Thanks.

**Comment by nolimits4web** [comment]
For pagination yes, if you use custom pagination buttons and when you call .swipeTo() method, it accepts `speed` parameter that you can adjust. For other things no, not possible

**Comment by lucasdidthis** [comment]
Thanks for the reply. Too bad, but my work-around solution works pretty well: Just change the speed-parameter dynamical (via mySwiper.params.speed) on TouchStart, SlideChangeEnd and the pagination-/next-buttons.

**Comment by nolimits4web** [comment]
Ok, glad you've found a workaround
