### ISSUE TITLE
onSlideNext and SlidePrev firing twice

### ISSUE THREAD

**Issue by jeremypbeasley** [nolimits4web/Swiper#1075]
For some reason when I click and drag on desktop, this event fires twice. With keyboard control enabled, using the arrows keys, it only fires once. Any idea why?

mySwiper.addCallback('SlideNext', function(swiper){
  console.log("forward");
  currentSlide = currentSlide + 1;
  console.log(currentSlide);
});     

mySwiper.addCallback('SlidePrev', function(swiper){
  console.log("backwards");
  currentSlide = currentSlide - 1;
  console.log(currentSlide);
})

**Comment by nolimits4web** [comment]
Do you have a live link or fiddle so i can take a look?

**Comment by jeremypbeasley** [comment]
Here ya go! http://test.bsley.com/sunder/

**Comment by nolimits4web** [comment]
That is because you have
```
$('.swiper-container').on('click', function(e){
	  e.preventDefault();
	  mySwiper.swipeNext();
	});
```
So when you release swiper, you always do one more transition, so you have two callbacks
