### ISSUE TITLE
Last slide is breaking to next line

### ISSUE THREAD

**Issue by coldpumpkin** [nolimits4web/Swiper#1076]
For some reason, my last slide, in a carousel, is breaking to the next line. Even if I remove or add slides, the last one listed always breaks. Here's how it looks like
![untitled-1](https://cloud.githubusercontent.com/assets/8443880/5965048/e28a45ce-a7f0-11e4-973a-31e618f58543.jpg)

My code is as simple as:
```
    var boxSwiper = new Swiper('#single .box .swiper-container',{
        initialslide: 0,
        slidesPerView: 'auto'        
    });
    $('#single .box .swiper-container .arrow-left').on('click', function(e){
        e.preventDefault()
        boxSwiper.swipePrev()
    });
    $('#single .box .swiper-container .arrow-right').on('click', function(e){
        e.preventDefault()
        boxSwiper.swipeNext()
    });
```

**Comment by nolimits4web** [comment]
Looks like you have border or margin on "swiper-slide"? If yes, should be removed

**Comment by coldpumpkin** [comment]
Seems like that fixed it. But I kinda want the margin, how can I achieve the good result with margin?

**Comment by nolimits4web** [comment]
Add inner div with padding inside of "swiper-slide"

**Comment by coldpumpkin** [comment]
Thank you, I tried setting margin in the img instead and it also works.
