### ISSUE TITLE
Using `reInit()` to change mode (horizontal / vertical) on the fly

### ISSUE THREAD

**Issue by shanehou** [nolimits4web/Swiper#1077]
I've read another issue (https://github.com/nolimits4web/Swiper/issues/308), and I think I may use `reInit()` to achieve it but problems happened.

                var mySwiper = $('.swiper-container').swiper({
                    mode: 'vertical',
                    loop: false,
                    calculateHeight: true,
                    centeredSlides: true,
                    onSlideChangeEnd: function(swiper) {
                        if (swiper.activeIndex === 6) {
                            if (swiper.previousIndex === 5) {
                                swiper.params.mode = 'horizontal';
                                swiper.params.loop = false;
                                swiper.params.calculateHeight = true;
                                swiper.params.centeredSlides = true;
                                swiper.reInit();
                                // swiper.swipeTo(6, 100, false);
                            } else if (swiper.previousIndex === 7) {
                                swiper.params.mode = 'vertical';
                                swiper.params.loop = false;
                                swiper.params.calculateHeight = true;
                                swiper.params.centeredSlides = true;
                                swiper.reInit();
                                // swiper.swipeTo(6, 100, false);
                            }
                        }
                    }
                }

Here I want to change the mode when I swipe to the 7th slide (index is 6).

But when the swiper was reinitialized, only the page transition animation changed. Gesture to change slide remained. And also, the next slide would be empty. (BTW, after reinit, it always return to the first slide.)

**Comment by nolimits4web** [comment]
No, it will not work. You may do .destroy() and init it again with new direction
