### ISSUE TITLE
Swiper Ajax - Share your thoughts!

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Swiper#108]
Hello to everyone. I am going to implement Ajax support (probably with separate plugin) for our favourite Swiper. Please let me know what kind of options/parameters you want to see there and what kind of logic you expect from it!

**Comment by naqvisyed** [comment]
@nolimits4web  

do u have any example which work on dynamic data.
Like i want to call  my ajax service on particular swiper index ? 
but there is an issue of DOM how can i reload the dom of particular index.
