### ISSUE TITLE
Make Areas in an imagemap dragable

### ISSUE THREAD

**Issue by meivin123** [nolimits4web/Swiper#1081]
Hello,
is there a way to also allow swiping on areas in an imagemap?
So I can drag the slide on areas too?
I tried changing the "a" in the code from preventLinks to "area" but it isnt working,

**Comment by nolimits4web** [comment]
What is your HTML?

**Comment by meivin123** [comment]
´
<div id="bench-wrapper" class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <img src="<?php TDIR(); ?>/img/img.png" 
                 alt=""
                 usemap="#benchMap"/>
        </div>
    </div>
    <div class="scrollbar"></div>
</div>
´

**Comment by nolimits4web** [comment]
And what and where did you make changes? I guess it should be on this line:
```
if (params.preventLinks) {
  var links = $$('a', _this.container);
...
```
to 
```
if (params.preventLinks) {
  var links = $$('area', _this.container);
...
```

But your map with area should be inside of "swiper-container"

**Comment by meivin123** [comment]
Nice thx.
