### ISSUE TITLE
Swipe more than one slide per once when clicking arrows

### ISSUE THREAD

**Issue by coldpumpkin** [nolimits4web/Swiper#1082]
Hello again,

I'm using the swiper in carousel mode and I have next and previous arrows. Anytime I click either, it advances or rewinds one slider. Is there a way to make it more than one?

Thanks.

**Comment by nolimits4web** [comment]
You may try the slidesPerGroup parameter or use .swipeTo method by passing custom index there

**Comment by coldpumpkin** [comment]
The slidesPerGroup didn't work (I set it to 2) and the swipeTo method I can't find it in the API :\

**Comment by nolimits4web** [comment]
@coldpumpkin i guess you use Swiper 2.x, it is API here https://github.com/nolimits4web/Swiper#swiper-2xx

**Comment by coldpumpkin** [comment]
Alright, I think I found it: `mySwiper.swipeTo(index, speed, runCallbacks) `

I should put it in my arrow function, right? Only thing is, I don't understand what I should put in the index parameter :O
