### ISSUE TITLE
swipeTo, clickedSlideIndex indexes base

### ISSUE THREAD

**Issue by JohnGurin** [nolimits4web/Swiper#1085]
Apparently 
```swipeTo(index, speed, callback)``` is zero-based and
```clickedSlideIndex``` returns one-based index.
Is it right?

I use ```swiper.swipeTo(swiper.clickedSlideIndex - 1,0);``` inside ```onSlideClick``` handler to prevent the possibility of clicking on a slide during a transition.
Maybe there is another approach?

**Comment by nolimits4web** [comment]
No, it returns the same 0 based index. Probably you have enabled loop
