### ISSUE TITLE
onSlideChangeEnd is not firing when sliding fast and over the slides

### ISSUE THREAD

**Issue by tuomaslaa** [nolimits4web/Swiper#1086]
onSlideChangeEnd is not firing when you move fast and in the beginning or in the end you still try to slide  more. This happens at least when using iOS 8.1.3. and Safari.

My settings:
            pagination: '.pagination',
            speed: 450,
            loop: false,
            paginationClickable: false,
            resistance : "100%",
            noSwiping : false,
            longSwipesRatio : 0.35,
            eventTarget: 'container',

**Comment by nolimits4web** [comment]
It was discussed many times, because when you slide fast there is no "transitionend" event. Anyway, check Swiper 3
