### ISSUE TITLE
Is there any way to prevent the extra white space

### ISSUE THREAD

**Issue by faressoft** [nolimits4web/Swiper#1087]
![screenshot-2015-02-08-07 51 39](https://cloud.githubusercontent.com/assets/1908658/6095480/c994fffe-af67-11e4-8b44-e994693bd878.png)

Is there any way to prevent the extra white space ?

**Comment by nolimits4web** [comment]
That is something wrong with your styles, probably there are some conflicts with your CSS

**Comment by faressoft** [comment]
It is from the demo page of swiper. It is not something wrong. It is the normal behaviour of the plugin. It happens when dragging the first slide to the right side.

**Comment by nolimits4web** [comment]
Oh, that is called "resistance". You may add `resistance: '100%'` parameter

**Comment by faressoft** [comment]
Thats it. Great :)
Thank very much
