### ISSUE TITLE
Any idea when Swiper3 will become alive ?

### ISSUE THREAD

**Issue by hyyan** [nolimits4web/Swiper#1088]

**Comment by nolimits4web** [comment]
It is actually ready, just need time to write docs and more demos. But you can try and see it here https://github.com/nolimits4web/Swiper/tree/Swiper3

**Comment by hyyan** [comment]
@nolimits4web  Thanks , I will give a try immediately :smile:

**Comment by nolimits4web** [comment]
So? Did you try it out?)

**Comment by hyyan** [comment]
@nolimits4web Of course , awesome as I expected , :smile:
