### ISSUE TITLE
how can I make text selectable? 

### ISSUE THREAD

**Issue by qurtopianodesign** [nolimits4web/Swiper#1089]
how can I make text selectable? i try with:
$('.swiper-slide select').on('MSPointerDown pointerdown MSPointerMove pointermove MSPointerUp pointerup', function(e){
  e.stopPropagation();
})

but nothing...

**Comment by nolimits4web** [comment]
```
$('.swiper-slide select').on('touchstart mousedown MSPointerDown pointerdown', function(e){
  e.stopPropagation();
})

**Comment by qurtopianodesign** [comment]
I tried but it does not work, if possbile I must find a way to be able to select text while the function of swipe...
