### ISSUE TITLE
Swiper miscalculates width and height when using percentages

### ISSUE THREAD

**Issue by kokujin** [nolimits4web/Swiper#109]
I really need the swiper to be resonsive in my Zurb Foundation grid so I am doing this:

/\* Specify Swiper's Size:    idangerous.swipers.css*/
.swiper-container, .swiper-slide {
    width: 90%;
    height:: 100%;
}

This does not calculate the widths and heights based on a percentage but makes them absolute pixel values out out them. The above creates the following values:
class="swiper-wrapper" style="width: 90px; height: 100px;" <-- note PX instead of  percentages

class="swiper-slide" style="width: 22.5px; height: 100px;" <- havoc here, I have no idea why it now calculates 22.5px for the width and leaving the height at 100px. Anyway, both values are wrong.

Any ideas what I am doing wrong? Thanks

**Comment by ShivkAgg** [comment]
Hey I am facing an issue am using swiper in ul li tags and its working fine but its shows li from center and I need it from top

any idea..?

**Comment by MrAndrianos** [comment]
I need direction! I use the latest swiper API version into an opencart template. The issue is the height of swiper-container. When i resize the screen the slides are cutting off !

**Comment by Filliposniper** [comment]
I am having a hard time with my swiper height  also, it scales responsively in width but it repeats the bg image on top and bottom. Here is the css i used any help is appreciated.

`@media only screen and (max-width: 991px){
    .swiper-slide {
        background-size: contain !important;
        background-repeat: no-repeat ! immportant;
        background-position: 0 50px !important;
        position: relative;
    }
}
`

**Comment by Filliposniper** [comment]
I think i have found the solution. but then you have to play with your desired height but the background image will be responsive, to prevent  bg image from repeating you have to use "background-size:  cover" here it goes.

`@media only screen and (max-width: 1170px){
    .swiper-slide {
        background-size: cover !important;
        background-repeat: no-repeat ! important;
        background-position: 0 0 !important;
    }
    .swiper-container{
        height: 600px;
    }
}`
