### ISSUE TITLE
Responsive view problem 

### ISSUE THREAD

**Issue by Issaxis** [nolimits4web/Swiper#1090]
Hello,
I am using your slider and bootstrap on my page
 code:

    <div class="widget-content">
        <div class="swiper-container" id="close-out-slider">
        	
		  <div class="swiper-wrapper">
		    
		      
		      <div class="swiper-slide">
		        
		        <div class="row">
		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-1.png" alt="close-out-1">
		        			<a href=""><div class="buy-now"></div></a>
		        			<div class="slider-product-name">Marque</div>
		        			<div class="slider-product-price">$10 - $15</div>
		        		</a>
		        	</div>

		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-2.png" alt="close-out-2">
		        			<div class="slider-product-name">Dauphine Throw & Pillow</div>
		        			<div class="slider-product-price">$550 - $750</div>
		        		</a>
		        	</div>

		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-3.png" alt="close-out-3">
		        			<div class="slider-product-name">Foglia</div>
		        			<div class="slider-product-price">$120 - $875</div>
		        		</a>
		        	</div>

		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-4.png" alt="close-out-4">
		        			<div class="slider-product-name">Lovable 21 Baby</div>
		        			<div class="slider-product-price">$50 - $350</div>
		        		</a>
		        	</div>
		        </div>
		      </div>
		      
		      
		      <div class="swiper-slide">
		        <div class="row">
		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-2.png" alt="close-out-2">
		        			<div class="slider-product-name">Dauphine Throw & Pillow</div>
		        			<div class="slider-product-price">$550 - $750</div>
		        		</a>
		        	</div>

		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-3.png" alt="close-out-3">
		        			<div class="slider-product-name">Foglia</div>
		        			<div class="slider-product-price">$120 - $875</div>
		        		</a>
		        	</div>

		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-4.png" alt="close-out-4">
		        			<div class="slider-product-name">Lovable 21 Baby</div>
		        			<div class="slider-product-price">$50 - $350</div>
		        		</a>
		        	</div>

		        	<div class="col-md-3 col-sm-3">
		        		<a href="">
		        			<img src="images/frontend/close-out-1.png" alt="close-out-1">
		        			<div class="slider-product-name">Marque</div>
		        			<div class="slider-product-price">$10 - $15</div>
		        		</a>
		        	</div>
		        </div>
		      </div>
		  </div>
		  
		</div>
        
    </div>
</div>

$(function(){
  var mySwiper = new Swiper('.swiper-container#close-out-slider',{
    speed:750,
    mode:'horizontal',
    loop: true,
    pagination:'.pagination-close',
    createPagination:true,
    paginationClickable: true,
    swipeToNext:true,
    swipeToPrev:true,
    grabCursor:true,
    calculateHeight:true,
    visibilityFullFit:true,
  });
  $(window).resize(function() {
    mySwiper.reInit()
	});
})

My problem is that I want to show only one element col-md-3 on mobile view, but now they are all showing up like one under one in very high slide.

Is it posible to show Them like i want?

(code might look not complete but all is working and reason is just paste in here)

**Comment by nolimits4web** [comment]
That is probably conflict with some styles, as Swiper shouldn't break it at all. Anyway, closing for now, as Swiper 3 just released with new API. If you have this issue with Swiper 3 reopen it
