### ISSUE TITLE
Attention! All issues are closed with release of new Swiper 3!

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Swiper#1092]
Note, that i have closed all issues with the release of Swiper 3. Which was rewritten from scratch, it has new API, new layout, compatible with different browsers, and has a bit different usage purpose. First of all, it is absolutely doesn't compatible with IE < 10 and Android < 4. 

So, old closed issues are not really related to new Swiper, or outdated, or their authors doesn't provide more required information or dropped discussion.

Anyway, you may reopen your closed issue or create new one if it is actual for Swiper 3

**Comment by cjjuice** [comment]
Nice work! Looking forward to exploring 3.0!

**Comment by LucasKA** [comment]
@nolimits4web I just started looking into implementing this earlier in the morning, are the API Docs linked in the README current to 3.x?

**Comment by nolimits4web** [comment]
@LucasKA Yes, everything is related to 3.x now. If you need to 2.x docs, you may found it here https://github.com/nolimits4web/Swiper/blob/Swiper2/API.md

**Comment by Rikk** [comment]
Will 2.x be discontinued?

**Comment by nolimits4web** [comment]
@Rikk yes

**Comment by Rikk** [comment]
Ok.
I didn't follow the development of the new version and couldn't find in the site but I think it would be interesting for users to know: what improvements were made to the new version, what features are new¹ and which ones were removed? Maybe it could be added to readme or changelog, it would be specially useful for people thinking about upgrading. Thanks!
¹ Was hash-navigation plugin incorporated, right?

**Comment by nolimits4web** [comment]
@Rikk Hard to say like that, because it could be a long list:) As a quick review

Removed features:
- totally dropped old browsers support 
- removed scollContainer in favor of using pure CSS overscroll:auto, which as much better performance and more native look on mobiles

Totally new features:
- new layout, now it uses flexbox instead of float:left with nasty size calculations like in 2.x. It should fix a lot of errors and cases with wrong/long/heavy sizes in 2.x
- all 2.x plugins (3D Flow, Progress, Hahshnav, Scrollbar) are incorporated and parts of the core in Swiper 3
- new built in transition effects: Fade, Cube, Coverflow
- true RTL support
- built in navigation buttons/arrows
- controller. Now one Swiper can be controlled by another one and contra versa
- multi row slides layout
- touch events handling with "captures". This allows to create horizontal in horizontal swipers
- pagination works in different way, it is now dynamic and number of bullets is always equal to number of so called "snaps", not to number of slides like in 2.x

So, as you see, most of 2.x features are here, but reworked, improved and increased with new great things ;)

**Comment by Rikk** [comment]
Thanks for keeping the great work!

(Now we need MS to kill IE up to 9, so the web can evolve too...)

**Comment by Taras123** [comment]
Thank you for continuous developing of such a good plugin. We are still using it to support ie9 but i agree that such browser must be forgotten in the past. Just one quick note - it works perfectly in Chrome and ie11, but in Firefox 35.0.1 mouse drag events are not working. I believe it is because of great update and can be fixed. Once again - thank you for your work.

**Comment by nolimits4web** [comment]
@Taras123 
With 3.0.1 should work ok in FF. And here is info about Swiper 2 if you still use it https://github.com/nolimits4web/Swiper#swiper-2xx

**Comment by knarfytrebil** [comment]
I'm migrating from 2.7.5 to 3.0.1, and I am using Swiper on my Hybrid mobile application, which relies on the 'pull down to refresh' feature heavily. And it seems the demo of that is missing. And since I'm using backbone.js, I realize when used with listviews with backbone items with delegated touch events ( like tap ) the scrolling gesture on freemode, also triggers the 'tap' event easily.

**Comment by KennyJack** [comment]
hi nolimits4web ,

I'm using swiper version3.0.8, and i found that in all IE 9, 10 and 11 having problem when click to next slide. The error shown 

SCRIPT438: Object doesn't support property or method 'transition' 
swiper.jquery.min.js, line 15 character 31485

could you please guide me how to solve this in ie?

**Comment by solarcellsky** [comment]
use this in head tags to work with IE9 or less
``

https://github.com/eligrey/classList.js
