### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by stephanebachelier** [nolimits4web/Swiper#1093]
@nolimits4web it may help some users that you add a reference to the last 2.x.x release and the Swiper2 branch in the current README.
There are lots of projects supporting old platforms and Swiper2 is still really one of the best existing.

and as always thank 4 u work, always awesome.

**Comment by nolimits4web** [comment]
Sure, will add it tomorrow

**Comment by tpinne** [comment]
And please make the API doc for 2.x.x available. I'm currently in a project with version 2.x.x and need that docs.

**Comment by nolimits4web** [comment]
@tpinne they are here https://github.com/nolimits4web/Swiper/blob/Swiper2/API.md

**Comment by nolimits4web** [comment]
Information about Swiper 2 added
