### ISSUE TITLE
Missing .js-reference in "main" in package.json

### ISSUE THREAD

**Issue by dgsunesen** [nolimits4web/Swiper#1097]
Hi,

I just updated to your latest version, but when I try to require your model, I keep getting 'Cannot find module swiper'.. So I looked through your package.json and it seems you're missing a reference to the swiper.js file in "main"... I guess instead of just "main": "dist/" it should be "main": "dist/js/swiper.js"..

Cheers.

**Comment by nolimits4web** [comment]
Yes, it is already fixed here, so in bower will be available with next release

**Comment by dgsunesen** [comment]
So if I update to latest version it should be fixed? I'm using it through npm not bower :)

**Comment by nolimits4web** [comment]
I guess it will not work with npm until new release. So you may specify custom path to script

**Comment by nolimits4web** [comment]
Fixed with 3.0.1 release
