### ISSUE TITLE
fade effect does not fade out inactive slides

### ISSUE THREAD

**Issue by cjjuice** [nolimits4web/Swiper#1098]
Can anyone else replicate?

I have images that do not completely fill the slide and I can see slides behind when using this effect.

**Comment by nolimits4web** [comment]
It is by design, because new slide just cover old one. Will think about adding cross fade feature. But as a solution you may use background-color on slide

**Comment by cjjuice** [comment]
background-color doesn't meet my needs in this case. I need it to be transparent since the slide is overlaying a background gif. May have to roll something custom

**Comment by nolimits4web** [comment]
You can make changes in core than for fade effect:
```
s.effects = {
    fade: {
        setTranslate: function () {
            for (var i = 0; i < s.slides.length; i++) {
                var slide = s.slides.eq(i);
                var offset = slide[0].swiperSlideOffset;
                var tx = -offset - s.translate;
                var ty = 0;
                if (!isH()) {
                    ty = tx;
                    tx = 0;
                }
                slide
                    .css({
                        //change opacity rule here
                        opacity: 1 + Math.min(Math.max(slide[0].progress, -1), 0)
                    })
                    .transform('translate3d(' + tx + 'px, ' + ty + 'px, 0px)');

            }
...

**Comment by cjjuice** [comment]
thanks!

**Comment by maddesigns** [comment]
ok. I have the same issue. What can I change to hide inactive slides?

**Comment by maddesigns** [comment]
I'm not the JS guy, but this fixed it for me:
```
.css({
  opacity: (slide[0].progress ? 0 : 1)
})
```

**Comment by AdamMarsden** [comment]
This is still a problem, can we open this up again?

**Comment by nolimits4web** [comment]
@AdamMarsden there is a crossFade parameter for that

**Comment by AdamMarsden** [comment]
@nolimits4web What about with you have two different slides that are controlling each other and you have one slide with 2 slides per view and the other with one? It seems to break and is very buggy.

**Comment by nolimits4web** [comment]
Fade effect doesn't intended to be used with slidesPerView more than 1

**Comment by thesublimeobject** [comment]
I am having this same issue, which seems to stem from the fact that you are assuming that any slider will have a background-color or background-image. To be fair, I don't think this is a horrible assumption, and perhaps something that I could overlook when writing something like this. Nonetheless, I am in a situation where I would like to use this library over a background that has a gradient on the div behind the slider; so there's really nothing that I can do to mend the issue on my side other than setting a CSS rule with opacity !important. 

This _will work_, but I think with the surprising number of issues I found that encountered this or a similar issue, it would be worth taking into consideration. This is my first time using this slider, but given the number of configuration options, if it works well, I'll probably switch to this as my go-to slider. I'd be happy to write the fix for it myself and submit a pull request, but based on the history of this issue it seems that you may be, for some reason, opposed to it?

**Comment by nolimits4web** [comment]
@thesublimeobject there is a crossFade option for this

**Comment by thesublimeobject** [comment]
@nolimits4web I'll have to double check, but I remember trying that option and it not solving the problem. But I'll definitely give it another try!

**Comment by tini2n** [comment]
@nolimits4web tried to use as in documentation, but cross fade is still not working.
Version is 4.0.7

`
let lightboxSlider  = new Swiper('.lightbox-container .swiper-container', {
        effect: 'fade',
        fade: { crossFade: true },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
        autoHeight: true
    });
`
How I can fix it?

**Comment by mjot** [comment]
@tini2n I can confirm it, cross fade isn't working in 4.0.7. Could we reopen this issue? @nolimits4web

**Comment by KiryaAfimin** [comment]
@mjot this works in 4.1.0`fadeEffect: {
    crossFade: true
  },`

**Comment by muhammadadamfirdaus** [comment]
I still got this issue in 4.2.2 with crossFade: true.

**Comment by ezetojo** [comment]
.swiper-slide:not(.swiper-slide-active){
  opacity: 0 !important;
}

**Comment by hal869** [comment]
@ezetojo That _does_ fix the non-zero opacity of not-active slides.  Thx!

But ... with

  swiper@4.3.3

The _active_ slides decrease, incrementally, in opacity, with each displayed slide.

I.e., 1st slide appears at opacity =1.

Next, at less, then next at less again, each getting dimmer ... until they vanish.

Not clear if this is the _same_ issue, or something else;  appears that 'fade' has a number of challenges!

fyi, @nolimits4web , re: your comment above, this _is_ with crossFade == true

**Comment by coolemur** [comment]
Issue still exists in v4.3.3.

(tricks by ezetojo and hal869 worked for me)

**Comment by stevenMouret** [comment]
Issue still exists in 4.4.5.

**Comment by yordanzhelevdev** [comment]
Add this in settings `fadeEffect: { crossFade: true },`
