### ISSUE TITLE
Can not swipe for initial slide in chrome

### ISSUE THREAD

**Issue by sukhpalsingh** [nolimits4web/Swiper#1099]
I am building something which depends all content of slides on ajax calls.
But as i can understand swiper will work only if there is atleast one or two slides available before initilising.
So, i am adding 2 slides using ajax and initilising after loading ajax slides using jquery append.

My issue is Swiper does not swipe left when the user swipe left on load.

I have function listener for onSlideChangeEnd which will triggered after slide is changed. As i said before, swipe left does not work on load so when the user do first swipe left, onSlideChangeEnd function is getting triggerd and am i loading next slide which will be 3 using appendSlide function. Everything starts working after this happen. But this is a bug that user need to swipe left before this start working.

I could not find any way to make swiper swipe left .

**Comment by nolimits4web** [comment]
Do you have a live link or fiddle so i can take a look?

**Comment by sukhpalsingh** [comment]
I will post you the working example soon.

**Comment by sukhpalsingh** [comment]
Created fiddle for the way i am using. But its working fine in the fiddle.

http://jsfiddle.net/3woLkfe8/

**Comment by nolimits4web** [comment]
So if it working fine in fiddle, then problem seems to on your side. Do you have a link to where i can see the issue, maybe some styles conflict?
