### ISSUE TITLE
Cannot use Vertical Direction

### ISSUE THREAD

**Issue by MrDesjardins** [nolimits4web/Swiper#1100]
The demo with vertical does not work on Chrome 41 for vertical slide. I decided to take a try on my local machine and it does not work either. In fact, on my machine it does horizontal scrolling. The code is exactly the one from the demo. This html inside the body:
```
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        <div class="swiper-slide">Slide 4</div>
        <div class="swiper-slide">Slide 5</div>
        <div class="swiper-slide">Slide 6</div>
        <div class="swiper-slide">Slide 7</div>
        <div class="swiper-slide">Slide 8</div>
        <div class="swiper-slide">Slide 9</div>
        <div class="swiper-slide">Slide 10</div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
</div>
```
and the JavaScript:
```
$(document).ready(function () {
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        direction: 'vertical',
        slidesPerView: 1,
        paginationClickable: true,
        spaceBetween: 30,
        mousewheelControl: true
    });
});
```

**Comment by nolimits4web** [comment]
Are you sure that you use Swiper 3? I have no any problems in chrome with it

**Comment by MrDesjardins** [comment]
I had to use the preview to make it works. With Swiper 2.7.6 it works, with the latest one it does not for me.

**Comment by MrDesjardins** [comment]
Going to : http://www.idangero.us/swiper/demos/03-vertical.html

Does not allow me to do anything. I do not see error in the console. This is strange because all other demos online are functional. I cannot even press the little circle at the right of the screen. Nothing occurs.

**Comment by nolimits4web** [comment]
Don't know where to get Chrome 41, but at current stable Chrome 40 and on Canary 42, it works without any problems. Seems like pure Chrome issue

**Comment by tut4ever** [comment]
I've getting the same problem.
I'm testing with Chrome Version 40.0.2214.115 m (error)
and Firefox Developer Edition version 37.0a2 (2015-02-23) (work)

I've tested with my script and http://www.idangero.us/swiper/demos/03-vertical.html

**Comment by nolimits4web** [comment]
Got many confirms that it was Chrome 40 issue

**Comment by ChanYiSen** [comment]
i have chrome 45,but swiper vertical does not work!

**Comment by theoldcounty** [comment]
This is still an issue.

**Comment by btnwtn** [comment]
Still an issue.
