### ISSUE TITLE
In Swiper 3, is there any alternative for swiper.touches['start'] and swiper.touches['current'];

### ISSUE THREAD

**Issue by faressoft** [nolimits4web/Swiper#1101]
In Swiper 3, is there any alternative for swiper.touches['start'] and swiper.touches['current'] from swiper 2

	onTouchMove: function(swiper) {

		var distance = swiper.touches['start'] - swiper.touches['current'];
		....
	}

**Comment by nolimits4web** [comment]
No, there is no such props anymore, probably need to add them

**Comment by faressoft** [comment]
Ok, Thanks.
