### ISSUE TITLE
Can not use swiper in chrome and IE

### ISSUE THREAD

**Issue by owidat** [nolimits4web/Swiper#1102]
I tried all examples and demos even www.idangero.us/swiper main swiper, navigation UI is showing but the navigation (next/prev) actions on Chrome is not working!!!
In IE: navigation UI is not showing at all, maybe CSS problem, but navigation actions is working fine except 3D effect demos
IE Dev Console error: SCRIPT5007: Unable to get property 'add' of undefined or null reference / File: swiper.min.js, Line: 16, Column: 8230 

other browsers work fine

**Comment by nolimits4web** [comment]
Seems to be it is Chrome issue, i don't see any problems in Chrome, and it actually was developed on Chrome. About IE, 3D effects are not supported, navigation also not visible because IE doesn't support not encoded SVG backgrounds

**Comment by mrijneveld** [comment]
I also have the same problem in ie11 emulation version 9. Did somebody find a fix already?

**Comment by nolimits4web** [comment]
> ie11 emulation version 9

Swiper doesn't support IE 9, no sense to emulate it

**Comment by nolimits4web** [comment]
Fixed in 3.0.5

**Comment by tanu502** [comment]
Code in IE is work

onSlideChangeEnd: function(swiper){
   //
}

Not work

onSlideChangeEnd(swiper){
   //
}
