### ISSUE TITLE
How can I remove a slide in Swiper 3?

### ISSUE THREAD

**Issue by DennisNygren** [nolimits4web/Swiper#1106]
I don't see anywhere in the documentation on how to remove slides with Swiper 3.

With Swiper 2 I used the "removeAllSlides" function.

**Comment by nolimits4web** [comment]
You may remove it using usual DOM manipulation, for example:
---js
var swiper = new Swiper(...);
$('.swiper-slide').eq(1).remove();
swiper.update(); //or swiper.onResize();

**Comment by DennisNygren** [comment]
Thank you that worked!

I would recommend putting that in the documentation since I'm probably not the only one coming from Swiper 2 (and even new users might have a hard time figure out how to do this). Personally I would also prefer being able to use functions like removeSlide/removeAllSlides for this case, especially since there's already equivalent prependSlide/appendSlide (so that feels natural to me).

Another thing coming from Swiper 2 that was confusing to me was the removal of resizeFix() function, until your comment above mentioning onResize() I didn't know what to do exactly on window resize, and just by looking the current documentation you can only assume the following functions should go in the resize window event:
swiper.updateContainerSize();
swiper.updateSlidesSize();
swiper.updateProgress();
swiper.updatePagination();

So I would recommend adding onResize() to the documentation as well.

Thanks for a great plugin and looking forward to follow the development of Swiper 3.
