### ISSUE TITLE
Cannot drag scrollbar thumb

### ISSUE THREAD

**Issue by lesarnott** [nolimits4web/Swiper#1110]
Prior to 3.0 I used to be able to mark a scrollbar as ' draggable' but in 3.0 it appears there is no such parameter and the thumb cannot be dragged.  Is this by design?

**Comment by nolimits4web** [comment]
Yes, currently it is by design, as it mostly mobile slider now where there is no such functionality. I'll think about making scrollbar draggable

**Comment by lesarnott** [comment]
Thanks for the confirmation. I still find it a useful option to reposition quickly to somewhere in a large gallery but I understand your position.

**Comment by glagola** [comment]
Hi, I'm also need this functionality in 3.0.

**Comment by Lucas-C** [comment]
I'd love this too.
And another user wanted the "Ability to drag swiper scrollbar" in #1405.
In the meantime, if I find a quick hack around this I'll post it here.

**Comment by Lucas-C** [comment]
As promised, here is the code snippet that did the trick for me:
````
var raf = window.requestAnimationFrame || window.setImmediate || function(c) { return setTimeout(c, 0); };

var getUniqueElementByClassName = function (className) {
    var elems = document.getElementsByClassName(className);
    if (!elems.length) {
        throw new Error('no .' + className + ' element found');
    } else if (elems.length > 1) {
        throw new Error('Several .' + className + ' elements found');
    }
    return elems[0];
};

var setScrollbarDraggingCallback = function (swiper) {
    var scrollbar = getUniqueElementByClassName ('swiper-scrollbar-drag'),
        scrollbarLength = getUniqueElementByClassName ('swiper-scrollbar').offsetWidth,
        swiperLength = _.sum(_.map(getUniqueElementByClassName ('swiper-wrapper').children, 'offsetWidth')),
        scrollRatio = swiperLength / scrollbarLength,
        lastPageX;
    var drag = function(event) {
        var delta = lastPageX - event.pageX;
        lastPageX = event.pageX;
        raf(function() {
            var translate = swiper.getWrapperTranslate() + delta * scrollRatio;
            swiper.setWrapperTransition(0);
            swiper.setWrapperTranslate(translate);
            swiper.updateProgress();
            swiper.updateActiveIndex();
        });
    };
    var stop = function() {
        document.removeEventListener('mousemove', drag);
        document.removeEventListener('mouseup', stop);
        swiper.slideReset();
    };
    var start = function(event) {
        lastPageX = event.pageX;
        document.addEventListener('mousemove', drag);
        document.addEventListener('mouseup', stop);
    };
    scrollbar.removeEventListener('mousedown', start);
    scrollbar.addEventListener('mousedown', start);
};
```

**Comment by iwazaru** [comment]
@Lucas-C : Draggable scrollbars have been implemented in version 3.1.5 although it's not documented yet. From the changelog:
* Ability to make the Scrollbar draggable using new paramaters:
    * `scrollbarDraggable` - (boolean) by default is `false`. Allows to enable draggable scrollbar
    * `scrollbarSnapOnRelease` - (boolean) by default is `false`. Control slider snap on scrollbar release

**Comment by Lucas-C** [comment]
Damn, a few hours spend on this for nothing :P
But thanks, that's great news !
Good job.

**Comment by nolimits4web** [comment]
Yeah, sorry guys, documentation will be update this weekend

**Comment by nguyendq** [comment]
Can we have function when scrollbar drag?
