### ISSUE TITLE
[Question] about Caption 

### ISSUE THREAD

**Issue by lenamtl** [nolimits4web/Swiper#1111]
Hi,

I'm new to Swiper
I'm wondering which scripts are you using for caption and caption animation with Swiper?

Thanks

**Comment by nolimits4web** [comment]
Where do you see captions? I don't know what to answer, but Swiper slide could contain any HTML, so you can just add them inside of slide as text with required CSS styles

**Comment by lenamtl** [comment]
I know there is no caption that why I'm asking ;)
Any recommendation like a script ready to use that play well with Swiper.

**Comment by nolimits4web** [comment]
Not sure that there will be ready captions script for Swiper, you need to do it by yourself, for example using Swiper callbacks to show/hide something inside of active slide

**Comment by lenamtl** [comment]
ok I see, I will continue my tests 
Thanks
