### ISSUE TITLE
Event values are undefined in the default browser on Android 4.4.4

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/Swiper#1112]
In the mentioned browser when I use for example the `onTouchMove(swiper, event)` function many values of the event object is undefined. Such as `event.movementX`, `event.webkitMovementX`, event.x and so on.
What cause this bug?

**Comment by nolimits4web** [comment]
Are you sure that these properties exist in `touchmove` event? Anyway, Swiper doesn't modify event, it just passes it through, so doesn't related to Swiper. As i see these props are parts of "Pointer Lock API" which is related to mouse events

**Comment by kireerik** [comment]
Thank you for your fast reply! Yes, you are right. The `onTouchMove` function name confused me a little bit. It even triggers when you move your mouse (and not holding it down) in a desktop browser. So sorry for reporting this as an issue.

**Comment by nolimits4web** [comment]
Yes, because it works like usual mousemove event on desktop. If you need callback when you only hold slider, then you may use onSliderMove callback
