### ISSUE TITLE
resistance: false seems doesn't work !

### ISSUE THREAD

**Issue by faressoft** [nolimits4web/Swiper#1113]
resistance: false seems doesn't work !

**Comment by nolimits4web** [comment]
Do you have a link a fiddle with this issue?

**Comment by faressoft** [comment]
https://jsfiddle.net/faressoft/yLynbb04/

**Comment by nolimits4web** [comment]
I see that everything is correct, there is no now any resistance and you can freely drag swiper. So what is wrong with it?

**Comment by nolimits4web** [comment]
Or what did you expect from it?

**Comment by faressoft** [comment]
I see that there is no difference if the value true or false.
I want something equivalence to the resistance: '100%' that was in Swiper 2.

**Comment by nolimits4web** [comment]
There is actually big difference)) You are probably looking for `resistanceRatio:0` option

**Comment by faressoft** [comment]
That's it :) thank you very much for your help.
