### ISSUE TITLE
Slide change in slide-nav div in movie app?

### ISSUE THREAD

**Issue by marco78** [nolimits4web/Swiper#1114]
Hallo! I'm using movie-app that is exactly what I need for my website. But if I use autoplay I see that slides change just in main container (swiper-content), while in swiper-nav nothing happens... is it possible to use autoplay in both containers so that ithey change at the same time?

**Comment by nolimits4web** [comment]
Swiper 2.x is not supported anymore, but it is possible by using callbacks on auto played slider to and call swipeNext on other one in the beginning of transition

**Comment by marco78** [comment]
Thanks for your answer but I don't know how to do it...
I have:
  var mySwiper = new Swiper('.swiper-container',{
	autoplay: 4000,
	loop: true,
  })

Now I have to add callbacks but I don't know how.
I think I should use onTransitionStart and swipeNext, but I cannot find instructions for unsing them :(

**Comment by nolimits4web** [comment]
Here is documentation for Swiper 2.x https://github.com/nolimits4web/Swiper/blob/Swiper2/API.md

**Comment by marco78** [comment]
Really thank you. I tried to use these lines of code but I don't know how to combine them for my needs. Now I can insert an alert onSlideChange, like the examples in documentation (and it works fine!), but nothing else...

var mySwiper = new Swiper('.swiper-container',{
	autoplay: 4000,
	loop: true,
	onSlideChangeStart: function(){
        ...
	}
})

I don't know how to build a function that has effect on swiper-nav div

**Comment by nolimits4web** [comment]
I don't remember what is there, but you should call swipeTo on another swiper:
```
var mySwiper = new Swiper('.swiper-container',{
autoplay: 4000,
loop: true,
onSlideChangeStart: function(swiper){
  anotherSwiper.swipeTo(swiper.activeIndex)
}
})

**Comment by nolimits4web** [comment]
Closing as seems to be not actual anymore. Reopen it if it is still actual
