### ISSUE TITLE
New Site Has No Documentation on Hash Navigation

### ISSUE THREAD

**Issue by ethanpil** [nolimits4web/Swiper#1119]
There is no information on using the hashnav feature on the API or Get Started pages. Only the API option to enable it....

**Comment by ethanpil** [comment]
I couldnt get it working at all. Here is what i ended up doing with jQuery in case you want to implement something similar to intercept the links


        $('.slide-menu a').click(function(e) { 
            e.preventDefault();
            var hash = $(this).attr('href').replace('#', '');
            for (var i = 0, length = app.swiper.slides.length; i < length; i++) {
                var slide = app.swiper.slides.eq(i);
                var slideHash = slide.attr('id');
               // console.log('Comparing hash: "'+hash+'" to slide.id: "'+slideHash+'" on index: "'+i+'"');
                if (slideHash === hash) {
                    app.swiper.slideTo(i, 300, true);
                  //  console.log('found at index: '+i);
                    break;
                }
            }            
        });

**Comment by nolimits4web** [comment]
I will add some guide, but mostly it enough to look at appropriate demo with hashnav where it works without any problems

**Comment by nolimits4web** [comment]
Closing, as information added
