### ISSUE TITLE
Mousewheel problem

### ISSUE THREAD

**Issue by strigga** [nolimits4web/Swiper#1122]
if i set mousewheelControl:true in my vertical slider, no matter in which direction i scroll, the slider only slides up

**Comment by nolimits4web** [comment]
Do you have the same issue in mousewheel demo? What device/os/browser

**Comment by strigga** [comment]
no, so i don't know where's the mistake

**Comment by nolimits4web** [comment]
Then provide a fiddle with not working example or live link. For now i am closing it

**Comment by strigga** [comment]
www.strigga-design.at/test1/

**Comment by strigga** [comment]
test

**Comment by pandada8** [comment]
have same problem when using swiper.jquery.js with angular
use swiper.js rather than swiper.jquery.js solved my problem
http://jsfiddle.net/mh6wp0oh/

**Comment by nolimits4web** [comment]
Ok, the problem in `swiper.jquery`, will take a look. While you may use standalone version

**Comment by nolimits4web** [comment]
Fixed now in dev version
