### ISSUE TITLE
Support for older Versions of Internet Explorer

### ISSUE THREAD

**Issue by ama-gi** [nolimits4web/Swiper#1124]
Internet Explorer 8: "Object doesn't support this property or method"

I get this error in line 15, char 5538 in swiper.jquery.min.js in version 3.0.2.

Please consider providing basic support in 3.0.2 for older versions of Internet Explorer.

**Comment by nolimits4web** [comment]
Sorry, currently no old ie support in plans. Use swiper 2.x
