### ISSUE TITLE
No smooth transitions

### ISSUE THREAD

**Issue by Moussawi7** [nolimits4web/Swiper#1127]
Hi,
I am creating a mobile app that use this slider.
The slider working excellent, but when i inserted HTML content inside the slides, I lost the smooth transitions.
Note that the number of slides is 20.
Thanks.

**Comment by nolimits4web** [comment]
Use lazy technic and try to hide content that is not in active/next/prev slieds

**Comment by nolimits4web** [comment]
Closing as required lazy technic, also images lazy loading already in 3.0.4

**Comment by Moussawi7** [comment]
unfortunately, i used lazy technique with negative result.
Thank you anyway.
