### ISSUE TITLE
Pagination accessibility

### ISSUE THREAD

**Issue by VaclovasV** [nolimits4web/Swiper#1134]
Hello,
It would be nice to be able to change pagination elements. Default spans should be changed to button or link elements.
Good example is slick.js pagination:
```
<ul class="slick-dots" style="display: block;"><li class="slick-active"><button type="button" data-role="none">1</button></li><li><button type="button" data-role="none">2</button></li><li><button type="button" data-role="none">3</button></li><li><button type="button" data-role="none">4</button></li><li><button type="button" data-role="none">5</button></li><li><button type="button" data-role="none">6</button></li></ul>
```
Best solution would be to customize pagination control element.
Thank you!

**Comment by nolimits4web** [comment]
You can always easily create custom pagination, but will consider about configuring its layout
