### ISSUE TITLE
Slide offset on Init

### ISSUE THREAD

**Issue by leifniem** [nolimits4web/Swiper#1136]
I ran into an issue where the Slides offset on initialization, if the viewport has not reached its max-width. When using the arrow or touch the slide corrects first, then the action runs on second click / tap.

I've checked that all contents use `content-box` sizing and removed all paddings in the slides themself, yet i run into this issue.

![swiper](https://cloud.githubusercontent.com/assets/5417518/6487673/d8f9162c-c292-11e4-82d9-dc35164c9c54.jpg)

**Comment by nolimits4web** [comment]
Not really understand what happens, seems like you init Swiper when it is invisible? Do you have a link so i can take a look?

**Comment by leifniem** [comment]
No, the DOM loads, swiper after it and when it's initialized the slides have an offset before interaction.
This only appears at a windows size < 1200px, but i couldn't figure out why.

iseedead.pf-control.de/markus is the link. I apologize if it turns out to be an issue of unattentive coding.

**Comment by nolimits4web** [comment]
In what browser? I see that everything is fine

**Comment by nolimits4web** [comment]
Or do you mean that it starts from different initiaSlide?

**Comment by leifniem** [comment]
Chrome OS X. The Random InitialSlide is on purpose.
I'm really sorry for bothering you.

**Comment by nolimits4web** [comment]
It is ok, but i just don't see the issue in same Chrome OS X, do you still have it?

**Comment by leifniem** [comment]
yes. still occurring on chrome, firefox and safari.
Reloading with cmd+shift+r helps me recreate it every time.

**Comment by nolimits4web** [comment]
Maybe some screen capture video, maybe i just don't understand what do you mean?

**Comment by leifniem** [comment]
On reload you see the dom loading and when the script inits creating an offset here:

https://www.dropbox.com/s/895r2cz1uu51e4d/wiggle.mp4?dl=0

**Comment by nolimits4web** [comment]
You can kill me, but i can see such :)

**Comment by nolimits4web** [comment]
Try on another machine/device, maybe some local related issue

**Comment by Rikk** [comment]
I see it happen on FF, only when doing full reload (ctrl+f5 or cmd+shift+r) and when window height can show the swiper area entirely. Maybe it's something on the site interacting with window resizing? Or modernizr? Dunno.

**Comment by leifniem** [comment]
Windows 8 Chrome. Will check for conflict with modernizr soon.

![screenshot 1](https://cloud.githubusercontent.com/assets/5417518/6504095/ab989e18-c333-11e4-90bb-ba669ae9893f.png)

**Comment by leifniem** [comment]
Narrowed the problem down a bit.
Slide width is calculated correctly, but the offset is 1,01164725457571 times the size it should be (For example: Slide 6 Width 1202px offset -7296px).

**Comment by nolimits4web** [comment]
Still good to me. You can try the following setup:
```
slidesPerView: 'auto'
```
And in CSS:
```
.swiper-slide {
  width:100%;
  height:100%;
}

**Comment by nolimits4web** [comment]
And one thing i notice, move swiper initialization script in the end of the body, not to good to have it somewhere in the middle

**Comment by leifniem** [comment]
It was the script placement in the middle of the page. I'm sorry.

Huge thank you!

**Comment by Rikk** [comment]
Looks broken right now... Place `<script>` tags as the last thing inside `<body>`

**Comment by leifniem** [comment]
It's because i'm conditionally loading the script on front page but the conditional won't work right now. Everythings fine :)
