### ISSUE TITLE
Phonegap problem, only the first image is added. But no problem on browsers. 

### ISSUE THREAD

**Issue by clarklight** [nolimits4web/Swiper#1139]
First thankyou for the great plugin, i have it working great with static images. Only problem i have is when i call the images in from a Ajax request. 

I am having 2 problems 1 with the scrolling. If i set loop:true; it doesnt click properly, But i dont need it to loop so i set it to false, and that works ok on all browsers for me. 

The main problem is when i package it into phonegap and load images from AJax request. 
The swiper is initialized and you can see the image is scrolling, but only the first images is added. So even though there should be multiple images only the first one is added and have the scrolling behavior. 
But i am having no issue at all on browsers on any mobile devices or desktop. 

But 1 thing is that i needed to call  mySwiper.onResize(); for scrolling to work on all browsers as well, so i am not sure if the onResize() isnt called on Phonegap, or the rest of the swiper-slide isnt added.

**Comment by nolimits4web** [comment]
If you do everything correct you don't need to call `mySwiper.onResize()`, it is better to call `.update(true)`

Check your PhoneGap app console, maybe error somewhere there

**Comment by clarklight** [comment]
Yer i think there is something not right that i am doing, because when i do .update(true) it won't scroll past the first image on any browser either. I will scroll the first image and can see the second image, but it wont scroll to it and bounce back.

**Comment by nolimits4web** [comment]
You need to show live example, also make sure that you use latest Swiper version

**Comment by clarklight** [comment]
Sorry my bad, i was referencing to the old version still.
