### ISSUE TITLE
iOS Safari - Swipe causes browser forward and backward instead of swipe event.

### ISSUE THREAD

**Issue by tmikaeld** [nolimits4web/Swiper#1140]
In iOS 7+, Safari causes a swipe on the slider to go forward or backwards in the browser instead of sliding the slider.

Maybe there is no way to prevent this?
I don't see any events or bubbling for this in the DOM.

**Comment by nolimits4web** [comment]
Do that you mean when you swiping from edge of the screen, Safar change pages instead of swiper sliding?

**Comment by tmikaeld** [comment]
Swiping exactly on the slider.

Most times sliding from the first slide to the next (right) works, but sliding back to the previous doesn't work 9 out of 10 times, even when holding the finger slowly over the device. (Tested with iPhone 4S on iOS 8.1.3 and iPhone 5s on emulator iOS 8.1)

**Comment by tmikaeld** [comment]
Found a reference to the issue:
https://stackoverflow.com/questions/16567188/is-there-a-way-to-control-safari-mouse-swipe-gestures

**Comment by nolimits4web** [comment]
Sorry, it is Safari behavior, if you swipe from edge of the screen it will cause browser back/forward. Nothing can do with it

**Comment by tmikaeld** [comment]
Ok, thanks for confirming it's an OS issue.
