### ISSUE TITLE
Swiper swipe keeps between slides

### ISSUE THREAD

**Issue by linoleum89** [nolimits4web/Swiper#1141]
There's is a bug, in some scenarios the swipe keeps between one slide and another, any idea? tested on iOS 7,8 and WP 8.1, thanks.

![img_2253](https://cloud.githubusercontent.com/assets/2753274/6513495/a4e1c086-c338-11e4-9b93-3f7a9b7d3445.PNG)

**Comment by nolimits4web** [comment]
Link?

**Comment by linoleum89** [comment]
There's no link it's a cordova app, this are the options i'm using on the plugin: 
pagination: '.swiper-pagination',
loop: true,
spaceBetween: 30

**Comment by nolimits4web** [comment]
Maybe you can replicate it in JSFiddle? Because i can't tell like that

**Comment by linoleum89** [comment]
Let me prepare an JSFiddle in the week, maybe is an issue with Intel App Framework.

**Comment by nolimits4web** [comment]
Yep, JSFiddle will be really helpful with that

**Comment by nolimits4web** [comment]
Closing as no further discussion. Reopen if issue or problem is still there
