### ISSUE TITLE
Will plugin be supported again?

### ISSUE THREAD

**Issue by francoismassart** [nolimits4web/Swiper#1142]
Hello,
I'm using the latest 2.x version of the Swiper and while testing out the version 3.0.3, I saw that the support for plugins was gone.

I made several plugin: filtering, lazyload, responsive configuration...

My plugin were usefull and easy to reuse. Do you plan to bring back the support for plugins ?
Thank you for your answer.

PS: any roadmap available for next releases?

**Comment by nolimits4web** [comment]
Didn't know that someone used it at all :) Yes, will back but in next release or release after

**Comment by francoismassart** [comment]
Great news :)
Yes, I did use the plugin and I could share them too once they are ready for v 3.
Plugin was a real nice feature for us!

Thank you.

**Comment by francoismassart** [comment]
@nolimits4web, I'm testing one of my plugin and I noticed that it was depending on jQuery.
What should I do inside my plugin source code in order to be able to use the helper functions that are defined inside `dom.js` ?
I'm trying to make 2 versions, a version free of dependency to jQuery and another version depending on jQuery...

But right now, inside my plugin code `$` is undefined...

```javascript
Swiper.prototype.plugins.myTestPlugin = function(swiper, params) {
    // $ is undefined unless if I add jQuery to the html page
};
```

Thank you for your help

**Comment by nolimits4web** [comment]
You may do it like in Swiper's core:
```
var $;
if (typeof Dom7 === 'undefined') {
    $ = window.Dom7 || window.Zepto || window.jQuery;
}
else {
    $ = Dom7;
}

**Comment by francoismassart** [comment]
I did try to do it this way after comparing both swiper.js and swiper.jquery.js in the gulpfile but $ remains undefined.
I'll prepare an example on jsfiddle or similar to ease the process here...

I started my test from the lazy loading demo page...

Thank you for the fast replies ;-)

**Comment by francoismassart** [comment]
Here is a demo of $ which is undefined even using your snippet to use Swiper's core:
http://jsfiddle.net/xu4y2sc9/7/

@nolimits4web 
Do you see what is wrong?
Thanks

**Comment by nolimits4web** [comment]
Yeah, in latest dev version, it is just accessible via Swiper instance like `swiper.$`
