### ISSUE TITLE
Two paginations?

### ISSUE THREAD

**Issue by Rikk** [nolimits4web/Swiper#1144]
How to have two paginations (one above and other below swiper)?

**Comment by nolimits4web** [comment]
Not sure that it is posssible, but did you try to just add two ".swiper-pagination" containers?

**Comment by Rikk** [comment]
Yes, but only one works, the other doesn't even appear I think; same when using jquery clone(true), but the second doesn't update and looks frozen.

**Comment by nolimits4web** [comment]
I see, will try to bring it in next update

**Comment by Rikk** [comment]
Thanks!

**Comment by Rikk** [comment]
Great! Will test when it is released...
