### ISSUE TITLE
A problem with onSlideChangeEnd

### ISSUE THREAD

**Issue by faressoft** [nolimits4web/Swiper#1145]
If the user swipe the slide and touch the slide during the transition the onSlideChangeEnd callback function never called.

I upload this private video, It explains the problem
http://youtu.be/XuJyvSUcA08

Code:
http://fiddle.jshell.net/faressoft/7rLn3xm7/

**Comment by nolimits4web** [comment]
It is easy to explain. When you do one more touchmove during slide transition to next slide, then it will get this touchmove for the new start move, and you leave it at current slide, then event will not be triggered. You may use onTransitionStart/End in this case

**Comment by faressoft** [comment]
That works fine :) Thank you.
