### ISSUE TITLE
2.x.x API Docs

### ISSUE THREAD

**Issue by pr1ntr** [nolimits4web/Swiper#1148]
Hi,
I am still using the 2.x version of swiper. Is there a copy of the old api docs somewhere?

**Comment by Rikk** [comment]
It is the last topic of main Readme at https://github.com/nolimits4web/Swiper
https://github.com/nolimits4web/Swiper/blob/Swiper2/API.md

**Comment by pr1ntr** [comment]
o weird, how did I miss that. thanks.
