### ISSUE TITLE
No new constructor call

### ISSUE THREAD

**Issue by dfcreative** [nolimits4web/Swiper#1149]
Just faced with a situation when I tried to init Swiper calling a constructor with no `new` expression, like so:
```js
var s = Swiper(selector, options);
```
instead of 
```js
var s = new Swiper(selector, options);
```

Supporting both cases became a somewhat common practice within components, for example, component-tip has [a line handling such initialization cases](https://github.com/component/tip/blob/master/index.js#L57).

Usually, it looks similar to:
```js
if (!(this instanceof Swiper)) return new Swiper(el, options);
```

Is there a sense to add a such detection, or you better prefer keeping more strict version of initialization call?

**Comment by nolimits4web** [comment]
I prefer to keep it strict and syntax-correct, but such addition will be useful, will add such line
