### ISSUE TITLE
Trigger events on instances, inherit swiper from Emitter

### ISSUE THREAD

**Issue by dfcreative** [nolimits4web/Swiper#1151]
Just an idea.
It might be quite useful having Swiper inherit [Emitter](https://www.npmjs.com/package/events), in order to get able to bind events to Swiper instances at any time you like. For now it is able to pass callbacks to swiper options, which is great and makes things done perfectly, but for more convenience and conformity it might be a nice improvement.

Examplary code:
```js
var s = new Swiper(element, options);
s.once('slideChangeStart', function () {
    //load new slides once first slide has started changnig
    this.appendSlide(newSlide);
});
```

That way you could separate events from options in API, which seems to be a nice improvement also.

**Comment by nolimits4web** [comment]
Sounds good, but i though about adding usual DOM events, so you can use it like `$('.swiper-container').on('slideChangeStart', function(){...})` Will think about it
