### ISSUE TITLE
Blurred screen on slide change

### ISSUE THREAD

**Issue by wyzwhp** [nolimits4web/Swiper#1153]
When slide change in mobile broswer ,slide view blurred screen,how to fixed this bug?

**Comment by nolimits4web** [comment]
Try to increase z-index on .swiper-container. Also you may try to add in css:
```
.swiper-container {
  -webkit-transform: translate3d(0,0,0);
}

**Comment by wyzwhp** [comment]
This demo is my page, http://sandbox.runjs.cn/show/p00439dk.The bug not fixed

**Comment by wyzwhp** [comment]
Thanks!

**Comment by vennamo** [comment]
I have similar issue on desktop chrome and safari. Slide content is blurry. 
The end transition is something like 132.6666666666667px. Maybe after the transition the value should be full pixels?

**Comment by vennamo** [comment]
added Math.ceil to translate3d values did work for me.
