### ISSUE TITLE
remove slides from dom to save memory

### ISSUE THREAD

**Issue by ndamofli** [nolimits4web/Swiper#1154]
I am using swiper v.3 with a really big slider (100 + slides/images). I am wondering if there is a way to remove unused slides / images from the dom to save memory (say keeping only 10 of them loaded at a time) 
Thank you

**Comment by nolimits4web** [comment]
Only some custom solution based on heavy usage of callbacks where you may remove and add slides depending on activeIndex. But i have in plans to realize something like Virtual Slides, that will keep in dom only required amount of slides

**Comment by nolimits4web** [comment]
You can also try to hide content/images in not-active/visible slides and use lazy loader on images

**Comment by Nytrm** [comment]
Any progress regarding this issue ?

**Comment by mikebonds** [comment]
As far as I can tell this will still require a custom solution. I have been working on something and if I manage to get it working I will post it up.

**Comment by Nytrm** [comment]
@mikebonds cool, let us know when you have something working :-)

**Comment by jlcarvalho** [comment]
I am also working on a solution using the callbacks.

**Comment by 3zzy** [comment]
+1 *Really* important for smooth performance on mobile devices.

**Comment by 3zzy** [comment]
A dirty solution:

```
<div class="swiper-slide"><img data-src="001.jpg"></div>
<div class="swiper-slide"><img data-src="002.jpg"></div>
<div class="swiper-slide"><img data-src="003.jpg"></div>
```

JS

```
var mySwiper = new Swiper('.swiper-container', {
    speed: 200,
    onInit: function (mySwiper) {
    	var activeIndex = mySwiper.activeIndex;
    	var activeSlide = $('.swiper-slide img')[activeIndex];
    	activeSlide.src = activeSlide.getAttribute('data-src');
    },
    onSlideChangeStart: function (mySwiper) {
    	var activeIndex = mySwiper.activeIndex;
    	var activeSlide = $('.swiper-slide img')[activeIndex];
    	activeSlide.src = activeSlide.getAttribute('data-src');
    }
});
```

I still see some lag while changing the slides. can anyone suggest improvements for better performance?

**Comment by 3zzy** [comment]
Lazy Loading doesn't seem to preload a few prev/next images like it should:

**Comment by 3zzy** [comment]
Also, once the data-src has been replaced with img, I wonder if I browse 300 images, that many will be loaded in memory?

**Comment by 3zzy** [comment]
Any progress on this? Swiper has everything I need, but its just slow compared to PhotoSwipe.

**Comment by grundmanise** [comment]
Virtual Slides would make this plugin the No. 1 choice. Lack of  the "virtual slides" it is the only thing that stops me from using this plugin.

**Comment by 3zzy** [comment]
No plans to implement this at all?

**Comment by T1mobil3** [comment]
Looks like this will be included in version 4: https://github.com/nolimits4web/Swiper/blob/master/CHANGELOG.md

**Comment by nolimits4web** [comment]
It is already in v4

**Comment by Satish-Sarakanam-Tcs** [comment]
@nolimits4web, Is there any api or  workaround  to remove a slide from the virtual slides. The general mySwiper.removeSlide() doesn't seem to work. 
Thanks in advance.
-Satish
