### ISSUE TITLE
IE11 fade effect glitch

### ISSUE THREAD

**Issue by SantzDesign** [nolimits4web/Swiper#1155]
I tested the fade effect on IE 11 running Windows 8.1 and it doesn't work as it should.

When the transition/animation is supposed to start, it's like it attempts to pull off the default swipe effect, but it then "corrects" itself and ends up doing the fade. It's messed up, I couldn't figure out a way to solve the bug. Will give it some more time tomorrow if no one solves this before.

**Comment by nolimits4web** [comment]
That should be fixed in dev version now, which using now so called "virtualTranslate"

**Comment by SantzDesign** [comment]
Great Vladimir. Will continue to debug, and let you know if anything shows up. I'm using this on a project and it's working great. Kind regards.
