### ISSUE TITLE
Auto SlidesPerView and Loop Conflict

### ISSUE THREAD

**Issue by lukeed** [nolimits4web/Swiper#1157]
Demo 8 (centered-auto) will throw an uncaught TypeError once `loop` is set to true

Uncaught TypeError: Cannot read property 'classList' of undefined on line 2679

**Comment by nolimits4web** [comment]
Did you read on API then you need to use loopedSlides parameter in this case?)

**Comment by lukeed** [comment]
Oh, no sir I did not. Thanks!

Perhaps make a note (similar to that of loopedSlides) in the slidesPerView description? Would make it more visible.
