### ISSUE TITLE
[Docs] slideTo is actually swipeTo

### ISSUE THREAD

**Issue by tonytamps** [nolimits4web/Swiper#1158]
In the swiper API docs (http://www.idangero.us/swiper/api/) under the 'Methods' heading there is documentation for `mySwiper.slideTo(index, speed, runCallbacks);`

I believe this should actually be `mySwiper.swipeTo`.

![image](https://cloud.githubusercontent.com/assets/2356776/6632044/19c4cd84-c984-11e4-9a88-ad9816908227.png)

I would make the update myself but your docs don't seem to be on GitHub.

**Comment by nolimits4web** [comment]
Docs are for Swiper 3, you are using Swiper 2.x

**Comment by tonytamps** [comment]
There doesn't seem to be a way to get to the API docs for Swiper@2.x
Have you got a link to them @nolimits4web ?

**Comment by nolimits4web** [comment]
Right on repo's home page https://github.com/nolimits4web/Swiper#swiper-2xx

**Comment by tonytamps** [comment]
Ah thanks, I was looking for it on http://www.idangero.us/swiper/api/
