### ISSUE TITLE
PhoneGap/Cordova rendering issue on iOS8 with slidePerView = 1 

### ISSUE THREAD

**Issue by chrismbeckett** [nolimits4web/Swiper#1159]
This is a weird problem, and difficult to debug. Pick any of the simple demos from the SwiperJS site but set slidesPerView =1. On iOS8, the screen will continuously flash and show the content flickering between the pane content unwrapped, and then wrapped to fit the container. It appears like a circular event related to setting the slide elements height or width.

I have tested this using the PhoneGap Developer app, and an iPod Touch Gen 5, and an iPad Gen 4 both running iOS 8.x. The same site is rendering correctly in the Safari Browser on the same devices, in desktop browsers including Firefox, Chrome and IE, and both Android and WinPhone 8.1 in Cordova. Seems to be specifically related to the PhoneGap/Cordova webview for iOS8.

**Comment by nolimits4web** [comment]
It is some issue with your layout, probably somewhere not fixed sizes at all. For example, go to http://www.idangero.us/framework7/kitchen-sink/ and then pick the Swiper Slider section, there will be a lot of swipers there and none of them will have this "flashing" in iOS8 webview, so just check-up your/those styles

**Comment by chrismbeckett** [comment]
I would expect if I had a flaw in my layout like you suggest, that it would demonstrate as a problem when rendering on other browsers and devices. I have tested it on a number of physical devices in Cordova, mobile browsers, and desktop browsers and it is only a problem on iOS8. Based on you suggest, I spent (a lot) more time looking and experimenting with my layout, and all slide elements inside the swiper-wrapper are using fixed widths.

If I could re-produce this problem in a normal browser, I would put together a JSFiddle to demonstrate the problem, but it only occurs inside PhoneGap. It's possible that Flexbox characteristics on the containers may somehow be contributing to this problem. I will continue to experiment.

**Comment by t2thec** [comment]
Hey @chrismbeckett, did you ever find a solution to this? I'm having the same issue in iOS10. Scrolling two Iframes (pre-loaded) might well be the issue. Fixed sized slides. When scrolling, the new slide isn't doesn't fully show in some cases. 

I'm thinking there is too much to animate - thought it might be worth checking in Justin case you found something. 

Cheers.
