### ISSUE TITLE
Parallax with Background for Each Slide

### ISSUE THREAD

**Issue by Mantrama** [nolimits4web/Swiper#1161]
Hi There,
I'm using parallax and have different bg for each slide.
also I have some other elements like text, subtitle,... which use different parallax value.
I'm considering to have different kind of easing for each elements, for example I want my h1 comes with ease-out with some delay, then my subtitle come with easeInElastic with different delay.
Anybody can guide me?
thanks so much.
Cyrus

**Comment by nolimits4web** [comment]
you can set up different easing using `transition-timing-function` CSS property on these elements  https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function

for delay you may use `transition-delay` CSS property

**Comment by Mantrama** [comment]
Thanks, but is there any way to use 'http://easings.net/' value for timing?
also, can I add `transition-delay` for items in parallax like subtitle, text,... separately?

**Comment by nolimits4web** [comment]
transition-timing-function supports for cubic-bezier function, with this you may achieve any kind of easing. Google will help you to find correct functions for you easings.

Yes, you can add transition-delay for separate elements in css, just use a different classname:
```
.text {
  transition-delay:100ms;
}
.subtitle {
  transition-delay:200ms;
}
//etc
