### ISSUE TITLE
a href inside swiper does not work in Galaxy S3

### ISSUE THREAD

**Issue by lennu** [nolimits4web/Swiper#1162]
I have link element on my swiper slides and they seem to work on every other platform except on Samsung Galaxy S3 normal browser. As this is quite used phone, I think it deserves an issue.

I have free-mode on.

Only the first two slides work properly and when you start to swipe, you can't open the rest of the slides links, you can only swipe them.

**Comment by nolimits4web** [comment]
Can you try it with dev version from this repo?

**Comment by lennu** [comment]
I tried the latest version and now it seems to break completely the slides width/height on Galaxy S3. The slide images are huge like 10x the viewport on some swipers, and there seems to be only 3 slides available even though there should be more. More slides a swiper has, more bigger the images are.

So the changes you have made in the dev version definately had some connection to Galaxy S3, but doesn't seem to fix the problem.

Other devices afaik still seem to be working very well.

**Comment by nolimits4web** [comment]
Sorry, but i haven't Galaxy S3 and don't know how to test and fix it. I'll check, if issue is not reproduces on any pure Android devices, so nothing can do with it. What is Android version by the way?

**Comment by lennu** [comment]
Android 4.3 and default browser. If I use Chrome it work very well.

Well, I figure out some way to avoid this, maybe some future update will fix the problem. Thanks.

**Comment by lennu** [comment]
I think I found the root cause for this behaviour.

The swiper-wrapper is not the size of the div where the slides are inserted, or the swiper-wrapper area is not moving with the swiper.

This causes weird behaviour on some browsers that can be noticed for by applying links to the slides which are not in swiper-wrapper area.

As you can see in the image below the swiper-wrapper in only the size of the first three items, and it doesn't move with the slider. And as the width is somehow counted from the left, some browsers only manage to handle the links on that area. Especially Android 4.3 native browser.

![swiper-wrapper](https://cloud.githubusercontent.com/assets/1713194/6683759/d439f002-cc92-11e4-96a2-7936cdd30648.jpg)

**Comment by nolimits4web** [comment]
Ok, the fix actually was pretty easy, already fixed in dev
