### ISSUE TITLE
No Carousel Until Browser Is Resized

### ISSUE THREAD

**Issue by Kyran1** [nolimits4web/Swiper#1163]
Hi there,

I am currently using swiper on an app and at the moment the carousel is not showing until I resize the browser - in which it then works perfectly.

I have tried a number of different workarounds but to no succession.

My example code is below:

```html
<div class="myAppPage" style="display:none">
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
    </div>
</div>
</div>
```
```javascript
jQuery(document).ready(function ($) {
    mySwiper = new Swiper('.swiper-container', {
         direction: 'horizontal',
         loop: true,
         pagination: '.swiper-pagination',
         paginationClickable: true,
         paginationBulletRender: function (index, className) {
             return '<span class="' + className + '">' + (index + 1) + '</span>';
         },
         bulletActiveClass: 'active'
 });
```

I would really appreciate any help with this.

**Comment by nolimits4web** [comment]
It is because you initialize it when it is invisible (in hidden container). Call .update() method when you make it visible

**Comment by Kyran1** [comment]
Thank you very much for your reply - I really appreciate your help with this issue!

I have created a function that is:

```javascript
showSwiper = function(){
     mySwiper.update();
};
```
But for some reason it isn't working - im getting back:

> Uncaught TypeError: undefined is not a function

**Comment by nolimits4web** [comment]
That is because it is undefined, call it in the same JS scope/function where you initialized it

**Comment by Kyran1** [comment]
Many apologies - I don't quite understand. 

This is my script - Am I doing something obviously wrong here?

```javascript
jQuery(document).ready(function ($) {
            //initialize swiper when document ready  
            mySwiper = new Swiper('.swiper-container', {
                direction: 'horizontal',
                loop: true,
                pagination: '.swiper-pagination',
                paginationClickable: true,
                paginationBulletRender: function (index, className) {
                    return '<span class="' + className + '">' + (index + 1) + '</span>';
                },
                bulletActiveClass: 'active'
            });
            
            showSwiper = function(){
                mySwiper.update();
            };
```

Also I forgot to mention in my original post that on my pagination items I am unable to get an active state for each active item. 

I really do appreciate your help with this!

**Comment by nolimits4web** [comment]
That looks correct. Make sure that you use latest Swiper version, and try to do console.log of variables. And will be better if you provide a link or fiddle with such issue

**Comment by Kyran1** [comment]
Sure no problem - give me a couple of minutes and Ill have a jsfiddle put together

**Comment by Kyran1** [comment]
Hey Again,

As requested an jsfiddle:

https://jsfiddle.net/Kyran1/sb6zu79y/

For some reason it seems to be working in here but not in my files. I just get back the error for undefined...

**Comment by Kyran1** [comment]
Okay I think I have just found why it was coming out with undefined.

If I have more than one swiper hero on the page - it is then, when it stops working.

**Comment by nolimits4web** [comment]
Look at this demo https://github.com/nolimits4web/Swiper/blob/master/demos/24-multiple-swipers.html
You need to init each swiper separately in this case and call its own .update method later

**Comment by Kyran1** [comment]
Great! Thank you very much for your help!

**Comment by acbfaria23** [comment]
hey, i'm working with a pagination swiper too, and it works with an Html extension. But I need to do this with php pages. any help?
