### ISSUE TITLE
slide indexes are 1 unit bigger than they shuld when loop mode is on

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/Swiper#1164]
When `loop` is `true` than there are some problems with the index values:
`swiper.activeIndex` is `1` on the first slide. I think it should be `0` in this case, because normally Swiper starts indexing with `zero`.
`swiper.previousIndex` is `0`, but after you interact with swiper it becomes one unit bigger than it should. For example when you swipe from the first slide to the second then it becomes `1`. I think it should be `0` too in this case, because normally Swiper starts indexing with `zero`.

I think I can help you fix this issue if you accept my contribution.

**Comment by nolimits4web** [comment]
It is everything fine with. In loop mode there are duplicated slides, and activeIndex returns index of Dom element. So you just need to consider it in your design

**Comment by kireerik** [comment]
Oh, I see. Sorry for reporting this as an issue and thank you for your detailed reply!
