### ISSUE TITLE
Feature request: add onInteraction(swiper) callback

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/Swiper#1165]
Maybe add `onInteractionStart(swiper)` and `onInteractionEnd(swiper)` instead.

**Comment by nolimits4web** [comment]
How they should work?

**Comment by kireerik** [comment]
Well, it is might related to my other feature request that I started to creating, but not yet posted:
### Feature recommendation: add `autoplayEnableOnIdle` parameter
### Autoplay
Parameter | Type | Default | Description
--------------|--------|-----------|---------------
`autoplayEnableOnIdle` | `boolean` | `true` | Set to `false` and autoplay will not be enabled after user not interacted with swiper for some time (`autoplayIdle`).
`autoplayIdle` |`number` | `60 * 1000` | Delay (in ms) after the autoplay should enabled again if `autoplayEnableOnIdle` is set to `true`.

So maybe there is no need for the requested callback.

**Comment by nolimits4web** [comment]
Thanks, good idea will think about including it in next releae

**Comment by kireerik** [comment]
Thank you for finding the idea useful! I think I can help you with the implementation if you accepts contribution to the project.

Also I think this new feature can be supported by only one new parameter. Something like this:
### Autoplay
Parameter | Type | Default | Description
--------------|--------|-----------|---------------
`autoplayReEnable` |`number` | `-` | Delay (in ms) after auto play should enabled again. If this parameter is not specified, re-enabling auto play will be disabled. Any interaction with the slider re-sets the delay.

**Comment by nolimits4web** [comment]
Sure, you may contribute the implementation. But please, make sure that you will take care about this feature in consideration with another autoplay parameters. Also, there shouldn't be too much code for this feature :)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
