### ISSUE TITLE
Outdated dist folder

### ISSUE THREAD

**Issue by francoismassart** [nolimits4web/Swiper#1166]
Hello,
is it normal that the js files inside the dist folder do not contain references to the plugin support?

If you take a look at this commit
https://github.com/nolimits4web/Swiper/commit/f1c385069e90c5b9ba4ac72c3fd7c3325246222d

You see that you define `s.callPlugins = function (eventName)` ... but when inspecting the js files inside of the dist folder there is no references to `callPlugins`...

Do you want me to do it for you and submit it as a pull request?

I'll need the updated version of the dist files in order to demo the issue I have on jsfiddle...

Thank you for your time

**Comment by nolimits4web** [comment]
It is a normal and usual development process, files in src/ folder are in development. When it will be ready to release, i will release it and this code will be in dist/ folder

**Comment by nolimits4web** [comment]
If you need to use it right now, you may use dev version by following build instructions

**Comment by francoismassart** [comment]
Ok, I'll fork the repo and host my copy of the dist files temporarily.
Thanks
