### ISSUE TITLE
Feature request: filtering

### ISSUE THREAD

**Issue by francoismassart** [nolimits4web/Swiper#1171]
Do you plan to allow filtering the shown slides?
For Swiper v2 I was simulating this feature by removing all slides then appending only the filtered slides.
Thank you for the info

**Comment by nolimits4web** [comment]
Not yet, but you can also do the same with adding/removing as in v2

**Comment by francoismassart** [comment]
Ok, then I'll adapt my plugin for v3 and share it on GitHub!

**Comment by anteksiler** [comment]
@nolimits4web It's quite hard to filter slides at the moment, append/prepend loses the original location of the slides.

It would be nice to get a filter functionality like the Slick carousel: http://kenwheeler.github.io/slick/

I am using it with filters here: http://twofold.fuelthemes.net/collection/collection-3/
