### ISSUE TITLE
iOS Cordova app crashes on input drag

### ISSUE THREAD

**Issue by jsundn** [nolimits4web/Swiper#1172]
Hi!

Im using 3.0.4 in a iOS Cordova app. Swiping works fine, but if I touch and drag over a input field the application crashes.Has this been encountered before?

**Comment by nolimits4web** [comment]
No, it shouldn't crash in this case. Something else goes wrong. As you may note that Swiper is used in mobile framework Framework7, it used a lot there with inputs and without any errors of such kind

**Comment by nolimits4web** [comment]
Closing for now as can't replicate this issue. Reopen if issue is still there, but provide some test case
