### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by MiloshRoll** [nolimits4web/Swiper#1173]
Hi everybody, I'm trying to add the swiper script to my web app and i'm encoutering this error :

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.                                swiper.jquery.js:1588 
s.getTranslate				swiper.jquery.js:1588 
s.getWrapperTranslate		swiper.jquery.js:1628 
s.onTouchMove			swiper.jquery.js:1098

The app is developped in struts 2. Please find below the code of my jsp that fires the error : 

        <div class="swiper-container">
			<div class="swipper-wrapper" id="slide"></div>
			 
		    <div class="swiper-pagination"></div>
		    
		    
		    <div class="swiper-button-prev"></div>
		    <div class="swiper-button-next"></div>
		    
		    
		    <div class="swiper-scrollbar"></div>
		</div>
	
	<script type="text/javascript"> 
	//récupération du fichier json grace à url avec valeurs insérer ds var data
	var myJson;
	$.getJSON( "http://localhost:8080/version_test_appli1_16_swiper/getJSONResult.action",
		function( data ) {
			myJson = data;
		}
	);
	
	//alert pour vérifier si on récupère bien le fichier json
	var jqxhr = $.getJSON( "version_test_appli1_16_swiper/getJSONResult.action", 
		function( data ) {
		console.log( "success "+data );
		myJson = data['rows'];
		var txt = "";
			for( var key in myJson )
				txt += key+":"+myJson[key];
			
			alert( txt );
			
			var nbLigne = myJson.length;
			var maxLigne = 10;
			// on répète la creation du tableau toute les 10 lignes
			for( var iTable = 0; iTable < nbLigne; iTable+=maxLigne ){
			
				var div = document.createElement('div');
				div.setAttribute("class", "swiper-slide");
				//div.id = "blabla";
				
				var table = document.createElement("table");
				div.appendChild( table );
				
				// pour l'entete
				var tr = document.createElement( 'tr' );
				
				var th = document.createElement('th');
				th.innerHTML = "Objet";
				tr.appendChild( th );
				
				th = document.createElement('th');
				th.innerHTML = "Date";
				tr.appendChild( th );
				
				th = document.createElement('th');
				th.innerHTML = "Type séance";
				tr.appendChild( th );
				
				th = document.createElement('th');
				th.innerHTML = "Numéro";
				tr.appendChild( th );
				
				table.appendChild( tr );
				
				
				
				
				
				// pour le corps
				for( var iLigne=iTable; iLigne < iTable+maxLigne ; iLigne++ ){
					var ligne = myJson[iLigne];
					tr = document.createElement( 'tr' );
					
					for( var iCell in ligne ){
						var cell = ligne[iCell];
						var td = document.createElement('td');
						td.innerHTML = cell;
						tr.appendChild( td );
						
					}
					
					table.appendChild( tr );
	
				}
				
				var divGrid = document.getElementById("slide");
				divGrid.appendChild( div );
				
			}
			
			
		})
		.done(function( data ) {
		console.log( "second success "+data );
		})
		.fail(function( data ) {
		console.log( "error "+data );
		})
		
      	
		
	//initialisation du swiper quand le document est pret avec Jquery
	$(document).ready(function () {
    //initialize swiper when document ready  
	    var mySwiper = new Swiper ('.swiper-container', {
	      // Optional parameters
	      direction: 'horizontal',
	      loop: true
	    })        
 	 });
	</script>
	
Please tell me if you need any more information in order to help.
I'll be very gratefull for your help.
Thanks a lot !!! And sorry again I'm VERY new to git hub and swipper ;)

**Comment by MiloshRoll** [comment]
sorry I've submitted before i've finished !!!
Please tell me if you need any more information in order to help.
I'll be very gratefull for your help.
Thanks a lot !!! And sorry again I'm VERY new to git hub and swipper ;)

**Comment by MiloshRoll** [comment]
i've just noticed that the begining of the codde is missing, it is : 


     <div class="swiper-container">
			<div class="swipper-wrapper" id="slide"></div>
                        
		        <div class="swiper-pagination"></div>

**Comment by MiloshRoll** [comment]
it is the line below that trows the error : 

curStyle = window.getComputedStyle(el, null);

it is inside the swiper.jquery.js in the function : 

 s.getTranslate = function (el, axis) {
            var matrix, curTransform, curStyle, transformMatrix;
        
            // automatic axis detection
            if (typeof axis === 'undefined') {
                axis = 'x';
            }
        
            curStyle = window.getComputedStyle(el, null);

So I guess that th 'el' parameter's got something wrong...

**Comment by MiloshRoll** [comment]
And the result of it is that all my divs 'swiper-slide' are displayed on the same page...

**Comment by nolimits4web** [comment]
Just initialize Swiper inside of getJSON callback, after you have parsed it and slides already in Dom

**Comment by MiloshRoll** [comment]
Thank you for your answer but i'm not sure to get your point... 
I've tried to initiaize swiper inside the getJSON as below : 
```
var jqxhr = $.getJSON( "version_test_appli1_16_swiper/getJSONResult.action", 
		function( data ) {
		console.log( "success "+data );
		myJson = data['rows'];
		var txt = "";
			for( var key in myJson )
				txt += key+":"+myJson[key];
			
			alert( txt );
			
			var nbLigne = myJson.length;
			var maxLigne = 10;
			// on répète la creation du tableau toute les 10 lignes
			for( var iTable = 0; iTable < nbLigne; iTable+=maxLigne ){
			
				var div = document.createElement('div');
				div.setAttribute("class", "swiper-slide");
				//div.id = "blabla";
				
				var table = document.createElement("table");
				div.appendChild( table );
				
				// pour l'entete
				var tr = document.createElement( 'tr' );
				
				var th = document.createElement('th');
				th.innerHTML = "Objet";
				tr.appendChild( th );
				
				th = document.createElement('th');
				th.innerHTML = "Date";
				tr.appendChild( th );
				
				th = document.createElement('th');
				th.innerHTML = "Type séance";
				tr.appendChild( th );
				
				th = document.createElement('th');
				th.innerHTML = "Numéro";
				tr.appendChild( th );
				
				table.appendChild( tr );
				
				// pour le corps
				for( var iLigne=iTable; iLigne < iTable+maxLigne ; iLigne++ ){
					var ligne = myJson[iLigne];
					tr = document.createElement( 'tr' );
					
					for( var iCell in ligne ){
						var cell = ligne[iCell];
						var td = document.createElement('td');
						td.innerHTML = cell;
						tr.appendChild( td );
					}
					
					table.appendChild( tr );
	
				}
				
				var divGrid = document.getElementById("slide");
				divGrid.appendChild( div );
				
			}
			
			var mySwiper = new Swiper ('.swiper-container'
		    		, {
		      // Optional parameters
		      direction: 'horizontal',
		      loop: true,
		      pagination: '.swiper-pagination',
		      nextButton: '.swiper-button-next',
		      prevButton: '.swiper-button-prev',
		      scrollbar: '.swiper-scrollbar',
		    })
			
		})
```
but the error still remains, sorry if I've got you wrong....

**Comment by nolimits4web** [comment]
Everything looks correct now. But i can't help more without looking at live example

**Comment by MiloshRoll** [comment]
What do you mean with live example ?

**Comment by MiloshRoll** [comment]
Hi ! Ok today I've fixed my eyes and I've found the problem : swiper spelt with two p...
```
<div class="swipper-wrapper" id="slide"></div>
```
instead of : 
```
<div class="swiper-wrapper" id="slide"></div>
```
Now it is working fine ! Thank you again for your help and for this very cool touch slider !
