### ISSUE TITLE
BUG loop: true causes strange pagination behaviour

### ISSUE THREAD

**Issue by francoismassart** [nolimits4web/Swiper#1174]
Take a look at this demo showing 2 swipers:

http://jsfiddle.net/z1nqa9y4/

Both swipers contain 6 slides and both show 2 slides per view/group.
The only difference between the 2 swipers is the loop parameter.

When loop is false, it behaves nicely:
-Swiper pagination has 3 bullets because there is 3 pages of 2 slides (ok)
-Click on bullets works as expected (ok)

When loop is true:
-Swiper pagination contains 6 bullets which is confusing, I would prefer 1 bullet per group/view of slides (ko)
-Clicking on bullets seems to be quite hazardous... For example, clicking on 3rd bullet (out of 6) makes the 5th bullet active! (ko)

Can you confirm this is a BUG?
What is the intended number of bullets?
One bullet per group or one bullet per slide?

Thank you for your response

**Comment by francoismassart** [comment]
Important to know: I'm using a build made using the latest commits and not the current version available in the dist folder of the master...

I'll try the same code using the current dist files and let you know how it behaves.

**Comment by nolimits4web** [comment]
Pagination bullets represents number of so called "snaps". And in loop mode (as in centeredSlides mode), number of "snaps" are the same as number of slides. Otherwise, number of snaps depends on slidesPerView and the current layout

**Comment by nolimits4web** [comment]
But i will check bullets clicks in loop mode

**Comment by nolimits4web** [comment]
The problem seems to be related to slidesPerGroup with loop mode. If you set it to "1" then everything works fine

**Comment by nolimits4web** [comment]
Closing as this should be highly improved in 3.0.5 release
