### ISSUE TITLE
fade effect doesn't autoplay

### ISSUE THREAD

**Issue by scottsanders** [nolimits4web/Swiper#1177]
Hi there. I've noticed that the when using fade effect and autoplay together, Swiper doesn't auto place beyond slide two. I have reproduced this error on the autoplay demo by adding the `effect: 'fade'. I'm looking into this now to see if I can suggest a fix, but thought I would raise it as an issue initially.

**Comment by scottsanders** [comment]
Ok, after looking through the code I've narrowed the problem to line 3123 of swiper.js:
```
if (e.target !== this) return;
```
where Swiper looks to compare the target of the browser's `transitionend` event with the Swiper wrapper while performing callback functions on transitionEnd(). The issue is that the browser's `transitionend` event for the `fade` effect fires has a `e.target` of .swiper-slide as the opacity transition applied to the .swiper-slide and not the .swiper-wrapper like a the `slide` effect transitions do. 

Commenting out this line makes the `fade` effect work in autoplay, but I suspect this could create other issues that I am not aware of. Any thoughts on how else we could resolve this?

**Comment by nolimits4web** [comment]
Fixed, thanks

**Comment by YarGnawh** [comment]
Using version 3.3.1, I had to use the following code to get it crossfade in-place:

```
var swiper = new Swiper('.swiper-container', {
        fade: { crossFade: true },
        virtualTranslate: true,
        autoplay: 5000,
        speed: 1000,
        effect: 'fade'
    });
```
