### ISSUE TITLE
Hash navigation breaks back button

### ISSUE THREAD

**Issue by simonrudkin** [nolimits4web/Swiper#1178]
http://www.idangero.us/swiper/demos/25-hash-navigation.html

Looks like the current slide isn't being updated when the hash is updated by the browser back or forward buttons.

New version is fantastic btw...

**Comment by nolimits4web** [comment]
Hash navigation currently doesn't have any common with browser state/pushState and not suppose to update slide. You may add custom solution for this using, for example `onpopstate` or `hashchange` techincs

**Comment by nolimits4web** [comment]
Closing as no further response or discussion
