### ISSUE TITLE
onClick not fired on desktop

### ISSUE THREAD

**Issue by A11oW** [nolimits4web/Swiper#1179]
on line 1211 <code>if (s.allowClick) {</code> checked allowClick, but allowClick always false.
He is false in function <code>s.onTouchMove = function (e) {</code> on line 1068
if I comment line 1068 onClick fired done

**Comment by nolimits4web** [comment]
Please provide at least JSFiddle and in which browser/system you have this issue

**Comment by A11oW** [comment]
http://jsfiddle.net/A11oW/jjkrva8b/2/
onClick and onTap not fired in Chrome 41.0.2272.89 m
in IE 11 work well done

**Comment by nolimits4web** [comment]
Do you have one of those Windows devices with both touch and mouse support?

**Comment by nolimits4web** [comment]
As it does work for me without problems in Chrome

**Comment by A11oW** [comment]
No, i don't have touch device. default PC with mouse. Windows 8.1. I tested on 5 PC in office and on 2 don't work.

**Comment by A11oW** [comment]
In Firefox 36.0.4 work done

**Comment by nolimits4web** [comment]
Ok, just checked on win 8.1 and same version of chrome, works fine, without any problems. I guess that problem is in those 2 of 5 PCs where it is not working, not in Swiper

**Comment by A11oW** [comment]
I found problem. I delete driver on 2 PC of Oculus Rift, and problem solved

**Comment by altaihero** [comment]
i am trying swiper 3.0.6 but not work pagination and next, prev buttons on chrome v 41.
How you solved can you share your source

**Comment by A11oW** [comment]
I am see this problem also, try use custom markup pagination. When I indicate clearly pagination css class, problem solved.
