### ISSUE TITLE
Swiper does not work on some tablets

### ISSUE THREAD

**Issue by NetanelBasal** [nolimits4web/Swiper#1183]
I test my phonegap app in samsung tablet and swiper does not work there at all, you have an idea why?

**Comment by nolimits4web** [comment]
Should i guess what is your tablet android version?

**Comment by NetanelBasal** [comment]
So you said it will not work on all versions? if yes what version it will not work? thanks.

**Comment by nolimits4web** [comment]
It will not work on Android < 4.0

**Comment by NetanelBasal** [comment]
Ok i will check what is my version and let you know.

**Comment by NetanelBasal** [comment]
This is samsung galaxy tab 3 android 4.2.2 version.

**Comment by nolimits4web** [comment]
So it should work. Check your developer console, maybe there are some errors. Also it would be much helpful if you can provide link so i can look at it. Something could break it also

**Comment by NetanelBasal** [comment]
But this is wired because in other devices like my galaxy phone its work, on this specific device it does not working. but i will try to see in console for errors anyway.

**Comment by nolimits4web** [comment]
Closing as no further discussion
