### ISSUE TITLE
Doesn't work @3.0.5 via browserify

### ISSUE THREAD

**Issue by dfcreative** [nolimits4web/Swiper#1184]
I use swiper as the main slider on a site, and with update to @3.0.5 it stopped to slide more than one slide. @3.0.4 works fine.

I build it via browserify.

**Comment by nolimits4web** [comment]
Can you give me a link to live example?

**Comment by JohnGurin** [comment]
The same here. Swiping works normally, but navigation buttons sporadically stop working. And again the issue occurs when `effect:fade`.

**Comment by nolimits4web** [comment]
Closing as no further discussion and can't replicate this issue with recent version. Reopen if issue or problem is still there
