### ISSUE TITLE
Licence File

### ISSUE THREAD

**Issue by dwhiting10** [nolimits4web/Swiper#1186]
This is a really nice plugin and it has some great features.  The issue that I have is that although you mention on your website that this plugin is licensed under the MIT licence (and it is noted in the files themselves) there is no licence file (that I can find) in the repository itself.  This probably isn't a huge problem most of the time but I am working on a project that is very strict about making sure that plugins used in the project are properly licences and that includes a licence file that can be pointed to.  If you could add the MIT licence file to the repository with your name and the year in the right places at the top (http://opensource.org/licenses/MIT)  that would be very helpful.  Thanks!

**Comment by nolimits4web** [comment]
Don't know how i missed it. Added

**Comment by dwhiting10** [comment]
Thanks so much.
