### ISSUE TITLE
Bug:当两个swiper-slide都有表单(input)时，用TAB键切换焦点时，滑动出现问题。

### ISSUE THREAD

**Issue by saymy** [nolimits4web/Swiper#1192]
当两个swiper-slide都有表单(input)的情况，用TAB键或手机“next"键，从一个swiper-slide切换到相邻的swiper-slide中input时（即焦点到了另一个swiper-slide中），滑动出现问题，即可视的窗口会卡在两个swiper-slide之间，之后的滑动也会出现偏移。

**Comment by nolimits4web** [comment]
Maybe you can write it in English?

**Comment by nolimits4web** [comment]
Sorry, reopen issues when you write it in english

**Comment by zhbhun** [comment]
I meet same issue. If there are some inputs in slide, switching input focus by tab or moble keyboard next key would make `swiper-container`'s scrollTop force a value.

https://codepen.io/zhbhun/pen/BdzweW?editors=1100
