### ISSUE TITLE
Ability to set slide height/width

### ISSUE THREAD

**Issue by cspicuzza** [nolimits4web/Swiper#1193]
I recently encountered an issue with a swiper set with centered slides is calculating the slide width/height too large.  If I set the width in css the centering calculation is off and nothing lines up correctly.   Is there a work around for this?  

Thanks!

**Comment by nolimits4web** [comment]
You need to provide link to issue or to JS fiddle with this issue

**Comment by cspicuzza** [comment]
http://jsfiddle.net/gvkkgj9t/10/

**Comment by nolimits4web** [comment]
That is easy http://jsfiddle.net/vwap6aua/3/
```js
slidesPerView: 'auto'
```
and 
```css
.swiper-slide {
  width:50%;
}
```
do the trick

**Comment by cspicuzza** [comment]
In this particular instance I need to keep the max-width of the slides to 480px.  How would we do that?
