### ISSUE TITLE
Multiple Swiper Implementations on Page Crash iPad IOS 7 and 8

### ISSUE THREAD

**Issue by pr1ntr** [nolimits4web/Swiper#1194]
Hi,
 We are working on a site that can potentially have a lot of swiper instances on the page. We found that this is crashing iPad safari quite regularly and are not sure what it could be. All we know at this point is that when we turn all the galleries off it works fine. We are pretty sure its a memory issue for ios devices. When we profile the application the js footprint is pretty low so we are not really sure what sup with it. We are working on our end to try to nail it down but any info or suggestions from the authors would be really helpful.

The site link:

www.carmichaellynch.com/work/  -> any link from this page.

The link to the gallery module wrapper:

http://pastie.org/private/0wkffshlmnxylfzuksjtq

Some notes on the module, it uses the swiper api to add some extra animations and features. 

BTW, We are really stoked with swiper. This is by far the best gallery plugin we have ever used. Thanks a lot!!

**Comment by nolimits4web** [comment]
Really don't like this line :) http://pastie.org/private/0wkffshlmnxylfzuksjtq#87 Why is that?

First of all, you may try to use different lazy technics with Swiper - like hiding content in not-active slides, also you may don't init Swipers that are not in Viewport, and init them later when user scroll to it.

Second, you use pretty outdated 2.x version of Swiper, it is not supported anymore. We already have Swiper 3 which was totally reworked and has a lot of improvements, fixes and changes

**Comment by pr1ntr** [comment]
Ok, I was thinking we should just update. Line 87 actually shouldn't be in there. I was seeing if csstransforms were causing crashes on IOS7 looks like it got left it in. Thanks for that.

**Comment by pr1ntr** [comment]
btw we bought you some beers ;) enjoy.

**Comment by nolimits4web** [comment]
Wow, thanks, the beer is nice ;)

**Comment by pr1ntr** [comment]
Just don't blow it on Baltika :P

**Comment by nolimits4web** [comment]
Ahah)) That is true, Baltika sucks:)

**Comment by nolimits4web** [comment]
Closing for now, reopen if issues are still there
