### ISSUE TITLE
Deferred css loading

### ISSUE THREAD

**Issue by JohnGurin** [nolimits4web/Swiper#1195]
`swiper v3.0.4`
I'v tried several techniques to defer swpier's style file loading but nothing works.
(for example, http://pastebin.com/sNxiYfWR,
http://www.phpied.com/when-is-a-stylesheet-really-loaded/,
 and swiper is initialized in callback)
I think that if
 ```javascript
var mySwiper = new Swiper(selector,defaults);
```
fires before the style is available the slider does not initialize correctly.
Apparently, this happens only when `effect` is not `slide`
So the _huge_ swiper's stylesheet is critical css.
Can anything be done about this?

**Comment by nolimits4web** [comment]
> I think that if `var mySwiper = new Swiper(selector,defaults);` fires before the style is available the slider does not initialize correctly.

Of course, that is actually how web works, it can't be initialized correctly without stylesheet.
But i think нou are very exaggerating the problem,

> So the huge swiper's stylesheet is critical css

Really, 4-5 KB gzipped CSS is "huge"?!

You shouldn't worry about it

**Comment by JohnGurin** [comment]
Agreed. It's Google's pagespeed insights forced me to panic.

**Comment by JohnGurin** [comment]
By the way, there is a legit way to listen to stylesheet onload event:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Stylesheet_load_events
https://pie.gd/test/script-link-events/
