### ISSUE TITLE
How to set total number of slides to be changes while fast swiping?

### ISSUE THREAD

**Issue by sackIndian** [nolimits4web/Swiper#1196]
Hi

Is it possible to set the total number of slide can change during fast swiping?

I want user to view all sides in my Slider, but if he swipe fast in any of the slide it will run over the slides.

i.e:
Consider i am on slide1, if i swipe fast at slide1, then my swiper go over slide2 and stops at slide3.
But actually i want it to stop at slide2, so that user can at least see all the contents once.

You can refer 
Swiper-3.0.5/demos/01-default.html
of swiper.

I tried with
resistanceRatio : 0,
slidesPerGroup:1

but didn't get it right??

**Comment by nolimits4web** [comment]
That is normal and expected behavior in many many mobile apps. If you do fast swipe, swipe more than 1.5 of slide (so you slide over Slide 1 and more than a half of Slide 2) then it will skip to Slide 3. There is no currently option to disable it, but you can play with the following parameters:
```
shortSwipes: true,
longSwipes: true,
longSwipesRatio: 0.5,
longSwipesMs: 300,
```
