### ISSUE TITLE
Very long swipe will not call onSlideChangeStart or onSlideChangeEnd

### ISSUE THREAD

**Issue by jsundn** [nolimits4web/Swiper#1198]
Hi!

If I hold down and swipe all the way to a new slide and then release (so that it is already at the new position on release), none of my callbacks is called. Only onTransitionStart which is called at the end.

**Comment by nolimits4web** [comment]
Need live example, jsfiddle or video

**Comment by jsundn** [comment]
No problem, give me some minutes and I will fix that

**Comment by jsundn** [comment]
Will this do? http://tinypic.com/r/28jgv48/8

**Comment by nolimits4web** [comment]
Ok, first of all, it is super rare edge case, which is 99% impossible in real world for user to swipe perfectly pixel to pixel on a width of swiper. Second, when you set it in such position, which is snap position of second slide, so there will no be any transition, and transitionEnd/slideChangeEnd event can't be triggered.

I will look on way to fix it, but as for now, you shouldn't worry much about it

**Comment by pasqualevitiello** [comment]
Yes, I was just noticing this issue today, so I decided to use onTransitionStart and onTransitionEnd instead. But, unfortunately, I've just found out another issue: if I set autoplay and fade effect, when the slider reaches the end those callbacks like onSlideChangeStart / onSlideChangeEnd / transitionStart / transitionEnd don't work anymore. They work, instead, with any other effect (slide, cube, coverflow).

Here's a working example (slide effect): http://codepen.io/pasqualevitiello/pen/zxbNaN
and here's the issue (fade effect): http://codepen.io/pasqualevitiello/pen/azMpLp

**Comment by nolimits4web** [comment]
@pasqualevitiello try with latest version, there were some fixes for fade effect

**Comment by pasqualevitiello** [comment]
Superfast answer! But that does not fix the issue.

**Comment by eightJie** [comment]
I use `onTransitionEnd` to instead, expect author to find a way to fix it. thanks

**Comment by nolimits4web** [comment]
@pasqualevitiello fixed issue with autoplays in fade effect

**Comment by pasqualevitiello** [comment]
That's OK, it works fine now! Are you going to merge this fix on next official release?

**Comment by nolimits4web** [comment]
Yes, it will be in next official release
