### ISSUE TITLE
incorrect behavior of thumbs with  loop on / centeredSlides off

### ISSUE THREAD

**Issue by manicko** [nolimits4web/Swiper#1200]
Hi and thank you for the plugin! 

I've created an example here with bootstrap http://jsfiddle.net/3f3vhnxa/

It is responsible and  works correctly except few issues:

1) if you uncomment  line // loop: true, you will see that after the click on thumb the position of the slide calculated incorrectly
2) if you then comment  line // loop: true, but uncomment the  centeredSlides: true, you will see that thumb is not working

Would be grate if you can help with it))
 
I've also found the solution to make the slider responsible without having to put it in 100% height containers and relative blocks.
Instead you could use:

    .gallery-top .swiper-slide{
           padding-top: 100%;
    }

**Comment by nolimits4web** [comment]
Mostly the same as https://github.com/nolimits4web/Swiper/issues/1187#issuecomment-85700991
It will not work like that because if nature and design of controller. To make it work you need to have the same percentage movement for each container, like here http://jsfiddle.net/wpz4rxho/
