### ISSUE TITLE
Error on IE11: Unable to set property 'perspectiveOrigin' of undefined or null reference

### ISSUE THREAD

**Issue by tmikaeld** [nolimits4web/Swiper#1201]
I get the following error, I'm not sure why. 
(IE Version 11.0.9600.17420)

![screenshot_2015-03-30_07-21-19_pm](https://cloud.githubusercontent.com/assets/907195/6902095/f486966a-d711-11e4-9a0b-44471324e140.jpg)

**Comment by nolimits4web** [comment]
Are you using latest latest Swiper version?

**Comment by tmikaeld** [comment]
Hello, sorry, I didn't notice that bower didn't connect when i issued the upgrade.

It all works fine!
