### ISSUE TITLE
Firefox: centeredSlides not centered on first load

### ISSUE THREAD

**Issue by amichel86** [nolimits4web/Swiper#1202]
Hi, thank you very much for this great plugin. I came across a problem and you might be able to help me. Unfortunately I don't have a link to show you but I've attached a screenshot to better explain it. Please note that this problem only occurs on Firefox.

Basically when I open the page in Firefox (close the browser and reopen it) the slides are not centered and after 4 seconds (autoplay) it gets centered automatically. I tried using a number in "slidesperview" but unfortunately when I resize the window I do not get the same responsive result as this configuration below (which I would like to keep). If I remove "centeredSlides" the slider is looking good on Firefox but the slide is (you guessed it) is not centered.

Config:

		 var swiper = new Swiper('#home-carousel-full', {
			pagination: '.swiper-pagination',
			nextButton: '.swiper-button-next',
			prevButton: '.swiper-button-prev',
			slidesPerView: 'auto',
			centeredSlides: true,
			loop: true,
			loopedSlides: 3,
			paginationClickable: true,
			autoplay: 4000,
		});

![firefox](https://cloud.githubusercontent.com/assets/5871701/6904268/b0a182bc-d6ed-11e4-9685-5f14baec2d5f.jpg)

**Comment by nolimits4web** [comment]
Can't say too much without looking at example, or at least at jsfiddle with such error. As only things i have in my minds is try to increase `loopedSlides`. Problem also could be related to images (if you use <img> tags) so FF can't init it correctly on page load while all images are loaded

**Comment by amichel86** [comment]
Looks like I found the solution. I specified a width and a height to my <img> tag and it resolved the issue. :)
