### ISSUE TITLE
Unnecessary spinner when looping back to first image with lazyLoading + loop

### ISSUE THREAD

**Issue by henrik** [nolimits4web/Swiper#1204]
See CodePen: http://codepen.io/anon/pen/KwYPXR

### Steps to reproduce:

* Click right arrow to move from image 1 to image 2, notice the spinner until image 2 loads
* Click left arrow to move back to image 1, note lack of spinner (since it's already loaded)
* Click right arrow to move to image 2 again, note lack of spinner (since it's already loaded)
* Click right arrow to loop back to image 1: we briefly see a spinner even though it should already be loaded

**Comment by nolimits4web** [comment]
That is fixed in dev version

**Comment by henrik** [comment]
:thumbsup: Quick work! Thank you so much :)
