### ISSUE TITLE
activeIndex is one too many with "loop: true"

### ISSUE THREAD

**Issue by henrik** [nolimits4web/Swiper#1205]
With `loop: true` and two slides, the `swiper.activeIndex` will be 3 (instead of the expected 1) when looping back to the first slide. See the console when clicking the right arrow twice here, for example: http://codepen.io/anon/pen/JoVPvP Get 3, expect 1.

I suspect this may be by design, but if so, maybe the documentation could mention it explicitly in the sections for `loop` and `activeIndex`?

**Comment by nolimits4web** [comment]
It is by design. If you'll inspect code you will note that there are duplicated slides, so in loop mode activeIndex is always shifted on number of looped slides. I'll add note in docs

**Comment by henrik** [comment]
Sounds great; thank you!

**Comment by nolimits4web** [comment]
Added notes in docs
