### ISSUE TITLE
lazyloading - prev and next on initialization

### ISSUE THREAD

**Issue by marc-costello** [nolimits4web/Swiper#1206]
Being able to preload the next slide on initialization. Currently it will only load the first slide; then subsequent slides on click of prev/next.

Ideally you would want the option to load the next (and or prev) slides on initialization also.

Awesome job btw, really nice library.

**Comment by nolimits4web** [comment]
Thanks. There will no be slides lazy loading feature, but there is in plans to realise something like virtual slides to keep DOM small. Related to #1154

**Comment by marc-costello** [comment]
Sorry I think you misunderstood. I meant lazyloading of the slide images. This functionality already exists. However it doesn't preload the next/prev images on swiper initalization. Only when you click prev/next nav buttons.

**Comment by nolimits4web** [comment]
Oh, you mean this. Then you need to also enable `lazyLoadingInPrevNext` - as docs states:
> Set to "true" to enable lazy loading for the closest slides images (for previous and next slide images)
