### ISSUE TITLE
Latest erlease not working under FireFox 19

### ISSUE THREAD

**Issue by DareDevil73** [nolimits4web/Swiper#1210]
Unfortunately on our production environment we use OpenKiosk (equipped with FireFox 19) on many older untouchable machines! :(

The 3.x doesn't work on it. The content are often misaligned and the scroll go off the screen.

Could you suggest me how to solved this issue.

This is very important for my company.

Thank you very much,
Antonio

**Comment by nolimits4web** [comment]
FF19 is very old buddy, no way to make it work with Swiper 3. Buy you may try Swiper 2 on it https://github.com/nolimits4web/Swiper#swiper-2xx

**Comment by DareDevil73** [comment]
Previously I'e just used Swiper 2, but recently we upgraded to Swiper 3 to fix some issues and get new features.

I'm trying to repackage FireFox 36 with https://addons.mozilla.org/it/firefox/addon/mkiosk/ in order to get the same features as OpenKiosk (FireFox 19).
