### ISSUE TITLE
2 issues with lazy loading

### ISSUE THREAD

**Issue by felixmaier1989** [nolimits4web/Swiper#1211]
Hi Vladimir, first of all thanks for your library, nice work! I might have found some bugs relative to lazy loading.

Issue #1: Lazy load is not triggered for next&prev slides if initialSlide is set

I found out that slideNextClass and slidePrevClass are missing in the DOM when attempting to lazy load prev&next image. Either L.2759 has a wrong if condition or function slideTo() should execute s.updateClasses() before onTransitionStart() and onTransitionEnd(). 

Issue #2: Lazy load is triggered on onTransitionStart and on onTransitionEnd if lazyLoadingOnTransitionStart is set to false

See console.trace() in my jsfiddle

----

Live example:
https://jsfiddle.net/fkoto00w/
Open your debugger console to reveal the issues
The code to set options to the swiper is at the end of the JS code
I flagged with "##EDIT" the lines I inserted in v3.0.6 code for debugging

**Comment by nolimits4web** [comment]
Will check it

**Comment by nolimits4web** [comment]
> Issue #1: Lazy load is not triggered for next&prev slides if initialSlide is set

Fixed

> Issue #2: Lazy load is triggered on onTransitionStart and on onTransitionEnd if lazyLoadingOnTransitionStart is set to false

Can't replicate, at least with dev version

> that documentation says that lazyLoadingInPrevNext and lazyLoadingOnTransitionStart are TRUE by default, but factually they are false

Docs are fixed

**Comment by nolimits4web** [comment]
If issues are still there, then please provide fiddle or live example with issue
