### ISSUE TITLE
`.swiper-pagination` could have `pointer-events: none` when `paginationClickable` is false

### ISSUE THREAD

**Issue by henrik** [nolimits4web/Swiper#1212]
When it's not clickable, it's unnecessary that it prevents you from clicking through to the underlying slide.

**Comment by nolimits4web** [comment]
Yes, it could, but it is not easy to add this simple one rule in CSS. Otherwise, if it is not clickable dev may want to add custom events/clicks on it, which will not work and may be a bit confusing. So i prefer to leave it to developer

**Comment by henrik** [comment]
Good point about wanting to add custom events. Probably makes sense. Closing!
