### ISSUE TITLE
Missed button clicks

### ISSUE THREAD

**Issue by DareDevil73** [nolimits4web/Swiper#1213]
Hi, after upgraded to the 3.0.x I got a problem with buttons. I explain better the concept.

Inside each slide there are some buttons, built with Bootstrap buttons (thus styled <a> tags) and handled by jQuery events.

Often I've to click twice in order to fire the bound event.

The same buttons outside swiper have no problems!

Could you help me?

Thank you!

**Comment by DareDevil73** [comment]
I've just checked the old release (2.7.6) and the clicks happen correctly.

**Comment by DareDevil73** [comment]
Hi, it'is very difficult to reproduce the error. I started to replicate part of the GUI, but it still not works yet...

https://jsfiddle.net/DareDevil73/psfgtc1j/52/

**Comment by nolimits4web** [comment]
This statement `if (!isTouched) return;` is 100% correct and should be there. Anyway, i also see that you use custom classes for swiper elements, so make sure that you have applied for them the same CSS rules as in *swiper.css*. And where should i look? As i see accordion seems to be working fine

**Comment by DareDevil73** [comment]
The CSS is the one listed on JSFiddle., have you seen it?

I'm inspecting the swiper behavior adding console loggin message before and after the if-statetement, and I see that when the click doesn't fire the if-statement exit the onTouchEnd.

The 2.7.6 works without any problem with the same HTML/CSS.

May Have I missed something inside the CSS as you mentioned?

**Comment by nolimits4web** [comment]
You add there default Swiper's CSS. But if you use "swiper-wrapper-menu" for wrapper class, then you need to copy all styles with ".swiper-wrapper" from Swiper CSS to the same but for ".swiper-wrapper-menu"

**Comment by DareDevil73** [comment]
I'm checking it...

**Comment by DareDevil73** [comment]
I checked styles, and they are correct.

My GUI has made of dynamic parts reloaded by ajax. The ones which contain a swiper container are re-initialized call the destroy method on any previously created swiper instance.

May this approach corrupt some state inside you library?

**Comment by nolimits4web** [comment]
As i see in fiddle, styles are wrong, just switch it to default class names and you will see. Anyway, clicks work correct here, at least that is what i see.

About destroy and reinit. I hope that you call destroy before you replace it with new one from Ajax. If yes, then everything should be correct. Just make sure that you you call destroy with both arguments as `.destroy(true, true)`

**Comment by ewholmes** [comment]
I'm also experiencing this, I think.

It looks like the class `cursor: -webkit-grabbing;` is being applied when I am clicking on the next/previous buttons.

Is there a way to threshold when "grabbing" is considered started? Perhaps it's a simple re-order of listeners to have click happen before the grab start

**Comment by cocomitte** [comment]
I have a similar issue. Mostly happens on Chrome but when I flick between slides buttons don't respond to hover or click. Sometimes when i click on the slide it then allows me to hover/click on the button but its erratic.

**Comment by hhff** [comment]
yeah same - it seems to me like if I click the "next arrow" before the `onSlideChangeEnd` callback has ran for the previous transition, the new transition won't be queued.

If I click rapidly, it seems that this actually prevents the callback from firing, and thus the slider doesn't respond.  I have to stop clicking, wait for the callback to run, and then click to transition to the next slide.

**Comment by hhff** [comment]
FWIW - it seems like the callbacks run extra slow (~1 second late) when I swipe the image with my mouse.

**Comment by IbeVanmeenen** [comment]
+1

**Comment by PawelGIX** [comment]
http://codepen.io/PawelGIX/pen/VPjMQr
My clicks on links in slide not work in Chrome / Windows
