### ISSUE TITLE
Bug in freeMode with only a slide

### ISSUE THREAD

**Issue by DareDevil73** [nolimits4web/Swiper#1214]
Maybe a bug when swiping a freeMode instance with only one slide.

The issue is inside the onTouchEnd function:

>
>        if (s.params.freeMode) {
>                if (currentPos < -s.minTranslate()) {
>                    s.slideTo(s.activeIndex);
>                    return;
>                }
>                else if (currentPos > -s.maxTranslate()) { // Here is the problem!!!
>                    s.slideTo(s.slides.length - 1);  
>                    return;
>                }

When I slide up the slide maxTranslate returns 0 so the swiper resets the position at 0.

My slide height is longer then swiper wrapper so I cannot keep position and show the remaing of the slide content.

Please help me!

The issue is not present in the 2.7.6.

Thank you!

**Comment by DareDevil73** [comment]
Hi again, I thinking about your answer.

We need swiper because of :

* Scrollbar
* Mouse wheel
* Bounce
* and so on...

Is there another way by swiper to accomplish this?

I our scenario the main issue is that when swiper resets the position we cannot display the off-screen part of the slide. :(

**Comment by nolimits4web** [comment]
Yes, Swiper 2 then. But default scrolling has all this:
- Scrollbar (default only), which is great on mobiles
- Mouse wheel - on desktops by default
- Bounce - on mobiles by default

**Comment by DareDevil73** [comment]
I remembered why had to upgrade to 3.0.x : the 2.7.6 has very poor performances on tablet (for my heavy application).

So, I cannot rollback, I need to find a valid solution!

Please give me some more information : the new release swipe only at a slide beginning at certain circumnstances? Is it right?

I ask this because I vae to rethink part of my gui...

Thank you again...

**Comment by DareDevil73** [comment]
I checked styles, and they are correct.

My GUI has made of dynamic parts reloaded by ajax. The ones which contain a swiper container are re-initialized call the **destroy** method on any previously created swiper instance.

May this approach corrupt some state inside you library?

**Comment by nolimits4web** [comment]
I don't know what to offer, just modify source code, you need the `s.updateSlidesSize` and part where snap/slidesGrid are calculated. You may probably try to split such slides into few values of snapGrid

**Comment by DareDevil73** [comment]
Hi, I did the trick : it is enough to add a fake slide height 1px. :)

Thank you for your assistance.

**Comment by paulamariano** [comment]
In my case, I have one slide, freeMode true, and slideWidth > wrapperWidth
I solved this problem in Swiper 3.1.2 adding this parameter: 
slidesOffsetAfter: 1
