### ISSUE TITLE
Is it possible for swiper 3 to mix "swipe effect" with normal scroll?

### ISSUE THREAD

**Issue by gfaceless** [nolimits4web/Swiper#1217]
e.g. When leaving the first page into the second page I have a "swipe effect", but the second page is a long page with a scroll bar, user can scroll up and down just as a normal flow, and when reaching its end, page3 swipes into view.

How to achieve such effect?

**Comment by nolimits4web** [comment]
Don't really understand what you mean. Would be good to see some example. But if you mean to Swiper and scrolling in same direction, then no, by default, it is impossible

**Comment by gfaceless** [comment]
Awesome work, dude! Yes, I meant Swiper and scroll in the same direction. I would like to trigger Swiper when a vanilla scroll reaches its end.

**Comment by nolimits4web** [comment]
No, it is not possible, closing for now
