### ISSUE TITLE
If you set the (display = none), and then resize the browser window, and then set the (display = block) disappear images

### ISSUE THREAD

**Issue by JekaYurko** [nolimits4web/Swiper#1220]
Hi team,
If you set the (display = none), and then resize the browser window, and then set the (display = block) disappear images.

Tell me how to solve it?

Thanks!

**Comment by nolimits4web** [comment]
Call Swiper's `.update` method or try to enable `observer` parameter

**Comment by nolimits4web** [comment]
If you still have this issue, then provide jsfiddle or live example with this issue, and reopen issue

**Comment by JekaYurko** [comment]
thank you very much, helped (observer = true)
