### ISSUE TITLE
Force width and height if Swiper is hidden

### ISSUE THREAD

**Issue by danielefenix** [nolimits4web/Swiper#1223]
Good morning everyone,

first of all, I would like to thank you all for this amazing product and for the support you give.

During the implementation of a single page application, I would need to force the dimensions of the swiper during its initialization. the problem is that if the swiper is initialized on hidden page, it can not calculate correctly (obviously) its dimensions. 

I would like to know if there is a way to force the Swiper, wrapper and slide dimension during its initialization.

Thank you one more time

best regards

**Comment by nolimits4web** [comment]
Currently no way to force it is size. Will think about adding it. But you/should may just call `.update` method when it becomes visible. Or you can try to enable `observer` properties that should do that automatically

**Comment by danielefenix** [comment]
@nolimits4web Thank you very much for your prompt reply. I will try the solution you are proposing.

Daniele

**Comment by danielefenix** [comment]
Thank you very much, it is now possible to specify width: and height: during the Swiper initialization. Even if I am sure you are going to do it, this is a kind reminder to update the documentation. Thank you one more time.
