### ISSUE TITLE
Blank slides

### ISSUE THREAD

**Issue by Issaxis** [nolimits4web/Swiper#1224]
Hello,

I have a problem with slides

code:

><div class="pagination-mono"></div>
<div class="swiper-container" id="mono-character">

 <div class="swiper-wrapper">

		<div class="swiper-slide line-mono">
				<img><div class="pattern-text">test "A"</div>
			</div>
			<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "B"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "C"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "D"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "E"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "F"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "G"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "H"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "I"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "J"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "K"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "L"</div>
  	</div>
  	<div class="swiper-slide line-mono">
  		<img><div class="pattern-text">test "M"</div>
  	</div>

		</div>

</div>

$(document).ready(function(){
 var mySwiper = new Swiper('.swiper-container#mono-character',{
		speed:750,
                pagination:'.pagination-mono',
                paginationClickable: true,
                slidesPerView:'auto',
 });
<

line-mono class is only for custom width

My problem is that I have 13 slides and i don't know why after last element there are "blank slides"?

it looks like :
1 2 3 4 5 6 7 8 9 10 11 12 13 blank blank blank blank blank blank blank blank

And new bullets appear on pagination

**Comment by nolimits4web** [comment]
Do you have live link or link to JSFiddle with this issue? It would be more helpful, so i can take a look

**Comment by Issaxis** [comment]
On JSFiddle it is working well, this must be problem on site and unfortunately I can't give you link,
Anyway thanks for your response :)

Swiper is amazing! Good job!
