### ISSUE TITLE
'onSlideChangeEnd' is not called on first slide change

### ISSUE THREAD

**Issue by ivanquirino** [nolimits4web/Swiper#1226]
this event is not called the first time you change a slide, the same for 'onTransitionEnd'. It calls 'onSlideChangeStart' and 'onTransitionStart' in the end of the first time the slide changes. So the image selector that I'm doing, which gets the select slide as the image only works on the second try :(.

**Comment by nolimits4web** [comment]
Sorry, can't replicate this issue, at least with latest dev version. Maybe you have some live example or JSFiddle so i can take a look?

**Comment by nolimits4web** [comment]
Closing as no further discussion. Reopen if issue or problem is still there

**Comment by amitcw** [comment]
I am also facing same issue with latest swiper version.

**Comment by brendler** [comment]
same here.
