### ISSUE TITLE
Swiper.animating somehow always false

### ISSUE THREAD

**Issue by KeKs0r** [nolimits4web/Swiper#1230]
I am checking swiper.animating in order to prevent touch events on Buttons, because I don't want to navigate when a user actually just wanted to swipe.

I thought that `swiper.animating`can be checked in order to see if there is currently any swiping going on.
Somehow it is always false.

I have now reimplemented what I thought should be done internally:
I have a ´inProgress` variable that is set to true on the progress event and set to false when onSlideChangeEnd.

Did I try using animating wrong?

**Comment by nolimits4web** [comment]
Yes, it was wrong usage, because it sets to true from onTransitionStart to onTransitonEnd, and i guess your custom click event handler executed before transition begin. So the correct logic would be a such kind of flag:
---
var allowClick = true;
o

**Comment by nolimits4web** [comment]
Closing as no further discussion. Reopen if issue or problem is still there
