### ISSUE TITLE
Swiper sliding Issue in a Lightbox or popup on load

### ISSUE THREAD

**Issue by impulsedl** [nolimits4web/Swiper#1231]
Hi I have created my demo over here http://jsfiddle.net/impulseinflame/ytvLmx3u/7/
(http://fiddle.jshell.net/impulseinflame/ytvLmx3u/18/show/)
The is demo is all about open swiper in a lightbox or popup. Issue is when I click on the link in the demo it opens the popup with the swiper(I have used the free mode), its ok but the swiping of the slides does not work for the first time properly…
But when i resize the window it just works fine… Can anybody help me in this, please its really would be a life saver
impulse

**Comment by nolimits4web** [comment]
You need to call Swiper .update after it became visible http://jsfiddle.net/uqLfkhr2/
