### ISSUE TITLE
on('onInit') seems not working

### ISSUE THREAD

**Issue by icewaters** [nolimits4web/Swiper#1234]
Using swiper 3.0.5
```js
var gallery = new Swiper('.swiper-container',{});
gallery.on('onInit',function() {    // not working 
    console.log('init');
  });
```

I found `s.emitterEventListeners` was a empty object before `s.emit('onInit', s);`

`onInit` event  working below
```js
var gallery = new Swiper('.swiper-container',{
   'onInit': function(){
       console.log('onInit...');
    }
});
```

Poor English... sorry

**Comment by nolimits4web** [comment]
```
gallery.on('onInit',...
```
Can't and will not work, because to the place where you write it, Swiper will be already initialised, so use it as callback only, like in your second example

**Comment by fabio-coolshop** [comment]
var swiper = new Swiper('.swiper-container', {
	on: {
		init: function(){
			console.log(this); // Swiper
		},
	}
});
