### ISSUE TITLE
Is possible to completely prevent the user from switching slides?

### ISSUE THREAD

**Issue by adam-lynch** [nolimits4web/Swiper#1235]
I'd like to be able to temporarily prevent switching slides. I'd love to be able to prevent a user going to a certain step until some conditions are met.

**Comment by nolimits4web** [comment]
Yes, look at `lockSwipes` method and `allowSwipeToNext/Prev` options

**Comment by nolimits4web** [comment]
Closing as no further discussion. Reopen if issue or problem is still there

**Comment by adam-lynch** [comment]
No problem. I meant to close this myself until we ran into a problem. :+1:

**Comment by freshdevelop** [comment]
allowSwipeToNext does not work. I'm using Swiper on two wordpress websites with sliders and in both it does not work (TypeError: this[r] is undefined). allowSwipeToPrev, by his side, works flawlessly.

**Comment by azaslavsky** [comment]
Hey @freshdevelop, not sure if this is still an issue for you ~6 months later, but I found a clean solution to the problem, described in my second comment to #1673.
