### ISSUE TITLE
Freemode plus centerSlides to center on active slide

### ISSUE THREAD

**Issue by aaronhb** [nolimits4web/Swiper#1237]
I am trying to use the free mode and have set centermode to true but id does not seem to center on the active slide or snap to the active slide. Is there a way to make it use freemode but as you scroll or it stops it snaps to the active slide and centers it?

**Comment by nolimits4web** [comment]
Sorry, that is why it is called free mode, it has no snaps

**Comment by aaronhb** [comment]
haha ok thanks for the quick reply! :)
