### ISSUE TITLE
Lazy loading: Finish loading the next slide before showing it.

### ISSUE THREAD

**Issue by tmikaeld** [nolimits4web/Swiper#1238]
Would this be possible? Because as it is now, the next image will look blank.

**Comment by nolimits4web** [comment]
I am not really sure what do you mean. But if you mean to load images in slides that are next/prev to the current one, then you need to enable `lazyLoadingInPrevNext` and probably `watchSlidesVisibility `

**Comment by nolimits4web** [comment]
Closing as no further discussion

**Comment by tmikaeld** [comment]
Sorry, was too busy to test it.
I have activated it now and the loading of the image seems to start before the slide changes, the issue is that it changes to the next slide before the load have finished. This is especially apparent on slow connections, since it will slide through several blank slides before showing.

**Comment by nolimits4web** [comment]
Sorry, what you are trying to achieve? If you want to prevent swiping until images are loaded, then it is not possible by default. But you can prevent it by using `lock/unlockSwipes` methods, and "unlock" swiper in `onLazyImageReady` callback. But this will be bad UX for user
