### ISSUE TITLE
Error In Display: Table

### ISSUE THREAD

**Issue by jayss** [nolimits4web/Swiper#1239]
[div style="display:table;"] 
[div style="display:table-cell;"] 
[swiper code]
[/div]
[/div]

 Hi team,
I don't know if it's a bug, but it will display incorrectly in the layout.
Sorry for the wrong html code in the example.
Thanks

**Comment by nolimits4web** [comment]
That is how table works, why you ever use table layout in our times? Anyway will be good to see live example or JSFiddle with it

**Comment by nolimits4web** [comment]
Closing as no further discussion
