### ISSUE TITLE
Responsive height: auto: scrolling/touch not working

### ISSUE THREAD

**Issue by stuff-lineupmedia** [nolimits4web/Swiper#1240]
I have a big vertical slider with 4 section and within a horizontal slider as a startslider.
Desktop everthing works fine, but when it changes to the responsive layout I can not scroll on ipad,
it is stucked, maybe the touchevent does not work.

Desktop version it should be fullscreen height: 100%,
but on mobile version, especially ipad portrait mode it should not. So I set the height to auto.

This is the dev. site:
http://test.lineupmedia.de/seitenwind/index.html

**Comment by nolimits4web** [comment]
But how it supposed to work if you have whole slider height as sum of all slides height, there is nothing to swipe than. So you may destroy it in this case, or use still use height 100% on .swiper-container and height "auto" on .swiper-slide

**Comment by nolimits4web** [comment]
Closing as no further discussion
