### ISSUE TITLE
IE9 not working

### ISSUE THREAD

**Issue by tbraune89** [nolimits4web/Swiper#1241]
Hey,

am i stupid or is the Swiper currently not working in IE9?

Dear lonely IE user, give it a try: http://www.idangero.us/swiper/demos/01-default.html

![untitled](https://cloud.githubusercontent.com/assets/672755/7206584/26c97fdc-e533-11e4-97c6-6f337e99ec34.png)

Thanks,
Tobi

**Comment by nolimits4web** [comment]
No, you not:) It is not compatible with IE9 (https://github.com/nolimits4web/Swiper/blob/master/CHANGELOG.md#swiper-300---released-on-february-11-2015), but has super simple compatible mode with `swiper.jquery.js` version

**Comment by salmenbej** [comment]
If i use the jquery version (3.1.2), it will work with IE9?

**Comment by nolimits4web** [comment]
@salmenbej no

**Comment by alexwenzel** [comment]
Hi @nolimits4web,

You say "has super simple compatibility mode with swiper.jquery.js version". Which Swiper version will work in jQuery Mode for IE9 ?

**Comment by julmot** [comment]
A official list of compatible browser would be very much appreciated.

**Comment by julmot** [comment]
@nolimits4web What is the reason why it has a "super simple compatibility mode" in IE9 but only with `jquery.swiper.js`?

**Comment by chrisdressler** [comment]
Is swiper compatible with IE11? I'm having problems with it there too, but seems to work OK in IE Edge. Is there a compatibility list?

**Comment by nolimits4web** [comment]
@chrisdressler yes it is compatible, except perfect support of 3D effects. What issues do you have?

**Comment by julmot** [comment]
@nolimits4web I just tested Swiper in IE10. It seems that the "grabCursor" does not work. Is there a compatibility constraint?

**Comment by fcubria** [comment]
So your comment about "simple compatibility mode with swiper.jquery.js" was just a joke?

**Comment by nolimits4web** [comment]
No, it wasn't a joke. If something is not clear, then use Swiper 2.x to get better support
