### ISSUE TITLE
Lazy load prev and next image?

### ISSUE THREAD

**Issue by Flayks** [nolimits4web/Swiper#1242]
Hey there,
I just discovered Swiper and that's damn hot!
I'm using a big slider and I was wondering if I can use LazyLoading for my previous and next slide image. Basically, a part of the previous and next slide and its image is displayed on screen (but I have only one item "visible", like the default slidesPerView), so I need to go to the next item to load the next image.
Any chance to "preload" the previous and next slide image?
Thank you!

**Comment by nolimits4web** [comment]
Did you see `lazyLoadingInPrevNext` parameter?

**Comment by Flayks** [comment]
Yep! But it seems to doesn't work well with <img/>. I finally used background images and data-background with the latest commits and it works well.

**Comment by nolimits4web** [comment]
For `<img/>` and background images it works totally in the same way. But yes, current dev version has more fixes for that than `dist` one
