### ISSUE TITLE
Mousewheel smooth scroll & free mode

### ISSUE THREAD

**Issue by Flayks** [nolimits4web/Swiper#1243]
I'm using the mousewheel and freemode options for a slider and it works well. But on Chrome – as usual –, the scroll is laggy/choppy… Is it possible to tweak it with CSS easings or GSAP animations?

**Comment by nolimits4web** [comment]
No, it is not possible to tweak it with default means. Only by changing source code for that part manually https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L2417
