### ISSUE TITLE
On the problems encountered in the use of nested

### ISSUE THREAD

**Issue by Chinalink** [nolimits4web/Swiper#1245]
In the process of using swiper, I found a problem, the use of 2 layers of nested, the outer layer of the loop true, to the inner slider plus the last click to enlarge effect, backward sliding, will fail.

**Comment by nolimits4web** [comment]
Don't really understand the problem. Do you have a link or JSFiddle with this issue?

**Comment by nolimits4web** [comment]
Closing as no further discussion
