### ISSUE TITLE
Different speeds for manual interactions vs. autoplay

### ISSUE THREAD

**Issue by joakimk** [nolimits4web/Swiper#1248]
How do you usually implement different speeds for manual interactions vs. autoplay? Having a slow slide change looks good for autoplay, but a slow change speed feels bad for swiping on a mobile device.

After looking though the API I managed to change the speed of the navigation buttons by doing this:

```coffee
    $swiperContainer.find(".swiper-button-next").click ->
        swiper.slideNext(true, manualSlideChangeSpeed)
```

But that does not change the speed for swipes and other methods of changing slide.

**Comment by nolimits4web** [comment]
you need to change `speed` parameter using, for example:
```
var swiper = new Swiper(..., {
  ...
  speed: 2000,
  onTransitionEnd: function(swiper){
    swiper.params.speed = 2000;
  },
  onTouchStart: function(swiper){
    swiper.params.speed = 400;
  },
  onTransitionStart: function (swiper) {
    swiper.params.speed = 400;  
  }
});

**Comment by nolimits4web** [comment]
Closing as no further discussion

**Comment by aleixfabra** [comment]
With version 4.2.2:

```js
var swiper = new Swiper(..., {
  ...
  speed: 2000,
  on: {
    transitionEnd: function () {
      swiper.params.speed = 2000;
    },
    touchStart: function () {
      featuredSwiper.params.speed = 400;
    },
  },
});
```
