### ISSUE TITLE
getting correct index when looped

### ISSUE THREAD

**Issue by bbnnt** [nolimits4web/Swiper#1249]
for the active index, in the api, when looped, you specify the following : 

"Note, that in loop mode active index value will be always shifted on a number of looped/duplicated slides"

Does this mean the active index can be available correctly out of the box ?
I have difficulties understanding what this really means, or what to do in order to get the right index
does it have to be hacked outside of swiper ?

**Comment by nolimits4web** [comment]
> Does this mean the active index can be available correctly out of the box ?

no

> I have difficulties understanding what this really means, or what to do in order to get the right index
does it have to be hacked outside of swiper ?

In most of cases it will be just `activeIndex - [slidesPerView]`. You can also check layout in developer tools and note that there are `data-swiper-slide-index` attribute on slides, so you can also get it by `swiper.eq(swiper.activeIndex).attr('data-swiper-slide-index')`;

**Comment by bbnnt** [comment]
I get it with this : ```swiper.eq(swiper.activeIndex).attr('data-swiper-slide-index');```
thanks a lot for your quick answer!

**Comment by guari** [comment]
with swiper 3.1.0 both previous solutions seem to return a wrong index, so when migrating from Swiper 2.x I replaced `swiper.activeLoopIndex + 1` with `Number(swiper.slides.filter('.swiper-slide-active').attr('data-swiper-slide-index')) + 1` to obtain a [1-N] index with jquery.
