### ISSUE TITLE
Multiple possible swipers on the same page, activate only one.

### ISSUE THREAD

**Issue by bbnnt** [nolimits4web/Swiper#1250]
I have a page with multiple possible swipers area

Let's say I only need a single one to be used at once (they have each different setups, depending on variables). My problem is that, as soon as one swiper is instantiated, they're all set.
The swiperContainer is correctly targeted

I see that in the demo page (http://www.idangero.us/swiper/demos/), you use iframes. So I wonder if there there Is anything specific to be done in order to achieve that

Thanks a lot for your help

**Comment by nolimits4web** [comment]
Look here, could be useful https://github.com/nolimits4web/Swiper/blob/master/demos/24-multiple-swipers.html

**Comment by nolimits4web** [comment]
Closing as no further discussion

**Comment by bbnnt** [comment]
yep thx!
