### ISSUE TITLE
Paging SlidesPerView Auto

### ISSUE THREAD

**Issue by keisersuze** [nolimits4web/Swiper#1253]
I have a problem. At first loading, the paging does not match with the slide width. But , when i resizing the page, it perfectly work!

see with jsfiddle: http://jsfiddle.net/keisersuze/mr24nmpw/1/show/

Can you fix-it please ?

**Comment by nolimits4web** [comment]
Problem is in your resize/fix script. Why you used it at all? CSS media queries are enough for that http://jsfiddle.net/tyrw28pd/

**Comment by keisersuze** [comment]
Thank you very much!
