### ISSUE TITLE
Add example of freeModeSticky to demos

### ISSUE THREAD

**Issue by cartogram** [nolimits4web/Swiper#1254]
Been having a hard time getting this to work.

**Comment by nolimits4web** [comment]
Why it was hard? It is just `freeModeSticky:true`, nothing special required

**Comment by cartogram** [comment]
Yeah, I've added that to the options, but do not see the effect. I might be missing something or unsure of how it is supposed to look, hence the request for a demo.

**Comment by nolimits4web** [comment]
Did you updated to latest 3.0.7 demo?

**Comment by cartogram** [comment]
Yeah I figured it out. It was working all a long, but the freemode is a bit odd if you have mousewheel turned on as well. When just scrolling through the slideshow, there is no snapping, but when you click and drag it snaps.

**Comment by cartogram** [comment]
Do you know of way to have mousewheel, freemode, and freeModeSticky work together so that when you use the mousewheel and stop scrolling it snaps to the slide that is most in view?

**Comment by nolimits4web** [comment]
No, will add it later. But if you need mousewheel, you probably better to disable freeMode at all

**Comment by cartogram** [comment]
Cool thanks and great work on this by the way!
