### ISSUE TITLE
Chrome sometimes  click does nothing.

### ISSUE THREAD

**Issue by Valonix** [nolimits4web/Swiper#1256]
var mySwiper = new Swiper ('.mainslider', {
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        slidesPerView: 1,
        loop: true
    });

but, if in console i write $(".swiper-button-prev").click();  slider will show a new slide.

This problem i see in your demo site too. This mean, its not my HTML or JS problem.

**Comment by nolimits4web** [comment]
It looks like a browser/environment problem. Duplicate of #1152 and the same in http://www.idangero.us/swiper/forum/#!/bugs-and-issues:nextbuttonprevbutton-doesn

**Comment by klaussilveira** [comment]
@nolimits4web why was this closed? It wasn't fixed.
