### ISSUE TITLE
slidesperView = auto IE11

### ISSUE THREAD

**Issue by stuff-lineupmedia** [nolimits4web/Swiper#1258]
I have a problem with my last slider on this page:
http://2014.seitenwind.com/
Scroll down to the last slider with the staff images.

I set:
slidesPerView: 'auto'

and via CSS:
swiper-slide {
    width: 16.6667%;
}

In Firefox and Chrome everthing works fine, but in IE11 the design chrashes, see screenshot
![screenshotie11slider](https://cloud.githubusercontent.com/assets/5910492/7370256/18cdd44e-edb9-11e4-982b-de804c322a02.jpg)

**Comment by nolimits4web** [comment]
It is your CSS problem, just set `width:100%` for its parent `.mitarbeiter-position` div
