### ISSUE TITLE
SpaceBetween and SlidesPerView Auto bug

### ISSUE THREAD

**Issue by keisersuze** [nolimits4web/Swiper#1259]
http://jsfiddle.net/tyrw28pd/2/

The spaces are unsupported in the Swiper Slide with SlidesPerView: auto

temporary solution in css with "calc"

```html
width:calc(20% - XXX);
```
Julien.

**Comment by nolimits4web** [comment]
Yes, and will not, because in "auto" mode Swiper doesn't check slides width, it is all up to you. So yes, you may use `calc` function. Also, instead of `spaceBetween` you may use `margin-right` on slides in CSS. 

Otherwise you may return to your previous JS solution, but setting it correctly, something like:
```js
var mySwiper = new Swiper(...);

function fixSwiper() {
	if ($(window).width() >= 1200) {
	  //For example 5 slides per slide:
	  mySwiper.params.slidesPerView = 5;
	}
	if ($(window).width() < 1200) {
	  //For example 2 slides per slide:
	  mySwiper.params.slidesPerView = 2;
	}
	if ($(window).width() <= 320) {
	  //For example 2 slides per slide:
	  mySwiper.params.slidesPerView = 1;
	}
    mySwiper.udpate();
}

fixSwiper();
$(window).on('resize', function() {
    fixSwiper();
})

**Comment by keisersuze** [comment]
OK, Thank you! I continue using ```calc``` function.

But i have an other incompatibility with ```slidesPerView:'auto'``` and ```Lazyload```. The images not charging correctly on Auto.

Thanks.

**Comment by nolimits4web** [comment]
As docs states: 
> If you use slidesPerView "auto" or slidesPerView > 1, then you should also enable watchSlidesVisibility and Swiper will load images in currently visible slides

Did you try this?
