### ISSUE TITLE
Vertical scrollbar on a horizontal swiping page?

### ISSUE THREAD

**Issue by jakediscovery** [nolimits4web/Swiper#1261]
In older versions of it was easy to have a scrollable text page on a full responsive page. The scrollbars only seem to appear horizontally now - is there a way to have the pages be vertically scrollable? 

Thanks

**Comment by nolimits4web** [comment]
Nothing changed about this, it is still the same. This demo could help you http://www.idangero.us/swiper/demos/32-scroll-container.html

**Comment by jakediscovery** [comment]
No thats not what I mean, heres an example of my issue, http://jdisco.byethost10.com/swiper/

The content on the first slide cuts off and theres no way to scroll down the first slide - is it possible? It used to be on previous versions of the Swiper. Thanks!

**Comment by jakediscovery** [comment]
Update, I fixed this by adding overflow-y:auto to the swiper-slide class and removing the centering/display/flex attributes.

**Comment by hypo1986** [comment]
http://www.idangero.us/swiper/demos/32-scroll-container.html 
It can not work in mobile,iphone4 or sumsung
