### ISSUE TITLE
IE: MouseDown Event not triggered within a slide

### ISSUE THREAD

**Issue by KeKs0r** [nolimits4web/Swiper#1263]
Hi,

I have found a bug within IE11:
http://jsfiddle.net/n8nmq20k/1/

If you click the text of "slide2" the mousedown event is triggered within chrome. But If you try the same with IE11, the event is not triggered.

**Comment by nolimits4web** [comment]
First of all, in your example is a Swiper 1.8 ?! Where did you get it? :D Update to latest version, and for IE 11 you need to use `pointerdown` event instead of `mousedown`
