### ISSUE TITLE
Preload css background images

### ISSUE THREAD

**Issue by fatsheepcn** [nolimits4web/Swiper#1264]
Images preload through 'img' tags. When come across css background images, it will not preload these images. I use an invisible div to wrap all css background image with 'img' tag:
```
<div class='invisible'>
    <img src='path/of/css background image'>
    <img src='path/of/css background image'>
</div>
```
This method can preload css background images. 
But I suggest providing an 'imgPreload' method to preload images that both images with a 'img' tag and css background image.

**Comment by nolimits4web** [comment]
It is not yet documented but Lazy Loading supports preloading for background image using `data-background` attribute

**Comment by re6exp** [comment]
Vladimir, how to use this data-background attribute?
