### ISSUE TITLE
can you provide a lite version not including mousewhell and anything not related for mobile to make size smaller?

### ISSUE THREAD

**Issue by mask2012** [nolimits4web/Swiper#1266]
Mobile device do not need so many features, I'm using the basic functions only for mobile. and it need  size sensitive, I wonder if you interested on make a lite version? thanks!

**Comment by nolimits4web** [comment]
You can remove not required modules in gulp.js file at https://github.com/nolimits4web/Swiper/blob/master/gulpfile.js#L42

And do `gulp build` to build required version
