### ISSUE TITLE
Does not show pagination buttons for dist idangerous.swiper.js

### ISSUE THREAD

**Issue by fredpedro** [nolimits4web/Swiper#1269]
The idangerous.swiper.js from the zip file doesn't show the pagination buttons of the slider. But when I tried to use the .js file using the CDN, the pagination buttons showed up. 

Also, Swiper doesn't  change slides when I use the next and prev button, and the pagination buttons. I am creating a slider on a Wordpress website.

**Comment by nolimits4web** [comment]
These JS files are totally the same. Something wrong in your code or with your layout. Provide none-working example or JSFiddle with issue. As for now, i am closing this issue
