### ISSUE TITLE
Height issue with vertical slider

### ISSUE THREAD

**Issue by DusanMilko** [nolimits4web/Swiper#1270]
When i make a slider go vertical the height of the items becomes ridiculous at some points.

The height of my slides is 200px, the slider works when horizontal, when i switch to vertical the slides are now 800 and if i resize they jump to huge numbers like 217088px. Seems that the calculation is off. I am not setting a height for the slides, but the automatic height of the items is 200px.

Help?

**Comment by DusanMilko** [comment]
The issue was that the "swiper-container" didnt have a set height. Once I set a height for this every works fine, but I wanted the height to be the size of the slider which the current slider doesnt calculate

**Comment by nolimits4web** [comment]
Sorry, in vertical mode it is mandatory to specify "swiper-container" height, otherwise you may set it using JS with custom code depending on current slide height
