### ISSUE TITLE
Lazy loading next slide when showing more than one slides at a time

### ISSUE THREAD

**Issue by arius28** [nolimits4web/Swiper#1271]
Hi,

I am not sure if it is a bug or a feature request. Either way I think it should be pretty easy coding-wise but I could be wrong!

It has to do with the lazy loading part. It would be nice if we could select the number of next/previous images to preload.

For example I am showing 2 slides per swipe (not in freeMode) and from what I can see nothing gets preloaded as a next slide. Because I show two slides at the same time the second slide counts as the next slide to pre-fetch but its already loaded. I think the appropriate thing would be to lazy-load the slide with index+2.

I hope it makes sense and thanks!

**Comment by nolimits4web** [comment]
As docs state:
> If you use slidesPerView "auto" or slidesPerView > 1, then you should also enable watchSlidesVisibility and Swiper will load images in currently visible slides

If you still have this issue, then provide a live example or JSFiddle and reopen issue

**Comment by arius28** [comment]
Hi Vladimir,

Thanks for the answer. I did try adding `watchSlidesVisibility: true` (alone and together with `watchSlidesProgress: true`) but the next slides are still not loading.

Here is a fiddle of that should give you an idea of what I mean:
https://jsfiddle.net/6r1owp6s/26/

Images in slides 1 and 2 don't have a lazy class attached so they are loaded immediately. All the images in the rest of the slides have the swiper-lazy class attached. Now I would expect that with `lazyLoadingInPrevNext` set to true, slides 3 and 4 should be preloaded before I slide them into view.

The same should happen for slides 5 and 6. As soon as slides 3 and 4 come into view, slides 5 and 6 should be pre-loaded if `lazyLoadingInPrevNext` is true. 

Unless I have misunderstood the purpose of `lazyLoadingInPrevNext`, what am I doing wrong?
