### ISSUE TITLE
Расстояние между слайдами

### ISSUE THREAD

**Issue by Valonix** [nolimits4web/Swiper#1272]
http://savepic.ru/6964217.png 
не получается вставить сюда код, код на скрине выше.

на выходе вижу такое http://savepic.ru/6979577.png
Неужели нельзя их как-то сблизить друг к другу. Если указано 3 и ширина 960 пикселей, то он дает им по 320 ширины. Из-за этого не влазят в мои 960 стрелки влево-вправо. И так на многих слайдах.

**Comment by nolimits4web** [comment]
> Если указано 3 и ширина 960 пикселей, то он дает им по 320 ширины.
Что как бы логично)

> Из-за этого не влазят в мои 960 стрелки влево-вправо.
Можете попробовать поставить slidesPerView:'auto', и выставить нужную ширину и отступы для слайдов в CSS. Или просто вынести стрелки за swiper-container

> не получается вставить сюда код, код на скрине выше.
Тут не понятно что "не получается"?

**Comment by Valonix** [comment]
при копировании и вставки кода он не показывался тут ) 

насчет слайдов, slider-wrapper в отдельный див указав ему ширину, а стрелки остались в slider-container

**Comment by nolimits4web** [comment]
Так проблема решена? Можно закрывать?

**Comment by Valonix** [comment]
да, конечно... разобрался сам :) спасибо.

2015-05-09 16:00 GMT+03:00 Vladimir Kharlampidi <notifications@github.com>:
