### ISSUE TITLE
click events not working when on touch-enabled device

### ISSUE THREAD

**Issue by theluk** [nolimits4web/Swiper#1275]
When you have a ms surface or other touch enabled device and you use your mouse instead of the touch screen, then the click events for the left right icons (and other elements) are not working.

**Comment by nolimits4web** [comment]
This problem was fixed a long time ago. Make sure that you use latest Swiper version (also try the dev one). If problem is still there, then provide a JSFiddle with none working elements and more information about system, device and browser
