### ISSUE TITLE
height is not 100% in the mobile phones 

### ISSUE THREAD

**Issue by assgod** [nolimits4web/Swiper#1276]
There is a problem on mobile phones when I use 20-mousewheel-control of the swiper .
I have set the .swiper-container to height:100% :
.swiper-container{
  width: 100%;
  height: 100%;
  margin-left: auto;
  margin-right: auto;
}
But it doesn't expand the height to 100% that I test in safari and browsers based on webkit.
This problem always happens when I use my finger to scroll the page, almost 50% happens . 
But it expands the height to 100% when I rotate/resize the phone to landscape or portrait direction.

online example for test: http://www.liyudao.com

in the picture below, the swiper-container doesn't expand the height to 100%, there is a gap of white space on the bottom in the browser:

![2015-05-10 111810](https://cloud.githubusercontent.com/assets/6192722/7552962/db2018f8-f706-11e4-8a5c-a66e234563eb.png)

**Comment by nolimits4web** [comment]
It is your layout issue. Swiper is 100% height, but your page is just scrollable, remove other elements after Swiper, or fix them with CSS
