### ISSUE TITLE
How can I remove some undesired features code to make the size smaller?

### ISSUE THREAD

**Issue by Riant** [nolimits4web/Swiper#1277]
I wander if I can remove some undesired features to make the file-size smaller, such as mouse-drag, keyboard Control, 3D, lazy-load.

Just because we only need a light-strong tool which has ability to slider with mouse click on PC, and swipe with finger on touch screen in many projects.

Thanks for such great slider.

**Comment by nolimits4web** [comment]
Look here #1266
