### ISSUE TITLE
Nested Slides - Android Chrome issue

### ISSUE THREAD

**Issue by angel1st** [nolimits4web/Swiper#1278]
Hi There,
I have a project which requires usage of nested views. I tried Swiper and I am having issue displaying 
nested slides under Android Chrome. Android OS 4.4.2, Chrome 42.0.2311.111.
Nested views (even on http://www.idangero.us/swiper/demos/11-nested.html) don't display properly - see screenshots below:
First slide is OK, since it has no nested ones:
![2015-05-10-09-35-37](https://cloud.githubusercontent.com/assets/8547131/7553304/4191b744-f6f9-11e4-8307-6ba7d07a4548.png)

this is how 2nd slide (with nested ones look like):
![2015-05-10-09-36-11](https://cloud.githubusercontent.com/assets/8547131/7553303/419091f2-f6f9-11e4-95ea-8763df61de1c.png)

Any ideas how I can solve that?

Best Regards,
Angel

**Comment by nolimits4web** [comment]
I am sorry, but it looks like issue with your device, seems like something wrong with rendering. I haven't such issue on my Android 4.4 device, also it is ok on Emulator. So closing it for now. If you'll have the same issue on other devices, let me know and i will reopen it
