### ISSUE TITLE
Lazy loading next slide when showing more than one slides at a time

### ISSUE THREAD

**Issue by arius28** [nolimits4web/Swiper#1279]
Hi Vladimir,

This is a reopening of issue #1271.

I did try adding `watchSlidesVisibility: true` (alone and together with `watchSlidesProgress: true`) but the next slides are still not preloading.

Here is a fiddle of that should give you an idea of what I mean:
https://jsfiddle.net/6r1owp6s/26/

Images in slides 1 and 2 don't have a lazy class attached so they are loaded immediately. All the images in the rest of the slides have the swiper-lazy class attached. Now I would expect that with `lazyLoadingInPrevNext` set to true, slides 3 and 4 should be preloaded before I slide them into view.

The same should happen for slides 5 and 6. As soon as slides 3 and 4 come into view, slides 5 and 6 should be pre-loaded if `lazyLoadingInPrevNext` is true and not start loading when they come in the viewport. Unless I have misunderstood the purpose of `lazyLoadingInPrevNext`.

**Comment by nolimits4web** [comment]
Ok, see what you mean. Will fix it
