### ISSUE TITLE
slideToClickedSlide not working

### ISSUE THREAD

**Issue by AchimKO** [nolimits4web/Swiper#1281]
Hi,

I tried to use the Parameter "slideToClickedSlide" but on click nothing happens.
I created a fiddle with an example: http://jsfiddle.net/zfegpfjx/2/

**Comment by nolimits4web** [comment]
Hmm, don't know what you suppose to get? This option means that when you click on any side slides then it will slide to that clicked slide. Just checked your fiddle. Everything works fine for me, as expected

**Comment by adamcoulombe** [comment]
I cannot get slideToClickedSlide to work in chrome using the latest 3.3.1

http://codepen.io/anon/pen/JXyBPK

**Comment by adamcoulombe** [comment]
Seems to work if I increase the timeout a bit on swiper.js @ [ ~line 1629](https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L1629)
``
            setTimeout(function () {
                if (s) s.allowClick = true;
            // }, 0); 
            }, 60);  //   <----bump up the timeout a bit

``
