### ISSUE TITLE
is it Possible to have different wrapper height per slide? 

### ISSUE THREAD

**Issue by clarklight** [nolimits4web/Swiper#1284]
Hi 

   I am wondering if it is possible to have the wrapper height different per each slide? Because i am trying to have the slide 1 to act as a slide in tab, it will drag in slide 2. 
And also it has 3 "slide1 tabs" 1 on top of each other. I attached a very badly drawn image, hope it explains what i am trying to achieve. 
The number is the z-index. And 1,2,3 is on screen(1,2,3 is the tabs, on top of each other), so when you slide them, the slide that are off screen will come in and covers up 1,2,3. (4,5,6 are the slide 2s). 

At the moment because i have to set the fix height for the wrapper for both the slide1 and 2s and give them a z-index, so some of the slides2 won't cover the slides1. 
![20150515_221329](https://cloud.githubusercontent.com/assets/9299584/7654561/b135d912-fb50-11e4-8798-5124ac07a916.jpg)

**Comment by nolimits4web** [comment]
Still not really clear for me what you are trying to achieve. Do you have a link or JSFiddle with what you have tried? Or maybe some live example?

**Comment by clarklight** [comment]
Hi sorry, yes i do "kind of" because i can't make what i am trying to do. But tried it with my best shot here on fiddle 

http://jsfiddle.net/B7hwh/48/

. So i want to stack the slide1, slide111, and slide 1111 like on the photo above as 1,2,3. And the slide 2s are much larger and will slide in and covers all the 1,2,3. 

The 1,2,3 should be 33.33% height each to make up the whole page. And the slide 2s are all 100% each, so when any one of them slides in, they will cover the first page.

**Comment by nolimits4web** [comment]
Sorry, just had a chance to look. And sorry, i think that it is not possible from the box

**Comment by nolimits4web** [comment]
I think we can close it as i can't see way to realize it with Swiper
