### ISSUE TITLE
Issue when using two sliders that control eachother

### ISSUE THREAD

**Issue by vdimitrovv** [nolimits4web/Swiper#1286]
I noticed a bug that if the thumbnail control slider doesn't have `centeredSlides:true;` set then the `activeIndex` will be wrong when sliding through the slides. Hope this helps.

**Comment by nolimits4web** [comment]
It is how `control` works. It works depending on difference in both Swipers. You may read here https://github.com/nolimits4web/Swiper/issues/1138
