### ISSUE TITLE
Responsive swiper

### ISSUE THREAD

**Issue by marianbodisteanu** [nolimits4web/Swiper#1289]
Hi. I have noticed many times when the swiper height is in % and window height is resized it doesn't work correctly. 

im waiting for such results:
![1-correct](https://cloud.githubusercontent.com/assets/8915339/7695512/73290bca-fdf9-11e4-99ba-fe2277bc6fe8.png)

but i get this results:
![2-wrong](https://cloud.githubusercontent.com/assets/8915339/7695515/7a8b3dac-fdf9-11e4-9c0b-931171d54f94.png)

this is my swiper init:
var swiper = new Swiper($swiper[0], {
            slidesPerView: 'auto',
            keyboardControl: true,
            freeMode: true
        });

CSS:
swiper default CSS +

html,body{height:100%;}

.swiper-container{
    position:absolute;
    left:0;
    top:0;
    width:100%;
    height: 30%;
}
.swiper-slide{
    height: 100%;
    position: relative;
    width: auto;
}

and inside swiper slide i have an image.

when i get wrong results after resize i have to hover each slide and it corrected. sometimes it happens for my full screen fade swiper too. any ideas? thanks.

**Comment by nolimits4web** [comment]
Something wrong with your CSS. Do you have a link or JSFiddle?

**Comment by marianbodisteanu** [comment]
here is a demo link of my problem. http://sipwebdev.com/swiper-problem/

1. resize window height
2. refresh page. i was waiting for such result after resize.
3. resize window height as it was. again wrong results

thanks.

**Comment by nolimits4web** [comment]
That is actually how CSS works, not related to Swiper. You may try to wrap images with something else, or you may set swiper-slide's sizes in JS depending on image size/aspect ratio
