### ISSUE TITLE
It can't work on the phone，iphone4 or sumsung ,the demo

### ISSUE THREAD

**Issue by hypo1986** [nolimits4web/Swiper#1290]
It can't work on the phone，iphone4 or sumsung .
This demo : http://www.idangero.us/swiper/demos/32-scroll-container.html
What's the matter.

thanks

**Comment by hypo1986** [comment]
This demo : http://www.idangero.us/swiper/demos/32-scroll-container.html

**Comment by nolimits4web** [comment]
iOS version, Android version, Android browser version? Closing until more information will be provided

**Comment by hypo1986** [comment]
ios6 safari ,Android 4.2.2 , can not work
