### ISSUE TITLE
Google Chrome Next/Previous clicks not working

### ISSUE THREAD

**Issue by ewholmes** [nolimits4web/Swiper#1293]
Hi there,

I believe the issue has to do with touch support. When clicking on Next/Previous, nothing happens. If I keep the dev tools open, I see the class changing on the container, which looks like a "grab" is being triggered rather than a click.

It looks like the class cursor: -webkit-grabbing; is being applied when I am clicking on the next/previous buttons.

Is there a way to threshold when "grabbing" is considered started (once mouse moved 5px, etc.)? Perhaps it's a simple re-order of listeners to have click happen before the grab start

**Comment by nolimits4web** [comment]
It is a browser/platform issue, the same as in #1152 and here http://www.idangero.us/swiper/forum/#!/bugs-and-issues:nextbuttonprevbutton-doesn

**Comment by ewholmes** [comment]
Thanks. It would be great if you could address the issue in one of these, then. As mentioned, this is also happening on your demo sliders, so it's not only a CSS issue.

**Comment by nolimits4web** [comment]
It is not a CSS issue, it is device/platform issue in Chrome, as there is no such issues on Mac, Linux, only on Chrome for Windows and not for everyone. At least, i can't replicate it
