### ISSUE TITLE
Text selection

### ISSUE THREAD

**Issue by soundworks** [nolimits4web/Swiper#1295]
Hi 
how do I enable text selection in the swiper?

Thanks

**Comment by nolimits4web** [comment]
You may add event listener with stopPropagation on mousedown/touchstart/pointerdown events on required text block, 
```
$('.some-text').on('mousedown touchstart pointerdown', function (e){
    e.stopPropagation();
});
```
But then it will be not possible to swipe over this block, otherwise there is no sense to have both abilities to swipe and to select text as they will conflict

**Comment by soundworks** [comment]
Because on my carousel I have banner with coupon codes and I would like them for user to select and copy the codes.

I tried the function but still can't 

Please advise

**Comment by nolimits4web** [comment]
Show you link, or code with what you have tried

**Comment by soundworks** [comment]
Trying to make the text selection only for ui-couponshops

/*swiper shared js*/

function initSwiper(swiperSelector) {
    var that = this;
    this.slideCount = $(swiperSelector + " .swiper-slide").length;
    this.currentIndex = Math.floor(Math.random()*that.slideCount);
    

    var pagingNav = $(swiperSelector + " .ui-slide-nav");
    this.updatePagingDots = function () {
        pagingNav.empty();
        for (var i = 0; i < that.slideCount; i++) {

            if (i === that.currentIndex) {
                pagingNav.append("<li class='active'></li>");

            } else {

                pagingNav.append("<li></li>");
            }

        }

    };

    this.updatePagingDots();


    this.mainSwiper = new Swiper(swiperSelector + " .swiper-container", {
        loop: true,
        calculateHeight: true,

    
       
        onSlideChangeStart: function (swiper) {

            that.currentIndex = swiper.activeLoopIndex;
            that.updatePagingDots();

        }


    });


    $(swiperSelector + " .ui-next-button").on("click", function (evt) {
        evt.preventDefault();

        that.mainSwiper.swipeNext();
    });

    $(swiperSelector + " .ui-back-button").on("click", function (evt) {
        evt.preventDefault();
        that.mainSwiper.swipePrev();


    });
    
        
    that.mainSwiper.swipeTo(this.currentIndex);
}


/*swiper shared js end*/



$(document).ready(function () {
    initTopBanner();
    initCountdown();
    initLeftMenu();

  

    new initSwiper(".ui-time-sale");
    new initSwiper(".ui-member-campaign");
    new initSwiper(".ui-bank");



    new initSwiper(".ui-couponshops",{
        simulateTouch:false
     });
    

    new initSwiper(".ui-newshops");
    new initSwiper(".ui-ladyfashion");
    new initSwiper(".ui-cosmetics");
    new initSwiper(".ui-mensfashion");
    new initSwiper(".ui-electronics");
    new initSwiper(".ui-gourmet");
    new initSwiper(".ui-living");
    new initSwiper(".ui-brandavenue");

**Comment by nolimits4web** [comment]
I don't see that you applied somewhere my code example

**Comment by nehachaudhary** [comment]
Why can't it be done condition based? I am using this library for swiping, it's working fine as expected on mobile/iPad layout. I don't need the swiping behaviour on desktop layout.
Could you not accept an object which takes breakpoint after which the swiping should be enabled?
