### ISSUE TITLE
parallax swipe between slides

### ISSUE THREAD

**Issue by leonidez** [nolimits4web/Swiper#1296]
Swiper currently has support for parallax movement of swiper backgrounds or within swiper-slide elements, but I would like to be able to parallax swipe between different slides. The effect would be the same as that found in Framework7. Any thoughts as to how I could do this?

**Comment by nolimits4web** [comment]
You can achieve it using callbacks, for example using progress. You may look at common logic in effects https://github.com/nolimits4web/Swiper/blob/master/src/js/effects.js
