### ISSUE TITLE
swiper-lazy is not working on Thumbs Gallery With Two-way Control

### ISSUE THREAD

**Issue by pmpSalween** [nolimits4web/Swiper#1297]
I am using Thumbs Gallery With Two-way Control and try to set swiper-lazy class to Gallery-Thumbs and it is not loading unless it is clicked/tapped.
I set "watchSlidesVisibility: true" but it does not help.

**Comment by nolimits4web** [comment]
Yes, there is such issue. Will be fixed in next update

**Comment by nolimits4web** [comment]
Actually no, just checked and it works fine. Please, try the dev version from GitHub

**Comment by pmpSalween** [comment]
Yes, it works fine. I was using version 3.0.4. Thanks for this awesome slider. Cheers
