### ISSUE TITLE
From 3.0.5 to 3.0.7, What is the difference with slidesPerView: 'auto'

### ISSUE THREAD

**Issue by faressoft** [nolimits4web/Swiper#1298]
I used to use the property slidesPerView: 'auto' to make a slide to reload effect with swiper v3.0.5.
But when I had update it to the version 3.0.7 it is not working any more. I have tried a lot of properties to figure what is the difference but I haven't find any solution to my problem.

This is my code that is working fine with v3.0.5:

```
new Swiper(element, {
        slidesPerView: 'auto',
        initialSlide: 1,
        longSwipesRatio: 1,
        wrapperClass: 'elementWrapper',
        slideClass: 'elementSlide',
        allowSwipeToNext: false,
        touchMoveStopPropagation: false
 })
```

I think the problem is with the 'allowSwipeToNext', When I removed it the swiper works fine. But I need it to prevent the user from swiping the element to the left side.

The second slide (The content of the element (the white slide)) should be the initial slide.
![Swipe to reload]
(http://s17.postimg.org/6le4lpajz/Screen_Shot_2015_05_29_at_8_01_36_PM.png)

**Comment by nolimits4web** [comment]
I am not sure that i understood what you are trying to achieve. Do you have a live link or JSFiddle?

**Comment by faressoft** [comment]
I uploaded it to this link:
http://novie.us/test
Better to run it in chrome DevTools mobile device mode.

The code of the swiper is here:
http://novie.us/test/app/novie-list/controllers/NovieListCtrl.js
At line 228

The problem is "allowSwipeToNext" when removed it every thing works fine, but I need it to prevent the user from slide to next slide. allowSwipeToNext works fine with 3.0.5.

**Comment by nolimits4web** [comment]
Ok, it is actually correct. It just doesn't allow you to swipe/set to 2nd slide because of `allowSwipeToNext: false` flag. Instead of this flag, you may just set `resistanceRatio:0` to prevent oversliding after 2nd slide

**Comment by nolimits4web** [comment]
Closing as no further response or discussion
