### ISSUE TITLE
Tap to stop scrolling not working

### ISSUE THREAD

**Issue by nikolafon** [nolimits4web/Swiper#1299]
I'm using version 3.0.7 on IOS 8 and Android 4.4 and when I try to scroll with fast swipe in free mode the it continues to slide until it slowly stop. But if I tap to stop the animation it just won't do anything and animation continues. I have to swipe the opposite side in order to stop it. It seems to work fine with mouse swipe emulation.

**Comment by nolimits4web** [comment]
Right, such behavior is by design
