### ISSUE TITLE
Chrome on IOS 8 free mode momentum not working

### ISSUE THREAD

**Issue by nikolafon** [nolimits4web/Swiper#1300]
In version 3.0.7 in latest Chrome for IOS 8 the after swipe animation is failing.
Swipe is working fine but after you release the finger the  free mode momentum is missing.
It just skips the ease animation and goes strait to final position.
Works fine on Safari and Chrome on Android 4.4.

**Comment by nolimits4web** [comment]
Can't replicate it on this demo http://www.idangero.us/swiper/demos/09-freemode.html

**Comment by nikolafon** [comment]
Strange. I couldn't get it working even after clearing the cache. I don't know what went wrong but now it works fine. I guess the issue can be closed.
