### ISSUE TITLE
Same direction nested Swipe does not work.

### ISSUE THREAD

**Issue by vnandan** [nolimits4web/Swiper#1308]
I used the same example as nested in the demo and switched the direction of vertical to horizontal. I also made the container of the inner swipe smaller but the swipe action is not caught by the inner slide and always slides the outer one.

####Update:

It works perfectly on mobile device but not on desktop browser.

**Comment by nolimits4web** [comment]
Maker sure that you have specified `nested: true` parameter on nested swipers

**Comment by wgroenewold** [comment]
Also ran into some issues of this a while back. First of all, make sure you don't break your UX by having swipers nested that way. Second of all, I managed to solve it by only enabling the nested swiper when hovering them.

**Comment by nolimits4web** [comment]
Closing as no further response or discussion from issue author
