### ISSUE TITLE
Swiper embed in iframe on safari mobile iphone and ipad

### ISSUE THREAD

**Issue by sandyricardo** [nolimits4web/Swiper#1309]
Hai, can anyone help me with this bug? I have searched all over the net and can't find the solution

Here is my link :
sandyricardo.com/testing.html

Problem :
When open in desktop or any android devices, everything fine. But in safari mobile (iphone and ipad) the content of iframe is bigger than iframe width so it has so many blank space and also a horizontal scroll

**Comment by nolimits4web** [comment]
Doesn't related to Swiper, look here http://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari
