### ISSUE TITLE
onSlideChangeEnd doesn't work well with watchSlidesProgress: true

### ISSUE THREAD

**Issue by zexron** [nolimits4web/Swiper#1310]
Hi,

When setting watchSlidesProgress as true, onSlideChangeEnd callback will not be fired if there's a long and slow swipe. onTransitionEnd is triggered, but swiper.previousIndex is the same as swiper.activeIndex, which should be +1 or -1 between them. A quick and short swipe will work correctly however.

**Comment by ms88privat** [comment]
i see the same issue, previousIndex is the same on long, slow swipes

**Comment by nolimits4web** [comment]
Ok, late reply, but explanation is simple. When you use `watchActiveIndex` then active index may be changed during touchmove action, so you shouldn't rely here much on onSlideChangeStart/End callbacks. Need to use onTransitionStart/End

**Comment by zexron** [comment]
Understood. Thank you!
