### ISSUE TITLE
Dealing with inertia based mousewheel issues

### ISSUE THREAD

**Issue by membla** [nolimits4web/Swiper#1312]
There are a number of issues and questions in the forums regarding problems that occur with with inertia based mousewheels/scrollpads such as the Apple Magic Mouse. The solution is certainly not trivial, [this issue](https://github.com/jquery/jquery-mousewheel/issues/36) in jquery mousewheel gives a good rundown.

However, there are solutions that would improve the current state of the functionality in Swiper. I have succesfully solved the issue of inertial scroll advancing two or more slides using the routine mentioned in the above discussion and available as [Lethargy](https://github.com/d4nyll/lethargy)

**Comment by MentalGear** [comment]
thanks for the share ! Comes in hand in other project and should mayb be added to swiper as an option.

**Comment by nolimits4web** [comment]
@membla i still see not correct behavior with your plugin and hot lot more false swipes. Even on your demo page, with fast swipe bottom on MBP trackpad i see 14 times `-1` in console and then many `false`. It is not fit for swiper as in this case slides are changed 14 times, but should be only one

**Comment by membla** [comment]
Just to be clear - this is not my implementation or repo. I have since I posted also found severe limitations with the implementation, people have different ways from mine of physically interacting with, for example an MBP trackpad, and it works good for certain user patterns but not so with others. As the core concept of the method seems sound I'll probably keep an eye on if progress is made on the implementation though. I guess the search can continue for a good solution to the problem...

**Comment by wgroenewold** [comment]
I've accomplished some better results by giving html, body{overflow:auto;}.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
