### ISSUE TITLE
Swiper: Local Fallback testing ?

### ISSUE THREAD

**Issue by MentalGear** [nolimits4web/Swiper#1313]
How could we test if swiper has been probably loaded from a cdn ?

For example: jQuery adds an object to the window, which can be tested on like this:
window.jQuery || document.write("< script src="js/jquery.min.js"><\/script >")

If the test fails, we can load a local copy.

Could you indicate the best way to test if swiper has been loaded probably?
E.x.: typeof (???) === undefined

**Comment by nolimits4web** [comment]
In the same way: window.Swiper || ...
