### ISSUE TITLE
Swiper pagination bullet per view

### ISSUE THREAD

**Issue by nmanhit** [nolimits4web/Swiper#1318]
Sorry ,  I'm not that good at English
I want show 5 bullet per page but ...
![116](https://cloud.githubusercontent.com/assets/12889051/8152834/9b468b24-134c-11e5-8bc1-0e89235b03db.png)
I want to have a result
![115](https://cloud.githubusercontent.com/assets/12889051/8152842/b1002fd8-134c-11e5-8b6e-7748ad22c376.png)
Thanks so much

**Comment by wgroenewold** [comment]
Make the bullets with another swiper, sync that one with the controller option and put the navigation swiper in a swiper with 5 bullets per page. Should work.

**Comment by nolimits4web** [comment]
It is not possible with default code at all. Only some custom solution like @wgroenewold purposed. Or just create a custom bullets and use Swiper .swipeTo method when you click on them
