### ISSUE TITLE
Name collision for .transition method

### ISSUE THREAD

**Issue by legomushroom** [nolimits4web/Swiper#1319]
Hey, good time of the day!

I'm working on client's `wordpress` theme and it uses few plugins with different sliders.
One of them is [revolutionary slider](http://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380), it uses it's own slider approach under the hood. After loading it on a page with a plugin that uses `Swiper`, the latest breaks. After hours of investigation I eventually came across the issue - name collision on `domLib.fn.transition` method, that the `revolutionary slider` sets to `jQuery.fn.transition = jQuery.fn.animate` and obviously spoils your plugin's behaviour. Renaming the `transition` method to something more explicit like `transitionSwiperPlugin` works perfectly well. Anyways I'm not submitting any `PR` here, my intention was to point out on the potential bottleneck that can add some headache to `Swiper`'s users.

Thanks a lot!

**Comment by nolimits4web** [comment]
Hi,
Thanks for reporting, but i am afraid i can't change that as it names of method from Dom7 library which is also used in other projects. So you may just use standalone version of script, there shouldn't be such issues

**Comment by nolimits4web** [comment]
Closing as nothing can do with it. Method name will not be changed
