### ISSUE TITLE
Partial slides last slide not getting active class

### ISSUE THREAD

**Issue by vennamo** [nolimits4web/Swiper#1320]
If using slidesPerView with 1.5 etc for partial visibility, the last slide is not getting the active class.

demo: http://jsfiddle.net/4L4v2m1t/1/

**Comment by vennamo** [comment]
http://jsfiddle.net/4L4v2m1t/2/

Same thing with onSlideChangeEnd for last slide.

**Comment by nolimits4web** [comment]
> If using slidesPerView with 1.5 etc for partial visibility, the last slide is not getting the active class.

It was discussed many times. In this case last slide will never be active, as active index/class depends on slider position. You may use some other layout, or set custom classes using callbacks

The same with onSlideChangeEnd, it is not fired because last slide never becomes active

**Comment by vennamo** [comment]
Ok. But it will some times become active. If swiping really fast.

**Comment by nolimits4web** [comment]
It depends on viewport and on your configuration, but still, don't expect last slide to be active

**Comment by vennamo** [comment]
Oright. I try to figure out something.
Thanks.

**Comment by felippe-regazio** [comment]
Just create an empty slide on your slide stack
<div class="swiper-slide last-slide"></div>

So, consider the last slide as lastSlide-1 on your js
This will secure that your fake last slide will always be reached
