### ISSUE TITLE
Use different transition based on input/interaction

### ISSUE THREAD

**Issue by nordisk** [nolimits4web/Swiper#1321]
Hi,

is it possible to mix transitions on a Swiper instance based on the interaction?

I would like to replicate the following scenario with pseudo events:
- OnSwipe/OnDrag translate the slides with "slide";
- OnKeyboardNav/OnClickcrossfade the slides with "fade";

Cheers.

**Comment by nolimits4web** [comment]
Hi,
Sorry, but it is not possible as these transitions/modes use different layout and logic
