### ISSUE TITLE
When slider has reached end, resizing viewport will move slider one slide to left

### ISSUE THREAD

**Issue by vennamo** [nolimits4web/Swiper#1323]
http://jsfiddle.net/4L4v2m1t/7/

**Comment by nolimits4web** [comment]
Will check it more deeper, looks like issue with rounding as we have 100%/3 width. With slidesPerView 4, 5, 8, etc. there is no such issue

**Comment by vennamo** [comment]
With three slides visible and certain viewport the onSlideChangeEnd callback never fires. I guess this is the rounding issue.

**Comment by vennamo** [comment]
http://jsfiddle.net/4L4v2m1t/11/

Here is example, where the reachEnd triggers correctly but the isEnd in onSlideChangeEnd is not true.
