### ISSUE TITLE
IE8 throws error "Object doesn't support property or method 'indexOf'"

### ISSUE THREAD

**Issue by revxx14** [nolimits4web/Swiper#1325]
I can't find a "supported browsers" list for this script, but I'm having an issue with IE8. It throws the error:

`Object doesn't support property or method 'indexOf'`

You can view this in action here: http://www.weblinxinc.com/beta/oswegoil/site/index.htm

**Comment by nolimits4web** [comment]
IE8 is not supported. You may try to use 2.x version for old browsers https://github.com/nolimits4web/Swiper/tree/Swiper2

**Comment by revxx14** [comment]
Ah, thanks, I figured that was probably the case.
