### ISSUE TITLE
Cannot read property 'swipePrev' of undefined

### ISSUE THREAD

**Issue by b3nhartl3y** [nolimits4web/Swiper#1326]
Hi all,

Having an issue - getting a console error of:

__Cannot read property 'swipePrev' of undefined when using the next and previous buttons.__

JS:
	var mySwiper = new Swiper('.swiper-count-2',{
	    paginationClickable: true,
	    slidesPerView: 2,
	    calculateHeight: true,
	    roundLengths: true,
	    resizeReInit: true,
	    grabCursor: true,
	    loop:true,
	    keyboardControl: true
	 })

I've got multiple sliders (hence the the .swiper-count-2)

Anyone else had this?

Many thanks,
Ben

**Comment by nolimits4web** [comment]
I don't see where you call `swipePrev`. And if you have multiple swipers then you have to initialize them separately. Anyway, check these issues, there are a lot of such with solutions https://github.com/nolimits4web/Swiper/search?p=2&q=multiple+swiper&type=Issues&utf8=%E2%9C%93
