### ISSUE TITLE
BLURRY TEXT AND IMAGES!!!!! roundLengths???

### ISSUE THREAD

**Issue by magentapose** [nolimits4web/Swiper#1328]
Where is roundLengths gone in the new version of Swiper?? I have blurred text and images because of .5px widths on my swiper-slides. Please help

**Comment by magentapose** [comment]
I fixed it by adding a Math.round() to the transform property. Developers, you R-E-A-L-L-Y need to add this as a variable, even though you probably don't want to. It has made working with Swiper a complete headache for me, because the blurriness is much worse than the extra pixel or two that comes without the .5 values. Please add roundLengths again, i'm begging you.

**Comment by vennamo** [comment]
Possible duplicate: #1153 
Im also hoping that this round issue get solved.
