### ISSUE TITLE
Controller issues when "loop" property is enabled

### ISSUE THREAD

**Issue by xrelaxerx** [nolimits4web/Swiper#1329]
Hi,

I want to achieve similar to your thumbnail gallery demo result but with "loop" parameter enabled on both Swipers. Without "loop" enabled controller works flawlessly, however the moment I enable the "loop" parameter controller stops working properly. Here is the demo: http://jsfiddle.net/rfc1en11/1/

Can you please advice if it is possible to solve this issue?

**Comment by nolimits4web** [comment]
It will not work as `Controller` requires for the same amount of slides in each slider. But if you enable loop, then amount of slides will be different. You may try to use `loopedSlides` parameter by passing the same number in both swipers

**Comment by xrelaxerx** [comment]
Seems to be working correctly now. Thank you.
