### ISSUE TITLE
Enable keyboard navigation in the demo?

### ISSUE THREAD

**Issue by dandv** [nolimits4web/Swiper#1331]
First time user evaluating slider libraries.

The UI of [the demo](http://www.idangero.us/swiper/) looked keyboard accessible, like [Superslides](http://nicinabox.com/superslides/). However, pressing left/right arrows after clicking in the slides didn't do anything.

Chrome 42.

**Comment by nolimits4web** [comment]
Ok, get your point. Will enable it along with clickable pagination

**Comment by nolimits4web** [comment]
Enabled
