### ISSUE TITLE
Enable clicking on the dots at the bottom of the slide

### ISSUE THREAD

**Issue by dandv** [nolimits4web/Swiper#1332]
![image](https://cloud.githubusercontent.com/assets/33569/8271053/5d87137a-17b7-11e5-9ef0-63c04ad4b2cb.png)

**Comment by benjamincharity** [comment]
I your options object specify `paginationClickable: true`.

Check out the section on pagination in the docs, [here](http://www.idangero.us/swiper/api/#.VYfi6BNVhBc).

**Comment by dandv** [comment]
Thanks. Could this be enabled in the online demo? (I should've been more specific in the issue title)

**Comment by nolimits4web** [comment]
@dandv it will not be enabled in online demo. It is well described in documentation and presented in a lot of demos, for example in this https://github.com/nolimits4web/Swiper/blob/master/demos/02-responsive.html

**Comment by dandv** [comment]
Very well. I do hope you realize that less sophisticated users who evaluate slider libraries, might be turned off by the apparent bug of the dots not doing anything when clicked, and leave for a competing plugin.
