### ISSUE TITLE
IE doesn't support property or method 'transition' 

### ISSUE THREAD

**Issue by KennyJack** [nolimits4web/Swiper#1333]
hi nolimits4web ,

I'm using swiper version3.0.8, and i found that in all IE 9, 10 and 11 having problem when click to next slide. The error shown

SCRIPT438: Object doesn't support property or method 'transition' 
swiper.jquery.min.js, line 15 character 31485

could you please guide me how to solve this in ie?

**Comment by nolimits4web** [comment]
IE9 is not supported. As for others, it looks like some conflict with your scripts. Try to use standalone version of Swiper

**Comment by KennyJack** [comment]
Hi thanks for quick reply. What does standalone version of swiper mean? Does it have link?

**Comment by nolimits4web** [comment]
This file https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.min.js

**Comment by KennyJack** [comment]
Thanks alot
