### ISSUE TITLE
function slideTo() does not work for swiper with slidesPerView>1

### ISSUE THREAD

**Issue by ayningcao** [nolimits4web/Swiper#1334]
Hi Vladimir, thanks for your great job. 
I have a swiper with slidesPerView=3. Now I need to change active slider programmatically using function slideTo(index). However I found it does not work, the active index of the slider is always the first slider. While I set slidesPerView=1, it works as expected. watchSlidesProgress and watchSlidesVisibility are all set to true. Attached is the sample code. thanks

            var galleryThumbs = new Swiper('#makeupImgSwiper', {
				loop: false,
				spaceBetween : 10,
				slidesPerView : 3,
				watchSlidesProgress : true,
				watchSlidesProgress : true
			});
			
			$(".test").click(function(){
				var v = $(this).val();
				galleryThumbs.slideTo(v, 0, true);
				alert(">>" + galleryThumbs.activeIndex); // always 0
				
				return false;
			});

**Comment by zhangpengdeshu** [comment]
how to slove

**Comment by zhangpengdeshu** [comment]
i have same problem
