### ISSUE TITLE
issues with params.loop

### ISSUE THREAD

**Issue by nitruxa** [nolimits4web/Swiper#1335]
having total slides of 5 with params as follows:

``` javascript
new Swiper('.carousel', {
    loop: true,
    speed: 1000,
    slidesPerView: 2,
    slidesPerGroup: 2,
    spaceBetween: 10
});
```

got this issue:
![swiper loop bug](https://cloud.githubusercontent.com/assets/6697516/8304969/544e9208-19b3-11e5-9738-c41a01d1ccd0.gif)

When clicking next arrow to show last slide, slides are reordered and you can see them flickering just before animation.

**Comment by ayningcao** [comment]
If you set loop to true, Swiper will add additional duplicated slides, thus cause it looks like that they are reordered

**Comment by nitruxa** [comment]
@ayningcao check gif attached. when scrolling something is wrong with transforms - wrongly calculated

**Comment by nolimits4web** [comment]
@nitruxa it will not work properly with 5 slides in your setup. You must have number of slides even to `2` as your slidesPerGroup

**Comment by nitruxa** [comment]
@nolimits4web so it is not possible to have 5 slides, but slide them by 2?

**Comment by nolimits4web** [comment]
It is possible if:
* you disable loop
* or add empty slide on the end
* or use slidesPerView `auto` and put two or one item in each slide

**Comment by nitruxa** [comment]
would be cool having that feature working with:
- loop enabled
- without empty slide on the end
- and having slidesPerView not `auto` 

thing is that we try to do this thing responsive. on different devices it would be from 1 `slidesPerView` to 5

**Comment by nolimits4web** [comment]
> would be cool having that feature working with

It is pretty weird usecase requiring different logic, so not in near future

**Comment by callumacrae** [comment]
Could also be solved by outputting 10 images—each image twice. Shouldn't have any performance impact as long as they're coming from the same URL

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
