### ISSUE TITLE
issue with display none 

### ISSUE THREAD

**Issue by vikasneelam** [nolimits4web/Swiper#1337]
Hi,
I guess Swiper will not be initialized in invisible elements.I am facing this issue with display:none. I tried to append slides to the swiper slide when the swiper container div is hidden.When I display the swiper container it doesn't  work all it shows is the first slide.

**Comment by nolimits4web** [comment]
Call Swiper's `.update` method or try to enable `observer` properties

**Comment by vikasneelam** [comment]
wow..swiper.update().. it works like a charm. Thanks a lot.
