### ISSUE TITLE
issue with setting the initial slide dynamically

### ISSUE THREAD

**Issue by vikasneelam** [nolimits4web/Swiper#1338]
Hi,
After appending slides to the swiper container dynamically , I tried swiper.params.initialSlide = 4; to set the initial Slide to the 4th slide but that didn't work

```javascript
function display()
    {
//function called after appending the slides to the hidden swiper container dynamically
    	$(".swiper-container").removeClass("display_none");
    	swiper.update(); 
    	swiper.params.initialSlide = 4;
    }
```
Is there any way to set the parameters for the swiper dynamically ?

**Comment by nolimits4web** [comment]
You can't set initial slide after initialization, use `.slideTo(4)` method
