### ISSUE TITLE
vertical direction on chrome can not support mouse drag

### ISSUE THREAD

**Issue by meast** [nolimits4web/Swiper#1339]
vertical direction on chrome can not support mouse drag.

**Comment by nolimits4web** [comment]
Really, why? This demo (http://www.idangero.us/swiper/demos/03-vertical.html) doesn't work for you?

**Comment by daemonchen** [comment]
the 2.7.6 version doesn't work.

**Comment by nolimits4web** [comment]
It does, read the 2.x api carefully https://github.com/nolimits4web/Swiper/blob/Swiper2/API.md

**Comment by meast** [comment]
full screen, some times works well, some times not. it seems that something wrong on my computer.

**Comment by nolimits4web** [comment]
Sorry, i can't test or check `sometimes` case. Need to have more information on how to exactly replicate this issue. Closing for now
