### ISSUE TITLE
How to check if slide next or prev?

### ISSUE THREAD

**Issue by dedepress** [nolimits4web/Swiper#1340]
Hi,

I googled and found the issue https://github.com/nolimits4web/Swiper/issues/492

but seems onSlideNext/onSlidePrev callbacks doesn't work, two ways I tried: 

var swiper = new Swiper('.swiper-container', {
          onSlideNext: function(swiper){
            console.log('next');
          }

swiper.on('onSlideNext', function(swiper){
      console.log('next');
    });

Anything I missed? Thanks.

**Comment by nolimits4web** [comment]
There is no such callbacks. Look at #1336

**Comment by dedepress** [comment]
Thanks. Although this is a bit weird,  there is so much properties, methods and callbacks, slideNext/slidePrev is not worth to become a single callback?

**Comment by nolimits4web** [comment]
Can't see any problem with it. There is much properties to give you a fluid control. Such callbacks will not be added as they are not clear in which transition state they should be fired. It is not hard to do `if (s.activeIndex > s.previousIndex) {...}` and it is possible to use in any callback and transition state
