### ISSUE TITLE
Issue of infinite-loop

### ISSUE THREAD

**Issue by prospdragon** [nolimits4web/Swiper#1341]
In demo/15-infinite-loop.html, I have coded below;
var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
		slidesPerView: 5,
		centeredSlides: true,
        paginationClickable: true,
        spaceBetween: 30,
        loop: true
    });
when I run it on mobile device, I get a issue.
It works well when I swipe from right to left (<-).
But when I swipe from left to right(->), sometimes in left half area of screen, I can't see Slide items.

**Comment by nolimits4web** [comment]
Try to increase `loopedSlides` parameter

**Comment by prospdragon** [comment]
I have tried to increase loopedSlides parameter.
Still I get same issue when I swipe.
But it is better than older.
Thank you.
