### ISSUE TITLE
noSwipingSlide: Unable to get property 'parentElement' of undefined or null reference

### ISSUE THREAD

**Issue by marcelboettcher** [nolimits4web/Swiper#1343]
Hey,

my log tells me that user with Win7 IE11 get following error. I cannot replicate it, but at a first glance this could be fixed by extending the while condition and check if `el` exists.

```
Unable to get property 'parentElement' of undefined or null reference
```

in Methode noSwipingSlide:
```
el = el.parentElement;  // now we iterate up (parent node)
} while (!noSwiping && el.parentElement && !hasClass(el, params.wrapperClass)); // also include el.parentElement truthy, just in case.
```

Cheers
Marcel

**Comment by nolimits4web** [comment]
Can't say much as Swiper 2.x is not supported anymore and there will no any updates or fixes for it
