### ISSUE TITLE
swiper slider when first loop is complted rollback all images 

### ISSUE THREAD

**Issue by kisan** [nolimits4web/Swiper#1345]

**Comment by callumacrae** [comment]
What does this mean?

**Comment by kisan** [comment]
after completions of the first loop and at the end of second loop when the first image is clicked to start the third  loop the slider misbehaves by rolling back to initial position

**Comment by nolimits4web** [comment]
@kisan still not clear, would be good to see live example or JSFiddle

**Comment by dineshdedhia** [comment]
http://demo.cogmat.in/Slide/carousel.html

**Comment by dineshdedhia** [comment]
Problem is When I slide Gently to the left or right, it shows some space and i need to remove that space and make that continuous

Thanks for the help in Advance

**Comment by callumacrae** [comment]
Replicated:

![Uploading Screen Shot 2015-07-07 at 11.23.17.png…]()

The images don't turn up until I swipe again.

**Comment by dineshdedhia** [comment]
yes you got that right, Can i get Solution to make that continuous slide.

Thanks for the help

**Comment by nolimits4web** [comment]
Just increase `loopeeSlides` parameter

**Comment by dineshdedhia** [comment]
I had already tried 'loopedSlides' parameter, still i get the same issue. Can you help me some other way.

Thank you for the help

**Comment by nolimits4web** [comment]
@dineshdedhia It would be good to see what exactly you have tried (code or better live preview)

**Comment by dineshdedhia** [comment]
Hello Vladimir,

Please find attached .zip file, Thanks for the help :)

**Comment by callumacrae** [comment]
You can't attach files in email replies, you'll need to upload it somewhere. a working jsfiddle demo would be best

**Comment by nolimits4web** [comment]
I think i can close it as there is no further discussion

**Comment by kisan** [comment]
its ok thanks for supports
