### ISSUE TITLE
02-Responsive Swiper: How to prevent images from distorting?

### ISSUE THREAD

**Issue by murtijung** [nolimits4web/Swiper#1347]
Hi,

I have used the 02-Responsive Swiper code on my mobile site for a gallery. Especially on vertical screens the images are very distorted on mobile screens. Can somebody help how I have to change the code so that the images don't distort? I would like them just to be displayed maintaining the original ratio of height/width and then either to be displayed centered over width or height of the mobile screen. 

Thanks!

**Comment by nolimits4web** [comment]
Remove styles related to `flexbox` from `.swiper-slide` and then style image size like you need in CSS

**Comment by nolimits4web** [comment]
Closing as no further response or discussion and issue is not really related to Swiper
