### ISSUE TITLE
swiper.onlyExternal 'remembers' unreleased touchMove

### ISSUE THREAD

**Issue by univie** [nolimits4web/Swiper#1349]
Let's say swiper.onlyExternal is set to true and the user tries swiping a slide. If onlyExternal is then set to false while the user is still swiping (i.e. before touchEnd), the swiper will 'remember' that swipe, causing a jump to where wrapper position would have been. This behaviour seems different from the previous version.

**Comment by nolimits4web** [comment]
Thanks, will check it
