### ISSUE TITLE
Unable to have thumbnail navigation without two swipers

### ISSUE THREAD

**Issue by dillonbailey** [nolimits4web/Swiper#1350]
Attempting to setup a slider with Swiper similar to the one in the attached screenshot. But the example with thumbnails creates two sliders that inevitably will go out of sync or not be able to be setup with a static set of thumbnails to act as navigation for the primary slider.

Is this setup currently supported or does it require some custom calls to the API to create the navigation in this way?

<img width="541" alt="screen shot 2015-07-06 at 8 12 37 am" src="https://cloud.githubusercontent.com/assets/1067872/8513643/dc4d0538-23b6-11e5-9283-67e5d08b7bf5.png">

**Comment by nolimits4web** [comment]
Don't use swiper for such thumbnails. Make them using custom code, and call `swipeTo` method when you click on it

**Comment by nolimits4web** [comment]
Closing as no further response or discussion
