### ISSUE TITLE
Dynamic loading and memory optimization

### ISSUE THREAD

**Issue by 3zzy** [nolimits4web/Swiper#1351]
Hi,

I'm planning to use Swiper for a project where I'll have huge and multiple galleries on a single page so I'm a tad bit worried about performance. So my questions:

1. A gallery contains 600 images, but I need to load 3 to 5 at a time, however, the pagination should show the actual slide/page number as if it was a 600 page gallery, is that possible with Swiper? 

2. Is Swiper memory efficient? I'm sure it must be but since nothing is mentioned on the website so I'm wondering if Swiper also does some of this:

>- PhotoSwipe keeps only three images in the DOM at once, because each “slide” is a composited layer, which consumes quite a lot of memory.
>- Almost no memory is consumed until the gallery is first opened.
>- The script has been tested for memory leaks. Navigating images back and forth and creating or deleting a gallery doesn’t leave a trace in memory.

>- RequestAnimationFrame is used wherever possible.
>- Only the transform and opacity properties are animated. Almost no paints occur during animation, making transitions as smooth as possible.

Thanks

**Comment by nolimits4web** [comment]
> PhotoSwipe keeps only three images in the DOM at once, because each “slide” is a composited layer, which consumes quite a lot of memory.

no

> Almost no memory is consumed until the gallery is first opened.
The script has been tested for memory leaks. Navigating images back and forth and creating or deleting a gallery doesn’t leave a trace in memory.

> RequestAnimationFrame is used wherever possible.

> Only the transform and opacity properties are animated. Almost no paints occur during animation, making transitions as smooth as possible.

yes
