### ISSUE TITLE
Choppy slide transition in Firefox (Swiper 3.0.8)

### ISSUE THREAD

**Issue by webpepper** [nolimits4web/Swiper#1353]
First of all, great script! 

I've recently developed two websites using Swiper and noticed the same issue on both websites. In Firefox (at least versions 38 & 39) the slide animation is very choppy. And there seems to be a lag between the user action (click, drag or swipe) and the actual beginning of sliding. I.e., after I click the "Next slide" button it take about 0.5-1 seconds before the Swiper does anything. On other browsers that I tested the response is instantaneous (Safari, Chrome) .

My 3.0.8 configuration is fairly simple:
```javascript
{
   freeMode: true,
   freeModeSticky: true,
   keyboardControl: true,
   mousewheelControl: true,
   speed: 1000
}
```

Some of my slides are heavy (videos & images in them), so that may be a part of it. But it doesn't make sense why Firefox is the only browser that has issues with them.

Here's a demo with large images to simulate the heavy slides:
https://jsfiddle.net/nhqp8y6j/5/

In the demo, the lag is especially noticeable when you click the next/prev arrows.

**Comment by nolimits4web** [comment]
Yes, the problem is in FireFox, probably it has performance issues when use a lot of big images. I recommend you to use any available lazy-loading technic here

**Comment by wgroenewold** [comment]
Noticed the same on Firefox 39 (OSX) with just a simple fullscreen test Swiper with 4 slides, no images. Config has nothing in it besides speed. The lag is just in de begin of the slideChange.

**Comment by webpepper** [comment]
I tried removing callbacks, extra checks, etc. from the code to try to pinpoint the bottleneck. But there was only a very insignificant increase in speed, the lag was still there. I tried it in Windows and OSX - same unfortunate result.

It looks like there ain't enough Fire in this Fox to pull off this stuff.

**Comment by webpepper** [comment]
I managed to achieve a significant improvement in responsiveness in Firefox by removing the `transform-style` rule or setting its value to `flat`. Keeping the value as `preserve-3d` is pointless anyway when the swiper runs in the sliding mode.

Add this to your custom CSS code if you don't want to edit Swiper's stylesheet:
```
.swiper-wrapper,
.swiper-slide{
   -moz-transform-style: flat;
   -webkit-transform-style: flat;
   -ms-transform-style: flat;
   transform-style: flat;
}
```

Updated demo that should run smoothly in Firefox:
https://jsfiddle.net/nhqp8y6j/6/

**Comment by nolimits4web** [comment]
I would recommend you to keep just
```
-moz-transform-style: flat;
```
because this `preserve-3d` style can actually improve performance on Mobiles (in webkit/Chrome)

**Comment by wgroenewold** [comment]
@nolimits4web How about implementing the -moz-transform-style:flat when no other mode than sliding is enabled?

**Comment by fluidbrush** [comment]
Implementing -moz-transform-style:flat will break the 3d type slider right?
