### ISSUE TITLE
Swiper unusable without a mouse

### ISSUE THREAD

**Issue by callumacrae** [nolimits4web/Swiper#1356]
Because `.swiper-pagination-bullet` is a span, it can't be used without a mouse. If they were `<button>` elements, it would be possible to activate them using the keyboard.

There are many users of the web who use only keyboards—some of them for convenience, some of them because of disabilities.

_(note: even though I'm opening tonnes of issues, I'm planning on fixing them and sending PRs myself; sorry for cluttering your issues :smiley: )_

**Comment by nolimits4web** [comment]
I would avoid button element because it's styled can be easily rewrited with something else, especially if it used within frameworks. You may also use paginationBulletRender parameter to use any element you may need to represent bullet

**Comment by callumacrae** [comment]
This is really bad for accessibility, though! A button element is the most semantic element to use. If a user overwrites it, that's their problem.

**Comment by nolimits4web** [comment]
Add and option to use it as any element, as well s button. The problem is the most devs who use Swiper are not experienced at all, and when they see additional/wrong colors and borders on pagination element, it will just produce a lot more questions here :)

**Comment by nolimits4web** [comment]
Add option to use it with button in c956980
