### ISSUE TITLE
Linking up text with the current slide

### ISSUE THREAD

**Issue by alexjohnlyman** [nolimits4web/Swiper#1357]
Thank you @nolimits4web for Swiper, it is awesome! I have to apologize, because I still pretty new to this so I hope that I can clearly explain what I am trying to do and that you can help out. 

I would like to have some text (title and description) associated with each image in the swiper, and ideally that text would display outside of the swiper-container. In other words, I want to update the text you see based on whichever image you are currently viewing in the swiper. I set-up a JSFiddle to try and illustrate what I basic version of what I currently have. I am looping through a library of images on my server which is why the img src is empty, but is showing text and images on my end.

https://jsfiddle.net/od7m1q99/11/

Please let me know if there is already functionality set-up to do this, and if not, any tips you have would be great. Thank you!

**Comment by alexjohnlyman** [comment]
I was able to get this figured out. I used the onSlideChangeEnd callback and set it show a description based on whichever div had the current "swiper-slide-active" class attached to it. I updated the JSFiddle with the code that I used. Should've caught that one sooner!

**Comment by keisersuze** [comment]
Hi,

Did you have a final exemple of your solution ? I'm interested.

Thanks.

**Comment by alexjohnlyman** [comment]
You bet. This is a portion of the JS for my swiper object which I believe fixed it. 

                onSlideChangeEnd : function (swiper) {
                    $('#current-slide').html(swiper.activeIndex);
                    selected = $(".swiper-slide-active div");
                    $('#current-desc').html($(selected).data('desc'));
                    $('#current-desc').fadeIn();
                }

Hope this helps.

**Comment by keisersuze** [comment]
Prefect! Thanks :) it work!

Just one question.

How to get "data-desc" (first slide) when Swiper load?

I have to use the function "onInit" with same method ?

Thank you very much

**Comment by alexjohnlyman** [comment]
Not sure. I actually am not using "onInit" in mine, but that would probably work fine.

In mine I also have this, but I don't think that this helps you at all.

                onSliderMove: function (swiper) {
                    $('#current-slide').html(swiper.activeIndex);
                    $('#current-desc').fadeOut();
                },

Sorry I wasn't more help. Good luck!

**Comment by keisersuze** [comment]
No problem, I found a solution :)

```
var MySwiper = new Swiper('.swiper-container', {
    paginationClickable: false,
    simulateTouch: false,
    slidesPerView: 1,
    onSlideChangeStart: function (swiper) {
        // start Swiper slide
        var sizes = $(MySwiper.slides[MySwiper.activeIndex]).attr("data-desc");
        $('.item .current-desc').html(sizes);
    },
});
// on Load Swiper
var sizes = $(MySwiper.slides[MySwiper.activeIndex]).attr("data-desc");
$('.item .current-desc').html(sizes);
```

Thanks for your time!
