### ISSUE TITLE
LazyLoad and appendSlide doesn´t load first Image

### ISSUE THREAD

**Issue by magic-77** [nolimits4web/Swiper#1358]
Hi,
i need to append all Slides dynamically. So i´m using this code.

    <div class="swiper-container swiper-gallery">
      <div class="swiper-wrapper"></div>
        <div class="swiper-button-prev sgp"></div>
        <div class="swiper-button-next sgn"></div>
    </div>

and JS

    var pgal0 = [
        {src: 'assets/images/9/8B4MQPNAB6-5505aee9.jpg'},
        {src: 'assets/images/6/ESTTV0M8OG-43b7a666.jpg'},
        {src: 'assets/images/7/T96V0685JW-69354fe7.jpg'},
        ....
    ];

    $(".initGallery").on("click", function() {
            var swiperGallery = new Swiper(".swiper-gallery", {
              nextButton: ".sgn",
              prevButton: ".sgp",
              grabCursor: true,
              preloadImages: false,
              lazyLoading: true,
              onInit: function(swiperGallery) {
                swiperGallery.appendSlide([
                  "<div class='swiper-slide'><img data-src='" + pgal0[0].src + "' class='swiper-lazy'><div class='swiper-lazy-preloader swiper-lazy-preloader-white'></div></div>",
                  "<div class='swiper-slide'><img data-src='" + pgal0[1].src + "' class='swiper-lazy'><div class='swiper-lazy-preloader swiper-lazy-preloader-white'></div></div>",
                  "<div class='swiper-slide'><img data-src='" + pgal0[2].src + "' class='swiper-lazy'><div class='swiper-lazy-preloader swiper-lazy-preloader-white'></div></div>",
                 ...
             ]);
           }
        });
      });

this causes, that the first image isn´t loaded. But swiping to the next slide, and sliding back loads the first image well.
When using "swiperGallery.prependSlide" first displayed image is being loaded.
Did i forgot an additional parameter or this is kind og Bug ?

p.s.: This is a really nice Plugin!!!

**Comment by nolimits4web** [comment]
There is no sense to do that - to load all slides within init event. Just append them before you init Swiper:
```
$('.swiper-wrapper').append('<div class="swiper-slide">...</div>...');
var swiperGallery = new Swiper(".swiper-gallery", {
          nextButton: ".sgn",
          prevButton: ".sgp",
          grabCursor: true,
          preloadImages: false,
          lazyLoading: true,
})

**Comment by magic-77** [comment]
Hey,
this works. Thanks for your help.
