### ISSUE TITLE
slidesGrid values are calculated incorrectly when slidesPerView = auto

### ISSUE THREAD

**Issue by mmakarin** [nolimits4web/Swiper#1359]
See example. You can open the left bar with a long swipe, but cannot open the right slide with the same action due to this bug.

Looks like this code produces error.
```javascript
for (var i = 0; i < s.slidesGrid.length; i++) {
    if (- translate >= s.slidesGrid[i]) {
        slideIndex = i;
     }
}
```

http://codepen.io/anon/pen/YXLwxw

**Comment by nolimits4web** [comment]
This code is correct, and i CAN open right panel with long swiper, not sure what issue did you mean?

**Comment by mmakarin** [comment]
When you pull left slide long enough it stays put. But when you pull the right one it doesn't.

**Comment by nolimits4web** [comment]
Ah, i see what you mean now. It is because with long swipes it looks on the 1/2 distance of current slide (orange one), so you have to move it more than on half to switch to next (right) slide. You can tweak it using `longSwipesRatio` parameter

**Comment by nolimits4web** [comment]
Closing as not further response & discussion
