### ISSUE TITLE
Bootstrap 3 modal

### ISSUE THREAD

**Issue by onebeat** [nolimits4web/Swiper#1361]
Hello, i have bootstrap 3 template where have added swipper "code" and everything is working just great but when i have added same code to bootstrap modal i cant swipe at all.

Did anybody had this kind of problem ?

**Comment by nolimits4web** [comment]
This problem is related to bootstrap. I don't know it is API, but i guess you need to call some of its method to reinit/update Swiper when modal with Swiper becomes visible

**Comment by onebeat** [comment]
Is there method for reinit swipper ?

**Comment by nolimits4web** [comment]
> Is there method for reinit swipper ?
`mySwiper.update` - it is well described in docs http://www.idangero.us/swiper/api/#.VaKlO5Ptmko
