### ISSUE TITLE
Swiper.js with WOW.js! Please help

### ISSUE THREAD

**Issue by shantanuay** [nolimits4web/Swiper#1362]
Hi, 

I was trying to get something like the Fiddle, but there is a issue i see that when swiper loads all the wow elements are executed. only the first time the wow animation is working and on other slides its not. Please help on it.
http://jsfiddle.net/impulseinflame/02achd8a/

**Comment by nolimits4web** [comment]
Sorry, this question should be probably related to the WOW community, you already have onSlideChangeStart/End callback, and in this callback you need to trigger WOW-animated elements

**Comment by shantanuay** [comment]
Thanks but if you have any idea on this?

**Comment by nolimits4web** [comment]
Nope, sorry. I am not familiar with WOW api and how it works

**Comment by shantanuay** [comment]
Thanks, just a favor, is there any example of swiper having animated content on each slide?

**Comment by nolimits4web** [comment]
You have callbacks for that, where you can do anything you want, including animating something with methods/plugins you know, for example with jQuery:
```js
onSlideChangeEnd: function (s) {
  var currentSlide = $(s.slides[s.activeIndex]);
  //do something
  currentSlide.find('.something').fadeIn();
}
```
Closing, as it is not an issue
