### ISSUE TITLE
slideTo undefined

### ISSUE THREAD

**Issue by aaronmarruk** [nolimits4web/Swiper#1363]
Hello, I'm trying to implement the slideTo method. I am trying to set slideTo of, for example, swiperB, based on activeIndex of swiperA.

However, I am getting 'slideTo undefined' on my swiperB, where I am able to successfully call slideTo on swiperA. Is there anything I need to do as a prerequisite to using slideTo?

Thanks in advance.
Ps. I've had a good read through the docs and was unable to find a solution.

**Comment by wgroenewold** [comment]
Hey,

If you want to trigger Swiper B based on SwiperA's activeIndex you should use the callback functions of SwiperA. So onSlideChangeStart of Swiper A SwiperB.slideTo(slidenumber-you-want-to-go-to)

**Comment by aaronmarruk** [comment]
Hey, thanks for the response. 

I found the issue, by accident I had 2x swiperB divs in my DOM. So the call to initialise swiperB wasn't completing successfully.
