### ISSUE TITLE
Swiper grid not working with loop:true

### ISSUE THREAD

**Issue by saukri** [nolimits4web/Swiper#1366]
I am getting " 'nodeType' of undefined " error while trying to make my grid to loop and autoplay. Whole thing breaks down.

my code:
var swiper = new Swiper('.swiper-container', {
	 loop: true,
	 pagination: '.swiper-pagination',
	 slidesPerView: 4,
	 slidesPerColumn: 2,
	 slidesPerGroup: 8,
	 spaceBetween: 5,
	 paginationClickable: true
});

**Comment by wgroenewold** [comment]
I never used the SlidesPerGroup, but to me it looks like your numbers are off. When there are 4 slides in a view then the maximum for a group can be 4 I think. So if you want 4 slides in 2 columns it should be 4,2,4. If you want 8 slides in 2 columns it should be 8,2,8. But then again that's my interpretation of the documentation, not experience. If this is not right then the documentation should improve ;)

**Comment by saukri** [comment]
No, in that case it moves only half of the grid

**Comment by nolimits4web** [comment]
@saukri can you provide a link to example or JSFiddle?

**Comment by nolimits4web** [comment]
Closing as not further response & discussion or examples

**Comment by teejayhh** [comment]
sorry to bring this up again  but I have this issue as well. I made a code pen. http://codepen.io/teejayhh/pen/rxKgWv

try resizing and you will see the error poping up
