### ISSUE TITLE
Check if slider destroed

### ISSUE THREAD

**Issue by A11oW** [nolimits4web/Swiper#1367]
I init slider something like that
<code>screenSlider = new Swiper($container, sliderParams);</code>
and then destroyed:
<code>screenSlider.destroy(true, true);</code>
In documentation first method argument destroy "delete Swiper instance", but after <code>destroy(true, true)</code>, screenSlider still have instance.
How then I can check destroyed "screenSlider" or not.

**Comment by A11oW** [comment]
In result I do that:
<code>screenSlider.destroy(true, true);</code>
<code>screenSlider = undefined;</code>

**Comment by wgroenewold** [comment]
There is a callback you can trigger. If you put the following in your config-object it will warn you:

```
 onDestroy: function(){
console.log('swiper destroyed');
}

```

**Comment by nolimits4web** [comment]
@A11oW `delete Swiper instance` is clearing internal Swiper instance, but it can't clean your variable as well. So you did it correct by assigning `undefined` to your variable
