### ISSUE TITLE
Prevent tapping on swipe

### ISSUE THREAD

**Issue by rozv** [nolimits4web/Swiper#1368]
I'm using hammer.js with swiper and i have links inside slides that are triggered with the hammer tap event. On desktop when swiping, the links work as expected-- they dont get clicked when you swipe. But on ios the links are getting clicked when swiping the slide. Is there a way to stop that from happening? I only really need it to work for IOS. Thanks!

**Comment by nolimits4web** [comment]
By default they are also not triggered on mobile device when you swipe. So the issue with Hammer.js.

**Comment by nolimits4web** [comment]
Closing as not further response & discussion
