### ISSUE TITLE
In swiper 3.1.0 break loop.

### ISSUE THREAD

**Issue by A11oW** [nolimits4web/Swiper#1369]
in swiper 3.1.0 break loop.
After first loop slides don't changes
http://jsfiddle.net/A11oW/jjkrva8b/25/

**Comment by nolimits4web** [comment]
Be more descriptive. I can swipe to next slide without any problems

**Comment by A11oW** [comment]
I try swipe on mouse wheel. when i swiped last slide, than swiper slide only between last and first slides.
Windows 8.1
Chrome 43.0.2357.134 m

**Comment by nolimits4web** [comment]
Ok, wil check it
