### ISSUE TITLE
Absolute Center (Vertical & Horizontal) "Responsive" it does not work

### ISSUE THREAD

**Issue by unehub** [nolimits4web/Swiper#1372]
Hello,

I'm use Bootstrap 3.3.5 and demo **30-lazy-load-images**, The problem is that the container can not have a fixed height(px), it must be "100% or auto" for it to be compatible with the responsive design. 

Check this demo http://jsfiddle.net/9s75kkxp/3/

    .swiper-container {
        width: 100%;
        height: 500px; // Only work if star height eg 500px, but need this container responsive 100% or auto.
    }

![captura de pantalla 2015-07-21 a las 2 57 00 p m](https://cloud.githubusercontent.com/assets/12479371/8811092/08965690-2fb9-11e5-9d5b-88df75ee95eb.png)

If set height: 100% or auto, .swiper-container height not initialize "0". How can we solve this? the image must be centered like the lazy load

**Comment by nolimits4web** [comment]
Sorry, but this is how CSS works, your images have `absolute` position so they don't bring any height/size to parent elements. Use then another method for their centering. The same with `100%` height, this is how CSS works again, if you set such height then it will take 100% height of its parent, to make it work you need to set 100% height to all parent elements including `<body>` and `<html>`

**Comment by nolimits4web** [comment]
Closing as not further response and issue not actually related to Swiper
