### ISSUE TITLE
standard location hash bug

### ISSUE THREAD

**Issue by josiah47** [nolimits4web/Swiper#1374]
It works fine to scroll to the end, but if you try to scroll to the beginning it does not work.
http://pastebin.com/fmzNaDr2

**Comment by nolimits4web** [comment]
It should be obvious, set your hash BEFORE you init Swiper. Reopen issue if you still have problems with it

**Comment by josiah47** [comment]
No go. Same thing.
http://pastebin.com/E3FkhvCn
