### ISSUE TITLE
Multiple swipers but different size

### ISSUE THREAD

**Issue by alvipeo** [nolimits4web/Swiper#1375]
Great plugin, thanks!

But I need to have multiple swipers on a page with different sizes. For example, main swiper for main area and two others to show documents (reports and ... another reports :) ). Can I do that? Couldn't find anything except sample 24 with multiple swipers of the same size...

Thanks!

**Comment by nolimits4web** [comment]
Just set them different width and height in CSS for each slider. Closing as not the Swiper issue
