### ISSUE TITLE
Centered slide with visible adjacent slides

### ISSUE THREAD

**Issue by ernstoarllano** [nolimits4web/Swiper#1376]
I'm trying to create a slider with one centered slide and adjacent slides that are only about half the width of the centered one. It's similar to the [Slides Per View / Carousel Mode](http://www.idangero.us/swiper/demos/05-slides-per-view.html) demo, but I need the center one to be bigger than the adjacent slides. 

I was able to get the desired width and height of the centered slide with this bit of CSS: 

    .swiper-container {
        width: 920px;
        height: 455px;
    }

I'm also using this bit of JavaScript:

    var swiper = new Swiper('.swiper-cotnainer', {
       centeredSlides: true,
       slidesPerView: 'auto' 
    });

The issue I'm having though is that the adjacent slides aren't visible. Any way to get the slides on the left and right of the centered one to be visible?

**Comment by nolimits4web** [comment]
I don't see anything related to the size of slide width. You just need to add something like this to CSS:
```css
.swiper-slide {
  width: 70%;
}

**Comment by k25neo** [comment]
var swiper = new Swiper('.swiper-cotnainer', {
                slidesPerView: 'auto',
                centeredSlides: true,
                loop: true,
                slidesPerGroup: 1,
                paginationClickable: true,
                spaceBetween: 30
});
