### ISSUE TITLE
Hashnav: possibility to omit the hash in the changed URL

### ISSUE THREAD

**Issue by herrbischoff** [nolimits4web/Swiper#1377]
Is there a way to make the links appear as "proper" URLs?

Example:

    http://example.com/projects/number-one

instead of the current

    http://example.com/projects/#number-one

and make them change accordingly when navigating through the slides. Can this possibly be solved by rewriting URLs and slightly modifying the Swiper code? Any hints how to archive this are greatly appreciated.

According to https://stackoverflow.com/questions/15133023/hash-url-rewrite-in-htaccess this may not even be possible at all. But I thought I may ask for input anyway.

**Comment by nolimits4web** [comment]
You may look here http://www.idangero.us/swiper/forum/#!/questions:use-hash-url-navigation-ha

If you want to spend a lot of time for this, you also need to change this part in the core https://github.com/nolimits4web/Swiper/blob/master/src/js/hashnav.js to use push state https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history

**Comment by herrbischoff** [comment]
As this is not easily done, I'm going to close this.
