### ISSUE TITLE
Cant swipe next slide until i change device orientation

### ISSUE THREAD

**Issue by mladenp** [nolimits4web/Swiper#1382]
I am using Swiper with jQuery Mobile on Android and when i try to swipe to next slide it won't switch. Swipe gesture is detected and i can move slide a little but it wont switch to next slide.

But if i change device orientation in any way slider starts working correctly.

I am using jQuery mobile 1.4.5 and jQuery 2.1.4.

**Comment by nolimits4web** [comment]
Discussed many times here, issue with jQuery Mobile. Init Swiper when the page with it becomes visible, or call its `.update` method
