### ISSUE TITLE
Setting allowSwipeToPrev to false prevents slide from bouncing back

### ISSUE THREAD

**Issue by marfire** [nolimits4web/Swiper#1383]
Normally, when you don't swipe all the way the slide bounces back (for example, in the [basic demo](http://www.idangero.us/swiper/demos/01-default.html)).

When you set `allowSwipeToPrev` to `false`, the slide stops in it's partially slid position until it reaches the threshold and goes to the next slide. See [this fiddle](https://jsfiddle.net/at5hpj0g/), which is the exact same code as the demo except with this option.

This is unexpected and unattractive behavior that did not occur in Swiper 2.7.6.

**Comment by nolimits4web** [comment]
Fiddle is not working for me. Include swiper scripts and styles from CDN

**Comment by marfire** [comment]
OK, try [this one](https://jsfiddle.net/9wjrh8ub/1/).
