### ISSUE TITLE
Mousewheel sensitivity ?

### ISSUE THREAD

**Issue by darkyen** [nolimits4web/Swiper#1384]
Is there a way to control scroll sensitivity when using mouse wheel ?

http://chat.stackoverflow.com/transcript/message/24762321#24762321

I got immediate reviews that the mouse seems to janky

**Comment by nolimits4web** [comment]
There is no way at the moment to control it. Will add in future release

**Comment by darkyen** [comment]
I am rekt than :-x any internal guidance so i can monkey patch it maybe ?

**Comment by darkyen** [comment]
Thank you so much.
