### ISSUE TITLE
Z-index issue with tooltip plugin

### ISSUE THREAD

**Issue by RomLeg** [nolimits4web/Swiper#1385]
Hello,
First thanks for this very powerful plug-in!
I have an issue with the swiper when I add some tooltip effect (from bootstrap) on elements hover inside the slides.
I can see that the tooltip is well triggered in the HTML but it does not appear because it seems "behind"  the swiper. For exemple if I set the tooltip placement "below" it stays outside the div and does not appear, and despite putting a high z-index on these tooltip class in CSS
Thank you for your help!
Ara

**Comment by nolimits4web** [comment]
Sorry, i don't really understand how this issue is related to Swiper. The issue seems to be with just correct z-index flow in your layout or with tooltip plugin
