### ISSUE TITLE
mousewheelControl + loop issue

### ISSUE THREAD

**Issue by Landen13** [nolimits4web/Swiper#1390]
I have one slide per view, vertical mode, and:
{
mousewheelControl: true,
loop: true
}

Mousewheel can't scroll slides properly after the next cycle of scrolling start.

- when we get to the first slide after scrolling all slides (the next cycle of scrolling), mousewheel is able to slide once only to the previous slide (to the last slide of swiper);
- when mousewheel slides to the last slide (as above), it's able to scroll once only to the next slide (to the first slide of swiper);

I checked out this demo - http://www.idangero.us/swiper/demos/20-mousewheel-control.html
and there is the same issue (when loop is true).

How can it be fixed?
Thanks!

**Comment by nolimits4web** [comment]
It is already fixed in dev version

**Comment by Landen13** [comment]
@nolimits4web, where can I get it?
dev version = gulp build?

**Comment by nolimits4web** [comment]
> dev version = gulp build?

Yes
