### ISSUE TITLE
Cannot swipe to next slide

### ISSUE THREAD

**Issue by antonshevchenko** [nolimits4web/Swiper#1391]
For some reason, after adding all the slides into the `slider-wrapper` and instantiating a `new Swiper`, I cannot completely swipe to the next slide.

When I swipe, the slide starts moving and display part of the next slide, but I can never get it to complete the slide motion and move to the next slide.

**Comment by ngstwr** [comment]
Same issue here

**Comment by antonshevchenko** [comment]
A hacky way to fix it is to wrap the instantiation into a `setTimeout` of 0 seconds.

**Comment by ngstwr** [comment]
I am a beginner, not getting how to do it!
Is below code correct?

        window.setTimeout(function(){
            var mySwiper = new Swiper ('.swiper-container', {
                loop: true,
                autoplay: 3000,
                autoplayDisableOnInteraction: false
            });
        }, 100);

**Comment by antonshevchenko** [comment]
That should do it!

**Comment by ngstwr** [comment]
Thanks!

**Comment by nolimits4web** [comment]
It just means that you init Swiper when it was hidden (display:none). Init it when it is visible or call its `update` method when it becomes visible

**Comment by antonshevchenko** [comment]
It wasn't hidden.

I had the following in my markup:
```
[...]
<div class="slider-container">
    <div class="slide-wrapper">
    </div>
</div>
[...]
```
And I would load slides directly into the `.slider-wrapper` before instantiating the Swiper.

**Comment by ngstwr** [comment]
Neither was mine!

**Comment by nolimits4web** [comment]
If everything fine, then it should work fine as you may see on all demos. Something is definitely wrong with the moment of initialization
