### ISSUE TITLE
slideToClickedSlide not working when simulateTouch set to false

### ISSUE THREAD

**Issue by sparanoid** [nolimits4web/Swiper#1392]
Fromt this issue: https://github.com/nolimits4web/Swiper/issues/1281

Demo: http://jsfiddle.net/zfegpfjx/8/

**Comment by nolimits4web** [comment]
Sorry, but it is a touch-first slider and when you disable this option most of mouse events will not work. If you need it, enable back this option, or make it manually:
```
$('.swiper-slide').on('click', function (){
  mySwiper.swipeTo($(this).index())
});
