### ISSUE TITLE
Swiper with lazysizes

### ISSUE THREAD

**Issue by magic-77** [nolimits4web/Swiper#1395]
Hi to all,
is it possible to use Swiper with Farkas "lazysizes", to manage sourcesets?
Do somebody has experienced this, and can tell me how to?

**Comment by magic-77** [comment]
The answer for combining Swiper and lazysizes i found for myself:
http://stackoverflow.com/questions/31939023/swiper-3-with-lazysizes

But i´m still looking for a clever solution if "Autoplay" is on, and Images needs more time to load.
So slider will play, without waiting for loaded content.

**Comment by nolimits4web** [comment]
I am not familiar with this library but probably it has some events when image is loaded. So you need to check it in Swiper callbacks, just for example:
```
var swiper = new Swiper('...', {
  ...
  onSlideChange: function () {
    if ([imageNotLoaded]) swiper.stopAutoplay();
    else swiper.startAutoplay();
  }
});

**Comment by magic-77** [comment]
Hey, yes indeed, there is a not well documented "load" Event, which if fired after Image Element is ready. So i completed my solution for interrupting autoplay during loading event.
