### ISSUE TITLE
Click immediately after swipe will click the elements in the previous slide 

### ISSUE THREAD

**Issue by davidtlee** [nolimits4web/Swiper#1396]
If I:
1) swipe a slide manually by dragging,
2) then immediately click some space on the new slide before the transition has completed,

then the element on the previous slide (in the location I clicked) gets a click triggered on it.

I tried fixing it by adding an if statement checking for "swiper.animating", but it doesn't fix the problem.

Any suggestions?

**Comment by davidtlee** [comment]
I just tried the following fix:
1) inside onSlideChangeStart, I set swiperAnimating = true
2) inside onSlideChangeEnd, I set swiperAnimating = false

It seems to fix the previous problem (now the previous element doesn't get clicked), but the slide transition seems to get halted halfway and "onSlideChangeEnd" never gets triggered (the slide itself also is positioned slightly off centered in the place it got halted at)

Any suggestions? (either a different fix for the previous problem or a fix for this new problem). Thanks!

**Comment by nolimits4web** [comment]
It will be good to see how to replicate this bug or even better the JSFiddle with issue so i can take a look

**Comment by davidtlee** [comment]
sounds good, I'll make a JSFiddle. Do you have any other examples of swiper / angular JSFiddle's that I can use as a starter?

**Comment by nolimits4web** [comment]
Seems to be problem is not relevant any more. Reopen issue with example if you still have it
