### ISSUE TITLE
mousewheelControl + nested swiper

### ISSUE THREAD

**Issue by deesx** [nolimits4web/Swiper#1399]
I have a vertical swiper, which contains one nested horizontal swiper (default, one slide per view, no specific controls or options). The vertical swiper can be controlled by mousewheelControl

No matter what I try, the vertical swiper keeps sliding twice when mouse wheel occurs

If I disable the horizontal swiper  _and_ remove the divs wrapping up the nested swiper, the vertical swiper starts to behave correctly (the slides moves one after another, I don"t get the double/triple slide gap I was getting before for each mouse wheel event)

Haven't tried on others browsers; I 'm on safari OS X, with a trackpad

Thanks if any help on this problem

**Comment by wgroenewold** [comment]
Have you tried forcing the axis with mousewheelForceToAxis? You could workaround this problem by only enabling the mousewheel on hover of the right swiper (I've done it like that before).

**Comment by bbnnt** [comment]
could be done
in any case, going into things complexier than what's shown in examples seem to be a bad idea; it feels like the plugin gets weak

**Comment by wgroenewold** [comment]
@bbnnt If you think the plugin maybe you should contribute more ;)

That said changing mousewheel-behavior is always troublesome and will always be hacky. 

Glad I could be of help :)

**Comment by bbnnt** [comment]
I might try to yep !
damnit mousewheel

**Comment by Marc3llo** [comment]
I'm having a similar setup and the following problem:

* If `mousewheelForceToAxis`is enabled, in IE10 mousewheel won't work.
* If `mousewheelForceToAxis`is disabled, in all Browsers a horizontal scroll will always also trigger vertical
* Scrolling on Firefox is pretty over sensitive when I scroll with a trackpad / Magic Mouse, one "scroll-swipe" will always scroll to slides, which is super annoying to navigate.

**Comment by wgroenewold** [comment]
@Marc3llo You could wrap your mousewheelForceToAxis config in a IE10 excluding wrapper as a workaround.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
