### ISSUE TITLE
Swiper not working on ie8

### ISSUE THREAD

**Issue by LeoRegulus** [nolimits4web/Swiper#1400]
Hi guys i need your help.Swiper not working on ie8 i am using version 3.x
here is images not working and working two images 
sorry for bad english i hope you will understand.
![Not Working](http://i.imgur.com/l7WfXIp.png)
![Working](http://i.imgur.com/zEr4iTw.png)

**Comment by A11oW** [comment]
swiper don't support ie8

**Comment by LeoRegulus** [comment]
Thanks man i fix it with manual javascript code rewrite some code :)

**Comment by visualcookie** [comment]
Swiper 3.0 won't support IE7-IE9. Please update your browser because IE8 doesn't get any security updates.

http://www.idangero.us/swiper/forum/#!/general:sadly-v300-looks-not-to-b

**Comment by LeoRegulus** [comment]
Thanks dude i already using chrome but our clients want to ie8 compatible website so i am using 3.0 but for ie8-9 i wrote special code and fix it :) thanks your help have a nice day

**Comment by A11oW** [comment]
@LeoRegulus can you write what you change?

**Comment by LeoRegulus** [comment]
@A11oW actually i didnt change plugin i wrote slider again for ie8 and ie9 if you want you can take a look 
<pre>
function isIE() {
        var myNav = navigator.userAgent.toLowerCase();
        return (myNav.indexOf('msie') != -1) ? parseInt(myNav.split('msie')[1]) : false;
    }
    if (isIE() && isIE() < 10) {
        $(function () {
            var headerWraperWidth = $(".swiper-container-header").width() * $(".swiper-container-header .swiper-slide").length;
            $(".swiper-container-header .swiper-slide").width($(".swiper-container-header").width());
            $(".swiper-container-header .swiper-wrapper").width(headerWraperWidth);
            var headerSlides = 1;
            var headerTimer = setInterval(function () {
                headerSlides++;
                if (headerSlides > $(".swiper-container-header .swiper-slide").length) {
                    headerSlides = 1;
                    $(".swiper-container-header .swiper-wrapper").animate({
                        left: 0
                    });
                    return;
                }
                $(".swiper-container-header .swiper-wrapper").animate({
                    left: "-=" + $(".swiper-container-header .swiper-slide").width()
                });
            }, 5000);
            $(".swiper-container-ads.swiper-container .swiper-wrapper .swiper-slide").addClass("col-md-2");
            $(".swiper-container-ads.swiper-container .swiper-wrapper .swiper-slide.col-md-2").width(136.656);
            var bol = Math.ceil($(".swiper-container-ads.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length / 2) + 2;
            var dongu = Math.ceil($(".swiper-container-ads.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length / 6) / 2;
            $(".swiper-container-ads.swiper-container .swiper-wrapper .swiper-slide.col-md-2").eq(bol).css("clear", "both");
            $(".swiper-container-ads.swiper-container .swiper-wrapper").width($(".swiper-container-ads.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length * $(".swiper-container-ads.swiper-container .swiper-wrapper .swiper-slide.col-md-2").outerWidth());
            var i = 1;
            setInterval(function () {
                i++;
                if (i > dongu) {
                    $(".swiper-container-ads.swiper-container .swiper-wrapper").animate({
                        left: 0
                    });
                    i = 1;
                    return;
                }
                $(".swiper-container-ads.swiper-container .swiper-wrapper").animate({
                    left: "-=" + ($(".swiper-container-ads").width() + 20)
                });
            }, 3000);
            $(".swiper-button-next").click(function (e) {
                e.preventDefault();
                i++;
                if (i > dongu) {
                    $(".swiper-container-ads.swiper-container .swiper-wrapper").animate({
                        left: 0
                    });
                    i = 1;
                    return;
                }
                $(".swiper-container-ads.swiper-container .swiper-wrapper").animate({
                    left: "-=" + ($(".swiper-container-ads").width() + 20)
                });
            });
            $(".swiper-button-prev").click(function (e) {
                e.preventDefault();
                i--;
                if (i < 1) {
                    $(".swiper-container-ads.swiper-container .swiper-wrapper").animate({
                        left: 0
                    });
                    i = 1;
                    return;
                }
                $(".swiper-container-ads.swiper-container .swiper-wrapper").animate({
                    left: "+=" + ($(".swiper-container-ads").width() + 20)
                });
            });
            $(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide").css({
                "background": "#ccc",
                "text-align": "center",
                "padding": "10px 0",
                "min-height": "120px"
            });
            $(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide").addClass("col-md-2");
            $(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide.col-md-2").width(136.656);
            var bol = Math.ceil($(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length / 2) + 1;
            var donguk = Math.ceil($(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length / 3) / 2;
            $(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide.col-md-2").eq(bol).css("clear", "both");
            $(".swiper-container-td.swiper-container .swiper-wrapper").width($(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length * $(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide.col-md-2").outerWidth());
            var bullets = "";
            for (var iB = 0; iB < donguk; iB++) {

                bullets += "<span class='swiper-pagination-bullet'></span>";
            }
            $(".swiper-pagination-td").html(bullets);
            $(".swiper-pagination-td span").first().addClass("active");
            $(".swiper-pagination-td span").css({
                "cursor": "pointer"
            });

            var k = 1;

            function tdSlider() {
                k++;
                if (k > donguk) {
                    $(".swiper-container-td.swiper-container .swiper-wrapper").animate({
                        left: 0
                    });
                    k = 1;
                    return;
                }
                $(".swiper-container-td.swiper-container .swiper-wrapper").animate({
                    left: "-=" + ($(".swiper-container-td").width() + 20)
                });
            }
            var timer1 = setInterval(tdSlider, 3000);
            $(".swiper-pagination-td").hover(function () {
                clearInterval(timer1);
            }, function () {
                timer1 = setInterval(tdSlider, 3000);
            });
            $(".swiper-pagination-td-pub").hover(function () {
                clearInterval(timer1);
            }, function () {
                timer1 = setInterval(tdSlider, 3000);
            });
            $(".swiper-pagination-td span").click(function () {
                clearInterval(timer1);
                var eq = $(this).index();
                k = eq + 1;
                $(".swiper-container-td.swiper-container .swiper-wrapper").animate({
                    left: -($(".swiper-container-td").width() + 20) * eq
                });
            });




            $(".swiper-container-td-pub.swiper-container .swiper-wrapper .swiper-slide").css({
                "background": "#ccc",
                "text-align": "center",
                "padding": "10px 0",
                "min-height": "120px"
            });

            $(".swiper-container-td-pub.swiper-container .swiper-wrapper .swiper-slide").addClass("col-md-2");
            $(".swiper-container-td-pub.swiper-container .swiper-wrapper .swiper-slide.col-md-2").width(136.656);
            var bol = Math.ceil($(".swiper-container-td-pub.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length / 2) + 1;
            var donguj = Math.ceil($(".swiper-container-td.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length / 3) / 2;
            $(".swiper-container-td-pub.swiper-container .swiper-wrapper .swiper-slide.col-md-2").eq(bol).css("clear", "both");
            $(".swiper-container-td-pub.swiper-container .swiper-wrapper").width($(".swiper-container-td-pub.swiper-container .swiper-wrapper .swiper-slide.col-md-2").length * $(".swiper-container-td-pub.swiper-container .swiper-wrapper .swiper-slide.col-md-2").outerWidth());
            var bulletsJ = "";
            for (var iBj = 0; iBj < donguj; iBj++) {

                bulletsJ += "<span class='swiper-pagination-bullet'></span>";
            }
            $(".swiper-pagination-td-pub").html(bulletsJ);
            $(".swiper-pagination-td-pub span").first().addClass("active");
            $(".swiper-pagination-td-pub span").css({
                "cursor": "pointer"
            });
            var j = 1;
            $(".swiper-pagination-td-pub span").click(function () {
                var eq = $(this).index();
                j = eq;
                $(".swiper-container-td-pub.swiper-container .swiper-wrapper").animate({
                    left: -($(".swiper-container-td-pub").width() + 20) * eq
                });
            });
            function tdSliderPub() {
                j++;
                if (j > donguj) {
                    $(".swiper-container-td-pub.swiper-container .swiper-wrapper").animate({
                        left: 0
                    });
                    j = 1;
                    return;
                }
                $(".swiper-container-td-pub.swiper-container .swiper-wrapper").animate({
                    left: "-=" + ($(".swiper-container-td-pub").width() + 20)
                });
            }
            var timer = setInterval(tdSliderPub, 3000);
            $(".swiper-pagination-td-pub").hover(function () {
                clearInterval(timer);
            }, function () {
                timer = setInterval(tdSliderPub, 3000);
            });
            $(".swiper-pagination-td-pub span").click(function () {
                clearInterval(timer);
                var eq = $(this).index();
                j = eq + 1;
                $(".swiper-container-td-pub.swiper-container .swiper-wrapper").animate({
                    left: -($(".swiper-container-td-pub").width() + 20) * eq - 1
                });
            });
        });
    }</pre>

**Comment by nolimits4web** [comment]
Ok, thanks for the solution @LeoRegulus ! Anyway closing the issue, as it is not compatible with IE < 10
