### ISSUE TITLE
mouseWheel and slide animation

### ISSUE THREAD

**Issue by A11oW** [nolimits4web/Swiper#1401]
If fast turn mouse wheel in this [example](http://www.idangero.us/swiper/demos/20-mousewheel-control.html) then sometimes missing animation between slides

Windows 10 chrome 44.0.2403.155 m

**Comment by wgroenewold** [comment]
Same here on OSX.

**Comment by wgroenewold** [comment]
It seems to happen when you initate a new scroll before the old one has finished. The animation gets skipped when the onSlideChangeEnd hasn't triggered yet, it is really visible when you have a slow speed.

**Comment by nolimits4web** [comment]
This should be fixed now with skipping slides in dev version.
