### ISSUE TITLE
Issue with continous looping linear moving slider

### ISSUE THREAD

**Issue by OlePc** [nolimits4web/Swiper#1404]
Hi, 
I'm trying to achieve a simple continous looping linear moving slider, but at a seemingly random point of time, the slider starts acting up. By acting up I mean breaking the normal behavior, and the slides start moving back and forth really fast.

This is my code:
var instagramSlider = new Swiper('.swiper-container', {
                slidesPerView: 5,
                autoplay: 1,
                speed: 8000,
                loop: true,
                simulateTouch: false,
                autoplayDisableOnInteraction: false,
            });
And then i set "transition-timing-function: linear !important;" on the swiper-wrapper.

Could you perhaps add an example of how you would achieve a continous looping linear moving slider to the demo section? Thanks.

**Comment by nolimits4web** [comment]
This works for me, no autoplay should be used here:
```
var swiper = new Swiper('.swiper-container', {
    slidesPerView: 5,
    loop:true,
    speed: 10000

});
function infinite() {
    swiper.slideTo(swiper.slides.length);
    swiper.once('transitionEnd', function(){
        swiper.slideTo(swiper.params.slidesPerView, 0, false);
        setTimeout(function () {
            infinite();    
        }, 0);
    });
}
infinite();
```

**Comment by nolimits4web** [comment]
And this should be set too:

> "transition-timing-function: linear !important;" on the swiper-wrapper.

**Comment by OlePc** [comment]
Thanks a lot, that works really well. Only thing is, that my swiper-slides are all a tags, but I can't click them now. Do you know a solution for this? Thanks.

**Comment by nolimits4web** [comment]
Yes, because the Swiper is animating. You may try to disable `preventClicks` parameter in this case
