### ISSUE TITLE
TypeError: swiperV.slideTo is not a function error for vertical child slider.

### ISSUE THREAD

**Issue by tejasacquaintsoft** [nolimits4web/Swiper#1406]
I have created 2 sliders one is horizontal and one is vertical. I have added vertical slider inside the horizontal slider. But the slideTo() method is not working for the vertical slider. However slideTo() is working fine for the horizontal slider. Can you help me to sort out this issue?

I am getting TypeError: swiperV.slideTo is not a function error for vertical slider. The same is working fine for the horizontal parent slider. Vertical is child one..

Thanks,
Tejas

**Comment by tejasacquaintsoft** [comment]
Fiddle Link : http://jsfiddle.net/cbLeq3u4/

**Comment by nolimits4web** [comment]
Fiddle doesn't work. Include required scripts and styles so i can see this issue

**Comment by wgroenewold** [comment]
Looks like your taking the number for slideTo() directly from a data-element. Is it outputted as a string of a number? Try to parseInt() it before using it.

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
