### ISSUE TITLE
Swiper 2 - Fade effect manually

### ISSUE THREAD

**Issue by leandroncbrito** [nolimits4web/Swiper#1407]
Hi,

I can't update my swiper to version 3.x because of customizations in css that are in the production servers of my customers (it's a cms and they can change css classes). 
Is there a way to implement this effect easily? Maybe with callbacks

Thanks

**Comment by nolimits4web** [comment]
2.x branch is not supported anymore. You can check this old plugin https://github.com/nolimits4web/Swiper-Smooth-Progress
