### ISSUE TITLE
Not working on class 'swiper-slide' when use slider on Modal Bootstrap

### ISSUE THREAD

**Issue by giangmd** [nolimits4web/Swiper#1408]
Hi as same title. I try another and it not working slide when i call modal. BUT i resize window it working.
Can you help me fix this issue. Thanks

**Comment by nolimits4web** [comment]
It is issue with bootstrap. Call swiper's `.update` method when this modal becomes visible

**Comment by giangmd** [comment]
Hi
After the modal show i was add code but it until not working

$.getScript("/public/packages/swiper/swiper.min.js").done(function() {
		
		var mySwiper = new Swiper('.swiper-container', {
	        pagination: '.swiper-pagination',
	        paginationClickable: true,
	        nextButton: '.swiper-button-next',
	        prevButton: '.swiper-button-prev',
	        // Enable debugger
	        debugger: false
	    });
	    
		mySwiper.update();

	});

**Comment by nolimits4web** [comment]
It is hard to say what is not working like that. Will be good to see live example with issue

**Comment by giangmd** [comment]
Yes. It's for catch event show of Modal Bootstrap. It's working now.
That's cool. Thanks.

**Comment by 1Rhino** [comment]
I have the same issue. These codes fixed it for me. 
I think, Swiper not regconize swiper-slide before it shown. So we have to wait it for complete 'shown'
(Example on coffescript)
```coffeescript
$('body').on 'shown.bs.modal', '#bootstrap-modal-element', ->
  newSwiper = new Swiper('.swiper-container',
    slidesPerView: 'auto'
    ....
```

**Comment by giangmd** [comment]
@1Rhino
Yes, it's jquery event. we must recall them to work on all DOM when the page not reload.
Nice to meet you, brother!

**Comment by DecoGrafics** [comment]
this is how i fixed it:
`
//swiper 
		    window.swiper = new Swiper('.swiper-container', {
				nextButton: '.swiper-button-next',
				prevButton: '.swiper-button-prev',
				pagination: '.swiper-pagination',
				paginationType: 'progress'
			});
`
i am using it on material design.
i hope it will help. 
Cheers.

**Comment by ozgrozer** [comment]
And this is how I fixed.

```js
setTimeout(function() {

	var swiper = new Swiper(".swiper-container", {
		loop: true,
		autoplay: 10000,
		grabCursor: true,
		centeredSlides: true,
		paginationClickable: true,
		autoplayDisableOnInteraction: true
	});

}, 0);
```
