### ISSUE TITLE
FreeMode + click

### ISSUE THREAD

**Issue by A11oW** [nolimits4web/Swiper#1409]
When I drag swiper and then drag out it with momentum, then catch swiper before momentum end I can't click any buttons in swiper slide, even in pagination buttons. [example](http://www.idangero.us/swiper/demos/09-freemode.html)

**Comment by BeklievParviz** [comment]
:+1:

**Comment by nolimits4web** [comment]
What is OS/version? Can't really replicate it, would be good to see some example or video with that

**Comment by BeklievParviz** [comment]
ОС: Windows 10 x64.
Браузер: Google Chrome 45.
Теперь не могу воспроизвести :pensive:

Ах, вот, что я заметил. Позавчера, когда я открывал эту страницу была возможность остановить действие слайда путём простого клика левой кнопки мыши, а сейчас хоть кликай, хоть не кликай он не останавливается. Вы не обновляли за эти 2 дня библиотеку?
Потому что именно благодаря остановке слайдером этим простым кликом и происходила дальнейшая беда.

Т.е. крутите с правой стороны влево и не дождавшись окончания остановки просто кликаете на любую часть слайдера (но не на пагинацию) и действие останавливалось (а сейчас не останавливается), и нужно было просто нажать на какой-нибудь элемент пагинации - но эта (пагинация) переставала работать (кликалась, но не крутила слайдер).

**Comment by nolimits4web** [comment]
> была возможность остановить действие слайда путём простого клика левой кнопки мыши, а сейчас хоть кликай, хоть не кликай он не останавливается. Вы не обновляли за эти 2 дня библиотеку?

Нет, такого функционала не было, видимо какой-то баг с браузером

**Comment by BeklievParviz** [comment]
Ну, ладно тогда, воспроизвести мне не удалось...
Может у **A11oW** получится.
В принципе, думаю можно закрыть это - отметив, что воспроизвести не удалось.

**Comment by A11oW** [comment]
Извините, за молчание, был в отпуске. Ошибка у меня все еще воспроизводится.
ОС: Windows 10 x64.
Chrome Версия 45.0.2454.93 m

@BeklievParviz все верно написал. нужно схватить мышкой слайды, дернуть их влево(или вправо, если можно) потом не дожидаясь конца анимации прокрутки, поймать их мышью и отпустить. после этого не работает пагинация и вообще не срабатывают события на кнопки внутри слайдов. При этом если еще раз дернуть слайды и дать им проиграть анимацию до конца, то все опять начинает работать.

**Comment by A11oW** [comment]
Могу записать видео, если это поможет.

**Comment by BeklievParviz** [comment]
@A11oW, я почему-то теперь не могу остановить слайды путём простого клика.
Раньше они останавливались, а сейчас нет.
Попробуйте [обновить страницу без кеша в Chrome](https://yadi.sk/i/HG0uMlhijDWvy) `[Ctrl]+[F5]`.

![обновить страницу без кеша в Chrome](https://leto19d.storage.yandex.net/rdisk/1d1b7fb5a1265a336f6d92af4b8659907089c5328ee09f28c27c4b958fd92655/inf/V7s1oEiBvg3tP0KbppGfkvl1RFxJvBssoWZpRhdcuiI3FNZ1rWX2gYwdaI_IRle8K6p9G0wGCKhAGaQE3v8cDw==?uid=0&filename=2015-09-21%2012-53-29%20%D0%91%D1%8B%D1%81%D1%82%D1%80%D1%8B%D0%B5%20%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D1%88%D0%B8%20-%20C%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0%20-%20Chrome%20-%20Google%20Chrome.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=5345d1c0d928368031d3db20bdcf385b&force_default=no&ycrid=na-d10d108aef140760495c06ca73713671-downloader7g)

**Comment by A11oW** [comment]
@BeklievParviz  Кеш сбросил, но у меня все еще воспроизводится.

**Comment by A11oW** [comment]
Кстати а это не может быть из за того, что когда начинается анимация пролистывания, пагинация сразу ставится на тот пункт на котором анимация должна закончится? Когда я прерываю анимацию, возможно что то отрабатывает не так и все ломается.

**Comment by A11oW** [comment]
@BeklievParviz Попробуй кликнуть не на слайды, а на точки пагинации во время анимации. остановится ли она у тебя?

**Comment by BeklievParviz** [comment]
@A11oW, нет, не останавилваются.
Пробовал по-всякому - раньше останавливалось, а теперь никак не могу воспроизвести.

**Comment by A11oW** [comment]
Сейчас побегал по офису, на 2х компьютерах из 3х воспроизвелся баг. Причем воспроизвелся на windows 10 и 8.1 и не воспроизвелся на 10. Версии Chrome одинаковые, последние. Попробовал в Firefox не воспроизводится. Магия =)

**Comment by BeklievParviz** [comment]
@A11oW, в таком случае лучшее решение - записать видео, чтобы @nolimits4web смог увидеть.

**Comment by A11oW** [comment]
Думаю можно закрыть задачу, т.к. у меня перестало воспроизводиться.
