### ISSUE TITLE
v.wrapper.transition is not a function

### ISSUE THREAD

**Issue by iamhd** [nolimits4web/Swiper#1410]
Still it is not fixed on version 3.1.2

**Comment by iamhd** [comment]
But It is not happening when using non jquery version.
Please try to fix this issue and your slider will rocks.

**Comment by nolimits4web** [comment]
The issue is not in Slider. Please provide at least live example or JSFiddle with this issue

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
