### ISSUE TITLE
In ie10 mousewheelControl + mousewheelForceToAxis:true don't work

### ISSUE THREAD

**Issue by A11oW** [nolimits4web/Swiper#1411]
Mousewheel doesn't work in ie11 when you use params mousewheelControl + mousewheelForceToAxis equal true
```
    var swiper = new Swiper('.swiper-container', {
        direction: 'vertical',

        mousewheelControl: true,
        mousewheelForceToAxis: true,
    });
````
[example](http://jsfiddle.net/A11oW/n8s29sp9/2/)

in Edge work fine.

**Comment by wgroenewold** [comment]
Try ditching the last comma in your configuration. IE is known to choke on that in JS.

**Comment by A11oW** [comment]
This is not the solution =(

**Comment by nolimits4web** [comment]
IE < Edge don't support this
