### ISSUE TITLE
The preloading preloads the wrong image when srcset is used

### ISSUE THREAD

**Issue by callumacrae** [nolimits4web/Swiper#1413]
This just took me about six hours to track down, it is not a fun bug!

When image preloading is enabled (which it is by default), swiper blindly loads the image specified in the src attribute—that might not be the one actually being loaded, though.

I have since disabled this behaviour on the site I'm working on, but it would be good if it were fixed in Swiper itself—either by calculating the correct image to download, or by just not preloading the image if srcset is used.

**Comment by nolimits4web** [comment]
Will fix it, thanks

**Comment by callumacrae** [comment]
I can fix it if you don't have the time, I'm just not sure how I would go about doing it—I'm not too familiar with responsive images.

**Comment by nolimits4web** [comment]
If you can fix it before the weekend, then i don't mind about it. I am just not familiar with them as well :smile:

**Comment by callumacrae** [comment]
I'll add it to the todo list, but I'm not sure I'll have the time (especially as it's not actually affecting us anymore)

**Comment by magic-77** [comment]
Hi Guys, maybe this source can be helpful to work with Responsive Images - https://github.com/aFarkas/lazysizes
I´m using this with Swiper Slider to manage Sourcesets with Background Images.
But it´s an external Solution.

**Comment by codegaze** [comment]
I 've used swiper with responsive images and confirm the problem.
@magic-77 I 'm using lazysizes in my page but there is a small bug. If you have enabled the responsive version of swiper and have the lazysizes script the slider height is not correct until all the images are loaded. 
I need to check the integration of these two or get dirty with the swiper source code to see what's wrong and disable the lazysizes for the swiper images.

**Comment by magic-77** [comment]
@codegaz: Hi, i´m using Swiper as Fullscreen Responsive Slider. For me it works, without knowing the actual Height of the image.
Demo: http://www.holmvintage.com

**Comment by codegaze** [comment]
@magic-77 Hi! You are right, maybe I need to take another look to my css. Thanks!

**Comment by nolimits4web** [comment]
Should be fixed with https://github.com/nolimits4web/Swiper/commit/06e833ed97b50c854588778393c8e25e14640791
