### ISSUE TITLE
Use Canvas on Slide

### ISSUE THREAD

**Issue by Fanvaron** [nolimits4web/Swiper#1414]
Hi, 
I'm currently trying to put a canvas on my slides, but for the user to be able to draw on the canvas I need to get the touch events.
Since I found no way to make it so the canvas get the event instead of the slide, I now tried using the callbacks and the drawing works, but the slide moves with it.
I looked trough the code, but I found no way to cancel the original swiper event, is there no "preventDefault" when using callbacks?
Greetings
Fanvaron

**Comment by nolimits4web** [comment]
No, you can use stopPropagation for your custom events on canvas, like:
```
$('.swiper-slide canvas').on('touchstart touchmove touchend', function(e){
  e.stopPropagation();
});
```
This should make a trick and you can handle your custom events, not callbacks

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
