### ISSUE TITLE
Mousewheel control in IE9 3.1.2 

### ISSUE THREAD

**Issue by vkrol** [nolimits4web/Swiper#1415]
Hi!

In the last version of Swiper (3.1.2) the mousewheel control in IE9 has stopped working. I can go only to the second slide. Example: http://jsbin.com/finoquhaqa/edit?html,css,js,output

**Comment by nolimits4web** [comment]
Sorry, but IE9 is actually not supported, you can use 2.x branch for IE 9 support

**Comment by vkrol** [comment]
Thanks. But what about "Super basic support for IE 9 with swiper.jquery version" from changelog about 3.0.5 version?

**Comment by nolimits4web** [comment]
Mousewheel control is far from basic support (in my opinion :small_red_triangle_down:  ) You may Swiper 2.x if you need full IE 9 support
