### ISSUE TITLE
Flex-direction: column with horizontal multi-row view

### ISSUE THREAD

**Issue by Azuka** [nolimits4web/Swiper#1417]
I'm trying to display a group of slides:

1 5 9   13 17
2 6 10 14
3 7 11 15
4 8 12 16`

By setting the container's flex-direction to column. However, this seems to break the layout as I get something that looks like:

3 7  11 15 2
4 8  12 16
5 9  13 17
6 10 14 1

When I scroll left. Is there a way to order my items in column order?

**Comment by nolimits4web** [comment]
Do you have a live example/fiddle of this?

**Comment by nolimits4web** [comment]
And `flex-direction to column` is not supported for horizontal direction, maybe you are looking for `slidesPerColumnFill` parameter which accepts `'row'` or `'column'` values

**Comment by Azuka** [comment]
Seems the swiper.jquery.min.js handler is broken.

This Fiddle: https://jsfiddle.net/kto0p68j/ works,

But this doesn't: https://jsfiddle.net/kto0p68j/1/

**Comment by nolimits4web** [comment]
The problem with jQuery, use 2.x + version of jQuery
