### ISSUE TITLE
Is it possible to update effect after init?

### ISSUE THREAD

**Issue by ye4241** [nolimits4web/Swiper#1418]
When I try to change the params.effect of swiper, and call the swiper.update(true).
It will not update the effect from 'fade' to 'slide'?
Is there any way to change it without destroying and init anthor Swiper again?

init the swiper;
```javascript
    var swiper;
    swiper = new Swiper('.swiper-container', {
        direction: 'vertical',
        effect: 'fade',
        grabCursor: true,
        lazyLoading: true,
        lazyLoadingInPrevNext: true,
        mousewheelControl: true,
        keyboardControl: true,
    });
```

try to change the effect:
```javascript
    swiper.params.effect = 'slide';
    swiper.update(true);
```

**Comment by nolimits4web** [comment]
No, it is not possible as they use totally different logic and "layout". You can try to destroy it first with `.destroy(true, true)` and then to init it again with another effect
