### ISSUE TITLE
Feature request: Minimum velocity setting

### ISSUE THREAD

**Issue by niper1** [nolimits4web/Swiper#1420]
First: Thank you for a great tool! 
We ran in to a small issue when the swiper would animate in slowmotion when the swipe were too slow. We fixed this by changing the if statement: if (Math.abs(s.velocity) < 0.02) to if (Math.abs(s.velocity) < 0.13) inside s.onTouchEnd inside swiper.jquery.js in version 3.0.7. But we dont want to hack into the code and we think this should be a simple setting instead. 

If I'm being an idiot and there is a setting or some other way to change this just tell me. 

The settings we use are: 

      getSettings: function (numOfSlides, slidesPerView, initialSlide) {
         
         return {
            initialSlide: initialSlide || 0,
            loop: numOfSlides >= slidesPerView,
            loopAdditionalSlides: 30,
            freeMode: true,
            freeModeMomentumBounce: false,
            freeModeMomentumRatio: 0.35,
            freeModeSticky: true,
            slidesPerView: slidesPerView,
            centeredSlides: true,
            slideToClickedSlide: true,
            paginationClickable: true
         };
         
      },
      
      getSlidesPerView: function () {
         if  ($( window ).width() > '767' && $( window ).width() < '1025') {
            return 3;
         }
         return 5;
      },

**Comment by nolimits4web** [comment]
Ok, will consider it for next release
