### ISSUE TITLE
Not responsive in loop mode

### ISSUE THREAD

**Issue by jayss** [nolimits4web/Swiper#1421]
There is a display bug after rotating when useing loop mode
![screenshot from 2015-09-03 15 03 52](https://cloud.githubusercontent.com/assets/4995023/9652372/3fd7535a-524d-11e5-83b0-76f891a00adf.png)

**Comment by nolimits4web** [comment]
This tells about nothing, it is responsive. Will be good to see live example or at least JS Fiddle with issue

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
