### ISSUE TITLE
If loop = true is set then events such as onSlideChangeStart and onTransitionEnd etc are fired automatically on page load

### ISSUE THREAD

**Issue by mirafreshface** [nolimits4web/Swiper#1426]
Hi!

If loop = true is set, then events such as onSlideChangeStart and onTransitionEnd etc are fired after the page loads without any user interaction. If I set loop = false then these events don't fire.

Is this a correct/normal behavior?

I would prefer them not to fire btw.

Thank you.

**Comment by nolimits4web** [comment]
You can disable `runCallbacksOnInit` parameter to disable it

**Comment by mirafreshface** [comment]
Can't believe I missed that in the API docs, thank you so much for your help Vladimir. Swiper is great :)

**Comment by tomasdev** [comment]
I have configured `runCallbacksOnInit: false` but `loop: true` and events fire anyway 👎
