### ISSUE TITLE
roundLengths = true, slideChangeEnd event not fired on certain screen sizes

### ISSUE THREAD

**Issue by veke** [nolimits4web/Swiper#1427]
If you set window size to example 638px and run the fiddle again, slideChangeEnd is not firing.
http://jsfiddle.net/6h473zgh/6/

If you set roundLengths to false and run fiddle again it's working.

**Comment by nolimits4web** [comment]
I guess this should be fixed with this PR #1419

**Comment by nolimits4web** [comment]
Closing as should be fixed
