### ISSUE TITLE
DoubleClick on swiper-button-next or swiper-button-prev

### ISSUE THREAD

**Issue by williesmithchen** [nolimits4web/Swiper#1428]
if DoubleClick on swiper-button-next or swiper-button-prev will be error.
display like this 
![image](https://cloud.githubusercontent.com/assets/4962190/9716389/a7efe8ca-559b-11e5-8da3-9dd6ad6523f3.png)

**Comment by nolimits4web** [comment]
Sorry, can't replicate it. Any more information on this, at least OS version, browser version. Have you tried it in other browsers?

**Comment by nolimits4web** [comment]
Closing as no further response/discussion

**Comment by anorudes** [comment]
+1 i have some problem
video: 
https://monosnap.com/file/P0qrIf6AF9IrZbYdH6N3AKWTarANyi

**Comment by HADB** [comment]
+1 I have the same.

It happens when the next button is clicked while the last animation is not finished.

**Comment by ailet37** [comment]
+1 i have the same problem. 
it happens only in Chrome, version 51.0.2704.103 m, os windows 7.
example: riapanda.ru
