### ISSUE TITLE
Compatibility question.

### ISSUE THREAD

**Issue by Sanderha** [nolimits4web/Swiper#1429]
I cant seem to find any post on how well this (awesome) plugin works on ie9?

**Comment by nolimits4web** [comment]
Don't expect much from IE9 support here. If you need IE 9 support you may use Swiper 2.x branch

**Comment by Sanderha** [comment]
Thanks. Yeah I ended up just having no slideshow on ie9, instead just showing the first slide.

**Comment by julmot** [comment]
A official list of compatible browser would be very much appreciated.

**Comment by wgroenewold** [comment]
A list of which features in a browser are used would be better. Testing against browsers is not a solid style.

**Comment by nolimits4web** [comment]
This features should be supported for full Swiper support: CSS Flexbox, CSS 3D Transforms, CSS Transitions, JS `classList`
