### ISSUE TITLE
Hashnav links between slides on the same page/back button?

### ISSUE THREAD

**Issue by mothunter** [nolimits4web/Swiper#1430]
Hi,

I don't know if this is specifically an issue of functionality but it's not doing something I would like it to do. Hopefully this post is allowed here.

I am working on a site here: http://mbeach.me/arch/

On the test page there are two swipers that are linked and the first slide links via hashnav to other slides within the swipers. When the links are clicked nothing happens. Similarly the slides do not change upon clicking the back or forward button in browser.

I have not seen any posts regarding hashnav links within swipers but I think the back button issue can be accomplished according to this previous issue here: https://github.com/nolimits4web/Swiper/issues/1178

Unfortunately I am not proficient enough to figure either of these out by writing my own code. Has anyone achieved a similar set up and willing to share code? Or are these tasks relatively easy to accomplish and could someone point me in the right direction?

**Comment by nolimits4web** [comment]
Sorry, hashnav only changes browser hash when you change slide. But it will not handle such links. You should do it manually using `.slideTo` method. There are a lot of solutions for this in forum
