### ISSUE TITLE
Up / down arrows as well as left / right arrows?

### ISSUE THREAD

**Issue by drawcard** [nolimits4web/Swiper#1432]
Hi, am I missing something - I am trying to find a style that allows you to show up / down arrows for cases where vertical scrolling / pagination is used. The left / right arrows work fine for horizontal mode but seem to be counter intuitive for paging up & down. It would be great if the up / down arrows were centrally positioned at the top / bottom of the page as well.

**Comment by nolimits4web** [comment]
I didn't add such arrows because i don't see much sense in such arrows. But you can do it easily by just adjusting arrows styles http://www.idangero.us/swiper/forum/#!/general:vertical-arrow-display-rath
