### ISSUE TITLE
Slider not working in FireFox and no errors in console

### ISSUE THREAD

**Issue by JRM93** [nolimits4web/Swiper#1433]
We have made a slider in various browsers it is working but in firefox the slides are not displaying. Can someone help me?

http://bit.ly/1NpwazA (not displaying link for google reasons)

**Comment by wgroenewold** [comment]
Previous there were some issues with empty slides. Try adding a &nbsp; to see if that works. Helped me out before.

**Comment by JRM93** [comment]
@wgroenewold already tried that, the slider contains 4 slides as we speak and is still not working.

**Comment by wgroenewold** [comment]
Ah, I see github removed my code example :/

Try a:

```
&nbsp;
```

inside your slide-element

**Comment by JRM93** [comment]
@wgroenewold i have places a &nbsp; in the slide element. It now shows a bit more, i have tried more &nbsp; in the element but that does not solve the problem.

**Comment by nolimits4web** [comment]
@JRM93 you should specify height for you slides and swiper-container

**Comment by JRM93** [comment]
@nolimits4web and in chrome, IE and safarai this is done automatically?

**Comment by nolimits4web** [comment]
@JRM93 No, you should specify it in CSS

**Comment by nolimits4web** [comment]
your swiper container doesn't have specified height, until you really well understand how `height: 100%` works in browser

**Comment by JRM93** [comment]
@nolimits4web now specified the container. would expect same in different browsers now a days.

**Comment by nolimits4web** [comment]
@JRM93 this is a question to browser vendor, unfortunately you still can't expect the same in different browsers nowadays ;)

**Comment by DTails** [comment]
@JRM93 I took a look at your website and it seems to be working fine in Firefox. Could you let us know how you did it in the end?

**Comment by shafeeqbsse** [comment]
this works for me 
`.swiper-wrapper {
    display: flex;
}`
and 
`.swiper-slide {
    display: table;
}`
