### ISSUE TITLE
Firefox scroll issue in freemode.

### ISSUE THREAD

**Issue by asimkt** [nolimits4web/Swiper#1434]
When freemode is enabled scrolling is hard. 

Please check the codepen in FF.
http://codepen.io/asim-coder/pen/NGGxKa

Chrome (Version 43.0.2357.81 (64-bit)) - good
FireFox (38.0) - Scrolling is not smooth. Pixels scrolled per event is low.
Other Browsers - Not tested.

**Comment by nolimits4web** [comment]
What is your OS? Do you see the same behavior at http://www.idangero.us/swiper/demos/32-scroll-container.html? As for me both Chrome and FF are smooth

**Comment by asimkt** [comment]
Ubuntu 14.04. 

I see the same behavior  at the link too. Looks like pixels scrolled per mouse event is like 5px.

**Comment by asimkt** [comment]
Please check the video for more information.
http://youtu.be/mujhswpmqu8
-or-
https://drive.google.com/file/d/0B2zWMerQcAOkT0dWQmNtazk2S0E/view?usp=drivesdk

Note: Touch slide is OK in FF. Only mouse scroll having the issue.

**Comment by nolimits4web** [comment]
Sorry, Swiper doesn't make scrolling "smoother", it is just scroll content on the value received by scroll event. So in your case is more system+browser issue. You can try to tweak this behavior using `mousewheelSensitivity ` parameter

**Comment by asimkt** [comment]
Thanks for your help.

**Comment by asimkt** [comment]
Thanks for your help. Sorry for the word 'smooth'. I would say different behavior in Ubuntu FF. Let me try `mousewheelSensitivity` param.

**Comment by asimkt** [comment]
Hi,

I have tested on OS X Yosemite. Firefox version: 39
Scrolling is good, even though chrome has moved more content per event.

And Windows 7, Firefox version 40
scrolling is same as  Ubuntu.

just for your information.

**Comment by asimkt** [comment]
Hi, after some digging I found that the delta value getting from the 'wheel' event (mousewheel.js: line number: 47 - 61) is '3' in Firefox where chrome is giving '120' from the event. This small delta value was causing this problem. So I normalized it using:
```javascript
if(Math.abs(delta) < 50){
  delta > 0 ? (delta = delta + 120) : (delta = delta - 120);
}
```
when freeMode is enabled. Is this okay?

**Comment by icek** [comment]
I have the same issue. After some digging i found this question and this answer: http://stackoverflow.com/a/30134826

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
