### ISSUE TITLE
Provide example for vertical 'Auto Slides Per View / Carousel Mode'

### ISSUE THREAD

**Issue by AW-UC** [nolimits4web/Swiper#1435]
Could you please add an example for a vertical version of [Auto Slides Per View / Carousel Mode](http://www.idangero.us/swiper/demos/06-slides-per-view-auto.html)?
I'd like to show the swiper slides in a container of a fixed height. It is supposed to include several slides of **different** heights. There should also be a pagination element with one knob per slide.
So far, I haven't been able to achieve this. Either the swiper container took the height of the largest slide, showing only one slide per view despite setting `slidesPerView: 'auto'`.  Or if setting the container to `height: 100%` the pagination doesn't work as expected.

**Comment by nolimits4web** [comment]
Will be good to see on live example or at least JS Fiddle of what you have tried so far

**Comment by AW-UC** [comment]
Nevermind. I messed up. I just found out, that setting `.swiper-slide` to `height: auto;` does the trick for me. Anyway, thanks a lot!
