### ISSUE TITLE
Не работают опции 'loopAdditionalSlides' и 'loopedSlides'

### ISSUE THREAD

**Issue by BeklievParviz** [nolimits4web/Swiper#1436]
> If you don't know Russian language - please, translate it with [Google Translator](https://translate.google.com).

Владимир, или я и ещё один разработчик неверно читаем документацию, или эти опции не работают...

Полный js-код, который использую:

``` javascript
    new Swiper ('#swiper-2-2', {
      loop: true,
      loopAdditionalSlides: 5,
      loopedSlides: 5,
      centeredSlides: true,
      slidesPerView: 'auto',
      spaceBetween: 20,
      pagination: '.swiper-pagination',
      paginationClickable: true
    });
```

[Пример на jsfiddle.net](http://fiddle.jshell.net/BeklievParviz/10o34any/68/show/light/) - прокрутите к bootstrap-алерту с содержимым "Не работают опции 'loopAdditionalSlides' и 'loopedSlides'..."

**[Исходник на jsfiddle](http://jsfiddle.net/BeklievParviz/10o34any/68/)**

[Скриншот](https://yadi.sk/i/CdI5U2ZEj2XXc)

**Comment by nolimits4web** [comment]
Общее количество "дублированных" слайдов (`loopedSlides`) не может быть больше чем общее количество слайдов, в вашем случае это не больше `2`, соответственно не больше 2-х дублированных слайдов с каждой стороны

**Comment by BeklievParviz** [comment]
А как можно решить эту проблему?
Есть ли другой способ?

**Comment by nolimits4web** [comment]
В данный момент есть варианта 2:

* увеличить количество слайдов
* или вручную продублировать их на нужное количетсво

**Comment by BeklievParviz** [comment]
Проблема в том, что есть разные разрешения экранов и придётся вычислять ширину экрана и ширину слайда и смотря на эти данные добавлять слайды для полного заполнения....

Просто, такое может произойти не только у меня, но и у других людей.

А что если сделать такой функционал в библиотеке?
И назвать опцию `loopCondition`.

**Comment by BeklievParviz** [comment]
> Общее количество "дублированных" слайдов (loopedSlides) не может быть больше чем общее количество слайдов,

Кстати, стоит добавить это в документацию.

**Comment by BeklievParviz** [comment]
> Проблема в том, что есть разные разрешения экранов и придётся вычислять ширину экрана и ширину слайда и смотря на эти данные добавлять слайды для полного заполнения....

> Просто, такое может произойти не только у меня, но и у других людей.

> А что если сделать такой функционал в библиотеке?
И назвать опцию loopCondition.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
