### ISSUE TITLE
Stop Swiper carousel from dragging the first / last slider 

### ISSUE THREAD

**Issue by heavenchains** [nolimits4web/Swiper#1437]
I am having a vertical swiper slider I just want it to stop dragging the first slide and the last slide in my mobile application its like when your in the first slide and you pull down it pulls down with you however it's splash screen so it doesn't look ver well so if there is a way to keep the animation between the slides but only control this issue would be great.

2. in this vertical slider I am having content that exceeds the height of any mobile phone so I was wondering if there is a way to make it scroll and and swipe without losing any of these 2 important methods.

thanks :)

**Comment by nolimits4web** [comment]
There is a `resistanceRatio` for this, which you can set to `resistanceRatio: 0`
