### ISSUE TITLE
Как получить доступ к API извне?

### ISSUE THREAD

**Issue by BeklievParviz** [nolimits4web/Swiper#1438]
> If you don't know Russian language - please, translate it with [Google Translator](https://translate.google.com).

Проблема очень простая.
Долго искал и не нашёл ответа на мой вопрос.

У меня на странице есть несколько каруселей, да и на сайте их очень много.
И чтобы было легче их инициализировать с необходимыми опциями - я создал функцию.

Выглядит она таким образом:
```javascript
function initCarousel($selector, options, callback) {
  $selector = $selector || $('.cards');
  options = options || {};
  callback = callback || function () {};

  $('.swiper-container', $selector).each(function () {
    var $carousel = $(this);

    var carouselAPI = new Swiper($carousel, {
      autoplay: options.autoplay || false,
      
      loop: options.loop !== false, //по-умолчанию true
      centeredSlides: options.centeredSlides !== false, //по-умолчанию true

      slidesPerView: options.slidesPerView || 'auto',
      spaceBetween: options.spaceBetween || 0,
      
      pagination: options.pagination || '.swiper-pagination',
      paginationClickable: options.paginationClickable !== false, //по-умолчанию true

      onInit: callback
    });
  });
}
```

**Что у меня есть:** лендинг с прокруткой всего экрана; сейчас я использую [fullPage.js](http://alvarotrigo.com/fullPage/), но оказывается и на Swiper можно постраничную карусель сделать, но на переделку нет времени, да и вопрос не в этом.
**Что мне нужно:** при переходе на экран с каруселью - запустить автопрокрутку; при уходе с этого экрана - отключить автопрокрутку.
**Вопрос:** как это сделать? Как получить доступ к API извне?

--
У карусели [owlCarousel](https://github.com/OwlFonk/OwlCarousel) есть возможность получить доступ к API извне следующим образом:
```javascript
var owl = $(".owl-carousel").data('owlCarousel');
owl.play() // Autoplay
owl.stop() // Autoplay stop
```

Есть ли в вашей библиотеке подобная возможность получения API?

**Comment by nolimits4web** [comment]
В самом конце страницы http://www.idangero.us/swiper/api/#access . Доступ есть через свойство `swiper` у `HTMLElement`'а:
```
$('.swiper-container').swiper(...);
var swiper = $('.swiper-container')[0].swiper;

**Comment by BeklievParviz** [comment]
Как же я не досчитал до конца...
Огромное спасибо, Владимир!

**Comment by BeklievParviz** [comment]
Как вы смотрите на то, чтобы добавить этот абзац/строки после первого упоминания доступа к API?
