### ISSUE TITLE
Nested Swipers slideChangeEnd program

### ISSUE THREAD

**Issue by guoruiruiguo** [nolimits4web/Swiper#1439]
I use Nested Swipers like http://www.idangero.us/swiper/demos/11-nested.html
Horizontal Slide trigger the Vertical Slide's callback method slideChangeEnd.

**Comment by nolimits4web** [comment]
What is your issue?

**Comment by guoruiruiguo** [comment]
Thanks,i had solved my progrom.I used the method 'slideTo',but not set the runCallbacks to false...
