### ISSUE TITLE
Swiper.slideTo() does not trigger progress ! 

### ISSUE THREAD

**Issue by teejayhh** [nolimits4web/Swiper#1440]
just a quick question, the slideTo method does not trigger the progress ticks it seems it only applies 1 or 0 which is a little annoying after I have trimmed my animations to work with the progress update.

Maybe I miss something.

Cheers Thomas

**Comment by nolimits4web** [comment]
Sorry, that is how CSS transitions work, they don't really have middle state. It was discussed here how to handle such cases, try to use search through issues

**Comment by guillaumebaeriswyl** [comment]
did you find any answer about this problem ? 
thank you
