### ISSUE TITLE
official website api list is incomplete

### ISSUE THREAD

**Issue by guoruiruiguo** [nolimits4web/Swiper#1441]
I found official website api list is incomplete,the url is http://www.idangero.us/swiper/api/.
For example,i use the method destory,but don't know how to reinitialize.
Now,i found there is a method called init,it's worked,but i don't know if this is the right way.

**Comment by nolimits4web** [comment]
`init` is internal method, if you need to reint swiper after destory, just init it again using `new Swiper(...)`
