### ISSUE TITLE
Gallery thumbnail sliding vertically?

### ISSUE THREAD

**Issue by undfnd** [nolimits4web/Swiper#1443]
Is there a posibility to position the thumbnails vertically?

http://screencast.com/t/e84jm5gbRZo

Thank you!

**Comment by nolimits4web** [comment]
Yes, it is possible, use `direction:'vertical'` for thumbs swiper

**Comment by undfnd** [comment]
Hey, thank you for responding.

I've just tried but the  thumbs aren't clickable and i cannot drag them to change the slide.. Is there a way to make them static position and to be only clickable?

Thank you again!

**Comment by sasoriza** [comment]
You will have to include `centeredSlides: true` for the thumbs swiper to fix non clickable and draggable thumbs
