### ISSUE TITLE
Track interslide progress ?

### ISSUE THREAD

**Issue by darkyen** [nolimits4web/Swiper#1444]
Is there any way to track when I am going from slide A to slide B ? Optimally a value -1 to 1 where -1 is previous slide completely and 1 is the next slide completely ? Like an offset from the current position

**Comment by nolimits4web** [comment]
Each slide HTMLElement has `progress` property that does what you ask:
```
var swiper = new Swiper('...', {
    watchSlidesProgress: true,
    onTouchMove: function(s){
        console.log(s.slides[0].progress); //first slide progress/offset
    }
});
