### ISSUE TITLE
Slides sometimes aren't animated if slide is changed via pagination

### ISSUE THREAD

**Issue by derz** [nolimits4web/Swiper#1446]
In Chrome (tested on v45 on OSX) the slides are sometimes not animated, if I jump to a slide with the pagination bullets. This happens because the transition-duration on .swiper-wrapper is set to 0 before the transition has ended.

		s.onTransitionEnd = function (runCallbacks) {
			s.animating = false;
			s.setWrapperTransition(0); // here's the error

As a quickfix I just removed the mentioned line, however I'm not sure, if there are any side effects on that one. It also happens on the official demo http://www.idangero.us/swiper/demos/#.VgD5JSDtlBd

**Comment by nolimits4web** [comment]
> This happens because the transition-duration on .swiper-wrapper is set to 0 BEFORE the transition has ended

No, this method is called inside `transitionEnd` event which is (supposed to be) called AFTER transition completed. It is a known Chrome + Windows only issue. Don't know workaround yet

**Comment by nolimits4web** [comment]
I think we can close it as there is no further discussion
