### ISSUE TITLE
Transition leap in loop mode with slideToClickedSlide

### ISSUE THREAD

**Issue by Liadel** [nolimits4web/Swiper#1448]
I've got an issue using loop mode and slideToClickedSlide: after several clicks on the slide transition to the next slide is broken up and swiper jumps several slides forward (or backward).

Sample code: http://jsfiddle.net/gja1j2jh/4/

Preconditions:
1) loop: true
2) slideToClickedSlide: true
3) slidesPerView > 1

Scenario: click on the left most slide in the view. After several clicks swiper  rewinds several slides.

See the gif (actually on the gif the issue is not clear but at least it's clear what to do in order to reproduce it :-)):
![recording1](https://cloud.githubusercontent.com/assets/5438540/10125143/c12300ac-6572-11e5-83a2-c0f456e54529.gif)

**Comment by Liadel** [comment]
Unfortunatly issue is not fixed in new build
Please see example with the new version
http://jsfiddle.net/gja1j2jh/6/

**Comment by nolimits4web** [comment]
reopened

**Comment by Yukiioz** [comment]
Hello,
I have a bug like this one, and unfortunatly the issue is not totally fixed in the last build.
Exemple : 
http://codepen.io/yukiioz/pen/VeYBvp

To see the bug just click on the down slide several times.
