### ISSUE TITLE
why did you make jQuery a dependency?

### ISSUE THREAD

**Issue by shlomiassaf** [nolimits4web/Swiper#1449]
Hi,

Old swiper (2.7.6) didn`t have jQuery as a dependency.

I just saw that jQuery is now a dependency (From 3.x.x+).

I guess you thought about it and decided to add it, what was the reason?

It now forces the developer to adopt jQuery, event if he does not use it... useless payload..

**Comment by nolimits4web** [comment]
Why have you decided that jQuery is dependency now?

**Comment by shlomiassaf** [comment]
see https://github.com/nolimits4web/Swiper/blob/master/package.json#L44

jQuery is a dependency, implied anyway...

**Comment by nolimits4web** [comment]
This shouldn't be here, came from another commit, will remove it
