### ISSUE TITLE
Parameter for disabling rerender of swiper pagination

### ISSUE THREAD

**Issue by limpock** [nolimits4web/Swiper#1454]
An Attribut like:
…
disablePaginationRerender: true,
…
is missing.
I worked on a website where i had to write my on pagination because of the .onResize bahavior of the swiper.
It seems that swiper is rerendering the pagination onResize() everytime. This causes my javascript positioning to fail.
I've added the same positioning calculation to my swipers .onResize like this:
myswiper.onResize(function(){
calculatemystuff();
});
That did not work. I assume there is a timing problem between .onResize() and the rerendering of the pagination.
Thats what Google told me:
stackoverflow.com/…/ation-and-ios-resize-issues
Its the same problem. Just with ovewritten classes and not style attributes.
It would be very nice if you guys could add the parameter.
I love the swiper and use it quiete often. Nice work! Keep it up!

**Comment by nolimits4web** [comment]
In this case just disable pagination at all, and use custom one where you can just assign `.slideTo` method to each pager bullet click, and it won't be breaked by Swiper. Pagination rerendering is required as it can contain different amount of bullets depending on window size.

Or you can use `paginationBulletRender` parameter to render pagination with required inline styles

**Comment by nolimits4web** [comment]
I think we can close it as there is no further discussion
