### ISSUE TITLE
If window is resized while swiper is in the background, slide positions occasionally scatter around

### ISSUE THREAD

**Issue by Jiia** [nolimits4web/Swiper#1457]
To reproduce, create a swiper with these settings and add multiple slides:

speed: 850, 
autoplay: 3000,
loop: true,
slidesPerView: 1,
simulateTouch: false,
direction: "horizontal",
effect: "fade",
fade: { crossfade: false }

1. Open the page where the swiper is
2. Open a new tab and leave the other page in the background
3. Resize the window horizontally.
4. Go back to the swiper tab
5. Slides scatter around and go next to each other even though they should be on top of each other.
(You might need to repeat the resizing part multiple times as the bug won't always trigger. I guess it only happens while slide change is happening in the background)

One workaround:
Add event listener for window focusin, call destroy(true, true) and reinit slider if the window width has changed. The downside is that this resets the swiper position.

I'm also investigating if it still happend if you stop autoplay while swiper is in the background.

Example of scattered slides. Only one slide should be visible at a time:
![swiper](https://cloud.githubusercontent.com/assets/5290053/10277777/06f1fe8c-6b61-11e5-8039-4c7abfc135bf.PNG)

Reproduced on multiple sites with multiple settings and multiple browsers.

**Comment by nolimits4web** [comment]
It is a browser issue/designed behavior. Because it slows down/ignores timeouts. Look at the forum, there were few solutions for that
