### ISSUE TITLE
Multicolumn slider behaves strange with few slides

### ISSUE THREAD

**Issue by Souldrinker** [nolimits4web/Swiper#1458]
I want to have a swiper with 3x3 slides per page with slidesPerColumnFill="row".

I'm testing based on your multirow demo, but with the following settings:
```
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        slidesPerView: 3,
        slidesPerColumn: 3,
	slidesPerColumnFill: 'row',
        paginationClickable: true,
        spaceBetween: 30
    });
```

This seems to work ok with many slides (>6), but if I for example have four slides I would expect the first line to have three slides and the second row to have one slide, but instead I get two columns with two rows.

Is this intended behavior? And if so is there a way to get it the way I want?

If I manually increase the width on the swiper-wrapper element in the browser the third one jumps up to the first line similar to what I want, but then third element has a larger top margin as if it was still on the second row.

**Comment by Souldrinker** [comment]
Well, after looking further into this it seems like it doesn't handle multirow at all how we expect it even for more slides with slidesPerColumnFill: 'row'. That is with the above setup and 10 slides the result will be that the first view will contain item 1,2 and 3 on the first line and the second line item 7, 8 and 9 while item 4, 5,  6 and 10 is on the second view not visible to the user.

We would have expected the first view to contain slides 1 to 9 and the second slide 10.

So our approach will probably instead be to use slidesPerView: 1 and no slidesPerColumn and write code ourselves to populate each slide with an array of up to 9 "views" which seems to work fine when we test.

**Comment by nolimits4web** [comment]
As for this part 

> This seems to work ok with many slides (>6), but if I for example have four slides I would expect the first line to have three slides and the second row to have one slide, but instead I get two columns with two rows.

I can agree, see the issue, will check it

But for this part :
> That is with the above setup and 10 slides the result will be that the first view will contain item 1,2 and 3 on the first line and the second line item 7, 8 and 9 while item 4, 5, 6 and 10 is on the second view not visible to the user.

It is designed/expected behavior, if you need to have views that contain slides 1-9, 10-18, etc, then such approach won't work and just manually put 9 "slides/blocks" into single slide with appropriate styling/position

**Comment by Souldrinker** [comment]
Regarding the second part, yes, we realized that yesterday after looking into how the swiper worked where it's a wide element with parts of it visible at the time. So I understand that making it behave as I wanted would probably mean rewriting pretty much the whole thing.

But since I also want it responsive (change number of visible columns when the window shrinks etc.) I would anyway need media queries and javascript code to change slidesPerView etc. so the approach we've started with and you suggest with putting several of our "blocks" into each slide will make it work as we want.

So rather than expect the swiper to sort stuff the way we want and change slider properties in the media queries we could just as well recalculate an array of "block"-arrays in those media queries and bind to that in the html to get our wanted behavior, and then we don't really need the first issue with few slides fixed either since we won't be using the multirow stuff in the swiper.

So if you want to look into that issue you could do that, but for us it's not necessary and maybe since the sorting isn't designed as we initially thought, maybe the behavior of the first issue is also expected/by design?

**Comment by nolimits4web** [comment]
> maybe the behavior of the first issue is also expected/by design?

No, it shouldn't behave like that. I will check it
