### ISSUE TITLE
Adjust slider size to each image width

### ISSUE THREAD

**Issue by brunovila** [nolimits4web/Swiper#1459]
How can I adjust the size of each slide to the size of each image when each image has diferent dimensions, keeping image responsive.

**Comment by sangyoo91** [comment]
+1

**Comment by nolimits4web** [comment]
would be good to see live example or JSFiddle of what you have tried

**Comment by nolimits4web** [comment]
or of what you are trying to achieve

**Comment by brunovila** [comment]
I've just done it removing the height attribute of each slide in css
