### ISSUE TITLE
Adding GSAP to enhance backwards compatibility

### ISSUE THREAD

**Issue by wgroenewold** [nolimits4web/Swiper#1461]
Hey,

For a few of our projects we relied on GSAP (http://greensock.com/gsap). Since one of their core values is backwards compatibility and they manage to do an awesome job at that I was wondering if you could make Swiper rely on that as well? By that way we could still do awesome stuff like CSS3 transitions and GPU acceleration but the GSAP framework will help with fallbacks for old browsers (like IE9).

Love to hear your ideas on this and would be willing to help you out with implementing this.

**Comment by nolimits4web** [comment]
Sorry, i understand your concerns about it, but this is the idea of Swiper 3.x, there is no support for old browsers (like IE9), for this case there is a Swiper 2.x which can be used as a callback. Also GSAP lib is not really popular and widely used and with pretty weird syntax :) And integrating such thing into Swiper will just add lots of unnecessary stuff to the code.

So currently, there is no plans to integrate it into Swiper
