### ISSUE TITLE
Высота slider-item при вертикальном direction

### ISSUE THREAD

**Issue by AleksandrKrokis** [nolimits4web/Swiper#1462]
Добрый день, Владимир.
Вот пример проблемы http://codepen.io/anon/pen/zvzogP
При количистве слайдов больше одного, высота слайда считается не правильно. Как этого избежать?

**Comment by nolimits4web** [comment]
Не вижу чтобы у вас вообще где то была задана высота контейнера, высота слайда считается от него

**Comment by AleksandrKrokis** [comment]
Тогда получается что ваша карусель, не очень респонсив. (в моей ситуации высота контейнера не известна, т.к. на разном разрешении высота слайда разная)
Мне кажется что правильней было бы считать высоту контейнера от высоты слайда.

**Comment by nolimits4web** [comment]
Тогда читаем тут #1132, закрываю как дубликат
