### ISSUE TITLE
Проблемы с scrollbarContainer + next/prev buttons

### ISSUE THREAD

**Issue by BeklievParviz** [nolimits4web/Swiper#1464]
> If you don't know Russian language - please, translate it with [Google Translator](https://translate.google.com).

Код, который я использую [[на jsFiddle](http://jsfiddle.net/BeklievParviz/9mzab5dm/)]
--

**HTML**
```html
<!-- Swiper -->
<div class="swiper-container">
	<div class="swiper-wrapper">
		<div class="swiper-slide">Очень длинный текст</div>
	</div>
    
	<!-- Add Scroll Bar -->
	<div class="swiper-scrollbar"></div>

	<!-- Add Arrows -->
	<div class="swiper-button-next"></div>
	<div class="swiper-button-prev"></div>
</div>
```

**JavaScript**
```javascript
$('.swiper-container').swiper({
	//Обязательные опции
	slidesPerView: 'auto',
	nextButton: '.swiper-button-next',
	prevButton: '.swiper-button-prev',

    //Необязательные
	scrollbar: '.swiper-scrollbar',
	scrollbarHide: false,
	scrollbarDraggable: true,
	mousewheelControl: true,
	freeMode: true
});
```

Проблемы (версия Swiper: 3.1.7)
--
1. Невозможно промотать кнопками влево/вправо в середину (мотается только в начало/конец);
2. Если отключить `freeMode` появляется такая же проблема и при прокрутке роликом мыши;
3. Кнопки влево/вправо не выключаются (не реагируют) на начало/конец контейнера при прокрутке роликом мыши, но если прокрутить в начало/конец с `mouseDrag` -  то реагируют нормально.

Посмотреть можно здесь: http://jsfiddle.net/BeklievParviz/9mzab5dm/

--
Помню раньше была опция `sliderPerViewFit` - она как раз отображала содержимое слайда по-частям, если не ошибаюсь, но такой опции сейчас нет.

**Comment by BeklievParviz** [comment]
Завершил описывать проблемы, можете отвечать.

**Comment by nolimits4web** [comment]
Это не актуально в данном случае, так как кнопки предназначены для переключения между слайдами и только, не между "кусками" одного слайда. Если нужно что то подобное то можете реализовать используя методы API

> Помню раньше была опция sliderPerViewFit - она как раз отображала содержимое слайда по-частям, если не ошибаюсь, но такой опции сейчас нет.

Была, убрана в связи со своей бессмысленностью)))

**Comment by BeklievParviz** [comment]
А каким API-методами можно реализовать?

**Comment by BeklievParviz** [comment]
Нашлась ещё одна проблема.
Обновил шапку добавив в самый конец описание 4й проблемы.

**Comment by BeklievParviz** [comment]
Посмотрите как работает слайдер `owlCarousel`
https://jsfiddle.net/BeklievParviz/10o34any/embedded/result/

Я там вставил в каждый слайд ссылку.
Работает очень хорошо и очень правильно.
Можно ли в swiper такой сделать?

**Comment by nolimits4web** [comment]
Ну в данном случае можно пользоваться .getWrapperTranslate чтобы узнать конкретное положение слайдера и .setWrapperTranslate чтобы "передвинуть" на новую позицию. По идее по нажатию на "next-button" нужно делать что то вроде:
```js
var newTranslate = swiper.getWrapperTranslate() - s.container.width(); //сдинуть на ширину слайдера
swiper.wrapper.transition(300); //для анимации
swiper.setWrapperTranslate(newTranslate); //установить новое значение
```
Также можно пользоваться методами `.minTranslate()` и `.maxTranslate()` чтобы узнать граничные значения

**Comment by BeklievParviz** [comment]
Спасибо!
А что по-поводу пункта №3?

**Comment by nolimits4web** [comment]
> А что по-поводу пункта №3?

Поправлен

**Comment by nolimits4web** [comment]
Думаю можно закрывать, так как видимо больше нет вопросов
