### ISSUE TITLE
swiper don't change slide until page get resized

### ISSUE THREAD

**Issue by beaudry12087** [nolimits4web/Swiper#1465]
I am using swiper.js with jquery mobile and sometimes when I create a swiper.js object , i noticed that changing slides doesn't do anything but I can see that the pagination changes. I noticed also that when i resize the page, things becomes normal and moving forward or backwards change slide properly. Any idea what is wrong? I don't know if that it is the cause but I am creating my swiper object using an element obj which has not yet been added to the document.

**Comment by nolimits4web** [comment]
Use search through forum or repo, there are some solutions. It is JQM issue, because you init Swiper in the moment it is still invisible

**Comment by beaudry12087** [comment]
Perfect. Thank you for the prompt response :)
