### ISSUE TITLE
mousewheel on nay apple trackpad

### ISSUE THREAD

**Issue by A11oW** [nolimits4web/Swiper#1466]
Strange working mousewheel on any apple devices with trackpad(notebook, mouse, trackpad)
Slides don't sliding or sliding only first 2;

http://www.idangero.us/swiper/demos/20-mousewheel-control.html

**Comment by nolimits4web** [comment]
What can i say, Chrome becomes more and more annoying breaking many things with new update :) Like in this time, for some reason it triggers "mousewheel" scroll event when you just touch it without actual scrolling, weird.

**Comment by nolimits4web** [comment]
Anyway, should be fixed now in dev
