### ISSUE TITLE
Callback on hash nav change

### ISSUE THREAD

**Issue by AlbertNowotny** [nolimits4web/Swiper#1468]
Hi,
it seems that `onSlideChangeStart` callback isn't executed after a slide change when `hashnav` is enabled, is there another callback?
(it might be useful when using a custom pagination with `hashnav: true`)

**Comment by nolimits4web** [comment]
> it seems that onSlideChangeStart callback isn't executed after a slide change when hashnav is enabled

Why, `onSlideChangeStart` always works. Otherwise would be good to see example or JSFiddle with this issue

**Comment by AlbertNowotny** [comment]
Sorry you're right, I was checking it by clicking anchor links in a menu, in that case the url in the addess bar of the browser changes but slides do not switch (and so `onSlideChangeStart` is not triggered).
We can close this issue, it's definitely not a swiper bug.
