### ISSUE TITLE
'onSlideChangeEnd' not working properly on fade effect

### ISSUE THREAD

**Issue by srikanthegdee** [nolimits4web/Swiper#1470]
Example 16 fade effect

When you go from initial slide to next slide it works. But when you go back to the first slide, the callback is not triggered. Same problem for 'onTransitionEnd'.

Tested on both Firefox and Chrome. Windows 7 OS

**Comment by nolimits4web** [comment]
Hmm, can't replicate it neither in Chrome nor in FF

**Comment by srikanthegdee** [comment]
set 'initialSlide' to something other than 0. Once the slider initializes, go back (by swiping) . 'onSlideChangeEnd' is not triggered.

```
   <script>
    var swiper = new Swiper('.swiper-container', {
		keyboardControl: true,
        pagination: '.swiper-pagination',
        paginationClickable: '.swiper-pagination',
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        spaceBetween: 30,
        effect: 'fade', 
		initialSlide: 2,
		keyboardControl: true,
		mousewheelControl:true,
	    onSlideChangeEnd: function(){alert("onSlideChangeEnd")},

    });
    </script>
```

**Comment by nolimits4web** [comment]
@srikanthegdee still works for me

**Comment by nolimits4web** [comment]
But on Chrome it can be related to this Chrome bug #1402

**Comment by srikanthegdee** [comment]
Well, the thing is, you need to keep navigating back and forth. In some cases the event is not triggered. Anyways, I guess I should close this because I am the only one who is having this issue. Thanks for the awesome library!
