### ISSUE TITLE
Package for Meteor

### ISSUE THREAD

**Issue by jimmiebtlr** [nolimits4web/Swiper#1471]
Any chance on getting this packaged for meteor?  There is an existing package that seems to be falsely claiming to be an official package.  https://atmospherejs.com/swiper/swiper

**Comment by nolimits4web** [comment]
Yes, it is not official. Will take a look to package it for meteor. As i understood i just need to create `package.js` file for Atmoshpere?

**Comment by jimmiebtlr** [comment]
A package.js for atmosphere, then meteor publish --create when in the directory to actually publish the package.

**Comment by nolimits4web** [comment]
Ok, will do it

**Comment by Chun-Yang** [comment]
I created a PR for this https://github.com/nolimits4web/Swiper/pull/1473.

**Comment by nolimits4web** [comment]
Published
