### ISSUE TITLE
Horizontal swiper vertically scrollable slide content

### ISSUE THREAD

**Issue by jainmohit1985** [nolimits4web/Swiper#1472]
Can we make a content of specific slide of horizontal swiper vertically scrollable (using scrollbar) while other slides can be static?

**Comment by nolimits4web** [comment]
Yes, just add `overflow: auto` CSS rule to the required slide

**Comment by jainmohit1985** [comment]
Thanks. I have already done that and working. But the real elastic scroll is not working on iOS and a ugly scroll is visible on desktop browsers. Any solution for this?

**Comment by kelrob** [comment]
Why cant i have more than two of the same swiper on  the same page without affecting each other. Because i tried it but each time i try i click on any of the pagination button it also affects the other swiper. Please Answer soon. Thanks Kelrob.

**Comment by nolimits4web** [comment]
@kelrob https://github.com/nolimits4web/Swiper/blob/master/demos/24-multiple-swipers.html and post your issues in appropriate thread

**Comment by nolimits4web** [comment]
@jainmohit1985 
> But the real elastic scroll is not working on iOS

Add `-webkit-overflow-scrolling: touch`

> ugly scroll is visible on desktop browsers

The only thing you can do here is to use some 3-rd party lib for scrolling then

**Comment by jainmohit1985** [comment]
Thanks. Your suggestion worked.
