### ISSUE TITLE
Lazy loading elements event handler

### ISSUE THREAD

**Issue by dannyhuly** [nolimits4web/Swiper#1474]
Hi All,

I'm using the swiper to display non images element in my project.
I would like to lazy load the elements data only if the swiper is displaying the elements.

It will be grate to have a way to tell which of the current items are displayed and then using the onInit or onSlideChangeStart/End to do the lazy loading.

Please advise.

**Comment by nolimits4web** [comment]
Didn't understand your question/issue. Usually you do it in just onSlideChangeEnd event:
```
onSlideChangeEnd: function (s){
  var currentSlide = s.slides.eq(s.activeIndex);
  //do something with elements of currently active slide
}

**Comment by nolimits4web** [comment]
I think we can close it as there is no further discussion
