### ISSUE TITLE
Avoid Browser Detection (use only feature detection)

### ISSUE THREAD

**Issue by karlitoz007** [nolimits4web/Swiper#1475]
Swiper.js and swiper.min.js files are using browser detection techniques to determine how the webpage should render across many different versions of browsers.

The recommendation is to use feature detection – a practice that determines if a specific feature has support in the current client and then chooses the best experience to render based on this Information.

**Comment by nolimits4web** [comment]
Yes, it uses something. But it is better to check first what are they used for, feature detection can't be used there

**Comment by nolimits4web** [comment]
It uses browser detection only for one case, to detect and fix very annoying Safari-bug with 3D transforms, which cannot be detected using feature-detection
