### ISSUE TITLE
Using lazy loading resulting in W3C html validation errors

### ISSUE THREAD

**Issue by sebastianbaumann** [nolimits4web/Swiper#1476]
Using Swiper with lazy-loading enabled results in errors when trying to validate html on https://validator.w3.org/ even though you provide fallback images on src attribute.

>Error: Bad value  for attribute src on element img: Must be non-empty.
>From line 104, column 37; to line 104, column 267
><img itemprop="contentUrl" src="" data-src="/images/..." class="swiper-lazy"

**Comment by nolimits4web** [comment]
HTML validation doesn't have much sense in HTML5, if you really care about (for some reason) you can't use lazy loading, or pass some placeholder 1x1 px image

**Comment by sebastianbaumann** [comment]
If you say so.
But like I said I'm getting this validation error even when using a placeholder image.

HTML: 
><img itemprop="contentUrl" src="placholder.gif" data-src="/images/real-image.jpg." class="swiper-lazy"

results in 
>Error: Bad value for attribute src on element img: Must be non-empty.
