### ISSUE TITLE
on tab change swiper did not load image in visible slides

### ISSUE THREAD

**Issue by amitcw** [nolimits4web/Swiper#1479]
I am having number of tabs and on each different tab different swiper with lazy load image is visible.
So when I click on tab it shows swiper with all slides perfectly but image is not loading on visible slide.
When I swipe or change the slide then only it loads image in visible slides.

**Comment by nolimits4web** [comment]
I guess it is because sliders in other tabs were hidden. Run this for the relative Swiper when tab with Swiper becomes visible `swiper.lazy.load()`

**Comment by amitcw** [comment]
Ok, I will try this ```swiper.lazy.load()``` at the place of below code:
```javascript
$(".swiper-slide-visible img,.swiper-slide-active img").each(function (index) {
	        var src = $(this).attr("data-src");
	        $(this).attr("src", src);
	        $(this).parent().find('.swiper-lazy-preloader').remove();
});
```

**Comment by amitcw** [comment]
Sorry, to tell you that the method which you shared is not working in my code.
So is it ok if I will continue with code which I mentioned in previous comment.

**Comment by nolimits4web** [comment]
> So is it ok if I will continue with code which I mentioned in previous comment.

Didn't check it, but if it works for you, then it is ok)
