### ISSUE TITLE
How to add captions to a slide?

### ISSUE THREAD

**Issue by lizardking93** [nolimits4web/Swiper#1482]
Hi! I've read all documentation and it should be something simple. The only captions options that I saw were for Parallax slides. Is there anyway to add to a normal slide?  

![slide](https://cloud.githubusercontent.com/assets/7432803/10829915/b7fc24c0-7e74-11e5-8959-90cec2b28f1a.jpg)

This is how it looks when I add a a div with class="title" to a slide.  
Thanks

**Comment by magic-77** [comment]
Hey,
what Caption Option do you really need?
Just add some HTML Markup inside the Slide Div, like:

    ...
    <div class="swiper-slide">
       <img src="image">
       <div class="caption">your Text</div>
    </div>
    ....

**Comment by lizardking93** [comment]
I managed to do something like that. I had to do some hacks tho

**Comment by nolimits4web** [comment]
I think we can close it, problem seems to solved

**Comment by ymc-sise** [comment]
@lizardking93 How did you solved that?
