### ISSUE TITLE
Safari jumps two slides on mouse-wheel with trackpad or magic-mouse

### ISSUE THREAD

**Issue by marcelhadorn** [nolimits4web/Swiper#1486]
I have this issue on chrome now and then, but it really happens each and every single time on safari, no matter how "softly" I scroll! Seems an Issue for client as well, since he uses his trackpad mostly.

It's a full-screen nested swiper. vertical swiper setting:

```
    mousewheelForceToAxis: true,
    mousewheelSensitivity: 10,
    freeMode: false
    mousewheelForceToAxis: false,
    mousewheelSensitivity: 0.5,
    freeMode: true,
    freeModeMomentum: true,
    freeModeMomentumRatio: 10,
    freeModeMinimumVelocity: 0.01,
    freeModeSticky: false
```

Horizontal swiper settings:

```
            pagination: '.swiper-pagination-h.'+id+'',
            mousewheelControl: true,
            mousewheelForceToAxis: true,
            mousewheelSensitivity: 1,
            mousewheelReleaseOnEdges: false,
            nextButton: '.swiper-button-next.'+id+', .peek.next.'+id+',  #'+id+' button.more',
            prevButton: '.swiper-button-prev.'+id+', .peek.prev.'+id+'',
            speed: 700,
```

Must ask client if I can post link to website here, meanwhile anyone a clue?

– M

**Comment by nolimits4web** [comment]
What Swiper version do you use? I can't replicate it with track pad, for example, here http://www.idangero.us/swiper/demos/20-mousewheel-control.html Otherwise, if you use latest version, would be good to see live example or JSFiddle at least

**Comment by Marc3llo** [comment]
Version 3.1.7.

I think I figured out something weird: If I use on every slide the same background-image, then it works fine, if there are different images it doesn't, even if those images are actually the same width and height or even if it's the same image with a different name.

I made a content free copy of the website, you can access here to check: http://duotones.ch/swiper-issue/#e-mail

Try Browser Safari & Trackpad or Safari & MagicMouse

**Comment by wgroenewold** [comment]
Why are there swiper-containers with no slides inside every slide?

**Comment by Marc3llo** [comment]
because I removed the slides, had to remove all the content. But it happens also with slides in the containers. Each vertical slide has horizontal slides in the final website.

**Comment by Marc3llo** [comment]
Any update on this?

**Comment by nolimits4web** [comment]
I see the issue on your link, but can't replicate it on my own. Don't have any idea why it is happening on your side

**Comment by Marc3llo** [comment]
@nolimits4web thanks for trying, did you also add background-images with background size cover to a full-screen swiper instance?

**Comment by StefanVilbrandt** [comment]
If i use the trackpad on mac in chrome, i have the same issue on his fiddle.
Mac 10.11.1
Chrome 46.0.2490.80 (64-bit)

**Comment by stephanedemotte** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue
