### ISSUE TITLE
Feature request: Fallback image

### ISSUE THREAD

**Issue by OliverKK** [nolimits4web/Swiper#1488]
Hi There,
i'am currently facing the situation to protect my photo gallery from being unusable
if my photo API is not available.

It would be nice to have a fallback url if a photo could not be loaded.
Thank you

**Comment by nolimits4web** [comment]
It should be done manually as it is easily can be done in vanilla js:
```
$('img').on('error', function(){
  $(this).attr('src', 'path/to/fallback-image.jpg');
});

**Comment by OliverKK** [comment]
Thank you @nolimits4web for your response.
The thing is, the code you provided changes the path for all images selected by `$('img')`
to the fallback image.

Think about swiping through a photo gallery made with `swiper` and lazy loading turned on.
When you reach the 3rd photo which is not available anymore all other images, even if they are still available(cache) are changed to the fallback image. 

I think, there should be the ability to use a fallback image to keep the swiper photo gallery work like
expected even if couple images are not available.

**Comment by nolimits4web** [comment]
> path for all images selected by $('img') to the fallback image.

No, the event assigned for all images, but it will be applied to only "error" images. You can make it more narrow if you want like:
```
$('.swiper-slide').on('error', function(){
  $(this).attr('src', 'path/to/fallback-image.jpg');
});

**Comment by OliverKK** [comment]
Thanks for the response. 
I wrote a little helper, which works pretty well. 

```javascript
  fallbackImage: function(tag, fallbackClass, fallbackUrl) {
    $(tag).on('load', function(element) {
      if (element.target.currentSrc.indexOf(fallbackUrl) == -1) {
        $(this).removeClass(fallbackClass);
      }
    });

    $(tag).on('error', function() {
      $(this).attr('src', fallbackUrl);
      $(this).addClass(fallbackClass);
    });
  }
```

Cheers OliverKK
