### ISSUE TITLE
UMD version broken

### ISSUE THREAD

**Issue by callumacrae** [nolimits4web/Swiper#1489]
https://github.com/nolimits4web/Swiper/commit/a0dcb5907cf74aa25f4d504d37bdac4eb1d5b2e2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L5

Why did you change the main field? This breaks the module when used with a CommonJS package manager such as Browserify is used.

Please don't update the `main` field on anything other than a breaking version! This change has caused over 80,000 errors on our website, because patch versions are automatically applied.

**Comment by nolimits4web** [comment]
No panic. It is done because Swiper is NOT a jQuery library and shouldn't require jQuery as a dependency by default. Many users complaining about that

**Comment by callumacrae** [comment]
Did you actually test your change? It's broken. It throws an error.

**Comment by nolimits4web** [comment]
No errors. jquery.umd version left intact. So basically you need to use it manually, not from package.json, or modify package.json manually after installation to use jquery.umd version

**Comment by callumacrae** [comment]
What do you mean, "no errors"? If you load Swiper using `require('swiper')`, it throws an error in all browsers. How is that not an error?

**Comment by nolimits4web** [comment]
Just checked with browserify and requirejs. Works smoothly. Here is my main.js example with browserify:
```
var Swiper = require('swiper');
var mySwiper = new Swiper('.swiper-container', {
    spaceBetween: 50,
    slidesPerView: 2,
    centeredSlides: true,
    slideToClickedSlide: true,
    grabCursor: true,
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    scrollbar: '.swiper-scrollbar',
    pagination: '.swiper-pagination',
});
```
It works without any problems

**Comment by callumacrae** [comment]
This is what I get:

```
TypeError: Unable to get value of the property 'add': object is null or undefined
```

Started happening on production too, because npm automatically updates patch versions—this was a breaking change and really should have been released as a major version, even if it was intentional.

**Comment by nolimits4web** [comment]
> TypeError: Unable to get value of the property 'add': object is null or undefined

Would be good to know how to replicate this issue, as i can't get it
