### ISSUE TITLE
watchSlidesVisibility does not work with slidesPerView > 1

### ISSUE THREAD

**Issue by fritzmg** [nolimits4web/Swiper#1492]
I want to use `watchSlidesVisibility: true` so that Swiper automatically assigns the `slideVisibleClass` to the currently visible slides (`swiper-slide-visible`). However, with the option `slidesPerView` set to something greater than 1 this does not work at all. Swiper seems to assign `swiper-slide-visible` to a few random slides, but definitely not the ones that are visible.

Tested with Swiper.js 3.2.0

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle of the issue you have

**Comment by AlexandrTuniev** [comment]
https://jsfiddle.net/atuniev/0rc68zg4/10/ here is fiddle with that bug,

**Comment by alejandroiglesias** [comment]
@nolimits4web this is still happening on 3.4.0. @AlexandrTuniev provided the fiddle.

**Comment by DanielRuf** [comment]
Still happening in latest version. The visibility class should be applied after all css transitions on elements and so on.
