### ISSUE TITLE
How to make the content width goes 100%?

### ISSUE THREAD

**Issue by yeemun** [nolimits4web/Swiper#1493]
I found that there are two white margin at both sides. How can I make the content width goes 100%? I was looking at CSS but couldn't find one. Sorry, I am new to CSS. :( 
Thanks in advance.
![capture](https://cloud.githubusercontent.com/assets/13152116/11082613/b119bcd4-8861-11e5-826d-cd6b5592ceb2.PNG)

**Comment by wwh447** [comment]
Code...

**Comment by wgroenewold** [comment]
@wwh447 means "Could you please make a code example on JSFiddle to show your problem?" :)
