### ISSUE TITLE
onSlideChangeEnd not firing if new slide is added during onSlideChangeStart

### ISSUE THREAD

**Issue by mikebonds** [nolimits4web/Swiper#1494]
For the sake of brevity, I will not go into the details. I am building a component of an app that manages the slides in swiper. It's meant to ensure smooth transitions between slides that are far apart so you don't see swiper slide through all the slides in between. A secondary goal is to manage the pages memory.

When a slide change is in progress, the manager adds and removes slides as needed. But when any modification to swiper such as adding a slide happens during the slideChangeStart, the slideChangeEnd does not fire. Though is does fire correctly if slides are added onSlideChangeEnd, and continues to fire correctly.

I am wondering if there might be a fix for this if you have seen this before?

Thanks

**Comment by nolimits4web** [comment]
Basically, you shouldn't do that on onSlideChangeStart as it forces relayout/reflow which can break animation. It also runs slideTo internally in some cases. So it is better to move the logic to onSlideChangeEnd or add them manually to DOM, and call `.update` within `onSlideChangeEnd`

**Comment by mikebonds** [comment]
Thanks a lot for the answer.
