### ISSUE TITLE
Is it possible to reverse the slide ??

### ISSUE THREAD

**Issue by KarunaLakshman** [nolimits4web/Swiper#1496]
Thanks for the awesome slider !!

We have localization in our project. So as per arabic locale i have to invert my text direction and also the slider should start transition from the right side.

Means the initialSlide (Zero)  should stick to right side and i should be able to swipe right to get the next activeIndex as One

Is it possible to achieve ?

**Comment by KarunaLakshman** [comment]
I solved it by giving rtl to container, But prev and next navigators are not disabled correctly. Prev button is disabled for initialSlide in RTL.

**Comment by nolimits4web** [comment]
All you need is:
```
<div class="swiper-container" dir="rtl">...
