### ISSUE TITLE
Swiper and Instafeed

### ISSUE THREAD

**Issue by charlesravndal** [nolimits4web/Swiper#1498]
Hi! Is it possible to use the images fetched from Instafeed (http://instafeedjs.com/) into Swiper? 

I tried to append it like this, but it didn't work:

        var feed = new Instafeed({
            get: 'user',
            userId: 3722752,
            accessToken: '3722752.467ede5.edc5948480384f54915ea14617ce6716',
            template: '<div class="swiper-slider"><a href="{{link}}"><img src="{{image}}" /></a></div>',
            after: function () {
                $('#instafeed').swiper({
                    slidesToShow: 1
                });
            }
        });
        feed.run();

Hopefully someone can help me :) Thanks in advance!

**Comment by tobiasMitt** [comment]
Hi,

i tried it too some days ago, it doesn't work because swiper duplicates slides instance and the slide div you see is not the one fetched with instafeed.

I went for a simpler and more robust solution by 'manually' fetching the instagram images server side with PHP (using Instagram JSON API) and building the correct html + js (so the images are visibile also to no-js users/bot).

If server side control (and building your js logic) is not a solution, you can try to init instafeed before initializing swiper and avoid using loop mode for slides (instafeed works only with an ID container, that should be a single html element)

**Comment by charlesravndal** [comment]
Server side control is not a solution for this project, but init instafeed before swiper sounds like the way to go. I'm just wondering how to control it like limiting the images 4 at a time for example since I'm still not fully fluent with this language.

**Comment by charlesravndal** [comment]
Hi! Manage to work it out with this:

var feed = new Instafeed({
            get: 'user',
            userId: 3722752,
            accessToken: '3722752.467ede5.edc5948480384f54915ea14617ce6716',
            template: '<div class="swiper-slide"><a href="{{link}}"><img src="{{image}}" /></a></div>',
            after: function () {

                var swiper = new Swiper('.swiper-container', {

                    effect: 'cube',
                    grabCursor: true,
                    loop: true,
                    autoplay: 4000,
                    cube: {
                        shadow: false,
                        slideShadows: false,
                        shadowOffset: 20,
                        shadowScale: 0.94
                    }
                });
            }
        });
        feed.run();

**Comment by charlesravndal** [comment]
var feed = new Instafeed({
            get: 'user',
            userId: 3722752,
            accessToken: '3722752.467ede5.edc5948480384f54915ea14617ce6716',
            template: '<div class="swiper-slide"><a href="{{link}}"><img src="{{image}}" /></a></div>',
            after: function () {

                var swiper = new Swiper('.swiper-container', {

                    effect: 'cube',
                    grabCursor: true,
                    loop: true,
                    autoplay: 4000,
                    cube: {
                        shadow: false,
                        slideShadows: false,
                        shadowOffset: 20,
                        shadowScale: 0.94
                    }
                });
            }
        });
        feed.run();

**Comment by charlesravndal** [comment]
Manage to fix it :) Thanks for the tip :)

**Comment by Basilakis** [comment]
Can u please share all the informations and how u solved it?

@charlesravndal

**Comment by charlesravndal** [comment]
@Basilakis  I'm so sorry for a very late reply. I just saw this today :)
 
Here is what we did:


    <script>
        var feed = new Instafeed({
            get: 'tagged',
            tagName: 'tagname here',
            userId: userid here,
            accessToken: 'Instagram access token here',
            resolution: 'standard_resolution',
            template: '<div class="swiper-slide"><a><img src="{{image}}" /></a></div>',
            after: function () {

                var swiper = new Swiper('.swiper-container', {

                    effect: 'cube',
                    grabCursor: true,
                    loop: true,
                    autoplay: 3000,
                    cube: {
                        shadow: false,
                        slideShadows: false,
                        shadowOffset: 20,
                        shadowScale: 0.94
                    }
                });
            }
        });
        feed.run();
    </script>
