### ISSUE TITLE
wrong s.clickedIndex calculated when wrapper contains non-slide elements

### ISSUE THREAD

**Issue by kaililleby** [nolimits4web/Swiper#1499]
in core.js, line 1152 (approx.):

```
s.updateClickedSlide = function (e) {
    var slide = findElementInEvent(e, '.' + s.params.slideClass);
    var slideFound = false;
    if (slide) {
        for (var i = 0; i < s.slides.length; i++) {
            if (s.slides[i] === slide) slideFound = true;
        }
    }

    if (slide && slideFound) {
        s.clickedSlide = slide;
        s.clickedIndex = $(slide).index();
    }
```

On line ` s.clickedIndex = $(slide).index();` the expression `$(slide).index()` will return the index of `slide` amongst all sub elements of the wrapper, not only amongst the elements having the slideClass. Other calculations seem to be based on only elements having the `slideClass`

Replacing  ` s.clickedIndex = $(slide).index();`  with 
`for (var i = 0; i < s.slides.length; i++)  if (s.slides[i] === slide) s.clickedIndex = i;`
fixes the problem - but I'm not into the Dom7 Library and the semantics of index()...

Thoughts?

**Comment by nolimits4web** [comment]
Sorry, but why `index` should return the slide's-only number. By `.index` you should expect slide index as a child's index number in parent. So if you have something else there you should just consider it.
