### ISSUE TITLE
Feature request: Retina lazyLoading

### ISSUE THREAD

**Issue by julmot** [nolimits4web/Swiper#1501]
Unfortunately the API nor the example has a note about retina image lazy loading. The lazyLoading example just shows how to lazy load a single image regardless of the ppi. Is it possible to load also @2x images on devices with high ppi? If so, how can we use it?

**Comment by magic-77** [comment]
Hi julmot,
it´s possible, but you have to use a third party plugin. I´m using "lazysizes".
An simple example for that you can find here.
http://stackoverflow.com/questions/31939023/swiper-3-with-lazysizes

If you have questions, tell me

**Comment by julmot** [comment]
It makes no sense for me to allow this option, but don't allow to set a retina image. If I need to switch to a third party lib to allow lazy loading then this functionality should not be shipped with the dist output.

**Comment by magic-77** [comment]
Then try to post a Feature Request.
For me it´s works well, and it´s ok to extend Functionality with third Party Plugs.

**Comment by nolimits4web** [comment]
It would be good to check docs before complaining :smile: http://www.idangero.us/swiper/api/#lazy
Look at examples and notes about `srcset`

**Comment by julmot** [comment]
@nolimits4web What do you mean?

Are you talking about this sentence?
> 
Lazy image source set for <img> element should be specified in "data-srcset" attribute instead of "srcset"

If so I think we both have a different understanding of this. For me this does not implicate to use this attribute for retina variants nor how. If this is the solution for retina I furthermore would not be able to use it since I dont know the syntax inside the attribute.

**Comment by nolimits4web** [comment]
And this example in the section doesn't tell you anything?
```
        <div class="swiper-slide">
            <img data-src="path/to/logo-small.png" data-srcset="path/logo/logo-large.png 2x" class="swiper-lazy">
            <div class="swiper-lazy-preloader"></div>
        </div>
```
If you are not familiar with `srcset` img's attribute, it worths to google it. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img There are also examples about it
