### ISSUE TITLE
Responsive Example not working properly in FF

### ISSUE THREAD

**Issue by thven1990** [nolimits4web/Swiper#1503]
I got a Slider with 4, 3, 2 and 1 slide in different resolutions. 4 and 3 are applied. But in mobile there are still 3 images in FF. 
IE, Chrome and so on work fine, even IE10. Only firefox is buggy as hell, even with your example. 
Just open the example 
http://www.idangero.us/swiper/demos/33-responsive-breakpoints.html
in FF and resize. The first step (4 slides) is applied, but 3 and 2 are never seen.

**Comment by thven1990** [comment]
Version 3.2.0

**Comment by thven1990** [comment]
Searched and got the problem: 
in Line 264 in non-minified- non-jquery version you got the line 
" for ( var point in s.params.breakpoints ) {"

--> when logging i get an ascending list of breakpoints in Chrome, but a descending list in FF. So FF declares, that the first should not be applied and quits as i think. You have to add code to iterate through the objects in an ascending order!

Don't want to edit in your code, so please fix yourself!

Looking forward to your reply.

**Comment by nolimits4web** [comment]
It was fixed in this commit https://github.com/nolimits4web/Swiper/commit/38e696266bbeebf0b9dcde54410b89b19d8b811b You can build dev version using instructions or wait for next release

**Comment by nolimits4web** [comment]
Fixed in 3.2.5
