### ISSUE TITLE
New Feature: AutoHeight

### ISSUE THREAD

**Issue by itstueben** [nolimits4web/Swiper#1507]
It would be nice if the Swiper had an auto Height Functionality. After a swipeEnd the Height of the Wrapper will be set to the Slide Height.

**Comment by nolimits4web** [comment]
Do you mean the auto height which was released in 3.2.5?

**Comment by theamundell** [comment]
I've attempted using this awesome new feature. However, I can't get it working all the way. The active slide is giving the wrapper and all slides the same height but it's not updating when I go to the next slide.
