### ISSUE TITLE
 autoplay have a problem

### ISSUE THREAD

**Issue by chenjmdgjl** [nolimits4web/Swiper#1508]
Hello, I found autoplay have a problem, after the lock screen, open again the case of the browser page, the page will stop the automatic playback, please advise which is why

**Comment by nolimits4web** [comment]
Doesn't related much with Swiper, this is how browser treats timeouts in hidden/closed tabs. You may have a look Page Visibility API if it is critical for you https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
