### ISSUE TITLE
Best way to use custom animation for slide along with translate

### ISSUE THREAD

**Issue by vikasneelam** [nolimits4web/Swiper#1509]
Hi,
I would like to use a different animation for the swiping. I would like to add custom animation. I would like to scale the slide from 100%(size) to 50% gradually for half of the slide transition time and then i would like to scale the slide from 50% to 100% gradually for the next half of the slide transition along with the normal translation of slide along X axis. How and where can i add this animation?

**Comment by nolimits4web** [comment]
Look how effects are done https://github.com/nolimits4web/Swiper/blob/master/src/js/effects.js Basically you just need to listen onSetTranslate/Transition callbacks and add all required logic there related to translate value
