### ISSUE TITLE
Firefox nested flexbox + swiper

### ISSUE THREAD

**Issue by veke** [nolimits4web/Swiper#1510]
http://jsfiddle.net/qzwffujn/
Im expecting to see 10em width left column and a full width right column. On firefox left column is squished and right one's overflow is broken as well swiper. Not sure that this is swiper related bug or not.
Swiper container has some flex-box styles. Maybe worth of checking.

**Comment by nolimits4web** [comment]
Nothing common with Swiper, this is how flex works. http://jsfiddle.net/ap3zppma/

**Comment by veke** [comment]
ah, min-width for firefox. Missed that one. Thanks.

**Comment by JacobDB** [comment]
Thanks for posting this, I was pulling y hair out trying to figure this one out! Do either of you know *why* `min-width: 0;` fixes this? I don't really understand it, seems like that'd solve the reverse problem.

**Comment by Interinactive** [comment]
I second this. It was driving me insane. Why does it fix the issue?

**Comment by JacobDB** [comment]
@Interinactive so I can't explain it exactly, but it seems that `min-width` and `min-height` default to `auto` on flexed elements.

https://developer.mozilla.org/en-US/docs/Web/CSS/min-width
