### ISSUE TITLE
Navigation button tap is delayed on iPad

### ISSUE THREAD

**Issue by julmot** [nolimits4web/Swiper#1512]
When tapping the navigation buttons in the Swiper example ("Navigation Buttons") on an iPad the action is delayed. Also double-tapping the navigation buttons on an iPad will trigger a page zoom.

Isn't Swiper using "touchstart" on mobile devices for navigation button events?

In my example I am using `ngTouch` in an AngularJS application. It will normally avoid the 300ms delay but only for `data-ng-click`-directives (which Swiper doesn't use). So I would need to use a library like Fastclick if Swiper uses "click" instead of "touchstart". But this seems to be overhead for just two buttons.

**Comment by nolimits4web** [comment]
Sorry, no chances to include something like Fastclick in Swiper. Swiper doesn't use touchstart instead of click because it will be wrong. Just use custom nav buttons and call slideNext/Prev method within your ng-click

**Comment by julmot** [comment]
Why would it be wrong to use `touchstart` for the navigation buttons? IMHO it is not user friendly to have such an delay. 

I would use custom nav buttons and call it on ng-click, but this will not disable/enable them if there are not enough items. Do you have a workaround for it?

**Comment by nolimits4web** [comment]
> Why would it be wrong to use touchstart for the navigation buttons?

touchstart is totally not the same as click or tap, there is too many difference

As for disable/enable buttons, again to manually for example in onSlideChangeStart callback, you can detect required position using `isEnd` and `isBeginning` properties

**Comment by julmot** [comment]
This is not very pretty, but it works. Thank you!
