### ISSUE TITLE
vertically center slides

### ISSUE THREAD

**Issue by thenewguy** [nolimits4web/Swiper#1513]
Unless I am doing something incorrectly, it doesn't appear that slides are vertically centered in the container when slides vary in height.

**Comment by thenewguy** [comment]
Something simple like the following onSlideChangeStart seems to do the trick:
```
            function verticallyCenterSlide(api) {
                var activeSlide = api.slides[api.activeIndex];
                var top = ($(api.container).height() - $(activeSlide).height()) / 2;
                $(activeSlide).css("top", ""+top+"px");
            }
```

**Comment by thenewguy** [comment]
But it would be nicer if it was calculated in the transform as a real solution

**Comment by nolimits4web** [comment]
Do you mean `centeredSlides: true` parameter?

**Comment by thenewguy** [comment]
`centeredSlides: true` seems to do horizontal centering but not vertical centering.

**Comment by nolimits4web** [comment]
This is for `vertical` direction. Otherwise you may just add this CSS:
```css
.swiper-wrapper {
  align-items: center; /* add this will all relevant prefixes */
}
```

**Comment by thenewguy** [comment]
Great!  thanks.  Seems I am behind the times with my css.

**Comment by koedev** [comment]
align-items doesn't work for me with the current version
