### ISSUE TITLE
Strange order in multi-row fill row layout

### ISSUE THREAD

**Issue by ebiasini** [nolimits4web/Swiper#1514]
I would expect to have This

1 2 3 4 5 
6 7 8 9 10
11 12 13 14 15

and on second slide

16 17 18 19 20
21 22 23 24 25…

But i get strange results such as

1 2 3 4 5
30 31 32 33 34…

With 6 being on 2nd slide?

`slidesPerView: 5,
 slidesPerColumn: 3,
        slidesPerColumnFill: 'row',
        slidesPerGroup: 5,`

**Comment by nolimits4web** [comment]
Nope, it doesn't fill slides according to `slidesPerView` it fills it by rows or by columns, no matter what is in sliderPerView

**Comment by ebiasini** [comment]
I believe it's a bit annoying in my opinion. But I can see you intended it somehow different.
If I use it in slidesPerColumnFill: 'column' I get something that makes sense, in my opinion, such as:

1 4 7 10 13
2 5 8 11 14
3 6 9 12 15

and then

16 17 18 19 20
21 22 23 24 25
26 27 28 29 30

**Comment by nolimits4web** [comment]
Nope, can't replicate it, would be good to see live example then. With slidesPerColumnFill: 'column` i see:
```
1 4 7 10 13
2 5 8 11 14
3 6 9 12 15
```
and
```
16 19 ... ... ...
17 20 ... ... ...
18 21 ... ... ...
```

**Comment by ebiasini** [comment]
This is exactly what I see too.
I find it strange that I won't get an order that makes sense per "slide container" with the row solution.

**Comment by nolimits4web** [comment]
It is because it is sorted by column. In sorting by ROW it sorts slides by row, not by slidesPerGroup/View or something else. If you need it something like in your first post, you may find a workaround, for example, just use 2 slides and put 15 custom elements in it

**Comment by ebiasini** [comment]
Unfortunately it's not a solution, as the elements are dynamic.
Thanks.

**Comment by nfalke** [comment]
I experience the same issue. It would be nice to be able to sort items like slidesPerColumnFill: 'group'.

**Comment by marcodussin** [comment]
up for slidesPerColumnFill: 'row' in multirow, multicolumn and loop mode: is still broken

**Comment by gauthier-huyghe** [comment]
Hi,

I would like to have :
1  4  7
2  5  
3  6

But when I put this as params :
            slidesPerView: 1,
            slidesPerColumn: 3,
            slidesPerColumnFill: 'column',

It do this :
1  4  6
2  5  7
3

When you put this params on the basic example, it do the same bug.
Can someone fix this ?

**Comment by blotkevin** [comment]
Up. Any fixes for gauthier-huyghe ? I do the same bug.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue
