### ISSUE TITLE
paginationContianer

### ISSUE THREAD

**Issue by aihaibo** [nolimits4web/Swiper#1515]
in swiper.jquery.js files at line 375
s.paginationContainer = $(s.params.pagination);
s.paginationContainer is search from whole document, not current node

**Comment by nolimits4web** [comment]
Yes, it is correct. Otherwise there is no way to use pagination outside of swiper-container. Just specify more strict selector or pass there HTMLElement

**Comment by aihaibo** [comment]
s.paginationContainer = s.container.find(s.params.pagination) 
maybe better

**Comment by nolimits4web** [comment]
> Otherwise there is no way to use pagination outside of swiper-container

**Comment by aihaibo** [comment]
get it
