### ISSUE TITLE
grab cursor compatibility

### ISSUE THREAD

**Issue by julmot** [nolimits4web/Swiper#1519]
I just tested Swiper in IE9-11 and MS Edge. It seems that the "grabCursor" does not work. Is there a compatibility constraint?

**Comment by nolimits4web** [comment]
It does fallback to `move` cursor where it is not supported

**Comment by julmot** [comment]
exactly, that is what appears. I did't know that it is actually using `-moz-grab`. Why aren't we using `cursor: url(images/cursor.cur);` as a fallback?

**Comment by nolimits4web** [comment]
1) because there is a `cursor: move` fallback. 
2) IE is not a Swiper's target platform

Just specify custom cursor if you really need it for IE
