### ISSUE TITLE
swiper as popup-left-navbar

### ISSUE THREAD

**Issue by nikitalaletin** [nolimits4web/Swiper#1520]
swiper.js works awesome to change main-content of my mobile app! But i'm stuck on creation hidden left-nav-panel, that should pop-up on swipe from the edge of device.
Is it possible to use swiper.js to create left-nav-menu? Have you ever tried to do this and what options should i change in source code?

**Comment by nolimits4web** [comment]
Not really, Swiper is not intended for this. I would better stick with custom solution or some other ready lib for this
