### ISSUE TITLE
slides to scroll on previous/next button click

### ISSUE THREAD

**Issue by ali-hellani** [nolimits4web/Swiper#1521]
First of all thank you for the hard work you put on this amazing plugin.

I have realized that we cannot define how many **slides to scroll** on each button click (next/previous) in case of carousel mode (Slides Per View).

is there anyway to do that ?!

Thanks in advance;

**Comment by nolimits4web** [comment]
Have you tried `slidesPerGroup` parameter?

**Comment by ali-hellani** [comment]
That is the option i want, thank u, maybe i got confused with the name.

but if i want to use it for gallery thumbs (another next/prev buttons for thumbs), the swiper does not appear to be working as expected, also slideToClickedSlide does not work as well for some thumbs.
