### ISSUE TITLE
Autoheight not firing on thumbnail gallery

### ISSUE THREAD

**Issue by rugor** [nolimits4web/Swiper#1522]
The new auto-height feature works well in individual sliders but when used in the thumbnail example it doesn't fire on the slider being controlled when just the thumbnail slider is advanced. 

[Example ](http://codepen.io/rugor/pen/dGyRde)

Any suggestions on how to make it fire on the controlled slider?

Great plugin, thanks for it.

**Comment by nolimits4web** [comment]
Fixed
