### ISSUE TITLE
API>breakpoints is not working.(when slidesPerColumn)

### ISSUE THREAD

**Issue by LeeYoonGu** [nolimits4web/Swiper#1525]
Hey,
Thank you for this great plugin.

I'm looking to change my slides-per-column at different media queries.

on Mobile the swiper has 1 slidesPerColumn.
on Tablet the swiper has 2 slidesPerColumn.
on Desktop the swiper has 3 slidesPerColumn.

Is this possible currently?(API>breakpoints is not working.)

```
var swiper = new Swiper('.swiper-container', {
  // Default parameters
  slidesPerView: 4,
  slidesPerColumn: 3,
  spaceBetween: 40,
  // Responsive breakpoints
  breakpoints: {
    // when window width is <= 320px
    320: {
      
      slidesPerColumn: 1,
      spaceBetweenSlides: 10
    },
    // when window width is <= 480px
    480: {
      slidesPerColumn: 2,
    },
    // when window width is <= 640px
    640: {
      slidesPerColumn: 3,
    }
  }
})
</script>
```

**Comment by nolimits4web** [comment]
`slidesPerColumn` can't be changed within breakpoints
