### ISSUE TITLE
Scroll Container can not  roll in weixin QQ browser

### ISSUE THREAD

**Issue by xuetian120** [nolimits4web/Swiper#1527]
http://www.idangero.us/swiper/demos/32-scroll-container.html
Android system, this demo can not roll in weixin QQ browser(http://weixin.qq.com/m)!
Incompatible QQ browser, Page can not slide!
Hope to resolve as soon as possible, thank you!

**Comment by nolimits4web** [comment]
Have no much idea what is QQ browser. Swiper is compatible with major browsers
