### ISSUE TITLE
Scrolling inside a section

### ISSUE THREAD

**Issue by KasperAndersson** [nolimits4web/Swiper#1528]
Hi @nolimits4web,

How is it possible to scroll inside a section? I've ```mousewheelControl``` set to ```true```.

**Comment by nolimits4web** [comment]
what is section? slide? If slide then just add in CSS:
```
.swiper-slide {
  overflow: auto;
}

**Comment by KasperAndersson** [comment]
Sorry, that I've responded. It worked.

**Comment by KasperAndersson** [comment]
Thanks @nolimits4web
