### ISSUE TITLE
Feature request: prevent overscrolling

### ISSUE THREAD

**Issue by b-strauss** [nolimits4web/Swiper#1530]
Hi, it would be great to have a way to tell Swiper that it should not scroll the content over the edges when you are at the first or last element.

I have a full width Swiper with fully fitting background images, and i don't want the user to see what's behind my swiper element when he is on the outermost slides.

Maybe something like:
```javascript
{
    overScrolling: false
}
```
Thx

**Comment by nolimits4web** [comment]
Look at `resistanceRatio` parameter, and try `resistanceRatio:0` or `resistanceRatio: 1`
