### ISSUE TITLE
Feature request: opacity transition

### ISSUE THREAD

**Issue by b-strauss** [nolimits4web/Swiper#1531]
Just like with parallax transitioning i would like to be able to define an opacity transitioning during slides.

Swiper argument:

``` javascript
{
    opacity: true
}
```

Data attributes on elements inside a slide element, due to the nature of opacity negative values would make no sense.

``` html
<div class="swiper-slide">
    <!--
        Normal opacity effect. The value would say after what
        distance in pixel the element would be completely invisible, ...
     -->
    <div data-swiper-opacity="250">Title</div>
    <!--
        ... or after what distance in percentage the element
        would be completely invisible.
     -->
    <div data-swiper-opacity="50%">Subtitle</div>
    <!-- Opacity effect with custom transition duration -->
    <p data-swiper-opacity="250" data-swiper-opacity-duration="600">Text</p>
</div>
```

Thx

**Comment by mikebonds** [comment]
I think I understand what you mean. What you would like to accomplish is fading in/out individual elements within a slide and to also animate these opacities at different speeds. I did something pretty similar within the onSlideChangeStart callback. In the callback you can look for elements within the current slide that has either certain classes or data attributes and apply the desired effects.

**Comment by Tusko** [comment]
+++

**Comment by Tusko** [comment]
@mikebonds can you send me your code?

**Comment by mikebonds** [comment]
@Tusko That code has was written probably close to 2 years ago. I believe that project has changed since then. I'll try to dig something up.

**Comment by Tusko** [comment]
@mikebonds thank you so much)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
