### ISSUE TITLE
Не работает mousewheel на IE11 и ниже

### ISSUE THREAD

**Issue by BeklievParviz** [nolimits4web/Swiper#1532]
Пример: [**на jsFiddle**](http://jsfiddle.net/BeklievParviz/s88z9gy8/) (используется Swiper версии 3.2.7)
Что интересно: mousewheel работает в браузере Edge (от Microsoft).

--
Вопрос: IE9 не поддерживается в 3й версии Swiper?
Скриншот: [скриншот1](https://yadi.sk/i/D5O0ELQvm9ZMZ) | [скриншот2](https://yadi.sk/i/wJfkBGkTm9ZUT)

**Comment by BeklievParviz** [comment]
Со вторым вопросом разобрался...
Нашёл ответ на вашем форуме: [скриншот](https://yadi.sk/i/9dKkqotUm9aEg)
> SNO man 25 Mar
Thanks, I spotted it. Can I ask about this bit in the Changelog?
**“•Super basic support for IE 9 with swiper.jquery version. No animation and transitions, but basic stuff like switching slides/pagination/scrollbars works”**
Does that mean it will work for simple sliding (left and right) and for simple fading between two images?
That would be enough for us I think.

Оказывается, просто нужно было подключить jquery-версию.

**Comment by nolimits4web** [comment]
Да, IE9 не поддерживается, тут есть много информации по этому поводу

**Comment by BeklievParviz** [comment]
Вы уже решили неработающий mousewheel на IE 11?
