### ISSUE TITLE
Swiper not SEO friendly

### ISSUE THREAD

**Issue by bearskin** [nolimits4web/Swiper#1533]
HI

your swiper works great .... buuuuut it is not really SEO because Google Search & Co don't really have an img-tag to crawl. So all the images in the swiper are not registered by google. 

The current output is e.g.:

    <div class="swiper-slide swiper-slide-active" style="background-image: url("https://domain-name.tld/cms/upload/KGWH_720x522/Stadtkind01/Stadtkind01_Bild01.jpg"); margin-right: 5px;" data-swiper-slide-index="0">
        <span id="swiperTitle" class="backgroundAlpha40">: Stadtkind 1</span>
    </div>

So how can I improve the SEO in this case? 

thx. bearskin.
 
PS: I also posted this question on stackoverflow (http://stackoverflow.com/questions/34204661/how-can-the-images-in-swiper-from-idangnero-us-be-made-seo)

**Comment by nolimits4web** [comment]
There is no magic here. Just use `<img>` then inside of slide
