### ISSUE TITLE
Fix error when swiper apply for many elements

### ISSUE THREAD

**Issue by Corey-Maler** [nolimits4web/Swiper#1534]
Hello.

If I try to apply swiper for many elements at same time ( ```$('.swiper-container').length > 1```),  I got an error:
```Uncaught TypeError: Cannot read property 'nodeType' of null```
In this line https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L208

To fix this enough add ```params[param] === null```

**Comment by marcomarasco** [comment]
Hi,
i have the same problem since v. `3.2.7`

To fix this issue i've downgraded Swiper to v. `3.2.6`

**Comment by nolimits4web** [comment]
Would be good to see live example or jsfiddle with this issue
