### ISSUE TITLE
I created two swipers in a page, swiper.container from event parameter has some problem

### ISSUE THREAD

**Issue by Capricair** [nolimits4web/Swiper#1536]
![image](https://cloud.githubusercontent.com/assets/6244446/11777602/620c1eaa-a28a-11e5-8cbc-48b235561b60.png)
mySwiper is the second swiper object, swp from touch end event parameters, mySwiper from constructor function, but I call the container, it return tow different results, mySwiper.container has two objects, the second object of the second container is correct, has id swiper1 is the container of first swiper object

**Comment by nolimits4web** [comment]
would be good to see live example or jsfiddle
