### ISSUE TITLE
autoHeight with lazyLoading

### ISSUE THREAD

**Issue by goranNetgen** [nolimits4web/Swiper#1537]
Is it just me or autoHeight feature combined with lazyLoading doesn't work?

First it sets the height and then loads the image, but the height of the slide stays small. If I use lazyLoadingInPrevNext it works ok when you switch to previous or next slide but then it breaks again if you skip a slide and switch directly to one that hasn't been loaded yet.

Is there any solution out of the box for this?

thx

**Comment by nolimits4web** [comment]
You can call `updateAutoHeight()` method for example in `onLazyImageReady` callback

**Comment by goranNetgen** [comment]
That solved it, thanks!

**Comment by diegocerdan** [comment]
Thanks for pointing it out. I had the same issue.
