### ISSUE TITLE
When autoplay is set and loop is false it is still looping

### ISSUE THREAD

**Issue by laoneo** [nolimits4web/Swiper#1539]
I want to let swiper automatically start, but not looping. I have the following configuration:

    var swiper = new Swiper("#mod-swiper", {
		direction: "horizontal",
		calculateHeight: true,
		speed: 1000,
		paginationClickable: true,
		nextButton: ".swiper-button-next",
		prevButton: ".swiper-button-prev",
		spaceBetween: 10,
		slidesPerView: "auto",
		loop: false,
		autoplay: 10,
		pagination: "#mod-swiper-pagination-container",
		centeredSlides: true,
		effect: "slide",
	});

After the page has loaded, swiper starts automatically to iterate trough the slides. After the last slide it starts again by the first one. But it should not as loop is set to false. Is there a configuration setting missing or is it a bug?

**Comment by nolimits4web** [comment]
Add `autoplayStopOnLast: true` parameter

**Comment by laoneo** [comment]
Is that parameter documented somewhere, I couldn't find it. Also in the code, it is not defaulted. I suggest either you document it or you remove it.
Honestly that's the parameter I was looking for, but it looked like it is a relic from an older version. That's why I'v opened that issue.
