### ISSUE TITLE
Disable height calculation

### ISSUE THREAD

**Issue by sebastiandammark** [nolimits4web/Swiper#1543]
How do I disable the size calculations of wrapper and slides ?

Link: http://radarlive.sheriffone.com:81/

Apparently it's doing it wrong, so I want to disable it.
I'm using this example: http://www.idangero.us/swiper/demos/02-responsive.html

And setWrapperSize is false by default.
I've tried adding it but neither true or false makes a difference.

I'm initiating this way:
var swiper = new Swiper(".swiper-container", {
  autoplay: 2000,
  slidesPerView: 1,
  loop: true,
  pagination: ".swiper-pagination",
  paginationClickable: true
})

**Comment by nolimits4web** [comment]
Link is not available, you probably need then to set `slidesPerView: 'auto'`
