### ISSUE TITLE
can't integrate in wordpress

### ISSUE THREAD

**Issue by michellomp** [nolimits4web/Swiper#1544]
I'm trying to integrate swiper 3D Coverflow Effect in wordpress 
I write this in the header.php
`<div class="swiper-container">
        <div class="swiper-wrapper">
            <?php
            global $post;
            $swiper_intro = new WP_Query(
                array(
                    'post_type' => 'publicite',
                    'category_name' => 'swipe',
                    'posts_per_page' => 3,
                )
            );
            ?>
             <?php while ( $swiper_intro->have_posts() ) : $swiper_intro->the_post(); ?>
                  <?php if ( has_post_thumbnail() ){?><?php $swipi = wp_get_attachment_image_src(get_post_thumbnail_id($swiper_intro->ID),'medium-thumb');?>
                                <div class="swiper-slide"style="background-image: url('<?php echo $swipi['0'];?>');"></div>
                            <?php } ?>
                    <?php endwhile; ?>
                <?php wp_reset_query(); ?>
        </div>
    </div>`
include correctly the swiper.jquery.min.js and the swiper.min.css files in function.php
and add

var swiper = new Swiper('.swiper-container', {
                        effect: 'coverflow',
                        grabCursor: true,
                        centeredSlides: true,
                        slidesPerView: 'auto',
                        coverflow: {
                            rotate: 50,
                            stretch: 0,
                            depth: 100,
                            modifier: 1,
                            slideShadows : true
                        }
    }); in my js but in the end i've got a white space in the swiper container 

Do you have any idea of what i'm doing wrong ?

**Comment by nolimits4web** [comment]
Have no idea. You probably have to ask it on StackOverflow or from WordPress developers
