### ISSUE TITLE
Parallax transition poor on some browsers

### ISSUE THREAD

**Issue by odnamrataizem** [nolimits4web/Swiper#1546]
Is it possible to add an option to *not* use CSS transitions for the parallax effects, falling back to using JavaScript + `requestAnimationFrame` instead? For simple setups CSS transitions suffice well, but more complex ones like [this][1] transition very poorly on some browsers, notably Firefox (notice how the background image fails to catch up with the rest of the transition, sometimes even scrolling in the opposite direction). From my testing, only on Safari (both OS X and iOS) and MS Edge on Xbox One does the cited example work smoothly with CSS transitions alone.

[1]: https://www.kantoradio.com.br/

**Comment by tychotycho** [comment]
Your link leads nowhere.

**Comment by odnamrataizem** [comment]
Weird, the link is working fine here... I could provide a jsfiddle, but in this case it might be better to see a real use case.

**Comment by nolimits4web** [comment]
No, it is not possible. And actually there is no difference in performance between CSS transitions and requestAnimFrame, and with JS solution you'll got worse peroformance
