### ISSUE TITLE
Как отключить мульти-прокрутку?

### ISSUE THREAD

**Issue by BeklievParviz** [nolimits4web/Swiper#1548]
Пример: https://jsfiddle.net/BeklievParviz/f2jy7s6s/embedded/result/

Не знаю даже как обяснить, но постараюсь.
Я не просто так, карусель расположил справа, в примере.

Итак, что я имею в виду под словосочетанием "мульти-прокрутка":
1. Зажать левой кнопкой мыши над каруселью
2. Потянуть влево (до упора)
3. Увидеть, как крутится не **на один** слайд, а **на несколько**.

Вопрос: как отключить эту "мульти-прокрутку" или как сделать так, чтобы прокручивался максимум до 1го слайда (не больше)?

**Comment by nolimits4web** [comment]
Так сделать нельзя, такой возможности не предусмотрено

**Comment by BeklievParviz** [comment]
И что теперь делать?
А можно ли каким-нибудь другим способом это реализовать?
