### ISSUE TITLE
Как получить размер слайда, и/или содержимого внутри него, например картинки, после загрузки слайда?

### ISSUE THREAD

**Issue by intsitesdotru** [nolimits4web/Swiper#1549]
Как получить размер слайда, и/или содержимого внутри него, например картинки, после загрузки слайда? Попробовал использовать колбеки onInit и onImagesReady, но там не успевает вычислиться размер корректно, нужно что-то вроде onReady, но не вижу его.
Например
var swiper = new Swiper('.swiper-container', {
  slidesPerView: 4,
  spaceBetween: 40,
  onInit: function(swiper){
                    console.log($(swiper.slides).filter('.swiper-slide-active').find('img').height()); // здесь выводится не корректный размер
                    setTimeout(function(){
                        console.log($(swiper.slides).filter('.swiper-slide-active').find('img').height()); // , а здесь корректно
                    }, 4000);
                }
})

**Comment by nolimits4web** [comment]
Нужно использовать это в onImagesReady

**Comment by intsitesdotru** [comment]
При использовании onImagesReady вместо onInit, такой же эффект, размеры не корректны

**Comment by nolimits4web** [comment]
> При использовании onImagesReady вместо onInit, такой же эффект, размеры не корректны

Хотелось бы увидеть живой пример или лучше JSFiddle с такой проблемой
