### ISSUE TITLE
Clicking on Links is sometimes prevented in Chrome on Windows

### ISSUE THREAD

**Issue by mstra001** [nolimits4web/Swiper#1552]
I am opening this page in chrome:
http://www.idangero.us/swiper/

Clicking on the links, e.g. API does not trigger anything.

Opening the same page in a new window and clicking again opens the API page.
To me it looks like the problem is in these lines, if I comment out the setTimeout everything works fine.

```
            setTimeout(function () {
                if (s) s.allowClick = true;
            }, 0);
```

https://github.com/nolimits4web/Swiper/blob/d8c79ceb2752314f7ad5ca6e96fc70d61ca72ac0/dist/js/swiper.js#L1508

I have no explanation why this issue occurs only sometimes but if it occurs, it occurs in every tab. Only opening a new window changes the behaviour.

Maybe someone can have a look on this - I am watching this over 4 month so this should be a major problem for everyone using this slider in production.

**Comment by nolimits4web** [comment]
That is Chrome + Windows issue only, there is no workaround yet

**Comment by zhongdeliu** [comment]
Any news about this topic. I would say Chrome+Windows is a pretty common combination...

**Comment by petermekhaeil** [comment]
@nolimits4web do we have any idea what is causing it or some form of work around? Happy to help if we have direction from any existing investigation.

Cheers,
Peter

**Comment by stentas** [comment]
Looks like I was in the wrong thread (#1584) for this bug

What is the status of this bug @nolimits4web?

**Comment by stentas** [comment]
I have found a workaround for the problem.

1. Put your link inside the wrapper  `<div className="links">`
2. Add the following callback call to the swiper element:
`onClick: function(swiper, e) {e.preventDefault(); }`

This solved it for me.

**Comment by prasademc** [comment]
@nolimits4web Please let us know the status of this bug?

**Comment by klaussilveira** [comment]
Updates, @nolimits4web?

**Comment by adamdilibero** [comment]
Is there any update on this? @nolimits4web
