### ISSUE TITLE
Slider broken on window resize with effect fade

### ISSUE THREAD

**Issue by pmoseas** [nolimits4web/Swiper#1556]
If the effect is set to "fade" with a fade duration of 1500ms for example - if you resize the browser during the fade process the slides get broken and displaced. It doesn't get fixed with .update()
Anyone have a solution? Thanks!

**Comment by nolimits4web** [comment]
Can't replicate it. Do you have a live example with the issue? Also make sure you are using latest version

**Comment by pmoseas** [comment]
Hi,
Thanks for replying!
Using the latest version.

Example: http://vids.im/slider/index_slider.html

Effect is fade.
Slides get displaced if you resize (or maximize/minimize) the browser 
window exactly during the fade effect.
In this example I deliberately set the fade duration to 4500 
milliseconds so it will be easier for you to observe.
Try to maximize/minimize browser during the fade between two images.

Regards

**Comment by nolimits4web** [comment]
It is fixed now in dev version

**Comment by pmoseas** [comment]
Many thanks!
