### ISSUE TITLE
Pagination render window resize

### ISSUE THREAD

**Issue by anteksiler** [nolimits4web/Swiper#1557]
I am adding captions to bullets using:

````
onInit: function(swiper) {
    for (var i = 0; i < swiper.bullets.length; ++i) {
        $(swiper.bullets[i]).html('<em>'+$(swiper.slides[i]).data('title')+'</em>');	
    }
},
````

However, whenever I resize the window, the pagination titles are gone. Couldn't find which callback I should change that. I could not use the above function with "paginationBulletRender" as it does not have the swiper instance.

**Comment by nolimits4web** [comment]
> I could not use the above function with "paginationBulletRender" as it does not have the swiper instance.

You can use it. Instead of instance you can use it like: `$('.swiper-slide').eq(i).data('title')`
