### ISSUE TITLE
When open the loop mode,the index of slides will be confused

### ISSUE THREAD

**Issue by simplecooler** [nolimits4web/Swiper#1559]
Especially between the first slide and the last slide.

**Comment by nolimits4web** [comment]
Everything is correct, it is because of duplicated slides. Do the search here or on forum

**Comment by simplecooler** [comment]
I'm sorry,I didn't discribe the question correctly.The problem I met is when I open the loop mode,the swiper.activeIndex  will not direct to the right slide.

**Comment by nolimits4web** [comment]
> This is correct. activeIndex is the index number of currently active slide HTMLElement. In loop mode there are duplicated slides
