### ISSUE TITLE
autoHeight not working with cube transition

### ISSUE THREAD

**Issue by julians** [nolimits4web/Swiper#1560]
Hello,

the height is not updated correctly when using the cube transition. It’s probably because `.swiper-slide` is set to `height: 100%` in the CSS.

**Comment by nolimits4web** [comment]
It doesn't suppose to work with Cube. How do you imagine a cube with different size sides

**Comment by julians** [comment]
Ah okay. I had imagined it would’ve resized after transitioning, with empty space or contents being cut off while doing so. (It’s a very tall cube so you never see its entirety, I mainly though the transition looked cool ;))
