### ISSUE TITLE
Missing semicolon at the end of Swiper 2 scrollbar plugin

### ISSUE THREAD

**Issue by wiest** [nolimits4web/Swiper#1563]
I'm using Swiper 2 for browser compatibility reasons (it's so sad legacy browser compatibility has been abandoned in v3!).
It took me an hour to figure out why my scrollbar plugin didn't work, when loading in the plugin API section of the main swiper, the _this.plugins object was always {scrollbar: undefined}, which was obviously caused by a missing semicolon in the scrollbar plugin file (at the end).

This doesn't seem to be an issue when the file is loaded separately (separate script tag) like in the demo, but breaks when merged together into one big JS file.

Maybe this is also true for other plugins, I haven't checked. Adding the semicolon fixed the problem for me, just wanted to let you know.

**Comment by nolimits4web** [comment]
IE 7/8? :smile: 

Sorry, but 2.x is not in development anymore and there will no be new fixes for it

**Comment by wiest** [comment]
Is v3 compatible from IE9 on? I couldn't find that information anywhere. You're lucky if you are allowed to just laugh about old browsers, I'd like to, too :-) But when dealing with corporate clients, the IE8 share is still there, not big, but big enough to force you to support it. We managed to unsupport IE6+7 a while ago, which was a nice relief.

**Comment by nolimits4web** [comment]
Yeah, remember those times. Swiper v3 is actually IE 10+, so i guess yes, you need Swiper 2, but anyway just add that semicolon manually and problem solved
