### ISSUE TITLE
Transition interrupts & freezes on prev/next button click

### ISSUE THREAD

**Issue by muratsalma** [nolimits4web/Swiper#1564]
If you click (mouse click) prev or next button before a slide transition ends, it interrupts/freezes transition.
Just set a high duration for slide animation, click next button (start transition), before this transition ends click next button again and it freezes.
Navigation bullets work well, only prev/next buttons cause this.
If you drag frozen slide with mouse it starts to working again.

**Comment by nolimits4web** [comment]
Need to see live example or JSFiddle as i can't replicate it

**Comment by muratsalma** [comment]
i think it's gone after 3.2.7, sorry, closing issue.
