### ISSUE TITLE
Track swipe progress after touch/click event stops

### ISSUE THREAD

**Issue by superfunkminister** [nolimits4web/Swiper#1570]
I'm trying to track the progress of my slideshow using the `onProgress(swiper, progress)` callback, however I stop getting the event when the touch/mouse event ends, rather than when the slide actually finishes animating. Is there a way around this?

**Comment by nolimits4web** [comment]
Was discussed many times here and on forum, try the search. This is how CSS transition works, there is no "trackable" middle state
