### ISSUE TITLE
Nested slider jumping

### ISSUE THREAD

**Issue by bramvanderholst** [nolimits4web/Swiper#1571]
When on the second to last slide on a nested slider and you swipe past the last slide (as shown in the video below) the parent slider snaps to the next slide instantly without any animation/followFinger. 
http://cl.ly/1R0k0i0q3z1e

This looks especially weird when the parent slider is already on the last slide;
http://cl.ly/281g120a2u0C

Any ideas?
Thanks
-Bram

**Comment by nolimits4web** [comment]
Yes, see the issue, will fix it
