### ISSUE TITLE
firefox tab navigation between slides set by order an not by html

### ISSUE THREAD

**Issue by DorinLevi** [nolimits4web/Swiper#1572]
hello,
I've realised that in chrome and explorer the 'tab' navigation using the keyboard between slides is as the order they appear in the HTML (as should be in my opinion)
in firefox the tab navigation is like the 'order' that is set in the inline style of the element.
can you please add support for tab navigation?
we are using it in our project for cato support. (inside the slide i have another buttons so that tabindex ignore them, thats why i cant set an order of my own)
an example for the behavior on firefox is in the next link:
https://jsfiddle.net/nxddsxo3/

Thanks.

**Comment by nolimits4web** [comment]
There is no tab navigation support in Swiper (which is mobile first by the way) and probably won't be. It is an ugly thing and make things broken in such layouts which doesn't respect CSS transform and overflows :smile: 

P.S. You can control order of tab navigation using `tabindex` attribute
