### ISSUE TITLE
Vertical scrollbar for each horizontal swiper-slide item

### ISSUE THREAD

**Issue by pilouf** [nolimits4web/Swiper#1573]
Hi,

I want to activate the "Scroll Container" function for each "swiper-slide" in my horizontal swiper. I tried, again and again and I think I miss something. Could you tell me what's wrong ?

My HTML demo page is accessible here : http://guillaumecaron.fr/swiper-demo/00TEST.html

Thanks for your time

**Comment by nolimits4web** [comment]
Is there any sense you use `autoHeight` on parent swiper if you want to do scrolling inside? You should disable it

**Comment by pilouf** [comment]
Just do it here : http://guillaumecaron.fr/swiper-demo/01TEST.html

Unfortunately that doesn't solve the problem :(

**Comment by nolimits4web** [comment]
Few CSS tweaks left. Set `height: 100%` on parent/horizontal slides and `height: auto` for child/vertical slides

**Comment by pilouf** [comment]
It's working :)

Thanks for your support !

Horizontal swipe isn't easy on mobile, is that normal ?

**Comment by nolimits4web** [comment]
What do you mean by `isn't easy on mobile`?
