### ISSUE TITLE
Event Feature Request - onPaginationReady

### ISSUE THREAD

**Issue by itbeyond** [nolimits4web/Swiper#1576]
I have the need to know when the pagination is completed being drawn as it also changes with browser resize and other updates so I have added the following after line 1028 to add an onPaginationReady event. Could this be included in the base:

s.emit('onPaginationReady', s);

I and using this as I have a requirement to add an additonal button to the pagination line. I tried using the onProgress event but this did not work correctly on init.

**Comment by itbeyond** [comment]
Oh yeah I also use this event to hide the pagination when there would only be one bullet created using this code.

    if (s.slides.length <= s.params.slidesPerView) { $(s.params.pagination).hide(); } else { $(s.params.pagination).show(); }

So this could be enhanced to add an option like paginationSingleButtonHide

**Comment by itbeyond** [comment]
Sorry I accidental hit close - is there a reason you closed this.

**Comment by Nauman7** [comment]
Guys in my scenario, I am running my code to hide two pagination bullets, for example there are total 8 swiper slides with 8 pagination bullets I want to show only 6 bullets.

I run my code as 
onInit: function () {
$(".swiper-pagination").each(function () {
      $(this).find("[class*=swiper-pagination-bullet]:last").prev().andSelf().hide();
            });
}

its working some time, but when page render completely it showing 8 bullets again.

**Comment by itbeyond** [comment]
Nauman7 - I open a new request for this as I accidental closed this one. What you are doing is the exact reason we need the onPaginationReady event as the pagination buttons are redrawn on several events including resize and update however the onInit is only called once when the swiper is initialized.

If you make the mod I suggested above and the change your onInit to onPaginationReady it will work 100% of the time.

Can you please add your comment in the new Issues post at https://github.com/nolimits4web/Swiper/issues/1577
