### ISSUE TITLE
Event Feature Request - onPaginationReady

### ISSUE THREAD

**Issue by itbeyond** [nolimits4web/Swiper#1577]
I have the need to know when the pagination is completed being drawn as it also changes with browser resize and other updates so I have added the following after line 1028 to add an onPaginationReady event. Could this be included in the base:

    s.emit('onPaginationReady', s);

I and using this as I have a requirement to add an additonal button to the pagination line. I tried using the onProgress event but this did not work correctly on init.

 I also use this event to hide the pagination when there would only be one bullet created using this code.

    if (s.slides.length <= s.params.slidesPerView) { $(s.params.pagination).hide(); } else { $(s.params.pagination).show(); }

So this could be enhanced to add an option like paginationSingleButtonHide

**Comment by nolimits4web** [comment]
Add `onPaginationRendered` event/callback
