### ISSUE TITLE
resize fullPage swiper

### ISSUE THREAD

**Issue by zolasty** [nolimits4web/Swiper#1581]
Hi, I have bug with resize fullPage slider with efect: fade, and image on background. It's happen when I change size from fullPage bronswer to smaller (not when resize).

**Comment by nolimits4web** [comment]
Are you sure you are using latest 3.3.0 version of Swiper?

**Comment by zolasty** [comment]
Swiper 3.1.7... Thank you. I will replace it for all my pages.

**Comment by zolasty** [comment]
I replaced it. But it don't work properly yet.
Example:
http://www.impresjaslubna.pl/
Bug is when I change window browser from full page mode to smaller window and when I back to full page.

**Comment by nolimits4web** [comment]
Link doesn't seem to work

**Comment by zolasty** [comment]
Now is working.
Second link http://zelnar.technetium.com.pl user test pass 654
On this page height slider is count in .js file but effect with bug is easier to repeat. When I turn on firebug on browser and trun on/turn off mobile mode (fast change witdth - no resize) slider is lost width for sliders.

**Comment by nolimits4web** [comment]
To be honest i can't see issue, but you didn't update Swiper to latest version. You also need to update its CSS file

**Comment by zolasty** [comment]
Ok, thanks, I changed. 
Someone make gif with the bug with the same effect:
https://raw.githubusercontent.com/ningshen/swiper-resize0bug/master/img/bug.gif

**Comment by nolimits4web** [comment]
It is different thing, it is about autoplay and hidden tabs. You may use JS Page Visibility API to stop/start autoplay when your page becomes visible/hidden. There are a plenty of solutions of this on Swiper forum, check there
