### ISSUE TITLE
lazy not called on resize

### ISSUE THREAD

**Issue by Kilbourne** [nolimits4web/Swiper#1582]
I have a slider with slidesPerViews: auto and lazy loading with watchSlidesVisibility.
when the browser get initial loading with one slide,on resize with more slides, these slides are not lazyloaded. visibility class is set right but lazy is not called. i give a rapid watch to the code and seems me that lazy is called only on init and not in resize handler?

**Comment by Kilbourne** [comment]
Ok , i have to modfied  the updateSlidesProgress function in core.js:    

    if (isVisible) {
                s.slides.eq(i).addClass(s.params.slideVisibleClass);
                if (s.lazy && s.params.lazyLoading){
						s.lazy.loadImageInSlide(i);
                }
    }

**Comment by nolimits4web** [comment]
Are you sure you are using latest 3.3.0 version? Would be good to see live example or JSFiddle with that issue then

**Comment by Kilbourne** [comment]
ok i have created [an example](http://www.menthalia.com/frontend-test/swiper-test.html)...
The slider have slidesperviews defined by css... when you get initial page load at mobile width and then resize to full screen images are not loaded.
The little commit [resolve this](http://www.menthalia.com/frontend-test/swiper-test2.htm).

But i have another problem: the onSlideChangeStart and onSlideChangeEnd callbacks are not fired when change slide by drag. I don't know if this is by design( but in that case the names are a little misleading) but i cannot find the callback for this case.
In the previous examples i've putted a callback which log these events...

**Comment by Kilbourne** [comment]
The last issue i was refering is already raised https://github.com/nolimits4web/Swiper/issues/1579

**Comment by Kilbourne** [comment]
Have you seene the examples?

**Comment by Kilbourne** [comment]
Your commit doesn't resolve the issue. recheck the [example](http://www.menthalia.com/frontend-test/swiper-test.html). I've updated swiper

**Comment by nolimits4web** [comment]
It is not in dist version yet, check the build version
