### ISSUE TITLE
"Loop + Pagination" Parameters with Breakpoints doesnt work

### ISSUE THREAD

**Issue by mertosman** [nolimits4web/Swiper#1585]
Example code:

``` javascript
var mySwiper = new Swiper('.swiper-container', {
        loop: true,
        pagination: '.swiper-pagination',
        slidesPerView: 4,
        slidesPerGroup: 4,
        breakpoints: {
            480: {
                slidesPerView: 1,
                slidesPerGroup: 1
            },
            767: {
                slidesPerView: 2,
                slidesPerGroup: 2
            },
            1200: {
                slidesPerView: 3,
                slidesPerGroup: 3
            }
        }
    });

```

it works if I remove the loop parameter. But, i use loop paremeter, plugin doesn't work.

Console error: "Uncaught TypeError: Cannot read property 'classList' of undefined".

Can you fix this please?

**Comment by mertosman** [comment]
Hello, can u here me ?

**Comment by nolimits4web** [comment]
Breakpoints is not supported with `loop` at the moment

**Comment by jmwohl** [comment]
This issue seems to have reappeared with release of v4 :/ ...

**Comment by darrena092** [comment]
Has indeed, 4.0.1 is affected anyways.

**Comment by darrena092** [comment]
Actually, seems to work in 4.0.2 again.

**Comment by jmwohl** [comment]
Great, thanks for posting the update — I ended up building it locally with the latest code base and it worked, so figured it would be working in an upcoming release.
