### ISSUE TITLE
Fixed height and variable width slides

### ISSUE THREAD

**Issue by lcolarieti** [nolimits4web/Swiper#1588]
Hi all,
I'm trying to set a slider with fixed height and different slide width.
On page load everythings is okay but when I resize my window or simply change my device orientation photos are stretched.
I try to update, destroy and reinit slider without getting the result.
Thanks

**Comment by nolimits4web** [comment]
Look here http://www.idangero.us/swiper/forum/#!/general:some-directional-help-neede

**Comment by lcolarieti** [comment]
Many thanks, you made my day :+1: 
Bye
