### ISSUE TITLE
onSlideChange not always fired in freeMode

### ISSUE THREAD

**Issue by r1m** [nolimits4web/Swiper#1590]
I have an horizontal slider with sticky free mode.
I want to be notify when the active slide changes.

I tried `slideChangeStart`, `slideChangeEnd` but they are not fired if we grab the swiper to change the active slide for less than 3 slide (forward or backward).
Same thing with `slideNextStart`. 

I was able to track any changes with `progress` event, but it is fired way too often, even if the slide hasn't changed. I have to filter it to be usable.

**Comment by ram-one** [comment]
Same problem with mouseWheel changes.

**Comment by braininteractive** [comment]
Did you find solution ?

**Comment by r1m** [comment]
I used a workaround. Listen for ```progress``` event with debounced callback and check that ```activeIndex``` has changed. Approximative code

```js
 function onProgress() {
      var index = swiper.activeIndex,
      index = index % swiper.slides.length; //if swiper is looped
      if (index  !== lastIndex) {
        //do something
      }
    }
swiper.on('progress', _.debounce(300, onProgress));
```

**Comment by shawnnaquin** [comment]
```
onProgress: function(swiper, progress) {
    var len = swiper.slides.length;
    var n = len+1;
    var curr = Math.round(progress*len) % n;
    console.log(' onProgress', curr );
},
```

**Comment by shawnnaquin** [comment]
use the swiper option 'onProgress', 
count just needs to be stored anywhere outside of onProgress,
add a debounce or setTimeout if you want.

```
count:1,
onProgress: function(swiper, progress) {
    var len =  swiper.slides.length;
    var l = Math.round( progress*len ) % (len+1) - 1;
    if ( l != this.count && l >= 0 ) {
        this.count = l;
        console.log( swiper.slides[this.count]);
    }
},
```

**Comment by shawnnaquin** [comment]
similar to r1m's answer, but this worked slightly better for me:
count:1,
onProgress: function(swiper, progress) {
    var len =  swiper.slides.length;
    var l = Math.round( progress*len ) % (len+1) - 1;
    if ( l != this.count && l >= 0 ) {
        this.count = l;
        console.log( swiper.slides[this.count]);
    }
},

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
