### ISSUE TITLE
swiper.params.control bug

### ISSUE THREAD

**Issue by dajbd** [nolimits4web/Swiper#1591]
in the demo:
Swiper-3.3.0\demos\23-thumbs-gallery.html

open it in your PC,
use mouse slide to 8th image, 
Up and down two pictures, not the same.
pls fix it.

 Chrome	47.0.2526.106  m 32bit

**Comment by nolimits4web** [comment]
Can't see such issue, everything is on the place

**Comment by dajbd** [comment]
I stay in China, maybe the images not loaded success / or in loading, cause the bug.
I can reproduce the bug.

**Comment by dajbd** [comment]
you can use chrome dev tool , simulate the situation, make image load slowly.
