### ISSUE TITLE
Idnangero Swiper is not working for Dynamic data 

### ISSUE THREAD

**Issue by NaveenGB** [nolimits4web/Swiper#1592]
This is html content

 <div class="swiper-container">
        <div class="swiper-wrapper">
           <div class="swiper-slide" id="contentDiv">------>am adding dynamic content here<------
           
        </div>
        
        
        </div>
        
	<div class="swiper-pagination"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>

and this is script
 <script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        spaceBetween: 30
    });
    </script>

Is there anything else, Please help me

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle

**Comment by NaveenGB** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="author" content="">
	<meta name="description" content="">
	<title>Demo</title>
	
	<script>document.documentElement.className = 'js';</script>
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.5">
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
    <link href="css/main_ui.css" rel="stylesheet" type="text/css" media="all" />
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
	
	<link rel="stylesheet" type="text/css" href="css/template.theme.min.css" />
    <link rel="stylesheet" type="text/css" href="css/template.min.css" />
     <link rel="stylesheet" href="css/swiper.min.css">
	
	

<link type="text/css" rel="stylesheet" href="css/jquery.mmenu.all.css" />

<script src="js/bootstrap.min.js"></script>
<script src="js/jquery-1.11.0.min.js"></script>
<script src="js/index.js"></script>
	
<script type="text/javascript" src="js/jquery_lib.js"></script>
<script type="text/javascript" src="js/jquery.mmenu.min.all.js"></script>
<script type="text/javascript">
$(function() {
$('nav#menu').mmenu();
});
</script>

	
	<script type="text/javascript"  src="js/loader.js"></script>
<script type="text/javascript"  src="js/loaderdemo.js"></script>
<link type="text/css" rel="stylesheet" href="css/loader.css" />
</head>

<body onload="">


<div id="wrapper">

  
     
		<div id="page">
        <div class="col-xs-12">
        <div class="row">
        <div class="col-xs-2 row"> <span class="header"><a href="#menu"></a></span></div>
        <div class="col-xs-6 col-xs-offset-2 row"><div class="header_icon_logo logo_middle_area"> <img src="images/ion-time-logo-2.png"></div></div>
         <div class="col-xs-3 row right_area"><div class="header_time_login" id="showdate"></div>
        <div class="header_icon_reminder"><a href="set_reminder.html"><img src="images/reminder_icon.png"></a></div>
        <div class="header_icon_logout"><a onclick="deleteLocalStorage()" ><img src="images/log_out.png"></a></div>
        </div>
          </div>
          </div>
            
<nav id="menu">
<ul>
<li><a href="mytimesheet_admin.html">Home</a></li>
<li><a href="create_new_timesheet.html">My Timesheet</a></li>
<li id="pendingTM"><a href="pending_timesheet.html">Pending Timesheets</a></li>
<li><a onclick="checkAction();" >Log Current Time</a></li>
<li><a onclick="swipeInSwipeOut();">Swipe In Swipe Out</a></li>
</ul></nav> 

</div>  
    
  
</div>

  
  <div class="clearfix"></div>
  
      <div class="swiper-container">
        <div class="swiper-wrapper">
           <div class="swiper-slide" id="contentDiv"><-----Ajax call ---->
           
        </div>
        
        
        </div>
        
	<div class="swiper-pagination"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
    
    <div class="clearfix"></div>
	<br>
    <div id="footer">
    	<div class="col-xs-12 cent"><a href="#" class="hover_color" onclick="approveRejectTimeSheets();"><img src="images/approve_btn.png">Submit</a></div>
    </div>
	
	
	<script src="js/swiper.min.js"></script>
	<script src="js/jquery.event.move.js"></script>
	<script src="js/jquery.event.swipe.js"></script>
	<script>
		(function(jQuery, undefined) {
			jQuery(document).ready(function() {
			
			getURLValues();
	
			
			}); 
			
		})(jQuery);	
		
	</script>
	 <script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        spaceBetween: 30
    });
    </script>
	<section class="demo">
 <p><input type="hidden" class="btn_grey_b" id="btn1" /> </p>
</section>
<section class="maskui_dialog" id="maskuiDialog1" >
<img src="images/loader.gif" style="height:70px;width:70px;visibility:hidden;" id="limg"/>
<a href="#" class="dialog_close" id="close" style="visibility:hidden;"></a>

</section>
 <script type="text/javascript" src="cordova.js"></script>
</body>
</html>

**Comment by NaveenGB** [comment]
I have created with swipe.js(Jquery), swipe is working fine am unable to get the pagination(Arrows)

**Comment by nolimits4web** [comment]
Sorry, i can't do anything with this code. Need to see `live` example or `JSFiddle` as a link which i can open and see the issue

**Comment by NaveenGB** [comment]
Sorry am unable replicate this issue, can u please suggest me how to replicate mobile app issues online because am new to mobile app development.

**Comment by nolimits4web** [comment]
It is a bit tricky with cordova app, you probably need to remove all cordova-related code in this demo and upload your project's `www` folder to somewhere online

**Comment by NaveenGB** [comment]
Hi,

Take your example itself which one you created for "Navigation Buttons", and can you make it for dynamic pages? or else just give hint

**Comment by nolimits4web** [comment]
Work without any problems:
```html
<div class="swiper-container">
    <div class="swiper-wrapper"></div>
</div>
```
```js
// Add slides dynamically
for (var i = 0; i < 10; i++) {
    $('.swiper-wrapper').append('<div class="swiper-slide">Slide ' + i + '</div>');
}
// And init swiper
var swiper = new Swiper('.swiper-container');
