### ISSUE TITLE
Multiple clicks on previous or next buttons result in animation stopping

### ISSUE THREAD

**Issue by DenysYefimenko** [nolimits4web/Swiper#1593]
If I press next button multiple times fast enough swiper freezes its current animation and stops reaction on clicks from both next and prev buttons. Clicking anywhere on slide restores swiper state so it is receiving click events and animates again.

**Comment by nolimits4web** [comment]
Chrome+Windows i guess?

**Comment by DenysYefimenko** [comment]
Correct. But looks like it has been fixed.
