### ISSUE TITLE
bug with slides height in Chrome

### ISSUE THREAD

**Issue by vididesign** [nolimits4web/Swiper#1596]
Hi, may be it's not a script problem, but i have a bug in Chrome using swiper as scrollable news list.
Swiper container has fixed height and each swiper slide contains one news item and has auto height.
In every browser it works great except Chrome. It sets slide height to container height on page load. 
Sometimes after f5 reload it displays correctly.

live example
http://vididesign.ru/scroll.php

**Comment by graybeltran** [comment]
I'm seeing a similar issue in Chrome only with slide width getting calculated incorrectly (ie way too wide). Was working fine on Friday.

**Comment by vididesign** [comment]
tried to set fixed width for slides 50px smaller than container. same trouble. :(

**Comment by nolimits4web** [comment]
@vididesign looks like new Chrome brings new issues. Remove `display: inline-block` from your `#flow .swiper-slide` CSS tule and add `min-height: 0` to same slide's rule.

@graybeltran i can't replicate the issue with widths, but i guess solution can be the same by setting:
```css
.swiper-slide {
  min-width:0;
}

**Comment by graybeltran** [comment]
@nolimits4web The issue seems to be that the swiper slides' width is being calculate based on the width or max-width of the swiper container's parent, which wasn't the case before.

**Comment by nolimits4web** [comment]
@graybeltran slides' width is calculated depending on `swiper-container` width only, not anything else, unless you have `slidesPerView: 'auto'`. If you have such issue then it probably something wrong with CSS or something else. Would be good to see example with such issue

**Comment by graybeltran** [comment]
@nolimits4web here's a codepen example: http://codepen.io/anon/pen/GoBYzZ

Note how the swiper slideshow appears correctly in Safari but not Chrome.

**Comment by nolimits4web** [comment]
@graybeltran actually everything is correct. This is how flex works, just add this to CSS:
```css
.column {
  min-width: 0;
}

**Comment by nolimits4web** [comment]
https://www.w3.org/TR/css-flexbox/#flex-common

> By default, flex items won’t shrink below their minimum content size (the length of the longest word or fixed-size element). To change this, set the min-width or min-height property.

**Comment by graybeltran** [comment]
@nolimits4web that worked, thanks! I don't know why it was working before.

**Comment by vididesign** [comment]
i did what you suggest

> #flow .swiper-slide {
	min-width: 0;
	height: auto!important;
	-webkit-box-sizing: border-box;
	box-sizing: border-box;
}

but problem still there :*(
http://vididesign.ru/scroll.php

**Comment by nolimits4web** [comment]
@vididesign i recommended you to set `min-height: 0` not `min-width` ;)

**Comment by vididesign** [comment]
oh, sorry :)
now its works good!
thanks!
