### ISSUE TITLE
Looping of groups is buggy

### ISSUE THREAD

**Issue by teejayhh** [nolimits4web/Swiper#1597]
Hello I have a slight problem explaining the exact problem but I think its some combination of the loop property + group and slidesPerView which causes: 
```
Uncaught TypeError: Cannot read property 'nodeType' of undefined

n.fn.extend.addClass @ jquery.js:7183
y.updateClasses @ swiper.jquery.js:938
y.onResize @ swiper.jquery.js:1111
``` 

I made a little codepen to show the issue.
http://codepen.io/teejayhh/pen/rxKgWv

try resizing and you will see the error coming up.

**Comment by nolimits4web** [comment]
Will check it, looks like related/same as #1585

**Comment by teejayhh** [comment]
With certain combinations of content it will fail from the start no matter if a breakpoint triggers.

**Comment by teejayhh** [comment]
Did I ever say that swiper is pretty amazing and has saved us a boat load of time. Thanks for all the work you have put into it !
