### ISSUE TITLE
Safari - Mac OS: With a uneven browser width content expands over it's container.

### ISSUE THREAD

**Issue by lvmh** [nolimits4web/Swiper#1599]
Hi,

on Safari 9.0.3 i'm experiencing trouble with content overflowing past it's container.

I can replicate this bug on http://www.idangero.us/swiper/demos/ with the "Slides Per View / Carousel Mode" demo.

If you adjust the browser width by 1 pixel you will see either  (please note the border/box shadow of the content)

Correct: ![screen shot 2016-02-03 at 12 38 26 pm](https://cloud.githubusercontent.com/assets/278196/12773094/16029064-ca73-11e5-84a0-770c98aebcbf.png)
or 
Incorrect (note the 2px border on the right hand side, and 0 px on the left hand side): ![screen shot 2016-02-03 at 12 38 34 pm](https://cloud.githubusercontent.com/assets/278196/12773100/1dde02f0-ca73-11e5-8fc2-753bc1ed7600.png)

The difference in display is causing issues on two websites that my company looks after.

I've tried adjusting the background color, fixed widths etc to no result.

Any ideas?

**Comment by nolimits4web** [comment]
Can't do much about it as this is how browser treats pixels rounding, you can try to enable `roundLengths: true` parameter
