### ISSUE TITLE
observer is loading in the last slide when loop = true

### ISSUE THREAD

**Issue by revxx14** [nolimits4web/Swiper#1601]
I have some Swipers in a tab system on a site I'm working on, and when I change a tab from display:none; to display:block; the Swiper gets reinitialized using the `observer` and `observeParents` parameters. This was working fine, until I set `loop` to `true`. Now they each load in the last slide in the deck rather than the first. I believe this is because when it's seeing the duplicated slides and counting them incorrectly upon re-initialization.

I think filtering for `.swiper-slide:not(.swiper-slide-duplicate)` upon initialization should fix the problem. I may try to fix this tomorrow; if I figure it out, I'll submit a pull request.

**Comment by revxx14** [comment]
Update on this: Apparently it's nothing to do with `observer`, and but is related to `loop: true` within an element that's `display: block;` before the Swiper gets initialized. I tried looking for a way to fix this, but your JavaScript is beyond my level :)

My workaround was to move my tabs way off screen (with `aria-hidden=true` set as well) so that they could initialize properly. Would still like a proper fix for this. Leaving open for now.

**Comment by nolimits4web** [comment]
Fixed, thanks

**Comment by revxx14** [comment]
Awesome, thanks much!
