### ISSUE TITLE
Swiper doesn't work properly unless called after DOM node is attached

### ISSUE THREAD

**Issue by rivertam** [nolimits4web/Swiper#1604]
I tried to dynamically create a Swiper slideshow using elements created by `document.createElement`. Some aspects of Swiper worked (such as scrolling) while others did not (such as snapping). These issues were resolved when I used `new Swiper` after attaching the elements to the DOM instead of before.

I think this behavior is reasonable, but Swiper should issue a warning or error if called on an unattached DOM node, and it should be noted in the documentation.

**Comment by nolimits4web** [comment]
You should expect that something what is heavily rely on styles/sizes and visuals in general may not work correctly when it is detached from DOM. There is no errors and warnings because Swiper actually works in this case, just call `swiper.update(true)` after you add it to DOM

**Comment by rivertam** [comment]
@nolimits4web Thanks! Didn't realize `swiper.update(true)` would fix it.
