### ISSUE TITLE
when swiper slides are less than one or zero then also one pagination bullet is visible?

### ISSUE THREAD

**Issue by amitchoubey** [nolimits4web/Swiper#1607]
Swiper shows one bullet when there is not swiper slides in swiper-wrapper.
Please tell me how can I solve this issue after swiper update also I am facing this issue.
I am using swiper 3.3.0 version.

**HTML**

    <div class="swiper-container">
        <div class="swiper-wrapper">
           
        </div>
        
        <div class="swiper-pagination"></div>
    </div>

**JS**
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true
    });

**Comment by nolimits4web** [comment]
Pagination doesn't reflect number of slides, it is reflected to number of "snaps". Just hide it manually when there is no slides
