### ISSUE TITLE
Swipeable-Tabs

### ISSUE THREAD

**Issue by jaiswalabhinav17** [nolimits4web/Swiper#1608]
Hi all,
I'm using material design for the Hybrid app development and I have used the "Swiper" in my project. It's really very great to have it. I have used Tabs in my project and to give the good user experience I would like to add the swipeable tabs. So instead of clicking, we can swipe between the tabs with the touch. 

Kindly, suggest me some solution to my problem.

Thanks in advance.

**Comment by nolimits4web** [comment]
And what is the problem? Just use Swiper and its callbacks if you need to update depending on slide. You can check how it is done in Framework7 at http://www.idangero.us/framework7/kitchen-sink-material/ go to Tabs -> Swipeable Tabs
