### ISSUE TITLE
Swiper 3.2.7 issue

### ISSUE THREAD

**Issue by AlainYahchouchi** [nolimits4web/Swiper#1609]
Hello,
I have a swiper slideshow:

 var slideshowSwiper = new Swiper('#slideshow .screen', {
        slidesPerView: 'auto',
        spaceBetween: 0,
        freeMode: true,
        autoplay: 1,
        speed: 70333,
        autoplayDisableOnInteraction: false,
        loop: true,
        preloadImages: false,
        lazyLoading: true,
        loopAdditionalSlides: 922299
    });

This slideshow consists of only and only 1 swiper-slide which is a very big image in width and therefore the speed of swiper  70333 to keep the swiper moving horizantally (loop is true).

However, problems occur when I want to pause the swiper.... stopAutoplay and startAutoplay arent helping in my case because the swiper will pause at the end of the swiper-slide motion which is 70333 long and restart after it (cz it is only 1 swiper-slide i am forced to structure it like that.....)

I used the following to instantly pause the swiper:
 var old_position = 0;
    $('#slideshow .plus').mouseover(function () {   //pause slideshow
        old_position = slideshowSwiper.getWrapperTranslate();
        $(this).parents('#slideshow').find('.swiper-wrapper').css({ 'transform': 'translate3d(' + old_position + 'px,0px,0px)' });
    });

This is fine however on mouseleave i want to directly resume the swiper from the instatntly paused position.... I cant figure out a way to do that on mouseleave....

any help?

**Comment by nolimits4web** [comment]
Swiper and its autoplay is not intended for such use case, stoping autoplay won't stop transition. You probably need to use some custom JS for your transition/animation. You can try something like Velocity.js
