### ISSUE TITLE
Exit swiper container after last slide

### ISSUE THREAD

**Issue by chrisalcantara** [nolimits4web/Swiper#1610]
Hello, 

I was wondering if it possible to exit the swiper container after swiping to the final slide. My slides take up the full width and height of my browser window and flows vertically.

Here's some basic code of the idea:
```
<div class="swiper-container swiper-container-full">
	<div class="swiper-wrapper">
		<div class="swiper-slides"></div>
		<div class="swiper-slides"></div>
		<div class="swiper-slides"></div>
	</div>
</div>

<!-- Ability to scroll down to div below the swiper container -->

<div class="new-div">
	<h1>Headline</h1>
	<p>Some paragraph text.</p>
</div>
```
I can't seem to find anything in the forums or issue logs. Any help or suggestions would be greatly appreciated. Thanks for an awesome library!

**Comment by nolimits4web** [comment]
What do you mean by "exit"? Would be good to see some live example or JSFiddle

**Comment by chrisalcantara** [comment]
Sure. Here's a [fiddle](https://jsfiddle.net/n0f99La4/2/).

For my situation, I'm using the [fullscreen, responsive](http://www.idangero.us/swiper/demos/03-vertical.html) vertical example. 

What I'd like to see is when a user gets to the final slide, they can scroll out – or exit as I mentioned – out of the container to another div written below the swiper container. 

I wrote a workaround in the fiddle, and it seems to work in my project for now. But I'd definitely be open for a simpler solution.

**Comment by arifchenko** [comment]
same issue here. and if I use `mousewheelControl: true` then the new div cannot be opened by scrolling. any solution?

here's a [fiddle](https://jsfiddle.net/n0f99La4/4/)

**Comment by rajeshtomjoe** [comment]
Please use **mousewheelReleaseOnEdges: true** for it to work

**Comment by nolimits4web** [comment]
@rajeshtomjoe 👍
