### ISSUE TITLE
Navigation & autoloop when 1 slide exists.

### ISSUE THREAD

**Issue by codegaze** [nolimits4web/Swiper#1612]
Shouldn't navigation be hidden and autoloop disabled when there is only one original slide inside the container? I'm using the latest github version in a development serve.

Sorry in advance if this is a problem with my configuration. 
If not, would be be interested for a PR if I try for a fix?

**Comment by nolimits4web** [comment]
No, it shouldn't. Someone may want to loop and autoplay one slide. Just don't enable it if you have only one slide and you don't need such behavoir

**Comment by codegaze** [comment]
Unfortunately its content is dynamic, but thanks for the answer. Maybe i'll set a setting to enable/disable the show/hide feature in the case of one slide.

**Comment by nolimits4web** [comment]
Just don't enable it then in case of one slide, for example something like:
```
autoplay: $('.swiper-slide').length > 1 ? true : false,
loop: $('.swiper-slide').length > 1 ? true : false

**Comment by codegaze** [comment]
This was very helpful @nolimits4web! Thanks!
