### ISSUE TITLE
Присвоить или убрать ссылке класс "active" после переключения или включения слайда 

### ISSUE THREAD

**Issue by Dornnn** [nolimits4web/Swiper#1614]
Здравствуйте!

Помогите пожалуйста, в скриптах разбираюсь только на ощупь, на уровне детского сада.

Перерыл весь интернет, удивляет насколько никто не использует Swiper в качестве основы на сайтах. В общем, задача банальная, допустим есть слайдер и меню:

```
<div class="nav">
  <a href="#" class="dog">Пес</a>
  <a href="#" class="fox">Лиса</a>
  <a href="#" class="cow">Корова</a>
</div>

<div class="swiper-container swiper-parent">
  <div class="swiper-wrapper">
    <div class="swiper-slide swiper-slide-dog"></div>
    <div class="swiper-slide swiper-slide-fox"></div>
    <div class="swiper-slide swiper-slide-cow"></div>
  </div>
</div>
```

Я нашел, как забиндить определенный пункт меню на переключение на нужный слайд и добавление класса "active":

```
var mySwiper = new Swiper('.swiper-container', {
	paginationClickable: true,
	direction: 'vertical',
	mousewheelControl: true,
	simulateTouch: false,
	hashnav: true,
	keyboardControl: true
 });

$('.dog').click(function(e) {
    e.preventDefault();
    $(".nav .active").removeClass('active');
    $(this).addClass('active');
    mySwiper.slideTo( $('.swiper-slide-dog').index(),500,false );
});
$('.fox').click(function(e) {
    e.preventDefault();
    $(".nav .active").removeClass('active');
    $(this).addClass('active');
    mySwiper.slideTo( $('.swiper-slide-fox').index(),500,false );
});
$('.cow').click(function(e) {
    e.preventDefault();
    $(".nav .active").removeClass('active');
    $(this).addClass('active');
    mySwiper.slideTo( $('.swiper-slide-cow').index(),500,false );
});
```

Допустим, мы на кнопки жмем, активное/не активное меняется, едем, а вот если мы колесиком мыши переключаем со слайда на слайд, как мне убрать/добавить "active" в соответствующие пункты меню? И никому главное оно не надо, никому не нужно подсвечивать активный пункт меню при переключении слайда =(

Пожалуйста помогите, горю..!

**Comment by nolimits4web** [comment]
http://www.idangero.us/swiper/forum/#!/questions:active-menu-items-when-swit
