### ISSUE TITLE
Lazy load first image/slide when in view

### ISSUE THREAD

**Issue by tonydieu** [nolimits4web/Swiper#1618]
I have slider that loads content from external/another source. I want to save some bandwidth by lazy load the first image /slide since the size can be very large.

Is it possible to lazy load first image / prevent loading data-src on init with current version 3.3.1?

I also want to load the image when it is visible in the browser view.

**Comment by nolimits4web** [comment]
Sorry, didn't get what is your question in? If the question, is there such feature as lazy loading, the answer is - yes http://www.idangero.us/swiper/api/#lazy

**Comment by tonydieu** [comment]
Sorry. The lazy load works and no issue here. My question Is it possible to prevent the first slide (image) to load/display?

I can see in chrome dev tools that the first image is loaded even though lazy load is enabled (normal behaviour). I was just wondering if you had a callback/method that can prevent the first image to be loaded on init. Basically I want to avoid the first slide/image to be loaded. - don't let the first slide/image change the data-src to src in the img tag. 

Use case:
I have a slider further down the page  (outside of the viewport). I use this slider to display images from an external source. I can't resize/shrink the image and sometimes the images can be really large. My strategy is to load the first image when the slider is visible in the viewport.

In some cases the visitor might not scroll down the page to see the slider so I want to avoid to load the extra kb from the first slide to save some load time.

 Many thanks!

**Comment by tonydieu** [comment]
I found a temporary solution by using [jquery lazy load](https://github.com/tuupola/jquery_lazyload) on the first slide. I changed the data-src to data-original on the first slide since the rest will be lazy loaded by swiper by still using the data-src. In the future this would be a nice-to-have feature to have if anyone else have the same use case.

Thank you @nolimits4web!
