### ISSUE TITLE
auto detect height

### ISSUE THREAD

**Issue by Dobby89** [nolimits4web/Swiper#162]
Feature Request:

Make it so the height of each slide is calculated automatically, instead of having to hard code the height inside idangerous.swiper.css.

This would be useful for mobile/responsive layouts where the width of images within the slideshow needs to be set at 100% to fill the full width of the screen.  It isn't possible to know the resultant height of the image if you're using 100% width and so it can't be set within a separate CSS file as it currently is.

**Comment by marlonlamancio** [comment]
Hi guys, how can I achieve this now in 3.0.7 version, i tried http://stackoverflow.com/questions/25946896/swiper-height-auto-resize but doesn't work. Thanks!

**Comment by nolimits4web** [comment]
@marlonlamancio in the same way. Look at example of @Novalis80, then only difference is that:
```
var activeSlide = swiper.activeSlide();
```
should be
```
var activeSlide = swiper.slides.eq(activeIndex);
```

**Comment by GoToBoy** [comment]
swiper 3.0 not include "calculateHeight" api , why not?

**Comment by CemHub** [comment]
Good question, why is the calculateHeight removed?

**Comment by nolimits4web** [comment]
@GoToBoy because it is not required with flex box layout

**Comment by CemHub** [comment]
1) Why did you remove the option in the first place? Users could decide for themselfs to drop IE8 support.

2) Will there be an example where flex-box is used as dynamic height?

**Comment by nolimits4web** [comment]
@CXHub You probably didn't understand how the `calculateHeight` option worked in Swiper 2.x and what it was for, nothing similar with setting different slider height for different slide. If you want to support old browser, just use Swiper 2.x
