### ISSUE TITLE
onInit doesn't appera to work.

### ISSUE THREAD

**Issue by revxx14** [nolimits4web/Swiper#1620]
I've got the following code snipet:

```
// change active swiper-menu-button on pagination
swiper.on("onSlideChangeStart", function(swiper) {

    // get the total slides
    var totalSlides = $(".swiper-slide:not(.swiper-slide-duplicate)").length;

    // get the new active slide
    var activeSlide = swiper.activeIndex;

    if (activeSlide > totalSlides) {
        activeSlide = 1;
    } else if (activeSlide < 1) {
        activeSlide = totalSlides;
    }

    // update the active thumbnail
    $(".swiper-menu-item.-active").removeClass("-active");
    $(".swiper-menu-item").eq(activeSlide - 1).addClass("-active");
});
```

This is used to handle some custom buttons that get marked as active as the slide paginates. Only problem is that it's not firing on init. I tried both of the following, neither of which worked:

```
swiper.on("onInit onSlideChangeStart", function(swiper) {
    ...
});
```

```
swiper.on("onInit", function(swiper) {
    ...
});
```

It seems that `onInit` may be broken (or maybe I'm just not understanding how to use it properly).

**Comment by revxx14** [comment]
For now, I'm using an additional bit of JavaScript for this, but I'd much prefer to merge the two:

```
$(".swiper-menu-item").eq(0).addClass("-active");
```

**Comment by ericmoff** [comment]
use in this way when you initialize swiper instance

```javascript
var mySwiper = new swiper('.swiper-container', {
    ...
    onInit: function(swiper){
        // do something
    },
    onSlideChangeStart: function(swiper){
        // do something
    }
});

```
or with Emitter API (http://www.idangero.us/swiper/api/#emitter):

```javascript
mySwiper.on('init', function(swiper){
    // do something
});
mySwiper.on('slideChangeStart', function(swiper){
    // do something
});
```

**Comment by revxx14** [comment]
So there's now way to merge these in to one? I kind of figured the `.on` worked the same way as `$(window).on("load resize", function() {...});`

**Comment by nolimits4web** [comment]
`onInit` can be used only as a callback parameter, because when you define it via emitter/event API it won't work because Swiper is already initialized to this moment. So can be used only like this:
```
var mySwiper = new swiper('.swiper-container', {
    ...
    // onInit only here!
    onInit: function(swiper){
        // do something
    },
 
});
