### ISSUE TITLE
swiper thumb gallery problem

### ISSUE THREAD

**Issue by AlainYahchouchi** [nolimits4web/Swiper#1623]
Hey,
I am using this demo of swiper the thumb gallery demo here: http://www.idangero.us/swiper/demos/23-thumbs-gallery.html

All is working properly but I noticed a bug only on chrome. Sometimes it works properly and sometimes not. The issue is that the little thumbnail images sometimes stop clicking but still drag.... only on chrome... firefox always working.... all other functionalities in this demo are always working in chrome however sometimes clicking on the bottom floated thumbnail images will not swipe the big slide.....
This bug wasnt in previous swiper versions.... it is in the demo itself so no need to post my code...

Any help?!?
Thankyou.
Alain from Lebanon.

**Comment by remtsoy** [comment]
+1

**Comment by gwarnants** [comment]
I got the same problem on Chrome with Swiper 3.3.1, but it is not easy to reproduce the problem.
A quick debug when the problem occurs brings me the `s.onTouchEnd()` function :
```javascript
 s.onTouchEnd = function (e) {
            // ...
            if (s.allowClick) {
                s.updateClickedSlide(e);
```
where `s.allowClick` seems to stay locked on `false`, so `updateClickedSlide()` is not called anymore

**Comment by AlainYahchouchi** [comment]
didnt work the bug is still on chrome sometimes
here is my code:

**Comment by AlainYahchouchi** [comment]
didnt find a solution yet..
here is my code
var galleryTop = new Swiper('#animation1 .screen', {
        spaceBetween: 0,
        slidesPerView: 1,
        nextButton: '#animation2 .next',
        prevButton: '#animation2 .prev'
    });

    var galleryThumbs = new Swiper('#animation2 .screen', {
        spaceBetween:20,
        centeredSlides: true,
        slidesPerView: 'auto',
        touchRatio: 0.2,
        slideToClickedSlide: true
    });

    galleryTop.params.control = galleryThumbs;
    galleryThumbs.params.control = galleryTop;

**Comment by jasonweng** [comment]
I also have a issue:

If the thumbs list width < container width, it didn't swipe to next thumb, please see attached:

`swiper-slide-active ` and `swiper-slide-next ` class didn't change and click on thumb didn't work too.

<img width="993" alt="screen shot 2016-03-30 at 5 50 15 pm" src="https://cloud.githubusercontent.com/assets/84782/14138489/17e06f1a-f6a0-11e5-8614-534d41fbd9d8.png">

<img width="1078" alt="screen shot 2016-03-30 at 5 54 16 pm" src="https://cloud.githubusercontent.com/assets/84782/14138571/772ccacc-f6a0-11e5-8e5c-aa6b24608c9d.png">



But if thumbs list width > container width, it works well.

Please check it out.

**Comment by josepaitamala** [comment]
Having the same issue here

**Comment by arnisjuraga** [comment]
+1

**Comment by arnisjuraga** [comment]
Are You using Lightbox for large image popup? I had the same problem, but switching from Lightbox to Photoswipe for large images, seems to be fixing the problem.

**Comment by Fulminant** [comment]
No, i don't use LIghtbox or Photoswipe. But i have found solution, to this problem. Only need to add option `centeredSlides: true`.

**Comment by Dralac** [comment]
+1

**Comment by adamcoulombe** [comment]
I had the same issue, here was my solution (this may or may not cause other undesired effects for you, depending on your configuration, but it seems to work well for me):

In the swiper.js file, Comment out [line 1515](https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L1515) 
`// var diff = s.touches.diff = s.isHorizontal() ? s.touches.currentX - s.touches.startX : s.touches.currentY - s.touches.startY; `

**Comment by C0deS1ayer** [comment]
+1

**Comment by ToBeCode** [comment]
+1

**Comment by ccebrand** [comment]
+1

**Comment by sitnikovalex** [comment]
+1

**Comment by tungvn** [comment]
I have same problem here and `centeredSlides: true` fix it all.
But I dont want to use `centeredSlides: true`. I tried to set it false but slide not working

**Comment by Benny29390** [comment]
+1

**Comment by awarche** [comment]
+1

**Comment by ApacheEx** [comment]
+1

**Comment by wangranxin** [comment]
👍

**Comment by darkkain** [comment]
+1

**Comment by smith64fx** [comment]
is there any fix? I really like this feature but it's not really production ready with this bug.

**Comment by smith64fx** [comment]
I know what's the problem. I'm gonna fix it

Just add this and you will know what's the problem.
```
        onTouchStart (swiper, event) {
          console.log('start')
        },
        onTouchMove (swiper, event) {
          console.log('move')
        }
```

If you click with your mouse and you move it afterwards some pixels, it will be an ultra-small swipe of 1-5px. That means, your click isn't recognized as a click but as an swipe to left/right.

So if you click and move your mouse strong enough it will swipe to left/right.

**Comment by smith64fx** [comment]
Hey guys,
here is the final solution. So simple but it works!

Just add this hook to your swiper config.
```
        onTouchEnd (s, e) {
          let range = 5
          let diff = s.touches.diff = s.isHorizontal() ? s.touches.currentX - s.touches.startX : s.touches.currentY - s.touches.startY
          if (diff < range || diff > -range) s.allowClick = true
        },
```

I think we should merge this into the swiper.js.

We should put this here and it will work like charm!

swiper.js, line 1773
```
            var timeDiff = touchEndTime - touchStartTime;
// ### Using this, a minimal click+drag with the mouse will trigger a click instead of a swipe.
          let range = 5
          let diff = s.touches.diff = s.isHorizontal() ? s.touches.currentX - s.touches.startX : s.touches.currentY - s.touches.startY
          if (diff < range || diff > -range) s.allowClick = true
// End ###
            // Tap, doubleTap, Click
            if (s.allowClick) {
```

We could also provide a range variable in the config so the user can change it.

**Comment by Alex360hd** [comment]
@smith64fx could not make your fix to work. could you please provide more details ? what is the complete code ? (cause you talk about swiper config but in a thumbnail configuration, there is 2 swiper).

I found another quick and dirty fix (waiting for an official bugfix), you keep the centermode to true, but you add some CSS :

    .gallery-thumbs .swiper-wrapper {
      transform:none !important;
    }

of course, change "gallery-thumb" by the class of you swiper thumbnail.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
