### ISSUE TITLE
Центровка активного слайда

### ISSUE THREAD

**Issue by EzheG** [nolimits4web/Swiper#1624]
Здравствуйте.
Возможно ли с опцией `slidesPerView: 'auto'` центрировать активный слайд как при `centeredSlides: true`, только чтобы с краю от первого и последнего слайда не было пустого места?
Т.е., первый активный слайд будет прижат к левому краю; последний активный к правому, а серединные активные будут по центроваться.

**Comment by nolimits4web** [comment]
Нет, такой возможности нет

**Comment by EzheG** [comment]
Я нашел способ это сделать :) После инициализации применяю небольшой декоратор на метод `updateSlidesSize`, который пересчитывает snapGrid по моим правилам.
Спасибо за слайдер с прекрасным API!
```javascript
function sliderDecoratorUpdateSlidesSize(func) {
  return function() {
    func.apply(this, arguments);
    
    var min = 0;
    var max = slider.virtualSize - slider.width;
    _.each(slider.snapGrid, function(val, i, list) {
      if (val < min) list[i] = min;
      else if (val > max) list[i] = max;
      else list[i] = Math.round(val);
    });
  };
}
```
