### ISSUE TITLE
Autoplay IE9 doesn't work for swiper 3

### ISSUE THREAD

**Issue by librisius** [nolimits4web/Swiper#1630]
I've checked swiper 2 it's ok, but for latest version (v3.3.1) autoplay doesn't work. That just switches to the second slide than stops on it. I've checked your demo.

Please fix it, because you have some options for ie9 for v.3 but autoplay doesn't work correctly.
Thank you.

**Comment by nolimits4web** [comment]
IE9 is not supported

**Comment by librisius** [comment]
Could you mark it on your site. Which browsers that plugin supports
