### ISSUE TITLE
Custom pagination showing x-x of total

### ISSUE THREAD

**Issue by adardesign** [nolimits4web/Swiper#1634]
How can I achieve Custom pagination like this
showing 1-6 of 24 when more then one slide is shown at once.

![screen shot on 2016-03-02 at 16-56-32](https://cloud.githubusercontent.com/assets/23543/13477066/9ff43116-e098-11e5-8380-d35f1cfaf679.png)

**Comment by nolimits4web** [comment]
Probably something like this, tweak it according to your purpose:
```
var swiper = new Swiper('.swiper-container', {
  //...
  paginationCustomRender: function (swiper, current, total) {
      return current + ' -  ' + (current + swiper.params.slidesPerView) + ' of ' + swiper.slides.length;
  }
});

**Comment by adardesign** [comment]
@nolimits4web, Thanks but sorry, This doesn't work.

I have a total (`swiper.slides.length`) of 9 slides and  5 `slidesPerView`  and at first it says `1 -  6 of 9` after first swipe it says `2 -  7 of 9` when in fact there is a total of 2 swipes.

Please advise.
Thanks again

**Comment by nolimits4web** [comment]
Why it doesn't work? Would be good to see what you have tried, better JSFiddle

**Comment by adardesign** [comment]
Please see gist:
https://jsfiddle.net/adardesign/353fe73x/
