### ISSUE TITLE
Question regarding Centered Slides + Auto Slides Per View

### ISSUE THREAD

**Issue by raulfelix** [nolimits4web/Swiper#1640]
In the "Centered Slides + Auto Slides Per View" example the first slide starts in the centre of the screen but it leave an empty space. 

Is there a way to have only the first slide left aligned to the container whilst all others use the centered behaviour? Same goes for the last slide too.

Thank you

**Comment by nolimits4web** [comment]
No, such behavior is not supported, if it is centered then it will always be centered
