### ISSUE TITLE
Multiple Slides and Paginations in One Page

### ISSUE THREAD

**Issue by muhammadadamfirdaus** [nolimits4web/Swiper#1642]
Hello,

Previously, thanks for make this great plugin.

I want to make 3 slides:
- (on header) slide 1 + pagination 1
- (on right sidebar) slide 2 + pagination 2
- (on right sidebar, bottom of slide 2) slide 3 + pagination 3.

Each slides has different id.

Slide 3 + pagination 3 are normal.
But, when I click on pagination 2, slide 1 is running too.
So, pagination 2 are slide 1 and slide 2.

I have wrote each id html are different. But doesn't work.

Thanks before.

**Comment by nolimits4web** [comment]
Please, show your code or live example or JSFiddle

**Comment by muhammadadamfirdaus** [comment]
This was solved.

If `pagination` is not required on one slide, don't write it.
Simply write about `pagination` that required for each slides.

Thanks.
