### ISSUE TITLE
Using for devices only, html5 video seems to conflict and disables Swiper.

### ISSUE THREAD

**Issue by FearTheWild** [nolimits4web/Swiper#1644]
I am using swiper container as my fallback for my portfolio on mobile devices. So on desktop it isn't being used.

It works great as I want, viewable on mobile but when I add html video to my desktop site, even though I am removing it for the mobile devices in media queries, it seems to brake Swiper? Have you seen this issue before? I'm not adding any new js, just what was provided.

`var mySwiper = new Swiper ('.swiper-container', {
		// Optional parameters
		direction: 'horizontal',
		loop: true
	}) `

Any advice on why this could be happening would be great.

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle

**Comment by FearTheWild** [comment]
Typically, I cannot seem to re-create the bug. So don't worry about it, must be something else conflicting.
