### ISSUE TITLE
Issues with vertical mode and swiper-container height

### ISSUE THREAD

**Issue by PixelZombie** [nolimits4web/Swiper#1645]
Hey there!

I'm using swiper to create a vertical calendar which displays a week per slide. Once I hit an "expand" button, a whole month should be displayed. 

The issue I'm having is to get swiper deal with container height changes correctly. As of now there are several issues like

- swiper does slide until the last slide is at the top of the container (but it sould stop as soon as the last slide is visible at the bottom of the container)
- Safari on OS X and iOS is behaving strangely (some kind of freemode, no snapping of slides - only correct after resize)
- slidesPerColumn is calculating the wrong width per slide

Could somebody please tell me what options are needed to get this right?

I made a pen for this: 
http://codepen.io/PixelZombie/pen/KzgrJr

Thanks a lot in advance!

**Comment by nolimits4web** [comment]
2 points:
1) `autoHeight` is for horizontal mode only!
2) Just call `swiper.update(true)` after you change height if swiper-container http://codepen.io/anon/pen/aNmeMw

**Comment by PixelZombie** [comment]
Thank you very much @nolimits4web !
It's working now but I have to keep autoHeight: true, otherwise the each slide will get the height of the container.
