### ISSUE TITLE
Using Swiper with infinite number of slides

### ISSUE THREAD

**Issue by mitya** [nolimits4web/Swiper#1650]
Hello Vladimir,

Thank you for the great plugin.

I wonder is there a simple way to use swiper when each slide represents a day, so there is an infinite number of slides. Basically, I want to implement something like a calendar with one day per slide.

I've tried to use the swiper with 3 slides in loop mode, and I've hoped to just update the prev/next slides content on each `onSlideNextEnd` / `onSlidePrevEnd`, but it seems that those events are triggered before swiper updates its html markup.

Thank you for any input

**Comment by nolimits4web** [comment]
Swiper doesn't update html markup. You can also try `onTransitionEnd` event, also check the HTML generated when you enable loop, there are also "looped/duplicated" slides, don't forget to update html there as well

**Comment by nolimits4web** [comment]
Closing as no further discussion. Reopen if you still have this issue
