### ISSUE TITLE
How to set html pages instead of slides

### ISSUE THREAD

**Issue by NaveenGB** [nolimits4web/Swiper#1654]
How to set html pages instead of slides, below code not working

<div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide" ><a href="index2.html"></a></div>
            <div class="swiper-slide"><a href="registration.html"></a></div>
            
        </div>
        
        <div class="swiper-pagination"></div>
    </div>

**Comment by nolimits4web** [comment]
It doesn't supported
