### ISSUE TITLE
angular-swiper multiple slider with dynamic content

### ISSUE THREAD

**Issue by myousufq** [nolimits4web/Swiper#1655]
Hi,

I am using three slider on one of my page. And data for slider are coming from server. 

I am facing very weird issue. On very first time slider are not working (I mean no slide show after populating data). Once I resize browser window they start working.  

In swiper.js I made a small change in **s.init ** method 
```

 setTimeout(function () {
                    s.preloadImages();
                }, 200)
```

if response coming within 200 milliseconds than sliders are working fine otherwise no sliding until I resize browser window.

If any one have example of using multiple instance on same page using angularjs. It would be great. 

thanks

**Comment by nolimits4web** [comment]
It just means you initialize it BEFORE it was added to DOM or became visible. Do it after or call its `.update(true)` method or use `observer` and `observeParents` parameters
