### ISSUE TITLE
Buggy behavior on mobile

### ISSUE THREAD

**Issue by sebj54** [nolimits4web/Swiper#1656]
I faced an issue on mobile with a buggy behavior. 
I have a swiper with three slides and it is working perfectly on desktop and large screen devices (tablets). On mobile, I have to remove one of the three slides, because its content is not relevant for a mobile usage. So I decided to hide the slide with a media query and the slide is removed from the swiper container with a line of js.

``` javascript
// slidesToRemove is an array with the slides index
if (slidesToRemove.length)
{
    $swiper.get(0).swiper.removeSlide(slidesToRemove)
}
```

Then, my slides are displayed correctly and I can swipe them but there are three problems: 
- When I a making a swipe in a specific way, the swiper pagination doesn't show me the current slide and slideChangeEnd event is not triggerred. 
- Possibly due to the previous bug, with autoHeight set to true, slide's height is not refreshed.
- When I am on the last slide and I am making a swipe to the right (trying to display a slide that doesn't exist), my slide is making a "jump".

Here is a gif of the bugs:
![Gif of the bugs](https://cloud.medialta.com/index.php/s/l7wJ0knKyx3pF0d/download)

For information, my swiper is initialized like this:

``` javascript
var swiper = new Swiper('#l-offre-agueris', {
    pagination: '#my-swiper .swiper-pagination',
    paginationClickable: true,
    nextButton: '#my-swiper .swiper-button-next',
    prevButton: '#my-swiper .swiper-button-prev',
    speed: 600,
    shortSwipers: false,
    slideToClickedSlide: true,
    autoHeight: true
})
```

Thanks in advance for your help and tell me if you need further information.

**Comment by nolimits4web** [comment]
Do you have live example so i can take a look?

**Comment by sebj54** [comment]
The website can be accessed at this URL: agueris [dot] projets-medialta [dot] com.
Like I said, you will see that it works fine on desktop but is buggy on small screens (touchable or not).

**Comment by nolimits4web** [comment]
Sorry for late reply, is it still actual? I can't see such Swiper on provided link

**Comment by sebj54** [comment]
Project has moved to production: agueris [dot] fr

Thanks for your help.

**Comment by nolimits4web** [comment]
Ok, can you describe/show how to replicate this issue, as i still can't see such Swipers? :)

**Comment by sebj54** [comment]
Sure, the only required thing is a viewport < 768px. Refresh the page may help if you don't see any change.

**Comment by nolimits4web** [comment]
Looks strange and it hard to isolate the problem, this shouldn't happen. But it really looks like you could initialize this swiper several times. Would be better if you can provide and replicate this issue isolated, for example in JSFiddle

**Comment by sebj54** [comment]
I'll try to provide you a JSFiddle soon. Thanks for your time, I'll keep you in touch.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
