### ISSUE TITLE
Swiper bug input radio checked

### ISSUE THREAD

**Issue by Serebanius** [nolimits4web/Swiper#1657]
The problem with input radio element in .swiper-slide with option loop:true.
- First of all defult checked radio after initialization plugin became not checked.
- When i checked radiobuton and start scrolling caruosel the checked radiobutton became not checked
- When i click on label with for="test" the radibutton with id="test" not became checked, so standard behavior of label with radio not suportted
[https://jsfiddle.net/hkn1c4pw/](https://jsfiddle.net/hkn1c4pw/)

**Comment by nolimits4web** [comment]
Look at generated source code, there are duplicated slides, so you'll have multiple radio inputs with same "value" attribute. You should consider it and add a bit of custom logic to check/uncheck such radios. For example https://jsfiddle.net/pddayjc4/1/
