### ISSUE TITLE
Illegal behavior when I use two way control with loop

### ISSUE THREAD

**Issue by AminulBD** [nolimits4web/Swiper#1660]
I need to create a gallery with infinity loop. I created by using "Thumbs Gallery With Two-way Control" this template. Only added ````loop```` parameter. But, The gallery is not working perfectly. You can see here the pen: http://codepen.io/aminul/pen/NNvGvV

Thanks!

**Comment by nolimits4web** [comment]
Both swipers should be looped http://codepen.io/anon/pen/KzXmQR

**Comment by AminulBD** [comment]
Yes, I already set that my work but I didn't know about "loopedSlides" this.

Now, This working fine.

Thanks :+1:
