### ISSUE TITLE
swiper crashes on button interaction if the slide animation is not finished

### ISSUE THREAD

**Issue by b-strauss** [nolimits4web/Swiper#1663]
http://idangero.us/swiper/demos/14-nav-arrows.html

Chrome Version: Version 49.0.2623.110 m (64-bit)

If you use the pagination or prev/next buttons at a time when the last transition has not been finished, the swiper crashes and does not respond to button interaction anymore. No console errors occurs. The mouse dragging still works.

I don't know in what chrome version this error was introduced, it worked a few weeks ago.

**Comment by nolimits4web** [comment]
Hm, have the same Chrome version and can't replicate this issue, works fine for me

**Comment by b-strauss** [comment]
Hmm, interesting. The problem does not always appear. I have no idea how to reproduce this consistently. Maybe this is a chrome bug or a problem with an extension. I will close the issue until I have more information.
