### ISSUE TITLE
Problems with slidesPerView auto and loops

### ISSUE THREAD

**Issue by pju-** [nolimits4web/Swiper#1664]
Check out the following pen please:
[Codepen](http://codepen.io/pju/pen/pyraMB)

When using _loopedSlides_ only or both _loopedSlides_ and _loopAdditionalSlides_, there are slides that are skipped:

**Setup 1:**

```
slidesPerView: 'auto',
loop: true,
loopAdditionalSlides: 2,
loopedSlides: 2,
```

Slides 6 & 7 (of 10) are never displayed when going forwards.
Also, when going backwards from 6, the slider goes forwards to 7.
In the DOM there are duplicates of 7,8,9,10 before the originals. There are duplicates of 1,2,3,4 after the originals.

**Setup 2:** 

```
slidesPerView: 'auto',
loop: true,
loopedSlides: 2
```

Using ONLY _loopedSlides_ as the doc recommends, things go even worse:
The slider skips from 3 to 10 when going forwards and from 8 to 9 when going backwards.
The DOM looks as expected though: 9 & 10 are duplicated before the originals, 1 & 2 after the originals.

**Setup 3:** 

```
slidesPerView: 'auto',
loop: true,
loopAdditionalSlides: 2
```

When only _loopAdditionalSlides_ is set, everything works as expected.
However, in the DOM all 10 elements are inserted once before and once after the original elements.

/Edit: I tried increasing the number as recommender [in this comment,](https://github.com/nolimits4web/Swiper/issues/1629#issuecomment-196746266) but that didn't help either.

**Comment by nolimits4web** [comment]
`loopAdditionalSlides` is a bit useless here. Just increase loopedSlides http://codepen.io/anon/pen/NNajXw

**Comment by pruthvip** [comment]
a small doybt, what if we have the following scenario,

slidesPerView: 'auto',
loop: true,
 centeredSlides: true,


and the number of images in the gallery is suppose 'n',
what should be the value of
 loopAdditionalSlides, loopedSlides instead of hard coding?

**Comment by pilou** [comment]
@pruthvip I've played with your pen. I think the answer is (n/2)+1

10 slides:
loopedSlides: 4 FAIL
loopedSlides: 5 OK

9 slides:
loopedSlides: 4 FAIL
loopedSlides: 5 OK

8 slides:
loopedSlides: 3 FAIL
loopedSlides: 4 OK

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
