### ISSUE TITLE
Swiper update, & video mute when slide... help !!

### ISSUE THREAD

**Issue by candyshien** [nolimits4web/Swiper#1667]
Hi, I use bootstrap 3.3.4 modal and Swiper 3.3.1 ...

I having problem when have 2 modal calling a swiper, the first button call the modal the swiper swipe work fine, the left right button work fine.. after close the 1st modal.. click 2nd modal, the swiper can't swipe, but left right button work fine... 

Not sure what problem, need some help...

https://jsfiddle.net/jhtdh4mr/

**Comment by candyshien** [comment]
I found to solve the slider on 2nd modal pop up....


But still having problem on swiper update... the update does not active/prev/next classes on slides and bullets,


And also need help on video slider, how to mute the volume when swipe to next slider.

Sample:
https://jsfiddle.net/jhtdh4mr/1/

**Comment by nolimits4web** [comment]
Just use observer parameters https://jsfiddle.net/hy8818b2/

**Comment by nolimits4web** [comment]
As for video, you need to use YouTube API to pause it in Swiper/Modal callbacks, or just overwrite iframe's `src' attibute

**Comment by candyshien** [comment]
thanks, for the help..

**Comment by candyshien** [comment]
I would like to ask having problem on IE 10 & IE 9 not working the slider

https://jsfiddle.net/hy8818b2/

**Comment by candyshien** [comment]
On IE 10,  landing direct load swiper ablt to swipe... but on bootstrap modal click swiper not init... how to re-init to run the swiper again...


Example Link below:
https://jsfiddle.net/hy8818b2/1/

**Comment by nolimits4web** [comment]
As said in another Issue, can't see any problems with modal. IE 9 is not supported
