### ISSUE TITLE
On hover stop autoplay mode issue 

### ISSUE THREAD

**Issue by tushar4monto** [nolimits4web/Swiper#1668]
Hello
I have used this plugin for vertically slide on my website but need to stop slide on hover how i can stop this with autoplayDisableOnInteraction:false because i want start and stop slider on hover

**Comment by nolimits4web** [comment]
For example with jQuery:

---js
var swiper = new Swiper('.swiper-container', {
  // ...
});
$('.swiper-container').on('hover', function(){
  swiper.stopAutoplay();
});

**Comment by gandhiselvarj** [comment]
$(".swiper-container").hover(function(){
		swiper.stopAutoplay();
	}, function(){
		swiper.startAutoplay();
	});
