### ISSUE TITLE
swiper 2 and ie 9 

### ISSUE THREAD

**Issue by michellomp** [nolimits4web/Swiper#1669]
Not an issue but a question 
I use swiper 2.7.6 cause i know swiper 3 doesn't support ie 9 but i've seen you use 
transform: translate3d(-1920px, 0px, 0px); transition-duration: 0.3s; for swiper 2 slider.
ie 9 doesn't support CSS3 3D Transforms.
Does swiper 2.7.6 work in ie 9 ?
and thanks for your plugin

**Comment by parhs** [comment]
ti isnt meant to support older browsers but works nicely.

**Comment by nolimits4web** [comment]
Yes, Swiper 2.x should work in IE 9, it uses JS animation and instead of CSS transitions. But it is not in development anymore
