### ISSUE TITLE
Swipe not working for mobile user agents

### ISSUE THREAD

**Issue by Ajeetlakhani** [nolimits4web/Swiper#1670]
I tried to open http://idangero.us/swiper/demos/05-slides-per-view.html with different user-agents for android, ios and pc. Pagination bullets are working but swipe is not working with mobile user-agents(tried with andoid kitkat and iphone6 user-agent).

**Comment by jasonaibrahim** [comment]
+1 experiencing this issue when using responsive design mode in google chrome. screencap here: http://recordit.co/LmNfnnPjDY

**Comment by HugoGon** [comment]
Hi Jason. 
Try to reload when you enter responsive mode and each time you change the emulated device in chrome. (they used to have a warning about that, but don't seem to have it anymore)

I have the same problem as Ajeet, i can swipe to the second item, but then it gets stuck, wont move to the next. You can only return to the first one. This happens either on a mobile phone or chrome emulation.

Cheers
Hugo

**Comment by nolimits4web** [comment]
It is because in mobile emulation mode Chrome enables touch events instead of mouse events which were not detected on Swiper initialization. Just hit "refresh" button in browser
