### ISSUE TITLE
[question/enhancement] Lazy-load progress (XMLHttpRequest)

### ISSUE THREAD

**Issue by rafaelnco** [nolimits4web/Swiper#1672]
Hey @nolimits4web, how are you?

Just wondering how the lazy load functionality is done and if is there any way to add a progress handler in the API, [as there is already one when using XMLHttpRequest to load files](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress).
Also, **[XMLHttpRequest progress events seems to be supported in the browsers that Swiper JS supports.](http://caniuse.com/#feat=xhr2)**

#### Use case

- Swiper js lazy loading HD images in a site with a splash screen. How much time do I have to wait until this splash screen disappears?!

#### Implementation

[Of course I'm going to look for this in the source code!](https://github.com/nolimits4web/Swiper/blob/master/src/js/lazy-load.js):

```

/*=========================
  Images Lazy Loading
  ===========================*/
s.lazy = {
    initialImageLoaded: false,
    loadImageInSlide: function (index, loadInDuplicate) {
        if (typeof index === 'undefined') return;
        if (typeof loadInDuplicate === 'undefined') loadInDuplicate = true;
        if (s.slides.length === 0) return;

        var slide = s.slides.eq(index);
        var img = slide.find('.swiper-lazy:not(.swiper-lazy-loaded):not(.swiper-lazy-loading)');
        if (slide.hasClass('swiper-lazy') && !slide.hasClass('swiper-lazy-loaded') && !slide.hasClass('swiper-lazy-loading')) {
            img = img.add(slide[0]);
        }
        if (img.length === 0) return;

        img.each(function () {
            var _img = $(this);
            _img.addClass('swiper-lazy-loading');
            var background = _img.attr('data-background');
            var src = _img.attr('data-src'),
                srcset = _img.attr('data-srcset');
            s.loadImage(_img[0], (src || background), srcset, false, function () {
                
                // ACTUAL CODE WOULD RUN ONLY WHEN PROGRESS == 100%
                // HERE YOU WOULD ACTUALLY START XML HTTP REQUEST AND SET PROGRESS HANDLER

                var oReq = new XMLHttpRequest();

                oReq.addEventListener("progress", updateProgress); // THIS SHOULD BE A PARAMETER FROM THE API

                oReq.open();

            }

```

What about it? Is there any chance this gets to the API ?

Att, Rafael

**Comment by nolimits4web** [comment]
There is no anything common with images lazy loading and XHR, these are different things. Images have `onload` event which you can use to know when it is loaded
