### ISSUE TITLE
Request: disableTouchControl() and enableTouchControl() methods

### ISSUE THREAD

**Issue by azaslavsky** [nolimits4web/Swiper#1673]
As mentioned in [this issue](https://github.com/nolimits4web/Swiper/issues/1235), I think it would a pretty useful feature to disable user swiping controls, without "locking the swiper entirely."  Currently, `.lockSwipes()` seems to work by completely preventing all slide changes, even those triggered from the API using the `.slideTo()` method.  What would be useful is a method that would prevent the user from sliding, but still enable the developer to programmatically move slides in the swiper.  I feel like an API that mimics `.disableKeyboardControl()` and `enableKeyboardControl()` would fit in nicely with the available methods.

**Comment by azaslavsky** [comment]
So I figured out that modifying the param `onlyExternal` like so:

`s.params.onlyExternal = true; //or false, if you so desire`

Since this is so simple, I think I'll make a PR implementing these methods for consistency, if you don't mind.

**Comment by nolimits4web** [comment]
Thanks, closed by #1674
