### ISSUE TITLE
IE10 swiper not working on Bootstrap modal, & IE9 swiper not working

### ISSUE THREAD

**Issue by candyshien** [nolimits4web/Swiper#1675]
I'm having problem on swiper, IE 9...

Unable to get property 'add' of undefined or null reference

**Comment by candyshien** [comment]
I would like to ask having problem on IE 10 & IE 9 not working the slider

https://jsfiddle.net/hy8818b2/

**Comment by candyshien** [comment]
On IE 10,  landing direct load swiper ablt to swipe... but on bootstrap modal click swiper not init... how to re-init to run the swiper again...


Example Link below:
https://jsfiddle.net/hy8818b2/1/

**Comment by nolimits4web** [comment]
Can't see any problems here, looks fine for me. As for IE 9 - it is not supported
