### ISSUE TITLE
How to know if the user touch causes slide change ?

### ISSUE THREAD

**Issue by nienlm-hhtv** [nolimits4web/Swiper#1682]
I don't know how to check if the user touch (swipe) cause the slider to change slide. I set the threshold and check the onTouchStart and onTouchEnd events but can't detect if the slider has been slided after this action. I need to check this before the slideChangeStart event

**Comment by nolimits4web** [comment]
You can try:
```
onSlideChangeStart: function(e, swiper) {
    console.log(swiper.touches.diff); //should be not empty in this case
}
