### ISSUE TITLE
Bug In Swiper.js Library

### ISSUE THREAD

**Issue by hasanbabaei** [nolimits4web/Swiper#1686]
Line Code 2660
Must be Follow Code :
for (i = s.activeIndex; i < s.activeIndex + (s.params.slidesPerView*s.params.slidesPerColumn) ; i++)
instead of
for (i = s.activeIndex; i < s.activeIndex + s.params.slidesPerView ; i++)

**Comment by nolimits4web** [comment]
Why it should be like that, what will it fix, would be good to see live example or JSFiddle with and without this fix difference
