### ISSUE TITLE
How can i disable bounce effect in Swiper 3?

### ISSUE THREAD

**Issue by Coffcer** [nolimits4web/Swiper#1691]
How can I disable bounce effect, i found a `resistance` parameter for that, but it only work in Swiper 2.
https://github.com/nolimits4web/Swiper/issues/1002

**Comment by DareDevil73** [comment]
Mee too ( https://github.com/nolimits4web/Swiper/issues/1698 ).

**Comment by DareDevil73** [comment]
**Solved**:

- resistance : true
- resistanceRatio : 0

**Comment by jkbreunig** [comment]
This no longer prevents horizontal bounce
 
resistance : true
resistanceRatio : 0
