### ISSUE TITLE
Swiper with thumbnails in Bootstrap Modal

### ISSUE THREAD

**Issue by vertisan** [nolimits4web/Swiper#1693]
Hi!

I tried to add swiper with thumbnails to bootstrap modal, but in modal it's not working, why?
Here is demo: http://codepen.io/vertisan/pen/MyBdKz

**Comment by nolimits4web** [comment]
This is how CSS works, you didn't specify swipers sizes (heights). Also add this two parameters to top swiper:
```
observer: true,
observeParents: true
```
