### ISSUE TITLE
Grab cursor issues with lockSwipes()

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/Swiper#1695]
I think when we are using `swiper.lockSwipes()` function and although the `swiper.params.grabCursor` is set to `true`, the default cursor should appear on hover instead of the grab one.

I also can not disable the grab cursor by setting the proper parameter as you can see below: `swiper.params.grabCursor = false`

**Comment by nolimits4web** [comment]
I will fix it. As for now you can disable grab cursor by setting `swiper.container[0].style.cursor = ''`. To set it back:
```js
swiper.container[0].style.cursor = 'move';
swiper.container[0].style.cursor = '-webkit-grabbing';
swiper.container[0].style.cursor = '-moz-grabbin';
swiper.container[0].style.cursor = 'grabbing';
```
