### ISSUE TITLE
Need a way to get the accurate activeIndex in loop mode

### ISSUE THREAD

**Issue by phongmedia** [nolimits4web/Swiper#1696]
I'm using Swiper for a user to set their 'current active image', and so hooking into the `onSlideChangeEnd()` callback.

As you know, when in loop mode, the `activeIndex` property is offset by the duplicated slides, although what I need is essentially the `data-swiper-slide-index` attribute of the currently selected slide. I can't find a way to get the currently selected slide or it's index.

I looked repeatedly for this value in the API, although I can't find anything, it seems like it should be there somewhere. The only other way I can think to get this value, would be to query the DOM for the slide with the active class on it, and grab it's `data-swiper-slide-index` value, although that's a pretty messy way to get a simple value.

**Comment by navyxie** [comment]
in loop mode active index value will be always shifted on a number of looped/duplicated slides. you can get attribute 'data-swiper-slide-index' whit function like:

**Comment by navyxie** [comment]
in loop mode active index value will be always shifted on a number of looped/duplicated slides. you can get attribute 'data-swiper-slide-index' whit function like:

```js
function getActiveIndex(swipe){
    var activeIndex = swipe.activeIndex;
    var slidesLen = swipe.slides.length;
    if(swipe.params.loop){
        switch(swipe.activeIndex){
            case 0:
                activeIndex = slidesLen-3;
                break;
            case slidesLen-1:
                activeIndex = 0;
                break;
            default:
                --activeIndex;
        }
    }
    return  activeIndex;
}
```

usage:

```js
var mySwiper = new Swiper('.swiper-container', {
    direction: 'vertical',
    loop:true,
    onSlideChangeEnd:function(swipe){
        console.log(getActiveIndex(swipe))
    }
}); 
```

@phongmedia

**Comment by phongmedia** [comment]
@navyxie Thanks for the function, I'll give that a spin. It would be great if something like this was already provided by the API, with something like `swiper.getActiveIndex()`

**Comment by navyxie** [comment]
@phongmedia    Sorry , Above way is not better , and will take a bug  when you set param loopAdditionalSlides or loopedSlides:

```js
var mySwiper = new Swiper('.swiper-container', {
    direction: 'vertical',
    loop:true,
    loopAdditionalSlides:1,
    loopedSlides:2,
    onSlideChangeEnd:function(swipe){
        console.log(geSlideDataIndex(swipe))
    }
}); 
```

I have made a [pr](https://github.com/nolimits4web/Swiper/pull/1697) to solve the problem  : [add property realIndex](https://github.com/nolimits4web/Swiper/pull/1697)。

```js
var mySwiper = new Swiper('.swiper-container', {
    direction: 'vertical',
    loop:true,
    onSlideChangeEnd:function(swipe){
        console.log(swipe.realIndex)
    }
});
```

**Comment by nolimits4web** [comment]
Closed by #1697

**Comment by nicmare** [comment]
Try this: 
`$('.swiper-slide-active').data("swiper-slide-index");`
in a callback function:
`mySwiper.on('onSlideChangeStart', function (swiper) {
            var sindex = $('.swiper-slide-active').data("swiper-slide-index");
            console.log(sindex);
        });`

**Comment by ikarynerv** [comment]
`$('.swiper-slide-active').data("swiper-slide-index") `  == undefined  when not in loop mode

this work in both modes:


```
var $slideActive = $('.swiper-slide-active'));
var realIndex = $slideActive.data('swiper-slide-index')
if(typeof realIndex === 'undefined') {
	realIndex = $slideActive.index();
}
```

**Comment by zhancheng** [comment]
realPreviousIndex  also helpful to me
