### ISSUE TITLE
Library not working inside ASP TAG

### ISSUE THREAD

**Issue by cristinatorress** [nolimits4web/Swiper#1699]
I'm trying to load the gallery swiper dynamically inyecting the code from an asp file to another file inside a bootstrap modal.

When it's not inside de ASP tag works perfectly but when i put it inside de ASP file stops working; the code is wrapped around this tag RESULTADOS=RESULTADOS & ""

What is wrong? or why is not working?

`RESULTADOS=RESULTADOS & "		<div class='swipper-gallery'>"
RESULTADOS=RESULTADOS & "			<div class='swiper-container gallery-top'>"
RESULTADOS=RESULTADOS & "				<div class='swiper-wrapper'>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/2' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/3' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/4' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/5' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "				</div>"
RESULTADOS=RESULTADOS & "			</div>"
RESULTADOS=RESULTADOS & "			<div class='swiper-container gallery-thumbs'>"
RESULTADOS=RESULTADOS & "				<div class='swiper-wrapper'>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/2' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/3' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/4' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "					<div class='swiper-slide'>"
RESULTADOS=RESULTADOS & "						<img src='http://lorempixel.com/1200/1200/nature/5' alt=''>"
RESULTADOS=RESULTADOS & "					</div>"
RESULTADOS=RESULTADOS & "				</div>"
RESULTADOS=RESULTADOS & "				<div class='swiper-button-next swiper-button-black'></div>"
RESULTADOS=RESULTADOS & "				<div class='swiper-button-prev swiper-button-black'></div>"
RESULTADOS=RESULTADOS & "			</div>"
RESULTADOS=RESULTADOS & "		</div>"
RESULTADOS=RESULTADOS & "	</div>"`

**Comment by nolimits4web** [comment]
Would be good to see live example, but it doesn't related much to Swiper itself
