### ISSUE TITLE
Issue when having many bullet (pagination)

### ISSUE THREAD

**Issue by HamzaLJ** [nolimits4web/Swiper#1701]
I wanted to have a custom pagination, for that I replaced the index number with string values likes: Nancy, Georges, etc...
The issue is that, instead of having the option to scroll horizontally over the names, Swiper simply take all of them and form multiple lines.
What I wanted basically to achieve is the following:

http://ionic-sarav.rhcloud.com/ionic/tabbedSlideBox/slidingTabsUsingRepeat.html#/

As you may see, no matter how you reduce the screen size, you can still scroll horizontal and view all the content. Is that even possible with Swiper? Is there any plans to have that in the near future?

**Comment by nolimits4web** [comment]
It is just about custom CSS, you should probably make their parent element scrollable with "overflow: auto"
