### ISSUE TITLE
Responsive design, Aspect ratio

### ISSUE THREAD

**Issue by kiwicat** [nolimits4web/Swiper#1706]
I am using the carousal on my website just for images.
When using different sized browsers the images get squished.
Is there some way I can maintain the aspect ratio of the images? 
This tag .img {width:100%; height:auto;} seems to be absolutely nothing. 
 I tried also adding these : 
  .swiper-wrapper {height:auto;}
.swiper-slide { height:auto;}
But they too seem to be doing nothing as well.

**Comment by rickibarnes** [comment]
+1 it's not really a responsive slider if I have to set an explicit height.

**Comment by kiwicat** [comment]
Are you sure? The slider is made to be used with touchscreens. It seems odd that it wouldn't be. 
It seems that even when i do set a height that when the window is resized it squishes stuff. 
Is the best bet just using media queries to set different heights for different window sizes? 

It just looks so unproffesional for the images to squish.

**Comment by rickibarnes** [comment]
I was just meaning that I don't think it counts as being fully responsive if you have to tell it what height to be. I think what we really need for our use case is for it to allow adaptive height, but I don't know how to implement it. It's a shame; everything else about this is perfect for me.

**Comment by kiwicat** [comment]
Oh  I see. Yes agreed 100%. 
I don't have tons of experience, I am a graphic design student and each semester we take one web design course. And most of the profs don't really care if students just populate barebones. 
I really enjoy building things and learning how it works, so that when I am working in the field I wont be 100% dependant upon the heavier coders. 
Anyhow I feel like Im missing out on something, because it seems so odd that this would not work responsively. 
Normally image divs are pretty easy to make responsive, and to maintain ratio. 
From my experience it feels like there should be a way to constrain images and for the actual "swiper div to just resize to those. If that makes any sense

**Comment by nolimits4web** [comment]
Please, provide live example or JSFiddle with the issue
