### ISSUE TITLE
indexes problems while unshifting new slides to begin

### ISSUE THREAD

**Issue by emps** [nolimits4web/Swiper#1707]
*** im using angularjs ngrepeat with ionic slides***
well the problem is while adding new slide to the front of the slides it makes slides Indexes that Swiper is using to move forward so the new one gets index 0 and all the rest gets ++ and makes swiper jump to the begin index that is the new one (0) and skip the previous slid

slides: [0 'a'] [1 'b'] [2 'c']
after unshifting new slide
slides: [0 'new' ] [1 'a'] [2 'b'] [3 'c']

so if im on index 1 that is 'b' and i am unshiftine new slide cause i wanna go to index 0 that is 'a'
Swiper jumping to index 0 that is the 'new' cause index 0 that was 'a' changed to index 1

i have fixed this problem by using 
`swiper.slideTo(1, 0);
`
right after unshifting to ngrepeat array but its breaking the sliding animation

is there option to change slide indexes numbers ? from 0 1 2 to 500 501 502 for example ?

**Comment by nolimits4web** [comment]
There is no such option, swiper index represents index number of slide element in DIV, just consider it in your logic
