### ISSUE TITLE
Swiper activeIndex issue

### ISSUE THREAD

**Issue by amitcw** [nolimits4web/Swiper#1716]
Swiper activeIndex is not working properly on last-slide, On every callback function it returns second last slide activeIndex number.

I am using swiper 3.3.1 latest version with following code.

            $('.sw-' + index).swiper({
            nextButton: $(this).find('.swiper-button-next'),
            prevButton: $(this).find('.swiper-button-prev'),
            pagination: $(this).find('.swiper-pagination'),
            slidesPerView: 'auto',
            paginationClickable: true,
            spaceBetween: 10,
           
            onSlideChangeStart: function (swiper) {
               
                console.log('slidechangeStart: '+swiper.activeIndex);
            },
            onSlideChangeEnd: function (swiper) {
             
                console.log('slidechangeEnd: ' + swiper.activeIndex);
            },
            onTransitionEnd: function (swiper) {
               
                console.log('onTransitionEnd: ' + swiper.activeIndex);
            },
            onInit: function (swiper) {
                swiper.update(true);
            }
            });

**Comment by amitcw** [comment]
I am getting issue only when `slidesPerView : auto` is there.
@nolimits4web can you resolve this issue.

**Comment by nolimits4web** [comment]
With slides per view > 1, last slide may never become active as activeIndex depends on slider position, not on something else. It is by design

**Comment by xiangkaiy** [comment]
So, How do I know the last slide appear ?

**Comment by wszgxa** [comment]
So, How do I know the last slide appear ?

**Comment by nixonthekat** [comment]
So, How do I know the last slide appear ?

**Comment by marcus-at-localhorst** [comment]
With `slidesPerView: 'auto'` I solved it this way:

```js
if(swiper.isEnd){
  swiper.activeIndex = (swiper.slides.length - 1);
}

// access swiper.activeIndex for whatever...
```

**Comment by 1mike12** [comment]
So, How do I know the last slide appear ?

**Comment by ivanempire** [comment]
So, How do I know the last slide appear ?

**Comment by johnn134** [comment]
So, How do I know the last slide appear ?

**Comment by mrVers** [comment]
So, How do I know the last slide appear ?

**Comment by Supachai-Cipher** [comment]
So, How do I know the last slide appear ?
