### ISSUE TITLE
Low Full Screen Performance

### ISSUE THREAD

**Issue by anteksiler** [nolimits4web/Swiper#1717]
If you check out my demo here:

http://twofold.fuelthemes.net/

You'll see that it's pretty choppy. It's affecting the mouse cursors. 

It gets so bad, I have to close my browser window.

**Comment by nolimits4web** [comment]
Sorry, it doesn't related much to Swiper itself. Try to optimize images, your custom transitions and maybe other scripts that can affect performance

**Comment by anteksiler** [comment]
@nolimits4web You might be right, but the same scripts on Swiper running the cube effect has no choppiness: http://twofold.fuelthemes.net/home-cube-effect/

**Comment by nolimits4web** [comment]
@andreybs11 there is no your custom "ken-burns" effect and custom cursor

**Comment by anteksiler** [comment]
This page: http://twofold.fuelthemes.net/home-slider/ does not have kenburns.

I have a local test, which I do not have anything besides the swiper. It just happens on normal slide function, the cube works fine.

CPU just spikes out of nowhere.

**Comment by anteksiler** [comment]
@nolimits4web I can send you a CPU profile if you want.

**Comment by anteksiler** [comment]
I think it's a conflict between Swiper & Greensock.

**Comment by nolimits4web** [comment]
Don't needed, try to narrow down the problem, for example, remove/disable this custom cursor thing script

**Comment by anteksiler** [comment]
@nolimits4web Believe me, that's the first thing I disabled :) 

It's just the change in effect.

**Comment by anteksiler** [comment]
@nolimits4web Could you update the dist files with the latest commits?

**Comment by nolimits4web** [comment]
They will be updated later with new version release. You can do it manually using node/gulp on local machine https://github.com/nolimits4web/Swiper#distrelease

**Comment by Cactusx09** [comment]
Hi @anteksiler, you solve problem? How?
