### ISSUE TITLE
Responsive slider with fixed slide size

### ISSUE THREAD

**Issue by orita7** [nolimits4web/Swiper#1720]
Hello!

I need to make a responsive slider, but I don't want the slides width and height to change. I want the slider container width to change according to the number of visible slides and to add padding so the slider will stay in the same place. I tried to do that with breakpoints and slidesPerView,
but the slides width changes every time I change the screen size.

Now the container size according to the clientWidth, Is there a way to update the container width every time the screen size changes by the next calculation:  ( amount of visible slide * slide fixed width) + (spaceBetween * (amount of visible slide – 1).

The goal is that the slides width will not change, but the amount of visible slides will change according to the breakpoints by changing the slider container width. 

Example of a site the uses a slider with the functionality that I need:
www.viewster.com/

Thanks!

Orit

**Comment by vbaimas** [comment]
If i understand correctly, you want fixed width/height of your container. In this case you need to customize with some css your .`swiper-container`

**Comment by dpbricher** [comment]
If you want the size of your slides to remain fixed regardless of the dimensions of the container, the parameter for that is `slidesPerView:'auto'`
