### ISSUE TITLE
slideTo animate from left to right for the first time

### ISSUE THREAD

**Issue by kdeit** [nolimits4web/Swiper#1721]
Good day.
http://d202d.tmweb.ru/eng/posters/stilyagi
Then i click on thumb (bottom of page) with event «slideTo» for the first time animation goes from left to right.
Next time there is everything OK.
How i can change animate direction from right to left?
Thanks.
За слайдер огромное спасибо :).

**Comment by nolimits4web** [comment]
Попробуйте поставить параметр `loopedSlides:2` (в вашем случае должно быть достаточно) вместо `loopAdditionalSlides`
