### ISSUE TITLE
Last bullet selected?

### ISSUE THREAD

**Issue by ATouhou** [nolimits4web/Swiper#1724]
Hey... My last bullet & slide is that which starts at load... Even changing order of init, makes no difference,  how can i make the first of a set of bullets, the "selected" according to API/best practice?

**Comment by nolimits4web** [comment]
Please provide an example or JSFiddle with the issue/problem

**Comment by ATouhou** [comment]
Example:
http://touhou.dk/byensfrontend/

Please scroll to the cars section as illustrated in the picture
![image](https://cloud.githubusercontent.com/assets/6802820/15538551/42ad90e8-227d-11e6-9f95-5ccead3b069c.png)


(Don't mind the non existing pictures in other categories)

Bullets loaded at: http://touhou.dk/byensfrontend/assets/js/theme.js

**Comment by nolimits4web** [comment]
Update Swiper to the latest version, this should be fixed there

**Comment by ATouhou** [comment]
That sorted it out, thanks
