### ISSUE TITLE
Last elements not visible on swiper js, 

### ISSUE THREAD

**Issue by ikalangita** [nolimits4web/Swiper#1726]
Hello,
Why some last elements are not visible? the are only appeared when i open chrome inspect screen : please see here ==> goo.gl/EUB3c4
I uset mySwiper.update() but not working to update swiper.
my html :
````<div class=“swiper-content”>
        <div class=“swiper-wrapper”>
             <div class=“swiper-slide”>content</div>
     </div></div>````
Js :
`var mySwiper = new Swiper ('.swiper-container',{
slidesPerView:'auto',
freeMode: true,
})`
Thanks for helpLike

**Comment by nolimits4web** [comment]
If it is still actual, create new issue and provide more details
