### ISSUE TITLE
Recentering centeredSlides after viewport resize

### ISSUE THREAD

**Issue by shuuki** [nolimits4web/Swiper#1731]
When swiper loads, slides are centered as expected with `centeredSlides = true`. As soon as the window is resized, the all the slides get pulled to the left by _n_ pixels, where _n_ is, presumably, a portion of the offset that is passed to the slides on load to center them initially. (Haven't been able to determine the exact value.)

This isn't _much_ of problem on desktop (madly resizing the window isn't normal user behavior), but it happens 100% of the time on mobile. This is the result of a resize event happening when the toolbar automatically hides after scrolling content. So the swiper loads correctly, but after the toolbar disappears the slides automatically shift. **Any kind of resizing**, even a vertical resize, effects the horizontal alignment of the slides. 

How should I go about forcing a recenter after resizing the viewport?

Currently I'm planning to look at the `centeredSlides` and `slidesOffset` code to see if I can identify a workaround. Since I'm using jQuery, I'll experiment with tricks inside `$(window).resize()`. 

---

Some of my current configuration:

```
centeredSlides: true,
loop: true,
slidesPerView: 'auto'
```

Also using `.swiper-slide { width: 70%; }` in CSS with 100% width images to fill the slides completely while leaving some room to show the edges of adjacent slides.

**Comment by ehinter** [comment]
@shuuki Did you find a solution to this?

**Comment by shuuki** [comment]
@ehinter i did find a solution to this issue. can't find the relevant code in my old site but i remember going digging in the swiper source for styles that were being set. somewhere there was a margin or height or some other kind of arbitrary css being applied that would break on resize. it was only a line or two. deleted that, and used regular site css to style the positioning. 

it's been a while but i think this was the commit to my personal test site where i identified or fixed the issue:
https://github.com/shuuki/mzxio/commit/394b2b2e91db2ca2e03eb4079181c27ce6de210c

**Comment by ehinter** [comment]
@shuuki Thanks!

**Comment by ehinter** [comment]
For anyone else who has this issue, for me the bug was using the `spaceBetween` setting. When I set that to 0 the problem went away.
