### ISSUE TITLE
Documentation site mistake

### ISSUE THREAD

**Issue by proll** [nolimits4web/Swiper#1733]
Hi,

Amazing slider. Best library I've seen for this purposes.

Just in case. I've just found mistake in documentation there http://idangero.us/swiper/api/ .
Breakpoints parameters section has mentions of **spaceBetweenSlides**.
Apparently it's an obsolete version of **spaceBetween* and code sample from there doesn't work as it should.

Working sample code would be

```javascript
var swiper = new Swiper('.swiper-container', {
  // Default parameters
  slidesPerView: 4,
  spaceBetween: 40,
  // Responsive breakpoints
  breakpoints: {
    // when window width is <= 320px
    320: {
      slidesPerView: 1,
      spaceBetween: 10
    },
    // when window width is <= 480px
    480: {
      slidesPerView: 2,
      spaceBetween: 20
    },
    // when window width is <= 640px
    640: {
      slidesPerView: 3,
      spaceBetween: 30
    }
  }
})
```

Cheers

**Comment by nolimits4web** [comment]
Fixed thanks
