### ISSUE TITLE
Detecting left-to-right swipe on activeIndex 0 

### ISSUE THREAD

**Issue by mikepaszkiewicz** [nolimits4web/Swiper#1736]
is there a way to detect an edge-swipe with this library? I'm basically trying to hook into a swipeRight event when already on activeIndex 0. Something like onSwiperMove, but only gets executed once & will give swipe direction.

**Comment by nolimits4web** [comment]
you can compare swiper.touches.startX and swiper.touches.currentX properties to define the direction
