### ISSUE TITLE
When effect: 'coverflow',onSlideChangeEnd doesn`t work

### ISSUE THREAD

**Issue by yongheng-wyh** [nolimits4web/Swiper#1744]
When effect: 'coverflow',onSlideChangeEnd doesn`t work

**Comment by ccqgithub** [comment]
i have the same trouble!!

**Comment by llyp618** [comment]
+1

**Comment by gsgenerator** [comment]
I got the same issue but investigated a little more.

And in my case:

onSlideChangeStart, onSlideChangeEnd is not triggered when effect is set to something else then 'slide' and you grab slide and slowly slide mouse to change to next / previews slide. When swipe is performed this usually work and functions are triggered. 

My workaround was to use onTransitionStart, onTransitionEnd instead but I don't think this is the way.

This will be fixed at some point ??

**Comment by adexerivera** [comment]
+1

Like @gsgenerator I use onTransitionEnd for my propose.

**Comment by qzthrone** [comment]
+1

**Comment by leiyu0932** [comment]
Read the source code， Then found when effect: 'coverflow' , watchSlidesProgress is true,
when watchSlidesProgress:true ,  implement  updateActiveIndex   （s.previousIndex = s.activeIndex;s.activeIndex = newActiveIndex;） when finger away , perform (s.previousIndex = s.activeIndex;s.activeIndex = newActiveIndex;) again in function slideto . so my workaround is

in function 'slideto'
if (!s.params.freeMode && !s.params.watchSlidesProgress) {
              s.previousIndex = s.activeIndex || 0;
              s.activeIndex = slideIndex;
            }

**Comment by leiyu0932** [comment]
My workround was to  change the 2064th line of swiper.js   to the following：
if (s.activeIndex !== slideIndex) {
              s.previousIndex = s.activeIndex || 0;
              s.activeIndex = slideIndex;
            }

**Comment by 86chenjie** [comment]
@leiyu0932   thanks for your solution. It works and it should be merged to master. 👍

**Comment by MaxInMoon** [comment]
It works with the v4.0.1, so this issue may be closed?
