### ISSUE TITLE
slidesPerView: 2.2, centeredSlides: true

### ISSUE THREAD

**Issue by senky** [nolimits4web/Swiper#1746]
Hi,
I would like to achieve horizontal scrolling with displaying little bit of previous and next slides, but with 2 active slides displayed. Basically, this setting:
```
slidesPerView: 2.2,
slidesPerGroup: 2,
centeredSlides: true
```
But this does not work. What it does is , that it centers first slide and displays part of second slide as well, see the image:
![snimka_2016-06-13_o_15 25 36](https://cloud.githubusercontent.com/assets/182498/16009105/9037684a-317b-11e6-92b1-81209d01959b.png)
But what I expect is to display both images next to each other (center would be just between them) and small portion of third image at very right side:
![snimka_2016-06-13_o_15 31 07](https://cloud.githubusercontent.com/assets/182498/16009181/e3c224d2-317b-11e6-9af3-76676611988e.png)

I think this must be some kind of bug, because settings allow me to expect such behaviour, but final result is not what I expect.

Could you, please, confirm that this is bug, or instruct me on how to achieve my desired state?

Thanks in advance!

**Comment by dpbricher** [comment]
You need to remove the 'centeredSlides' value from your settings (or set it to false); This will align your first slide with the left edge of the container.

If you want a gap between the first slide and the left edge then there is probably/hopefully another setting for that.
