### ISSUE TITLE
slidesPerGroup don't working in IE9

### ISSUE THREAD

**Issue by williamcosta** [nolimits4web/Swiper#1747]
I have a slide with the following settings:

`var carousel_home = new Swiper ($('.content-tabs[data-tab="'+ tab_id +'"]'), {
slidesPerView: 2,
slidesPerColumn: 2,
slidesPerGroup: 4,
spaceBetween: 30,
});`

Only in IE9 appears only 2 slides per group. Has anyone ever experienced this?

**Comment by nolimits4web** [comment]
slidesPerColumn is not supported and won't be supported in IE9
