### ISSUE TITLE
Multiple paginationType

### ISSUE THREAD

**Issue by LorenzoBocchi** [nolimits4web/Swiper#1749]
Hi, 
I was trying to use multiple pagination types in the same gallery.
In the .js file it says "or":
`paginationType: 'bullets', // 'bullets' or 'progress' or 'fraction' or 'custom'`

In my project I would like to use 'progress' and 'fraction' together. Is that possible?
Thanks.

**Comment by nolimits4web** [comment]
Multiple paginations are not supported
