### ISSUE TITLE
Stress Test

### ISSUE THREAD

**Issue by MentalGear** [nolimits4web/Swiper#175]
Hi,
I actually got big performance drops when using the swiper with 14 plus slides.
I am not sure if it is my setup or if the swiper has a slides number after which it becomes laggy.

Is there something like a official stress test with 100 slides or so?

**Comment by sergiopera** [comment]
Hi, is there any solution for this? i have problems with 5 sliders with 13 products each in Magento 2, while on desktop works great with 1 or 2, with 5 gets bit laggy but on android is impossible to handle
