### ISSUE TITLE
Swiper slider gallery, and changing orientation on Iphone

### ISSUE THREAD

**Issue by ogutierrezdiario** [nolimits4web/Swiper#1753]
I made an image gallery format. It's responsive (boostrap and some own medias @), when i click an image, a Swiper (http://idangero.us/ plugin) slider opens to show images one by one in a bigger size. I tested on PC, and Android phones, and it's working fine on this 2 devices:

responsive, changing orientation on phone (android), all formats are working fine...

except iphones, when i click an image, it opens fine, but when orientation is changed, it doesnt resize the swiper area.

I allready try this 2 options:

``````
window.addEventListener("orientationchange", function() {
    mySwiper.update(); and thisone: mySwiper.onResize();
})
```;
Also i notice this, after changing orientation (landscape to portrait OR portrait to landscape), and do a small scroll-down, swiper resize the container (the scroll to hide the addres-bar upside) and works fine, but in android, that's not necesary.
``````

**Comment by GSP1** [comment]
@ogutierrezdiario Did you ever find a fix? Having exact same issue with the iPad.

**Comment by GSP1** [comment]
@nolimits4web Any ideas?

**Comment by schhogyel** [comment]
I also have a similar issues. When changing orientation, the layout is messed up but works when refreshed.

**Comment by zakton5** [comment]
Any word on this? I'm having this issue via Ionic 2

**Comment by aleixfabra** [comment]
The same happens to me. 

Any solution?

**Comment by Webrusterkk** [comment]
+1

**Comment by aramin** [comment]
The problem still exists.

Steps to reproduce: Open this URL https://www.welt.de/vermischtes/article167880352/Und-dann-tat-Trump-was-man-auf-keinen-Fall-tun-sollte.html#cs-Sonnenfinsternis-in-den-USA.jpg in Safari (iOS 10.3) and change the orientation. Simulator will show you the bug as well.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by dongseok0** [comment]
I found this issue on my project also.
This happens because there is wrong width/height from window object in resize event handler.
( https://bugs.webkit.org/show_bug.cgi?id=170595 )
I managed to workaround it by giving timeout and call `swiper.update()` manually.
