### ISSUE TITLE
Wrong slide gets activated on click

### ISSUE THREAD

**Issue by Krakabek** [nolimits4web/Swiper#1756]
Sometimes if you click on slide, wrong slide becomes active
For example if you have carousel and you click on 2 and 4 slides repeatedly, 5th slide can became active after click on 2nd.

I use config like that:

``` javascript
var galleryTop = new Swiper('.gallery-top', {
                    slidesPerView: 3,
                    lazyLoading: true,
                    centeredSlides: true,
                    slideToClickedSlide: true,
                    keyboardControl: true
                });
var galleryThumbs = new Swiper('.gallery-thumbs', {
                    spaceBetween: 0,
                    centeredSlides: true,
                    slidesPerView: 10,
                    touchRatio: 0.2,
                    slideToClickedSlide: true,
                    lazyLoading: true
                });
galleryTop.params.control = galleryThumbs;
galleryThumbs.params.control = galleryTop;
```

Is there something I am doing wrong?

**Comment by enverarslan** [comment]
I faced too this issue. I think this happened when using different slidesPerView parameters. It understands whole viewed thumbnail items in one group. Main slider changed when that group skipped.

We have to clear solution for that. 

Maybe using `slidesPerView: "auto"` setting help you. [Official demo use this setting.](https://github.com/nolimits4web/Swiper/blob/master/demos/23-thumbs-gallery.html#L101)
