### ISSUE TITLE
Exception thrown on application bootstrap

### ISSUE THREAD

**Issue by maheshambiga** [nolimits4web/Swiper#1757]
Getting below exception,
\node_modules\swiper\dist\js\swiper.js:3627
var ua = navigator.userAgent.toLowerCase();
^

ReferenceError: navigator is not defined

**Comment by maheshambiga** [comment]
#1541

**Comment by maheshambiga** [comment]
#1541

**Comment by maheshambiga** [comment]
nolimits4web/Swiper#1541

**Comment by maheshambiga** [comment]
There is a similar issue here nolimits4web/Swiper#1541
#14

**Comment by CinKon** [comment]
+1

**Comment by wangranxin** [comment]
💯
