### ISSUE TITLE
Swiper doesn't changed slides when hash changes

### ISSUE THREAD

**Issue by jklegseth** [nolimits4web/Swiper#1759]
With `hashnav` enabled `location.hash` is correctly updated on slide change and the correct slide is shown on page load, however using the browser back button has no effect on the slides. You can reproduce this simply using the official Swiper demo at http://idangero.us/swiper/demos/25-hash-navigation.html:

1. On page load the URL is http://idangero.us/swiper/demos/25-hash-navigation.html.
2. Click the forward navigation twice to Slide 3. The slide is #3 and the URL is http://idangero.us/swiper/demos/25-hash-navigation.html#slide3. This is correct.
3. Click the browser Back button. The URL is now http://idangero.us/swiper/demos/25-hash-navigation.html#slide2 but Slide 3 is still showing rather than the expected Slide 2.

**Comment by uzumakinaruto123** [comment]
+1 @jklegseth  any workaround yet ?

**Comment by jklegseth** [comment]
@uzumakinaruto123 you can listen for the hashchange event (https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange) and then call mySwiper.slideTo() (see API at http://idangero.us/swiper/api/#.V3V-n5MrJE4) to show the matching slide. Hopefully the Swiper library will fix this.

**Comment by uzumakinaruto123** [comment]
Thanks alot :) @jklegseth  will try this. Yes , calback like onHashChanged()  would help a lot.

**Comment by Tusko** [comment]
+1
