### ISSUE TITLE
The next and prev buttons (arrows) dont work

### ISSUE THREAD

**Issue by lgarridoj** [nolimits4web/Swiper#1761]
Using Swiper  ver. 3.3.1 from CDN. The next and prev buttons (arrows) dont work when I clic on them.
The console shows the following error:

> Error: Mismatched anonymous define() module: function () {
>         'use strict';
>         return window.Swiper;
>     }
> http://requirejs.org/docs/errors.html#mismatch
> makeError()require.js:166
> intakeDefines()require.js:1221
> localRequire/<()require.js:1408
> 1require.js:166:17
> 

Does this error is related to Swiper?

**Comment by nolimits4web** [comment]
Not Swiper related
