### ISSUE TITLE
Pagination outside the slider

### ISSUE THREAD

**Issue by isoriaizquierdo** [nolimits4web/Swiper#1763]
Is it possible to get the pagination bullets outside the slider area (where the image is)?
I have tried different things with CSS, but no luck...
Thanks!

**Comment by nolimits4web** [comment]
Yes, just put pagination's HTML element where you needed

**Comment by HHGB12** [comment]
https://media.giphy.com/media/Z95A4g4GOYz60/giphy.gif

**Comment by HHGB12** [comment]
https://giphy.com/gifs/Z95A4g4GOYz60/html5

**Comment by HHGB12** [comment]
[``](https://giphy.com/gifs/Z95A4g4GOYz60/html5)

**Comment by HHGB12** [comment]
![giphy](https://user-images.githubusercontent.com/24680535/34643912-28927fb6-f32d-11e7-9c3b-7d137396ad57.gif)
