### ISSUE TITLE
Update swiper velocity on freeMode

### ISSUE THREAD

**Issue by pierrechls** [nolimits4web/Swiper#1764]
How could I change global velocity ? I think the sensitivity of my touch screen is too high but It would be great if we could change global Swiper velocity.

Something like this : 
`slider = new Swiper('.swiper-container', {
      slidesPerView: 4,
      speed: 1000,
      centeredSlides: true,
      spaceBetween: 50,
      freeMode: true,
      freeModeSticky:	true,
      velocityRatio: 0.5 
})`

I had to add `s.velocity = s.velocity / 2` after this line https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L1679

**Comment by BrettGregson** [comment]
+1

**Comment by pierrechls** [comment]
If you want, I've forked and implemented this : [pierrechls/swiper](https://github.com/pierrechls/swiper)
