### ISSUE TITLE
Black fields in Firefox 38.8 ESR on Windows 7

### ISSUE THREAD

**Issue by wiewioor** [nolimits4web/Swiper#1768]
I have an issue that appears in Firefox 38.8 ESR (latest corporate version) on Windows 7.
After animation of slide and texts, there are black fields on the slider:
1. On a part of text on slider
2. Between arrows, through the whole slider horizontally.

![capture2](https://cloud.githubusercontent.com/assets/20246783/16529555/d8850c0a-3fc3-11e6-97f7-7fe51d9fc955.jpg)

Can you please help?

**Comment by nolimits4web** [comment]
Looks like it is FF rendering issue, there is nothing such black in Swiper itself
