### ISSUE TITLE
chilren can not hover or select on firefox

### ISSUE THREAD

**Issue by ccqgithub** [nolimits4web/Swiper#1770]
the problem is:
when then parent element has `preserve-3d`, the children element can not click and select(on my mac firefox).

i find the solution: set `translateZ(10px)` to the children element can resolve the problem, but if i do this ,it will overrite the style that has added by swiper……

**Comment by ccqgithub** [comment]
it seems to that: if the translateZ less than `0px` the element can not selected on my firefox

**Comment by ccqgithub** [comment]
i resolve this issue by set `depth` to a negative：
```
coverflow: {
        rotate: 50,
        stretch: 0,
        depth: -100,
        modifier: 1,
        slideShadows: true
      },
```

**Comment by nolimits4web** [comment]
Yeah, that is how different browsers treat 3d perspective. And this is how FF does, i don't see workaround here, it is more FF bug
