### ISSUE TITLE
Could you add callbacks like 'scroll,scrollStart,scrollEnd' in IScroll?

### ISSUE THREAD

**Issue by angry-Dylan** [nolimits4web/Swiper#1774]
Sometimes I need to do something while scrolling, and not just with finger. So the 'onTouchMove' callback is not enough for me.

**Comment by a-zharkov** [comment]
+1. Could you please add such events.

When the parameter "mousewheelControl" set to true, then there are no callback triggered when user scroll the slider by mouse wheel or touch pad.

Thank you.
