### ISSUE TITLE
carousel for smart tv app

### ISSUE THREAD

**Issue by saimirg** [nolimits4web/Swiper#1776]
I searched through the issues before asking this question and found out that by design, the last item 2 items on the carousel cannot be selected/navigated to using the keyboard. Since all smart tvs are navigated through remote control, is there any way to circumvent this?
The centeredslides parameter makes it possible to navigate through all items using keyboard, but it starts with a gap on the left and it also ends with a gap on the right, which we dont want.

Thank you.

**Comment by nolimits4web** [comment]
No, "active slide" is depends only on position, otherwise you need to specify your own logic to highlight selected slides
