### ISSUE TITLE
Cannot set initial slide with certain parameters

### ISSUE THREAD

**Issue by stevenmwade** [nolimits4web/Swiper#1779]
Cannot set `initialSlide` when setting `allowSwipeToPrev` and `allowSwipeToNext` to false.

http://codepen.io/anon/pen/RRLzkv

**Comment by openks** [comment]
it's not reasonable to set both `allowSwipeToPrev` and `allowSwipeToNext` to false,if so, you can just use a div instead

**Comment by stevenmwade** [comment]
@openks If it's not reasonable set both of them, why is that an option? I also have another that is set to `externalOnly` and it still does not work.
