### ISSUE TITLE
swiper.d.ts

### ISSUE THREAD

**Issue by feurjarx** [nolimits4web/Swiper#1783]
swiper.d.ts(88,43): error TS7006: Parameter 'distance' implicitly has an 'any' type.
swiper.d.ts(89,42): error TS7006: Parameter 'distance' implicitly has an 'any' type.
swiper.d.ts(129,5): error TS7008: Member 'params' implicitly has an 'any' type.
swiper.d.ts(130,5): error TS7008: Member 'positions' implicitly has an 'any' type.
swiper.d.ts(159,5): error TS7008: Member 'touches' implicitly has an 'any' type.
swiper.d.ts(178,26): error TS7006: Parameter 'duration' implicitly has an 'any' type.

**Comment by kraftwer1** [comment]
+1

**Comment by nolimits4web** [comment]
Not related to this repository
