### ISSUE TITLE
Responsive Break Points Not Working

### ISSUE THREAD

**Issue by VetroMedia** [nolimits4web/Swiper#1787]
Below is the code I'm using but cant seem to get my break points to work.
any ideas?
var swiper = new Swiper('.s1', {
	        slidesPerView: 5,
	        slidesPerColumn: 2,
	        spaceBetween: 30,
			nextButton: '.swiper-button-next',
        	prevButton: '.swiper-button-prev',
	        breakpoints: {
	            1024: {
	                slidesPerView: 5,
	                spaceBetween: 30
	            },
	            768: {
	                slidesPerView: 1,
	                spaceBetween: 10
	            },
	            640: {
	                slidesPerView: 1,
	                spaceBetween: 10
	            },
	            320: {
	                slidesPerView: 1,
	                spaceBetween: 10
	            }
	        },
	      });

	      var swiper = new Swiper('.s2', {
	        pagination: '.swiper-pagination',
            paginationClickable: true,
            slidesPerView: 3,
	        spaceBetween: 30,
       		nextButton: '.swiper-button-next',
        	prevButton: '.swiper-button-prev',
	        breakpoints: {
	            1024: {
	                slidesPerView: 2,
	                spaceBetween: 30
	            },
	            768: {
	                slidesPerView: 1,
	                spaceBetween: 10
	            },
	            640: {
	                slidesPerView: 1,
	                spaceBetween: 10
	            },
	            320: {
	                slidesPerView: 1,
	                spaceBetween: 10
	            }
	        },
	      });

**Comment by nolimits4web** [comment]
Hard to say without example. If this issue is still actual, create new one and provide more details
