### ISSUE TITLE
After navigating Swiper with hashnav enabled, Swiper jumps to the next slide on page reload, instead of showing the same slide.

### ISSUE THREAD

**Issue by jared83** [nolimits4web/Swiper#1790]
The behaviour can be observer [here](http://deep-waves.com/).
This service is still in development (though about to be launched).
The vertical issue navigation are Swipe bullets generated with a function.
Note that the [Pagepiling plugin ](https://github.com/alvarotrigo/pagePiling.js) I use to navigate the website (via the horizontal nav) also uses hash navigation.
If I disable hash navigation for pagepiling the issue still occurs.
Can you please have a look at is asap? We are launching the service very soon.
Thank you for your help.
Best regards

**Comment by jared83** [comment]
Um... is this project still active?

**Comment by nolimits4web** [comment]
Looks like conflict somewhere in your side, as you can see it works fine here http://idangero.us/swiper/demos/25-hash-navigation.html#slide3
