### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by mrdv** [nolimits4web/Swiper#1793]
Hi there,

Anyone has troubles with safari displaying the images?

The html generated from swiper has no background images at all. 

`<div class="swiper-slide" style="width: 320px;" data-swiper-slide-index="0"></div>`

The div slides dont have any style in them. 

Console return no errors. 

var imageTabSwiper = new Swiper('.image-tab-swiper', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        spaceBetween: 0,
        effect: 'slide',
        autoplay: 5000,
        loop: false,
        paginationBulletRender: function (index, className) {
          var fake_index = index +1;  
          return '<span class="' + className + " " + cssClass + '">' + $('[data-order='+fake_index+']').data('value') + '</span>';
        }
    });

**Comment by nolimits4web** [comment]
Looks like you just don't have an images inside or some error in HTML markup
