### ISSUE TITLE
Disable swipe, disable navigation

### ISSUE THREAD

**Issue by ivelfan** [nolimits4web/Swiper#1794]
Hello,

I try something unusual with Swiper : I want to disable swiping/sliding touch move and only change slide programmatically.
I disable swiping move : 
`vm.sliderOptions = {
            loop            : false,
            effect          : 'flip',
            speed           : 200,
            initialSlide    : 0,
            pagination      : false,
            simulateTouch   : false,
            allowSwipeToNext: false,
            allowSwipeToPrev: false
        };`

And I can't slide to another slide programmatically : `vm.slider.slidePrev();`
I need to unlock swipe to do that : 
`vm.slider.unlockSwipeToPrev();
  vm.slider.slidePrev();
  vm.slider.lockSwipeToPrev();`

Do I miss something ?

Thanks

**Comment by nolimits4web** [comment]
Yes, if you lock swipes it won't be moved, so you doing things right

**Comment by jfitz0** [comment]
IMO it would be a useful feature to disable manual swiping while allowing programatic swiping rather than unlocking, sliding, and then locking again.

**Comment by glemiere** [comment]
Or you can simply create a transparent overlay over the swiper. Works like a charm 👌

**Comment by ngouy** [comment]
@glemiere I wonder how you are doing that: it doesn't work at all for me... Even with an overlay with `pointer-events: none`

**Comment by glemiere** [comment]
I have the swiper and the overlay inside a div, they’re both in position absolute, and my overlay has a greater z-index than my swiper ;-)

**Comment by AStaege** [comment]
Same problem here, but with more responsivity, thus resizing and stuff, and lazy loading of images. Makes it difficult to retrieve height and width for the overlay. Would be nice, when there would be any functionality like initial rendering and then disabling the whole thing (i'm using coverflowEffect, without auto swiping)

**Comment by glemiere** [comment]
My overlay is totally responsive, using % and calc() in css should be enough ;)
