### ISSUE TITLE
stopAutoplay on hover at exact position

### ISSUE THREAD

**Issue by taitaro** [nolimits4web/Swiper#1798]
Hello,

my swiper works with linear transition-timing, thus it is constantly running. It is supposed to stop on hovering. 
When I hover over a slide it stops autoplaying, but only after it finished its current transition, so it won't stop immediately.

Is there something that might help with a smooth stop and start on hovering?

Thanks

**Comment by huiyikang** [comment]
Of course, I need this function like you, i try to modify the source but still i'm not so familier with the slider my code still have many bugs. I will share it to you after i done it. @taitaro

**Comment by taitaro** [comment]
@huiyikang 

I found a solution, how to stop the Swiper immediately on hover. 

It is simple configuration, without modifying the source.

`
var transformValue;
$(swiper.wrapper).hover(function() {
  swiper.stopAutoplay();

  //here you remember the translation, the swiper originally wanted to go
  transformValue = this.style.transform;

  //then you set the transition duration on zero

  this.style.transitionDuration = "0ms";

  //then you set the wrapper translation hard on its current translation value
  //this might also work with swiper.setWrapperTranslate(swiper.getWrapperTranslate())
  this.style.transform = "translate3d(" + swiper.getWrapperTranslate() + "px, 0px, 0px)";

}, function() {

  //here you set the transition duration back to it's original value
  this.style.transitionDuration = swiper.params.speed + "ms";
  
  //and give it back its originial destination
  this.style.transform = transformValue;

  //then start autoplay again
  swiper.startAutoplay();
}
`

**Comment by huiyikang** [comment]
@taitaro 
Hi dude，These days i was for a work travel,I was stubborn and do not consider about the way you said, it's really great.

My way is to modify the source code, but it looks a little complex and I defined a MouseHoverControl event when the mouse enter or out will active the event.

I will publish the code when i back home for your reference.

**Comment by huiyikang** [comment]
@taitaro Code like below

var defaults = {
********
********
//define the event, you could define it as you want
`//mouseoverControl`
  mouseoverControl: false,
//mouseoutControl
   mouseoutControl: false,
********
********
}



 /*=========================
          mousehover Control
          ===========================*/
        //active the function to stop the animation
       function handleMouseOver(event){
            s.stopAutoplay();
        }
        //destroy the mouse over event
        s.disableMouseOverControl= function () {
            s.params.mouseoverControl = false;
            $(s.container).off('mouseover', handleMouseOver);
        
        };
        //bind the mouse over event
        s.enableMouseOverControl = function () {
            s.params.mouseoverControl = true;
            $(s.container).on('mouseover', handleMouseOver);
        };

        /*=========================
          mouseout Control
          ===========================*/
        //mouseout event
        function handleMouseOut(e){
            s.startAutoplay();
            //autoplay();   
        }
        s.disableMouseOutControl= function () {
            s.params.mouseoutControl = false;
            $(s.container).off('mouseout', handleMouseOut);
        };
        s.enableMouseOutControl = function () {
            s.params.mouseoutControl = true;
            $(s.container).on('mouseout', handleMouseOut);
        };



line 3521 (not accuracy)
     s.init = function () {
     *********
     //call the function to active mouse over event
      if (s.params.mouseoverControl) {
         if (s.enableMouseOverControl)      s.enableMouseOverControl();
        }
    //call the function to active mouse out event
      if (s.params.mouseoutControl) {
         if (s.enableMouseOutControl)       s.enableMouseOutControl();
         }
     *******
     }    

line  3620 (not accuracy)
s.destroy = function (deleteInstance, cleanupStyles) {
    ************
   //call the function to destroy mouse over event
    if (s.params.mouseoverControl) {
         if (s.disableMouseOverControl)          s.disableMouseOverControl();
    }
    //call the function to destroy mouse out event
     if (s.params.mouseoutControl) {
         if (s.disableMouseOutControl)              s.disableMouseOutControl();
     }

   *************
     }


use it just like below
var swiper = new Swiper({
     //all of the both default value is false, setting is true could active it 
     mouseoverControl: true,
     mouseoutControl: true
});


All of code like above FYR.
