### ISSUE TITLE
Problem with loop and autoplay

### ISSUE THREAD

**Issue by markbuettner** [nolimits4web/Swiper#1800]
We're using Swiper in one of our shops. We have one slider with 17 items in it. Swiper is initialized with the following code:

     var car_swiper = new Swiper('#home_slider_1', {
    	nextButton: '#car-slider .svg-button-next',
        prevButton: '#car-slider .svg-button-prev',
    	loop: true,
    	slidesPerView: 5,
     	slidesPerGroup:5,
    	autoplay: 4000,
        paginationClickable: true
    });

The problem is, as soon as the Swiper shows the last two items and the first three, this slide is stuck in an endless loop. 
It seems that this is a problem with the combination of loop and autoplay, using console.log I saw that the slideTo(slideIndex, speed, runCallbacks, internal) function is called three times with 3, 17 and 20 as slideIndex.

The live example can be found at [https://www.lott.de/de/](https://www.lott.de/de/) on the bottom of the page. The affected slider is the vehicle manufacturer slider.

**Comment by nolimits4web** [comment]
The issue here is that with such configuration you must have number of slides even to 5, so as a workaround i recommend you to add 3 empty slides to have 20 in total
