### ISSUE TITLE
swiper breakpoints are not responsive

### ISSUE THREAD

**Issue by AlainYahchouchi** [nolimits4web/Swiper#1804]
I have a swiper above 768px (ipad) slidesPerView: 'auto', and slidesPerGroup: 3,
**but under 768** :  horizSwiper.params.slidesPerView = 1;
        horizSwiper.params.slidesPerGroup = 1;

i am using breakpoints it work well when i resize from big screen to small screen but when i get back to big screen everything goes wrong..... on refresh all is gd...
it is not responsive?!
an help?

**my code:**

 var horizSwiper = new Swiper('#slider .screen', {
        loop: true,
        autoplay: 5000,
        speed: 1200,
        slidesPerView: 'auto',
        slidesPerGroup: 3,
        spaceBetween: 0,
        keyboardControl: true,
        breakpoints: {
            767: {
                slidesPerView: 1,
                slidesPerGroup: 1
            }
        }

```
});
```

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle with the issue to see it

**Comment by satodavan** [comment]
Swiper don't calculate width from slide's style after window resized from small viewport to large, if change  slidesPerView property from numeric to 'auto'. [JSFiddle](https://jsfiddle.net/satodavan/qortcq20/)

**Comment by sgoess** [comment]
I'm having this issue, too. Any plans on fixing this?

**Comment by apapacy** [comment]
After resize (breackpoint 980) autoplay not work

`
{
      pagination: '.swiper-pagination-about',
      autoplay: 12000,
      loop: true,
      speed: 3000,
      initialSlide: 0,
      slidesPerView: 3,
      slidesPerGroup: 3,
      touchRatio: 1,
      paginationClickable: true,
      centeredSlides: false,
      roundLengths: false, //значение true "ломает" слайдер (цикл)
      breakpoints: {
        980: {
          autoplay: 6000,
          loop: true,
          speed: 2000,
          initialSlide: 0,
          slidesPerView: 2,
          slidesPerGroup: 1,
          paginationClickable: true,
          centeredSlides: true,
          observer: true,
          observeParents: true,
          roundLengths: false,
        }
      },
    });
`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
