### ISSUE TITLE
Is it possible to chose direction of vertical scroll?

### ISSUE THREAD

**Issue by malyo** [nolimits4web/Swiper#1807]
Hello,

I want to merge 2 swipers, having one scroll up, and other one bottom. I only found direction option that determines horizontal/vertical, but not specific direction. Is it possible to achieve with current version of Swiper?

**Comment by nolimits4web** [comment]
You can use `allowSwipeToPrev` and `allowSwipeToNext` to allow scrolling for only one direction (top or bottom)
