### ISSUE TITLE
mousewheel jumping to second slide

### ISSUE THREAD

**Issue by gmourasilva** [nolimits4web/Swiper#1810]
Here is my scenario: 

I have a 100vh section and after I have a vertical Swiper container controlled by mousewheel.
When I scroll down I am supposed to stop on the swiper, see the slides and then see the rest of the website.

The issue that I am facing is that when I scroll I go straight to the second slide. 
I looked the API and this is what I did, combining mousewheelControl, mousewheelReleaseOnEdges and mousewheelSensitivity: 

http://plnkr.co/edit/1gPTqcYxhBMnbbkAaiYP?p=preview

Any suggestions in how to solve this? 

(Sorry for using this space, but I looked the other issues and documentation and didn't find something related)

**Comment by gmourasilva** [comment]
no one?

**Comment by nolimits4web** [comment]
It just means that during scroll from 100vh section (especially on macOs) swiper will receive mousewheel scroll event. Can't do much with it
