### ISSUE TITLE
.update() method not working

### ISSUE THREAD

**Issue by stergosz** [nolimits4web/Swiper#1811]
I init the swiper in a .js file and it is being displayed correctly on the screen.

When i try to grab it and reload it using the following code:

```
var swiper = parent.find(".slideshow")[0].swiper;

swiper.update(true);
```

I get the following error:

`Uncaught TypeError: Cannot read property 'update' of undefined`

**Comment by nolimits4web** [comment]
Then you use old version of Swiper, or you are referring to wrong element in dom
