### ISSUE TITLE
Prevent swipe for a single slide

### ISSUE THREAD

**Issue by gggg990** [nolimits4web/Swiper#1813]
I am using a php while loop to load slides from sql..
When I have multiple slides swipes work okay, but when there is only 1 slide you can still swipe right and left and it just loops the same slide again.. Is there a simple way to prevent this and have it fixed?

Best Regards,
Greg

**Comment by paOol** [comment]
hmm 

if ( count( $yourVariable) > 2 ) {
  // then include your swiper stuff
}

**Comment by klihelp** [comment]
@paOol the question is for the swipe functionality only, without switching off all other functionality which could include customisations.

The logic is to use the swiper api onInit callback function to modify the slider setting and trigger the swiper update.

**Comment by meredevelopment** [comment]
Could anyone, or @klihelp, expand on the answer above? I have a site using Swiper were pages often have just one slide. For these I want to remove autoplay, and disable any touch swipe action. 

Here's the sort of thing (not working) that I've tried: 

```javascript
var mySwiper = new Swiper ('.swiper-header', {
  'onInit': function(){
    if ( mySwiper.slides.length > 2 ) {
      this.autoplay = false
    }
  },
  direction: 'horizontal',
  loop: true,
  autoplay: 2000,
  autoplayDisableOnInteraction: true,
  spaceBetween: 16,
  nextButton: '.swiper-button-next',
  prevButton: '.swiper-button-prev',
});
```

In the above code, the slides.length is not accessible there. 
Interesting, if I remove the 'if' statement, and just set autoplay to false in the onInit function, the swiper slides once, then stops.

What am I doing wrong please...
