### ISSUE TITLE
Gap on Righthandside

### ISSUE THREAD

**Issue by Gouvi** [nolimits4web/Swiper#1814]
I have the swiper-container width set to 100%, have not set a pre-determined width and the slides are randomly coming up with a 16px gap on the righthandside. On some page refreshes it is not an issue, if I open dev tools it re-calculates and sets the correct width.

Am I missing a setting for the responsive 100% width to work?

**Comment by nolimits4web** [comment]
It depends on how this gap is set, but you have to make sure it is set via CSS margin-right on slides or just use spaceBetween
