### ISSUE TITLE
The Swiper-way to use breakpoints

### ISSUE THREAD

**Issue by sydneykaiserman** [nolimits4web/Swiper#1817]
I have studied the market for image sliders and carousels for many years and I have to say that nothing comes close to Swiper. It really is a revolutionary piece of software. I am trying to make it the go-to software for every e-commerce website I build as I really think Swiper can be adapted to most scenarios. However, it is true that today, many websites require a nice slider for tablets and desktop but just need images stacked on top of one another on mobile devices, without a slider. Users are used to scroll up and down on small screens and this is a trend that seems to grow stronger and stronger. I have done a lot of research and all the solutions for implementing this functionality with Swiper point to convoluted workarounds which result in buggy and inconsistent behavior across devices. One of the most common solutions suggests destroying Swiper when resizing the browser window to a narrower state but Swiper does not recreate itself properly if the browser window is increased again.

What is the current true “Swiper-way” to display staked images (without swiper) on mobile devices and to have Swiper take over when the browser window is increased to 768 or above?

**Comment by nolimits4web** [comment]
One of the solutions is to destroy/init Swiper. Another way is breakpoints (see docs), you can also just disable swiping on large screens using appropriate methods
