### ISSUE TITLE
watchSlidesVisibility cause slides flickering 

### ISSUE THREAD

**Issue by 350d** [nolimits4web/Swiper#1820]
If `watchSlidesVisibility` set to `true` and you trying to hide/show/animate somehow non visible elements like in [this example](https://jsfiddle.net/350D/u1etgpmj/) — slides start flashing after first or 4 transitions in both cases autoscroll and manual.

I've tried to update `updateSlidesProgress` function to minimize DOM manipulations - no luck, it doesn't help.

            // Visible Slides
            
            for (var i = 0; i < s.slides.length; i++) {
                var slide = s.slides[i];
                var slideProgress = (offsetCenter - slide.swiperSlideOffset) / (slide.swiperSlideSize + s.params.spaceBetween);
                if (s.params.watchSlidesVisibility) {
                    var slideBefore = -(offsetCenter - slide.swiperSlideOffset);
                    var slideAfter = slideBefore + s.slidesSizesGrid[i];
                    var isVisible =
                        (slideBefore >= 0 && slideBefore < s.size) ||
                        (slideAfter > 0 && slideAfter <= s.size) ||
                        (slideBefore <= 0 && slideAfter >= s.size),
                        slideToUpdate = s.slides.eq(i);
                    if (isVisible) {
                        if (!slideToUpdate.data('slideVisible')) {
                        	console.log('Add slideVisible');
                        	slideToUpdate.addClass(s.params.slideVisibleClass).data('slideVisible',true);
                        }
                    } else {
                    	if (slideToUpdate.data('slideVisible')) {
                    		console.log('Remove slideVisible');
                    		slideToUpdate.removeClass(s.params.slideVisibleClass).data('slideVisible',false);
                    	}
                    }
                }
                slide.progress = s.rtl ? -slideProgress : slideProgress;
            }

**Comment by nolimits4web** [comment]
It happens because you have loop:true, in your logic you should also consider looped/duplicated slides

**Comment by 350d** [comment]
Sorry, but i don't get the point. Check my CSS for visible/hidden slides - can you tell me whats wrong in my logic there? Only i have is `.swiper-slide {opacity:0}` and `.swiper-slide-visible, .swiper-slide-active {opacity: 1}` and it's doesn't work.

**Comment by nolimits4web** [comment]
Look at slider html in dev tools. There are duplicated slides, this is how the loop works, when it slides to somepoint it immediately change slider position and classes, but because you have animation on elements you see this delay/flickering

**Comment by 350d** [comment]
I see how it works. But if you have 4 slides per view and 1 slide per slide and loop - there is no need to have 3 duplicates before and 3 after, and no need to redraw all slides on every slide, right? You can just clone first and last one to the end and to the beginning of the slider and always translate slider by -slideWidth pixels. Check my [example here](http://www.turpinmeadowranch.com) (slider after hero image). I mean, wipe and redraw of the visible slider part on every slide is not good looking solution here, what you think?
