### ISSUE TITLE
Crashed Safari/Chrome on iPad when nesting a sliding swiper inside a fading swiper

### ISSUE THREAD

**Issue by octoxan** [nolimits4web/Swiper#1821]
If you take a swiper instance that is set to fade, and nest a swiper instance that slides.. the browser crashes after the fading slide transitions.

"Aw, snap" page in Chrome. Page reload in Safari.

**Comment by nolimits4web** [comment]
Can't replicate it nor in Safari not in Chrome. Probably something related to your slides content. If it is still actual. Create new issue and provide more details
