### ISSUE TITLE
when i slide one for and another,it can't run onSlidereChangeEnd this function

### ISSUE THREAD

**Issue by semi-xi** [nolimits4web/Swiper#1822]
i click section one drag to slide for another section ，the callback can't run onSlidereChangeEnd。only can run onTransitionStart and onTransitionEnd

**Comment by nolimits4web** [comment]
Yes, because these callbacks are attached to transitions, so the slide is being changes within your long touch move, not within transition, so it is not being fired. Use `onTransitionEnd` instead
