### ISSUE TITLE
Unable to set initial slide in safari

### ISSUE THREAD

**Issue by nunocsilva** [nolimits4web/Swiper#1824]
I'm using various instances of swiper in the same page, they slide fine, but i'm having some trouble setting my initial slide, if i inspect the slider elements, my active slide is the last one, witch is weird. This is happening on Safari, on chrome and firefox the first slider is active, even though it is swiper-slide-duplicate, but i don't mind this.
Here's the code i'm using.

`var guestHouseSlide = $(this);
$this.swiper({
        initialSlide: 0,
        centeredSlides: false,
        spaceBetween: 0,
        slideToClickedSlide: true,
        loop: true,
        slidesPerView: 'auto',
        onSliderMove: function(swiper) {
            $this.parent(".photoContent").addClass("visible");
         
        },
        breakpoints: {
            768: {
                centeredSlides: true,
                loop: true
            }
        }, 
        onInit: function(){
            
        }
    });`

If i remove the slidesPerView, the first slide is selected has the active slide , but visually i don't get the result i want.

Anyone with some clue why this is happening?

**Comment by nolimits4web** [comment]
I guess this happens because on the moment of slider initialization it is invisible. Run it's `update()` method after it becomes visible or enable `observer` properties
