### ISSUE TITLE
Problem with widths of slide contents in versions of Firefox before 22.

### ISSUE THREAD

**Issue by Kravimir** [nolimits4web/Swiper#1825]
In browsers that "display:-moz-box" is being applied, percentage widths seem not to work correctly on the children of a slide (in at least some cases).  I saw the problem in a mobile-first design.

Fortunately a workaround for "width:100%" is easy:
`.swiper-slide>* {width:inherit} `

**Comment by nolimits4web** [comment]
Sorry, 3-years old FF not really a Swiper's target especially if there is simple fix for this
