### ISSUE TITLE
watchSlidesVisibility doesn't work correctly when roundLengths is set to false?

### ISSUE THREAD

**Issue by rezadaraee** [nolimits4web/Swiper#1828]
Hi,
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.3.1
* Platform/Target and Browser Versions: macOS, CHROME.

I'v found a bug that cause some problems in my code. when i set **roundLenghts** to false, swiper add visibleItem class to out of view slides(the slide before first visible slide and the slide right after last visible slide) when slides width is **decimal**.
I'v test in responsive demo of swiper package with fallowing configuration:

    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        roundLengths:false,
        slidesPerView:3,
        watchSlidesVisibility:true,
        paginationClickable: true
    });

Please check it.

Thanks in advance

**Comment by nolimits4web** [comment]
Sorry can't see such problem, as by the way `roundLengths` is always `false` by default
