### ISSUE TITLE
A bug about switching effect？

### ISSUE THREAD

**Issue by z649319834** [nolimits4web/Swiper#1829]
y.effects = {
                    fade: {
                        setTranslate: function () {
                            for (var e = 0; e < y.slides.length; e++) {
                                var a = y.slides.eq(e), t = a[0].swiperSlideOffset, s = -t;
                                y.params.virtualTranslate || (s -= y.translate);
                                var r = 0;
                                y.isHorizontal() || (r = s, s = 0);
                                var i = y.params.fade.crossFade ? Math.max(1 - Math.abs(a[0].progress), 0) : 1 + Math.min(Math.max(a[0].progress, -1), 0);
                                a.css({opacity: i}).transform("translate3d(" + s + "px, " + r + "px, 0px)")
                            }
                        }

The wrong place：var i = y.params.fade.crossFade ? Math.max(1 - Math.abs(a[0].progress), 0) : 1 + Math.min(Math.max(a[0].progress, -1), 0);

Should be changed to：var i = !y.params.fade.crossFade ? Math.max(1 - Math.abs(a[0].progress), 0) : 1 + Math.min(Math.max(a[0].progress, -1), 0);

**Comment by nolimits4web** [comment]
No, everything is correct
