### ISSUE TITLE
The difference between idangerous.swiper.min.js and swiper.min.js

### ISSUE THREAD

**Issue by bonnielai** [nolimits4web/Swiper#1831]
I find that the older version , less than 2.7.6, is named idangerous.swiper.min.js ; but the newer version is named swiper.min.js. Some method of idangerous.swiper.min.js is not in swiper.min.js, such as "swipeTo". Is it true that the idangerous.swiper.min.js is just the old version? Should I change the  idangerous.swiper.min.js to swiper.min.js?

**Comment by Bessonov** [comment]
@bonnielai Look at slideTo method. I think it was renamed.

**Comment by nolimits4web** [comment]
@bonnielai i believe what you have find with `swipeTo` method is the old version. Use the package and documentation from website http://idangero.us/swiper/

**Comment by bonnielai** [comment]
Thanks for your answer ! I have found the new method and resolve the problem. The slideTo method is the new one in new version to replace the swipeTo method and the swiper.min.js is the name of new version.
