### ISSUE TITLE
Swiper loop doesn't work for IE9

### ISSUE THREAD

**Issue by jantimon** [nolimits4web/Swiper#1834]
Swiper.jQuery works quite nice on IE9 however if setting `loop:true` it gets stuck after clicking the arrows once.

Is there any way to fix this?

**Comment by jantimon** [comment]
Just tested #1833 and it fixes the issue by getting around the missing transitionEnd event in IE9.

**Comment by nolimits4web** [comment]
Fixed by #1833

**Comment by jantimon** [comment]
@nolimits4web will you release this soon?
