### ISSUE TITLE
Detach a single event from a swiper

### ISSUE THREAD

**Issue by SwordElucidator** [nolimits4web/Swiper#1836]
Thanks a lot for this excellent swiper!

I tried to only detach one or several events from a swiper.
 I saw that there are functions
```javascript
mySwiper.detachEvents(); //Detach all events listeners
mySwiper.attachEvents(); //Attach all events listeners again
```

Is there a function that can do something like following?
```javascript
mySwiper.detachEvent("swipeup") //To detach swipe up event, and also for attach
```

Thank you!

**Comment by nolimits4web** [comment]
No, there is no such function as basically there is no much sense in it. There are other methods/ways to disable some not needed functionality
