### ISSUE TITLE
apple ios10 a notice prev function() {this.dir=- 1} next function () {this.dir=1 }

### ISSUE THREAD

**Issue by chuhemiao** [nolimits4web/Swiper#1844]
页面中轮播图直接显示这段代码，求告知这是什么原因？bug？

http://lp.gaeamobile.net/adownload/landPageThree825

**Comment by chuhemiao** [comment]
@nolimits4web

**Comment by nolimits4web** [comment]
Can you please describe it in more details and in English?

**Comment by chuhemiao** [comment]
@nolimits4web sorry, I got mixed up，this is a  Swiper  problem.

**Comment by chuhemiao** [comment]
@nolimits4web  sorry, I got mixed up,this is a zepto problem,My custom label.
