### ISSUE TITLE
$(...).outerWidth is not a function

### ISSUE THREAD

**Issue by lifetin** [nolimits4web/Swiper#1848]
$(...).outerWidth is not a function

swiper.jquery.js

Zepto not method outerWidth

**Comment by odahcam** [comment]
`$(elem).width()` --- jQuery
`$(elem)[0].offsetWidth` --- JavaScript

From jQuery `outerWidth()` docs:
| This method is not applicable to window and document objects; for these, use .width() instead.

Maybe the `$(elem)` is not a DOM object.

**Comment by lifetin** [comment]
I have to rewrite it, the problem is solved.

  Zepto.fn.outerWidth = function(){
     return $(this).width();
  }

thnks
