### ISSUE TITLE
slidesPerView breakpoints does not work

### ISSUE THREAD

**Issue by sanderha** [nolimits4web/Swiper#1852]
This is my code:
```
				loop: false,
				speed: 700,
				nextButton: '.swiper-button-next-info',
				prevButton: '.swiper-button-prev-info',
				slidesPerView: 3,
				spaceBetween: 15,
				breakpoints: {
					900: {
						slidesPerView: 2
					},
					640: {
						slidesPerView: 1
					}
				}
```
I am using the jQuery version. My version constraint is ~3.1.2. Nothing happens on breakpoints, it just stays as default setting

**Comment by nolimits4web** [comment]
Would be good to see live example

**Comment by nolimits4web** [comment]
Closing as no further discussion

**Comment by xurshid29** [comment]
Same problem here.
![screen shot 2017-07-25 at 12 17 19 pm](https://user-images.githubusercontent.com/5887811/28560262-6105c82a-7133-11e7-973c-624c60651595.png)
![screen shot 2017-07-25 at 12 17 57 pm](https://user-images.githubusercontent.com/5887811/28560267-65dd2c58-7133-11e7-8565-5cb286af8cb7.png)

**Comment by xurshid29** [comment]
Working now, after replacing with http://idangero.us/swiper/dist/js/swiper.min.js
