### ISSUE TITLE
Class names active/next/prev issue with 2 slides

### ISSUE THREAD

**Issue by gabma** [nolimits4web/Swiper#1857]
* [x] bug
* Swiper Version: 3.1.1

I'm trying to show a swiper with only 2 slides.

Here are the settings:
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev',
      slidesPerView: 3,
      loop: false,
      hashnav: true,
      centeredSlides: false,
      spaceBetween: 0,
      slideToClickedSlide: false

First slide (slide1) has the class name swiper-slide-active
Next slide (slide2) has the class name swiper-slide-next

But when clicking on slide2, I would have expected it to get updated with the class name swiper-slide-active, but it stayed swiper-slide-prev. Slide1 would have become swiper-slide-prev

Is this a desired  behavior ?

**Comment by nolimits4web** [comment]
No, swiper classes depends only on slides position, so if nothing changes then no classes changes
