### ISSUE TITLE
Высота блоков в iOS высчитывается некорректно.

### ISSUE THREAD

**Issue by edDimensi** [nolimits4web/Swiper#1862]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.3.1 jquery
* Platform/Target and Browser Versions: iOS 9.1, 9.3, 10

### What you did
Поставил вертикальную прокрутку и сделал слайды на всю высоту через 100vh, слайдер на iOS высчитывает почему-то с лишними пикселями. Примерно на 10-20 пикселей ошибается. Я подумал, что проблема в том, что у меня весь js в одном файле из-за этого не успевает правильно построится, поэтому код делил и помещал весь активный в шапку, но все без толку. На android устройствах и пк такой проблемы не заметил. Только на айфонах и айпадах. 
Вот живой пример http://knowprof.ru. 
Как это лечить? Заранее спасибо за ответ.

**Comment by nolimits4web** [comment]
Еще актуально? Я честно вроде не вижу бага. Если актально, то укажите проблемные места на скриншоте

**Comment by edDimensi** [comment]
Да, моя ошибка, не предоставил скриншотов. Проблему решил переходом на другой плагин.
