### ISSUE TITLE
Can't use Scrollify with Swiper

### ISSUE THREAD

**Issue by niko9911** [nolimits4web/Swiper#1864]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.3.1
* Platform/Target and Browser Versions:  All

### What you did
I used ´scrollify.js´ script.

### Expected Behavior
It should be: https://i.gyazo.com/ee33b37c41acb863a1e8bde84a4b0f36.jpg

### Actual Behavior
And result is this: https://i.gyazo.com/fcb6766a0cc595283d1b1bc951b4a627.jpg

**Comment by nolimits4web** [comment]
The issue is not related directly to Swiper. Make sure you have correct not overlapping styles and you init libraries in correct order

**Comment by niko9911** [comment]
Not meant to be evil, but by looking console it's your problem. If you don't feel responsible about your library, keep it then yourself. There is many other libraries to use. Thanks for nothing and bye.
