### ISSUE TITLE
iOS 6-9 issues with bootstrap 3 not respecting width

### ISSUE THREAD

**Issue by frecinos** [nolimits4web/Swiper#1869]
Using swiper 3.3.1 with bootstrap 3, freemode and slidesperview auto. When rendering on iOS devices the swiper horizontal view streches the container out of viewport and unable to slide.

When given swiper-container a fixed width via css it works but is not responsive. When given a width via options like "width: 450" is not respected.

This issue does not happens on android devices.

**Comment by nolimits4web** [comment]
The issue is likely related to bootstrap and its styles. Start searching from there, as Swiper itself and all its variations is greatly compatible with iOS Safari
