### ISSUE TITLE
Passive Event Listeners

### ISSUE THREAD

**Issue by sparkrevolutions** [nolimits4web/Swiper#1870]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I've got swiper running in an app to emulate some side-by-side pagination in a grid. It works great!

However as our App is beginning to do alot of complex logic in the background, it has become a constant battle to maintain smooth animation.

I am starting to see this message a lot in the console on Swiper:

Handling of 'touchstart' input event was delayed for 160 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

I have done a little bit of reading on the new passive event listeners and the general response seems to be that performance is greatly enhanced on scroll based activity - however it has to be implemented properly.

Anyway, my question is if Passive Event Listeners are in your roadmap at all?

**Comment by sparkrevolutions** [comment]
Thank you!

Has made a huge difference straight from dropping it in 👍

**Comment by nolimits4web** [comment]
@sparkrevolutions really?) I don't have Android device to really test it, made it basically in blind

**Comment by sparkrevolutions** [comment]
Yeah - I have a swiper with 100~ slides, with each slide containing a masonry grid of 9 items on a Cordova-based EmberJS app on iOS 10.0.2 (iPad Air 2).

Only the slides within 5 of the active slide have "proper" content, the rest are just empty white boxes.

Before, sliding forward say 5 slides and then sliding again whilst my App was sorting out content would lock the UI for at least a second.

Now, I can continue to swipe without the UI lock. Only small lag remains which I need to sort in my own code.

**Comment by nolimits4web** [comment]
Ok, cool)

**Comment by JacobDB** [comment]
@nolimits4web is there any way that `moveCapture` [here](https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L1351-L1371) can be changed to a passive listener? Trying to get a perfect PWA score from [Lighthouse](https://github.com/GoogleChrome/lighthouse). If it's not possible, then that's fine, just figured I'd ask :)
