### ISSUE TITLE
SWIPPER EFFECT FLIP

### ISSUE THREAD

**Issue by salimbenfarhat** [nolimits4web/Swiper#1872]
My probleme concerns this demo : http://idangero.us/swiper/demos/35-effect-flip.html
I want to integrate at this slide : 
- One image at the left and one at the right.

Look the picture to see what I want and if you can help me please.
![1](https://cloud.githubusercontent.com/assets/18363859/19079297/752c7d70-8a53-11e6-961b-0f6af497055c.PNG)

And when I click at right arrow for exemple, the image at the left image passes through the center, etc..

**Comment by nolimits4web** [comment]
Nope, it is not possible. Flip effect works only with single slide per view
