### ISSUE TITLE
Navigation on second Swiper control first Swiper, created with same name

### ISSUE THREAD

**Issue by DeniR** [nolimits4web/Swiper#1873]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.3.1
* Platform/Target and Browser Versions: All

### What you did
1. Create multiple Swiper with navigation divs
2. Init all with single call  var mySwiper = new Swiper ('.swiper-container');
3. Press navigation button Prev and Next on second button
4. They controls first and second Swiper simultaneously

### Expected Behavior
Every navigation button control only they Swiper

### Actual Behavior
Every navigation button control all Swiper simultaneously

**Comment by samuelbalin67** [comment]
You need a unique class for every slider and for every navigation button. Then init each slider one by one with its own navigation buttons using these new unique classes.

It's quite long, but it will allow you to have different options for your sliders.

**Comment by nolimits4web** [comment]
Take a look at `uniqueNavElements` parameter
