### ISSUE TITLE
Auto resize images on swiper, without distort them. Using responsive demo

### ISSUE THREAD

**Issue by MikeFranc** [nolimits4web/Swiper#1874]
I'm trying to use the swiper on my new website. but I cannot manage to make the images to full fit the swiper area.
Also in little screens the images distort a lot.
How can I control the width and height of the images according to the screen size?
with css? or swiper has some how a way to control it?

Thanks in advance

**Comment by nolimits4web** [comment]
Swiper doesn't control images, use CSS to achieve it
