### ISSUE TITLE
Breakpoints appears not working properly

### ISSUE THREAD

**Issue by edirpedro** [nolimits4web/Swiper#1875]
Test: https://jsfiddle.net/sdvz3L4a/2/

I tried many options, like destroy the object and instantiate it again, but it doesn't work too. The second and third swiper are for explain how it should work in different screen sizes.

Are breakpoints working as it expect?
Do you have any idea about how to implement such thing without breaking on resize window?

**Comment by nolimits4web** [comment]
You use `loop` in your breakpoints. There is a statement in docs about it 
> Not all parameters can be changed in breakpoints, only those which are not required different layout and logic, like slidesPerView, slidesPerGroup, spaceBetween. Such parameters like slidesPerColumn, loop, direction, effect won't work
