### ISSUE TITLE
Change allowSwipeToNext on the fly doesn't work

### ISSUE THREAD

**Issue by Defcon0** [nolimits4web/Swiper#1876]
This is a (multiple allowed): bug

* Swiper Version: Latest tag
* Platform/Target and Browser Versions: Ionic 1.3, cordova 6, Chrome

### What you did
I want to achieve the following:

A slider implemented using Swiper (http://idangero.us/swiper) should have 4 slides. But the last one shouldn't be reachable by swiping but only programmatically if some condition is fulfilled.

I thought I could retrieve activeIndex in the onSlideChangeStart() event and use that as condition for setting "allowSwipeToNext". But no success: It seems I can't change that option on the fly in an event.

**Comment by nolimits4web** [comment]
There is a `lockSwipeToNext()` method to achieve this and it works
