### ISSUE TITLE
Unable to work in a div display:none

### ISSUE THREAD

**Issue by fe719319448** [nolimits4web/Swiper#1877]
This is a (multiple allowed):bug
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.3.1
* Platform/Target and Browser Versions: macos . window 10  chrome firefox

### What you did
Put all the components in one div whitch is display:none

**Comment by nolimits4web** [comment]
Call `swiper.update()` when it becomes visible or enable `observer` options
