### ISSUE TITLE
Firefox autoheight and srcset sizes problem

### ISSUE THREAD

**Issue by albi** [nolimits4web/Swiper#1878]
Bug
Swiper Version: 3.3.1
Platform/Target and Browser Versions: Mac OS X 10.11.6 and Firefox 49

Maybe I've discovered a serious bug. I do have a gallery where I need the autoheight setting to be true. 'preloadImages', 'updateOnImagesReady' and 'runCallbacksOnInit' are set to true. And the callback is set to onImagesReady: function(swiper){swiper.update()}

So everything seems to be fine from this perspective. Safari and Chrome are working like expected. 

But in Firefox latest the swiper-container won't have the proper height. It is just as high as the previous and next buttons are. After changing the slide to the next one, the height is calculated.

I did some tests on my static templates and my (autoheight-) gallery was working there, even with Firefox. But not on the live (WordPress) version of the website. The only difference to the static templates is, that Wordpress uses true responsive images, my templates won't.

So I removed all responsive images from the WordPress code inside, the srcset attribute and the sizes attribute was removed too. After that it would work again in Firefox. Adding the srcset attribute without the sizes would work for Firefox. Adding the sizes attribute the gallery won't have the correct height.

For me this seems to be a serious bug. I thin I've nailed it down to autoheight and the sizes attribute withing the image tag.

My broken example:
http://contratto.ch/referenzen/erhaltungsprojekt-mositunnel-brunnen/

Maybe we could discuss this issue further to find a solution.

**Comment by albi** [comment]
Hi Vladimir,

is there any chance to grab the latest version of swiper to test the bugfix?

Kind regards
Alex

**Comment by albi** [comment]
Hi Vladimir,

I've updated to 3.4 but the bug is still there. http://contratto.ch/referenzen/erhaltungsprojekt-mositunnel-brunnen/ the same bug as before in Firefox latest (v49).

Kind regards
Alex

**Comment by katerlouis** [comment]
Could this have something to do with my issue?
On windows (chrome and firefox) when using only `srcset` in the `img` inside the `picture`-tag I get miscalculated initial height aswell.
#1899
