### ISSUE TITLE
swiper demo problem?

### ISSUE THREAD

**Issue by kimown** [nolimits4web/Swiper#1886]
The swiper  demo,when I open the demo
![image](https://cloud.githubusercontent.com/assets/7932380/19461904/3191fc2a-951b-11e6-9d64-03ab9c0199d8.png)

OK, I use an older version, 3.3.0, It works.
![image](https://cloud.githubusercontent.com/assets/7932380/19462307/7232e80e-951e-11e6-8121-df6f87464e18.png)

**Comment by klojniewski** [comment]
Related: #1888
