### ISSUE TITLE
Documentation update after sent Swiper Instance into paginationBulletRender

### ISSUE THREAD

**Issue by klojniewski** [nolimits4web/Swiper#1888]
Function: paginationBulletRender now takes:
- Swiper Instance
- index
- className

In documentation Swiper Instance is not included:

`paginationBulletRender(index,` `className)`

Commit id: 
https://github.com/nolimits4web/Swiper/commit/81291f009164ddf42db6cc9cb658bf84233072c6#diff-c1a8a21c933e1f48d90be645db83630f

**Comment by Kreozot** [comment]
Yes, please!
Because when you open official documentation you expect it to be actual.

**Comment by laco0416** [comment]
This is a **breaking change** absolutely. why isn't the major version raised?

**Comment by Tusko** [comment]
+1
