### ISSUE TITLE
get next/previous slide with slidesperview and loop="true" options

### ISSUE THREAD

**Issue by krizz07** [nolimits4web/Swiper#1896]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- Swiper Version: Swiper 3.2.7
- Platform/Target and Browser Versions: desktop web

i am making a simple swiper instance that looks like this

`<div class="swiper-cont">`
`<div class="swiper-wrapper">`
`<div class="swiper-slide"></div><!--slide 1-->`
`<div class="swiper-slide"></div><!--slide 2-->`
`<div class="swiper-slide"></div><!--slide 3-->`
`<div class="swiper-slide"></div><!--slide 4-->`
`<div class="swiper-slide"></div><!--slide 5-->`
`</div>`
`</div>`

the swiper is looped and has slidesperview=3. On the page, there should be the swiper with 3 slides viewable, while the rest is hidden. Let's say that slide 1,2,3 is currently visible. 

What i want to do is adding class to "slide 4" which currently hidden when the user slide next. This also apply when the user slide prev, in this case the duplicated "slide 5"

is there any way to get the next visible slide from an instance with slidesperview option?

my current experiment is:

`var slidetoanimate = $('.swiper-berita-index .swiper-slide-next').next().next();`
`slidetoanimate.addClass('left-behind');`

`publikasislideberita.on('onSlideNextStart', function(){`
`console.log('changed');`
`$('.swiper-slide').removeClass('left-behind');`
`slidetoanimate = $('.swiper-berita-index .swiper-slide-next').next().next();`
`slidetoanimate.addClass('left-behind');`
`});`

it is for the slide next behavior. It does work until the last non duplicated slide

for problem illustration please check out link below
[http://imgur.com/a/05X59](url)

in this case i need to get  slide 1 and 5 which are not visible

thanks

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
