### ISSUE TITLE
activeIndex is not right when set loop=true

### ISSUE THREAD

**Issue by mike8625** [nolimits4web/Swiper#1898]
activeIndex is not right when set loop=true

**Comment by mike8625** [comment]
var mySwiper = new Swiper('.swiper-container',{
    loop: true
  });
  alert(mySwiper.activeIndex); //expect 0,  result: 1 
//when loop Attribute add, "swiper-slide-duplicate" element add, and acitveIndex is wrong !

**Comment by mike8625** [comment]
alert(mySwiper.activeLoopIndex )  // undefined

**Comment by nolimits4web** [comment]
Read documentation about it in loop mode

**Comment by mike8625** [comment]
sorry, I couldn't read DOC seriously. mySwiper.realIndex is ok.
