### ISSUE TITLE
Responsive images initial height miscalculated when only using srcset

### ISSUE THREAD

**Issue by katerlouis** [nolimits4web/Swiper#1899]
This is a (multiple allowed):
- [x] bug

![f32be7ed-55ec-4bc4-b034-e0ef2bc26ffe](https://cloud.githubusercontent.com/assets/1983382/19579918/4335e572-9723-11e6-9af7-0bde54aca1d1.png)

The site is live on:
http://cubesports.de/fitness

The issue occurs in both
Swiper 3.4.0 and 3.3.1
### What you did
- I'm using responsive images (with picture and source tag + polyfill) inside each slider.
  https://github.com/scottjehl/picturefill
- Every image per breakpoint has exactly the same dimensions.
- I almost always use the `roll`-effect.
### Expected Behavior

no extra space
### Actual Behavior

Initial load shows extra space below the image on; 
reproducible 99% on just refreshing.
Windows 8.1 (IE11, Chrome)
Windows 10 (Edge, Chrome)

In Firefox (Windows again) sometimes there is no height at all; reproducible roughly 10%. Rest of the time it works as expected. Same 10% chance on OS X Chrome and Firefox, Safari seems stable.

**the issue doesn't occur on `effect: "fade"`**
**the issue doesn't occur when I use `src`-attribute in the `img` inside the `picture`**
But the polyfill-developer strongly recommends only to specify the `srcset` attribute.
I want to follow this recommendation and.. adding all the `src`-attributes will be a huge pain.

`autoHeight: true` obviously solves the issue after the first transition. But that is not acceptable for me; especially in the rare Firefox cases where you don't get access to the controls at all. And the jump for my scroll preventation is a killer aswell.

`autoHeight: false` resolves in slightly less space, but still significant.

The miscalculated height of `.swiper-container` **does not equal** the height of the tallest image in the sources / srcset! (+ Chrome has native support for the picture tag, anyhow)

Strange:
For lightbox-like modal-dialogues I need to disable the scroll. I do that by making `body { position: fixed }` – the extra space then disappears and reappears after removing `position: fixed` which results in the unwanted jump.

``` html
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <picture>
                <source srcset="...jpg 1x, ..@2x.jpg 2x" media="(min-width: 1024px)" />
                <source srcset="...jpg 1x, ..@2x.jpg 2x" media="(min-width: 800px)" />
                <img **srcset**="...jpg 1x, ..@2x.jpg 2x" alt="..." />
            </picture>
        </div>
        ... more slides
    </div>
</div>
```

``` js
$(".swiper-container").each(function() {
    $t = $(this);

    var $prev = $t.children("[class*='prev']");
    var $next = $t.children("[class*='next']");
    var $pagination = $t.find("[class*='pagination']");

    var autoplay = (typeof $t.attr("data-autoplay") == "undefined") ? false : $t.attr("data-autoplay");
    var effect = (typeof $t.attr("data-effect") == "undefined") ? "roll" : $t.attr("data-effect");

    var settings = {
        autoplay: autoplay,
        effect: effect,
        autoHeight: true,
        loop: true,
        prevButton: $prev,
        nextButton: $next,

        pagination: $pagination,
        paginationClickable: true
    };
    $t.data("swiper", new Swiper($t, settings));
})
```

**Comment by katerlouis** [comment]
Update: By roughly 10% chance the exact same issue occurs on OS X Chrome & Firefox aswell.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
