### ISSUE TITLE
Size of some divs is brutally increased

### ISSUE THREAD

**Issue by baumannzone** [nolimits4web/Swiper#1900]
This is a (multiple allowed):
- [x] bug
- Swiper Version: Swiper 3.0.7 (From the swiper.min.css file I'm loading)
- Platform/Target and Browser Versions:  
  - macOS v10.11 and Windows10
  - CHROME v53.0 (Current, but previous too, since this happens months ago) Desktop mode, 
### What you did

I have a travel website, it has at least 3 swipers in some pages where I get the problem. I use them in this areas (In the same page):
- Main Header swiper
- Hotels
- Activities 
- Bottom swiper

After use some swiper arrows or swipe contents and move around the site, I close the popup where I was using the swiper, I go back and I have some `<div>` with a height / width very very big, sometimes more than 50k px each. 🤔
I mean, this happens only if I use the swiper (arrows, swipes, etc). I got this in my 3 environments (dev, pre & pro)
### Expected Behavior

Keep all sizes of all the elements same size as always.
### Actual Behavior

As you can see in the image below, `max-height` is _1.0128e+07px_. 😱 
Sometimes instead the `max-height` it changes the `height` of some parent, so the image gets a height of 50k px or more. But the result is the same. Very very long divs with weird sizes. 
I don't know how to reproduce this error when I want, it's random after I play with the swiper.
I've been looking for a solution to this and I didn't find it.

![image](https://cloud.githubusercontent.com/assets/5422102/19581760/bae56122-972f-11e6-8e9d-ed9fa8672c65.png)
- That's the size of the image, I got the error again.
  ![image](https://cloud.githubusercontent.com/assets/5422102/19582510/56e59286-9735-11e6-84d6-9c23807fb58a.png)
- That's the image (parent) container
  ![image](https://cloud.githubusercontent.com/assets/5422102/19582520/7e6e3f9c-9735-11e6-974c-5589c35c14d5.png)
- Preview of the image (It becomes a gradient bg-color) I think it's because the screen can't handle the amount of pixels. 
  Also look the scroll bar size.
  ![image](https://cloud.githubusercontent.com/assets/5422102/19582562/d9541abc-9735-11e6-8219-43e94ca3b7f6.png)

Regards,
Jorge Baumann

**Comment by Tusko** [comment]
In latest version have the same bug

**Comment by jakedowns** [comment]
experiencing the same issue here with v3.4.0

![screencap](https://d3vv6lp55qjaqc.cloudfront.net/items/1r3E472Z001H3N2d3p0o/Image%202016-11-16%20at%203.14.12%20PM.png?X-CloudApp-Visitor-Id=88002&v=b6a27721)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
