### ISSUE TITLE
paginationBulletRender problem on version 3.4

### ISSUE THREAD

**Issue by fagianico** [nolimits4web/Swiper#1903]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4
* Platform/Target and Browser Versions: Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### What you did
Upgrading to version 3.4 the function to customize paginations bullets does not work :
```javascript
var swiper = new Swiper('.swiper-slider', {
	    nextButton: '.swiper-button-next',
	    prevButton: '.swiper-button-prev',
	    spaceBetween: 30,
	    autoplay: 8000,
        paginationType:'bullets',
	    pagination: '.swiper-pagination',
        paginationClickable: true,
      paginationBulletRender: function (index, className) {
            return '<span class="' + className + '">' + (index + 1) + '</span>';
        }
}
```
### Expected Behavior
the function should return 'swiper-pagination-bullet' as className and the index of each single slide

### Actual Behavior
[object object ] is returned as index, and a number(the index?) as className

**Comment by Tusko** [comment]
thank you!
it works ;)

But I have a problem with `active` pagination item.
Thy to drag slides here https://arsmoon.com/ (pagination `active` class works only with first and last item)

MacBook Pro
MacOS Sierra
Google Chrome
