### ISSUE TITLE
Stop autoplay while hovering

### ISSUE THREAD

**Issue by stereodenis** [nolimits4web/Swiper#191]
There is no option for that

**Comment by gandhiselvarj** [comment]
$(".swiper-container").hover(function(){
		swiper.stopAutoplay();
	}, function(){
		swiper.startAutoplay();
	});

**Comment by monty-georgiev** [comment]
What if you have more than one instance? How would you reuse the stop and play functions?
Can you get the instance and do something like:

$(".swiper-container").hover(function(){
[getTheInstance].stopAutoplay();
}, function(){
[getTheInstance].startAutoplay();
});

**Comment by ptz-nerf** [comment]
`var mySwiper = $('.swiper-container')[0].swiper;`

But during initialization your already have instance:
var mySwiper = new Swiper('#target');
$("#target").hover(function(){
     mySwiper.stopAutoplay();
}, function(){
     mySwiper.startAutoplay();
});

**Comment by monty-georgiev** [comment]
Your approach suggests that if I have 3 instances (e.g. swiper1, swiper2, swiper3) and I want to stop the autoplay on hover, then I should go:
```
$('#target1).hover(function(){swiper1.stopAutoplay}, function(){swiper1.startAutoplay});
$('#target2).hover(function(){swiper2.stopAutoplay}, function(){swiper2.startAutoplay});
$('#target3).hover(function(){swiper3.stopAutoplay}, function(){swiper3.startAutoplay});
```
However that's not really DRY is it?

Instead, the following solution, that I found, works way better:
`$(".swiper-container").hover(function(){
     this.swiper.stopAutoplay();
}, function(){
     this.swiper.startAutoplay();
});`

So this is how you get the instance.

**Comment by ptz-nerf** [comment]
1) If you have 3 instances with same configuration, it is better to write some function which creates them. 
2) I'm glad that you have found a solution. Note this.swiper and $('.swiper-container')[0].swiper are the same.

**Comment by qJake** [comment]
The code @monty-georgiev posted should be included as an option in swiper. I shouldn't have to hack the library with jQuery in order to get some desired functionality. :)

**Comment by davidwu220** [comment]
I'm getting `start/stopAutoplay() is not a function` error. Any idea?

**Comment by davidwu220** [comment]
NVM, just found the solution in the api documentation: 
```
$(".swiper-container").hover(function() {
    swiper.autoplay.stop();
}, function() {
    swiper.autoplay.start();
});
```

**Comment by killmanda** [comment]
no jQuery solution
```
var mySwiper = new Swiper ('#target')
mySwiper.el.addEventListener("mouseenter", function( event ) {   
	mySwiper.autoplay.stop();
}, false);
```
