### ISSUE TITLE
paginationClickable: true, not working when using paginationCustomRender

### ISSUE THREAD

**Issue by juanmata09** [nolimits4web/Swiper#1921]
Hi

It appears that you cannot use paginationCustomRender and still allow the dots to be clickable. 

I have paginationClickable: true and it still will not work, i've also manually added classes to match that of the standard pagination dom and it still wont work.

If i remove paginationCustomRender then the dots become clickable again?

**Comment by nolimits4web** [comment]
It can't be clickable as it is for CUSTOM pagination, i can't know what kind of custom HTML user will place there and what to add event listeners for
