### ISSUE TITLE
Swiper with Lazysizes Responsive Background Images Issue

### ISSUE THREAD

**Issue by magic-77** [nolimits4web/Swiper#1930]
Hi,
i'm using lazysizes with Swiper. I need to have Responsive Background Images. But i'm running into issues   when trying to catch the "lazyloading" state of the active Slide.

This i my Code i'm using. So maybe somebody can help me out please.
Here is also an Demo:
http://eee-ltd.com/_proto/index.html

    `<div class="header__swiper swiper-container">
        <div class="swiper-wrapper">
          <div class="swiper-slide">
            <div class="swiper__image lazyload" data-bgset=" userimages/desktop.jpg 1x, userimages/desktop@2x.jpg 2x [(min-width: 1201px)] | userimages/tablet.jpg 1x, userimages/tablet@2x.jpg 2x [(min-width: 768px)] | userimages/phone.jpg 1x, userimages/phone@2x.jpg 2x" data-sizes="auto">
              <div class="swiper__text _lazyload">Begin Your Search <span class="swiper__text--color">Today</span></div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="swiper__image lazyload" data-bgset=" userimages/desktop-1.jpg 1x, userimages/desktop-1@2x.jpg 2x [(min-width: 1201px)] | userimages/tablet-1.jpg 1x, userimages/tablet-1@2x.jpg 2x [(min-width: 768px)] | userimages/phone-1.jpg 1x, userimages/phone-1@2x.jpg 2x" data-sizes="auto">
              <div class="swiper__text _lazyload">This is a longer Demo Text <span class="swiper__text--color">with Color</span></div>
            </div>
          </div>
        </div>
        <div class="swiper-button-prev swiper-button-white"></div>
        <div class="swiper-button-next swiper-button-white"></div>
      </div>`

Lazysizes Config

    `window.lazySizesConfig = window.lazySizesConfig || {};
     window.lazySizesConfig.expFactor = 1.5;
     window.lazySizesConfig.expand = -100;
     window.lazySizesConfig.loadMode = 1;
     window.lazySizesConfig.init = false;`

The Main Javascript for Swiper

    function swiperHeader() {
    swiperHeader = new Swiper($swiperHeader, {
      effect: 'fade',
      preloadImages: false,
      lazyLoading: false,
      observer: true,
      autoplay: 8250,
      speed: 1000,
      loop: true,
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev',

      onInit: function(swiper) {
        swiper.stopAutoplay();
        // enable lazysizes
        lazySizes.init();
      },

      onSlideChangeEnd: function(swiper) {
        console.log("onSlideChangeEnd");
        var activeSlide,
          slideLazy;

        function pause() {
          activeSlide = swiper.slides.eq(swiper.activeIndex);
          slideLazy = activeSlide.find($('img'));

          console.log("hasClass -> lazyloading: ", slideLazy.hasClass('lazyloading'));

          if (slideLazy.hasClass('lazyloading')) {
            console.log('lazyloading fired');
            swiper.stopAutoplay();
          }
          window.clearTimeout(timeoutIDswiper);
        }
        timeoutIDswiper = window.setTimeout(pause, 50);
      }
    });

    document.addEventListener('load', (function() {
      var onLoad = function() {
        console.log('onLoad fired [loading finished] ', $(this));
        var activeSlide = swiperHeader.slides.eq(swiperHeader.activeIndex),
          slideLazy = activeSlide.find($('.swiper-lazy-preloader'));

        console.log('activeSlide: ', activeSlide);

        //swiperHeader.startAutoplay();
      };

      return function(e) {
        // get swiper images
        $(e.target).filter('.swiper__image img').each(onLoad);
      };
    })(), true);

**Comment by nicmare** [comment]
i also need responsive background images. the syntax of magics example looks promising but seems not to work with swiper by default :(

**Comment by piccante** [comment]
I'm also keen to see if there is a solution for a responsive set of images for the data-bg feature with lazy load. Has anyone found something that works?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
