### ISSUE TITLE
If you touch again while touching, the swipe stop.

### ISSUE THREAD

**Issue by pistis** [nolimits4web/Swiper#1936]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version
  * Swiper 3.4.0 - Released on October 16, 2016
  * Swiper 4.0.3 - latest version
* Platform/Target and Browser Versions: 
  * Android
    * Chrome and Default Browser
    * Webview
  * iPhone
    * Safari Browser
    * Webview

#### summary html(default)
```
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <img style="width:100%;height:100%;" src="...."></div>
            ... there are many slides
    </div>
    <div class="swiper-pagination"></div>
</div>
```

#### summary javascript(default)
```
var sswiper = new Swiper('.swiper-container', {
            loop : true,
            pagination : '.swiper-pagination',
            paginationClickable : true,
            autoplay : 2000,
            autoplayDisableOnInteraction : false,
            autoplayStopOnLast : false
        });
```

#### reproduce steps.
1. Touch and move with one finger.
2. Touch another finger again.
3. Release your finger.

When i touch one more by another finger while dragging slide, swipe stopped.
In additional, if i do set autoplay, autoplaying stopped as well.

#### test video is as below. you can see that.
3.4.0
as-is : https://goo.gl/qlbHcI
4.0.3
as-is : https://goo.gl/CQtBjL
to-be : https://goo.gl/Pxy6ty

### Expected Behavior
I expect swipe should not be stopped and autoplaying should work.

### Actual Behavior
Swipe will stop and autoplay will not work.

### Additional
i think, this is critical issue.

so, i have one solution.
solution is as below.

it is that add code in onTouchStart function of core.js.(onTouchStart.js)

#### AS-IS
if (!isTouchEvent && 'which' in e && e.which === 3) return;

#### TO-BE
if (!isTouchEvent && 'which' in e && e.which === 3) return;
if (isTouched && isMoved) return;

how do you think about it?

**Comment by lemontree2000** [comment]
Me too. In the sliding process, another finger's touch will stick

**Comment by sophister** [comment]
same problem
