### ISSUE TITLE
slideToClickedSlide does not work infinitly

### ISSUE THREAD

**Issue by iDVB** [nolimits4web/Swiper#1937]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v3.4.0
* Platform/Target and Browser Versions: macOS

### What you did
[CodePen](http://codepen.io/iDVB/pen/xRdNzd?editors=1111)
I have 4 actual slides...
```
      slidesPerView:'auto',
      loop: true,
      loopedSlides:3,
      centeredSlides:true,
      slideToClickedSlide: true,
```

### Expected Behavior
Navigating next, by clicking on next slide itself, continuously will cause the slides to proceed one after another similar to the next button and will continue into infinity.

### Actual Behavior
Navigating next, by clicking on next slide itself, continuously will cause the slides to proceed one after another until about 3 loops and then you hit the end of the slides.

I've reviewed the existing issues, and the forum with no success. There seems to be a great deal of confusion around **slidesPerView:auto** and **loop:true** being used together.

### Important Note
Even if I get this working, I still don't understand how I can tell the slider to go to **the closest** index:3. Meaning, don't rewind the past the clones and back to the original.... just move to the closest index, left, or right, clone or original.

**Comment by iDVB** [comment]
I believe this person is having the [same issue](http://stackoverflow.com/questions/36708027/idangero-swiper-when-keep-clicking-slides-the-white-space-shows) as well.

**Comment by koga73** [comment]
Same issue, other link is dead. Is there a solve?
