### ISSUE TITLE
Uninitialize Swiper

### ISSUE THREAD

**Issue by jgamao** [nolimits4web/Swiper#1949]
How can I uninitialize swiper on resize?

Thank you!

**Comment by nolimits4web** [comment]
Call .destroy() method

**Comment by jgamao** [comment]
It works!! Thank You @nolimits4web !

**Comment by xdemocle** [comment]
@nolimits4web why I can't call .destroy() from my Swiper instance?
Console is keep saying:
Uncaught TypeError: swiperInstance.destroy is not a function

my swiper instance as been initialized normally with
var swiperInstance = new Swiper({
option1: ..
etc: ...
})
