### ISSUE TITLE
Make long swipes smoother and more consistent

### ISSUE THREAD

**Issue by marfire** [nolimits4web/Swiper#1953]
This is a:
* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.0

I just spent some time trying to improve the smoothness of long swipes. Let me share my observations.

1. Swiper currently uses the `speed` parameter for the transition time, allowing the actual speed - that is, pixels traversed per second - to vary quite dramatically.

    For example, let's say we have a container 1000 pixels wide, a `speed` of 1000ms, and a `longSwipesRatio` of 0.1. If the user drags 100 pixels and then lets go, the remaining 900 pixels will be traversed in 1000ms (a speed of 900 pixels/s). If the user drags 900 pixels and then lets go, the remaining 100 pixels will also be traversed in 1000ms (a speed of 100 pixels/s). That's an extreme example, but I find the inconsistency in speed to be quite noticeable in real use.

    I think the best solution is to interpret the `speed` parameter as the amount of time that it should take to traverse the whole distance, and then scale the actual transition time according to the ratio already traversed. Using the example above, if the user has already dragged 500px then the transition time should be set to 1000ms * (500px / 1000px) = 500ms.

2. When doing a fast long swipe, there is a noticeable discontinuity between the speed at `touchend` and the speed at the start of the transition to the next slide. Doing this really well would probably require figuring out the velocity at `touchend` and then calculating a smooth velocity path for the transition based on the desired transition time. That sounds hard.

    One simple improvement, though, would be to use `ease-out` for the `transition-timing-function` on long swipes. Here's what happens with the default `ease`: the user does a fast long swipe; after `touchend`, the regular transition starts slowly, as defined by the `ease` curve; the transition picks up speed through the middle of the curve; finally, the transition slows down and finishes. So the overall speed goes from fast, to slow, to faster, and then slower again. With the `ease-out` curve you still have the speed discontinuity at `touchend`, but at least the speed is monotonically decreasing.

These are both things that can be accomplished outside of the core Swiper code (e.g. by changing the `speed` parameter from the `onTouchEnd()` callback), but I think the project would be improved by making these transitions smoother.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
