### ISSUE TITLE
implementing prev and next button on custom position than the usual position

### ISSUE THREAD

**Issue by Santhoshsvg** [nolimits4web/Swiper#1955]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 3.4.0
* Platform/Target and Browser Versions: web browser.

### What you did
wanted to implement vertical slider with previous and next button on top and bottom of the swiper instead of the usual middle position with arrow marks left and right.

### Expected Behavior
want the prev and next button on top and bottom of the div where the slides are placed.

### Actual Behavior
not able to find out how to implement.

**Comment by nolimits4web** [comment]
You need to overwrite the following default styles in your CSS https://github.com/nolimits4web/Swiper/blob/master/dist/css/swiper.css#L117-L132
