### ISSUE TITLE
Responsiveness does not work inside flex item

### ISSUE THREAD

**Issue by cibgraphics** [nolimits4web/Swiper#1958]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.0

### What you did
Integrated default slider inside flex item.

### Expected Behavior
Slider should be responsive and calculate correctly

### Actual Behavior
Slider is not responsive. Responsive breakpoints do not work as well

Demo:
https://jsfiddle.net/eLruf9vq/1/

**Comment by nolimits4web** [comment]
This is how CSS works, not related to Swiper, just add `.wrapper {width:100%}`
