### ISSUE TITLE
height, autoheight, etc. not working

### ISSUE THREAD

**Issue by BabyDead** [nolimits4web/Swiper#1962]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.1. 0475133
* Android - chrome, PC - chrome

### What you did
I switched from 3.3.1 to 3.4.1, for the zoom capabilities.
I expected the same results, but got different ones. The autoheight and height features do not seem to work anymore. The swiper just assumes 100% height at all times, now.
```
<div class="swiper-container swiper-container-horizontal swiper-container-autoheight">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">

    <div class="swiper-slide swiper-slide-active">
      <div class="swiper-zoom-container">
        <img src="imgsrc" srcset="imgsrc 1x, imgsrc 2x" alt="">
      </div>
    </div>

   <div class="swiper-slide swiper-slide-next">
      <div class="swiper-zoom-container">
         <img src="imgsrc" srcset="imgsrc 1x, imgsrc 2x" alt="">
      </div>
    </div>

  </div>
</div>
```
```
      prodPopupSwiper = new Swiper('.swiper-container', {
        // Optional parameters
        zoom: true,
        // loop: true,
        autoHeight: true,
        setWrapperSize:true,
        pagination: '.swiper-pagination',
        paginationClickable: true
      });
```

### Expected Behavior
The same functionality as in 3.3.1, where the swiper would grow by the image sizes

### Actual Behavior
Swiper takes 100% height in all situations

-- On a maybe helpful sidenote:
While switching back to 3.3.1, I noticed it was still broken. I had forgotten to switch back the CSS as well.
So I tested it out, and this is working perfectly fine with 3.4.1 JS but 3.3.1 CSS. So it's definitely a CSS issue.

**Comment by psiclonehi** [comment]
Not sure if anyone is still working on this slider anymore, but I'm having a similar issue.  If any one of my slides contents is significantly longer than the others, the whole slider container takes on that height.  Thus, any other slides have a ton of white space at the bottom.  It really makes the whole slider for content kind of useless from a design standpoint.

**Comment by beatelite** [comment]
Having same issue in Swiper 3.4.2

**Comment by skhtml** [comment]
same issue, 3.4.2  this is just not work properly

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
