### ISSUE TITLE
Nested vertical swiper and mousewheel

### ISSUE THREAD

**Issue by 1ucay** [nolimits4web/Swiper#1965]
Hi, I have two vertical swiper. In first slide is big logo, second is content with scrollbar. If Im on second slide with scrollbar, there is issue with mousewheel. If I scroll UP by mouse wheel, it should wait for another mouse scroll, but now its jumps on first slide too quickly. There should be some delay.
Simillar problem was in https://github.com/alvarotrigo/fullPage.js in history, but I love swiper, bcs there is multiple possibilities with one JS. 

    <div class="swiper-container swiper-v">
        <div class="swiper-wrapper">
            <div class="swiper-slide"></div>
            <div class="swiper-slide">
                <div class="swiper-container swiper-i">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <header style="height: 50px;"></header>
                            looong text
                        </div>
                    </div>
                    <div class="swiper-scrollbar"></div>
                </div>
            </div>
        </div>
    </div>

    var swiperV = new Swiper('.swiper-v', {
        direction: 'vertical',
        roundLengths: true,
        mousewheelControl: true,
        grabCursor: true,
        keyboardControl: true,
        onInit: function() {
            var swiperI = new Swiper('.swiper-i', {
                scrollbar: '.swiper-scrollbar',
                direction: 'vertical',
                slidesPerView: 'auto',
                mousewheelControl: true,
                roundLengths: true,
                grabCursor: true,
                keyboardControl: false,
                scrollbarHide: false,
                scrollbarDraggable: true
            });
        }
    });

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
