### ISSUE TITLE
i have to use "mSwiper.createLoop()" which is not on api list because loop property is not working 

### ISSUE THREAD

**Issue by macazy** [nolimits4web/Swiper#1966]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

### What you did
      const InsuranceSelect = Vue.extend({
        props:["data"],
        template: "#insuranceSelect_template",
        data:function(){
          return {
            insuranceSchemes:[]
          };
        },
        created: function(){
          this.getinsuranceSchemes();
        },
        updated: function(){
          var vm = this;
          vm.swiper.createLoop();
        },
        mounted: function() {
          var vm = this;
          vm.swiper = new Swiper(vm.$el.firstElementChild, {
            pagination: '.swiper-pagination',
            effect: 'coverflow',
            grabCursor: true,
            centeredSlides: true,
            slidesPerView: 1.5,
            observer:true,
            loop:true,
            loopAdditionalSlides:2,
            coverflow: {
              rotate: 50,
              stretch: 0,
              depth: 100,
              modifier: 1,
              slideShadows: true
            }
          });
        },
        methods:{
          getinsuranceSchemes:function(){
            var vm = this;
            $.ajax({
              url: "insuranceSchemes.json",
              type: "get",
              contentType: "application/json",
              beforeSend: function() {
                $.showLoading();
              },
              success: function(data) {
                if (data.statusCode != 200) {
                  $.alert(data.errorText, "错误");
                } else {
                  insuranceSchemes = data.data;
                  for (var i in insuranceSchemes) {
                    var insuranceScheme = insuranceSchemes[i];
                    insuranceScheme.compulsoryInsurance = true;
                    vm.insuranceSchemes.push(insuranceScheme);
                  }
                }
              },
              complete: function() {
                $.hideLoading();
              }
            });
          }
        }
      });

### Expected Behavior
1.dynamic addtion sliders 
2.loop behavior
3.coverflow effect 

### Actual Behavior

# http://test.www.ins-box.com/boxmvi_vue/#/insuranceSelect

## this is the demo page

u can use app.$children[0].getinsuranceSchemes() to emulate dynamic addtion sliders 
and override updated function  to disable vm.swiper.createLoop()

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
