### ISSUE TITLE
slidesPerGroup skipping to end after first slide.

### ISSUE THREAD

**Issue by benbrehaut** [nolimits4web/Swiper#1969]
This is a:
* [x] bug

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Chrome (latest), Safari (latest) and Firefox (latest) on MacOS (10.12)

### What you did
Code Example: http://codepen.io/benb/pen/gLyVEe

Have defined to show three ``slidesPerGroup`` and three ``slidesPerView``, so that each slide has three slides out of a group of 12 and that toggling the button or swiping through will move to the next group of three slides.

### Expected Behaviour
To slide through the Slider, with three slides at a time until reaching the end of the slider.

### Actual Behaviour
After the first slide showing slide one, two and three, it skips to the end of the slider showing slide 10, 11 and 12. This happens when clicking on the arrow or by swiping through with mouse / touch. 

Once I turn off ``slidesPerGroup`` it does not skip any slides.

I have not been able to find this in issues and I can't see that I am doing anything wrong, so I apologise in advanced if I missed something.

**Comment by motou** [comment]
In your code example, the wrong swiper.js version is used:

`https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.2.6/js/swiper.jquery.min.js`

If you change that to 3.4.1, it should work. See my example: https://codepen.io/motou/pen/LxbjyM

Besides, your initial parameters "slidesPerView" and "slidesPerGroup" should be defined as integer, like:

`slidesPerView: 3,
 slidesPerGroup: 3,`
