### ISSUE TITLE
Can't use Swiper options because ionic.bundle.js value isn't updated

### ISSUE THREAD

**Issue by 1BJK903** [nolimits4web/Swiper#1970]
Hi all,

I have a rather odd issue. I am using Swiper and I can't get the options of the Swiper slider to work. So what I did was, checking out **_ionic.bundle.js_**. I noticed it's using Swiper 3.2.7...

So, what I also noticed in ionic.bundle.js, is this:

```
        var defaults = {
            // autoplay
            autoplay: false,
```

But: Swiper documentation says it's not a boolean, but a number (you can see that [here](http://idangero.us/swiper/api/). So in my options, in my app.js, I have:

```
  $scope.options = {
    autoplay: 2500,
    loop: false,
    speed: 1000,
    slidesPerView: 1,
    centeredSlides: true
  }
```

But this doesn't work! Instead, it uses the "false" from ionic-bundle.js. So I can't seem to override it.

My question: how is this even possible and how do I change this? When I change the value "false" in ionic.bundle.js to "2500" for example, the autoplay suddenly works! 

**So now I know the issue is right there, but how do I fix it?** I don't want to _hardcode_ it, but instead, override the value or at least change ionic.bundle.js to use Swiper 3.4.1, which is the latest version.

Can someone help me please?

PS: this is the reason for this bug, I assume: https://github.com/driftyco/ionic/issues/9783

**Comment by nolimits4web** [comment]
This is probably has to be done/fixed by Ionic authors
