### ISSUE TITLE
Remove jQuery as a dependency when importing Swiper module.

### ISSUE THREAD

**Issue by notbogdan** [nolimits4web/Swiper#1975]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: NPM 

### What you did
Installed Swiper and tried to import it as so: 

`import Swiper from 'swiper';`

Compiled using Webpack. Webpack throws error: 
`Module not found: Error: Cannot resolve module 'jquery' in ......./node_modules/swiper/dist/js`

### Expected Behavior
Should be able to use the Swiper library without jQuery.

### Actual Behavior
Throws an error.

**Comment by ThomasRalee** [comment]
@notbogdan why did u close this? Did you manage to solve it?

**Comment by notbogdan** [comment]
@ThomasRalee this was a while back but I think it was a problem with my configuration. Make sure you don't have jQuery installed somewhere by accident, I think my webpack config was importing jQuery in some obscure corner of the codebase at the time

**Comment by ThomasRalee** [comment]
weird, am sure that i dont have jQuery installed. But thanks for sharing, i will look into it =)
