### ISSUE TITLE
Gallery not working when container div is hidden (display:none)

### ISSUE THREAD

**Issue by wwwwwwoorks** [nolimits4web/Swiper#1981]
I want the swiper gallery to show after clicking on a "Show the gallery" link.
But it looks like Swiper is not working properly if initialized inside an hidden div.

Here is my page:

```
<div>
<a href=“javascript:;” onclick=“toggle_visibility('gallery');”><img src=“img.jpg” alt=“Click to open the gallery”></a>
</div>

<div id=“gallery” style:“display:none”>
<!— Swiper —>
<div id=“slide-event” class=“swiper-container swiper-container-event”>
<div class=“swiper-wrapper”>
…
</div>
<!— Add Arrows —>
<div id=“show-hide” class=“swiper-button-next”></div>
<div id=“show-hide” class=“swiper-button-prev”></div>
</div>
<!— End Swiper —>
</div>

<script src="js/swiper.jquery.js"></script>
```

Maybe there is a javascript trick?
I read about a setTimeout function that could fix this issue.
Any suggestion?

**Comment by wwwwwwoorks** [comment]
It is far easier than this.
Just add:
```
observer: true,
observeParents: true,
```
To the swiper initialization.

**Comment by MaxInMoon** [comment]
@wwwwwwoorks, thanks it works 👍

**Comment by VBagmut** [comment]
@wwwwwwoorks thank you! It helps me ;)

**Comment by CressZZ** [comment]
@wwwwwwoorks You are Great man for me!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sabatiny** [comment]
@wwwwwwoorks thank you !!!

**Comment by kai-ziefle** [comment]
@wwwwwwoorks Great, worked for me, too. Thank you!

**Comment by bloodstorms** [comment]
@wwwwwwoorks Thanks a lot!! You saved my day 😍

**Comment by evenloooo** [comment]
@wwwwwwoorks You are my hero!

**Comment by shahjehanali1** [comment]
@wwwwwwoorks You saved my day thanks 👍

**Comment by abaumer** [comment]
Yeah!

**Comment by bear30921** [comment]
thank you . 👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by louishwy** [comment]
@wwwwwwoorks You saved me!

**Comment by annewanghy** [comment]
Thank you. You save my day!

**Comment by kfirba** [comment]
@wwwwwwoorks Not all heroes wear capes.

**Comment by goyadidi** [comment]
thank you x1000000

**Comment by m1roku** [comment]
oh thanks, spent half hour to figure out why my swiper doesn't work in popup lol

**Comment by Boggy992** [comment]
Thank you my man !

**Comment by MarcoCpDigital** [comment]
thank!! you saved my time!

**Comment by natejsimonsen** [comment]
Wow, thank you so much that was a frustrating bug!

**Comment by echohuiecho** [comment]
Thank you! You save my project!

**Comment by echohuiecho** [comment]
Thank you! You saved my life!

**Comment by Belouccio** [comment]
thank you!

**Comment by ceciiiron** [comment]
Worked on my react proj. Order of elements is important. `hidden` class should be added first
```js
<div className={classNames([
		isStartSlide && "hidden",
		"swiper-prev absolute h-full z-10 -left-5 flex flex-col justify-center items-center"
	])}> <div>PREV</div>
</div>
```

Thank you!
