### ISSUE TITLE
Positive oversliding on single slide swiper using infinite loop won't display the next image after reaching the final slide until an action triggers it

### ISSUE THREAD

**Issue by cliffordgurney** [nolimits4web/Swiper#1985]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: CHROME / Evergreen browsers.

### What you did
CodePen Example: http://codepen.io/cliffgurney/pen/yggvVK

Really simple single image slider which has overflow visible on the container `.gallery-content` so you can see the previous and next image in the "wings"

```bash
var gallerySwiper = new Swiper('.gallery-content', {
    // Optional parameters
    direction: 'horizontal',
    slidesPerView: 1,
    loop: true,
    autoplay: 4000,
    autoHeight: true,
    loopAdditionalSlides: 100,
    // Navigation arrows
    nextButton: '.gallery-content .swiper-button-next',
    prevButton: '.gallery-content .swiper-button-prev',

    pagination: '.swiper-pagination',
    paginationType: 'progress'
});
```

When you reach the last image in the slider, you can see the previous image in the overflow, but the next image doesn't appear (see. positive oversliding function) until you re-trigger the slider through swiping, clicking etc.

### Expected Behavior
"Next" image on the right hand side to be in view like it is before it reaches the end of the loop of duplicates, this ruins the "seamless infinite loop" look and feel.

### Actual Behavior
"Next" image after looping once is not in view on the right until you begin to swipe again. 

### Hack Fix
I've identified the issue where positive oversliding triggers 1 slide too late. I've hacked a fix by adding another conditional to the `s.fixloop` funtion in the `core.js`, labelled as `(s.params.slidesPerView === 1 && s.activeIndex > (s.slides.length - s.params.slidesPerView * 2) - 1)`

There might be a better way to target this condition, however for my project this seems to do the trick.

```
       s.fixLoop = function () {
            var newIndex;
            //Fix For Negative Oversliding
            if (s.activeIndex < s.loopedSlides) {
                newIndex = s.slides.length - s.loopedSlides * 3 + s.activeIndex;
                newIndex = newIndex + s.loopedSlides;
                s.slideTo(newIndex, 0, false, true);
            }
            //Fix For Positive Oversliding
            else if (
                  (s.params.slidesPerView === 'auto' && s.activeIndex >= s.loopedSlides * 2)
                  ||
                  (s.activeIndex > s.slides.length - s.params.slidesPerView * 2)
                  ||
                  (s.params.slidesPerView === 1 && s.activeIndex > (s.slides.length - s.params.slidesPerView * 2) - 1)
            ) {
                newIndex = -s.slides.length + s.activeIndex + s.loopedSlides;
                newIndex = newIndex + s.loopedSlides;
                s.slideTo(newIndex, 0, false, true);
            }
        };
```

Let me know if this is helps in other peoples projects where you might want to preview the prev/next image in a single carousel, instead of hiding the overflow.

EDIT: new conditional statement targets more specifically to the single up slider `(s.params.slidesPerView === 1 && s.activeIndex > (s.slides.length - s.params.slidesPerView * 2) - 1)`, the old condition caused issues with 2-3 'slides in view' carousels  `(s.activeIndex > s.slides.length - s.params.slidesPerView * 3)`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by 4t4r1** [comment]
@cliffordgurney Found a somewhat more elegant solution that doesn't hack the core.

`
var $swiper = $.find('.swiper-container').first();
var $slides = $swiper.find('.swiper-slide');
var $first = $slides.eq(0);
new Swiper($swiper, {
    loop: true,
    loopAdditionalSlides: 2,
    onSlideChangeEnd: function (swiper) {
        var newIndex = -swiper.slides.length + swiper.activeIndex + swiper.loopedSlides;
        if ((newIndex === 0)) {
            $first.addClass('no-transition');
            swiper.slideTo(newIndex + swiper.loopedSlides, 0, false, true);
            setTimeout(function () {
                $slides.eq(0).removeClass('no-transition');
            }, 50);
        }
    }
});
`

Trick is to add addition slides using the `loopAdditionalSlides` param & them reset the slide to the first one when it reaches the first clone.

I had to add the `no-transition` class or I got double-firing animations in my case, this won't always be necessary. Hope this helps.

@nolimits4web Sorry for bumping dead threads :P  but maybe this helps someone else, as `overflow: visible` Swipers are quite common in my experience 👍

**Comment by clifford-lc** [comment]
@4t4r1 Great find, these customizations are definitely better in the swiper options than in the hacked into the core.

Adding this extra functionality that you added to the event `onSlideChangeEnd` might be nicer if it were in the core library, perhaps attached to the prop `loopAdditionalSlides`?
