### ISSUE TITLE
onSlideChangeEnd() is not fired when swiping the full width

### ISSUE THREAD

**Issue by marfire** [nolimits4web/Swiper#1988]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Android Chrome 52, Mobile Safari 10

### What you did
Manually swiped a slide all the way from one side to the other.

### Expected Behavior
`onSlideChangeEnd()` should be fired.

### Actual Behavior
`onSlideChangeEnd()` is not fired.

This was previously filed as #1198. However that issue ended up being combined with another one, which was fixed, and the issue was closed. The original problem remains, however. There is a video in the other issue giving an example. (One difference is that I'm seeing `onSlideChangeStart()` fired every time.)

In that issue it was said that: "it is 99% impossible in real world". I would counter that having your app fail 1 out of 100 times is actually not good. And I'm seeing this at higher rates in regular real world usage. Some things seem to make this more likely, like having full-width slides, and swiping to the last slide (so it sticks at the edge and you can't go past the end point).

I can actually reproduce this 100% of the time on mobile by swiping part of the way, putting another finger down to pause the swipe (not sure if this is a bug or a feature?), and then resuming the swipe further back so that I always reach the end point while my finger is still down.

Regardless of the frequency, I hope that it is accepted that `onSlideChangeEnd()` should always be fired, regardless of which pixel you happen to be on when you lift your finger. Thank you for your attention.

**Comment by mnewmedia** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
