### ISSUE TITLE
Swiper slider pagination works incorrect with dynamic content

### ISSUE THREAD

**Issue by Helge85** [nolimits4web/Swiper#1989]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Hi, first of all i have to admit that swiper is my favourite slider tool - well done 👍 

I have a problem with the pagination fraction. I have a Kirby CMS page and i have a container with a simple foreach loop like

```
	<?php foreach($page->children()->visible() as $project): ?>
			<div class="project--container padding-bottom--2rem padding-top--2rem border--bottom padding-left-right--15px">
				<h3 class="text-align--center padding-bottom--1rem"><?php echo $project->title()->html() ?></h3>


				<div class="swiper-container swiper-container--mobile">
					<!-- Additional required wrapper -->
					<div class="swiper-wrapper">    
						<!-- Slides -->
						<?php foreach($project->images()->sortBy('name', 'asc', SORT_NATURAL) as $image): ?>
							<figure class="swiper-slide">
								<img src="<?php echo $image->url() ?>" alt="<?php echo $page->title()->html() ?>">
							</figure>
						<?php endforeach ?>
					</div>
					
<div class="swiper-pagination"></div>

		<?php endforeach ?>
```

**After Load**
Swiper counts the number of the first project for all. 
Which means on load I get f.e.'1/28' for each project container

**First swipe**
If I start to swipe swiper updates the current slide correctly for the current sliding project. With the right total image number

**The other projects after first swipe** 
They are updated again with the value from the project i used to swipe first. If i swipe on a current project all the others are updated with the current value.

I'd like to have a solution that the value for the fraction pagination for each project is counted correctly. Thanks for your answer in advance

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
