### ISSUE TITLE
Swiper multirow order of slides

### ISSUE THREAD

**Issue by kanon488** [nolimits4web/swiper#1995]
I want to put 3 slidesPerView and 3 slidesPerColumn in this order:
first Slide             second slide
1|2|3                  10|11|12
4|5|6  -------->  13|14|15
7|8|9

but only can organize like this:
perColumn:
1|4|7               10|13||16
2|5|8   ------->11|14|17
3|6|9                12|15|
perRow:
1|2|3        4|5|6
7|8|9---->10|11|12

how i can fix this?

**Comment by bhaniel** [comment]
I sent a pull request that solve this issue.
#2008

**Comment by billmn** [comment]
Having the same problem using the latest version (4.0.5).
Does exists a fix?
