### ISSUE TITLE
Zoom on iPad stops working on appended slides

### ISSUE THREAD

**Issue by RidleyDeckard** [nolimits4web/Swiper#2006]
This is a (multiple allowed):
* [x] bug

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.
I have a slide presentation which allows users to zoom in, on an iPad they can pinch-out to zoom in. I've got additional slides that I manually add in at the end of the presentation

<div class="swiper-container">
<div class="swiper-wrapper">
<div class="swiper-slide"><div class="swiper-zoom-container"><img src="Slide1.jpg"></div></div>
<div class="swiper-slide"><div class="swiper-zoom-container"><img src="Slide2.jpg"></div></div>
<div class="swiper-slide"><div class="swiper-zoom-container"><img src="Slide3.jpg"></div></div>
</div>
</div>
<script>
var appendNumber = 3;
    var swiper = new Swiper('.swiper-container', {
        slidesPerView: 1,
        centeredSlides: true,
		zoom: true
    });

    $('.addslide').on('click', function (e) {
        e.preventDefault();
	swiper.appendSlide('<div class="swiper-slide"><div class="swiper-zoom-container"><img src="Slide' + (++appendNumber) + '.jpg"></div></div>');
    });
</script>
### Expected Behavior
When the user gets to the new, added slides they should still be able to pinch-out to zoom into the image

### Actual Behavior
Pinching-out does nothing, double clicking does zoom in, but the users can't scroll around the image, it just scrolls the image as through it was the normal size. 

Any help would be greatly appreciated.

**Comment by RidleyDeckard** [comment]
Quick update, I managed to fix it by calling 

swiper.zoom.init();

on the line after the appendSlide action. As it seems the problem was the zoom touch gestures weren't being added to the new div. This fixes it and it seems to work perfectly.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
