### ISSUE TITLE
Flexbox stretch properties stop working when swiper applied

### ISSUE THREAD

**Issue by voodoo6** [nolimits4web/Swiper#2011]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Tested on macOS 10.12.3, iOS 9/10, Safari 10.0.3, Chrome 56

### What you did
I used flexbox to create a equal-height grid of 'cards'.
I added swiper as instructed in the docs.

### Expected Behaviour
When swiper is applied the flex layout should stay the same.

### Actual Behaviour
The cards no longer 'stretch' to be equal heights.

See here for reduced test case.. [http://thehooknew.webflow.io/swiper-test](http://thehooknew.webflow.io/swiper-test)
The grid of cards at the top has `display: flex` applied to the container `.flex-parent` and the cards behave as expected, stretching to have equal heights. The grid below is the same but with swiper classes, styles and scripts applied – notice how the cards are no longer equal height (the first grid is the same as the second but with swiper classes removed from the elements).

I can find one person with the same problem in the forum but no solution.

(Many thanks for the script and any help).

**Comment by nolimits4web** [comment]
This question is about CSS and how flexbox works overall. Just add this to CSS:
```
.swiper-slide {
  height: auto;
}

**Comment by voodoo6** [comment]
So simple in the end, thanks!
