### ISSUE TITLE
Import swiper inside typescript/angular 2 class

### ISSUE THREAD

**Issue by bm-software** [nolimits4web/Swiper#2016]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1.
* Platform/Target and Browser Versions: None.

### What you did
I'm simply trying to use swiper (and @types/swiper) within my angular 2 application from visual studio 2015. I've installed everything both swiper and its typings.

### Expected Behavior
I would be able to import the Swiper class in my component.

### Actual Behavior
When I try to import the Swiper or SwiperOptions class (for initialization) visual studio can't find the module "swiper".
I've tried with the following import statements:

`import { Swiper } from "swiper";`

and

`import swiper = require("swiper");`

What am I missing?

**Comment by bm-software** [comment]
I've tried for hours with no success. I've made a last try, rebooting my system and now it works. Sorry for the useless issue.

**Comment by mbn18** [comment]
@bm-software , Can you please share the code that load the swiper lib?
And also, how did you managed to overcome the server side execution (universal/platform server)?
