### ISSUE TITLE
Pagination Transition Breaking onSwipe when images loaded via Ajax Dynamically

### ISSUE THREAD

**Issue by jaylane** [nolimits4web/Swiper#2026]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: All Browsers 

### What you did
Images on our ecommerce site are loaded via ajax request on page load initially then when a color change is initiated the DOM is updated with the images for the different color of the product. Swiper works fine until you try to select another color, at this point the pagination bullets no longer progress when you specially use swiping for navigation. If you use next/prev buttons or pagination bullets the active bullet updates.

Here is my initialization set up along with an jquery .change() function I thought might fix the issue but it hasn't:

```
var countSlides = $("#swiper-wrapper img").length;
            var viewPort = $(window).width();
            var swiper = new Swiper('.swiper-container', {
                pagination: '.swiper-pagination',
                paginationClickable: true,
                nextButton: '.next',
                prevButton: '.prev',
                loop: true,
                onInit: function(){
                    if(countSlides === 1){
                        $('.swipearrowwrapper').hide();
                    }
                    if(viewPort < 768){
                        $('#swiper-wrapper a').click(function( event ) {
                            event.preventDefault();
                        });
                    }
                }
            });
            $('#swiper-wrapper img').change(function(){

                        swiper.update();

                }
            );
```
here is an example on our site: [RugsUSA.com](http://www.rugsusa.com/rugsusa/rugs/rugs-usa-moroccan-trellis/Navy-Blue/200MTVS27D-860116.html)

Swipe the first image of the rug that appears on page load (blue rug) then choose another color and swipe.

### Expected Behavior
After color change pagination bullets should still update the active class on swipe gesture

### Actual Behavior
active pagination bullet does not change from the 1st bullet

Thanks

**Comment by nolimits4web** [comment]
Is it still actual, from what i see it is working site on your website, after i change color, i see images are replaced and pagination works as expected

**Comment by jaylane** [comment]
It's working now I wound up just using the destroy method and then
recreating the Swiper object on image update instead of just trying to
reinitialize the already created object.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
