### ISSUE TITLE
Active image not getting 100% opacity

### ISSUE THREAD

**Issue by JacobDB** [nolimits4web/Swiper#2028]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v3.4.1
* Platform/Target and Browser Versions: macOS 10.12.2, Chrome 56.0.2924.87 (64-bit), Firefox 53.0a2 (2017-02-27) (64-bit), Safari 10.0.2 (12602.3.12.0.1), Opera 43.0.2442.806

### What you did
Simply inited Swiper as usual. Included vendor CSS & JS, added a few minor custom styles, and inited the script with the following parameters:

```
var swiper = new Swiper (".swiper-container", {
    autoplay: 3000,
    effect: "fade",
    fade: { crossFade: false },
    speed: 500,
    loop: true,
});
```

### Expected Behavior
Each slide transitions to 100% opacity as it becomes active.

### Actual Behavior
Each slide seems to be progressively transitioning to less and less opacity as it becomes active. 

![image](https://cloud.githubusercontent.com/assets/1123997/23380856/02667148-fd02-11e6-9fdc-bb5492429a1c.png)

This is visible here: http://www.bearrivercasino.com/

I'll continue trying to debug it, will report back if I figure out why this is happening.

**Comment by JacobDB** [comment]
I've tried setting `crossFade` to both `true` and `false`, doesn't seem to make a difference.

**Comment by JacobDB** [comment]
Wow, figured it out actually. Turns it out having `padding: 0 20px;` on `.swiper-slide` was causing the issue. No idea why.

**Comment by JacobDB** [comment]
@nolimits4web since that seems like a legitimate bug, do you have any plans to look in to correcting it?

**Comment by gekkoukisi** [comment]
I think `fade: { crossFade: false }` is not correct.
it should be `fadeEffect: { crossFade: false }` .
