### ISSUE TITLE
Slide disappear when using loop and centeredSlides

### ISSUE THREAD

**Issue by silverprize** [nolimits4web/Swiper#2030]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: macOS/CHROME

### What you did
I read the https://github.com/nolimits4web/Swiper/issues/792 and I have tried to increase loopedSlides/loopAdditionalSlides parameters. But Still I get same issue when I swipe.

### Expected Behavior
click prev button 3 times.
3,1,2 -> 2,3,1 -> 1,2,3 -> 3,1,2

### Actual Behavior
reproduce link : https://jsfiddle.net/4verbkex/2/
click prev button 3 times.
3,1,2 -> 2,3,1 -> 1,2,3 -> (blank),1,2

**Comment by WwupengP** [comment]
set the loopAdditionalSlides value larger then zero may works

**Comment by silverprize** [comment]
It is still being reproduced.
https://jsfiddle.net/rssv555m/1/

**Comment by Triloworld** [comment]
I confirm. Actually you can see in source:

Before clicks: 

`<div class="swiper-wrapper" style="width: 1800px; transform: translate3d(-400px, 0px, 0px); transition-duration: 0ms;"><div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-active" data-swiper-slide-index="0" style="width: 200px;">Slide 1</div><div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-next" data-swiper-slide-index="1" style="width: 200px;">Slide 2</div><div class="swiper-slide swiper-slide-duplicate swiper-slide-prev" data-swiper-slide-index="2" style="width: 200px;">Slide 3</div>
        
        <div class="swiper-slide swiper-slide-active" data-swiper-slide-index="0" style="width: 200px;">Slide 1</div>
        <div class="swiper-slide swiper-slide-next" data-swiper-slide-index="1" style="width: 200px;">Slide 2</div>
        <div class="swiper-slide swiper-slide-duplicate-prev" data-swiper-slide-index="2" style="width: 200px;">Slide 3</div>
    <div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-active" data-swiper-slide-index="0" style="width: 200px;">Slide 1</div><div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-next" data-swiper-slide-index="1" style="width: 200px;">Slide 2</div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="2" style="width: 200px;">Slide 3</div></div>`

After clicks (see duplicate class):

`<div class="swiper-wrapper" style="width: 1800px; transform: translate3d(200px, 0px, 0px); transition-duration: 0ms;"><div class="swiper-slide swiper-slide-duplicate swiper-slide-active" data-swiper-slide-index="0" style="width: 200px;">Slide 1</div><div class="swiper-slide swiper-slide-duplicate swiper-slide-next" data-swiper-slide-index="1" style="width: 200px;">Slide 2</div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="2" style="width: 200px;">Slide 3</div>
        
        <div class="swiper-slide swiper-slide-duplicate-active" data-swiper-slide-index="0" style="width: 200px;">Slide 1</div>
        <div class="swiper-slide swiper-slide-duplicate-next" data-swiper-slide-index="1" style="width: 200px;">Slide 2</div>
        <div class="swiper-slide swiper-slide-duplicate-prev" data-swiper-slide-index="2" style="width: 200px;">Slide 3</div>
    <div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="0" style="width: 200px;">Slide 1</div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="1" style="width: 200px;">Slide 2</div><div class="swiper-slide swiper-slide-duplicate swiper-slide-prev" data-swiper-slide-index="2" style="width: 200px;">Slide 3</div></div>`

**Comment by Triloworld** [comment]
Find one more example in production: https://github.com/nolimits4web/Swiper/issues/370#issuecomment-264108419

Same behavior like this one.

**Comment by kpoconnor** [comment]
+1  This seems to have been an issue for a long time and also affects all frameworks that use Swiper, like [Ionic](https://github.com/driftyco/ionic).

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
