### ISSUE TITLE
Can't get parallax to work for both elements inside one slide

### ISSUE THREAD

**Issue by Madebym** [nolimits4web/Swiper#2034]
Maybe the title is unclear, but here is an explanation. 

I have two swiper slides, inside each of them are two images, one on the left and one on the right. Orientation is vertical.

I want to have parallax effect on both images inside one slide. But it only works for one image.

I guess it is not due to wrongly positioning elements, because if I remove parallax option, the images are displayed as they should.

Here is the link if anyone is interested:

Edit: Just needed to put overflow hidden on each slide.

**Comment by shimbala** [comment]
Oincubhvgvdgdfh,fuhudziouisslbvgvvh
