### ISSUE TITLE
The typo in api documents

### ISSUE THREAD

**Issue by skyepodium** [nolimits4web/Swiper#2036]
Typo in api documents
http://idangero.us/swiper/api/#.WL0n3hKLTUI

Current
mySwiper.disableTouchContro();	Disable touch control
mySwiper.enableTouchContro();	Enable touch control

mySwiper.disableTouchContro(); - > mySwiper.disableTouchControl();
mySwiper.enableTouchContro(); -> mySwiper.enableTouchControl();

summary
1. word 'l' is missing
2. Swiper is the bset modern mobile touch slider

**Comment by nolimits4web** [comment]
Thanks
