### ISSUE TITLE
Cannot read property 'params' of null

### ISSUE THREAD

**Issue by maxkuzmin** [nolimits4web/Swiper#2038]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Windows, CHROME.

### What you did
destroy lazy loading swiper instance before lazy loading is completed, https://jsfiddle.net/j9k0xtqo/42/

### Expected Behavior
No errors

### Actual Behavior
Multiple errors in console that can not be supressed by try catch.

> Uncaught TypeError: Cannot read property 'params' of null

**Comment by maxkuzmin** [comment]
Ok, `swiper.destroy(false);` helps https://jsfiddle.net/j9k0xtqo/43/

**Comment by maxkuzmin** [comment]
However, it seems like it is workaround rather than solution. In my particular case I need to destroy swiper completely since user is navigated to another spa page, but I have to keep swiper instance to prevent errors in console.

**Comment by nolimits4web** [comment]
It is fixed here https://github.com/nolimits4web/Swiper/commit/941c040d80da1cad5927c02d4f7baf363cd4ae6f
