### ISSUE TITLE
Conflict with other jQuery plugin due to .transition

### ISSUE THREAD

**Issue by drosendo** [nolimits4web/Swiper#2040]
Hi,

Swiper conflict with plugin: http://ricostacruz.com/jquery.transit

Due to "transition()", I renamed all instances to prevent conflict and is working.

Any suggestions?
Thanks,
David

**Comment by FCHAPLIN** [comment]
Same issue here.

**Comment by drosendo** [comment]
Closed due to no proper feedback form authors.
