### ISSUE TITLE
duplicates/clones should includes attributes like style

### ISSUE THREAD

**Issue by aufdenpunkt** [nolimits4web/Swiper#2045]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: all

### What you did
-

### Expected Behavior
duplicates/clones should also include attributes like "style"

### Actual Behavior
duplicates/clones doesn't include attributes like "style"

**Comment by nolimits4web** [comment]
Duplicated slides are done via DOM cloning so the include everything. Make sure you add your custom styles BEFORE you init swiper with loop
