### ISSUE TITLE
Swipe not shows extra slides

### ISSUE THREAD

**Issue by nam-co** [nolimits4web/Swiper#2049]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.1.
* Platform/Target and Browser Versions: SAFARI AND CHROME, ETC.

Hi, hope somebody can help me, I got 8 slides , the swipe shows the first 4, but the next group (slides 5 to 8) month show, their invisible, the pagination shows the 2 dots for the 2 groups but their not appearing, can somebody please help me

<d-iv class="swiper-container">
<div class="swiper-wrapper">

		<div class="swiper-slide" style="height: 300px;">Slide 1</div>
	        <div class="swiper-slide" style="height: 300px;">Slide 2</div>
	        <div class="swiper-slide" style="height: 300px;">Slide 3</div>
	        <div class="swiper-slide" style="height: 300px;">Slide 4</div>
		<div class="swiper-slide" style="height: 300px;">Slide 5</div>
	        <div class="swiper-slide" style="height: 300px;">Slide 6</div>
	        <div class="swiper-slide" style="height: 300px;">Slide 7</div>
	        <div class="swiper-slide" style="height: 300px;">Slide 8</div>
            
</div>

<div class="swiper-pagination" style="margin-top: 20px;"></div>
</div>

    <script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
		paginationClickable: true,
        slidesPerView: 4,
        slidesPerGroup: 4,
		responsive: true,
        spaceBetween: 0
    });
    </script>

![swipe1](https://cloud.githubusercontent.com/assets/3951529/24006568/38f45456-0a3a-11e7-9b13-557c9979a3cf.jpg)

![swipe2](https://cloud.githubusercontent.com/assets/3951529/24006582/3dd5b7a8-0a3a-11e7-9874-8930d1bbb39b.jpg)

**Comment by suture** [comment]
Did you find a solution?
