### ISSUE TITLE
callback onReachBeginning while dragging to beginning freezes page (chrome)

### ISSUE THREAD

**Issue by jessycormier** [nolimits4web/Swiper#2056]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows 10, Chrome 56.0.2924.87 (64-bit)
### What you did
The HTML ( _dots "..." represent other contnet above/below code sample_ )
```html

...

<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        <div class="swiper-slide">Slide 4</div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>

...

```

The script included just before the `</body>` tag.
```javascript
var appendNumber = 4;
var prependNumber = 1;
var swiper = new Swiper('.swiper-container', {
    initialSlide: 1,
    pagination: '.swiper-pagination',
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    effect: 'coverflow',
    coverflow: {
        rotate: 50,
        stretch: 0,
        depth: 140,
        modifier: 1,
        slideShadows : false
    },
    roundLengths : true,
    slidesPerView: 3,
    centeredSlides: true,
    paginationClickable: true,
    grabCursor: true,
    keyboardControl:true,
    mousewheelControl:true,
    spaceBetween: 8,
    onReachBeginning: function(swiper) {
        swiper.prependSlide([
            '<div class="swiper-slide">Slide ' + (--prependNumber) + '</div>',
            '<div class="swiper-slide">Slide ' + (--prependNumber) + '</div>'
        ]);
    },
    onReachEnd: function(swiper) { 
        swiper.appendSlide([
            '<div class="swiper-slide">Slide ' + (++appendNumber) + '</div>',
            '<div class="swiper-slide">Slide ' + (++appendNumber) + '</div>'
        ]);
    }
});
```

### Expected Behavior
You'll see my use of two callback functions `onReachBeginning` and `onReachEnd` which I'm attempting to use to prepend and append slides when these are called. 

I expected slides to be added to either end when the ends where "viewed".

### Actual Behavior
You'll see my use of two callback functions `onReachBeginning` and `onReachEnd` which I'm attempting to use to prepend and append slides when these are called.

The interaction works great with keyboard arrow keys, it works great when using triggers (arrow buttons and the user clicks them).

It stops working is if the user uses the drag feature. Dragging to the end works (right side), but dragging to the start will completely freeze the chrome tab. (I have to kill the tab via chromes Task manager)

---

I hope this helps, any further questions let me know!

Thanks!

**Comment by nolimits4web** [comment]
I believe it may happen because you got infinite loop here. Try to prepend slides within `0` timeout
