### ISSUE TITLE
Use autoprefixer

### ISSUE THREAD

**Issue by shrpne** [nolimits4web/Swiper#2059]
This is a:
* [x] enhancement
* [x] feature-discussion (RFC)

I suggest to use [autoprefixer](https://github.com/postcss/autoprefixer) in build procces and remove prefixes from sources.
It will make sources cleaner, remove unsupported prefixes from dist and only apply prefixes for browsers from current project's [browserlist](https://github.com/ai/browserslist)

**Comment by nolimits4web** [comment]
Already in use in v4
