### ISSUE TITLE
[question] customizing transition effects?

### ISSUE THREAD

**Issue by tconroy** [nolimits4web/Swiper#2060]
Swipers comes with a handful of pre-defined effects to change the transition between slides.

However, I would love if you could expose an interface for customizing / controlling the transition effects. 

Is there any way to do this currently? Looking through the docs, I don't see anything.

**Comment by followthemadhat** [comment]
agreed. is there any way to customize the transition for the different elements within the slide (e.g. header text, image etc.) and not the slide itself? for example, on slide change, the text would slide-out first, then (with a little delay) the image, and then the next slide would appear. any workarounds?

**Comment by tconroy** [comment]
@followthemadhat I like that idea, although I feel like if we could pass some sort of information to the slides of what the swipe "progress" is ( say 0 is center/stationary, -1 is all-the-way left and 1 is all-the-way-right), you could use those values inside your slide to animate the inner content how you see fit.

**Comment by nolimits4web** [comment]
In v4 it can be used within `setTranslate` event:
```js
swiper.on('setTranslate', function onTranslate() {
  var swiper = this;
  var progress = swiper.progress; // main swiper progress (from 0 to 1);

  swiper.slides.each((slideIndex, slideEl) => {
    /* Slide Progress
    0 - active
    1 - one slide after active slide offset
    2 - two slide after active slide offset
    -1 - one slide before active slide offset
    -2 - two slide before active slide offset
    */
    let slideProgress = slideEl.progress;

    // Do something depending on main progress or slide progress
    // ...
  });
})

```
