### ISSUE TITLE
Effect: 'fade' and slidesPerView: 4 not working together

### ISSUE THREAD

**Issue by SimonFricker** [nolimits4web/Swiper#2062]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 3.4.2
* Platform/Target and Browser Versions: CHROME

### What you did
```
var swiper = new Swiper('.partners', {
    slidesPerView: 4,
    spaceBetween: 30,
    effect: 'fade'
});
```

### Expected Behavior
I expected it to show 4 slides and fade them all out and in at once with the next 4

### Actual Behavior
Slides were stacked and faded on top of each other

**Comment by nolimits4web** [comment]
`fade` effect designed to be used ONLY with `slidesPerView: 1`
