### ISSUE TITLE
Swipe : If user tries to swipe images from out of the container, then images are applied bluish

### ISSUE THREAD

**Issue by kumaravel95** [nolimits4web/Swiper#2064]
* [ ] enhancement

Swiper Version:V 3.4.2

Platform : macOS, Windows , CHROME (All desktop browsers).

### Expected Behavior
If user tries to swipe images from out of the container, then images shoud not apply bluish

### Actual Behavior
If user tries to swipe images from out of the container, then images are applied bluish (REF: Attachement)

Attachement
http://www.screencast.com/t/HvNNM7Hs

**Comment by alejandroiglesias** [comment]
It seems a user selection. You might want to try `user-select: none` on the Swiper container or the slide elements.

**Comment by nolimits4web** [comment]
Closing as irrelevant
