### ISSUE TITLE
BUG: Last slide briefly appears instead of second slide

### ISSUE THREAD

**Issue by davidenco** [nolimits4web/Swiper#2066]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows 7 x64

### What you did
Please see https://jsfiddle.net/6so2jamL/.

$(document).ready(function () {
  var swiper = new Swiper('.swiper-container', {
    preloadImages: false,
    lazyLoading: true,
    watchSlidesVisibility: true,
    initialSlide: 2,
    autoplay: 3000,
    loop: true,
    effect: 'fade',
    speed: 750,
    pagination: '.swiper-pagination',
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    autoplayDisableOnInteraction: false
  });
});

In Firefox or Chrome (latest versions), when the page loads, the initial slide (3) is displayed. For each slide thereafter that is lazy loaded, the fade effect is ignored and the image loads instantly. At the end of the loop when slide 1 is loaded, it's faded in but when it switches to slide 2, a glimpse of slide 6 can be seen for a split second before slide 2 is lazy loaded.

This issue only occurs when lazy loaded is used. If the images are preloaded, the issue does not occur.

**Comment by davidenco** [comment]
The flicker issue with slide 2 does not seem to occur with the non-jQuery version of Swiper.

**Comment by followthemadhat** [comment]
I have the same issue, regardless of version used. I notice this happens when I set additional transition-delay to some slide elements or swiper-wrapper. also having this strange behavior with slide 2 when slider is looped.

**Comment by treforcoster** [comment]
Same issue here with fade.. get some flicker of other slides when using pagination to skip through.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
