### ISSUE TITLE
Resizing on container resize instead of window resize

### ISSUE THREAD

**Issue by AO16** [nolimits4web/Swiper#2068]
This is a (multiple allowed):
* [x] bug
* [x] enhancement

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: All platforms

### What you did
After a `window.resize` a css animation is triggered on the parent container and the slider size is not updated appropriately.

### Expected Behavior
Slider's width updates appropriately given the updated container width.

### Actual Behavior
Slider's width stays at the width of after the `window.resize`, not after the container width change upon css animation.

**Comment by nolimits4web** [comment]
This technology have not standartized yet and the polyfill uses requestAnimationFrame and Mutation Observers to watch for changes which is not perfect from terms of performance. You can use this polyfill manually and call `swiper.update` when changes happen
