### ISSUE TITLE
Different value for parameter autoHeight for different screen sizes - https://codepen.io/versatile/pen/NjxrGK

### ISSUE THREAD

**Issue by SahilMepani** [nolimits4web/Swiper#2071]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: All Browsers

### What you did
Example:
https://codepen.io/versatile/pen/NjxrGK

//  Swiper Init
```
jQuery(document).ready(function($) {
  var tabSlider = new Swiper('.swiper-container', {
    nextButton: '.btn-next',
    prevButton: '.btn-prev',
  });
  var updateTabSlider = function updateTabSlider() {
    if ( window.innerWidth < 768 ) {
      console.log('xs called');
      tabSlider.params.autoHeight = true;
      console.log('AutoHeight: ' + tabSlider.params.autoHeight);
      tabSlider.update(true);
    }
    if ( window.innerWidth > 767 ) {
      console.log('sm called');
      tabSlider.params.autoHeight = false;
      console.log('AutoHeight: ' + tabSlider.params.autoHeight);
      tabSlider.update(true);
    }
  }
  updateTabSlider();
  window.addEventListener( 'resize', debounce(updateTabSlider, 200) );
});
```

### Expected Behavior
Slider slide height should be flexible. autoHeight is setting up and slider should be updated.

### Actual Behavior
Slider slide height is staying fixed.  autoHeight is setting up but slider is not updating.

**Comment by SahilMepani** [comment]
Any help please? Not sure what I am doing wrong.

**Comment by SahilMepani** [comment]
I'm still looking for help :(

**Comment by SahilMepani** [comment]
Any help is appreciated. I'm still not able to fix it.

Thanks

**Comment by nolimits4web** [comment]
Works in v4. Don't also forget to reset height css property on `swiper-wrapper`
