### ISSUE TITLE
bundaries for selectable slides?

### ISSUE THREAD

**Issue by Waog** [nolimits4web/Swiper#2072]
Thanks for your great library. I love to use it so far.

This either is a question is swiper offers such possibility, or a feature request if it doesn't.

Desired Behaviour
---
Assume I want to have 5 Slides:

1.  Non-selectable, purely decorative visible slide
2. Non-selectable, purely decorative visible slide
3. Actually selectable slide
4. Actually selectable slide
5. Non-selectable, purely decorative visible slide

When swiping to another slide than *3.* or *4.*, swiper should bounce back, like it does for the first/last slide in default mode.

Question / Feature Request
---
Is there any way to define which slides are selectable or non-selectable? A range or starting/end-index would be sufficient as well.

**Comment by nolimits4web** [comment]
No, such behavior doesn't supported
