### ISSUE TITLE
Able to swipe infinitely to the left on the first slide

### ISSUE THREAD

**Issue by ChadHelbling** [nolimits4web/Swiper#2075]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v3.4.1 via framework7 1.5.2
* Platform/Target and Browser Versions: cordova, specifically android and the crosswalk webview

### What you did
Using ember-cordova we have the swiper set up in an ember component this is our set up:
```javascript  
 const $swiper = f7Application.swiper('.swiper-container', {
      spaceBetween: 12, // 12px between slides
    });
```

We're also observing onSlideChangeStart to set the active slide index for displaying some stuff outside the swiper that correlates to each slide.

### Expected Behavior
I would expect the swiper to not allow left swiping on the first slide

### Actual Behavior
When we enter the page the first slide is shown but I'm able to swipe to the left into blank space. After I swipe right to the next slide it corrects itself and then I'm not able to swipe into blank space. 

As a workaround I've locked swipe to previous on the first slide and then unlocked after I swipe right, but this seems superfluous. It might be some conflict with crosswalk but I haven't been find the root cause?

**Comment by nolimits4web** [comment]
Doesn't related to Swiper. But looks like you init Swiper in a wrong moment, when it is invisible
