### ISSUE TITLE
onSetTranslate callback stopped running!

### ISSUE THREAD

**Issue by RaiBrightfox** [nolimits4web/Swiper#2085]
In the project I'm working on, I need to do an animation with some images at the same time I drag the swipe, it is working really great with these setting:

    var bgAnim = function(){

            var opacity = (100+(swiper.translate/8))/100,
                move = swiper.translate/4,
                tDur = $('.swiper-wrapper').css('transition-duration').slice(0,-1)*1000; // ## problem to run AUTOPLAY
            if(move>0){move=0}
            if(move<-200){move=-200}
            if(opacity>1){opacity=1}
            if(opacity<0){opacity=0;tDur=tDur/2}
            
            //console.log('move='+move+' - opacity='+opacity+' - tDur='+tDur);

            $('#girl-bg').animate({     // ## problem to run AUTOPLAY
                'left':move,
                'opacity':opacity
            },tDur);
            $('#logo-bg').animate({     // ## problem to run AUTOPLAY
                'opacity':opacity
            },tDur);

        }

    var swiper = new Swiper('.vision', {
        //autoplay: 500,
        autoplayDisableOnInteraction: false,
        slidesPerView: 3,
        spaceBetween: 24,
        freeMode: true,
        slidesOffsetAfter:1000,
        onSetTranslate: bgAnim
    });

The problem is, when I use autoplay it conflicts with the two lines I marked above, if I take the animate and $('.swiper-wrapper').css('transition-duration') off it works well, but I need both to animate the background images...

Can someone help me?

**Comment by RaiBrightfox** [comment]
I found the solution, I did an AutoPlay with some methods and callbacks as you can see below and it worked perfectly. (:

  ```
  var swiperAutoplay = function () {
            swiper.setWrapperTranslate(swiper.getWrapperTranslate() - 1);
            swiper.update(true);
            var autoTime = setTimeout(swiperAutoplay, 3);
            $(homeSwiper).children().click(function () {
                clearTimeout(autoTime);
            });
   };

    setTimeout(swiperAutoplay, 5000);
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
