### ISSUE TITLE
Mousewheel event and magic mouse (inertial)

### ISSUE THREAD

**Issue by bragovo** [nolimits4web/Swiper#2086]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: macOS (Chrome, Safari).

On default demo http://idangero.us/swiper/demos/20-mousewheel-control.html try to switch slides by mouse wheel on magic mouse (Apple mouse with inertial scrolling).

### Expected Behavior
Normal, default behaviour like mouse drag or touch.

### Actual Behavior
First slide switch correct, but mouse have inertia, so events called after finger leave mouse - it' ok.
If I wait last event and scroll again I get normal behaviour, but if I try to scroll until last event is called I get infinite event but slide don't switch, because swiper don't recognise new scroll gesture.

https://youtu.be/JeGZG7Ix5yo

Seems this example working correct http://promo.github.io/wheel-indicator/

**Comment by Kapsul-Brice** [comment]
Also occurs with trackpad 

- Swiper Version: 3.4.2
- Platform/Target and Browser Versions: macOS 10.12.4 (Chrome latest, Safari latest).

**Comment by bragovo** [comment]
On HP laptop (ProBook 430 G4) touchpad slides switching correct like expected behavior. So, can't confirm this bug on not mac touchpad (regular scroll have inertial movement).

**Comment by rossenv** [comment]
The same here
- Swiper Version: 3.4.2
- MacOS 10.12.6
-  Chrome 60.0.3112.101

**Comment by logan-jobzmall** [comment]
Yep. It seems to stop scrolling all together if you continue to scroll. You then have to wait a few seconds before you can even attempt to scroll again.

**Comment by logan-jobzmall** [comment]
@nolimits4web - What would the ETA on this look like? A lot of people with gesture-based laptops will be having similar issues. Thanks!

**Comment by hacknug** [comment]
This is not an ideal solution but it worked for me. Using wheel-indicator to listen to scroll inputs and firing a slide change if the swiper instance is not already transitioning between slides: https://codepen.io/hack_nug/pen/dRxvbN

**Comment by nolimits4web** [comment]
There is no bulletproof way to detect whether scroll happens with inertia or not. So there is a timeout set that has minimal allowed delays between scroll events. If i remove this delay you will get a lot unpredicted slide changes fired by intertia.
