### ISSUE TITLE
Slider won't reposition correctly when toggling on and off of fullscreen.

### ISSUE THREAD

**Issue by jmelendev** [nolimits4web/Swiper#2090]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2.
* Platform/Target and Browser Versions: macOS, CHROME

### What you did
I have a function where on click the user can expand the browser to fullscreen. Swiper adjusts correctly when going to full screen but when exiting fullscreen mode the slider get out of alignment. Also to note, I am expanding the section containing the slider and hiding the left banner at the same time as expanding the window. 

The function call I am using is:

```
    var mySwiper = new Swiper ('.swiper-container', {
      // Optional parameters
      direction: 'horizontal',
      loop: true,
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev',
      observer: true,
      observeParents: true
    });
    $(window).resize(function() {
      mySwiper.onResize();
    });
```

The Function that expands the slider looks like this

```
expandButton.on("click", function(){
        $(this).addClass('hide');
        shrinkButton.addClass('show');
        toggleFullScreen();
        $("body header").toggleClass("hidden");
        $("body main").toggleClass("expanded");
      });
```
I'm hoping im just missing a setting here. Otherwise, love the plugin. Great Work!

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by glerinsonum** [comment]
@jmelendev Hello. 

I have used this script for Simple Slider, and I'm satisfied.  
var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        paginationClickable: true,
        spaceBetween: 30,
        centeredSlides: true,
        autoplay: 4000,
        speed: 1000,
        watchSlidesVisibility: false,
    });

**But** When I touch or to see more new from simple slider using left and right icon, autoplay stopped.

**Comment by julmot** [comment]
I have the same problem currently.

**Comment by Oliver-Piorun** [comment]
Same problem here. Greetings ~

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
