### ISSUE TITLE
How to change swiper-slide width?

### ISSUE THREAD

**Issue by scurk1415** [nolimits4web/Swiper#2095]
Well I have setup my swiper so that it shows 2 images with centered slides (picture below).
https://ibb.co/foRFkk

Is it possible to set the swiper-slide width to about 80% of the visible container, so that the centered image gets bigger and we see less of the images at the side?

**Comment by nolimits4web** [comment]
`slidesPerView: 'auto'`

and in CSS `.swiper-slide { width: 80% }`

**Comment by DanielRuf** [comment]
I'm curious why this can not be used with `slidesPerView`. For example the visible slides should have different width (prev 25%, active 50%, next 25%) but the slides are always calculated when `slidesPerView` is a number. @nolimits4web

**Comment by DanielRuf** [comment]
So far combining (prev 25%, active 50%, next 25%) + `slidesPerView: auto` + `loop: true` + `centeredSlides: true` is problematic.

**Comment by DanielRuf** [comment]
I guess they are not recalculated as the slides widths dynamically change (prev 25%, active 50%, next 25%)

**Comment by arsyandipratama22** [comment]
i found this issue

yaa it's simple, in tag <div class="swiper-container"> just add inline css <div class="swiper-container" style="width:100%; height:400px;"> if you want to change width or height in swiper

**Comment by arsyandipratama22** [comment]
just add  inline css
<div class="swiper-container" style="width:100%; height:400px;">
if you want to change width or height in swiper content
i try it
and it's work :3
