### ISSUE TITLE
Random spacing between the slides in IE11

### ISSUE THREAD

**Issue by adamk22** [nolimits4web/Swiper#2096]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows, IE 11

### What you did
I have a swiper instance on page which doesn't much modifications other than setting the heights. It works as expected in Firefox, Safari, Chrome and Edge but not in IE11. For some peculiar reason, some images have a strange gap in between the images (screenshots: http://imgur.com/a/VCngt). I've tried everything using CSS to fix this issue thinking it might be a flex issue due to partial flexbox support for IE11. But unfortunately, this is not the case (or if you can show me otherwise).

The spacings happen very randomly. Sometimes only the first few slides work like they suppose to and sometimes only the last or middle ones. 

The slider has a mixture of wide and portrait images.

### Expected Behavior
I expect the images to sit next to each other like they do in firefox, chrome, safari in edge.

### Actual Behavior
The slides within the wrapper randomly get a spacing on one side or sometimes both sides of the image. I suspect that the slides are not correctly calculated. (screenshots: http://imgur.com/a/VCngt)

How the slider is formatted:
```
<div class="single-gallery">
    <div class="container-fluid no-padding-right">
        <div class="row">
            <div class="col-xs-12">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for item in post.get_field('project_gallery') %}
                        <div class="swiper-slide">
                            <img src="{{TimberImage(item.image).src('large')}}" />
                            <div class="single-gallery_description">
                                {{item.description}}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>   
            </div>
        </div>
    </div>
</div>
```

How the js is initialized (this is wrapped in a document ready):
```
function swiperInit() {
        var windowWidth = $(window).width();
        if(windowWidth < 768) {
          swiper = new Swiper('.swiper-container', {
            autoHeight: true,
            slidesPerView: 1
          });
        } else if (windowWidth > 769){
          swiper = new Swiper('.swiper-container', {
            autoHeight: false,
            slidesPerView: 'auto',
            slidesOffsetAfter: 800
          }); 
        }
      }

swiperInit();
```

CSS:

```
.single-gallery {

	.swiper-container {
		overflow: visible;
 		height: auto;
		@media (min-width: $screen-sm-min) {
			height: 500px;
		}
		@media (min-width: $grid-max-container) {
			height: 750px;
		}
	}

	.swiper-slide {
		@media (max-width: $grid-max-container) {
			max-width: 100%;
			img {
				max-width: calc(100% - 20px);
			}
		}

		img {
			@media (min-width: $screen-sm-min) {
				max-height: calc(100% - 40px);
			}
			margin-right: 20px;
		}	
		width: auto;
		transition: $transition-normal;
	}

	&_description {
		opacity: 0;
		margin-top: 10px;
		transition: $transition-normal;

		@media (min-width: $screen-sm-min) {
			margin-top: 0;
			position: absolute;
			bottom: 0;
			left: 0;
			width: 100vw;	
		}
	}
	.swiper-slide-active {
		transition: $transition-normal;
		.single-gallery_description {
			opacity: 1;
		}
	}
	.swiper-slide-next,
	.swiper-slide-prev {
		cursor: pointer;
	}
}
```

I've spend a couple hours trying to debug this issue without any luck and I haven't found any similar case on git. So if anyone has any leads on this, please do share!

**Comment by sinneren** [comment]
I have similar issue with margin-right and translate3D. But bug only with my site, and when I paste my styles to codepen\fiddle it works fine...

**Comment by adamk22** [comment]
I've done a lot of testing and I believe it has to do something with the initialisation. A dirty trick I tried which worked out was using a setTimout..

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
