### ISSUE TITLE
Swiper 3.4.2 with loop + navigational buttons will disable buttons

### ISSUE THREAD

**Issue by xavianaxw** [nolimits4web/Swiper#2099]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Any

### What you did
Simple setup with loop functionality with navigational controls
``` js
const swiper = new Swiper(this.el, {
  nextButton: '.swiper-button-next',
  prevButton: '.swiper-button-prev',
  loop: true
});
```

### Expected Behavior
Similar to demo where looping of slides work and navigational buttons are always not disabled

### Actual Behavior
Buttons getting disabled when reaches first and last slide

**Comment by iCodr8** [comment]
I have the same problem. Is there a simple solution or workaround for that?

**Comment by iCodr8** [comment]
Workaround:

```
var swiper1x = new Swiper('.swiper-1x', {
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    loop: true
  });

  $('.swiper-1x')
    .on('click', '.swiper-button-prev', function() {
      swiper1x.slidePrev();
    })
    .on('click', '.swiper-button-next', function() {
      swiper1x.slideNext();
    });
```
