### ISSUE TITLE
initialslide: 0 or mySwiper.slideTo(0)

### ISSUE THREAD

**Issue by cojaco** [nolimits4web/Swiper#2103]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Swiper 3.4.2
Windows Chrome, and probably others

I have a problem with initialslide: 0 or mySwiper.slideTo(0).

I open a popup and parse the clicked item (itemindex) now the swiper is initialiced and opens with correct slide.
Except, when its the first slide (itemindex is 0) if this is the case, the last slide is visible, not the slide with index = 0,

function testswiperpopup(itemidndex) {

            var popupswiper = new Swiper('.swiper-popup-container', {
                initialSlide: itemidndex,
                slidesPerView: 1,
                lazyLoading: true,
                lazyLoadingInPrevNext: true,
                lazyLoadingInPrevNextAmount: 1,
                spaceBetween: 60,
                keyboardControl: true,
                nextButton: '.test-swiper-next',
                prevButton: '.test-swiper-prev'
            });
            popupswiper.slideTo(itemidndex,0,false);
        }

### Expected Behavior
I tried both methods initialSlide and slideTo.
And I expect, the Popup to start with slide 0 if itemindex is = 0.

Does anybody has an idea how to fix that?

**Comment by cojaco** [comment]
ok, i made it work like this:

        var popupswiper = new Swiper('.swiper-popup-container', {
            initialSlide: itemidndex,
            slidesPerView: 1,
            lazyLoading: true,
            lazyLoadingInPrevNext: true,
            lazyLoadingInPrevNextAmount: 1,
            spaceBetween: 60,
            keyboardControl: true,
            nextButton: '.test-swiper-next',
            prevButton: '.test-swiper-prev'
        });

        popupswiper.setWrapperTranslate(0);
        popupswiper.slideTo(itemidndex,0,false);
    }

but its a little strange that you can "slideTo(x)" or set "initialSlide: x" any swipe except the first one

**Comment by wgroenewold** [comment]
You should'nt init the swiper every time you open the popup. It's better to set observer to true and then do your hide/show magic.

**Comment by yadsun** [comment]
you should not let initialSlide the same as the slideIndex you want slideTo

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
