### ISSUE TITLE
stopAutoplay resets timer, while it's supposed to function as a pause.

### ISSUE THREAD

**Issue by stefan1294** [nolimits4web/Swiper#2109]
This is a:
* [x] bug

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows, Chrome, MacOS

### What you did
` $(this.element).on({
                mouseenter: function () {
                    productImageSlider.stopAutoplay();
                    swiperNextButtonCircleDiv.toggleClass('pause');
                },
                mouseleave: function() {
                    productImageSlider.startAutoplay();
                    swiperNextButtonCircleDiv.toggleClass('pause');
                }
            });`

### Expected Behavior
When I hover, the slider has to stop. If the autoplay speed is set to 5000ms and I hover at 2500ms and afterwards I leave my mouse from the element, the new slide animation will start in 2500ms.

### Actual Behavior
When I hover at 2500ms and I remove my mouse from the element, I have to wait another 5000ms for the next slide animation to start. When I hover at 4000ms, I also have to wait another 5000ms for the next animation slide to start.

**Comment by nolimits4web** [comment]
Because it called `stop`. Stop means stop, no pause
