### ISSUE TITLE
Slideable menu is not working from right 

### ISSUE THREAD

**Issue by ai-tushar** [nolimits4web/Swiper#2113]
* [x] bug
* [x] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: macOS, Windows, IOS, ANDROID, CHROME, ETC.

### What I did
i have tried to show the slideable menu from right side, but its not working,
here's what i did,
```
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <div class="swiper-slide content">
                    <div class="menu-button">
                        <div class="bar"></div>
                        <div class="bar"></div>
                        <div class="bar"></div>
                    </div>
                    Content slide
                </div>
                <div class="swiper-slide menu">Menu slide</div>
            </div>
        </div>
```
move the menu slide after the content slide. and set the `initialSlide: 0`
```
          var toggleMenu = function () {
                if (swiper.previousIndex == 0)
                    swiper.slidePrev()
            };
            var menuButton = document.getElementsByClassName('menu-button')[0];
            var swiper = new Swiper('.swiper-container', {
                slidesPerView: 'auto',
                initialSlide: 0,
                resistanceRatio: .00000000000001,
                onSlideChangeStart: function (slider) {
                    if (slider.activeIndex == 0) {
                        menuButton.classList.add('cross')
                        menuButton.removeEventListener('click', toggleMenu, false)
                    } else
                        menuButton.classList.remove('cross')
                },
                onSlideChangeEnd: function (slider) {
                    if (slider.activeIndex == 0)
                        menuButton.removeEventListener('click', toggleMenu, false)
                    else
                        menuButton.addEventListener('click', toggleMenu, false)
                },
                slideToClickedSlide: true
            })
```
### Expected Behavior
expected to work when i click on the button, the menu would be opened from right side, and when click again, menu will close.

### Actual Behavior
1. button click event is not working after moving the menu slide after content slide.
2. onSlideChangeStart and onSlideChangeEnd callbacks are not getting called after this. but this should be always getting called whenever slide changes. i have tried console.log() inside this, and i am sure these are not getting called.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
