### ISSUE TITLE
In Chrome v50.0.2661.102, container cannot be hidden

### ISSUE THREAD

**Issue by gg343917542** [nolimits4web/Swiper#2114]
This is a (multiple allowed):
* [x] bug

* Swiper Version:  3.4.2

* Platform/Target and Browser Versions: Chrome 50.0.2661.102

### Actual Behavior
When the mouse moves to the code in Dev Tools 'Elements' page,the container will hide. But other browsers have not yet been able to do so. I think this is a browser problem.

**Comment by DanielRuf** [comment]
Chrome 50? Sounds old. Chrome 60 is the current version.

Is this still occurring?
