### ISSUE TITLE
Cube effect + Nested does not start from the first slide

### ISSUE THREAD

**Issue by mogholito** [nolimits4web/swiper#2121]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2.
* Platform/Target and Browser Versions: tested on macOS 10.12, Windows 10, Chrome (v.58), Firefox (v.53 MacOS and v.51 WIndows).

### What you did
I set up a nested Swiper based on the [demo](http://idangero.us/swiper/demos/11-nested.html), with six horizontal slides and two additional slides in the nested slider. I set Loop to true and added up/down arrows.
I numbered the slides to make it easier to see the bug.
You can check on [JSFiddle](https://jsfiddle.net/redcats/84h3nm9w/)

### Expected Behaviour
The default behaviour is to start from the first slide to the last. It works fine when using all effects except the cube.

### Actual Behaviour
When choosing the cube effect, Swiper starts with the Slide 5 then continues with the Slide 6 and as expected because there are six slides, it goes to the Slide 1, but instead of to go to the next Slide 2, it shows the Slide 4 then 5 and the last Slide 6. So Swiper never shows Slide 2 and 3!
And the most incoherent behaviour is as 'loop' is set to true, Swiper restarts with the Slide 1 then directly jumps to the Slide 6.
It seems the indexing system is completely buggy when the cube effect is enabled.

**Comment by hfreedman73** [comment]
Yes, I can confirm the bug.  It happens with cube effect and not with slide effect. With cube it happens with more than 4 horizontal elements and nested vertical ones.
