### ISSUE TITLE
触摸设备多点触摸时出现卡住/Touch devices appear jammed when multi touch

### ISSUE THREAD

**Issue by lemontree2000** [nolimits4web/Swiper#2124]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
Steps to reproduce

官网任何示例在手机上，先用单指滑到一半，然后在用另一手指触摸滑动的块。会出现卡住的问题。

Any example on the phone, first slip to half with a single finger, and then touch the slider with another finger. There will be a stuck problem.

What is Expected?

希望多指滑动不会出现异常。

Hope that the fingers will slip and no abnormalities will occur

What is actually happening?

出现卡住的问题。

Stuck problem.

**Comment by nolimits4web** [comment]
Fixed in latest version
