### ISSUE TITLE
condition statement which detecting positive oversliding is wrong

### ISSUE THREAD

**Issue by wumengqiang** [nolimits4web/Swiper#2126]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version:3.4.2
* Platform/Target and Browser Versions: Mac/Chrome

### What you did
1. init swiper
```
        this.swiper = new Swiper('.farmhouse-wrapper', {
          direction: 'horizontal',
	  loop: true,
          runCallbacksOnInit: false,
          wrapperClass: "farmhouse-list",
          centeredSlides: true,
          spaceBetween: 0,
          slidesPerView: "auto",
          loopedSlides: 1,
          watchSlidesProgress:true,
 
              })
```

2. i have 4 slide.

### Expected Behavior
 the loop slide range is  [1,4]. for example, when i swipe to left , active indexes should be 1 , 2, 3 , 4, 1, 2....

### Actual Behavior
 found the loop slide range is [1,2],when i swipe to left , active indexes are 1, 2,  1, 2, 1, 2....

### BUG I FOUND
in s.fixLoop, **positive oversliding condition statement** is buggy, it may be 
```
(s.params.slidesPerView === 'auto' && s.activeIndex >= s.slides.length - s.loopedSlides * 2) || (s.activeIndex > s.slides.length - s.params.slidesPerView * 2)
``` 
other than 
```
(s.params.slidesPerView === 'auto' && s.activeIndex >= s.loopedSlides * 2) || (s.activeIndex > s.slides.length - s.params.slidesPerView * 2)
```

**Comment by nolimits4web** [comment]
Would be good to see the PR instead. With examples before and after the fix
