### ISSUE TITLE
Hide navigation from screen reader option

### ISSUE THREAD

**Issue by ygatesoupe** [nolimits4web/Swiper#2127]
Hello,

It's great to have a a11y option that provide correct ARIA but it would be interesting to allow hiding those elements from screen reader as well.

Since screen reader user can navigate through all slides without arrow nav buttons it's not worth mentioning it to user and can be confusing.

I'm testing with NVDA screen reader.

This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1

**Comment by nolimits4web** [comment]
I believe you can just add `aria-hidden="true"` attribute to those elements
