### ISSUE TITLE
Dynamically add Slider to website (after ajax call)

### ISSUE THREAD

**Issue by tripboxer** [nolimits4web/Swiper#2128]
I try to build a website with multiple swiper sliders which are loaded dynamically with ajax. The pagination and the controls seem to be shown correctly for each loaded slider but none of the sliders is working properly.

Is there any way to dynamically add new sliders to website (not slides to an existing slider!)?

**Comment by eduardopopego** [comment]
Hi!

I could be wrong but I think you should create a new instance of the Swipe object for each slider that you want to create, each of the latter with a unique class name or # ID.
```
var mySwiper1 = new Swiper('.swiper-container-unique-class-name', {
loop: true,
pagination: '.swiper-pagination',
});
var mySwiper2 = new Swiper('.swiper-container-another-unique-class-name', {
loop: false,
pagination: '.another-swiper-pagination'
});
```

So basically you should create a new mySwiper# variable and initialize Swiper for every new slider you wish to add. You could set this upon success of the ajax call or whatever you feel is best.

Haven't tested it, but seems reasonable.

**Comment by nolimits4web** [comment]
Closing as looks like resolved or due to inactivity
