### ISSUE TITLE
Set active class with click even if all slides are visible

### ISSUE THREAD

**Issue by dgsunesen** [nolimits4web/Swiper#2129]
Hi there,

I'm working on a project where I have slider that behaves differently depending on screen sizes.

If I'm on a rather large desktop screen, the slider should more or less behave like a tab with all slides visible with the first active slide to the left. Here I would like to be able to click any slide to set it to active. At the moment I see in the DOM that it actually responds to my clicks but it's always the first slide that's set to active.

Now, when I get to a smaller screen size, the idea is to have it slide normally with the slides centered.

So, I guess my questions is, if it's possible to set the active slide class even if all slides are visible and have it sort of behave like a tab and then on smaller screen sizes (using breakpoints) go back to normal sliding?

Best regards,
Dan

**Comment by nolimits4web** [comment]
Such logic should be added manually. To disable swiping you can use `allowTouchMove` parameter within breakpoints. But settings active class to all slides should be done manually.

**Comment by dgsunesen** [comment]
Alright. Thanks for answering. I went with another approach which didn't include the tab thing :)
