### ISSUE TITLE
about  at line 3881,what 's meaning .

### ISSUE THREAD

**Issue by herrdu** [nolimits4web/Swiper#2131]
Swiper 3.4.0

about  at line 3881:    

what's the diffrent between 

  if (s.isHorizontal() &&(
                        (Math.floor(z.image.minX) === Math.floor(z.image.startX) && z.image.touchesCurrent.x < z.image.touchesStart.x) ||
                        (Math.floor(z.image.maxX) === Math.floor(z.image.startX) && z.image.touchesCurrent.x > z.image.touchesStart.x))
                    ) {
                        console.log('s.isHorizontal is true');
                        return;
                    } else if (!s.isHorizontal() &&(
                        (Math.floor(z.image.minY) === Math.floor(z.image.startY) && z.image.touchesCurrent.y < z.image.touchesStart.y) ||
                        (Math.floor(z.image.maxY) === Math.floor(z.image.startY) && z.image.touchesCurrent.y > z.image.touchesStart.y))
                    ) {
                        console.log('s.isHorizontal is false');
                        z.image.isTouched = false;
                        return;
                    }

and 

  if (s.isHorizontal() &&
                        (Math.floor(z.image.minX) === Math.floor(z.image.startX) && z.image.touchesCurrent.x < z.image.touchesStart.x) ||
                        (Math.floor(z.image.maxX) === Math.floor(z.image.startX) && z.image.touchesCurrent.x > z.image.touchesStart.x)
                    ) {
                        console.log('s.isHorizontal is true');
                        return;
                    } else if (!s.isHorizontal() &&
                        (Math.floor(z.image.minY) === Math.floor(z.image.startY) && z.image.touchesCurrent.y < z.image.touchesStart.y) ||
                        (Math.floor(z.image.maxY) === Math.floor(z.image.startY) && z.image.touchesCurrent.y > z.image.touchesStart.y)
                    ) {
                        console.log('s.isHorizontal is false');
                        z.image.isTouched = false;
                        return;
                    }

**Comment by DanielRuf** [comment]
Just some extra braces: https://www.diffchecker.com/ajZ2xtiq
