### ISSUE TITLE
Feature-Request for nextButton and prevButton

### ISSUE THREAD

**Issue by Daijobou** [nolimits4web/Swiper#2133]
See this fiddle https://jsfiddle.net/ee32t6q4/ 

Request is for setting "slidesPerView: auto"

Click on nextButton or prevButton its swipe a single element. I wish that it scroll to the first not complete visible Slide. Means: When I see "Slide 1" "Slide 2" "Slide 3" and not or only partly "Slide 4" than "Slide 4" should be the first Slide. Has anyone understood my request or is this already possible?

**Comment by nolimits4web** [comment]
There is `slidesPerGroup` parameter to control such behavior

**Comment by Daijobou** [comment]
Thanks, but how I use this in a responsive design with diffrent count of slides in a view? I like to slide all visible slides, what depends on devicescreen size.
