### ISSUE TITLE
Is there any options in idangero swiper plugin to highlight active slide by zooming or increasing the active slide size?

### ISSUE THREAD

**Issue by sackIndian** [nolimits4web/Swiper#2137]
I have used 'idangero swiper' for one of my album view, i want to show a custom animation which is something like 'effect:coverflow'.

But as with 'coverflow' i dont want to place other slides in decreasing size order. Means i want to highlight active slide with 400x400 resolution, keeping all other slides 200x200.

So when i slide the active slide will become 400x400 keeping other slides 200x200.

I have done some css tricks as follow,

.swiper-slide-active {
     width: 400px;
    height: 400px;
}
But i want to introduce a zoomed animation during swipe(as happens with effect:coverflow)

Is there any way i can achieve this?

**Comment by DanielRuf** [comment]
Did you already try a transition with transform:scale?
