### ISSUE TITLE
Bug on Chrome 59, the pagination is active without pushing any buttons and doesn't scroll the slides

### ISSUE THREAD

**Issue by maofree** [nolimits4web/Swiper#2138]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

Chrome's version 59.0.3071.109 (Build) (a 64 bit) on linux

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

go to your demos page and move the mouse on the second carousel "Responsive / Fullscreen + Pagination" also in others with more visible slides and pagination
the slide will follow the mouse without scroll the slide to the next or previous one and without pushing on any buttons

http://idangero.us/swiper/demos

bye

![1](https://user-images.githubusercontent.com/653230/27585532-ff0b25a4-5b3c-11e7-9df9-52bb508da52a.png)

**Comment by maofree** [comment]
I'm trying more tests
now in some demos it is ok but on "Slides Per View / Carousel Mode" I get this problem
try to do some drag tests on the first carousels then go down and you will see that the scrolling will have more problems then it will stop to work

**Comment by maofree** [comment]
on firefox all work well

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by maofree** [comment]
Hi
I've tested now and I get the same problem on chrome 62
go here
http://idangero.us/swiper/demos/
and check the demo "Centered Slides" or "Auto Slides Per View / Carousel Mode"
push the left button of your mouse over the carousel and move the mouse left and right, then stop to push the button and continue to move the mouse left and right, the slides will continue to following the mouse direction left and right.
In some case all is ok in others I get often this problem
however I can easily reproduce it on your site

**Comment by nolimits4web** [comment]
It is because the demo runs in iframe

**Comment by maofree** [comment]
ok thanks
so you can close this topic

bye
