### ISSUE TITLE
Hard to trigger click event on Wacom / pen tablet

### ISSUE THREAD

**Issue by yuchant** [nolimits4web/swiper#2139]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.3.1, but the bug has been seen for at least 2-3 years.
* Platform/Target and Browser Versions: macOS Chrome/Safari

### What you did
For years, since first starting to use this plugin, I have always had problems with my Wacom tablet sensitivity causing usability issues with Swiper. 

Clicking on elements on the Swiper such as pagination, next/prev, or buttons often results in a slide change or slide movement as opposed to a click event.

Many people in my industry use a Wacom tablet, and I've seen the problem replicated consistently. 

I have always considered this a non issue / specific to a tiny fraction of people, and ignored the issue. It occurs to me it could be fixed and make the experience better for all Wacom users.

### Expected Behavior
Expected behavior is to register clicks more consistently upon clicking on a button with a Wacom pen. 

### Actual Behavior
What actually happens is the click is not registered, and instead we get a micro movement of swiper, or a swipe change. 

## Notes
Would a dead zone of 3-5px dragging being considered a click cause many issues for non pen users?

**Comment by nolimits4web** [comment]
> Would a dead zone of 3-5px dragging being considered a click cause many issues for non pen users?

Yes

**Comment by nolimits4web** [comment]
There fix can be do it only for Wacom, but i have not such device and not able to fix it. If you can, PR is appreciate

**Comment by MarcinRabczynski** [comment]
Its not just issue for specific tablet, the same problem exist when you have on click action on swiper item.
In many case clicking on image slides left or right instead of click action.

Such option for configure dead zone would be very valuable.
