### ISSUE TITLE
Leaked Swiper instances after destroy()

### ISSUE THREAD

**Issue by sergeystoma** [nolimits4web/Swiper#214]
I have a single page app which repeatedly creates and destroys Swiper instances. While cleaning up our memory usage, I've noticed that at least according to Chrome's Heap Snapshot tool, swiper stays around in memory even after calling **destroy()**

I'm not sure I really understand retain chains in this case - all events are cleaned up, and there are no DOM references, but setting **_this** var to **null** at the end of **destroy()** seem to help and leaked instances are gone after that.

**Comment by superfunkminister** [comment]
+1, still having this issue. Crashes the browser eventually.
