### ISSUE TITLE
Hashnav doesn't work with data-history

### ISSUE THREAD

**Issue by goldquest** [nolimits4web/Swiper#2145]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: macOS 10.12.4, Chrome 59

### What you did
I activated `hashnav` and `hashnavWatchState` and added `data-history` attributes to elements.

### Expected Behavior
Changing slides should work as normal, also back button of browser should change the slide to the last shown.

### Actual Behavior
When trying to change the slide, it always scrolls to the first slide.

It seems like in following file, only `data-hash` is used, but not the `data-history` attribute, which is recommend in the API. https://github.com/nolimits4web/Swiper/blob/master/src/js/hashnav.js#L7-L10

**Comment by nolimits4web** [comment]
data-history is to work with History navigation (http://idangero.us/swiper/api/#history-navigation) , not for Hash navigation
