### ISSUE TITLE
Hashnav: Slides jump a bit when sliding

### ISSUE THREAD

**Issue by goldquest** [nolimits4web/Swiper#2146]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions:  macOS 10.12.4, Chrome 59

### What you did
I activated `hashnav` and `hashnavWatchState` and added `data-hash` to the elements.

### Expected Behavior
Swiping to other slides should work normally. Using the back button in the browser should go back to the previous slide.

### Actual Behavior
It slides to the expected slide, but there is some back-and-forth jumping visible.

**Comment by goldquest** [comment]
my fault. Works as expected

**Comment by jakelaz** [comment]
@goldquest having trouble setting up my swiper with hash nav. Can you please send the proper code structure to my email: jake@openmessage.io?
