### ISSUE TITLE
Issue with container using flexbox

### ISSUE THREAD

**Issue by shkodasv** [nolimits4web/Swiper#2151]
The same issue I faced with idangerous swiper as described here https://github.com/kenwheeler/slick/issues/2378
If the container has display:flex, then on resize the width is calculated incorrect. When i reload the page everything is fine.
How can I fix it ?

example https://jsfiddle.net/ValentinaSmirnova/bu5kb0c6/

**Comment by webappcreations** [comment]
Maybe you could reinitialize the Swiper when resizing?
eg.:


`
setTimeout(function() {    
    initSwiper();   
}, 1000);

window.initSwiper = function() {

    var swiper = [];

    $('.swiper-container').each(function(index){

        var $el = $(this);

        swiper[index] = $el.swiper({
          //options
        });
    
        $(window).resize(function() {
            updateSwipers();
        });
    });
}

window.updateSwipers = function() {
    $('.swiper-container').each(function() {
        this.swiper.update();
        //this.swiper.slideTo();
        //this.swiper.startAutoplay();
    });
}
`
Not sure if this would help... Important is the swiper.update() function when resizing the page!

**Comment by nolimits4web** [comment]
Not the Swiper issue, this is how CSS flex works
