### ISSUE TITLE
Feature Request: 360 Viewer Example

### ISSUE THREAD

**Issue by julmot** [nolimits4web/Swiper#2156]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

The "fade" effect is already quite similar to what I'm looking for. I just want to show up to 72 images in one single swipe animation, not one image per swipe. This is used to show a product from all sides. Like this plugin already does:

https://www.magictoolbox.com/magic360/

I would like to see an example for this in the Swiper showcase.

**Comment by nolimits4web** [comment]
I believe you can just enable autoplay and set `speed` parameter to `0`
