### ISSUE TITLE
Set a11y option to true by default

### ISSUE THREAD

**Issue by julmot** [nolimits4web/swiper#2158]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

From my experience, accessibility is something only a few developers like me care about. However, the user base of blind or handicapped people is large. Due to these facts, I'd recommend to enable the `a11y` option by default. Most people won't even notice and it will cause a better web experience for many people.

**Comment by julmot** [comment]
Don't close.

**Comment by nolimits4web** [comment]
It is already enabled by default
