### ISSUE TITLE
Swiper SASS styling

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [nolimits4web/swiper#2159]
This is a:
* [x] enhancement

It would be great if Swiper also had sass in addition to less styling. If (like me) you develop your projects using sass, being able to import and modify sass variables before being processed would be a nice addition :)

**Comment by camdagr8** [comment]
I used this tool when I needed to set it up as a sass file. It's not perfect, but it at least gave me a starting point to then variablize my styles. 

http://css2sass.herokuapp.com/

**Comment by landsman** [comment]
yes please! :)

**Comment by asso1985** [comment]
It would be great

**Comment by mescie** [comment]
+1 would be great to have SASS

**Comment by James-Bovis** [comment]
+1 I would love to see a SASS port too. I'm facing the same problem as @goranNetgen ]

**Comment by paolocavanna** [comment]
+1 it'd be absoluteley a useful feature to be added

**Comment by dangelion** [comment]
+1 please

**Comment by goranNetgen** [comment]
Guess this won't be a problem anymore soon since LibSass decided to undeprecate CSS imports (yay) https://github.com/sass/libsass/pull/2684
It would still be a nice feature.

**Comment by dangelion** [comment]
Actually on [Hugo](https://gohugo.io/hugo-pipes/scss-sass/) I get error

`error: failed to transform resource: SCSS processing failed: file "stdin", line 57, col 1: File to import not found or unreadable: ../../../../node_modules/swiper/dist/css/swiper.`

because of importing css from an scss is not good
