### ISSUE TITLE
slidesPerView and slidesPerColumn didn't work with breakpoints

### ISSUE THREAD

**Issue by tranlehaiquan** [nolimits4web/swiper#2160]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

### What you did
I want make slide  slidesPerView: 2 and slidesPerColumn: 3, and when window width <= 550 it change to 
slidesPerView: 1 and slidesPerColumn: 1, but it didn't work.

### Expected Behavior
From  slidesPerView: 2 and slidesPerColumn: 3 to slidesPerView: 1 and slidesPerColumn: 1 when window width <= 550
### Actual Behavior
Column show all item

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by tranlehaiquan** [comment]
Working well but must reload browser at that beakpoint!

**Comment by scooterlord** [comment]
Well, I noticed this issue today as well, I would expect it to be working without interaction.
