### ISSUE TITLE
Navigation display bug with safari

### ISSUE THREAD

**Issue by nbohlen** [nolimits4web/Swiper#2161]
When using the 3d cube effect the slider-navigation dispappears on **Safari** within the middle Slides. You can see it on the projects demo page (with safari): http://idangero.us/swiper/demos/17-effect-cube.html

Another strange behavior in safari is that the clickable area within the slides gets cut. 
Is there any solution to this problem?

**Comment by nbohlen** [comment]
**Update** I fixed the navigation Problem with this Fix by trial and error:

```
.swiper-pagination-clickable .swiper-pagination-bullet {
  cursor: pointer;
}

.swiper-container-vertical > .swiper-pagination {
  right: 10px;
  top: 50%;
  -moz-transform: translate3d(0px, -50%, 1px);
  -webkit-transform: translate3d(0px, -50%, 1px);
  transform: translate3d(0px, -50%, 1px);
}
```
But the Click behaviour on **Safari** still exists: I set up a fiddle for this:
https://jsfiddle.net/m9q48aks/

On Safari: if you try to click on the link "Test" you see that that the active click area is moved.
On Chrome / Firefox: everything is fine

**Comment by nolimits4web** [comment]
This is actually issue with Safari, this is how it treats 3d perspective. You will see what is the problem with you try to inspect elements that its actual place and size is different from what Safari renders
