### ISSUE TITLE
Swipers Progress doesn't update smoothly on click.

### ISSUE THREAD

**Issue by katerlouis** [nolimits4web/Swiper#2165]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.2

### What you did
I need custom transitions between bullets.
Therefore I want to update a GSAP Timeline's progress on Swiper's progress. 

### Expected Behavior
Swipers progress property updates smoothly even when I click a bullet / next, prev / or a another slide.

### Actual Behavior
When I click on a bullet or on another slide, the slider still animates (as expected) but the progress property jumps to the final number.

Illustrated in the following pen.
Drag the slider and watch the progress-output.
Then drag and let loose at some point inbetween slides > the progress jumps, the slider animates.
Then click a slide or bullet. Progress jumps, slider animates. Bummer!

https://codepen.io/katerlouis/pen/QMwpJB

**Comment by katerlouis** [comment]
* gentle push *

**Comment by katerlouis** [comment]
Slightly harder push?

**Comment by danielkalen** [comment]
Extra push

**Comment by nolimits4web** [comment]
It happens because progress doesn't updates smoothly, it has fixed values. Use CSS `transition` on required elements for smooth transitions
