### ISSUE TITLE
Swiper actual size

### ISSUE THREAD

**Issue by gosh34** [nolimits4web/Swiper#2168]
Dear Team,
I am happy that I found Swiper and started to dig into it.

I am using this:
http://jsfiddle.net/9VBha/14/
with jQuery jquery-3.2.1.slim.min.js

The issue I am unable to fix is related to the size of the container. When the browser size is two small, for example the size of a mobile device, even when the Container size is set to max-width that is less than the browser size, the horizontal scrollbar appears. When you open it via mobile, there is some horizontal scrolling what is really annoying. 

So the container is less than the browser size, it is also set to overflow: hidden, but there is like something invisible for about 10 pixels at the right of the container that makes the vertical scrolling and I cannot get rid of it.

Please see the picture attached.
![swiper](https://user-images.githubusercontent.com/6117573/28707529-6c677fa6-7381-11e7-9f84-385941275494.jpg)

Thank you in advance!
Great job!

**Comment by nolimits4web** [comment]
Please update swiper to latest version, you are using something really old
