### ISSUE TITLE
ARIA attributes for Swiper Elements

### ISSUE THREAD

**Issue by bke-daniel** [nolimits4web/swiper#2169]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: to be discussed / implemented
* Platform/Target and Browser Versions: all

### What you did
Hey everyone,
first of all, great work with swiper. I'm using it on every projects which requires some swiping mechanism. So for so good.
In my current project I have to improve the code with some ARIA labels. So far, there aren't any. That's why I wan't to open an discussion / feature request about weather or not to implement them.
Looking forward hearing your ideas.

Cheers,
Daniel

Edit: To make it clear: Surely there's the option `a11y: true`, but it's not what I'm looking for, because it's "just keyboard accessibility"

### Expected Behavior
Swiper uses proper ARIA labels. But as far as I know there's no proper role for an carousel / image slider?

### Actual Behavior
No ARIA labels / attributes at all.

**Comment by hacknug** [comment]
Did you set `a11y: true`? Also, @julmot proposed on #2158 changing the default to `true` to make Swiper instances more accessible.

**Comment by bke-daniel** [comment]
@hacknug Yes, i did. I've been adding further information with: 

>  Edit: To make it clear: Surely there's the option a11y: true, but it's not what I'm looking for, because it's "just keyboard accessibility"

**Comment by julmot** [comment]
Can you elaborate what attributes you're missing?

**Comment by bke-daniel** [comment]
Hey there,

sorry for the late answer, have been busy.
Well, if you ask this way: I think that an element around the "buttons" with a certain role is missing. From here on I can't answer you question any further because, weather which role we're going to use we'll get different answers. Which leads to another question: What is the proper role, is it carousel, listbox or anything else?

But to stress the initial question a bit more:
- Shouldn't there an "Slide X of Y" ARIA indicator
- Shouldn't a slide have an `aria-hidden="XXXX"` declaration?
- Shouldn't there an ARIA element around the navigation elements

All in all I'm having [ARIA Live Regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) in mind.

Cheers,
Daniel

**Comment by julmot** [comment]
Daniel, please inspect the DOM. Most of the things you've mentioned are already there, e.g. the live region.

**Comment by bke-daniel** [comment]
Hey again,

I did, it just uses aria-live on the element with the CSS class "swiper-notification". Doesn't it have to be on the parent / root element, the swiper-container itself? Maybe my bad!?
Again, on slides i don't see any `aria-hidden="XXXX"` declarations. I'm using version 3.4.2 via bower, my global swiper options:

    swiperOptions: {
        speed: jQuery.fx.speeds._default,

        autoHeight: false,
        updateOnImagesReady: true,
        lazyLoadingInPrevNext: true,
        centeredSlides: true,

        //ui
        grabCursor: true,

        // pagination
        pagination: '.swiper-pagination',
        paginationClickable: true,

        // arrows
        prevButton: '.swiper-button-prev',
        nextButton: '.swiper-button-next',

        // ARIA
        a11y: true,
        prevSlideMessage: 'Vorheriger Slide.',
        nextSlideMessage: 'Nächster Slide.',
        firstSlideMessage: 'Dies ist der erste Slide.',
        lastSlideMessage: 'Dies ist der letzte Slide.',
        paginationBulletMessage: 'Gehe zu slide {{index}}',
    }

If swiper is perfectly ARIA ready then we'll find and someone can close this ticket! Just wanted to make sure it's the best out there! :)

Cheers

**Comment by sskmscss** [comment]
Did this aria-hidden issue resolved?

**Comment by julmot** [comment]
Don't close.
