### ISSUE TITLE
Incorrect behavior with free width slides with images, specially when calling update().

### ISSUE THREAD

**Issue by akaztp** [nolimits4web/swiper#2170]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: V3.4.2 d9f17789d48a514f63e9d3aef89cfcf121a1536e
* Platform/Target and Browser Versions: CHROME.

### What you did
Horizontal swiper with variable/free width images. The problem only applies in this case where the slides' width must be re-calculated whenever a slide image is loaded because only then the width of the slider is the final one.

Slide config:
```
slidesPerView: 'auto',
centeredSlides: true,
watchSlidesVisibility: true,
preloadImages: true,
```

### Expected Behavior
Moving the slider before all images are loaded, works correctly enabling to swipe/scroll across all already loaded images. Only relevant on slow networks where images load slowly.
Moreover, after all loaded, adding more slides should allow scrolling to the added ones.

### Actual Behavior
Moving the slider before all images are loaded, does not work correctly: slides are not all reachable and active slide is not on center. This gets corrected as soon as all images are completely loaded.
Moreover, after all loaded, adding more slides does not allow scrolling to the added ones.

### Pull Request
I've corrected this and have a PR ready.
https://github.com/akaztp/Swiper/tree/fix-preloadimages

### Remark
Also, on this scenario where all slide content have width set to auto or 100%, sliding while images were loading made the all slider disappear intermittently. This was corrected by adding a `min-width: 2px` to the `swiper-slide` class. The problems seems to arise while any slide have actual zero width. I did not investigate this problem further, thus is not addressed by that PR.

**Comment by DanielRuf** [comment]
I have a smiliar issue. But here the visibility class is not applied due to transitions which are basically race conditions.
