### ISSUE TITLE
Style questions about autoHeight

### ISSUE THREAD

**Issue by ZivGit** [nolimits4web/Swiper#2173]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: macOS / Chrome

### why not do like this:?
`
/* Auto Height */

.swiper-container-autoheight,

.swiper-container-autoheight>.swiper-slide {

height: auto;

}
`

**Comment by nolimits4web** [comment]
You can do it like this
