### ISSUE TITLE
Swiper disappear on IE11

### ISSUE THREAD

**Issue by gosh34** [nolimits4web/swiper#2174]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Windows 10 and IE11.

### What you did
Using simple Swiper for horizontal image gallery.

### Expected Behavior
swiping horizontally on all browsers

### Actual Behavior
swiping horizontally on all browsers but IE11

Is there any issue for SWIPER with Internet Explorer 11.
It does work on all browsers, even on Edge, but not in IE11, the swiper container just disappear.

Any ideas on that?

Thanks!

**Comment by mariosmaselli** [comment]
Do you have any errors?

**Comment by DanielRuf** [comment]
Please provide a codepen to demonstrate the issue.
