### ISSUE TITLE
Disappearing slides when sliding back with coverflow effect

### ISSUE THREAD

**Issue by 93lucasp** [nolimits4web/swiper#2175]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: all browsers.

### What you did
https://codepen.io/93lucasp/pen/VzaOGY

### Actual Behavior
When you slide back and the slide with id="8" is in the middle all the slides on the left disappeared

**Comment by wsjscss** [comment]
And this bug appear only when use Coverflow + loop: true

**Comment by RicoLiu** [comment]
same issue as [https://github.com/surmon-china/vue-awesome-swiper/issues/358](https://github.com/surmon-china/vue-awesome-swiper/issues/358)

**Comment by RicoLiu** [comment]
@aMUSiC Have u solved this bug?
