### ISSUE TITLE
observeParents doesn't appear to work in IE10

### ISSUE THREAD

**Issue by gabrielzzarate** [nolimits4web/Swiper#2178]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 3.4.1
* Platform/Target and Browser Versions: IE10

var swiperEventsReelPhotos = new Swiper('.events-swiper-reel', {
  centeredSlides: true,
  initialSlide: 1,
  slidesPerView: 'auto',
  paginationClickable: true,
  nextButton: '.next-reel',
  prevButton: '.prev-reel',
  spaceBetween: 0,
  observer: true,
  observeParents: true,
  loop: true,
  pagination: '.pagination-reel'
});

### What you did
Tested in IE10 and the slider is broken (won't switch slides at all)

### Expected Behavior
I expect to be able to have the parent of the slider be display: none by default, then display: block and have the swiper work as expected

**Comment by DanielRuf** [comment]
Observers are not supported in IE10

http://caniuse.com/#feat=mutationobserver
