### ISSUE TITLE
Loading image and play slider when reach viewport, lazy Loading

### ISSUE THREAD

**Issue by casper66m** [nolimits4web/Swiper#2182]
Hi, Thanks for great work, My site have multiple slider one in bottom , one in middle and one in top.
For website performance I want middle slider and bottom slider load image and play when user scroll to them ( slider loads and play image when reach viewport), How I implement this?
Thank you again

**Comment by nolimits4web** [comment]
Not related to Swiper. https://www.google.ru/search?q=lazy+loading+images+on+website&oq=lazy+loading+images+on+website&aqs=chrome..69i57.7464j0j1&sourceid=chrome&ie=UTF-8

**Comment by nolimits4web** [comment]
Swiper lazy loads only for load in active/inactive slides
