### ISSUE TITLE
rtl swiper-scrollbar-drag 'jumps' to the left

### ISSUE THREAD

**Issue by serbol** [nolimits4web/Swiper#2183]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS 
macOS, browser Chrome

### What you did
set this configurations:
...
scrollbar: '.swiper-scrollbar',
scrollbarHide: false,
scrollbarDraggable: true
...
and added dir="rtl" to element with class name - "swiper-container"

### Expected Behavior
To be able to swipe with scrollbar from right to left

### Actual Behavior
When I start to swipe with scrollbar from right to left swiper-scrollbar-drag 'jumps' to the left!

**Comment by serbol** [comment]
link to example: https://jsfiddle.net/7yc6xzko/

**Comment by serbol** [comment]
Please, help me. I need to fix it for one arabic project

**Comment by delblues** [comment]
I have the same issue. Can't use swiper, as it's keep going back from left, when I swipe right->left.

**Comment by nolimits4web** [comment]
Fixed in v4
