### ISSUE TITLE
Swiper stops at second slide

### ISSUE THREAD

**Issue by fritzmg** [nolimits4web/Swiper#2186]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: `3.4.2`.
* Platform/Target and Browser Versions: _any_.

### What you did
See the jsfiddle here: https://jsfiddle.net/tdqshh67/1/

### Expected Behavior
Swiper should automatically slide through all slides.

### Actual Behavior
Swiper stops at the second slide.

**Comment by fritzmg** [comment]
The cause seems to be
```json
speed: 0
```
Using a `speed` of `>0` works around the problem.

**Comment by nolimits4web** [comment]
Closing as looks like solved
