### ISSUE TITLE
Breakpoint-specific effects

### ISSUE THREAD

**Issue by ekesto** [nolimits4web/swiper#2189]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: any

### First of all: Thank you so much for all your efforts, Vladimir! 

Analysing a swiper image gallery on a project, our team just had a discussing about how a "slide" effect feels much more native on mobile devices, whereas a "fade" effect is the smoothest and least eye-disturbing solution for desktop devices.

I know that breakpoint-specific effects are not supported at the moment, but are there plans in the pipeline to add this feature in a future release?

Or does anyone has experience with a workaround on this topic?

**Comment by nolimits4web** [comment]
There only way here at the moment is to destroy swiper and reinit it with another effect

**Comment by ekesto** [comment]
Appreciate your feedback. Thanks for the input!
