### ISSUE TITLE
Auto return to slide 1

### ISSUE THREAD

**Issue by LarkinAngel** [nolimits4web/Swiper#219]
Is it possible to have the swiper return to the first slide when user is done swiping?

**Comment by spidernik** [comment]
it goes to first slide as soon as it reaches to last slide. how can I able click on last slide(if it has link).

I tried with `onTap` event and it triggers well with `isEnd`, but it always slide to +1 index when I used `slideTo` function
```    
            var swiper = new Swiper('.swiper-container', {
                nextButton: '.swiper-button-next',
                prevButton: '.swiper-button-prev',
                slidesPerView: 1,
                onTap: function(swiper){
                    if(swiper.isEnd){
                        swiper.slideTo(0,1000,true); //it will slide to second slide
                     //swiper.slideTo(1,1000,true); // it will slide to third slide
                    }
                },
            });
```
I simply need rewind functionality after last slide.
