### ISSUE TITLE
Scrollbar not showing correct position when loop is true

### ISSUE THREAD

**Issue by presidentnickson** [nolimits4web/Swiper#2191]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: **3.4.2**
* Platform/Target and Browser Versions: **all**

### What you did
Setup a very basic example of swiper with loop set to true. Here is the jsfiddle example : https://jsfiddle.net/1vsnLqu1/

### Expected Behavior
Scrollbar to be in fully left position on slide 1, fully right position on last slide

### Actual Behavior
Scrollbar shows 1 position away from left on load, and then shows fully to the right when you slide through to the first slide.

**Comment by nolimits4web** [comment]
Same as #2315
