### ISSUE TITLE
No change when lazyLoading enabled

### ISSUE THREAD

**Issue by k3j** [nolimits4web/swiper#2192]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: macOS & Chrome 60.0.3112.101

I have set preloadImages to false and lazyLoading to true and I can't get lazy loading to work. Here is my swiper init:

 ```
   var modelImgSwiper = new Swiper('.js-product-image-swiper', {
      direction: 'horizontal',
      autoHeight: true,
      loop: false,
      pagination: '.swiper-pagination',
      paginationClickable: true,
      preloadImages: false,
      lazyLoading: true
    });
```

All photos in my slideshow are being preloaded, I don't see any other steps in the documentation so I'm not sure what I'm missing here. I noticed in the lazyload demo that the swiper images have a class of swiper-lazy but that didn't help either.

**Comment by Anderson-Vasques** [comment]
@k3j Don't you forgot using data-src instead src in your images tags?
