### ISSUE TITLE
Beta v1: Custom Next / Prev Buttons Don't Work

### ISSUE THREAD

**Issue by julmot** [nolimits4web/Swiper#2196]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.0.0-beta.1
* Platform/Target and Browser Versions: Windows 10, Firefox latest

### What you did
Specified a `nextButton` or `prevButton` selector or HTMLElement.

### Expected Behavior
Should act like the corresponding button.

### Actual Behavior
Doesn't add any events.

**Comment by nolimits4web** [comment]
The API has changed. At the moment you may refer to the v4 demos https://github.com/nolimits4web/Swiper/tree/v4/demos 

Example of specifying nav buttons https://github.com/nolimits4web/Swiper/blob/v4/demos/14-nav-arrows.html#L83-L85
