### ISSUE TITLE
scrollbar bug on version 4 beta

### ISSUE THREAD

**Issue by WebKieth** [nolimits4web/Swiper#2201]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.0.0 beta
* Platform/Target and Browser Versions: linux ubuntu 16.04, latest chrome

hi, I install latest version of swiper from npm (npm i swiper --save) to init custom horizonatal scrollbar. npm gave me a beta 4.0.0 - after config writing (just pasted from example and change direction on default horizontal, but vertical don't work too) i was confused by bug with custom scrollbar. Wrapper start working, but .swiper-scrollbar was not detected by library and swiper-scrollbar-drag with mousewheel control wasn't work. 
I repair this, when saw beta version into my package.json and installed 3.4.2

**Comment by nolimits4web** [comment]
v4 has different API (not yet documented) check the v4 demos https://github.com/nolimits4web/Swiper/blob/v4/demos/13-scrollbar.html
