### ISSUE TITLE
slide changes on vertical swipe 

### ISSUE THREAD

**Issue by ebgranger** [nolimits4web/swiper#2202]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: iOS 10.3, iphone 5

### What you did
Our swiper is embedded in a Vue app.

### Expected Behavior
I would expect the swiper to only swipe horizontally. We're not sure what else to try.

### Actual Behavior
When I swipe vertical, or tap, the swiper-slide-active class is applied to the next element(gif included below). This happens a lot when we hit the bottom too. 

![swiperbug](https://user-images.githubusercontent.com/4431706/30173769-d49d1b3e-93c6-11e7-8aa7-b11b41df084f.gif)

To replicate you can head to this URL: https://internet.frontier.com/?lp=5300

1. Enter in an address of:
        East 12th Ave
        Tampa, FL 33605
2. Click continue, and you should be on the swiper in the gif.

**Comment by thomaslein** [comment]
@ebgranger did you find a solution for this? Have the same problem in my react app.

**Comment by ebgranger** [comment]
@thomaslein I've been in a holding pattern on this until I hopefully hear back from the main contributors.

**Comment by nolimits4web** [comment]
Is it still actual? As it looks like there is an another slide on the site

**Comment by ebgranger** [comment]
@nolimits4web yes we removed the swiper as a part of our testing but we may feature a swiper in the future. @thomaslein do you have a current production example? 

I might be able to rig up something in a codepen it's just not my main priority at the moment.

**Comment by thomaslein** [comment]
@ebgranger No I dont. But I should be able to revert the project in git so I can reproduce the problem.
