### ISSUE TITLE
Swiper loads and executes without error, but rendered content is broken.

### ISSUE THREAD

**Issue by kneeki** [nolimits4web/Swiper#2203]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Mobile browsers, currently working in Chrome

### What you did
Downloaded swiper from this repo
Copied the entire extracted folder to my assets/libs
Included the .js and .css, copied and the setup code from [the demo](https://github.com/nolimits4web/Swiper/blob/master/demos/05-slides-per-view.html)
Placed the code in my `<div class="hidden-md hidden-lg"></div>` for mobile layouts only.
Refreshed the page and experienced disappointment.

Here is a [pastebin](https://pastebin.com/B6Ba3e3T) of the rendered HTML.

### Expected Behavior
That Swiper loads the content correctly, and works as described.

### Actual Behavior
![image](https://user-images.githubusercontent.com/1012169/30243067-fc5436b2-953d-11e7-92b3-d5c50ddf3eb7.png)

**Comment by nolimits4web** [comment]
Swiper must be initialized when it is visible!
