### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by bdebever** [nolimits4web/Swiper#2204]
Hi guys, 

I am using the latest version and trying to import it using ES6 syntax: 
`import` Swiper from "swiper";`

I have the slider working, but it sounds like the whole is not working: pagination is not working, responsiveness neither. 

Have you some recommendation for that? I can't find any doc on that. 

Thanks. 

* Platform/Target and Browser Versions: Chrome on macOS

**Comment by nolimits4web** [comment]
V3 doesn’t support ES modules. You can use v4 beta for this

**Comment by bdebever** [comment]
Thanks for your answer - any way to install it using npm?

**Comment by hacknug** [comment]
@bdebever v4.0.0-beta2 is already the latest published version on npm: https://www.npmjs.com/package/swiper
