### ISSUE TITLE
Loop on multirow

### ISSUE THREAD

**Issue by stratio84** [nolimits4web/swiper#2205]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 3.4.2.
* Platform/Target and Browser Versions: Windows, Chrome

### What you did
I'm trying to implement a swiper showing elements on 2 rows and 3 columns and I would like it to loop.

Here's my configuration:

swiper = new Swiper('.swiper-container', {
    pagination: '.swiper-pagination',
    slidesPerView: 3,
    slidesPerColumn: 2,
    paginationClickable: true,
    slidesPerColumnFill: 'row',
    slidesPerGroup: 6,
    spaceBetween: 50,
    loop: true
});

### Expected Behavior
I would like the swiper to loop.

### Actual Behavior
The loop is not working well, it doesn't show all the elements and it doesn't loop at all when swiping right.

If I set just one row (slidesPerColumn to 1) it works fine so I think I'm missing some config elements or maybe there could be a bug when using multirow and loop.

Do I miss any configuration?

Do I have to specify the fields 'loopedSlides' or 'loopAdditionalSlides' or other fields inside the config?

Thanks for all the help.

Thanks,

Gianpiero.

**Comment by stratio84** [comment]
Hello everybody, I'm using Swiper 3.4.2 on Windows.

I'm trying to implement a swiper showing elements on 2 rows and 3 columns and I would like it to loop.

Here's my configuration:

swiper = new Swiper('.swiper-container', {
                pagination: '.swiper-pagination',
                slidesPerView: 3,
                slidesPerColumn: 2,
                paginationClickable: true,
                slidesPerColumnFill: 'row',
                slidesPerGroup: 6,
                spaceBetween: 50,
                loop: true
            });

However the loop is not working well, it doesn't show all the elements and it doesn't loop at all when swiping right.

If I set just one row (slidesPerColumn to 1) it works fine so I think I'm missing some config elements or maybe there could be a bug when using multirow and loop.

Do I miss any configuration?

Do I have to specify the fields 'loopedSlides' or 'loopAdditionalSlides' or other fields inside the config?

Thanks for all the help.

Gianpiero.

**Comment by xiangxingliyan** [comment]
I also, when the automatic cycle will stay in the last one，Use v2.7.6 can be resolved, but I do not want to do so
