### ISSUE TITLE
Swiper4 seems cannot be compressed by webpack UglifyJs plugin

### ISSUE THREAD

**Issue by teamen** [nolimits4web/Swiper#2206]
Error below occurred when I tried to compress swiper4 via Webpack3 build-in UglifyJs plugin).

```
ERROR in scripts/lion_6a64ded940eb84148718.js from UglifyJs
Unexpected token: name (i) [scripts/lion_6a64ded940eb84148718.js:6536,6]
```

**Comment by bumbella** [comment]
I have same problem.
I use laravel and production crash this error

**Comment by bumbella** [comment]
3.4.2 version is ok Webpack build uglify

**Comment by nolimits4web** [comment]
You are probably including ES-next version of swiper. If you use it with imports you need to use something like `babel-loader` or import correct version:
`import Swiper from 'swiper/dist/js/swiper.js';`

**Comment by CarlosSouza** [comment]
I was using just `import Swiper from 'swiper';` and  I can confirm that `import Swiper from 'swiper/dist/js/swiper.js';` solved the issue for me.

**Comment by moisespio** [comment]
Yes, adding the absolute-like path fixed the issue :)

**Comment by Phalconline** [comment]
Didn't help me =(
package.json
`"swiper": "=>4.0.2"`
js code:
`import Swiper from 'swiper/dist/js/swiper.js'`
error:
`scripts/main_93aa9e33.js from UglifyJs
Unexpected token: name (w) [scripts/main_93aa9e33.js:20173,4]
`

**Comment by devanflaherty** [comment]
@Phalconline :
I tried running everything as you did but still getting the same exact error.

Can you tell me what you mean by you added swiper to exclude?

I'm afraid if I can't get this to run I'm going to have use a different slider.

**Comment by Phalconline** [comment]
@devanflaherty 
yep, on webpack config add next:

`
module: {
    rules: [
      {
        test: /\.js$/,
        exclude: [/(node_modules|bower_components)(?![/|\\](swiper))/],
        use: [
          { loader: 'cache' },
          { loader: 'buble', options: { objectAssign: 'Object.assign' } },
        ],
      }
`

**Comment by devanflaherty** [comment]
Saved my butt. Thanks man.

**Comment by ashen9** [comment]
@Phalconline  Did you resolve this problem, i meet the same problem like you
 Unexpected token: name (w) [./node_modules/swiper/dist/js/swiper.esm.bundle.js:15,0]

**Comment by Phalconline** [comment]
@ashen9 yep, look below, just exclude swiper `exclude:` [/(node_modules)(?![/|\\](swiper))/],'

**Comment by DanielRuf** [comment]
It should be `exclude: /node_modules\/(?!(dom7|swiper)\/).*/,` per the docs.

**Comment by DanielRuf** [comment]
But this does not solve the issue at all when used with the es2015 preset.

**Comment by DanielRuf** [comment]
At least template literals are not transpiled by default. `Unexpected character \'`\''`

**Comment by DanielRuf** [comment]
Does anybody know the needed babel plugins and presets to compile the esm version?
