### ISSUE TITLE
cannot use slidesPerGroup and slideTo simutaneously

### ISSUE THREAD

**Issue by yuqy** [nolimits4web/Swiper#2208]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Chrome  60.0.3112.113

### What you did
I have 10 images. aim to show 3 images in one slide. In some cases, I hope swiper can scroll to the 2nd slide automatically. This is how I initialize swiper:
```
 var swiper = new Swiper('.swiper-container', {
        slidesPerView: 3,
        slidesPerGroup: 3,
    });
swiper.slideTo(1);  // hope to scroll to the 2nd slide.
```
however, slideTo method doesn't work at all.
### Expected Behavior
scroll to the 2nd slide.

### Actual Behavior
no scroll happens.

P.S. 
also set initialSlide to swiper also not work if slidesPerGroup is set.

**Comment by nolimits4web** [comment]
It is designed behavior. If you have `slidesPerGroup:3` then you can slideTo to slides with indexes: 0, 3, 6, ..etc
