### ISSUE TITLE
Freemode + Mousewheel - breaks loop functionality and smooth scrolling

### ISSUE THREAD

**Issue by nailsiddeeq** [nolimits4web/swiper#2210]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions:  Windows

`var mySwiper3 = new Swiper ('#column-1', {
		    	// Optional parameters
			    direction: 'vertical',
			    loop: true,
			    speed:500,
			    spaceBetween: 20,
        		   centeredSlides: true,
        		   mousewheelControl: true,
        		   slidesPerView: 'auto',
        		   freeMode: true,
        		   freeModeMomentum: true,
        		   mousewheelSensitivity: 0.02,
        		   simulateTouch: true
		  	}); 

		  	var mySwiper4 = new Swiper ('#column-2', {
		    	// Optional parameters
			    direction: 'vertical',
			    loop: true,
			    speed:1000,
			    spaceBetween: 20,
			    centeredSlides: true,
        		    slidesPerView: 'auto',
        		   freeMode: true,
        		   freeModeMomentum: true,
        		   mousewheelSensitivity: 0.02,
        		   simulateTouch: true
		  	}); 

		  	mySwiper3.params.control = mySwiper4;
		  	mySwiper4.params.control = mySwiper3;`

[see here](https://jsfiddle.net/7t4s1hz4/l)

It works perfectly when I drag with mouse or swipe; however, using the mouse-wheel with free-mode breaks the loop functionality entirely and the scrolling is very choppy. I've tested this in FF and Chrome on Windows 10 with the same results.

I've tried playing with mousewheelSensitivity - smaller values make the slides move in smaller increments, as such its less choppy but progression is too slow; however, that seems to fix the loop functionality. If it were possible to somehow accumulate some inertia after each mouse-wheel trigger that would pretty much do the trick I think.

What can I do to achieve the same experience as swiping and dragging with mousewheel as well?

Thanks!

**Comment by StickNitro** [comment]
I got the same issue, is there any update on this?

My issue is with Mouse Wheel and Touch Swipe, my config is below:

swiperConfig: SwiperConfigInterface = {
        direction: "vertical",
        slidesPerView: 5,
        centeredSlides: true,
        loop: true,
    keyboardControl: true,
    mousewheelControl: true,
    mousewheelForceToAxis: true,
    mousewheelReleaseOnEdges: false,
    freeMode: true,
    freeModeSticky: true
    };

When is swipe or mouse wheel the swiper gets stuck at the boundary of the loop until I swipe or mouse wheel again

Would be great to get an update on this?
