### ISSUE TITLE
Prev / Next arrows on click not adding swiper-button-disabled

### ISSUE THREAD

**Issue by RachnaChohan** [nolimits4web/Swiper#2211]
I would like the next arrow to be disabled on the last slide 
& 
the previous arrow to be disabled on the first slide

This is working on swipe gesture on the slide and when clicking on the bullets within the pagination.
BUT
When clicking on the arrow and getting to the last or first slide the arrows are not adding the swiper-button-disabled class. Therefore it still is showing.

AS WELL AS
When you load the page the previous arrow should be disabled cause its on the first slide. 

How can I achieve this ?

**Comment by nolimits4web** [comment]
It works fine in latest version
