### ISSUE TITLE
LazyLoad not working with .setWrapperTranslate

### ISSUE THREAD

**Issue by eparisio** [nolimits4web/Swiper#2219]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows, Chrome

### What you did
LazyLoad image is not working with the .setWrapperTranslate() followed by a .update(true)
The images are nor loaded.

### Expected Behavior
Images are loaded, as the pagination counter updates the current slide position

### Actual Behavior
https://codepen.io/eparisio/pen/OxmOGx
move the slide with the mouse to see that the images will be loaded

**Comment by nolimits4web** [comment]
Lazy not called on setWrapperTranslate, just add `swiper.lazy.load()` after you call `update`
