### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by wiedikerli** [nolimits4web/Swiper#222]
Console from Chrome DevTool:
Uncaught TypeError: Cannot set property 'innerHTML' of undefined --> jquery.swiper.js:1787
_this.createPagination --> jquery.swiper.js:1787
makeSwiper --> jquery.swiper.js:2070
Swiper --> jquery.swiper.js:2083
$.fn.swiper --> jquery.swiper.js:2341

Init:

`````` javascript
$(function () {
     var mySwiper = $('.swiper-container').swiper({
       mode: 'horizontal',
       loop: false,
       pagination: '.my-pagination'
     });
});```
``````

**Comment by myfocus** [comment]
我也碰到了汗。。。

**Comment by huanghui8030** [comment]
@myfocus  需要手动添加分页的html就可以解决了。
