### ISSUE TITLE
swiper 4.0.0 beta pagination not working

### ISSUE THREAD

**Issue by e1111o** [nolimits4web/Swiper#2223]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.0 beta
* Platform/Target and Browser Versions: Mac

https://github.com/nolimits4web/Swiper/blob/master/demos/02-responsive.html

After running `npm install swiper`, I entered the above source and there is a bug that the bullet is not generated in `.swiper-pagination`. I have not been able to install `npm install swiper@3.4.2`.

**Comment by nolimits4web** [comment]
Documentation for v4 will be updated this weekend. Refer to demos for its syntax https://github.com/nolimits4web/Swiper/blob/master/demos/030-pagination.html
