### ISSUE TITLE
Demo source code github links are wrong

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [nolimits4web/Swiper#2226]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Not exactly a bug with swiper itself but with the demo site.

From here http://idangero.us/swiper/demos/ clicking any of the "Source Code" links takes you to a 404.

Example
Links for default setup is:
https://github.com/nolimits4web/Swiper/blob/master/demos/01-default.html

should be:
https://github.com/nolimits4web/Swiper/blob/master/demos/010-default.html

**Comment by nolimits4web** [comment]
It is because website hasn't been update to v4 docs and demos yet. You can refer to v3 demos at https://github.com/nolimits4web/Swiper/tree/Swiper3/demos

**Comment by StraightOuttaCrompton** [comment]
Sweet, just making sure you were aware!

**Comment by nolimits4web** [comment]
Docs updated
