### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by DQvsRA** [nolimits4web/Swiper#2228]
Don't know why but it's looks like pagination does not work. 
Please check.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 4.0.0 (latest from npm)
* Platform/Target and Browser Versions: CHROME

![image](https://user-images.githubusercontent.com/442111/31281578-2cb928da-aab0-11e7-8931-cfe2a503d720.png)

**Comment by nolimits4web** [comment]
> Before you open an issue, please check if a similar issue already exists or has been closed before.

#2223
