### ISSUE TITLE
Navs & pagination bug in 4.0 version

### ISSUE THREAD

**Issue by Margaret0106** [nolimits4web/Swiper#2230]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

I'm using your plugin in every project, but today, after installing new 4.0 version, I was disapointed, because navs and pagination were broken.  Whole hour I was looking for problem and then realesed that it is a new version of plugin. Old version is OK. Please, fix this!

**Comment by nolimits4web** [comment]
> Before you open an issue, please check if a similar issue already exists or has been closed before.
