### ISSUE TITLE
Fade effect stops working on ajax load

### ISSUE THREAD

**Issue by mariosmaselli** [nolimits4web/Swiper#2233]
So I have the following

```
initSlider()

initSlider() {

		this.mySwiperSlider = new Swiper ('.header-slider-container', {
		    loop: true,
		    pagination: '.myswiperslider-pagination',
		    paginationClickable: true,
		    autoplay: 3000,
		    effect: 'fade',
		    fade: {
	             crossFade:true
	           }

		})
	}
```

This is working and it fades in out. 

But the problem comes when I load another page (ajax) that is using Swiper so instead of using the fade effect then starts sliding. Not sure why... Everything works slides and nav also works is just the effect that changes.

Any idea how can I fix this ? 

Demo: hollandgreenuk.staging.wpengine.com/location/oxfordshire-architects

On first load works.. then you click on another page that has Swiper slider (another location for example) And the effect goes away (starts sliding). Hope the demo helps to understand

Thanks a lot!

**Comment by nolimits4web** [comment]
Looks like you are trying to init same slider multiple times. Make sure you destroy previous one if use same slider container before init new one

**Comment by mariosmaselli** [comment]
I have tried to destroy it but it doesn't work at all...

`this.mySwiperSlider.destroy() `

Plus it gives me an error after second time that I'm changing that page. "this.mySwiperSlider.destroy is not a function"

If I `console.log(this.mySwiperSlider)` now I have two instances of Swiper inside an array` [Swiper, Swiper]`
