### ISSUE TITLE
onInit not called properly

### ISSUE THREAD

**Issue by crtl** [nolimits4web/Swiper#2235]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.0
* Platform/Target and Browser Versions: Chrome, Windows

### What you did
Iterate over a collection of jQuery elements, initialize multiple Swipers with an `onInit`-callback.

```
$(".swiper-container").each(function() {

 var s = new Swiper(this, Object.assign({
    onInit: function(swiper) {
      console.log("swiper.onInit");  //Not called
    }
  }, defaults});
});
```

### Expected Behavior
`onInit`-callback should be called

### Actual Behavior
`onInit`-callback is ignored.

**Comment by xavianaxw** [comment]
The syntax may have changed quite a bit for most of the Swiper options. The examples on http://idangero.us/swiper/ may be only for 3.4.2 whereas you are on 4.0.0

Reference: https://github.com/nolimits4web/Swiper/blob/master/demos/420-custom-plugin.html

```
const swiper = new Swiper('.swiper-container', {
  on: {
    init: function() {
      console.log('init');
    }
  }
} 
```

**Comment by nolimits4web** [comment]
Refer to updated docs http://idangero.us/swiper/api/
