### ISSUE TITLE
lockSwipes is not a function

### ISSUE THREAD

**Issue by crtl** [nolimits4web/Swiper#2236]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.0
* Platform/Target and Browser Versions: Chrome, Windows.

### What you did
Call `swiper.lockSwipes()` after initialization.
```
var s = new Swiper(this, options);
s.lockSwipes();
```

### Expected Behavior
Swipes should be locked

### Actual Behavior
An error is thrown saying that lockSwipes is not defined.

```
Uncaught TypeError: s.lockSwipes is not a function
    at HTMLDivElement.<anonymous> (file.js:80)
    at Function.each (jquery.min.js:2)
    at r.fn.init.each (jquery.min.js:2)
    at file.js:49
    at file.js:243
```

**Comment by depoulo** [comment]
Yup, they released v4 without updating the documentation.

From looking at the source, I got it working like so:

```js
mySwiper.allowSlidePrev = mySwiper.allowSlideNext = false;
mySwiper.update();
```

**Comment by nolimits4web** [comment]
Refer to v4 documentation http://idangero.us/swiper/api/

**Comment by depoulo** [comment]
The linked documentation is still for v3 at the time of this writing, and the download link also still points [to v3|https://github.com/nolimits4web/Swiper/archive/v3.4.2.zip].

My above answer is correct, the v3 documentation is not working with v4.
