### ISSUE TITLE
Importing v4.0.0 into an ES6 module breaks the JS build on IE11

### ISSUE THREAD

**Issue by chansecampbell** [nolimits4web/Swiper#2237]
* [x] bug

* Swiper Version: V4.0.0
* Platform/Target and Browser Versions: IE11 on a Windows machine running 8.1 / 10.

### What you did
```
import Swiper from 'swiper';

class PageProductDetail {
  constructor() {
    this.swiper = new Swiper('.swiper-container', {
        pagination: {
          el: '.swiper-pagination',
          clickable: true,
        },
        a11y: true,
      });
  }
}

export default PageProductDetail;
```
### Expected Behavior
This simplified example above produces a working slider on every browser/machine apart from IE11 on Windows machines. The slider should work as expected on the page.

### Actual Behavior
The imported Swiper library appears to break my JS bundle, breaking all JavaScript on Windows machines using IE11. I'm getting no errors in my console so I feel like something must be breaking the build. I'm using Webpack 2 and babel in this project.

**Comment by nolimits4web** [comment]
Hard to understand if there are no errors. If you are using Webpack try importing UMD version instead:
```
import Swiper from 'swiper/dist/js/swiper.js`;
```

**Comment by chansecampbell** [comment]
@nolimits4web Thanks for your time, this seems to have fixed the issue 👍 🙌
