### ISSUE TITLE
Uncaught TypeError: Controller.LinearSpline is not a constructor

### ISSUE THREAD

**Issue by xavianaxw** [nolimits4web/Swiper#2239]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.0
* Platform/Target and Browser Versions: Any

### What you did
A simple thumbs-gallery

```
this.image = new Swiper(this.el.querySelector('.js-carousel-image'), {
   effect: 'slide',
   speed: 300,
   loop: false,
});

this.type = new Swiper(this.el.querySelector('.js-carousel-type'), {
   effect: 'slide',
   speed: 300,
   loop: false,
   navigation: {
      nextEl: this.controls.next,
      prevEl: this.controls.prev,
   },
});

this.image.controller.control = this.type;
this.type.controller.control = this.image;
```

### Expected Behavior
Both swipers to be able to control the sliding of each other

### Actual Behavior
Error thrown on Google Chrome Debugger

```
Uncaught TypeError: Controller.LinearSpline is not a constructor
    at Swiper$1.getInterpolateFunction (webpack-internal:///23:5029:9)
    at setControlledTranslate (webpack-internal:///23:5044:27)
    at Swiper$1.setTranslate (webpack-internal:///23:5071:7)
    at Swiper$1.setTranslate (webpack-internal:///23:5150:25)
    at self.eventsListeners.(anonymous function).forEach (webpack-internal:///23:300:24)
    at Array.forEach (<anonymous>)
    at eventsArray.forEach (webpack-internal:///23:299:37)
    at Array.forEach (<anonymous>)
    at Swiper$1.emit (webpack-internal:///23:297:17)
    at Swiper$1.setTranslate (webpack-internal:///23:940:10)
```

Not sure if this is a webpack issue or there needs to be some configuration with `alias`.

Any suggestions welcomed!

**Comment by daviddelusenet** [comment]
I'm also experiencing this error.

**Comment by rash2x** [comment]
the same problem.

**Comment by rash2x** [comment]
@daviddelusenet I see the problem if I use Swiper as a module. But if I will add a script in HTML with <script> tag, the problem is fixed.

**Comment by nolimits4web** [comment]
Guys do you use Bable or Buble to transpile it to ES5 when you use it as module? Because the module is in the ES-next syntax

**Comment by daviddelusenet** [comment]
@nolimits4web I use Webpack 3 combined with Babel to compile to ES5.

**Comment by xavianaxw** [comment]
I'm on the same boat with @daviddelusenet Webpack 3 with Babel for ES5 compilation.

**Comment by nolimits4web** [comment]
Looks like problem in compiled code then (in Babel). I just checked it with Rollup + Buble all good. Can you please make just a Swiper compiled code and post it here, or somewhere so i can check?

**Comment by nolimits4web** [comment]
As a workaround you can use UMD build (works with webpack) `import Swiper from 'swiper/dist/js/swiper.js`

**Comment by xavianaxw** [comment]
Hang on. Will do it for you soon-ish

**Comment by chenhaoact** [comment]
`import Swiper from 'swiper/dist/js/swiper.js`

it works，thank you @nolimits4web

**Comment by Uriziel01** [comment]
@nolimits4web Do you still need Swiper compiled by webpack+babel? I can do that for you if it will help to solve the issue.

**Comment by nolimits4web** [comment]
@Uriziel01 yes, will be helpful to see such issue live

**Comment by Uriziel01** [comment]
Indeed the problem seems to be in these two lines:
```js
new Controller.LinearSpline(swiper.slidesGrid, c.slidesGrid) :
new Controller.LinearSpline(swiper.snapGrid, c.snapGrid);
```
Where in fact `LinearSpline` is just a method defined inside `Controller` const, simply removing the `new` from these lines fixes the issue temporarily.

I'll prepare live issue for you but in a few hours I can't do it right now.

[swiper.chunk.js.zip](https://github.com/nolimits4web/Swiper/files/1524724/swiper.chunk.js.zip)

**Comment by Uriziel01** [comment]
@nolimits4web 
I've tried creating jsfiddle demo for this issue but I'm not sure how I can use webpack imports there.
So I've created standalone issue reproduction and I'm attaching it below 😄 

Just open the page and try to mouse move any Swiper.
[swiper #2239.zip](https://github.com/nolimits4web/Swiper/files/1526746/swiper.2239.zip)

**Comment by nolimits4web** [comment]
@Uriziel01 thanks, i've fixed it, fix will arrive in next release. But anyway, it is still recommended to run Babel/Buble over swiper `esm` packages. In this case you won't have this error

**Comment by jeffhuang2086** [comment]
@chenhaoact   你好，想请教一下，你的问题是怎么解决的？
