### ISSUE TITLE
Docs were not properly updated in v4.0.0 (broken pagination).

### ISSUE THREAD

**Issue by meyve** [nolimits4web/Swiper#2242]
* [x] enhancement

* Swiper Version: 4a5084dff1412a3c0b4f8f0bf0c33b1513a1b846

I've looked for similar issues but found only those that were related to broken pagination. Fortunately, it was not broken.
However, I've spent few hours of researching just because the documentation of Swiper v.4.0.0 was not properly updated.
Here are two screenshots so you can see the difference:

v.3.4.2.
![selection_045](https://user-images.githubusercontent.com/19283375/31430242-01b60f50-ae79-11e7-98d4-f6f145f85f50.jpg)

v.4.0.0.
![selection_046](https://user-images.githubusercontent.com/19283375/31430296-235db9e6-ae79-11e7-97e2-3e57d104d919.jpg)

Cheers :)

**Comment by Dizzzy** [comment]
A lot is different in v4, not just the pagination. Navigation, keyboard, mousewheel.. Most of the initialising options are now grouped together in separate objects like this. Callbacks seem to be gone (at least I couldn't find them), replaced by events. Documentation is lagging behind but still this is a fantastic slider, thanks so much for all your work on it!

**Comment by nolimits4web** [comment]
Docs updated
