### ISSUE TITLE
last slide does not receive swiper-slide-active class in auto mode

### ISSUE THREAD

**Issue by alexandere** [nolimits4web/Swiper#2246]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.2 & 4.0.1.
* Platform/Target and Browser Versions: Reproducable in at least: Chrome. Firefox and Edge on Windows 10

### What you did
swiper configured in auto mode, navigate to last slide

### Expected Behavior
last slide receives class swiper-slide-active

### Actual Behavior
if the slide before is still in view, that slide will receive swiper-slide-active class
 
example of behavior: http://idangero.us/swiper/demos/06-slides-per-view-auto.html

**Comment by nolimits4web** [comment]
It is by design. Active slide depends on slider position
