### ISSUE TITLE
“Loop” is not working as expected when roundLengths is set to true

### ISSUE THREAD

**Issue by tantan199** [nolimits4web/swiper#2249]
This is a
* [x] bug

* Swiper Version: 3.4.2 & 4.0.1.

### What you did
var swiper = new Swiper('.swiper-container', {
    autoplay: 1000,
    speed: 2000,
    loop: true,
    slidesPerView: 5,
    slidesPerGroup: 5, 
    spaceBetween: 16,
    roundLengths: true
});

### Expected Behavior
If a slider has 10 slides, then expected behavior is Page1->page2->page1->page2->….

### Actual Behavior
But I got the wrong behavior page1->page2-page1->page1->page1->page1->….

P.S. If you can not reproduce the problem on your side, then set spaceBetween to 15 to try again.

**Comment by apapacy** [comment]
Swiper 3.4.2
`
      slidesPerView: 3,
      slidesPerGroup: 3,
      loop: true,
      roundLengths: true
`
total: 9 slides
loop was broken:
123
456
789
123
123
123
Can this be a loss of accuracy in the division?

**Comment by tantan199** [comment]
That's the same problem as I reported, temporary solution is removing roundLengths:true Hope someone can get the problem fixed.
