### ISSUE TITLE
update API documentation?

### ISSUE THREAD

**Issue by cutelittleturtle** [nolimits4web/Swiper#2251]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [ X] feature-discussion (RFC)

Hi, just wondering if the API documentation could be updated? The demos are the new 4.0.0 style but the API seems still like 3.x.x version. 

Specifically I am looking for `preloadImage:` option, wondering where I should put it :smile:

**Comment by thesublimeobject** [comment]
+1 on this. swiper was recommended to me by a friend, and the configuration options are amazingly dreamy, but given the update this week, i've had a lot of trouble getting it working. i assumed doc updates are in the works, but just wanted to affirm this.

**Comment by jmwohl** [comment]
+1 — the only thing worse than no docs is incorrect docs.

**Comment by ajschmidt8** [comment]
+1. hoping these new docs are ready soon!

**Comment by nolimits4web** [comment]
Updated 🎆
