### ISSUE TITLE
freemode with different widths

### ISSUE THREAD

**Issue by javimata** [nolimits4web/Swiper#2258]
This is a (multiple allowed):
* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.1
* Platform/Target and Browser Versions: macOS, CHROME

### What you did
I wanna do a freemode slide width differents widths of images

### Actual Behavior
I see the slides but all with the same width, so, i have a space between slides slims

**Comment by nolimits4web** [comment]
You need to set `slidesPerView: 'auto'`

**Comment by javimata** [comment]
i have this script

	var swiper = new Swiper('.swiper-container', {
	  slidesPerView: 'auto',
	  spaceBetween: 0,
	  freeMode: true,
	  autoplay: 3000,
	  loop: true,
	  autoHeight: true,
	});

but all images have the same width and leave a space between when adapt the height

http://test.adview.mx/lr/rp
