### ISSUE TITLE
onBeforeResize, onAfterResize in 4.0.1

### ISSUE THREAD

**Issue by exdeniz** [nolimits4web/Swiper#2259]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.1
* Platform/Target and Browser Versions: ALL

### What you did
onAfterResize, onBeforeResize don't work in 4.0.1 and work in 3.4.2

**Comment by capyash** [comment]
Looks like there aren't beforeResize and afterResize events in 4.0.1. The new function is just resize and the new format is

```
 on: {
            init: function(swiper) {
                console.log('init');
            },
            resize: function(swiper) {
                console.log('4.0.1 resize');
            }
        }
```

**Comment by exdeniz** [comment]
Yes, I looked in the source and not found it. But need event onAfterResize for set dynamic param slidesOffsetAfter

**Comment by scott-grav** [comment]
I was never able to get onAfterResize to work in 3.4.2. Are there code examples of how it or simply the onResize method should be used?

**Comment by exdeniz** [comment]
@nolimits4web onAfterResize?

**Comment by scott-grav** [comment]
Sure, either way, I have never gotten it to work and cannot find example code of it working
