### ISSUE TITLE
Zoom out won't work on Windows Chrome

### ISSUE THREAD

**Issue by mateusvelleda** [nolimits4web/swiper#2260]
This is a:
* [x] bug

* Swiper Version: 4.0.1 and lower
* Platform/Browser: Windows 10, CHROME  61.0.3163.100 64 bits

### Bug
We have been testing on every browser / OS and such behavior only occurs on Chrome for Windows. Once an image gets zoomed in, it's not possible to get back to the original size (double click has no effect).
I noticed that unlike other browsers, a mousedown event is triggered instead of a double click event.

**UPDATE:** it looks like the problem is at src\components\zoom\zoom.js:100
swiper.allowClick is getting always false

```
if (!gesture.$imageEl || gesture.$imageEl.length === 0) return;
swiper.allowClick = false;
```

### Expected Behavior
Zoom out as a zoomed image is double clicked

### Actual Behavior
Once the image gets zoomed, it can't get back to the initial scale.

**Comment by gabisanmartin12** [comment]
I have the same problem!
