### ISSUE TITLE
The Navigation Not Work When The Page is Loading by Ajax

### ISSUE THREAD

**Issue by MarkSky** [nolimits4web/Swiper#2261]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.1
* Platform/Target and Browser Versions: Windows 10, Chrome

### What you did
I use fetch API to load a page, and control the pics on the page to slide.

### Expected Behavior
If I click the '.swiper-button-next' and '.swiper-button-prev' buttons, the pics will slide.

### Actual Behavior
When I click the buttons, it doesn't work.
But when I use ther version 3.4.2, it works fine.

**Comment by nolimits4web** [comment]
Make sure you init swiper AFTER its content is presented on page
