### ISSUE TITLE
Loop mode won't show previous slide without interaction + initialSlide doesn't work

### ISSUE THREAD

**Issue by daviddelusenet** [nolimits4web/swiper#2262]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: macOS multiple browsers

### What you did
I'm using Swiper in my React application. I've two sliders which control each other. This is the code I use to set up my Swiper instances: 

```
componentDidMount() {
  this.initSwiperTop();
  this.initSwiperBottom();
  this.initSwiperControls();
}

initSwiperTop() {
  this.swiperTop = new Swiper(this.swiperContainerTop, {
    initialSlide: 0,
    direction: 'vertical',
    loop: true,
    mousewheelControl: false,
    runCallbacksOnInit: false,
    slidesPerView: 'auto',
    loopedSlides: this.props.slides.length,
    autoHeight: true,
    onSlideChangeStart: (swiper) => this.onSlideChangeStart(swiper),
    onSlideChangeEnd: (swiper) => this.onSlideChangeEnd(swiper)
  });
}

initSwiperBottom() {
  this.swiperBottom = new Swiper(this.swiperContainerBottom, {
    initialSlide: 0,
    direction: 'vertical',
    loop: true,
    mousewheelControl: false,
    slidesPerView: 'auto',
    loopedSlides: this.props.slides.length,
    slideToClickedSlide: true,
    autoHeight: true
  });
}

initSwiperControls() {
  this.swiperTop.params.control = this.swiperBottom;
  this.swiperBottom.params.control = this.swiperTop;
}
```

### Expected Behavior
I expect it to look like this: 
![screen shot 2017-10-18 at 09 39 05](https://user-images.githubusercontent.com/1398418/31706149-3f33a85a-b3e8-11e7-9e2f-bfd1af2ba290.png)

Instead, it looks like this:
![screen shot 2017-10-18 at 09 39 08](https://user-images.githubusercontent.com/1398418/31706178-545ccc70-b3e8-11e7-8701-78bf604707e7.png)

After you have any interaction with the slider it changes to the correct styling. Also (I don't know if this is related) setting initialSlide to any other value than 0 doesn't work.

### Actual Behavior
You can see the actual behaviour here: http://preview.momkai.com/

**Comment by JackCA** [comment]
I am experiencing the exact combination of issues as well
