### ISSUE TITLE
Webpack Production Bundling fails because of UglifyJS Error with Dom7

### ISSUE THREAD

**Issue by martinherweg** [nolimits4web/Swiper#2263]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.1.
* Platform/Target and Browser Versions: -

### What you did
I have installed Swiper as normal dependency in my Project and import it to my scripts file like this `import Swiper from 'swiper';` 
If I try to bundle it to a production ready version with webpack i get this error

```ERROR in js/vendor.a8b881e4dc98829fb5c4.js from UglifyJs
Unexpected token: name (Dom7) [./node_modules/dom7/dist/dom7.modular.js:14,0][js/vendor.a8b881e4dc98829fb5c4.js:36577,6]

ERROR in js/vendor.a8b881e4dc98829fb5c4.js from UglifyJs
Unexpected token: name (Dom7) [./node_modules/dom7/dist/dom7.modular.js:14,0][js/vendor.a8b881e4dc98829fb5c4.js:36577,6]
```

as soon as I downgrade Swiper to version 3.4.2 everything works as expected.

### Expected Behavior
Bundling and compression via webpack is working

### Actual Behavior
UglifyJS throws an error because of dom7

**Comment by nolimits4web** [comment]
Make sure you have enabled Bable or Buble for Swiper ES-module to transpile it from ES-next syntax

**Comment by martinherweg** [comment]
@nolimits4web I use ES6 syntax in my own code and use babel-loader to compile.
I use babel-preset-env in my .babelrc but it's still not working.

**Comment by nusson** [comment]
"I've downgraded to v3.4.2 and the problem went away."
https://github.com/JeffreyWay/laravel-mix/issues/1244

**Comment by daviddelusenet** [comment]
@nolimits4web can you share a working webpack config?

**Comment by daviddelusenet** [comment]
I fixed this by removing the following line: `exclude: /node_modules/,` from my Webpack config.

@nolimits4web distributing Swiper as an ES6 module is wrong in my eyes. Now during compilation Webpack has to search through my entire `node_modules` folder to look for ES6 modules. Can you please provide an ES5 version of Swiper?

**Comment by nolimits4web** [comment]
Well, there is probably kind of option to look only in `node_modules/swiper`. The reason why i keep it in ES6 is the tree-shaking. It just doesn't work properly with ES5-syntax modules.

You may then just include UMD version of swiper which is in ES5: `import Swiper from 'swiper/dist/js/swiper.js';`

**Comment by martinherweg** [comment]
Maybe we can use the `include` option in loaders to just include swiper.

@nolimits4web How do you do it in Projects where you need to compile everything down to ES5?

**Comment by nolimits4web** [comment]
I don't say it should not be compiled to ES5, it must be. The bundle package must be compiled. But keeping Swiper module is in ES6 syntax is a mandatory for tree-shaking to work. For example, if it is in ES5 syntax then:
```js
import { Swiper, Pagination } from 'swiper/dist/js/swiper.esm.js';` 
```
Will still keep all other modules you don't need in your bundle

**Comment by deasmahaputra** [comment]
what is this?

**Comment by daviddelusenet** [comment]
Ok guys I managed to fix it. Just use the normal Swiper import method:

`import Swiper from 'swiper';`

Then in your Webpack config add the following part:

```
module: {
  rules: [
    {
      test: /\.js$/, // Check for all js files
      exclude: /node_modules\/(?!(dom7|swiper)\/).*/,
      loader: 'babel-loader'
    }
  ]
}
```

This excludes all `node_modules` from your `babel-loader` but includes `dom7` and `swiper`.

**Comment by DanielRuf** [comment]
https://github.com/nolimits4web/Swiper/issues/2263#issuecomment-339924563

Unfortunately it seems this is not enough. What is your babel-preset that you use and do you have a .babelrc and what are its contents?

**Comment by daviddelusenet** [comment]
@DanielRuf I'm using the following Babel configuration

```
{
  "presets": [
    ["env", {
      "modules": false, // webpack understands the native import syntax and uses it for tree shaking
      "targets": {
        "browsers": ["last 5 versions", "safari >= 7"]
      },
    }],
    "react" // transpile React components to JavaScript
  ],
  "plugins": ["transform-class-properties"],
  "env": {
    "dev": {
      "plugins": [
        "react-hot-loader/babel", // enables React code to work with HMR
        ["react-css-modules", {
          "context": "./src",
          "generateScopedName": "[local]___[hash:base64:5]",
          "filetypes": {
            ".scss": {
              "syntax": "postcss-scss"
            }
          }
        }]
      ]
    },
    "prod": {
      "plugins": [
        ["react-css-modules", {
          "context": "./src",
          "generateScopedName": "[local]___[hash:base64]",
          "filetypes": {
            ".scss": {
              "syntax": "postcss-scss"
            }
          }
        }]
      ]
    }
  }
}
```

**Comment by DanielRuf** [comment]
Hm, does not work here =/

**Comment by xx4159** [comment]
I did like this...
It also works!

```javascript
import * as Swiper from 'swiper/dist/js/swiper.js';
...
... new Swiper(swiperContainer, this.options) ...
...
```

**Comment by DanielRuf** [comment]
Well, this is the compiled dist file and not the esm version or the source version ;-)

**Comment by Giovanni-Mattucci** [comment]
@xx4159 I used your method as I'm using typescript, and it worked for me :)
Better than scanning for Dom7 and Swiper in my `node_modules` folder. 
I couldn't use a regex like this `exclude: /node_modules\/(?!(dom7|swiper)\/).*/` in my `tsconfig.json`.

**Comment by charlespernet** [comment]
Hey guys just sharing my experience here, I am new to WebPack with rails and i spent time struggling to figure out where to add config shared by daviddelusenet.

I you have a classic Rails 5.1 config you should probably have a `config/webpacker.yml` file.
This file is loaded by `config/webpack/environment.js` which should look like : 

```
const { environment } = require('@rails/webpacker');
module.exports = environment;
```

In case you want to add config, just add a file in webpack folder, in my case I added `swiper_config.js` with this code : 

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/, // Check for all js files
        exclude: /node_modules\/(?!(dom7|swiper)\/).*/,
        loader: 'babel-loader'
      }
    ]
  }
};
```

then you have to edit your `environment.js` or `production.js` (if you want this config only for production) to look like this : 

```
const { environment } = require('@rails/webpacker');
const swiperConfig = require('./swiper_config');

environment.config.merge(swiperConfig);

module.exports = environment;
```

Hope this could help so newbies like me starting with Webpack. 
By the way Swiper is fantastic ! Thanks to people contributing, and special thanks to @daviddelusenet for sharing his solution.

**Comment by wujunchuan** [comment]
### to sum up:
Swiper4.x module is in ES6 syntax in order for tree-shaking to work.
Due to my environment **is not include babel translater**
use UMD version of swiper which is in ES5 work for me: 
`import Swiper from 'swiper/dist/js/swiper.js';`

**Comment by maximelebreton** [comment]
Can somebody could provide a `.babelrc` config version (i'm using Parcel)?

Thanks!

**Comment by daviddelusenet** [comment]
`.babelrc`:

```
{
  "presets": [
    ["@babel/preset-env", {
      "useBuiltIns": "usage",
      "targets": {
        "browsers": [
          "> 5%",
          "last 2 versions",
          "not ie < 11",
          "ios_saf >= 10.2"
        ]
      }
    }],
    "@babel/preset-react"
  ],
  "plugins": ["transform-class-properties"],
  "env": {
    "dev": {
      "plugins": ["babel-plugin-styled-components", "react-hot-loader/babel"]
    }
  }
}
```

`webpack.base.js`:

```
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
        use: 'babel-loader',
      },`
      // Some more loaders here..
    ],
  },
```

**Comment by zhangliqq** [comment]
![2 n 9 0 05jxx u vz gw_q](https://user-images.githubusercontent.com/23396290/47498284-60c13d80-d88f-11e8-864a-3ccba950d75a.png)
![glt3b guj6rc7 woe ybknp](https://user-images.githubusercontent.com/23396290/47498528-17bdb900-d890-11e8-9853-230898b3fa9d.png)

These are not solutions to the problem.
I don't sure the problem is from swiper and it occurred  only when  I build my project.  The problem is .call()  con't  resolve.....sorry  it's  difficult to describe it.
![cx a y bw w6g ok jc f_q](https://user-images.githubusercontent.com/23396290/47498248-4d15d700-d88f-11e8-98e9-27dd4869fa21.png)

**Comment by modestotech** [comment]
I've had swiper working for many months with the following setup:

webpack.config.json
``` javascript  
module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
        use: 'babel-loader',
      },
      {
// more loaders
}
```

.babelrc
```json
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

Now for some reason it stopped working. It might be when I started renaming files containing jsx to jsx format, and there for changed the test clause to `test: /\.js$/,`. It can also be some dependency that I've updated I suppose. 

Does anyone know of something that has changed in the last months and that may have caused this? That would save some time for me not having to pinpoint the problem. Few people are using IE so it takes some time before the alarm arises.

**Comment by DanielRuf** [comment]
> When I run `ll | grep dom7` in `node_modules` I get one folder named `dom7`.
> Was that what you requested, @DanielRuf ?

Was any dependency updated like webpack or babel-loader or swiper itself? In general it should be locked using yarn.lock / package-lock.json to get reproducible builds.

**Comment by DanielRuf** [comment]
Probably do selective updates and do some bisecting which dependency produces this issue (I guess babel-loader).

**Comment by DanielRuf** [comment]
`yarn` / yarn.lock is often better.

**Comment by ViieeS** [comment]
why just don't include?

rules: [{
    include: [
    path.resolve(__dirname, 'src'),
    /node_modules\/(dom7|swiper)/
  ],
  loader: 'babel-loader',
  presets: [['@babel/preset-env', {
  'modules': false
  }]]
},
  test: /\.(js)$/
}]

**Comment by ViieeS** [comment]
Looks like [TerserPlugin](https://webpack.js.org/plugins/terser-webpack-plugin/) doesn't have such problem. So you don't need to include `dom7|swiper` in your config.

**Comment by bsudeep** [comment]
> Looks like TerserPlugin doesn't have such problem. @ViieeS

Thank you!

**Comment by vertic4l** [comment]
@ViieeS How is this possible? Still got issues with IE11, although latest webpack + TypeScript is being used. Any ideas?

**Comment by DanielRuf** [comment]
> Any ideas (**without babel-loader**...)?

You have to transpile it for browsers.

**Comment by vertic4l** [comment]
@DanielRuf how? 

tsconfig looks like this:

```
"module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "target": "es5",
    "lib": [
      "es2015",
      "dom",
      "es2017"
    ],
```

or do you mean the mainFields settings in the `resolve` part of webpack?

**Comment by vertic4l** [comment]
Why does the tree-shaking not work? @nolimits4web @DanielRuf 
What's missing?

```
use: {
    loader: "babel-loader",
        options: {
            presets: ["@babel/preset-env"],
            compact: true,
        }
    }
```

```
import { Swiper, Virtual, Zoom, Lazy, SwiperOptions, SelectableElement } from "swiper/dist/js/swiper.esm.js";
```

**Comment by slorber** [comment]
@nolimits4web I understand that:
- you want treeshaking to work for ES users
- according to the readme, user is responsible for handling the lib transpiling if he wants to consume ES modules and support older browsers (IE11/Edge)


But:
- You can keep treeshaking and yet transpiling the lib in advance
- You don't need to ask user to setup transpiling
- This package is only for the web, so not transpiling is just annoyance for all webpack consumers with no advantage

Let's take a popular package, like Redux. 

https://unpkg.com/redux@4.0.4/es/redux.js

You can see in the original source code a modern syntax with const/let/rest/spread and ES6 modules. Yet in the published ES module, you can see an older syntax, but still ES6 modules.

This package works with treeshaking, and does not require webpack users to add any additional config. 


Wouldn't it be better if all those issues about uglify / ie / edge failing were not opened because consuming your libs would be easier? Most web users expect to not have to transpile node_modules when installing a lib, and will likely not even read your readme entirely.
