### ISSUE TITLE
Gaps to the left of slides on Chrome for Windows

### ISSUE THREAD

**Issue by sdelpuerto** [nolimits4web/swiper#2268]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2 (tested on 4.0.2 and it happens aswell)
* Platform/Target and Browser Versions: Windows 10 - Chrome 62
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/BwMxWX

### What you did
Create a full width swiper.

### Expected Behavior
There are no gaps between slides

### Actual Behavior
On Windows, using Chrome and when the window width is bigger than (approximately) 2000px, there are gaps between slides on the left. Those gaps disappear when reducing the window size.

Screenshot for reference:

![swiper-bug](https://user-images.githubusercontent.com/25384839/31884522-a6c2ed88-b7ed-11e7-8386-37aaee344390.png)

#### Update 1:

I found this only happens when using the "slide" effect, which is the default. Changing it to any other fixes it, but that's far from a solution.

#### Update 2:

This doesn't happen on the last slide when `loop: false`.

**Comment by nolimits4web** [comment]
Does it happen only on Windows + Chrome? Fine in other browsers?

**Comment by sdelpuerto** [comment]
Yes, it's fine even on Internet Explorer. It doesn't happen on Chrome for Mac. Haven't tested on Linux though. I'm pretty sure it's a render issue. Do you have any idea what might be causing it?

**Comment by nolimits4web** [comment]
Can’t check right now as I don’t have access to windows at the moment.  It if you inspect slide in Chrome inspector does it show it highlight it like there is no gap? If yes then rendering issue

**Comment by sdelpuerto** [comment]
Yes, the whole slide is highlighted. The element has `style="width: 2560px"`, which is my screen size, so it doesn't seem to be a CSS or JS issue.

**Comment by sdelpuerto** [comment]
I updated the issue to include a screenshot, please check it out.

**Comment by nolimits4web** [comment]
Thanks will check it

**Comment by lettgers** [comment]
I also have this problem. Is there a good way to solve it?
