### ISSUE TITLE
Swiper needs window resize to work propperly

### ISSUE THREAD

**Issue by lukasholzer** [nolimits4web/Swiper#2276]
Hey @fabrizim, this is a bug, I am facing the problem that I have one *main Slider* and a second slider that is *navigating the main slider*. My problem is that I always have to **resize** the window, so that the swiper is working propperly.

Therefore is it possible to loop the swipers? – It broke everything when I tried this.

I uploaded a live preview of my problem [here](http://robertholzer.typeflow.cc/).
The files are on this branch [github-swiper-issue-test](https://github.com/lukasholzer/robert-holzer/tree/feature/github-swiper-issue-test) in this [repo](https://github.com/lukasholzer/robert-holzer).

## Versions:
* swiper version: ^3.4.2
* npm version: 5.3.0
* node version: v8.2.1

### The Markup simplified:
The original Markup code is found in this file: [repertoire.twig](https://github.com/lukasholzer/robert-holzer/blob/feature/github-swiper-issue-test/theme/views/repertoire.twig)

```html

<container>
   <swiper-container navigation>
      <swiper-slide></swiper-slide>
      …
   </swiper-container>

   <swiper-container main>
      <swiper-slide></swiper-slide>
      …
   </swiper-container>
</container>

```

### The Javascript code is the following:
```typescript
import { Component, ElementRef } from 'mojiito-core';

@Component({
  selector: '.repertoire'
})
export class RepertoireComponent {

  private static NAV_CONTAINER = 'nav.swiper-container';
  private static WORK_CONTAINER = 'main.swiper-container';

  private navMobile = document.querySelector('.mobile-navigation') as HTMLSelectElement;
  private navigation: Swiper;
  private works: Swiper;

  constructor(private elementRef: ElementRef) {

    this.initSwipers();
    this.navMobile.addEventListener('change', (event: Event) => {
      this.navigation.slideTo(parseInt(this.navMobile.value));
    });
  }

  initSwipers() {

    this.works = new Swiper(RepertoireComponent.WORK_CONTAINER, {
      mousewheelControl: true,
      mousewheelForceToAxis: true,
      mousewheelInvert: true,
      autoHeight: true,
      slidesPerView: 'auto',
    });

    this.navigation = new Swiper(RepertoireComponent.NAV_CONTAINER, {
      spaceBetween: 10,
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      mousewheelControl: true,
      keyboardControl: true,
      touchRatio: 0.2,
      slideToClickedSlide: true,
      onSlideChangeStart: () => {
        this.navMobile.selectedIndex = this.navigation.activeIndex;
      }
    });

    this.works.params.control = this.navigation;
    this.navigation.params.control = this.works;

  }

}
```

**Comment by fabrizim** [comment]
Hi @lukasholzer - I haven't been working with this library in quite some time, so, unfortunately, I'm won't be able to help with this.  FWIW, it looks like its working for me in Chrome; you should include the browser(s) where you see this failing for better help debugging.

Best of luck-
Mark

**Comment by nolimits4web** [comment]
If
> Swiper needs window resize to work propperly

Then you init it in a wrong time. It must be initialized when it is visible. Otherwise call its `.update()` method when it becomes visible. Or try to enable `observer` params
