### ISSUE TITLE
4.0.2 API / DOC 

### ISSUE THREAD

**Issue by katerlouis** [nolimits4web/Swiper#2277]
It seems that the new version isn't represented correctly in the API / DOCS.

For instance:
http://idangero.us/swiper/api/#pagination

renderBullet parameter `index` gives me the actual `className` and the third parameter is `undefined` in the return.

Another example:
![image](https://user-images.githubusercontent.com/1983382/31943700-cf73218a-b8c9-11e7-9bbe-8d3d391e361d.png)
`mySwiper.on("onTransitionEnd")` why is there another "on" only on "transitionEnd" and not "transitionStart" aswell?
this doesn't seem consistent and I bet this is unintended :D

One more:
`mySlider.on("changeSlideTransitionStart" ..)` works.
`mySlider.on("init", )` doesn't – for init callbacks I needed to go the `on: { init: { ... } }` route.

I hope you could clarify my confusements :)
Thank you.

**Comment by teolaz** [comment]
Inspecting the source code, seems also we passed from
```javascript
autoplay: {
    delay: 3000
}
```
to
```javascript
autoplay: 3000
```

and also from
```javascript
pagination: {
    el: '.aaa'
}
```
to
```javascript
pagination: '.aaa'
```

What's going on?

**Comment by nolimits4web** [comment]
@teolaz everything about Autoplay and Pagination parameters is correct in docs at http://idangero.us/swiper/api/

**Comment by nolimits4web** [comment]
Docs updated

**Comment by nolimits4web** [comment]
@katerlouis `mySlider.on("init", )` won't work because you add this code AFTER swiper initialization, so should be added within `on` parameters

**Comment by katerlouis** [comment]
One more inconsistency:
events `autoplayStart` and `autoplayStop` are entirely absent from the docs–
