### ISSUE TITLE
Can't focus on the last slide

### ISSUE THREAD

**Issue by sean-hill** [nolimits4web/Swiper#2278]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.2
* Platform/Target and Browser Versions: Chrome
* [Live link](http://idangero.us/swiper/demos/120-slides-per-view-auto.html)

### What you did
With [this demo](http://idangero.us/swiper/demos/120-slides-per-view-auto.html) I can't focus slide 10, even if you click on the pagination.

### Expected Behavior
I expect to be able to focus slide 10 and have it's left edge against the left side of the parent container.

### Actual Behavior
Slide 10 is not able to be focused.

**Comment by nolimits4web** [comment]
Was fixed in 4.0.3
