### ISSUE TITLE
Last page does not become active when using multi row swiper

### ISSUE THREAD

**Issue by marwej** [nolimits4web/Swiper#2280]
This is a (multiple allowed): bug

* Swiper Version: 4.0.2
* Platform/Target and Browser Versions: macOS, Chrome

### What you did
Multi row Swiper with 4 column and 2 rows. `slidesPerGroup` is the same as number of columns. Total number of slides is 11 which gives us 2 pages (but not filling the last page).

### Expected Behavior
When swiping to the second (last) page I expect the second bullet to become active. The second page is not a complete page though, but includes 4 slides from the first page.

### Actual Behavior
First bullet is still active.

<img width="1458" alt="page1" src="https://user-images.githubusercontent.com/5296840/31998231-512e891a-b98f-11e7-9da5-e554ab2b039d.png">

<img width="1431" alt="page2" src="https://user-images.githubusercontent.com/5296840/31998230-510a71ba-b98f-11e7-8c7b-3d9c4a67c8e9.png">

**Comment by nolimits4web** [comment]
Should be fixed in latest release
