### ISSUE TITLE
Swiper 4.0.2 as ES module not working on IE10 & IE11

### ISSUE THREAD

**Issue by gramulos** [nolimits4web/Swiper#2282]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.2
* Platform/Target and Browser Versions: Internet Exproler 10 and 11.
* Error image: https://imgur.com/a/lb9Eh

### What you did
I'm using swiper as ES module importing it from 'swiper/dist/js/swiper.esm.js'. Everything works fine in Chrome, Safari, Firefox, Opera, Edge browsers except IE10 & IE11.

Here example of usage:
```
import { Swiper, Pagination } from 'swiper/dist/js/swiper.esm.js';
Swiper.use([Pagination]);
const mySwiper = new Swiper('.swiper_horizontal', {
  loop: true,
  slidesPerView: 'auto',
  loopedSlides: 4,
  pagination: {
    el: '.swiper-pagination',
  },
});
```

### Expected Behavior
Work normally as in other brothers.

### Actual Behavior
Breaks swiper with the console error: SCRIPT1003: Expected ':'
On click this error it opening 'swiper.esm.js' and showing line 23.

**Comment by nolimits4web** [comment]
Swiper ES module should be transpiled with Babel or Buble to ES5 syntax

**Comment by latviancoder** [comment]
@nolimits4web this task is not trivial. I had to explicitly add swiper and dom7 libraries to my babel-loader configuration and also use "transform-exponentiation-operator" plugin. 

I don't think I have ever encountered another npm library that does the same. You could consider transpiling on your end.

**Comment by coonmoo** [comment]
I just run into the same issue on IE11 :/

**Comment by geekdada** [comment]
@nolimits4web I think you're wrong.

See https://github.com/webpack/webpack/issues/2902#issuecomment-241608119

**Comment by sebastian-naicker** [comment]
Hey Guy's,
Also had this issue, maybe it should be mention-able that this is an issue for guys using the npm package version of this library. As this is not something extremely obvious.

I have solved the above issue, by simply using the below in my `webpack.config.js`:
```
module: {
    rules: [
      {
        exclude: [/node_modules\/(?!(swiper|dom7)\/).*/, /\.test\.jsx?$/],
        test: /\.jsx?$/,
        use: [{ loader: 'babel-loader' }],
      }
    ],
  }
```

Note that I'm using react in my project, so you can ignore the `.jsx` tests.

**Comment by eassymo** [comment]
@sebastian-naicker your comment helps, basically the npm "swiper" package, has modern javascript declarations that IE does not support, i removed npm "swiper" package (i'm ussing angular) and just imported the required files (swiper.min.js and swiper.min.css), error gone.

(We are not ussing nolimits4web package, we were ussing "npm install swiper")

**Comment by rsurjano** [comment]
so, how I should configure swiper in a angular-cli application? (same scenario above)

**Comment by daviddelusenet** [comment]
@nolimits4web it's quite frustrating that EVERYONE who uses the ES module thinks this is shit, still you think you're doing the world a favour. Please just fix this issue and make this library great again.
