### ISSUE TITLE
noSwipingClass preventClicks Not Working on 4.x

### ISSUE THREAD

**Issue by skyliwq** [nolimits4web/Swiper#2284]
noSwipingClass preventClicks Not Working on 4.x Because the project requires these two function to ask you for help

**Comment by MaxInMoon** [comment]
Seems related to these PR?:

https://github.com/nolimits4web/Swiper/pull/2285

https://github.com/nolimits4web/Swiper/pull/2279

**Comment by nolimits4web** [comment]
Fixed #2279
