### ISSUE TITLE
Request: onStartAutoplay & onStopAutoplay events

### ISSUE THREAD

**Issue by katerlouis** [nolimits4web/Swiper#2286]
I am doing some things with lots of code which only should happen while autoplay is running. 
Hooking stuff to events such as `onStartAutoplay` and `onStopAutoplay` would be a huge improvement.

What do you say?

**Comment by katerlouis** [comment]
Just looked into the code trying to implement it myself.. 
found out it is already implemented with `autoplayStart` and `autoplayStop`.
But there is no sign of that in the docs– please fix the docs!

**Comment by nolimits4web** [comment]
Added to docs
