### ISSUE TITLE
4.0.3 - dynamic pagination - tiny bug when thier only two slides

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [nolimits4web/Swiper#2289]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.0.3
* Live Link: https://codepen.io/ezra_siton/pen/vebqbd
### Actual Behavior
Slider with - Two slides - thier is some bug with the **style** (when **slide 1/2 active** --> **bullet 2/2** looks cut - overflow)

**Comment by Ezra-Siton-UIX** [comment]
Thanks

**Comment by asso1985** [comment]
Problem is still present on 4.1.6
