### ISSUE TITLE
s.wrapper.transition is not a function

### ISSUE THREAD

**Issue by routinet** [nolimits4web/Swiper#2291]
Saw #1246 and #1410.  I am receiving very similar error with simple demo page:

`Uncaught TypeError: s.wrapper.transition is not a function
    at Swiper.s.setWrapperTransition (swiper-3.4.2.js:2188)
    at HTMLDocument.Swiper.s.onTouchMove (swiper-3.4.2.js:1675)`

Just downloaded the libraries this evening.  Structure is from one of your demo pages.  I have tried initializing "straight" and with jQuery.

Can see live at http://bit.ly/2lrFbBJ

**Comment by routinet** [comment]
Due to no input, I reverted back to Swiper 3.3.1 as found in a demo on a third-party site.  After reproducing their config by scraping the scripts, I was finally able to get it to work, with and without jQuery.

Also, the navigation buttons did not work after reverting.  I used the solution put forward in https://github.com/nolimits4web/Swiper/issues/1317#issuecomment-161328375.

**Comment by nolimits4web** [comment]
3.x version is not supported anymore. I can recommend you to use 4.x
