### ISSUE TITLE
[4.0.3] - loop `swiper-slide-duplicate-*` classes not consistent across slides

### ISSUE THREAD

**Issue by Uriziel01** [nolimits4web/Swiper#2292]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.0.3

### What you did
Used `loop` option that should add duplicate classes for slides.
Code:
```js
let settings = {loop:true};
new Swiper(this, settings);
```

### Expected Behavior
Each duplicated slide should have class `swiper-slide-duplicate` and additionally another `swiper-slide-duplicate-*` class depending at the duplicated slide type.

### Actual Behavior
Active duplicated slide has both `pon-swiper-slide-duplicate` and `swiper-slide-duplicate-active` classes where next/prev slides have only `swiper-slide-duplicate-prev` without `swiper-slide-duplicate` class. This leads to more difficult DOM selectors if one wants to target all duplicated slides.

**Comment by Uriziel01** [comment]
![image](https://user-images.githubusercontent.com/568207/32170634-974a2672-bd75-11e7-86a0-657b67b9ca2c.png)

**Comment by nolimits4web** [comment]
Everything is correct here. `swiper-slide-duplicate-prev` and `swiper-slide-duplicate-next` may be duplicated slides or not. This classes assigned to slides which are duplicated copies (in this case it will also have `swiper-slide-duplicate` class) or original of duplicated copies (in case not)

**Comment by DanielRuf** [comment]
> Everything is correct here. swiper-slide-duplicate-prev and swiper-slide-duplicate-next may be duplicated slides or not. This classes assigned to slides which are duplicated copies (in this case it will also have swiper-slide-duplicate class) or original of duplicated copies (in case not)

But how do you in CSS know then which of these are the ones that should be visible?
