### ISSUE TITLE
swiper stopAutoplay while changing the browser tabs 

### ISSUE THREAD

**Issue by cvaraj** [nolimits4web/Swiper#2296]
HI @nolimits4web 
swiper stop autoplay while we  changing browser current tab to another tab, it was stopped  autoplay is there any solution for this

**Comment by nolimits4web** [comment]
You may use Page Visibility API to stop it when user switch to another tab and enable it again when use comes back to tab with Swiper https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
