### ISSUE TITLE
iPad Crash + Add and remove slides dynamically

### ISSUE THREAD

**Issue by df-fady** [nolimits4web/Swiper#230]
Hi,
I am using Swiper in my Web App as an HTML container with multiple slides (30 slides).
Each slide contains complex HTML.
On the desktop everything is working fine, but when i try the Web App on the iPad, and after swiping multiple times through slides, the app is crashing.
I believe it is a memory issue.
I managed to add and remove slides dynamically from Swiper while swiping and the app is working fine now on iPad, but i lost the animation effects.
Does Swipper has a "Buffer" parameter to only hold, let's say 3 slides at the same time in the DOM, and the other slides will be hidden or located in a DIV outside Swiper.
The above behavior, "Buffer", is the one adopted by "Sencha Touch" carousel.

Thank you.

**Comment by ClancyHood** [comment]
We fixed this by commenting out all the -webkit-transforms in the css
