### ISSUE TITLE
Event lazyImageReady firing early

### ISSUE THREAD

**Issue by diegocerdan** [nolimits4web/Swiper#2300]
* This is a: bug
* Swiper Version: 4.0.3
* Browser: Chrome
* URL with issue: http://arrayate.com/fotos/navidad/papa-noel-te-necesita/

### What you did
Slides have lazy loaded images. 
Move to a slide with the image still loading. 
When imagen finish loading the size is wrong.

![swiper_wrong_size](https://user-images.githubusercontent.com/1403537/32261341-1d290070-bece-11e7-847d-5ef466c772f0.png)

So I want to recompute size at event lazyImageReady but it fires to early:
```javascript
on: {
    lazyImageReady: function() {
        this.updateSize();
        console.log("fired too early");
    }
} 
```

### Expected Behavior

Is expected that lazyImageReady event fires once lazy image is loaded.

**Comment by nolimits4web** [comment]
Everything is correct, i don't see any issues on link. And this event is fired when image has been loaded (as you can see at https://github.com/nolimits4web/Swiper/blob/master/src/components/lazy/lazy.js#L63 it is within `loadImage` callback)
