### ISSUE TITLE
Multiple Swipers: Nav buttons in one Swiper trigger other Swipers without nav buttons

### ISSUE THREAD

**Issue by Visiluna** [nolimits4web/Swiper#2302]
This is a bug.

* Swiper Version: 4.0.3
* Platform/Target and Browser Versions: Currently developing/testing on MacOS 10.12.6 with Safari 11
* Here's a [CodePen](https://codepen.io/visiluna/pen/eepGQP) demonstrating the issue.

### What you did
I added multiple `.swiper-container`  elements to the same page. Some have navigation buttons, some do not.

### Expected Behavior
Navigation buttons should control only the `.swiper-container` element which contains them. `.swiper-container` elements which do not include navigation buttons should not be affected by other `.swiper-container` elements that include navigation buttons.

### Actual Behavior
Any `.swiper-container` element which does not include its own navigation buttons receives navigation events from any other `.swiper-container` element that include navigation buttons. `.swiper-container` elements that include navigation buttons do not appear to be affected by the navigation buttons in other `.swiper-container` elements.

**Comment by nolimits4web** [comment]
It is correct behavior because Swiper supports navigation elements outside of swiper-container.
