### ISSUE TITLE
Error when destroying Swiper when clicking on a slide

### ISSUE THREAD

**Issue by marwej** [nolimits4web/Swiper#2304]
This is a (multiple allowed):
[x] bug

* Swiper Version: 4.0.3
* Platform/Target and Browser Versions: Chrome/macOS

### What you did
I use Swiper as icons for navigation in my app. I have click listener on my icon/slide that will do navigation and also destroy the Swiper (the react component is unmounted). 

### Expected Behavior
The Swiper disappears and leaves no trace. Did work fine in version 3.

### Actual Behavior
There is a `click` event fired in Swiper after 300ms but at that time the Swiper is gone. Thus, an Error is thrown. 

```
index.js:2177 TypeError: Cannot read property 'click' of undefined
    at swiper.js:1097
    at Array.forEach (<anonymous>)
    at Swiper.emit (swiper.js:1096)
    at swiper.js:2647
```

**Comment by julmot** [comment]
Have the same thing.
