### ISSUE TITLE
[Question] Is it possible to combine 2 types of transitions?

### ISSUE THREAD

**Issue by aviramga** [nolimits4web/Swiper#2305]
Hi, Sorry for asking this here but I couldn't get an answer in the forum or SO.

Is there an easy way to combine 2 types of slide effects?
My page is divided into 2 sides and I would like each side to slide with a different effect.

Thanks!

**Comment by nolimits4web** [comment]
No it is not possible

**Comment by aviramga** [comment]
Ok thanks, are there examples how to set a custom slide effect? all the examples I find are related to old versions with outdate api
