### ISSUE TITLE
Fix for slideTo with slidesPerView

### ISSUE THREAD

**Issue by LoicHa** [nolimits4web/Swiper#2308]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows , Chrome

### What you did
This is the fix for the method slideTo with sliderPerView and sliderPerGroup

Replace 
**s.snapIndex = Math.floor(slideIndex / s.params.slidesPerGroup);**

with

**s.snapIndex = Math.floor(slideIndex / (s.params.slidesPerGroup*s.params.slidesPerView));**

**Comment by nolimits4web** [comment]
If you want to send a fix, it must be done with PR. And make sure your fix is for latest version
