### ISSUE TITLE
No swiping class is not respected with version 4+

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/Swiper#2310]
`swiper-no-swiping` class is not respected
- This is a bug
- Swiper Version: 4.0.3
- Platform/Target and Browser Versions: Windows 10, Google Chrome 62.0.3202.75 (64 bit)
- Live website with issue: http://idangero.us/swiper/ (You can add the `swiper-no-swiping` class to any element within the Swiper and the setting will be ignored.)

**Comment by nolimits4web** [comment]
Fixed with #2279
