### ISSUE TITLE
Free mode with different widths and height

### ISSUE THREAD

**Issue by javimata** [nolimits4web/Swiper#2311]
I wanna do a freemode slide with images with different widths, and in some cases differente height

i do it adapt the height with this:
`
alto = $( window ).height();
$(this).height(alto - 140);
`

but the width is the same and have spaces between the slide, how can i adjust the width and the height in a freemode slider?

i have the example here: http://test.adview.mx/lr/mercado

the script are:
`
		var swiper = new Swiper('.swiper-container', {
			slidesPerView: 'auto',
			spaceBetween: 0,
			freeMode: true,
			autoplay: 3000,
			loop: true,
			mousewheel: true,
			keyboard: true,
			initialSlide: 0,
			speed: 900,
			preloadImages: true,
			updateOnImagesReady: true
`

**Comment by nolimits4web** [comment]
This is how CSS works, and you have `width:100%` for `.swiper-slide` in styles, you need to overwrite it
