### ISSUE TITLE
Swiper effect issue on loop

### ISSUE THREAD

**Issue by Mosata** [nolimits4web/Swiper#2312]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.3
* Platform/Target and Browser Versions: Windows/Chrome 62.0.3202.89 (Official Build) (64 bit) version
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/wPzvGM

### What you did
After the 2nd loop has started, the 2nd slide has an error in the effect.This is a bug or my fault?

### Expected Behavior
Work without effect error.

**Comment by nolimits4web** [comment]
This is because of the nature of loop, it has duplicated slides, don't use `:nth-child` selectors here to set slide's width, use classes like "width-60", "width-40", .etc.
