### ISSUE TITLE
activeIndex is not working in transitionEnd event on swiper last slide.

### ISSUE THREAD

**Issue by amitchoubey** [nolimits4web/Swiper#2313]
I am trying to get activeIndex on swiper transitionEnd but on last slide I am not able to receive correct activeIndex of slide.

I tried with following code with latest swiper version.

var swiper1 = new Swiper('.swiper1', {
				pagination: {
				  el: '.swiper-pagination1',
				}, 				
				slidesPerView: 1.3,
				paginationClickable: true,
				on: {
					transitionEnd : function(){            	 			 
							console.log("Swiper1 transitionEnd :: "+swiper1.activeIndex );
					}
				}
                       }

Can you help me to resolve this issue.

**Comment by nolimits4web** [comment]
It is by design, as active index depends on position

**Comment by amitchoubey** [comment]
@nolimits4web can you please tell me how to then find correct value of last slide on transition end.

**Comment by amitchoubey** [comment]
@nolimits4web waiting for your reply?
