### ISSUE TITLE
Swiper 4.05 | loop=true & scrollbar tiny bug

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [nolimits4web/Swiper#2315]
First, the scrollbar is a very cool feature.

This is a:
* [x] bug

* Swiper Version: 4.05

* Live Link Codepen:
https://codepen.io/ezra_siton/pen/vebqbd

### What you did
set `loop: true`, & `scrollbar: { el: '.swiper-scrollbar' }`, I dont know if this is reasonable combination (If not - maybe add some node in the docs).

### Actual Behavior
The scrollbar does not align correctly now (Like in "loop: false" mode). See codepen

**Comment by nolimits4web** [comment]
It is by design. Scrollbar is not supported with `loop` mode

**Comment by Ezra-Siton-UIX** [comment]
Ok. Thanks
