### ISSUE TITLE
Delay between slides

### ISSUE THREAD

**Issue by undfnd** [nolimits4web/Swiper#2316]
Hello,

Is there a way to add a delay between the slides? Something like this (it doesn't work):

<pre>.swiper-slide { transition-delay: 500ms }</pre>

Thank you!
Daniel

This is a (multiple allowed):
* [ ] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.5

**Comment by nolimits4web** [comment]
No, it is not possible
