### ISSUE TITLE
Swiper not working, all slide move to left

### ISSUE THREAD

**Issue by mrtuvn** [nolimits4web/Swiper#2318]
### What you did
I have intergrated swiper lib as slider in my magento 2 extension. Used swiper v4.0.3

### Expected Behavior
Slide not working, i can't see any transition or move slide. All slide image move to left

When i see in chrome devtools i found swiper-slide element apply inline style
like this 
   ```
 width: 920px;
    opacity: 0.652174;
    transform: translate3d(-320px, 0px, 0px);
```
Here is screenshot 
![issues](https://user-images.githubusercontent.com/1908873/32588132-3997438a-c53f-11e7-8f2a-fb967134ed38.png)
My Js  file for initial swiper . See content file [here](https://pastebin.com/raw/N4eUmw2w). Magento 2 js init by requireJS
How to fix this problem?. I checked everywhere and i think this problem related to swiper lib js

**Comment by nolimits4web** [comment]
Looks like you are still using v3 api. Also provide a live example please

**Comment by klihelp** [comment]
Review the 'pagination' option.

**Comment by mrtuvn** [comment]
Thanks guy. I found reason my problem. My css swiper wasn't loaded so it cause this problem

**Comment by nolimits4web** [comment]
Yes, it supports AMD and RequireJS
