### ISSUE TITLE
Multiple Swipers move at the same time with onTouchStart

### ISSUE THREAD

**Issue by KevinPy** [nolimits4web/Swiper#2320]
* Swiper Version: 3.3.1.
* Platform/Target and Browser Versions: Angular 4+.

### What you did
I created multiple swipers with same config. All swipers are the same numbers of columns.

```
<swiper [config]="config">
    <section class="swiper-wrapper">
      <article *ngFor="let article of articles" class="swiper-slide">
        <!--Code-->
      </article>
    </section>
    <div class="swiper-pagination"></div>
  </swiper>

  <!--Code-->

  <section *ngFor="let row of rows">
    <swiper [config]="config">
      <div class="swiper-wrapper">
        <span class="swiper-slide" *ngFor="let col of row.columns">
          <p *ngFor="let detail of col">{{detail}}</p>
        </span>
      </div>
    </swiper>
  </section>
```

```
this.config = {
  slidesPerView: 'auto',
  centeredSlides: true,
  pagination: '.swiper-pagination',
  paginationClickable: true
};
```

### Expected Behavior
I wish to when touch a Swiper (any of them), all swipers move at the same time (like keyboardControl).

### Actual Behavior
Actually, when I touch a swiper for move, the swiper works, but others Swipers don't move.

**Comment by nolimits4web** [comment]
This is not possible by default. Check the Controller API http://idangero.us/swiper/api/#controller and this demo https://github.com/nolimits4web/Swiper/blob/master/demos/300-thumbs-gallery.html
