### ISSUE TITLE
Swiper 4.0.x uses dedicated variables of javascript, it makes problems in larger projects

### ISSUE THREAD

**Issue by ed0ras** [nolimits4web/Swiper#2323]
Hey,

in the first, I have to say Swiper 4.0 is great, I would like to thank you for your work.

We use Swiper in a larger project, with links to the older javascript code, and we have some problems with version 4.0 because you use reserved javascript variables, such as "static" and "in", which you then overwrite in your code and it makes problems.

Do you plan to solve this in the future?

Thank you

**Comment by nolimits4web** [comment]
Where does it use such variables?

**Comment by ed0ras** [comment]
Just for example, on the line 1173 you using "static" and 5513 is "in".

**Comment by nolimits4web** [comment]
On the line of which file?

**Comment by nolimits4web** [comment]
These are object properties, not separate variables, they are not reserved
