### ISSUE TITLE
Loop mode won't execute click event

### ISSUE THREAD

**Issue by superkuanggithub** [nolimits4web/swiper#2325]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper-3.4.2
* Platform/Target and Browser Versions: Windows7 Chrome & Firefox

### What you did
    //Initialize Swiper
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        spaceBetween: 30,
        loop:true
    });

### Expected Behavior
There is <p>element in the Swiper. And I add a click event for it with jquery.

### Actual Behavior
But when Swiper moving from the first item to the last item (or from the last to the first), the click event dosen't work. [Test Project Link](https://github.com/superkuanggithub/Swiper-test)

**Comment by jenerse** [comment]
I have the same issue, any solution?

**Comment by Ezra-Siton-UIX** [comment]
Why not update your code to [version 4](http://idangero.us/swiper/)?  (Create codepen to check if you see this problem thier).

**Comment by superkuanggithub** [comment]
@Ezra-Siton-UIX This problem remains the same in version4.

**Comment by superkuanggithub** [comment]
@Ezra-Siton-UIX Thank you for your advice. I add a [test project link](#issue-273652668)

**Comment by lampercy** [comment]
+1

**Comment by weizijian101** [comment]
add eventListener to parent node
