### ISSUE TITLE
Coverflow Effect Weird behaviour in IE11 

### ISSUE THREAD

**Issue by jengz** [nolimits4web/swiper#2329]
Hi,

I am using Swiper 4.0.6 Coverflow Effect

var swiper = new Swiper('.swiper-container', {
      effect: 'cube',
      grabCursor: true,
       direction:'vertical',
      cubeEffect: {
        shadow: true,
        slideShadows: true,
        shadowOffset: 20,
        shadowScale: 0.94,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });

Vertical direction not showing properly in ie 11

**Comment by nolimits4web** [comment]
IE 11 has aweful implementation of 3D transform, let's won't expect much from it
