### ISSUE TITLE
Multiple `swiper`s conflict with `Bootstrap` `tab-pane`s. Only 1st works correctly!

### ISSUE THREAD

**Issue by mynameismosa** [nolimits4web/Swiper#2333]
It's interesting that by putting each Swiper inside a `tab-pane`, only first one works correctly. I tried all possible approaches!  

Is there any solution for this?  

`<div class="clearfix slidingcats">
	<ul class="nav nav-tabs">
		<li class="active"><a data-toggle="tab" href="#brands">Brands</a></li>
		<li><a data-toggle="tab" href="#categories">Categories</a></li>
	</ul>
	<div class="tab-content">
		<div id="brands" class="tab-pane fade in active">
			<div class="swiper-container swiper_brands">
				<div class="swiper-wrapper">{% for brand in brands %}
					<div class="swiper-slide text-center">{% if brand.link %}<a href="{{ brand.link }}"><img src="{{ brand.image }}" alt="{{ brand.title }}" class="img-responsive" /></a><a href="{{ brand.link }}">{{ brand.name }}</a>{% else %}<img src="{{ brand.image }}" alt="{{ brand.title }}" class="img-responsive" />{% endif %}</div>
					{% endfor %}</div>
			</div>
		</div>
		<div id="categories" class="tab-pane fade">
			<div class="swiper-container swiper_categories">
				<div class="swiper-wrapper"> {% for category in categories %}
					{% if category.products >= 0 %}
					<div class="swiper-slide text-center"> <a href="{{ category.href }}">{% if category.thumb %}<img src="{{ category.thumb }}" class="img-responsive" />{% endif %}</a><a href="{{ category.href }}">{{ category.name }}</a> </div>
					{% endif %}
					{% endfor %} </div>
			</div>
		</div>
	</div>
			<script type="text/javascript"></script> 
</div>
`

**Comment by nolimits4web** [comment]
You must init Swiper when it becomes visible or call its `update()` method when tab with it becomes visible

**Comment by mynameismosa** [comment]
Many many thanks! It worked!
