### ISSUE TITLE
Multiple execution 'destroy' function will be reported wrong

### ISSUE THREAD

**Issue by noney** [nolimits4web/Swiper#2334]
I use swiper on the mobile native app,  Because it supports the drop-down refresh page，So I need to do it multiple times execution 'destroy' function，Then the following error was reported：

Uncaught TypeError: Cannot set property 'paused' of undefined 
Uncaught TypeError: Cannot call method 'transition' of undefined

The code is here

let window.slideObj = null;
if (window.slideObj) {
       window.slideObj.destroy();
       console.log('%c%s', 'color:green', 'destroy');
} 
window.slideObj = new dmSwiper('.swiper-container', {
      centeredSlides: true,
      loop: true,
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
      // spaceBetween: 20,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      preloadImages: true,
      updateOnImagesReady : true
});

Have any Suggestions

Thank you very much

**Comment by nolimits4web** [comment]
Try to call `window.slideObj.autoplay.stop()` before `window.slideObj.destroy();`

**Comment by noney** [comment]
I try to use this method, But it's still a mistake

**Comment by noney** [comment]
if (window.slideObj) {
    window.slideObj.autoplay.stop();
    window.slideObj.destroy();
    console.log('%c%s', 'color:green', 'destroy');
}

@nolimits4web

**Comment by noney** [comment]
This mistake no longer occurs, My current version is 4.0.3, I updated the code to use the latest version 4.0.6, fxied this bug.

thank you very mush @nolimits4web
