### ISSUE TITLE
swiper failed to bundle in react app,help~

### ISSUE THREAD

**Issue by LLily7** [nolimits4web/Swiper#2335]
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/swiper/dist/js/swiper.esm.bundle.js:15

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vedatmahir** [comment]
Have the same thing..

**Comment by DarkChris86** [comment]
Same problem

**Comment by nolimits4web** [comment]
There is section at http://idangero.us/swiper/get-started/

<img width="1141" alt="swiper-esm" src="https://user-images.githubusercontent.com/999588/33077460-f460fd82-cee0-11e7-8b9b-71a5eaf034d0.png">

**Comment by DarkChris86** [comment]
**Hi nolimis4web!**

Tried your recommendation, but unfortunately it doesn't work.

Cheers,
Chris

**Comment by Riprios** [comment]
Hi,

I just installed Swiper to a freshly installed create-react-app, and I receive this exact error, when I tried to 'npm run build'.

Any idea to solve this?

Best regards,
Richard

**Comment by geekwill** [comment]
Same problem, and try the above scheme is invalid

**Comment by geekwill** [comment]
```
alias: {
      swiper$: 'swiper/dist/js/swiper.js',
      dom7$: 'dom7/dist/dom7.js',
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },
```

The above webpack configuration can be resolved, but I'm still a little confused about why.

@Riprios @DarkChris86 @nolimits4web

**Comment by dsc1025** [comment]
`alias: {
      swiper$: 'swiper/dist/js/swiper.js',
      dom7$: 'dom7/dist/dom7.js',
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },`
useful

**Comment by dsc1025** [comment]
> alias: {
      swiper$: 'swiper/dist/js/swiper.js',
      dom7$: 'dom7/dist/dom7.js',
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },

useful

**Comment by wmzhong** [comment]
Just import the swiper with the absolute path.
`import Swiper from 'swiper/dist/js/swiper.js'`
