### ISSUE TITLE
reLoop method

### ISSUE THREAD

**Issue by rjohnep** [nolimits4web/Swiper#2336]
Hello @nolimits4web, 

I've used the "reLoop" method in some my projects, it's really the best way to update duplicated slides. 

Can you help me with updating duplicates in v.4? 

Thank you.

**Comment by nolimits4web** [comment]
It was a shortcut for few methods. You can adopt it from v3 source code https://github.com/nolimits4web/Swiper/blob/Swiper3/src/js/core.js#L2387-L2394
