### ISSUE TITLE
Disable/Enable Swiping

### ISSUE THREAD

**Issue by Bluxart** [nolimits4web/Swiper#2337]
Hi, I tested Swiper Slider for disable the swiping on desktop and renabled it on mobile/tablet via breakpoints, but not work and I don't know if this is a bug.

If resized from desktop -> mobile the swiper not re-enabled the swiping.
Same thing if load the page from 992 ( or below ) the swiping work but when resized the viewport >= 992 the swiping not turned off.

Swiper Version: 4.0.6
Code Example:

```javascript
var footerCarouselSwiper = new Swiper('.footer-carousel-swiper', {
	effect: 'slide',
	slidesPerView: 6,
	spaceBetween: 0,
	loop: true,
	noSwiping: false,
	allowSlidePrev: false,
	allowSlideNext: false,
	speed: 600,
	autoplay: false,
	keyboard: false,
	breakpoints: {

		480: {
			slidesPerView: 1,
			noSwiping: true,
			allowSlidePrev: true,
			allowSlideNext: true
		},

		992: {
			slidesPerView: 3,
			noSwiping: true,
			allowSlidePrev: true,
			allowSlideNext: true
		},

		1024: {
			slidesPerView: 6,
			noSwiping: false,
			allowSlidePrev: false,
			allowSlideNext: false
		}

	}
});
```

Thanks for your help and time!

**Comment by Bluxart** [comment]
I tested with the version 3.4.2 and work. Possible in this new version exist a bug or this feature it removed.

**Comment by Fetzner** [comment]
noSwiping: true, works for me
