### ISSUE TITLE
Swiper v4.0.6 erroring on init in IE10

### ISSUE THREAD

**Issue by ashein** [nolimits4web/Swiper#2339]
I can't seem to find the minimum browser versions Swiper is expected to support, but v3 supported IE10 fine, so I expected v4 to continue with the trend.

Issue type: **bug**
Platform: **Win7 IE10** (tested both with SauceLabs and using local VM)
Website with issue: [official demo page](https://idangero.us/swiper/demos/)

Expected behaviour: page loads, demos work
Actual behaviour: page loads, none of the examples work.

**STR** is simple: fire up IE10, visit the official demo page with console open and you'll see a TypeError on line 3356 in the unminified file. The error pertains to the empty module property. It feels like the object accessor doesn't fire up the component import to the Swiper object on init. I am unable to monkey-patch this on my own, unfortunately.

Feel free to close if IE10 is not supported anymore.

**Comment by dmaus** [comment]
When I try the demos with IE10 (Win7) I get the following error:
`SCRIPT5007: Object.keys: argument is not an Object 
swiper.min.js, line 12 character 48515`

-> swiper.js:
`Object.keys(swiper.modules).forEach(function (moduleName) {...`
This is because swiper.modules is undefined.

**Comment by claverwebdesign** [comment]
Could you pre-compile the package? I would like to use it as swiper.min.js file. 

Thumbs up for the quick fix though!

**Comment by nolimits4web** [comment]
@claverwebdesign will be with next release. Otherwise you can do it by yourself https://github.com/nolimits4web/Swiper#production-build

**Comment by orauch-a** [comment]
Hello,

Can you change your dist/js/moment.js and  dist/js/moment.min.js  ?

You must change :
```
// Swiper Class
// Core Modules
Swiper$1.components = [
  Device$2,
  Support$2,
  Browser$2,
  Resize,
  Observer$1,
  Virtual$1,
  Keyboard$1,
  Mousewheel$1,
  Navigation$1,
  Pagination$1,
  Scrollbar$1,
  Parallax$1,
  Zoom$1,
  Lazy$1,
  Controller$1,
  A11y,
  History$1,
  HashNavigation$1,
  Autoplay$1,
  EffectFade,
  EffectCube,
  EffectFlip,
  EffectCoverflow
];

return Swiper$1;

```
by 

```
var components = [
  Device$2,
  Support$2,
  Browser$2,
  Resize,
  Observer$1,
  Virtual$1,
  Keyboard$1,
  Mousewheel$1,
  Navigation$1,
  Pagination$1,
  Scrollbar$1,
  Parallax$1,
  Zoom$1,
  Lazy$1,
  Controller$1,
  A11y,
  History$1,
  HashNavigation$1,
  Autoplay$1,
  EffectFade,
  EffectCube,
  EffectFlip,
  EffectCoverflow
];

if (typeof Swiper$1.use !== 'undefined') Swiper$1.use(components);
else Swiper$1.Class.use(components);

return Swiper$1;
```

Thanks !

**Comment by orauch-a** [comment]
Hello,

The dist/js/moment.js must be change :
```
if (typeof Swiper$1.use !== 'undefined') Swiper$1.use([
  Device$2,
  Support$2,
  Browser$2,
  Resize,
  Observer$1,
  Virtual$1,
  Keyboard$1,
  Mousewheel$1,
  Navigation$1,
  Pagination$1,
  Scrollbar$1,
  Parallax$1,
  Zoom$1,
  Lazy$1,
  Controller$1,
  A11y,
  History$1,
  HashNavigation$1,
  Autoplay$1,
  EffectFade,
  EffectCube,
  EffectFlip,
  EffectCoverflow
]);
else Swiper$1.Class.use([
  Device$2,
  Support$2,
  Browser$2,
  Resize,
  Observer$1,
  Virtual$1,
  Keyboard$1,
  Mousewheel$1,
  Navigation$1,
  Pagination$1,
  Scrollbar$1,
  Parallax$1,
  Zoom$1,
  Lazy$1,
  Controller$1,
  A11y,
  History$1,
  HashNavigation$1,
  Autoplay$1,
  EffectFade,
  EffectCube,
  EffectFlip,
  EffectCoverflow
]);

return Swiper$1;
```
