### ISSUE TITLE
Display:none swiper

### ISSUE THREAD

**Issue by nicopetremann** [nolimits4web/Swiper#234]
Hello,

I have a problem with swiper. I've had a class "display_none" who has the following style (display:none). I would like to remove this class when a user click on a button. 

On click, the swiper appears but if i don't resize window, it doesn't work...

Jquery : 
$(document).ready(function() {
    var mySwiper = new Swiper('.swiper-container')
    $('#btn_step1').on('click', function(e){
    $("#step3").removeClass('display_none')
  })
  });

Screenshot 

![capture decran 2013-06-25 a 22 46 30](https://f.cloud.github.com/assets/4688417/705531/5d542160-ddd8-11e2-8aa5-6cea80fe13bb.png)

If you can help me .. I've tried to reInit Swiper but it doesn't work ...

Thanks

**Comment by mytharcher** [comment]
No `resizeFix()` and `reInit()` method in latest code (v3.07). And still can't initialize the right size when the container is not displaying.

I noticed that in `updateContainerSize()` method, you are not using `.width()` and `.height()`. If change to the jQuery dimension method, it could get the width and height from css rules. I am not sure if there is any risk to change. Or I can send a PR to do this little fix.
