### ISSUE TITLE
Documentation: fix mistake

### ISSUE THREAD

**Issue by Triloworld** [nolimits4web/Swiper#2341]
Swiper V4

Go to: http://idangero.us/swiper/api/#initialize

Issue: documet.querySelector give error
Right: document.querySelector

Find: 
> var mySwiper = documet.querySelector('.swiper-container').swiper

Replace:

> var mySwiper = document.querySelector('.swiper-container').swiper

Thanks :)

**Comment by Triloworld** [comment]
Another one:
Go to:  http://idangero.us/swiper/api/#virtual

Find:

> zoom

Replace:

> virtual

**Comment by blowsie** [comment]
Perhaps there should be a note on how to contribute towards the documentation?
http://idangero.us/swiper/api/#coverflow-effect

Find:

> cubeEffect

Replace:

> coverflowEffect

**Comment by nolimits4web** [comment]
Thanks guys, fixed
