### ISSUE TITLE
Why documentation isn't responsive?

### ISSUE THREAD

**Issue by lucas-viewup** [nolimits4web/Swiper#2343]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I observed this in chrome in responsive mode and in my phone:

![screenshot](https://user-images.githubusercontent.com/28161720/33135510-c49fe1e0-cf89-11e7-9cbd-c30402a27dc2.png)

Adding this tag should fix the problem:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by nolimits4web** [comment]
Click `Open in new window` link to open demo in responsive format
