### ISSUE TITLE
Обновить сортировку

### ISSUE THREAD

**Issue by VladimirIvanin** [nolimits4web/Swiper#2345]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.0.6
* Live Link or JSFiddle/Codepen or website with isssue: [Пример сортировки](https://codepen.io/brainmurder/pen/NwMZJK)

При большом списке брейкпоинтов сортировка работает некорректно.

[Сортировка в плагине](https://github.com/nolimits4web/Swiper/blob/04eb489ff84bf798ffb982e2c0308f1fcbbaaa23/src/components/core/breakpoints/getBreakpoint.js#L11)

**Comment by nolimits4web** [comment]
![f3e4ad77-9fbc-4c72-a449-73dadac024f1](https://user-images.githubusercontent.com/999588/33178848-7f649914-d078-11e7-9a81-07643ad53a84.png)

**Comment by nolimits4web** [comment]
Мне кажется или я вижу одно и тоже в обеих колонках?

**Comment by VladimirIvanin** [comment]
https://image.prntscr.com/image/kAkKhDg7QwKhNW_wRrpZyw.jpeg
![image](https://user-images.githubusercontent.com/15268753/33179049-361574a8-d079-11e7-9f16-b23f6ab55349.png)

Chrome 62.0.3202.94, windows 10

**Comment by nolimits4web** [comment]
Видимо проблема Хрома, так как во всех остальных нормально. Может PR?
