### ISSUE TITLE
slidesPerView: 'auto' with breakpoints does not work 

### ISSUE THREAD

**Issue by miladfm** [nolimits4web/Swiper#2346]
**I have the following swiper configuration:**

     slidesPerView: 'auto',
       breakpoints: {
          640: {
            slidesPerView: 1,
          }
       }

**Also the width of ever odd slide is set to:**

    .swiper-slide:nth-child(2n+1) {
      width:200px;
    }

**Problem description:**
When the app starts odd swiper-slides are 200px in width. Resizing from above 640px to below does work and I only get one slide per view. However, resizing back to above 640px results in odd swiper-slides which are **NOT 200px** but still 640px in width. See link above for live test! Thanks.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.6 (but also in 3.x.x)
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/miladfm/pen/dZeBgm

Cheers
MiladFm

**Comment by nolimits4web** [comment]
It happens because Swiper doesn't unset slide's width style attribute, you can do it manually https://codepen.io/anon/pen/bYKjQJ

**Comment by miladfm** [comment]
tnx :)
