### ISSUE TITLE
swiper not working properly in IOS

### ISSUE THREAD

**Issue by xhuljomamoci** [nolimits4web/Swiper#2351]
Hey im using Swiper 4.0.6 .  As my code works perfectly in Android , it appears to have some issue when running it in IOS. The slides get stuck for a moment when swiping them.
Any ideas what is causing this issue and how to solve it?
Here is the code bellow...

export default {
 data () {
      const vue = this
      return {
        tab: 0,
        notNextTick: true,
        swiperOption: {
          autoplay: false,
          autoHeight: true,
          slidesPerView: '1',
          onTransitionStart (swiper) {
            vue.tab = swiper.activeIndex + 1
          }
        }
      }
    },
 computed: {
      swiper () {
        return this.$refs.mySwiper.swiper
      }
 },
methods: {
  changeTab (tabNumber) {
        this.swiper.slideTo(tabNumber - 1, 300, false)
        this.tab = tabNumber
  }
}
}

**Comment by nolimits4web** [comment]
> get stuck for a moment when swiping them

Usually means something wrong with performance, e.g. content of slide is very heavy or you are trying to do heavy JS operations within `onTransitionStart` callback

**Comment by xhuljomamoci** [comment]
as you can see from the code above im not doing any heavy JS operation within `onTransitionStart` callback. Also the content of the slides is not that heavy . Is there any other reason why this happens only in IOS ?
