### ISSUE TITLE
swiper.esm.js contains erroneous * characters

### ISSUE THREAD

**Issue by baseten** [nolimits4web/Swiper#2355]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.6.
* Platform/Target and Browser Versions: macOS.

### What you did
Trying to import this file throws Unexpected token errors

### Expected Behavior
File imports without errors

### Actual Behavior
In many places where multiply calculations are done in this file, there is a double `**` instead of a single `*`

**Comment by DanielRuf** [comment]
Which line causes this?

**Comment by baseten** [comment]
There are a few: 719, 722, 4360, 4411, 4414, 4513, 4516, 4520, 4523

**Comment by DanielRuf** [comment]
You mean `**` which is just `Math.pow()`? Did you actually transpile the file to ES5 using Babel or anything else?

The file is written in ES6.

Also see https://stackoverflow.com/questions/33284569/is-the-double-asterisk-a-valid-javascript-operator

**Comment by baseten** [comment]
Ah, got you. Yes I'm transpiling with babel, looks like this is ES7, so maybe I need some extra stuff in my .babelrc

**Comment by DanielRuf** [comment]
Probably the 2017 preset if available. https://babeljs.io/docs/plugins/preset-es2017/

**Comment by DanielRuf** [comment]
Or better the env preset.

**Comment by nolimits4web** [comment]
http://idangero.us/swiper/get-started/

<img width="860" alt="esm" src="https://user-images.githubusercontent.com/999588/33322424-60e260ee-d45a-11e7-9e1a-246f018a011b.png">

**Comment by DanielRuf** [comment]
I could solve it by upgrading UglifyJS to 3
