### ISSUE TITLE
[4.0.6] Vertical Slider with dynamic height (freemode)

### ISSUE THREAD

**Issue by teckes** [nolimits4web/Swiper#2357]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.6
* Platform/Target and Browser Versions: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
 / macOS Sierra 10.12.6
* Live Link or JSFiddle/Codepen or website with issue: https://jsfiddle.net/teckes/7cp5qg7r/

### What you did
I am trying to use a vertical swiper over the whole screen height. All slides heights are defined by their content, so some are higher then others. When to try to slide this swiper, it bounces back to the first slide.

I tried some options like resistance, resistanceRatio and all the other freeMode options, but nothing worked for me so far.

### Expected Behavior
The swiper should not bounce back to the first slide. it should stick with the active slide like in horizontal state.

### Actual Behavior
the slider bounces back to the first slide.

**Comment by luco** [comment]
I'm having a similar issue on mobile. I'm setting a dynamic height on page load, but the vertical slider seems not to work until I scroll the page.

**Comment by nolimits4web** [comment]
In your demo:
- `swiper-container` element is missing
- `swiper-container` element must have height in order to work
