### ISSUE TITLE
Used Loop after update when filtering the slides

### ISSUE THREAD

**Issue by orphen92** [nolimits4web/swiper#2358]
Hello, I did a function to filter the contents of the swipper.
I'm used Angular 4.
The Swipper gets up to date after using my function combined with the update method.

However, I would like to use the carousel loop option and it does not work properly.

If my loop option is enabled when i loading the page, the Swipper duplicates the content.
I use my filter to delete elements, however the old duplicate elements are still present in the DOM.
Suddenly the old content appears when I comming to the end of the Swipper.

Can you help me?

this is my filter function

```Javascript
  public filterChange(test) {
    this.SystemsItemsFiltered = this.SystemsItems.filter(function(val){
      return val.developer === test;
    });
    this.usefulSwiper.swiper.update();
    console.log('this.SystemsItemsFiltered', this.SystemsItemsFiltered); // Good value
  }
```

Another post talk about this problem

https://stackoverflow.com/questions/35601972/idangerous-swiper-duplicates
https://github.com/zefoy/ngx-swiper-wrapper/issues/84#issuecomment-346864647

**Comment by nolimits4web** [comment]
You need to use Swiper API to remove slides correctly in Swiper
