### ISSUE TITLE
touchReleaseOnEdges isn't working on iOS devices

### ISSUE THREAD

**Issue by yasingencnet** [nolimits4web/Swiper#2359]
Hello,

I'm using Swiper for a project. Everything is good except **touchReleaseOnEdges** parameter. 

When a user reach end of slider, swiper must allow for further page scrolling.  But touchReleaseOnEdges isn't working on iOS devices. User can't scroll. By the way this parameter works perfectly on any Android devices.

**Version:** 4.0.6
**Live Example:** https://s.codepen.io/yasingencnet/debug/eePYEx/PBkNWxeJRJKM
**See** #1978 

```
var swiper = new Swiper('.swiper-container', {
      direction: 'vertical',
      touchReleaseOnEdges: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
    });
```

So, how can i solve this problem?

**Comment by nolimits4web** [comment]
Fixed by 628a048
