### ISSUE TITLE
FireFox latest version issue

### ISSUE THREAD

**Issue by cththemes** [nolimits4web/swiper#2360]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.2, 4.0.6, 4.0.7
* Platform/Target and Browser Versions: With FireFox browser on MAC OSX Sierra

### What you did
The slider doesn't work on Firefox latest version if I set:

centeredSlides: true
loop : true
slidesPerView : 'auto'
loopedSlides: 7 (number of slides)

You can check this demo page: http://demowp.cththemes.com/inshot/home-carousel-center/

### Actual Behavior
The slider doesn't work, just display blank. If you resize the browser it will work again.

Please help. Thank you.

**Comment by nolimits4web** [comment]
Hmm, works for me in latest FF. But the issue in FF may be because of `srcset` attribute on images

**Comment by nolimits4web** [comment]
Closing as more likely FF's issue. Otherwise, if it is still happening, open the new issue with the clear steps how to replicate it
