### ISSUE TITLE
adding swiper overrides its parent's flex attributes

### ISSUE THREAD

**Issue by guykatz** [nolimits4web/Swiper#2361]
* [x] bug

* Swiper Version: 4.0.7
* Platform: chrome desktop but maybe others as well
* Codepen: https://codepen.io/guykatz/pen/NwEMYO?editors=1111

### What you did
I have a container the is flexed, row with 2 stretched items. items have flex grow of 1 so the container renreders like a rectangle split in half, each item takes half of the flex container.
once I put a swiper inside one of the flex items, it "ignores" the flex layout and "does not understand" that its width is its parent width and it grows.

in code the attached codepen, simply remove the swiper container html to see the actualy space I assume swiper needs to occupy

### Expected Behavior
swiper takes only the space of its parent

### Actual Behavior
swiper grows overriding its parent length and overriding is sibling flex item

i have read similar issues on github but they are not the same as what I describe

thanks

**Comment by nolimits4web** [comment]
Doesn't related to Swiper. This is how CSS works. E.g.:
```
.flexitem {
  width: 100%;
  flex-shrink: 1;
  min-width: 0;
}
```
Will fix it
