### ISSUE TITLE
Breakpoints properties reduced in version 4.0.0+

### ISSUE THREAD

**Issue by hassanasad** [nolimits4web/swiper#2362]
I want to ask a question

* Swiper Version: ^4.0.0
* Platform/Target and Browser Versions: macOS Chrome

In earlier version we could specify control in "breakpoints" property such as:
```
breakpoints            : {
	1024: {
		slidesPerView: 4,
		spaceBetween: 0
	},
	767: {
		slidesPerView         : 1,
		spaceBetween          : 0,
		freeMode              : false,
		freeModeSticky        : true,
		freeModeMomentum      : false,
		freeModeMomentumBounce: false,
		pagination            : { el: '.swiper-pagination', clickable: true },
		scrollbar             : null,
		mousewheel            : { sensitivity : 0.75 },
	}
}
```

However, in the newer Swipe version (^4.0.0) we cannot specify breakpoint properties other than "slidesPerView", "spaceBetween" and "sliderPerGroup". Is this intentional?

**Comment by nolimits4web** [comment]
Yes, scrollbar, pagination, can't be turned on/off by breakpoints, and it was the same in previous versions
