### ISSUE TITLE
On 4.0.7 ForceToAxis on nested does not work

### ISSUE THREAD

**Issue by andrestef** [nolimits4web/Swiper#2363]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: macOS

The ForceToAxis function in the Nested template no longer works.
It worked correctly up to version 3.4.2

**Comment by nolimits4web** [comment]
Link with JSFiddle or live example will be very helpful

**Comment by andrestef** [comment]
Swipe with magic mouse or track pad also triggers the vertical scroll
[CODEPEN](https://codepen.io/anon/pen/yPQrGm)

**Comment by nolimits4web** [comment]
Check the API please first http://idangero.us/swiper/api/#mousewheel
