### ISSUE TITLE
Website has typo

### ISSUE THREAD

**Issue by ibrent** [nolimits4web/Swiper#2367]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Current Website

### What you did
Typo on this page
http://idangero.us/swiper/get-started/

### Expected Behavior
"Styles" is misspelled.  "4. Swiper CSS Stlyes/Size"

### Actual Behavior
Typo baby

**Comment by nolimits4web** [comment]
Fixed, thanks
