### ISSUE TITLE
Incorrect first slide and slides disappearing on sliding left with looping

### ISSUE THREAD

**Issue by arnisjuraga** [nolimits4web/swiper#2374]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: tested on 4.0.5 - 4.0.7
* Codepen: https://codepen.io/arnisjuraga/pen/VrNVdx

### What you did
Create a slider with `loop` and with SLIDES_TOTAL, slidesPerGroup so, that:
`SLIDES_TOTAL % slidesPerGroup != 0`

e.g. - `slidesPerGroup` and `slidesPerView` set to 3, 
and add 4 slides in total

# Problem 1
### Expected Behavior
When first sliding to the left, should show 2,3,4 slides, next time: 3,4,1 and so on.

### Actual Behavior
The "first" slide will never be shown! You can see, that slide scrolls out of the screen 

# Problem 2

### Expected Behavior
If you add `loopAdditionalSlides: NUMBER,`, as suggested in some issues, it should append NUMBER slides in additional, but slides order should not be changed.

### Actual Behavior
The last slide (4th in my example), is always displayed as first one! And now, 3rd slide always scrolls away and is never displayed on screen, if sliding left!

**Comment by orphen92** [comment]
i thinks its the same problem

https://github.com/nolimits4web/Swiper/issues/2358

**Comment by arnisjuraga** [comment]
There are few more issues on loop behaviour, which can be similar. Waiting for a fix, please 👍

**Comment by arnisjuraga** [comment]
The same problem with latest Swiper 4.3.3 still is not fixed.
The same as #1925

**Comment by arnisjuraga** [comment]
The problem is still not fixed! 
Updated codepen with latest 4.4.1 version: https://codepen.io/arnis-juraga/pen/xaNZYR

**Comment by nolimits4web** [comment]
With loop mode there must be `SLIDES_TOTAL % slidesPerGroup === 0`

**Comment by nolimits4web** [comment]
https://codepen.io/anon/pen/ZMNWbp
