### ISSUE TITLE
swiper@4.0.6 don't support IE10

### ISSUE THREAD

**Issue by vvpvvp** [nolimits4web/Swiper#2375]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.0.6.
* Platform/Target and Browser Versions: WIN10 IE10.
* Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/

### What you did
use IE10 visit http://idangero.us/swiper/demos/

### Expected Behavior
everything is ok

### Actual Behavior
errors
![image](https://user-images.githubusercontent.com/7303371/33655335-b804bd6e-daad-11e7-96b3-0c930818153e.png)

**Comment by claverwebdesign** [comment]
Experiencing the same issue. Would be great if someone could look into this.

**Comment by nolimits4web** [comment]
Duplicate #2339
