### ISSUE TITLE
Child slider changes the parent slider when it reaches first/last slide

### ISSUE THREAD

**Issue by aMUSiC** [nolimits4web/swiper#2376]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: chrome / cordova (ios/android).

### What you did

I have a parent horizontal slider (set to virtual as it contains many slides), and on each slide there is another horizontal child slider (also set to virtual), set with:

nested: true
spaceBetween: 5
slidesPerView: 5
centeredSlides: 5

I slide through the child slide either towards the end, or the start of the slider and I reach the end/start respectively.

### Expected Behavior

The child slider should stop sliding (with the respective friction effect) and not change the parent slider to the next/previous slide.

### Actual Behavior

The parent slider changes to the next/previous slide.

### Additional Info

- If I manually add stopPropagation on the touchStart event of the child carousel, then the behavior is as described in the Expected Behavior section

- If this is the intended behavior, I'd like to suggest the inclusion of an extra option for nested sliders (slideParentOnEnd: true/false) which enables or disables said behavior.

**Comment by nolimits4web** [comment]
Can you provide a JSFiddle with issue? Don't really understand what is happening
