### ISSUE TITLE
Slides disappearing on nested virtual sliders

### ISSUE THREAD

**Issue by aMUSiC** [nolimits4web/swiper#2377]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: chrome / cordova (ios/android).

### What you did

I have a parent horizontal slider (set to virtual as it contains many slides), and on each slide there is another horizontal child slider (also set to virtual), set with:

nested: true
spaceBetween: 5
slidesPerView: 5
centeredSlides: 5

The child slider is created dynamically when the parent slide becomes the active one for the first time (held in an array of slider instances) and reused/updated when it's in view again. Each slider is initialized with a different class name.

I slide through the parent slider back and forth, and for each slide I slide through the child slider.

### Expected Behavior

The child slider's slides should all be there

### Actual Behavior

Some of the child slider's slides disappear. 

### Additional Info

- This only happens when I slide to a slide where the child slider has been previously created, not on slides where the child slider gets created upon slide entry.

- The number of missing slides is not consistent. Sometimes it's just one, sometimes more.

- The behavior is not consistent, as sometimes there are no missing slides, but it's easily reproducible as it happens 80% of the time

- When this happens, the alignment of the slides is off. The active slide is not centered (it errs to the left). If I slide to the end of the child slider and then back, it snaps back into alignment (however the slides are still missing)

- Sometimes there are two or more slides with the swiper-slider-active class. Calling swiper.update() and swiper.virtual.update() resolves this. However calling update()/virtual.update() does not resolve the missing slides issue.

- this is happening regardless of whether centeredSlides is true or false

**Comment by nolimits4web** [comment]
Can you please provide a JSFiddle with the issue?
