### ISSUE TITLE
Unreasonable height of vertical swiper

### ISSUE THREAD

**Issue by ashishthedev** [nolimits4web/swiper#2378]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.6
* Platform/Target and Browser Versions: Chrome Linux
* Live Link or JSFiddle/Codepen or website with isssue:  https://jsfiddle.net/4ogo3vcg/4/

### What you did
Created a vertical swiper as per the docs

### Expected Behavior
I was expecting vertical slider to remain in bounds of the parent element(a bootstrap4 row)

### Actual Behavior
But the swiper-container(vertical) element is unreasonably long and its height is being miscalculated to around 14400px.

**Comment by daviddelusenet** [comment]
I'm experiencing the same issues. To put it bluntly, the vertical part of this slider is just pure shit. Been literally spending weeks on getting one to work properly, still can't manage to do it.

**Comment by daviddelusenet** [comment]
My swiper settings:

```
this.swiperTop = new Swiper(this.swiper, {
  direction: 'vertical',
  loop: true
});
```

My swiper gets slides of 16443 pixels in height.....

**Comment by ashishthedev** [comment]
Found a "workaround".
Apply specific height to the v-swiper-container and specify overflow: hidden

Working JS Fiddle:
https://jsfiddle.net/4ogo3vcg/5/

@nolimits4web  - if you feel the above settings are definitely required and not just a workaround, please update the docs and specify these css options.



http://idangero.us/swiper/api/

direction | string | 'horizontal' | Could be 'horizontal' or 'vertical' (for vertical slider).

**Comment by nolimits4web** [comment]
This is basically CSS basics that if you want to have something scrollable/swipeable vertically you must have fixed height
