### ISSUE TITLE
Swiper Transition are not working on IOS11

### ISSUE THREAD

**Issue by arthursouviron** [nolimits4web/Swiper#2379]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7 (anything 4.0 and up)
* Platform/Target and Browser Versions: IOS 11
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/arthur_souviron/full/YEoLLR/

### What you did
Basic vertical swiper

### Expected Behavior
The animation should look fine while swiping through the page

### Actual Behavior
The animations after releasing the swiper are happening instantly on IOS11, there is no transition.
See video 
![giphy](https://user-images.githubusercontent.com/5681289/33752044-1d35de12-dc1a-11e7-8e70-2923ce8d67f1.gif)

I tested on chrome & safari and both have the issue.
Works fine on Android and desktop

**Comment by nolimits4web** [comment]
Works for me in iOS 11

**Comment by zjtt** [comment]
How do you solve this bug?

**Comment by arthursouviron** [comment]
@zjtt I didn't change anything but it seems to work now.
The only thing we changed in our app was switching from [uiwebview](https://developer.apple.com/documentation/uikit/uiwebview) to [wkwebview](https://developer.apple.com/documentation/webkit/wkwebview). This seems to have solved the issue.

**Comment by zjtt** [comment]
thanks
