### ISSUE TITLE
How do I get multiple swiper galleries with thumbs to work on same page? 

### ISSUE THREAD

**Issue by nitin00709** [nolimits4web/swiper#2381]
* Swiper Version: Version used Swiper 4.0.3

### What you did
I tried this code here:
$(document).ready(function(){
        var galleryTop = new Swiper('.gallery-top', {
          spaceBetween: 10,
          loop:true,
          direction: 'horizontal',
          loopedSlides: 3,
          effect: "fade"
        });
        var galleryThumbs = new Swiper('.gallery-thumbs', {
          spaceBetween: 4,
          slidesPerView: 3,
          touchRatio: 0.2,
          direction: 'vertical',
          loop: true,
          loopedSlides: 3,
          slideToClickedSlide: true,
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          },
          breakpoints: {
              320: {
                slidesPerView: 1,
                spaceBetween: 4
              },
              480: {
                slidesPerView: 2,
                spaceBetween: 4
              },
              640: {
                slidesPerView: 3,
                spaceBetween: 4
              }
           }
        });
        galleryTop.controller.control = galleryThumbs;
        galleryThumbs.controller.control = galleryTop;
     });

### Expected Behavior
What i want is to have multiple galleries with thumbs on single page. 

### Actual Behavior
It does work if there is only one gallery on page but its not working when i have multiple galleries on single page. Also I have been using this gallery in a popup for individual item.
The actual issue is that its not giving the active, next and prev classes in the slider. Its giving me following error on page with multiple galleries in console-
"galleryTop.controller is undefined"
but working perfectly on page with single gallery.

**Comment by nolimits4web** [comment]
> but its not working when i have multiple galleries on single page

Use more specifi selector to init each swiper separately. I won't recommend to use `new Swiper('.gallery-top')` if you have multiple ".gallery-top" on the page

**Comment by hibanastudio** [comment]
@nolimits4web Sorry to open this thread again. 
Would you mind showing a sample on how it's done?
I'm looping some galleries with thumbnails with php on the same page so I'm bumping into the same issue.
