### ISSUE TITLE
Feature request: Don't require .swiper-slide class

### ISSUE THREAD

**Issue by powerbuoy** [nolimits4web/swiper#2384]
So glad I found Swiper. Easily the best such tool out there right now. I have a feature request though:

It would be awesome if you could style the actual slides using `.swiper-wrapper > *` instead of with `.swiper-slide`. This way you wouldn't have to manually add the `swiper-slide` class every time you create a slideshow.

I'm using Swiper in an Aurelia project atm, and I've wrapped it all in a `<swiper>` custom element. To create a slideshow one simply adds one's slides as children of the `<swiper>` element like so:

```html
<swiper>
    <div>Slide 1</div>
    <div>Slide 2</div>
    <div>Slide 3</div>
</swiper>
```

At least that's how I'd like it to work :) Right now I instead have to:

```html
<swiper>
    <div class="swiper-slide">Slide 1</div>
    <div class="swiper-slide">Slide 2</div>
    <div class="swiper-slide">Slide 3</div>
</swiper>
```

It's a minor inconvenience of course, but it would be so easy to swap `.swiper-slide` with `.swiper-wrapper > *` so just putting it out there :)

**Comment by nolimits4web** [comment]
`.swiper-wrapper > *` is an option for default support, because instead of slides there could be other elements. You can in same way create `<swiper-slide>` element

**Comment by powerbuoy** [comment]
I'm sorry but I don't understand? Are you saying the swiper-slide class is optional? Because I can't get the slider to work without it.
