### ISSUE TITLE
What happened to the fullscreen function

### ISSUE THREAD

**Issue by MaximilianUE** [nolimits4web/Swiper#2385]
This is a (multiple allowed):
* [ x ] enhancement
* [ x ] feature-discussion (RFC)

### Info
* Swiper Version: 3.4.2 (newest)
* Platform/Target and Browser Versions: all

### What you did
I was looking for a fullscreen demo and couldn´t find any.
I checked the repo and found two commits regarding the addition of this feature by @nolimits4web:
https://github.com/nolimits4web/Swiper/commit/1cef9025bbc9263962a2cfb2da9508544a2e31fa
https://github.com/nolimits4web/Swiper/commit/8383b5e1941bd6c6ddb22e325c611c3126d51fd4
I then checked the changelogs but couldn´t find any mentionings of this feature. nor a note why it was removed 

### Expected Behavior
Finding info why it was removed or (even better) the addition of it: 
A button /function to enlarge (fullscreen) my swiper gallery (like reveal or overlay)

### Actual Behavior
feature isn´t existing anymore(?)

**Comment by nolimits4web** [comment]
Because it can be done easily with vanilla JS, e.g.:
```
document.querySelector('.swiper-container').webkitRequestFullscreen();

**Comment by MaximilianUE** [comment]
makes sense thanks for helping me out there :)

**Comment by DanielRuf** [comment]
I guess https://gist.github.com/simonewebdesign/6183356 is sufficient?

**Comment by DanielRuf** [comment]
> Because it can be done easily with vanilla JS, e.g.:
> 
> document.querySelector('.swiper-container').webkitRequestFullscreen();

Not really:
> Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

Is there any other solution for Chrome?

**Comment by DanielRuf** [comment]
https://stackoverflow.com/a/29282049/753676
