### ISSUE TITLE
buttons are not disabled with slidesOffsetBefore/slidesOffsetAfter

### ISSUE THREAD

**Issue by jonnitto** [nolimits4web/swiper#2386]
If I have a swiper instance with a value in `slidesOffsetBefore` and/or `slidesOffsetAfter` and `slidesPerView` on `auto`, you can always slide the value who is set. Like that, also the buttons never get disabled.
```
slidesOffsetBefore: 15,
slidesOffsetAfter: 15,
slidesPerView: "auto"
```

**Demo**

![swiper](https://user-images.githubusercontent.com/4510166/33925279-b8ce5922-dfd9-11e7-8d69-f1e2b60a8c21.gif)

If I set both values to `0`, the slider is fixed and the buttons are disabled as expected:

<img width="984" alt="screenshot 2017-12-13 07 45 53" src="https://user-images.githubusercontent.com/4510166/33925272-b246bc52-dfd9-11e7-81c7-dabb3b0b86e5.png">

**Comment by jonnitto** [comment]
The problem is still here…

**Comment by jonnitto** [comment]
The problem is still here…

**Comment by jonnitto** [comment]
The problem is still here…

**Comment by jasonlav** [comment]
This bug still exists.

**Comment by corymckenzie** [comment]
it sure does, its driving me nuts

**Comment by idzer0lis** [comment]
Confirmed...Could not find any solution.

**Comment by adrienpoly** [comment]
This is what worked for me 
```js
slidesOffsetBefore: 10,
slidesOffsetAfter: 10, // required or the navigation persists
watchOverflow: true,
```

**Comment by xxvii** [comment]
This is BY DESIGN guys! ahahahah

https://github.com/nolimits4web/swiper/issues/4211
https://github.com/nolimits4web/swiper/issues/4217
