### ISSUE TITLE
Feature request: noSwipingSelector

### ISSUE THREAD

**Issue by powerbuoy** [nolimits4web/swiper#2388]
In addition to supporting `noSwipingClass` (which requires the user to add said class to every element), an additional property `noSwipingSelector` would be nice so that the user can simply say: `noSwipingSelector: 'form'` (for example) - without having to add the class to every single form that may or may not be inside a slideshow.

**Comment by powerbuoy** [comment]
Why close this without even a comment?

**Comment by nolimits4web** [comment]
<img width="774" alt="ss" src="https://user-images.githubusercontent.com/999588/35567544-7bc50b34-05d6-11e8-861c-059cbdb18a9c.png">

**Comment by powerbuoy** [comment]
I beg your pardon :) thank you sir!
