### ISSUE TITLE
Navigation doesn't work properly when there are multiple swipers per page for swipe actions

### ISSUE THREAD

**Issue by rdy4ever** [nolimits4web/swiper#2390]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Windows, Android, iOS

### What you did
I have multiple swiper galleries with navigation and pagination on the same page. If I use the navigation arrows to navigate, the pagination gets updated correctly. If I use swipe gestures to navigate, the pagination doesn't get updated.

### Expected Behavior
Each navigation should update correctly.
### Actual Behavior
If there is more than one swiper per page, swiping will not update the navigation bullets.

**Comment by nolimits4web** [comment]
JSFiddle or live example with the issue is required!

**Comment by minhtranite** [comment]
Hi Guys!
I have create two pen to reproduce two issues. May be it can help @rdy4ever 

## Pagination
https://codepen.io/minhtranite/pen/Gyjygd
Pagination of slider 1 not work correct. when swipe or click on pagination
Reason: Slider 2 not have pagination element on html but script still have option for it.
```
pagination: {
      el: '.swiper-pagination',
      clickable: true
    },
```
## Navigaiton
https://codepen.io/minhtranite/pen/Mrjrma
Try click to slider 1 navigation button.

Reason: same with slider 1 but with navigation elements

**Comment by mehulRojasara** [comment]
i face same problem when i was working in my old HTML theme
i just add pagination to each swiper and i dont want it, i just hide it by adding css class it works fine for me
i think when we don't add pagination it consider prev pagination as handle
try this in your second swiper
HTML
<div class="swiper-pagination display-none"></div>
-------------------------------
CSS
.display-none { display:none; }
