### ISSUE TITLE
fast swipe seems lag

### ISSUE THREAD

**Issue by ibreathebsb** [nolimits4web/swiper#2391]
* bug?
* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: OSX ,Chrome for Android 63
``` js
this.swiper = new Swiper({
      el: '.swiper-container',
      scrollbar: {
        el: '.swiper-progress'
      }
    })
```
``` css
.swiper-wrapper {
    transition-timing-function: ease-out;
}
```

After `touchend` event form a fast swipe, the initial transition speed should be high, but there is a short period that it moves slow, then it goes faster and finnally slow when reach the next, i already set the `transition-timing-function: ease-out`, but it's not working, there is a obvious lag after touchend, it would be nice if it started at the same velocity when the touch is released.

**Comment by ibreathebsb** [comment]
while it seems  `transition-duration` is not correctly calculated, it uses the `param.speed`  and `actual distance` to calculate the time. I did some tricks to make it more smooth:

``` js
this.swiper = new Swiper({
      el: '.swiper-container',
      scrollbar: {
        el: '.swiper-progress'
      },
      freeMode: true,
      freeModeSticky: true,
      freeModeMomentumBounce: false
    })

    this.swiper.on('setTransition', function (time) {
      console.log(time)
     // avoid slow touch move that causes long time transition
      if (time > 300) {
        document.querySelector('.swiper-wrapper').style['transitionDuration'] = '300ms'
        document.querySelector('.swiper-scrollbar-drag').style['transitionDuration'] = '300ms' // if u have a progress bar
      }
    })
```

**Comment by DanielRuf** [comment]
Not sure if this is related but when we enable `loop` it seems it happens also.

Enable `loop` and `keyboard` at 
https://danielruf.github.io/swiper-builder/ and hit the right/left key. And try it without `loop`.

**Comment by DanielRuf** [comment]
Why was this closed?
