### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by ThakurNiteshkumarSingh** [nolimits4web/Swiper#2392]
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by zougamohamed** [comment]
I get the same warning, is it normal ?

**Comment by rushsteve1** [comment]
I am having the same issue. Is this the expected behavior?

**Comment by kumarkodari** [comment]
I am having the same issue. how to resolve this issue. error

**Comment by 9-lives** [comment]
How can hide this?

**Comment by chanphillip** [comment]
I have a remote machine running with this library. I saw this warning in the log and suspected people somehow might not be able to use the touchscreen after this warning, but I couldn't confirm yet.

**Comment by xiaoxiongzi** [comment]
Add a css3 attribute to the html element
```
touch-action: none;
```
Can solve this problem
