### ISSUE TITLE
When I use swiper in webpack has error

### ISSUE THREAD

**Issue by jenerse** [nolimits4web/Swiper#2394]
When I use swiper in react, and use webpack to run my web application, it has a error:
`ERROR in bundle.js from UglifyJs
Unexpected token: name (w) [./node_modules/swiper/dist/js/swiper.esm.bundle.js:15,0][bundle.js:55903,4]`

How to fixed it?
Thanks!

**Comment by nolimits4web** [comment]
Look at the end of this page http://idangero.us/swiper/get-started/
