### ISSUE TITLE
Multiple Swiper Instances but There are UI issues.

### ISSUE THREAD

**Issue by ranonengineer** [nolimits4web/Swiper#2396]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Chrome, Firefox, IE11 or above
* Live Link or JSFiddle/Codepen or website with isssue: N/A (I'm building a local workspace with AEM corporate)

### What you did
I'm trying to create multiple instances of swipers. All swipers have same configuration. The swiper is basically image gallery slider. It works great when it's placed on visual and obvious page. I'm trying to add this slider into different element as such as Accordion element. When it's accordion expand set to true, the swiper container looks great. However, if the accordion expand is false (collapsed accordion) and I'm clicking to expand that accordion. The swiper container with left and right arrow, pagination did not work or show. I tried swiper.destroy() and swiper.init(). It does work but the pagination and arrows are still not working after that.

**** HTML *****

```
<div class="swiper-container imageGallerySlider">
	<div class="swiper-wrapper">
		<!-- Slides -->
		<sly data-sly-list.imagePart="GRABIMAGELIST"> 
			<div class="swiper-slide">
				<img src="IMAGE" alt="" />
				<span class="slideCaptionText">CAPTIONTEXT</span>
				<span class="slideCreditText">CREDITTEXT</span>
			</div>
		</sly>
	</div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev igs-button-prev"></div>
    <div class="swiper-button-next igs-button-next"></div>
	<div class="caption-box">
		<span class="caption-text">Caption Description</span>
		<div class="caption-icon"></div>
    </div>
	<span class="photo-credit">Photo Credit</span>
	<!-- Add Pagination -->
	<div class="swiper-pagination imageGallerySwiperPagination"></div>
</div>
```

******** JS ************
```
var sliderList = [];
jQuery(".imageGallerySlider").each(function(index, element){
    var $this = jQuery(this);
    var swiper = new Swiper(this,{
    	direction: 'horizontal',
    	pagination: {
    		el: $this.find(".imageGallerySwiperPagination")[0],
    	},
    	loop: true,
        navigation: {
          nextEl: $this.find(".igs-button-next")[0],
          prevEl: $this.find(".igs-button-prev")[0],
        }
    });
    sliderList.push(swiper);
});
```

```
//Image Gallery Slider
var initImageGallerySliderFunc = function(){
	console.log("init initImageGallerySliderFunc()");
	jQuery(".imageGallerySlider").each(function(index,element){
		console.log("looping imageGallerySlider sliders and index at: "+ index);
		
		var getSliderElem = $(this);
		if( getSliderElem.parents(".accordion-reusable").length > 0){
			console.log("this slider has accordion parent and index at: " + index);
			sliderList[index].destroy(false,true);
			sliderList[index].init();
		}
	});
}

```
```
jQuery(document).ready(function(){
	jQuery(".accordion-reusable .toggle").click(function(){	
		if($(".imageGallerySlider").length > 0){
			console.log("imageGallerySlider exists");
			accordionToggleListener("open", ".imageGallerySlider", this, initImageGallerySliderFunc);
		}
	});
});
```

```
function accordionToggleListener(state, selector, _this, doFunc){
	var accordThis = $(_this).parent().parent();
	if(state == "open"){
		console.log("listening to open accordion click");
		var openAccord = $(_this).parents(".collapsed");
		if(openAccord.length > 0){
			if(openAccord.find(selector).length > 0){
				doFunc();
			}
		}
	}else if(state == "close"){
		console.log("listening to close accordion click");
		var closeAccord = accordThis.not(".collapsed");
		if(closeAccord.length > 0){
			if(closeAccord.find(selector).length > 0){
				doFunc();
			}
		}
	}
}
```

### Expected Behavior
I'll like to be able to restart swiper with same configuration every time.

### Actual Behavior
Swiper was successfully restarted but I could not get pagination, arrows, or even breakpoint configurations to work.

### Additional Note
I'm wondering if swiper.init() limits to what we can do to initialize the swiper again?

Thank you for your assistance in advance!

Edit 1: I updated the code formatting on this issue form.

**Comment by nolimits4web** [comment]
Slider can not be initialized with `init()` after it was destroyed. Use `new Swiper()` again on swiper after destroying

**Comment by ranonengineer** [comment]
Thank you for reply! Can you add that note to your API page? I think that's important information. What about swiper.update()? Maybe, you can add swiper.restart() in future? It seems silly to have to create new Swiper() again. Thank you again!
