### ISSUE TITLE
IE10 and mouse Events

### ISSUE THREAD

**Issue by orauch-a** [nolimits4web/Swiper#2398]
Hello, 

"Click and drag" event don't work on IE10.

There is an arror in your 'dist/js/moment.js' and 'dist/js/moment.min.js'
You must replace
`desktop = ['MSPointerDown', 'MsPointerMove', 'MsPointerUp'];`
by
`desktop = ['MSPointerDown', 'MSPointerMove', 'MSPointerUp'];`

Can you build a new version ?

Thanks

**Comment by nolimits4web** [comment]
Must be fixed in 4.1.0
