### ISSUE TITLE
Wrong starting index with dynamic slides using observer true

### ISSUE THREAD

**Issue by sconix** [nolimits4web/swiper#2399]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Chrome
* Live Link or JSFiddle/Codepen or website with isssue: http://plnkr.co/edit/onFxyvZgEOw97JUFxqHT?p=preview

### What you did
I am maintainer of ngx-swiper-wrapper which is a simple wrapper library for Angular 4/5. Few of the users have reported issue with the Swiper starting with last slide when slidesPerView is 'auto' or > 1 and slides are dynamically / asynchronously created. With Angular its very often the case that slides are generated dynamically or even asynchronously so observer true option needs to be used often to avoid manually calling the update. The observer: true works nicely for most of the cases, but not with the above slidesPerView setting. I decided to report this since I think there might be some small bug in the Swiper when it comes to how update/observer re-initialization works.

I tracked the issue here: [https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L3588-L3592](https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L3588-L3592)

For some reason when the observer runs the update the isEnd is still true even though slides already exists in the DOM. So could there be a bug that isEnd is not updated correctly or is this just some limitation of observer feature.

I included a Plunker example from the wrapper library where the issue can be seen with the Directive approach (the Component approach has the slides in the DOM before initializing Swiper so that's why it works correctly).

### Expected Behavior
The initial slide should stay at the initialSlide and not to jump to the last slide.

### Actual Behavior
When slides are rendered the initial slide will be the last slide.

**Comment by sconix** [comment]
If you think this is not a bug and is some sort of limitation of the specific features then any insight to why this might be happening would be appreciated so I could try to figure out a workaround for the wrapper. 

Since I was not able to track the root of the cause only the place where the wrong index is set, but not the core reason why the isEnd is still true.

**Comment by MaxInMoon** [comment]
@sconix did you find any workaround?

**Comment by MaxInMoon** [comment]
fixed in v4.1.0!

**Comment by herzinger** [comment]
I'm seeing this same behavior in v4.1.6. Is there any way to capture the update event? If so, I could manually move the slider back to the initial position at least.
