### ISSUE TITLE
VirtualTranslate and autoplay not working together

### ISSUE THREAD

**Issue by silviaaimone** [nolimits4web/Swiper#2400]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Windows, browser Google Chrome 63.0
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/gdcnm3wq/

### What you did
I created a simple swiper with virtualTranslate (I want to implement my own transitions) and autoplay

### Expected Behavior
I expected the swiper would add the class "swiper-slide-active" to every slide after the time indicated in autoplay param.
 
### Actual Behavior
Actually it works just until the second slide, then the autoplay seems to stop.

**Comment by elcferreira** [comment]
This bug occur with me.
I will create function for control slides with setInterval and el.slideNext().
Do you can find solution?

**Comment by meduzen** [comment]
Exactly the same for me: autoplay slide from first to right. Here’s my Swiper instance with some `console.log()` for debug:
```js
this.slider = new Swiper('.my-swiper-wrapper', {
  slidesPerView: 1,
  virtualTranslate: true,

  autoplay: {
    delay: this.autoPlayInterval, // 4000 (int)
    disableOnInteraction: true
  },

  iOSEdgeSwipeDetection: true,
  touchReleaseOnEdges: true,

  wrapperClass: 'my-wrapper-class',
  slideClass: 'my-slide-class',
  slideActiveClass: 'my-active-slide-class',

  on: {
    touchMove: () => { doSomething() },
    touchEnd: () => { doSomething() },
    slideChange: () => {
      console.group('slidechange') // output once when slide changes from first to second
      console.log(this.slider.autoplay.running) // true
      doSomething()
      console.log(this.slider.autoplay.running) // true
      console.groupEnd()
    },
    reachEnd: () => {
      console.log('reachend', this.slider.autoplay.running) // never output
      if (this.slider.autoplay.running) {
        this.autoPlayTimeOut = setTimeout(() => {
          this.slider.slideTo(0)
          this.slider.autoplay.start()
        }, this.autoPlayInterval)
      }
    },
    autoPlay: () => { console.log('autoplay slidechange') }, // never output
    autoPlayStart: () => { console.log('autoplay start') }, // never output
    autoPlayStop: () => { console.log('autoplay stop') } // never output
  }
})
```

It seems the `autoPlay` events aren’t fired at all.
