### ISSUE TITLE
Object doesn't support property or method 'use' IE 10

### ISSUE THREAD

**Issue by qwertylyy** [nolimits4web/Swiper#2401]
This is error your demo. Please see this image
https://www.screencast.com/t/873drpI6qge

Can you fix it and commit code to github.
Thanks in advance!

**Comment by Vervinsky** [comment]
Do anybody has any updates?

**Comment by nolimits4web** [comment]
Must be fixed in 4.1.0

**Comment by qwertylyy** [comment]
Thanks!
