### ISSUE TITLE
Slides jumps when dragging between last and first slide in loop mode

### ISSUE THREAD

**Issue by udovichenko** [nolimits4web/swiper#2402]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7 and earlier (at least since 2015)
* Platform/Target and Browser Versions: Chrome, Firefox, etc on both macOS and Windows.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/udovichenko/pen/wpoGww

### What you did
I am dragging looped swiper between first and last slide.

### Expected Behavior
Smooth animation, when pointer keeps the same position over a slide while dragging.

### Actual Behavior
Swiper instantly jumps to ~half of slide width to left or right (depends on dragging direction).

It looks like a position calculation error when duplicated slides is beeing appended or removed. But I'm not sure...
This bug is easier to observe in free mode, but it also presents without free mode.
Here's a gif, that illustrates the issue:
![swiper-looped-dragging-bug](https://user-images.githubusercontent.com/4137519/34321716-e5cf0d86-e826-11e7-9fcf-b53af8d14d08.gif)

I found 2yo topic on forum with the same issue description http://idangero.us/swiper/forum/#!/bugs-and-issues:loop-with-freemod-itll-j without replies. It also has a gif, that illustrates this issue.

I really hope for a solution to this problem in the near future, because it is critical for a project I'm working on at the moment, and I really do not want to exchange my beloved Swiper to another slider such as Flickity))

Thanks!

**Comment by zahod5277** [comment]
+1
