### ISSUE TITLE
pagination did not update when using multiple swipers

### ISSUE THREAD

**Issue by david43** [nolimits4web/swiper#2403]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: CHROME
* Codepen : https://codepen.io/anon/pen/jYVYwo

### What you did
Pagination did not update when I resize

### Expected Behavior
Should be show correct number of swiper-pagination-bullet when resize

![Image of Bug](https://d2ffutrenqvap3.cloudfront.net/items/3w3y2T3q3T0g430e1z3h/Screen%20recording%202017-12-25%20at%2001.09.17%20AM.gif?v=d898f2d6)

### Actual Behavior
It did not update

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by mhshakouri** [comment]
I see you are using breakpoints to define multiple slides per view in different viewport widths .

So the swiper instance needs to be re-initialized / updated on each breakpoint.

This can be embeded in to the core of the swiper api but for now
I think you better do something with js to re-initialize/update the swiper instance on each breakpoint
