### ISSUE TITLE
allowSlideNext Bug（slowly pull back will stop there）

### ISSUE THREAD

**Issue by rongpeng1989** [nolimits4web/swiper#2405]
When I setted AllowSlideNext: false, after locking, slowly pull back a bit, will stop there, won't bounce back, please resolve this bug, thanks.

**Comment by Tobycct** [comment]
This problem also occurred in the version of swiper 3.x, api as lockSwipeToNext() and allowSwipeToNext.
Thanks for your help and time to solve this problem!
