### ISSUE TITLE
Stop autoplay while hovering when have multiple slides per view

### ISSUE THREAD

**Issue by mohsin-ahead** [nolimits4web/swiper#2406]
I have swiper slider with multiple slides per view (slidesPerView: 4), I added the below script to stop on hover but it stops after completing the current transition.
$(".swiper-container").hover(function(){
     this.swiper.stopAutoplay();
}, function(){
     this.swiper.startAutoplay();
});
I want to stop the slider immediately when mouse is on slider.

**Comment by nolimits4web** [comment]
It is impossible to to stop slider during transition by default, you may need to set `transition:0` on its swiper-wrapper, but the further behavior can be wrong
