### ISSUE TITLE
API documentation 

### ISSUE THREAD

**Issue by RyanGosden** [nolimits4web/Swiper#2408]
First of all great work guys.
Any chance you can add API documentation to github as your site is currently down.
I managed to set most of the plugin without doc but have a few queries. 
Thanks in advance.

**Comment by nolimits4web** [comment]
Website is up and running. I’ll upload it to github when I have time

**Comment by DanielRuf** [comment]
Bump. We still need the docs. Best is to host them in the Swiper repository with the Swiper versions so developers should always have the complete docs with a full install.

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper-website
