### ISSUE TITLE
Feature detections broken since navigator.pointerEnabled and friends are removed.

### ISSUE THREAD

**Issue by jdalton** [nolimits4web/Swiper#2410]
Edge removed the non-standard `navigator.pointerEnabled` and MS prefixed forms. This means the feature detects used in Swiper fail for it now. Would doing something like `"onpointerdown" in window` be a good compromise?

**Comment by DanielRuf** [comment]
Does the removal by MS produce any bugs or issues in the current Edge versions?

**Comment by jdalton** [comment]
Yes, since the detections fail swiper behaves incorrectly in Edge.

**Comment by DanielRuf** [comment]
Edge 15 and 16? In which way exactly and with which config? So far our projects did not change their behavior in Edge afaik.

**Comment by jdalton** [comment]
You can reproduce the bug here:
http://idangero.us/swiper/demos/

In [Edge 16](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/16299/) you can't change contents by swiping horizontally.

**Comment by DanielRuf** [comment]
Not reproducible here
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

I can swipe horizontally without any issues and the slide is changed. Or what exact example do you mean?

**Comment by jdalton** [comment]
Are you swiping with your finger or mouse?

**Comment by DanielRuf** [comment]
Mouse. Please be more specific on which sort of devices and with which input mode you tested this and where it is reproducible.

If it is on touch I have to find a device (probably the Surface at work).

**Comment by DanielRuf** [comment]
Would be `navigator.pointerEvent` sufficient? https://github.com/Microsoft/vscode/issues/33117

**Comment by jdalton** [comment]
> If it is on touch I have to find a device (probably the Surface at work).

Yes, please try the Surface.

> Would be `navigator.pointerEvent` sufficient? Microsoft/vscode#33117

I'll double check!

**Comment by DanielRuf** [comment]
I guess we should follow the advices at https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/dom/pointer-events

**Comment by DanielRuf** [comment]
> Does the removal by MS produce any bugs or issues in the current Edge versions?

I've tested on a current Edge. So far there are at least no errors in the console.
The only issue is that the old code does not work and at least does not throw any errors?

**Comment by DanielRuf** [comment]
Not fully tested. Would be great to get some help with testing.

Do you think this is enough to support touch gestures on Edge again?

https://github.com/nolimits4web/Swiper/pull/2415

**Comment by jdalton** [comment]
>> Would be `navigator.pointerEvent` sufficient? Microsoft/vscode#33117

>I'll double check!

I can confirm @DanielRuf in that using touch nothing happens *(swiping has no affect)*. I checked and `navigator.pointerEvent` does not exist. The `"onpointerdown" in window` or `window.PointerEvent` does though.

**Comment by DanielRuf** [comment]
See https://github.com/nolimits4web/Swiper/pull/2415/files
