### ISSUE TITLE
box-sizing overwritten by core styles

### ISSUE THREAD

**Issue by DanielRuf** [nolimits4web/swiper#2417]
It seems the wrapper sets the box-sizing to content-box which resets / overwrites, see https://github.com/nolimits4web/Swiper/tree/master/src/components/core/core.less#L25

It would be better to not set this by default as it manipulates the inherited values.

**Comment by nolimits4web** [comment]
As i remember it was required for correct layout and styles/sizes computation, need to check will it work and cover all use cases with `border-box` or not
