### ISSUE TITLE
在ie11浏览器中报错

### ISSUE THREAD

**Issue by tianyesh** [nolimits4web/Swiper#2418]
在vue项目中用了"swiper": "^3.4.2"，但是在ie浏览器中报错了，出现了白屏，其他的浏览器都是没有问题的，已经加了babel-polyfill包，在测试的时候发现不引人swiper的时候，ie浏览器就不会出现问题，请问这个是什么原因造成的，非常感谢
![default](https://user-images.githubusercontent.com/29880599/34763531-80b7b516-f626-11e7-815e-2fefc16975f5.png)

**Comment by kukac7** [comment]
![](https://media.giphy.com/media/3o6fJ7uaPs0w3jLlXa/giphy.gif)

**Comment by tianyesh** [comment]
ie9、ie10、ie11都有这个问题

**Comment by SketchK** [comment]
@tianyesh 问题是怎么解决的啊

**Comment by yipjianbo** [comment]
@tianyesh 老哥，解决方案发一下呀~
