### ISSUE TITLE
Urgent : Problems with simulateTouch, and draggable scrollbar, and MouseDrag events

### ISSUE THREAD

**Issue by mhshakouri** [nolimits4web/swiper#2425]
This is a (multiple allowed):
* [x] bug (s)
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: Windows, TouchScreen, Surface Pro 4, Mouse, TypeCover TouchPad
* Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/

### What you did
simulateTouch simply don't work, upgrading to version 4.1.0, you can also see the resulting bug in the demos section of the swipers own website.
If you load script related to a previous version, lets say 4.0.7 as I've tried that, it get's back to working state.
I think there are unpointed changes in each version as you release new version. These changes should be announced.

### Expected Behavior
It is expected to switch between slides with mouse click and drag.

### Actual Behavior
If you click and drag with mouse/touch pad , nothing will ever happen. Hopefully the touch functionality is still working.

Another thing that is bothering, in no versions, the scroll bar is draggable with mouse.
Sample code from the API is : 
`var mySwiper = new Swiper('.swiper-container', {
  scrollbar: {
    el: '.swiper-scrollbar',
    draggable: true,
  },
});`
but in no version it will not work.
You cannot click or click/drag with mouse / touchpad on the scrollbar.
But again if you touch the scroll bar and drag it or click some where on it's range line, it will work.

**Comment by nolimits4web** [comment]
Does it related to #2410? Looks like it was fixed, no?

Edge/MS touch gestures implementation is very annoying, is there any chance to test it without actual Surface device?

**Comment by mhshakouri** [comment]
I am currently using it in chrome.
There is no problem with touch events.
The problem is with MouseDrag actions in desktop. I'm using the latest version of Chrome Browser.

It's all fine under Firefox (latest)
and Edge (latest) including IE (latest).

Let me re cap:

On Chrome:
- No mouse Drag is working (on the slides - container)
- the Scroll bar is only draggable with touch screen
- the slides can be dragged and thus changed (swiped) with touch

On fireFox:
- Mouse drags work just fine  (on the slides - container)
- the Scrollbar is only draggable with touch screen

On Edge:
- Mouse drags work just fine (on the slides - container)
- The scrollbar is only draggable with touch screen

on IE
- EVERYTHING IS FINE :|

**Comment by mhshakouri** [comment]
I'm eager to help you on this. 
Please inform me on anything I could do.
I'll test it on non surface device as soon as possible as I have access to one.

**Comment by mhshakouri** [comment]
UPDATE:
I've had the chance to test the case against two other devices.
1. ASUS NON-Touch Laptop:
It's all fine. Everything is working as expected.
2. ACER Touch Display Laptop:
Just the same as the above conditions I am experiencing with my Surface Pro 4

# Where I think the problem is:
In swiper.js file, line 5086
`    swiper.scrollbar.dragEvents = (function dragEvents() {
      if ((swiper.params.simulateTouch === false && !Support.touch)) {
        return {
          start: 'mousedown',
          move: 'mousemove',
          end: 'mouseup',
        };
      }
      return touchEvents;
    }());`
I think there is something wrong in here.
It is only handling either mouse or touch events, not combined.
Again It's my guess but I still am happy if I could be of any help

**Comment by mhshakouri** [comment]
I think I've just came to a solution for this problem
created the right PR.
