### ISSUE TITLE
iOS next slide bleeds into current slide frame until the page is scrolled. video attached.

### ISSUE THREAD

**Issue by dantheman213** [nolimits4web/Swiper#2426]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.
* Platform/Target and Browser Versions: iOS (iPhone), Chrome, Safari
* Live Link or JSFiddle/Codepen or website with issue: Main banner, home page, here, no need to scroll or do anything just load this URL and swiper is used in the header of the index page. 

https://staging.dualpath.net/

### What you did
Vanilla implementation of this library. It works on every device flawlessly, except for iOS, specifically iPhones.

### Expected Behavior
Transitions perfectly from slide to slide on mobile. 

### Actual Behavior
A slide will have some bleeding into the next slide. It will correct itself when you start scrolling the page. Please see attached video that is inside of ZIP file because GitHub wouldn't let me share otherwise.

Chrome on iOS:
[ScreenRecording_01-14-2018 20-23-25.zip](https://github.com/nolimits4web/Swiper/files/1630279/ScreenRecording_01-14-2018.20-23-25.zip)

Safari on iOS.
[ScreenRecording_01-14-2018 20-15-39.zip](https://github.com/nolimits4web/Swiper/files/1630288/ScreenRecording_01-14-2018.20-15-39.zip)

It works fine on Chrome for Android. Desktop also works fine.

Thanks for the assistance!
Dan

**Comment by nolimits4web** [comment]
Weird, try:
- disable `breakpoints: {480: {…}}` parameter, no much sense in such
- try to add in your CSS `.swiper-slide{ box-sizing: border-box }`

From what i see it detects wrong swiper size. Make sure you init after all DOM manipulations you may have related to Swiper, otherwise call its `.update()` method after

**Comment by dantheman213** [comment]
Thanks for getting back to me so quickly. I went ahead and tried out some of your suggestions but didn't have luck in a 'simple' fix. I disabled the breakpoints rule for the main header and added the border-box rule you suggested, but that didn't seem to help. I don't believe I'm doing additional DOM manipulations to the Swiper elements but did have success using a 1 second timeout calling the .update() method. This does work but I'm not 100% convinced this problem is being caused by custom app code. However, if you're not seeing this elsewhere then it may be a good indication of such a thing. Either way -- thank you for your assistance.

**Comment by nolimits4web** [comment]
This is 100% because of some custom code, as you may see all demos work fine. You can also try to set `observer: true` and `observeParents: true` so swiper will try to update itself when something changed with its element or with its parents
