### ISSUE TITLE
npm install on windows 7 NODE_ENV error and dom7/dist/dom7.modular couldn't be resolved

### ISSUE THREAD

**Issue by benny-ben** [nolimits4web/Swiper#2427]
This is a:
* [x] bug?

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Windows 7 64-bit

### What you did
I tried to install Swiper in Windows 7 64-bit with npm@5.6.0 and node@v9.4.0, gulp-cli@2.0.0 is globally installed.

`
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:dev' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prebuild:dev', 'build:dev', 'postbuild:dev' ]
5 info lifecycle swiper@4.0.7~prebuild:dev: swiper@4.0.7
6 info lifecycle swiper@4.0.7~build:dev: swiper@4.0.7
7 verbose lifecycle swiper@4.0.7~build:dev: unsafe-perm in lifecycle true
8 verbose lifecycle swiper@4.0.7~build:dev: PATH C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Bob\Dropbox\Development\vhosts\mongoose-project\vanilla\themes\JointsWP\node_modules\node-sass\node_modules\.bin;C:\Users\Bob\Dropbox\Development\vhosts\mongoose-project\vanilla\themes\JointsWP\node_modules\.bin;C:\Users\Bob\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs;C:\Users\Bob\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle swiper@4.0.7~build:dev: CWD: C:\Users\Bob\Dropbox\Development\plugin\Swiper
10 silly lifecycle swiper@4.0.7~build:dev: Args: [ '/d /s /c', 'NODE_ENV=development gulp build' ]
11 silly lifecycle swiper@4.0.7~build:dev: Returned: code: 1  signal: null
12 info lifecycle swiper@4.0.7~build:dev: Failed to exec build:dev script
13 verbose stack Error: swiper@4.0.7 build:dev: 'NODE_ENV=development gulp build'
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid swiper@4.0.7
15 verbose cwd C:\Users\Bob\Dropbox\Development\plugin\Swiper
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error swiper@4.0.7 build:dev: 'NODE_ENV=development gulp build'
22 error Exit status 1
23 error Failed at the swiper@4.0.7 build:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

But the answer I get is that "NODE_ENV" is not recognized as an internal or external command, operable program or batch file.

Then I tried to modify package.json with "scripts" this way:

`
...
"scripts": {
	"build:dev":  "set NODE_ENV=development && gulp build",
	"build:prod": "set NODE_ENV=production && gulp build",
	"dev":        "set NODE_ENV=development && gulp build && set NODE_ENV=development && gulp playground && set NODE_ENV=development && gulp server",
	"prod":       "set NODE_ENV=production && gulp playground && set NODE_ENV=production && gulp server",
	"lint":       "eslint .",
	"test":       "npm run lint && npm run build:dev"
},
...
`

Deleting node_modules folder and package-lock.json file and run again `npm install`. This way the installation looks good, but as far as I run:

`
$ npm run build:dev

swiper@4.0.7 build:dev C:\Users\Ben\Dropbox\Development\plugin\Swiper
set NODE_ENV=development && gulp build

[19:38:43] Using gulpfile ~\Dropbox\Development\plugin\Swiper\gulpfile.js
(node:23912) ExperimentalWarning: The http2 module is an experimental API.
[19:38:43] Starting 'js'...
[19:38:43] Starting 'less'...
'dom7/dist/dom7.modular' is imported by src\utils\dom.js, but could not be resolved â treating it as an external dependency
'dom7/dist/dom7.modular' is imported by src\utils\dom.js, but could not be resolved â treating it as an external dependency
[19:38:44] Finished 'js' after 1.11 s
[19:38:44] Finished 'less' after 1.52 s
[19:38:44] Starting 'build'...
[19:38:44] Finished 'build' after 29 Î¼s
`

When it gets to "starting less" the warning above appears and I can't see the build/ folder. I don't know if all this is normal; even when I run

`
$ npm run build:prod

swiper@4.0.7 build:prod C:\Users\Ben\Dropbox\Development\plugin\Swiper
set NODE_ENV=production && gulp build

[19:44:39] Using gulpfile ~\Dropbox\Development\plugin\Swiper\gulpfile.js
(node:24064) ExperimentalWarning: The http2 module is an experimental API.
[19:44:39] Starting 'js'...
[19:44:39] Starting 'less'...
'dom7/dist/dom7.modular' is imported by src\utils\dom.js, but could not be resolved â treating it as an external dependency
'dom7/dist/dom7.modular' is imported by src\utils\dom.js, but could not be resolved â treating it as an external dependency
[19:44:41] Finished 'js' after 1.11 s
[19:44:41] Finished 'less' after 1.5 s
[19:44:41] Starting 'build'...
[19:44:41] Finished 'build' after 22 Î¼s
`

I get the same notice/warning, but in this case it looks like the files in dist/ folder get updated without problems.

**Comment by benny-ben** [comment]
I tried last commit [7d415b7](https://github.com/nolimits4web/Swiper/commit/7d415b772434ded3e704dcfc98ca86a2a85fbb1f) and the install is ok:

<pre>
$ npm install
added 780 packages in 27.417s
</pre>

Everything is fine even when I run:

<pre>
$ npm run build:dev

> swiper@4.1.0 build:dev C:\Users\Ben\Dropbox\Development\plugin\Swiper
> cross-env NODE_ENV=development gulp build

[20:26:02] Using gulpfile ~\Dropbox\Development\plugin\Swiper\gulpfile.js
(node:472) ExperimentalWarning: The http2 module is an experimental API.
[20:26:02] Starting 'js'...
[20:26:02] Starting 'less'...
[20:26:02] Finished 'less' after 292 ms
[20:26:03] Finished 'js' after 1.77 s
[20:26:03] Starting 'build'...
[20:26:03] Finished 'build' after 21 Î¼s
</pre>

Warnings doesn't appear anymore and the build folder has been created.

Instead when I run:

<pre>
$ npm run build:prod

> swiper@4.1.0 build:prod C:\Users\Ben\Dropbox\Development\plugin\Swiper
> cross-env NODE_ENV=production gulp build

[20:26:23] Using gulpfile ~\Dropbox\Development\plugin\Swiper\gulpfile.js
(node:46500) ExperimentalWarning: The http2 module is an experimental API.
[20:26:23] Starting 'js'...
[20:26:23] Starting 'less'...
'dom7/dist/dom7.modular' is imported by src\utils\dom.js, but could not be resolved â treating it as an external dependency
'dom7/dist/dom7.modular' is imported by src\utils\dom.js, but could not be resolved â treating it as an external dependency
[20:26:24] Finished 'js' after 1.14 s
[20:26:24] Finished 'less' after 1.54 s
[20:26:24] Starting 'build'...
[20:26:24] Finished 'build' after 21 Î¼s
</pre>

Warnings are there again, even if files seem to update correctly.

**Comment by nolimits4web** [comment]
Just ignore these warnings

**Comment by benny-ben** [comment]
Ok thank you!
