### ISSUE TITLE
Pagination bullet click inconsistent result (cross platform)

### ISSUE THREAD

**Issue by SSiertsema** [nolimits4web/swiper#2428]
http://idangero.us/swiper/demos/180-nested.html

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Version released on http://idangero.us/swiper/demos/180-nested.html.
* Platform/Target and Browser Versions: Windows + Chrome, Windows + Edge, probably cross platform.
* Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/180-nested.html.

### What you did
As user i go to : http://idangero.us/swiper/demos/180-nested.html
I click around on the pagination bullets for a while.

### Expected Behavior
I Expect that swiper is navigating to the appropriate slide every time I try to navigate.

### Actual Behavior
Sometimes swiper is navigating to other slides.

**Comment by nolimits4web** [comment]
How to replicate "**Sometimes** swiper is navigating to other slides"?

**Comment by SSiertsema** [comment]
Hey Vladimir. Unfortunately I could not find a pattern :S
I can make a video if you like.

Best Regards,
Sven

Van: Vladimir Kharlampidi
Verzonden: maandag 15 januari 2018 16:23
Aan: nolimits4web/Swiper
CC: sven-siertsema; Author
Onderwerp: Re: [nolimits4web/Swiper] Pagination bullet click inconsistent result(cross platform) (#2428)

How to replicate "Sometimes swiper is navigating to other slides"?

**Comment by nolimits4web** [comment]
Video will be good

**Comment by nolimits4web** [comment]
You can put it here

**Comment by SSiertsema** [comment]
[Reproduction-inconsistent-navigation.zip](https://github.com/nolimits4web/Swiper/files/1632755/Reproduction-inconsistent-navigation.zip)

**Comment by nolimits4web** [comment]
On your video i see everything is correct, where is the issue?

**Comment by SSiertsema** [comment]
[cut-2.zip](https://github.com/nolimits4web/Swiper/files/1636084/cut-2.zip)

Cut-2, slower pace: on 39seconds I click on 3rd bullet. Swiper is navigating to slide 1.

**Comment by primat** [comment]
I can confirm this bug although it's hard to reproduce since there doesn't appear to be a pattern. Happens with both arrows and pagination and more often when click before the animation stops.

**Comment by SSiertsema** [comment]
I've implemented swiper with 3 items. It seems that the bug occurs more often on 3 items. Maybe quantity has an impact on this bug.

**Comment by primat** [comment]
Not sure how to turn off animations but one thing I noticed is that when the "bug" occurs, the slide only moves one forward or one backward. I also noticed that shortSwipes is very sensitive. So I disabled shortSipes and been trying to reproduce the problem and haven't been able to. So maybe the issue is just that shortSwipes is too sensitive for our shaky hands?

**Comment by Nikolay01** [comment]
I had the same issue. I noticed that swipe event works over bullets too, and swiper navigates to other slides because of mini swiping move while you pressing bullet. To solve this issue I simple moved bullets out of .swiper-container

**Comment by jhadenfeldt** [comment]
The solution @Nikolay01 used unfortunately doesn't really work when using multiple sliders though.
Is there any plan to ignore swipes on bullets?

**Comment by Etto91** [comment]
solved by changing touchEventsTarget to 'wrapper'

**Comment by csbug** [comment]
i am using latest version of swiper but facing same issue -  Sometimes swiper is navigating to other slides.

**Comment by 1de** [comment]
same here. behaves like @SSiertsema mentioned.

@csbug: the solution of @Etto91 with 'touchEventsTarget' set to 'wrapper' seems to work (for me and till now - i'm not able to reproduce)
