### ISSUE TITLE
fade effect not working, first slide "slides left" and no other slide appears.

### ISSUE THREAD

**Issue by amouratoglou** [nolimits4web/Swiper#2430]
Hey guys I use swiper a lot, I simply love it.
I'm experiencing a problem with the fade effect, is not working.
are they any known issues like this, maybe I'm doing something wrong?
-The slides have a background image each.

### What you did
```
        var swiper1 = new Swiper('.swiper-container-hero', {
       slidesPerView: 1, 
fadeEffect: {
    crossFade: true
  },    
  effect: 'fade',
   loop: true,
      allowTouchMove: false

    });
```

and this is my HTML

```
   <div class="swiper-container swiper-container-hero">

    <div class="swiper-wrapper">

      <div class="swiper-slide" style="background:url(1.jpg)">             </div>
      <div class="swiper-slide" style="background:url(2.jpg)">             </div>
      <div class="swiper-slide" style="background:url(3.jpg)">             </div>
      <div class="swiper-slide" style="background:url(4.jpg)">             </div>

      </div>
      </div>

```

### Expected Behavior
Fade effect is supposed to trigger but not happening.

### Actual Behavior
First slide slides to the left, and no other slide appears. then after a while it appears again, of the 4 slides only slide 1 shows.

no JS errors in the console.

If I remove this code it works as normal without the fade effect.

```
 crossFade: true
  },    
  effect: 'fade',
```

**Comment by nolimits4web** [comment]
But you can see it is working here http://idangero.us/swiper/demos/220-effect-fade.html right? Something probably wrong on your side, need live example with the issue

**Comment by amouratoglou** [comment]
Sorry I know. here is the link https://goo.gl/sdTFeF

**Comment by nolimits4web** [comment]
Update Swiper to latest 4.x version
