### ISSUE TITLE
SlideChange event would run twice

### ISSUE THREAD

**Issue by thoamsy** [nolimits4web/Swiper#2435]
This is a Bug🐛
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: macOS
* [CodePen](https://codepen.io/QueenYoung/pen/goBmEP)
**Please remember to open the console!**

### What you did
I add a `slideChange` in the swiper, to do something.

### Expected Behavior
I think the `slideChange` event would only run once every slide change.

### Actual Behavior
from _slide 1_ to _slide 2_, the event will emit twice.

**Comment by nolimits4web** [comment]
It is intended behavior because of `loop`, with loop there are duplicated slides that may be changing when needed, so you have a slideChange event
