### ISSUE TITLE
Swiper does not calculate correctly slide height in vertical mode

### ISSUE THREAD

**Issue by casph** [nolimits4web/swiper#2437]
related to https://github.com/nolimits4web/Swiper/issues/2017

I'm using last stable version of swiper in my wordpress page, every slide height is set to 1312px instead of it's real height.

You can se the page here, in the events section:
https://aslmltpsebp02.datamanagement.it/icom/

**Comment by nolimits4web** [comment]
I see correct swiper sizes on your link

**Comment by nolimits4web** [comment]
<img width="1198" alt="sizes" src="https://user-images.githubusercontent.com/999588/35185173-120982e6-fe11-11e7-8792-8ae6f793ce9a.png">

**Comment by mjot** [comment]
Same Problem here. The height isn't calculated right, and all slides are visible.
Please see the following Pen: [https://codepen.io/emjay/pen/VygpPM](url)

**Comment by nolimits4web** [comment]
@mjot this is actually how CSS works https://codepen.io/anon/pen/QaYpqX

**Comment by mjot** [comment]
I thought swiper would calculate the needed height and sized the swiper-container as needed. Same as in the horizontal Version.I can't give a fixed height, because when the screen size is smaller, the text needs more height. How should I do this with a fixed height?

**Comment by nolimits4web** [comment]
Then how Swiper would do it. Swiper's autoHeight at the moment is not support for vertical direction. As an option you may use `overflow: auto` on swiper slide to do the scrolling inside of slide in case there is a lot of content in it

**Comment by mjot** [comment]
Okay, that's no good solution. I think I will take another path. Thanks for your reply!
