### ISSUE TITLE
Slide change event inconsistencies

### ISSUE THREAD

**Issue by marfire** [nolimits4web/swiper#2438]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target: Chrome

I recently switched from Swiper 3 to Swiper 4. The `onSlideChangeStart` event no longer exists. I thought I could achieve the same thing with `slideChangeTransitionStart`, but that event acts differently. It fires if the slide is *moved*, even if it doesn't change (e.g. if it is swiped a bit, but not enough to change the slide).

I assumed that `slideNextTransitionStart` would do the same, since it's documented as "Same as "slideChangeTransitionStart" but for "forward" direction only". But it actually behaved as I originally expected, only firing when the slide is actually changed.

This inconsistency is presumably unintended. I would hope that `slideChangeTransitionStart` can be altered to fire only when the slide is actually changed.

**Comment by nolimits4web** [comment]
JSFiddle with the issue would be great

**Comment by marfire** [comment]
[Here you go](https://codepen.io/anon/pen/BJMOYv).

If you open the console you'll see that dragging a bit and then rebounding produces the `slideChangeTransition` events, even though the slide hasn't changed. If you drag enough to change the slide, both sets of events fire.

This reveals another bug as well. If you drag a bit and rebound from `Slide 2` to `Slide 1` the `slideNextTransition` events fire, even though you're going backwards (and, as above, not changing the slide).

In my opinion the correct behavior is to only fire the events when the slide is actually changing. That matches the behavior of Swiper 3 and is far more useful.
