### ISSUE TITLE
Swiper "jumping" to the incorrect slide at beginning of swipe

### ISSUE THREAD

**Issue by primat** [nolimits4web/Swiper#2440]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: MAC OSX sierra, Google Chrome v63
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/XVoqGa?editors=1111

### What you did
Create a Slider with 8 slides, 5 sliders per container and 5 sliders per group. Swipe to the second group. Then, gently start swiping again and notice that the slide on the left quickly "jumps" from slide 6 to slide 4 immediately after beginning the swipe.

### Expected Behavior
Swiper should swipe the following groups (where the numbers are the indexes of the slides) and the arrow represents a swipe:
[0,1,2,3,4] -> **[5,6,7,0,1]** -> [2,3,4,5,6] -> [7,0,1,2,3] -> ...

### Actual Behavior
On the second swipe, Swiper quickly moves the slides so that the group contains the 5 last slides of the whole set.
[0,1,2,3,4,] -> **[5,6,7,0,1]** upon swiping, the container resets to the following set: **[3,4,5,6,7]**

**Comment by nolimits4web** [comment]
It is intended behavior, pass `loopFillGroupWithBlank: true` to fill group with blank slides in this case

**Comment by primat** [comment]
That's too bad. I'll have to use another library then. Thanks for the reply and good luck with Swiper.
