### ISSUE TITLE
Add TypeScript support (and how to)

### ISSUE THREAD

**Issue by odahcam** [nolimits4web/swiper#2441]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)

* Swiper Version: `4.1.0`
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/angular-swiper-gallery

### Expected Behavior
Swiper should have some explanations on how to use it with TypeScript, I know it shouldn't be a focus, but Angular, for example, has nothing like Swiper and using it with Angular seems really hard.

### Actual Behavior
Things in Swiper docs didn't work in Angular with TypeScript, I had a lot of trouble with typings and I think that anyone that access that StackBlitz demo, will notice the typing issues.

I've searched for another issues like this, but I found nothing usefull.

I hope I'm doing something wrong that could be explaned in the docs, but in the worst scenário this could be a typing issue.

**Comment by odahcam** [comment]
I have an issue open at @DefinitelyTyped/DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23056) for adding the v4 TypeScript typings.

**Comment by atilkan** [comment]
@odahcam Did you manage to make it work with webpack and ts-loader?

**Comment by odahcam** [comment]
Not 100% yet! Swiper is very "peculiar" about it's moduling system and etc and I'm very new to TS.

**Comment by atilkan** [comment]
@odahcam Let me know if you can. Thanks.

**Comment by odahcam** [comment]
@atilkan I made it work with Angular 6, but I'm not using Webpack now. Do you got any news?

**Comment by atilkan** [comment]
I used by old way,  included build script.

**Comment by odahcam** [comment]
What tech are you using with your TS? Angular?

**Comment by atilkan** [comment]
@odahcam Sorry for late reply. i use vuejs with ts. But not related to swiper.

**Comment by odahcam** [comment]
I got it working after doing some work on the `@types` library, now everything works fine, but Swiper stills not in the Angular way, so using it can be a little strange sometimes.

**Comment by atilkan** [comment]
@odahcam
Can you share?

**Comment by odahcam** [comment]
Of course! Maybe I can create a StackBlitz demo, but basically I imported Swiper trough the `esm` bundle and instantiated a Swiper instance on my Swiper container (obtained via `ViewChild`) on the `ngAfterViewInit` hook.
