### ISSUE TITLE
API docs shows wrong keyname

### ISSUE THREAD

**Issue by odahcam** [nolimits4web/swiper#2442]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0

![image](https://user-images.githubusercontent.com/3942006/35177522-4020a164-fd67-11e7-8a4d-bb01b6bf97f3.png)

As you can see, the keyname for the `flipEffect` parameter is wrong.

**Comment by odahcam** [comment]
As said in https://github.com/nolimits4web/Swiper/issues/2408 we aren't able to fix the docs, so I'm wating for who can. 😄

**Comment by nolimits4web** [comment]
Fixed this. For further issues, PR can be sent to https://github.com/nolimits4web/swiper-website

**Comment by odahcam** [comment]
Awesome, can I suggest to put something on docs like that? (taken from Vue.js docs)

![image](https://user-images.githubusercontent.com/3942006/35183309-0af1cb26-fdcb-11e7-9409-ec93af696b3c.png)
