### ISSUE TITLE
Adding css to slides breaks after certain point!

### ISSUE THREAD

**Issue by omeith** [nolimits4web/swiper#2443]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/LeqRBe

### What you did
The current slide in the middle gets the extra css class ".big"
after sliding the class gets removed

### Expected Behavior
It should work for all slides.

### Actual Behavior
After reaching the 3. slide the css gets addet but you cant see it .
For the first and second slide its working.

**Comment by nolimits4web** [comment]
There are duplicated slides in loop mode, no sense to use IDs on elements, use CSS classes instead
