### ISSUE TITLE
custom prev button jumps a few slides back

### ISSUE THREAD

**Issue by DanielRuf** [nolimits4web/swiper#2445]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Chrome 63 on macOS 10.12/10.13
* Live Link or JSFiddle/Codepen or website with isssue: Will probably prepare one

### What you did
We created a customer Swiper with some elements which are in an element with overflow: hidden.
We set `slidesPerView: 'auto'` because the client can see multiple slides at once. It is some cross selling element.

### Expected Behavior
When clicking the custom prev button it should always just go one slide backwards and set the active class on the right slide.

### Actual Behavior
The prev button sometimes jumps a few slides back and sets the active class on the wrong slide before the slide which should actually have it.

So far I did not directly find an issue which describes this behavior/bug.

**Comment by nolimits4web** [comment]
This is weird, would be really good to see example, maybe some isolated JSFiddle?

**Comment by DanielRuf** [comment]
We'll try to provide some. cc @MaximilianUE

**Comment by DanielRuf** [comment]
So far it only happens when I go to the last slide and then click the prev button.

**Comment by DanielRuf** [comment]
Did some further testting
```
  console.log('snapgridlength',snapGrid.length)
  if (snapGrid.indexOf(translate) >= 0) {
    snapIndex = snapGrid.indexOf(translate);
    console.log('ai 4', snapIndex);
  } else {
    snapIndex = Math.floor(activeIndex / params.slidesPerGroup);
    console.log('ai 5', snapIndex);
  }
  if (snapIndex >= snapGrid.length) { snapIndex = snapGrid.length -1; }
  if (activeIndex === previousIndex) {
    if (snapIndex !== previousSnapIndex) {
      swiper.snapIndex = snapIndex;
      console.log('ai 6', snapIndex);
      swiper.emit('snapIndexChange');
    }
    return;
  }
```

Clicking the next button in a small viewport results in
```
snapgridlength 1
ai 4 0
ai 6 0
snapgridlength 7
ai 4 1
snapgridlength 7
ai 4 2
snapgridlength 7
ai 4 3
snapgridlength 7
ai 4 4
snapgridlength 7
ai 4 5
snapgridlength 7
ai 4 6
ai 6 6
```

Clicking the prev button after this results in
```
snapgridlength 7
ai 4 4
```

**Comment by DanielRuf** [comment]
Everything above `snapGrid.length` is problematic as it seems.

**Comment by DanielRuf** [comment]
It is reproducible here:
https://danielruf.github.io/swiper-builder/
instructions:
* enable `navigation`
* enable `slidesPerViewAuto`
* add following styles in the browser dev tools:
```
.swiper-slide {
    width: 200px !important;
}
```

Clicking right possible: 5 times.
Clicking left possible from the right edge: 4 times.

![bildschirmfoto 2018-01-23 um 11 31 39](https://user-images.githubusercontent.com/827205/35271009-0981a5fa-0031-11e8-896a-8e048b89a76f.png)

**Comment by DanielRuf** [comment]
cc @MaximilianUE
