### ISSUE TITLE
Navigation arrows doesn't work after zoom-out image (touch)

### ISSUE THREAD

**Issue by odahcam** [nolimits4web/swiper#2449]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: Chrome Android, Moto G4.
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/angular-swiper-gallery

### What you did
See example.

### Expected Behavior
Arrows should work.

### Actual Behavior
When I touch arrows, its like I'm touching the image, nothing happens to arrows.

**Comment by nolimits4web** [comment]
Looks like same as #2460

**Comment by odahcam** [comment]
Unfortunatelly it is not. After zoom-in some image, I'm unable to use navigation arrows in mobile devices, no matter how I touch'em they do nothing. I can say that seems like `touchEventsTarget: 'wrapper'` didn't help in this case.

**Comment by nolimits4web** [comment]
https://www.dropbox.com/s/p2lbndslbq5s9k7/zoom-nav.mov?dl=0

**Comment by odahcam** [comment]
yeah, as i said, using a cursor everything works fine, but with a **real** touch device things don't work as they should.

**Comment by nolimits4web** [comment]
It is not a cursor, it is an iPhone simulator = real touch events, i can do totally the same on real device

**Comment by odahcam** [comment]
@nolimits4web Also, I've tested http://idangero.us/swiper/demos/400-zoom.html and it shows the same behavior shown in my last comment's video.

Device: Moto G4 Play
SO: Android 6.0.1
Browser: Chrome (64.0.3282.123)
