### ISSUE TITLE
possible to sync scrollposition / drag position with multiple Swipers?

### ISSUE THREAD

**Issue by DanielRuf** [nolimits4web/swiper#2452]
So far we connect two Swiper instances using
```
sliderGallery.controller.control = sliderGalleryText;
sliderGalleryText.controller.control = sliderGallery;
```

But they are not 100% synced when dragging / scrolling as the other non-dragged/scrolled instance moves a bit after the other.

Is it possible to track the horizontal drag / scroll position and keep them 100% in sync as someone would control both at the same time?

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

**Comment by nolimits4web** [comment]
Check the `controller.by` parameter, it can sync it by slides or container in general

**Comment by DanielRuf** [comment]
> Check the controller.by parameter, it can sync it by slides or container in general

Mh, maybe it was because of something else. It seems to work now.
