### ISSUE TITLE
Zoom not working with virtual slides

### ISSUE THREAD

**Issue by kalimantos** [nolimits4web/swiper#2453]
Zoom works only with the first slides, then it doesn't work anymore. I suppose it's because in zoom component is used the `slides` array with `activeIndex` without keeping in mind of the `zoom.from` property. Also it seems zoom events are not attached to new slides.

**Comment by DanielRuf** [comment]
Probably missing event listeners. Can you test if the `slides` array is different when using virtual slides or not changing at all?

**Comment by kalimantos** [comment]
While in virtualized mode the slides array has only in DOM slides, not all. It's because of this i was supposing the `activeIndex` is not enough and it require to use the `zoom.from` property to have a relative index. As events are attached only first time, every time a slide is appended it doesn't have required handlers for the zoom.

**Comment by DanielRuf** [comment]
Possible workaround: try the `disable` and `enable` method of the zoom component which removes and adds eventlisteners.

Reference: https://github.com/nolimits4web/swiper/blob/master/src/components/zoom/zoom.js

**Comment by kalimantos** [comment]
Yes, i already did a workaround adding that code to the `slideChangeTransitionEnd` event.
It's pretty rough.
```javascript
let oldIndex; // here i put my first slide index
...
slideChangeTransitionEnd: function() {
  const { virtual, zoom: { gesture, disable, enable }, slides, activeIndex } = swiper;
  if (oldIndex === activeIndex) return;
  disable();
  enable();
  oldIndex = activeIndex;
  gesture.$slideEl = slides.eq(activeIndex - virtual.from);
  gesture.$imageEl = gesture.$slideEl.find('img, svg, canvas');
  gesture.$imageWrapEl = gesture.$imageEl.parent(`.${swiper.params.zoom.containerClass}`);
},
...
```
for the moment this work, but cold be better if that is resolved to the root of the problem.
Thank you for the quick response!

**Comment by DanielRuf** [comment]
Normally the source should not be changed. You can listen for the swiper events.

**Comment by kalimantos** [comment]
Yes but this is a bug, right? So the workaround I've implemented shouldn't be there. 
The bug should be solved inside code of the swiper zoom component, right? 🤔

**Comment by DanielRuf** [comment]
Exactly. Or in the `virtual` component.

**Comment by kalimantos** [comment]
Thank you @nolimits4web !!!!  👏👏
Any idea when this fix will be released on npm?
