### ISSUE TITLE
Trapped inside vertical swiper when scrolling up

### ISSUE THREAD

**Issue by hacknug** [nolimits4web/swiper#2457]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.1.0
* Platform/Target and Browser Versions: macOS 10.13.2, Safari 11.2 Release 48 (WebKit 13606.1.2.2).
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
```js
var swiper = new Swiper('.swiper-container', {
    direction: 'vertical',
    slidesPerView: 5,
    centeredSlides: true,
    simulateTouch: false,
    mousewheel: {
      forceToAxis: true,
      releaseOnEdges: true,
      invert: true
    },
    keyboard: true,
    freeMode: true,
    freeModeSticky: true
  })
```

### Expected Behavior
I want users to be able to navigate through the slides using their mouses/trackpads. Scrolling over the swiper should do that. Reaching the last slide should allow them to keep scrolling through the page. Going back up should let them navigate through the slides backwards. Reaching the first slide should let them keep scrolling through the page upwards.

### Actual Behavior
I want users to be able to navigate through the slides using their mouses/trackpads. Scrolling over the swiper should do that (it does). Reaching the last slide should allow them to keep scrolling through the page (it does). Going back up should let them navigate through the slides backwards (it does). Reaching the first slide should let them keep scrolling through the page upwards (**it doesn't**).

### How To Fix It (?)
This line seems to be the culprit: https://github.com/nolimits4web/swiper/blob/e28632b53866fba15a3b34208ecee257506078b7/src/components/mousewheel/mousewheel.js#L170

Adding `position === swiper.minTranslate()` to the conditional seems to fix it in my case. Not sure if this would break something else.

Let me know if you'd like me to open a PR with the change or do something else.

**Comment by DanielRuf** [comment]
We also have this issue even when `releaseOnEdges: true` is set.

**Comment by DanielRuf** [comment]
But we have the issue with horizontal Swiper instances.

**Comment by shashank1010** [comment]
I have the same issue. To add to that, as I'm scrolling through the page once the swiper container hits the cursor, the page scroll stops, the next slide event is also triggered.

The expected behaviour would be to take control of the mousewheel once explicitly scrolling over the swiper container.
