### ISSUE TITLE
When using coverflow in Firefox 58.0 the transition is not smooth.

### ISSUE THREAD

**Issue by marten83** [nolimits4web/swiper#2459]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: macOS - Firefox 58.0

### What you did
```javascript
var swiper = new Swiper('.swiper-container', {
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows : true,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });
```
### Expected Behavior
When using "coverflow" in other browser than Firefox for example Chrome the transition between slides is smooth and work as expected.

### Actual Behavior
In Firefox (58.0) the transition is choppy. The same behavior occurs on your own "topslider" at: http://idangero.us/swiper/. The first slides is fine but after some transition the problem starts. This was working fine before updating Firefox to 58.0

**Comment by nolimits4web** [comment]
Issue with FF itself, something got broken in it. If you disable 3d-related CSS rules, it works normal, but without 3d effect
