### ISSUE TITLE
Navigation arrows not stopping click propagation

### ISSUE THREAD

**Issue by odahcam** [nolimits4web/swiper#2460]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: Chrome.
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/angular-swiper-gallery?file=app%2Fngx-popper%2Fngx-popper.component.ts.

### What you did
Implemented zoom, navigation and base carousel.

### Expected Behavior
I expect to click in the navigation and just navigate not do something with the slide.

### Actual Behavior
When I click fast in the navigation buttons zoom is triggered in the slide (very awkward), probably because the navigation buttons doesn't stops events propagation thru `event.stopPropagation()`.

**Comment by nolimits4web** [comment]
You can just set `touchEventsTarget: 'wrapper'`

For future issue, please provide vanilla JS example, it is hard to track where the issue is
