### ISSUE TITLE
Server side rendering - window is not defined

### ISSUE THREAD

**Issue by adrienlamotte** [nolimits4web/swiper#2465]
Hello !

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: Server side (NodeJS)

### What you did
My app (Angular 5) use server side rendering.
On server side, I have an error : 
```
ERROR ReferenceError: window is not defined
    at Dom7.css (E:\Project\dist\server.js:133805:22)
    at new Swiper (E:\Project\dist\server.js:136806:95)
```

That seems to point to that line of code (at least) : 
```
if (this[0]) { return window.getComputedStyle(this[0], null).getPropertyValue(props); }
```

### Expected Behavior
No errors on server side

### Actual Behavior
document, window, etc... should be protected for SSR.

Thank you !

**Comment by yacineblr** [comment]
Same for me...

**Comment by nolimits4web** [comment]
Ok, so it is actually comes from Dom7, Swiper has fix for this:
https://github.com/nolimits4web/swiper/blob/master/src/utils/window.js
https://github.com/nolimits4web/swiper/blob/master/src/utils/document.js

Will fix it in Dom7
