### ISSUE TITLE
IE11: Fat arrow function causing syntax error

### ISSUE THREAD

**Issue by esvi** [nolimits4web/swiper#2466]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0.
* Platform/Target and Browser Versions: IE11.

Hi,

I have encountered a bug in IE11 that's causing every page with a swiper to break. Apparently the browser doesn't like fat arrow functions. 

I get a syntax error which leads to line `55` in `swiper.esm.js`:

`Object.keys(Methods).forEach((methodName) => {
  $.fn[methodName] = Methods[methodName];
});`

I could not find a similar issue on here. Is there a chance this can be fixed or could please you suggest a workaround?

**Comment by nolimits4web** [comment]
`swiper.esm` module must be transpiled to ES5. It said here http://idangero.us/swiper/get-started/ in the end
