### ISSUE TITLE
Navigation dots are not working properly

### ISSUE THREAD

**Issue by Vervinsky** [nolimits4web/swiper#2467]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0

When you switch slide using pagination dot you may be navigated the wrong slide.

https://drive.google.com/open?id=1BppKItmN3O6O1HIztMX_7odBISHDM2D3
https://drive.google.com/open?id=1HPMNJr_VnQv9GAInX7TOe2CMAL5FBpFE

### What you did
Switch between first and second slide using dots

### Actual Behavior
https://drive.google.com/open?id=1BppKItmN3O6O1HIztMX_7odBISHDM2D3
https://drive.google.com/open?id=1HPMNJr_VnQv9GAInX7TOe2CMAL5FBpFE

**Comment by nolimits4web** [comment]
Can't open your links, they are protected

**Comment by Vervinsky** [comment]
Sorry, could you try once again, please?

**Comment by nonlinearcom** [comment]
Same here, did anyone managed to solve it?

I think It could be related to [this swiper issue](https://github.com/nolimits4web/swiper/issues/2467)
