### ISSUE TITLE
debouncing swiper instances

### ISSUE THREAD

**Issue by DanielRuf** [nolimits4web/swiper#2468]
So far the following snippet seems to be the best solution to debounce swiper instances.

```
    swiper.on('slideChangeTransitionStart',function() {
        swiper.allowSlidePrev = false;
        swiper.allowSlideNext = false;
      });

      swiper.on('slideChangeTransitionEnd',function() {
          swiper.allowSlidePrev = true;
          swiper.allowSlideNext = true;
      });
```

It might be a good idea to set this with some `debounce: boolean` option

**Comment by nolimits4web** [comment]
What do you mean by debouncing? Do you mean to prevent slide changing during transition?

**Comment by DanielRuf** [comment]
Right. Did not find any other solution ehich did not retrigger the trsnsitions on slides and slide elements.
