### ISSUE TITLE
Repeat animation of the first slide (loop)

### ISSUE THREAD

**Issue by NetGon** [nolimits4web/swiper#2471]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: Windows
* Live Link https://codepen.io/ArtStyles/pen/XZKQBo

### What you did
The problem occurs if there are two sliders with common navigation.
If you remove the code for general navigation, then there is no re-animation of the first slide.
```
s2.controller.control = s1;
s1.controller.control = s2;
```

**Comment by nolimits4web** [comment]
You need to consider duplicated active slide as well https://codepen.io/anon/pen/PQpWgB

**Comment by NetGon** [comment]
Thanks!
