### ISSUE TITLE
Nav Buttons not working with Bootstrap Tab Event

### ISSUE THREAD

**Issue by diegocardoso213** [nolimits4web/swiper#2472]
Hello guys,

I have one problem happening on a project and I cannot seem to find the proper answer/fix for it. I even found one kind of similar answer through the threads on this forum, but it wasn't the right fix for my issue.

My problem is described below, hope any of you can help me! =)

======================================================

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.3
* Platform/Target and Browser Versions: Multiple Platforms
* Live Link or JSFiddle/Codepen or website with isssue: http://imovel-cia.com.br/empreendimentos/canvas-alphaville-high-houses-apartamentos-270-338-metros-alameda-cauaxi-purus-em-frente-ao-alphaville-2

JS file used to initialize the slider: http://imovel-cia.com.br/assets/site/redesign/assets/js/imovel.js
### What you did
I have a group of tabs running throught this type of page, inside my project. It's a structured page, to be dynamically created for multiple instances of data (called from my DB). I have 4 tabs and the ones called "Plantas" and "Ilustrações" (2nd and 3rd), have Swiper sliders instances created for each one of them.

### Expected Behavior
All sliders inside those tabs should have their effect working properly (prev-next buttons).

### Actual Behavior
Only one of them do it. The other one is only draggable, but loses its pagination between images. (It happens when have Swiper Sliders created on both tabs. If only one has a slider instance, it works fine, but not when multiple tabs have sliders inside of them. =/

Thanks in advance, guys!

**Comment by diegocardoso213** [comment]
Hello guys!

Any help with that? Still struggling and cannot seem to find a fix for the problem of the multiple inicialization of the Swiper Slider inside this type of tabs =/

Thanks in advance!

**Comment by nolimits4web** [comment]
You have two swiper with same ID attribute, it is wrong and won't work. Use different IDs on them, and init them separately

**Comment by diegocardoso213** [comment]
Hello @nolimits4web !

Thanks for your input. As you can see now (UPDATED) on the pages that I've linked on my first post, I've tried to initialize them separately, but it won't work.

By the time that you've seen my code, I might have made a rollback, because this problem is kind of annoying and I'm trying everything that I can, but nothing seems to work.

Either way, I've updated everything to the most recent change that I've made, containing the solution that you've mentioned above.

Can you give me any insight around it?

**Comment by diegocardoso213** [comment]
Hello, any input since my last message? Thanks!

@nolimits4web
