### ISSUE TITLE
Serious performance regression with latest Firefox

### ISSUE THREAD

**Issue by Uriziel01** [nolimits4web/swiper#2474]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: Firefox 58.0 (it works like a charm with Firefox branch 56 and before that)
* Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/240-effect-coverflow.html

### What you did
Resize window to a width smaller than 1000px. Switched slides using mouse to the very end.

### Expected Behavior
The swiper should perform the same for each slide.

### Actual Behavior
Swiper performance drops significantly when negative translate3d on `swiper-wrapper` exceedes windows width so first slides work as intended and last slides are stuttering heavily.

**Comment by nolimits4web** [comment]
Was discussed here, can't do much here. It is FF issue

**Comment by Uriziel01** [comment]
OK then thank you for the response. I've reported the issue into bugzilla as well
[https://bugzilla.mozilla.org/show_bug.cgi?id=1436316](https://bugzilla.mozilla.org/show_bug.cgi?id=1436316)

**Comment by Uriziel01** [comment]
@nolimits4web This issue has been fully resolved in the latest Firefox Dev version **60.0b4**
