### ISSUE TITLE
parameter setWrapperSize set wrapper width of whole slider

### ISSUE THREAD

**Issue by fenyagg** [nolimits4web/swiper#2475]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: all

### What you did
`slidesPerView: 'auto',
setWrapperSize: true`

### Expected Behavior
should set the wrapper width to the size of the slides, not the whole slider

### Actual Behavior
But it set slider width, becouse
`swiper.virtualSize = Math.max(swiper.virtualSize, swiperSize) + offsetAfter;`

I want to center the slider container when there are not enough of them. 
Please tell me if there is another way.

**Comment by fenyagg** [comment]
I solved the problem through the sum of the widths of the slides and margin. But it seems to me that the parameter 'setWrapperSize' should do this

**Comment by nolimits4web** [comment]
It is actually can be achieved with pure CSS without `setWrapperSize` parameter:
```css
.swiper-container {
  display: flex;
}
.swiper-wrapper {
  margin-left: auto;
  margin-right: auto;
}
