### ISSUE TITLE
coverflow effect animation broken on Firefox 58 

### ISSUE THREAD

**Issue by wnvdhoven** [nolimits4web/swiper#2476]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: macOS, Firefox 58.0.1
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/addzycullen/pen/kXKKBZ

### What you did
See this codepen: https://codepen.io/addzycullen/pen/kXKKBZ

### Expected Behavior
I am expecting the animations to be shown as in for example Chrome 63

### Actual Behavior
The animations for the coverflow seem to be broken. I would expect the transitions to be smooth, but it seems they are done in the correct order, but without transition time which should make it look smooth.

**Comment by Uriziel01** [comment]
It was already discussed in [https://github.com/nolimits4web/swiper/issues/2474](https://github.com/nolimits4web/swiper/issues/2474) and its a Firefox bug, Swiper can't overcome this issue. My reported issue to mozilla's bugzilla is already evaluated so we should expect the fix in next dev channel Firefox version.
