### ISSUE TITLE
Bugs: Thumbs Gallery With Two-way Control

### ISSUE THREAD

**Issue by lautiamkok** [nolimits4web/swiper#2481]
There are bugs on the gallery options when you have the following settings:

```
var galleryTop = new Swiper('.gallery-top', {
    spaceBetween: 10,
    loop: true,
    grabCursor: true,
    freeMode: false,
    keyboard: {
      enabled: true,
    },
    navigation: {
      nextEl: '.swiper-gallery .swiper-button-next',
      prevEl: '.swiper-gallery .swiper-button-prev',
    },
  })
  var galleryThumbs = new Swiper('.gallery-thumbs', {
    loop: true,
    spaceBetween: 10,
    centeredSlides: false,
    slidesPerView: 'auto',
    touchRatio: 0.2,
    slideToClickedSlide: true
  })
  galleryTop.controller.control = galleryThumbs
  galleryThumbs.controller.control = galleryTop
```

It gets strange behaviours and the thumbnail does not co-respond with the top gallery.

Could you please take a look?

I just added some extra options from the demo here https://github.com/nolimits4web/Swiper/blob/master/demos/300-thumbs-gallery.html

The first and obvious bug is when you set `centeredSlides` to `false` for `galleryThumbs`, the thumbnail nav just stopped working.

**Comment by lautiamkok** [comment]
After a few hours of "debugging", I have it fixed with the following hack:

```
var galleryTop = new Swiper('.gallery-top', {
        spaceBetween: 10,
        slidesPerView: 1,
        loop: true,
        centeredSlides: true,
        grabCursor: true,
        freeMode: false,
        keyboard: {
            enabled: true,
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });

    var galleryThumbs = new Swiper('.gallery-thumbs', {
        loop: true,
        spaceBetween: 10,
        // centeredSlides: true,
        slidesPerView: 'auto',
        touchRatio: 0.2,
        slideToClickedSlide: true
    });

    galleryTop.on('slideChange', function () {
      console.log("view index: " + this.realIndex)
      galleryThumbs.slideTo(this.realIndex)
    });
    galleryThumbs.on('slideChange', function () {
      console.log("thumb index: " + this.realIndex)
      galleryTop.slideTo(this.realIndex + 1)
    });
```
It is the index that causing the bug. I think you should into this. The index numbers are odd as they change when `centeredSlides` is `false` or `true`. Shouldn't they be constant??

Hope this hack helps others who may have experienced the same problem.

**Comment by omeraplak** [comment]
Hello @lautiamkok ,
I have same issue. I don't understand "this.realIndex", what is this?

Thanks

**Comment by lautiamkok** [comment]
@omeraplak 

Check this out - it is well explained here - http://idangero.us/swiper/api/
