### ISSUE TITLE
global in current amd/umd wrapper undefined in strict mode

### ISSUE THREAD

**Issue by DanielRuf** [nolimits4web/swiper#2482]
In specific scenarios the `global` variable in the generated amd/umd wrapper is undefined.
Normally it should be `window` and most libraries need a `if(global === undefined && window!== undefined) global = window;` to fix this.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: macOS.

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE. (todo)

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE. (todo)

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE. (todo)

**Comment by DanielRuf** [comment]
Something like bebraw/libumd@f43a331

dimsemenov/PhotoSwipe#1413

**Comment by DanielRuf** [comment]
More references:

https://github.com/fians/Waves/pull/181
https://github.com/jonathantneal/svg4everybody/issues/162

**Comment by nolimits4web** [comment]
This is actually UMD definition which should work correct in most of cases where it is used correctly. Can you show me an example of such env where it will throw an error?

**Comment by nolimits4web** [comment]
If you mean in something like this:
```
function () {
  'use strict';
  // ... full swiper.js source code here
}
```
Then it will throw an error, but i would say it is a wrong usage rather then UMD issue

**Comment by DanielRuf** [comment]
You can ask @bebraw of libumd as ther eis also this fix ;-)

**Comment by mikestreety** [comment]
I can confirm this solved an issue for me where I didn't want to install via node_modules and was just including the downloaded file in my Vue project. Thanks @DanielRuf.
