### ISSUE TITLE
Bug gallery with Thumbs and Two way control when centeredslides: false

### ISSUE THREAD

**Issue by EdicionPG** [nolimits4web/swiper#2483]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: W10, Chrome & Firefox lastest version.
* Live Link or JSFiddle/Codepen or website with isssue: http://000whpg.000webhostapp.com/

### What you did
Using demo from gallery with Thumbs and 2 way control (http://idangero.us/swiper/demos/300-thumbs-gallery.html) selected centeredslides as false it doesnt work as expected

### Expected Behavior
Normal function with thumbs aligned to left.

### Actual Behavior
It fail when click on last thumbs.

**Comment by the-fedorr** [comment]
Having the same issue. It is totally broken when there is only few slides on the page and thumbs fits on a screen.

**Comment by thomas-obernberger** [comment]
same here!

**Comment by purzlbaum** [comment]
Same here.

**Comment by remcotak** [comment]
Same here! Would love to see a fix

**Comment by kysonic** [comment]
+1

**Comment by alesak** [comment]
replaced native controller functionality with click handler on thumb slider:
`                            on: {
                                click: function (event) {
                                    if (galleryThumbs.clickedIndex !== undefined) {
                                        galleryTop.slideTo(galleryThumbs.clickedIndex);
                                    }
                                }
                            }
`

**Comment by morettolss** [comment]
+1 for @alesak solution

**Comment by ilyaztsv** [comment]
any news about the issue?

**Comment by thomas-obernberger** [comment]
please fix the issue, dont want to move to an other library

**Comment by ntucakovic** [comment]
This is a big issue. We have to do a lot of workaround to achieve `centeredSlides: false` along with other behavior we might need to implement.
