### ISSUE TITLE
Snapping in freeModeSticky with slide groups prefers previous slide

### ISSUE THREAD

**Issue by lohfu** [nolimits4web/swiper#2485]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2 and 4.1.5
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/lohfu/pen/oEWOrq.

### What you did
See the linked codepen

### Expected Behavior
When using slide groups, I would expect Swiper to snap to the next group if i have swiped more than half of the current group (even when not passing minimum velocity).

If using the mousewheel, i expect to stay at the end if i have scrolled to the end.

### Actual Behavior
When swiping or scrolling you have to scroll over 80% of a slide group to go to the next one. Ie, in the codepen i linked i have to swiper past slide 4 to go the group that starts with slide 6.

If using the scroll wheel, it is not possible to get the swiper to stay in the last swipe group. If i scroll to the end, the swiper will snap back to the last full group when scrolling stops.

Is this the intended behaviour or am I missing an option to change the behaviour?

**Comment by nolimits4web** [comment]
This is not the usecase. Result will be the same as just to disable freeMode, so just disable it in this case

**Comment by lohfu** [comment]
@nolimits4web the problem is i want to be able to use the velocity option... ie in a swiper with many views/groups the user should be able to swipe with a high velocity and have the swiper page through many of the views/groups...

**Comment by nolimits4web** [comment]
Fixed now
