### ISSUE TITLE
can't set automatic number of slides per view in loop true mode

### ISSUE THREAD

**Issue by passionato** [nolimits4web/swiper#2488]
I am creating a photo carousel. 

Here are the params of the swiper:

    mySwiper = Swiper('.swiper-container', {
        loop: false,
        speed: 800,
        slidesPerView: 'auto',
        grabCursor: true,
        spaceBetween: 2,
        initialSlide: 0,
        keyboardControl: false,
        resizeReInit: true,
        autoplayDisableOnInteraction: false,
        pagination: '.swiper-pagination',
        paginationClickable: false,
        nextButton: '.swiper-next',
        prevButton: '.swiper-prev'
    });

My purpose is to fit as many slides into the view as possible. The photos are of different width and size, some are landscape mode and some are portrait. 

**Problem:** only showing one slide per view.

**Goal**: fit in as many slides as possible into view.

could somebody help me to achieve this?

**Comment by nolimits4web** [comment]
Have you seen this big red square in docs?!

<img width="572" alt="screen" src="https://user-images.githubusercontent.com/999588/36604774-bf3732c8-18cf-11e8-8da1-9ecba2135b8f.png">
