### ISSUE TITLE
Parallel swipers on one page + swiper move direction 

### ISSUE THREAD

**Issue by pmdstudio** [nolimits4web/swiper#2489]
Hi,
Is it possible to detect the swiper move direction? I didn't find any method or API for that.
I need 2 swipers on the same page and when the first swiper get to a certain index the second one to slide next / prev depending on the first swiper moving direction.

Is it possible?

**Comment by nolimits4web** [comment]
You can just compare `activeIndex` and `previousIndex` to get the direction
