### ISSUE TITLE
Controller Inverse has no effect

### ISSUE THREAD

**Issue by andre-arsenault** [nolimits4web/swiper#2491]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: CORDOVA, IOS, ANDROID, CHROME
* Live Link or JSFiddle/Codepen or website with issue: [https://jsfiddle.net/odur6jms/6/](https://jsfiddle.net/odur6jms/6/)

### What you did
Set `controller: { inverse: true }` when creating a Swiper instance, as shown in the [documentation example](http://idangero.us/swiper/api/#controller).

### Expected Behavior
Instead of swiping _left_ to advance through the slides, input should be inverted and swiping _right_ will advance through the slides. (If `direction: 'vertical'`, swiping _down_ instead of _up_ should advance.) Any effects (such as flip) should also be inverted and follow the touch input.

### Actual Behavior
Nothing different seems to happen. The Swiper behaves as if no settings were changed.

**Comment by nolimits4web** [comment]
Controller is used when one Swiper controls another one. For single swiper it has no effect.

**Comment by andre-arsenault** [comment]
You might want to update your documentation example then, and provide one that is functional.

**Comment by nolimits4web** [comment]
Everything is correct in docs. This is where controller is used http://idangero.us/swiper/demos/300-thumbs-gallery.html

**Comment by andre-arsenault** [comment]
That example is good, I meant this: http://idangero.us/swiper/api/#controller

```
var mySwiper = new Swiper('.swiper-container', {
  controller: {
    inverse: true,
  },
});
```

**Comment by andre-arsenault** [comment]
So aside from documentation quibbles, if I want a slider with `direction: 'vertical'` where you swipe _down_ to advance, how should I do it?

My current understanding would be to make a second invisible slider control on top of the visible one, have the invisible one control the visible one, and set inverse: true on the invisible one. Is that really the best way?

**Comment by nolimits4web** [comment]
No, i would just go with setting `initialSlide` parameter equal to last slide index, and if needed place slides elements in reverse direction as well

**Comment by andre-arsenault** [comment]
You'd still be swiping _up_ to advance though them, you'd just be going through them in reverse order.

**Comment by andre-arsenault** [comment]
Never mind, I see what you mean. Thanks!
