### ISSUE TITLE
Hide Some Sliders with jQuery

### ISSUE THREAD

**Issue by ui-1** [nolimits4web/swiper#2495]
Let me tell you that it's a great dynamic library for sliders, but I tried to hide some sliders using jQuery.hide() method but found that sliders (cover flow in my case) have been resized to a smaller size and the hidden sliders place still being but the sliders itself is hidden. I have searched found that I should remove (swiper-slider) class, I did that but something strange is here: the slider does not respond to my code until I resize the document.Can you make hide method in your library to able us to hide any slide with a certain class or data attributes?
My code is here :
$('.vc_automation').hide();
                //                Swiper Slider Editing
                if($(".swiper-slide").is(".vc_automation")){
                    $(".vc_automation").removeClass("swiper-slide");
                };

**Comment by nolimits4web** [comment]
> something strange is here: the slider does not respond to my code until I resize the document

Swiper needs to update it size to do the proper things, try to call its `.update` method when you hide/show slides or try to enable `observer` and `observeParents` parameters

**Comment by nolimits4web** [comment]
```
swiper.update()
