### ISSUE TITLE
[bug] You can not change loadPrevNext and loadPrevNextAmount params

### ISSUE THREAD

**Issue by Gr0m** [nolimits4web/swiper#2496]
var photosSlider = new Swiper($('.swiper-container', photos), {
	lazy: true,
	loadPrevNext: true,
	loadPrevNextAmount: 2
});

Swiper will never enter "if (params.loadPrevNext) {" (line 6104 in swiper.js).

Swiper 4.1.6

**Comment by nolimits4web** [comment]
check docs about syntax:
```
...
lazy: {
  enabled: true,
  loadPrevNext: true,
  loadPrevNextAmount: 2
}
...

**Comment by Gr0m** [comment]
Sorry, still trying to use Swiper in the old way.
