### ISSUE TITLE
reponsive images and lazy loading: `data-srcset`/`data-src` break media conditions in `sizes`

### ISSUE THREAD

**Issue by sjf-dev** [nolimits4web/swiper#2499]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.0
* Platform/Target and Browser Versions: Chrome v63 on MacOS X 10.13.3
* JSFiddle with issue (using `data-src`/`data-srcset` with `class="swiper-lazy"`): https://jsfiddle.net/sjf_dev/kvjos7f8/
* JSFiddle without issue but also without lazy loading (`using src`/`srcset` without `class="swiper-lazy"`): https://jsfiddle.net/sjf_dev/7oysxcox/

### What you did
Set up a Swiper Slideshow with images using `data-src`/`data-srcset`/`sizes` with `class="swiper-lazy"`:
``` html
<!-- Slider main container -->
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
    <div class="swiper-slide">
          <img
            class="swiper-lazy"

            data-srcset="
                https://via.placeholder.com/400x200 400w,
                https://via.placeholder.com/800x400 800w,
                https://via.placeholder.com/1200x600 1200w,
                https://via.placeholder.com/1600x800 1600w,
                https://via.placeholder.com/2400x1200 2400w,
                "

            sizes="
                (max-width: 800px) 400px,
                (max-width: 1200px) 600px,
                (max-width: 1920px) 800px,
                1200px
            "
            data-src="https://via.placeholder.com/400x200" 
      >
      <div class="swiper-lazy-preloader"></div>
      </div> 

    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- If we need scrollbar -->
    <div class="swiper-scrollbar"></div>
</div>
```

### Expected Behavior
Browser choses higher resolution images using the media conditions declared in `sizes`.

### Actual Behavior
Browser choses higher resolution not as declared but earlier. In my example the media conditions are set to be `width: 800px`, `width: 1200px`, (…). However the browser actually uses `width: 490px`, `width: 693px`, (…).

I found out that using `srcset` and `src` instead of `data-srcset` and `data-src` on the image tag leads to correct use of the media conditions declared in `sizes`. However I lose the lazy loading functionality. Check out the second Fiddle above for comparison.

I inspected with Chrome v63 DevTools and disabled cache. Can you reproduce? Any Ideas?

Thank you!

**Comment by nolimits4web** [comment]
To be honest don't know how to fix it, as this is how image preloader works https://github.com/nolimits4web/swiper/blob/master/src/components/core/images/loadImage.js#L13-L21 so it first set `sizes`, then `srcset` then `src` and i believe issue comes from here, maybe because these tags are set one after another, but there is no way to set them all at once

**Comment by sjf-dev** [comment]
Thank you Vladimir for your response. Unfortunately I have only limited understanding of JavaScript so I am not able to help with tracking this down. 
To me it sounds like this is a general issue and not only related to my specific case. I assume this issue applies to many use cases, and — as "wrong" high-res images are served — is resulting in bloated data traffic and page load times.

Do we agree that Swiper is currently not working as expected when using lazy loading with responsive images (with `data-src`/`data-srcset`/`sizes`)?

**Comment by nolimits4web** [comment]
> Do we agree that Swiper is currently not working as expected when using lazy loading with responsive images (with data-src/data-srcset/sizes)?

Looks like, but it is more browser issue
