### ISSUE TITLE
Cant press  swiper-slide thumbnails, It should show in the right side once pressed.

### ISSUE THREAD

**Issue by agneszan** [nolimits4web/swiper#2500]
I've search on google for days and no help,i've updated your swiper.min.js to latest version.
What I want to do is make the thumbnails show in the right side when you click on it.
Here is the problem: http://teepeetest.dns-systems.net/product/test/ see for yourself , the slider works but if you click the thumbnails nothing happend.

Working example here : http://teepeetest.dns-systems.net/product/bundle-deal-peter-rabbit-cream-blue-tweenie-teepee-floor-mat-cushions/. This is old API but it breaks the site with AW SNAP ! error.

Please help ,thank you.

//product thumbnails swiper	
		var product_thumbnails_swiper = new Swiper ('.product_thumbnails .product_thumbnails_swiper_container',{
			slidesPerView: "auto",
			watchActiveIndex: true,
			mousewheelControl: true,
			slideToClickedSlide:true,
			direction:'vertical',
			
			//i think there is a problem here below :/ thats why it will not work.
			onSlideClick : function() {
				owl.goTo(product_thumbnails_swiper.clickedSlide);
				for (var i = 0; i < product_thumbnails_swiper.slides.length; i++){
					product_thumbnails_swiper.slides[i].style.opacity = 0.2;
					product_thumbnails_swiper.slides[i].style.cursor = 'pointer';
				}
				product_thumbnails_swiper.slides[product_thumbnails_swiper.clickedSlide].style.opacity = 1;
				product_thumbnails_swiper.slides[product_thumbnails_swiper.clickedSlide].style.cursor = 'default';
				product_thumbnails_swiper.slideTo(product_thumbnails_swiper.clickedSlide, 300, '');
			}
		});

**Comment by nolimits4web** [comment]
Please make sure you are using latest version and check it is API, it changed http://idangero.us/swiper/api/
