### ISSUE TITLE
[bug] Multi row slides with loop=true is buggy

### ISSUE THREAD

**Issue by MiMaMuh** [nolimits4web/swiper#2502]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Targets: 
macOS with Chrome, Firefox, Safari, ... I think it is the same on windows too. 
* Codesandbox.io:
[https://codesandbox.io/s/52mpq4j40x](https://codesandbox.io/s/52mpq4j40x)

### What you did
Creating a multi row setup like in your demo [here](https://github.com/nolimits4web/Swiper/blob/master/demos/170-slides-per-column.html) and it leads to weird behaviour when using it with `loop: true`. 

### Expected Behavior
Loop properly

### Actual Behavior
Slides missing, or flickers on drag, too many slides or similar. Multiple behaviours ...

**Comment by nolimits4web** [comment]
loop is not supported for multi row swiper
