### ISSUE TITLE
Slider with tabs (thumbnail)

### ISSUE THREAD

**Issue by fxmountain** [nolimits4web/swiper#2505]
This is a (multiple allowed):
* [X] bug (idk?)
* [X] enhancement (X)
* [X] feature-discussion (idk?)

* Swiper Version: [4.1.6](https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.1.6/css/swiper.css)
* Platform/Target and Browser Versions: Chromium on Linux (newest)
* Live Link or JSFiddle/Codepen or website with issue: [Codepen](https://codepen.io/fxmt/pen/KQGQWO) (var swiperTabs)

### What I did
* [X] Building a slider with tabs (if possible with dynamic content) based on [Thumbs Gallery With Two-way Control](http://idangero.us/swiper/demos/)
* [X] Tested if bootstrap has something to do with that (has not)

### Expected Behavior
* [ ] When setting centeredSlides to false still beeing able to navigate throuw the thumbs/tabs
* [ ] (secondary) Looping both is buggy

### Actual Behavior
* [X] Tabs do not work, when `centeredSlides: false` -> Not able to navigate
* [X] With `centeredSlides: true` it works fine.

**Comment by nolimits4web** [comment]
When you disable centeredSlides then there is no room for sliding and there is no sliding for `swiperTabs`, so it doesn't work in this case

**Comment by fxmountain** [comment]
Is there an other case? :sweat_smile:
