### ISSUE TITLE
Lazy-loaded background images not loading if initialized with initialSlide other than zero

### ISSUE THREAD

**Issue by alejandroiglesias** [nolimits4web/swiper#2506]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6

### What you did
Reduced test code:
```html
<div class="swiper-container" id="my-element">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <div class="swiper-lazy" data-background="path-to-image">
        <div class="swiper-lazy-preloader"></div>
      </div>
    </div>
  </div>
</div>
```
```javascript
new Swiper('#my-element', {
    initialSlide: 2,
    lazy: {
        loadPrevNext: true,
        loadPrevNextAmount: 3
    },
    preloadImages: false,
});
```

### Expected Behavior
Expected the background images for the initially displayed slides to be loaded.

### Actual Behavior
No background image is loaded (until sliding, window resizing, etc.) unless initialized with `initialSlide` to zero.
This is the Swiper source code part that checks for `initialSlide` to be zero:
```javascript
init: function init() {
  var swiper = this;
  if (swiper.params.lazy.enabled && !swiper.params.loop && swiper.params.initialSlide === 0) {
    swiper.lazy.load();
  }
},
```
I cannot understand the reason for that checking since it seems a reasonable use case to start from a different initial slide and have the initially displayed slides to be loaded.

**Comment by nolimits4web** [comment]
The code is correct and i see it is working. Can you please provide a JSFiddle or live example with the issue?
