### ISSUE TITLE
updateAutoHeight() transition

### ISSUE THREAD

**Issue by pooledge** [nolimits4web/swiper#2509]
This is a (probably):
* [x] enhancement

* Swiper Version: 4.1.0 via npm

### What I did
I have two use cases, where I successfully call updateAutoHeight() and I'd like the new wrapper height to be transitioned with the same 'speed' parameter I supply:
 
1. Unlike swiping or clicking on navigation arrows in thumbs-gallery, clicking a specific thumb slide didn't update main gallery wrapper height
2. Upon lazyload (as described here): https://github.com/nolimits4web/Swiper/issues/1537

### Expected Behavior
Same wrapper height transition as on swipe or navigation.

### Actual Behavior
A hard jump.

P.S. I'm afraid I haven't seen any relevant answers on 'swiper updateAutoHeight transition' on SO or here.

**Comment by nolimits4web** [comment]
JSFiddle or example with the issue?

**Comment by pooledge** [comment]
Sorry it took a while. I've moved on for now by giving the lazy-preloader the desired image dimensions and placing navigation into the gallery-top.

Here is a fiddle: https://jsfiddle.net/dpfqr9u5/36/

Thank you!
