### ISSUE TITLE
 Incorrect behavior with disabled slide

### ISSUE THREAD

**Issue by SpartakN** [nolimits4web/swiper#2510]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: Windows (Firefox & Chrome)
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/nsjs/rvLyvnpj/12/

### What you did
Before I initialized swiper I disabled the slide (using "display: none"). Then I swipe for "Slide 4".

### Expected Behavior
The active slide must have the class "swiper-slide-active".

### Actual Behavior
The active slide takes the class "swiper-slide-next".

```
<div class="swiper-container">

    <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide" style="display: none;">Slide 3</div>
        <div class="swiper-slide">Slide 4</div>
        <div class="swiper-slide">Slide 5</div>
    </div>
    
    <div class="swiper-pagination"></div>
    
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    
</div>
```

**Comment by nolimits4web** [comment]
Disabled/hidden slides are currently not supported
