### ISSUE TITLE
Blank slides, images are at wrong position

### ISSUE THREAD

**Issue by adrianmihalko** [nolimits4web/swiper#2511]
I am trying to implement Swiper on my website. For some reason it's not working, the images are pushed to the left under each other and pagination controls are missing:

![untitled](https://user-images.githubusercontent.com/733361/36938248-5c74ea9e-1f1f-11e8-9b65-5fee565ef415.jpg)

I set background color red for easier view of the swiper container.

Can anyone take a [quick look](http://otthon.mihalko.eu:1999/opencart/mihalko/public_html/) what can be the problem here?

**Comment by nolimits4web** [comment]
Can you please update your example so it load swiper scripts correctly?

**Comment by adrianmihalko** [comment]
Sorry, swiper script was pointing to my local server ip. I updated the example to load script from a live server. 👍

**Comment by nolimits4web** [comment]
And where is the swiper.css?

**Comment by adrianmihalko** [comment]
Ahhhhhh! Thank you very much. I feel stupid.😀
