### ISSUE TITLE
Disable the first slide animation on load?

### ISSUE THREAD

**Issue by christianhall10** [nolimits4web/swiper#2512]
Hey guys. 

When I load the swiper the first slide-in animation is choppy and looks like you see the last second of the end slide before seeing the first. I'm sure the intent of this was to look great but it actually looks glitchy more times than not.

So basically all I need is the FIRST slide to not transition in on load. Otherwise this swiper isn't gonna work. And it looks glitchy. Can someone help?

EDIT: Also I changed the effect to "fade" and it works but the first slide still slides in! I really need help.

UPDATE: Okay so I decided to completely reproduce my EXACT code onto codepen and it works WAY better than if the SAME code is in Wordpress. Why is this? I literally duplicated it exactly and the functionality is way different. I really need some help here. I don't have interfering code and I'm using the same CDN's for Swiper and jQuery.

**Comment by nolimits4web** [comment]
This is performance issue, the longer script takes to load the more time will be required for swiper to init. You can do some lazy loading technic or something similar
