### ISSUE TITLE
How can we stack the slides

### ISSUE THREAD

**Issue by dotnetdreamer** [nolimits4web/swiper#2515]
i would like to know how can we stack the slides ? 
### What you did
I asked the question here but there is code pin as well. but didn't get any response.
https://stackoverflow.com/questions/49104896/how-can-we-stack-swiperjs-slides-stacked

Pin:
https://codepen.io/anon/pen/WMBXvX

**Comment by nolimits4web** [comment]
> I asked the question here but there is code pin as well. but didn't get any response.

It still not the reason to raise an issue
