### ISSUE TITLE
Accessibility: Pause Button

### ISSUE THREAD

**Issue by julmot** [nolimits4web/swiper#2517]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

If you want to have an accessibility certification for your website you'll have to optimize your website in several ways. Regarding Swiper that would be translation, WAI-ARAI attributes e.g. for buttons (both already fulfilled) but also a pause button when autoplay is set to true. Currently no pause button is generated, for but accessibility reasons it's required and you won't receive a certification otherwise. Please implement it.

**Comment by nolimits4web** [comment]
> If you want to have an accessibility certification for your website

I don’t want such certificate for my website

**Comment by julmot** [comment]
But you're not only maintining the library for yourself? There are many people with disabilities out there that would really appreciate this feature.

**Comment by nolimits4web** [comment]
Then you have to correctly write an issue.
