### ISSUE TITLE
Usability: Enlarge Bullet Hotspot Area

### ISSUE THREAD

**Issue by julmot** [nolimits4web/swiper#2518]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

The bullet points are quite small, which is fine. However, the clickable area should be enlarged, for easier tapping on mobile devices and clicking on Desktop devices.

**Comment by nolimits4web** [comment]
They originally was designed not to be clickable as clicking such small bullets pretty useless on mobiles. So please, enlarge it as you need in your app/website
