### ISSUE TITLE
Pagination Bullets Not Available on Init

### ISSUE THREAD

**Issue by julmot** [nolimits4web/swiper#2519]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: Windows 10, Firefox 58
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/86nmntkn/2/

### What you did
I want to add a pause button in the on init function, respectively insert it into "swiper-pagination". At this time, it seems, no pagination bullets are available.

### Expected Behavior
The entire library should be initialized when calling "init", including pagination bullets available.

### Actual Behavior

> At this time, it seems, no pagination bullets are available.

**Comment by nolimits4web** [comment]
Use `paginationRender` event instead http://idangero.us/swiper/api/#pagination-events
