### ISSUE TITLE
Centering slides when slide count is less than slidesPerView

### ISSUE THREAD

**Issue by kieraneglin** [nolimits4web/swiper#2520]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: Any desktop browser

### What you did
I created a slider with 5 `slidesPerView`, but only 3 slides total.  Loop is `false`

### Expected Behavior
Through some configuration or CSS, slides should be center-aligned instead of left-aligned

### Actual Behavior
Slides are left-aligned.  Adding the CSS below does center it, however the left-most slide is then cut off (as described in #2081).

```css
.swiper-wrapper {
  justify-content: center;
}
```
 There is a solution in #2081, however it's _really_ hacky and I wanted to check if there was a better solution now.

**Comment by nolimits4web** [comment]
Nothing hacky, just check the amount of slides and set/unset `justify-content: center;` prop when required

**Comment by yellow1912** [comment]
I think this is something the library should handle instead, because in most use cases people will want the slides to be centered if possible. What do you think? Perhaps we can add a config for that?
