### ISSUE TITLE
Slider in slider

### ISSUE THREAD

**Issue by Andreyukr87** [nolimits4web/swiper#2524]
Hi,

I apologize in advance, I do not speak English well, translated as an interpreter. I need to implement such a task. In the slider place slides photo. But the problem is that when you try to make a svayp on the secondary carulleys, the main one is also scrolled. It may be possible to remove the main scroll from the area of ​​the secondary sliders. Thank you.

Example of sliders in the slider https://codepen.io/Vlastelin/pen/EgwAqd

**Comment by nolimits4web** [comment]
You must enable `nested: true` parameter on nested sliders
