### ISSUE TITLE
Slides showing all in one slide.

### ISSUE THREAD

**Issue by holoverse** [nolimits4web/swiper#2525]
My swiper slider used to work, then suddenly today, it just stopped working.  Now all the slides show up on the first slide.  The subsequent slides all exist, but they are empty.  All the swiper-slide content shows up only on the first slide.  So wierd.

I have var swiper = new Swiper('.swiper-container');

and layout is

      <div class="swiper-container">
                <div class="swiper-wrapper">
                  @foreach($questions as $q)
                  <div class='swiper-slide'  data-hash="question{{$q->order}}">
                    @include('forms.question')
                  </div>
                  @endforeach
             </div>
      </div>

I cant for the life of me understand why this would suddenly just start happening.   Literally nothing changed.  It just started happening.  Yersterday iot was working.  Today its not.

Version 4.1.6  From the CDN

**Comment by nolimits4web** [comment]
> My swiper slider used to work, then suddenly today, it just stopped working

"suddenly" can't be because of Swiper as you were using same lib. So 100% the issue is in your side. If not, then create new issue and fill the issue form correctly providing JSFiddle or example with the issue
