### ISSUE TITLE
Swiper slide duplicates itself

### ISSUE THREAD

**Issue by TiberiusVE** [nolimits4web/swiper#2526]
Hello. 
For some reason, in a completely random manner, my swiper slider duplicates itself. Well, the slides do. The problem is, precisely, the randomness. 

It does not happen all the time, only if you refresh the page a certain amount of times. There's no way to know when it's gonna happen.

For example, if I create a setup with 3 slides max, sometimes they become six slides. 
Any ideas?

**Comment by nolimits4web** [comment]
If you have enabled `loop` then yes, it works based on automatic slides duplication
