### ISSUE TITLE
Change direction from horizontal to vertical in mobile device

### ISSUE THREAD

**Issue by mehulRojasara** [nolimits4web/swiper#2527]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 4.1.6.
* Platform/Target and Browser Versions:  CHROME, windos 10 responsive **mode (mobile)**.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/mehulRojasara/full/QmNJoZ/

### What you did
wants to change swiper direction horizontal to vertical in mobile devices responsive view

### Expected Behavior
in responsive view swiper should be vertical direction.

### Actual Behavior
design is not proper and swiper slides are not in actual place

**Comment by nolimits4web** [comment]
No, direction change doesn't supported. There is no `direction` method on swiper as well. You can try to destroy swiper and init it again with required parameters

**Comment by mehulRojasara** [comment]
Thank you for your response 
we already try this thing when we use the older version of swiper 
but when we get new methods in updated swiper we just want to reduce line of code using new functionality.

Thanks again for great new features and your response.
