### ISSUE TITLE
autoplay sometimes keeps animating even after destroy()

### ISSUE THREAD

**Issue by WHI-CH** [nolimits4web/swiper#2529]
We are initializing and destroying the Swiper on window resize depending on the window width for the mobile/desktop version of a site.

Sometimes the container keeps animating after destroy() has been called - usually when the slide is currently being animated when destroying the Swiper.
We have tried calling mySwiper.autoplay.stop() before destroy(), but that didn't help either.

Thanks in advance for any help/tips/fixes ;)

**Comment by nolimits4web** [comment]
When the slide is currently animating it won't stop. You can call `swiper.setTransition(0)` before destroy

**Comment by WHI-CH** [comment]
No, the problem is that the container will keep animating with the specified "autoplay delay" even after destroy() is called and the Swiper doesn't even exist anymore. So it will keep updating css transform every few seconds.

**Comment by nolimits4web** [comment]
There is something wrong in your code. Can you provide a JSFiddle with the issue where i can see it?

**Comment by WHI-CH** [comment]
Thanks for the quick replies!

I've removed .htpasswd from the test site and added the relevent "window resize" code directly to the bottom of the source if that's enough?

https://test.w24.at

**Comment by nolimits4web** [comment]
Look at your code, you init Swiper each time on response, no matter whether it is initialized or not

**Comment by WHI-CH** [comment]
True, adding a "if ( ! swiperHome )" before init seems to have fixed it.
Sorry and thanks for the quick help!
