### ISSUE TITLE
Portrait images does not show in IE 11

### ISSUE THREAD

**Issue by BrahmanandaK** [nolimits4web/swiper#2530]
Portrait images does not show in IE 11 

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: IE 11 Windows 7.

### What you did
portrait images does not showup in IE 11. Works good in chrome and firefox
use following images for test

![1](https://user-images.githubusercontent.com/25649217/37534618-5b993fb4-2913-11e8-9a2b-f4547a103440.jpg)
![2](https://user-images.githubusercontent.com/25649217/37534619-5bad4efa-2913-11e8-9fcf-46db468e4cd1.jpg)

**Comment by nolimits4web** [comment]
What is portrait images?

**Comment by nolimits4web** [comment]
Still not clear, these images say nothing to me

**Comment by BrahmanandaK** [comment]
![image](https://user-images.githubusercontent.com/25649217/37534055-a822bd4e-2911-11e8-9e63-e68d37efbcad.png)

**Comment by BrahmanandaK** [comment]
please use the images and you see the problem in IE. images are edited and they are white.

**Comment by nolimits4web** [comment]
I still see just the blank screen, please provide the full detailed explanation on what you use, how do you use it, code example, etc

**Comment by BrahmanandaK** [comment]
It could be issue with browser supporting the image type itself.
