### ISSUE TITLE
Incorrect loop behavior using slidesPerView, slidesPerGroup, and centeredSlides.

### ISSUE THREAD

**Issue by vitogoh** [nolimits4web/swiper#2531]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6.
* Platform/Target and Browser Versions: macOS/Chrome.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/qoarzj_.

### What you did
Setup swiper with **loop**, **slidesPerView**, **slidesPerGroup**, and **centeredSlides** using 12 slides.

### Expected Behavior
Next and Previous arrow should loop the slides continuously

### Actual Behavior
The next arrow works as expected but on the second click the previous arrow, instead of the slide moving to the right to reveal [6][7][8], the slider slides the opposite direction.

i've been increasing the **loopedSlides** and it looks like the magic number which gives slide 1 the correct starting position and the slide to not have empty gaps while clicking on previous arrow is 9. however, any number higher than that in multiples of 3, e.g, 12, 15, 18, etc. doesn't seem to do anything different than 9.

i've also tried adding **loopAdditionalSlides** into the mix with no changes.

![awesomescreenshot-2018-03-16t22-26-15-422z](https://user-images.githubusercontent.com/1999704/37547394-c1481eb4-2947-11e8-95cf-3b0b799d35d4.gif)

I also get a slightly different behavior if i drag it. When i drag to the right, I can actually get to [6][7][8], but as soon as i start the drag again from that position, [6][7][8] becomes [12][1][2]

![asdf](https://user-images.githubusercontent.com/1999704/37548145-496de626-294c-11e8-9e22-1fc1dfc049c9.gif)

**Comment by designandreev** [comment]
I'm having the same problem. Is it possible to use centeredSlides with loop?
