### ISSUE TITLE
CDN Links broken

### ISSUE THREAD

**Issue by Xsmael** [nolimits4web/swiper#2533]
All the CDN links Mention on the getting sarting guide are broken

https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.0/css/swiper.css
--
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.0/css/swiper.min.css
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.0/js/swiper.js
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.0/js/swiper.min.js
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.0/js/swiper.min.js.map

Getting 404 errors

**Comment by nolimits4web** [comment]
Need to wait a bit until cdnjs update it
