### ISSUE TITLE
Vertical mode bug.

### ISSUE THREAD

**Issue by Zver64** [nolimits4web/swiper#2534]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.0.
* Platform/Target and Browser Versions: windows google chrome 64.0.3282.186.
* https://jsfiddle.net/Geminis/8hzogg76/

### What you did
I copypasted the html from Getting Started With Swiper page and changed the slides to simple colored divs with different heights. I also set the width and the height if the slider itself as it has been done in the getting started guide. so the html is:
```
<!-- Slider main container -->
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">
        	<div class="box-1"></div>
        </div>
        <div class="swiper-slide">
        	<div class="box-2"></div>
        </div>
        <div class="swiper-slide">
        	<div class="box-1"></div>
        </div>

    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- If we need scrollbar -->
    <div class="swiper-scrollbar"></div>
</div>
```
The js is:
```
var mySwiper = new Swiper ('.swiper-container', {
    // Optional parameters
    direction: 'vertical',
    loop: true,
    
  })
```
the css is:
```
.swiper-container {
    height: 300px;
    width: 300px;
}
.box-1 {
	height: 100px;
	background-color: green;
}
.box-2 {
	height: 200px;
	background-color: red;
}
```

Here is my jsFiddle https://jsfiddle.net/Geminis/8hzogg76/

### Expected Behavior
1)I expected the slider to be the same height as I had set in my css. 

### Actual Behavior
1)The slider has different height and it's larger than I need.

**Comment by shashank1010** [comment]
@Zver64 The demo link is not properly function because, instead of the Link to the css file, you've used the HTML Tag. also, the link is incorrect. That should resolve the issue you face.

**Comment by Zver64** [comment]
@shashank1010 I changed it, but unfortunately nothing happened.

**Comment by hacknug** [comment]
@Zver64 it works when you link to swiper properly like @shashank1010 mentionesd. Here's a fiddle with those things fixed: https://jsfiddle.net/8hzogg76/7/
