### ISSUE TITLE
masonry slides

### ISSUE THREAD

**Issue by mefynn** [nolimits4web/swiper#2535]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 
    `Swiper 3.3.1`
* Platform/Target and Browser Versions: 
    `Any`
* Live Link or JSFiddle/Codepen or website with isssue: 
    http://zeu.fynn.it

### What you did
I tried to build a masonry slider, where the slide heights/widths are set according to the image height/width (depending of screen orientation). [works]

### Expected Behavior
slideNext(), autoplay recognise slide height and behave accordingly 

### Actual Behavior
wrapper height/width is mixed up, slides with height < window.height/width seem to be not recognised as standalone slides and skipped on slideNext()/ autoplay

**Comment by nolimits4web** [comment]
From what i see it works correctly on your website. But first of all, i can recommend to update to latest 4.x version
