### ISSUE TITLE
Autoplay option may have Garbage Collection problems

### ISSUE THREAD

**Issue by sammok** [nolimits4web/swiper#2538]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Just using chrome dev tools Performance Panel, then recording 30s this page below:
[280-autoplay.html](http://idangero.us/swiper/demos/280-autoplay.html)

### Expected Behavior
JS Heap and Listeners GC works good

### Actual Behavior
JS Heap and Listeners GC looks have problems, not clean all

**Comment by nolimits4web** [comment]
More detailed explanation will be good, what means `works good` or `have problems`?

**Comment by sammok** [comment]
when switching autoplay to true, GC collection not clean all each times, and memory cost increasing

you can see the memory curve below picture,

http://program.vipjr.com/ this website is an online demo, you can using Chrome Dev tool to measure the memory cost,

http://idangero.us/swiper/demos/280-autoplay.html this demo also have the same problem

![image](https://user-images.githubusercontent.com/7930154/37753409-b75caee4-2dd7-11e8-8afc-6287121c4972.png)

**Comment by ahmadyunus** [comment]
I wonder anyone also have this problem? the number of listener keep increasing in autoplay mode. 
I use version 4.2.0

<img width="733" alt="screen shot 2018-04-16 at 14 09 41" src="https://user-images.githubusercontent.com/5524546/38794653-1b8dbc80-4180-11e8-9b9a-cf54d2ac0403.png">
