### ISSUE TITLE
VirtualTranslate and autoplay still not working together

### ISSUE THREAD

**Issue by alien-house** [nolimits4web/swiper#2539]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.0

* Platform/Target and Browser Versions: Mac google chrome 65.0.3325.162

### What you did

Setup Swiper with loop, autoplay, and virtualTranslate(true) together.
And I added my own transition animation using CSS by myself.

```
var swiper = new Swiper({
            el: '.swiper-container',
            loop: true,
            autoplay: {
                delay:5000,
                disableOnInteraction:false
            },
            virtualTranslate:true
        });
```

There is the same issue [here](https://github.com/nolimits4web/swiper/issues/2400) and already closed but it seems not fixed yet.

### Expected Behavior

After each delay time, slideshow goes around. 
And never stop.

### Actual Behavior

After one slide ended, it's stopped.

**Comment by nolimits4web** [comment]
You need to set `waitsForTransition: false` autoplay option
