### ISSUE TITLE
Empty pagination with dynamically added slides

### ISSUE THREAD

**Issue by chrishaensel** [nolimits4web/swiper#2541]
First of all: Thank you SO MUCH for your awesome work!

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform: Apache Cordova

### What I did
Hi. When I have all slides in my container when I initialize the slider, all pagination works fine.
Now I have all slides come in dynamically (from JSON). After adding each slider using appendSlide(), I call swiper.update()

All swiping works great, but the container which should hold the pagination is absolutely empty.

### Expected Behavior
Adding a bullet to the pagination after adding a slide and calling update()

### Actual Behavior
Empty pagination controller

Thanks for your help!

**Comment by nolimits4web** [comment]
Can't see such behavior. Can you please provide a JSFiddle with the issue where i can see it?
