### ISSUE TITLE
Loop: true not working when slidesPerView and slidesPerColumn set

### ISSUE THREAD

**Issue by ChrisChiera** [nolimits4web/swiper#2542]
It appears others ran into this same issue last year <https://github.com/nolimits4web/Swiper/issues/1922> though looks like it was closed. One person mentioned adding:

```
setTimeout(function(){
    mySwiper.update(true);
    mySwiper.slideTo(0, 0)
}, 100);
```

to fix the issue. I'm not sure where to add that as I added to here and caused things to break.

```
var mySwiper = new Swiper ('#my-swiper', {
  slidesPerView: 3,
  slidesPerColumn: 2,
  spaceBetween: 30,
  speed: 2000,
  loop: true,
setTimeout(function(){
    mySwiper.update(true);
    mySwiper.slideTo(0, 0)
}, 100);
  autoplay: {
    delay: 1000,
    disableOnInteraction: false,
  },

```
Is there somewhere else it should be added or is there another fix, so that loop true works out of the box when using slides per view and slides per column? Thanks for any help anyone may have!

**Comment by nolimits4web** [comment]
`slidesPerColumn` doesn't compatible with `loop`

**Comment by ChrisChiera** [comment]
Hi yes, that's the issue I'm experiencing. Hopefully it can eventually be fixed. In the meantime, a workaround appears to be creating two instances of swiper one for the top row and one for the bottom and then removing slides per column. Not ideal, but works.

**Comment by chrisyaxley** [comment]
> `slidesPerColumn` doesn't compatible with `loop`

& `slidesPerColumn can't be changed within breakpoints`

Ironic for a product maintained by someone with a name like 'nolimits4web'.

**Comment by netdragonboberb** [comment]
This happens when you're using the <swiper> tag. I fixed it by using "directive" mode

								<div  class="swiper-container carousel" [swiper]="slideConfig" (init)="swiperInit($event)" (reachEnd)="swiperReachEnd($event)" (reachBeginning)="swiperReachBeginning($event)" (slideChange)="swiperSlideChange($event)">
									<div class="swiper-wrapper">

**Comment by KingPengZero** [comment]
Number of slides per column, for multirow layout
slidesPerColumn > 1 is currently not compatible with loop mode (loop: true)
😢
