### ISSUE TITLE
Slides get stuck when dragging with mouse

### ISSUE THREAD

**Issue by eduardowgmendes** [nolimits4web/swiper#2544]
Hi Guys! 
Today i've encountered a bug while a dragged the slides with the mouse. Sometimes and randomly some slides get stucked in the middle of transition from the previous slide to the next.

Here is my Swiper Setup: 

```
var mySwiper = new Swiper('.swiper-container', {
	effect: 'slide',
	centeredSlides: true,
	direction: 'horizontal',
	slidesPerView: 1,
        spaceBetween: 30,
	mousewheel: false,
	loop: false,
	pagination: {
		el: '.swiper-pagination',
		type: 'progressbar',
	},
	navigation: {
		nextEl: '.swiper-button-next',
		prevEl: '.swiper-button-prev',
	},
});
```
* Swiper Version: 4.0.2.

**Comment by nolimits4web** [comment]
"Sometimes" is really hard to replicate, need the direct steps on how to replicate the issue

**Comment by eduardowgmendes** [comment]
I'm using Webflow to create this project and i'm using the Swiper to create a slide view style. Here is my project link: 

http://wa05181-ed-10-rs.webflow.io/

I did realized that if i have some embedded elements like videos or other components in the page the drag with mouse on these elements are not working. How i can solve this?

**Comment by nolimits4web** [comment]
> videos or other components in the page the drag with mouse on these elements are not working

means those components intercept mouse/touch events so they are unavailable for Swiper.

Closing as not related to Swiper
