### ISSUE TITLE
Set params loop to true.

### ISSUE THREAD

**Issue by jenerse** [nolimits4web/swiper#2547]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: lastest.
* Platform/Target and Browser Versions: chrome 65.0.3325.181 for mac.
* Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/010-default.html.

### What you did
when I run the below code in console:
`swiper.params.loop=true`

### Expected Behavior
It will swipe to the first slide, the loop will work.

### Actual Behavior
when I swipe to last slide and swipe again, the loop option is not working, it was error.
```
Uncaught TypeError: Cannot read property 'classList' of undefined
    at i.addClass (swiper.js:204)
    at t.updateSlidesClasses (swiper.js:1624)
    at t.slideTo (swiper.js:2008)
    at t.loopFix (swiper.js:2220)
    at t.E (swiper.js:2633)
```

thanks.

**Comment by nolimits4web** [comment]
Loop can only be passed on initialization
