### ISSUE TITLE
swiper-slide height issue in iOS Safari 10

### ISSUE THREAD

**Issue by DanielRuf** [nolimits4web/swiper#2550]
`height: 100%` is problematic, especially in iOS Safari 10. `height:auto; min-height: 100%;` works much better.

**Comment by nolimits4web** [comment]
In what usecase, example? Can't see any problems with it

**Comment by DanielRuf** [comment]
It happens on a small viewport where we work with elements which use flexbox around them and Safari 10 has issues with height: 100% in this case.

**Comment by DanielRuf** [comment]
We should probably apply this change only in our project as not everyone is affected in the default setup?

**Comment by nolimits4web** [comment]
Yeah, as it is a pretty specific case
