### ISSUE TITLE
Slide width is millions of pixels wide on iOS

### ISSUE THREAD

**Issue by nolaandy** [nolimits4web/swiper#2552]
* [x] bug

* Swiper Version: 4.2.0
* Platform/Target and Browser Versions: iOS
* Live Link: https://codepen.io/nolaandy/pen/32630cd8790378ccc8d6fca6d5a8ed6e

Slider works well on Android and on the desktop, including Safari on a Mac.
The issue arises when I look at the page on iOS. The width of the slider-wrapper is miscalculated and gets these inline styles:
transition-duration: 0ms;
transform: translate3d(-100663248px, 0px, 0px);

I was expecting the slider to be 100% width of the viewport but the inline styles on the slides and wrapper is humongous. ex: each .swiper-slide gets an inline style> width: 33554416px

Any idea why this might be occurring?

Thank you! Great plugin by the way!

**Comment by nolimits4web** [comment]
You need to set swiper-container width:
```css
.swiper-container {
  width: 100%;
}
```

**Comment by agentphoenix** [comment]
I'm seeing the same issue and have my container height and width set already. The inline style is set to `width: 3.35544e+07px;`
