### ISSUE TITLE
Click the prevButton will jump 2 slide

### ISSUE THREAD

**Issue by wszgxa** [nolimits4web/swiper#2554]
* bug
* Swiper Version: 4.2.0
* Platform/Target and Browser Versions: ALL
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/hiluluke/wpt5pdvh/10/
### What you did
Going to the last slider and then click the prevButton.

### Expected Behavior
Just jump one slider

### Actual Behavior
skip one slide, jump 2 slide

### How this happens
When you set the slide's width is not 100% of the swiper wrapper and set the slidesPerView to auto.

### Related link
https://github.com/nolimits4web/swiper/pull/2198
https://github.com/nolimits4web/swiper/issues/2003

**Comment by intrepid-tr** [comment]
chrome has the same problem Is there a solution?
