### ISSUE TITLE
Previous element not loading when loop=true and itemsPerView > 1

### ISSUE THREAD

**Issue by brunolm** [nolimits4web/swiper#2558]
This is a (multiple allowed):
* [x] bug

* Swiper Version: `"swiper": "^4.2.0"`
* Platform/Target and Browser Versions: any
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/github-ph1huz

### What you did
- `loop` = `true`
- `itemsPerView` = `3`

Click `itemsPerView` (3) times up.

### Expected Behavior
To see an element previous to the current one

### Actual Behavior
No elements are shown previous to the current one

**Comment by nolimits4web** [comment]
Add this parameter for example `loopedSlides: 4`
