### ISSUE TITLE
Swipe not working when Toggle device toolbar on Chrome developer tools

### ISSUE THREAD

**Issue by ochanje210** [nolimits4web/swiper#2560]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.0
* Platform/Target and Browser Versions: CHROME with version 65.0.3325.16.
* Live Link or JSFiddle/Codepen or website with issue: N/A

### What you did
from Developer Tools, if you click 'Toggle device toolbar' button and change desktop view to mobile view or vice versa, swiping does not work.

### Expected Behavior
swiping should keep working no matter what the screen resolution is.

### Actual Behavior
Swiping simply not working

**Comment by nolimits4web** [comment]
It doesn’t depend on screen resolution, you have to reload page after you toggle device emulation
