### ISSUE TITLE
 Swiper + TweenMax

### ISSUE THREAD

**Issue by NetGon** [nolimits4web/swiper#2562]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 4.2.2
* Platform/Target and Browser Versions: All.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/ArtStyles/pen/KoRLQJ

### What you did
Hi.
There is a problem in loop mode when the slider returns to the first slide - the animation does not work for the first slide.

**Comment by nolimits4web** [comment]
You need to consider duplicated slides in loop mode
