### ISSUE TITLE
Horizontal layout cannot be used！direction: 'vertical'；  swiper.slideTo(0) invalid

### ISSUE THREAD

**Issue by lettywiterock** [nolimits4web/swiper#2565]
Use the framework  React

import { Swiper, Navigation, Pagination, Scrollbar } from 'swiper/dist/js/swiper.esm.js';

Swiper.use([Navigation, Pagination, Scrollbar]);
    swiper = new Swiper(element, {
      direction: 'vertical',
    });

swiper.slideTo(0) invalid!!!

**Comment by lettywiterock** [comment]
This is two questions

**Comment by nolimits4web** [comment]
Live example with the issue please

**Comment by lettywiterock** [comment]
if(id%2==0){
     console.log('0000000')
      swiper.slideTo(0)
    }else if(id%2==1){
      console.log('1111111')
      swiper.slideTo(1)
    }
//Console Print 00000  swiper   swiper-slide-active  index 0     but Display is not index 0

**Comment by nolimits4web** [comment]
> Live example with the issue please

**Comment by lettywiterock** [comment]
<div className="swiper-wrapper">
                  {[1,2,3].map((item,key)=>{
                    return <Row className={styles.vehicpCarousList+' '+"swiper-slide"}>
                                {[1,2,3,4,5,6,7,8].map((item2,key2)=>{
                                  return <Col key={key2} span={6} className={styles.vehicpCarousItem+' '+(vehicleProfile.tabListShow[key2]?styles.carousItemActive:'')}>
                                      <div className={styles.carousItem}>
                                        <div className={styles.carousItemTitle}>测试{item}</div>
                                        <div className={styles.carousItemBody}>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={24}>...</Col>
                                          </Row>
                                        </div>
                                      </div>
                                  </Col>
                                })}
                            </Row>
                  })}
              </div>

**Comment by lettywiterock** [comment]
<div className="swiper-wrapper">
                  {[1,2,3].map((item,key)=>{
                    return <Row className={styles.vehicpCarousList+' '+"swiper-slide"}>
                                {[1,2,3,4,5,6,7,8].map((item2,key2)=>{
                                  return <Col key={key2} span={6} className={styles.vehicpCarousItem+' '+(vehicleProfile.tabListShow[key2]?styles.carousItemActive:'')}>
                                      <div className={styles.carousItem}>
                                        <div className={styles.carousItemTitle}>测试{item}</div>
                                        <div className={styles.carousItemBody}>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={24}>...</Col>
                                          </Row>
                                        </div>
                                      </div>
                                  </Col>
                                })}
                            </Row>
                  })}
              </div>

**Comment by lettywiterock** [comment]
`<div className="swiper-wrapper">
                  {[1,2,3].map((item,key)=>{
                    return <Row className={styles.vehicpCarousList+' '+"swiper-slide"}>
                                {[1,2,3,4,5,6,7,8].map((item2,key2)=>{
                                  return <Col key={key2} span={6} className={styles.vehicpCarousItem+' '+(vehicleProfile.tabListShow[key2]?styles.carousItemActive:'')}>
                                      <div className={styles.carousItem}>
                                        <div className={styles.carousItemTitle}>测试{item}</div>
                                        <div className={styles.carousItemBody}>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={12} className={styles.item_item}>1</Col>
                                            <Col span={12} className={styles.item_item}>2</Col>
                                          </Row>
                                          <Row className={styles.carousItem_item}>
                                            <Col span={24}>...</Col>
                                          </Row>
                                        </div>
                                      </div>
                                  </Col>
                                })}
                            </Row>
                  })}
              </div>`

**Comment by lettywiterock** [comment]
react  In addition to this  ： import { Swiper, Navigation, Pagination, Scrollbar } from 'swiper/dist/js/swiper.esm.js';
There are other ways  import Swiper？？
I installed swiper

**Comment by nolimits4web** [comment]
Can you please setup a minimal project at https://stackblitz.com/ which can illustrate this issue?

**Comment by lettywiterock** [comment]
I solved it，thankyou。
swiper.slideTo(1)
swiper.slidePrev()
