### ISSUE TITLE
Mousewheel freeMode, freeModeSticky - overshooting the slide

### ISSUE THREAD

**Issue by elaman** [nolimits4web/swiper#2567]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.2.2
* Platform/Target and Browser Versions: macOS, CHROME
* Live Link or JSFiddle/Codepen or website with issue: https://jsfiddle.net/elaman/yy859fuf/3/

### What you did
I've configured library to use mousewheel + freeMode + freeModeSticky.

### Expected Behavior
When you scroll, it predicts the last slide, then stops abruptly without overshooting it.

### Actual Behavior
When you scroll, it overshoots the last slide, then goes back to it.

**Comment by nolimits4web** [comment]
JSFiddle you provided doesn't have such issue
