### ISSUE TITLE
Prevent swiping if all slides are visible?

### ISSUE THREAD

**Issue by davidenco** [nolimits4web/swiper#2569]
Is there a way to prevent swiping automatically if all slides are visible? I have a swiper gallery with a few slides that require swiping controls on mobile devices, but if the browser window is made bigger, then all slides are visible on-screen and there is no longer a need to swipe.

**Comment by mlegait** [comment]
Take a look at the `watchOverflow` parameter : http://idangero.us/swiper/api/#parameters
I think it will solve your problem.

**Comment by davidenco** [comment]
Sorted, thanks.
