### ISSUE TITLE
Stop autoplay when swiper is disappear and start again when appear

### ISSUE THREAD

**Issue by evilebottnawi** [nolimits4web/swiper#2570]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: latest.
* Platform/Target and Browser Versions: not required.
* Live Link or JSFiddle/Codepen or website with isssue: not required.

### What you did
Using example from http://idangero.us/swiper/api/

### Expected Behavior
Swiper should stops autoplay when he is disappear and start again when appear on user screen. Why? It is increase perf. We don't spend user resources (cpu/memory/etc) when he is don't see swiper. We can use https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API for implement this feature. If browser don't has support this api works as usual. Feedback welcome :+1: 

### Actual Behavior
Swiper autoplay works always.

**Comment by nolimits4web** [comment]
Just do it manually when it becomes invisible, no one as you knows your app/website better and when it needed to be stopped
