### ISSUE TITLE
Request - hide pagination dots if only 1 "page"

### ISSUE THREAD

**Issue by lougreenwood** [nolimits4web/swiper#2572]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 4.2.2.
* Platform/Target and Browser Versions: ALL.
* Live Link or JSFiddle/Codepen or website with issue: N/A

### What you did
* Created a multi-row swiper which has it's contents dynamically updated (slides added/removed).
* On initial load, only 1 "page" may have slides, so the pagination button is a distraction.
* Swipers may or may not have slides dynamically added as the user interacts with the application

### Expected Behavior
* If a swiper contains only 1 "page", dynamically hide the pagination dots.
* If more slides are dynamically added (e.g lazy loaded) and this results in total "pages" > 1, dynamical add the pagination buttons.
* If total "pages" > 1 and slides are destroyed, evaluate and dynamically hide the pagination dots.

### Actual Behaviour
If pagination is enabled, page dots are shown, even if only 1 "page" is visible (aka no swiping) - this decreases the usability and is likely to confuse end users - after all, pagination is only useful if there are multiple pages 😃

**Comment by nolimits4web** [comment]
Why not just hiding/disabling pagination when you have only one page?

**Comment by lougreenwood** [comment]
I guess that's possible, but it seems a feature like this would be better suited to being part of the library so that all users get the same baseline UX improvement.

Personally, I can't think of any scenario where showing a pagination dot with only 1 slide/page is a benefit to UX...

I'd offer to contribute, but I'm a PHP dev, my JS knowledge is very limited.

**Comment by jfleblanc** [comment]
Correct me if i'm wrong, but you could simply set `{ watchOverflow: true }` and as long as your single slide isn't wider than .swiper-container, it should do the trick.

**Comment by steve231293** [comment]
+1 for this needed request. 

Swiper pagination shouldn't show when just has single dot.

Swiper Pagination need recalculate visibility when has loop, has breakpoint, slidesPerGroup

Please help.

**Comment by MixMe** [comment]
+1

**Comment by lougreenwood** [comment]
Looks like `watchOverflow: true` works for me 👍

**Comment by MixMe** [comment]
but how to hide "navigation" automatically?

**Comment by steve231293** [comment]
Thank jfleblanc, everything's working perfect.

**Comment by PersianArt** [comment]
`watchOverflow: true`  not work when loop is true, 

@nolimits4web, First of all I must say thanks for this great free slider. 
Indeed when you have only 1 slide it means you can not go to next or previous slide because there is nothing to do then the pagination, navigation, scrollbar must not show even when the loop is true, or at least needs option to show/hide them.

I suggest this is increase usability if you consider this or put option for it,

Thanks

**Comment by yuchant** [comment]
+1. Use case is responsive. Currently have pagination only on small displays..

**Comment by Seanom** [comment]
This is how we approach the single pagination button, when we reduce the viewport width we change the amount we display so smaller viewports include the dots and are visible but increase the width to display all the slides and we just hide it.

```
.swiper-pagination-bullet:only-child {
    visibility: hidden;
}
```

**Comment by steve231293** [comment]
Seanom's solution is working, but it can appear unexpected white space while it has margin or padding.

**Comment by MuneebRabaney** [comment]
I used `pagination: ' '` and it worked like a charm. using `swiper version 4.5.0`

My end code looks like this

```
<SwiperCarousel
          breakpoints={{
            '1366': {
              slidesPerView: 5,
              spaceBetween: 30,
            },
            '1024': {
              slidesOffsetAfter: 50,
              slidesOffsetBefore: 50,
              spaceBetween: 50,
            },
            '991': {
              slidesPerView: 3,
              slidesPerColumn: 1,
              slidesOffsetAfter: 0,
              slidesOffsetBefore: 0,
              spaceBetween: 10,
            },
            '420': {
              **pagination: ' ',**
              freeMode: false,
              spaceBetween: 10,
              slidesPerView: 1,
              slidesPerColumn: 1,
              slidesOffsetAfter: 10,
              slidesOffsetBefore: 10,
            },
          }}
          freeMode
          slidesOffset={0}
          slidesPerView={5}
          spaceBetween={40}
          slidesPerColumn={1}>
          { this.renderUpgradeColorsFromUpgradeItemCategory({ index }) }
        </SwiperCarousel>
```

Hopefully this helps someone as well

**Comment by liho98** [comment]
thanks, @Seanom i prefer your css solution!

**Comment by dippas** [comment]
> 
> 
> `watchOverflow: true` not work when loop is true,
> 
> @nolimits4web, First of all I must say thanks for this great free slider.
> Indeed when you have only 1 slide it means you can not go to next or previous slide because there is nothing to do then the pagination, navigation, scrollbar must not show even when the loop is true, or at least needs option to show/hide them.
> 
> I think this is increase usability and I suggest consider this or put option for it,
> 
> Thanks

I opened a new  issue regards to that #4747

**Comment by acevnn** [comment]
> Correct me if i'm wrong, but you could simply set `{ watchOverflow: true }` and as long as your single slide isn't wider than .swiper-container, it should do the trick.

But watchOverflow: true, only add a new css class which is "swiper-button-lock" I know that I can hide the navigation/pagination with css "display: none", but as I understood, watchOverflow should make them disappear by itself?

**Comment by miro-ux** [comment]
@acevnn It works only when `loop: false` would be nice if `watchOverflow` worked the same way with `loop: true`

**Comment by dippas** [comment]
> @acevnn It works only when `loop: false` would be nice if `watchOverflow` worked the same way with `loop: true`

 yup I opened a ticket about this #4747

**Comment by gleenk** [comment]
Not a nice way but it works. If you can't do anything server-side, adds a callback on init that count bullets. if there's only one, hide it
`on: {
				init: function(e){
					const bulletNumber = document.querySelectorAll('.swiper-pagination-bullet');
					/* Hide pagination */
					if(bulletNumber.length == 1){
						document.querySelector('.swiper-pagination').style.display = 'none';
					}
				}
			}`
