### ISSUE TITLE
I quoted swiper plug-in outside, NPM run build, wrong

### ISSUE THREAD

**Issue by lettywiterock** [nolimits4web/swiper#2577]
information:
Creating an optimized production build...
Failed to compile.

19.400dbb9d.async.js from UglifyJs
Unexpected token: operator (>) [19.400dbb9d.async.js:64602,43]

49.504adf06.async.js from UglifyJs
Unexpected token: operator (>) [49.504adf06.async.js:5765,43]
------------------------------------------------------------------------
Page code：

import Swiper from 'swiper';
swiper = new Swiper(‘class’, {
	loop:true,
	direction: 'vertical',
	initialSlide:0,
	 navigation: {
		 nextEl: '.swiper-button-next',
		 prevEl: '.swiper-button-prev',
	 },
})
----------------------------------------------
antd-pro:
npm start  OK
npm run build ERROR !

Unexpected token: operator (>) [19.400dbb9d.async.js:64602,43]

help me

**Comment by nolimits4web** [comment]
http://idangero.us/swiper/get-started/
Read "As an ES module" section
