### ISSUE TITLE
Not looping smoothly with freeMode enabled

### ISSUE THREAD

**Issue by Tucsky** [nolimits4web/swiper#2578]
This is a
* [x] bug

* Swiper Version: **4.2.2**
* Platform/Target and Browser Versions: **WINDOWS, OSX (and probably every os and browsers)**
* Live Link or JSFiddle/Codepen or website with isssue: **https://jsfiddle.net/o7b25rc9/26/**

### What you did
- Setup a slider with freescroll, loop, centeredSlide & multiple sides per view
 `{
  loop: true,
  centeredSlides: true,
  freeMode: true,
  slidesPerView: 'auto'
}`
- Freescroll FAST (or not, depending on number of slide you have in your slider) on a any direction

### Expected Behavior
- The slider continue to loop SMOOTH until freemode lose his velocity
> Slider create duplicates during freemode

### Actual Behavior
- The slider bounce on the last slide (which is centered) leaving a side of the slider EMPTY
> Slider does not create duplicates during freescroll until velocity is 

![demo](https://i.imgur.com/YrXJo0e.gif)

**Comment by nolimits4web** [comment]
This is by Swiper architecture design as it doesn't do any loop or anything else during transition
