### ISSUE TITLE
Thumb issue (Thumbs seem dependent on centeredSlides)

### ISSUE THREAD

**Issue by Scaalees** [nolimits4web/swiper#2580]
Hi,

I've been experimenting with the swiper controller and I can't seem to get the thumbs to work in the intended behaviour without applying `centeredSlides: true`. 

If you look at the demo link supplied, once you get to the 6th slide (either swiping or clicking the next arrow), the thumbs go back a slide. In addition, if you click the click the 6th slide in the thumbs, the other controller slides to the end.

Enabling `centeredSlides` seems to fix all of the issues above.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.2
* Platform/Target and Browser Versions: macOS - CHROME.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/scaalees/pen/vRbPvY

**Comment by nolimits4web** [comment]
In order to work correctly both of sliders must have same amounts of "snap points", so to make it work you need to add 3 empty slides to the bottom thumbs slider

**Comment by Scaalees** [comment]
Right, that doesn't really seem like a great solution and not what I'm looking for.

Related to this, is there anyway that you can make the thumbs static in movement, but still function with `slideToClickedSlide`. The example shows that you cannot click any of the thumbs due tono movement.

Is this also due to "snap points"?

Example: https://codepen.io/scaalees/pen/BrbxoQ

**Comment by nolimits4web** [comment]
`slideToClickedSlide` will not of course work because there is no where to slide

**Comment by Scaalees** [comment]
Well there is still an issue with the slides not interacting with the thumbs. Surely the corresponding thumb should be active with the slide. Is there anyway of adding the interactivity between the two carousels?

**Comment by nolimits4web** [comment]
This is how controller works, it depends on offset. If there is nowhere to slide then it won't work. To add interactiviry in this case, you to use callbacks on top slide to update "active" class on bottom slider, and add custom click handlers on bottom slider and call `slideTo` on top
