### ISSUE TITLE
Swiper not initializing when { init: false }

### ISSUE THREAD

**Issue by zabojad** [nolimits4web/swiper#2582]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.1.6
* Platform/Target and Browser Versions: everywhere actually (chrome on osx, chrome on Android, etc...)

The [documentation](http://idangero.us/swiper/api/#events) says:
> Event will be fired right after Swiper initialization. Note that with swiper.on('init') syntax it will work only in case you set init: false parameter:
> 
>     var swiper = new Swiper('.swiper-container', {
>       init: false,
>       // other parameters
>     })
>     swiper.on('init', function() { /* do something */ });
>     // init Swiper
>     swiper.init();
> Otherwise use it as the parameter:
> 
>     var swiper = new Swiper('.swiper-container', {
>       // other parameters
>       on: {
>         init: function () {
>           /* do something */
>         },
>       }
>     });

However if we do so (setting `init: false` in the parameters), swiper does not initialize at all...

So, either fix the doc or fix swiper :)...

**Comment by nolimits4web** [comment]
Read documentation carefully:

> swiper.init();

Have you seen this line?

**Comment by zabojad** [comment]
ah indeed, sorry for this unnecessary ticket...

Thanks for your answer!
