### ISSUE TITLE
Define measurement in vw rather than only px

### ISSUE THREAD

**Issue by saftle** [nolimits4web/swiper#2584]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: https://github.com/nolimits4web/swiper/commit/7d29094f011177e6313ddc23bd1dd568e2ea1acc
* Platform/Target and Browser Versions: [NWJS](https://nwjs.io/)
* Live Link or JSFiddle/Codepen or website with isssue: N/A.

### What you did
I wanted to specify the spaceBetween (as well as other settings) in vw rather than px. 

### Expected Behavior
Specifying whether the value is in vw or px measurement.

### Actual Behavior
Everything is defined in px.

**Comment by nolimits4web** [comment]
Set `slidesPerView: 'auto'` and you can specify in CSS like you need:
```
.swiper-slide {
  width: 30vw;
  margin-right: 10vw; /* space between */
}
```
