### ISSUE TITLE
Slides are blurred when the container is scaled down using transform:scale()

### ISSUE THREAD

**Issue by akshaykumarbu** [nolimits4web/swiper#2586]
I am scaling down the 'swiper-container' for the smaller screens using transform:scale() CSS method. And this is making the slides blur since the swiper-wrapper is having translate3d property on it. I am using the vertical scroll here. By replacing the translate3d to translateY in the developer console, the blurriness is gone. I also tried setting the roundLengths property to true. But, that didn't help! Let me know how I can solve this.

**Comment by nolimits4web** [comment]
Sorry, but translate3d is a must for performance optimization.

Closing as not related to Swiper
