### ISSUE TITLE
Loop without duplication?

### ISSUE THREAD

**Issue by yellow1912** [nolimits4web/swiper#2588]
This is a (multiple allowed):
* [] bug
* [] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: CHROME ON WINDOWS

### What you did
I was trying to enable loop feature for the slider without creating duplicated thumbnails.

### Expected Behavior
In some cases, you want to enable the loop, but you do not want to duplicate the thumbnails, you simply want it to jump back to the first thumb when it reaches the last step.

### Actual Behavior
Currently, the thumbnails will be duplicated to create a sense of continuous (loop)

**Comment by saftle** [comment]
+1

To add to this, it'd be cool if you could optionally disable loop duplication if "Number of items < SlidesPerView".

**Comment by saftle** [comment]
As a workaround (thanks to [Elaman](https://github.com/elaman)), you can also add the following under the `init` event:

```
var swiper = this;

if (swiper.originalParams.loop && swiper.loopedSlides < swiper.originalParams.slidesPerView) {
swiper.params.slidesPerView = swiper.loopedSlides;
swiper.destroy(false, false);
swiper.init();
}
```

**Comment by yellow1912** [comment]
that is an interesting fix actually, do you also have the issue with the thumbnails not being centered when you dont have enough items?
