### ISSUE TITLE
activeIndex miscalculation on screen orientation change

### ISSUE THREAD

**Issue by pooledge** [nolimits4web/swiper#2595]
This is a:
* [x] bug

* Swiper Version: 4.2.0.
* Platform/Target and Browser Versions: tested on latest Chrome @ MacOS 10.9.5
* http://idangero.us/swiper/demos/300-thumbs-gallery.html

### What you did
While using 2-way-controlled swipers from the stock example above, try to switch screen orientation (I am using DevTools, but a real world iPhone with Safari provides same experience).

### Expected Behavior
Active slide remains same, for both swipers.

### Actual Behavior
Active slide changes, also a slight shift revealing neighbour slide occurs (see screenshot https://ibb.co/jmqUpH)

I've initially reported this under https://github.com/nolimits4web/Swiper/pull/1766, so feel free to kill the unnecessary duplication. It seems to me, that changing following properties for galleryThumbs doens't change this behaviour:
- slidesPerView to an int
- slideToClickedSlide to false
- normalizeSlideIndex to false

**Comment by nolimits4web** [comment]
Fixed by https://github.com/nolimits4web/swiper/commit/bddcc0f323fdb5283f4271693e05c91eca95079e
