### ISSUE TITLE
auto slidesPerView does not work with angular 5

### ISSUE THREAD

**Issue by abbymrs** [nolimits4web/Swiper#2596]
I use `Swiper `with `angular 5` , but if I set `slidesPerView: 'auto‘`, the slides not work(cannot see all sliders), event i have set the `loopedSlides `. After checking the css code generated, i found that the `swiper-wrapper` is with the wrong `translate3d(1024px, 0px, 0px)`, and i cannot see the sliders.
**But if i resize the window, the sliders show!**
May I know why this happen?
Pls help to resolve this poblem, thanks a lot!

`sources codes:`

> AppComponent

```
import { Component, AfterViewInit } from '@angular/core';
import Swiper from 'swiper';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  silderVm: Swiper;
  ngAfterViewInit(){
    this.silderVm = new Swiper('.swiper-container', {
      loop: true,
      loopedSlides: 2,
      centeredSlides: true,
      spaceBetween: 60,
      slidesPerView: 'auto'
    })
  }
}
```

> app.component.html

```
<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide">Slide 1</div>
    <div class="swiper-slide">Slide 2</div>
    <div class="swiper-slide">Slide 3</div>
    <div class="swiper-slide">Slide 4</div>
    <div class="swiper-slide">Slide 5</div>
  </div>
  <!-- Add Pagination -->
  <div class="swiper-pagination"></div>
</div>
```

> app.component.css

```

html, body {
  position: relative;
  height: 100%;
}
body {
  background: #eee;
  font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
  font-size: 14px;
  color:#000;
  margin: 0;
  padding: 0;
}
.swiper-container {
  width: 100%;
  height: 100%;
}
.swiper-slide {
  text-align: center;
  font-size: 18px;
  background: #fff;
  width: 80%;
  /* Center slide text vertically */
  display: -webkit-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  -webkit-justify-content: center;
  justify-content: center;
  -webkit-box-align: center;
  -ms-flex-align: center;
  -webkit-align-items: center;
  align-items: center;
}

```

**Comment by kukac7** [comment]
@abbymrs demo link, please: https://angular-ttyp1e.stackblitz.io

**Comment by abbymrs** [comment]
@nolimits4web I made some changes according to your advise: Init Swiper in ngOnInit and update the swiper in ngAfterViewInit, and the sliders show.
But, the layout is still have some problem(left side of the first slider is blank), and it is hard to slide to next sliders, and event cannot slide to the third slider....

**Comment by abbymrs** [comment]
@nolimits4web Hi, i found another problem, if use fade effect, the sliders do not move....

**Comment by abbymrs** [comment]
@kukac7 hi, i saw your demo, when i swipe to the last slider, it has blank....

**Comment by abbymrs** [comment]
@nolimits4web i used setTimeout to update the sliders, and it works now, thanks a lot!

**Comment by abbymrs** [comment]
@nolimits4web another issue occurred, if the sliders' data is from api, then the swiper cannot work, only can drag to the 2nd slider, and i have update the swiper, still not work, could you help to solve this issue?
Thanks a lot!

Here is the demo link: [https://stackblitz.com/edit/angular-gnd8mj](https://stackblitz.com/edit/angular-gnd8mj)

**Comment by kukac7** [comment]
@abbymrs why do not you use this ngx wrapper? https://github.com/zefoy/ngx-swiper-wrapper
