### ISSUE TITLE
content will be hidden when slide down in safari(ios)

### ISSUE THREAD

**Issue by seasidesun** [nolimits4web/swiper#2597]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.0.2.
* Platform/Target and Browser Versions:  ios safari.
* Live Link or JSFiddle/Codepen or website with isssue: 
https://jsfiddle.net/ut0gcakp/   
http://sports.qq.com/kbsweb/qb/swiper-test.htm

### What you did
in the IOS browser, when fingers slide down on the screen，the content of second swiper will be hidden;

the diffrence of the two swiper is that first swiper's style has 

```
.swiper-container-a {
    overflow: initial;
}
```

and the second swiper ths the class(from the core.less):
```
.swiper-container {
    ... 
    overflow: hidden;
    ...
}
```

**Comment by nolimits4web** [comment]
Checking it on iOS and can't see any issues? Can you provide more details, maybe screen recording of what do you see?

**Comment by seasidesun** [comment]
here is the screenshot and recording：

[](http://7xii35.com1.z0.glb.clouddn.com/8EF495F97EE125CBBDED7A33D76D2E4D.jpg)

http://7xii35.com1.z0.glb.clouddn.com/99CCABC01D533E4929151BC977D1C154.mp4

**Comment by seasidesun** [comment]
here is the screenshot and recording：

http://7xii35.com1.z0.glb.clouddn.com/8EF495F97EE125CBBDED7A33D76D2E4D.jpg

http://7xii35.com1.z0.glb.clouddn.com/99CCABC01D533E4929151BC977D1C154.mp4
