### ISSUE TITLE
Swiper Prev Bug

### ISSUE THREAD

**Issue by bariskrdrl** [nolimits4web/swiper#2599]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
https://codepen.io/bariskaraderili/pen/LmZpRy

### Expected Behavior
When I press the slider back button 1 slide needs to go

### Actual Behavior
3 slides going when I press the slider back button

https://codepen.io/bariskaraderili/pen/LmZpRy

**Comment by mlegait** [comment]
I have exactly the same issue here : https://codepen.io/mlegait/pen/NMRNvv

I go to the slide 3 by clicking on the right arrow. Then I click on the left arrow, and I arrive directly on the slide 0 jumping slides 2 and 1.

**Comment by bmurashin** [comment]
Same here. In slidePrev() function a call to swiper.loopFix() can set swiper.translate to a value, not present in swiper.snapGrid. That happens when diff is not 0:

```
    if (slideChanged && diff !== 0) {
      swiper.setTranslate((rtl ? -swiper.translate : swiper.translate) - diff);
    }
```

Next, this part in slidePrev() gets `prevSnap` and `prevIndex` == null

```
  var translate = rtlTranslate ? swiper.translate : -swiper.translate;
  var currentSnap = snapGrid[snapGrid.indexOf(translate)];
  var prevSnap = snapGrid[snapGrid.indexOf(translate) - 1];
  var prevIndex;

  if (prevSnap) {
    prevIndex = slidesGrid.indexOf(prevSnap);
    if (prevIndex < 0) { prevIndex = swiper.activeIndex - 1; }
  }
```
And next, `slideTo(null, ...)` stops the show

**Comment by mlegait** [comment]
@nolimits4web Thank you very much for having managed this issue so quickly 😄 

But ... I've updated my CodePen (https://codepen.io/mlegait/pen/NMRNvv) to use the last version of swiper (https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.6/css/swiper.css and https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.6/js/swiper.js) and I still encounter the issue 😕 

Am I wrong somewhere?

**Comment by nolimits4web** [comment]
@mlegait it is not released yet

**Comment by mlegait** [comment]
Oh sorry 😅

An thank you very much for your reactivity.

**Comment by 7iomka** [comment]
Any news? Latest version and issue isn't fixed(

**Comment by bariskrdrl** [comment]
Why issues closed? @nolimits4web 
I have problem
https://codepen.io/bariskaraderili/pen/LmZpRy

**Comment by hacknug** [comment]
@bariskrdrl you're not using the latest Swiper version in that pen…

**Comment by bariskrdrl** [comment]
@hacknug Lastest version width update.the problem continues

**Comment by mlegait** [comment]
@bariskrdrl : As @nolimits4web said, the fix is not released yet. We have to wait for the next release 😄

**Comment by davorpeic** [comment]
Installing latest 4.3.3. version fixes this issue :)
