### ISSUE TITLE
sliderPerView: 'auto' is moving slides too far to the left 

### ISSUE THREAD

**Issue by brynshanahan** [nolimits4web/swiper#2604]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.2
* Platform/Target and Browser Versions: Platform all, target IE11, Edge, Chrome, Safari
* https://www.sff.org.au/program/browse/ghost-stories (swiper instance is accessible at `window.slider`)

### What you did
```javascript
this.slider = new Swiper(this.element[0], {
   speed: 600,
   slideToClickedSlide: true,
   autoplay: { 
     delay: 5000,
     disableOnInteraction: false
   },
   preloadImages: false,
   watchSlideVisibility: true,
   loop: true,
   loopedSlides: this.children.length,
   slidesPerView: 'auto',
   loopAdditionalSlides: this.children.length,
   keyboard: {
      enabled: true,
      onlyInViewport: false
   },
   on: {
      slideChangeTransitionEnd: animateButton(this, $),
         lazyImageReady: function (...els) {
            // Fade in animation
            anime({
               targets: els,
               opacity: [0, 1],
               duration: 600,
               easing: 'easeOutQuad'
            })
         }
      }
   })
```
<img width="786" alt="sketch1" src="https://user-images.githubusercontent.com/37826020/39340131-bcacb6d8-4a0f-11e8-841d-9b15987f7f4a.png">

```javascript
this.slider = new Swiper(this.element[0], {
   speed: 600,
   slideToClickedSlide: true,
   autoplay: { 
     delay: 5000,
     disableOnInteraction: false
   },
   preloadImages: false,
   watchSlideVisibility: true,
   loop: true,
   loopedSlides: this.children.length,
   // slidesPerView: 'auto',
   loopAdditionalSlides: this.children.length,
   keyboard: {
      enabled: true,
      onlyInViewport: false
   },
   on: {
      slideChangeTransitionEnd: animateButton(this, $),
         lazyImageReady: function (...els) {
            // Fade in animation
            anime({
               targets: els,
               opacity: [0, 1],
               duration: 600,
               easing: 'easeOutQuad'
            })
         }
      }
   })
```
<img width="841" alt="sketch" src="https://user-images.githubusercontent.com/37826020/39340139-cb317e50-4a0f-11e8-84e5-1eeaf78ad734.png">

### Expected Behavior
Slides should be at the same position when slidesPerView is set and unset

### Actual Behavior
On `slidesPerView: 'auto'` slides are being positioned incorrectly to the left

**Comment by nolimits4web** [comment]
Live example or JSFiddle with the issue?

**Comment by northkode** [comment]
I'm having this issue too. The demo shows  slidesPerView:'auto' and centerSlides:true, and the first slide is centered

When i do the same thing the first slide is all the way to the left of the container, not in the center.
