### ISSUE TITLE
Swiper sometimes moves oppositely when using mouse

### ISSUE THREAD

**Issue by zap-mueda** [nolimits4web/swiper#2610]
I click prev button or next button with the mouse. Swiper sometimes moves oppositely.

This is demo movie.
![mouse4](https://user-images.githubusercontent.com/12146028/39465290-7ce28e32-4d5d-11e8-98e2-5cbd7b28e83d.gif)

Do you have any solutions?

**Comment by fadeyev** [comment]
Observed the same issue: both in Firefox and Chrome. To reproduce click repeatedly on navigation buttons on Navigation demo: http://idangero.us/swiper/demos/

**Comment by nolimits4web** [comment]
It is not the issue, it is because you do a short swipe instead of click. It is configurable via parameters

**Comment by fadeyev** [comment]
Then probably defaults need to be adjusted to make them less susceptible to short mouse swipes.
