### ISSUE TITLE
Loop not working if the browser is set to 90% zoom (chrome)

### ISSUE THREAD

**Issue by yvannnoto** [nolimits4web/swiper#2614]
Hi,

I'm experiencing an issue when my swiper is set to loop : true. My swiper is doing weird jumps after a few clicks on the right arrow. Once i'm at the end of my swiper, it's doing weird jumps and not looping anymore, but if I go backwards (left arrow), the swiper is working properly.

I can only experiencing this issue on my browser (chrome) is set to 90% zoom, but not 100% and higher. I don't have the problem with Firefox.

Did someone have the same issue ?

Thanks a lot for your help.

Regards,
Yvann.

if($('.soutien-container').length ){
        var mySwiper = new Swiper ('.soutien-container', {
            // Optional parameters
            direction: 'horizontal',
            spaceBetween: 65,
            centeredSlides: true,
            speed: 200,
            initialSlide: 5,
            loop: true,
            slidesPerView: 'auto',
            preventClicks: true,

            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
        });
    }

**Comment by nolimits4web** [comment]
Sounds like Chrome issue, Swiper doesn't do anything with zooming
