### ISSUE TITLE
3d effect bug

### ISSUE THREAD

**Issue by luweiCN** [nolimits4web/swiper#2615]
*[x] While I run the code in 3D effect mode. When the sliders switch, the slider come through the pagination, so that the pagination disappear.Here is a gif for it.This happens only in my IPhone.The gif is a little bit big is size(24MB), so it should take some time to download.
[image](https://drive.google.com/open?id=1cSOX6bVfBvTczZjNawye0Sgq2yteYB9W)

**Comment by nolimits4web** [comment]
This is how Safari renders 3D effects. Nothing can do here. You can tweak pagination position styles to put it in different place, like a little bit lower
