### ISSUE TITLE
Lazyload background image before Destroy

### ISSUE THREAD

**Issue by babyPrince** [nolimits4web/swiper#2617]
Hey @nolimits4web,
I'm running a destroy for mobile situation. If used without lazy loading, images load normally, but since I'm destroying the slideshow, seems it's also killing the lazy loading (i'm having the images as background). 

Is there a way to sneak in something like
`mySwiper.lazy.load();` or `mySwiper.lazy.loadInSlide(index);` for all slides

before running 
`if (mySwiper !== undefined) mySwiper.destroy(true, true);`

```
(function() {
  "use strict";

  // breakpoint where swiper will be destroyed
  const breakpoint = window.matchMedia("(max-width:992px)");

  // keep track of swiper instances to destroy later
  let mySwiper;

  const breakpointChecker = function() {
    if (breakpoint.matches === true) {

      // clean up old instances and inline styles when available
      if (mySwiper !== undefined) mySwiper.destroy(true, true);

      // or/and do nothing
      return;

    } else if (breakpoint.matches === false) {
      // fire large viewport version of swiper
      return enableSwiper();
    }
  };

  const enableSwiper = function() {
    mySwiper = new Swiper(".swiper-container", {
      lazy: true,
      loop: true
    });
  };

  // keep an eye on viewport size changes
  breakpoint.addListener(breakpointChecker);

  // kickstart
  breakpointChecker();
})();
```

**Comment by nolimits4web** [comment]
Sorry, but no way to keep loading it after destroying since it can produce memory leaks and other unwanted side effects. Destroy means destroy, no more Swiper functionality can happen after destroying

**Comment by babyPrince** [comment]
@nolimits4web 
What I'm trying to do is basically have a slideshow for desktop and each slide below each other on mobile. Is there a way to approach this?
