### ISSUE TITLE
custom pagination bullets separator bug

### ISSUE THREAD

**Issue by pbuzdin** [nolimits4web/swiper#2622]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.2.6
* Platform/Target and Browser Versions: Win7/Chrome66 (may be any platform/browser)
* http://output.jsbin.com/kewabom

### What you did
I added an aditional element to pagination bullets and this broke bullets standart behavior: clicking 2 bullet doesn't navigate me to 2 slide

### Expected Behavior
clicking second bullet should navigate me to 2 slide.

### Actual Behavior
I dont know

**Comment by nolimits4web** [comment]
pagination render must return single element. Such separators can be made with CSS styles
