### ISSUE TITLE
Animate.css only triggering on first element

### ISSUE THREAD

**Issue by andyiwest** [nolimits4web/swiper#2626]
I'm using animate.css, but it only applies to the very first instance, every other slider's text remains unanimated, is this doable?

> <div class="swiper-slide">
            <h1 class="animated zoomIn">Test Heading</h1> <-- Only this heading animates
            <img src="path-to-image.jpg" width="100%" height="100%">
</div>

> <div class="swiper-slide">
            <h1 class="animated zoomIn">Test Heading 2</h1>
            <img src="path-to-image-2.jpg" width="100%" height="100%">
</div>

**Comment by shimbala** [comment]
Animation is applied to all instances at same time. You have to add class "animated" to element when slide transition is finished  (on event transitionEnd or slideChangeTransitionEnd or slideChange)

**Comment by andyiwest** [comment]
Is there some documentation for this?

**Comment by nolimits4web** [comment]
Closing as not actually related to Swiper
