### ISSUE TITLE
How to make slider start at specific slide?

### ISSUE THREAD

**Issue by oneezy** [nolimits4web/swiper#2627]
How to make slider start at specific slide?

**Comment by oneezy** [comment]
For anyone else wondering, it was super simple:

```
var mySwiper = new Swiper ('#mySwiper', {
	
	direction: 'horizontal',
	loop: false
	
});

mySwiper.slideTo(1, false,false);
```

**Comment by nolimits4web** [comment]
Actually there is a `initialSlide` parameter that you can pass http://idangero.us/swiper/api/#parameters
