### ISSUE TITLE
Pagination bullets don't show up in Bootstrap3 hidden tabs

### ISSUE THREAD

**Issue by hagisuda** [nolimits4web/swiper#2628]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 4.2.6
* Platform/Target and Browser Versions: Windows, CHROME, Bootstrap3
* Live Link or JSFiddle/Codepen or website with isssue: 

https://codepen.io/Hagisu/pen/JvmZRj

### What you did
I added each Swiper into each Bootstrap tab. 

### Expected Behavior
Each Swiper is supposed to show all pagination bullets on each tab.

### Actual Behavior
Swipers in hidden tabs(from the second tab) didn't show the  pagination bullets.

**Comment by nolimits4web** [comment]
This question was discussed many times here, you need to update swiper or use observer in hidden tabs. Please, use search in issues

**Comment by hagisuda** [comment]
Thanks for your answer. 
Observer and observeParents work as a charm.
