### ISSUE TITLE
Never use if(var) to check the existence

### ISSUE THREAD

**Issue by iamrototo** [nolimits4web/swiper#2635]
on methods
  function slidePrev (speed, runCallbacks, internal) {

line 2117
if (prevSnap) {}

need to be replaced by

if (prevSnap !== undefined && prevSnap !== null) {

Otherwise, it can happen that if the prevSnap value is 0, the click on the arrow go to the first slide of the slider instead of the previous one.

**Comment by nolimits4web** [comment]
Was fixed in e9ebeb0
