### ISSUE TITLE
Links in Swiper slides

### ISSUE THREAD

**Issue by cedi-code** [nolimits4web/swiper#2638]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.2.6
* Platform/Target and Browser Versions: Windows 10 PC, Google Chrome
* Live Link or JSFiddle/Codepen or website with isssue: 
http://cedilabs.de/labs/2/Portfolio_Layout/

### What you did
I'm trying to make a website layout with Swiper.js. I want to add Links and buttons in the swiper slides.
I know the parameters     preventClicks: false, & preventClicksPropagation: false 

```javascript
var names = [];
$(".swiper-wrapper .swiper-slide").each(function(i) {
    names.push($(this).data("name"));
});

var swiper = new Swiper('.swiper-container', {
    preventClicks: false,
    preventClicksPropagation: false,
    keyboard: {
        enabled: true,
    },
    pagination: {

        el: '.swiper-pagination',
        clickable: true,
        hoverState: true,
        renderBullet: function (index, className) {
            console.log(index);
            return '<span class="' + className + '"><p>' + (names[index]) + '</p></span>';
        },
    },
    history: {
        key: 'slide',
    },
});
```

```html
<div class="swiper-slide center-slide" data-name="About" data-history="about">
            <div class="tablebox">
                <div class="tablebox-cell">
                    <div class="tablebox-content">
                        <h1 style="float: left">
                            Links
                        </h1>
                        <div class="typing-animation-line"></div>
                        <a href="#">
                            test
                        </a>
                    </div>
                </div>

            </div>
        </div>
```

### Expected Behavior
all links in the swiper slide can be clicked. 

### Actual Behavior
but the parameters preventClicks  only work in the div swiper-slider. If you have an extra div with a link in it, it can't be pressed or hoverd.

example: 
http://cedilabs.de/labs/2/Portfolio_Layout/

**Comment by nolimits4web** [comment]
This is because your custom pagination overlays slides and links:

<img width="1374" alt="screen" src="https://user-images.githubusercontent.com/999588/40584917-6d3493f4-61b2-11e8-9043-2e38cb931ee3.png">
