### ISSUE TITLE
Please specify "old browsers"

### ISSUE THREAD

**Issue by pixelass** [nolimits4web/swiper#2639]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
* [x] Question

**Readme.md**

> [...] or you need old browsers support [...]

Which browsers are considered "old" or "modern". 

Please add a list of supported browsers (browser-matrix)

**Comment by shashank1010** [comment]
In my experience, most things work on IE10+ including Edge
The swiper works a charm on Chrome, Safari and Mozilla Firefox

**Comment by pixelass** [comment]
Moving away from github. Feel free to reopen if interested.
