### ISSUE TITLE
Issue with bootstrap flexbox

### ISSUE THREAD

**Issue by sonupandit** [nolimits4web/swiper#2640]
I have a bootstrap layout with sidebar, when swiper initialized. layout broke up and slider stretched to the full width.
please check codepen demo-

https://codepen.io/pndtsonu/pen/deLgBa?editors=1010

**Comment by nolimits4web** [comment]
Can't see any issues in your pen

**Comment by sonupandit** [comment]
@nolimits4web Just comment initialization script and you will see the changes in layout.
I have fix this by adding following css.

`.swiper-slide{
  width: auto !important;
  flex-basis: 100%;
}`

**Comment by nolimits4web** [comment]
Closing as fixed
