### ISSUE TITLE
questions about a multi-row layout

### ISSUE THREAD

**Issue by xiangrenya** [nolimits4web/swiper#2642]
This is a (multiple allowed):
* [x] bug
### What you did
visit: https://codepen.io/xiangrenya/pen/KRLaJo
### Expected Behavior
slide 6 is in row 3, column 2
### Actual Behavior
slide 6 is not in row 3, column 2

**Comment by shashank1010** [comment]
I've created a add slide button for a swiper that has 10 slidesPerView and 5 slidesPerColumn
The following link will help you understand how the slides are added.
https://jsfiddle.net/px5j4a2t/4/

I do not know the logic to render it this way, but it makes sense to not show a column which has 1/2/3 cells where as all others have 5. This way there is a balance between adjacent columns.

**Comment by nolimits4web** [comment]
Or https://codepen.io/anon/pen/mKPvpz
