### ISSUE TITLE
Freemode - (And official demo) - not working in Chrome iOS

### ISSUE THREAD

**Issue by psmod2** [nolimits4web/swiper#2645]
See the official demo

http://idangero.us/swiper/demos/150-freemode.html

This isn’t working as it does in Safari on Chrome. 

It’s jumping slides. 

Observed on iOS
Safari - ok
Chrome - broken

**Comment by nolimits4web** [comment]
Can’t see any issues with it. If you see any issues create new issue and fill issue form correctly
