### ISSUE TITLE
Previous sliders are hidden

### ISSUE THREAD

**Issue by RicardoRibeirorr** [nolimits4web/swiper#2646]
* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: Windows, CORDOVA, CHROME

### What you did:
            var swiper = new Swiper('.swiper-container', {
                slidesPerView: 2,
                spaceBetween: 10,
                lazy: true,
                pagination: {
                    el: '.swiper-pagination',
                    clickable: true,
                    dynamicBullets: true,
                },
            });

### Explanation
I'm getting data with ajax and using it with Mustache(like template7), and then after instantiate the elements, i'm calling the swiper with a limit of 2 elements for slide.
It works well, the problem appears when i try to see the others slides.. they seem to be there, but they are not visible.
Note: the active class is change to the elements as expected. Everything seems to be alright! 

### Expected Behavior
Show the present slide elements when appear.

### Actual Behavior
They still hidden.

**Comment by nolimits4web** [comment]
Would be good to see JSFiddle or codepen with the issue
