### ISSUE TITLE
Custom Fraction "its own parameter 0"

### ISSUE THREAD

**Issue by Cheizerman** [nolimits4web/swiper#2652]
Good afternoon! Thank you very much for the cool slider! I always use it. I really need your help in a small business.
I use pagination as a type fraction, everything works fine, but according to the designer's idea, you need to add 0 before the number, tell me please how to do it right? I'm not strong at JS, I'm just learning: (in the example below I try to do it but it does not work like this.

`pagination: {
                    el: $('#slider .swiper-pagination')[i],
                    type: 'fraction',
                    renderFraction: function (currentClass, totalClass, index) {
                        return '<span class="' + currentClass + '">0 '+ index +' </span>' +
                            ' / ' +
                            '<span class="' + totalClass + '">0 '+ total +' </span>';
                    },
 `

How I want what would look like a result of "01/02" the first number is the current slide ordinal number, and the second is the total number of slides.
How to implement this? Tell me please!

**Comment by nolimits4web** [comment]
Added two new pagination parameters `formatFractionCurrent` and `formatFractionTotal` to handle this case, will be in next release

**Comment by Cheizerman** [comment]
Thank you! While I decided on css :)

`.swiper-pagination-current:before{
  content: "0"
}

.swiper-pagination-total:before{
  content: "0"
}`
