### ISSUE TITLE
Can't find variable: Dom7 - iOS 10

### ISSUE THREAD

**Issue by ozasadnyy** [nolimits4web/Swiper#2654]
This works everywhere except Safari 10.

![web inspector iphone 7 safari localhost 2018-06-01 17-20-39](https://user-images.githubusercontent.com/2954281/40845724-3f68f17e-65c0-11e8-8aac-8dfd6e1d23fd.png)

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.0.
* Platform/Target and Browser Versions: iOS10 Safari.

### What you did
I am using webpack 4.8.3 with babel 7.0.0-beta.49. Run transformation as mentioned in the documentation

*webpack.config.js*
```
module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
                loaders: ['babel-loader'],
            },
            ...
```

*.babelrc*
```
{
    "presets": [
        "@babel/preset-react",
        "@babel/preset-flow",
        [
            "@babel/preset-env",
            {
                "targets": {
                    "browsers": [
                        ">0.25%",
                        "not ie 11",
                        "not op_mini all"
                    ]
                },
                "useBuiltIns": "usage"
            }
        ]
    ],
    "plugins": [
        "transform-class-properties",
        [
            "@babel/plugin-proposal-decorators",
            {
                "legacy": true
            }
        ],
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-proposal-export-default-from",
        "@babel/plugin-transform-block-scoping",
        "lodash"
    ],
}
```

`babel-polyfill` is included in the entry.

### Actual Behavior
`Dom7` is undefined. However, the class defined at the top of the file `dom7.modular.js`.
![web inspector iphone 7 safari localhost 2018-06-01 17-08-32](https://user-images.githubusercontent.com/2954281/40845853-8edd0e5c-65c0-11e8-9669-43ec0dbca9aa.png)

**Comment by nolimits4web** [comment]
There is something wrong with your webpack/babel setup

**Comment by joeribakker** [comment]
I'm also experiencing this exact issue. I'm also on Webpack 4, and include `ios >= 7` in my browserslist.

**Comment by hsxfjames** [comment]
Renaming `.babelrc` to `babel.config.js` works fine in my case. I think you could also have a try if you are using babel@7.
See: https://babeljs.io/docs/en/config-files
