### ISSUE TITLE
Previous Navigation bug when slidesPerView: 'auto', centeredSlides: true, and loop:true

### ISSUE THREAD

**Issue by Matra-Simca** [nolimits4web/swiper#2656]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.2
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/MatraSimca/L063jo3x/25/

### What you did

Using the main demo for "Centered Slides + Auto Slides Per View" on the Swiper website, I added only the navigation html:

    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>

and the options:

`loop: true,
 loopedSlides: 10,
 roundLengths: true,
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      }, `
### Expected Behavior
Clicking the Previous navigation moves through the slides in sequence

### Actual Behavior
Clicking the Previous navigation makes the Swiper behave erratically, either moving repeatedly to the first slide or moving only between the first and last slide.

The bug happens 99% of the time depending on viewport width. I have noted in testing that when using fixed width slides (explicit px) the issue only occurs when `roundLengths: true` is used.

**Comment by nolimits4web** [comment]
Pushed fix for this but there is no sense to use `roundLengths` with percentage slides widths
