### ISSUE TITLE
virtualTranslate not working AT ALL.

### ISSUE THREAD

**Issue by ndimatteo** [nolimits4web/swiper#2657]
This is a:
* [x] bug

* Swiper Version: **4.3.2**
* Platform/Target and Browser Versions: **Chrome**
* Live Link or JSFiddle/Codepen or website with isssue:
1. https://layout.wydown.nickdimatteo.com
2. https://codepen.io/ndimatteo/pen/QxNWmq

### What you did
I set `virtualTranslate: true`, and I added `disableOnInteraction: false` and `waitForTransition: false` to the `autoplay` options.

### Expected Behavior
I would expect swiper to behave AS-IS, just simply not translate the swiper container. Allowing me to style and position slides how I'd like, and manipulate the transition to the active slide on my own.

### Actual Behavior
The entire swiper stops working. `slidePrev()` and `slideNext()` no longer work. The active slide is not being updated.

**For the record I love Swiper, I've used it on countless projects but man this is frustrating. I don't understand why the whole plugin breaks down when we want to use our own transition effects. You claim to support this but it works HORRIBLY.**

**Comment by nolimits4web** [comment]
Example on what did you try would be extremely helpful, JSFiddle even better

**Comment by ndimatteo** [comment]
@nolimits4web I shared a dev url where it's happening in the original, but let me pull it apart into a pen for you. Hang tight!

**Comment by ndimatteo** [comment]
@nolimits4web here you go: https://codepen.io/ndimatteo/pen/QxNWmq

I've isolated Swiper here, and you can see that it behaves totally unexpectedly, and simply does not progress on prev/next clicking.

**Comment by nolimits4web** [comment]
Loop mode has a lock to prevent slide change when it is animating, swiper has an `animating` flag on "transition" start which supposed to be unset automatically on transition end. You don't have any transition, so you need to do it manually https://codepen.io/anon/pen/MXyzEr (added `slideChangeTransitionStart` callback)
