### ISSUE TITLE
Кастомизация слайдов (разная ширина)

### ISSUE THREAD

**Issue by nikki2lol** [nolimits4web/swiper#2658]
Добрый день!
Не могу разобраться, возможно ли задать слайдам разную ширину, не переписывая при этом изначально заложенную логику.
Есть контейнер в 1400px, в нем должно отображаться 3 слайда. Активный слайд имеет ширину 800pх и располагается по центру,, а предыдущий и следующий по 200px, между всеми слайдами  расстояние в 100px.
Изначальный код для прорисовки такого слайдера у меня выглядит так:
```
    var mainSlider = new Swiper('.main-slider__container', {
        slidesPerView: 'auto',
        spaceBetween: 100,
        loop: true,
        centeredSlides: true
      });
```

Но в таком случае слайдер не совсем корректно понимает расстояние, на которое ему необходимо прокрутиться. Установка setTranslate(200) совсем ломает все
Есть ли способ кастомизировать слайды с разными параметрами ширины/высоты, не переписывая при этом заложенную Вами первоначальную логику переключения классов для слайдов?

**Comment by nolimits4web** [comment]
Нет, по умолчанию это не поддерживается
