### ISSUE TITLE
Not adding swiper-button-disabled on last slide

### ISSUE THREAD

**Issue by amouratoglou** [nolimits4web/swiper#2660]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did

Hey! Thanks for such amazing slider...

I have updated to swiper 4.3.2 

The next arrow doesn't get the class added on the last slide, then the arrow is visible. 

http://www.danielleandagustin.com/pt/testimonials/
pass 123

```

    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
       paginationClickable: true,
        direction: 'vertical',  
    speed: 900, loop: false,
     parallax:true,
        mousewheel: {
    invert: false,
  },
     mousewheelReleaseOnEdges: true,
        nextButton: '.swiper-button-next',
       prevButton: '.swiper-button-prev'


    });
```

### Expected Behavior

The class swiper-button-disabled  to be added to the arrow on last slide.

### Actual Behavior

It doesn't work.

thanks

**Comment by nolimits4web** [comment]
You have wrong parameters. Check the v4 API http://idangero.us/swiper/api/
