### ISSUE TITLE
mousedown/up events not firing in MacOS Chrome

### ISSUE THREAD

**Issue by kmturley** [nolimits4web/swiper#2669]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 4.3.3
* Platform/Target and Browser Versions: MacOS 10.12.6, Chrome 67.0.3396.79
* Live Link or JSFiddle/Codepen or website with issue: http://jsfiddle.net/kmturley/1gL7e2ch/

### What you did
Created an example from your first demo, then added an id:
```
<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide" id="example">Slide 1</div>
    <div class="swiper-slide">Slide 2</div>
    <div class="swiper-slide">Slide 3</div>
  </div>
</div>
```
Then added event listeners:
```
var example = document.getElementById('example')
example.addEventListener('mousedown', () => {
  console.log('mousedown')
  example.innerHTML = 'mousedown';
})
example.addEventListener('mouseup', () => {
  console.log('mouseup')
  example.innerHTML = 'mouseup';
})
```

### Expected Behavior
Expect event to fire, works fine in MacOS Firefox and Safari, but not Chrome 67.0.3396.79

### Actual Behavior
Event is not being fired!

**Comment by kmturley** [comment]
No thanks! Would like to know of it's something needing a fix

**Comment by wilsonssss** [comment]
we are facing the same issue right now, macOS 10.14.2, Chrome  71.0.3578.98, Safari 12.0.2

**Comment by Daijobou** [comment]
Here too. Why swiper steals the event?
