### ISSUE TITLE
Multiple controllers: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by qmorel** [nolimits4web/swiper#2672]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.3.3 and lower
* Platform/Target and Browser Versions: Chrome, Fx…
* Live Link or JSFiddle/Codepen or website with issue: https://jsfiddle.net/bgo0rcft/19/

### What you did
Just trying to inter-connect 3 or more swiper. Code example with different tests in the Fiddle (in comment on the JS section)

### Expected Behavior
All swiper connected

### Actual Behavior
Get the "Uncaught RangeError: Maximum call stack size exceeded" error in console when trying to swipe one slider.

I see this is an old issue, not really solved. Hope my code example could help. If you have a real solution for this or a patch/trick :)

Related to https://github.com/nolimits4web/Swiper/issues/1322

**Comment by 7iomka** [comment]
I have the same problem on my current project.
I needed to make 3 connected sliders (at least)
It seems to me that the problem of memory leakage is the cross-calculating transition and transform.
My friend suggested to me the option to implement the mechanics of the controller without using it.
That's how I solved my problem: https://codepen.io/7iomka/pen/xJddmR?editors=0010
This is a temporary solution that has a number of caveats:
1) This implementation is not suitable for cases **where the width of the slides is different**
2) This implementation requires additional style processing to ensure cross-browser compatibility

I would like to hear from the creator of the plugin any comments on this account, why controllers do not work crosswise? And can we somehow solve this problem in a different way?
Thanks in advance!
