### ISSUE TITLE
Autoplay stops working when you change the browser window breakpoint

### ISSUE THREAD

**Issue by Ghost180195** [nolimits4web/swiper#2677]
Swiper version: 4.3.3
Browser: Google Chrome 67 (64 bit)
OS version: Windows 10 
Link: [Test here](https://codepen.io/anon/pen/BVdpBz?editors=0010)

**Comment by nolimits4web** [comment]
You need to set `autoplay.disableOnInteraction: false` parameter to keep it sliding
