### ISSUE TITLE
Incompatibility with rollup ^0.61

### ISSUE THREAD

**Issue by jonnitto** [nolimits4web/swiper#2680]
This is a:
* [x] bug

* Swiper Version: v4.3.3
* Platform: macOS

I have done a custom [build](http://idangero.us/swiper/api/#custom-build) from the Swiper:

```js
import {
    Swiper,
    Mousewheel,
    Navigation,
    Pagination,
    Lazy,
    HashNavigation,
    Autoplay,
    EffectFade
} from "swiper/dist/js/swiper.esm.js";

Swiper.use([
    Mousewheel,
    Navigation,
    Pagination,
    Lazy,
    HashNavigation,
    Autoplay,
    EffectFade
]);
```

 If I use`rollup ^0.61` I get following error:

``` 
Cannot use 'in' operator to search for 'MutationObserver' in undefined
```

Below the Version, 0.61 everything works fine.

**Comment by nolimits4web** [comment]
Looks like you have problems in your build, make sure you have `rollup-plugin-node-resolve` and `ssr-window` package is correctly included to your build

**Comment by jonnitto** [comment]
Thank you for your fast answer. I have `rollup-plugin-node-resolve` in my build system. The strange thing is, that below version 0.61 everything works. In line 14 of `swiper.esm.bundle.js` and `swiper.esm.js` swiper imports stuff from `dom7`, which also imports `ssr-window`. The strange thing is: If I remove the import of `ssr-window` in swiper (line 15) the build works and the swiper also…

**Comment by jonnitto** [comment]
I've built over the last year this package, and I would really like to fix this problem: https://github.com/CarbonPackages/Carbon.Gulp

I deeply know that this is not your problem, but I would really appreciate If you could give me a hint. Of course, I would give credits to you in the release notes…

**Comment by nolimits4web** [comment]
Can you setup a minima reproduction repo so i can take a look?

**Comment by jonnitto** [comment]
Great! I invited you to https://github.com/jonnitto/RollupFix

**Comment by anteprimorac** [comment]
It's related to https://github.com/rollup/rollup/issues/2316 issue. It seems like rolling back to rollup 0.60.x is the only solution for now.

**Comment by jonnitto** [comment]
I've updated the [repo](https://github.com/jonnitto/RollupFix) and with version [0.63.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0630) I get following error
```
Cannot use 'in' operator to search for 'ontouchstart' in undefined
```
