### ISSUE TITLE
Sliding not moving and activating bullets

### ISSUE THREAD

**Issue by EA12** [nolimits4web/swiper#2681]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.6.
* Platform/Target and Browser Versions: CHROME or EDGE.

What I did:
In a React-Project I import Swiper like so:
`const Swiper = require('swiper/dist/js/swiper.min.js');
let swiperInstance = null;`

In a initialization method I create an Swiper-Instance:
`swiperInstance = new Swiper('.swiper-roomnews', {
	pagination: {
		el: '.swiper-pagination-roomnews',
		type: 'bullets',
		clickable: true,
		renderBullet(index, className) {
			return '<span class="${className} ${sliderStyles.connexBullet}"></span>';
		}
	},
	enablePagination: true
});`

[Example-Code.txt](https://github.com/nolimits4web/swiper/files/2123630/Example-Code.txt)
See Container-Code in attachment (your code markdown is mixing my code)

### Expected Behavior
If I slide by mouse, the bullets should move also and be activated.

### Actual Behavior
Only if I slide (by mouse) to the last or the first, the bullet will move.
Prev- and next-Button (Chevrons) are working as exspected. Clicking the bullets is working also (moving and activation)

From the picture you will see that the first bullet is active while this is not the first slide.

![slider_forum](https://user-images.githubusercontent.com/22025808/41719049-264eed34-755f-11e8-9c40-f851d6d2ca00.png)

Further Investigation.
The activeIndex is not set when sliding by mouse but when clicking the bullets or the pagination Buttons. I verified this by adding slideChange-event.
`on: {
		slideChange() {
			console.log('slide changed: activeIndex:='+swiperInstance.activeIndex);
		}
	} `

**Comment by nolimits4web** [comment]
Would be good to see live example with the issue

**Comment by EA12** [comment]
I just added a Code pen and realized that Code pen did not compile our scss (mixin, includes), so I changed the css to Default css and put all classes to the same Level. Then I could not reproduce the error. So I will Change the css in my Project and let you know if this is the case.
