### ISSUE TITLE
Sliding by mouse causing Error

### ISSUE THREAD

**Issue by EA12** [nolimits4web/swiper#2682]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.6.
* Platform/Target and Browser Versions:  CHROME or EDGE.

What I did:
If I slide by mouse the UI is working but console logs Errors.

Please see my initialisation code and container in attachment.
[Example-Code.txt](https://github.com/nolimits4web/swiper/files/2123680/Example-Code.txt)

### Expected Behavior
The console should not report such error.

### Actual Behavior
Under Chrome I get following error:
`swiper.js:933 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.getTranslate (swiper.js:933)
    at t.getTranslate (swiper.js:1811)
    at t.<anonymous> (swiper.js:2701)`

In debuging-mode I can see that ..
var a=i.getComputedStyle(e,null);return i.WebKitCSSMatrix?((r=a.transform||a.webkitTransform).split(",").length>6…

Under Edge the same Test-Case leads to following error:
`SCRIPT5007: Unable to get property 'transform' of undefined or null reference`

In debuging-mode I can see that .. var a=i.getComputedStyle(e,null);return i.WebKitCSSMatrix?((r=a.transform||a.webkitTransform).split....

a will be null so a.transform will raise the error.

This might effect slide by touch in mobile views.

**Comment by nolimits4web** [comment]
Would be good to see live example with the issue
