### ISSUE TITLE
iPad 1 & iPhone < 6  crash by the use of  the operator ( ** ) in the library

### ISSUE THREAD

**Issue by HectorLS** [nolimits4web/swiper#2684]
### "swiper": "^4.3.3",

Hello, i have found a weird issue about the use of the [Exponentiation (**)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Exponentiation)
 crash on iPad 1 & iPhone < 6  in Safari

```shell
SyntaxError: Unexpected token '*'
```

```javascript
// dist/ swiper.esm.js or // swiper.esm.bundle.js
if (params.resistance) data$$1.currentTranslate = (swiper.minTranslate() - 1) + ((-swiper.minTranslate() + data$$1.startTranslate + diff) ** resistanceRatio);
```
If i replaced those by Math.pow the erros is fixed and jump to the next.

<img width="1609" alt="screen shot 2018-06-22 at 11 11 43" src="https://user-images.githubusercontent.com/6190477/41768878-c9d638be-760d-11e8-9721-0ebc7c2f3e56.png">
<img width="878" alt="screen shot 2018-06-22 at 11 11 20" src="https://user-images.githubusercontent.com/6190477/41768879-c9f2590e-760d-11e8-8a0e-121ccd067356.png">

**Comment by nolimits4web** [comment]
You need to use transpiled version of Swiper or if use module version then you need to transpile it by yourself with Babel or Buble

**Comment by weituotian** [comment]
@nolimits4web where can i find the  transpiled version of Swiper?
