### ISSUE TITLE
Swiper text-content, on 'slide' or 'fade' transitions, moves up/down ~1px at begin/end of transition

### ISSUE THREAD

**Issue by hal869** [nolimits4web/swiper#2692]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: swiper@4.3.3 (on linux/64)
* Platform/Target and Browser Versions: Desktop Browsers

In text-content Swipers, whith effect == either 'slide' or 'fade', immediately at start of transition, the content appears to move up ~ 1px.

Then the transition occurs.

At the end, after the transition's completed, the content 'settles' back down the same ~1px.

So the current visual effect is a slight text 'jerking', up & down.

I can't (yet) find the source of that up/down motion ...

**Comment by nolimits4web** [comment]
I believe it is a browser rendering bug

**Comment by hal869** [comment]
@nolimits4web 

It appears that you may be correct!  It happens in Firefox 62.0b2/DevEd, but _not_ in Chrome/stable.

Is there a workaround that you're perhaps aware of?  Or some greater detail as to what's occurring -- I can then take it up with the FF crowd.
