### ISSUE TITLE
Getting CodePen working with Swiper?

### ISSUE THREAD

**Issue by hal869** [nolimits4web/swiper#2693]
> * Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

Just trying to get Swiper working on CodePen.

IIUC, this

https://codepen.io/hal924/pen/PaKYrZ

should be working.  Apparently, I don't as it's non-responsive.

What've I missed to get Swiper live on the codepen?

**Comment by nolimits4web** [comment]
You didn’t include required scripts and styles. Closing as not Swiper issue
