### ISSUE TITLE
How to achieve tinder like swiping?

### ISSUE THREAD

**Issue by exebook** [nolimits4web/swiper#2696]
I.e. swipe-left or swipe-right both send you to the same next slide, and you cannot go back?
I believe it could be achieved with `renderExternal` and `virtual`, but it is just an assumption, I annot find any documentation regarding those features.

This:
   http://idangero.us/swiper/api/#virtual

only prefils `virtual.slides`, i.e. it does not even look virtual like this.

**Comment by exebook** [comment]
I am also trying `loop: true`, cannot figure, it does not swipe forward only backwards for some reason.

**Comment by nolimits4web** [comment]
It is not supported
