### ISSUE TITLE
How I can prevent background click of swiper buttons.

### ISSUE THREAD

**Issue by vinayistar** [nolimits4web/swiper#2698]
How to set event.stopPropagation() on navigation buttons. Im having click event on image and arrows on that image. When I click on navigation arrow button, image on click event is also called.
Please help me.

**Comment by shashank1010** [comment]
From what I understand, you are trying to click on a an image which is a child of the active swiper slide. The next slide event is fired along with the click event of the image.

Try experimenting with 'preventClicks', and 'preventClicksPropagation' options. I believe that should give you desired results.

**Comment by vinayistar** [comment]
I have tried all above events.But its still a problem
