### ISSUE TITLE
Loop not working when used with slidesPerView / slidesPerColumn. 

### ISSUE THREAD

**Issue by zaynzafar** [nolimits4web/swiper#2700]
This is a:
* [x] bug

* Swiper Version: 
4.3.3

* Platform/Target and Browser Versions: 
macOS (but problem persists on all browsers/platforms) 

### What you did
I tried two things:

1) Enabling loop: true
2) Binding an event to a button to progress to the next / previous slide using .slideNext() and .slidePrev().

```
  var swiper = new Swiper('.swiper-container', {
    autoplay: {
      delay: 6000
    },
    loop: true,
    allowTouchMove: false,
    slidesPerView: 1,
    slidesPerColumn: 3,
    spaceBetween: 0,
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
    }
  });
```

### Expected Behavior
Slide is meant to loop through

### Actual Behavior
Layout breaks if I used loop: true

**Comment by nolimits4web** [comment]
`loop` not supported with `slidesPerColumn`
