### ISSUE TITLE
Lazyloading background image with different image sizes per device.

### ISSUE THREAD

**Issue by benedikt-buchert** [nolimits4web/swiper#2705]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: v4.3.3
* Platform/Target and Browser Versions: All Browsers
* Live Link or JSFiddle/Codepen or website with isssue: https://uhle-webpelze.com/

### What you did
I'm using a background image swiper that I want to be lazy loading for performance reasons and also for image art direction I might want to use a different cropping or image. 

### Feature
This would be a great feature to support.
Not exactly how this would be implemented in the best way.

```
data-background="@media (min-width: 1440px) {
background-image: url("/img/cortina-pfeffer.jpg");
}
@media (..."
```

**Comment by benedikt-d** [comment]
I ended up using the `<img>` tag with `object-fit: cover;`

**Comment by benedikt-d** [comment]
@gearsandcode but that doesn’t make the image responsive meaning it doesn’t load a different size image per device with.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
