### ISSUE TITLE
nextjs ssr

### ISSUE THREAD

**Issue by Brightchild** [nolimits4web/swiper#2719]
Hi,
Does anyone try Swiper with Nextjs or in a Server Side Rendering (SSR) context?
Thanks for your experience feedbacks!
Best

**Comment by BarbarConan** [comment]
Switched to class component from statless and it seems to be fixed for now!

**Comment by orditeck** [comment]
@BarbarConan could you please explain how you fixed this?

**Comment by BarbarConan** [comment]
@orditeck it seems you fixed it, didn't you?

**Comment by orditeck** [comment]
Yes, I did using a React Component with `componentDidMount`
