### ISSUE TITLE
[FEATURE] Controller featured for thumbs gallery

### ISSUE THREAD

**Issue by anvucodespot** [nolimits4web/swiper#2721]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: Latest version
* Platform/Target and Browser Versions: Every
* Live Link or JSFiddle/Codepen or website with isssue: None

### What you did
Like your demo  here http://idangero.us/swiper/demos/300-thumbs-gallery.html

### Expected Behavior
The thumbnails position will start in the left of content (LTR situation), and one more thing, when the slider don't have enough thumbnails to scroll, no need to scroll the thumbnails.

The Slick slider works well in this case, but i want to stick with your product. You can refer here http://kenwheeler.github.io/slick/ in section Slider Syncing. It can work with loop mode, non-loop mode, center mode and non-center mode.

### Actual Behavior
When you initialize a two-ways control, the thumbnails position will start in the center of content. It can't work with loop mode.

**Comment by ofyalcin** [comment]
+1

**Comment by ofyalcin** [comment]
Hi, I found a secret demo. It solved my problem. Maybe it might be useful for you. http://idangero.us/swiper/demos/310-thumbs-gallery-loop.html

**Comment by anvucodespot** [comment]
Hi @ofyalcin ,

It is very helpful for me. Thank you so much for this secret demo.
