### ISSUE TITLE
Can see 1px width of the next slide

### ISSUE THREAD

**Issue by jtibbles** [nolimits4web/swiper#2722]
This is a:
* [x] bug

* Swiper Version: 4.3.3
* Platform/Target and Browser Versions: All html5 browsers
* Live Link or JSFiddle/Codepen or website with issue: http://www.walkswithalf.com/

### What you did
Added slideshows on page with arrows (draggable) using the example code provided from Swiper

### Expected Behavior
When finished sliding from one to the next you should just see that one slide

### Actual Behavior
on the right-hand side of the side (once you have swiped a few times) you can see full height, 1px width on the next slide. It looks like an overlap error? Or perhaps the slider image isn't filling 100% the width as it should. 
(Image attached, issue highlighted in red)
![overlap](https://user-images.githubusercontent.com/3278809/42987514-ddc76904-8bf9-11e8-845a-df1810c0bfdc.jpg)

**Comment by nolimits4web** [comment]
I can't see such issue at your link, so assume could be browser/system rendering issue. Try also to play with `roundLengths` parameter
