### ISSUE TITLE
Assign controller after swiper initialization - broken?

### ISSUE THREAD

**Issue by 7iomka** [nolimits4web/swiper#2725]
I forked this demo for illustrate problem:
1) Swiper v3.3.2 (old) - https://codepen.io/7iomka/pen/qyrZep 
2) Swiper (latest version 4.3.3) https://codepen.io/7iomka/pen/bjqpyX

In the old version - all is ok.
In the new version, I've already spent half a day to get my code working (in the example code I simplified the task), but without success.

In my real project, the task is to make a bunch of "1 to many, many to many, many to 1", but first I would understand why a simple example in the demonstration does not work!
Thank you!

**Comment by nolimits4web** [comment]
It works, syntax is a bit different:
```
quoteSwiper1.controller.control = [imageSwiper, quoteSwiper2];
imageSwiper.controller.control = quoteSwiper1;
```
