### ISSUE TITLE
Unexpected slidesOffsetAfter behavior

### ISSUE THREAD

**Issue by ReedBe** [nolimits4web/swiper#2726]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: `4.3.3`
* Platform/Target and Browser Versions: *.

Hello,

As it stands today, I find the behavior of the `slidesOffsetBefore` and `slidesOffsetAfter` parameters a bit odd: it seems like they will add extra space to the wrapper even if the sum of all the slides and their margins is inferior to the width of the main container.

So, for instance, if I have a `.swiper-container` with a width of `1000px` that contains 2 slides that are `200px`-wide and I instantiate Swiper with these parameters:

```
const slider = new Swiper('.swiper-container', {
    freeMode: true,
    setWrapperSize: true,
    spaceBetween: 100,
    slidesPerView: 'auto',
    slidesOffsetAfter: 250,
})
```

... Then the wrapper will still have a width of `1250px` and I will be able to slide it to `-250px`, even though the sum of all the slides and their margin is well under `1000px`.

Is that the intended behavior for Swiper? If so, is there any way to avoid that?

Thanks!

**Comment by sameoldmadness** [comment]
@nolimits4web Bumped into the same issue. 

Probably should be reopened.

**Comment by Gierand** [comment]
I'm having the same issue.
