### ISSUE TITLE
Multiple Instances of Swiper on Same page?

### ISSUE THREAD

**Issue by nadirnasir** [nolimits4web/Swiper#273]
How can I initiate and control multiple instances of swiper slides on the same page?

**Comment by furkankinyas** [comment]
var sliders = [];

    $('.swiper-container').each(function(index, element){
    	$(this).addClass('s'+index);
    	$(this).find('.icon-right-arrow').addClass('r'+index);
    	$(this).find('.icon-left-arrow').addClass('l'+index);
    	var slider = new Swiper('.s'+index, { 
    		slidesPerView: 5,
    		spaceBetween: 12,
    		nextButton: '.r'+index,
    		prevButton: '.l'+index,
    		onProgress: function(e){
    			if(e.isBeginning){
    				$('.l'+index).hide();
    				$('.r'+index).show();
    			} else if(e.isEnd){
    				$('.r'+index).hide();
    				$('.l'+index).show();
    			} else {
    				$('.r'+index).show();
    				$('.l'+index).show();
    			}
    		}
    	});
    	sliders.push(slider);
    });

**Comment by julmot** [comment]
It is necessary to add a unique selector to each dependent element. That means also the prev and next buttons need to have a unique selector. This will solve it:
JS:
```javascript
$(".swiper-container").each(function(index, element){
	var $this = $(this);
	$this.addClass("row-" + index);
	$this.find(".swiper-button-prev").addClass("btn-prev-" + index);
	$this.find(".swiper-button-next").addClass("btn-next-" + index);
	var swiper = new Swiper(".row-" + index, {
		slidesPerView: "auto",
		grabCursor: true,
		simulateTouch: true,
		preventClicks: true,
		keyboardControl: true,
		paginationClickable: true,
		nextButton: ".btn-next-" + index,
		prevButton: ".btn-prev-" + index
	});
});
```
Related HTML:
```html
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide">Slide 1</div>
            <div class="swiper-slide">Slide 2</div>
            <div class="swiper-slide">Slide 3</div>
            <div class="swiper-slide">Slide 4</div>
            <div class="swiper-slide">Slide 5</div>
            <div class="swiper-slide">Slide 6</div>
            <div class="swiper-slide">Slide 7</div>
            <div class="swiper-slide">Slide 8</div>
            <div class="swiper-slide">Slide 9</div>
            <div class="swiper-slide">Slide 10</div>
            <div class="swiper-slide">Slide 11</div>
            <div class="swiper-slide">Slide 12</div>
            <div class="swiper-slide">Slide 13</div>
            <div class="swiper-slide">Slide 14</div>
            <div class="swiper-slide">Slide 15</div>
            <div class="swiper-slide">Slide 16</div>
            <div class="swiper-slide">Slide 17</div>
            <div class="swiper-slide">Slide 18</div>
            <div class="swiper-slide">Slide 19</div>
        </div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>
```

**Comment by esgardilion** [comment]
@julmot Excellent!!

**Comment by Alivezoned** [comment]
Yup excellent

**Comment by nolimits4web** [comment]
Guys, it is not necessary to add extra classes as all these parameters accept HTMLElements as well:
```js
$(".swiper-container").each(function(index, element){
    var $this = $(this);
    $this.swiper({
        // your settings ...
        nextButton: $this.find(".swiper-button-next")[0],
        prevButton: $this.find(".swiper-button-prev")[0]
    });
});
```

**Comment by julmot** [comment]
Can you explain why it will work with `$this.swiper(....`? The documentation says it expects an

> HTMLElement or string

But this is an jQuery object.

**Comment by nolimits4web** [comment]
This syntax is as jQuery plugin (which is built-in in Swiper's jQuery version):
```js
var swiper = $(something).swiper({...});
```
But as i see it is not documented ... for some reason, will add it.

As for 
> HTMLElement or string

Then with usual syntax:
```js
$(".swiper-container").each(function(index, element){
    var $this = $(this);
    var swiper = new Swiper(this, {
        // your settings ...
        nextButton: $this.find(".swiper-button-next")[0],
        prevButton: $this.find(".swiper-button-prev")[0]
    });
});
```

**Comment by julmot** [comment]
@nolimits4web I agree with you, it is an important hint. I was thinking already that this is weird, there exists an jquery version but it's not possible to call it like every jquery plugin...

However, I just tried your variant and it didn't work for me:
![tt](https://cloud.githubusercontent.com/assets/8310677/11339742/36ca975c-91fb-11e5-942d-ecfc1100e009.png)

**Comment by nolimits4web** [comment]
@julmot can't replicate it. Would be good to see live example or JSFiddle with it

**Comment by julmot** [comment]
I can't replicate it on JSFiddle neither :bowtie: Seems like it has something to do with my environment.
So let's leave it as it is. The main thing is that it will work in the demos.

**Comment by mod667** [comment]
Hello,
I place 2 istances of the swiper in one page, exactly the Images Lazy Loading using this solution:

HTML
```
<div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                 <img data-src="image 1" class="swiper-lazy">
                 <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
            </div>
            <div class="swiper-slide">
                 <img data-src="image 2" class="swiper-lazy">
                 <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
            </div>
      <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-white"></div>
        <!-- Navigation -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>
      </div>
</div>

<div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                 <img data-src="image 1" class="swiper-lazy">
                 <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
            </div>
            <div class="swiper-slide">
                 <img data-src="image 2" class="swiper-lazy">
                 <div class="swiper-lazy-preloader swiper-lazy-preloader-white"></div>
            </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-white"></div>
        <!-- Navigation -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>
      </div>
</div>
```
calling the script:
```
 <!-- Initialize Swiper -->
    <script>
       $(".swiper-container").each(function(index, element){
       var $this = $(this);
       $this.addClass("instance-" + index);
       $this.find(".swiper-button-prev").addClass("btn-prev-" + index);
        $this.find(".swiper-button-next").addClass("btn-next-" + index);
	$this.find(".swiper-pagination").addClass("pagina" + index);
       var swiper = new Swiper(".instance-" + index, {
        nextButton: $this.find(".swiper-button-next")[0],
        prevButton: $this.find(".swiper-button-prev")[0],
	pagination: $this.find(".swiper-pagination")[0],
        paginationClickable: true,
        // Disable preloading of all images
        preloadImages: false,
        // Enable lazy loading
        lazyLoading: true,
    });
    });
</script>
```
I use it jQuery v1.11.1.
The script work well with the Pagination and the Navigation with 2 istances on the same page.
Thank's to all for the infos posted before !

**Comment by furkankinyas** [comment]
when i use this code how is update 'swiper' out each function?
<pre>
$(".swiper-container").each(function(index, element){
    var $this = $(this);
    var swiper = new Swiper(this, {
        // your settings ...
        nextButton: $this.find(".swiper-button-next")[0],
        prevButton: $this.find(".swiper-button-prev")[0]
    });
});
</pre>

**Comment by julmot** [comment]
I don't understand your question.

**Comment by furkankinyas** [comment]
i can use 'swiper.update' but i take error because i use each function

**Comment by julmot** [comment]
You need to store each instance in an object with a unique identifier.  Then you can call update on a specific instance.

**Comment by furkankinyas** [comment]
can u give an example?

**Comment by julmot** [comment]
@furkankinyas 
```javascript
var swiperInstances = {};
$(".swiper-container").each(function(index, element){
	var $this = $(this);
	$this.addClass("instance-" + index);
	$this.find(".swiper-button-prev").addClass("btn-prev-" + index);
	$this.find(".swiper-button-next").addClass("btn-next-" + index);
	swiperInstances[index] = new Swiper(".instance-" + index, {
		// your settings ...
		nextButton: ".btn-next-" + index,
		prevButton: ".btn-prev-" + index
	});
});

// Now you can call the update on a specific instance in the "swiperInstances" object
// e.g.
swiperInstances[3].update();
```

**Comment by nolimits4web** [comment]
Or you can access it via `swiper` property of HTMLElement later. For example if you need to update every instance:
```
$(".swiper-container").each(function(index, element){
    var swiper = this.swiper;
    swiper.update();
});

**Comment by furkankinyas** [comment]
thank u all support ;)

**Comment by MayhemUK** [comment]
I wanted to post my comment :) its f.... ridiculous that slider with so many functions didn't take care of so simple thing. Now days pages can have 3/4/5 sliders. Reading all this make me just switch the plugin instead of using one that CREATES PROBLEMS AND MAKE ME LOOSE TIME RESOLVING THEM till now it was my #1 new slider plugin - after discovering this - last place

**Comment by nolimits4web** [comment]
@MayhemUK seriously? Sorry, but if you don't know the basics and can't understand anything from examples, it is not the plugin fault. Remember the simple rule - "don't like it - don't use it"
