### ISSUE TITLE
Performance Issues using observer option

### ISSUE THREAD

**Issue by rayvincent-bsd** [nolimits4web/swiper#2730]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.3.
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with isssue:
  * https://codepen.io/rayvincent-bsd/pen/mjqOVZ
    * With codepen editor
  * https://s.codepen.io/rayvincent-bsd/debug/mjqOVZ/wQrPoNZOqgNM
    * Without codepen editor overhead

### What you did
Enabled `observer` option and added 500 slides dynamically

### Expected Behavior
Upon the next mutation event, the swiper should process the update efficiently without performance issues.

### Actual Behavior
Swiper will execute 'onResize' event handler over 500 times, once for each mutation that occurred in the mutation event.  This is causing drastic performance issues.

With the given codepen link, you can see that the it takes about 15 seconds with the attached Chrome profile. Tested in Chrome v67.0.3396.99 (Mac OSX)

- [codepen.profile.gz](https://github.com/nolimits4web/swiper/files/2238018/codepen.profile.gz)

**Comment by nolimits4web** [comment]
Fixed by #2731
