### ISSUE TITLE
event lazyImageReady triggers early on mobile devices

### ISSUE THREAD

**Issue by razvan-smarandeanu-rm** [nolimits4web/swiper#2732]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.3
* Platform/Target and Browser Versions: chrome and safari on IOS

### What you did
There is an awkward bug in the lazyImageReady event on mobile devices. The event works fine on the google chrome emulator, but not on mobile devices.

I have 5 slides with 300px by 300px images set on data-src and a 1x1 pixel gif set on src:

image1.png

image2.png

image3.png

image4.png

image5.png

I set swiper to loadPrevNextAmount = 1, which means that on page load the event lazyImageReady fires for image1.png and image2.png and the console prints out 300 for image1 and 300 for image2.

After that initial load, i start swiping and lazyImageReady fires for image3.png and the console prints out the witdh 1.

This happens for the rest of slides.

If i set a timeout of 100ms before getting the width of the image everything works fine.

HTML:

<img class=“swiper-lazy” src=“data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==” data-src=“image1.png” />

<img class=“swiper-lazy” src=“data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==” data-src=“image2.png” />

<img class=“swiper-lazy” src=“data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==” data-src=“image3.png” />

<img class=“swiper-lazy” src=“data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==” data-src=“image4.png” />

<img class=“swiper-lazy” src=“data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==” data-src=“image5.png” />

JS:

// initialize content swiper

swiper = new Swiper('.swiper-container', {

slidesPerView: 1,

spaceBetween: 0,

loop: false,

preloadImages: true,

lazy: {

loadPrevNext: true,

loadPrevNextAmount: 1,

},

pagination: {

el: ‘.swiper-pagination’,

dynamicBullets: true,

dynamicMainBullets: 3,

},

});

swiper.on('lazyImageReady', function (slide, image) {

console.log(image.width()); // prints out incorrect width of 1px

setTimeout(function(){

console.log(image.width()); // prints out correct witdh of 300px

}, 100);

});

### Expected Behavior
all images lazy loaded should have correct width/height 

### Actual Behavior
width/height returned is the image src(1px transparent gif)  instead of data-src(the actual image)

**Comment by razvan-smarandeanu-rm** [comment]
I dont know how i missed your comment, but i tried with anything below ~70ms and it doesnt work. At 100ms timeout i get consistent and correct behavior.

**Comment by lilgrassin** [comment]
This issue isn't just limited to mobile, I'm seeing the same thing on desktop Safari. Since the timeout required depends on the download rate (sometimes even 100-200ms wasn't good enough) I've made the following workaround. It's probably not the best performance, but it works:

```
function myLazyHandler(slideEl, imageEl) {
	if (imageEl.complete) {
		// do stuff
	} else {
		setTimeout(function () { myLazyHandler(slideEl, imageEl); }, 100);
	}
}

swiper.on('lazyImageReady', myLazyHandler);
```

**Comment by lilgrassin** [comment]
I've just discovered the above code fails if the image is cached (`imageEl.complete` seems to return `true` before the image is actually loaded).

**Comment by krass1251** [comment]
It was very helpful for me I hope it can help you too: 
 
```javascript
itemSwiper.on('lazyImageReady', function (slide, image) {
    if (image.complete) {
        itemSwiper.update();
    } else {
        image.addEventListener('load', function () {
            itemSwiper.update();
        });
    }
});
```
