### ISSUE TITLE
Whats the difference between slideChangeTransitionEnd & transitionEnd ?

### ISSUE THREAD

**Issue by vin-ni** [nolimits4web/swiper#2733]
I built a simple slider and would like to run a function after each transition. If I swipe back during the transition (so to block the locking into the new position) but both functions still run twice.

I expected `transitionEnd` to run once after animation ended. No matter how often you change the swiping direction.

Thanks a lot!

**Comment by nolimits4web** [comment]
`transitionEnd` can also happen on Slide "reset", while another one only when active slide changed
