### ISSUE TITLE
slideTo bug with loop: true

### ISSUE THREAD

**Issue by dantistus** [nolimits4web/swiper#2734]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.3
* Platform/Target and Browser Versions: Windows 10, Chrome
* Live Link or JSFiddle/Codepen or website with isssue: 

### What you did
I am initializing Swiper with loop: true option. I then want to use API method slideTo to go to certain slides.

### Expected Behavior
Whenever I call slideTo(n), I expect the slider to show me n-th slide, regardless of underlying implementation. Good example of this is bxSlider - it also uses cloned nodes for infinite loop functionality, but bxSlider handles API transitions to n-th slide properly.

### Actual Behavior
When I initialize Swiper with loop: true, the slideTo(0) method shows last slide instead of first. slideTo(1) shows first slide instead of second etc. I believe this error happens because when loop: true option is set, the slider creates clones of first and last slides, and the slideTo method doesn't take that into account.

**Comment by dantistus** [comment]
P. S. I have just checked and this **bug** hasn't been fixed in latest release version 4.3.3, I will edit issue description (I have discovered this **bug** on version 4.2.2)

**Comment by nolimits4web** [comment]
There is .slideToLoop method that does exactly what you need

**Comment by dantistus** [comment]
Thank you for your answer. This is of course still one of the dumbest things that I have encountered in my life. Why stop at 2 methods instead of 1? The possibilities here are truly endless:

- slideToHorizontal / slideToVertical
- slideToFixedHeight / slideToAutoHeight
- slideToFade / slideToCube / slideToFlip
- etc.
