### ISSUE TITLE
Slide loop bug when styling background in stylesheet

### ISSUE THREAD

**Issue by nbsimmo** [nolimits4web/swiper#2735]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2 -> Present
* Platform/Target and Browser Versions: Chrome
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/nbsimmo/pen/ajqWxG

### What you did

Code slider as I normal do using the following options:

        var mySwiper = new Swiper('.swiper-container', {
            // Optional parameters
            direction: 'horizontal',
            loop: true,
            pagination: {
                el: '.swiper-pagination',
                clickable: true
            },
            navigation: {
                nextEl: '.newSwiperButton-next',
                prevEl: '.newSwiperButton-prev',
            },
        });

Due to always integrating with a CMS this issue has never been present as background have been coded on the element rather than in an external stylesheet. Upon styling using an external stylesheet using nth puesdo, it provides me with this issue.

### Expected Behavior
Slides should loop to beginning, displaying as normal, displaying the background image.

### Actual Behavior
Although the swiper does indeed loop, it produces a white background upon going to the last slide and then looping around. To replicate, slide through as normal and then swipe past the last slide.

This isn't present when using inline styling for backgrounds on each slide element (style="background: url()"...) - only when styling via an external stylesheet.

**Comment by nolimits4web** [comment]
Loop mode created duplicated slides, so `nth-child` styling won't work here, use, for example, specific classes on each slides with required bg
