### ISSUE TITLE
Can't get value from input in the last slide, if "loop: true"

### ISSUE THREAD

**Issue by ahmadzakiy** [nolimits4web/swiper#2736]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.2
* Platform/Target and Browser Versions: Chrome.
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/ahmadzakiy/pen/mjxEbY

### Problem
I make 5 slides and for the last slide I put the form (input email and button), problem comes when I'll try to get the input's value, Events works but the value is empty, if I put the form in slide 1 or 2 or 3 or in config "loop" is set false, I can get the value.

Thank you.

**Comment by ahmadzakiy** [comment]
[UPDATE]

After inspecting the DOM, I think the problem where I can't get the value from the input is because, when you set "loop: true" swiperJS will duplicate the first and the last slide, so there will be 2 first slides and 2 last slides, render at the DOM and if you put "Input" at those slides and try to select "Input" with the selector, it will never get the value.

My solution, for now, is to put the "input" in the second slides at the code, and then set back two times so that will be the last side in the view. what I custom at swipper.js are: 

_set back slide two times: second slides will be last slides_
**line 4993:** `var $bullet = bullets.eq(current - 2);`

_set clickable pagination_  
**line 5133:** _swiper.slideTo(index + 2);_

**Comment by nolimits4web** [comment]
Or do it right https://codepen.io/anon/pen/PByxQQ
