### ISSUE TITLE
Do not go to the last slide when displaying multiple items and not looping

### ISSUE THREAD

**Issue by Phan-Ha** [nolimits4web/swiper#2737]
Hi,
I have a problem when init slide with show multiple and not use loop ! 
When I click the button next and click with mouse (slideToClickedSlide). Everything stays normal until only the last 3 slides are not clickable (slidesPerView: 4).  And I use mouse click on three last slides (slideToClickedSlide) will not work

HTML (jade) code : 
.swiper-container
  .swiper-wrapper
   .swiper-slide Slide 1
   .swiper-slide Slide 2
   .swiper-slide Slide 3
   .swiper-slide Slide 4
   .swiper-slide Slide 5
   .swiper-slide ..... n slide
 .swiper-button-next
 .swiper-button-prev

JS code :

var mySwiper = new Swiper('.swiper-container', {
   slidesPerView: 4,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    allowTouchMove: false,
    slideToClickedSlide: true,
});

**Comment by nolimits4web** [comment]
Number of slides must be even to `slidesPerView`
