### ISSUE TITLE
A big problem faced! Loop true with single item

### ISSUE THREAD

**Issue by sandeepdesigns** [nolimits4web/swiper#2738]
I faced a big problem i have only single item in my slider (But it could be more dynamically), I found its cloned to 3 items.. same item repeated 3 times.. Kindly resolve it.
Here is my code in filddle:
https://jsfiddle.net/sandeeptripathi/8pqagwf5/12/

**Comment by niklashultstrom** [comment]
That should be the expected behaviour. If you don't want it to loop when there is only one slide, you can do something like this: { loop: !!$('.swiper-slide').length }

**Comment by nolimits4web** [comment]
It is by design
