### ISSUE TITLE
Unexpected transition behavior when the loop starts over

### ISSUE THREAD

**Issue by Jentoz** [nolimits4web/swiper#2739]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: macOS, CHROME
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/Jentoz/nczdeafj/8/

### What you did
I created slider with loop. Added opacity 0.1 for all slides, opacity 1 for active slide and css transition-duration to make changes look smooth when changing the slides. 

### Expected Behavior
I expected the transition-duration to be equal on every slide change.

### Actual Behavior
Unfortunately, transition-duration didnt work as expected on the first slide after the slider was looped through once.

You can check the jsfiddle, click "next" button 4 times, on the fourth slidechange you will see that opacity is changing instantly, without any transition.

How can I fix this problem?

**Comment by nolimits4web** [comment]
You also need to consider `swiper-slide-duplicate-active` class
https://jsfiddle.net/nczdeafj/10/
