### ISSUE TITLE
Swiper slider loses swiper-slider-active class on first slide

### ISSUE THREAD

**Issue by eugeniodsjgfo** [nolimits4web/swiper#2742]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.1.7
* Platform/Target and Browser Versions: Any browser

### What you did
I have a Swiper Slider that use "loop" property. The matter is, if my swiper completes a full lap, after last slide (third slide) goes the first one, but it doesn't get swiper-slider-active class, so I get other troubles about CSS.

Note: It doesn't happen if I stay in second slide and I go to previous slide.

Can you help me?

Here is my swiper:

```
swiperSlide.end()
    .find("[data-caption-animate]")
    .addClass("not-animated")
    .end()
    .swiper({
      autoplay: s.attr('data-autoplay') !== "false" && !isNoviBuilder ? s.attr('data-autoplay')  : null,
      direction: s.attr('data-direction') ? s.attr('data-direction') : "horizontal",
      effect: s.attr('data-slide-effect') ? s.attr('data-slide-effect') : "slide",
      speed: s.attr('data-slide-speed') ? s.attr('data-slide-speed') : 600,
      keyboardControl: s.attr('data-keyboard') === "true",
      mousewheelControl: s.attr('data-mousewheel') === "true",
      mousewheelReleaseOnEdges: s.attr('data-mousewheel-release') === "true",
      nextButton: next.length ? next.get(0) : null,
      prevButton: prev.length ? prev.get(0) : null,
      pagination: pag.length ? pag.get(0) : null,
      paginationClickable: pag.length ? pag.attr("data-clickable") !== "false" : false,
      paginationBulletRender: pag.length ? pag.attr("data-index-bullet") === "true" ? function (index, className) {
        return '<span class="' + className + '">' + (index + 1) + '</span>';
      } : null : null,
      scrollbar: bar.length ? bar.get(0) : null,
      scrollbarDraggable: bar.length ? bar.attr("data-draggable") !== "false" : true,
      scrollbarHide: bar.length ? bar.attr("data-draggable") === "false" : false,
      loop: s.attr("data-loop") && !isNoviBuilder ? s.attr('data-loop') !== "false" : false,
      simulateTouch: s.attr('data-simulate-touch') && !isNoviBuilder ? s.attr('data-simulate-touch') === "true" : false,
      autoplayDisableOnInteraction: true,
      onTransitionStart: function (swiper) {
        toggleSwiperInnerVideos(swiper);
      },
      onTransitionEnd: function (swiper) {
          toggleSwiperCaptionAnimation(swiper);
      },
      onInit: function (swiper) {
        toggleSwiperInnerVideos(swiper);
        toggleSwiperCaptionAnimation(swiper);

        var swiperParalax = s.find(".swiper-parallax");

        for (var k = 0; k < swiperParalax.length; k++) {
          var $this = $(swiperParalax[k]),
            speed;

          if (parallax && !isIEBrows && !isMobile) {
            if (speed = $this.attr("data-speed")) {
              makeParallax($this, speed, s, false);
            }
          }
        }
        $(window).on('resize', function () {
          swiper.update(true);
        })
      }

```

On load:
![image](https://user-images.githubusercontent.com/42176375/43777511-4e89b860-9a53-11e8-80f5-5a74c94b8abf.png)

On second slide active: 
![image](https://user-images.githubusercontent.com/42176375/43777529-5d3fdba0-9a53-11e8-8fc9-9cfefab82b03.png)

On third slide active: 
![image](https://user-images.githubusercontent.com/42176375/43777542-6a71cc52-9a53-11e8-88af-85703b803fd3.png)

On first one after third slide (Third slide is the last one, so I'm going to next item): 
![image](https://user-images.githubusercontent.com/42176375/43777563-79f5adec-9a53-11e8-96bb-c1f8ccf84e64.png)

On first one after second slide (Now, I'm going to previous item): 
![image](https://user-images.githubusercontent.com/42176375/43777577-80c472c0-9a53-11e8-9059-2f51454665ce.png)

Thank you so much.

**Comment by nolimits4web** [comment]
Swiper v3 is not maintained anymore. Upgrade to v4 and if this issue is still there then open new one
