### ISSUE TITLE
how import swipere.css 

### ISSUE THREAD

**Issue by zeroone2005** [nolimits4web/swiper#2745]
1. i npm install swiper
`npm install swiper`

2. webpack.config.js modules 
`{
            test    : /\.js$/,
            exclude : /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
            use     : {
                loader: "babel-loader?presets[]=es2015"
            }
        }`
3. entry js file
`
import Swiper from 'swiper';
    var mySwiper = new Swiper('.menu-left', {
        freeMode       : true,
        slidesPerView  : 'auto',
        freeModeSticky : true,
    });
`

swiper.js loaded, but swiper.css how  import?  import form node_modules in entry js file?
 `import '../node_moudes/swiper/dis/css/swiper.css`

**Comment by andreolaya** [comment]
If you are using webpack, you can import directly like this:

    import Swiper from 'swiper'    
    import 'swiper/dist/css/swiper.css'
