### ISSUE TITLE
Missing slides with irregular slidesPerView (looped and centered)

### ISSUE THREAD

**Issue by Kwapi** [nolimits4web/swiper#2749]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.35.
* Platform/Target and Browser Versions: macOs Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/SpuriouslyAwake/pen/qyGXXG

### What you did
I set the slider to `centeredSlides: true`, `loop:true` and `slidesPerView:1.5`

When setting up swiper to show one slide in full and with the bits of the prev/next slide on each side, swiping left or right often results in a missing slide on either side. The codepen shows the behaviour.
https://codepen.io/SpuriouslyAwake/pen/qyGXXG

### Expected Behavior
Continuous loop with prev/next slide on each side of the current centered slide

### Actual Behavior
Missing slides resulting in white background

**Comment by crazyleega** [comment]
I have the same issue too when use swpier version 3.4.0, but add 'loopedSlides' solve this problem，hope this will help you.
