### ISSUE TITLE
Second Swiper initiates 2 instances of itself to the variable

### ISSUE THREAD

**Issue by vin-ni** [nolimits4web/swiper#2750]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 4.3.3
* Platform/Target and Browser Versions: macOS Chrome

### What you did
I'm initiating a second swiper like that:

```javascript
  var swiperTwo = new Swiper('.swiper-container-kieztour', {
    direction: 'vertical',
    slidesPerView: 'auto',
    init: false,
    wrapperClass: 'swiper-wrapper-kieztour',
    slideClass: 'swiper-slide-kieztour',
    slideActiveClass: 'swiper-slide-kieztour-active',
    centeredSlides: true,
    // slidesOffsetAfter: 120,
    // slidesOffsetBefore: -140,
    // spaceBetween: 30,
  });
```

### Expected Behavior
`swiperTwo` would hold one instance of the vertical slider.

### Actual Behavior
Actually `swiperTwo` weirdly holds two instances: `[t, t]`. They are exactly identical from the data inside, but only the seconds instance `[1]` is linked to the slider visible. (the first one is somehow off and can't be inited)

I'm initiating both sliders at the same time. Without waiting for the first one to be finished. Could it have something to do with that?

**Comment by nolimits4web** [comment]
It means that you have 2 `.swiper-container-kieztour` elements on the page

**Comment by vin-ni** [comment]
Ouch!
Sorry, for this mistake, you're right.
