### ISSUE TITLE
Virtual slides ignore initialSlide in the beginning

### ISSUE THREAD

**Issue by websirnik** [nolimits4web/swiper#2755]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: CHROME
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/bqv2137n/11/

### What you did
When using `initialSlide` setting together with `virtual`, there is extra computing happening. Despite the value of `initialSlide`, Swiper currently always calls `renderSlide` with `0`&`1` indexes before rendering `initialSlide` slide. This is costly, when my `createSlide()` function is heavy. 
```
var mySwiper = new Swiper('.swiper-container', {
    initialSlide: 4,
    virtual: {
        slides: ['Slide 1', 'Slide 2', 'Slide 3', 'Slide 4', 'Slide 5', 'Slide 6'],
        renderSlide: function(slide, index){
            console.log(slide);
            return createSlide(slide);
        }
    }
});
```

### Expected Behavior
Console Output: 
```
Slide 4
Slide 5
Slide 6
```

### Actual Behavior
Console Output: 
```
Slide 0
Slide 1
Slide 4
Slide 5
Slide 6
```

**Comment by nolimits4web** [comment]
Fixed by #2756
