### ISSUE TITLE
 lazy pre loading for images only works with an integer as 'slidesPerView'

### ISSUE THREAD

**Issue by rkrz** [nolimits4web/swiper#2757]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: all
* Live Link or JSFiddle/Codepen or website with isssue: http://www.plnkr.co/edit/twdgGAkupDrZkaKM7QNr

### What you did
I'm displaying 1.2 (one slide is completely shown, the next slide on the right slide only partially) lazy loaded images, but I want the next/prev images to be loaded before they are shown in the viewport.

```JavaScript
    var swiper = new Swiper('.swiper-container', {
      // Enable lazy loading
      lazy: {
        loadPrevNext: true
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      },
      // does not preload images, if this value includes a comma
      // with e.g. 2 it works
      slidesPerView: 1.2
    });
```

If you change the value of slidesPerView to 2 everything works as expected.

### Expected Behavior
When the first 1.2 images are shown, the 3rd image should already be loaded.

### Actual Behavior
When the first 1.2 images are shown and is is swiped to image 2 the 3rd image just begins to load.

Best regards,
Reinhard

**Comment by AN602** [comment]
+1 I´ve got the same issue.

**Comment by Guy-Incognito** [comment]
same here

**Comment by rkrz** [comment]
Has somebody found any possible solution so far? Or can you direct me where there might be the problem, so I can fix that myself?

**Comment by lilgrassin** [comment]
Same issue here, I need to use `slidesPerView: 'auto'` because I have variable width slides, but lazy loading only loads the first 2 slides and then 1 slide every time you swipe forwards. I've tried using `watchSlidesProgress: true`, `watchSlidesVisibility: true`, `observer: true`, `observeSlideChildren: true` and `swiper.update()` but the issue persists.
