### ISSUE TITLE
iPad mini fade effect problem

### ISSUE THREAD

**Issue by kierok** [nolimits4web/swiper#2759]
Hello. Nice plugin i not far ago discovered and already implemented it to one of my sites, but i got really weird issue on ipad mini. When i use 'fade' effect for slide change, page can not be loaded and breaks in safari. delete fade effect string in js - and everything loads and works as expected. 
[x] bug

Swiper version : 4.3.5
Platform/Target and Browser Versions: iPad mini ios 9.3.5 safari 9.0
Live link: http://avon.nv-web.studio/katalog-12-2018/

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.
var catalogFull = new Swiper('.catalog-fullimg', {
		loop: false,
		speed: 700,
		autoplay: false,
		slidesPerView: 1,
		// Disable preloading of all images
		preloadImages: false,
		// Enable lazy loading
		lazy: true,
		effect: 'fade',
		fadeEffect: {
			crossFade: true
		}
         });
### Expected Behavior
Everything is okay on non-ios devices. fade effect is working nice. 

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
on ipad it causes not to load page with break message.

**Comment by nolimits4web** [comment]
I guess some performance issue. Your website works slow even on my desktop mac book, try to use some oprimization technics including delivering optimized-size images
