### ISSUE TITLE
Problem with dynamic scaling

### ISSUE THREAD

**Issue by JanNovakFRI** [nolimits4web/swiper#2760]
Hello, I would like to report a bug. 

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: Everywhere
* [https://codepen.io/jannnovak/pen/eLNqYx](https://codepen.io/jannnovak/pen/eLNqYx)

### What you did
I have a situation where I have to for some reason dynamically scale some parts of page. Parts also include one or more swiper components, which is causing me some troubles. The problem is if transform: scale(x), where x != 1, is applied on those parts I can no longer scroll to the end of swiper. I have created a simple [fiddle](https://codepen.io/jannnovak/pen/eLNqYx) where problem is simulated. To see a problem resize a browser and try to scroll to the 10th slide. I did try with update function but does not help. Is there a way I could fix?

### Expected Behavior
To be able to scroll to the end of swiper.

### Actual Behavior
Can't scroll to end, scroll is resisting!

**Comment by nolimits4web** [comment]
Issue because getting slide size with `getBoundingClientRect` returns size considering transform, so it doesn't work in this case. I pushed some fix so the `roundLengths` option need to be set to use other calc and transform won't be considered
