### ISSUE TITLE
Scrollbar default element

### ISSUE THREAD

**Issue by svitch** [nolimits4web/swiper#2762]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

There is a huge issue when you have multiple swiper elements on page, you have to set individual scrollbar elements for each swiper instance like:
```
var mySwiper = new Swiper('.swiper-container', {
  scrollbar: {
    el: '.swiper-scrollbar',
    ...
  },
});
```
It's definitely not the best solution.
Can you please change it's default value to the child of main swiper instance?
So when you just enable the scrollbar, it's "el" is set to
```
<div class="swiper-container">
     ...
    <div class="swiper-scrollbar"></div>
</div>
```
and initialize it like this:
```
var mySwiper = new Swiper('.swiper-container', {
  scrollbar: {
    enabled: true,
    ...
  },
});
```

**Comment by nolimits4web** [comment]
It is already looking for a child element if there are more than one such elements
