### ISSUE TITLE
IE 11 not adding slide classes

### ISSUE THREAD

**Issue by anteksiler** [nolimits4web/swiper#2763]
Hi there,

We are using 2 sliders in sync in looped mode here: https://www.verweilzeit.at/

It works without any issues except IE11. In IE11, no slide classes are added.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: IE11
* Live Link or JSFiddle/Codepen or website with isssue: https://www.verweilzeit.at/

**Comment by anteksiler** [comment]
Any update on this?

**Comment by nolimits4web** [comment]
Don't have any chances to test it in IE 11. Do you see any errors in console?

**Comment by thamas** [comment]
The problem can be that IE11 does not support Array.from what is used by Swiper.
This polyfill resolved the issue for me: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill

**Comment by nolimits4web** [comment]
Closing as since v5 IE is not supported anymore
