### ISSUE TITLE
Non-looped thumbs gallery, looped swiper / slider

### ISSUE THREAD

**Issue by gitsilvan** [nolimits4web/swiper#2764]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: Any

### What you did
As many others I wanted to have a [two-way-controlled main and thumbnail slider](https://idangero.us/swiper/demos/300-thumbs-gallery.html). In contrast to the demo, it makes sense to have the main slider looped (so you don't end up in a dead end), but the thumbnails not (as they only serve as  navigation).

To achieve this, you can write your own event handlers and don't use the "official" controller declaration. The only drawback is the missing sync of touch movements between the two sliders.

In the linked demo you would add

`on: { slideChange: function() { if (galleryThumbs) { galleryThumbs.slideTo(this.realIndex); }; } }`

to your galleryTop and

`on: { slideChange: function() { if (galleryTop) { galleryTop.slideTo(this.realIndex + 1); }; } }`

to your galleryThumbs options.

As this functionality was wished for several times in the issues, maybe this could be added to the demos?

### Expected Behavior
Two-way control both sliders with the main slider being looped. Find this in demos.

### Actual Behavior
Not to be found in the demos.

**Comment by ofyalcin** [comment]
I was having problems with the same topic and today I found a secret demo. You can check: http://idangero.us/swiper/demos/310-thumbs-gallery-loop.html
