### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by smurfiez** [nolimits4web/Swiper#277]
Is there a way to use responsive layout and keep the aspect ratio?  I have a page that looks great when in portrait mode but looks weird in landscape mode.  

Also wondering how to do a  slidesPerView: 'auto' while in responsive mode.

Your help is very greatly appreciated and thanks for such an excellent slider!

**Comment by rulatir** [comment]
window.resize()?

Swiper should encapsulate this.
