### ISSUE TITLE
Short delay before slide change

### ISSUE THREAD

**Issue by gitsilvan** [nolimits4web/swiper#2770]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: Chrome on macOS

### What you did
Using Swiper with `effect: 'fade',
      fadeEffect: {
        crossFade: true
      }` and `loop: true`.

### Expected Behavior
Normal / fast sliding behavior.

### Actual Behavior
When first clicking through the slides, there is a small, but noticeable delay before the slide actually changes. When going through the slides for the second time, everything is as fast expected.

**Comment by gitsilvan** [comment]
I just noticed that this is has nothing to do with the lazy loading. It also occurs when not using it.

**Comment by nolimits4web** [comment]
I guess it can be rendering/caching browser issue, nothing to do with Swiper
