### ISSUE TITLE
Duplicated ID attribute on cloned slides while `loop: true`

### ISSUE THREAD

**Issue by icunioli** [nolimits4web/swiper#2771]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.6
* Platform/Target and Browser Versions: macOS, Windows, iOS, Android
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/zJKWrG

### What you did

1. Created a set of slides with their own ID attribute
2. Initialized Swiper with the `loop: true` option

### Expected Behavior
The duplicated slides will not have the same ID attribute as the original slide.

### Actual Behavior
The duplicated slides has the same ID attribute as the original slide, which by W3C specs shouldn't be done:

> ...The value must be unique amongst all the IDs in the element's home subtree...
> https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute

**Comment by nolimits4web** [comment]
This is how loop mode works it duplicates slides

**Comment by icunioli** [comment]
But it shouldn't duplicate the ID attribute on those duplicated slides, as I've said, per W3C spec.
