### ISSUE TITLE
"preventInteractionOnTransition = false" not working with loop

### ISSUE THREAD

**Issue by gitsilvan** [nolimits4web/swiper#2772]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: Chrome on macOS

### What you did
Initialized a looped slider with `preventInteractionOnTransition = false`.

### Expected Behavior
Clicking on the navigation while the slide changes (for example clicking the "next" button twice) should work and change the slide according to the clicks.

### Actual Behavior
Clicking has no effect during the slide transition and only works again after the transition has finished.

**Comment by gitsilvan** [comment]
This is still a problem. It can be observed in the [demos](http://idangero.us/swiper/demos/): the non-looped demos change slides as soon and often you click the next or previous button—the looped demo only responds again when the last slide transition has finished.

**Comment by nolimits4web** [comment]
This is by design in loop mode
