### ISSUE TITLE
Looped slides with partial slides per view not working

### ISSUE THREAD

**Issue by hassanasad** [nolimits4web/swiper#2773]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: Chrome 68
* Live Link or JSFiddle/Codepen or website with issue: https://plnkr.co/edit/H9VIYuX9CrpQnP6OIJDk?p=preview

### What you did
I am trying to loop slides that are partial, for instance 1.5 slidesPerView - The left navigation works fine but the right doesn't after few clicks.

### Expected Behavior
Left and right navigation should work correctly. I want a slide peaking from the right side. (As it seems when using left navigation arrow)

### Actual Behavior
Right navigation stops working even though loop is set to true.

**Comment by nolimits4web** [comment]
According to your example set `loopedSlides: 2`

**Comment by hassanasad** [comment]
I have tried, it doesn't work as intended still. You can try it in the Plunker example. When clicking Left navigation button it skips slides.
