### ISSUE TITLE
box-shadow always gets larger and larger on effect 'fade'

### ISSUE THREAD

**Issue by SilencerWeb** [nolimits4web/swiper#2776]
This is a bug.

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: macOS
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/SilencerWeb/pen/XPpdvO

### Expected Behavior
`box-shadow` should be always the same and it should not get larger on every slide

### Actual Behavior
`box-shadow` gets larger and larger on every slide

**Comment by kukac7** [comment]
@SilencerWeb yes, because all elements are rendered together for the fade effect.

**Comment by SilencerWeb** [comment]
@kukac7 any hack to fix this?

**Comment by kukac7** [comment]
@SilencerWeb are you just giving the first slider elements shadows?

**Comment by SilencerWeb** [comment]
but it doesn't work if elements have different sizes

**Comment by nolimits4web** [comment]
Or
```
fadeEffect: {
    crossFade: true
},
```

**Comment by SilencerWeb** [comment]
@kukac7, @nolimits4web yup, this works :)
