### ISSUE TITLE
We can use swpier 2. X in winform's WebBrowser to slide, but we can't use swiper 4. X to slide. Is there a compatibility problem?

### ISSUE THREAD

**Issue by zhaozhenzzz** [nolimits4web/swiper#2778]
We can use swpier 2. X in winform's WebBrowser to slide, but we can't use swiper 4. X to slide. Is there a compatibility problem?

**Comment by zhaozhenzzz** [comment]
We can use swiper 4. x to slide on IE11, not on winform's webbrowser, and swiper 2. x can slide on both.

**Comment by nolimits4web** [comment]
Make sure you use this script https://github.com/nolimits4web/swiper/blob/master/dist/js/swiper.js and IE 11 is not officially supported by 4.x so it may not work correct
