### ISSUE TITLE
lazy pre loading for images in loop mode

### ISSUE THREAD

**Issue by larslehners** [nolimits4web/swiper#2780]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/minute/pen/RYVrpL

### What you did
Testsetup: A swiper with 5 slides and lazy loading

If you navigate directly from slide 1 to slide 5 by pagination everthing works as aspected. But if you use the navigation (or touchMove) to go to slide 5 backwards, the preloading is not working correctly.

### Expected Behavior
Testsetup: A swiper with 5 slides and lazy loading
* Initial loading: Slide 5, Slide 1, Slide 2 are loaded
* Slide to the left to Slide 5: Image of Slide 4 is loaded

### Actual Behavior
* Initial loading: Slide 5, Slide 1, Slide 2 are loaded
* Slide to the left to Slide 5: Slide 4 is **not** loaded.

I think the problem is a wrong index caused by the duplicated slides in loop mode.

**Comment by sixty-nine** [comment]
We have this exact same problem.

**Comment by JeroenMetsemakers** [comment]
We also encounter this proble. @sixty-nine Did you fount a solution or workaround?

**Comment by vineetit1991** [comment]
We are also facing the same problem. Do we have any workaround for this ?

**Comment by sixty-nine** [comment]
@JeroenMetsemakers unfortunately not. We have tried forcing the load of the images with `swiper.lazy.load()` or `swiper.lazy.loadInSlide(index)` without much success. 

It's always the same image that causes problems and it look definitely related to the count of duplicated images in loop mode.

**Comment by JeroenMetsemakers** [comment]
We have added the following function to set the image src of the last 3 items.

```javascript
    on: {
      slideChange: function() {
        if (this.activeIndex === 0) {
          this.lazy.loadInSlide(this.slides.length - 3);
        }
      },
    }
```

**Comment by vineet-tellytale** [comment]
How about this ?
`
swiper.slides[swiper.slides.length - 1].querySelector("img").classList.remove("swiper-lazy-loading");

swiper.lazy.loadInSlide(this.el.swiper.slides.length - 1)
`

**Comment by Ralphy001** [comment]
I have the same issue: seems to be unsolved yet. I could also fix the issue by 
`  on: {
      slideChange: function() {
        if (this.activeIndex === 0) {
          this.lazy.loadInSlide(this.slides.length - 3);
        }
      },
    }`
