### ISSUE TITLE
Problem to apply vertical swiper in page

### ISSUE THREAD

**Issue by mehulRojasara** [nolimits4web/swiper#2782]
* Swiper Version: Swiper 4.3.5.
* Platform/Target and Browser Versions: Windos chrome 68.0.3440.106
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/Mehul_Rojasara/full/VGWNdm/

### What you did
once the page is loaded and then refresh the page will cause this issue, there is second slide visible in screen
*OR*
when open inspect element window and close it without change this problem occurs.
![swiper-issue-1](https://user-images.githubusercontent.com/29998538/45076062-aae73780-b106-11e8-909e-6f2cf9d50bad.jpg)

### Expected Behavior
want to visible only one slide on screen and also want to solve height calculation problem on window resize with inspect element window,
*I made some mistakes in code or css but i'm not able to find out, can you please help to out of this? *

**Comment by mehulRojasara** [comment]
![swiper-issue-1](https://user-images.githubusercontent.com/29998538/45080393-74171e80-b112-11e8-8e8e-de5411de5d98.jpg)

**Comment by nolimits4web** [comment]
I can't see such issue on provided CodePen

**Comment by mehulRojasara** [comment]
i upload my single page on live site and i can see this issue here 

[www.themezaa.com/html/litho-beta/home-creative-agency.html](www.themezaa.com/html/litho-beta/home-creative-agency.html)

**Comment by nolimits4web** [comment]
I see you have a lot of things to do on window resize, so this could be issue and swiper can't detect correct size, so please look for a problem on your size, because there is no such issue with clean swiper like here http://idangero.us/swiper/demos/090-vertical.html

**Comment by mehulRojasara** [comment]
Thanks for taking time to look up on my issue ,

yes you are right there is no issue with clean swiper,
also today i found that all the issues are generated when i use the code for "fullscreen height" otherwise it goes perfect 

Thanks again for your response.
