### ISSUE TITLE
iOS wrong translate value after browser bar hidden

### ISSUE THREAD

**Issue by vin-ni** [nolimits4web/swiper#2787]
This is a:
* [x] bug

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: IOS
* Live Link or JSFiddle: https://jsfiddle.net/ct30wgu4/8/

### What you did
I'm using a vertical slider as an artist selection carousell.

### Expected Behavior
If the browser bars resize due to scroll or phone rotation to landscape and back, the initial top offset (translate 3d) is as when inited.

### Actual Behavior
If the viewport height changes du to scroll or phone rotation, the translate  3d gets somehow shifted. eg. Initially I start at -250px and after rotating the phone to portrait and back it is -190px

I believe the wrapper size or the dom grows, that make it scrollable and is therefore causing the shift in the y axis.

Screenshots I took from the last slide before and after the resize:

![before](https://user-images.githubusercontent.com/9806572/45142925-18a06b80-b1ba-11e8-85a4-ce8cd1a954f8.png)
![after](https://user-images.githubusercontent.com/9806572/45142933-1ccc8900-b1ba-11e8-84fb-053aa1af7e68.png)

**Comment by vin-ni** [comment]
To best see the bug: Open the site, rotate the phone and rotate it back. Now the first slide will be higher than before.

**Comment by nolimits4web** [comment]
I see you change slide's width during transition (active slide has different size), it is not supported

**Comment by vin-ni** [comment]
Alright, I removed that (used a little bit of `transform: scale()` to get a little animation)  and now it's working. Do you have any idea on how to make it work or can you imagine it being supported one day? I think a vertical slider with variable width could be interesting for interfaces.

**Comment by nolimits4web** [comment]
>  or can you imagine it being supported one day?

No, this won't be supported. As a workaround you can change style of slide's inner element, but slide size must be same during transition
