### ISSUE TITLE
Responsiveness broken

### ISSUE THREAD

**Issue by SniperGER** [nolimits4web/swiper#2789]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: macOS 10.12.6 / Safari 11.0.3
* Live Link or JSFiddle/Codepen or website with isssue: https://github.com/SniperGER/storeUI

_To build storeUI, run `npm install; npm install -g grunt-cli; grunt build`. You can then open the demo in `build/demo/index.html`._

### What you did
storeUI uses a responsive multirow layout with Swiper with 3 rows per group. On screens smaller than or equal 414px (iPhone Plus models), these groups are at 100% width, filling its container. On various iPad screens (9.7", 10.5" 12.9", including portrait and landscape) and above, the slides have a fixed width (10.5" landscape has 384px, while 12.9" portrait has 350px, for example).
I'm using the following parameters for a component called "Small Lockup" (3 rows, multiple columns):
```
roundLengths: 'false', // This should probably be a boolean, but it still seems to work this way
slidesPerView: 'auto',
slidesPerColumn: 3,
slidesPerGroup: 1,
spaceBetween: 32,
breakpoints: {
    414: {
        spaceBetween: 10,
        slidesPerView: 1
    }
    // Various spacing attributes for other screen sizes
    [...]
}
```

### Expected Behavior
Slides should _always_ stay at 3 rows, multiple columns, and should keep their set width. The Swiper container width should not exceed the screen width if using 3 slides or less.

### Actual Behavior
On screens smaller than 414px, the sliders are sometimes located beneath each other and the width exceeds the screen width by a thousand. I solved that by using `slidesPerView: 1` at 414px. This only happens at iPhone screen sizes, as iPad screen sizes are unaffected. However, setting `slidesPerView: 1` breaks the responsiveness of Swiper. Switching between screen sizes (or sometimes even orientations, which is basically the same) results in incorrectly located slides, 1 or 2 slides per row or full width slides as seen on 414px and lower.

**Comment by nolimits4web** [comment]
> To build storeUI, run npm install; npm install -g grunt-cli; grunt build. You can then open the demo in build/demo/index.html.

Can you please build it and share live link? Even better to see JSFiddle with the issue

**Comment by SniperGER** [comment]
Last commit added a `dist` folder. I might add a `gh-pages` branch soon, but this is all I can offer right now.

**Comment by joejoseph00** [comment]
I am observing perhaps something similar when displaying in breakpoints that the breakpoint display appears correct however I am unable to now "swipe" navigate properly unless in desktop mode , and I also notice that the item position moves around greatly when switching from desktop to mobile.  I'm testing on Firefox and Chrome.

I am going to try an older version of the library and see if that makes  a difference.

In my configuration I have a Drupal slideshow swiper view displaying 3 items of 6 items, in mobile I want one item, in tablet 2 items.  I switch to tablet resolution size and 2 items as configured, but the item position is unexpected and the swipe navigation seems to be stuck although I can drag and see the next item, as soon as I let go of the mouse button it snaps back to the item that it wants to display not the one I want to navigate to.

I have done custom modifications to a patched module that supports the swiper library in order to add the breakpoints configuration support for the swiper library for use with the views_slideshow_swiper Drupal module using a patch to allow compatibility with the latest 4.x swiper library .  I've added what appears to be working breakpoints configuration and have come across what appears to be a similar issue.

**Comment by joejoseph00** [comment]
I have written a patch to allow GUI configuration of breakpoints using the views_slideshow_swiper https://drupal.org/project/views_slideshow_swiper for Drupal 7 , requires the Swiper library (I am using the latest v4.4.1) and also requires a patch to the views_slideshow_slider module https://www.drupal.org/files/issues/2018-10-15/views_slideshow_swiper-upgrade_library_to_v4-2952971-29.patch

to set this up, I set up breakpoints settings as follows:
```
'breakpoints' => array(
                   1200 => array(
                     'slidesPerView' => 3,
                     'spaceBetween' => 10,
                   ),
                   480 => array(
                     'slidesPerView' => 1,
                     'spaceBetween' => 10,
                   ),
                   768 => array(
                     'slidesPerView' => 1,
                     'spaceBetween' => 11,
                   ),
                   992 => array(
                     'slidesPerView' => 2,
                     'spaceBetween' => 11,
                   ),
                   'enabled' => 1,
                 ),

these settings appear to be registered correctly as the display matches this.

However the issue is navigating in the various mobile modes, the only mode that works is the non breakpoint mode.

see the rest of the settings below.

```

and the other settings are described below:

```
              'views_slideshow_swiper' => array(
               'a11y' => array(
                 'enabled' => TRUE,
                 'firstSlideMessage' => 'This is the first slide',
                 'lastSlideMessage' => 'This is the last slide',
                 'nextSlideMessage' => 'Next slide',
                 'notificationClass' => 'swiper-notification',
                 'paginationBulletMessage' => 'Go to slide {{index}}',
                 'prevSlideMessage' => 'Previous slide',
               ),
               'autoplay' => array(
                 'delay' => 300,
                 'disableOnInteraction' => TRUE,
                 'waitForTransition' => TRUE,
               ),
               'coverflowEffect' => array(
                 'depth' => 100,
                 'modifier' => 1,
                 'rotate' => 50,
                 'slideShadows' => TRUE,
               ),
               'cubeEffect' => array(
                 'shadow' => TRUE,
                 'shadowOffset' => 20,
                 'shadowScale' => 0.94,
                 'slideShadows' => TRUE,
               ),
               'flipEffect' => array(
                 'limitRotation' => TRUE,
                 'slideShadows' => TRUE,
               ),
               'history' => array(
                 'key' => 'slides',
               ),
               'keyboard' => array(
                 'onlyInViewport' => TRUE,
               ),
               'lazy' => array(
                 'elementClass' => 'swiper-lazy',
                 'loadPrevNextAmount' => 1,
                 'loadedClass' => 'swiper-lazy-loaded',
                 'loadingClass' => 'swiper-lazy-loading',
                 'preloaderClass' => 'swiper-lazy-preloader',
               ),
               'mousewheel' => array(
                 'eventsTarged' => 'container',
                 'sensitivity' => 1,
               ),
               'navigation' => array(
                 'disabledClass' => 'swiper-button-disabled',
                 'enabled' => 1,
                 'hiddenClass' => 'swiper-button-hidden',
                 'nextEl' => '.swiper-button-next',
                 'prevEl' => '.swiper-button-prev',
               ),
               'pagination' => array(
                 'bulletActiveClass' => 'swiper-pagination-bullet-active',
                 'bulletClass' => 'swiper-pagination-bullet',
                 'bulletElement' => 'span',
                 'clickableClass' => 'swiper-pagination-clickable',
                 'currentClass' => 'swiper-pagination-current',
                 'dynamicMainBullets' => 1,
                 'el' => '.swiper-pagination',
                 'hiddenClass' => 'swiper-pagination-hidden',
                 'modifierClass' => 'swiper-pagination-',
                 'progressbarFillClass' => 'swiper-pagination-progressbar-fill',
                 'totalClass' => 'swiper-pagination-total',
                 'type' => 'bullets',
               ),
               'parameters' => array(
                 'allowSlideNext' => TRUE,
                 'allowSlidePrev' => TRUE,
                 'allowTouchMove' => TRUE,
                 'breakpoints' => array(
                   1200 => array(
                     'slidesPerView' => 3,
                     'spaceBetween' => 10,
                   ),
                   480 => array(
                     'slidesPerView' => 1,
                     'spaceBetween' => 10,
                   ),
                   768 => array(
                     'slidesPerView' => 1,
                     'spaceBetween' => 11,
                   ),
                   992 => array(
                     'slidesPerView' => 2,
                     'spaceBetween' => 11,
                   ),
                   'enabled' => 1,
                 ),
                 'containerModifierClass' => 'swiper-container-',
                 'direction' => 'horizontal',
                 'effect' => 'slide',
                 'followFinger' => TRUE,
                 'freeMode' => 1,
                 'freeModeMinimumVelocity' => 0.02,
                 'freeModeMomentum' => TRUE,
                 'freeModeMomentumBounce' => TRUE,
                 'freeModeMomentumBounceRatio' => 1,
                 'freeModeMomentumRatio' => 1,
                 'freeModeMomentumVelocityRatio' => 1,
                 'iOSEdgeSwipeThreshold' => 20,
                 'init' => TRUE,
                 'longSwipes' => TRUE,
                 'longSwipesMs' => 300,
                 'longSwipesRatio' => 0.5,
                 'loop' => 1,
                 'noSwiping' => TRUE,
                 'noSwipingClass' => 'swiper-no-swiping',
                 'normalizeSlideIndex' => TRUE,
                 'passiveListeners' => TRUE,
                 'preloadImages' => TRUE,
                 'preventClicks' => TRUE,
                 'preventClicksPropagation' => TRUE,
                 'resistance' => TRUE,
                 'resistanceRatio' => 0.85,
                 'runCallbacksOnInit' => TRUE,
                 'shortSwipes' => TRUE,
                 'simulateTouch' => TRUE,
                 'slideActiveClass' => 'swiper-slide-active',
                 'slideClass' => 'swiper-slide',
                 'slideDuplicateClass' => 'swiper-slide-duplicate',
                 'slideDuplicatedActiveClass' => 'swiper-slide-duplicate-active',
                 'slideDuplicatedNextClass' => 'swiper-slide-duplicate-next',
                 'slideDuplicatedPrevClass' => 'swiper-slide-duplicate-prev',
                 'slideNextClass' => 'swiper-slide-next',
                 'slidePrevClass' => 'swiper-slide-prev',
                 'slideVisibleClass' => 'swiper-slide-visible',
                 'slidesPerColumn' => 1,
                 'slidesPerColumnFill' => 'column',
                 'slidesPerGroup' => 1,
                 'slidesPerView' => 3,
                 'speed' => 300,
                 'touchAngle' => 45,
                 'touchEventsTarget' => 'container',
                 'touchMoveStopPropagation' => TRUE,
                 'touchRatio' => 1,
                 'touchReleaseOnEdges' => 1,
                 'uniqueNavElements' => TRUE,
                 'updateOnImagesReady' => TRUE,
                 'wrapperClass' => 'swiper-wrapper',
               ),
               'scrollbar' => array(
                 'dragClass' => 'swiper-scrollbar-drag',
                 'dragSize' => 'auto',
                 'el' => '.swiper-scrollbar',
                 'lockClass' => 'swiper-scrollbar-lock',
               ),
               'style_options__views_slideshow_swiper__active_tab' => 'edit-style-options-views-slideshow-swiper-parameters',
               'zoom' => array(
                 'containerClass' => 'swiper-zoom-container',
                 'maxRatio' => 3,
                 'minRatio' => 1,
                 'toggle' => TRUE,
                 'zoomedSlideClass' => 'swiper-slide-zoomed',
               ),
              )
```

**Comment by joejoseph00** [comment]
Here's a link to my sandbox environment .

https://media.olstad.biz/en/slider-test

**Comment by joejoseph00** [comment]
if you want to try editing the view and adjusting the settings:
sandbox environment:
https://media.olstad.biz/en/slider-test

and to edit the settings:
https://media.olstad.biz/en/admin/structure/views/view/slider_test/edit/page?destination=slider-test
click settings next to slideshow and you'll get the slider settings.
then press save at the top.

**Comment by joejoseph00** [comment]
created a pull request https://github.com/nolimits4web/swiper/pull/2834
please review

**Comment by SniperGER** [comment]
I'm going to try this and see if it fixes my issues too

**Comment by joejoseph00** [comment]
just FYI, I'm actively working on this issue, I'll make a new pull request once it's ready.  The first pull request is somewhat of an improvement, it appears that there's more to it than that, I think the breakpoints will also need to provide the slidesPerGroup for each breakpoint, that is what my requirement will ultimately need, and it does make sense, if we drop to 1 item on mobile narrow from 2 or 3 then the slidesPerGroup should also drop to 1 , but go up to x or X+1 slidesPerGroup on higher resolutions as per config value

**Comment by joejoseph00** [comment]
I've re-forked this repo , working on it here https://github.com/entreprise7pro/swiper
not yet ready but hopefully soon.

**Comment by joejoseph00** [comment]
OK, good news, I have a fix and it's relatively simple.  it was because the breakpoints parameters were comming in as strings when in fact they need to be numbers.  this was for all the breakpoints parameters that need to be integers not strings.  I will push this up as soon as possible, just packaging it up right now.

works great this time!!!

**Comment by joejoseph00** [comment]
Ok, I've created a pull request #2838 
this pull request has the source code fix.
However, for everyone else , if you cannot wait for the maintainer/owner to fix this, I've created a forked build in my repo here:
https://github.com/entreprise7pro/swiper  if you clone this , it's got the swiper.min.js build and the swiper.js in there with the fix.  I'll verify this fix again soon but it should be ok now.

**Comment by joejoseph00** [comment]
If you want to test this out with Drupal 7, here's the corresponding patch for views_slideshow_slider https://www.drupal.org/project/views_slideshow_swiper/issues/2952971#comment-12818796 download the views_slideshow module and the views_slideshow_swiper module (7.x-2.x dev release), enable them, create a view of type slideshow, set the type to swiper, edit the settings as you wish, all you need is a view that generates 6 or more items and it should work fairly nicely for a quick demo.

make sure to put a copy of my forked library https://github.com/entreprise7pro/swiper in the sites/all/libraries folder , the folder name is case sensitive, must be called Swiper

to be up and running quicker download a copy of the media_dev distribution, it already has most of the stuff you'll need to get started quickly and easily https://www.drupal.org/project/media_dev

**Comment by joejoseph00** [comment]
I see the pull request was taken Thanks @nolimits4web , however I imagine it will take some time for a build to be created, I haven't tested @nolimits4web nolimits4web changes meanwhile, until there's a build here you can use my build instead
https://github.com/entreprise7pro/swiper

**Comment by joejoseph00** [comment]
this issue is fixed thanks all

**Comment by joejoseph00** [comment]
lame stale bot, this is fixed, get yourself some better ai routines.

**Comment by joejoseph00** [comment]
bot, you are really lame
