### ISSUE TITLE
watchSlidesVisibility problem

### ISSUE THREAD

**Issue by kprodinfo** [nolimits4web/swiper#2790]
Hi!

I've noticed a problem.

The watchSlidesVisibility parameter does not work with slidesPerView. When you enter a page with the .swiper-slide-visible class, only the first element is marked.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: any
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/NLyBpB

**Comment by nolimits4web** [comment]
Documentation extreamly clearly says `watchSlidesProgress should be enabled`

<img width="1161" alt="ss" src="https://user-images.githubusercontent.com/999588/45489494-0780cd00-b76d-11e8-9591-1ed98cd835bc.png">

**Comment by kprodinfo** [comment]
@nolimits4web Yes you are right, but it does not help. [Check this](https://codepen.io/anon/pen/YOvgLX)
