### ISSUE TITLE
Sometimes the slide with index 1 is centered when swiped, scrolled or dragged in freeMode with freeModeSticky set to true

### ISSUE THREAD

**Issue by AUK4GIT** [nolimits4web/swiper#2792]
I am initialising the swiper with the below settings. My requirement is to get the details of the centered slide. But when scrolled, sometimes, the slide with index 1 is centered automatically even when I am scrolling or swiping from slide 50 to something more.

    {
    speed: 800,
    initialSlide: 0,
    slidesPerView: 13,
    spaceBetween:0,
    centeredSlides: true,
    slideToClickedSlide: true,
    freeMode: true,
    freeModeSticky: true }

Following is the link to fiddle https://jsfiddle.net/auk4fiddle/drqLzb08/11/

Upon debugging in the swiper.js file I found that, for freeModeSticky=true, the slideToClosest() function is called onTouchEnd() which is returning slidesPerGroup variable whose default value is 1. Below is the if condition the method that is causing the issue.

      function slideToClosest (speed, runCallbacks, internal) {
    if ( speed === void 0 ) speed = this.params.speed;
    if ( runCallbacks === void 0 ) runCallbacks = true;

    var swiper = this;
    var index = swiper.activeIndex;
    var snapIndex = Math.floor(index / swiper.params.slidesPerGroup);

    if (snapIndex < swiper.snapGrid.length - 1) {
      console.log("swiper.rtlTranslate:- "+swiper.rtlTranslate+" swiper.translate:- "+swiper.translate);
      var translate = swiper.rtlTranslate ? swiper.translate : -swiper.translate;

      var currentSnap = swiper.snapGrid[snapIndex];
      var nextSnap = swiper.snapGrid[snapIndex + 1];
      console.log("currentSnap:- "+currentSnap+" nextSnap:- "+nextSnap);
      console.log("lhs:- "+(translate - currentSnap)+" rhs:- "+(nextSnap - currentSnap) / 2);

      // Here is the condition that is returning the slidesPerGroup
        if ((translate - currentSnap) > (nextSnap - currentSnap) / 2) {
          index = swiper.params.slidesPerGroup;
        }
    }

As I am not making use of the variable slidesPerGroup, I have changed the if condition as below

     if (((translate - currentSnap) > (nextSnap - currentSnap) / 2) && swiper.params.slidesPerGroup != 1) {
          index = swiper.params.slidesPerGroup;
        }

[Click this video link to see the issue I am facing.][1]

[Here is another video link to see the issue.][2]

I have tried the various combination of configuration variables but could not fix the issue. I am missing anything ? Can any one hep me fix this ?

  [1]: https://drive.google.com/file/d/1XoTcazxqyUyD3ykbiUQw0BXzefdk5Yw_/view?usp=sharing
  [2]: https://drive.google.com/file/d/1ykGJbT2E4gF8gNit-aRmwBjZ2sxm91hl/view?usp=sharing

**Comment by nolimits4web** [comment]
So does it happens in RTL only?

**Comment by nolimits4web** [comment]
The fiddle you provided works totally fine for me

**Comment by AUK4GIT** [comment]
Hi @nolimits4web ,
Thanks for responding.

The issue happens not only in RTL but also LTR.
As reported by a customer, in the mobile app, it happens sometimes when they swipe briskly.

Yea, it's hard to reproduce this issue when you are using a mouse.

I am able to reproduce the issue consistently in my Laptop(Mac book pro) when I swipe/drag on the UI with three fingers on the trackpad.

**Comment by AUK4GIT** [comment]
Hi @nolimits4web,
were you able to reproduce the issue ?
