### ISSUE TITLE
Swiper, only reload/refresh fixes display issue

### ISSUE THREAD

**Issue by steffatstellaviecom** [nolimits4web/swiper#2795]
Displaying 3 slides/images per view, looped, centered.

With a clean cache, Swiper starts with the last slide and misses the first to the right. Browser refresh seems to fix it: swiper starts/initializes with first slide, no blank slides remain.

The amount of images is dynamic.

UPDATE:

The issue is with the CSS we added:

.swiper-container {
    width: 100%; height: 100%;
    margin-left: auto; margin-right: auto;
}

.swiper-slide {
    max-width: 1200px;
    height: auto;
    text-align: center;
    line-height: 0;
}

.swiper-slide img {
    height: 550px;
    width: auto;
}

.swiper-slide:nth-child(1n) {
    height: 550px;
    width: auto;
}

Removing the very last bit (nth-child) resets the slider to always start with the first slide. But the images stop sitting next to each other, but instead are spread apart.

Created this to demonstrate a little quicker:

http://jsfiddle.net/L3b1fzh9/13/

**Comment by nolimits4web** [comment]
When `slidesPerView: 'auto'` is used, you need to specify swiper-slide width in order to make it work correctly

**Comment by steffatstellaviecom** [comment]
Thx. Changing swiper-slide width to width: auto; and adding margin: 0 auto; is the solution. And removing .swiper-slide img and .swiper-slide:nth-child(1n) completely.
