### ISSUE TITLE
Swiper Pagination Bug

### ISSUE THREAD

**Issue by dlbone** [nolimits4web/swiper#2796]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.3
* Platform/Target and Browser Versions: macOS, Windows, Chrome, Safari, Edge, Firefox
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/deskmaster/pen/dqeQbB

### What you did
Created a new swiper and set loop to true. 

### Expected Behavior
Everytime I click the pagination bullet it should go to the correct slide.

### Actual Behavior
If you click pagination bullets enough eventually it goes to the wrong slide. 

I have checked the closed and open issues and not seen one where this bug is actually resolved.

**Comment by nolimits4web** [comment]
It works correctly, if you click too fast, then you can do a swipe instead of click
