### ISSUE TITLE
Can't change the slide by dragging on a link(image)

### ISSUE THREAD

**Issue by phx-vic** [nolimits4web/swiper#2798]
Swipper 4.4.0. MacOS. 
When change the slide by dragging the mouse on a link or image, the native drag is turned on.

https://codepen.io/phx-vic/pen/RYBpOx

**Comment by nolimits4web** [comment]
Can't see such issue, on horizontal swipes/drag everything is correct

**Comment by nolimits4web** [comment]
Fixed by #2799

**Comment by nolimits4web** [comment]
Fixed in 4.4.1
