### ISSUE TITLE
SlideNext instead SlidePrev on click button Next or preview

### ISSUE THREAD

**Issue by Advart** [nolimits4web/swiper#2802]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.1
* Platform/Target and Browser Versions: Windows,CHROME 69.0.3497.92
* Live Link or JSFiddle/Codepen or website with isssue: 
http://idangero.us/swiper/demos/ 

### Actual Behavior
On click right (left) arrow sometimes you go to previous (next) slide, not to next. Same problem on all projects only with swiper

**Comment by davorpeic** [comment]
This is still an issue, I think it is related on how many items you are displaying/pages

**Comment by Trojan0523** [comment]
I still encountered it too. Does anyone have a solution to resolve it?
