### ISSUE TITLE
Custom Pagination - a different bullet than the clicked one gets the active class

### ISSUE THREAD

**Issue by AngelikiSkandalou** [nolimits4web/swiper#2804]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.5
* Platform/Target and Browser Versions: Windows, CHROME 69.0.3497.92
* Example gif (borrowed from [this](https://github.com/nolimits4web/swiper/issues/2706) issue): 
![custom_pagination_error](https://user-images.githubusercontent.com/33658609/45612838-955a0200-ba64-11e8-802d-1dabfe9f7b3e.gif)

### What you did
I added a custom pagination slider, similar to the [Swiper Demos](http://idangero.us/swiper/demos/) one.

### Expected Behavior
I would expect that on every bullet click, the corresponding slide is shown.

### Actual Behavior
But, when running through the bullets, the selected slide "jumps" unexpectedly (eg when bullet 8 is clicked, bullet 6 is active and then when bullet 4 is clicked, bullet 2 is the active one, as seen in the gif above)

**Comment by nolimits4web** [comment]
I suspect you are just doing short swipe during fast click over bullets, try to change “touchEventsTarget” parameter
