### ISSUE TITLE
IE11 + transition on :hover : slides outside container get visible during trans

### ISSUE THREAD

**Issue by Tucsky** [nolimits4web/swiper#2805]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.1.
* Platform/Target and Browser Versions: IE11
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/Tucsky/ecq0naox/embedded/result

![swiper_ie11_csstransition_issue](https://user-images.githubusercontent.com/5738336/45623305-29d55c00-ba87-11e8-951f-17683a97609d.gif)

### What you did
Setup on simple carousel with 4 slidesPerViews
Add a transition on hover to highlight the hovered slide AND fadeout other slides that are not hovered
```
.swiper-slide {
  transition: opacity .4s ease-out;

  &:hover {
    opacity: 1 !important; // highlight hovered slide
  }
}

.swiper-container:hover .swiper-slides {
  opacity: .5; // fade out other slide
}
```

### Expected Behavior
Hovered slide is fully opaque while others are less opaque, carousel works, and slides that are outside .swiper-container doesnt shows up.

### Actual Behavior
Everything works out except when the transition of the slides occur, slides that are outside container get visible (even overflow:hidden is set on .swiper-container, as it is by default)

### How to fix
Idk why but setting `perspective: 1px` on the wrapper fix that issue.

**Comment by nolimits4web** [comment]
IE issue, nothing can do with it
