### ISSUE TITLE
runCallbacksOnInit set to false, still runs callback on init

### ISSUE THREAD

**Issue by webgineergit** [nolimits4web/swiper#2807]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.3
Chrome, OS X El Capitan + multiple other versions of browsers and devices

### What you did
set runCallbacksOnInit to false.

### Expected Behavior
runCallbacksOnInit set to false, does not run callbacks on init.

### Actual Behavior
runCallbacksOnInit set to false, does calls callback on init.

**Comment by Hello2Jason** [comment]
same probleam, hope the developers could fix it!
