### ISSUE TITLE
Feature request: Make virtual slides work also in loop mode.

### ISSUE THREAD

**Issue by ms-ox** [nolimits4web/swiper#2813]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.4.1
* Platform/Target and Browser Versions: all

It would be really great if virtual slides were supported also in loop mode.

**Comment by joemidi** [comment]
I really needed this on a project recently.

Any pointers on how this could work?

**Comment by glebmachine** [comment]
Oh

**Comment by digi4care** [comment]
Hi is the motivation still there to work on this enhancement?

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
