### ISSUE TITLE
slideNext & slidePrev Click Problem

### ISSUE THREAD

**Issue by kenangundogan** [nolimits4web/swiper#2815]
slideNext & slidePrev Click Problem

You can see the problem with the video recording in the problem.
https://www.youtube.com/watch?v=TmLQnG9C8zA&feature=youtu.be

**Swiper:** v4.4.1
**Computer:** macOS High Sierra version 10.13.6
**Browser:** Chrome Version 69.0.3497.100 (Official Build) (64-bit)
**Browser:** Chrome Version 70.0.3538.22 (Official Build) beta (64-bit)

**Comment by kukac7** [comment]
[this demo?](http://idangero.us/swiper/demos/200-infinite-loop.html)
i have nothing to do with it.

**Comment by omasback** [comment]
The last version with correct behavior was 4.0.7.
I believe this bug was introduced in 4.1.0

**Comment by dangelion** [comment]
This could be the same I said here: https://github.com/nolimits4web/swiper/issues/2821

**Comment by misterbailey** [comment]
@kenangundogan I've experienced similar issues with slideNext & slidePrev conflicting with drags. I found upping the `threshold` param value fixes this conflict 👍
