### ISSUE TITLE
breakpointsInverse: true does not work as mobile first

### ISSUE THREAD

**Issue by komarovartem** [nolimits4web/swiper#2816]
Hello,

When we are using `breakpointsInverse: true` for mobile first websites, assuming that the larger window width parameters inherit rules from smaller window width parameter. But it does not work as expected. 

<pre>
breakpointsInverse: true,
slidesPerGroup: 1,
slidesPerView: 1,
breakpoints: {
576: {spaceBetween: 20, slidesPerView: 2}
768: {spaceBetween: 40, slidesPerView: 3}
992: {spaceBetween: 60, slidesPerView: 4}
1200: {spaceBetween: 80}
}
</pre>

For example this code will display only one slide per view for desktops (1200px) but if resize window to mobile width (576px) and then resize it back to desktop resolution the slider will apply 4 slides per view. So it seems during initialisation swiper does not check all breakpoints but only the last one.

Regards

**Comment by nolimits4web** [comment]
Just add `slidesPerView: 1` for `1200` breakpoint

**Comment by komarovartem** [comment]
> Just add `slidesPerView: 1` for `1200` breakpoint

Well, this is EXACTLY the issue i'm pointing on. Please check the issue.
