### ISSUE TITLE
404 error for  swiper.esm.bundle.js and swiper.esm.js on cloudfare cdn

### ISSUE THREAD

**Issue by SamnnyWong** [nolimits4web/swiper#2818]
Hello

Just in case you're not aware of this, the URL embedded in the 4.4.1 version of the swiper is returning a 404 at the moment:

<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.x.x/js/swiper.esm.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.x.x/js/swiper.esm.bundle.js"></script>

From the get started page:
http://idangero.us/swiper/get-started/

Any fix?
Thanks in advance.

**Comment by nolimits4web** [comment]
This page clearly says:

> Don't forget to change 4.x.x to actual Swiper version

**Comment by SamnnyWong** [comment]
I did replace it with 4.2.1 and it return 404 error

https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.1/js/swiper.esm.js
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.1/js/swiper.esm.bundle.js

Did i do something wrong?

**Comment by nolimits4web** [comment]
Yes, there is no 4.2.1 version

**Comment by SamnnyWong** [comment]
I am sorry, i tired 4.4.1, it doesn't work too

https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/js/swiper.esm.js
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/js/swiper.esm.bundle.js

**Comment by nolimits4web** [comment]
esm modules are not available on CDN

**Comment by marvinpoo** [comment]
> esm modules are not available on CDN

Makes sense. **1b** should be updated for that to prevent confusion.
https://idangero.us/swiper/get-started/
