### ISSUE TITLE
Clickable Pagination does not navigate to the correct slide

### ISSUE THREAD

**Issue by omasback** [nolimits4web/swiper#2820]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.1
* Platform/Target and Browser Versions: Chrome 69.0.3497.100 MacOS 10.13.6
* http://idangero.us/swiper/demos/200-infinite-loop.html

### What you did
click pagination bullet

### Expected Behavior
carousel should navigate to the corresponding slide

### Actual Behavior
does not go to the correct slide. It usually goes to the next slide

**Comment by omasback** [comment]
The last version with correct behavior was 4.0.7. 
I believe this bug was introduced in 4.1.0

**Comment by mpbunch** [comment]
Same issue.

**Comment by mpbunch** [comment]
Is there any activity on this?

**Comment by jmjunod** [comment]
Also see https://github.com/nolimits4web/swiper/issues/3015

**Comment by mr-lizer** [comment]
I solved inserting these lines into option 

var swiperOptions = {
preventClicks:false,
preventClicksPropagation:false,
slideToClickedSlide:true,

I Think clicking on pagination bullet interferes in some way on slide interaction so with the above code all is ok...at least for my project

**Comment by nasangw** [comment]
@mr-lizer Thank you so much

**Comment by gNesh01** [comment]
@mr-lizer Thank you! This worked for me as it should.
