### ISSUE TITLE
Can drag slides while on navigation arrows

### ISSUE THREAD

**Issue by dangelion** [nolimits4web/swiper#2821]
Hi
I noticed that I can drag the slides also when I'm on the nav buttons.

Before I figured out that this was the cause, it happened that while clicking on Next button, the slides randomly scroll backward instead of forward! And this seemed an awful bug. 

Please check the below gif for better understand what I mean.

[![record.gif](https://i.postimg.cc/JhF37bzb/record.gif)](https://postimg.cc/B8xPMPD6)

Is this a bug? Is there a way to avoid it? In other words, I'd like to not drag the slides when the cursor is clicking on nav buttons. Thanks.

**Comment by t-ricci-delta** [comment]
Got here after opening #3062 (duplicated, didn't notice this issue).

Anybody else noticed this behavior? Can we expect for it to be fixed any time soon?

**Comment by nolimits4web** [comment]
Check `touchEventsTarget`, it must be set to `wrapper` http://idangero.us/swiper/api/
