### ISSUE TITLE
SlidePrev go to first slide

### ISSUE THREAD

**Issue by nicolasrozas** [nolimits4web/swiper#2825]
* Swiper Version: v4.4.1
* Platform/Target and Browser Versions: Chrome.

--------------------------------------------------------------------------

Im using the slider with this config

> direction: 'horizontal',
    observer: true,
    slidesPerView: 'auto',
    scrollbar: false,
    watchOverflow: true,
    spaceBetween: 20,
    freeMode: true,
    freeModeSticky: true,
    centeredSlides: false,
    freeModeMomentumVelocityRatio: 0.2,
    slidesOffsetAfter: 33,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
      disabledClass: 'hidden'
    }

im adding in the swiper items with the event (reachEnd) and when this happen, sometimes the first item is not in the edge of the container, and when i click back it goes to the first slide.

[YOUTUBE EXAMPLE](https://youtu.be/WB0slKYqv28)

PS: If when this happen i use the "slideTo" method, it works well

**Comment by Wayne-Wen** [comment]
We are having the same issue. I believe that the issue should be "auto" for the "slidesPreView". When swipe on the slide, the "translate" is not in "normalizedSnapGrid" which make "prevIndex" undefined.
So using "slideTo" manually instead of "slidePrev" will fix the problem

**Comment by goodfairy** [comment]
> We are having the same issue. I believe that the issue should be "auto" for the "slidesPreView". When swipe on the slide, the "translate" is not in "normalizedSnapGrid" which make "prevIndex" undefined.
> So using "slideTo" manually instead of "slidePrev" will fix the problem

in file /swiper/esm/components/core/slide/slidePrev.js
replace 
-  if (!prevSnap && normalizedTranslate >= snap)  prevSnap = snap;
+  if ((!prevSnap || prevSnap < snap) && normalizedTranslate >= snap)  prevSnap = snap;
and
-  prevIndex = slidesGrid.indexOf(prevSnap);
+ prevIndex = slidesGrid.indexOf(prevSnap)-1;
