### ISSUE TITLE
Virtual API seems not to work together with History API

### ISSUE THREAD

**Issue by michelstomp** [nolimits4web/swiper#2826]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.0
* Platform/Target and Browser Versions: Browser, swiper.esm.bundle
* Live Link or JSFiddle/Codepen or website with issue: Not available...

### What you did
I am using both Virtual and History API
const swiperOptions = {
    slidesPerView: 1,
    spaceBetween: 0,
    observer: true,
    freeMode: false,
    effect: this.$el.data('effect') || 'slide',
    keyboard: true,
    shortSwipes: is.touchDevice(),
    navigation: {
        nextEl: this.$el.data('buttonNext') || '.swiper-button-next',
        prevEl: this.$el.data('buttonPrev') || '.swiper-button-prev',
    },
    pagination: {
        el: this.$el.data('pagination') || '.swiper-pagination',
        type: 'progressbar',
    },
    history: {
        key: this.data.slug,
    },
    virtual: {
        slides: this.data.pages,
        renderSlide: this.renderSlide.bind(this),
    }
};

this.swiperInstance = new Swiper(this.$el.data('swiperContainer'), swiperOptions);
this.swiperInstance.on('slideChange', this.onSlideChangeTransitionEnd.bind(this));

### Render slides method
renderSlide(slide, index){
        return `<div id="slide-${slide.id}" class="magazine-slide swiper-slide ${this.swiperItemClassName} bg-white" data-history="${ slide.slug }">${ slide.html }</div>`
}

### Expected Behavior
Three slides in DOM, adding / removing slides with Virtual API. 

### Actual Behavior
swiper.esm.bundle.js?fca7:5759 Uncaught TypeError: Cannot read property 'toString' of undefined
    at Object.slugify (swiper.esm.bundle.js?fca7:5759)
    at Swiper.setHistory (swiper.esm.bundle.js?fca7:5744)
    at Swiper.transitionEnd (swiper.esm.bundle.js?fca7:5820)
    at swiper.esm.bundle.js?fca7:294
    at Array.forEach (<anonymous>)
    at swiper.esm.bundle.js?fca7:293
    at Array.forEach (<anonymous>)
    at Swiper.emit (swiper.esm.bundle.js?fca7:287)
    at Swiper.transitionEnd$1 [as transitionEnd] (swiper.esm.bundle.js?fca7:1035)
    at HTMLDivElement.<anonymous> (swiper.esm.bundle.js?fca7:1142)

**Comment by patrickcate** [comment]
I've just run into the same issue/error.

**Comment by alexvais** [comment]
Could you fix this issue, i am running in the same isse in version 6.2.0.

@patrickcate @michelstomp

**Comment by ynamite** [comment]
Same here. Any plans on fixing this?
