### ISSUE TITLE
Zoom handles wrong slide

### ISSUE THREAD

**Issue by ms-ox** [nolimits4web/swiper#2827]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.3.3 release, 0dcd6ca
* Platform/Target and Browser Versions: Chrome 69.0.3497.100 on Ubuntu 18.04.1 LTS

### What you did
Configured Swiper to simulate touch and use zoom with toggle.
1. Initialize Swiper
2. Double click on slide to zoom in
3. Call `mySwiper.slideNext()` or `mySwiper.slideTo()` to switch to the next slide
4. Call `mySwiper.zoom.in()`

### Expected Behavior
The current slide should be zoomed.

### Actual Behavior
The previous slide is zoomed

### Notes
- With simulate touch is activated, a double click on the slide, or switching a slide via navigation button invokes `updateClickedSlide(e)`
- This updates `swiper.clickedSlide` and `swiper.clickedIndex` to the current slide
- Calling `mySwiper.slideTo()` **doesn't invoke** `updateClickedSlide(e)`, therefore `swiper.clickedSlide` and `swiper.clickedIndex` were not updated.
- Calling `mySwiper.zoom.in()` again checks for `gesture.$slideEl = swiper.clickedSlide ? $(swiper.clickedSlide) : swiper.slides.eq(swiper.activeIndex);`
- Where `swiper.activeIndex` points the the current slide `swiper.clickedSlide` still points to the previous slide

**Comment by daliborkovac** [comment]
In the previous post by @ms-ox the Expected Behavior and Actual Behavior text should be reversed. The expected behavior is that the current slide should be zoomed.

**Comment by daliborkovac** [comment]
I have done my workaround like this:
In zoom.in and zoom.out functions I've commented out the parts where it uses the clicked slide and left just the part where it uses the activeIndex:

`        gesture.$slideEl = /*swiper.clickedSlide ? $(swiper.clickedSlide) :*/ swiper.slides.eq(swiper.activeIndex);
`

**Comment by ms-ox** [comment]
> In the previous post by @ms-ox the Expected Behavior and Actual Behavior text should be reversed. The expected behavior is that the current slide should be zoomed.

Many thanks to @daliborkovac for bringing this up! I fixed the description.

**Comment by tienbuide** [comment]
I had the same problem and solved it by setting the `clickedSlide`-property right before calling `swiper.zoom.in();`/`swiper.zoom.toggle();`

`swiper.clickedSlide = swiper.slides.eq(swiper.activeIndex);`
