### ISSUE TITLE
TypeError: Cannot read property 'slidesPerGroup' of undefined"

### ISSUE THREAD

**Issue by proshuai** [nolimits4web/swiper#2828]
This is a (multiple allowed):
* [✔️] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: swiper4.0
* Platform/Target and Browser Versions: PC chrome 68.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
when you change slide, but i dont set this option

**Comment by nolimits4web** [comment]
JSFiddle or live example is required

**Comment by faizyukstay** [comment]
Me also experience the same thing when doing `swiper.slideTo(index, 1000, false);` it return 

**TypeError: Cannot read property 'slidesPerGroup' of undefined**

```
Swiper.slideTo
node_modules/swiper/dist/js/swiper.esm.bundle.js:1292
  1289 |   return false;
  1290 | }
  1291 | 
> 1292 | var snapIndex = Math.floor(slideIndex / params.slidesPerGroup);
       | ^  1293 | if (snapIndex >= snapGrid.length) snapIndex = snapGrid.length - 1;
  1294 | 
  1295 | if ((activeIndex || params.initialSlide || 0) === (previousIndex || 0) && runCallbacks) {
```
