### ISSUE TITLE
swiper.esm.js: Webpack compile and report errors

### ISSUE THREAD

**Issue by jiankafei** [nolimits4web/swiper#2830]
config:
```js
module: {
  rules: [{
    test: /\.js$/,
    exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
    loader: 'babel-loader',
  }]
}
```

TypeError:
Cannot assign to read only property 'exports' of object '#Object'

**Comment by zebapy** [comment]
did you fix this? exclude isn't working for me

**Comment by danjayrose** [comment]
I had this issue as well but discovered a fix by including paths for babel-loader rather than using exclude, eg:

`include: [
          path.resolve(__dirname, "src"),
          path.resolve(__dirname, "node_modules/dom7"),
          path.resolve(__dirname, "node_modules/ssr-window"),
          path.resolve(__dirname, "node_modules/swiper")
],`
