### ISSUE TITLE
Navigation direction sometimes wrong

### ISSUE THREAD

**Issue by kieste** [nolimits4web/swiper#2846]
Sometimes when I click on the next slide navigation button the slider goes to the previous slide and vice verca.

This can be reproduced on the Swiper demo page http://idangero.us/swiper/demos/

Steps to reproduce:
1.) Go to second slider on http://idangero.us/swiper/demos/
2.) navigate to slide 3
3.) click on next slide navigation button
4.) click on previous slide navigation button
5.) repeat steps 3 and 4 several times

I am using Firefox 62.0.3 on Mac. Is this a known issue?

**Comment by nolimits4web** [comment]
You just doing short swipe instead of click. Change touchEventsTarget to don’t track swipe gestures over whole container
