### ISSUE TITLE
Custom Pagination Click loads wrong slide.

### ISSUE THREAD

**Issue by mpbunch** [nolimits4web/swiper#2848]
This is a (multiple allowed):
* [x] bug

* Swiper Version: latest
* Platform/Target and Browser Versions: browsers
http://idangero.us/swiper/demos/

### What you did
I looked at the swiper demo "custom pagination" and clicked on the custom navigation links (circles with numbers)
-- Also, the same steps in my implementation 

### Expected Behavior
The custom pagination button clicked should take you to that particular slide.

### Actual Behavior
At, what seems to be random, when clicking 1->2->3->4 etc, the page that gets loaded, is not what you clicked.

**Comment by nolimits4web** [comment]
Try to set `touchEventsTarget: 'wrapper'`
