### ISSUE TITLE
v4.4.2 release is needed

### ISSUE THREAD

**Issue by joejoseph00** [nolimits4web/swiper#2851]
I did fork the v.4.4.1 and put in fixes that were pulled into your master however I needed a build so I built a forked v4.4.2 release and I've tested it to work correctly whereas v4.4.1 is lacking the fixes I need.

I could continue to use my fork but I have to make a special request to have the swiper library whitelisted to get it released on my project and so far they only whitelisted your releases not mine.

So, would you please build and push and tag and release v4.4.2 ?  So that I don't have to make another whitelist request?

**Comment by nolimits4web** [comment]
Released

**Comment by joejoseph00** [comment]
Большое спасибо моему другу, я не говорю по-русски, но, может быть, когда-нибудь я смогу научиться этому.
