### ISSUE TITLE
Swiper stopped working on chrome 70

### ISSUE THREAD

**Issue by sagikarni** [nolimits4web/swiper#2853]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.4.1.
* Chrome 70 on windows 10
* https://idangero.us/swiper/

### What you did
Trying to swipe in desktop PC with touch screen

### Expected Behavior
Swiper should work

### Actual Behavior
Swiper not working anymore when swiping in desktops

"ontouch* members on window, document, and element are disabled by default on desktop devices"
see here : https://www.chromestatus.com/feature/4764225348042752

Any workarounds ?
btw , "slick" swiper (http://kenwheeler.github.io/slick/) seems to be working well...

**Comment by Jing-King** [comment]
We use this on windows desktop with a touchscreen and render the app with chrome. So chrome 70 change touch event on desktops. https://www.chromestatus.com/feature/4764225348042752
Work Around was to enable it on chrome://flags/

**Comment by sagikarni** [comment]
The problem is that i cant ask all my users to change their chrome settings...

**Comment by Jing-King** [comment]
I know what you mean, it was a workaround that works for me. but the odd part is that hammerjs is still working. http://hammerjs.github.io/

**Comment by nolimits4web** [comment]
But what is the issue? Swiper already uses Pointer Events where supported

**Comment by Jing-King** [comment]
https://vimeo.com/298408082

**Comment by SteveMcAwesome** [comment]
This change in Chrome broke our production software, in the exact same way as @Jing-King's video, so we had to do a quick upstream fix. The problem was only in the feature detection, so we went for changing

```
    touch: (win.Modernizr && win.Modernizr.touch === true) || (function checkTouch() {
      return !!(('ontouchstart' in win) || (win.DocumentTouch && doc instanceof win.DocumentTouch));
    }()),
```

into

```
    touch: true,
```

Of course the better solution is for a new way of detecting touch support, but all of our target devices do so this works for us. YMMV.

**Comment by sagikarni** [comment]
Is there any plan to fix this bug ?

**Comment by nolimits4web** [comment]
How can i see/test the issue on a windows or windows VM without touch screen laptop/device?

**Comment by geekorn** [comment]
Hi! Sorry for my english.
You can test this issue when run chrome with flags:
```"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --incognito --noerrdialogs --disable-infobars --disable-suggestions-service --disable-save-password-bubble --start-maximized --disable-gpu --disable-pinch --kiosk```
and open ChromeDevTools with touch device emulation.

**Comment by HansTenBrinke** [comment]
I ran into the same issue. This has fixed it for me:

`touch: (win.Modernizr && win.Modernizr.touch === true) || (function checkTouch() {
        return !!(('ontouchstart' in win) || (win.DocumentTouch && doc instanceof win.DocumentTouch) || navigator.maxTouchPoints > 0);
      }()),`

**Comment by sagikarni** [comment]
Thanks HansTenBrinke ,I will try it out.
Working with chrome will help me personally but wont work for all my users out there...

**Comment by sagikarni** [comment]
thx...

**Comment by weituotian** [comment]
@sagikarni 
when on touch screen! 
then event
```
new Swiper(el, {
                    loop: true,
                    on: {
                        click: function (event) {
                            if (
                                !event.target.classList.contains('swiper-pagination-bullet') &&
                                !event.target.classList.contains('swiper-button-next') &&
                                !event.target.classList.contains('swiper-button-prev')
                            ) {

                                // 文档地址
                                // https://github.com/surmon-china/vue-awesome-swiper/issues/226#issuecomment-443201823
                            }
                        }
                    }
                })
```

the event 'onclick' not work!
no other solution!
please fix it!
