### ISSUE TITLE
Issue with slidesPerView and centeredSlides causing last few slides to disappear

### ISSUE THREAD

**Issue by adriantwarog** [nolimits4web/swiper#2855]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.4.1
* Platform/Target and Browser Versions: All

### What you did
````
latestOffersSwiper = new Swiper('.latest-offers-swiper', {
		init: false,
		initialSlide: 2,
		slidesPerView: 'auto',
		spaceBetween: 30,
		slidesOffsetBefore: 124,
		centeredSlides: true,
		// loop: true,
		pagination: {
			el: '.swiper-pagination',
			clickable: true,
		},
	});
````

Removing centeredSlides on this syntax will cause the last few slides to literally disappear. The issues doesnt occur if i remove slidesPerView, set to a number, or if i remove centeredSlides.

### Expected Behavior
For the number of slides to equal how many in the HTML code. Its strange that if I have 5 slides, and set centeredSlides: false, 2 randomly disappear.

centeredSlides: true
![alt text](https://i.imgur.com/OiVgopW.jpg "Working")

centeredSlides: false
![alt text](https://i.imgur.com/7tWK3yf.jpg "Not Working")

**Comment by nolimits4web** [comment]
Would be good to see live example

**Comment by ihatem** [comment]
I had the same issue. You didn't share your css code but for me the problem is caused by the "justify-content" set to center. I turned it to normal and it worked.
