### ISSUE TITLE
Virtual slides breaks the correct order of slides

### ISSUE THREAD

**Issue by alejandroiglesias** [nolimits4web/swiper#2857]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.x
* Platform/Target and Browser Versions: Chrome 70 (works fine in Chrome 69 and other browsers).
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/alejandrogarciaiglesias/k0Lj1xmn/8/

### What you did
Initializing Swiper with virtual slides on Chrome 70 changes the order of slides after sliding a few times.

```js
var swiper = new Swiper('.swiper-container', {
  virtual: {
	// ...
  },
});
```

In order to reproduce, please go to the Virtual Slides Demo page, click "Slide 250" and then "Slide 1".

### Expected Behavior
The expected behavior for the slider is to go back to the initial position maintaining the slides sequential order (Slide 1, Slide 2, Slide 3, Slide 4, Slide 5, etc).

### Actual Behavior
What happens is that the slider goes back to the beginning, but the first slides' order is inverted (ie, Slide 3, Slide 2, Slide 1, Slide 4, Slide 5, etc).

**Comment by igalicodean** [comment]
Note: also reproduced in the jsfiddle by clicking on `slide 250` and then on `slide 1`

**Comment by alejandroiglesias** [comment]
I just realized it can be reproduced in the Swiper demo without any changes just by clicking on "slide 250" and then on "slide 1", so not related to `slidesPerGroup` per se.
