### ISSUE TITLE
missing slideChangeTransitionEnd event

### ISSUE THREAD

**Issue by igal1c0de4n** [nolimits4web/swiper#2862]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.2
* Platform/Target and Browser Versions:  macOS, CHROME 70.0.3538.77 
* Live Link or JSFiddle/Codepen or website with isssue: work in progress
For now, issue seems to happen on the swiper in our app which has with one main card (+two partially visible cards)

### What you did
1. open url https://story.mapme.com/the-rise-of-the-donald/section/2ad68d14-97b2-4b51-b4a8-6831ebb36458/details
2. open devtools, select a portrait mobile view (for example Pixel 2)
3. start swiping cards. 
I'm not sure how, but maybe there's a way of inspecting/hooking into the swiper component. If so, it may be possible to see the event isn't fired

### Expected Behavior
slideChangeTransitionEnd event should fire 
### Actual Behavior
slideChangeTransitionEnd event is missing
slideChange fires, so it's possible to use as a temp workaround

Probably related to #2439 (not sure)

**Comment by garrettmaring** [comment]
I'm also experiencing this. `slideChangeTransitionEnd` is not firing consistently.

**Comment by garrettmaring** [comment]
![screen shot 2018-12-10 at 11 43 12 am](https://user-images.githubusercontent.com/8270120/49757278-e7c84a80-fc70-11e8-9b88-900efc4c737f.png)

I know this doesn't help much but when swiping back and forth between two slides quickly, I'm able to make the issue very noticeable.

I have virtualized slides and have `preventInteractionOnTransition` set to `true`

**Comment by davidstoner** [comment]
I've noticed that this bug will happen if you slide "past" the beginning or end of a set of slides that doesn't loop. So trying to slide back from the first slide and then moving to the last won't fire the event, but starting from the beginning and only going forward will.

**Comment by alewin** [comment]
same issue 5.2.1

**Comment by KristerV** [comment]
I have both `slideChange` and `slideNextTransitionEnd`. Only going forward, first swipe triggers only `slideChange`, second only `slideNextTransitionEnd`, from then on both are triggered every time (unless i swipe back).
