### ISSUE TITLE
Swiper does not call slideChange when slidesPerView: 'auto'

### ISSUE THREAD

**Issue by TitanFighter** [nolimits4web/swiper#2864]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.2.
* Platform/Target and Browser Versions: Ubuntu 18.04; Chrome 70.0.3538.77 (Official Build) (64-bit).
* Live Link or JSFiddle/Codepen or website with isssue: [DEMO](https://codesandbox.io/s/8k5l4mk270).

### What you did
Just try to swipe slides and you will see that `slideChange` event is not triggered. Using this event I want to get `realIndex`. Just want to draw your attention that there are 3 slides but just 2 nav bullets (in my case I do not care what `realIndex` can be, because I can simply do +-1, but what I really need is a workable `slideChange` event).

### Expected Behavior
Swiping of slides should trigger `slideChange` event in order to let me get `realIndex`.

### Actual Behavior
Swiping of slides does not trigger `slideChange` event.

**Comment by alejandroiglesias** [comment]
In my case, I also use `slidesPerView: 'auto'` and I get the `slideChange` event except for the last slide, which is very weird.

**Comment by r0skar** [comment]
Experiencing the same issue as @alejandroiglesias. When `slidesPerView: 'auto'` is set, no callbacks for the last slide is fired.

**Comment by joelamltc** [comment]
#3108

**Comment by begonaalvarezd** [comment]
I am experiencing the same issue and `centeredSlides: true` though it fixed it, is not an option for me because I also need the slides to be left aligned. Did anybody find a solution? :pray:

**Comment by Yaolegol** [comment]
still issue

**Comment by asakasinsky** [comment]
I am experiencing the same issue with `slidesPerView: 1.2`.

**Comment by doxiaodong** [comment]
Is it possibly to add a param(such as slideFollowPagination)?

**Comment by arnevankauter** [comment]
Is there any update on this? Still seeing this issue.

**Comment by webgrafia** [comment]
same problem

**Comment by RLIRT** [comment]
The slideChange event is triggered when the active slide changes in a SwiperJS instance. However, when the slidesPerView option is set to auto, the number of visible slides in the SwiperJS instance is dynamically calculated based on the available space. In this mode, the active slide may change more frequently than when a fixed number of slides is set using the slidesPerView option.

Therefore, in the auto mode, the slideChange event may be triggered more frequently than expected, and this can affect the performance of your application. To avoid this issue, the SwiperJS library does not trigger the slideChange event when the slidesPerView option is set to auto.

Instead, you can use the transitionEnd event, which is triggered when the SwiperJS instance finishes its transition to a new slide. You can then check the activeIndex or realIndex property of the SwiperJS instance to determine which slide is currently active.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
