### ISSUE TITLE
Resize slides based on -active, -prev, -next classes (width as percentage)

### ISSUE THREAD

**Issue by opetznick** [nolimits4web/swiper#2866]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.2
* Platform/Target and Browser Versions: probably anywhere
* Codepen: https://codepen.io/865678/pen/aQOrXp

### What you did
I'm using an infinite loop Swiper, centeredSlides with slidesPerView on auto. The Slides get resized based on the -active, -prev and -next classes. The Slides are using a percentage width to determine the amount of visible slides. I would like to have at max 5 visible slides so my current definition is active: 30%, prev & next: 20%, normal slides: 15%. 

### Expected Behavior
5 visible centered variable width slides with the right arrangement.

### Actual Behavior
The arrangement of the slides is not centered. If the browser gets resized or i call update() the slides are perfectly centered.

**Comment by St3ve89** [comment]
Any solution to this one ?
