### ISSUE TITLE
Swiper .slideTo() bug

### ISSUE THREAD

**Issue by ElVisPL** [nolimits4web/swiper#2876]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: `4.4.2`, (It is little better on `4.3.3`)
* Platform/Target and Browser Versions: Tested on chrome & chrome mobile

### What you did
Generally `slideTo()` does not work properly when adding dynamically slides and when slider container right boundary is close to slide that we want to slide to

But from `4.3.5 it` does not work even for some slides that are on the screen but are close to end of slide container

Simple reproduction is to call `slideTo()` to slide already visible

It is hard to reproduce behavior bugged from 4.3.5 but maybe it will give some idea:
```
const selectedItemIndex = this.walls.indexOf(this.selectedWall)
      if (selectedItemIndex !== -1) {
        this.swiper.slideTo(selectedItemIndex, this.slideTimeout)
      }
```
this.walls.length = 36 and bug happens when index is <= 13, but it depends on screen size, when it is wider then buggy index is higher....

### Expected Behavior
`.slideTo() `method Slides to slide with index
`slideChangeTransitionEnd` is called

### Actual Behavior
`.slideTo()` method slides to end of slider and calls `reachEnd` method. Moreover `slideChangeTransitionEnd` is not called

**Comment by smndhm** [comment]
Is it fixed in the next release ?
I'm having an issue with it.
