### ISSUE TITLE
`vertical` mode fully unusable inside flexed parents, even if current element is an auto height. The spacing between thumbs grows with each resize.

### ISSUE THREAD

**Issue by yuchant** [nolimits4web/swiper#2882]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.2

* Platform/Target and Browser Versions: Chrome up to date as of today 
Version 70.0.3538.102 (Official Build) (64-bit)

* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

https://jsfiddle.net/gr5jwLbe/

### What you did
Created a vertical swiper with minimal configs inside of a bootstrap column, or flexed parent but in a child that does not fill up to the height of its parent.

### Expected Behavior
The swiper should calculate the right heights for the slides. If 4 slides are to appear, 4 should appear without 1000px of whitespace (after you resize a few times).

### Actual Behavior
The swiper shows lots of whitespace between slides.
The extra whitespace grows exponentially as you resize the browser.

Please note I've spent many hours debugging and trying to fix via forcing heights, guaranteeing that the swiper parent is not flexed to full height, etc.

My solution current is calculating the height of the slides and wrapper myself on resize, but is very weak.

**Comment by NenadObradovic** [comment]
Hi guys,

I have the same issue as yuchant. 
Also there is the problem if you ser 1 item for slidePerView option. Slide got full height, you can see 2 items instead of one and sliding are messed up.

Best regards,
Nenad

**Comment by hartey11** [comment]
I'm having the same issue. What is the solution to this?

**Comment by nolimits4web** [comment]
Because, based on what it should know/limit its height? You need to have height fixed for vertical swiper so it can be calculated, e.g. fixed value like `px` or relative like `vh/w` or other ones

**Comment by yuchant** [comment]
Why can't it determine that these images are 100 pixels tall? 
https://jsfiddle.net/gr5jwLbe/

If some CSS made the image max-width: 50px, we'd still be able to see that $("img").height() is 50. Thanks for any help!!
