### ISSUE TITLE
bug when dragging in zooming rtl direction

### ISSUE THREAD

**Issue by frmostafa** [nolimits4web/swiper#2884]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.2

hi .sorrry im not good in english . thanks for yout great library . when my direction is in 'rtl' mode zooming is in trubble . can you help me to fix it? tnx

**Comment by alaa-alshamy** [comment]
any news here ?
