### ISSUE TITLE
slideToClickedSlide does not work with first n slides...

### ISSUE THREAD

**Issue by siulca** [nolimits4web/swiper#2886]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Latest (4.2.5)
* Platform/Target and Browser Versions: MacOs Firefox

### What you did
Used the Virtual Slides Example, added option to make it Coverflow effect and slideToClickedSlide = true

### Expected Behavior
Swiper should select and slide to clicked slide.

### Actual Behavior
Clicking on the first few slides the click event does not seem to trigger. But it works after the first few slides.

**Comment by jrgparamo** [comment]
I see the same issue in FireFox 67.0.1, on Linux and Windows
