### ISSUE TITLE
slidesPerView: 'auto' + larger active slide

### ISSUE THREAD

**Issue by QJan84** [nolimits4web/swiper#2889]
Hello!

The number of visible slides should be 3. The active slide is 50% wide and the other two 25% each. In the CSS, each slide is 25% wide and the active slide will get 50% once the class "swiper-slide-active" has been set.

The problem now is that swiper goes through the 25% width of 4 slides instead of 3. Click several times on the "next" button and you'll see that there are 4 slides at once.

**In principle I would like to have only 3 slides visible, where however the active slide receives 50% width and the other two slides 25% each.**

* Swiper Version: 4.4.1
* Live Link or JSFiddle/Codepen or website with isssue: [CodePen](https://codepen.io/QJan84/pen/YREBEK)

**Comment by stayacid** [comment]
Still no solution?( Really need this feature
