### ISSUE TITLE
watchOverflow and loop

### ISSUE THREAD

**Issue by durchanek** [nolimits4web/swiper#2900]
When you have one image/element/slide, watchOverflow: true hides the navigation and pagination as expected. However, if you also have loop: true (because you want it to loop in instances where there is more than one slide), watchOverflow no longer has any effect. I guess the watchOverflow calculation isn't done before the additional/duplicate slides are inserted for the loop effect.

**Comment by nolimits4web** [comment]
Everything is correct, because with loop you have more than one slide. Just don't enable loop if you don't need it in this case

**Comment by durchanek** [comment]
Well, that is technically correct, but for example with only one slide, loop: true and slidesPerView: 3, I end up with 3 same slides, which is not what would the user expect, is it? It would be more practical to use the number of real slides for watchOverflow calculation, hide the navigation and do not generate the extra slides.
I am referring to the case when the number of slides is not known (e.g. they come from CMS) and slidesPerView changes with breakpoints.

**Comment by stevenleija** [comment]
This is a problem I am encountering.  Is there a way to configure the swiper so when in loop mode the navigation is checked and if the number of slides is less than visible slide viewport looping is not necessary?  The additional problem is when configured with loop mode and breakpoints that in a desktop mode navigation is not needed so no looping but when reduced to tablet then navigation is needed which would place it in loop mode as well.

**Comment by kireerik** [comment]
This is a duplicate of #2621. So I think we can keep this one closed.
