### ISSUE TITLE
manual window resize event is changing the active slide

### ISSUE THREAD

**Issue by ai-tushar** [nolimits4web/swiper#2901]
Hi there,
i am using this plugin for quiet sometimes now. loving this.
recently facing an issues which i am unable to resolve.
in my page, during some button click action i needed to trigger window resize event in an specific way,
that is, `window.dispatchEvent(new Event('resize'));`
but after this line has been executed every time, the slider active slide changes to index 0 (first slide). it does not trigger onSlideChangeEnd event, but just change the active slide to first slide.

this isn't normal. let me know how i can resolve it.

Thanks in advance.

**Comment by nolimits4web** [comment]
Would be good to see JSFiddle with the issue
