### ISSUE TITLE
coverflow effect has an error

### ISSUE THREAD

**Issue by z2014** [nolimits4web/swiper#2902]
This is a :
* [x] bug

* Swiper Version: 4.3.5.
* Platform/Target and Browser Versions: android, ios.

### What you did
when the page includes two swipers, and each of them has different speed, and they have same effect
`effect: coverflow`, so that is all.

### Expected Behavior
normal work

### Actual Behavior
but it is not true; the picture slide into the view getting a little Caton, the picture's size is scaling small

**Comment by z2014** [comment]
@nolimits4web can you give me a simple live href?so i can modify some config

**Comment by z2014** [comment]
[live demo](https://jsfiddle.net/1aLdz7ty/1/)
this is my code

**Comment by nolimits4web** [comment]
You have error in your code, here is correct https://jsfiddle.net/4epxwr9n/
