### ISSUE TITLE
Padding no longer taken into account

### ISSUE THREAD

**Issue by Davarov** [nolimits4web/swiper#2903]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.4.2.
* Platform/Target and Browser Versions: Chrome.
* JSFiddle: https://jsfiddle.net/2q7oyLrj/.

### What you did
Click the right button a few times and you'll notice the content will shift to the right.
When checking what happens I noticed the swiper-wrapper only shifted for a total value equal to the width and margin, it doesn't take padding width into account.
This works fine in 4.4.1.

### Expected Behavior
Translation takes margin, width and padding into account.

### Actual Behavior
Translation only takes margin and width into account.

**Comment by nolimits4web** [comment]
Like this https://jsfiddle.net/eb1fnc9g/ ?

**Comment by Davarov** [comment]
border-box is indeed a good work around but doesn't fix the underlying issue.
It only takes the width of the padding out of the equation.
