### ISSUE TITLE
npm build failure, looking for non-existent package on NPM registry

### ISSUE THREAD

**Issue by aeblin** [nolimits4web/swiper#2905]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.4.2
* Platform/Target and Browser Versions: Mac OSX 10.14.1

### What you did
`npm build` results in the following error.
```
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@3.3.6
```

### Expected Behavior
The build should complete, and shouldn't be using package links that don't resolve on the NPM Registry. The event-stream package lists https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz as its "resolved" parameter in the package-lock.json that is available when downloading. All the other packages are looking for event-stream 3.3.4, which does have a link that resolves on the NPM registry.

### Actual Behavior
The build does not complete, because the version of event-stream specified (3.3.6) does not have a .tgz available for download on the NPM registry.

**Comment by nolimits4web** [comment]
Fixed
