### ISSUE TITLE
Changing focus does not update translate

### ISSUE THREAD

**Issue by mattdemps** [nolimits4web/Swiper#291]
If focus changes through tabbing or through javascript and shifts the swiper, the translate value is not accurate causing the swiper to be offset by however much the focus shifted the content.

**Comment by ianespanto** [comment]
Same here. Translate does not seem to update after I resize the window with another tab.

![untitled-1](https://user-images.githubusercontent.com/5529280/28737274-9f410aa2-73a2-11e7-844f-3b4d09f16132.jpg)
