### ISSUE TITLE
Swiper brokes when resizing window

### ISSUE THREAD

**Issue by rgllm** [nolimits4web/swiper#2921]
### This is:

* [x] bug
* [ ] feature-discussion (RFC)
* [ ] enhancement

### Info

* Swiper Version: 4.4.5
* Platform/Target and Browser Versions: All, desktop
* Live Link or JSFiddle/Codepen or website with isssue: https://d.pr/v/3oDGYx (example video on demo site)

### What you did
1. Click on slide in desktop
2. Resizing window
3. Tried to swipe on the slider

### Actual Behavior
When resizing window, slide doesn't work properly. Seems a bit laggy.

**Comment by Eusen** [comment]
Maybe u should invoke instance.update(), when u resize window

**Comment by Eusen** [comment]
ok, update not work

**Comment by nolimits4web** [comment]
Nothing common with window resize. It happens because in emulation mode, other events are used, and swiper must be reinitialized. It is not the real usecase

**Comment by GlebGulin** [comment]
Any question. Sorry, but I have question about mobile adaptation fow swiper. So, in version 3.4.1 when width of windows is 485px, we have two columns. If these colums with for example Testimonials, then we have so long text. It's not beautifully. When width is 320px, we have one columns. I look at code, but algorithm so dificult. How can I do two columns for width 485px. Thank you for answer.
What I did. I added this: 
var swiper = new Swiper('.anyclass', {
 
                 slidesPerView: 3,
                 slidesPerGroup: 6,
                spaceBetween: 30,
                breakpointsInverse: true,
   // Responsive breakpoints
                 breakpoints: {
 //    when window width is <= 480px
                 480: {
                     slidesPerView: 1,
                    spaceBetween: 30,
  
                     },
                  }
             });
Ok. I can see one column in width 485px. But slides move only for half. Help please
