### ISSUE TITLE
noSwiping not work in latest version(4.4.5)

### ISSUE THREAD

**Issue by Eusen** [nolimits4web/swiper#2922]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.4.5
* Platform/Target and Browser Versions: CHROME
* Live Link or JSFiddle/Codepen or website with isssue: nop

### What you did
A simple recitation of this problem, It doesn't work whether noSwiping set to true or false.
You can try it with dome: 160-scroll-container.html

### Expected Behavior
I want to disable swiping on elements matched to class specified in 

### Actual Behavior
It's not work

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle

**Comment by Eusen** [comment]
I sent a video, you can watch it. 
[https://youtu.be/2GgZiw_Z190](https://youtu.be/2GgZiw_Z190)

**Comment by Eusen** [comment]
I think u forget add no-swiping-class for swiper-warpper

**Comment by Eusen** [comment]
mebay `swiper-container` doesn't have `swiper-no-swiping`
