### ISSUE TITLE
is it possible set different effect & interval for each slider?

### ISSUE THREAD

**Issue by terryzwt** [nolimits4web/swiper#2926]
For example, I have 3 slides, 
```
A: 3s, fade
B: 5s, coverflow
C: 10s, cube
```
I need control the play time and effect for each slide. After study the demo codes, I havn't find a way to finish this task.

So can swiper meet this requirement? 
Thanks in advanced for prompt response.

**Comment by joebentaylor1995** [comment]
No solution still @terryzwt ? Looks like ill be using another slider then it seems as the support is non-existant atm

**Comment by terryzwt** [comment]
@joebentaylor1995 finally I'm using https://jqueryui.com/effect/ to do that.

**Comment by terryzwt** [comment]
@joebentaylor1995 finally I'm using https://jqueryui.com/effect/ to do that.
