### ISSUE TITLE
Layout issue with scrollable slides introduced in version 4.4.2

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/swiper#2927]
Steps to reproduce this issue in the [Slideable Navigation Drawer demo](https://idangero.us/swiper/demos/430-slideable-menu.html):
Add extra content to the following slides and add `overflow: auto;` style properties here:
https://github.com/nolimits4web/swiper/blob/c6f92692d2643d41cf14638638b991b5cd41d1e2/demos/430-slideable-menu.html#L145-L146
So the slides are scrollable. You can see that the left slide is too wide since version `4.4.2` and it works as expected with version `4.4.1` and below.

**Comment by kireerik** [comment]
This is still an issue as of version `5.0.4`.

**Comment by nolimits4web** [comment]
@kireerik can't see anything like that. Please provide live example or JSFiddle with the issue

**Comment by kireerik** [comment]
@nolimits4web All right. I have created a JSFiddle (https://jsfiddle.net/evutyhbs) based on the [Slideable Navigation Drawer demo](https://swiperjs.com/demos/430-slideable-menu.html).

**Comment by nolimits4web** [comment]
Still don't get, what it is the issue? :) I see in JSFiddle that everything is fine

**Comment by kireerik** [comment]
I am also attaching a screenshot, so you can see the issue described here (https://github.com/nolimits4web/swiper/issues/2927#issue-393022104):

![image](https://user-images.githubusercontent.com/3628043/66077049-6cb58500-e55f-11e9-9543-50d982585e82.png)

**Comment by kireerik** [comment]
This is still an issue as of version (`5` and) `6.x`.

Expected behavior example (using version `4.4.1`): https://jsfiddle.net/pt73roya

Actual behavior example (using version `6.2.0`): https://jsfiddle.net/pt73roya/1

**Comment by kireerik** [comment]
@nolimits4web Can you see the difference here (https://github.com/nolimits4web/swiper/issues/2927#issuecomment-696882115)?

**Comment by kireerik** [comment]
@nolimits4web Can we reopen this issue or should I open a new one?

**Comment by nolimits4web** [comment]
@kireerik open new one with your examples
