### ISSUE TITLE
Swiper not working until I resize browser window

### ISSUE THREAD

**Issue by chinhkimhuynh** [nolimits4web/swiper#2928]
i using wrap-swiper. it incorrect working util i resize brower size. Has anyone else had this problem?. Please help me. thank

**Comment by cagcak** [comment]
Temporary fix might be: 

```
mySwiper = new Swiper('.swiper-container', {
	// ...
})
setTimeout(() => {
	mySwiper.update()
}, 500)
```

**Comment by vsarunov** [comment]
@cagcak Life saver.

**Comment by srikat** [comment]
Spent half an hour counting the number of hairs I pulled out while trying to resolve this issue.

Thanks @cagcak.

**Comment by ItsLeeOwen** [comment]
When you initialize swiper can be important, before or after CSS has been rendered.

https://github.com/nolimits4web/swiper/issues/2218#issuecomment-509683102
