### ISSUE TITLE
Slides are moved more than 1 slide

### ISSUE THREAD

**Issue by kriss145** [nolimits4web/swiper#2935]
Hi,

I have the latest Swiper on my website.

Problem:
Swiper has 10 thumbs (slides) when visible is 4. I would change slide always not more than 1. When I first-time swipe left then carousel moved more than 1 slide. Later is fine. The problem is the happen too when I would swipe right when we are on the last slide.

It is normal behaviour of this script? Is there maybe param to change it?

Thanks

**Comment by sonamgupta-kiwi** [comment]
I am facing the same issue .. is there any update ??
