### ISSUE TITLE
Swiper 4.x doesn't triggers the resize event when using the updateSize method

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/swiper#2937]

**Comment by kireerik** [comment]
Workaround:
```JavaScript
swiper.updateSize()
swiper.resize.resizeHandler()
```

Swiper version `3.x` equivalent:
```JavaScript
swiper.onResize()
```

I would probalby expect `swiper.updateSize()` to do what the workaround does.

**Comment by nolimits4web** [comment]
There is a `swiper.update()` for that

**Comment by kireerik** [comment]
In certain cases the `swiper.update()` doesn't works and the swiper container is not resized properly.

But now I tested thing again and the undocumented `swiper.resize.resizeHandler()` always works properly even without using `swiper.updateSize()`. `swiper.updateSize()` just like `swiper.update()` also doesn't works in certain cases.

**Comment by chengyinjie** [comment]
Vue, Swiper 4.5
I called swiper.update() after updating the bind data, but it had no effect.

**Comment by chengyinjie** [comment]
> Vue, Swiper 4.5
> I called swiper.update() after updating the bind data, but it had no effect.

figure out!
I called the update() in a Vue Watcher, when the bind data update, update() was called immediately. But the dom(Vue template) has not been updated yet.
