### ISSUE TITLE
Container sized inaccurately when using watchOverflow

### ISSUE THREAD

**Issue by kireerik** [nolimits4web/swiper#2938]
Swiper container sized inaccurately when `watchOverflow` is enabled and the controls are hidden on initialization.
It is also sized inaccurately when the window is resized and the controls are becoming hidden.

Workaround:
```JavaScript
var resize = function () {
	setTimeout(function () {
		if (slider.isLocked)
			slider.resize.resizeHandler()
	}, 0)
}
, isLockedPreviously = false
, slider = new Swiper('.swiper-container', {
	watchOverflow: true
	, on: {
		init: resize
		, resize: function () {
			if (!isLockedPreviously && swipeableSlider.isLocked)
				resize()

			isLockedPreviously = swipeableSlider.isLocked
		}
	}
})
```

Version: `4.x` (`4.4.6`)

**Comment by kireerik** [comment]
It is also sized inaccurately when the window is resized and the controls are becoming shown.

This is the updated workaround:
```JavaScript
var isLockedPreviously = false
, slider = new Swiper('.swiper-container', {
	watchOverflow: true
	, on: {
		init: function () {
			setTimeout(function () {
				if (swipeableSlider.isLocked)
					swipeableSlider.resize.resizeHandler()
			}, 0)
		}
		, resize: function () {
			if (!isLockedPreviously && swipeableSlider.isLocked || isLockedPreviously && !swipeableSlider.isLocked)
				setTimeout(function () {
					swipeableSlider.resize.resizeHandler()
				}, 0)

			isLockedPreviously = swipeableSlider.isLocked
		}
	}
})
```

**Comment by kireerik** [comment]
Simplified workaround:
```JavaScript
var isLockedPreviously = false
, slider = new Swiper('.swiper-container', {
	watchOverflow: true
	, on: {
		init: function () {
			if (this.isLocked)
				this.resize.resizeHandler()
		}
		, resize: function () {
			if (!isLockedPreviously && slider.isLocked || isLockedPreviously && !slider.isLocked)
				setTimeout(function () {
					slider.resize.resizeHandler()
				}, 0)

			isLockedPreviously = slider.isLocked
		}
	}
})
```

**Comment by kireerik** [comment]
This issue seems to be "resolved" by version `5.x` or the behavior of this feature was altered (without mentioning it in the change log).

`5.x` introduces another issue which can be related to the behavior of `watchOverflow`, `slidesPerView` (`'auto'` as well) and possibly even to `breakpoints`.

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle with the issue

**Comment by kireerik** [comment]
I am closing this for now since I can not reproduce the originally reported issue with version `5.x`.

I will investigate and create an issue for the new issues I noticed related to this once #2927 is resolved.
