### ISSUE TITLE
SlideToClickedSlide not always triggering

### ISSUE THREAD

**Issue by ENKl** [nolimits4web/swiper#2941]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.2
* Platform/Target and Browser Versions: Windows on Chrome, MacOS on Chrome

### What you did

````
{
        speed: 1000,
        slidesPerView: 5,
        spaceBetween: 20,
        centeredSlides: true,
        slideToClickedSlide: true,
        initialSlide: 3,
        longSwipes: false,
        shortSwipes: false,
        resistance: false,
        allowTouchMove: false,

        breakpoints: {
            1420: {
                slidesPerView: 3,
            },

            565: {
                slidesPerView: 2,
            },

            400: {
                slidesPerView: 1,
            }
        },
 }
````

### Expected Behavior
When trying to click to the next slide by clicking on the slide the clicked slide should become active.

### Actual Behavior
When trying to click to the next slide (by clicking on the slide) it doesn't always trigger, sometimes you need to click 2-3 times before it does. This seems to be worse on Mac (made me think it was a magic mouse issue but happens too on windows)

Before you open an issue, please check if a similar issue already exists or has been closed before.
I could not find this exact issue logged.

**Comment by ynamite** [comment]
Issue is still present ... yawn

**Comment by nickensoul** [comment]
caused this on last project, it still happens

**Comment by b851TYiytNCk** [comment]
2022 - still present issue
