### ISSUE TITLE
 Push the next button and the image goes in reverse

### ISSUE THREAD

**Issue by SakiOaku** [nolimits4web/swiper#2943]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions:  Windows on Chrome, MacOS on Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://www.goodrooms.jp/detail/001/1000178377/?transit_area=203

### What you did
```
var swiper = new Swiper ('.swiper-container', {
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    loop: true,
    speed: 650
  });
```

### Expected Behavior
When the next button is pushed, always the next image is displayed.

### Actual Behavior
When buttons are pushed, *sometimes* the image goes in reverse.

There are conditions that tend to cause this phenomenon.
- When next button and prev button are pressed twice at once again and again.
- You use a mouse to push buttons.
- `loop: true`

The same thing happened on other sites.
example: https://xn--web-oi9du9bc8tgu2a.com/js-swiper-sample/

**Comment by nolimits4web** [comment]
Guess same as #2953
