### ISSUE TITLE
Slider not scrolled to active thumbnail if it visible, but not entirely

### ISSUE THREAD

**Issue by kachurun** [nolimits4web/swiper#2947]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.6

### What you did
If part of the preview is visible, then when you go to this preview (by clicking on the preview or otherwise), the preview is not shown completely. 

It may be reproduced in default demo (http://idangero.us/swiper/demos/300-thumbs-gallery.html) if  you move thumbs to left (50px or more) and then move to slide №5
Screenshot: https://imgur.com/a/yp8MZYw

### Expected Behavior
Previews should be scrolled so that the active element is fully visible.

I think problem in `watchSlidesVisibility` option which thinks that the slide is visible if at least 1px on the screen. May be need `watchSlidesVisibilityFull` or similar option?

**Comment by QJan84** [comment]
`watchSlidesVisibilityFull ` this would ne great!

**Comment by SiCoUK** [comment]
I realise this old but I have just run into the same issue, has anyone worked out how to do it?

I believe johnlewis.com use swiper and they don't appear to have this issue.

**Comment by rameshsth08** [comment]
I also have a same issue, do you guys get any solutions for it?
