### ISSUE TITLE
ios slideTo from click event issue

### ISSUE THREAD

**Issue by sante85** [nolimits4web/swiper#2952]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.46
* Platform/Target and Browser Versions:  IOS 12.x
* Live Link or JSFiddle/Codepen or website with isssue: 

### What you did
i have a button then click i call slideTo(number)

### Expected Behavior
click go to slide

### Actual Behavior
click in first time is right, in next not run right

https://jsfiddle.net/m1k2xtnq/2/

**Comment by yourcharlie23** [comment]
bumped still problem in iOS 12 and below.
