### ISSUE TITLE
will get wrong img index, when fast click pre-button & next-botton

### ISSUE THREAD

**Issue by SunXinFei** [nolimits4web/swiper#2953]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

you will get this issue in http://idangero.us/swiper/demos/  or see the video
http://img.sunxinfei.com/QQ20190122-121838-HD.mp4
this bug is when click pre or next button quickly , will get the wrong img index.

**Comment by sante85** [comment]
+1

**Comment by nolimits4web** [comment]
Discussed here numerous times, when you tap quickly you accidentally do a quick swipe. It is configurable via parameters
