### ISSUE TITLE
speed of undefined: slideTo()

### ISSUE THREAD

**Issue by cagcak** [nolimits4web/swiper#2959]
In documentation, it says speed parameter optional but when I don't assign a value, I get error as follows 

```
Uncaught TypeError: Cannot read property 'speed' of undefined
    at Swiper.slideTo (swiper.min.js:1971)
```

for the caller code-block: 

`MySwiper.slideTo(MySwiper.slides.length)`

Here is the docs argument:

![screenshot from 2019-01-28 15-12-48](https://user-images.githubusercontent.com/1567108/51835970-03b2a900-2310-11e9-940c-5933dfbdcbd8.png)

ref: http://idangero.us/swiper/api/#events

**Comment by nolimits4web** [comment]
http://idangero.us/swiper/demos/010-default.html

Run in console:
```
swiper.slideTo(swiper.slides.length)
```

You won't see any issues
