### ISSUE TITLE
swiper has wrong direction when clicks on slide

### ISSUE THREAD

**Issue by dimidrola** [nolimits4web/swiper#2965]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version:  4.4.6.
* Platform/Target and Browser Versions: Windows 10, Chrome (71).
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/dimidrola/pen/aXVRzW?editors=0010.

I have looped swiper gallery, with slideToClickedSlide, when i try tap or click on right from centered slides all is fine, but when i clicks on left from centered slides, some times slider have wrong direction

### Expected Behavior
slider swipes to the left slide

### Actual Behavior
slider swipes to the right not actual clicked slide

**Comment by dimidrola** [comment]
the problem in loopFix `if (activeIndex < loopedSlides) {...`
in situation when we have real index (for example 0) and actual index is 7 too, and when i tap on real index 4 swiper slides to 11, as i understand swiper should update loop but don't do this

**Comment by jesperlandberg** [comment]
Also having this issue, is there any fix/temporary fix to this yet?

**Comment by migueltrias** [comment]
Also having this issue... 
Seems to happen randomly.
Any workaround to fix it?

**Comment by udidol** [comment]
+1

**Comment by liamsnowdon** [comment]
You can see this behaviour on the homepage, for the "Build Complex Touch Galleries" example, but as @migueltrias said, it seems quite random. http://idangero.us/swiper/

**Comment by liamsnowdon** [comment]
The fix that worked for me was setting `threshold: 5` or whatever your sweet spot is, it just needed to be greater than 0, which is the default. It seems that if you move the mouse (or your finger I guess) even by 1px at the same time you click, it registers a swipe instead so it goes the other direction. I found this here: https://github.com/nolimits4web/swiper/issues/3167#issuecomment-520947900

**Comment by robpop** [comment]
@dimidrola Take a look at my pull request #3126 which is for a separate issue, I think that may fix this. Let me know.

**Comment by robpop** [comment]
@dimidrola I'll take a look at this. I think this is also a bug when using navigation arrows.

**Comment by robpop** [comment]
So this has to do with the ```onTouchEnd``` event when it checks ```timeDiff > params.longSwipesMs```.  As @liamsnowdon mentioned, the click is being registered as a short swipe because you're clicking after moving your cursor. This could have to do with how the ```onTouchMove``` event is continuously fired whenever your cursor moves. 

Best way to fix this is to follow the advice shown at https://github.com/nolimits4web/swiper/issues/3167#issuecomment-520947900

**Comment by nicklocicero** [comment]
It was a problem for me today, but adding threshold: 5 fixed it...
