### ISSUE TITLE
DOMAIN EXPIRED

### ISSUE THREAD

**Issue by ENKl** [nolimits4web/swiper#2971]
Hey, your domain has expired 😭

**Comment by nickhempsey** [comment]
I had just clicked on API to look something up.... :(

**Comment by ENKl** [comment]
Here's the online cached version: http://webcache.googleusercontent.com/search?q=cache:http://idangero.us/swiper/api/&strip=1&vwsrc=0 

Here's a screenshot of the cached version of the API incase google caches the parked domain: 

![webcache googleusercontent com_search_q cache_http___idangero us_swiper_api_ strip 1 vwsrc 0](https://user-images.githubusercontent.com/43470594/52421386-d625e680-2aeb-11e9-8e0c-cfa3f17e3f97.png)

You can probably gulp the website too from the other repo

**Comment by nolimits4web** [comment]
Already renewed, will be live soon. Until website repo with all docs, as always, available here https://github.com/nolimits4web/swiper-website
