### ISSUE TITLE
Carousel no longer works if it has a parent div

### ISSUE THREAD

**Issue by marbuser** [nolimits4web/swiper#2972]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.6
* Platform/Target and Browser Versions: macOS, Chrome, VueJS
* Live Link or JSFiddle/Codepen or website with isssue: CODE: https://codesandbox.io/s/0ook5pwn5w FULL PREVIEW: https://0ook5pwn5w.codesandbox.io/

### What you did
As shown in the code linked above inside `App.vue`, if you add a div tag around `.swiper-container`, it causing the width of the carousel to just break and causes various other bugs. If you remove that `div` tag that is around the carousel and remove the h1 tag, you will notice the carousel fixes itself and works as intended.

This is incredibly inconvenient especially if you are using something like flexbox to group elements together (Like shown in my example.)

### Expected Behavior
I'm not great at explaining so I'll let this image I made up explain what the expected behaviour SHOULD be.
Essentially, the carousel should shrink the contents as well as its own width to the max width of its container instead of going out of it like in the code example.

![image](https://user-images.githubusercontent.com/34422459/52467466-9bda4900-2bc0-11e9-9183-841a52aa462e.png)

### Actual Behavior
View code above.

Just to clarify, you can "fix" this by setting a max width on the parent, but you'd literally need to do this FOR EVERY SINGLE SITUATION, and generally this isn't very intuitive. 
As the viewport shrinks, so should the carousel.

**Comment by nolimits4web** [comment]
Swiper container needs size that can be determined, this is how CSS works in general
