### ISSUE TITLE
Slide animation doesn't work well on iOS

### ISSUE THREAD

**Issue by jack-sf** [nolimits4web/swiper#2974]
On Chrome on iPhone 7 the slide animation looks very bad. It can be reproduced on current SwiperJS webpage ( http://idangero.us/swiper/demos/ ). It can't be reproduced on desktop browsers or on Safari on iPhone. (This is only-iOS only-Chrome bug.)

Video: https://photos.app.goo.gl/4ptfxbAv24WHENAT9

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Anybody met this issue as well? Any idea what causes it, and if this can be fixed?

**Comment by garrettmaring** [comment]
Which iOS version is the iPhone 7 running? And maybe what version of the Chrome app as well.

I've tested that it works correctly on iPhone X running iOS 12.1.4 and Chrome app 72.0.3626.74.

**Comment by jack-sf** [comment]
Just woke up and tried again. Now can't repeat it anymore. Mhm, strange.

Sorry for trouble then. Let's close it for now, until it happens again.

**Comment by rcobiella** [comment]
Sorry for re-opening. This also happens to me every once in a while, then it stops, and after some time it happens again. It's been like this for the last couple of months, before and after updating to iOS12, and only on Chrome.
