### ISSUE TITLE
Parallax is still applied even when `parallax` is set to false

### ISSUE THREAD

**Issue by garrettmaring** [nolimits4web/swiper#2979]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.6
* Platform/Target and Browser Versions: macOS

### What you did
Applied parallax `data-swiper-parallax-x` to an element yet set parallax to false when initializing swiper.

### Expected Behavior
Parallax is not applied.

### Actual Behavior
Parallax is applied.

**Comment by sethwhitaker** [comment]
Im also experiencing this. I am attempting to have 2 different configurations for desktop & mobile (need to change more than can be configured in the breakpoints object) so I have a media query listener setup to destroy the swiper and re-init a new one, whenever I start as a desktop width swiper and resize down to mobile, the re-init keeps the parallax on even though I have `parallax: false` in the mobile config.
