### ISSUE TITLE
Add `slideChangeEnd` event (RFC)

### ISSUE THREAD

**Issue by garrettmaring** [nolimits4web/swiper#2980]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.6

**Abstract**

There is a need to detect when a new slide has been completely presented to a user.

There are currently two useful events for detecting whether a slide has changed `slideChange` and `slideChangeTransitionEnd`.

`slideChange` is called when the active slide changes. By Swiper's internal usage, the active slide changes halfway through the swipe when the majority of the next/previous slide is visible. Because of this `slideChange` is called mid-transition & mid-swipe.

`slideChangeTransitionEnd` is called when the transition to a changed slide is ended. This is more useful for detecting a complete transition to a new slide but isn't fully accurate. If a user "flicks" to the next slide yet catches the swiper before the animation completes, `slideChangeTransitionEnd` will be fired since the transition was interrupted. Therefore, `slideChangeTransitionEnd` cannot be used to detect whether a full new slide has been presented to the user.

**Comment by garrettmaring** [comment]
Just FYI @nolimits4web I still think this is a good issue to tackle! Stale bot is a grump.

**Comment by prakhar-parashar-au7** [comment]
This issue should get some light. Major missing in swiperjs events.
