### ISSUE TITLE
height issue in every major browser if window width is less than 1024px

### ISSUE THREAD

**Issue by Lacika1981** [nolimits4web/swiper#2986]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: latest version
* Platform/Target and Browser Versions: macOS, Chrome, Firefox, Safari

### Expected Behavior
Vertical slide, full screen slides

### Actual Behavior
If the window width is less than 1024px than each slides height is half of the actual window height
I.e.: 1000px * 500px -> each slide height is only 250px.

**Comment by nolimits4web** [comment]
Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by Lacika1981** [comment]
The problem was on my side. I am sorry to open this case.
