### ISSUE TITLE
Hero Slider - ADA - The screen reader should only be reading the current slide content and only jump to other slides if the user goes to previous/next slide first. Currently, it reads all slides even if the slide is not in view

### ISSUE THREAD

**Issue by shahjehanali1** [nolimits4web/swiper#2989]
See video demonstration. The screen reader should only be reading contents within the slide that is active unless they go to the next/previous slide.
 
Testing URL: https://mosaic.dev.laneterralever.com/
 
In this video, you can see the screen reader goes off screen or advances the slider without clicking next or previous arrows or any of the dots. This can be confusing to a user who is just trying to read the slide they initially selected.
 
https://www.screencast.com/t/CkCiwRKRK

**Comment by florgb02** [comment]
Hi [shahjehanali1](https://github.com/shahjehanali1) any solution on this. I am facing the same issue. 
Thanks
