### ISSUE TITLE
Errors on use thumbnail (change, click)

### ISSUE THREAD

**Issue by MartDSam** [nolimits4web/swiper#2990]
I have 2 sliders, 1 for the thumbnails and the other for the larger images.

When I click on the thumbnail to change the larger image some errors are happening. Errors do not occur at the same time, sometimes one, sometimes another.

1 - I click on the thumbnail and this error happens:
Cannot read property 'indexOf' of undefined

In addition, the thumbnail is "glued" to the mouse pointer, with and if you are dragging with your finger on the phone.

2 - I click on a thumbnail, but it does not become active. The active class continues in the previously clicked thumbnail.

3 - Sometimes the swiper-slide-thumb-active class changes to the active slide, but the swiper-slide-active class remains on the previous slide.

4 - The clicks are not fluent, I often click on the thumbnail and nothing happens, it seems that it does not identify the click. Sometimes I click more than once or twice for him to identify.

5 - It often looks like the thumbnail only changes if I double-click.

Here demo: [Code pen demo](https://codepen.io/Haisan/pen/wNbNQm)

**Comment by efor74** [comment]
Решил попробовать перейти на этот слайдер, раньше использовал Slick, но на первом же проекте возникла та же проблема :(
Тормознул пока этот процесс.

**Comment by nolimits4web** [comment]
Fixed by #3020
