### ISSUE TITLE
Height is miscalculated on IE11 when using <picture>

### ISSUE THREAD

**Issue by bpeab** [nolimits4web/swiper#2994]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.1
* Platform/Target and Browser Versions: Internet Explorer 11

### What you did
We've been using Swiper with the simplest use case possible. The one's causing problems is when slides contains the `<picture>` with multiples `<source>` and an `<img>` as fallback.

### Expected Behavior
Swiper should be calculating the height based on the actual targeted `<source>` of the viewport. 

### Actual Behavior
Swiper is calculating the slides height based on the `<img>` fallback element which isn't the expected behavior. Since the `<img>` has an mobile-optimized image, Swiper leaves us with an extra space on desktop-size viewports. 

The `<picture>` element is polyfilled correctly for IE and imported at the top of our entry point (webpack) so the problem isn't with our bundle.

This issue seems similar to #1899 and #1878 but only appears on Internet Explorer 11 in our case. The bug result in exactly the same as in the #1899 screenshot.

**Comment by bpeab** [comment]
If someone else has this issue, here's the workaround I used to resolve it. 

For some reason, Picturefill doesn't have the time to do it's magic before Swiper is initialised. So, before initialising Swiper, I'll do the following check:

```js
if (!!window.HTMLPictureElement) {
    this._swiper.init();
} else {
    setTimeout(() => {
        this._swiper.init();
    }, 50);
}
```

I don't consider this chunk of code being the right way to do it but it'll do the job in the meanwhile. If somebody have a better solution, I'll be happy to discuss about it.

**Comment by nolimits4web** [comment]
Closing as since v5 IE is not supported anymore
