### ISSUE TITLE
Pinch zoom on image always zooms in to centre of the image

### ISSUE THREAD

**Issue by rajkumar-osm** [nolimits4web/swiper#2998]
* [x] bug

* Swiper Version: 4.4.1
* Platform/Target and Browser Versions: ANDROID, IOS
* Codepen: [https://codepen.io/Recai/full/YGrbVG](https://codepen.io/Recai/full/YGrbVG)

### What you did
Initialised the swiper with zoom enabled. 

### Expected Behavior
Pinch zoom on an image should zoom in the area where I was trying to pinch.

### Actual Behavior
No matter where I pinch in, it always zooms in towards the centre of the image.

### **Codepen**
[https://codepen.io/Recai/full/YGrbVG](https://codepen.io/Recai/full/YGrbVG)

Open this codepen in Chrome on Android or Safari on iOS, try to zoom in the picture by pinching, you will notice that it always zooms in towards the centre of the image no matter where you would like to zoom in.

**Comment by philip-firstorder** [comment]
This needs to be reopened and solved, I get it using the official zoom demo too.
