### ISSUE TITLE
swiper and fancybox3 - bug with slidesPerView="auto" - lost navigation buttons

### ISSUE THREAD

**Issue by vollyimnetz** [nolimits4web/swiper#3000]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0 (and previous versions), Fancybox 3.5.6
* Tested in Win Chrome, Win Firefox
* https://jsfiddle.net/volly_imnetz/4aj51ehf/14/

### What you did
I added linked images to the swiper slider. On click the images will be open in an fancybox-lightbox-group. When i move through the fancybox group some items (4-5 items) and then close the lightbox, the swiper navigation buttons disapear.

### Expected Behavior
The swiper navigation buttons are still visible after the fancybox close. The swiper do not need to update its position. The swiper should be fully functional.

### Actual Behavior
The swiper updates the slide-position. After that the **.swiper-wraper** seems to not work correctly (no visible hight-width when inspected in chrome dev). The navigation buttons are not visible. The slider do not work as intended (touch wont work correct).

**Comment by fancyapps** [comment]
Hi,

fancybox places focus back on corresponding trigger element after closing the instance (for accessibility) by default, but that can cause problems with sliders like swiper. So, try disabling that feature like this:

 ```JS
$('[data-fancybox="group1"]').fancybox({
    backFocus : false
});
```

**Comment by vollyimnetz** [comment]
@fancyapps thank you very much for the support. Worked perfect.
