### ISSUE TITLE
Reset nested swiper to index

### ISSUE THREAD

**Issue by koenpopma** [nolimits4web/swiper#3001]
While using the "parent" swiper, I would like to reset the "child" (`nested`) swiper to index = 0, on the non-current parent swiper.
Using `ChildSwiper.slideTo(0)` gives `TypeError: ChildSwiper.slideTo is not a function`

Simplified visiual idea:
```
.parent (reset index = 0)
  .child
  .child
  .child
.parent.active (triggers other parents to reset)
  .child
  .child
  .child
  .child
.parent (reset index = 0)
  .child
  .child
```

In the script below I am not even targeting the "non-current" ChildSwiper.

```
$(function(){

var ParentSwiper = new Swiper('.parent-swiper, {
	direction:		'horizontal',
	// ... interaction settings,
	on: {
		transitionEnd:	function(){
			console.log('ParentSwiper: transitionEnd @'+ParentSwiper.activeIndex);
			// reset all children
			ChildSwiper.slideTo(0);

 			// this function works, it pushes the parent to 0, but not the child..
 			// ParentSwiper.slideTo(0);
		}
	},
});


var ChildSwiper = new Swiper('.child-swiper, {
	direction:		'vertical',
	// ... interaction settings,
});

});
```
I even tried to init the ChildSwiper before the ParentSwiper, but no success...

**Comment by crystalenka** [comment]
+1 on this, I'm trying to figure out the exact same thing and getting an error as well. I tried defining the `ChildSwiper` var before the `ParentSwiper` in case it was an undefined variable problem, and it still gets the same error.

@koenpopma, did you find a solution?

**Comment by crystalenka** [comment]
I figured it out! See my solution with comments below:

`/* child slider (multiple instances) - vertical */

    childSwiper = []; 

// if you don't use var, it sets it as a global variable
// I'm iterating through each parent slide element so that I can target specific instances of the child swiper, below

    $(".parent-slide").each(function(index, element){  
        var $this = $(this);
        childSwiper.push(new Swiper(this, {
            // Optional parameters
            direction: 'vertical',
            // ...interaction settings
            
            on: {
                // ... some methods called
            },
        }));
    });

    /* parent slider - horizontal, single instance */

// again, don't use var, and the swiper becomes a global variable

    parentSwiper = new Swiper('#all-projects', {
        // Optional parameters
        direction: 'horizontal',
        // ... interaction settings
        on: {
            slideChangeTransitionEnd: function() {
                childSwiper[parentSwiper.previousIndex].slideTo(0, 0, true);
            },
        }
    });
`

I hope this helps you and anyone else who may need this!
