### ISSUE TITLE
edgeSwipeDetection - win.screen.width incorrect

### ISSUE THREAD

**Issue by Ralpharoo** [nolimits4web/swiper#3003]
This is a (multiple allowed):
* [x] bug

* Swiper Version: <=4.5.0
* Platform/Target and Browser Versions: iOS 12.3

### Actual Behavior
Using `edgeSwipeDetection: true` on iOS 12 (and presumably others) often incorrectly blocks the Swiper touches when viewed on real devices in landscape.

The `win.screen.width` parameter is not updated according to screen orientation. This remains the device's actual height and width as if it were in portrait.

This is then incorrectly assessed here;
>var edgeSwipeDetection = params.edgeSwipeDetection || params.iOSEdgeSwipeDetection;
>var edgeSwipeThreshold = params.edgeSwipeThreshold || params.iOSEdgeSwipeThreshold;
>    if (
>      edgeSwipeDetection
>      && ((startX <= edgeSwipeThreshold)
>      || (startX >= win.screen.width - edgeSwipeThreshold)) **<!-- This is often true in landscape as screen.width === actual height**
>    ) {
>      return;
>}

This post outlines the inconsistencies across devices/browsers of this behavior; [https://stackoverflow.com/questions/1649086/detect-rotation-of-android-phone-in-the-browser-with-javascript/6603537#6603537](https://stackoverflow.com/questions/1649086/detect-rotation-of-android-phone-in-the-browser-with-javascript/6603537#6603537)

Seems to be a few options including;
- Checking `win.orientation` and selecting `screen.width` or `screen.height` accordingly (-90, 90)
- Using `win.innerWidth`

Note: I've used the latter to patch this for now and this seems to be working perfectly for our tests. 
 
Cheers,

**Comment by DavidWiesner** [comment]
I have the same issue but never found the cause. Thx

**Comment by Ralpharoo** [comment]
@nolimits4web - FYI, this is still an issue with version 4.5.1 and seen on iOS 12 and 13

**Comment by Ralpharoo** [comment]
This is still a problem and now lives [here on line 2830](https://github.com/nolimits4web/swiper/blob/2ab084e5742893d576e13507b92ab48385584c86/package/js/swiper.js#L2830) which can be changed to;

`|| (startX >= win.innerWidth - edgeSwipeThreshold)) // innerWidth is updated with orientation changes & multitasking, screen.width on iOS is always the static screen width`

**Comment by DavidWiesner** [comment]
This is still not solved in the latest version

**Comment by Hirbod** [comment]
@nolimits4web
