### ISSUE TITLE
Active class is not added when using Virtual Slides and Vue.js

### ISSUE THREAD

**Issue by randomobject** [nolimits4web/swiper#3004]
I'm using swiper in a Vue.js SPA and when use the Virtual Slides, pretty much as per the documentation, the active slide class is not added.

**Comment by randomobject** [comment]
Is there a way to fix this? It's driving me insane.

**Comment by alejandroiglesias** [comment]
I was wondering the same thing. And it's not specified anywhere in the docs that when using `renderExternal` you need to take care of setting the active class, but it seems you need to.

**Comment by raphaelnoguier** [comment]
Hey, I'm facing the same issue ... Do you guys have an idea ? 

Thanks

**Comment by ctwhome** [comment]
same here

**Comment by vltansky** [comment]
@randomobject you have now an official Swiper Vue component. I guess the issue can be closed, right?
