### ISSUE TITLE
Parameters watchOverflow and slidesOffsetBefore/slidesOffsetAfter don't work together

### ISSUE THREAD

**Issue by brandonce** [nolimits4web/swiper#3005]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: macOS Chrome
* Live Link or JSFiddle/Codepen or website with issue: https://jsfiddle.net/rcug4j1w/ (adapted from swiper demo for Freemode)

### What you did
Freemode swiper with watchOverflow set to true, and slidesOffsetBefore/slidesOffsetAfter set to any number

### Expected Behavior
Swiper should lock scrolling when all slides PLUS the before/after offset space are fully visible

### Actual Behavior
Swiper doesn't lock scrolling, even if viewport is wide enough to fit everything in view. I think that if slidesOffsetBefore/slidesOffsetAfter are set, the before/after offset pixels just need to be factored into the visible width when checking for overflow?

**Comment by Maxklebe** [comment]
Any progress on this? Facing the same issue without freemode.
https://codepen.io/m11x/pen/OeaGpP

**Comment by robpop** [comment]
@brandonce to be clear before I work on this, if you set ```slidesOffsetBefore``` and ```slidesOffsetAfter``` to 0, you'd get your desired behavior?

**Comment by Maxklebe** [comment]
@robpop Not trying to steal the thread here but yes, setting those values to 0 makes the horizontal scroll locked.

https://jsfiddle.net/kqt5gLw1/ (original fiddle with values set to 0)

**Comment by robpop** [comment]
@brandonce @Maxklebe checkout #3291 and let me know if that works for you.
