### ISSUE TITLE
How to disable or enable navigation on responsive breakpoints

### ISSUE THREAD

**Issue by rajuahammadfanz** [nolimits4web/swiper#3006]
Hello,
How to disable or enable navigation on responsive breakpoints?

Thanks

**Comment by randomobject** [comment]
I hide the controls on the required breakpoints using CSS or it might work to pass an empty param on the breakpoints in js:

`        navigation: {
          nextEl: '',
          prevEl: '',
        },`

**Comment by rajuahammad98** [comment]
> I hide the controls on the required breakpoints using CSS or it might work to pass an empty param on the breakpoints in js:
> 
> ` navigation: { nextEl: '', prevEl: '', },`

**Comment by ahmadrz1379** [comment]
breakpoints: {
      300: {
        navigation: false,
      },
    }, 
    this code its not working
