### ISSUE TITLE
Barbajs and events trigger

### ISSUE THREAD

**Issue by tedc** [nolimits4web/swiper#3007]
Hi, I'm working with Barbajs and Swiper and I'm having some problems with the event trigger. 
On 'newPageReady', I destroy all the sliders and recreate all the sliders. The problem is that every swiper related events, such as 'slideChangeTransitionStart' or 'slideChange', is triggering as mush as I change page (ie. if I leave and come back to the home page 4 times, the related slider trigger his events 4 times). How can I fix that?

**Comment by smallio** [comment]
@tedc 

I put all my scripts in a function & reinit them all together like so.

`Barba.Dispatcher.on('transitionCompleted', function(currentStatus, oldStatus, container) {
    reInitializeScripts();
});`

Speaking of barba... have you managed to get pagination working and if so how? Can't get swiper & pagination working at ALL in barba & it's killing me.
