### ISSUE TITLE
Pagination from default to dynamic is not refreshing correctly on breakpoint

### ISSUE THREAD

**Issue by marcosalatin** [nolimits4web/swiper#3013]
### This is a:
* [x] bug

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: All
* Code: 

```
var swiper_settings = {
  slidesPerView: 4,
  slidesPerGroup: 4,
  spaceBetween: 40,
  loop: false,
  speed: 500,
  simulateTouch: false,
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },
  pagination: {
    el: '.swiper-pagination',
    type: 'bullets',
    clickable: true,
  },
  breakpoints: {
    540: {
      slidesPerView: 1,
      slidesPerGroup: 1,
      spaceBetween: 30,
      pagination: {
        dynamicBullets: true,
        dynamicMainBullets: 8,
        clickable: false,
      }
    },

    640: {
      slidesPerView: 2,
      slidesPerGroup: 2,
      spaceBetween: 30,
      pagination: {
        dynamicBullets: true,
        dynamicMainBullets: 8,
      }
    },

    768: {
      slidesPerView: 2,
      slidesPerGroup: 2,
      spaceBetween: 40,
      pagination: {
        dynamicBullets: false,
      }
    },

    900: {
      slidesPerView: 3,
      slidesPerGroup: 3,
      spaceBetween: 30,
      pagination: {
        dynamicBullets: false,
      }
    },

    1024: {
      slidesPerView: 3,
      slidesPerGroup: 3,
      spaceBetween: 40,
      pagination: {
        dynamicBullets: false,
      }
    },

    1280: {
      slidesPerView: 4,
      slidesPerGroup: 4,
      spaceBetween: 30,
      pagination: {
        dynamicBullets: false,
      }
    }

  }
}

var mySwiper = new Swiper('.swiper-container', swiper_settings);
```

### What you did
I've tried various functions available like mySwiper.destroy(), then setting a new instance, mySwiper.update, both on resize/orientation change event, but neither of these are working.

### Expected Behavior
When you hit breakpoints 540 or 640 on window resize (on mobile devices orientation changes also) the pagination should "refresh", then get correct positioning, style and number of bullets should apply from default pagination to dynamic and vice versa.

### Actual Behavior
<img width="453" alt="after-breakpoint-hit" src="https://user-images.githubusercontent.com/12809514/54421956-c6fb0f80-470d-11e9-87b2-9b941361d945.png">
<img width="624" alt="before-breakpoint-hit" src="https://user-images.githubusercontent.com/12809514/54421957-c6fb0f80-470d-11e9-983f-930ae12b7138.png">

Pagination is keeping the settings/styles from previous breakpoint and aren't dynamic and same situation if you resize from small to bigger. Pagination is correct when you refresh browser, but that is not correct behavior.

**Comment by wkoehn** [comment]
Any news on this? I'm seeing the same issue.

**Comment by smartfox87** [comment]
there is a solution problemy? I'm seeing the same issue.
 * Swiper 5.3.8

samle codepen
https://codepen.io/smartfox87/pen/yLewmJK

Video Sample
https://take.ms/2Qv3f

**Comment by smartfox87** [comment]
I found a solution

breakpoints: {
	320: {
		slidesPerView: 1,
		slidesPerGroup: 1,
		pagination: {
			dynamicBullets: true,
			dynamicMainBullets: 7,
		},
	},
	430: {
		slidesPerView: 2,
		slidesPerGroup: 2,
		pagination: {
			dynamicBullets: false,
		},
	},
},
on: {
	breakpoint: function (swiper) {
		if (swiper.params.pagination.dynamicBullets) {
			swiper.pagination.init()
		} else {
			setTimeout(function () {
				swiper.pagination.el.style.width = '100%'
				swiper.pagination.el.classList.remove('swiper-pagination-bullets-dynamic')
			})
		}
	},
}
