### ISSUE TITLE
Pagination Bullet Event not sliding to correct slide

### ISSUE THREAD

**Issue by adshodgson** [nolimits4web/swiper#3015]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Latest
* Platform/Target and Browser Versions: Mac Chrome 73
* Live Link or JSFiddle/Codepen or website with isssue: See below for mp4

### What you did
I went on the Demos page to the 'Custom Pagination' section
(https://idangero.us/swiper/demos/)

Chrome 73.0

### Expected Behavior
The Pagination bullets should slide you to the correct slide.

### Actual Behavior

I started to tap on the bullet pagination icons to slide to the next and previous slides. Sometimes the slider would slide correctly and sometimes it would slide to the incorrect slide. 
I am experiencing this issue on my own project also, so thought that showing the version which is on the Demo's page would be a good indicator that the problem exists.

I have attached a zip/mp4 of the bug.

[SwiperJSPaginationBug.mp4.zip](https://github.com/nolimits4web/swiper/files/2978123/SwiperJSPaginationBug.mp4.zip)

Gif example also. (Chrome 73.0)

![ezgif-4-1c3173b9be6f](https://user-images.githubusercontent.com/47153371/54531456-3dea0f80-497d-11e9-8b6a-7ecba5136892.gif)

**Comment by RusyiOleh** [comment]
Yeap. And slideTo() method works the same. From time to time it slides to a wrong slide. The plugin looks great, good functionality, but this bug is crucial.

**Comment by athrunsun** [comment]
To me this also happens on Chrome 73 on Mac, but never happens on Chrome on Win10. Why?

**Comment by jmjunod** [comment]
Also see https://github.com/nolimits4web/swiper/issues/3036
