### ISSUE TITLE
Uncaught TypeError: Cannot read property 'swiper' of undefined

### ISSUE THREAD

**Issue by sheldonrobinson** [nolimits4web/swiper#3022]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: All platforms

### What happens
Uncaught TypeError: Cannot read property 'swiper' of undefined
    at Swiper.slideChange (swiper.js:8051)
    at swiper.js:1123
    at Array.forEach (<anonymous>)
    at swiper.js:1122
    at Array.forEach (<anonymous>)
    at Swiper.emit (swiper.js:1116)
    at Swiper.updateActiveIndex (swiper.js:1787)
    at Swiper.slideTo (swiper.js:2072)
    at Swiper.slideNext (swiper.js:2126)
    at swiper.js:7268

### Expected
Should check for object before calling property

### Fix for swiper.js
Add check for swiper.thumbs
````
8051c8051
<         if (!swiper.thumbs.swiper) { return; }
---
>         if (!swiper.thumbs || !swiper.thumbs.swiper) { return; }
8056c8056
<         if (!swiper.thumbs.swiper) { return; }
---
>         if (!swiper.thumbs || !swiper.thumbs.swiper) { return; }
8061c8061
<         if (!swiper.thumbs.swiper) { return; }
---
>         if (!swiper.thumbs || !swiper.thumbs.swiper) { return; }
8066c8066
<         if (!swiper.thumbs.swiper) { return; }
---
>         if (!swiper.thumbs || !swiper.thumbs.swiper) { return; }

````

**Comment by DyaryRaoof** [comment]
having the same issue
