### ISSUE TITLE
Swiper autoplay and loop properties not working proper in Angular 2+ on server.

### ISSUE THREAD

**Issue by smartHasmukh** [nolimits4web/swiper#3023]
Hello Swiper Team,

I am using `Angular6` with `CLI`. I have install `Swiper` package in my project - `"angular2-useful-swiper": "^5.0.1"` and `"swiper": "^3.4.2"`. 

### 1st Issue on server
I am using below config ` loop: true` and `autoplay: 1000` added but autoplay not working on server. In my local system working fine

```
Config1: SwiperOptions = {
    pagination: '.swiper-pagination',
    paginationClickable: true,
    spaceBetween: 30,
    loop: true,
    slidesPerView: 1,
    autoplay: 1000
  }

```

### 2nd Issue on server
I am using same config as above except `autoplay` but Swiper loop not working properly. I have attached `ZIP` file for `videos` for `local` and `dev server`. Please download and check it.

```
Config2: SwiperOptions = {
    pagination: '.swiper-pagination',
    paginationClickable: true,
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    spaceBetween: 30,
    loop: true,
    slidesPerView: 4
  };
```

[videos-of-issue.zip](https://github.com/nolimits4web/swiper/files/3025215/videos-of-issue.zip)

If any doubt or any confusion then let me know. I will try to explain in brief.

**Comment by aminsmartsense** [comment]
Hello Team,

Same issue getting in my project also. Please give some solutions for server build. 

Thank you Team.

**Comment by smartHasmukh** [comment]
@nolimits4web Any updates?
