### ISSUE TITLE
Smooth mousewheel scroll with horizontal freemode

### ISSUE THREAD

**Issue by Zmove** [nolimits4web/swiper#3024]
Hello,

I'm trying to create a global horizontal scroll for a website, and I think swiper could be a good candidate for that.

I could easily setup my slider, but unfortunately, the scroll is not smooth when I use my mousewheel. It "jump", 100px by 100px, completely ruining the desired effect.

Do you see a solution for this, or swiper is just not the good candidate to create that kind of navigation ? Do you have some other plugins to suggest me that would fit my need ?

Thank you

**Comment by steve231293** [comment]
Hello, I need also this feature. Have you got any solutions, yet?
How can i make mousewheel smooth like when dragging with freemode?

**Comment by adamcoulombe** [comment]
yeah I agree. I suspect there is some conflict with the way the lib handles slide transitions. It appears the transitions are intentionally squashed.

for example, you can add your own css rule to force a transition, but its a little janky.
```
.swiper-wrapper{
transition-duration: 1.2s!important;
}
```
I started down to road of adding my own scroll behavior with a separate animation library (GSAP), though, I eventually moved on  because I didn't feel like messing around with it a whole bunch. It looked something like this, I'll fully admit, this is pretty half-baked.
```
window.addEventListener('mousewheel',handleMouseWheel);
function handleMouseWheel(e){
   var translate = { y: swiper.translate }
   TweenMax.to(translate,1.2, { y: (e.deltaY) * -1, onUpdate:function(){
      swiper.setTranslate(translate.y)
   } })
}
```

**Comment by Kulgar** [comment]
I managed to do something quite nice using that code:

```
  onMouseWheel = (e) ->
    console.log(e)
    clearTimeout($.data(this, 'timer'))

    $(".swiper-wrapper").addClass('mousewheel')

    $.data(this, 'timer', setTimeout( () ->
      $(".swiper-wrapper").removeClass('mousewheel')

    , 250))

  window.addEventListener( 'mousewheel', onMouseWheel, false )
  window.addEventListener( 'DOMMouseScroll', onMouseWheel, false )
```

Then in your CSS:

```
.swiper-wrapper.mousewheel {
  transition-duration: 1.2s !important;
}
```

You can play with mousewheel sensitivity & transition-duration to change the pace and feel of the smooth effect.

**Comment by dluigirafael** [comment]
Still an issue

**Comment by notrealdev** [comment]
same here

**Comment by nionios** [comment]
Adding smoothscrolling libraries to a website made with swiper.js seems to mess with swiper.progress too much. You have to set sensitivity to 0, which results in progress staying 0 also. 
This makes it impossible (afaik) to rely on another plugin for horizontal smoothscroll. Has anyone figured out anything new?
