### ISSUE TITLE
Loop does not work with float number slides per view

### ISSUE THREAD

**Issue by komarovartem** [nolimits4web/swiper#3025]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/komarovdesign/pen/YMKOzd 

### What you did
Set float number for slidesPerView with loop mode. For some design cases, you must have just a pick of the next slide

### Expected Behavior
loop should work in both directions 

### Actual Behavior
you can slide endlessly only for prev slides but if you try to slide for next slides, the loop stops working

This issue already was reported #2773 but was not fixed. Please take a closer look at this issue since it is definitely a bug. Thank you

**Comment by robpop** [comment]
I made a pull request that addresses this issue @ #3225
