### ISSUE TITLE
Pagination Dynamic Bullets Issue

### ISSUE THREAD

**Issue by 2078421** [nolimits4web/swiper#3029]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Windows, Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/NmGzMN

### What you did
Swiped from the penultimate slide to the final slide (slide 9 to slide 10).

### Expected Behavior
The pagination bullets should show two main bullets (as is specified when configuring swiper)

### Actual Behavior
The pagination bullets show one main bullet.

### Additional Notes
It looks like swiping from slide 1 to slide 10 is fine

**Comment by Nadya1993** [comment]
Thank you for creating this issue. I thought that it was me who set the incorrect config for swiper. BTW, version 4.4.1 works great.

**Comment by robpop** [comment]
I'll look into this
