### ISSUE TITLE
Apple Magic Mouse registering false swipes in navigation clicks

### ISSUE THREAD

**Issue by garrettreed** [nolimits4web/swiper#3030]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: macOS 10.14.1, Chrome 73.0.3683.86, Firefox 66.0, Safari 12.0.1
* Live Link or JSFiddle/Codepen or website with issue: https://gfycat.com/slimyinexperiencedindianjackal

### What you did

Reproduced across Chrome, Firefox, and Safari, with 10 different computers and Apple Magic mice, including the Magic Mouse versions 1 and 2.
Apple trackpads and Logitech mice work as expected.
I see there have been past issues regarding scroll events and the magic mouse's momentum. I couldn't find one that referenced click events.

### Expected Behavior

Clicking "next" button with Apple Magic Mouse always transitions to the next slide. Clicking "previous" navigation button always transitions to the previous slide.

### Actual Behavior

Previous and Next buttons clicked with an Apple Magic Mouse occasionally produce erratic behavior, transitioning in the incorrect direction or multiple slides. See the above link for a video demonstrating the behavior using the Navigation demo at http://idangero.us/swiper/demos/.

**Comment by dmcgrew** [comment]
I'm having this problem as well. Any updates on fixing this issue?

**Comment by cb-eli** [comment]
Same for me, any one can help?
