### ISSUE TITLE
I can't use the slideClass and wrapperClass

### ISSUE THREAD

**Issue by zefexdeveloper** [nolimits4web/swiper#3031]
I tried to follow the documentation API to use `slideClass` and `wrapperClass` but it doesn't work, it always bug the slider. How can I change the slide class and wrapper class?

**Comment by tnfno** [comment]
I have the same problem.  I expected this to work:

`var swiper = new Swiper(".swiper-container", {
  nameclass: {
    wrapperClass: 'view-content',
  },
});`

But the "wrapperClass: 'view-content' line makes no difference, with our without it I get this error:

Uncaught DOMException: Failed to execute 'matches' on 'Element': '..view-content' is not a valid selector.

**Comment by kirill0186** [comment]
Similar problem.
Try to set slide class with Swiper react componet prop slideClass. In DOM element have default class _swiper-slide_, but lose other classes like _swiper-slide-prev_, _swiper-slide-next_ and _swiper-slide-active_.
Resolve problem by setting global styles for _swiper-slide_ class.
