### ISSUE TITLE
Pagination bug, reproduces on swiper demo page too.

### ISSUE THREAD

**Issue by Phalconline** [nolimits4web/swiper#3036]
This is a (multiple allowed):
* [x] bug

Swiper Version: So I see that bug on swiper a long time ago and can be reproduced on many versions.
Platform/Target and Browser Versions: Chrome, macOS
Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/200-infinite-loop.html

**Steps to reproduce.**
1. Go to demo page http://idangero.us/swiper/demos/200-infinite-loop.html
2. Try click to bullet points (2-4), then to the last couple of bullets, repeat it a several times.

Result: Swiper show randomly slides from time to time.
Expectation: Swiper must show slides which trigger bullet point.

Here is my gif from the swiper demo page: https://cl.ly/7c3bb1d75462

**Comment by Antimated** [comment]
I got the same exact issue, I hope a fix will be deployed soon as I use this feature for a client :/

**Comment by jmjunod** [comment]
Same issue here on the demo page

**Comment by pasyuk-uproxx** [comment]
set pagination.clickable to true solve the problem

**Comment by Antimated** [comment]
Pagination.clickable is set to true and the issue persists.

**Comment by udidol** [comment]
+1, having same issue

**Comment by robpop** [comment]
Working on this now

**Comment by robpop** [comment]
#3244

**Comment by robpop** [comment]
Closed https://github.com/nolimits4web/swiper/pull/3244#issuecomment-537463249
> I would better just recommend to enable `threshold` swiper parameter instead

**Comment by yomizhong** [comment]
Adding touchEventsTarget: 'wrapper' as a swiper option seemed to fix it for me 

thanks for [click here](https://github.com/nolimits4web/swiper/issues/2727#issuecomment-532540290)

**Comment by bukandicki** [comment]
hi, have you guys tried **_v8.4.5_**? i think will work if you guys using this version instead 😁
