### ISSUE TITLE
Feature request: make 300ms click delay configurable

### ISSUE THREAD

**Issue by mrcoles** [nolimits4web/swiper#3045]
This is a:
* [ ] bug
* [X] enhancement
* [X] feature-discussion (RFC)

Info:
* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Mac OS X, Chrome 73 mobile emulator and iOS 12.2 Safari
* Live Link or JSFiddle/Codepen or website with isssue: N/A

It appears that the code enforces a 300ms delay before triggering [click events](https://idangero.us/swiper/api/#events) (“Event will be fired when user click/tap on Swiper after 300ms delay.”). It looks like this is hardcoded into the project.

Is this decision related to how mobile browsers used to work with a click delay? If so, this [changed years ago](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away):

> As of Chrome 32 (back in 2014) this delay is gone for mobile-optimized sites, without removing pinch-zooming! Firefox and IE/Edge did the same shortly afterwards, and in March 2016 a similar fix landed in iOS 9.3.

**Comment by musiclover174** [comment]
any reaction here?

**Comment by nolimits4web** [comment]
Removed in v5
