### ISSUE TITLE
iPhone scroll entire screen

### ISSUE THREAD

**Issue by Wicko-Design** [nolimits4web/swiper#3049]
This is a (multiple allowed):
* [x] bug
* Swiper Version: 4.5.0.
* Platform/Target and Browser Versions: iPhone, all iOS devises.

### What you did
On iPhone you are able to scroll the whole screen to the right and view blank white space when swiping normal web content. You can then see all the other images in wrapper. If you are on last image you can not swip whole screen.

How can I stop this scrolling on iPhone?  

### Expected Behavior
Unbale to scroll entire screen and view blank space.

**Comment by Wicko-Design** [comment]
Have found a solution to this. 
Add stying to html. 
Insert the scroller within:
`<div style="max-width: 100%; overflow-x: hidden;">
</div>
`

**Comment by spinninghamster** [comment]
> Have found a solution to this.
> Add stying to html.
> Insert the scroller within:
> `
> 
> `

Please explain a bit more?
