### ISSUE TITLE
How  to use  fraction and progressbar at the same time??

### ISSUE THREAD

**Issue by xjj0322** [nolimits4web/swiper#3051]
How  to use  fraction and progressbar at the same time??

![image](https://user-images.githubusercontent.com/44220867/56454462-44f0ad00-6383-11e9-8b5c-9c8ef32f3f0e.png)

**Comment by xjj0322** [comment]
I think the fraction needs to be independent as a new function。

**Comment by xjj0322** [comment]
I think the Fraction needs to be independent as a new function。And we can use  new Fraction with bullets or progress together.

**Comment by Uranbold** [comment]
I think these two type really need to separate function. Please consider about it!
