### ISSUE TITLE
Mousewheel demo does not work until I move my mouse

### ISSUE THREAD

**Issue by rossenv** [nolimits4web/swiper#3052]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: macOS and Windows, Chrome 73 
* https://idangero.us/swiper/demos/270-mousewheel-control.html

### What you did
Load or reload page with ctrl/cmd + R not moving mouse cursor

### Expected Behavior
When swipe vertical change slide to next/prev

### Actual Behavior
No slide chage until move mouse cursor or click or resize window

**Comment by joebentaylor1995** [comment]
I have this issue in production too, see here: [Click me](https://colorworld.netlify.com/company/)

Causing some major issues until you move the mouse slightly

**Comment by ardavan-ansari** [comment]
Any updates on this issue? ( or maybe someone has a workaround ? )

**Comment by kevinbism** [comment]
You need to download the lastest version. The issue is solved.
