### ISSUE TITLE
Multiple different pagination (Progressbar + Bullets)

### ISSUE THREAD

**Issue by InsOmniall** [nolimits4web/swiper#3054]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: ^3.1.3
* Platform/Target and Browser Versions: macOs, Windows (Chrome)

### What you did
Hello! I wanted to add multiple different paginations to my project with swiper. For example progress bar + bullets. But found nothing anywhere about this feature.

### Expected Behavior
2 different kinds of pagination on 1 swiper instance.

### Actual Behavior
Only 1 pagination is allowed.

**Comment by warudin** [comment]
I would like this option as well!

**Comment by JamesZXCVBNM** [comment]
I'd also like to be able to have Bullets + Fraction pagination on the same slider
