### ISSUE TITLE
Importing the whole Swiper SCSS

### ISSUE THREAD

**Issue by dangelion** [nolimits4web/swiper#3061]
I'm importing Swiper in my project via SCSS like this:

```
// Swiper
@import "~swiper/src/swiper";
```

but it doesn't contain all the components, so I should import them one by one like so:

```
@import "~swiper/src/components/navigation/navigation";
@import "~swiper/src/components/pagination/pagination";
...
```

But this is dirty and prone to errore, because if the library structure/names changes, with future upgrade we'll get errors.

Is there a secure way to import the whole library SCSS without manually importing components?
Thanks

**Comment by nolimits4web** [comment]
No, SCSS and LESS sources designed to be used as modular
