### ISSUE TITLE
Dragging on pagination elements will change active slide

### ISSUE THREAD

**Issue by t-ricci-delta** [nolimits4web/swiper#3062]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.6 from NPM (c6f92692d2643d41cf14638638b991b5cd41d1e2)
* Platform/Target and Browser Versions: currently tested on Firefox developer edition (windows 67.0b18 64-bit) and Chrome (macOS Version 74.0.3729.131 Official Build 64-bit)
* Live Link or JSFiddle/Codepen or website with isssue: website currently not public, but can be seen in demos as well (http://idangero.us/swiper/demos/)

### What you did
I dragged the finger/mouse on the pagination elements under the slides

### Expected Behavior
Nothing

### Actual Behavior
The active slide changed (as if I dragged on the slide)

**Comment by t-ricci-delta** [comment]
Hmm, looks like I missed another issue already opened #2821

**Comment by t-ricci-delta** [comment]
I was thinking to close and/or mark as duplicated, but I see the other issue has been ignored.
I'll keep this issue open if it gets some attention

**Comment by nolimits4web** [comment]
Check `touchEventsTarget`, it must be set to `wrapper` http://idangero.us/swiper/api/

**Comment by t-ricci-delta** [comment]
Oh, thanks. Didn't see that option and didn't find an answer in the other issue

**Comment by acwo** [comment]
```
swiper.on('slideChange', function() {
    swiper.pagination.render();
    swiper.pagination.update();
});
```

Above code solves the problem.
