### ISSUE TITLE
Slides disappear in RTL with virtual slides and `renderExternal`

### ISSUE THREAD

**Issue by alejandroiglesias** [nolimits4web/swiper#3064]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0, 4.0.0
* Platform/Target and Browser Versions: Chrome 74, Firefox 66, Safari 12.1 (all macOS)
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/8no41jp6l8

### What you did
1. Open the CodeSandbox. Slide 1 will be displayed.
2. Swipe to the right for the next slide (because on RTL). Swipe again a second time. Now there are no slides displayed. You can slide back to the second and it re-appears.

### Expected Behavior
It's expected for the slides to keep appearing.

### Actual Behavior
After the second slide (probably `slidesPerView` + 1 more as a buffer), the other slides aren't displayed (probably the wrong offset is returned on virtual slides data?).

**Comment by joshudev** [comment]
@alejandroiglesias  - did you manage to find a workaround for this bug?

**Comment by alejandroiglesias** [comment]
@joshudev no. Unfortunately, I had to force the slider to work as LTR even on RTL languages.

**Comment by joshudev** [comment]
@alejandroiglesias - ok, thanks. We've dropped the use of virtual slides for now instead.
