### ISSUE TITLE
Progress bar showing incorrect fraction/position

### ISSUE THREAD

**Issue by JohntheFish** [nolimits4web/swiper#3066]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Chrome, Firefox (latest).
* Live Link or JSFiddle/Codepen or website with issue: n/a

### Expected Behavior
If I have 11 slides, I expect the progress bar to be shown with 11 segments, slide 1 in the leftmost segment, slide 11 in the rightmost segment.

### Actual Behavior
Location of current position on progress bar is including loopedSlides. So when I have 11 slides and 2 looped slides to allow for a looped slider, the bar appears to be calculated as 2+11+2 slides long. Going forwards, slide 1 is 3/15 segments in from the left, then as it loops, slide 11 is 3/15  slides in from the right, and forward to slide 1 puts progress 2/15 slides in from the right.

Similar incorrect progressbar going backwards, with slide 11 showing at position 2/15 when looped backwards.

Similar to https://github.com/nolimits4web/swiper/issues/2191 (now locked)

![slide1 at start](https://user-images.githubusercontent.com/1260106/57540383-84883480-7344-11e9-915a-781474d52f4d.png)
![slide1 looped](https://user-images.githubusercontent.com/1260106/57540544-de88fa00-7344-11e9-9f32-4f8ff5221d81.png)

**Comment by robpop** [comment]
I'll work on this if @nolimits4web agrees that this should be a feature. He had said previously in #2315 that this is by design. 

https://github.com/nolimits4web/swiper/issues/2315#issuecomment-343162574

**Comment by JohntheFish** [comment]
Bump

**Comment by JohntheFish** [comment]
Bump
