### ISSUE TITLE
Continue scrolling after last slide

### ISSUE THREAD

**Issue by acespace90** [nolimits4web/swiper#3068]
* Swiper Version: 4.5.0.
* Platform/Target and Browser Versions: macOS, Windows, Chrome, Firefox, Safari and others.

### What I did
On my site I'm using several swipers without any problem but only in a page I have a it. Swiper continues scrolling after last slide despite navigation arrows disappear. But if I drag with the mouse/finger it still scrolls.

PS: how can I disable dragging on desktop?

### Expected Behavior
I expect it stops to scroll when I am on last slide.

Look at the video below.

![swiper-issue](https://user-images.githubusercontent.com/12846842/57683494-18534c80-7634-11e9-9e09-3ec7a8f13f27.gif)

**Comment by acespace90** [comment]
Nothing?

**Comment by dmitriydementor** [comment]
Same problem

**Comment by techoi** [comment]
@acespace90 If you share your code would be better to get more specific help..

**Comment by lean1024** [comment]
previously
![image](https://user-images.githubusercontent.com/32680721/152826492-e65d35c1-f536-4514-afe9-911f567f3fb8.png)

after fix
![image](https://user-images.githubusercontent.com/32680721/152826573-8e587dbc-7b7a-4b15-811a-f721a03275b6.png)
