### ISSUE TITLE
VirtualTranslate and loop not working together

### ISSUE THREAD

**Issue by michaelWoe** [nolimits4web/swiper#3070]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Windows,  CHROME.
* Live Link or JSFiddle/Codepen or website with issue: [https://jsfiddle.net/u4vqyt7o/](https://jsfiddle.net/u4vqyt7o/)

### What you did
Initialized autoplay-example with following JS:
```javascript
var swiper = new Swiper('.swiper-container', {
  spaceBetween: 30,
  centeredSlides: true,
  virtualTranslate: true,
  loop: true,
  autoplay: {
    delay: 2500,
    disableOnInteraction: false,
    waitForTransition: false,
  },
  pagination: {
    el: '.swiper-pagination',
    type: 'fraction',
  },
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  }
});
```

### Expected Behavior
Slideshow working correctly (pagination counting correctly and slide classes updating).

### Actual Behavior
* Slideshow get's stuck on 2nd slide.
* Swiping working if stuck but navigation not.
* It also is not working without autoplay.

**Comment by pmkhoa** [comment]
Had the same issue when using `virtualTranslate` and `loop` both set to true. Then the navigation next/prev will not working. Only the swipe works.

**Comment by romanran** [comment]
Same problem here.

**Comment by Djules** [comment]
I found out that reseting swiper internal `animating` flag on `slideChangeTransitionStart` event make it works again.

```js
var swiper = new Swiper('.swiper-container', {
  …
});

swiper.on('slideChangeTransitionStart', function() {
  setTimeout(function() {
    this.swiper.animating = false;
  }, 0);
});
```

**Comment by godness84** [comment]
@Djules `this` inside `setTimeout` refers to `window` instead of the swiper instance. I replaced with `swiper.animating = false` and it works.

**Comment by Djules** [comment]
@godness84 whoops my bad! I edited my previous comment. Glad it works!

**Comment by herrschuessler** [comment]
@nolimits4web This issue still persists in Swiper 6. Is it possible to re-open this issue?

**Comment by vltansky** [comment]
@herrschuessler did you try the following workaround?

> I found out that reseting swiper internal `animating` flag on `slideChangeTransitionStart` event make it works again.
> 
> ```js
> var swiper = new Swiper('.swiper-container', {
>   …
> });
> 
> swiper.on('slideChangeTransitionStart', function() {
>   setTimeout(function() {
>     swiper.animating = false;
>   }, 0);
> });
> ```

**Comment by herrschuessler** [comment]
@vltansky Yes, and I can confirm that it works!

**Comment by jonaaust** [comment]
This is still a bug [v8.4.5]. Loop does not work when virtual is true.

**Comment by karinfdez** [comment]
I'm having the same issue. Virtual does not work with loop in true. It only renders the initial slides, and then when it gets to the end of the rendered slide, it gets stuck. Loop doesn't work and it doesn't generate the rest of the slides.

**Comment by jackkemmish** [comment]
Can confirm this workaround still works in v11.1.14 but feels like something that shouldn't need a workaround by this point?

I can also confirm that `virtualTranslate: true` and `autoplay` don't work in harmony with eachother. It autoplays the first slide then stops. Weirdly if I navigate away from the tab then go back it then autoplays another slide. Anyone had this before? Feels like a bit of a bug.
