### ISSUE TITLE
Clicking on next randomly jumps backwards or changes direction to previous

### ISSUE THREAD

**Issue by wzol** [nolimits4web/swiper#3074]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Windows 10, Chrome 74.0.3729.157
* Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/020-navigation.html

### What you did
Multiple fast clicking on next slide.

### Expected Behavior
Change to next slide.

### Actual Behavior
Randomly jumping back to a few slides or changing direction to backwards (so next acts like previous).

It seems quite random, but happens with a 20-30% chance, I have tried many combinations of options but it didn't help, also it acts similar with the simple demo too.

**Comment by ametthey** [comment]
Hi, I'm having the same issue, my case is special, I'm on Wordpress, working on a custom theme, but when working with the lazy load WP Rocket plugin, it's bugged, but when the plugin is desactivated, all good =)

**Comment by sethwhitaker** [comment]
also experiencing this randomly at times

**Comment by dana-davis** [comment]
I am also experiencing this. Has anyone found a fix?

**Comment by nolimits4web** [comment]
Because you also do a short swipes, use `touchEventsTarget: 'wrapper'`
