### ISSUE TITLE
Lazy loading with slidesPerview="auto" does not work at init without sliding

### ISSUE THREAD

**Issue by sneko** [nolimits4web/swiper#3075]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: ^4.5.0
* Platform/Target and Browser Versions: all

### What you did
```
  {
    slidesPerView: 'auto',
    centeredSlides: false,
    freeMode: true,
    preloadImages: false,
    watchSlidesVisibility: true,
    lazy: {
      loadPrevNext: true,
      loadPrevNextAmount: 2,
      loadOnTransitionStart: true,
    },
  }
```

### Expected Behavior
Seeing visible slides at init.

### Actual Behavior
No image will be loaded unless I start to slide a bit the slider (even if just 1px). Like if the visibility area was not watched correctly 😢 

Any idea what could help?

**Comment by sneko** [comment]
Since I'm loading data remotely, I thought calling the `update()` method would do the trick, but it doesn't.

Note: the main issue is that after loading data my slides don't have the visibility css class. So even by running `swiper.lazy.load()` nothing special happens.

After digging deep in the Swiper code, I find a solution to manually replay the process to load initial visible images:
```
swiper.updateSlidesProgress()
swiper.lazy.load()
```

Like that the first instruction will watch a new time viewport and add visible css class to appropriate slides.

That sounds like a workaround for me 🤔 ... I don't understand why triggering `update()` after having loaded the whole set of data is not setting visible class, what do you think @nolimits4web?

By the way, big thank to this amazing lib 👍

**Comment by sneko** [comment]
Hi @nolimits4web,

I'm still with the issue of `loadOnTransitionStart = true` not working when slides become visible.

Thank you,

**Comment by Kinasha** [comment]
> Hi @nolimits4web,
> 
> I'm still with the issue of `loadOnTransitionStart = true` not working when slides become visible.
> 
> Thank you,

hi @sneko  I'm still has this problem and my swiper version is 6.8.4 ,this is how i use it 
```js
            slidesPerView={3}
            freeMode
            lazy={{ loadPrevNext: true, loadPrevNextAmount: 10 }}
            watchSlidesVisibility
            afterInit={(swiper) => {
                swiper.updateSlidesProgress();
                swiper.lazy.load();
            }}
```
could you tell me if you solve this problem or not ?

**Comment by natapg** [comment]
any updates on this? I have the same issue using 
```
 <Swiper
            modules={[Lazy]}
            spaceBetween={116}
            slidesPerView='auto'
            watchSlidesProgress
            centeredSlides={true}
            lazy={{ loadPrevNext: true, loadPrevNextAmount: 2 }}
            preloadImages={false}
            onBeforeInit={(swiper) => {
              swiperRef.current = swiper
            }}>
```

**Comment by putrafajarh** [comment]
i had this problem too, temp fix for me is `loadPrevNextAmount: 3`

**Comment by acatzk** [comment]
```
import SwiperCore, { Lazy } from 'swiper';

SwiperCore.use([Lazy]);
```
