### ISSUE TITLE
Another vertical slider height issue...

### ISSUE THREAD

**Issue by hartey11** [nolimits4web/swiper#3076]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Chrome Version 76.0.3800.0 (Official Build) canary (64-bit).
* https://the-transmission.harte.online/post-20
Scroll down and click the button "Launch Demo Modal"

This is what I am trying to build:
https://the-transmission.harte.online/wp-content/uploads/sites/7/2019/05/modal-slider-vertical-thumbnails.png

### Expected Behavior
Display 2 sliders side by side. left shows a large version of the image. The right side shows a 2-column by 5-row vertical scrolling thumbnails of all the images in the gallery.

### Actual Behavior
Height isn't correct and the height of each slide increases every time you resize the screen.

**Comment by nolimits4web** [comment]
Closing as not the issue with Swiper, fix vertical Swiper's height

**Comment by hartey11** [comment]
How do I fix the height?
