### ISSUE TITLE
Some events are not triggered on long swipes in virtual slides mode with `renderExternal`

### ISSUE THREAD

**Issue by alejandroiglesias** [nolimits4web/swiper#3078]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: macOS Chrome, Firefox, and Safari
* Live Link or JSFiddle/Codepen or website with issue: https://codesandbox.io/s/swiper-events-are-not-fired-on-long-swipes-9p4mb

### What you did

1. Open the CodeSandbox (also open the console at the bottom of the preview).
2. Slide with a long swipe from the rightmost end of the slide, to the leftmost edge (ie, a long swipe).

### Expected Behavior
`slideChange, `transitionStart`, `slideChangeTransitionStart`, `slideNextTransitionStart`, `transitionEnd`, and `slideChangeTransitionEnd` events to be triggered.

### Actual Behavior
Only `slideChange`, `transitionStart`, `slideResetTransitionStart`, and `transitionEnd` events are triggered.

I'm aware of #2439, but this is not working when enabling virtual slides with `renderExternal`. If I disable virtual slides and `renderExternal`, all the events are triggered correctly.

**Comment by alewin** [comment]
Same issues

**Comment by ankitmechu** [comment]
same issue with me

**Comment by MrMaksi** [comment]
Any updates on this? I have the same problem

**Comment by shoespray** [comment]
same problem here, using reactjs
