### ISSUE TITLE
Lazy Load, Each slide image is loaded twice

### ISSUE THREAD

**Issue by sethwhitaker** [nolimits4web/swiper#3079]
When lazy load is enabled, each slide image gets loaded twice as seen in the network tab of my browser. Is this expected? Its really nice to cut down on the initial load of the page, but if someone interacts through the slider, they end up consuming double the data in the end compared to not lazy loading at all.

Not sure if this is a bug or expected behavior or if im not understanding what is happening in the network tab.

This is a (multiple allowed):
* [x] bug ??
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with isssue: Issue can be seen on the swiper demo page http://idangero.us/swiper/demos/370-lazy-load-images.html

### Expected Behavior
Each slide image only loaded once.

### Actual Behavior
Each slide image data is loaded twice as seen through the browsers developer tools network tab.

**Comment by sethwhitaker** [comment]
Any response?

**Comment by lazysergey** [comment]
same here

**Comment by qlanders** [comment]
+1

**Comment by slorber** [comment]
Same here,

If that helps, here are 2 stacks of the image loads:

![image](https://user-images.githubusercontent.com/749374/61702342-ed762a80-ad3f-11e9-95a4-328a880f5a28.png)

![image](https://user-images.githubusercontent.com/749374/61702373-f830bf80-ad3f-11e9-818a-954ce76332b1.png)

**Comment by slorber** [comment]
it seems related to image caching not being enabled, so when image loads and we update image src attribute it reloads again instead of using the already loaded version

https://github.com/nolimits4web/swiper/issues/3017

**Comment by sethwhitaker** [comment]
good find, disappointing that the author closed that ticket and blamed server caching. We have server caching on and it still loads images twice on our sites. weve been conflicted as to whether we should even bother using the lazy load feature because people will end up using more data if they ever interact with the site sliders.

**Comment by nolimits4web** [comment]
Go to http://idangero.us/swiper/demos/370-lazy-load-images.html
Open dev tools, make sure that `Disable cache` is not checked
See how many times image is loaded
