### ISSUE TITLE
'eventsTarged' not working properly

### ISSUE THREAD

**Issue by xdcha** [nolimits4web/swiper#3083]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

The 'eventsTarged' property does not seem to work. A few people on here mentioned how it should be 'target' but neither the API page or the raw .js file suggest this is the case. 

     mousewheel: {
        eventsTarged: "c-home"
      },

I wish to use the div `c-home` (which wraps around the entire container) to trigger mouse wheel events, but no luck. Doesn't look like anyone else has this issue either.

**Comment by mnoesel** [comment]
I think it should say 

` mousewheel: {
    eventsTarget: "c-home"
  },`

**Comment by AidosMarcos** [comment]
I have exactly the same issue, created an element to use as trigger and it seems swiper doesnt detect.
