### ISSUE TITLE
slidesPerView for images

### ISSUE THREAD

**Issue by strarsis** [nolimits4web/swiper#3085]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Chrome, Windows 10
* Live Link or JSFiddle/Codepen or website with isssue: 
https://jsfiddle.net/ybq27ch1/6/

### What you did
Initialized swiper slider with slides containing an image.

### Expected Behavior
Slides are correctly distributed, `spaceBetween` as gap.

### Actual Behavior
Each slide occupies the complete view (slider width).

**Comment by t-ricci-delta** [comment]
you need to use the option  slidesPerView: "auto"

**Comment by strarsis** [comment]
@t-ricci-delta: The option `slidesPerView: "auto"` is set (also in fiddle).

**Comment by t-ricci-delta** [comment]
did you try to set .swiper-slide { width: auto; } ?

**Comment by t-ricci-delta** [comment]
div by default are display: block and take the full width

**Comment by strarsis** [comment]
@t-ricci-delta: Thanks! Yes, currently the element that contains the `<img>` is `display: block`.

**Comment by t-ricci-delta** [comment]
no problem, then @strarsis close the issue if it's solved

**Comment by t-ricci-delta** [comment]
you could use display: inline-block but I discourage from doing so, makes a lot of problems usually..
just width: auto should do the trick, it's plenty enough
