### ISSUE TITLE
watchSlideVisibility only works on screen resize.

### ISSUE THREAD

**Issue by ecDusty** [nolimits4web/swiper#3086]
Firstly, this is a FANTASTIC gallery slider, amazing stuff building this. 

This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0 (Latest version)
* Platform/Target and Browser Versions: This issue is consistent through all browser interfaces I've tested (Chrome-(Mac & Windows), Firefox-(Windows), Safari, iOS Safari, Android Chrome)
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/HKDusty/pen/qGJYQY

### What you did
So I read through all your documentation within the API. I wanted to build a card gallery slider, that has the slides that are going off screen that shrink & go a little see-through. I initiallize a new Swiper like so:

```
const favSwiper = new Swiper('.swiper-container', {
	direction: 'horizontal',
	spaceBetween: 32,
	loop: false,
	watchOverflow: true,

	// Set Slide Class
	slideClass: 'swiper-slide',
	// watchSlidesProgress: true,
	watchSlidesVisibility: true,
	centerInsufficientSlides: true,
    preloadImages: false,
    // Enable lazy loading
    lazy: true,

	// Pagination
	pagination: {
		el: '.swiper-pagination',
		type: 'bullets',
		clickable: true,
        renderBullet: function (index, className) {
			return '<span class="' + className + '"><span>' + (index + 1) + '</span></span>';
		},
	},

	// Navigation Arrows
	navigation: {
		nextEl: '.swiper-button-next',
		prevEl: '.swiper-button-prev',
	},

	// Breakpoints
	breakpointsInverse: true,
	breakpoints: {
		768: {
			slidesPerView: 2,
			// slidesPerGroup: 2,
		},

		1084: {
			slidesPerView: 3,
			// slidesPerGroup: 3,
		},

		1456: {
			slidesPerView: 4,
			// slidesPerGroup: 4,
		}
	}
});
```

The number of cards that show depends on the width of the screen. I then use the ```.swiper-slide-visible``` class to apply the visible styles to. Then the non-active / non-visible slides have the CSS properties set to ```transform:scale(0.7); opacity(0.7)``` use the standard ```.swiper-slide``` class.

The key is that the ```.swiper-slide-visible``` class gets applied to slides that are visible

### Expected Behavior
Any Swipe Slide that is visible on screen with have the ```.swiper-slide-visible``` class added to it. Which then has the ```.swiper-slide-visible``` class CSS styles applied.

### Actual Behavior
Only the active slide has the ```.swiper-slide-visible``` class applied to it. (Which is the first slide). 

But on any screen resize or rotation, ```.swiper-slide-visible``` class gets applied to all visible slides.
Created a video for reference as well:
[swiper visibility issue video.zip](https://github.com/nolimits4web/swiper/files/3236369/swiper.visibility.issue.video.zip)

I've searched all issues, and can't find anyone referring to this, in anyway.

**Comment by nolimits4web** [comment]
Hi, the problem is in this CSS prop you have:
```css
transition: all 0.25s ease-out;
```

Replace it with:
```css
transition-duration: 250ms;
transition-property: transform, opacity;
```

You shouldn't set `all` for transition properties, because in this case slide changes width for duration, and on a moment of sizes calculation it receives not expected sizes
