### ISSUE TITLE
Slides containing responsive pictures break Swiper when window is resized

### ISSUE THREAD

**Issue by ghost** [nolimits4web/swiper#3088]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.0
* Platform/Target and Browser Versions: any
* Live Link or JSFiddle/Codepen or website with issue:

```
       var swiperOptions = {
            //centeredSlides: true, // tried both with true and false doesn't change much
            slidesPerView: "auto"
        }

<li class="swiper-slide"> <!-- contains <picture> with breakpoints (mobile bp uses a squared image and tablet/desktop a rectangle image) --> </li>
```

See example Codepen: https://codepen.io/t-ricci-delta/pen/gNOzQq

### What you did
See above pseudo-code: using auto slidesPerView (also tried centeredSlides), and each slide contains a responsive <picture> using [picturefull](https://github.com/scottjehl/picturefill), initializing swiper instance on document ready using jQuery

### Expected Behavior
Expected Swiper to recalculate the slide dimensions on window resize (especially when passing the breakpoints set in the <picture> tag of the slide)

### Actual Behavior
When the window is resized (or smartphone flipped from portrait to landscape or vice-versa) the current slide offset is not centered, and the prev/next buttons won't work as expected (all the offsets are incorrect, presumably they still use the previous width of the slides)

**Comment by t-ricci-delta** [comment]
For additional information:
I also tried to invoke swiperInstance.update() on window resize handler, but didn't update the width of the slides

**Comment by t-ricci-delta** [comment]
Hi @nolimits4web, do you think this is a non-supported feature, an actual bug, or am I using it wrong?
Would it be difficult to make this work, or add support "responsive" slide items? Can you take a look?
Tell me if you need a hand I'll see what I can do to contribute

**Comment by timoanzalone** [comment]
I'm having the same problem.

**Comment by t-ricci-delta** [comment]
Added a codepen example for reference and testing it out:

https://codepen.io/t-ricci-delta/pen/gNOzQq

**Comment by t-ricci-delta** [comment]
Any update on this?
We're using the plugin on a well-known website with large traffic, would you help us out?

**Comment by mattiamari** [comment]
Same here. Device rotation does not update the translate-3d property on ionic resulting in slides half visible. Calling update() on window resize does not help.

**Comment by vltansky** [comment]
https://github.com/ionic-team/ionic-framework/issues/19065

**Comment by KappaPrajd** [comment]
Same here. Is it still not resolved or did someone find a solution to this?
