### ISSUE TITLE
on reach end and change slide to next

### ISSUE THREAD

**Issue by KPLehmann** [nolimits4web/swiper#3095]
Hi there! I need a bit of help here: 
I'd like to load a new page when clicked on the last slide (or mousewheel turned on last slide). 

The following triggers the pageload when the last slide is reached, but I want this to happen when clicked on last slide.

mySwiper.on('reachEnd', function () {
  console.log('reached End');
  window.location = '<?php echo $previous_post_url ?>';
});

Any help is much appreciated!

**Comment by KPLehmann** [comment]
👨🏽‍💻

**Comment by disbelief** [comment]
@KPLehmann were you able to figure this out?
