### ISSUE TITLE
Multiple row perView

### ISSUE THREAD

**Issue by robertnicjoo** [nolimits4web/swiper#3102]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Used in Ionic 5 (not sure about swiper version)
* Platform/Target and Browser Versions: Cordova (ionic) - android

### What you did
I tried to get 6 element in each slide divided in 2 rows each one 3 columns but i get all my images at once.

```
categoriesOpts = {
    loop: false,
    slidesPerView: 6,
    slidesPerColumn: 3
  }
```

### Expected Behavior
show 6 item in 2 rows.

![Screenshot_20190617_140200](https://user-images.githubusercontent.com/8672823/59584662-d1f87e00-9108-11e9-807e-e09345f5501b.jpg)

### Actual Behavior
shows 7 items in 1 slide

![4578](https://user-images.githubusercontent.com/8672823/59584470-51d21880-9108-11e9-979f-d86c3a6272e7.png)

**Comment by robertnicjoo** [comment]
# SOLVED

https://jsfiddle.net/w29Lmhjp/

```
slidesPerView: 3, //columns
slidesPerColumn: 2, //rows
```

**Comment by KingPengZero** [comment]
loop: true
right swiper is invalid
