### ISSUE TITLE
Hide / Show slides

### ISSUE THREAD

**Issue by LeoFlandin** [nolimits4web/swiper#3106]
Does hiding / showing slides using css display properties is supported in Swiper version 4.5.0 ?
In the documentation, it seems it could be : 

> `mySwiper.update();`  You should call it after you add/remove slides manually, or after you hide/show it, or do any custom DOM modifications with Swiper

I have a multi-columns multi-rows slider and I want to hide / show slides based on a filter.
I does not seems to work on multi-columns multi-rows slider. The styles are messed up when hiding elements. 

There is a codepen : https://codepen.io/gabriel-glenn/pen/KjgwJv

**Comment by notrealdev** [comment]
+1

**Comment by robpop** [comment]
I'll go ahead and look into this. [swiper bug swatting](https://github.com/users/robpop/projects/5)

**Comment by robpop** [comment]
@LeoFlandin are you referring to how the pagination truncates to 1 when you click the "even" button?

**Comment by LeoFlandin** [comment]
Sorry for the late reply.

Yes, indeed and also the general organisation is messed up.

The expected result, for me at least, is a 3x3 grid, sliding left/rigth, as in the 'all' case but with the filtered elements removed.

Thanks for looking into this issue.

**Comment by robpop** [comment]
The most recent version of Swiper makes this issue worse. I'm not exactly sure how to approach this.
