### ISSUE TITLE
Solution: Last slide not getting active when 'slidePerView' set to 'auto'.

### ISSUE THREAD

**Issue by joelamltc** [nolimits4web/swiper#3108]
I currently experienced the same problems like as many people did and also looked through the issues but no results.
https://github.com/nolimits4web/swiper/issues/2571, https://github.com/nolimits4web/swiper/issues/1257, https://github.com/nolimits4web/swiper/issues/534
Finally, I found out a way to do it, a better way to do it guys!.

By setting the `snapGrid` settings as same as the `slidesGrid` settings after the swiper initialized.
And then the swiper will work as what you expected.
```
const swiper = new Swiper(
    '.awesome-swiper', 
    {
        init: false,
        direction: 'horizontal',
        speed: 700,
        slidesPerView: 'auto',
        spaceBetween: 80,
    }
);

swiper.init();
swiper.snapGrid[swiper.snapGrid.length - 1] = swiper.slidesGrid[swiper.slidesGrid.length - 1];
```

or even completely replacing it by cloning the settings.
```
// can do this way
swiper.snapGrid = swiper.slidesGrid.slice(0);

// or ES6 way
swiper.snapGrid = [...swiper.slidesGrid];
```

### Update: 2020-11-18
You will need to update the `snapGrid` when responsive by using built-in [Events](https://swiperjs.com/api/#events).

**Comment by kubiqsk** [comment]
Do you have idea why it's not working with new version of swiper? :/

**Comment by joelamltc** [comment]
Would you like to provide a codepen, etc. to have look tgt?

**Comment by kubiqsk** [comment]
Actually I just found solution - it's because of images inside are not loaded yet and I use width: auto and 'auto' slidesPerView, so I have to wrap everything into imagesLoaded function and it works now ;) Thanks anyway... this is my demo web if you want to look http://swiper.kubiq.sk/history/

**Comment by alexknipfer** [comment]
Any update on this, I'm dealing with the same issue where the `slideChange` event doesn't get fired for the last slide when `slidePerView` is set to auto? I'm don't think my issue is related to images being loaded, another thread mentioned setting `centeredSlides: true` fixes it, which it does, however, I don't want my slides centered.

**Comment by pedromg311** [comment]
I'm facing the same issue.
This "swiper.snapGrid = [...swiper.slidesGrid];" seems to work 90% of the time. Since there are still random cases where it fails and i have no idea why. It seems that the swiper grid calculation are ignoring something, i just can't seem to understand what.
I also notice that changing to landscape and back to portrait forces me to set the snapGrid again, since every time the swiper update method is called the snapGrid is reset.

**Comment by joelamltc** [comment]
@pedromg311 I think it need to re assign the value after responsive.

**Comment by otr-tomek** [comment]
Alternative:
```
mySwiper.on('reachEnd', function () {	
			myAction(this.slides[this.slides.length - 1]);
// or You can add 'swiper-slide-active' class
		})
```

**Comment by mmintel** [comment]
The solution mentioned here changes the way my slides are arranged, I have a combination of 

```
  centeredSlides: true,
  centeredSlidesBounds: true,
```

using this method fixes the initial bug but introduces another where my slides are not aligned properly. I only needed the correct index so my workaround was to calculate the index based on the progress and `slides.length`

**Comment by mxcihak** [comment]
For everyone still struggling with this bug, try setting @joelamltc solution on every slide change using `slideChange` event. And also set `updateOnWindowResize: false,` on init, as calculation on window resize also overrides snapGrid.

**Comment by WilliBautista** [comment]
> I currently experienced the same problems like as many people did and also looked through the issues but no results.
> #2571, #1257, #534
> Finally, I found out a way to do it, a better way to do it guys!.
> 
> By setting the `snapGrid` settings as same as the `slidesGrid` settings after the swiper initialized.
> And then the swiper will work as what you expected.
> 
> ```
> const swiper = new Swiper(
>     '.awesome-swiper', 
>     {
>         init: false,
>         direction: 'horizontal',
>         speed: 700,
>         slidesPerView: 'auto',
>         spaceBetween: 80,
>     }
> );
> 
> swiper.init();
> swiper.snapGrid[swiper.snapGrid.length - 1] = swiper.slidesGrid[swiper.slidesGrid.length - 1];
> ```
> 
> or even completely replacing it by cloning the settings.
> 
> ```
> // can do this way
> swiper.snapGrid = swiper.slidesGrid.slice(0);
> 
> // or ES6 way
> swiper.snapGrid = [...swiper.slidesGrid];
> ```

this work for me, but with a little adjustment:
I placed this line `this.snapGrid = [...this.slidesGrid];` inside of the `reachEnd` event, like this:

`const swiper = new Swiper('.awesome-swiper', {
    direction: 'horizontal',
    speed: 700,
    slidesPerView: 'auto',
    spaceBetween: 80,
    on: {
      reachEnd: function() {
        this.snapGrid = [...this.slidesGrid];
      },
    }
 }`

**Comment by kubiqsk** [comment]
```
on: {
	snapGridLengthChange:function(){
		if( this.snapGrid.length != this.slidesGrid.length ){
			this.snapGrid = this.slidesGrid.slice(0);
		}
	}
}
```

**Comment by AndreyKnyazkov** [comment]
> > I currently experienced the same problems like as many people did and also looked through the issues but no results.
> > #2571, #1257, #534
> > Finally, I found out a way to do it, a better way to do it guys!.
> > By setting the `snapGrid` settings as same as the `slidesGrid` settings after the swiper initialized.
> > And then the swiper will work as what you expected.
> > ```
> > const swiper = new Swiper(
> >     '.awesome-swiper', 
> >     {
> >         init: false,
> >         direction: 'horizontal',
> >         speed: 700,
> >         slidesPerView: 'auto',
> >         spaceBetween: 80,
> >     }
> > );
> > 
> > swiper.init();
> > swiper.snapGrid[swiper.snapGrid.length - 1] = swiper.slidesGrid[swiper.slidesGrid.length - 1];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or even completely replacing it by cloning the settings.
> > ```
> > // can do this way
> > swiper.snapGrid = swiper.slidesGrid.slice(0);
> > 
> > // or ES6 way
> > swiper.snapGrid = [...swiper.slidesGrid];
> > ```
> 
> this work for me, but with a little adjustment:
> I placed this line `this.snapGrid = [...this.slidesGrid];` inside of the `reachEnd` swiper event, like this:
> 
> ```
> const swiper = new Swiper('.awesome-swiper', {
>     direction: 'horizontal',
>     speed: 700,
>     slidesPerView: 'auto',
>     spaceBetween: 80,
>     on: {
>       reachEnd: function() {
>         this.snapGrid = [...this.slidesGrid];
>       },
>     }
> }
> ```

This one didn't work for me. When I go to the last item I have to click twice to reach the last element. 
The solution is to click on the next button through javascript when I reach the reachEnd function. It works only with the setTimeout function because of no reason
Here we go:
```
       on: {
          reachEnd: function() {
            this.snapGrid = [...this.slidesGrid];
            setTimeout(() => {
              document.querySelector('.swiper-button-next').click()
              clearTimeout()
            }, 1);
          },
        }
```

**Comment by geekysaurabh001** [comment]
Anyway to solve this in React? SwiperReact?

**Comment by federicofrasca796** [comment]
> Anyway to solve this in React? SwiperReact?

@geekysaurabh001 

The equivalent for React users is the following:

`
<Swiper
        onSwiper={(swiper) => {
          swiper.snapGrid = [...swiper.slidesGrid];
        }}
        onReachEnd={(swiper) => (swiper.snapGrid = [...swiper.slidesGrid])}
 >
`

Note that `slidesGrid` may be marked as unexistent in `SwiperClass `type.

**Comment by estebanrocca** [comment]
add and empy element at end works for me
