### ISSUE TITLE
Clobbers AddEvent because of duplicated IDs

### ISSUE THREAD

**Issue by bderblatter** [nolimits4web/swiper#3122]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: Swiper 4.2.0
* Platform/Target and Browser Versions: All modern browsers and OSs

### What you did
I put [AddEvent](https://www.addevent.com/add-to-calendar-button) code into a Swiper slide

```html
<div class="swiper-slide">
    <button class="addeventatc" data-intel="false">
        <span class="start">{$atc_start}"</span>
        <span class="end">{$atc_end}"</span>
        <span class="timezone">{$atc_timezone}"</span>
        <span class="title">{$atc_title}"</span>
        <span class="description">{$atc_description}"</span>
        <span class="location">{$atc_location}"</span>
        Add to Calendar
    </button>
</div>
```

### Expected Behavior
AddEvent shows add to calendar dialog when button is clicked

### Actual Behavior
Nothing happens when button is clicked

### How to fix
Detect IDs on elements and make cloned slides have unique IDs (including child nodes).  I know the ID issue has been brought up before.  IDs should generally not be used for styling, but IDs do need to be used for interactive elements (like labels for specific input fields).  In this case, AddEvent uses an ID to know where to append the dialog and which element to trigger to open the dialog.  If the IDs are duplicated, AddEvent breaks.

**Comment by nolimits4web** [comment]
This is how it works, consider those duplicate ids in your code
