### ISSUE TITLE
[Bug] Autoplay stop on resize window

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [nolimits4web/swiper#3123]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0.
* Platform/Target and Browser Versions: Debian 9 - Firefox Quantum 60.7.1-ESR
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/1rytecaw/
### What you did
When auto play is active and browser window size was change it stop and does not working.
### Expected Behavior
Auto play working like before...
### Actual Behavior
Auto play stop

**Note** : This bug was [reported before](https://github.com/nolimits4web/Swiper/issues/574) but won't fixed and closed with out date reason.

**Comment by AmirHosseinKarimi** [comment]
Hi @nolimits4web , Can you please tell me the reason of closing this issue?

**Comment by nolimits4web** [comment]
Because it was fixed
