### ISSUE TITLE
SlidesPerGroup Change

### ISSUE THREAD

**Issue by sethchhim** [nolimits4web/swiper#3125]
* [x] feature-discussion (RFC)

* Swiper Version: 4.5.0

Hello, I am using your swiper with `slidesPerView` set to `auto`. My request is to set `slidesPerGroup` dynamically as sometimes it will need to be a value of 1, 2, or 3 depending on the width of the current slides.

I have tried to set params and updating the swiper on every slide change. The end result behavior is correct but the update is very heavy and lags the swiper very much: 

```
// onSlideChange
swiper.params.slidesPerGroup = getNextPositionOffset()
swiper.updateSlides()
```

Do you have any advice on how to update `slidesPerGroup` dynamically?

Also, I'm looking for something along the lines of `slidesPerGroupNext` and `slidesPerGroupPrevious` to achieve complete dynamic control.

Thank you for consideration, any help would be appreciated!

**Comment by fritzmg** [comment]
@sethchhim why did you close this?

This is still a relevant feature discussion. We frequently use `slidesPerView: 'auto'` but usually also want a `slidesPerGroup: 'auto'`, which is currently not possible. In our case, only advancing one slide, when there is e.g. 6 slides visible with the current viewport is not really useful.

**Comment by sethchhim** [comment]
@fritzmg I did not find resolution. I closed it because I switched framework and thought this issue only affected me. Hope you can figure it out.

**Comment by fritzmg** [comment]
Well it's a feature discussion ;)

**Comment by guille-alibrate** [comment]
I also find this feature useful. Clearly, `slidesPerGroup` should have an *auto* option.  And take `slidesPerView` as reference.

Please reopen .

**Comment by guille-alibrate** [comment]
It's an old request, btw
https://github.com/nolimits4web/Swiper/issues/338
