### ISSUE TITLE
Support for Angular 7, 8

### ISSUE THREAD

**Issue by ayoubkhan558** [nolimits4web/swiper#3129]
Support for Angular 7, 8

**Comment by SilviaTormo** [comment]
I need support for Angular 8 also.

**Comment by SouengKimmeng** [comment]
+ 1

**Comment by floodedcodeboy** [comment]
@ayoubkhan558 @SilviaTormo @SouengKimmeng have you tried using `ngx-swiper-wrapper`? It has allowed us to use this library in angular 5-8 projects.

**Comment by floodedcodeboy** [comment]
I would however like to point out that even if you do use [ngx-swiper-wrapper](https://github.com/zefoy/ngx-swiper-wrapper) with Angular 8 - You will struggle to make this work if you have to support IE11 (non-modern browsers) as the Angular 8 compiler does not transpile and compile the Dom 7 library (which is a hard dependency of Swiper) out of the box.

I've seen a few posts regarding this issue : https://github.com/nolimits4web/swiper/issues/2282 for instance where @nolimits4web has simply told people to update their webpack configs and then closed the thread. (I do fear a similar fate to this thread). 

So in response to 'just update your webpack config' :
Angular 8 no longer allows you to eject the webpack config, making the use of custom webpack configs no minor feat. 

I would also like to emplore @nolimits4web to stop censoring people with real issues with this library and consider a fix or at least enter a discussion or some discovery.

**Comment by Antonio-Laguna** [comment]
I really hope this can move forward since it's a common issue for all wrapper libs.

**Comment by floodedcodeboy** [comment]
@Antonio-Laguna I'm so glad that you agree. It would also be very helpful if you could include examples of any issues you might be having with these libraries.

**Comment by Antonio-Laguna** [comment]
Libraries aren't an issue itself but rather that the code that's served isn't transpiled. Since they all serve proper ESM files with no dependencies transpiled and such, webpack won't transpile so it just fails
