### ISSUE TITLE
Lazy Loading + centeredSlides doesn't load 3rd image, even when in view

### ISSUE THREAD

**Issue by maximilianschmidt** [nolimits4web/swiper#3136]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.5.0
* https://codepen.io/thisismx/pen/WqKZRB

### What you did
Create Swiper with Lazy Loading for the slides background images (`data-background` Parameter). The parameter `centeredSlides` is set to `true` for layout reasons. 

### Expected Behavior
The Swiper will load all Images visible to the user.

### Actual Behavior
When using Swiper with `lazy: true;` and `centeredSlides: true;`, the third image doesn't get lazy-loaded, even though it is in view. I fiddled around with `loadPrevNextAmount` but to no avail. In my CodePen you can see two Swiper Elements, the top one with `centeredSlides: true` and the bottom one with `centeredSlides: false`. 

The third Image on the Top Slider hasn't been loaded yet (see also the missing `swiper-lazy-loaded` class on this particular element). On the Bottom Slider, everything works as expected. 

I am using the coverFlow effect in my example, feel free to comment out the corresponding lines (15 - 20) to see the same bug affecting the swiper in "normal" mode without any effects.

**Comment by jamaluddinrumi** [comment]
i experience this in safari desktop until now
