### ISSUE TITLE
fade effect navigation fast double click

### ISSUE THREAD

**Issue by destimon** [nolimits4web/swiper#3141]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 3.4.2.
* Platform/Target and Browser Versions: Windows, Google chrome.

### What you did
```
        loop: true, 
        speed: 1000,
        slidesPerView: 1,
        slidesPerGroup: 1,
        spaceBetween: 0,
        effect: 'fade',
        autoplay: {
          delay: 8000,
          disableOnInteraction: false,
        },
        fadeEffect: {
          crossFade: true,
        },
```

I trying to click immediately on swiper-button-prev/next twitce, to change slide immediately twice without delay

### Expected Behavior
Fast change slide without delay due fast twice(or more) click,

### Actual Behavior
I must wait to delay end to be able to change slide again

**Comment by nolimits4web** [comment]
This is requirement for `loop: true`. In loop mode, it is not possible to switch slides during transition
