### ISSUE TITLE
Too many slides? Page with ~90 slides doesn't open on mobile

### ISSUE THREAD

**Issue by justinasdmt** [nolimits4web/swiper#3144]
Hello,

I use this slider on many pages and everything is OK. But there is a gallery page which has 93 photos that are used with the Swiper. This page works perfectly on desktop but it simply doesn't open on mobile (iPhone Xs and iPhone 5s / Safari and Chrome). The phone shows the error message "A problem repeatedly occured on www..." and then the white screen with the message:

> This webpage was reloaded because a problem occurred

I tried reducing the number of photos to about ~30 and then it works but lacks performance. At about ~50 photos and more the page doesn't open.

I believe it's somehow related to performance / memory? Has anyone encountered anything similar?

Here's the swiper config I use:

```
    var lightboxSwiper = new Swiper ('.lightbox .swiper-container', {
        speed: 800,
        effect: 'coverflow',
        centeredSlides: true,
        slidesPerView: 'auto',
        coverflowEffect: {
            rotate: 50,
            stretch: -90,
            depth: 100,
            modifier: 1,
            slideShadows : false,
        },
        preloadImages: false,
        lazy: {
            loadPrevNext: true,
            loadPrevNextAmount: 3
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
        loop: true,
        keyboard: {
            enabled: true,
        },
        pagination: {
            el: '.swiper-pagination',
            type: 'fraction',
        }
    })
```
The same code works good on pages with less photos.

**Comment by justinasdmt** [comment]
OK, I partly figured it out. For mobile I set "effect" to "slide" and it works. The coverflow effect seems to eat too much memory on mobile even if not used yet.

**Comment by zhangchao828** [comment]
+1

**Comment by zhangchao828** [comment]
@justinasdmt I set "effect" to "slide" but not work for me

**Comment by nolimits4web** [comment]
Use virtual slides
