### ISSUE TITLE
Add delay before switching slide

### ISSUE THREAD

**Issue by PubliAlex** [nolimits4web/swiper#3153]
Hello,

It would be a nice addition to allow to define a delay between 2 slide transition. The idea behind that is to have time to make some CSS animation before switching slide, without being obliged to use virtualTranslate and reinvent all the wheel.

something like : 

    var mySwiper = new Swiper('.swiper-container', {
      speed: 400,
      spaceBetween: 100,
      delayBetweenSlides: 700,
    });

Thanks

**Comment by nolimits4web** [comment]
You can just set `transition-delay` property to swiper-wrapper to get desired effect

**Comment by mgeorgievsky** [comment]
Seems like it's not working in 6.x version. How can i do it in 6.x?
