### ISSUE TITLE
RFC proposal: detect mousewheel deceleration for smoother sticky snapping

### ISSUE THREAD

**Issue by justingrant** [nolimits4web/swiper#3154]
Swiper today handles modern trackpads (MacBooks, Surface laptops, etc) via the `mousewheel` option. But when also using `freeMode` and `freeModeSticky`, there's an awkward delay between when the momentum scroll stops and when Swiper snaps to the nearest item.  I want to discuss a possible solution to that awkward delay. I'd consider building a PR for this solution if there's interest.

Here's the idea: momentum scrolling follows a predictable pattern of `wheel` events that are sent during deceleration at the end of a momentum scroll. Instead of the current solution which waits for a timeout after the last wheel event, instead could we detect the deceleration event pattern, bail out early of the system-managed scrolling, and snap to the desired position a few hundred milliseconds earlier than the current implementation can?  

Even if this works as intended, it probably wouldn't be as smooth as the touch solution, but it should be smoother and faster than the current implementation.  As part of the solution I also have an idea how to reduce the "post-scroll" lockout delay discussed here: https://github.com/nolimits4web/swiper/issues/2086#issuecomment-326455917.

Here's a real-world example from a simple React app I built that logs `wheel` events to the console during a momentum scroll. When a momentum scroll is slowing down, the `deltaX` (or `deltaY` for vertical scrolling) of `wheel` events follow a predictable pattern, at least on my 2015 MacBook Pro: 
* There's ~30 events sent in the final 500 msecs of the momentum scroll
* An event is sent every 16ms tick (or almost every tick) 
* `DeltaX` gradually decreases while the number of events for each ΔX value gradually increases: 
   * 1-2 events each for ΔX 9 through 5
   * 3-4 events each for ΔX 4 through 2
   * 8 events for ΔX 1

Below is a table showing these events. The first number in each row is the number of milliseconds before the last event, measured using  `Date.now()`.

```
Time |  ΔT | ΔX
-500 | -16 | 9
-484 | -17 | 8
-467 | -17 | 8
-450 | -17 | 7
-433 | -17 | 6
-416 | -17 | 6
-399 | -16 | 5
-383 | -16 | 5
-367 | -17 | 5
-350 | -17 | 4
-333 | -16 | 4
-317 | -17 | 4
-300 | -17 | 3
-283 | -18 | 3
-265 | -15 | 3
-250 | -17 | 3
-233 | -17 | 2
-216 | -17 | 2
-199 | -15 | 2
-184 | -17 | 2
-167 | -17 | 1
-150 | -17 | 1
-133 | -16 | 1
-117 | -18 | 1
 -99 | -16 | 1
 -83 | -34 | 1
 -49 | -16 | 1
 -33 | -33 | 1
   0 |   0 | 1
```

It'd take some experimentation to get it right, but a starting point for a detection algorithm could be something like: 
* when wheel scrolling starts, store a rolling window of the last N (N=20?) `wheel` events
* do all of those events have decreasing or same ΔX?
* did all events arrive in the last M (M=300?) msecs?
* does the earliest event have a ΔX that's at least P (P=2?) larger than the most recent event?
* does the latest event have a ΔX that's smaller than Q (Q=5?) pixels?

If the answer to all questions above is "yes" then:
* programmatically scroll to the nearest snap point (current Swiper behavior)
* ignore wheel events for 300 msecs after the last `wheel` (current Swiper behavior?), UNLESS...
   * ...a new `wheel` event arrives with a larger ΔX than the most recent event received during deceleration, which indicates that the user has started another scroll.  In this case, clear the timeout and start scrolling.

If for some reason (e.g. overloaded CPU) the algorithm doesn't get triggered, simply fall through to the current behavior.

Does something like this seem like it might work?  If yes, would you be interested in a PR for it?  Also, let me know if you have any advice about the problems inherent in this approach, because you probably know this problem space much better than I do.  Thanks!

### This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: MacOS (Chrome, Safari, Firefox-- all latest version) 
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/justingrant/pen/JgoPWP

### What you did
Scrolled a `Swiper` using a MacBook Pro trackpad with `mousewheel`, `freeMode`, and `freeModeSticky` enabled.

### Expected Behavior
Smooth deceleration to a snap point, like on a touch device.

### Actual Behavior
Smooth deceleration to a non-snap point, then a short delay, then a smooth scroll to the nearest snap point, and finally a significant delay before I can scroll again with the trackpad.

**Comment by nolimits4web** [comment]
The most annoying thing here for me was the inability to actually differentiate user scroll and momentum scroll as basically use can scroll with the same effect/deceleration as momentum scroll. But if you can send PR, you are welcome and let's go for it and try, maybe really we will have a better result

**Comment by justingrant** [comment]
> But if you can send PR, you are welcome and let's go for it and try, maybe really we will have a better result

Hi @nolimits4web - Take a look at #3304.  I've been using it for a few months in my own projects and I'm pretty happy with the results.  Let me know what you think.

P.S. - Sorry for bombarding you with 4 PRs today!  The other three are simpler: 2 bug fixes and one minor build change suggestion.
