### ISSUE TITLE
mySwiper.updateSlidesClasses() is not working

### ISSUE THREAD

**Issue by iamjonasmarlo** [nolimits4web/swiper#3160]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Windows 10 / Google Chrome

### What you did
I've try to control a Swiper-Slider with ScrollMagic. Swiper is running in freemode, so I'm not able to use some of the native methods like mySwiper.slideNext(speed, runCallbacks). So I have to manipulate the transform-property of the **swiper-wrapper** element. Everything works fine but the class for the active slide is not given to the correct element. So I'm using the native method mySwiper.updateSlidesClasses().

### Expected Behavior
The slider is moving within the actual scroll position (done by ScrollMagic). The slide, which is currently in the viewport, should get the native active class.

### Actual Behavior
The first element in the slider stays active.

### My Code

```
var projectSlider = new Swiper ('.project-slider__container', {
    loop: false,
    speed: 800,
    slidesPerView: 'auto',
    centeredSlides: false,
    freeMode: true,
    mousewheel: false,
    simulateTouch: true,
    virtualTranslate: false,
});

var projectSliderMovement = new ScrollMagic.Scene({
    triggerElement: ".project-slider",
    triggerHook: 0,
    duration: '400%'
})
.on("progress", function (e) {projectSlider.updateSlidesClasses()})
.setTween('.project-slider .swiper-wrapper', {'transform': 'translate3d(-3000px, 0px, 0px)'})
.addTo(controller)
```

**Comment by nolimits4web** [comment]
Not much chances here. Calling `updateSlidesClasses` is not enough as there are many more things happen under the hood. You may want to learn source code to understand better what needs to be called
