### ISSUE TITLE
Ability to slideNext/Prev multiple slides or control slideToLoop direction

### ISSUE THREAD

**Issue by JenBerry** [nolimits4web/swiper#3161]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: All modern desktop and mobile browsers
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/jenberry/pen/WVRxJb

### What you did
See my codepen - I have multiple slides visible, with looping. I want next and previous buttons that slide a set number of slides in looped mode. I don't want to use `slidesPerGroup` because I want touch events to still be able to slide to any slide. Using `mySwiper.slideToLoop(mySwiper.realIndex + 5)` and `mySwiper.slideToLoop(mySwiper.realIndex - 5)` almost achieves what I want except that the animation sometimes runs in the wrong direction. Is there any way around this?

### Expected Behavior
When I click next it slides 5 slides to the right each time
When I click prev is slides 5 slides to the left each time

### Actual Behavior
The 5th time I click next, the animation slides to the left
The 2nd time I click prev, the animation slides to the right

**Comment by mbibko** [comment]
It will be great if this can be fixed
