### ISSUE TITLE
Feature Request: Staggering animation of multiple swiper slides

### ISSUE THREAD

**Issue by nicmare** [nolimits4web/swiper#3162]
Hi there,

it's a little bit tough to describe but i will try:
has someone any idea how to slide in next slides one by one? 
assuming we have three slides per view. Now when i hit next button this would happen:
1. first slide slides out
2. second slide slides out
3. third slide slides out
4. at the same time then the fourth slide slides in and the 5th and 6th…

Each animation timing overlaps with the previous slide animation. otherwise it would take to long. 
Simple example of a stagger animation done by greensock: 
https://codepen.io/GreenSock/pen/gifIe
Why do we want this? Because nobody else have it. This would be a very unique and dynamic animation.

thank you

**Comment by nolimits4web** [comment]
Closing as not the issue
