### ISSUE TITLE
Clicking next slide goes to previous and clicking previous goes to next

### ISSUE THREAD

**Issue by rgllm** [nolimits4web/swiper#3167]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: All

### What you did

I've a swiper slide with the following configurations:

```
	slidesPerView: "auto",
    centeredSlides: true,
    preloadImages: true,
    loopedSlides: 20,
    slideToClickedSlide: true,
    preventClicks: false,
    preventInteractionOnTransition: true,
    preventClicksPropagation: true,
    loop: true,
    longSwipes: false,
    autoplay: {
      delay: 5000,
      disableOnInteraction: true,
    },
    spaceBetween: 30,
```

### Expected Behavior

When I clicked the next slide is expected this to become the active slide.

### Actual Behavior

Sometimes I click multiple times in the previous and next slides, Swiper does not work as expected. Instead, for example when I click next it goes to previous and when I click previous It goes to next. With swipe everything works as expected.

**Comment by rgllm** [comment]
@nolimits4web I think this is related with #1448 and #1456. Could you please help me?

**Comment by beaulac** [comment]
Experiencing the same issue on 4.5.0 with the following config:

```js
{
  nested: true,
  allowTouchMove: isTouchCapable,
  speed: 500,
  pagination: {
    el: '.home-hero-swiper__pagination',
    type: 'fraction'
  },
  navigation: {
    nextEl: '.home-hero-swiper__btn-next',
    prevEl: '.home-hero-swiper__btn-prev'
  }
}
```

**Comment by rgllm** [comment]
@nolimits4web any news on this topic? This is something that will be fixed?

**Comment by mhshakouri** [comment]
@rgllm did you notice the above message by @beaulac ?
If yes please provide a link.
Is your website RTL?
in that case make sure the class you see is (next - prev) not the image icon

let me know if you plan to make a live demo of your problem

**Comment by nolimits4web** [comment]
Closing as not the issue and behavior described correctly by @beaulac
