### ISSUE TITLE
Centering with fixed width

### ISSUE THREAD

**Issue by gregurco** [nolimits4web/swiper#3168]
Hello!

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: Ubuntu Chrome / Firefox
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/wvps1h2t/1/

### What you did

Configure swiper with fixer width and centered.

```
width: 50,
centeredSlides: true,
```

![Selection_999(020)](https://user-images.githubusercontent.com/4052904/62765987-0863d100-ba9a-11e9-8428-1cb15700bc89.png)

### Expected Behavior
Centering will be applied.

### Actual Behavior
Slides starts from left side and centering is ignored.

Thanks, Vlad.

**Comment by nolimits4web** [comment]
Set `slidesPerView: 'auto'` and `.swiper-slide { width: 50px }` in CSS https://jsfiddle.net/sj75aqhp/
