### ISSUE TITLE
Autoplay does not work after hide / show

### ISSUE THREAD

**Issue by NeptuneG** [nolimits4web/swiper#3170]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: OSX / iOS, Android, Chrome, Safari
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/NeptuneG/pen/eYOpEEM

### What you did

1. Hide `<div>` including an autoplay swiper then show a modal.
2. Close the modal and show the hidden `<div>` include the swiper then call `swiper.update()` .

- I tried the workaround mentioned in [Issue #2073](https://github.com/nolimits4web/swiper/issues/2073#issuecomment-296546690), but still simply not work.
 
### Expected Behavior

- The swiper is rendered and continue autoplay from the slide shown before hiding the `<div>` .

### Actual Behavior

- The swiper was rendered but autoplay stopped.

**Comment by saltb0rn** [comment]
You may have a try like this to fix it,

          $(function () {
             $('#modalTrigger').click(function () {
                 swiper.autoplay.stop();
                 toggleModal();
             });
             $('#modalReturnBtn').click(function () {
                 toggleModal();
                 swiper.autoplay.start();
                 swiper.update();
             });
         });

**Comment by NeptuneG** [comment]
@saltb0rn It seems to work! Thanks.
