### ISSUE TITLE
Potential fix to slideToClickedSlide loop issue.

### ISSUE THREAD

**Issue by jmckinnell** [nolimits4web/swiper#3171]
It seems that when both `slideToClickSlide` and `loop` is `true` there's an issue when you get to the end of the loop it doesn't populate duplicate slides.

Here's the line that's causing the issue, the if statement needs to be a bit better.
https://github.com/nolimits4web/swiper/blob/6b16107359b9e2e523eb03cc75bf4569940a22dd/src/components/core/slide/slideToClickedSlide.js#L31

Updating this line to this seems to solve the problem for both directions.
`} else if (slideToIndex >= swiperLength - slidesPerView || slideToIndex <= 0) {`

**Comment by robpop** [comment]
@jmckinnell you should prepare a pull request with your fix.

**Comment by GennadyK** [comment]
@jmckinnell   Thanks a lot for the fix. It works for me for 3 slides, but there is the same bug for the 4 slides - after the 5th click on the 2nd slide there is nothing in place of the last 4th slide ("swiper-slide swiper-slide-duplicate swiper-slide-duplicate-prev" is missing). Then one more click and it back. In inspector just before the 5th click:
1st:   class="swiper-slide swiper-slide-duplicate swiper-slide-active"
2nd:   class="swiper-slide swiper-slide-duplicate swiper-slide-next"
3rd:   class="swiper-slide swiper-slide-duplicate"
4th:   class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-prev"
