### ISSUE TITLE
Filtered Thumbnails Retain Original Slide Index

### ISSUE THREAD

**Issue by ConduciveMammal** [nolimits4web/swiper#3174]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0.
* Platform/Target and Browser Versions: Chrome 76.0.3809.100 on macOS Mojave

### What you did
I'm using image toggles to filter out slides from both thumbnails and gallery image using the following JS:

```js
thumbnailSlide.not(function () {
  return ($.inArray($(this), $(thumbsToKeep)) > -1);
}).removeClass('swiper-slide').hide();
$(thumbsToKeep).addClass('swiper-slide').show();

thumbnailSwiper.update();
```

### Expected Behavior
After filtering, clicking a thumbnail should change the primary gallery image.

### Actual Behavior
After filtering, clicking on any thumbnail will activate the very last slide and won't change from it. However, filtering again to the first set of slides will allow it to function properly again.

**Comment by nolimits4web** [comment]
Hidden slides are not supported
