### ISSUE TITLE
swiper slideTo() doesn't work

### ISSUE THREAD

**Issue by jeankhawand** [nolimits4web/swiper#3178]
Hey Guys,
I am currently facing an issue I have 3 slides div in my index.html
```
<div class="swiper-container">
  <div class="swiper-wrapper">
  <div class="swiper-slide slide1 noswipe">
           <div class="button">
           </div>
  </div>
  <div class="swiper-slide slide2 noswipe"></div>
  <div class="swiper-slide slide3 noswipe"></div>
  </div>
</div>
```

while in my main.js file 
```
var swiper = new Swiper('.swiper-container', {
        direction: 'vertical',
        noSwipingClass: 'noswipe'
    });
	$(".button").click(function(){
		setTimeout(function () {
			swiper.slideTo(1);
        }, 175);
	})
```

so all what I've made is just added in one of these slides a button that once clicked this button will move to another slide. This method didn't work and I used swiper.js documentation to check
```slideTo()``` which takes as parameters index, speed and runCallbacks . any help ?

Thanks In advance.

**Comment by Mamboleoo** [comment]
I just made this demo on JSFiddle and it does work.
https://jsfiddle.net/xtg51ny6/1/
Try to reproduce your issue somewhere online so we can check what's wrong with your project ;)
