### ISSUE TITLE
LoremPixel is down

### ISSUE THREAD

**Issue by Mamboleoo** [nolimits4web/swiper#3182]
Hey, I noticed the demos were using http://lorempixel.com/ as placeholder for the images.
http://idangero.us/swiper/demos/300-thumbs-gallery.html

Sadly LoremPixel is no more so it's probably time to switch for another service.

Here are two I'm suggesting: 
https://placebear.com
https://www.fillmurray.com

Any other suggestion?

**Comment by kukac7** [comment]
@Mamboleoo working well.

**Comment by Mamboleoo** [comment]
Hum indeed it seems to be "back" but very slow (at least from Belgium, I don't know where it's hosted)
The demo page is taking over a minute to load because of the images :/
![image](https://user-images.githubusercontent.com/6048794/63747687-02e2f500-c8a8-11e9-85b8-55a23480594e.png)
