### ISSUE TITLE
freeModeSticky doesn't clear it's timeout function when swiper instance is destroyed

### ISSUE THREAD

**Issue by thecontstruct** [nolimits4web/swiper#3189]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, FireFox, Safari.

### What you did
Running Swiper in an SPA and with `freeMode: true, freeModeSticky: true`. Swiping to scroll swiper sometimes triggers a page Back navigation which results in the Swiper instance being destroyed/cleaned up. 

### Expected Behavior
Swiper is destroyed and everything runs on as expected.

### Actual Behavior
Swiper crashes due to `freeModeSticky`'s setTimeout function that calls `slideToClosest()`. That function tries to access `this.params.speed` which doesn't exist anymore since it was destroyed.

Looks like this is another instance of https://github.com/nolimits4web/swiper/issues/1189 but for `freeModeSticky`. 

handler is in components/mousewheel/mousewheel.js line 170

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle with the issue
