### ISSUE TITLE
Cannot read property 'indexOf' of undefined swiper.js:7986

### ISSUE THREAD

**Issue by zt-117** [nolimits4web/swiper#3190]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: PC windows

### Expected Behavior
I want Thumbs Gallery, just like :https://idangero.us/swiper/demos/300-thumbs-gallery.html

### Actual Behavior
My demo works well when you first open the page. But if you press F5, it doesn't work well.
If you press control+shift+delete to delete cache or F12 disable cache, it works well, but only
for once, press F5 it doesn't work well again.

**Comment by evankford** [comment]
Was this fixed? Having this issue still. Or did you find another issue with your code?

**Comment by kronthto** [comment]
I think this/your issue may have been fixed in cf4a72d2f77528adc6da78f4edcf96602d7e1cad (v4.5.1)
