### ISSUE TITLE
Maintain image rotation when zoom is applied

### ISSUE THREAD

**Issue by N00nDay** [nolimits4web/swiper#3191]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.
* Platform/Target and Browser Versions: Chrome.

### What you did
I am currently using Swiper in react and using the react-id-swiper wrapper.  I am using the following parameters:

```
const params = {
  pagination: {
    el: ".swiper-pagination",
    type: "bullets",
    clickable: true
  },
  zoom: true,
  shouldSwiperUpdate: true,
  navigation: {
    nextEl: ".swiper-button-next",
    prevEl: ".swiper-button-prev"
  },
  getSwiper: s => (swiper = s),
  initialSlide: props.selectedItem,
  runCallbacksOnInit: true,
  on: {
    slideChange: () => {
      if (swiper) {
        if (swiper.realIndex !== undefined) {
          props.updateSelectedItem(swiper.realIndex);
        }
      }
    }
  }
};
```

Nothing too crazy here but mainly need to see that I am setting "zoom" to true.  My slide structure is as follows:

```
<div
  key={image._id + key}
  className="slide-container"
  data-key={key}
  data-id={image._id}
  data-url={`${image.src}`}
>
  <div
    className="swiper-zoom-container"
  >
      <img
        alt="something"
        src={image.src}
        className="slide-image"
        style={{
          transform: "rotate(0) scale(1) translate3d(0px, 0px, 0px)"
        }}
      />
  </div>
</div>
```
I have a function built that will rotate my image 90 degrees to the right or the left depending on if you click rotate right or rotate left which works perfectly.  This function also changes the image to fit the screen as large as it can without breaking the images original aspect ratio.  Again works perfectly.  My issue is that when zoom is initiated the "transform" property is overwritten with the new scale property but none of the original transform properties (ie. rotate) are retained. 

I am currently retaining the scale property when I am rotating the image, meaning once zoomed I can rotate all I want but when I zoom back out the image rotates back to its initial rotate state of 0.  Usability is there but user experience isn't good when an image is moving when that movement was not initiated by them.

### Expected Behavior
The expectation is that when zoom is initiated/uninitiated that the image would retain all former transform properties minus the scale property.

### Actual Behavior
All original transform properties are not retained thus rotating the image back to its initial rotation.

**Comment by nolimits4web** [comment]
I guess you need wrap image with extra custom container or put it inside of zoom container. Because custom transforms can't be maintained
