### ISSUE TITLE
Make multi row swiper where slides have different heights look like Masonry grid?

### ISSUE THREAD

**Issue by siavashgolabi** [nolimits4web/swiper#3195]
I tried to set a multi row swiper with this settings:
`let Swiper = new Swiper('.swiper', {
    autoHeight: true,
    slidesPerView: 4,
                slidesPerColumn: 2,
                slidesPerGroup: 4,
                slidesPerColumnFill: 'row',
                spaceBetween: 25,
                }
            });`
slides have different heights,
Actual Behavior :
![image](https://user-images.githubusercontent.com/46656481/64093429-86e82180-cd6d-11e9-8084-3f973eb908a8.png)

how can i remove vertical space between slide with smaller height and make it look like masonry grid?
Desired Behavior:
![image](https://user-images.githubusercontent.com/46656481/64093454-a7b07700-cd6d-11e9-959c-b24da7103ef7.png)

**Comment by nolimits4web** [comment]
This should be possible in v5 with `slidesPerColumnFill: 'column'`
