### ISSUE TITLE
Zoomed image looks blurry on iOS

### ISSUE THREAD

**Issue by acromatica** [nolimits4web/swiper#3198]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v4.5.0
* Platform/Target and Browser Versions: IOS
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/acromatica/pen/VwZydyR

### What you did
Add big image to swiper, zoom it in Safari or Chrome on iOS.  

### Expected Behavior
Zoomed image should look sharp.

### Actual Behavior
Zoomed image looks blurry no matter its original size. In codepen example image is 2250x2250px, but still looks blurry when zoomed with default multiplier (3) on 375px wide screen.

<img width="375" alt="iPhone-Safari" src="https://user-images.githubusercontent.com/13260691/64424043-e745ce80-d09f-11e9-8bd0-7f3db6106235.jpeg">
<img width="399" alt="desktop-Chrome" src="https://user-images.githubusercontent.com/13260691/64424071-f75dae00-d09f-11e9-9066-9e95111bd749.png">

**Comment by nolimits4web** [comment]
Can't do much with it, i guess is more about how browser render things

**Comment by acromatica** [comment]
Sure, but zoom feature kinda looses its purpose this way. Rather than seeing all the details in zoomed in area you get it all blurry.
If you change the size of the image instead of zooming it in with `transform: scale(X)` it won't get blurry.

**Comment by aaa930811** [comment]
> Sure, but zoom feature kinda looses its purpose this way. Rather than seeing all the details in zoomed in area you get it all blurry.
> If you change the size of the image instead of zooming it in with `transform: scale(X)` it won't get blurry.

so can we use a setup item to control which zoom mode to use

**Comment by JeffJassky** [comment]
Anybody have luck with fixing this?

**Comment by acromatica** [comment]
@JeffJassky @aaa930811 

I ended up using a placeholder element and adding background with zoomed in image to it. Here's my code:

```
<style>
.my-swiper-container {
    touch-action: manipulation
}

.my-swiper-container .swiper-slide-zoomed img {
    opacity: 0
}

.img--placeholder {
    position: absolute;
    top: 50%;
    left: 50%;
    background-position: 50% 50%;
    background-repeat: no-repeat;
    background-size: contain;
    transform: translate3d(-50%, -50%, 0);
    pointer-events: none;
    -webkit-touch-callout: none;
    z-index: -1
}

.img--placeholder::before {
    content: '';
    display: block;
    padding: 80% 0 0 /* Proportion of my image, in my case it's 375x300 px */
}

.zoom--loading::after {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    border: 2px solid #fff;
    border-right-color: transparent;
    border-radius: 50%;
    width: 24px;
    height: 24px;
    margin: -12px 0 0 -12px;
    animation: spin 1s linear infinite
}

@keyframes spin {
    0% {
        transform: rotate(0deg)
    }

    100% {
        transform: rotate(360deg)
    }
}
</style>

<div class="swiper-container my-swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <div class="swiper-zoom-container">
                <span class="img--placeholder"></span>
                <img src="small_image_1.jpg" data-srczoom="big_image_1.jpg" alt="" />
            </div>
        </div>
        <div class="swiper-slide">
            <div class="swiper-zoom-container">
                <span class="img--placeholder"></span>
                <img src="small_image_2.jpg" data-srczoom="big_image_2.jpg" alt="" />
            </div>
        </div>
    </div>
</div>

<script>
    let swiper = new Swiper('.my-swiper-container', {
        zoom: {
            maxRatio: 5.3,
        },
        on: {
            zoomChange: function (scale, imageEl, slideEl) {
                let placeholder = slideEl.querySelector('.img--placeholder');

                placeholder.style.width = scale * 100 + '%';

                if(!imageEl.classList.contains('src--updated')) {
                    slideEl.classList.add('zoom--loading');
                    let img = new Image();

                    img.onload = function() {
                        imageEl.classList.add('src--updated');
                        slideEl.classList.remove('zoom--loading');
                        imageEl.src = imageEl.dataset.srczoom;
                        placeholder.style.backgroundImage = 'url(' + imageEl.dataset.srczoom + ')';
                    };

                    img.src = imageEl.dataset.srczoom;
                }
            }
        }
    });
</script>
```

**Comment by ColossalisT** [comment]
> Anybody have luck with fixing this?

Hi, I use swiper@5.3.7 in react project.
I have my solution about this, maybe it works well in your project either. 
I searched a lot for this problem, it seems like `translate3d` cannot work well with `scale` on iOS.
### Workaround
Replaced some `translate3d(0, 0, 0)` with `translate(0, 0)` of `gesture.$imageEl` in file `node_modules\swiper\js\swiper.js`.
In version @5.3.7, these changes are in L6448, L6467, L6624, L6740, L6763 .
![image](https://user-images.githubusercontent.com/14233681/83725218-25ded880-a674-11ea-9287-42bd91cdbd8e.png)
![image](https://user-images.githubusercontent.com/14233681/83725257-342cf480-a674-11ea-8b8e-b01b808372f3.png)
![image](https://user-images.githubusercontent.com/14233681/83725273-3d1dc600-a674-11ea-989e-d95d8db982ac.png)
![image](https://user-images.githubusercontent.com/14233681/83725292-4444d400-a674-11ea-8f40-dac66b06a764.png)
![image](https://user-images.githubusercontent.com/14233681/83725312-4dce3c00-a674-11ea-9bfb-9e6c0fd6e1b7.png)

After do that, pictures looked sharply on my iPhone6p, iphone6, iPhoneX and iPad Air 2.
BTW, in swiper@5.3.7, it better to set `maxRatio` much than 3 if your pictures need to zoom in a large scale.
I hope that can help you.

**Comment by aaa930811** [comment]
> > Anybody have luck with fixing this?
> 
> Hi, I use swiper@5.3.7 in react project.
> I have my solution about this, maybe it works for you.
> I searched a lot for this problem, it seems like `translate3d` cannot work well with `scale` on iOS.
> 
> ### Workaround
> Replaced some `translate3d(0, 0, 0)` with `translate(0, 0)` of `gesture.$imageEl` in file `node_modules\swiper\js\swiper.js`.
> In version @5.3.7, these changes are in L6448, L6467, L6624, L6740, L6763 .
> ![image](https://user-images.githubusercontent.com/14233681/83725218-25ded880-a674-11ea-9287-42bd91cdbd8e.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725257-342cf480-a674-11ea-8b8e-b01b808372f3.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725273-3d1dc600-a674-11ea-989e-d95d8db982ac.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725292-4444d400-a674-11ea-8f40-dac66b06a764.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725312-4dce3c00-a674-11ea-9bfb-9e6c0fd6e1b7.png)
> 
> After do that, pictures looked sharply on my iPhone6p, iphone6, iPhoneX and iPad Air 2.
> BTW, in swiper@5.3.7, it better to set `maxRatio` much than 3 if your pictures need to zoom in a large scale.
> I hope that can help you.

This problem begin from version 3.I used the same method to solve the problem at that time

**Comment by ColossalisT** [comment]
> > Anybody have luck with fixing this?
> 
> Hi, I use swiper@5.3.7 in react project.
> I have my solution about this, maybe it works for you.
> I searched a lot for this problem, it seems like `translate3d` cannot work well with `scale` on iOS.
> 
> ### Workaround
> Replaced some `translate3d(0, 0, 0)` with `translate(0, 0)` of `gesture.$imageEl` in file `node_modules\swiper\js\swiper.js`.
> In version @5.3.7, these changes are in L6448, L6467, L6624, L6740, L6763 .
> ![image](https://user-images.githubusercontent.com/14233681/83725218-25ded880-a674-11ea-9287-42bd91cdbd8e.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725257-342cf480-a674-11ea-8b8e-b01b808372f3.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725273-3d1dc600-a674-11ea-989e-d95d8db982ac.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725292-4444d400-a674-11ea-8f40-dac66b06a764.png)
> ![image](https://user-images.githubusercontent.com/14233681/83725312-4dce3c00-a674-11ea-9bfb-9e6c0fd6e1b7.png)
> 
> After do that, pictures looked sharply on my iPhone6p, iphone6, iPhoneX and iPad Air 2.
> BTW, in swiper@5.3.7, it better to set `maxRatio` much than 3 if your pictures need to zoom in a large scale.
> I hope that can help you.

This method worked 12 days ago. But today it reproduced on my iOS devices even if I modified as that.
