### ISSUE TITLE
Why keep closing un-transpilation issues?

### ISSUE THREAD

**Issue by Antonio-Laguna** [nolimits4web/swiper#3199]
This is a (multiple allowed):
* [ ] bug
* [X] enhancement
* [X] feature-discussion (RFC)

I made an issue long ago with ESM issues: https://github.com/nolimits4web/swiper/issues/3073 today I discover I have an issue using React Id Swiper because of this very same issue. Not only that but this issue is happening for more people https://github.com/kidjp85/react-id-swiper/issues/273

What surprises me is the fact that this was reported and the issue (3047) was deleted too which seems odd enough. 

So, my question is why do you keep silencing these issues when they are real and they make using your library for older browsers a nuisance? I assume you don't want that as, otherwise, you wouldn't have continued with Swiper this long.

Can we move forward and try to fix this situation? If not, what's preventing it from happening?

Thanks.

**Comment by nolimits4web** [comment]
There is nothing to fix and there is no situation. Is it so hard to add these few lines to webpack config?
```
module: {
  rules: [
    {
      test: /\.(js|jsx)$/,
      use: 'babel-loader',
      include: [
        resolvePath('node_modules/swiper'),
        resolvePath('node_modules/dom7'),
        resolvePath('node_modules/ssr-window'),
      ],
    },
    ...
  ...
}
```
Or import UMD bundle instead.

What is the issue? ES modules will not be transpiled here, and main reason for this is tree-shaking, transpiling classes will make it not tree-shakeable.
