### ISSUE TITLE
Swiper slide height -> Make initial height same as the slide with the biggest height

### ISSUE THREAD

**Issue by vedran-korponajic** [nolimits4web/swiper#3200]
I have a swiper with expandible content -> Like this
<img width="1226" alt="Screen Shot 2019-09-10 at 9 52 01 AM" src="https://user-images.githubusercontent.com/43841707/64594649-b839a080-d3b0-11e9-887d-a0ca6dd1bd4f.png">

As you see, the height is not the same because some titles are longer. Is there a build in way to adapt the height of all slides to the highest one? I tried setting height: auto for the swiper-slide, but that only produced more bugs.
When show more is clicked the height will be different, that is ok, but when the page is loaded the height needs to be the same for all slides.

Tried using autoHeight, also did nothing.

**Comment by mrvonwyl** [comment]
@vedran-korponajic I have the same issue. What is your solution?
