### ISSUE TITLE
Virtual Slides: First Slide Not Displayed When initialSlide Set to '0'

### ISSUE THREAD

**Issue by Jumble123** [nolimits4web/swiper#3208]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0 & 4.5.1
* Platform/Target and Browser Versions: macOS Mojave 10.14.6, Safari 12.1.2

### What you did
Set initialSlide using a variable whose value was the string '0'.

To reproduce the issue, start with the file at https://github.com/nolimits4web/swiper/blob/master/demos/410-virtual-slides.html and add:
* "var initSlide = '0'" before the line beginning "var swiper = "
* " initialSlide: initSlide," after the line beginning "var swiper = "

### Expected Behavior
The first slide should be displayed (notwithstanding the fact that initialSlide should really be set with a numeric value). After all:
* '0' works with non-virtual slides
* a numeric string greater than '0' works like the equivalent number with both virtual and non&#8209;virtual slides.

### Actual Behavior
No slide is displayed initially:

<img width="876" alt="InitialSlideNotShown" src="https://user-images.githubusercontent.com/44160279/64952582-a5bfdb00-d878-11e9-8a05-ae8439118f51.png">

When the next button (the right arrow) is clicked, Slide 1 comes into view momentarily before Slide 2 is displayed.

**Comment by nolimits4web** [comment]
`initialSlide` must be a `Number`

**Comment by Jumble123** [comment]
Shall we call it an enhancement instead? I was going to propose a simple one-line change.
