### ISSUE TITLE
Swiper Minified JS not loading on Chrome Mobile 

### ISSUE THREAD

**Issue by tomrobst** [nolimits4web/swiper#3210]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.1 (via NPM)
* Platform/Target and Browser Versions: Chrome mobile on Android (76.0.3809.132)
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
Using the script tag with swiper.min.js does not load on Chrome on Android (but works fine on Firefox and Chrome on desktop).

### Expected Behavior
Swiper should load and initialise correctly.

### Actual Behavior
Swiper does not load. Gives error in remote chrome debugging console:
Uncaught SyntaxError: missing ) after argument list (swiper.min.js:12)
Uncaught ReferenceError: Swiper is not defined (this is in the site specific JS code).

Clicking on the link to the line in Chrome DevTools goes to this line:
isSafari:(s=J.navigator.userAgent.toLowerCase(),0<=s.indexOf("safari")&&s.indexOf("chrome")<0&&s.indexOf("android")<0),isUiWebView:/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/i.test(J.nav

It seems there is a ')' missing at the end?

Thanks!
Tom
--

**Comment by DanielRuf** [comment]
Hi @tomrobst,

Please provide a codepen which reproduces this.
