### ISSUE TITLE
Syntax error in latest version

### ISSUE THREAD

**Issue by ghaiat** [nolimits4web/swiper#3211]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 5.0.0.
<img width="904" alt="Screenshot 2019-09-17 at 14 23 24" src="https://user-images.githubusercontent.com/5446909/65045516-da09c900-d956-11e9-8c86-bc0b6f583098.png">

all the esm files have a syntax issue for the translate function

**Comment by ghaiat** [comment]
@nolimits4web thanks for the quick fix.

would you consider merging a pr to add support for shadow dom in swiper ? we really need it and we can upgrade the code

**Comment by nolimits4web** [comment]
@ghaiat if you send it, then sure will merge it ;)

**Comment by ghaiat** [comment]
@nolimits4web here you go , let me know what you think
https://github.com/nolimits4web/swiper/pull/3215
Cheers
