### ISSUE TITLE
Swiper virtual mode -> append prepend not working as expected

### ISSUE THREAD

**Issue by stefanholzapfel** [nolimits4web/swiper#3216]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.5
* Platform/Target and Browser Versions: Chrome / Windows 10
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/demos/410-virtual-slides.html

### What you did
Today I tried to use the swiper with virtual slides. Initially everything was working good, but as soon as I started to dynamically add slides via appendSlide() / prependSlide(), things turned weird.

### Expected Behavior
I expect that after appending / prepending slides dynamically at runtime, the swiping functionality works just like before, except that I have more slides to swipe through than before.

### Actual Behavior
After appending / prepending slides dynamically at runtime, the swiper jumps across multiple slides upon swiping and does other crazy stuff.

At first I thought it was an issue with my code, but then it found out, that similar things happen in the online demo at [https://swiperjs.com/demos/410-virtual-slides.html](https://swiperjs.com/demos/410-virtual-slides.html).

To reproduce: Load page, then alternate between prepending and appending slides. You should already see that the active slide jumps between 1 and -1. If you afterwards swipe through the slides, you will recognize that the active slide is all but not the correct one.

Thanks in advance!

**Comment by stefanholzapfel** [comment]
@nolimits4web Thanks for quick reaction, but I still have the issues with version 5.0.3. 

After dynamically appending / prepending virtual slides, the swiper sometimes picks the wrong slides upon slide change. You can see that effect when slowly dragging the slides to the left/right. Instead of switching to the next /previous slide, in the middle of the sliding action (i guess when the action to replace the virutal dom slides is triggered), the next/prev slide is replaced with a wrong index.

**Comment by nolimits4web** [comment]
Would be good to know exact reproduction scenario. Maybe a video with screen recording?

**Comment by stefanholzapfel** [comment]
Yes I can do that, but later today. Thank you.

**Comment by stefanholzapfel** [comment]
Sorry for the delay.

I have attached a recording of the swiper in our webapp. As you can see, during slide change, the slides get replaced with different ones. I guess that happens when the virtual slide mechanism kicks in to add / remove DOM.

In the background I use a [LitElement](https://lit-element.polymer-project.org/) lifecycle hook ("updated") to react to changes in my data array. This hook is triggered with the initial data (data for the selected slide and five slides to the left/right) and whenever I receive some more data from network. Network requests are fired upon every swipe when not enough data is cached to show previews for 5 slides to both sides of the selected one.

Here is the code of the complete "updated" lifecylce hook:
```    
protected updated(changedProps: PropertyValues) {
  if (changedProps.has('spots') && this.selectedSpot && this.spots !== null && this.spots.length > 0) {

  // Delete slides that are no more part of spots
  const toRemove = [];
  this.swiperSpots.forEach((spotToDisplay, index) => {
    const sliderSpotsIndexInSpotsArray = _.findIndex(
      this.spots,
      spot => spot.id === spotToDisplay.id
    );
    if (sliderSpotsIndexInSpotsArray === -1) {
      toRemove.push(toRemove);
    }
  });
  if (toRemove.length > 0) {
    this.swiper.virtual.removeSlide(toRemove);
  }

  // Add new spots to slides
  const toPrepend = [];
  const toAppend = [];
  this.spots.map((spot, index) => {
    if (this.swiperSpots.length === 0 || spot.id > this.swiperSpots[0].id) {
      toPrepend.unshift(spot);
    } else if (spot.id < this.swiperSpots[this.swiperSpots.length - 1].id) {
      toAppend.push(spot);
    }
  });

  // Apply to swiper
  if (toPrepend.length > 0) {
    this.swiper.virtual.prependSlide(toPrepend);
  }
  if (toAppend.length > 0) {
    this.swiper.virtual.appendSlide(toAppend);
  }
}
```

Maybe also relevant: I start with an empty slide array and add all the slide via the above mechanism.

[25.09.2019_11.47.07_REC.zip](https://github.com/nolimits4web/swiper/files/3651792/25.09.2019_11.47.07_REC.zip)

Thanks in advance!

**Comment by stefanholzapfel** [comment]
Omg I think i found the problem and it was my fault.
I had a typo in the "left" property of the swiper-slide's style. Seems to work now.

Sorry for inconvenience.

**Comment by CitizenBeta** [comment]
@stefanholzapfel how did you end up solving this? I'm running into the same thing.

**Comment by stefanholzapfel** [comment]
Hi @CitizenBeta !

As mentioned in my last comment, it was just a typo in my styles.

So in general, double check if you have wired everything correctly. E.g. not settings style properties on the slides correctly can produce weired effects.
