### ISSUE TITLE
Swiper-slide

### ISSUE THREAD

**Issue by pavliggs** [nolimits4web/swiper#3217]
Здравствуйте. У меня возникла следующая проблема при подключении Swiper.

![2019-09-18_23-42-58](https://user-images.githubusercontent.com/51763058/65184581-7c68a000-da6e-11e9-8bb0-93c209379bed.png)

На картинке видно как следующий слайд налезает на предыдущий. То есть почему-то между слайдами нет расстояния.
Должно быть как на картинке ниже

![2019-09-18_13-13-55](https://user-images.githubusercontent.com/51763058/65184683-b2a61f80-da6e-11e9-8f79-2bedac869d77.png)

Вот мой html

![2019-09-18_23-57-37](https://user-images.githubusercontent.com/51763058/65185419-2f85c900-da70-11e9-9ddb-152a844a5ae1.png)

CSS (sass)

![2019-09-19_00-00-00](https://user-images.githubusercontent.com/51763058/65185585-8e4b4280-da70-11e9-8e00-c5319a925f7b.png)

![2019-09-19_00-01-22](https://user-images.githubusercontent.com/51763058/65185794-f6018d80-da70-11e9-943e-201214423be6.png)

Script

![2019-09-19_00-04-41](https://user-images.githubusercontent.com/51763058/65185949-41b43700-da71-11e9-9e7f-7364d566c96d.png)

Подскажите, пожалуйста, в чём тут проблема? Почему слайды прижаты друг  к другу  и неправильно реагируют на отступы родительского блока (class="case-study__left ideas swiper-container")? Спасибо.

**Comment by nolimits4web** [comment]
Это как работает CSS, padding должен быть установлен на слайде или поставьте spaceBetween. Закрываю так как не относится к Swiper
