### ISSUE TITLE
Zoom option behaves abnormally

### ISSUE THREAD

**Issue by LZQCN** [nolimits4web/swiper#3218]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.0.2
* Platform/Target and Browser Versions: Chrome/75.0.3770.142 | Chrome/63.0.3239.132 | Windows 10 1803 1713.984
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/demos/400-zoom.html

### What you did

original:
我在 Chrome 打开了 \swiper-5.0.2\demos\400-zoom.html 文件， 并且在 Chrome F12 开启了 设备工具条 ，所选的预设是 touch设备，分辨率是 375*640。

google translate:
I opened the \swiper-5.0.2\demos\400-zoom.html file in Chrome, and the device toolbar is turned on in Chrome F12. The selected preset is touch device with a resolution of 375*640.

### Expected Behavior

original:
我希望 Swiper5.0.2 表现的和 4.5.0 中的 400-zoom.html 一样
双击放大后去 touch 拖动被放大的图片，能够在 swiper-zoom-container 中同步移动被放大的图片，并且 swiper-wrapper 不会受到影响。

google translate:
I want Swiper 5.0.2 to behave the same as 400-zoom.html in 4.5.0
Double-click to zoom in and touch to drag the enlarged image to move the enlarged image synchronously in the swiper-zoom-container, and the swiper-wrapper is not affected.

### Actual Behavior

original:
在 Chrome F12 启动设备工具条并模拟移动设备后，无法正常使用 zoom 选项。双击 zoom 放大后再去 touch 拖动被放大的图片，结果不仅仅是 swiper-zoom-container 中的图片被移动了， 整个 swiper-wrapper 也被意外的移动了。桌面设备并没有出现这种情况。

google translate:
The zoom option does not work properly when the Chrome F12 launches the device toolbar and emulates a mobile device. Double-click zoom to zoom in and then touch to drag the enlarged image. The result is that not only the image in swiper-zoom-container is moved, but the entire swiper-wrapper is also accidentally moved. This is not the case with desktop devices.

**Comment by nolimits4web** [comment]
Please, open issues in English

**Comment by LZQCN** [comment]
> Please, open issues in English

I re-edited this issue, I hope you understand it.
