### ISSUE TITLE
Two slides have same order

### ISSUE THREAD

**Issue by marwej** [nolimits4web/swiper#3220]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 5.0.2
* Platform/Target and Browser Versions: macOS
* Live Link or JSFiddle/Codepen or website with isssue: N/A

### What you did
17 slides, 2 rows, 5 columns => 2 groups
`slidesPerColumnFill = row`

### Expected Behavior
Nice slider

### Actual Behavior
Two slides have order 9. The second one with order 9 is misplaced and have wrong margins. I think that the slider think that it should be in group 2 (since it is index 9 and we have 5 columns. But we only have 17 slides in total meaning that slide with index 9 is in group 1 and row 2).

<img width="1642" alt="Skärmavbild 2019-09-19 kl  09 03 27" src="https://user-images.githubusercontent.com/5296840/65222083-a34ec280-dabe-11e9-89a6-4b907b374a7e.png">

**Comment by nolimits4web** [comment]
What are exact swiper parameters?
