### ISSUE TITLE
Autoplay paused status stays true after switching between browser tabs

### ISSUE THREAD

**Issue by gedeminas** [nolimits4web/swiper#3221]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.0.2
* Platform/Target and Browser Versions: macOS, Chrome 76

### What you did
Running Swiper with autoplay enabled. Checking swiper.autoplay.paused status with my own setInterval. Switched browser tabs forth and back.

### Expected Behavior
After switching back to tab with Swiper running, swiper.autoplay.paused should be false.

### Actual Behavior
swiper.autoplay.paused is true and doesn't change until next slide.
As I understand after document visibilitychange event slider.autoplay.run() runs to restart autoplay, but doesn't change paused status.

**Comment by nolimits4web** [comment]
Can't replicate it and and timeout/intervals are not reliable in hidden tabs. Would be good to see real example or JSFiddle and what does it break?

**Comment by gedeminas** [comment]
Sorry, probably I'm not so good at explaining. It breaks my progress bar animation:
[https://jsfiddle.net/7k216cyx/](JSFiddle)

When you are dragging the slides for example, autoplay.paused is true and, but after releasing the slide, autoplay resets state, as it should.

But if you go to another browser tab and come back, paused is true, maybe the timer should reset also? Or just the autoplay.paused state?
