### ISSUE TITLE
Image of first to last slide in the loop cannot be displayed

### ISSUE THREAD

**Issue by nao50** [nolimits4web/swiper#3223]
This is a :
* [x] bug

Environment : 
* Swiper Version: 5.0.3
* Platform/Target and Browser Versions: macOS chrome
* Live Link : https://stackblitz.com/edit/angular-swiper-issue

### What you did
I create an application that fetch the URL of an image from the API and displays it on autoplay loop slides.

Since the image file is obtained from the API, it is assumed that there will be a slight delay.

```typescript
fetch(): Observable<string> {
  return of(' IMAGE_URL ').pipe(
    // If there is no delay, it can be displayed without problems 
    delay(1000)
  );
}
```
And binding the obtained URL to HTML as follows

```typescript
this.swiperService.fetch().subscribe(
  (response: string) => {
    this.image = response;
  }
);
```

```html
<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <img src="{{ image }}">
    </div>
    <div class="swiper-slide">
      <img src="{{ image }}">
    </div>
  </div>
</div>
```

### Actual Behavior
No image is displayed when returning from the last slide to the first slide.
Looking at the HTML, it seems that only one of the duplicated slides has not been bound to the image tag.

```html
<div class="swiper-slide swiper-slide-duplicate swiper-slide-active" data-swiper-slide-index="0">
  <img>
</div>
```

I'm looking for a synchronous way of writing the workaround, but I feel it would be nicer if the images were bound to all the slides.

Thank you.

**Comment by naoyamaguchi** [comment]
I create workaround.

- Live Link : https://stackblitz.com/edit/angular-swiper-issue-walkaround

It was redrawn after getting the data. (Not smart and only angular way)

```typescript
this.swiperService.fetch().subscribe(
  (response: string) => {
    this.image = response;
    // this mean redrawing
    this.changeDetectorRef.detectChanges();
    const nativeElement = this.elementRef.nativeElement;
    this.swiper = new Swiper(nativeElement.children[0], this.swipeOptions);
  }
);
```

**Comment by muhammadadamfirdaus** [comment]
Me too. On the last slide, image couldn't be displayed.

**Comment by gAusWeb** [comment]
This is still an issue after all this time - any updated resolved re this ? TIA
