### ISSUE TITLE
Horizontal draggable list

### ISSUE THREAD

**Issue by marcelo2605** [nolimits4web/swiper#3224]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.1.
* Platform/Target and Browser Versions: Windows, CHROME.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/marcelo2605/pen/KKPJpZa?editors=1010

### What you did
Make an horizontal scroll with a single like, following [Scroll Container demo] (https://swiperjs.com/demos/)

### Expected Behavior
Click and drag to see hidden items.

### Actual Behavior
1. After drag and release mouse button, list back to initial state.
2. Horizontal scrollbar is not visible.

**Comment by nolimits4web** [comment]
You need to set `.swiper-slide { width: auto }` in styles
