### ISSUE TITLE
Swiper dragging breaks when resizing the screen using Chrome's dev tools.

### ISSUE THREAD

**Issue by JanYalda** [nolimits4web/swiper#3229]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: CHROME

### What you did
If I start the webpage with normal screen size it works fine, but once I resize it to a phone screen from the dev tools it breaks the grab to slide I can only use the arrows to navigate to the different slides. Same thing happens If I start with a phone screen then switch to full screen by closing the dev tools it breaks! 

### Expected Behavior
Should function as expected drag in either direction to switch slides.

### Actual Behavior
Grab slide to switch slide breaks, only arrows work.

**Comment by nolimits4web** [comment]
You need to reload browser when toggle device emulation

**Comment by ezetojo** [comment]
```
$(window).on("resize", function() {
    mySwiper.autoplay.start();
    mySwiper.update();
});
```
