### ISSUE TITLE
Why does AutoPlay stop working when I switch slides with the navigation button?

### ISSUE THREAD

**Issue by Vladddosss** [nolimits4web/swiper#3230]
Why does AutoPlay stop working when I switch slides with the navigation button? It is enabled again after the page is refreshed.

How to fix it?

**Comment by nolimits4web** [comment]
Check `disableOnInteraction` parameter

**Comment by Vladddosss** [comment]
@nolimits4web 
> Check disableOnInteraction parameter

This does not solve the problem.

Here's my code.
```
var` NewsLineSwiper = new Swiper('.drozd-news-line', {
	speed: 400,
	autoplay: {
		delay: 3000,
		},
		disableOnInteraction: false,
		navigation: {
			nextEl: '.swiper-button-next',
			prevEl: '.swiper-button-prev',
		},
		loop: true,
});
```

**Comment by baskinvolkan** [comment]
// Import Swiper and modules
import { Swiper, **Autoplay**, Navigation, Pagination } from 'swiper/js/swiper.esm.js';

// Install modules
Swiper.use([**Autoplay**, Navigation, Pagination]);

**Comment by AndreuSergienko** [comment]
disableOnInteraction should be inside autoplay: { disableOnInteraction: false }
Hello from 2022!

**Comment by salmaniz82** [comment]
I am having same issue, added all module even using the example provided. 
Autoplay crashes when next / previous is clicked using React Component version.

**Comment by ArtyshukPavlo** [comment]
Same thing. Libriaries included from files, but disablseOnInteraction: false are not working( 2025....

**Comment by jklue** [comment]
When I removed `touchRatio: 0` it behaved as expected, and didn't stop the autoplay.
