### ISSUE TITLE
Swiper.$el and Swiper.$wrapperEl is not a dom elements

### ISSUE THREAD

**Issue by projct1** [nolimits4web/swiper#3233]
Its objects http://skrinshoter.ru/s/250919/qlhWR2G2
By the way, swiper.slides is object too, except of array.

**Comment by nolimits4web** [comment]
And they not supposed to be. See docs https://swiperjs.com/api/

**Comment by projct1** [comment]
Ok, thanks. And what about slides? Why they not an array? They have only numeric keys.
