### ISSUE TITLE
Swiper 5.0+ Dropped IE Support Question

### ISSUE THREAD

**Issue by sethwhitaker** [nolimits4web/swiper#3236]
Forum link doesnt work anymore...

In the release notes for v5.0 there is mention that IE support is dropped. What exactly does this entail? I downloaded v5.0.3 and tested it out in IE 11 (still need to support for some clients) and it still works. Can specifics on what exactly was dropped from IE support be clarified so I can know if i am going to run into some edge case issue with IE down the road by upgrading to v5 for projects.

**Comment by andreyberezhnoy** [comment]
Same question. 'IE support is dropped' means dist files builded without IE support or swiper 5 used a modern API which don't have a polyfill?

**Comment by nolimits4web** [comment]
You can check that commit: https://github.com/nolimits4web/swiper/commit/6cba971b1004521859f8699d73f0a702f5134d46

But basically, yes, checks for support of CSS transitions, CSS 3D transforms, flexbox, and others, and their fallbacks in code were removed. But probably it still can work in IE 11, but if it is not, it is not the case for Swiper anymore
