### ISSUE TITLE
RFC: slide through multiple slides when "quick" swiping

### ISSUE THREAD

**Issue by fritzmg** [nolimits4web/swiper#3239]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Would it be possible to integrate a feature into Swiper.js where Swiper would detect a "quick" swipe to the left or right (on touch devices) which would override the `slidesPerView` setting and simply slide over the slides with a certain speed depending on the speed of the swipe. The speed would gradually reduce and and then stop at the next possible slide when the speed reaches a certain threshold.

I hope it's clear what I mean ;). Not sure how complex this would be...

**Comment by robpop** [comment]
@fritzmg is this what you mean?

https://swiperjs.com/demos/150-freemode.html

**Comment by fritzmg** [comment]
Ha, yes it is 😁 Sorry, I did not realize it was already possible.

**Comment by dbleisch** [comment]
Unfortunately the Free Mode example does not support scroll snaping (https://swiperjs.com/demos/150-freemode.html)
CSS Scroll Snap comes closer to the requirement. Here you can also skip several slides by scrolling faster (scroll wheel)
But https://swiperjs.com/demos/145-css-mode.html
