### ISSUE TITLE
scss variables conflict with others libraries

### ISSUE THREAD

**Issue by raky291** [nolimits4web/swiper#3242]
In the scss files the global variable of `$colors` is overwriting the Bootstrap variable and can overwrite any other library.

It is recommended to add the name of the library at the beginning of the variable to avoid conflicts, eg. `$swiper-colors: (white: #ffffff, black: #000000)! default;` and `$swiper-theme-color: #007aff! default;`

**Comment by nolimits4web** [comment]
Doing this will break everyone’s code who already use this, so not an option
