### ISSUE TITLE
Textarea on swiper slide not clickable via mouse

### ISSUE THREAD

**Issue by stefanholzapfel** [nolimits4web/swiper#3243]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.0.3
* Platform/Target and Browser Versions: Windows 10 / Chrome 77.0.3865.90

### What you did
Used a textarea within a slide.

### Actual Behavior
Focus is not set on click. Obviously the simulated touch behaviour for mouse is interfering with the mouse click and the textarea is not focused. With simulateTouch set to false, it works. But then it's not possible to swipe with the mouse.

### Expected Behavior
I would expect the textarea (or every input) to be excluded from the simulated touch behaviour, because otherwise it is not possible to select text oder even focus an input. It seems that was already the case in older versions of swiper.

**Comment by nolimits4web** [comment]
Nope, can't replicate it. Please provide a live example or JSFiddle with the issue

**Comment by robpop** [comment]
@stefanholzapfel we'll be able to fix this if you provide a JSFiddle or CodePen that replicates the issue

**Comment by ajp8164** [comment]
I have a similar issue on **iOS**. Clicking into a textarea which is placed on a slide results in the text caret not being displayed. The keyboard is presented.

Setting simulateTouch false makes no difference.

I've made a simple [codepen](https://codepen.io/ajp8164/pen/jOOMoJQ) to demonstrate.

**Comment by robpop** [comment]
@ajp8164 I'll take a look into this, don't imagine it'll be too difficult to fix.
