### ISSUE TITLE
Swiper And Dom7 do not transpiles es6 code to es5 after build

### ISSUE THREAD

**Issue by tohbansoon** [nolimits4web/swiper#3245]
```
{
    test: /\.js(x)?$/,
    exclude: [/node_modules\/(?!(swiper|dom7)\/).*/, /\.test\.jsx?$/],
    use: [{ loader: 'babel-loader' }],
},
```

According to `react-id-swiper` document, I have added this into the webpack.config.js but after `npm run build`, it doesnt transpile the code to into es5... I can still find `const` inside the .js file in dist folder... This cause old browser like safari9 or IE10 display error as below

```
SyntaxError: Use of const in strict mode.
```

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
