### ISSUE TITLE
support 3D slide

### ISSUE THREAD

**Issue by leeseean** [nolimits4web/swiper#3249]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
support 3D slide.

### Actual Behavior
support 3D slide
<img src="https://s2.ax1x.com/2019/10/02/udyut0.gif" />

**Comment by nolimits4web** [comment]
There is a `cube` transition effect, see docs

**Comment by leeseean** [comment]
> cube

no,It didn`t support touch event,when I touch stop,it will have a angle,when I touchend ,then flip
