### ISSUE TITLE
change param after init 

### ISSUE THREAD

**Issue by badoubadou** [nolimits4web/Swiper#325]
Hi, I want to change slidesPerView, and centeredSlides parameter after init. I do this, but it doesn't seem to work.... 
mySwiper.params.slidesPerView = 'auto';
mySwiper.params.centeredSlides = true;
Am I doing something wrong, or should I modify the swiper plugin so it take effect ?

Thanks a lot for your help !

**Comment by odahcam** [comment]
Should label this as [question], [outdated] and [<version>] and also close conversation, this can be confusing.
