### ISSUE TITLE
Can't scroll the page vertically at all on mobile 

### ISSUE THREAD

**Issue by xmadscientist** [nolimits4web/swiper#3250]
Example from our site:
https://olsatools.com/products/extractor-hex-key-set

Browse to that page on mobile and try to scroll down the page to the description by starting your swipe on the main image and bring your finger up your screen.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Tried a bunch of different properties for the swiper object. No luck.

Example: https://olsatools.com/products/extractor-hex-key-set

### Expected Behavior
Scroll the page vertically on mobile. 

### Actual Behavior
Page is stuck and doesn't scroll vertically on mobile.

**Comment by nolimits4web** [comment]
Looks like there is something in your code in swiper settings that breaks it on mobile, as you can see on https://swiperjs.com there is no such issue

**Comment by xmadscientist** [comment]
@nolimits4web 

Here are the settings that were used for that section of the page:

`ot.productImageSlider = (function() {
  var productImage = new Swiper('#product-img-carousel', {
    spaceBetween: 10,
    breakpoints: {
      1023: {
        pagination: {
          el: '#product-img-carousel .swiper-pagination',
        }
      }
    },
    thumbs: {
      swiper: ot.productThumbSlider
    }
  });

  return productImage;
})();`

**Comment by Gloosecap** [comment]
Same for me iphone iOS 13.1.2 on Chrome, Safari and Firefox you can scroll left and right of course, but scrolling up or down over the image does nothing. My images are covering most of the viewport so its quite difficult to scroll past the slideshow. My settings are:

slidesPerView: 'auto', 
observer: true, 
observeParents: true, 
loop: false, 
spaceBetween: 40

**Comment by Gloosecap** [comment]
By accident, I had touch-action: none; on a class that was also on the swiper-container which was not allowing me to scroll while on top of the slideshow :( all fixed :)
