### ISSUE TITLE
The UI didn't auto scroll up when keyboard appear in page - iOS 13.1

### ISSUE THREAD

**Issue by kientrungtran** [nolimits4web/swiper#3257]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Tested with 3.0.4 and latest 4.5.1
* Platform/Target and Browser Versions: Safari - iOS 13.1.2
* Live Link or JSFiddle/Codepen or website with issue: https://jsfiddle.net/um9xnog6/

### What you did
As checked, this issue happens due to existing css **translate3d** in wrapper swiper (If try to remove it from HTML, input fields will be fine but swiper will be broken).
Also, in these slides, cursor of input doesn't blink when user tap/ focus on it.

**Note: Just occur from second slide. It always works in the first slide.**

### Expected Behavior
The UI auto scroll up when keyboard appear. And cursor blink in input fields

### Actual Behavior
The UI didn't auto scroll up when keyboard appear in safari. And cursor doesn't blink in input fields.

Please check and let me know if have any solution.

Thanks for support!

**Comment by Tata1989** [comment]
We have the same issue.

**Comment by Tata1989** [comment]
> If try to remove it from HTML, page is okay.
Do you mean remove  the existing css translate3d in wrapper swiper will don't have this issue.
It didn't  work when I debug. Can you show the details? Thx

**Comment by kientrungtran** [comment]
You can try to comment translate3d() style and tap on input fields from second slide to see differences. But, it doesn't mean if remove this since library is basing on translate3d.

**Comment by Tata1989** [comment]
I'm not clear for the comment. Because when I commented the translate3d style, it auto went to the first slide.

**Comment by kientrungtran** [comment]
Swiper will break layout once you remove translate3d. If wanna show second slide, you need adding some css to move it on top (like "left: ...px")

**Comment by kientrungtran** [comment]
Swiper will break layout once you remove translate3d. If wanna show second slide, you need adding some css to move it on top (like "left: ...px")

**Comment by cbahai** [comment]
i have the same problem on iOS13.1, first slide it's ok. but second slide, no cursor, can't select, can't copy, can't paste.

**Comment by ajp8164** [comment]
> i have the same problem on iOS13.1, first slide it's ok. but second slide, no cursor, can't select, can't copy, can't paste.

Same [issue](https://github.com/nolimits4web/swiper/issues/3243) here. Though doesn't work on first slide for me either.

**Comment by gap1994** [comment]
> i have the same problem on iOS13.1, first slide it's ok. but second slide, no cursor, can't select, can't copy, can't paste.

Have you found a solution?

**Comment by kientrungtran** [comment]
Retest in iOS 13.2 official. It's resolved.

**Comment by gap1994** [comment]
> Retest in iOS 13.2 official. It's resolved.

so it`s no answer in IOS 13.1

**Comment by kientrungtran** [comment]
Seems like iOS bug and no solution now. So, only upgrade iOS version.

**Comment by gap1994** [comment]
alright, that is not my problem~~
