### ISSUE TITLE
Swiper removeAllSlider not working if I use hidden-xs class

### ISSUE THREAD

**Issue by yop289** [nolimits4web/swiper#3258]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 4.3.5
* Platform/Target and Browser Versions: CHROME not tested in others

### What you did
I have two sliders on the same page, one I hide on a mobile environment.

### Expected Behavior
I add new sliders after click event, but before I remove all so I use 
 mySwiperMain.removeAllSlides();
 mySwiperAdditional.removeAllSlides();

### Actual Behavior
On Computer environment all works fine.
On mobile with swipper with class hidden-xs removeAllSlider is not working.
On mobile with swipper without class hidden-xs removeAllSlider is working.

**Comment by robpop** [comment]
@yop289 can you provide a CodePen / JSFiddle to recreate the issue
