### ISSUE TITLE
lazy:true and preloadImages: false — swiper is still loading all images with class "swiper-lazy" immediately

### ISSUE THREAD

**Issue by Tykkiduf** [nolimits4web/swiper#3260]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: All
* Live Link: https://testi.sivututka.fi/smartblock/product-picker/

### What you did
I have built a product configurator with nested swipers. User can change features such as size, color etc.

Because this swiper page contains roughly 80 .png images (80 - 400kb size) it sometimes crashes in iOS devices on portrait orientation...

So I activated lazy loading as usual but every image is still being loaded right on the swiper init instead of when they are shown on screen.

### Expected Behavior
I expect to only see a few images loaded when page loads, then I expect more images to be loaded when they are needed.

### Actual Behavior
Every single image is being loaded immediately on page load, causing longer load time and some iOS problems.

**Comment by Tykkiduf** [comment]
Update: 

I circumvented this problem by setting the display of images inside swiper slides to display:none unless the slide has class: .swiper-slide-active, .swiper-slide-next, .swiper-slide-prev

Still, I believe this is a valid bug.

**Comment by anhkhoi** [comment]
The same issue for me. This setting is not working. `preloadImages: false`

All my images are still loaded in the same time.

**Comment by elm11g** [comment]
Still a bug

**Comment by serhatyl** [comment]
The bug still persists.

**Comment by 520xcy** [comment]
browser does not support loading="lazy". Try to use swiper 8
