### ISSUE TITLE
Carousel not working correctly after Swiper.params.slidesPerView Auto

### ISSUE THREAD

**Issue by YBOP84** [nolimits4web/swiper#3262]
I'm working with Wordpress and Elementor on a simple landing page which has a carousel. I want slides to be added/subtracted in regard to the screen width. From the Elementor backend it is not possible to set the slidesPerView to 'auto'. So I'm using a small script to achieve this after the initialisation of the carousel. It works, however:

<ol>
<li>The loop doesn't work correctly, slides keep shifting/jumping after a few clicks on the navigation.</li>
<li>The slidesPerView set in the Elementor backend is not being changed by 'auto'. I expect the open space to be filled with additional slides, but that doesn't happen.</li>
</ol>

`jQuery(document).ready(function($) {
    var mySwiper = document.querySelector('.swiper-container').swiper;
    mySwiper.params.slidesPerView = 'auto';
    mySwiper.update();
})`

Hope someone can shine some light on this.

Thank you

**Comment by nolimits4web** [comment]
You also need to unset style="width:..." on slide elements before calling update

**Comment by YBOP84** [comment]
Hi there,

Thank you for answering the second question. Your input solved it!

However, the loop still doesn't work correctly. I use the prev and next navigation. When pressing the next button for the 4th time the loop skips to the 8th slide. After that the loop keeps skipping back after pressing next or prev.

Any idea?
