### ISSUE TITLE
On mobile only (iOS Chrome, iOS Safari, and others(?)), performing a pinch zoom on a site using swipe with React and many images (~20?) causes site to crash

### ISSUE THREAD

**Issue by DavrosFl** [nolimits4web/swiper#3264]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 5.0.4
* Platform/Target and Browser Versions: iPhone X, iOS v13.1.2, iOS Chrome v77.0.3865.103, iOS Safari version latest for iOS v13.1.2 as of this writing.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/davrosfl/pen/JjjdmQe or clone from github https://github.com/DavrosFl/carousels.git

### What you did
1. I created a VERY simple react app to use swipe with 20+ images.
2. Go to the codepen link on one of the browsers in the iPhone X (haven't tried other phones)
3. Pinch zoom a bunch of times in succession on any of the images (slides) that appear in the carousel.
4. Site crashes (Chrome "Aw, Snap"; Safari "A problem repeatedly occurred on ..")
_I apologize that I'm not able to get remote debugging working on my phone so I don't have any error information_

### Expected Behavior
User can zoom on a carousel with many images without site dying.

### Actual Behavior
Site crashes (Chrome "Aw, Snap"; Safari "A problem repeatedly occurred on ..")
_I apologize that I'm not able to get remote debugging working on my phone so I don't have any error information_

**Comment by nolimits4web** [comment]
There is always a memory limit for this, try to use lazy loading technics to avoid it. Closing as not directly related to swiper
