### ISSUE TITLE
Event on scroll to end

### ISSUE THREAD

**Issue by ptimlive** [nolimits4web/swiper#3265]
* [X] feature-discussion (RFC)

* Swiper Version: 5.0.4
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/demos/090-vertical.html

### Feature request
Could we have an event fired when the user tries to scroll to the end on either side of a slide?

For example on:
https://swiperjs.com/demos/090-vertical.html

On Slide 1 if the user tries to scroll up or on Slide 10 if the user continues to try to scroll down.

Uses: On Slide 1 this could be used to activate pull to refresh.
And on Slide 10 this could be used to load more slides (like infinite scroll).

### Actual Behavior
N/A

**Comment by nolimits4web** [comment]
There is already `reachEnd` and `reachBeginning` events https://swiperjs.com/api/#events
