### ISSUE TITLE
Blurry Slides

### ISSUE THREAD

**Issue by RedPlugDesign** [nolimits4web/swiper#3266]
I have read several posts about blurry slides & I have attempted different fixes including transform: translate3d(0, 0, 0);, z-index & roundLengths.  Unfortunately, the images does not always load properly.  I cannot replicate aside from repeatedly reloading and checking.  

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.3.3
* Platform/Target and Browser Versions: Windows, latest Chrome
* Live Link or JSFiddle/Codepen or website with issue: https://groceries-filter-theme.myshopify.com/

### What you did
Basic Install

### Expected Behavior
Clear images

### Actual Behavior
Not consistent, but every few loads the 2nd slide image does not load properly

**Comment by nolimits4web** [comment]
Have to close it because
1) 4.x is not supported anymore
2) If `roundLengths` doesn't help then it is browser rendering issue
