### ISSUE TITLE
Slide to coordinates

### ISSUE THREAD

**Issue by jasonlav** [nolimits4web/swiper#3268]
This feature would allow animation to specific a position. Functionality would be similar to the existing `slideTo` method, except instead of passing an index, X or Y coordinates would be passed.  Useful for when swiper is being implemented as a scroller or in freemode.

This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

**Comment by nolimits4web** [comment]
You can use `setTranslate` method for this https://swiperjs.com/api/#methods

**Comment by jasonlav** [comment]
`setTranslate` does not resolve the issue as it does not **animate** to the position.

I did find an undocumented `setTransition` method that, if set before `setTranslate` will cause an animation. However, events such as `transitionEnd` do not fire.
