### ISSUE TITLE
Swiper orientation change from landscape to portrait problem on IOS

### ISSUE THREAD

**Issue by ptimlive** [nolimits4web/swiper#3276]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.0.4
* Platform/Target and Browser Versions: IOS 13.1.2
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/demos/090-vertical.html

### What you did
In Safari open https://swiperjs.com/demos/090-vertical.html in portrait orientation.
Rotate to landscape and then back again, 

### Expected Behavior
Swiper should now go back into fullscreen portrait.

### Actual Behavior
Swiper does not resize correctly and there is a gap at the bottom of the screen.

**Comment by nolimits4web** [comment]
Sorry, closing as this has nothing to do with Swiper itself
