### ISSUE TITLE
Dynamic RTL change

### ISSUE THREAD

**Issue by codesignist** [nolimits4web/swiper#3279]
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.0.4
* Platform/Target and Browser Versions: Windows - Chrome 77.0.3865.120
* Codepen: https://codepen.io/codesignist/pen/VwwaqNj

### What you did
I've changed html direction to "rtl" by JS.
```javascript
document.documentElement.dir = "rtl";
```

### Expected Behavior
RTL change should affect Swiper and should work from right to left as expected.

### Actual Behavior
RTL change doesn't make any effect on Swiper.

**Comment by nolimits4web** [comment]
It is by design, it can be initialized when it is rtl or not, and it’s behavior can’t be changed after init. If you really need such behavior you can destroy and reinit Swiper in this case

**Comment by Terrafire123** [comment]
@nolimits4web Why?

It seems **already be working** just fine as is. Why not include it in the official documention?

window.on('myChangeLanguageEvent',function(event){
        swiper.rtl =  (event.direction === 'rtl');
        swiper.rtlTranslate = (event.direction === 'rtl');
});

**Comment by farhadf246** [comment]
is it possible add direction changes in to the observe parameter? or when call update method update slider direction too?

**Comment by kirillsakun** [comment]
Seems like it doesn't reset margins that were added by `spaceBetween` option.
