### ISSUE TITLE
Many bugs using Swiper with thumbnails and zoom functionality 

### ISSUE THREAD

**Issue by Riccardo-Andreatta** [nolimits4web/swiper#3286]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.1
* Platform/Target and Browser Versions: macOS, Windows, any browser.
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/riccardo-andreatta/pen/dyypOvG

### What you did

In the example above there are many bug (follow the numbers on each of the following sections):
1. click on any thumbnails,
2. click multiple time on the same thumbnails,
3. double click on the main gallery Swiper, the main image is then zoomed,
4. double click on the main gallery Swiper, the main image is then zoomed, try to swipe to the next image but without going to that image.

### Expected Behaviour

1. the thumbnail clicked will be highlighted as it gets the class `swiper-slide-thumb-active`,
2. clicking multiple time on the same thumbnails does not affect the main gallery swiper,
3. when the main image is zoomed, I can pan the image,
4. when the main image is zoomed, if you try to swipe to the next image, the main image is zoomed out, and the icon is going back to the initial status.

### Actual Behaviour

1. the thumbnails are not highlighted because the class `swiper-slide-thumb-active` is not changing position as in the Demo from the Swiper website,
2. clicking multiple time on the same thumbnails, the main Gallery Swiper is operating weirdly like swiping to another slide with the same image (like swiping to the duplicate one),
3. when the main image is zoomed, the pan functionality is not working,
4. when the main image is zoomed, if you try to swipe to the next image, the image is zoomed out, but the slide still have the class `swiper-slide-zoomed` that is causing the icon status still be the one that should zoom out the image.

**Comment by nolimits4web** [comment]
Swiper 4.x is not supported anymore
