### ISSUE TITLE
Some bugs using Swiper with thumbnails and zoom functionality

### ISSUE THREAD

**Issue by Riccardo-Andreatta** [nolimits4web/swiper#3287]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.1.0
* Platform/Target and Browser Versions: macOS, Windows, any browser.
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/riccardo-andreatta/pen/dyypOvG

### What you did

In the example above there are many bug (follow the numbers on each of the following sections):
1. double click on the main gallery Swiper, the main image is then zoomed,
2. double click on the main gallery Swiper, the main image is then zoomed, try to swipe to the next image but without going to that image.

### Expected Behaviour

1. when the main image is zoomed, I can pan the image,
2. when the main image is zoomed, if you try to swipe to the next image, the main image is zoomed out, and the icon is going back to the initial status.

### Actual Behaviour

1. when the main image is zoomed, the pan functionality is not working,
2. when the main image is zoomed, if you try to swipe to the next image, the image is zoomed out, but the slide still have the class `swiper-slide-zoomed` that is causing the icon status still be the one that should zoom out the image.

**Comment by Riccardo-Andreatta** [comment]
As expected, there is never an answer from @nolimits4web nor a support...

**Comment by Ferie** [comment]
This has became stale... where is the author? Where is the support?

**Comment by vltansky** [comment]
@Riccardo-Andreatta @Ferie looks like you implemented zoom without `.swiper-zoom-container` wrapper:
```html
...
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <div class="swiper-zoom-container"> <--- This div is missing in your demo
                <img src="path/to/image1.jpg">
            </div>
        </div>
```
see https://swiperjs.com/api/#zoom

take a look at this demo: https://codepen.io/vltansky/pen/bGwyGgG

**Comment by rob-myers** [comment]
> when the main image is zoomed, if you try to swipe to the next image, the image is zoomed out, but the slide still have the class swiper-slide-zoomed that is causing the icon status still be the one that should zoom out the image.

This just hit me. I was trying to layer the zoomed image above a subsequent image:
```css
.swiper-slide.swiper-slide-zoomed {
  z-index: 1;
}
```
But `swiper-slide-zoomed` is not removed when we un-zoom on-change-slide, which breaks this approach.

**Comment by MRamonLeon** [comment]
I faced the same issue, still not solved 😢

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by Riccardo-Andreatta** [comment]
@vltansky if I use your solution the image become no more full screen (cover) but it gets the dimension of the container.

And btw, this issue seems not yet solved... but they have closed it anyway... 🤦

**Comment by smiler142** [comment]
The only way to disable swiping in Swiper while zooming is to completely disable swiping and allow slide changes only through navigation buttons, pagination bullets, and the thumbs slider

```
const thumbsSwiper = new Swiper(".thumbSlider", {
    slidesPerView: 4,
    spaceBetween: 10,
    watchSlidesVisibility: true
});

const mainSwiper = new Swiper(".mainSlider", {
    spaceBetween: 10,
    zoom: {
        maxRatio: 3,
        minRatio: 1,
        panOnMouseMove: true,
    },
    thumbs: {
        swiper: thumbsSwiper,
    },
    navigation: {
        nextEl: ".mainSliderNext",
        prevEl: ".mainSliderPrev",
    },
    pagination: {
        el: '.main_slider_dots',
        type: 'bullets',
        clickable: true,
        dynamicBullets: true,
        dynamicMainBullets: 5
    },
    allowTouchMove: false,
    simulateTouch: false,
});
```
