### ISSUE TITLE
Swiper doesn't work when browser is resized

### ISSUE THREAD

**Issue by RajuMenon** [nolimits4web/swiper#3289]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.1
* Platform/Target and Browser Versions: Windows 10 Firefox & Chrome 
* Live Link or JSFiddle/Codepen or website with isssue: https://github.com/nolimits4web/swiper/blob/master/demos/430-slideable-menu.html

### What you did
I have implemented the swiper plugin on a website and while doing responsive testing, I noticed that when window is resized the swiping doesn't work, I have to refresh the page to make it work, At first, I thought it must be something with my code, may be some conflict with the other scripts but when I tested the '430-slideable-menu.html' demo page, it also has that same issue. I also tried calling the swiper script when window is resized, doesn't work. 

### Expected Behavior
When browser is resized the swiping should work.

### Actual Behavior
In Chrome/Firefox desktop browser,  after opening '430-slideable-menu.html' page, the swiping works then I use the developer tool in browser to switch to mobile/tablet resolution, after switching to a mobile/tablet resolution the swiping doesn't work.. If I refresh the page in mobile, the swiping works and if I switch back to desktop resolution the swiping stops working. 

I would really appreciate it if you can provide the code to make the demo page responsive so that the swiping works when browser is resized. 

Thanks

**Comment by nolimits4web** [comment]
When toggle mobile emulation page must be refreshed

**Comment by RajuMenon** [comment]
Thanks for responding.

Is there a way to fix it without refreshing the page? I tried to initialize the script on page resize and from some forums I got swiper.update() but none of these methods worked.
