### ISSUE TITLE
slidesPerColumn not working

### ISSUE THREAD

**Issue by erwinheldy** [nolimits4web/swiper#3290]
* Swiper Version: 5.1.0.
* Platform/Target and Browser Versions: Windows 10 1709, Opera 63, Firefox 69.
* Live Link: https://codepen.io/erwinheldy/pen/qBBqRjR/right/.

**Comment by nolimits4web** [comment]
swiper-container must have specified/limited height

**Comment by erwinheldy** [comment]
still not working

![image](https://user-images.githubusercontent.com/1826289/67212646-e34eef80-f446-11e9-949c-b98c7743dd90.png)
