### ISSUE TITLE
Script in duplicated loop slide not working

### ISSUE THREAD

**Issue by ceehaupt** [nolimits4web/swiper#3292]
I'm using the following code. I have an overlay in the slides, but when i reach the end to the first slide the script for the overlay is not working. When I slide to the second and get back to the first it works!

`swipy = new Swiper(this.element, {
            slidesPerView: 1,
            direction: 'vertical',
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            mousewheel: true,
            keyboard: {
                enabled: true,
                onlyInViewport: false,
            },
            simulateTouch: false,
            loop: true,
            on: {
                init: function () {
                    var ntext = document.querySelectorAll('[data-swiper-slide-index="1"]')[0].getAttribute('data-title');
                    document.querySelector('.swiper-button-next').innerHTML = ntext;
                    var ptext = document.querySelectorAll('[data-swiper-slide-index="' + real +'"]')[0].getAttribute('data-title');
                    document.querySelector('.swiper-button-prev').innerHTML = ptext;

                    for (let i = 0; i < dbtn.length; i++) {
                        dbtn[i].addEventListener('click', () => {
                            document.body.classList.add('is-open');
                            dbtn[i].nextElementSibling.classList.add('is-expanded');
                            swipy.allowSlidePrev = swipy.allowSlideNext = false;
                            swipy.update();
                        });
                    }

                    for (let i = 0; i < cbtn.length; i++) {
                        cbtn[i].addEventListener('click', () => {
                            document.body.classList.remove('is-open');
                            cbtn[i].parentElement.classList.remove('is-expanded');
                            swipy.allowSlidePrev = swipy.allowSlideNext = true;
                            swipy.update();
                        });
                    }
                }
            }
        });`

You can see it on http://c-haupt.de

**Comment by nolimits4web** [comment]
You need to consider duplicated slides in your code

**Comment by ceehaupt** [comment]
When are the duplicates created? Because on init is not working.
