### ISSUE TITLE
Looping back to first slide isn't working when roundLengths is set to true

### ISSUE THREAD

**Issue by dskoziol** [nolimits4web/swiper#3297]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.0.4
* Platform/Target and Browser Versions: Mac Chrome 79, Safari 13.0.2, Firefox 69.0.3
* **Note, this seems to be the same issue as #2249, which has since been closed.**

### What you did
Swiper config:
```
    new Swiper(slider, {
        direction: 'horizontal',
        loop: true,
        slidesPerView: 1,
        spaceBetween: 40,
        roundLengths: true,
        navigation: {
            nextEl: '[data-master-slider=next-button]',
            prevEl: '[data-master-slider=previous-button]',
        },
        simulateTouch: false,
        breakpoints: {
            1280: {
                slidesPerView: 3,
            },
            768: {
                slidesPerView: 2,
            },
        },
    });
```

### Expected Behavior
Clicking on the right arrow should keep looping through the slider indefinitely

### Actual Behavior
When reaching the last slide in the DOM, I can no longer click forward. It does loop correctly in the backwards direction. When I remove `roundLengths: true` it loops correctly, but then I get the blur bug on non-retina screens that is `roundLengths` exists to fix.

**Comment by robpop** [comment]
@dskoziol can you provide a CodePen / JSFiddle recreating the issue
