### ISSUE TITLE
Missed method mySwiper.translateTo()

### ISSUE THREAD

**Issue by Yubari** [nolimits4web/swiper#3298]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: macOS, CHROME

There is method `mySwiper.translateTo()` in documentation, but there is no this method in final script.

**Comment by nolimits4web** [comment]
It is added in v5
