### ISSUE TITLE
Swiper marquee takes along time until stop on mouseenter

### ISSUE THREAD

**Issue by rakan49** [nolimits4web/swiper#3314]
How can I stop swiper autoplay immediately when mouseenter on and stop it when mouseleave on  with speed: 6000 and make it doesn't take long to stop?
`var SwiperTop = new Swiper('.swiper--top', {
		spaceBetween: 0,
		speed: 6000,
		autoplay: {
			delay: 0.1
		},
		loop: true,
		slidesPerView:'auto',
		disableOnInteraction: true, 
		autoplayDisableOnInteraction: true,
	});
	$(".swiper--top").mouseenter(function() {
		SwiperTop.autoplay.stop();
		console.log('slider stopped');
	});
	$(".swiper--top").mouseleave(function() {
		SwiperTop.autoplay.start();
		console.log('slider started again');
	});`

**Comment by proksh** [comment]
Same issue. Any solution to this?
