### ISSUE TITLE
Version 4.5.2 and 4.5.3 are not published on npm

### ISSUE THREAD

**Issue by dellamina** [nolimits4web/swiper#3324]
Title should be self explanatory: last 2 releases of Swiper4 branch are not on npm.

**Comment by Josh979** [comment]
Any update on this? Encountered the same problem today.

**Comment by jasminexie** [comment]
I've found a workaround. Target the downloadable `tar` file on github in `package.json`

```
"swiper": "https://github.com/nolimits4web/swiper/archive/v4.5.3.tar.gz"
```
or 
```
npm install https://github.com/nolimits4web/swiper/archive/v4.5.3.tar.gz
```

However dependencies with `swiper` as a nested dependency may not be downloading this version, and this does not work with yarn resolutions.
