### ISSUE TITLE
Mouse wheel: debouncing scroll event instead of throttling it

### ISSUE THREAD

**Issue by a-barbieri** [nolimits4web/swiper#3326]
This is a (multiple allowed):
* [x] feature-discussion (RFC)

* Swiper Version: `55496b4a`.
* Platform/Target and Browser Versions: any desktop browser, particularly visible with Apple trackpad or Magic Mouse.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/a-barbieri/pen/ZEExOdb.

### What you did
Having a full-page slider I'm scrolling to see the content and because there is nothing but this slider I just scroll up and down. Easy.

### Expected Behavior
Every time I scroll I'd like to see the slider reacting movie up or down.

### Actual Behavior
Sometime the slider just doesn't move when I scroll and it gets worst when I try repeatedly to scroll to see if it works because then it don't move for the whole time I try. You will notice in fact that once it's blocked you can keep on trying to scroll continuously for 1 minute and the slider won't react. Only if you stop, wait a second, then retry, it will return to work.

---

### Possible cause: the scroll event keeps being debounced
The problem is in this if statement: 
https://github.com/nolimits4web/swiper/blob/55496b4a999c42aa8f58b007bb8efcf43d8de73d/src/components/mousewheel/mousewheel.js#L147-L158

`swiper.mousewheel.lastScrollTime` is updated even if the user scrolls before the time limit (currently 60ms). So for example:

- User scrolls 
- Swiper reacts moving a slide then it freezes for 60s
- After 50s the user scrolls again (unlikely but possible)
- The above action forces Swiper to reset `lastScrollTime` value to 60ms
- The above reset brings the total time Swiper is frozen to **110ms**
- After 50s the user scrolls again (very unlikely but still possible)
- The above action forces Swiper to reset `lastScrollTime` value to 60ms
- The above reset brings the total time Swiper is frozen to **170ms**
- and so on so forth until the user don't move the wheel anymore

### Is this the behaviour we want? 
I'm thinking about a situation in which the user has 40 slides and he wants to get to the bottom quickly by **scrolling like-there's-no-tomorrow**. He will not be able. He will have to scroll&wait at a specific pace until he decides to use the scrollbar (hoping that the designer didn't request to hide it).

### Throttle might be a better solution

The current behaviour is similar to Lodash `debounce` but what we really want maybe is `throttle`. If you don't know the difference please see [this article](https://css-tricks.com/debouncing-throttling-explained-examples/).

**Comment by a-barbieri** [comment]
I've seen that [Lodash](https://www.npmjs.com/package/lodash) is already a dependency of Swiper dependencies (**eslint** among other four, see [npm page](https://www.npmjs.com/package/eslint)).

I will use it in the PR I'm creating and explicitly adding it to the package dependencies. If it's a issue I can copy/paste the code, but then we need to maintaining ourselves.

**Comment by a-barbieri** [comment]
Rather than incorporating lodash entirely I might just get the [throttle package](https://www.npmjs.com/package/lodash.throttle).

Let me know your thoughts.

**Comment by nolimits4web** [comment]
Fixed by #3328
