### ISSUE TITLE
no transition effect when using slideTo with virtual slides 

### ISSUE THREAD

**Issue by imokya** [nolimits4web/swiper#3329]
no transition fade effect when using slideTo with virtual slides，the speed parameter dosen't work.
and slideChangeTransitionEnd event never gets called, if the speed parameter is greater than 0.
the problem occurs when the target slide is not in dom and the effect is Fade.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.0
* Platform/Target and Browser Versions: Windows, CHROME

**Comment by uxohotteixo** [comment]
Yeah, same problem. Need help plsss

**Comment by Hirbod** [comment]
event without virtual slides it does not work for me. touchmove works though

**Comment by Hirbod** [comment]
Not stale

**Comment by jonxssc** [comment]
still a problem
