### ISSUE TITLE
Thumbs stops working after I destroy and reinit the sliders

### ISSUE THREAD

**Issue by TheZanBoy** [nolimits4web/swiper#3331]
This is a :
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Tested from 4.5 => 5.2.0
* Platform/Target and Browser Versions: Chrome Win 10 / Chrome macOs Catalina
* JSFiddle: https://jsfiddle.net/49jayf28/

### Steps to reproduce the issue in JSFiddle
* If you first destroy and then reinit, thumbs component stops working.
* If you first reinit destroy and then reinit again, thumbs component works just fine.
(refresh for each step)

### Expected Behavior
Destroy and reinit sliders with the same passed params

### Actual Behavior
After I destroy and reinit the sliders everything works except for thumbs component, when I click nothing happens (no errors in the console).

**Comment by nolimits4web** [comment]
You need to pass first `.destroy` argument as `true` to correctly destroy it or without args at all:
```
galleryThumbs.destroy();
galleryTop.destroy();
```
