### ISSUE TITLE
slide with img background become white at first time on edge 41

### ISSUE THREAD

**Issue by cyphernull** [nolimits4web/swiper#3332]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
new Swiper('.swiper-container', {
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      speed: 1200,
      allowTouchMove: false,
      autoplay: {
        delay: 3000,
        disableOnInteraction: false,
      },
      loop: true,
    });

### Expected Behavior
img should be displayed correctly

### Actual Behavior
when page loaded: after the first two imgs passed the third slide became white. After 1 or 2 seconds then the third img finally shows. 

when the above behaviour happened, every slide has the same werid issue

![IMG_0412 2](https://user-images.githubusercontent.com/23122353/68542196-05ec7c80-03e5-11ea-8911-a9edf08d6fbf.jpg)

**Comment by sourcejockey** [comment]
I added a "loopedSlides" parameter, and it fixed this issue for me.

**Comment by bradley2083** [comment]
@sourcejockey What did you set the "loopedSlides" parameter to?  It seems that this works if you set it to the number of slides, but that's not a great solution if the number of slides is dynamic on a per page basis.  Any ideas how to handle that?  I'm getting a blank slide at the end of clicking (if you click the slide image --> https://codepen.io/bradley2083/pen/zYYepdp ... however, if you click "next" it continues to loop okay.
