### ISSUE TITLE
Stop the scroll with the touch in freemode

### ISSUE THREAD

**Issue by boesbo** [nolimits4web/swiper#3336]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

To give usability similar to slides for mobile native apps it would be necessary for the freemode scroll to stop at the touch. Is this work done?

**Comment by Brolly0204** [comment]
Is there a solution? I'm doing a running lamp. I can't stop the animation right away
