### ISSUE TITLE
Blue lines on mobile Chrome

### ISSUE THREAD

**Issue by TasioC** [nolimits4web/swiper#3338]
[Hello !!
I have a problem when my slides is opened on mobile chrome, that when i touch the screem show a blue lines arround the container of my swiper. I dont know where is the porblem i have the effect "fade".
 var swiper = new Swiper('.swiper-container', {
     
                loop: true,
                slidesPerView: '1',
                effect:  'fade',
                fadeEffect: {
                    crossFade: true
                },navigation: {
                    nextEl: '.swiper-button-next',
                    prevEl: '.swiper-button-prev',
                },
    });

]
![unnamed](https://user-images.githubusercontent.com/44347615/68684843-6c9aa300-0569-11ea-888c-46bea2e0e1bb.jpg)

**Comment by nolimits4web** [comment]
That some rendering bug or your styles issue. Swiper doesn't add any blue lines
