### ISSUE TITLE
Slide to clicked slide breaks with loop set to true

### ISSUE THREAD

**Issue by bradley2083** [nolimits4web/swiper#3343]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.0
* Platform/Target and Browser Versions: macOS and Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/bradley2083/pen/zYYepdp

### What you did
In my pen, click next slide image a few times and notice after a few clicks the loop ends (but it's set to true).  If you reload and then click the "next" navigation link (rather than the next slide image), you'll see the loop functions as expected.   If I add "loopedSlides: 3" to my options, it works.  This isn't a great solution though because the number of slides will change on a per page basis so this needs to be dynamic. 

### Expected Behavior
The loop should continue. 

### Actual Behavior
See above.  Thank you!

**Comment by ynamite** [comment]
This is a bug and should be fixed 🤷🏽‍♂️

**Comment by dothar** [comment]
Having the same issue here...

**Comment by vltansky** [comment]
Updated demo with the latest swiper: https://codepen.io/vltansky/pen/gOwJqPx

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
