### ISSUE TITLE
Multiple slideChange events triggered when looping

### ISSUE THREAD

**Issue by widmanski** [nolimits4web/swiper#3344]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 8d55dba4f1250ea272e385773a9e558644a2889c
* Platform/Target and Browser Versions: macOS, Windows, Chrome & other browsers (believed to be consistently reproducible regardless of the env)
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/qmzk5sau/

### What you did
When running Swiper in looped mode, the slideChange event is emitted twice when going from the last slide to the first slide, and then to the next slide, or from the first slide to the last slide, and then to the previous slide. The extra event is emitted from the change between the "duplicate slide" (`.swiper-slide-duplicate`) created for looping, and the "real slide" - which is not visible to the end user.

### Expected Behavior
Changing between the duplicate slide and the "real" slide should not emit a `slideChange` event. Changing from the last slide to the first slide should emit a single `slideChange` event. The change from the duplicate to real is not visible to the end user.

Alternatively, a `realSlideChange` event could be emitted, if the duplicate `slideChange` is required for some purpose.

### Actual Behavior
1. Swipe to the previous slide (1 -> 4) - observe a single `slideChange` event
2. Swipe to the previous slide again (4 -> 3) - observe two `slideChange` events

**Comment by widmanski** [comment]
Update: when reviewing the source code, I actually found a `realIndexChange` event. The event, however, is not documented. 

In this case, it seems like the fix would be to update the documentation to:
- include a note that `slideChange` is emitted twice in looped mode
- include a note about `realIndexChange`

**Comment by thenomadicmann** [comment]
@widmanski I am also experiencing this issue.

**Comment by maestroosram** [comment]
The issue is stil present in Swiper js for Nuxt3
`realIndexChange` is the only usable event for checking slide change
