### ISSUE TITLE
SASS + CSS3 var issue

### ISSUE THREAD

**Issue by Kassaila** [nolimits4web/swiper#3345]
Hi, guys.

I have used SCSS version of the swiper for my project and faced with out of shielding on `--swiper-theme-color: $themeColor;`

https://prnt.sc/pzyuqc There should be `--swiper-theme-color: #{$themeColor};`

Please, take a look

**Comment by TanShun** [comment]
@nolimits4web I have the same issue, here has the reason:  [Sass 3.5 Release Candidate](http://sass.logdown.com/posts/809572-sass-35-release-candidate)

**Comment by adampatterson** [comment]
Thank you! 

My experience in using the scss has been frustrating so far, once I found that I had to include the components I was not able to change the theme color.
