### ISSUE TITLE
Randomize Slides?

### ISSUE THREAD

**Issue by Toolbox3** [nolimits4web/swiper#3346]
* Swiper Version: 2.1
* https://test.tractionworksdev.com

### I am able to feed swiper slides and it works just fine with the sliding and swipe functionality on both desktop and mobile. 
---HTML (php using ACF)
<div class="swiper-container">
	<div class="swiper-wrapper">
               <?php if (have_rows('video_thumbs')):
               while (have_rows('video_thumbs')): the_row(); ?>
                    <div class="swiper-slide" id="swiper-slide">
     	               <div href="#" class="box">
                            <div class="video-top">
     			      <img class="top"src="<?php the_sub_field('video_thumb2'); ?>">
                                  <a href="#" class="<?php the_sub_field('video_id'); ?> play-button"></a>
                           </div>
     		  <div class="overlay <?php the_sub_field('video_id'); ?>"></div>
     		      <img class="thumb-main"src="<?php the_sub_field('video_thumb'); ?>">
                          <h3><?php the_sub_field('title'); ?></h3>
     		  <div class="bottom">
                          <h4><?php the_sub_field('description'); ?></h4>
                  </div>
                  <a href="#" class="vertical">SEE ALL <?php the_sub_field('category'); ?></a>
                      <?php
                          $videolink = get_sub_field('video_embed');
                          $videoid = get_sub_field('video_id');
                                 echo do_shortcode('[wp-video-popup id="' .$videoid. '" 
                                 video="' .$videolink. '"]'); ?>
     	          </div>
		</div>
              <?php endwhile;
              endif; ?>
         </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
----JS------
<script src="https://unpkg.com/swiper/js/swiper.min.js"></script>

 <script>
	 var swiper = new Swiper('.swiper-container', {
		 slidesPerView: 1.5,
		 spaceBetween: 5,
		 // init: false,
		 navigation: {
         nextEl: '.swiper-button-next',
         prevEl: '.swiper-button-prev',
      },
         pagination: {
	          el: '.swiper-pagination',
		  clickable: true,
		  arrows: true,
		 },
		 breakpoints: {
			 640: {
				 slidesPerView: 2,
				 spaceBetween: 5,
			 },
			 768: {
				 slidesPerView: 3,
				 spaceBetween: 5,
			 },
			 1024: {
				 slidesPerView: 4,
				 spaceBetween: 3,
			 },
		 }
	 });
 </script>

-------------What I am Wanting-------------
I just want to try to randomize the .swiper-slide div on page load.

**Comment by sshra** [comment]
You can shuffle slides before swiper init, look an example here:
https://shra.ru/2021/03/peremeshivaem-slajjdy-pered-nachalom-raboty-v-swiper-js/
