### ISSUE TITLE
Breakpoint initialization is ignoring the current screen size (or the default option)

### ISSUE THREAD

**Issue by iskyd** [nolimits4web/swiper#3348]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 5.2.1
* Platform/Target and Browser Versions: Google Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/6xruhe5k/6/

I have specified 3 breakpoints with differente slidesPerView and a default slidesPerView option. When swiper loads at first he doesn't load my default slidesPerView but only 1 slides per view. This create a bad effects. 

This is my configuration:
```
var swiperReccomended = new Swiper ('.swiper-reccomended', {
                // Optional parameters
                direction: 'horizontal',
                loop: true,
                slidesPerView: 4,
                spaceBetween: 25,
                breakpoints: {
                    768: {
                        slidesPerView: 2,
                        spaceBetweenSlides: 25
                    },
                    991: {
                        slidesPerView: 2,
                        spaceBetweenSlides: 25
                    },
                    1240: {
                        slidesPerView: 4,
                        spaceBetweenSlides: 25
                    }
                }
            })
```

As you can see from the [fiddle](https://jsfiddle.net/6xruhe5k/6/) when it loads he just loads 1 slidePerView and then apply the breakpoints configuration, but my default configuration is using 4 slidesPerView.

I'm doing the same thing as in the example provided here (that seems to work): https://github.com/nolimits4web/Swiper/blob/master/demos/380-responsive-breakpoints.html

The example uses 1 slidesPerView as default configuration so it seems to works, but maybe it's just because it's not using a configuration with a default slidesPerView != 1.

**Comment by lwxbr** [comment]
I had that problem too. My guess is they changed to get the min instead of max, so the breakpoint is min 1240, min 991, 768 and the default is when you didn't match any breakpoint. I want a way to force the max instead the min, it broke all the breakpoints i've set.

**Comment by simmonsr** [comment]
@nolimits4web yes, default parameters are being ignored here: https://swiperjs.com/api/#thumbs

**Comment by simmonsr** [comment]
ok looks like you changed it from <= to >= after 4.4.6...

**Comment by nolimits4web** [comment]
No need to guess, it clearly stated in v5 changelog https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#swiper-500---released-on-september-17-2019
