### ISSUE TITLE
Zoom position is incorrect when you need to scroll page down to the swiper

### ISSUE THREAD

**Issue by acromatica** [nolimits4web/swiper#3351]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.1.
* Platform/Target and Browser Versions: macOS Chrome 78.0.3904.108, IOS 13.1.3 Safari.
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/acromatica/pen/VwZydyR.

### What you did
Add a swiper with zoom to a page that has any content (or just empty space) above the swiper.

### Expected Behavior
When you double click or double tap an image from swiper it should zoom clicked area of image, for example top right corner of the image.

### Actual Behavior
Bottom half of the image gets zoomed.

https://www.dropbox.com/s/9zxg5tf2n3eljpo/zoom-position.mov?dl=0

**Comment by acromatica** [comment]
It looks like `gesture.$slideEl.offset().top` returns incorrect value (document scroll always returns 0).

**Comment by alexGDdev** [comment]
In our case we solved the problem using jQuery:

`jQuery(gesture.$slideEl).offset().top;`

Seems that Swiper calculates `offset()` differently, and in our implementation of swiper produce unwanted effects.
