### ISSUE TITLE
slidesOffsetAfter and slidesPerView: 'auto' bug

### ISSUE THREAD

**Issue by maxonik** [nolimits4web/swiper#3352]
* [x] bug

* Swiper Version: 4.5.1
* Platform/Target and Browser Versions: Windows, Chrome 78.0.3904.108
* Live Link: https://jsfiddle.net/mbibko/szg0uynk/6/

![image](https://user-images.githubusercontent.com/3294708/69622676-20ac2b80-104a-11ea-86d6-3ec630ce9356.png)

When swipe on last slide, slider scrolls offset so big 
![image](https://user-images.githubusercontent.com/3294708/69622302-5a306700-1049-11ea-9ba6-4705526edc73.png)

**Comment by nolimits4web** [comment]
`slidesOffsetAfter` should be a number

**Comment by maxonik** [comment]
Thanks! Sorry
