### ISSUE TITLE
Mousewheel Failing

### ISSUE THREAD

**Issue by Maor44** [nolimits4web/swiper#3358]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: ^5.2.1
* Platform/Target and Browser Versions: Windows10, Chrome, and FF. 
* Live Link or JSFiddle/Codepen or website with issue:  https://swiperjs.com/demos/270-mousewheel-control.html

### What you did
The mousewheel scrolling fails intermittently. need to scroll a lot of time to move one slide.

### Expected Behavior
Free scroll with mousewheel

### Actual Behavior
Mousewheel slider control does not function

this problem was discussed here: https://github.com/nolimits4web/swiper/issues/2624 but didn't see any solution for this problem.

**Comment by Baggio89** [comment]
Seeing #2624 i thought, could this have something to do with the grab simulation? In the API the grabCursor only 'fires' after the mouse is clicked and then dragged. If this same behaviour is in the scrollEvent i can see why scrolling has to happen multiple times. 

Just a thought, will dive into this :)

**Comment by shangxinbo** [comment]
any solution?

**Comment by stormitornado** [comment]
This problem affects only mousewheel, touchpad is still working.
I've faced this problem on every browser, and there is also another bug: when you pass an object to mousewheel property, it doesn't enable it, only  mousewheel: true  is working

**Comment by Baggio89** [comment]
No fix yet?

**Comment by stormitornado** [comment]
I've checked in version 6.0.4 - it's functions normally
