### ISSUE TITLE
Pagination bullets don't always go to the correct slide

### ISSUE THREAD

**Issue by karengill** [nolimits4web/swiper#3359]
This is a:
* [x] bug

* **Swiper Version:** Whatever version the Swiper demo page is using (I'm using the most recent version on my own website and seeing the same issues as the demo page)
* **Platform/Target and Browser Versions:** Mac 10.13.4 / Chrome Version 78.0.3904.108 | Firefox 71.0 (64-bit) | Safari Version 11.1
* **Live Link or JSFiddle/Codepen or website with isssue:** https://swiperjs.com/demos/ (Custom Pagination Demo)

### What you did
I clicked through the pagination numerically in order: 1, 2, 3, 4, 5 ... etc.

### Expected Behavior
I expect it to slide to the slide that I am clicking on in order

### Actual Behavior
Most times you get to #5, and all of a sudden it starts highlighting and going to past slides rather than the slide you clicked on. Keep clicking in order and you'll see it jump around, it's very inconsistent.

**Comment by Yi98** [comment]
I tried it and it works just fine.

**Comment by karengill** [comment]
Here is a screencast using the "Custom Pagination" Demo on Swiper's own website. 

http://somup.com/cYVrqjf9C5

You will be clicking on items in order and all of a sudden it will jump and start highlighting items backwards or just going to random slides.

**Comment by leonexcc** [comment]
We have the exact same problem in one of our projects.

**Comment by yomizhong** [comment]
same problems

**Comment by domxdom** [comment]
same problem in one of our projects.
`version: "5.2.0"`

and seeing the same issues as the demo page
`version: "5.3.8"`

**Comment by yomizhong** [comment]
aha，touchEventsTarget: 'wrapper', it helped me
