### ISSUE TITLE
Swiper works in desktop not mobile

### ISSUE THREAD

**Issue by sanishkr** [nolimits4web/swiper#3360]
* [x] bug

* Swiper Version: Current - 13236e2
* Platform/Target and Browser Versions:  ANDROID CHROME.
* CodeSandBox link : https://codesandbox.io/s/relaxed-fast-q8387?fontsize=14&hidenavigation=1&theme=dark

### What you did
In App2 of Above Link - I use useEffect hook of react, got some data, put it in some state using useState hook. then initiated the swiper. 
App.js one works perfectly and also App2.js works if I use it like class-based component.

### Expected Behavior
Swiper swiping in all devices as normal

### Actual Behavior
Slides don't swipe in mobile or sometimes no slide appears.

**Comment by nolimits4web** [comment]
There is something wrong in your code, make sure you init them when they are in DOM, and make sure you have specified unique selectors for both of them
