### ISSUE TITLE
Swiper not working on Internet Explorer

### ISSUE THREAD

**Issue by Jotomen91** [nolimits4web/swiper#3364]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.1
* Platform/Target and Browser Versions: Windows 10, Internet Explorer Version: 11.476.18362.0.

### What you did
We implemented Swiper library in our project. We tried to use Scroll Container on Internet Explorer Version: 11.476.18362.0.

### Expected Behavior
Scroll Container should be working properly with the mouse scroll, but it doesn't. 

### Actual Behavior
You can't scroll with the mouse scroll because of Math.sign() is not supported for IE11. The official demo are not working on IE11 either - https://swiperjs.com/demos/.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Sorry but Internet Explored is not supported by Swiper

**Comment by TongjieYang** [comment]
@Jotomen91 when you can babel, you can add swiper and dom 7 , it work in ie11
