### ISSUE TITLE
Need to Stop Autoplay at a timed interval NO HOVER

### ISSUE THREAD

**Issue by soupking** [nolimits4web/swiper#3372]
Hi there,

I'm searching through the API and forum posts and I can't find anything to stop or timeout autoplay at a given amount of time. 

Isn't there something like that available? Please advise, I'd be super stoked to know if this is possible. 

Thanks!

**Comment by nolimits4web** [comment]
```
setTimeout(() => {
  swiper.autoplay.stop()
}, 3000)
