### ISSUE TITLE
swiper width: auto not working.

### ISSUE THREAD

**Issue by PavankumarKori1** [nolimits4web/swiper#3380]
I want slider width to be auto. But when i put width: auto; Slider not working

Here is the [codepen](https://codepen.io/pavankumar_kori/pen/dyPWdyx)

**Comment by muuvmuuv** [comment]
I would love to see some functionality as well. The slides I show all have a fixed with and their own breakpoints and I do not want Swiper handle that, especially because they can vary in width.

**Comment by PavankumarKori1** [comment]
what I need is Test slider. the width should be auto. But it is taking full width.

**Comment by muuvmuuv** [comment]
I have found a workaround by just using `width: auto !important` on the slide item element. This works for our case.

**Comment by PavankumarKori1** [comment]
Thank you width: auto !important worked

**Comment by basicfeatures** [comment]
Would be nice with a proper way of doing this though. I'm trying to avoid patching my stylesheets with `!important` altogether.
