### ISSUE TITLE
Mousewheel Fail when refresh

### ISSUE THREAD

**Issue by Luluda** [nolimits4web/swiper#3382]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: ^5.2.1
* Platform/Target and Browser Versions:  macOS(0.14.3), Chrome(79.0.3945.88), safari(12.0.3)
* Live Link or JSFiddle/Codepen or website with isssue:  https://swiperjs.com/demos/270-mousewheel-control.html

### What you did
Refreshing the website and don't move my mouse, scroll mouse wheel, the page doesn't scroll. If I move the mouse or click, the bug is fixed and I can scroll the page.
This occurs  when I use touchpad too.
### Expected Behavior
When I refresh the page, even I don't move the mouse, I can scroll the website.

### Actual Behavior
This bug happens in my project, too. My config is as below:
```
swiperOption: {
                    direction: 'vertical',
                    mousewheel: {
                        disable: true,
                        sensitivity: 5
                    },
                    speed: 800,
                    parallax: true,
                    slidesPerView: 'auto'
                }
```

Then I debug the source code of swiper, I find the bug is caused by
https://github.com/nolimits4web/swiper/blob/765d9a1c062f5ee7d0a583576082cd1542988673/src/components/mousewheel/mousewheel.js#L124
before I move the mouse, `swiper.mouseEntered = false`, and `releaseOnEdges = false` cause I don't need this.
My solution is to set `releaseOnEdges = true` and this is fixed, but it's not reasonable cause I don't want releaseOnEdges feature。This problem was discussed here: [#2624](https://github.com/nolimits4web/swiper/issues/2624)
I'll commit a pr to fix this, and it works in my project

**Comment by nolimits4web** [comment]
Fixed in #3383
