### ISSUE TITLE
```I tried this and even separate classes for containers but 2nd swiper works only when the browser is resized

### ISSUE THREAD

**Issue by ibrahimshams79** [nolimits4web/swiper#3384]
```
<div class="swiper-container" id="swiper1">...</div>
<div class="swiper-container" id="swiper2">...</div>
```

```
var swiper1 = new Swiper('#swiper1', {...});
var swiper2 = new Swiper('#swiper2', {...});
```

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/1016#issuecomment-65376823_

**Comment by ibrahimshams79** [comment]
I have tabs to hide and show 2 swipers in a single page. when I unhide the 2nd swiper it doesn't work until I resize the browser. 

**I TRIED ALL THESES METHODS...**

	<script>
    var swiper1 = new Swiper('.s1',
	{
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 30,
        stretch: -70,
        depth: 600,
        modifier: 1,
        slideShadows : true,
		preloadImages: false,
		lazyLoading: true
      }
    }	
	);
	
	    var swiper2 = new Swiper('.s2', 
	{
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 30,
        stretch: -70,
        depth: 600,
        modifier: 1,
        slideShadows : true
      }
    }
	);
	
  </script>
  
**or...
TARGETING BY ID**


  
  **or...**

**Comment by ibrahimshams79** [comment]
<script>
    var swiper1 = new Swiper('.s1',
	{
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 30,
        stretch: -70,
        depth: 600,
        modifier: 1,
        slideShadows : true,
		preloadImages: false,
		lazyLoading: true
      }
    }	
	);
	
	    var swiper2 = new Swiper('.s2', 
	{
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 30,
        stretch: -70,
        depth: 600,
        modifier: 1,
        slideShadows : true
      }
    }
	);
	
  </script>

**Comment by ibrahimshams79** [comment]
or...
TARGETING BY ID

**Comment by nolimits4web** [comment]
You need to call `update()` when it becomes visible
