### ISSUE TITLE
initialSlide should apply the correct class in the thumbs component

### ISSUE THREAD

**Issue by scooterlord** [nolimits4web/swiper#3385]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Using the latest swiper version..

when applying the `initialSlide` option on a thumbs component that is synced to a thumbs gallery, then the class `swiper-slide-active` is _in fact_ added, but in essence the `swiper-slide-thumb-active` should be applied to make it work properly.

The class `swiper-slide-active` is only added when option `centeredSlides:true` is set for the thumbs component.

**Comment by ronaldbarendse** [comment]
Just updated from 4.5.0 to 4.5.1 and it indeed doesn't add the `swiper-slide-thumb-active` class anymore.

**Comment by ronaldbarendse** [comment]
Version 4.5.1 is the lastest 4.x published on npm: https://www.npmjs.com/package/swiper, so [4.5.2](https://github.com/nolimits4web/swiper/releases/tag/v4.5.2) and [4.5.3](https://github.com/nolimits4web/swiper/releases/tag/v4.5.3) are currently not published...

**Comment by feibi** [comment]
The same problem for me

**Comment by philwolstenholme** [comment]
@nolimits4web would you be able to publish 4.5.2 and 4.5.3 on npm? I can't upgrade to >5 because I need IE11 support, but 4.5.1 has the bug described in this ticket, so I'd like to try 4.5.2 or 4.53.
