### ISSUE TITLE
Swiper cube loop problem

### ISSUE THREAD

**Issue by Micu22** [nolimits4web/swiper#3386]
* [x] bug

* Platform/Target and Browser Versions: both chrome 79 and edge produce a problem
* Live Link or JSFiddle/Codepen or website with isssue: [https://biiird.com/slider/](url) (there are two swipers, the issue is about the cube one

### What I did
I have created a cube slider with the parameter loop: true,
The slider glitches between the first and the last slide when swiping backwards
Here is the swiper code:
`var swiper = new Swiper( '.custom-swiper > .elementor-container', {
        speed: 400, 
        loop: true, 
        parallax: true, 
        effect: 'cube',
        grabCursor: true,
        cubeEffect: {
            shadow: true,
            slideShadows: false,
            shadowOffset: 20,
            shadowScale: 0.94,
        },
        navigation: {
            nextEl: '.custom-swiper .swiper-button-next',
            prevEl: '.custom-swiper .swiper-button-prev',
        },`

### Expected Behavior
slides going in a loop without glitches

### Actual Behavior
glitch between the first and last slide when sliding backwards

![image](https://user-images.githubusercontent.com/51614436/71597236-a9831f00-2b42-11ea-94eb-6e4df92a0e26.png)
![image](https://user-images.githubusercontent.com/51614436/71597254-ba339500-2b42-11ea-9334-deda68592c08.png)
![image](https://user-images.githubusercontent.com/51614436/71597279-ce779200-2b42-11ea-87b5-772c069cbea8.png)

**Comment by Yi98** [comment]
Can you provide the html code? I would like to replicate your problem :)

**Comment by Micu22** [comment]
You can see the problem here on codepen: 
[https://codepen.io/iamrc1/pen/MdGKYQ](url)
I can provide my code, but this is simpler and shows the same problem.
When going from first slide directly to the last one by draging the animation glitches.

**Comment by Yi98** [comment]
I found out that there must be at least 4 swiper-slide components inside a swiper-wrapper for it behave normally. In your case, you have only 3 swiper-slide components which is also why the unexpected behavior occurred. This is indeed a bug that need to be fixed. For now, you may choose to add on 1 more swiper-slide to temporarily solve the issue :)

**Comment by Gumbraise** [comment]
Still here

**Comment by Dupflo** [comment]
Still there

**Comment by EmanuelOcampo** [comment]
still there
