### ISSUE TITLE
 Click on a thumb with Apple Magic Trackpad 2

### ISSUE THREAD

**Issue by GuiguiWeb** [nolimits4web/swiper#3388]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.0.4 and 5.2.1
* Platform/Target and Browser Versions: macOS - CHROME
* Live Link: https://jsfiddle.net/GuiguiWeb/s4h17p9v/11/

### What you did
Use a Magic Trackpad 2 to click on the thumbs (sometimes it works, so try several times).
The bug can be reproduced on https://jsfiddle.net/GuiguiWeb/s4h17p9v/11/

### Expected Behavior
When I click on a thumb, it should activate.

### Actual Behavior
When I click on a thumb with Apple Magic Trackpad 2, it works randomly.
The touchStart event occurs all the time but not necessarily the click event.
The double tap event works well.

**Comment by CressZZ** [comment]
You can add these option

threshold: 10,
shortSwipes: false

**Comment by GuiguiWeb** [comment]
@CressZZ  
It doesn't work: https://jsfiddle.net/GuiguiWeb/s4h17p9v/13/

**Comment by GuiguiWeb** [comment]
> You can add these option
> 
> threshold: 10,
> shortSwipes: false

It works ! Thank you !
