### ISSUE TITLE
Document `data-sizes` lazy loading attribute

### ISSUE THREAD

**Issue by patrickcate** [nolimits4web/swiper#3391]
* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.1

I ran into the same issue with lazy loading breaking srcset media conditions as: https://github.com/nolimits4web/swiper/issues/2499

The solution for me was to use the `data-sizes` attribute instead of the regular `sizes` attribute. This isn't documented [in the API](https://swiperjs.com/api/#lazy) however. I only found out about the attribute by looking at the source code linked in the https://github.com/nolimits4web/swiper/issues/2499 issue.

It would be great if this documentation was added.

P.S. Thanks for your great work on this library, it's my go-to slider.

**Comment by simeonbugarija** [comment]
Hey @patrickcate, could you please provide more information on how you made this work? I tried your suggestion and it works when i resize the window, but when I toogle the device toolbar and switch to responsive mode then it shows always the larger image.

![image](https://user-images.githubusercontent.com/10814563/124128014-a4c36200-da7c-11eb-9a54-1f259ee13486.png)

![image](https://user-images.githubusercontent.com/10814563/124128043-ad1b9d00-da7c-11eb-9824-a313e98d10c8.png)
