### ISSUE TITLE
Problem with Subpixel

### ISSUE THREAD

**Issue by nischi** [nolimits4web/swiper#3392]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.0
* Platform/Target and Browser Versions: Windows 10, Chrome 79
* Live Link or JSFiddle/Codepen or website with isssue: Screenshots. It is a internal application.

### What you did
Create a simple slider:

We have a problem with some supixels on .swiper-wrapper. Swiper use here 100% for the width, which is fine. Thats exactly 833.5px for example, depends on screen of course.

### Expected Behavior
Use subpixels everywhere. My suggestion are that we use floating pixels for .swiper-slide

### Actual Behavior
So but the width they give to .swiper-slide is always a int instead of float. Which means 834px.

Normal:
![70322106-7abaa700-1829-11ea-848a-0dd5a13899d8](https://user-images.githubusercontent.com/2036054/71764111-cec9b180-2ee3-11ea-812e-05775ba8aaf1.png)

Cutted

![70322109-7d1d0100-1829-11ea-85f4-7c4e144fb063](https://user-images.githubusercontent.com/2036054/71764110-cbcec100-2ee3-11ea-8b8c-e9a9b2956df0.png)

That ends that after 10 slides we miss 5px. Which cut the content.

**Comment by SimonPrimetzhofer** [comment]
Adding a "padding-left: 5px;" solves the issue but an out-of-the-box solution would be great!

**Comment by scottgonzalez** [comment]
Can we get this issue reopened? This is noticeable in a lot of scenarios.

**Comment by unnamed777** [comment]
The issue with subpixel is really annoying.
