### ISSUE TITLE
Slides get stuck at the end when dragging mouse

### ISSUE THREAD

**Issue by ben-styling** [nolimits4web/swiper#3398]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: **5.3.0**
You can see this on Swiper's own demo.
https://swiperjs.com/demos/110-slides-per-view.html

### What you did
Use the mouse to drag slides, when you get to the end the slides get stuck and the next navigation arrow isn't in the disabled state.

### Expected Behavior
To spring back like it does when you try and go back from the first slide.

### Actual Behavior
The slides get stuck and the next navigation arrow isn't in the disabled state.

**Comment by Raisenku** [comment]
Can confirm, also the last slide's images aren't loaded if they are lazy loaded

**Comment by grloch** [comment]
I can confirm this too, I use 4  slides per group:
```
var mySwiper = new Swiper('.swiper-container', {
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        }, slidesPerView: 'auto',
        freeMode: false,
        slidesPerGroup: 4,
        spaceBetween: 10,
        centerInsufficientSlides:true,
        loop: false,
    })
```

**Comment by milanwake** [comment]
I also have this error. In earlier versions it was not.

**Comment by codesignist** [comment]
I think this bug should related with this change:
https://github.com/nolimits4web/swiper/commit/cd87ce51fca74b6ddecb5c64618300d59bacc4c4#diff-a285802d362fd397a1e00fc52eb92e72

**Comment by codesignist** [comment]
More details about this bug:
- If you make "centeredSlides: true" it works correctly.
- If you move your mouse slow it works well too. But when you move your mouse fast and on mouse up it suddenly stops.

**Comment by francesco-bizen** [comment]
Encountered this bug today as well (and a lot of other ones too...).
What fixed it for me was declaring the same value for both slidesPerView and slidesPerGroup.

Also had a bug that would make the slider get stuck on resize from lower to higher resolution if i was on the last page. Basically if i was on last page with 2 slides, once i resize to show 3 slides the last slot would be empty and the whole slider would be off position. Resolved this by attaching a slideTo(0) action to the resize event.

**Comment by dangelion** [comment]
Same problem here.

Thanks @francesco-bizen, adding `slidesPerGroup` with same value of `slidesPerView` solved, for me. 

Anyway, waiting for a proper bugfix from Swiper in the next release.

**Comment by fedemar** [comment]
Adding slidesPerGroup with same value as slidesPerView prevents carousel from moving in any direction when the value is 'auto'.

**Comment by MMasey** [comment]
I can also confirm that this bug is occuring. In my instance I am using `slidesPerView: "auto"` so the slidesPerGroup fix won't work for me. 

I had a quick check of @codesignist's PR #3414 and it seems to fix the issue.

**Comment by fedemar** [comment]
@codesignist's PR #3414 fixed the issue for me

**Comment by nolimits4web** [comment]
Fixed by #3414

**Comment by tarpagad** [comment]
Looks like the bug just reappeared again : unable to reach the last 3-5 slides 🤔

**Comment by cgarrovillo** [comment]
@nolimits4web

**Comment by sinansubasi95** [comment]
I have the same problem.

**Comment by agalloch21** [comment]
setting **touchReleaseOnEdges** to true solves my problem

**Comment by nuleongee** [comment]
I solved it by adding **touchStartForcePreventDefault**

**Comment by gabemate** [comment]
> setting **touchReleaseOnEdges** to true solves my problem

This fixed mine thanks for this

**Comment by SefyanKehail** [comment]
You can reproduce the bug if you set a margin on the x axis on each swiper-slide.
I just make sure to use spaceBetween instead, that was it for me.

**Comment by santibh** [comment]
Setting **freeMode** to true solves my problem
