### ISSUE TITLE
Prev/next icons don't render within shadow DOM

### ISSUE THREAD

**Issue by richrd** [nolimits4web/swiper#3400]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 5.0.0 and above
* Platform/Target and Browser Versions: Chrome, Firefox and likely other browsers

### What you did
Use Swiper within a shadow DOM.

### Expected Behavior
Seeing the icon font rendered in the prev / next buttons.

### Actual Behavior
No icons are shown, instead the texts "prev" and "next" are visible.

This seems to be more like a browser bug. Seems like `@font-face` isn't supported at all within shadow DOM. I'm reporting it here anyway just in case, since Swiper uses the icon font by default since v5.0.0. Chrome bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=336876
Other issues related to fonts within shadow DOM: https://github.com/ionic-team/stencil/issues/1875 https://github.com/ionic-team/stencil/issues/2072

**Comment by alex84G** [comment]
You have to query the prev and next button manually in the shadow dom and add the HTMLElements in the navigation object:

const slide = this.shadowRoot.querySelector('.swiper-container');
const prev = this.shadowRoot.querySelector('.swiper-button-prev');
const next = this.shadowRoot.querySelector('.swiper-button-next');

const mySwiper = new Swiper(slide, {
navigation: {
	nextEl: next,
	prevEl: prev,
     	},
});

**Comment by richrd** [comment]
Yes I know, I'm already doing that and the buttons work fine, they are just missing the icons. They also have the correct classes. The issue is that CSS in shadow DOM can't load custom fonts which the icons in the buttons are based on.

**Comment by scenaristeur** [comment]
hi @richrd , i'm new to swiper, but old in Polymer, so
If it could help I got it working in Polymer /Lit-element https://github.com/scenaristeur/solidarity/blob/master/src/hola/app-element.js
i add it at the beginning of the render  <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">

and in the html https://github.com/scenaristeur/solidarity/blob/master/dist/index_swipe.html

here is the result https://scenaristeur.github.io/solidarity/index_swipe.html

![image](https://user-images.githubusercontent.com/4020744/74487568-13237680-4ec0-11ea-9ca2-237a6c87ddda.png)

**Comment by richrd** [comment]
@scenaristeur Was the polymer implementation using native shadow dom or was it polyfilled somehow? I tried to check but your links no longer seem to work.

Anyway the issue seems to be a browser bug mostly, just wanted to mention it here in case others hit the same problem.
