### ISSUE TITLE
请问为什么设置了mousewheel: true  但是鼠标连续滚动不了呢

### ISSUE THREAD

**Issue by 1067831145** [nolimits4web/swiper#3404]

**Comment by windy0220** [comment]
我也是这个问题，一共三页，滚动到第二页，滚轮就不起作用了。我看swpier中文网的demo 也是这个bug "swiper": "^5.3.6",

---
I have this problem too. There are three pages in total. If you scroll to the second page, the scroll wheel will not work. I see the demo of swpier Chinese website is also this bug "swiper": "^ 5.3.6",
