### ISSUE TITLE
Autoplay does not work when fade effect enabled

### ISSUE THREAD

**Issue by ngamanning** [nolimits4web/swiper#3408]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
<script>
    var homeSlider = new Swiper('.home-carousel .swiper-container', {
        slidesPerView: 1,       
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        autoPlay: {
            delay: 3000,           
        },      

    });
    if (homeSlider) {
        homeSlider.autoplay.start();        
    }
   
</script>

### Expected Behavior
Swiper (in this case it works as a carousel) should loop back to the first slide after the the entire carousel has been played. 

### Actual Behavior

When fade effect enabled with autoplay, autoplay only loops through swiper slide once and it does not repeat after the last slide. Slide, cube and coverflow effect work as expected. Only fade effect has this behaviour.

**Comment by marckraw** [comment]
What swiper version are you using ? @ngamanning 

We had the same problem, but the reason was were using version 5.3.0 and we've started using `.scss` files. And we've imported only `swiper.scss` without explicitly importing other styles from swiper.

So to have effects-fade working we had to import that `.scss` files:
```
@import "~swiper/swiper";
@import "~swiper/components/effect-fade/effect-fade";
```
and then fade effect was working correctly :)

**Comment by ngamanning** [comment]
@marckraw We're using 5.3.0. The fade effect works  but the autoplay on fade effect doesn't. I tried the SASS way you suggested and yet the autoplay still doesn't work :-(

**Comment by ngamanning** [comment]
The fade effect does work with auto play. We had a transition declaration on the slider and that throws off the swiper transition. Removed the custom transition and everything is fine.

**Comment by sk8Guerra** [comment]
I'm using `Swiper` component for reactjs like this: 
`<Swiper slidesPerView={1} effect={"cube"} fadeEffect={{ crossFade: true }}>` but effect is still like a slide.

I'm also importing these `scss` files:

`import 'swiper/swiper.scss';`
`import 'swiper/components/effect-fade/effect-fade.scss';`

And doesn't seem to work... am I forgetting something?

**Comment by gleenk** [comment]
`import Swiper, {Pagination, Autoplay, Navigation, EffectFade} from 'swiper';
new Swiper('.hero-flip__slider', {
	modules: [Autoplay, EffectFade],
	slidesPerView: 1,
	effect: 'fade',
	fadeEffect: {
		crossFade: true
	},
	loop: true,
	autoplay: {
		delay: 2500,
		disableOnInteraction: false,
	},
});
`

Not working

**Comment by ZakaryaNoori** [comment]
The same problem arose for me. In my case, I solved it by loading "swiper-bundle.min.css" instead of "swiper.min.css".
