### ISSUE TITLE
SlideTo breaks autoplay

### ISSUE THREAD

**Issue by digitalchase** [nolimits4web/swiper#3412]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.1
* Platform/Target and Browser Versions: Windows, Chrome.

### What you did
I've initiated swiper slider with autoplay: {delay: 3000} and then tried to move to first slide from a different function using method mySwiper.slideTo(). 

### Expected Behavior
The slider is expected to go to the first slide and then change slides once in 3s.

### Actual Behavior
The slider goes to the first slide, but no autoplay happens. No console errors or warnings are spawned.

**Comment by mak33v** [comment]
I have this problem, can anyone tell me something about this?
