### ISSUE TITLE
Animation stops at prependSlide

### ISSUE THREAD

**Issue by oorooroot** [nolimits4web/swiper#3413]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.0
* Platform/Target and Browser Versions: cordova, chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/hizahazahub/pen/GRgeJyd

### What you did
Swipe animation stops when calling prependSlide() (click prepend slide button in codepen example during animation).

### Expected Behavior
Animation should continue, just as when appendSlide method used.

### Actual Behavior
Animation stops (looks like at activeSlide because index change?).

**Comment by nolimits4web** [comment]
It is expected behavior
