### ISSUE TITLE
If number of visible slides > number of slides, loop works only on one direction

### ISSUE THREAD

**Issue by plagasul** [nolimits4web/swiper#3423]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.2.1.
* Platform/Target and Browser Versions: all major updated
* Live Link or JSFiddle/Codepen or website with isssue: http://jaumeferrete.net/_jaumeferrete/dev/bienalfemsa/en (scroll down, right below the banner "upcoming programs and events" there is the swiper)

### What you did
I have a regular swiperjs structure with this initalization, including slidesPerView: 'auto' and loop: true, so loopedSlides: 8 

```
  var swiperEvents = new Swiper ('.swiper-container.events', {
    // Optional parameters
    loop: true,
    slidesPerView: 'auto',
    loopedSlides: 8,
    updateOnWindowResize: true
  })

```
### Expected Behavior
I would expect loop to work with any number of slides, 1, 2, 3, 4 , no matter how many of them are visible in the first place. So even if I have 2 slides, but I am showing 4 on initial view (2 slides + 2 duplicate) I would expect loop to work.

### Actual Behavior
When the ammount of **visible slides** are less than the total number of slides (so at least one duplicate is already showing when the swiper is initialized) loop does not work in both directions. slidePrev works forever but slideNext hits a wall after a number of slides, which I believe is the number of visible slides. In other words loop does not work with slideNext at all.

I tried looking for similar issues but can't seem to find the right keywords.

**Comment by Pixney-William** [comment]
This is probably the same issue as :  #2942

**Comment by stefanosalvucci** [comment]
in my case was looping only once only in larger screen, this happened because slidesPerView was > than the actual slides in the DOM
