### ISSUE TITLE
Bring back `breakpointsInverse`

### ISSUE THREAD

**Issue by udidol** [nolimits4web/swiper#3425]
### Summary
I want to upgrade the Swiper version we use from 4.4.6 to the latest (5.3.0 at this time). I can't do that because there is a breaking change in breakpoints functionality.

Why was it changed?
And if the default was changed, why remove the option to inverse it back?

### This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

* Swiper Version: 5.0.0 onwards 
* Platform/Target and Browser Versions: All platforms all browsers (excluding IE)

### Expected Behavior
The default behavior before removing the parameter `breakpointsInverse` is what I expect.
In 5.X.X you changed the default behavior of breakpoints - this is a breaking change.

I expect breakpoint to imitate the behavior of CSS media query `max-width`, as in all versions before 5.0.0. If not by default, then at least keep the `breakpointsInverse` parameter for changing it back!

### Actual Behavior
Breakpoints act as if the pixel widths are used with a `min-width` CSS media query property, instead of a `max-width` property.

**Comment by nolimits4web** [comment]
> this is a breaking change

And that is why version number starts from `5`
