### ISSUE TITLE
Event progress value not defined in @types/swiper

### ISSUE THREAD

**Issue by solidevolution** [nolimits4web/swiper#3430]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3 (@types/swiper version 5.2.1)
* Platform/Target and Browser Versions: macOS 10.15.2, Chrome 79.0.3945.130
* Live Link or JSFiddle/Codepen or website with issue: [https://codesandbox.io/s/swiper-9p9d6](https://codesandbox.io/s/swiper-9p9d6)

### What you did
Added @types/swiper

### Expected Behavior
```
swiper.on('progress', (progress: number) => {
  console.log('progress parameter exists: ' + progress)
})
```

### Actual Behavior
`Argument of type '(progress: number) => void' is not assignable to parameter of type '() => void'.`

**Comment by nolimits4web** [comment]
Sorry, but i am not the maintainer of `@types/swiper`. I think it is here https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by janbiasi** [comment]
@nolimits4web how about adding types to the main package? Because the types are pretty broken by the third party author and as of today as more and more projects are using TS it would be a great feature :)
