### ISSUE TITLE
Allow Breakpoint property to use variable

### ISSUE THREAD

**Issue by simmonsr** [nolimits4web/swiper#3435]
Can you allow for breakpoint property to use variable?

```
        var mobileBreakpoint = 480;
                breakpoints: {
                    mobileBreakpoint: {
                        slidesPerView: 2,
                        spaceBetween: 10
                    },
              }
```

Currently the above method does not work.

**Comment by nolimits4web** [comment]
https://stackoverflow.com/questions/19837916/creating-object-with-dynamic-keys

**Comment by simmonsr** [comment]
Cheers to you sir!

**Comment by simmonsr** [comment]
In case someone would like to do the same. Do this:

        var mobileBreakpoint = 480;
                breakpoints: {
                    [mobileBreakpoint]: {
                        slidesPerView: 2,
                        spaceBetween: 10
                    },
              }
