### ISSUE TITLE
Как мне сменить linear-gradient у .swiper-slide-shadow-left на свой?

### ISSUE THREAD

**Issue by maxjust** [nolimits4web/swiper#3440]
Как мне сменить linear-gradient у .swiper-slide-shadow-left на свой?

**Comment by nolimits4web** [comment]
Переопределить в CSS 😉

**Comment by maxjust** [comment]
Да, только там стиль вешается через JS напрямую в атрибут style у тега обертки. Собственно у него приоритет перед любыми css

**Comment by nolimits4web** [comment]
Он прописан в CSS https://github.com/nolimits4web/swiper/blob/master/package/css/swiper.css#L103-L105
