### ISSUE TITLE
Performance issue on touch swipe - iOS13.3

### ISSUE THREAD

**Issue by MMasey** [nolimits4web/swiper#3441]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.0
* Platform/Target and Browser Versions: iOS
[whatismybrowser.com/w/9EQ6CR9](https://whatismybrowser.com/w/9EQ6CR9)

### What you did
On the latest iOS and the latest Swiper version, when swiping, the touch event seems to be quite janky. Then you release the finger, the css transition kicks in and it's buttery smooth, but whilst actually swiping there is jank.

### Expected Behavior
When using a finger to swiper through the items, the interaction should feel jank free and smooth

### Actual Behavior
When swiping using a finger on iOS, the animation is a bit juttery / janky. This isn't to bad when it's just text, but when there are images with text etc, it is quite noticable.

It have recorded a screen capture to try and dislpay the issue. The gif compression probably doesn't help, the the issue is there.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/6573613/74021870-5ba8d480-4994-11ea-8658-f1c3e99fdd1a.gif)

**Comment by nolimits4web** [comment]
Sorry, closing as not related to Swiper. In latest iOS, it reports touch events coordinates as rounded values (before it had fractional values) so now movement is possible only with a step minimum to 1px which you take for performance issue 🤷‍♂️

**Comment by MMasey** [comment]
Ah ok, that sucks! Thanks for letting me know 🙂
