### ISSUE TITLE
Swiper2.7.6 is not working for Dynamic data in ie8

### ISSUE THREAD

**Issue by yuanqt** [nolimits4web/swiper#3447]
I found a bug on this page https://github.com/nolimits4web/swiper/blob/Swiper2/demos/03-dynamic-slides.html.
First click the Append slide button, add some slides, and then swipe multiple times quickly.
The page gets stuck on one slide and the page cannot slide to another slide

**Comment by nolimits4web** [comment]
Swiper 2 is not maintained anymore
