### ISSUE TITLE
Zoom handles wrong slide #2827 - reopen

### ISSUE THREAD

**Issue by tienbuide** [nolimits4web/swiper#3450]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.1
* Platform/Target and Browser Versions: Chrome - Version 80.0.3987.87 (Offizieller Build) (64-Bit)
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/swiper-demo-39-zoom

### What you did
Configured Swiper to simulate touch and use zoom with toggle.

1. Initialize Swiper
2. Double click on slide to zoom in (manually)
3. Call mySwiper.slideNext() or mySwiper.slideTo() to switch to the next slide
4. Call mySwiper.zoom.in()

### Expected Behavior
The current slide should be zoomed.

### Actual Behavior
The previous slide is zoomed

(mostly copy and paste from #2827)

**Comment by juanpasolano** [comment]
I've been having this same exact issue. Only reproducible using the method `zoom.in()` Which is what i need to use

**Comment by nolimits4web** [comment]
Fixed by #3451
