### ISSUE TITLE
freeMode momentum not working on IOS

### ISSUE THREAD

**Issue by nrgnrg** [nolimits4web/swiper#3454]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.0
* Platform/Target and Browser Versions: IOS
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/swiper-demo-16-scroll-container (The issue is present in this official demo)

### What you did
With freemode, when you swipe the slide  once your finger leaves the screen, the scroll action is not animated and immediately jumps to its final position.

### Expected Behavior
It should smoothly animate to the final position, not jump.

### Actual Behavior
See above

**Comment by nolimits4web** [comment]
Can’t replicate it on iOS 13.3.1 Does anyone see this issue?

**Comment by Sanchez3** [comment]
on iOS 13.3.1
safari
this issue still persists
do not follow Finger

**Comment by vukhacbiet** [comment]
Both Chrome and Safari in iOS 13.4.5 (beta)
Could anyone help me

**Comment by amf-paulinho** [comment]
I am having this problem, I am using version 8.3.2... Freemode is not working on react application. Scroll Movement is very clunky . Android and Desktop works perfectly

**Comment by goranhorvathr** [comment]
Problem still persists. Tested with real device iPhone 14 and on Samsung Galaxy S22. Works ok for desktop however for mobile devices its very much unusable clunky, laggy. We decided to disable it on mobile leave it on desktop and tablet until this is debugged and resolved.

**Comment by paullewisn** [comment]
I am finding the same issue. Silky smooth on my Google Pixel 7 and on my Mac Safari/Chrome/Firefox. On iOS Safari it is jerky and just not very nice. The issue is present on the Swiper demo page.
