### ISSUE TITLE
Zoom with picture tag not working as expected and javascript errors

### ISSUE THREAD

**Issue by rodden** [nolimits4web/swiper#3456]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.1
* Platform/Target and Browser Versions: On Windows 10. Using Chrome Version 79.0.3945.130, but also tested on Firefox 73.0. Saw same problems.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/rodden/pen/NWqNxVg

### What you did
1. Have the Chrome dev tools open so can see Console error messages
2. Double click to zoom on slide
3. Drag with mouse:
   problem #1: cannot move zoomed image vertically/freely
   problem #2: errors in console:

utils.js:30 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
at Object.getTranslate (utils.js:30)
at Swiper.onTouchMove (zoom.js:116)
at HTMLDivElement.handleLiveEvent (dom7.modular.js:324)

### Expected Behavior
Expected to drag and move zoomed image freely around on image. When not using HTML picture tag and just plain img tag, it does work.  Selector in code probably not checking for picture tag (see possible fix below).

### Actual Behavior
When zoomed, dragging locked to horizontal and error messages in javascript console

### Possible fix
replace in swiper.js
gesture.$imageEl = gesture.$slideEl.find('img, svg, canvas');
with
gesture.$imageEl = gesture.$slideEl.find('picture, img, svg, canvas');

**Comment by SqrTT** [comment]
current fix bring new issue:

![image](https://user-images.githubusercontent.com/1271300/88460161-e75ee080-cea2-11ea-91c0-3597ce2e7169.png)

`$imageEl` contain two elements which brings to incorrect scale:

```javascript
gesture.$imageEl.transition(300).transform(`translate3d(0,0,0) scale(${zoom.scale})`);
```

**Comment by mannux-git** [comment]
Hi @nolimits4web, above is true. i suggest adding a new parameter do define the target elements:
zoomable: 'img, svg, canvas, picture, .swiper-zoom-target',
then just use that when you need it:
gesture.$imageEl = gesture.$slideEl.find(params.zoomable);
cheers

**Comment by jellesiderius** [comment]
> current fix bring new issue:
> 
> ![image](https://user-images.githubusercontent.com/1271300/88460161-e75ee080-cea2-11ea-91c0-3597ce2e7169.png)
> 
> `$imageEl` contain two elements which brings to incorrect scale:
> 
> ```js
> gesture.$imageEl.transition(300).transform(`translate3d(0,0,0) scale(${zoom.scale})`);
> ```

You can add something like this

```
let picture = gesture.$slideEl.find('picture');
if (picture) {
    gesture.$imageEl = picture;
} else {
    gesture.$imageEl = gesture.$slideEl.find('img, svg, canvas');
}
```
