### ISSUE TITLE
Slider becomes unresponsive after first touch swipe on iOS Safari

### ISSUE THREAD

**Issue by andredalmolin** [nolimits4web/swiper#3458]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.1
* Platform/Target and Browser Versions: Firefox 73.0 on Windows 10 Pro 1909 and Safari on iOS 13.3.1
* Live Link or JSFiddle/Codepen or website with isssue: Video demonstrating the issue https://www.youtube.com/watch?v=s10cV-2bvH8. The issue happens on the Swiper demos too. https://swiperjs.com/demos/

### What you did
This issue is happening on almost all sliders I tested. Including on the demos in the Swiper website. I made an video (which the link is above) demonstrating the issue.

### Actual Behavior
The issue is that on iOS Safari, the first touch swipe interaction works great. The slides follow your finger perfectly. But if you release the touch and interate again, the slides doesnt follow your finger anymore. From now on, you move your finger, and the slides stay still, and only change to another when you do an fast gesture (to change the slide). I think on the video you guys can see this very clear. On Windows Chrome DevTools simulated touch devices, the issue dont happen. It works great every time.

### Expected Behavior
The expected behavior is that on iOS Safari, after you made the first touch gesture on the slider, the slider should keep following the finger, like what happens on Chrome with DevTools simulating touch devices.

**Comment by nolimits4web** [comment]
On same iOS 13.3.1 I can’t reproduce it, everything works correctly. Can anyone else see such issue in iOS?

**Comment by Sanchez3** [comment]
similar problem, need help
eg. https://3.swiper.com.cn/demo/microWeb/    
visit this on iPhone in safari
