### ISSUE TITLE
Calculate speed based on slide width

### ISSUE THREAD

**Issue by jedlikowski** [nolimits4web/swiper#3459]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.0.

It would be awesome if it was possible to pass a function to the `speed` option which would calculate speed for each slide separately.

Recently I had to implement a slider of tags with constant, slow transition (like flash news bar at the bottom of a TV screen). So I used `speed=4000`, `autoplay=true`, `freeMode=true` and `slidesPerViews="auto"`, `loop=true`. And the tags were automatically flowing really nicely. But there was an issue that they would speed up and slow down depending on the width of each tag. So I basically implemented autoplay myself by calling `slideNext()` after each slide transition and passing it the speed based on current slide width.

It would make my life much easier if I was able to pass a function to the `speed` parameter and use it to return different values based on current slide width. Not sure if I explain myself correctly.

**Comment by LeeConnelly12** [comment]
I assume the function could take the current slide as a parameter.

```
speed: function(slide) {
    return parseInt(slide.style.width) / 2;
}
```

In the example above we are sliding to the next slide based on half of the current slide's width.
Is this what you meant @jedlikowski ?

I've made a commit for this in my fork: 
https://github.com/LeeConnelly12/swiper/commit/2cb8ca6f4a02c346381a408761f20dc568a5be8d

Would like to know if this change looks ok @nolimits4web ?
