### ISSUE TITLE
Freemode on Mobile Breakpoint

### ISSUE THREAD

**Issue by JakeHenshall** [nolimits4web/swiper#3460]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

I just want to enable freemode on Mobile with Dynamic Height Slides and then just normal slides on Desktop.

What's the best way to get this to work.

```js
var mySwiper = new Swiper('.swiper-container', {
    direction: 'vertical',
    speed: 800,
    keyboard: {
        enabled: true,
    },
    hashNavigation: true,
    mousewheel: true,
    freemode: false,
    breakpoints: {
        767: {
            freemode: true,
        }
    }
});
```

Thanks.

**Comment by nolimits4web** [comment]
In version 5 this works as it is
