### ISSUE TITLE
Sticky Pagination Buttons Fixed to top

### ISSUE THREAD

**Issue by andrewxgithub** [nolimits4web/swiper#3461]
I've tried a bunch of options (placing pagination div outside of main container, modifying CSS to fixed, etc.), but I'm having no luck.

Is it possible to have the pagination buttons positioned independently from the main carousel? The slides are long vertically, so I want the user to be able to scroll, but still have the pagination dots fixed to the top (like a sticky navbar).

**Comment by nolimits4web** [comment]
> Is it possible to have the pagination buttons positioned independently from the main carousel?

Yes, just move it out of the swiper-container and style/position it as you want/need
