### ISSUE TITLE
Responsive mode crashing in ie11.

### ISSUE THREAD

**Issue by Heliken** [nolimits4web/swiper#3464]
Responsive mode not working in ie11.
https://swiperjs.com/demos/380-responsive-breakpoints.html
This is a: bug
Swiper Version: 5.3.1
Platform/Target and Browser Versions: Internet Explorer 11, Windows

Dont think this post need much of an explanation: slider wont initialize in ie11 when using responsive mode. Throws an error: Object doesn't support property or method 'startsWith'
Assuming it somehow connected with 5.3.0 New ratio-based breakpoints (#3389)

**Comment by TongjieYang** [comment]
@Heliken , when you can babel, you can add swiper and dom7 , it work in ie11
