### ISSUE TITLE
bug：swiper实例调用 update后，swiper 的loop属性不生效

### ISSUE THREAD

**Issue by xishanxu** [nolimits4web/swiper#3465]
bug的demo：
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
    <script src="https://unpkg.com/swiper/js/swiper.min.js"> </script>

    <style>
        .swiper-container {
            width: 600px;
            height: 300px;
            background: pink;
        }
    </style>
</head>

<body>
    <div id="box">
        <swiper :aaaa="datalist"></swiper>
    </div>
    <script>
        Vue.component("swiper", {
            template: `
            <div class="swiper-container dingding">
            <div class="swiper-wrapper">
                <div class="swiper-slide" v-for="data in aaaa" :key="data">
                    {{data}}
                </div>
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-pagination"></div>
        </div>
            `,
            props: ["aaaa"],
            mounted() {
                this.myswiper = new Swiper(".dingding", {
                    loop: true,
                    slidesPerView: 1,
                    spaceBetween: 30,
                    centeredSlides: true,
                    autoplay: {
                        delay: 2500,
                        disableOnInteraction: false,
                    },
                    navigation: {
                        nextEl: '.swiper-button-next',
                        prevEl: '.swiper-button-prev',
                    },
                    pagination: {
                        el: '.swiper-pagination',
                        clickable: true,
                    },
                })
            },
            updated() {
                this.myswiper.update(true);
                // new Swiper(".dingding", {
                //     loop: true,
                //     slidesPerView: 1,
                //     spaceBetween: 30,
                //     centeredSlides: true,
                //     autoplay: {
                //         delay: 2500,
                //         disableOnInteraction: false,
                //     },
                //     navigation: {
                //         nextEl: '.swiper-button-next',
                //         prevEl: '.swiper-button-prev',
                //     },
                //     pagination: {
                //         el: '.swiper-pagination',
                //         clickable: true,
                //     },
                // })
            },
        })
        new Vue({
            el: "#box",
            data: {
                datalist: [],
            },
            mounted() {
                setTimeout(() => {
                    this.datalist = ["11111", "222222", "333333"]

                }, 1000)
            },

        })
    </script>
</body>

</html>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
