### ISSUE TITLE
Next navigation is going backwards

### ISSUE THREAD

**Issue by lupus78** [nolimits4web/swiper#3467]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.6
* Platform/Target and Browser Versions: Mac/Windows Google Chrome version 79
* Live Link or JSFiddle/Codepen or website with isssue: It's the same as the Thumb with Loop mode demo, but you can see the live website here: https://www.exoticestates.com/breck-balmoral-lodge

### What you did
I've implemented the Thumbs with Loop demo: https://swiperjs.com/demos/#thumbs_gallery_with_loop_mode

### Expected Behavior
Next button should go forward, but it does not all the time. Sometimes moves back once or twice. 

### Actual Behavior
Not always happening, but once in a while it will go backwards when Next is clicked, and then maybe one more back, than starts to go forwards and works as expected.
Here is a video showing the behavior: https://drive.google.com/file/d/16KzBJheXuj_DhXeNuRSzESOfDvKQH5yh/view?usp=sharing
You can see, that only the Next button is clicked, but it goes like this: 1 -> 2 -> 1 -> 53 -> 1 -> 53 -> 1 -> 2 -> 3 -> ... and from here it works as expected.

The worst is that I can not reproduce this issue on my Linux / Chrome 80, but my colleges can on Windows and Mac too.

Here is the actual code to generate the slideshow:

	var propertySwiperThumbs = new Swiper ('#property-slideshow-thumbs.swiper-container:not(.swiper-initialized)', {
		spaceBetween: 10,
		slidesPerView: 'auto',
		freeMode: true,
		watchSlidesVisibility: true,
		watchSlidesProgress: true,
		centeredSlides: false,
		loop: true,
		loopedSlides: 5,
		on: {
			init: function () {
				this.$el.addClass('swiper-initialized');
			},
		},
	});
	var propertySwiper = new Swiper ('#property-slideshow.swiper-container:not(.swiper-initialized)', {
		// Optional parameters
		direction: 'horizontal',
		loop: true,
		loopedSlides: 5,
		zoom: true,
		pagination: {
			el: '.swiper-pagination',
			type: 'fraction'
		},
		navigation: {
			nextEl: '.swiper-button-next',
			prevEl: '.swiper-button-prev',
		},
		thumbs: {
			swiper: propertySwiperThumbs
		},
		on: {
			init: function () {
				this.$el.addClass('swiper-initialized');
			},
		},
	});

**Comment by nolimits4web** [comment]
Can it be reproduced with latest Swiper v5? When you say "sometimes" it goes back. It can happen if you do a short "swipe" on next link to previous direction which causes navigating back

**Comment by edmsgists** [comment]
We had a problem similar to this one using version 4.5. Upgrading to 6 did nothing to solve it. After reverting to 4.5 and using `allowTouchMove: false` we could not reproduce the problem anymore.
