### ISSUE TITLE
Transitions cut short based on number of open tabs in Chrome iOS

### ISSUE THREAD

**Issue by soulmartian** [nolimits4web/swiper#3470]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.1
* Platform/Target and Browser Versions: Chrome 80.0.3987.95 (anonymous & normal tabs), iPhone 8, iOS 13.3.1 
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/, https://youtu.be/okM2hMaFjMw, (Generally any instance with cssMode disabled)

### What you did
I opened Chrome browser with no additional tabs open and navigated to https://swiperjs.com/. Animations of swiper work as expected at this point, once I created additional tabs in Chrome and got back to Swiper website I touched the swiper and moved my finger to the side (left/right doesn't matter)

### Expected Behavior
Once I lifted my finger up i expected slides to transition smoothly to their final position.

### Actual Behavior
Smooth transition is skipped and slides jump to their final position. The portion of animation skipped somehow depends on how many tabs I opened, once I close those tabs problem persists.

I suspect this Chromium bug to be the culprit https://bugs.chromium.org/p/chromium/issues/detail?id=899130

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
