### ISSUE TITLE
slide with links and fade effect doesn't work

### ISSUE THREAD

**Issue by iamalessiopaoletti** [nolimits4web/swiper#3471]
Hi,

I have a slider with image + text + link for every slide,

all works but if I set the `effect: 'fade'`

the links are not clickable because the "next" slide it's over the actual slide with `opacity: 0` I think.

How can I solve this?
I tried to change the z-index but nothing change.

if you want a preview it's almost at the end of this page with the title "PROGETTI":

[http://alessiopaolettidesign.it/preco-snc/](url)

(sorry for my english)

**Comment by nolimits4web** [comment]
I can clearly click on links with fade effect, check here (2nd slide) https://stackblitz.com/edit/swiper-demo-22-fade-effect-ruemsh

Closing as can't replicate

**Comment by vahromeevilya-widestudio** [comment]
It worked for me **pointer-events:none;** for all slides except the active one

**Comment by QuirkWebDevelopment** [comment]
Adjusting z-index like this worked for me. 

` // fix swiper fade effect click bug  
.swiper 
  &-fade {
    .swiper-slide {
      &-prev, &-next {
        z-index: -1;
      }
    }
  }`

**Comment by AfkanOzdemir** [comment]
### Fix for fade effect slides still receiving pointer events in Swiper.js

Hi! I recently faced this issue and wanted to share a quick solution in case someone else runs into it.

When using effect: "fade", inactive slides are hidden visually but still receive pointer events like clicks or hovers. To fix this, I limited pointer events only to the active slide:


            const swiperOptions = // Your swiper options.
            const swiperName = // Your swiper name.
    
            swiperOptions.modules = [Navigation, Pagination, EffectFade, FreeMode];
            const swiperInstance = new Swiper(swiperElement, swiperOptions);
    
            // This is for fade effect to make the active slide pointer-events: auto
            if (swiperOptions.effect === 'fade') {
                const allSlides = swiperElement.querySelectorAll('.swiper-slide');
            
                const updatePointerEvents = () => {
                    const activeIndex = swiperInstance.activeIndex;
                    allSlides.forEach((slide, index) => {
                        slide.style.pointerEvents = index === activeIndex ? 'auto' : 'none';
                    });
                };
            
                updatePointerEvents();
                swiperInstance.on('slideChange', updatePointerEvents);
            }


This ensures only the current (visible) slide is interactive. Hope it helps!
