### ISSUE TITLE
White flashes on borders when slides changes (real iPad/iPhone)

### ISSUE THREAD

**Issue by ArtyshukPavlo** [nolimits4web/swiper#3472]
This is a:
* [x] bug

* Swiper Version: 4.1.6.
* Platform/Target and Browser Versions: iPad/iPhone real devices.
* Live Link or JSFiddle/Codepen or website with issue: http://dev.viewdemo.co/wp/aira/

loop on, 3 slides

### What I did
backface-visibility:hidden;
not resolve problem.

### Expected Behavior
Smoothly change slides.

### Actual Behavior
White flashes on borders when slides changes (only on real iPad/iPhone devices).
https://drive.google.com/file/d/1Om7p2jYM0Dnc9Fh0nfZBZQlbbbf5Vxtm/view

**Comment by nolimits4web** [comment]
Closing as not really related to Swiper. It is more about device rendering/memory issues.
