### ISSUE TITLE
Breakpoints with slidesPerView and slidesPerGroup pagination issue

### ISSUE THREAD

**Issue by hassanasad** [nolimits4web/swiper#3473]
This is a (multiple allowed):
* [ ] feature-discussion (RFC)
* [x] bug
* [ ] enhancement

* Swiper Version: 5.3.1
* Platform/Target and Browser Versions: MacOS - Chrome 80

### What you did
The swiper pagination bullet calculation is not working properly when breakpoints are used. It doesn't recalculate number of bullets when `slidesPerView`, `slidesPerGroup` values are defined in breakpoint.

### Expected Behavior
It should recalculate the number of bullets - It was working fine in older versions.

### Actual Behavior
Its calculating number of bullets based on top level slidesPerView/slidesPerGroup values.

Example:
```
readonly swiperConfig: SwiperConfigInterface = {
		pagination            : { el: '.swiper-pagination', clickable: true },
		direction              : 'horizontal',
		slidesPerView          : 4,
		slidesPerGroup         : 4,
		mousewheel             : { forceToAxis: true, invert: true, sensitivity: 1 },
		freeMode               : true,
		freeModeMinimumVelocity: 0,
		watchOverflow          : true,	// hide navigation in case no slides
		preloadImages          : true,
		lazy                   : false,
		roundLengths           : true,
		observer               : true,
		breakpoints            : {
			1024: {
				slidesPerView: 4,
				spaceBetween: 0
			},
			991: {
				slidesPerView: 3,
				slidesPerGroup: 3,
				spaceBetween: 0
			},
			767: {
				slidesPerView         : 1,
				slidesPerGroup        : 1,
				spaceBetween          : 0,
				freeMode              : false,
				freeModeSticky        : true,
				freeModeMomentum      : false,
				freeModeMomentumBounce: false,
				pagination            : { el: '.swiper-pagination', clickable: true },
				scrollbar             : false,
				mousewheel            : { sensitivity : 0.75 },
			}
		}
	};
```

**Comment by nolimits4web** [comment]
Can't reproduce it with latest version. Would be good to see live example or JSFiddle

**Comment by hassanasad** [comment]
@nolimits4web I have made an Angular based sample on StackBlitz - Hope that helps.

https://stackblitz.com/edit/angular-revejz

If you change the window width you will see breakpoints acting up.

**Comment by nolimits4web** [comment]
And i can't see the issue in your demo. Or what is the issue/wrong with it?

**Comment by hassanasad** [comment]
The breakpoint 767 should work less < 767 resolution right ? For me when i make the width of window less than 767, i still see 4 slides and 4 in each group. I hope i am able to explain the issue.

Basically the breakpoints are not working as intended in terms of `slidesPerView`, `slidesPerGroup`

**Comment by nolimits4web** [comment]
> The breakpoint 767 should work less < 767 resolution right ?

No, it will work when `width >= 767`, check docs https://swiperjs.com/api/#parameters

**Comment by hassanasad** [comment]
Was this changed in recent versions? It used to work the other way previously ?

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#swiper-500---released-on-september-17-2019

**Comment by hassanasad** [comment]
oh dang - I see. Thanks man for the clarification.

**Comment by warudin** [comment]
I am unable to see the stackblitz example but I'm experiencing the same problem with version 6.1.1.

When the number of slidesPerView & slidesPerGroup changes according to a breakpoint, the number of navigation bullets doesn't change to reflect this.
