### ISSUE TITLE
Broken iOS "swipe animation"

### ISSUE THREAD

**Issue by jrtderonde** [nolimits4web/swiper#3474]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.1
* Platform/Target and Browser Versions: iOS 13.3.1 (Safari / Google Chrome)
* Live Link or JSFiddle/Codepen or website with isssue: https://jimderonde.nl/thrcrds/

### What you did
I tried to change around the `parallax` and `snapOnRelease` parameters but that didn't really change a lot. 

### Expected Behavior
I was expecting the same slide/swipe behavior as it was showing on my desktop and laptop. 

### Actual Behavior
The swipe animation looks as if it's instant (or really, really fast).

**Comment by nolimits4web** [comment]
Can't see anything like that in iOS. Is it still relevant? If yes, please provide more information

**Comment by jrtderonde** [comment]
> Can't see anything like that in iOS. Is it still relevant? If yes, please provide more information

I found out that this only complies when "Reduced Motion" is activated on iOS.

**Comment by nolimits4web** [comment]
Then closing as not related to Swiper

**Comment by stefanbayjensen** [comment]
I'm still experiencing this on iOS chrome

**Comment by artshevtsov** [comment]
@stefanbayjensen I am facing the same issue on chrome ios. Slide animation turns off after switching between site tabs. Chrome termination and restarting fixes this issue for a while. 
Demo: https://youtu.be/gev1PvGWsKg
