### ISSUE TITLE
Show or hide switch arrows on breakpoints

### ISSUE THREAD

**Issue by ivansteff** [nolimits4web/swiper#3475]
* [x] feature-discussion (RFC)

* Swiper Version: Latest.
* Platform/Target and Browser Versions: Google chrome.

### What you did
I would like to add the ability to hide the switching arrows on certain breakpoints

### Expected Behavior
I would like to indicate which breakpoint show switch arrows.

### Actual Behavior
Like that:
```
swiperOption: {
                slidesPerView: 9,
                spaceBetween: 20,
                slidesPerGroup: 1,
                navigation: {
                    nextEl: `.swiper-button-next`,
                    prevEl: `.swiper-button-prev`,
                },
                breakpoints: {
                    1600: {
                        showSwitchArrows: false;
                        slidesPerView: 8,
                    },
                    1200: {
                        showSwitchArrows: true;
                        slidesPerView: 7,
                    },
                }
            },

```

**Comment by VictorGabriel1998** [comment]
I recommend doing this with CSS, using responsiveness methods

**Comment by nolimits4web** [comment]
There are CSS media queries for this purpose

**Comment by taofeek-ob** [comment]
How do we achieve this? Cannot pinpoint the button in order to use hidden class, especially on tailwindcss.

Thanks.
