### ISSUE TITLE
Mousewheel on IE 11

### ISSUE THREAD

**Issue by Elyos59** [nolimits4web/swiper#3479]
Hi!

When I activate MouseWheel for my swiper and scroll down/up I have this error in console :

> SCRIPT438: Object does not manage property or method « sign »
> swiper.min.js (15,75128)

**Comment by Elyos59** [comment]
Okay...

Just add

`if (!Math.sign) Math.sign = function(x) { return ((x > 0) - (x < 0)) || +x; };`

at top of code

**Comment by nolimits4web** [comment]
Sorry, but IE 11 is not supported by v5

**Comment by themevan** [comment]
Does swiper 6.x support IE 11?
