### ISSUE TITLE
Swiper support slidePerView: 1.3 or 3.2 for example? (Decimal)

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [nolimits4web/swiper#3482]
No docs about this issue - its safe to use this idea?

`
slidePerView: 1.3
`
![image](https://user-images.githubusercontent.com/16711871/75630545-51c16c80-5bf4-11ea-856b-76651c8ea977.png)

Codepen example:
https://codepen.io/ezra_siton/pen/QWwJBRr?editors=1101

"carousel" - Looks like this demo her (Using `auto`):
https://swiperjs.com/demos/120-slides-per-view-auto.html

**Comment by nolimits4web** [comment]
It would be better to use slidesPerView: 'auto' and set slide width in CSS to something like `80%`
