### ISSUE TITLE
Does not update the width of the slide after Swiper has been destroyed and re-initialized

### ISSUE THREAD

**Issue by SergeyPismennyi** [nolimits4web/swiper#3484]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.6..
* Platform/Target and Browser Versions: windows, mac, chrome.
* Live Link or JSFiddle/Codepen or website with isssue: [codepen](https://codepen.io/SergeyPismennyi/pen/MWwoXVg?editors=0000) [codesandbox](https://codesandbox.io/s/pedantic-waterfall-7xt8b)

### What you did
Does not update the width of the slide after Swiper has been destroyed and re-initialized.
Steps to reproduce: 
1. Click "destroy Swiper" button
2. Click "init Swiper" button
3. Resize the window

### Expected Behavior
The width of the slides is updated when resizing.

### Actual Behavior
The width of the slides is not updated.

**Comment by nolimits4web** [comment]
You need to recreate instance with calling `new Swiper`, `swiper.init()` won't have effect after destroying

**Comment by SergeyPismennyi** [comment]
Unfortunately, I am not able to do this. I'm using 'react-id-swiper' that wraps Swiper and it does not provide the ability to create a new Swiper instance.
Just the ability to maintain an instance after its destruction implies the possibility of its reinitialization.

**Comment by surmon-china** [comment]
@SergeyPismennyi Maybe you can:

```jsx
{
  shoudBeRenderSwiper && (
    <Swiper ...>
  )
}
```
