### ISSUE TITLE
Allow elements inside slide to flow outside of carousel container

### ISSUE THREAD

**Issue by lukeisif** [nolimits4web/swiper#3485]
I'm trying to enable an element thats placed inside each slide to flow outside of the carousel container (`.swiper-container`). Adding `overflow: visible` works but then we can see the following slides to the right of the carousel track.

Have tried using `overflow-y: visible` but this then just creates enables the container to be scrollable.

With the element closed:
![Screenshot 2020-03-02 at 13 14 00](https://user-images.githubusercontent.com/53814956/75679641-f04add80-5c87-11ea-8f85-e406573176e4.png)

Element open but trapped by `overflow: hidden`:
![Screenshot 2020-03-02 at 13 14 04](https://user-images.githubusercontent.com/53814956/75679703-0bb5e880-5c88-11ea-8715-0a995a6166c6.png)

Element visible with `overflow: visible` enabled but end up with hidden slides showing:
![Screenshot 2020-03-02 at 13 14 18](https://user-images.githubusercontent.com/53814956/75679710-0f496f80-5c88-11ea-8df6-52aaacb6e9ed.png)

The element that needs to flow out is positioned absolutely within the slide so I'm not even sure why when using `overflow-y: visible` the container ends up scrollable, it doesn't make much sense.

**Comment by nolimits4web** [comment]
You should probably set overflow:visible, and add another parent container with required spacing and overflow: hidden.

Closing as not related to Swiper itself
