### ISSUE TITLE
Multirow - class isn't removed after resize

### ISSUE THREAD

**Issue by Triloworld** [nolimits4web/swiper#3486]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Version (I use VUE & Nuxt):
Installed: "vue-awesome-swiper": "^3.1.3",
https://www.npmjs.com/package/vue-awesome-swiper
Swiper 4

### What you did
Set this params:

        swiperOption:{
          autoplay: false,
          slidesPerView: 'auto',
          slidesPerColumn: 2,
          slidesPerColumnFill: 'row',
          allowSlidePrev: false,
          allowSlideNext: false,
          breakpoints: {
            768: {
              slidesPerColumn: 1,
              slidesPerColumnFill: 'column',
              allowSlidePrev: true,
              allowSlideNext: true,
            },
          },
          pagination: false //{el: '.swiper-pagination', clickable: true}
        }

### Expected Behavior
Load from more than 900px and resize to small 767px (in this example)
Class "swiper-container-multirow" removed from DOM

### Actual Behavior
Class stay and need to be removed manually.
It isn't problem after resizing up as I can add property from css manually (flex: wrap)

Why no class modifier to this option or renaming in Namespace section?

**Comment by laulim** [comment]
The same issue with "swiper": "=4.5.0"

**Comment by vltansky** [comment]
`vue-awesome-swiper` isn't related to swiper. Use swiper official vue component.

**Comment by Triloworld** [comment]
For future, yeah - sorry! That's right, it's not bug in this repo. Only done push in code, no trace that this class is removed in any time.
Reference: https://github.com/nolimits4web/swiper/blob/e39d8e924048fd043377054e0a2d6d9496bf11aa/src/components/core/classes/addClasses.js
