### ISSUE TITLE
Add class to slides inside visible part of swiper container

### ISSUE THREAD

**Issue by Aleksei-M** [nolimits4web/swiper#3489]
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

This is a feature request to add some class to slides that are visible (say positioned inside visible part of .swiper-container or any other container set by API). For example, if there is four slides visible inside some wrapper, then add to all the four something like .swiper-slide-visible. That will be a good alternative to .swiper-slide-active in case if there are more than one slide shown.

**Comment by nolimits4web** [comment]
Check `watchSlidesVisibility` parameter https://swiperjs.com/api/
