### ISSUE TITLE
slideToClickedSlide not working for coverflow in MS Edge

### ISSUE THREAD

**Issue by denismcmahon** [nolimits4web/swiper#3498]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 5.3.6
* Platform/Target and Browser Versions: Windows, Microsoft Edge
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/dmcmahon82/pen/wvaPWjR

### What you did
Set the slideToClickedSlide to true to allow slides to focus when clicked, this works fine in Chrome, but not in IE Edge as per code pen sample, I also tried to just manually set up click events with jQuery, but the same problem

### Expected Behavior
Slides should focus when .swiper-slide element clicked

### Actual Behavior
The functionality is not working in IE Edge, as it is in Chrome where it works

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by DjulLau** [comment]
Was about to open a similar issue on **Firefox 74.0.1 (64 bits)** but I believe it's the same problem.
It looks like the swipper-wrapper is "eating" the event.


Possible workaround : 
``` CSS
.swipper-wrapper {
 pointer-events: none;
}
.swipper-slide {
 pointer-events: auto;
}
```

**Comment by stupidguy176** [comment]
Thank you so much!

> Was about to open a similar issue on **Firefox 74.0.1 (64 bits)** but I believe it's the same problem. It looks like the swipper-wrapper is "eating" the event.
> 
> Possible workaround :
> 
> ```css
> .swipper-wrapper {
>  pointer-events: none;
> }
> .swipper-slide {
>  pointer-events: auto;
> }
> ```

Thank you so much!
