### ISSUE TITLE
'No conflict' configuration to avoid conflict between two swiper versions.

### ISSUE THREAD

**Issue by lwxbr** [nolimits4web/swiper#3503]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Windows/Chrome 80.0.3987.132 (64-bit)

### What you did
Tried to import two different Swiper versions.

### Expected Behavior
Use a function like jQuery does to avoid conflict between versions and multiple imports.
https://api.jquery.com/jquery.noconflict/

### Actual Behavior
Conflict between two swiper versions, the one that I import in my site and the other one that a plugin imports.

**Comment by nolimits4web** [comment]
This won't landed and you shouldn't include 2 swipers into your codebase
