### ISSUE TITLE
Motion blur effect

### ISSUE THREAD

**Issue by DevilHtml** [nolimits4web/swiper#3504]
* [  ] bug
* [  ] enhancement
* [x] feature-discussion (RFC)
 
 
* Swiper Version: 4.5.1
* Platform/Target and Browser Versions: MacOs, Safari, Chrome...
* [codepen](https://codepen.io/Pieroelma/pen/KKpRxNx)
 
### What you did
I found this script which adds the motion blur effect and tried to update it to the latest swiper version. Does not work.
[(original script)](https://codepen.io/Webevasion/pen/dNmNov)
 
### Expected Behavior
Add motion blur effect.
 
### Actual Behavior
The script does not work, I believe it is due to the update of the event scripts of the new version of Swiper.
 
Thanks

**Comment by nolimits4web** [comment]
Closing as not related to Swiper core
