### ISSUE TITLE
AutoHeight problem: height is too big initially

### ISSUE THREAD

**Issue by Celestialray** [nolimits4web/swiper#3505]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.6
* Platform/Target and Browser Versions: Ubuntu 18.04, Chrome Version 80.0.3987.132 (Official Build) (64-bit)

### What you did
Initialized swiper with autoHeight: true parameter in order to have flexible height according to each slide present.

### Expected Behavior
The swiper-wrapper container's height should contain the sliders perfectly.

### Actual Behavior
The swiper-wrapper container's height is significantly higher than it should be. Although the height gets adjusted when you resize the window, the initial height is bigger than expected and so it's a bad user experience.

**Comment by nolimits4web** [comment]
That is something to CSS related in your layout, swiper doesn't do anything except `activeSlide.offsetHeight`.
