### ISSUE TITLE
Slider loops through all slides at initialization, goes back to first slide

### ISSUE THREAD

**Issue by udidol** [nolimits4web/swiper#3506]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.6
* Platform/Target and Browser Versions: Reproduced in Chrome, windows and Mac. Didn't test other platforms
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/udidol/pen/GRJEmqO

### What you did
Initialized a slider with 10 images, with the following settings:
```
{
    slidesPerView: 3,
    slidesPerGroup: 3,
    loop: true,
    autoplay: {
        delay: 5000,
        disableOnInteraction: true,
    },
    loopedSlides: 10,
    effect: 'slide',
    swiperOptions.pagination = {
        el: '.swiper-pagination',
	type: 'bullets',
	clickable: true,
    },
}
```

Note the `loopedSlides: 10` parameter. When I remove it, the slider seems to work fine.

### Expected Behavior
The slider should initialize and start moving (autoplay is true), slides 3 at a time (slides per group = 3 in my settings).

### Actual Behavior
The slider slides through all of the slides and goes back to the first slide. It does that continuously according to the autoplay delay time (5000). If I do not use the navigation arrows/pagination bullets, the autoplay gets stuck on the first slide (see codepen link above).

**Comment by udidol** [comment]
After further testing, this happens also in `effect: fade` mode, and in `loop: false` mode:

Codepen: https://codepen.io/udidol/pen/NWqEGVQ

I put a long `transition-duration` on the `.swiper-slide` class so it can be seen very very clearly.

**Comment by TomDeSmet** [comment]
I have a similar issue. When combining `loop: true` with `slidesPerGroup` the autoplay goes wrong. I'm not using the `loopedSlides` property.

```
loop: true,
loopFillGroupWithBlank: true,
spaceBetween: 36,
speed: 1000,
roundLengths: true,
watchOverflow: true,
slidesPerView: 1,
slidesPerGroup: 1,
autoplay: {
    delay: 5000,
    disableOnInteraction: false
},
navigation: {
    nextEl: btnNext,
    prevEl: btnPrev
},
breakpoints: {
    // when window width is >= 768px
    768: {
        slidesPerView: 3,
        slidesPerGroup: 3,
    },
    1024: {
        slidesPerView: 4,
        slidesPerGroup: 3,
    },
    1280: {
        slidesPerView: 5,
        slidesPerGroup: 3,
    }
}
```
