### ISSUE TITLE
Swiper not working properly in magento 2.3.4

### ISSUE THREAD

**Issue by Mathanagopal97** [nolimits4web/swiper#3509]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 5.3.6.
* Platform/Target and Browser Versions: Ubuntu 19.10(Eoan Ermine), Browser - Google Chrome Version 80.0.3987.149 (Official Build) (64-bit).

### What you did
1. I instantiated swiper container in the phtml file.
Here is the code to it - [accordionContent.phtml](https://gist.github.com/Mathanagopal97/0553350d16497607da21b8ac09bc3ff6)
2. Then, I rendered this template on the fly using an ajax call to the controller.
Here is the code to it - [Index.php](https://gist.github.com/Mathanagopal97/b75f22ff9cb2df899539f6bfff8ef76d)

### Expected Behavior
All the swipers working perfectly fine.

### Actual Behavior
Only the first set of swipers are working. The second set of swipers that are in the another accordion is not working perfectly. When I press F12 from the keyboard and open the developer tools, it is working as expected.

[Here](https://imgur.com/a/efah2N7) I have attached the images that would help you.

If you want any other things please mention in the comment.

**Comment by Mathanagopal97** [comment]
I have found the cause of the issue. It seems that if the ```div``` or ```section``` that has the class which is going to be converted into **swiper** (```swiper-container``` for an instance) is set to **```display:none```** before the script is called upon, will cause this bug. So @nolimits4web , please look into this issue and rectify it before closing it.

**Comment by nolimits4web** [comment]
> It seems that if the div or section that has the class which is going to be converted into swiper (swiper-container for an instance) is set to display:none before the script is called upon, will cause this bug

This is how Swiper works, it must be visible on init

**Comment by erankitsrivastava** [comment]
@nolimits4web @Mathanagopal97 

any solution or workaround, for this one??
