### ISSUE TITLE
Transitions are instant on Iphone using Chrome v80

### ISSUE THREAD

**Issue by fulopdaniel** [nolimits4web/swiper#3517]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v5.3.6.
* Platform/Target and Browser Versions: Iphone XS, chrome v80.
* Live Link or JSFiddle/Codepen or website with issue: https://swiperjs.com/demos/ .

### What you did
Try to swipe through the demo slides with your finger.

### Expected Behavior
The transitions are smooth.

### Actual Behavior
After releasing  your finger off the screen, the transition to the next (or back to the current) element is instant.

Here is a gif of the behavior for better understanding.
https://gfycat.com/shadowygreengraywolf

**Comment by Mulegoat** [comment]
Hi fulopdaniel,

See my comment on issue [#3532](https://github.com/nolimits4web/swiper/issues/3532) 

Should hopefully fix your issues too

**Comment by nolimits4web** [comment]
Closing and seems not related to Swiper itself
