### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by simonmaass** [nolimits4web/swiper#3522]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.6
* Platform/Target and Browser Versions: Windows, Chrome

### What you did
Included as in docs

### Expected Behavior
No console errors

### Actual Behavior
Everytime you scroll there is error in console:
Unable to preventDefault inside passive event listener invocation.

**Comment by simonmaass** [comment]
this is not stale btw...


![image](https://user-images.githubusercontent.com/32599710/127170927-972bcc30-b4fb-4b03-89c1-48a50ab32fe1.png)

**Comment by szmazhr** [comment]
is there any resolution on that
