### ISSUE TITLE
Google Chrome in iOS -> Swiper speed param is not working at all

### ISSUE THREAD

**Issue by HectorLS** [nolimits4web/swiper#3532]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: `"swiper": "^4.5.0",`
* Platform/Target and Browser Versions: `iOS Ipad 5th gen`

Hello, **Swiper speed param is not working at all** on **iOS Ipad using Google Chrome** as the browser, but it's working on Safari, super weird.
you can test this in the [Library demo page https://swiperjs.com/demos/](https://swiperjs.com/demos/)

**Comment by Mulegoat** [comment]
Hi Hector, I was struggling to figure this out too. I added webkit-transition prefixes to other parts of my site that use css transforms and then restarted chrome and this seemed to fix the issue. Very weird. E.g:

  -webkit-transition: transform 600ms ease;  
  -webkit-transition: -webkit-transform 600ms ease;

Note, I did not have to add this to anything swiper related so look for other parts of your site using transforms. The site I'm currently working on uses swiper extensively and after restarting iOS chrome works much better with speed and parralax parameters now working:

https://staging.reefandrainforest.co.uk/

**Comment by HectorLS** [comment]
Hi @Mulegoat ! gonna try it with a simple html five with just a full screen Swiper to test it

**Comment by HectorLS** [comment]
Hi again @Mulegoat 
 i have tested it, with the simplest structure below
```emmet
html > body > main > section.swiper-container > ul.swiper-wrapper > li.swiper-slide
```
There is no transitions or transforms,  just the swiper and still happening 😭

🙏  Let see if @nolimits4web or some other hero has some workaround this

**Comment by Mulegoat** [comment]
Sorry to hear that Hector :(

I know it's a stupid question but have you tried closing the chrome app and restarting it (Not just exiting the app but actually closing it via the tabs) - this for some weird reason was what worked for me after I'd applied the additional transform styles

**Comment by HectorLS** [comment]
Hi @Mulegoat , still nothing.

**Comment by nolimits4web** [comment]
Closing and seems not related to Swiper itself
