### ISSUE TITLE
Loop does'nt work with > 2 slidesPerView

### ISSUE THREAD

**Issue by almirsantos99** [nolimits4web/swiper#3535]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 5.3.6

### What you did
I turn the loop true with slidesPerView: 3 (also test with loopAdditionalSlides: 50 and loopedSlides: 10, 20, 30 etc...)
var testimonial = new Swiper('.testimonial-slider', {
	navigation: {
		nextEl: '.testimonial-button-next',
		prevEl: '.testimonial-button-prev',
	},
	slidesPerView: 3,
	loop: true,
});

### Expected Behavior
The slide works normally swiping right in loop.

### Actual Behavior
The loop stop working forward, only backwards (yeah), he gave me 1 more cloned item and nothing more, if i switch slidesPerView to 4 he didn't even swipe right, only left. With 2 or less works perfectly but 3 or more doesn't work at all.

**Comment by nolimits4web** [comment]
Apparently you need to have more than `slidesPerView` actual slides

**Comment by almirsantos99** [comment]
> Apparently you need to have more than `slidesPerView` actual slides

Wut?! Sorry but if i have only one item and want to show it 3 times in loop, i must be able to, i'm not have to be forced to have more than slidesPerView, that's what LOOP is supposed to do.

**Comment by kenzrad** [comment]
Hey @almirsantos99  - I know this has closed, but have you looked into loopFillGroupWithBlank at all? Maybe this would resolve your issue with looping?

**Comment by almirsantos99** [comment]
Hey @kenzrad, thanks for the help. I tried the loopFillGroupWithBlank right now and doesn't work, the result it's the same, forward not loop and backwards infinite loop

**Comment by ChristosTsm** [comment]
Same problem here. Any solution came up?

**Comment by zavvla** [comment]
up?

**Comment by nargesghahremani** [comment]
+

**Comment by isour** [comment]
same problem

**Comment by hsnmrd** [comment]
same problem, any solution ??

**Comment by tushariar** [comment]
Did you find any solution?

**Comment by Gayathri-cognizant** [comment]
I just updated Swiper 9.1.0. I want show slidesperview 3 and i have 4 slides (which is less than **slidesperview*2**) with Loop enabled. But my pagination and next button is not working as before.

**Comment by GayathriKL** [comment]
I just updated Swiper 9.1.0. I want show slidesperview 3 and i have 4 slides (which is less than slidesperview*2) with Loop enabled. But my pagination and next button is not working as before. Once 4th slide appeared in view, next button is not working. 
Any solution?

**Comment by markilay** [comment]
same problem

**Comment by axonde** [comment]
same problem guys

**Comment by axonde** [comment]
I found this issue, mb can help u: 
[stack](https://stackoverflow.com/questions/75450242/swiper-js-loop-when-slidesperview-is-bigger-than-half-of-the-amount-of-slides)

**Comment by invisibleved** [comment]
Did any solution come up?

**Comment by JH1ller** [comment]
Also have this issue. On swiper 8 the loop mode worked perfectly with 2 items, on any version above it's broken..
