### ISSUE TITLE
Enabling history causes Uncaught TypeError.

### ISSUE THREAD

**Issue by iamdave210** [nolimits4web/swiper#3536]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 5.3.7
* Platform/Target and Browser Versions: All platforms and browsers.
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/0e5o68h7/2/

### What you did
I tried to enable history, both with and without replaceState and with and without a key value set. I also tried it with and without hashNavigation enabled. The behavior was the same.

### Expected Behavior
Swiper updates URL by adding hash to URL

### Actual Behavior
Swiper breaks with the error `Uncaught TypeError: Cannot read property 'toString' of null`

**Comment by iamdave210** [comment]
It's possible this is a "bug" in the documentation. Or maybe in my reading comprehension. If it's the latter, my apologies in advance. :)

**Comment by alexvais** [comment]
@iamdave210 could you fix it?

**Comment by iamdave210** [comment]
@alexvais no; I rolled my own. Here it is with most of the irrelevant bits stripped out:

        const getInitSlide = function(){
            let lmnt = document.querySelector('[data-hash="'+params.get('img')+'"]'),
                i = 0;
            
            while((lmnt = lmnt.previousSibling) != null) if(lmnt.nodeType == 1) ++i;
            
            return i;
        }
        
        var params = new URLSearchParams(window.location.search),
            vis = document.getElementById('vis'),
            swiperOpts = {
                slidesPerView: 1,
                loop: true,
                initialSlide: ((params.has('img')) ? getInitSlide() : 0),
                on:{
                    slideChangeTransitionEnd: function(){
                        params.set('img',this.slides[this.activeIndex].dataset.hash);
                        window.history.replaceState({}, '', `${window.location.pathname}?${params}`);
                    }
                }
            },
            swiper = new Swiper(vis, swiperOpts);

IIRC, I had trouble using swiper's slide index in conjunction with looping, something to do with the cloned elements, and that's why I had to add a `data-hash` attribute to each `.swiper-slide` element with a unique ID for each image, find that element, and count to find its position in the list. In a simpler situation you might be able to use swiper's indices and skip the while loop.
