### ISSUE TITLE
Cannot swipe on firefox when using html5 video

### ISSUE THREAD

**Issue by vitogoh** [nolimits4web/swiper#3537]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.7.
* Platform/Target and Browser Versions: Firefox 72.0.2 Mac Mojave.
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/swiper-demo-1-default-k1tq5u.

### What you did
Swipe to the next slide

### Expected Behavior
I can swipe to the next slide

### Actual Behavior
Swiping does't work

Swiping works in Chrome, Safari and IE

**Comment by vitogoh** [comment]
my hunch is that the video element is somehow hijacking the touch event by either sitting in a different z-index or due to the swiper-wrapper having a translate3d. however, manipulating the z-index of the video and adding transform-style: preserve-3d to the swiper-wrapper, but it doesn't seem to change anything. 

i manage to get a workaround by disabling the video's pointer event and using a click event on the swiper-slide to trigger the video, but the solution is not ideal since the video has to be paused before the touch events can be registered. if anyone has a better idea. i'm all for it. 

https://stackblitz.com/edit/swiper-firefox-video-fix?file=index.html

**Comment by dippas** [comment]
@vitogoh  it works perfectly in latest firefox.

**Comment by catapop84** [comment]
I just upgraded to v10.0.4 and this problem persists in Firefox. Is there a solution?

**Comment by Javier-Machin** [comment]
Sadly still a thing

**Comment by Javier-Machin** [comment]
@catapop84 Got it working adding `pointer-events: none;` to the video element. In my case the users are not expected to interact with the video, so it works for my use case.
