### ISSUE TITLE
Not compatible with ES5 as dependency

### ISSUE THREAD

**Issue by Fermain** [nolimits4web/swiper#3538]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.7
* Platform/Target and Browser Versions: Webpack, IE11, legacy browsers

### What you did
Attempt to consume Swiper as an NPM dependency.

### Expected Behavior
Normal use of Swiper library.

### Actual Behavior
Syntax error in bundle, causing entire vendor bundle to fail.

I am aware that this has been raised repeatedly. I have read official responses, but this really sets Swiper apart from the rest of the ecosystem and forces ugly workarounds that negate the point of working with such a well designed library.

My webpack environment uses TypeScript, yet I am targeting IE11. Despite many vendor dependencies, Swiper is the only one that requires special gloves to transpile properly.

**Comment by nolimits4web** [comment]
https://swiperjs.com/get-started/

> In case you use it as an ES module make sure:

> you have enabled Babel or Buble to transpile it to ES5 syntax,
> you have enabled node modules resolving and babel transpiling for Swiper as it uses Dom7 and ssr-window packages as dependencies.
