### ISSUE TITLE
breakpoint settings don't update on swiper.update() call

### ISSUE THREAD

**Issue by udidol** [nolimits4web/swiper#3539]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.6
* Platform/Target and Browser Versions: Tested on Windows 10 Latest Chrome version to date
* Live Link or JSFiddle/Codepen or website with issue: https://codepen.io/udidol/pen/NWqEGVQ. This requires changing the `swiper.params.breakpoints` param in the console, then calling `mySwiper.update()` (also in the console).

### What you did
I instantiated a Swiper with 3 slides and gave it the following config:
```
{
    slidesPerView: 1,
    slidesPerGroup: 1,
    grabCursor: true,
    initialSlide: 0,
    loop: false,
    speed: 500,
    observeParents: true,
    observer: true,
    //effect: 'fade',
    breakpoints: {
      0: {
        slidesPerView: 2,
      },
    },  
    /*fadeEffect: {
        crossFade: true
    }, */
    pagination: {
        el: '.swiper-pagination',
	      type: 'bullets',
	      clickable: true,
    },
    navigation: {
				prevEl: '.swiper-button-prev',
				nextEl: '.swiper-button-next',
    },
}
```
Then, in the console, I changed `swiper.params.breakpoints` as follows, and called `swiper.update()`:
```
swiper.params.breakpoints[ 0 ] = {
    slidesPerView: 1,
};

swiper.update();
```

### Expected Behavior
If I change the `swiper.params.breakpoints` property, then call `swiper.update()`, the Swiper instance should update accordingly. 

### Actual Behavior
When I change the `swiper.params.breakpoints` property, then call `swiper.update()`, nothing happens.

**Comment by lstoyanoff** [comment]
I've stumbled upon the same thing on v7.3.3 (probably it's the same for older versions as well)

There's a check in `setBreakpoint` method that prevents updates if the breakpoint hasn't changed -- https://github.com/nolimits4web/swiper/blob/v7.3.3/src/core/breakpoints/setBreakpoint.js#L16

For anyone who's trying to update breakpoint params after init you can "hack it":

```js
swiper.params.breakpoints[0].slidesPerView = 1;
swiper.currentBreakpoint = false;
swiper.update();
```

**Comment by panksi** [comment]
@lstoyanoff Ljubi te brat!
