### ISSUE TITLE
Broken image displayed with lazyload

### ISSUE THREAD

**Issue by haswent** [nolimits4web/swiper#3545]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.7
* Platform/Target and Browser Versions: Chrome
* Live Link or JSFiddle/Codepen or website with issue: https://www.stocktonkia.co.uk/

### What you did
Hero page with images set to lazyload (See link above for live example) 

### Expected Behavior
Would expect just the preloader icon to show without the broken image icon

### Actual Behavior
The preloader is showing, but there is also a broken image icon shown
![image](https://user-images.githubusercontent.com/50839406/79873865-950fae80-83df-11ea-9833-1e54a9908bca.png)

**Comment by haswent** [comment]
I turned off lazyloading to get around this

**Comment by retroriff** [comment]
I have the same problem. Did you find a solution?
