### ISSUE TITLE
Is there a way to connect multiple sliders to the Thumbs slider?

### ISSUE THREAD

**Issue by kevinmu17** [nolimits4web/swiper#3551]
I'm trying to drive 2 sliders with 1 thumbs slider but it isn't working. I'm seeking the asForNav function like slick slider js, witch can chain multiple sliders to each other.

This is a (multiple allowed):
* [] bug
* [x] feature-discussion (RFC)
* [x] enhancement

* Swiper Version: 5.3.7
* Platform/Target and Browser Versions: macOS, Windows, CORDOVA, IOS, ANDROID, CHROME etc
* Live Link or JSFiddle/Codepen or website with isssue: n / a

### What you did
`const workingFor = new libs.Swiper('.mainslider', {
    spaceBetween: 10,
    loop: false,
    loopedSlides: 5,
    thumbs: {
        multipleActiveThumbs: true,
        swiper: {
            el: '.images',
            loopedSlides: 5, //looped slides should be the same
        },
        swiper: {
            el: '.thumbs',
            loopedSlides: 5, //looped slides should be the same
            slidesPerView: 3,
        }
    }
});`

### Expected Behavior
I expect that .thumbs slider can control both .images and .mainslider.

### Actual Behavior
.thumbs on click is only driving .mainslider and not the .images

**Comment by maxa315** [comment]
Hello, were you able to solve this problem?

**Comment by kevinmu17** [comment]
Yes, you need this: https://swiperjs.com/swiper-api#controller instead of the thumbs.

Init your swipers and than attach them with with the method.

```
const swiper1 = new Swiper()
const swiper2 = new Swiper()
const swiper3 = new Swiper()

swiper1.control = [swiper2,swiper3]
```
