### ISSUE TITLE
TypeError: Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by zerostyle** [nolimits4web/swiper#3559]
Swiper fails when I try and destroy the instance of swiper.

* [x] bug
* Swiper Version: 5.3.8.
* Platform/Target and Browser Versions: Mac OS, Chrome 81.0.4044.129 and Safari 13.1 

### What you did
This happens when I try to unmount and destroy the instance.

### Expected Behavior
Should just unmount and clean up events and styles.

### Actual Behavior
I get a TypeError: Cannot read property 'removeEventListener' of undefined.

` el.removeEventListener('mousedown', swiper.onTouchStart, false);`

<img width="1029" alt="Screenshot 2020-05-01 09 20 11" src="https://user-images.githubusercontent.com/185137/80835050-af8b1a00-8b8d-11ea-9a43-bc7bfb0954cf.png">

**Comment by curiousdustin** [comment]
What was your solution?
