### ISSUE TITLE
Can you remove the references to UIWebView please?

### ISSUE THREAD

**Issue by phusting** [nolimits4web/swiper#3561]
This is a (multiple allowed):
* [x] bug
* [X ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.8
* Platform/Target and Browser Versions:  macOS, Windows, CORDOVA, IOS, ANDROID, CHROME

### What you did
Prior to April 30, 2020 we could use UIWebView

### Expected Behavior
It should automatically be approved by apple

### Actual Behavior
TMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

**Comment by nolimits4web** [comment]
There is no references to UIWebView in Swiper

**Comment by phusting** [comment]
Just one of several files, but I'll list the line numbers in the following files.  But it is in all your .js files.  Apple rejects app that even in text contain that keyword.  :o) 

https://github.com/nolimits4web/swiper/blob/master/package/js/swiper.js

Line 2830, 3822, 4464, 8148

**Comment by phusting** [comment]
> There is no references to UIWebView in Swiper

Just one of several files, but I'll list the line numbers in the following files. But it is in all your .js files. Apple rejects app that even in text contain that keyword. :o)

https://github.com/nolimits4web/swiper/blob/master/package/js/swiper.js

Line 2830, 3822, 4464, 8148
