### ISSUE TITLE
Multi row slides layout does not work with direction 'vertical'

### ISSUE THREAD

**Issue by martin-petzold** [nolimits4web/swiper#3563]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.7
* Platform/Target and Browser Versions: Linux, Google Chrome 63.0.3239.132
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/swiper-demo-17-multi-row-slides-layout?file=index.html (set direction to vertical)

### What you did

I tested 'multi-row-slides-layout' in Stackblitz and set the direction to 'vertical'.

I also tried to change width and height calculation, but I can't get it working.

### Expected Behavior

Two columns with three rows. Scrolling is vertical.

### Actual Behavior

One column with three rows. Scrolling is vertical.

**Comment by dvjeshka** [comment]
+

**Comment by ygj6** [comment]
The example you provide does not seem to have the problem you describe.

**Comment by Elvenmagic** [comment]
I've got same problem. 

Here's the link of default multirow demo, which I forked and added direction: "vertical" in options. 

https://codesandbox.io/s/swiper-slides-per-column-forked-i4gfo

![image](https://user-images.githubusercontent.com/4090891/122748129-e560f580-d29c-11eb-804f-92d0448afbc0.png)
