### ISSUE TITLE
Any way for a donation for a great Swiper product?

### ISSUE THREAD

**Issue by WhereJuly** [nolimits4web/swiper#3565]
Hey Vladimir, did you consider the donation for the product?

I use it in commercial projects and I would like to contribute to the development with some financial support. Any baker platform you are in?

**Comment by nolimits4web** [comment]
Hi! Thanks, i am here https://www.patreon.com/vladimirkharlampidi just for the case :)

**Comment by WhereJuly** [comment]
True :) My bad. I am not used to these sponsor badges. You could duplicated it it onto https://swiperjs.com/ as well. Would not do any harm at all.

Apart of it again advanced product features look really usefull and carefully taken care of. Top notch.
