### ISSUE TITLE
Refresh lazy slides when src changes

### ISSUE THREAD

**Issue by raphaelnoguier** [nolimits4web/swiper#3568]
This is a :
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.8.
* Platform/Target and Browser Versions: MacOS Chrome.

### What you did
I have a slider with lazy loading, images are set like this : 

<img width="532" alt="Capture d’écran 2020-05-07 à 15 38 52" src="https://user-images.githubusercontent.com/22751073/81301073-dd35fe80-9078-11ea-9b5b-7cfc8d09cbfb.png">

The problem is when i change my "activeCategory" variable (to get different images), the lazy loading is not triggered while the data-src attribute is changing.
I tried "mySlider.lazy.load()" to refresh the slides but it didn't work. 

### Expected Behavior
Every time data-src change, trigger lazy loading events and change the src

### Actual Behavior
The src that has been set from the first loading stay in place. It should get replaced by the new data-src attribute. Any idea @nolimits4web ? 

Thank you very much ! 😃

**Comment by kalitk0** [comment]
Have you found a fix, I have the same problem.

**Comment by nerfologist** [comment]
Hello, I'm running into the same problem; this issue should probably be reopened since it hasn't been addressed or resolved. Can we work together on this?

**Comment by raphaelnoguier** [comment]
@nerfologist @kalitk0 Nope. Unfortunately the project i was working on just removed the feature that needed this lazy loading so i've never found a way to fix that ...
