### ISSUE TITLE
Swiper not updating offset without resize

### ISSUE THREAD

**Issue by harm-matthias-harms** [nolimits4web/swiper#3571]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.3.8
* Platform/Target and Browser Versions: all
* Live Link or JSFiddle/Codepen or website with isssue: [Stackblitz demo](https://stackblitz.com/edit/swiper-demo-15-free-mode-no-fixed-positions-nipqeq)

### What you did
I wanted to change the offset parameter after the initialization:
```
swiper.params.slidesOffsetBefore = -100;
swiper.update();
```
### Expected Behavior
The swiper updates the offset properly.

### Actual Behavior
The swiper isn't updating the slides until the window gets resized.

**Comment by harm-matthias-harms** [comment]
If free mode is disabled the swiper is working as intended.

**Comment by niklasp** [comment]
probably related #3929

**Comment by vltansky** [comment]
@harm-matthias-harms 
I can't reproduce the issue
https://stackblitz.com/edit/swiper-demo-15-free-mode-no-fixed-positions-t3tnlf?file=index.html
Looks like it's working fine in this example, no?

**Comment by harm-matthias-harms** [comment]
@vltansky Yes, it seems to work with the latest version. I'm closing this issue. Thanks for checking.
