### ISSUE TITLE
Swiper-wrapper size is different when content is not cached 

### ISSUE THREAD

**Issue by digitalfive** [nolimits4web/swiper#3576]
Hey everyone,

so i have an issue with the swiper wrapper, i think.
Everytime i reload my page and clear the cache, my slider is not exactly centered in the middle.
After i cached the slider, the slider is centered correctly.

Here is a example:
![screen-capture](https://user-images.githubusercontent.com/32178696/81803826-7dc46c80-9518-11ea-8068-c7951347a38c.gif)

First i reload the page + clear the cache. After that, i just refreshed the page.

I think it has something todo with the calculation when i added "loop: true" to my slider.

`var projectSwiper = new Swiper ('.project-swiper', {
    loop: true,
    centeredSlides: true,
    slidesPerView: 'auto',
    loopedSlides: 2,
    spaceBetween: 180,
    grabCursor: true,
    keyboard: true,
    speed: 800
});
`

**Comment by digitalfive** [comment]
So after trying different things i think the problem is, that man slider loads to fast.
My fix looks like this right now.

` setTimeout(function() { `
`   projectSwiper.update();   `
` }, 200);`

Is there a better way to fix it?

**Comment by nolimits4web** [comment]
This is related to images sizes which are unknown until they are loaded
