### ISSUE TITLE
Windows 10, Chrome 81, mousewheel is not working from version 5.2.1

### ISSUE THREAD

**Issue by ljanecek** [nolimits4web/swiper#3581]
On the Windows 10, Chrome 81, mousewheel scroll is not working. It's not possible to scroll to third and other slides. 

https://swiperjs.com/demos/270-mousewheel-control.html

**Comment by digitalfive** [comment]
Same Problem, this is my work around right now.

`const content = document.querySelector('body');`
``
`content.addEventListener("wheel" , (e) => {`
    `e.deltaY < 0 ? projectSwiper.slideNext(800) : projectSwiper.slidePrev(800);`       
`});`

**Comment by nolimits4web** [comment]
Duplicate of #3420
