### ISSUE TITLE
autoScrollOffset not working

### ISSUE THREAD

**Issue by zigi05** [nolimits4web/swiper#3591]
If I understand it correctly, then `autoScrollOffset` shows the number of thumbs from an active thumb to the border of thumbs container.

For example if `autoScrollOffset: 2`, the the expected result should be this:

![thumbs](https://user-images.githubusercontent.com/10746393/82656975-439c4e80-9c2d-11ea-85df-2d888a4696de.jpg)

However, it doesn't seem to work, as demonstrated here:
https://jsfiddle.net/zov4pwaL/

**Comment by nolimits4web** [comment]
You have wrong syntax in parameters, it should be:
```
const galleryTop = new Swiper('.main-slider', {
  thumbs: {
    autoScrollOffset: 3,
    swiper: {
      el: '.gallery-thumbs',
      slidesPerView: 5,
      spaceBetween: 2,

    }
  }
});
```
