### ISSUE TITLE
PSA: Too big/wide slider on initialization

### ISSUE THREAD

**Issue by strarsis** [nolimits4web/swiper#3599]
When your swiper slider initializes too big (sometimes even far, far wider than the page), 
this could happen from the slider wrapper element being inside a CSS flexbox/grid container.
The following styles fix the issue:
```scss
.swiper-container {
  width: 100%;
  max-width: 100%;
  max-height: 100vh;
  // CSS Grid/Flexbox bug size workaround
  // @see https://github.com/kenwheeler/slick/issues/982
  min-height: 0;
  min-width: 0;
}
````
IT also contains a fix for Firefox and it also works with the Slick slider (and probably other like Splide).
I had to search quite a bit to find a working solution, 
so I hope this is helpful for me in the future and other developers, enjoy!

Related issues:
https://github.com/nolimits4web/Swiper/issues/312
https://github.com/nolimits4web/swiper/issues/2095
https://github.com/nolimits4web/Swiper/issues/312
https://github.com/nolimits4web/swiper/issues/109
https://github.com/nolimits4web/Swiper/issues/153
https://github.com/nolimits4web/Swiper/issues/153
https://github.com/nolimits4web/swiper/issues/2095

**Comment by linonetwo** [comment]
Oh man, you save my day! This solution actually works, and it should be in the doc.

**Comment by linonetwo** [comment]
Also, note that:

`.swiper-slide` requires these in some case:

```css
  width: auto;
  flex-shrink: 0;
  display: block;
  height: 100%;
  max-height: 100%;
```

`.swiper-wrapper` needs:

```css
  max-height: 100%;
  height: 100%;
  display: flex;
```

**Comment by Codisy** [comment]
Если у вас проблема с swiper и grid layouts, когда у далекого от слайдера родителя установлены grid-template-columns в фракциях, то эти хаки уже не помогают просто так. Я имею ввиду ситуации когда например у body стоит grid-template-columns: 3fr 9fr; а уже у глубоко лежащего div внутри находится swiper, то ближайшему к swiper родителю надо установить display: grid; тогда эти хаки заработают. 

Вот наглядный пример этого поведения: https://jsfiddle.net/codisy/2nc1dz4q/84/

**Comment by strarsis** [comment]
@Codisy: Translated to English (Google Translate):
> If you have a problem with swiper and grid layouts, when the parent far from the slider has grid-template-columns in fractions set, then these hacks no longer help just like that. I mean the situation when, for example, the body has grid-template-columns: 3fr 9fr; and already the deeply lying div has a swiper inside, then the parent closest to the swiper needs to set display: grid; then these hacks will work.
> 
> Here's a good example of this behavior: https://jsfiddle.net/codisy/2nc1dz4q/84/

**Comment by kronthto** [comment]
This may be relevant too, it solved it for us: https://stackoverflow.com/a/53022198/7362396 
It was added on a flex parent item many layers above the Swiper.

**Comment by strarsis** [comment]
> This may be relevant too, it solved it for us: https://stackoverflow.com/a/53022198/7362396 
> It was added on a flex parent item many layers above the Swiper.

Obligatory StackOverflow answer that answers should contain the code and not just a link to it. :)

**Comment by clearly-outsane** [comment]
Oh my god thank you this saved me. I was so confused for 30 minutes straight - my div size was 3 million pixels wide but this fixed it xD

**Comment by ndhanh96** [comment]
if you use tailwind add overflow-hidden to swiper container
`
<div className='swiper overflow-hidden ...>
....
</div>
`

**Comment by jcswanson** [comment]
I LOVE YOU. I got rid of `display: flex;` and it solved the issue of my width going over 1.6 million pixels below 768px width. Crashed my computer once as well.

**Comment by Stephen4018** [comment]
in my own case, swiper seems to be shrinking my webpage on mobile view but its  okay on desktop view

**Comment by minlare** [comment]
In my case I simply had to do the following:

```
.my-swiper-container {
  display: grid;
}

.my-swiper-container .swiper {
  max-width: 100%;
}
```

**Comment by hsdonkin** [comment]
One workaround I found is to use `minmax(0, 1fr)` instead of `fr` or `auto` 

https://lightrun.com/answers/nolimits4web-swiper-css-grid--swiper-wrapper---wrong-width-calculated

**Comment by gabrielpb88** [comment]
I solved the problem setting max values for height and width:
`.carousel__container {
        max-width: 100%;
        max-height: 100%;
    }`

**Comment by GoglichidzeMike** [comment]
> In my case I simply had to do the following:
> 
> ```
> .my-swiper-container {
>   display: grid;
> }
> 
> .my-swiper-container .swiper {
>   max-width: 100%;
> }
> ```

this has actually helped me. than you

**Comment by emsitkowski** [comment]
> `.swiper-slide` requires these in some case:
> 
> ```css
>   width: auto;
>   flex-shrink: 0;
>   display: block;
>   height: 100%;
>   max-height: 100%;
> ```

This has fixed my bug, thanks 💪

**Comment by Chen-913** [comment]
> In my case I simply had to do the following:就我而言，我只需执行以下操作：
> 
> ```
> .my-swiper-container {
>   display: grid;
> }
> 
> .my-swiper-container .swiper {
>   max-width: 100%;
> }
> ```

My God! You saved me! Thanks

**Comment by emreygc7** [comment]
Thanks. You saved my time.

**Comment by eseQ** [comment]
DON'T USE css `flex` on `swiper` container. If you want make slide full height — just use `height: 100%` for parent and slides!

**Comment by martinharyanto** [comment]
so many work around, so many people got this problem, why this is still not a fix you yet? I don't mean to be annoying, but I myself got this problem, and was very confused on why it is not working. 

I can't or even know what to search in google lol. I was checking one by one if any of the issue (if any one) was same like me.. I hope this is fixed or at least moved to the docs as known bug / quickfix

**Comment by sueharaluke** [comment]
Only this worked for me: 

```html
<style>
  .swiper {
    display: grid;
  }
  .swiper-wrapper {
    min-width: 0;
  }
</style>

<div class="swiper">
  <div class="swiper-wrapper">
    <div class="swiper-slide"></div>
    <div class="swiper-slide"></div>
    <div class="swiper-slide"></div>
  </div>
</div>
```

**Comment by adampatterson** [comment]
The Desktop version is perfectly fine, but once I go to mobile my slides get an inline width of `width: 3.35544e+07px`.

**Comment by damontes** [comment]
> The Desktop version is perfectly fine, but once I go to mobile my slides get an inline width of `width: 3.35544e+07px`.

This was actually working fine dont know what might change, also i just return to the version that i have but still not working

**Comment by projct1** [comment]
Still the same problem. When initialized, the width of the sliders is very large. Overriding styles as above does not help.

**Comment by ArtemKobko** [comment]
Hi all! I had the same problem, the solutions described above did not help. I think that the creators slightly changed the classes inside the library. Now I don’t see the class "swiper-container", but there is just "swiper" . Here is my  only one thing , that I added into global styles file .swiper {
  width: 100%;
}

**Comment by projct1** [comment]
I switched to splidejs, there are absolutely no problems with it.

**Comment by estebesm** [comment]
This worked for me
![image](https://github.com/nolimits4web/swiper/assets/61909292/a7ffb5e8-572c-4d54-abc0-8b5f4ce7d268)

**Comment by lukerhd** [comment]
Just ran into this and after trying a couple of the fixes mentioned w/o avail, it got me thinking and this finally resolved it in my case:
`.swiper-slide {
    flex-shrink: 1;
  }`
Note: My parent class to `.swiper-slide` is `.swiper-wrapper`, which is `display: flex;`

**Comment by abishekbaiju** [comment]
> In my case I simply had to do the following:
> 
> ```
> .my-swiper-container {
>   display: grid;
> }
> 
> .my-swiper-container .swiper {
>   max-width: 100%;
> }
> ```

adding width full solved mine. thanks

**Comment by tiennguyenvan** [comment]
> Если у вас проблема с swiper и grid layouts, когда у далекого от слайдера родителя установлены grid-template-columns в фракциях, то эти хаки уже не помогают просто так. Я имею ввиду ситуации когда например у body стоит grid-template-columns: 3fr 9fr; а уже у глубоко лежащего div внутри находится swiper, то ближайшему к swiper родителю надо установить display: grid; тогда эти хаки заработают.
> 
> Вот наглядный пример этого поведения: https://jsfiddle.net/codisy/2nc1dz4q/84/

You saved my whole life brother! Thank you very much.

**Comment by skyslide22** [comment]
Also if your layout looks like this:
```html
<div class="grid">
  <div class="sidebar"></div> 
  <div class="main">
    <swiper ...>
  </div>
</div>
```

my solution was forcing the grid children to have min width of 0:
```css
.grid {
    display: grid;
    grid-template-columns: 300px 1fr;
    min-height: 100%;

    & > * { 
        /* nesting works in CSS since a year now */
        /* <selector> > * will affect all direct children of the parent, so .sidebar & .main are targeted only */
        min-width: 0 !important;
    }
}
```

found on https://stackoverflow.com/a/75311699/16835259

**Comment by Abu-Bakr-Mohamed** [comment]
I had the same problem where the slider's width increases infinitely when the parent is a flexbox

I wrapped the swiper inside a div with class="grid grid-cols-1 max-w-6xl" and that fixed the problem.

**Comment by Udeh-png** [comment]
Dude even ai couldn't help me!! thank you all soo much

what worked for me was just adding min-w-0 to the direct child (parent of Swiper component) of the parent that had the grid display
