### ISSUE TITLE
preventLinks not working

### ISSUE THREAD

**Issue by bobhuf** [nolimits4web/Swiper#360]
Hi,

I'm using Swiper in combination with [Magnific Popup](http://dimsemenov.com/plugins/magnific-popup/). Unfortunately preventLinks is not working. I've tried adding e.preventDefault(); to every callback possible but it doesn't work.

I made some code available here for you to inspect:
https://dl.dropboxusercontent.com/u/2177001/bs/index.html

**Comment by sintro** [comment]
Just did the same trick for Swiperbox library, here is the code (coffee):
```
window.enableGalleryClick = false;

$(document).ready(function() {
  var mainSwiper = new Swiper('.photos-gallery', {
    onTouchMove: function() {
      window.enableGalleryClick = false;
    },
    onTouchEnd: function() {
      setTimeout(function() {
        window.enableGalleryClick = true;
      }, 100);
    }
  });
  $('.swipebox').swipebox({
    beforeOpen: function() {
      if (!window.enableGalleryClick) {
        return false;
      }
    }
  });
});
```
