### ISSUE TITLE
swiperjs.com constantly unreacheable from Russia

### ISSUE THREAD

**Issue by sashabeep** [nolimits4web/swiper#3608]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Opened website https://swiperjs.com/
From time to time i'm getting errors about firefox could not create secure connection
In some minutes site opens and i can read the documentation.
Tried some different internet providers with the same result.

### Expected Behavior
Site must be available from everywhere

### Actual Behavior
It feels like site in hibernation, and after some minutes it's woke up.

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
