### ISSUE TITLE
Effects cube, fade and coverflow not working with renderExternal [Vue]

### ISSUE THREAD

**Issue by ctwhome** [nolimits4web/swiper#3613]
Type:
* [x] bug

* Swiper Version: 5.4.2
* Vue Version: 2.6.11
* Platform/Target and Browser Versions: macOS, Chrome
* Live Link with isssue: https://codesandbox.io/s/cube-effect-not-working-with-render-external-ti99n?file=/src/App.vue

### What you did

Not able to show 3d effect when `renderExternal` is present. 

```vue
 mounted() {
    const self = this;
    this.mySwiper = new Swiper(".swiper-container", {
      // ...
      effect: "slide", //<-- cube, fade, coverflow
      virtual: {
        slides: self.slides,
        renderExternal(data) {
          // assign virtual slides data
          self.virtualData = data;
        }
      }
    });
```

### Expected Behavior
Get Cube, Fade and overflow effects working.
I wish the effects were working properly to show a list of more than 1000 cards. 

### Actual Behavior
For `cube` effect, doesn't work at all. 
for `fade effect` the slides stop showing after 3 slides.
for `coverflow effect`: the animation gets out of place.
![cube](https://user-images.githubusercontent.com/4195550/83801046-bc2cf180-a6a8-11ea-9edd-e53e4a17b645.gif)

**Comment by nolimits4web** [comment]
Because i guess Vue overwrites slide classes or some styles. Closing as not relevant directly to Swiper

**Comment by ctwhome** [comment]
Hi @nolimits4web would you be willing to take a look at what's is exactly going on? This only happens with render external, I don't' see the relation with Vue changing/removing classes because of that? Tnx!
