### ISSUE TITLE
Zoom: Double tap to reset no longer works in iOS Safari 13.1

### ISSUE THREAD

**Issue by wwform** [nolimits4web/swiper#3615]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 5.3.6
* Platform/Target and Browser Versions: iOS Safari 13.1

Double tap to zoom in works, double tap to zoom out does not work.
This works fine on iOS Safari 13.0 on the Simulator but no longer works on 13.1.

Double click on desktop works. 
Touchstart event seems to register fine.

**Comment by enderimen** [comment]
@nolimits4web, This problem still persists. Are you not going to make an improvement for it?
