### ISSUE TITLE
Slides overflow when using flex container

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [nolimits4web/swiper#3617]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.2.
* Platform/Target and Browser Versions: Windows, firefox, chrome.

I am experiencing the exact same issue as https://github.com/nolimits4web/swiper/issues/3067 however there has been no discussion or solution provided and yet the issue is close.

Is there a solution to this problem?

**Comment by nolimits4web** [comment]
Check #3599
