### ISSUE TITLE
Autoplay not working with fade effect

### ISSUE THREAD

**Issue by nicolebo** [nolimits4web/swiper#3622]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.3
* Platform/Target and Browser Versions: Firefox, Chrome with Windows.

### What you did
Autoplay works when i use some other effect, like flip, cube, etc
Code:  var Swiper = require('swiper');
     $('.fss').each(function(){
            window.fss = new Swiper.default($(this), {
                effect: 'fade',
                fadeEffect: {
                    crossFade: false,
                },
                direction: 'horizontal',
                loop: true,
                speed: 500,
                autoplay: true,
                keyboard:
                {
                    enabled: true,
                    onlyInViewport: false,
                },
                autoplayDisableOnInteraction: false,
                slidesPerView: 1,
                spaceBetween: 0,
                mousewheel: false,
            });
    });
### Expected Behavior
What I hope is that I do an autoplay with the fade effect.

### Actual Behavior
The application starts, appearce the first slide, then swipe to the next slide but there it stops and stays.

**Comment by Splode** [comment]
Running into this issue with v5.4.1 as well.

**Comment by nfq** [comment]
I had to hack a fix as well. It seems `.swiper-slide-active` is not applying `opacity: 1`. I added this to my stylesheet manually and fade now works.

**Comment by porosh2002** [comment]
STILL FACING THIS ISSU WITH 
7.0.1

**Comment by porosh2002** [comment]
STILL FACING THIS ISSUE WITH 7.0.1
