### ISSUE TITLE
Page Up / Page Down captured by Swiper

### ISSUE THREAD

**Issue by scottsweb** [nolimits4web/swiper#3623]
This is an issue carried over from the Jetpack project:

https://github.com/Automattic/jetpack/issues/14567

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.1
* Platform/Target and Browser Versions: All Browsers
* Live Link or JSFiddle/Codepen or website with isssue: 
* Code in question: https://github.com/nolimits4web/swiper/blob/8d0dd34f87a48a497389f2cc8ed9503c0ba351b3/src/components/keyboard/keyboard.js#L53

### What you did

The Jetpack project uses Swiper as a gallery block for the Gutenberg project. It implements the keyboard shortcuts feature and we have had reports of accessibility concerns when using the "Page Up" and "Page Down" keys. 

For keyboard users, they are unable to get past the galleries and remains stuck inside the gallery.

### Expected Behavior

"Page Up" and "Page Down" to not be on the list of shortcuts OR for the list of shortcuts to be customisable. The other option would be to not loop to the start when using these keys.

### Actual Behavior

"Page Up" and "Page Down" are no longer working, making it harder to navigate the page via keyboard.

**Comment by ktan88** [comment]
@nolimits4web why is this closed?
Issue still existis
