### ISSUE TITLE
Speed for Autoplay Independent from Interaction Speed

### ISSUE THREAD

**Issue by kerns** [nolimits4web/swiper#3625]
This is a (multiple allowed):
* [x] enhancement
* [ ] bug
* [ ] feature-discussion (RFC)

Would just be very nice if you could set one speed to be applied for the slideshow (or pre-interaction) phase, and another speed for use once the swiper has been interacted with.

I want a very calm, easy going transition between items at 2.4 secs per transition, but this obviously makes for a horrible interaction once you begin swiping between slides on your own.

I hoped something like this would work but it doesn't seem to at the moment.

```
...
...
autoplay: {
  delay: 5000,
  disableOnInteraction: true,
  speed: 2400,
},
speed:400,
...
...

```

**Comment by ScreenDream** [comment]
Same here, would be great to have this ability.
Since I seem to be unable to change the speed after init, a feature like this would be great!
