### ISSUE TITLE
disabledClass for Navigation Never Applied

### ISSUE THREAD

**Issue by EvilJordan** [nolimits4web/swiper#3627]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.5
* Platform/Target and Browser Versions: All
* https://jsfiddle.net/snf2g34h/1/

### What you did
Attempting to initialize with `allowSlideNext` or `allowSlidePrev` works, but does not apply the `disabledClass` to the button.

### Expected Behavior
Navigation button is initialized with the `swiper-button-disabled` and `aria-disabled="true"`

### Actual Behavior
Navigation button _looks_ enabled, but actually isn't.

**Comment by EvilJordan** [comment]
It also appears calling `mySwiper.allowSlideNext = false;` does not apply the `disabledClass`, nor does calling `mySwiper.navigation.update();` post boolean setting.

**Comment by EvilJordan** [comment]
I have temporarily solved for this by moving the `init` function outside the initializer, the applying a class change directly to the navigation element:

```
var mySwiper = new Swiper ('.swiper-container', {
    init: false,
    allowSlideNext: false,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    }
});
mySwiper.on('init', function() {
    this.navigation.nextEl.classList.add('swiper-button-disabled');
});
mySwiper.init();
```

**Comment by andynoir** [comment]
@EvilJordan have you tried to wrap your swiper initialization into `requestAnimationFrame` ? I have a similar problem, on initial page load `swiper-button-disabled` class is not being added, but i am using VueJS. I have done something like this:

```
requestAnimationFrame(() => {
      const swiperInstance = new SwiperInstance('.swiper-container', settingsObject)
    })
```

**Comment by vltansky** [comment]
updated demo:
https://jsfiddle.net/xgLa76q8/

**Comment by dangelion** [comment]
Anyone solved this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
