### ISSUE TITLE
Looped swiper with thumbnails and typing effect - problems

### ISSUE THREAD

**Issue by rudolphreti** [nolimits4web/swiper#3629]
Hi,
your Swiper is a great job. I'm very grateful to you. I added typing effect to it and there are some problems. Could you take a look at this code: https://codepen.io/reti/pen/YzwNdqz

Please pay special attention to that:
```
galleryTop.on("transitionStart", function() {
    allowTouchMove(false)
    clearTopContainersIfNotEmpty()
    typingInc = 0
    hideNavDuringTransition("none")
})

galleryTop.on("transitionEnd", function() {
    setTimeout(function() {
        hideNavDuringTransition("unset")
        allowTouchMove(true)
    }, delayAfterTransitionEnd)
    setTimeout(typeWriter, delayAfterTransitionEndForTypingWriter)
}) 
```
This solution eliminates the problems with putting text for slides 4 and 0 to wrong containers:
1. hideNavDuringTransition(x) and allowTouchMove(x) prevent problems when slides are changed very fast,
2. delay for typeWriter() prevent problems when slides are changed in normal tempo.
It's very ugly and must be changed, right? How should I do it correctly?

**Comment by nolimits4web** [comment]
When `loop` mode enabled it will duplicate slides HTML elements, you should consider it in your custom script
