### ISSUE TITLE
Autoplay doesn't work

### ISSUE THREAD

**Issue by catamphetamine** [nolimits4web/swiper#3630]
`autoplay` `delay` doesn't work.
It only switches the slide one time, stops, then switches every time a browser tab is switched.

**Comment by catamphetamine** [comment]
Found the workaround.
The source of the bug is the line:

```js
  onTransitionEnd: function onTransitionEnd(e) {
    var swiper = this;
    if (!swiper || swiper.destroyed || !swiper.$wrapperEl) return;
    if (e.target !== this) return;
```

`e.target` is always a DOM element, `this` is always a `Swiper` instance.

The fix is using `waitForTransition: false` option in `autoplay` config.

**Comment by nolimits4web** [comment]
Fixed in latest 6.x

**Comment by huanlirui** [comment]
> Fixed in latest 6.x

in 6.3.5 (react) autoplay does not work !

**Comment by egenita** [comment]
> > Fixed in latest 6.x
> 
> in 6.3.5 (react) autoplay does not work !

Same here, autoplay is not working in 6.3.5

**Comment by duoluodexiaoxiaoyuan** [comment]
> waitForTransition

I'm using version swiper 6.4.5 and it works autoplay, but sometimes it stops suddenly, can you take the method above. Because this situation is accidental.

**Comment by duoluodexiaoxiaoyuan** [comment]
> > Fixed in latest 6.x
> 
> in 6.3.5 (react) autoplay does not work !

想问下你这种情况是偶发的还是必现的，我现在遇到的是偶发的，所以我不知道应该如何解决
