### ISSUE TITLE
Keep initialized styling on -initialized class

### ISSUE THREAD

**Issue by Curzey** [nolimits4web/swiper#3633]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.2
* Platform/Target and Browser Versions: General

### What you did
Added HTML markup for slider, to be initialized on _some_ breakpoints (on desktop it has swiper markup, but it wont be initialized)

### Expected Behavior
The swiper classes `swiper-container`, `swiper-wrapper` and `swiper-slide` has no/minimal styling, so non-initialized content won't behave like a bugged slider. All slider-related styles should then be attached on `swiper-container-initialized` - which in fact already gets added to the DOM.

### Actual Behavior
The swiper classes `swiper-container`, `swiper-wrapper` and `swiper-slide` has slider-related styling. E.g `swiper-container` has some overflow styling, so even though the slider is **not** initialized, the slides are still overflown.

**Comment by nolimits4web** [comment]
Swiper is designed to be used as initialised only! If you don't init it, remove those classes

**Comment by Curzey** [comment]
This doesn't really resolve the issue where I want to initialize then slider on mobile, but not desktop. So it would be nice if I were able to keep the swiper markup ready for initialization. 

Can't see how it should be a problem to best these styles in the initialized class?
