### ISSUE TITLE
Lazy Loading images(Lazysizes) of the swiper when it is not in viewport

### ISSUE THREAD

**Issue by keerthanaswarnakumar** [nolimits4web/swiper#3634]
Hi, I am currently using Swiper 5.3.7.  Everything works fine except the Lazy Loading.
I am using a separate module **Lazysizes** for Lazy Loading images in the site.
And I am aware that Swiper provides Lazy Loading only for images that are inside the slider(Active/Inactive slides).

When I am using Lazysizes with Swiper Lazy Load, Lazy Load works perfect until I reach the viewport. Once I am in the viewport, it loads all the images of the slides are loaded irrespective of the active/Inactive state.

Expected Outcome:
Swiper Lazy Load should be enabled when the page reaches the viewport. Till then Lazysizes will control the images loading.

**Comment by Daijobou** [comment]
Have you this issue in version 6.2 too? Can you make a demo (fiddle)?

**Comment by keerthanaswarnakumar** [comment]
@Daijobou 

I am using Swiper version 5.3.7 and I fixed this issue with my custom code.

Issue was due to the width of the swiper slider.  I was using the swiper inside "2 column left" layout, but the swiper container is considering the whole page layout and hence the images that are hidden are not lazyloaded.

**Comment by v-hc** [comment]
@Daijobou I have the same issue with my fullscreen slider. could you share your fix? that would be amazing.

**Comment by vltansky** [comment]
@v-hc still relevant in v6.x.x?
