### ISSUE TITLE
Files missing in repository

### ISSUE THREAD

**Issue by KonstantinSchuette** [nolimits4web/swiper#3635]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### Expected Behavior
Files like `swiper-bundle.min.css` should be in the `/package` folder.

### Actual Behavior
No files like `swiper-bundle.min.css` are in the `/package` folder.

**Comment by nolimits4web** [comment]
> Files like swiper-bundle.min.css should be in the /package folder.

No, they shouldn't be there
