### ISSUE TITLE
Continuous high CPU usages by pre-loader animation.

### ISSUE THREAD

**Issue by shahedurrahman** [nolimits4web/swiper#3636]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.5
* Platform/Target and Browser Versions: Windows 10, Edge/Chrome

### What you did
I have a page with multiple swiper (~10) and each swiper contains 10 to 15 image slides. The page loads fine and when loading animation ends, I still see continuous high CPU usages in Browser's task manager.

### Expected Behavior
CPU usages should come back to normal after page load.

### Actual Behavior
Continuous high CPU usages even after page finishes loading.

Here is my swiper initialization code.
```javascript
function init() {
	new Swiper('.swiper-container', {
		cssMode: false,
		roundLengths: true,
		preloadImages: false,
		loop: true,
		lazy: true,
		pagination: {
			el: '.swiper-pagination',
			dynamicBullets: true
		},
		navigation: {
			nextEl: '.swiper-button-next',
			prevEl: '.swiper-button-prev'
		},
	})
}
```

For now I have disabled loading animation by removing following code, and CPU usages is as expected.
```html
<div class="swiper-lazy-preloader"></div>
```

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
