### ISSUE TITLE
Closing as not related to Swiper (I'm sorry, I don't know how else to communicate)

### ISSUE THREAD

**Issue by shahedurrahman** [nolimits4web/swiper#3637]
I'm sorry, but I really don't understand how this is not related to Swiper! Anyone care to put a line to explain? Thanks!

Closing as not related to Swiper

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/3636#issuecomment-648789070_

**Comment by nolimits4web** [comment]
Swiper loader uses simple CSS animation to rotate it. Of course, as any animation it increases CPU usage. You have it many -> more CPU usage. Nothing can be done on Swiper side. Don't like it? Remove preloaders or disable animation for them
