### ISSUE TITLE
Can't see right navigation arrow within a zoomed page (transform: scale(1+))

### ISSUE THREAD

**Issue by janstrbik** [nolimits4web/swiper#3638]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.5
* Platform/Target and Browser Versions: Windows 10, Chrome v83
* Stackblitz issue : https://stackblitz.com/edit/swiper-demo-31-thumbs-gallery-with-loop-mode-1pwq9m

### What you did
I am using swiper v 5.4.5 and found a bug, when I zoom a page with e.g. `transform: scale(1.5)` then I cant see the right arrow, it is possible to click on that area where it should be, but it is not visible. Please see Stackblitz example with the official example of gallery, I have just added scaling there with `style="transform: scale(1.5); width: 260px;"`:

### Expected Behavior
with navigation allowed, both arrows should be visible

### Actual Behavior
right navigation arrow is hidden due to swipe overflow when transform: scale is more then 1

**Comment by nolimits4web** [comment]
Add to CSS
```css
.swiper-button-next {
  transform: translate3d(0,0,0)
}
```
