### ISSUE TITLE
Swiper pagination dynamicBullets is not working

### ISSUE THREAD

**Issue by gbshhennsi** [nolimits4web/swiper#3639]
* Swiper Version: 
   "ngx-swiper-wrapper": "version": "9.0.1",
"swiper": "^5.3.0"

### What you did

Hey Guys!
I am implementing the Swiperjs library into my Angular Project via the ngx-swiper-wrapper.
The swiping works completetly fine and I really like this library!

The pagination works almost fine except for one strange case.
When I set "dynamicBullets" inside my pagination to "true" the behavior of the pagination bullets doesn't change.

My swiper Config looks like this:
```
export const swiperConfig: SwiperConfigInterface = {
  direction: 'horizontal',
  slideToClickedSlide: true,
  grabCursor: true,
  updateOnWindowResize: true,
  centeredSlides: true,
  watchSlidesProgress: true,
  roundLengths: true,
  keyboard: true,
  touchEventsTarget: 'wrapper',
  loop: true,
  threshold: 50,
  observer: true,
  slidesPerView: 1,
  spaceBetween: 50,
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
    hideOnClick: false,
    type: 'bullets',
    dynamicBullets: true,
    dynamicMainBullets: 5,
    renderBullet: function (index, className) {
      return '<span class="' + className + '">' + (index + 1) + '</span>';
    }
  },
  init: true,
};
```

My scss setup of the swiper-pagination looks like this

```
  .swiper-pagination {
    display: flex;
    justify-content: center;
    position: inherit !important;
    width: 100% !important;

    .swiper-pagination-bullet {
      width: 20px !important;
      height: 20px !important;
      text-align: center;
      line-height: 20px !important;
      font-size: 12px;
      opacity: 1;
      border-radius: 100%;
      background: rgba(0, 0, 0, 0.2);
      margin: 3px;
      cursor: pointer;
    }
    .swiper-pagination-bullet-active {
      color: $color-white;
      background: $color-blue2;
      transform: scale(1);
    }
  }
```

### Expected Behavior

I expect the pagination to behave like it behaves in the example of the dynamic bullets:
![image](https://user-images.githubusercontent.com/53291773/85850084-67aefa80-b7ac-11ea-9440-3a57d6ddfea5.png)

### Actual Behavior

In full screen size it looks like this 
![image](https://user-images.githubusercontent.com/53291773/85850158-87462300-b7ac-11ea-8aa7-9640b7b68209.png)

and if the pagination wouldn't fit to the screen size it looks like this:

![image](https://user-images.githubusercontent.com/53291773/85850218-a5138800-b7ac-11ea-9ef8-ea95a8d101ff.png)

**Comment by nolimits4web** [comment]
> ngx-swiper-wrapper

I think you should look for issue on that's library side as it works correctly here https://stackblitz.com/edit/swiper-demo-4-pagination-dynamic-bullets?file=index.html
