### ISSUE TITLE
silder disappear on IOS device.

### ISSUE THREAD

**Issue by PankajK-HnH** [nolimits4web/swiper#3644]
Hi,

I am using swiper.js to implement coverflow effect. slider working fine in web and android devices but in IOS device slider disappear on the first slide. please help me..

here is the js code.
HTML  I have use the same as mentioned in the swiper js document.
```
var swiper = new Swiper('.swiper-container', {
    effect: 'coverflow',
    loop: true,
    centeredSlides: true,
    slidesPerView: 4,
    initialSlide: 0,

    coverflowEffect: {
      rotate: 0,
      stretch: 0,
      depth: 200,
      modifier: 1,
      slideShadows: true,
    },

    autoplay: {
      delay: 1500,
      disableOnInteraction: false,
    },
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    breakpoints: {
      320: {
        effect: 'fade',
        slidesPerView: 1,
        fadeEffect: {
          crossFade: true,
          slideShadows: false,
        },

      },
      480: {
        effect: 'fade',
        slidesPerView: 1,
        fadeEffect: {
          crossFade: true,
          slideShadows: false,
        },
      },
      640: {
        slidesPerView: 2,
      },
      1000: {
        slidesPerView: 3,
      },
      1250: {
        slidesPerView: 4,
      }

    }

  });
```

**Comment by Nic787** [comment]
Hi,

I also have a problem with IOS. Swiper doesn't work.
I can see navigation arrows, but nothing happen when I click on them and pagination is just gone.
I can only see first slide, but can't see the others.

Thank you

**Comment by abomokhahmed** [comment]
I have the same issue.
I am using swiper on my cordova app, and it really works fine on android but on ios it will blink for the first second of scrolling the items to the left.
I must tell that i am using RTL slider if that is relevant.
