### ISSUE TITLE
Swipe gestures dont work on tablet or desktop

### ISSUE THREAD

**Issue by antonioberetini** [nolimits4web/swiper#3649]
I tested swiper components on windows machine with touch interface, swipe gestures don't work. I tried this out in Chrome and Chromium Edge. Is this a known issue? I am working on a progressive web app which is targeting touch enabled tablets with windows

**Comment by kebien6020** [comment]
In #3589  there is a couple of cases with similar issues.

**Comment by vltansky** [comment]
Duplicate of #3772
