### ISSUE TITLE
Undefined variable: "$colors" in pagination.scss and navigation.scss

### ISSUE THREAD

**Issue by qtv100291** [nolimits4web/swiper#3653]
Hello, 
I use swiper for a React project but when importing :

     import 'swiper/components/navigation/navigation.scss';
     import 'swiper/components/pagination/pagination.scss';

An error message appears : Undefined variable: "$colors". 
Hope you can help, thanks!

**Comment by nikiman8888** [comment]
Same problem here)

**Comment by nikiman8888** [comment]
i delete from 
node_modules\swiper\components\pagination\pagination.scss
this peace of code and the pagination appear.

@each $paginationColorName, $paginationColorValue in $colors {
  .swiper-pagination-#{$paginationColorName} {
    --swiper-pagination-color: #{$paginationColorValue};
  }
}


PS : I guess you can change the css a bit to appear better, but for me by deleted this piece of code - start to work

**Comment by avidi** [comment]
> i delete from
> node_modules\swiper\components\pagination\pagination.scss
> this peace of code and the pagination appear.
> 
> @each $paginationColorName, $paginationColorValue in $colors {
> .swiper-pagination-#{$paginationColorName} {
> --swiper-pagination-color: #{$paginationColorValue};
> }
> }
> 
> PS : I guess you can change the css a bit to appear better, but for me by deleted this piece of code - start to work

There is a similar block of code in `navigation.scss` that references $colors that you can delete to make that work for now.

**Comment by nikiman8888** [comment]
Yes i did .Hope this help.

**Comment by wmzhong** [comment]
Same issue for the less version.
