### ISSUE TITLE
Old CDN URLs no longer work

### ISSUE THREAD

**Issue by jaredlt** [nolimits4web/swiper#3654]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Since version 6 was released, the CDN URLs have changed. But in addition, the old URLs no longer work at all :(

I encountered this this morning when I discovered our website looked broken. I know I should really install the assets locally but given the first step of [getting started](https://swiperjs.com/get-started/) suggests the CDN approach I think a LOT of people will be doing it this way.

Is it possible to keep the old URLs alive?

NB. There is a similar issue here https://github.com/nolimits4web/swiper/issues/3652 but I opened this new one as I feel the issue is bigger than just an 'enhancement'

FYI for affected users, you need to update the CSS and JS references in your HTML.

OLD:

```erb
<!-- minified -->
<link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
<script src="https://unpkg.com/swiper/js/swiper.min.js"></script>

<!-- non-minified -->
<link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.css">
<script src="https://unpkg.com/swiper/js/swiper.js"></script>
```

NEW

```erb
<!-- minified -->
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- non-minified -->
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
```

**Comment by nolimits4web** [comment]
> Is it possible to keep the old URLs alive?

No, see changelog 

https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md
