### ISSUE TITLE
Swiper doesn't work on Safari (IOS)

### ISSUE THREAD

**Issue by Nic787** [nolimits4web/swiper#3657]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0
* Platform/Target and Browser Versions: Safari IOS
* Live Link or JSFiddle/Codepen or website with isssue: http://test.nicolas-duclos.com/

### What you did
I followed the documentation to make my slides and everything works fine on all browsers except Safari on IOS and poor Internet Explorer 11, but forget about the last one. Safari is used by lot of people and the slider doesn't work at all.
```var mySwiper = new Swiper('.swiper-container', {
        // Optional parameters
        loop: true,
        speed: 1000,
        allowTouchMove:true,
        // If we need pagination
        pagination: {
          el: '.swiper-pagination',
        },
        // Navigation arrows
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        },
        //Pagination
        pagination: {
            el: '.swiper-pagination',
            type: 'bullets',
            clickable: true,
        },
        //Autoplay
        autoplay: {
            delay: 7000,
            disableOnInteraction: false,
        },
    });
```

### Expected Behavior
Slider should works like other browser.

### Actual Behavior
Only first slider is showing without pagination or navigation possibility. Something is broken somewhere, but can't find the problem.

**Comment by nolimits4web** [comment]
There is something on your side, Swiper works perfectly in Safari as you may see if you check demos with Safari https://swiperjs.com/demos/

**Comment by Yienders** [comment]
> There is something on your side, Swiper works perfectly in Safari as you may see if you check demos with Safari https://swiperjs.com/demos/

thanks
