### ISSUE TITLE
Version 6 404'in from UNPKG

### ISSUE THREAD

**Issue by ashley-plott** [nolimits4web/swiper#3659]
Seems to be version 6 is 404'in from UNPKG

**Comment by signorecello** [comment]
Also having issues with that. Using one of these solved the issue

`<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>`

Hope it helps!

**Comment by amapparat** [comment]
yes, https://unpkg.com/swiper/css/swiper.min.css is down.
I'm using this as an import in a lot of projects, all sliders broken

**Comment by nolimits4web** [comment]
What is the issue? There was a major release, which assumes braking changes. Check changelog or read the docs
