### ISSUE TITLE
Changing slides with 'loop: true' shows previous (not existing anymore) slide

### ISSUE THREAD

**Issue by tofra** [nolimits4web/swiper#3667]
The slider is showing the previous slides when `loop: true`, after changing the slides.

Situation:
I have a swiper, with just one slide, color green.
After 2 seconds I remove the green slide, and add a red and a yellow slide. A real world example is that you are loading data, and when loaded you will show it.

I expect that:
I see a red slide
swipe left -> yellow slide
swipe left -> red slide

What happens is:
I see a red slide
swipe left -> yellow slide
swipe left -> green slide
when I release, and then move the slide just a pixel to the right, it "pops" back to red, and the "next" upcoming slide on the left is green again.

See Angular stackblitz example: https://stackblitz.com/edit/ngx-useful-swiper-28yvnn

PS. ngx-useful-swiper is just a wrapper to have the swiper work in Angular. I tried with the default swiper example (https://stackblitz.com/edit/swiper-demo-1-default?&file=index.html) but that doesn't even work at stackblitz.

**Comment by tofra** [comment]
With some further investigation, I noticed that the "right" and "left" slide which are out of the screen are "remembered" and never be rebuild.
Eg: create the HTML which has 1 slide with <p>A</p> on it.
After 5 seconds (eg setTimeout()), change the HTML of the slide: remove the <p>A</p> and replace it with <p>B</p>
If you scroll you will see on the "left" and "right" slide still contains the A instead of the "new" B.

@nolimits4web Let me know if I need to make another example which describes the problem.

**Comment by venarius** [comment]
+1 having the same exact problem

**Comment by paul-git** [comment]
From the [documentation](https://swiperjs.com/api/): `mySwiper.update()`; _You should call  it after you add/remove slides manually, or after you hide/show it, or  do any custom DOM modifications with Swiper_

Does this fix your issue?

**Comment by venarius** [comment]
> From the [documentation](https://swiperjs.com/api/): `mySwiper.update()`; _You should call it after you add/remove slides manually, or after you hide/show it, or do any custom DOM modifications with Swiper_
> 
> Does this fix your issue?

Sadly not. Also not doing any modifications to the slider after it has been initialized.

**Comment by tofra** [comment]
@paul-git I've updated the example (https://stackblitz.com/edit/ngx-useful-swiper-28yvnn) so it will run the update method, but still no change in the result.

**Comment by paul-git** [comment]
Hey, I'm not on a computer right now, but I think there is a typo:
this.swiperRef.swiper.update(); should be
this.swiperRef.Swiper.update(); with capital S for Swiper. Does this fix it?

Best,
Paul

Am 24.07.2020 um 08:33 schrieb Tom Franssen:

**Comment by tofra** [comment]
No. This is `this.swiperRef`
![image](https://user-images.githubusercontent.com/1746173/88407673-bd3ded80-cdd2-11ea-815f-bb20775e3178.png)

**Comment by paul-git** [comment]
Look carefully what I wrote:
this.swiperRef.Swiper.update();
Swiper with capital S not swiperref.



Am 24.07.2020 um 11:26 schrieb Tom Franssen:

**Comment by tofra** [comment]
I saw that, but that's why I posted the screenshot of `this.swiperRef` and as you can see it has swiper there without a capital. That's the Swiper object.

**Comment by elliottregan** [comment]
I haven't dug into the source, but it doesn't look like mySwiper.update() updates all the markup; it only runs a few update functions related to Swiper's state (number of slide, active slide classes, etc.). So, if you change the markup on a slide, the previously cloned slides do not get updated.

**Comment by ygj6** [comment]
![image](https://user-images.githubusercontent.com/7699524/100497896-473efe00-3199-11eb-93ed-1cdc4b27669e.png)
Swiper.update() doesn't seem to work here.

**Comment by vltansky** [comment]
use https://swiperjs.com/angular/
