### ISSUE TITLE
React passing pagination element ref doesn't update Swiper

### ISSUE THREAD

**Issue by viters** [nolimits4web/swiper#3668]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.1
* Platform/Target and Browser Versions: macOS Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/still-field-wq1rc?file=/src/Swiper.js

### What you did
I've tried to use pagination element ref to setup pagination outside swiper-container. I am aware that `useRef` will not trigger rerender, but I've also tried to use `useState`, swiper did rerender but pagination was not rendered anyway. Moreover, I've tried to pragmatically call `pagination.update()` and `pagination.render()`, with no effect.

### Expected Behavior
Pagination appears in referenced element.

### Actual Behavior
Pagination does not update / rerender on element ref change.

**Comment by joebentaylor1995** [comment]
I also have this issue too
