### ISSUE TITLE
Swiper React: changing parameters based on component state

### ISSUE THREAD

**Issue by taze-fullstack** [nolimits4web/swiper#3669]
This is a (multiple allowed):
* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: **v6.0.1**.
* Platform/Target and Browser Versions: PC Windows + Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/old-sky-bczl8?file=/src/App.js

### What you did
Is it possible to make parameters dependent on [toggleable] state? So that:
```
const [noSwiping, setNoSwiping] = useState(false);
const [direction, setDirection] = useState("vertical");
...
<Swiper direction={direction} noSwiping={noSwiping}>
  ...
</Swiper>
```

### Expected Behavior
Swiper will update based on the changing state.

### Actual Behavior
Nothing happens.

**Comment by nolimits4web** [comment]
It is already reacts to props changes and will change direction. 

For `noSwiping` check docs, i guess it is doing not what you think https://swiperjs.com/api/#parameters

**Comment by taze-fullstack** [comment]
> It is already reacts to props changes and will change direction.
> 
> For `noSwiping` check docs, i guess it is doing not what you think https://swiperjs.com/api/#parameters

@nolimits4web It doesn't :( I updated the codesandbox to explicitly show and log component state vs. swiper.params.param
https://codesandbox.io/s/old-sky-bczl8?file=/src/App.js

Here's a loom video of the component changing the state but swiper not reflecting these changes:
https://www.loom.com/share/a6b5d826a8884634923c5fa69a731b01

**Comment by StaySharp0** [comment]
@taze-fullstack 
https://github.com/nolimits4web/swiper/issues/3668
https://github.com/nolimits4web/swiper/issues/3682
etc...

I have investigated several things for parameter reinitialization, but there seems to be no clear way.
This can also be inferred from the absence of a demonstration of the dynamic option.
The only way seems to be to destroy and reproduce the swiper.

Landering optimization is not done, but the example provided has been changed to work.
https://codesandbox.io/s/vigilant-brahmagupta-1tber?file=/src/App.js

**Comment by taze-fullstack** [comment]
@StaySharp0 thanks. it seems that swiper doesn't rebuild instantly on prop change, but conditionals can be applied to build a new one each time. My gripe with the modified example is that, when you're on slide 3 when on horizontal, and then I change noSwiping, it is fully rebuilt and displays slide 1, which doesn't fit what I need at the moment, but I guess I can re-modify your example to save existing index before there are changes on state, then reapply active index on new build but this probably (a) will produce visual flicker and (b) is performance heavy.

**Comment by austencm** [comment]
In case this helps anyone else, you can change the `key` prop to force Swiper to rerender.
