### ISSUE TITLE
Using loop mode with deep cloning slides (with data and eventListeners)

### ISSUE THREAD

**Issue by Kirigetov** [nolimits4web/swiper#3670]
* [x] enhancement

* Swiper Version: 5.4.2; (vue-awesome-swiper: 4.1.1)

I use vue-awesome-swiper - vue wrapper for swiper slider. I have slider which contains another widget in one of the slides inside. Slider must work with **loop mode**. Duplicated slides doesn't have any eventListeners which where on widget inside. 
Since the slider uses `slidesPerView: 'auto'` parameter, there is no interaction with copies of the widget.

Is it possible to use **loop mode** with deep cloning of real slides? (like JQuery.clone())

**Comment by gullerya** [comment]
Another possibility would be to actually move the slides position so that there is always prev/post slide in the strip, without cloning the DOM - which, IMHO is the correct approach, and while involves a bit more of maths, escapes an insane cloning issue.

**Comment by nolimits4web** [comment]
> Is it possible to use loop mode with deep cloning of real slides?

No

> IMHO is the correct approach

No, it is not correct and doesn't cover many cases. E.g. when you just have 2 slides and `slidesPerView: 3`

Closing, as issue related to `vue-awesome-swiper` implementation
