### ISSUE TITLE
Swiper 6.X

### ISSUE THREAD

**Issue by usb248** [nolimits4web/swiper#3671]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.X
* Platform/Target and Browser Versions: Windows, last version FF

### What you did
Before 6.X, i could import : `import _Swiper from 'swiper/js/swiper.min.js';` all worked fine
Now this script doesn't exist anymore.
I tried all bundles (ex: `swiper/bundle`). All the same error :
![image](https://user-images.githubusercontent.com/7659927/86944007-73ed6d00-c147-11ea-9524-648c8f764fc6.png)

### Expected Behavior
No error

### Actual Behavior
Script failed on the first interaction (but correctly instancied)

Please fix this, all works fine except your lib in my app after upgrading ;). All others esm/umd lib works great ... I downgrade to 5.4.5 while waiting a fix

**Comment by MDzyga** [comment]
In my case with Angular Universal 10, autoPlay option doesn't work.

**Comment by nolimits4web** [comment]
Can't replicate such issue. Would be great to see more complete example, better example on CodeSandbox/StackBlitz

**Comment by MDzyga** [comment]
This is my configuration which works with version 5.4.5

```
@ViewChild('carousel') carousel: SwiperComponent;
carouselConfig: SwiperOptions = {
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
      type: 'bullets',
    },
    speed: 500,
    preloadImages: this.isPreload,
    autoplay: true,
    on: {
      slideChange: () => {
        if (this.carousel.swiper) {
          this.carouselTemplateService.setState({ type: this.type, index: this.carousel.swiper.activeIndex });
        }
      },
    },
  };
```

and HTML

```
<swiper *ngIf="config && viewModels"
        #carousel
        [config]="carouselConfig"
        class="carousel-template">
  <div class="swiper-wrapper">
    <div *ngFor="let avatar of viewModels; let i = index"
         class="swiper-slide item cursor-pointer">
            <div [style.backgroundImage]="'url('+avatar.imageUrl+')'"
                 class="ng-lazyloaded img">
            </div>
    </div>
  </div>

  <div class="swiper-pagination"></div>
</swiper>
```

Versions:
Angular 10.0.2
Angular Universal 10.0.1
ngx-useful-swiper: 9.0.3
swiper: 5.4.5 (work), with version 6.0.1 doesn't work

**Comment by pttolev** [comment]
I am facing the same problem but I am using Vue.js with TypeScript. 
The Swiper 6.0.2 version shows the same errors and more.

I have figured out that a very basic Vue installation works.
Then I found that both instances look different.
The types of $el and $wrapperEl are different.
You can see the screenshots attached:

![swiper](https://user-images.githubusercontent.com/9511621/87152155-dbc5c400-c2bd-11ea-9075-0ca705744250.png)

Versions:
Vue.js 2.6.11
TypeScript 3.9.6

**Comment by nolimits4web** [comment]
Still need to see live example (JSFiddle, Codepen, etc.) with core Swiper (not 3rd party Vue or Angular implementations)

**Comment by usb248** [comment]
The problem seems exactly with others frameworks. your lib should be not in conflicting with @nolimits4web.

**Comment by chungmarcoo** [comment]
facing same issue when developing a simple website using vue and swiper (i.e. vue 2 from cdn, and swiper 6.x from unpkg)

Temporary solution: use swiper v5.4.5 from unpkg
