### ISSUE TITLE
Swiper 6:  Property 'progress' does not exist on type 'Element'.

### ISSUE THREAD

**Issue by vovalukashov** [nolimits4web/swiper#3675]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.X.
* Platform/Target and Browser Versions: MacOS Catalina, Chrome 83.0.4103.116 (Official Build) (64-bit).

### What you did
I use TypeScript. When I try to execute the following code for I get the error "TS2339: Property 'progress' does not exist on type 'Element'."

`swiper.slides.forEach((slide) => {
      console.log(slide.progress)
   })`

I’ll get the same if I want to change the style of a single slide

`swiper.slides.forEach((slide) => {
      slide.style.transition = '{some number}ms'
   })`

### Expected Behavior
It seems to work

### Actual Behavior
slide must not be an Element type

**Comment by nolimits4web** [comment]
Just use ` //ts-ignore ` because Swiper add `progress` property to slide element
