### ISSUE TITLE
Fullscreen parallax transitions are janky on Firefox, on UHD display

### ISSUE THREAD

**Issue by chris-ball** [nolimits4web/swiper#3676]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.2.
* Platform/Target and Browser Versions: Windows 10, Firefox 78.0.2 (64-bit), 3840x2160 @ 2dppi.
* Codepen with issue: https://codepen.io/verism/full/MWKXyYz

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

Initialised a single, full-screen slider, with parallax, as recommended by the guide:

```
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <div class="slide-inner"
                 style="background-image:url(http://placehold.it/1200x1200?text=One)"
                 data-swiper-parallax="50%"></div>
        </div>
        ...
    </div>
</div>
```

```
const swiper = new Swiper('.swiper-container', {
    speed: 1000,
    loop: true,
    parallax: true,
})
```

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

I expected (as observed on Chrome) smooth animations when transitioning between slides.

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

The animation appears very janky, I'd argue that it's pretty much unacceptable by current standards. At smaller sizes the issue disappears, but at full-screen it's highly noticeable.

**Comment by nolimits4web** [comment]
Closing as not related to Swiper. If it is slow in some browser, then you can open issue for that browser asking why it is slow
