### ISSUE TITLE
SlidesPerView doesn't works well with slidesOffsetBefore

### ISSUE THREAD

**Issue by fmcdigital** [nolimits4web/swiper#3679]
Hello, I'm uptading swiper component by calculating the windows offset, and using `slidesPerView: 5.5`

But, when resizing the window, the Slides doen't calculates the slides per view within the offset, so the last card starts disappearing...

You can see on the screen shots.

![Screen Shot 2020-07-10 at 15 36 53](https://user-images.githubusercontent.com/12851638/87187248-3f062500-c2c3-11ea-8ef2-d706e00c46f1.png)

![Screen Shot 2020-07-10 at 15 37 04](https://user-images.githubusercontent.com/12851638/87187237-39a8da80-c2c3-11ea-8a76-bf5671c96766.png)

![Screen Shot 2020-07-10 at 15 38 21](https://user-images.githubusercontent.com/12851638/87187348-6bba3c80-c2c3-11ea-96f5-80e39b27228b.png)

**Comment by drewlonious** [comment]
yes, same problem here. any idea?

**Comment by Kasey777K** [comment]
[](https://www.icloud.com/notes/0YEmBTwl_D3KdsNJowK89fclA)

**Comment by Kasey777K** [comment]
@Kasey777K

**Comment by vltansky** [comment]
@fmcdigital @drewlonious  @Kasey777K 
could you make some demo on stackblitz / codesandbox / etc.  please ?

**Comment by howells** [comment]
@fmcdigital @drewlonious @Kasey777K did you guys ever figure this out?

@vltansky I tried making a codesanbox demo, but seems there's a problem importing swiper react: https://codesandbox.io/s/fragrant-field-xg3n4

To replicate, just add a non-zero integer for `slidesPerView`, and add a `slidesOffsetBefore`: the slides won't take into account the offset.
