### ISSUE TITLE
When virtual option is used Swiper-React 6.0.x renders no slide

### ISSUE THREAD

**Issue by valnub** [nolimits4web/swiper#3683]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version:
6.0.0-alpha.10

* Platform/Target and Browser Versions:
macOS 10.15.5
Google Chrome 83.0.4103.116

* Demo
Download and extract [this zip file](https://github.com/nolimits4web/swiper/files/4908487/swiper-react-test-virtual.zip). Then do `yarn` and `yarn start`.

### What you did
Created minimal project with swiper-react and enabled virtual like this:
```jsx
<Swiper virtual>{slides}</Swiper>;
```

### Expected Behavior
Should start rendering slides.

### Actual Behavior
Does not render any slides. Swiper-wrapper is empty.

**Comment by nolimits4web** [comment]
Swiper is out of alpha for a while already. Can you provide live example, for example on https://stackblitz.com/

**Comment by valnub** [comment]
@nolimits4web Hm, weird. I upgraded to swiper 6.0.2 but still the same problem remains.

Tried to create demo app on stackblitz but getting `Import error, can't find file:
../../core`.

Link to stackblitz:
https://stackblitz.com/edit/react-af5alb

So, I uploaded the demo on my webspace:
https://timo-ernst.net/misc/swiper-react-test-virtual/

Source code on GitHub:
https://github.com/valnub/swiper-react-test-virtual

**Comment by shoespray** [comment]
same here, using reactjs

**Comment by laxman-ram-iconnect** [comment]
+same here

**Comment by Zackasaurus** [comment]
same

**Comment by nolimits4web** [comment]
You need to install Swiper's Virtual module in order to make it work:
```
import SwiperCore, { Virtual } from 'swiper';

SwiperCore.use([Virtual]);
```

**Comment by JSteunou** [comment]
@nolimits4web this is not documented, that s why so much people experiment this error :)

**Comment by valnub** [comment]
@JSteunou Looks like this was added here: https://github.com/nolimits4web/swiper-website/commit/52981e8a38eb8805279abb4c9318a78245764395
