### ISSUE TITLE
CDN filename has been updated without redirecting the old one

### ISSUE THREAD

**Issue by alfonsomatute** [nolimits4web/swiper#3684]
Hi, I know this is not the correct place, but I was using the CDN URL you offer on unpkg.com, pointing to "swiper.min.js" file and this url has been removed without redirect and changed to swiper-bundle.min.js, so all my projects has stopped working. Please, consider keeping the old file for compatibility. By the way, thank you for your great script I use a lot.

**Comment by nolimits4web** [comment]
Duplicates #3664
