### ISSUE TITLE
The arrow buttons not working in 6.0.2

### ISSUE THREAD

**Issue by wizardnet972** [nolimits4web/swiper#3686]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.2
* Platform/Target and Browser Versions: ALL
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.
https://stackblitz.com/edit/swiper-test?file=index.html

### What you did
Just write simple example of swiper as say in the docs.

### Expected Behavior
When I click the arrows, nothing happens.

### Actual Behavior
Change slides

**Comment by nolimits4web** [comment]
https://swiperjs.com/get-started/

> By default Swiper exports only core version without additional modules (like Navigation, Pagination, etc.). So you need to import and configure them too:
