### ISSUE TITLE
[v 6.0.3] swiper/react vertical direction gives SwiperSlide's height wrong?

### ISSUE THREAD

**Issue by github0013** [nolimits4web/swiper#3691]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.3
* Platform/Target and Browser Versions: Darwin mbp 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64 / Google Chrome 83.0.4103.116

* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/swiper-vertical-oktkb

### What you did
I made Swiper vertical.

### Expected Behavior
Each slide (SwiperSlide) should not have extra height.

### Actual Behavior
Each slide (SwiperSlide) gets extra height.   SwiperSlide seems to gets fixed height.

**Comment by nolimits4web** [comment]
Vertical Swiper must have some fixed CSS height, e.g. 
```
.swiper-container {
  height: 300px;
}
```

**Comment by github0013** [comment]
For the height, I was doing height prop, but it doesn't do the work?

```tsx
<Swiper height={300} 
```

And even after giving 

```css
.swiper-container {
  height: 300px;
}
```

it seems `slidesPerView={1}` is not working?

I see multiple slides sliding up at the same time.
https://codesandbox.io/s/swiper-vertical-oktkb?file=/src/App.tsx

**Comment by github0013** [comment]
I think this is somehow related to codesandbox. 
When I did this css on my local, it worked fine...

```css
.swiper-container {
  height: 300px;
}
```

**Comment by BernhardSmuts** [comment]
I set 
``
.swiper {
  height: 500px;
}
``

and that seemed to do the trick with bringing up the vertical orientation, I'm still working on the centeredSlides as well, noting working on my side yet. 

using V7.3.1 on a create-react-app build

**Comment by Lukrisum** [comment]
> I set `.swiper { height: 500px; }`
> 
> and that seemed to do the trick with bringing up the vertical orientation, I'm still working on the centeredSlides as well, noting working on my side yet.
> 
> using V7.3.1 on a create-react-app build

As we all know, `.swiper` is the common class of all `<Swiper/>`, if you use this method to specify the height of the current `<Swiper/>`, other `<Swiper/>` will also change at the same time, which is something we don't want to see. 

By the way, @nolimits4web ，I also saw the similar situation in the code of the demo in the official Swiper documentation. 
May I ask if this is an inappropriate way of writing (especially when you want to use multiple <Swiper/> in an application).  

> screenshot of similar situation in the Swiper documentation , or [check here](https://codesandbox.io/s/62rdbz?file=/src/styles.css):

![image](https://user-images.githubusercontent.com/91905983/203843981-59051561-1489-4e38-bac9-5feb10afc940.png)
