### ISSUE TITLE
[version 6.0.3] swiper/react can't find `use` method in TS project

### ISSUE THREAD

**Issue by jozsefDevs** [nolimits4web/swiper#3693]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.3
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/react-id-swiper-update-two-4irn6?file=/src/App.tsx

### What you did
Wanted to try out how to use Controller (as per the description in: https://swiperjs.com/react/#controller) with Swiper/React + React in a CRA with TS configured. 

### Expected Behavior
The example works as described in the Swiper/React page.

### Actual Behavior
Type Error: _react2.Swiper.use is not a function

Is there any way to make these imports to work in a TS project?

**Comment by nolimits4web** [comment]
It must be `SwiperCore.use(...)`

**Comment by MagicLegend** [comment]
Maybe the docs should be a little more verbose about this. Now it's written like it should be done on the `swiper` instance. Also I was unsure what to pass the function, the docs of this function should maybe also state that this should be `SwiperComponent` classes in an array, and not strings.
