### ISSUE TITLE
Autoheight and vertical mode buggy

### ISSUE THREAD

**Issue by usb248** [nolimits4web/swiper#3695]
Autoheight with vertical mode is so buggy.
![image](https://user-images.githubusercontent.com/7659927/87540078-50727700-c69f-11ea-8e88-cffa5ce9f379.png)
there is nothing in the documentation that says it doesn't work.
All slides have the same height whereas it shoudn't

This is a (multiple allowed):
* [ ] enhancement
* [x] bug
* [x] feature-discussion (RFC)

* Swiper Version: 5.4.X
* Platform/Target and Browser Versions: Win 10 - FF

### Expected Behavior
Correctly calculate translate Y length and calculate the correct height

### Actual Behavior
So buggy

**Comment by nolimits4web** [comment]
Autoheight is only for horizontal mode

**Comment by usb248** [comment]
@nolimits4web have you any workaround/solution to support this ?
Calculated maybe myself the height on the content the current slide and set the height in a callback ?

**Comment by usb248** [comment]
@nolimits4web can you make possible crossFade effect in vertical mode with autoheight ? There is visually the same thing as horizontal mode
