### ISSUE TITLE
Cannot make clickable tabs

### ISSUE THREAD

**Issue by ArthurShlain** [nolimits4web/swiper#3699]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 6.0.4
* Platform/Target and Browser Versions: Windows 10, CHROME 83.0.4103.116
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/ArtZ91/pen/XWXPGGX

### What you did
I try to make clickable tabs (slide = tab).

### Expected Behavior
I expect to see active class on clicked slide.
Need option to switch not the entire screen, but the active slide within the visible slides.

### Actual Behavior
Navigation disabled and no option to change this behavior. 
`normalizeSlideIndex` option description is very similar to this, but it's possibly not working.

**Comment by nolimits4web** [comment]
Наивный человек 😂 После того что ты написал, забудь вообще о том, чтобы сюда писать и на что-то расчитывать. Отправил на тебя репорт в GitHub

<img width="658" alt="ss" src="https://user-images.githubusercontent.com/999588/87568117-cdb4e080-c6cd-11ea-949e-e61d0a34f1c0.png">
