### ISSUE TITLE
Loop mode for "Centered Active Slide" layout. 

### ISSUE THREAD

**Issue by Denoizzed** [nolimits4web/Swiper#370]
Hi, I want to use slider in Centered mode but noticed that there is no loop mode for that layout. Theoretically, is it possible to create a loop mode for it (so last slides are prepended to the first one, just like in other modes)? 

Thanks!

**Comment by Uranbold** [comment]
Hello,

This issue is still coming ;)

How do we resolve this?

Demo -> http://themes.themewaves.com/centura/

Check the main slider and end of the loop there has an White Space is there and it comes end of the loop of slider.

Thanks.
