### ISSUE TITLE
CDN files disappeared

### ISSUE THREAD

**Issue by samuelecarpene** [nolimits4web/swiper#3701]
Hi i'm opening this issue to understand why the files
```
https://unpkg.com/swiper@6.0.4/js/swiper.min.js
https://unpkg.com/swiper@6.0.4/js/swiper.min.js
```
are disappeared from CDN.
I was using theme for multiple projects and I was forced to update them all.

Can i know the exact date when you removed these files and the reason?

Basically a cdn must keep old versions (in some cases you can make redirect when new versions are released).

**Comment by nolimits4web** [comment]
> Before you open an issue, please check if a similar issue already exists or has been closed before.
