### ISSUE TITLE
Swiper don't work anymore since 6.0.4 release

### ISSUE THREAD

**Issue by wouterdam** [nolimits4web/swiper#3702]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.4.
* Platform/Target and Browser Versions: macOS, Safari and Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://www.idd.nu/#team

### What you did
I've made this site (https://www.idd.nu/) with Webflow and use Swipe with 'custom code' (<script src="https://unpkg.com/swiper/js/swiper.min.js"></script>). A few months it works perfect, but since latest release nothing happen.
In the console I see this errors:

[Error] Failed to load resource: the server responded with a status of 404 () (swiper.min.js, line 0)
[Error] Refused to execute https://unpkg.com/swiper/js/swiper.min.js as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] ReferenceError: Can't find variable: Swiper Globale code (www.idd.nu:225)

### Expected Behavior
Swiping, automatic and/or by dragging

### Actual Behavior
Nothing

Is there a way to fix this? Thanks in advance!

**Comment by nolimits4web** [comment]
> Before you open an issue, please check if a similar issue already exists or has been closed before.
