### ISSUE TITLE
Thumbs in loop mode poorly tracking main slider

### ISSUE THREAD

**Issue by nexces** [nolimits4web/swiper#3704]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.1
* Platform/Target and Browser Versions: all
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/nexces/pen/bGEmRoM

### What you did
I've setup main slider with 8 slides and thumbs slider with 6 slides per view and 6 slides in group with loop and 
 blanks filling - codepen link provided

### Expected Behavior
I've expected that when moving from slide 6 to 7 on main slider, thumbs will transition to left revealing 2nd group of slides with slides 7&8

### Actual Behavior
When moving from slide 6 to 7 nothing happens, and when moving from slide 7 to 8 thumbs are transitioning to right.
Same happens with change from slide 8 to 1 (nothing), and moving from slide 1 to 2 - thumbs are transitioning to right.

**Comment by ygj6** [comment]
@nexces  This example is similar to your example, but there are no problems you describe.
https://github.com/nolimits4web/swiper/blob/master/demos/310-thumbs-gallery-loop.html

**Comment by nexces** [comment]
@ygj6 Indeed, however:
* I'm not using freeMode
* I'm using slidesPerView, slidesPerGroup, loopFillGroupWithBlank

And I'm pretty sure that this option combination might be responsible - it just might as simple as bad comparison ( ">" instead ">=") or something similar
