### ISSUE TITLE
Active slide updating only once if all slides are visible with "slidesPerView".

### ISSUE THREAD

**Issue by MaxVeilleuxMTL** [nolimits4web/swiper#3705]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: ALL
* Live Link or JSFiddle/Codepen or website with isssue: 
https://ivadolabs.akufen-server.ca/en/our-process/
<img width="1359" alt="swiper-all-slides-visible" src="https://user-images.githubusercontent.com/49200337/87693723-4dd55780-c75b-11ea-831d-96976a915f8c.png">

### What you did
```
this.swiper = new Swiper (this.view, {

	// Optional parameters
	autoplay: {
		delay: 4000,
	},
	speed: 1000,
	loop: false,
	slidesPerView: 1,
	allowTouchMove: false,
	watchSlidesProgress: true,
	virtualTranslate: true,
	watchSlidesVisibility: true,
	breakpoints: { 
		767: {
			 allowTouchMove: true
		},
		979: {
			 allowTouchMove: true
		},
		1024: {
			 allowTouchMove: false
		}
	},
});
```

### Expected Behavior
All I need is for swiper to update my "active" slide, without actually moving the slider.

P.S. Loop must be false, and all slides visible as you can see on the screenshot above.

### Actual Behavior
Active slide is updating only once with autoplay.

**Comment by nolimits4web** [comment]
Active slide depends ONLY on slider position. If position not changed -> active slide will be the same.

> All I need is for swiper to update my "active" slide, without actually moving the slider.

You need to implement custom solution to handle it
