### ISSUE TITLE
React - Coverflow/Flip effects are not working.

### ISSUE THREAD

**Issue by cristian-eriomenco** [nolimits4web/swiper#3707]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.4
* Platform/Target and Browser Versions: Windows,  83.0.4103.116 (Official Build) (64-bit)
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/pensive-euclid-kmlbw?file=/src/comp.js

### What you did
Tried to use the coverflow effect and the flip effect.
There are no errors in the console and none of the effects are working. Thought maybe its an issue with the styles, tried to import .less then .scss, then the minified bundle, play with the props. Nothing helped.

### Expected Behavior
Expected for the slides to have at lease some effects

### Actual Behavior
No effects are applied

**Comment by nolimits4web** [comment]
https://swiperjs.com/react/#usage

> By default Swiper React uses core version of Swiper (without any additional components). If you want to use Navitation, Pagination and other components, you have to install them first:
