### ISSUE TITLE
Swiper v6 claims "sideEffects: false" but actually HAS side effects

### ISSUE THREAD

**Issue by xumepadismal** [nolimits4web/swiper#3708]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Environment:
* Swiper Version: 6.0.4.
* Platform/Target and Browser Versions: macOS, CHROME.
* Framework: Angular 10

### What you did
Updated Swiper from 5 to 6.

### Expected Behavior
The library should work

### Actual Behavior
While the library is working perfectly locally, it is completely broken when building for Production (w/ Tree Shaking)

After some investigations I found out these side effects that are cut off by webpack:
https://github.com/nolimits4web/swiper/blob/9ed4c97717fc17ab46f62bd3fbaa39f1c96f4ae6/src/utils/dom.js#L80-L82

Adding this particular file to array of sideEffects in library's package.json solved my problem but there are other files that have similar side effects. For example, this one:
https://github.com/nolimits4web/swiper/blob/1b08355540bdda8707debfc72721c8e0a12274c2/src/swiper.js#L10-L18

...and styles mentioned in #3673 

### Possible solutions

1. I'm not sure whether it's possible to rewrite library to be **really** side effects free but it would be ideal solution of course :)
1. `sideEffects: false` in `package.json` can be considered as short-term solution to ensure everything is working fine
1. Include all such files into `sideEffects: [...]` after reviewing each source file...

**Comment by xumepadismal** [comment]
Thanks for quick response. Just tried to play around webpack and terser and can't reproduce the issue indeed.

However when I install new Angular app and integrate Swiper into it then the issue persist: Swiper just can't see any methods of dom7 ('children' is not a function)

Please don't close the issue so far. I will try to figure out whether it is Angular or Webpack is the source of problem and come back. Not sure that my knowledge will be enough to figure it out though

**Comment by nolimits4web** [comment]
Dom7 uses Array subclassing, (e.g. `class Dom7 extends Array`), not sure how Angular works but maybe it tries to add some reactivity to array, thinks it usual array and don't inherit Dom7 props properly?

Same issue with Vue (https://github.com/vuejs/vue/issues/9259) but it is solved with proposed there code snippet

**Comment by xumepadismal** [comment]
Well I created issue on angular CLI but they insist that dom.js HAS a top-level side effect. Technically it's true Webpack's definition of "side effect":

> A "side effect" is defined as code that performs a special behavior when imported, other than exposing one or more exports.

Please see [the last comment](https://github.com/angular/angular-cli/issues/18297#issuecomment-660991059) of the issue I created (already closed)

**Comment by ierehon1905** [comment]
I ran into the same issue. I made a minimal reproduction repo https://github.com/ierehon1905/swiper-minimal-repo. Hope it helps.

**Comment by valse** [comment]
Hi, I have the same problem with a Gatsby project: in the development all works fine but when I build the project the styles are excluded.
To solve it I've been adding a "fake" use of it:
```js
import style from "swiper/swiper-bundle.css"
console.log(style)
```

**Comment by gavrashenko** [comment]
`require('swiper/swiper-bundle.css');` inside webpack project can be used as temporary solution.
