### ISSUE TITLE
Initiation problem, works normal every time I resize the window

### ISSUE THREAD

**Issue by Edwin1122** [nolimits4web/swiper#3713]
This is a (multiple allowed):
* [x] bug

* Swiper Version:5.4.5
* Platform/Target and Browser Versions:  macOS, Windows CHROME
* Live Link or JSFiddle/Codepen or website with isssue: https://www.masonsoft.com/user_details?prof_id=1734254&w=preview

### What you did
I initiated like this:
$(function() {
       var mySwiper = new Swiper ('.swiper-container', {
        loop: false,
        autoplay:false,
        autoHeight: true,
        delay: 5000,
        pagination:{
            el: '.swiper-pagination',
            clickable:true,
            type: 'custom',
            renderCustom:function(swiper,current,total){
                  var customPaginationHtml = ""; 
                console.log(current)
                  for(var i = 0; i < total; i++) { 
                   if(i == (current - 1)) { 
                   customPaginationHtml += '<span class ="circleBox"><span class="swiper-pagination-bullet swiper-pagination-bullet-active""></span><span></span></span>'; 
                   } else { 
                   customPaginationHtml += '<span class="swiper-pagination-bullet"></span>'; 
                   } 
                  } 
                  return customPaginationHtml; 
            }
        }
    });  
 });

### Expected Behavior
Show pagination bar, no loop.

### Actual Behavior
The pagination bar not show, and the swipe logic is wrong(loop is open), Every time I resize the window, it becomes normal.

**Comment by nolimits4web** [comment]
> Every time I resize the window, it becomes normal

It means that on moment of initialization Swiper container was hidden or had 0 size
