### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by adamjw3** [nolimits4web/swiper#3718]
```
    mySwiper = new Swiper(".js-collection-slider", {
      // Optional parameters
      observer: true,
      observeParents: true,
      slidesPerView: 3.5,
      loop: false,
      lazy: true,
      // Responsive breakpoints
      breakpoints: {
        // when window width is >= 320px
        320: {
          slidesPerView: 2.2,
          spaceBetween: 10,
        },
        768: {
          slidesPerView: 3.5,
          spaceBetween: 20,
        },
        // when window width is >= 640px
        992: {
          slidesPerView: 4.5,
          spaceBetween: 20,
          slidesOffsetBefore: offset,
        },
      },

      fadeEffect: {
        crossFade: true,
      },

      // Navigation arrows
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
        hideOnClick: true,
      },

      // And if we need scrollbar
      scrollbar: {
        el: ".swiper-scrollbar",
        draggable: true,
        hide: false,
        dragSize: 40,
      },
      on: {
        resize: function () {
          offset = $(".c-navbar__brand-link").offset().left;
          mySwiper.update(true);
        },
      },
    });
```

I have two instances of the slider on my page using the same code, when calling  mySwiper.update(true) i get the following error

Uncaught TypeError: e.update is not a function
    at t.<anonymous> (site.min.js?v=17608386537194063032:1)
    at Function.each (jquery.min.js:2)
    at t.resize (site.min.js?v=17608386537194063032:1)
    at swiper-bundle.min.js?v=15223073478888129480:1124
    at Array.forEach (<anonymous>)
    at swiper-bundle.min.js?v=15223073478888129480:1123
    at Array.forEach (<anonymous>)
    at t.emit (swiper-bundle.min.js?v=15223073478888129480:1117)
    at resizeHandler (swiper-bundle.min.js?v=15223073478888129480:2225)

**Comment by nolimits4web** [comment]
If you have more than on Swiper it returns array with swiper instances (and array apparently doesn't have `update` method)
