### ISSUE TITLE
HTML misalignment due to 3d perspective when using SwiperJS on a WebKit browser (Safari)

### ISSUE THREAD

**Issue by uncvrd** [nolimits4web/swiper#3721]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 6.0.4.
* Platform/Target and Browser Versions: Safari (Web or Mobile).
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/red-microservice-n9oqj?file=/index.html

^^ make sure to open on a WebKit browser!!

### What you did
I've discovered an issue when using the Swiper component within a WebKit browser such as Safari (on mobile or desktop). Even though the elements are displayed properly, their actual "clickable" areas have shifted due to the perspective css class added on `swiper-container-3d`. Here's a quick video showing the problem:

Link: https://streamable.com/rovnnn

Timestamps:

**0:00 to 0:12** shows misaligned clickable button element

**0:12 to 0:20** removing perspective on parent element

**0:20 to END** showing the fixed element is now clickable across the entire button

I have no issues here when running it on Chrome.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/25097099/88322778-0e1bec00-ccd6-11ea-9a39-e505025044d6.png)

**Comment by nolimits4web** [comment]
This is a Safari bug (or feature)

**Comment by uncvrd** [comment]
@nolimits4web any suggestions on a workaround then that doesn't break swiper?

**Comment by sergeyOrokon** [comment]
+1 
Do you have any suggestions on a workaround? Please help me.
