### ISSUE TITLE
Assign controller after initialization in v6.0.4 doesn't work

### ISSUE THREAD

**Issue by mob8607** [nolimits4web/swiper#3722]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.4.
* Platform/Target and Browser Versions: Chrome 84

### What you did
I have two Swipers which are connected to each other. In v5.4.5 we did it like this:
```
gallerySwiper = new Swiper(this.$refs.gallery, galleryOptions);
thumbsSwiper = new Swiper(this.$refs.thumbnails, thumbnailOptions);

gallerySwiper.controller.control = this.thumbsSwiper;
thumbsSwiper.controller.control = this.gallerySwiper;
```

### Expected Behavior
Swipers should work and control each other.

### Actual Behavior
The Swipers are not connected to each other and the controls don't work for the gallery swiper. Console shows an error message that there is no `controller` object on the Swiper instance.

There was a similar issue in an older version, but it looks like this has changed again.
https://github.com/nolimits4web/swiper/issues/2725

**Comment by nolimits4web** [comment]
https://swiperjs.com/get-started/

> By default Swiper exports only core version without additional modules (like Navigation, Pagination, etc.). So you need to import and configure them too

**Comment by mob8607** [comment]
Ah, sorry i missed that. Thank you very much!
