### ISSUE TITLE
Mousewheel not working

### ISSUE THREAD

**Issue by CapablancaYEHA** [nolimits4web/swiper#3723]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 6.0.4
* Platform/Target and Browser Versions: Windows, Latest Chrome, React, Gatsby

### What you did
I try to at least re-create Mousewheel Control from Demo page - not working

I cannot re-produce Mousewheel control from your demo Page in any way.
This prop does not work with Gatsby or Webpack.

Help?

**Comment by nolimits4web** [comment]
https://swiperjs.com/react/

> By default Swiper React uses core version of Swiper (without any additional components). If you want to use Navitation, Pagination and other components, you have to install them first

**Comment by CapablancaYEHA** [comment]
@nolimits4web Jesus!
Thank you very much!
But i gotta tell current API Doc is a little misleading, i didnt see that Link - its poorly highlighted and i really though i can work with all the info on /React page only - not to go into some Custom JS build sections where that is explaned

Excuse me please!
Bit again, that is not very obvious
