### ISSUE TITLE
Undefined variable: "$colors" in pagination.less and navigation.less

### ISSUE THREAD

**Issue by stevenhales** [nolimits4web/swiper#3724]
I see there was recently the exact same issue with the scss version of these files. From the fixes, it was needed to include the vars at the head of the files. It seems that the less versions were not updated with the fix.

The SCSS issue: https://github.com/nolimits4web/swiper/issues/3653

**Comment by Lumen27** [comment]
Same issue

**Comment by lbjlsy** [comment]
Same issue
