### ISSUE TITLE
Swiper not transitioning using Touchscreen on Windows 10 in Chrome.

### ISSUE THREAD

**Issue by pmascis** [nolimits4web/swiper#3728]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version:  6.0.4
* Platform/Target and Browser Versions: 
Windows 10. Touch Screen (Dell XPS 15). Chrome Version 84.0.4147.89

### What you did
Attempt to change slides using a touch screen in Windows 10 in Chrome.

### Expected Behavior
Slider should translate to the next slide.

### Actual Behavior
Swiper does not change between slides.
When the screen is first touched to swipe a direction it immediate appears to start to transition but then gets stuck in place mid transition.
Moving the mouse over the slider then transitions the slides left / right as if the mouse button is being held down.

I don't believe this is an issue specific to my project as this issue can also be replicated using the top swiper on https://swiperjs.com/

**Note:**
Works in Firefox 78.0.2 
This wasn't an issue in my old 5.2.1 version.

**Comment by pixelplant** [comment]
Same problem in Chrome, on Windows 10, on a Lenovo Yoga 920 with touchscreen.
We just switched from the latest v4 to 6.0.4 and discovered this bug.

**Comment by nbiada** [comment]
Same problem on big touchscreen (totem) based on Windows 10 with Chrome.
Same problem on Surface (Chrome & Edge Chromium).

**Comment by andrey-yumasoft** [comment]
I've managed to find a workaround:

Set _simulateTouch = false_ in config
Then subscribe to _touchStart_ event with a listener like this:

```
 onSwiperTouchStart($event:any) {
    $event.preventDefault();
  }
```

**Comment by lyhlg** [comment]
thanks for your comment. It is works for me.😬

**Comment by pmascis** [comment]
Thanks @andrey-yumasoft, that's not bad.
Unfortunately implementing this still has the problem of one working whilst the other doesn't. 
i.e. Now I can't click/drag my mouse to move between slides anymore.

@nolimits4web 
Any ideas? Are you able to assist, thanks!
I think this may be the same issue as #3772 

On a side note, I didn't know about overscroll-behavior, that is great thanks :)

**Comment by matadorhernan** [comment]
> Thanks @andrey-yumasoft, that's not bad.
> Unfortunately implementing this still has the problem of one working whilst the other doesn't.
> i.e. Now I can't click/drag my mouse to move between slides anymore.
> 
> @nolimits4web
> Any ideas? Are you able to assist, thanks!
> I think this may be the same issue as #3772
> 
> On a side note, I didn't know about overscroll-behavior, that is great thanks :)

you need to fall back to a 5.3 release and it will be back to normal

**Comment by paultuckey** [comment]
Same problem for me.  On Windows Edge 86 "mouse click and drag" works, however "finger on the touchscreen" did not.
 
After some debugging I noticed that the `pointermove` and `pointerup` events weren't being fired, to fix I added ` touch-action: none` to ensure the browser does not capture those events: 

```
    .swiper-slide {
        touch-action: none;
    }
```
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by pmascis** [comment]
Doing a quick test by adding that within Chrome dev tools on swiper.js.com home page seems to work for me. I will test fully with my previous project a bit later on.
Thanks @paultuckey !

**Comment by mathijshendrikx** [comment]
@paultuckey this fixes it partially. You are no longer able to scroll up and down a page if your touch event starts on a swiper instance.

**Comment by paultuckey** [comment]
@mathijshendrikx this is a problem for my code also.  I was able to fix it by adding `touch-action: pan-y;` to the `div` inside my `.swiper-slide` that allowed vertical scrolling.

**Comment by wbbhacker** [comment]
I combined the results of the people above and it worked

**Comment by MalekSmida** [comment]
> @mathijshendrikx this is a problem for my code also. I was able to fix it by adding `touch-action: pan-y;` to the `div` inside my `.swiper-slide` that allowed vertical scrolling.

This works perfectly for me! thank you

**Comment by DmitryUvarov** [comment]
Hi. Today I faced this problem. The solution below did not fully help me, as the vertical scrolling of the page in the slider area disappeared. **Version
9.0.4**

Rolled back to the old version bug disappeared. **Version
8.4.7**

**Comment by mialdi98** [comment]
Hello everyone, I hope it's similar to an issue that I faced on Swiper Version 10.2.0 using IOS Safari.
When I was swiping left/right it was generating small shifts to the top and it caused problems in swiping.
The code above helped a little but did not resolve the issue completely, so this is my code to resolve an issue:


``` js
const swiperBefore = new Swiper(".swiper", {
  effect: "coverflow",
  loop: true,
  grabCursor: true,
  centeredSlides: true,
  slidesPerView: "auto",
  initialSlide: 2,
  coverflowEffect: {
    rotate: 0,
  },
});

// Workaround start.
const mainWrappers = document.querySelectorAll('html, body');
function swiperTouchStart(swiper, event) {
  mainWrappers.forEach((wrapper) => {
    wrapper.style.overflow = "hidden";
  });
}
function swiperTouchEnd(swiper, event) {
  mainWrappers.forEach((wrapper) => {
    wrapper.style.overflow = null;
  });
}
swiper.on('touchStart', swiperTouchStart);
swiper.on('touchEnd', swiperTouchEnd);
// Workaround end.
```

**Comment by seopei** [comment]
> @mathijshendrikx this is a problem for my code also. I was able to fix it by adding `touch-action: pan-y;` to the `div` inside my `.swiper-slide` that allowed vertical scrolling.

Works for me with     "swiper": "^10.2.0"
