### ISSUE TITLE
Control two instances with different option loop

### ISSUE THREAD

**Issue by iforcode** [nolimits4web/swiper#3730]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.4.
* Platform/Target and Browser Versions: ALL.
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/7wa109z2/ or in https://stackoverflow.com/questions/63096486/swiper-js-control-two-instances-with-different-option-loop.

### What you did
I try to make a slider with thumb. But i want my slider is loop=true and my thumb is loop=false. Here is my setting

`var galleryTop = new Swiper('.gallery-top', {`
`	spaceBetween: 10,`
`	navigation: {`
`		nextEl: '.swiper-button-next',`
`		prevEl: '.swiper-button-prev',`
`	},`
`	loop: true`
`});`

`var galleryThumbs = new Swiper('.gallery-thumbs', {`
`	spaceBetween: 10,`
`	centeredSlides: true,`
`	slidesPerView: 'auto',`
`	touchRatio: 0.2,`
`	slideToClickedSlide: true`
`});`

`galleryTop.controller.control = galleryThumbs;`
`galleryThumbs.controller.control = galleryTop;`

### Behavior and suggested improvement
It not working well, my slider and my thumb is not show correct. Ex: when i swipe my slide from 1 to 2 then my thumb show 3.

**Comment by 2silver** [comment]
I can confirm this 👍

**Comment by ygj6** [comment]
I tried to play with it, that's what I get:
https://jsfiddle.net/5hvndmxg/33/

Is it works as you wanted @iforcode ?
