### ISSUE TITLE
Add event emitter if slide in viewport

### ISSUE THREAD

**Issue by ddtch** [nolimits4web/swiper#3731]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 5.4.5 commit: 3d12d5248bd125305f4ceeca5683719dc67bce8cE
* Platform/Target and Browser Versions: CORDOVA, IOS, ANDROID, CHROME.

Hello guys, how do you think would it be useful to add a feature like live checking if a slide in the viewport with threshold option. 

I use swiper with ionic and in my app, I'm now trying to add this option. A good example is Instagram and tik-tok when we sliding feed and the previous video stops playing and the new one starts.

**Comment by nolimits4web** [comment]
You can use `slideChange` event to detect and handle this case
