### ISSUE TITLE
mousewheel and pagination property isn't working

### ISSUE THREAD

**Issue by akshaybosamiya** [nolimits4web/swiper#3732]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.4.
* Platform/Target and Browser Versions: CHROME
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/mousewheel-control-example-p1r1b

### Expected Behavior
Mousewheel should work. Pagination shoudn't be disappear. 

### Actual Behavior
Upgrading version of swiper from 5.4.2 to 6.0.4 it stops working.

**Comment by nolimits4web** [comment]
> Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by akshaybosamiya** [comment]
> > Before you open an issue, please check if a similar issue already exists or has been closed before.

@nolimits4web Can you please refer the existing issue? I tried to go through the list. I didn't find it somehow. 

Thanks.

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/3723
