### ISSUE TITLE
Bug: l.children is not a function when building an angular project using --prod option

### ISSUE THREAD

**Issue by AXeL-dev** [nolimits4web/swiper#3733]
This is a:
* [x] bug

* Swiper Version: 6.0.4.
* Platform/Target: Ubuntu 18.04.
* Browser Versions: Chrome, Firefox (latest).
* Angular version: 9.1.9.

### What you did

I created an angular project & applied instructions from [Getting Started With Swiper](https://swiperjs.com/get-started/) (using option **c. Install from NPM**).

Then, i added a simple image slider (from the same example in the getting started page). Till here everything worked just fine, i was able to `ng serve` or `ng build` my project without any issues. The problem shows when i compile the project using `ng build --prod` for production use & try to launch my app.

### Expected Behavior
Having a working slider like when using `ng serve`.

### Actual Behavior
The slider shows, but doesn't seems to be initialised (no pagination & no working arrows) + I keep getting the `l.children is not a function` error on my browser console.

![image](https://user-images.githubusercontent.com/30635693/88720118-41b6a600-d11c-11ea-8501-ec5b02b2c384.png)

### My troubleshoot
After spending some hours trying a different approach like using the [ngx-useful-swiper](https://www.npmjs.com/package/ngx-useful-swiper) wrapper for Angular, which gave me the same error, i concluded that the error was related to Swiper itself & tried to troubleshoot it & finally ended up on to the following part of code:

https://github.com/nolimits4web/swiper/blob/3d83e7f4b6fc743759adbb6def36382ac0c26933/src/components/core/core-class.js#L139-L145

One of the `.children` calls is responsible of the console error, but i couldn't go further than that 'cause i didn't feel comfortable with that way of troubleshooting which seems like swimming in a huge sea without knowing the way out :sweat_smile:.

### My workaround
It seems like downgrading Swiper to version `5.4.5` fixes the issue & so i did in the end. But i just wanted to report that since i didn't find any similar issues on this repository.

**Comment by Sebiworld** [comment]
Oh wow, thank you @AXeL-dev for this workaround. I've spend hours looking at this error.

I get the same error working with:
- Swiper Version: 6.0.4.
- Platform/Target: MacOS 10.15.5
- Browser Versions: Chrome, Safari, MobileSafari under iOS
- Angular version: 8.2.14.

Like Axel said, only in production-mode. A regular dev-build works fine. Downgrading to version 5 fixed it for the moment.

**Comment by nolimits4web** [comment]
Duplicate #3708

**Comment by SoYoung210** [comment]
Why does this issue overlap with #3708 ? For css, sideEffect: true doesn't work. Are there any settings that need to be made when using swiper to create an npm package and use it in a service that uses it? @nolimits4web

**Comment by SoYoung210** [comment]
Oh no. I misunderstood it, and when I applied the settings, it works fine. What is the relationship between l.children and the solution?
