### ISSUE TITLE
Swiper 6 loses imported CSS when built in production environment.

### ISSUE THREAD

**Issue by syberon** [nolimits4web/swiper#3734]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.4
* Webpack Version: 4.44.0
* Platform/Target and Browser Versions: Windows

### What you did
I trying to build (production environment) my Webpack project with Swiper 6.

Simple cofiguration and source code to reproduce this bug is attached to this message.

I have a project module that uses Swiper:

**webpack config:**
```
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: {
        'main': './main.js',
    },
    resolve: {
        modules: [
            path.resolve(__dirname, './src/'),
            path.resolve(__dirname, './node_modules/'),
        ],
    },

    context: path.resolve(__dirname, './src/'),
    module: {
        rules: [
            {
                test: /\.(css)$/,
                use: [
                    'style-loader',
                    'css-loader'
                ]
            }
        ]
    }
};

```

**module source:**
```
import Swiper from 'swiper';
import 'swiper/swiper-bundle.css';

window.addEventListener('load', function() {
    new Swiper ('.top-slider', {});
});
```

If i trying to build this project in development environment `npm run dev` then i got normal compiled module on output with imported css built-in. 

If i trying to build project in production environment `npm run build` then i got compiled module but the imported css is missing inside it.

The project normally compiles with built-in CSS with Swiper 5.x and the problem appear only in Swiper 6.x

[test_config.zip](https://github.com/nolimits4web/swiper/files/4992435/test_config.zip)

### Expected Behavior
Expecting the compiled module with imported CSS built-in.

### Actual Behavior
When i build project in production environment `npm run build` then i got compiled module but the imported css is missing inside it.

**Comment by EveryOneTesla** [comment]
same to me

**Comment by nolimits4web** [comment]
Duplicate #3708
