### ISSUE TITLE
Undefined variable: "$colors" in pagination.less and navigation.less

### ISSUE THREAD

**Issue by stevenhales** [nolimits4web/swiper#3737]
Previously closed issue has not resolved:
https://github.com/nolimits4web/swiper/commit/3d83e7f4b6fc743759adbb6def36382ac0c26933

Still receiving the same error with fresh removal and adding back of package:

```
.navigation-color-loop(@ruleset) when (length( @colors ) >= 1) {
                                             ^
Variable @colors is undefined
```

Thanks

**Comment by nolimits4web** [comment]
> Previously closed issue has not resolved

Because it wasn't released yet
