### ISSUE TITLE
Api docs on breakpoint parameter are not correct

### ISSUE THREAD

**Issue by juergengenser** [nolimits4web/swiper#3738]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.4

### What you did
set up a slider with different breakpoint settings

### Expected Behavior
Breakpoints to be calculated via min-width media query as stated in the documentation

### Actual Behavior
Breakpoints are apparently calculated per max-width media query

**Comment by nolimits4web** [comment]
Example?

**Comment by juergengenser** [comment]
would still have to set up an example but am I basically wrong here? is min-width still correct?

**Comment by nolimits4web** [comment]
All works correctly as stated in docs, you can see it in this demo https://swiperjs.com/demos/380-responsive-breakpoints.html

**Comment by juergengenser** [comment]
my bad! my viewport meta tag was wrong - that was apparently causing this behaviour!
