### ISSUE TITLE
Swiper not showing in Gatsby's production build

### ISSUE THREAD

**Issue by diego3799** [nolimits4web/swiper#3740]
* [x] bug

* Swiper Version: ^6.0.4
* Platform/Target and Browser Versions: Ubuntu 20.04 LTS, Chrome

### What you did
I'm develiping  Gatsby site and using Swiper. Everything works nice in development. But after running gatsby build and gatsby serve the swiper dosen't show up. I don't know what's happening.
```
<Swiper
        effect="coverflow"
        slidesPerView={"auto"}
        css={css`
          height: 450px;
        `}
        loop
        spaceBetween={30}
        coverflowEffect={{
          rotate: 50,
          stretch: 30,
          depth: 50,
          modifier: 1,
          slideShadows: false,
        }}
        centeredSlides
        pagination
      >
        {nodes.map(({ titulo, descripcion, imagen: { fluid } }) => (
          <SwiperSlide key={titulo} className="max-w-md">
            <div className="shadow-lg max-w-xs mx-auto mt-5 bg-white ">
              <Image className="w-full " fluid={fluid} />
              <div className="px-6 py-4">
                <h2 className="font-bold text-lg mb-4 font-openSans">
                  {titulo}
                </h2>
                <p className="text-gray-700 text-base leading-normal text-left">
                  {descripcion}
                </p>
              </div>
            </div>
          </SwiperSlide>
        ))}
      </Swiper>
```

### Expected Behavior
This is a development SS.
![image](https://user-images.githubusercontent.com/43474408/88992789-d995ca80-d2a9-11ea-9a78-8b4c25063d3e.png)

### Actual Behavior
I doesn't show anything.

**Comment by diego3799** [comment]
I solved by coping and pasting all the css of the swiper-bundel.css into my own stylesheet, I dont think thats expected behavior. But if any of u run into this problem you can do that.

**Comment by nolimits4web** [comment]
Same as #3708
