### ISSUE TITLE
Last slide can't get activeIndex if slidesPerView: 'auto' when slide width is not 100%

### ISSUE THREAD

**Issue by WhitePrestige** [nolimits4web/swiper#3741]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.5.
* Platform/Target and Browser Versions: IOS, ANDROID, CHROME.

I have to make a slider with pagination, because default pagination styles don't suit me, I use API _activeIndex_ to get the index of the current slide and display in pagination, also I need the slides to be 85% of wrapper width and the last slide was aligned to the right border of wrapper. I faced the problem that the index is not calculated on the width less 100%. 

```
                this.swiper = new Swiper('.swiper-container', {
			direction: 	'horizontal',
			spaceBetween: 8,
			slidesPerView: 'auto',
		});

                   this.swiper.on('slideChange', () => {
			this.paginationUpdate();
		   });
                }

        paginationUpdate() {
		this.activeSlideNumber = this.swiper.activeIndex + 1
                // this.activeSlideNumber it is value of prop which I send to my custom pagination component
	}
```

**Comment by ygj6** [comment]
@WhitePrestige Could you provide the test code with bugs?

**Comment by iMakedonsky** [comment]
Same issue. Last slides navigation with `slidesPerView='auto'` doesn't work.
I added activeSlideClass to display what's currently active. 
Video: https://gyazo.com/f7bfbe1f1cd202445105d490c87696c0

**Comment by WeHaveBOOST** [comment]
fix this please
