### ISSUE TITLE
Issue with swiper.slideto() function 

### ISSUE THREAD

**Issue by hassannadeem97** [nolimits4web/swiper#3746]
I am trying to use swiper.slideTo() function as a way to display a certain slide when a certain hyperlink within a div is clicked on but the swiper.slideTo() function stops working when I display two different sliders in the same HTML file.

**Comment by ygj6** [comment]
@hassannadeem97 Could you provide the test code with bugs?

**Comment by hassannadeem97** [comment]
@ygj6 Nevermind, I was not implementing it properly.

**Comment by ygj6** [comment]
so,I think issue can be closed?

**Comment by hassannadeem97** [comment]
yes
