### ISSUE TITLE
use swiperJs in Next.js

### ISSUE THREAD

**Issue by MohammadPCh** [nolimits4web/swiper#3749]
This is a:
* [x] bug

* Swiper Version: 6.1.1
* Platform/Target and Browser Versions: Next.js  9.5.1

### What you did
I update Next.js  from 9.4.4 to 9.5.1 and Swiper.js from 6.0.4 to 6.1.1

### Expected Behavior
Working without any issue.

### Actual Behavior
I have a warning in server side:
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
    in SwiperSlide (at carousel.tsx:44)

**Comment by valse** [comment]
I have the same issue (with the same versions) on development: if I build the project all works fine

**Comment by tpperez** [comment]
same here... by now, it's only a terminal warning.
