### ISSUE TITLE
SSR + Next.JS 'react' does not contain a default export

### ISSUE THREAD

**Issue by oeduardoal** [nolimits4web/swiper#3759]
In a project with Next.js a getting this error: 'react' does not contain a default export

This is a (multiple allowed):
* [x] bug

* Swiper Version:
```
└── swiper@6.1.1
└── next@9.3.6
└── react@16.13.1
```
* Platform/Target and Browser Versions: Chrome - SSR with Next.js

### What you did
```jsx
// Carousel.js

import React, { Children } from 'react'
import { Swiper, SwiperSlide } from 'swiper/react'

const Carousel = props => {
  const childrens = Children?.map(props.children, child => <SwiperSlide>{child}</SwiperSlide>)

  return <Swiper>{childrens}</Swiper>
}

export default Carousel
```

```jsx
      <Carousel>
        {banners.map((banner, index) => (
          <Banner banner={banner} key={index} />
        ))}
      </Carousel>
```

### Expected Behavior
Render correctly Swiper Component

### Actual Behavior
![image](https://user-images.githubusercontent.com/12778450/89803954-e4522a00-db09-11ea-99ad-9ed618dbd325.png)

<img width="400" alt="Screen Shot 2020-08-10 at 12 57 39" src="https://user-images.githubusercontent.com/12778450/89803280-fa131f80-db08-11ea-968d-886865c8ba95.png">

<img width="400" alt="Screen Shot 2020-08-10 at 12 57 39" src="https://user-images.githubusercontent.com/12778450/89803361-1c0ca200-db09-11ea-96a7-d498526b6918.png">

**Comment by oeduardoal** [comment]
My `.babelrc` file

```
{
  "presets": ["next/babel"]
}

```

**Comment by nolimits4web** [comment]
I would assume something is wrong with your env, as it just does `import React from 'react'`

**Comment by goongoguma** [comment]
Did you find warning saying 
```
useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. 
```
as well?
