### ISSUE TITLE
6.1.2 Release

### ISSUE THREAD

**Issue by Sydney-o9** [nolimits4web/swiper#3761]
Hi Team,

This [commit](https://github.com/nolimits4web/swiper/commit/0f13b59644dbe12a975ace7fbc5d78b5629a0c42) fixes some great issues when using `NextJS`, is there an ETA for the next tagged `6.1.2` release?

**Comment by Sydney-o9** [comment]
Hi Team, do you think you can tag a new release please? 🙏 🙏

**Comment by nolimits4web** [comment]
6.1.2 released
