### ISSUE TITLE
Cannot build with vitejs

### ISSUE THREAD

**Issue by stephanedemotte** [nolimits4web/swiper#3763]
* [x] bug
* Swiper Version:  ^6.1.1
* Platform/Target and Browser Versions: Linux ubuntu

### What you did

Create a fresh [vitejs](https://github.com/vitejs/vite) app
```
$ yarn create vite-app <project-name>
$ cd <project-name>
$ yarn
$ yarn dev
```

add swiper `yarn add swiper`

Go to `App.vue` and simply load and call swiper
```
import { Swiper } from 'swiper'
console.log(Swiper)
```

Try to build `yarn build`

### Expected Behavior

Build without error

### Actual Behavior

Build throw an error

<img width="1277" alt="Screen Shot 2020-08-11 at 11 49 25 AM" src="https://user-images.githubusercontent.com/2158130/89918997-bc75cb80-dbc8-11ea-97a7-f9bab1230c4f.png">

No problem with `yarn dev`

**Comment by nolimits4web** [comment]
It works with webpack and rollup.  I guess issue is on vite side, open issue there
