### ISSUE TITLE
Next.js ssr with Swiper-reat warning issue.

### ISSUE THREAD

**Issue by goongoguma** [nolimits4web/swiper#3769]
First of all, thank you for making this awesome library. It really helps me to save a lot of time.
I am using swiper-react(v. 6.1.1) with Next.js(v. 9.5.1) and found following warning in my terminal

**Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.**

I googled the issue and found out that this is something to do with Next.js ssr behavior and useLayoutEffect.

I changed useLayoutEffect hook to useEffect hook in swiper-slide.js in node_module like this below.

```
  (0, _react.useEffect)(function () {
    if (externalRef) {
      externalRef.current = slideElRef.current;
    }

    if (!slideElRef.current || !swiper) return;

    if (swiper.destroyed) {
      if (slideClasses !== 'swiper-slide') {
        setSlideClasses('swiper-slide');
      }

      return;
    }
```
Now the warning is gone but I don't understand why exactly this is happening.
Could this be a bug that should be fixed?

**Comment by nolimits4web** [comment]
1. It is just a warning
2. Update to 6.1.2 where its is fixed
