### ISSUE TITLE
paginationBulletMessage does not work as expected

### ISSUE THREAD

**Issue by anneke** [nolimits4web/swiper#3773]
Hi there,

thank you for your work on this slider! I encountered a bug that got a little in my way today.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.1.2
* Platform/Target and Browser Versions: all
* Live Link or JSFiddle/Codepen or website with isssue: I do not have a link, but I hope to explain the case clearly below 

### What you did
I load the Swiper script the page's head, and then set the settings for the slider in a external script that I load at the end of my HTML file. 

## Expected behaviour
When I try to set `paginationBulletMessage` to a value like `Ga naar slide {{ index }}`, as is suggested in the API documentation, I expect the bullet to get an aria-label with `Ga naar slide 1` (for slide number 1), and the right number for each slide.

## What happens
The rendering of the slider changes the aria-label of the bullet element to `Ga naar slide `.

## What I tried
I tried to use `Ga naar slide { index }`, even though this is not what the API docs say, because I thought I saw a filter in the javascript. Unfortunately neither works. This leads me to believe this is a bug :)

**Comment by nolimits4web** [comment]
`Ga naar slide {{ index }}` is not a valid value, it should be `Ga naar slide {{index}}`
