### ISSUE TITLE
lazy-load cann't work correctly

### ISSUE THREAD

**Issue by paultyh** [nolimits4web/swiper#3778]
This is a bug.

* Swiper Version: 6.1.2.
* Platform and Browser Versions: Windows->Chrome.

### What you did
I create a lazy-loaded img ,
```
<img className={'swiper-lazy'} data-src={'XX'}>
```
when DOM has been rendered, lazy-load component cann't work correctly.

### Expected Behavior
Img's className should change to 'swiper-loaded', and it's data-src changes to src. 

### Actual Behavior
className and data-src couldn't change absolutely after rendered.

**Comment by ygj6** [comment]
@paultyh Could you please provide the complete test code with JSFiddle, CodeSandbox, etc?
