### ISSUE TITLE
renderExternal() not firing

### ISSUE THREAD

**Issue by stefanholzapfel** [nolimits4web/swiper#3781]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: >= 6.0.0
* Platform/Target and Browser Versions: Chrome 84.0.4147.135 on Windows 10

### What you did
Updated from Version 5.x to 6.x

### Expected Behavior
Virtual scroll callback "renderExternal()" to fire.

### Actual Behavior
renderExternal is not firing anymore after updating from 5.x to a version >= 6.0.0

My swiper inititilization looks like this (didn't change that, just updated from 5.x to 6):

```
this.swiper = new Swiper(
                    this.shadowRoot.querySelector('.swiper-container') as HTMLElement,
                    {
                        initialSlide: 0,
                        watchOverflow: true,
                        navigation:
                            {
                                nextEl: this.shadowRoot.querySelector('.swiper-button-next') as HTMLElement,
                                prevEl: this.shadowRoot.querySelector('.swiper-button-prev') as HTMLElement,
                                disabledClass: 'swiper-button-disabled',
                                hiddenClass: 'no-swiper-button'
                            },
                        slidesPerView: 1,
                        on: {
                            slideChange: () => {
                                
                            }
                        },
                        virtual: {
                            slides: this.swiperSpots,
                            renderExternal: (data: VirtualData) => {
                                this.virtualData = data;
                            },
                            addSlidesBefore: 4,
                            addSlidesAfter: 4
                        }
                    }
                );
```

It was working as expected before Upgrade. When downgrading swiper back to 5.x, renderExternal is working again.

Thank you!

**Comment by nolimits4web** [comment]
Make sure you are using bundle version of Swiper or you need to install Virtual component if you use core version (which v6 uses by default)

**Comment by stefanholzapfel** [comment]
Thank you.

For anybody else not finding it in the manual:

Use the static "use" method on Swiper to provide the virtual component:

Swiper.use([Virtual]);
