### ISSUE TITLE
Fade effect and navigation buttons not working at version 6.1.2

### ISSUE THREAD

**Issue by florianrubel** [nolimits4web/swiper#3784]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.1.2
* Platform/Target and Browser Versions: Dedicated to browser or operating system.
* Live Link or JSFiddle/Codepen or website with isssue: Update one of the demos to use version 6. They all use version 5.

### What you did
I updated to version 6 from 5. Configuration is good.

### Expected Behavior
Navigation buttons (prev, next) work and fade effekt works.

### Actual Behavior
Fade effect is not working. The default effect is used. The navigation buttons don't work at all.

```html
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide" v-for="{title, files} in versions">
            <div class="swiper-slide-title" v-if="title">{{title}}</div>
            <img class="swiper-slide-image" v-for="file in files" :src="getFullUrl(file)"/>
        </div>
    </div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
</div>
```

```js
this.swiperInstance = new Swiper('.swiper-container', {
    autoHeight: false,
    effect: 'fade',
    loop: true,
    navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
    },
    on: {
        slideChange: () => {
            let activePaginationItem = document.querySelector('.pagination__item--active');
            if(activePaginationItem) {
                document.querySelector('.pagination').scrollLeft = activePaginationItem.offsetLeft;
            }
        }
    }
});
```

**Comment by florianrubel** [comment]
Nevermind. I found out why it's not working.
The documentation is very poorly updated.

**Comment by SztefkoKamil** [comment]
> Nevermind. I found out why it's not working.
> The documentation is very poorly updated.

Can you explain how you fix it?

**Comment by ovionlogis** [comment]
@SztefkoKamil I found a solution to a similar problem here [https://github.com/nolimits4web/swiper/issues/371](https://github.com/nolimits4web/swiper/issues/3716), might be helpful for someone else
