### ISSUE TITLE
[Swiper React] Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by Danetag** [nolimits4web/swiper#3786]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.1.2
* Platform/Target and Browser Versions: Chrome, but issue is on every platform

### What you did
Setup `<Swiper>` React

### Expected Behavior
When I'm trying to drag/drop, the console throws the following error

```
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'
```

### Actual Behavior
No error should be thrown, and I should be able to drag/drop

Example:

```.tsx
<nav>
   <Swiper
         centeredSlides
         slidesPerView={'auto'}
         freeMode
         mousewheel
         grabCursor
         virtual
         simulateTouch
         wrapperClass="breadcrumbs-wrapper" // doesn't work
         wrapperTag="ol"
         initialSlide={navigationItems.length - 1}
         aria-label="Breadcrumbs"
         css={styles.root} // using Emotion
    >
      {navigationItems.map((item, idx, array) => {
          return (
           <SwiperSlide
                tag="li"
                key={`${item.label}_${idx}`}
                css={styles.item}
                slot="wrapper-start" // have to add "wrapper-start" otherwise `li` elemnts are out of the `ol` wrapper element...
              >
                 ... content
           </SwiperSlide>
        )
      })}
    </Swiper>
</nav>
```
Also little note: the `breadcrumb-wrapper` class is not applied and I had to add `slot="wrapper-start"` :/

**Comment by Danetag** [comment]
Hello! Any update around here?

**Comment by nolimits4web** [comment]
Would be good to see live example (in a form of JSFiddle, CodeSandbox, etc.)

**Comment by patric-eberle** [comment]
Had the same error when setting up the basic slider (not react related). My fault was, that I used the wrong root element.

On the official demo HTML, you need to bind the instance to `.swiper-container` and NOT `.swiper-wrapper` like I did initially.

```html
<!-- Slider main container : Bind swiper instance to this element -->
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        ...
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>

    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- If we need scrollbar -->
    <div class="swiper-scrollbar"></div>
</div>
```

**Comment by cgarrovillo** [comment]
This needs to be reopened because the solution is not swiper react related but for a basic slider.

**Comment by octocat415** [comment]
Hi, support
I faced this error when I tried to use Swiper in my HTML.

```
<script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
<script>
  var mySwiper = new Swiper ('#test-swiper', {
    slidesPerView: 1,
    grabCursor:true,
    slidesPerGroup: 1,
    a11y: false,
    spaceBetween: 100,
    autoHeight: true,
    loop: true,
    navigation: {
      nextEl: '#ah-arrow-next-slide',
      prevEl: '#ah-arrow-prev-slide',
    },
  });
```
</script>

![image](https://github.com/nolimits4web/swiper/assets/149055220/4040ce33-d04f-4361-b28a-fe97dd18ba3e)

Any idea of this?

**Comment by vincepaquette** [comment]
> Hi, support I faced this error when I tried to use Swiper in my HTML.
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
> <script>
>   var mySwiper = new Swiper ('#test-swiper', {
>     slidesPerView: 1,
>     grabCursor:true,
>     slidesPerGroup: 1,
>     a11y: false,
>     spaceBetween: 100,
>     autoHeight: true,
>     loop: true,
>     navigation: {
>       nextEl: '#ah-arrow-next-slide',
>       prevEl: '#ah-arrow-prev-slide',
>     },
>   });
> ```
> 
> </script>
> ![image](https://private-user-images.githubusercontent.com/149055220/282249346-4040ce33-d04f-4361-b28a-fe97dd18ba3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NjI2NjYsIm5iZiI6MTcwMTQ2MjM2NiwicGF0aCI6Ii8xNDkwNTUyMjAvMjgyMjQ5MzQ2LTQwNDBjZTMzLWQwNGYtNDM2MS1iMjhhLWZlOTdkZDE4YmEzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQyMDI2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzc2MjdlMTUyNmU2ZjYzOWEyNDMxNzljZDM5YmY4Mjg2MDA0MThmZDkyZDU4OWQ2NmNiOTM2ZGViYTU5YTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.suNukaxtWCaG2G0ZQNX-mYXFsP0rkwMNyB3Ih-FjZno)
> 
> Any idea of this?

@octocat415 Your js seems fine, can you show your HTML ? 

I had the same issue, i then realised that i was missing a parent div with the class swiper-wrapper. Here's how it should look:

```
<div class="swiper" id="test-swiper">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      My Slide
    </div>
    <div class="swiper-slide">
      My Slide
    </div>
    <div class="swiper-slide">
      My Slide
    </div>
    <div class="swiper-slide">
      My Slide
    </div>
  </div>
</div>
```

**Comment by nickfmc** [comment]
just putting this here because it is likely to help somebody in the future searching for this error and swiper, if you are calling the function inside of jquery you will need to use 
`var swiper = new Swiper($block.find(".swiper").get(0), {
    // Swiper options...
});`

instead of `var swiper = new Swiper(".swiper", {`
