### ISSUE TITLE
slides auto scrolls on click

### ISSUE THREAD

**Issue by x1881** [nolimits4web/swiper#3787]
Hello. I am working on a website using swiper.js

The slides should only change when the down arrow is clicked, **NOT** when any other element on the page is clicked, neither the text or the background of the page, but strangely, when other elements are clicked, the slides are changing, I don't understand why.

Here is a video where I show what happens, it can be seen clearly when I click on the "seasons of change" section and then the slide changes up, also in the last section, when I click on several words and then the slide changes again upwards:
https://z-testing.000webhostapp.com/_swiper/video.webm

Here is a demo of the website:
https://z-testing.000webhostapp.com/_swiper/

This is my code:

    $(window).load(function() {

      var swiper = new Swiper('.swiper-container', {
        direction: 'vertical',
        slidesPerView: 1,
        spaceBetween: -1,
        mousewheel: true,
        preventClicks: true,
        allowTouchMove: true,
        preventClicksPropagation: true
      });

      // next slide
      $(".scrolldown").on("click", function (e) {
          e.preventDefault();
          swiper.slideNext();
          return !1;
      });

    });

Thanks

**Comment by nolimits4web** [comment]
It works as expected:

> when I click on the "seasons of change" section and then the slide changes up

you are doing show swipe/drag here
