### ISSUE TITLE
Swiper React custom navigation components

### ISSUE THREAD

**Issue by MacGyver98** [nolimits4web/swiper#3788]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: swiper@6.0.1.

* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
I set navigation property 
`<Swiper navigation={{
    navigation: {
        nextEl:  (<div className='next'></div>),
        prevEl:  (<div className='next'></div>)
    }}>
...  </Swiper>`

### Expected Behavior
I want to see my own navigation buttons

### Actual Behavior
The navigation isn't there, nither the original. It's like "navigation: false".

Thanks in advance

**Comment by awt0523** [comment]
Navigation is  possible with boolean, and the default value is true.

<Swiper
navigation>
Try

Just before
swiper.use([Navigation]) should be declared

you should document is recheck
https://swiperjs.com/react/

**Comment by lucaskahl** [comment]
@awt0523 If you check the Typescript interface from navigation, it can receives an object with nextEl and prevEl and both can receive a CSSSelector or HTMLElement and yeah, for some reason they aren't showing.

@MacGyver98 To get around this, I ended up creating a useRef in the swipe to access the slideNext and slidePrev methods, here's an example.

```jsx
import React, { useMemo, useRef } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, { Autoplay } from 'swiper';

function Swiper() {
  const swiperRef = useRef(null);
  SwiperCore.use([Autoplay]); // don't need navigation anymore

  const prevSlide = useMemo(() => {
    swiperRef.current.swiper.slidePrev();
  }, []);

  const nextSlide = useMemo(() => {
    swiperRef.current.swiper.slideNext();
  }, []);

  return (
    <>
      <div className="left-floating-el" onClick={prevSlide}>
        an floating element
      </div>
      <Swiper
        ref={swiperRef}
        spaceBetween={30}
        slidesPerView={slidesPerView}
        autoplay={{ delay: 5000 }}
        loop
      >
        <SwiperSlide>slide 1</SwiperSlide>
        <SwiperSlide>slide 2</SwiperSlide>
      </Swiper>
      <div className="right-floating-el" onClick={nextSlide}>
        an floating element
      </div>
    </>
  );
}

```

**Comment by maeertin** [comment]
You could also use [Swiper Slots](https://swiperjs.com/react/#slots) to place your navigation buttons within the `.swiper-container` which is where Swiper places it's own navigation buttons.

```jsx
<Swiper ref={swiperRef} {...other}>
  <span slot="container-start">
    <div className="left-floating-el" onClick={prevSlide}>
      an floating element
    </div>
    <div className="right-floating-el" onClick={nextSlide}>
      an floating element
    </div>
  </span>

  <SwiperSlide>slide 1</SwiperSlide>
  <SwiperSlide>slide 2</SwiperSlide>
</Swiper>
```

The **issue** here is that you lose functionality for getting the `.swiper-button-disabled` className and the `A11y` module not setting the `aria-disabled` or `tabindex` attributes. Therefore I am also in need of being able to pass custom navigation elements. Ideally I would want to do something like below.

```jsx
import React from 'react'
import SwiperCore, { A11y, Navigation } from 'swiper'
import { Swiper, SwiperSlide } from 'swiper/react'
import ArrowBackwardIosIcon from '@material-ui/icons/ArrowBackwardIos'
import ArrowForwardIosIcon from '@material-ui/icons/ArrowForwardIos'
import IconButton from '@material-ui/core/IconButton'

SwiperCore.use([A11y, Navigation])

const Swiper = () => (
  <Swiper
    navigation={{
      prevEl: <IconButton><ArrowBackwardIosIcon /></IconButton>,
      nextEl: <IconButton><ArrowForwardIosIcon /></IconButton>,
    }}
  >
    <SwiperSlide>slide 1</SwiperSlide>
    <SwiperSlide>slide 2</SwiperSlide>
  </Swiper>
)
```

**Comment by nolimits4web** [comment]
As to documentation nextEl and prevEl receive HTMLElement or string with CSS selector, so it should be:
```
  <Swiper
    navigation={{
      prevEl: '.prev',
      nextEl: '.next',
    }}
  >
    <SwiperSlide>slide 1</SwiperSlide>
    <SwiperSlide>slide 2</SwiperSlide>
    <div className="prev" />
    <div className="next" />
  </Swiper>
```

**Comment by maeertin** [comment]
Oh I see! Works like a charm, thanks 👍

**Comment by maeertin** [comment]
Hi @nolimits4web,

Using classnames does not work for me as as I need the navigation buttons to be scoped to each rendered Swiper instance. Luckily documentation states that `prevEl` and `nextEl` can also be of type "HTMLElement" which would solve this issue perfectly. However, how would this be implemented correctly in React as `refs` are `null` on initial render?

My current workaround:
```jsx
// MySwiper.js

const MySwiper = () => {
  const navigationPrevRef = React.useRef(null)
  const navigationNextRef = React.useRef(null)

  return (
    <Swiper
      navigation={{
        // Both prevEl & nextEl are null at render so this does not work
        prevEl: navigationPrevRef.current,
        nextEl: navigationNextRef.current,
      }}
      onSwiper={(swiper) => {
        setTimeout(() => {
          // Override prevEl & nextEl now that refs are defined
          swiper.params.navigation.prevEl = navigationPrevRef.current
          swiper.params.navigation.nextEl = navigationNextRef.current
          // Re-init navigation
          swiper.navigation.destroy()
          swiper.navigation.init()
        })
      }}
    >
      <SwiperSlide>slide 1</SwiperSlide>
      <SwiperSlide>slide 2</SwiperSlide>
      <div ref={navigationPrevRef} />
      <div ref={navigationNextRef} />
    </Swiper>
  )
}

// App.js

const App = () => (
  <div>
    <MySwiper />
    <MySwiper />
  </div>
)
```
