### ISSUE TITLE
multiple swiper sliders on a same page, not letting the arrow nav button control all the sliders. 

### ISSUE THREAD

**Issue by 1101blueli** [nolimits4web/swiper#3797]
Hello 
I have some multiple swiper sliders duplicated on a same page but the arrow nav button is affecting to all others.
Any way to solve it without adding extra class for the arrow element?

This is the JS for my code block looks like:
var mySwiper = new Swiper('.swiper-container-product', {
  	speed: 200,
  	freeMode: true,
  	freeModeMomentumBounce: false,
	navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
    },
}};

I have try something like this. does not seems to work.

var mySwiper2 = new Swiper('.swiper-container-product-2', {
  	speed: 200,
  	freeMode: true,
  	freeModeMomentumBounce: false,
	navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
    },
}};

Thanks

**Comment by maeertin** [comment]
Hi there @1101blueli,

[SwiperJS documentation](https://swiperjs.com/api/#navigation) states that navigation prevEl/nextEl can either be of type "string" or "HTMLElement". So the two options I see are:

**Unique string selectors**
```js
var mySwiper1 = new Swiper('.swiper1', {
  navigation: {
    prevEl: '.swiper1-prev',
    nextEl: '.swiper1-next',
  },
}};

var mySwiper2 = new Swiper('.swiper2', {
  navigation: {
    prevEl: '.swiper2-prev',
    nextEl: '.swiper2-next',
  },
}};
```

**HTML nodes**
```js
var mySwiper1Prev = document.querySelector('.swiper1 .swiper-prev')
var mySwiper1Next = document.querySelector('.swiper1 .swiper-next')
var mySwiper1 = new Swiper('.swiper1', {
  navigation: {
    prevEl: mySwiper1Prev,
    nextEl: mySwiper1Next,
  },
}};

var mySwiper2Prev = document.querySelector('.swiper2 .swiper-prev')
var mySwiper2Next = document.querySelector('.swiper2 .swiper-next')
var mySwiper2 = new Swiper('.swiper2', {
  navigation: {
    prevEl: mySwiper2Prev,
    nextEl: mySwiper2Next,
  },
}};
```
