### ISSUE TITLE
Is it possible to have vertical scrolling thumbnails with a horizontal scrolling swiper?

### ISSUE THREAD

**Issue by dtgit2020** [nolimits4web/swiper#3799]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

I've searched through here and google to try to find this out.
My goal is to display a slideshow of 20 images.  On the side I need a vertical thumbnail bar with 5 thumbs displayed at a time.
When a thumbnail is clicked, I'd like the main slideshow image to change to the one that is clicked.

The built in thumbnails seem to only be horizontal layout.  Is there a vertical one?
I've also seen other trying to do it by using Controller and having two swiper instances, one controlling the other.  I've tried an implementation of that and it doesn't seem to work and have opened a ticket about it.

This ticket is to find out if there's a another/simpler way of achieving this that I might have overlooked.  I thought we could have just set the built in thumbnail property to vertical, but that doesn't seem to have been included?  Or did I miss it?

Thank you for any help in advance

**Comment by nolimits4web** [comment]
Set `direction: 'vertical'` on Thumbs swiper
