### ISSUE TITLE
Multi-row setup does not work

### ISSUE THREAD

**Issue by klausXR** [nolimits4web/swiper#3800]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.1.3
* Platform/Target and Browser Versions: Newest Chrome/Firefox
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/dslavov/pen/mdPqqpj

### What you did
https://codepen.io/dslavov/pen/mdPqqpj

I did fork this codepen https://codepen.io/tim-gh/pen/RwNzgOJ and updated the versions. I'm experiencing the exact same problems in my project with code copy-pasted from the Multi-row example from your web page. 

### Expected Behavior
[this](https://swiperjs.com/demos/170-slides-per-column.html)

### Actual Behavior
Slides display below one another

**Comment by rhcarlosweb** [comment]
Same problem here

**Comment by rhcarlosweb** [comment]
https://codepen.io/rhcarlosweb/pen/yLOqoXR i found the problem, well, kind of...

I put a wrapper in slider with a fixed height value, because without a parent div with height the swiper multi row don't see to work

and i put a calc height to .swiper-slide div, seems to work
