### ISSUE TITLE
contenteditable attribute not working as expected

### ISSUE THREAD

**Issue by andreyc0d3r** [nolimits4web/swiper#3801]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.1.
* Platform/Target and Browser Versions: win chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/digitalapps/pen/JjXOQqr

### What you did
Added contenteditable="true" attribute to the slider content

### Expected Behavior
On left click I should be able to edit the content

### Actual Behavior
On the left click, nothing is happening, or right-click can edit

**Comment by andreyc0d3r** [comment]
Hi I was just curious if this bug has been acknowledged and if the fix should be expected?

**Comment by ygj6** [comment]
@nolimits4web Do you think we need to deal with this kind of scene?

**Comment by andreyc0d3r** [comment]
thanks @nolimits4web

**Comment by andreyc0d3r** [comment]
@ygj6 incase you are curious if the content editable attribute is necessary and how it is used, heres a use case. I have built a plugin [WP Swiper](https://wordpress.org/plugins/wp-swiper/) it's a Gutenberg block. Gutenberg is a new editor for WordPress. I wanted to use Swiper React component and allow users to be able to visually create slides using the Gutenberg Editor.

**Comment by toanredweb** [comment]
Can you guide me to get the shortcode?

**Comment by uschmelzer** [comment]
+1
