### ISSUE TITLE
How to change pagination from bullets to progress on different screens?

### ISSUE THREAD

**Issue by appleansa** [nolimits4web/swiper#3803]
Hi! I'm trying to change swiper pagination container using breakpoints, but it doesn't works for me. Have Any ideas how to make it work? When Slider smaller <992px it works fine, when screen stay bigger swipper progressbar don't work's for me.

http://lantorg.appleansa.myjino.ru/ - slider on the main screen.

Here my code: 
`var myMsSwiper = new Swiper('.ms-inner', {
                 loop: true,
                  autoHeight: true,
                 height: 400,
                 pagination: {
                     el: '.ms-pagination', 
                 },
                 navigation: {
                     nextEl: '.ms-buttons .swiper-btn-next',
                     prevEl: '.ms-buttons .swiper-btn-prev',
                 },

                 breakpoints: {
                     992: {
                         slidesPerView: 2,
                         spaceBetween: 0,
                         height: '500',
                         updateOnWindowResize: true,
                          pagination: {
                     el: '.ms-navi-custom .swiper-progressbar',
                     type: 'progressbar',
                 },
                     }
                 },
                 on: {
                     init: function() {

                         var totalslide = $('.ms-slider .swiper-slide:not(.swiper-slide-duplicate)').length;
                         $(".ms-navi .swiper-total-slides").html('0' + totalslide);

                         var slidewidth = $('.ms-slider .swiper-slide').width();
                         $('.ms .swiper-navi-compact').css({ 'left': slidewidth });

                     },

                     resize: function() {

                         var slidewidth = $('.ms-slider .swiper-slide').width();
                         $('.ms .swiper-navi-compact').css({ 'left': slidewidth });

                     }
                 }
             });

             myMsSwiper.on('slideChange', function() {
                 var activeslide = myMsSwiper.realIndex + 1;
                 $(".ms-navi .swiper-active-slides").html('0' + activeslide);
             });
`

**Comment by nolimits4web** [comment]
Sorry, but such behavior is not supported at the moment, pagination can be only one of the types all the time
