### ISSUE TITLE
swiper/vue: render wrong dom when using v-for

### ISSUE THREAD

**Issue by wsli10** [nolimits4web/swiper#3808]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.2.0,
* Platform/Target and Browser Versions: macOS Catalina 10.15, chrome 85.0.4183.83, vue 3.0
### What you did
I was trying to use vue3 and swiper/vue，I found swiper doesn't work when I use `v-for` on `swiper-slide` component

When I use swiper like this:
```html
 <swiper>
    <swiper-slide>Slide 1</swiper-slide>
    <swiper-slide>Slide 2</swiper-slide>
    <swiper-slide>Slide 3</swiper-slide>
    ...
  </swiper>
```
Everything is ok, the DOM is :
![image](https://user-images.githubusercontent.com/50507732/92458783-71b39780-f1f8-11ea-9e47-f86c288c89d1.png)

But when I use `v-for` on `swiper-slide` component, like:
```html
  <swiper>
    <swiper-slide
      v-for="slide in slides"
      :key="slide"
    >{{ slide }}</swiper-slide>
  </swiper>
```
The DOM is:
![image](https://user-images.githubusercontent.com/50507732/92459204-f7374780-f1f8-11ea-96be-a1c278e7b733.png)

We can see that the element `.swiper-slide` is out of `.swiper-wrapper`

---
Besides, I modified `/node_modules/swiper/esm/vue/swiper-silde.js` for [issue 3802](https://github.com/nolimits4web/swiper/issues/3802)

**Comment by nolimits4web** [comment]
It is fixed in https://github.com/nolimits4web/swiper/commit/123f7915be3207dbc822d1f5828ed0cfcd431754, wait when it will be released
