### ISSUE TITLE
Double Tap feature does not work with two taps in ios 13 version.

### ISSUE THREAD

**Issue by enderimen** [nolimits4web/swiper#3811]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.2
* IOS Versions: IOS 13..
* https://www.boyner.com.tr/limon-gomlek-843068-200104 (**in mobile view**)
**NOT:** You can open the carousel on this page in mobile view on iOS 13 device and try it.

### What you did
I included the version of swiper.js **4.2.2** in my page and i wrote the code below.

```
on: {
       doubleTap: function (event) {
          console.log("zoom-in-zoom-out");
       }
},
```
### Expected Behavior
When I click the slider twice, the doubleTap function is not active. This function is active with triple-tap (3). For this reason I cannot zoom-in / zoom out with the double tap. 

### Actual Behavior
For this reason I cannot zoom-in / zoom out with the double tap. It works on Android versions but does not work as of IOS 13.

**Comment by nolimits4web** [comment]
Version `4.2.2` is not maintained. Update to latest version where it was fixed
