### ISSUE TITLE
Slim or Extension Version?

### ISSUE THREAD

**Issue by Daijobou** [nolimits4web/swiper#3814]
Is there a chance that there will be a slim version or extension system in the future?

I would like to have a smaller slimmed version which reduces the loading time in the browser. For example with only the standard navigation arrows. The plugin contains great features. But surely not all functions are always needed. Here it would be great to have a standard plugin and be able to extend it with extensions. So you could add effects and pagnation afterwards.

Like jQueryUI https://jqueryui.com/download/ 
I mean here only the splitting in small parts, not such a download page ;)

There is a workaround without remove too much code. Use not minified version. In my case I only need Navigation$1 as component, after minified all unnecessary functions were removed automatically. Instead 140 KB its only 75 KB.

```
    //var components = [Virtual$1, Keyboard$1, Mousewheel$1, Navigation$1, Pagination$1, Scrollbar$1, Parallax$1, Zoom$1, Lazy$1, Controller$1, A11y$1, History$1, HashNavigation$1, Autoplay$1, EffectFade, EffectCube, EffectFlip, EffectCoverflow, Thumbs$1];
    var components = [Navigation$1];
```

**Comment by nolimits4web** [comment]
Here is instruction on how to do it https://swiperjs.com/api/#custom-build
