### ISSUE TITLE
mySwiper.update() does not update active/prev/next classes on slides

### ISSUE THREAD

**Issue by acromatica** [nolimits4web/swiper#3815]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v6.2.0
* Platform/Target and Browser Versions: macOS CHROME.
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/acromatica/pen/qBZYbJX

### What you did
I added a swiper and hid first two slides with css by adding style="display: none" to them, after that I called mySwiper.update(), but it doesn't seem to be updating active/prev/next classes properly.

### Expected Behavior
I expect current active (visible) slide to have swiper-slide-active class instead of hidden slide.

### Actual Behavior
Hidden slide still has swiper-slide-active class, and when I change slides active class is added to the next hidden slide.

**Comment by ExileofAranei** [comment]
Faced the same problem. Thumbs in same situation will also have wrong classes and also clicking on them does not navigate to the right one main swiper slide.
Tried to filter array with hidden thumb swiper slides on main swiper 'changeSlider' event and add custom active class and it worked, but the last thumb instead of 3th slide navigated to 2nd, don't know how to handle it

**Comment by nolimits4web** [comment]
Sorry, but hidden slides are not supported. You need to remove/add them instead from DOM

**Comment by acromatica** [comment]
@ExileofAranei 
I ended up setting swiper activeIndex to the index of current active slide (mySwiper.activeIndex = [index of current visible slide]) and calling mySwiper.updateSlidesClasses() after that, seemed to fix my problem, but as I'm not using thumbs I don't know if this solution is going to work for you).

**Comment by ExileofAranei** [comment]
@acromatica 
Solved my problem with removing and adding slides from both sliders just like nolimits4web answered, in my case it turned out to be more convenient way, but thanks for response

**Comment by putrafajarh** [comment]
> @ExileofAranei I ended up setting swiper activeIndex to the index of current active slide (mySwiper.activeIndex = [index of current visible slide]) and calling mySwiper.updateSlidesClasses() after that, seemed to fix my problem, but as I'm not using thumbs I don't know if this solution is going to work for you).

how to get index of current visible slide?
