### ISSUE TITLE
DocumentTouch is deprecated since Gecko 25 (Firefox 25 / Thunderbird 25 / SeaMonkey 2.22)

### ISSUE THREAD

**Issue by Daijobou** [nolimits4web/swiper#3819]
In function calcSupport() there is this line:
`touch: !!('ontouchstart' in window || window.DocumentTouch && document instanceof window.DocumentTouch),`

window.DocumentTouch is deprecated since long time.
https://developer.mozilla.org/en-US/docs/Web/API/DocumentTouch

Maybe instead this check?
`'ontouchstart' in window || navigator.maxTouchPoints > 0`

**Comment by nolimits4web** [comment]
It is for detection of [`TouchEvents`](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent), which has nothing to do with Pointer Events

**Comment by Daijobou** [comment]
I'm confused, because DocumentTouch has been removed 2013 (firefox 25).
