### ISSUE TITLE
Different callbacks according to the slide direction

### ISSUE THREAD

**Issue by jbo-tech** [nolimits4web/Swiper#382]
Hello,

Thank you for your work.

Is there any way to have different callbacks according to the slide direction?
- from right to left > onSlideChangeStart: action A
- from left to right > onSlideChangeStart: action R

**Comment by carlosalvidrez** [comment]
This method won't work if you only have one slide, will it?
I ask because I'm only interested in capturing the swipe direction, and based on it, change the current route.
Thanks
