### ISSUE TITLE
Keyboard controls not working in version 6

### ISSUE THREAD

**Issue by SeanRoberts** [nolimits4web/swiper#3823]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.2.0, 6.1.x, 6.0.x
* Platform/Target and Browser Versions: MacOS Chrome and Safari
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/swiperjs-forked-kw14w?file=/src/index.js

### What you did
If you enter the CodeSandbox linked above you should be able to see for yourself.  Pinning the Swiper dependency to 5.4.5 allows the arrow keys to work as expected.  When you pin the dependency to 6.0.0 or higher you'll see the arrow keys no longer work.  Additionally, if you check the result of `console.log(mySwiper.keyboard)` you can see that it's undefined on >=6.0.0

### Expected Behavior
Ideally it would just work the way it was working in 5.4.5

**Comment by nolimits4web** [comment]
https://swiperjs.com/get-started/

> By default Swiper exports only core version without additional modules (like Navigation, Pagination, etc.). So you need to import and configure them too:

**Comment by SeanRoberts** [comment]
🤦‍♂️ sorry
