### ISSUE TITLE
Custom slideThumbActiveClass removed on first load on React

### ISSUE THREAD

**Issue by valse** [nolimits4web/swiper#3827]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.2.0.
* Platform/Target and Browser Versions: Windows 10 Chrome.
* Live Link: https://frasix.it/frasi/5807

### What you did
I set on main swiper the thumbs prop like this:
``` js
thumbs={{ swiper: thumbsSwiper, slideThumbActiveClass: "is-active" }}
```

### Expected Behavior
The first thumb swiper must have the `is-active` custom class on first load

![image](https://user-images.githubusercontent.com/1492995/93447841-2b82c600-f8d3-11ea-8091-7440689f98e4.png)

### Actual Behavior
The `is-active` custom class disappear on first load

![image](https://user-images.githubusercontent.com/1492995/93447973-566d1a00-f8d3-11ea-9c85-4b7ade8d37a4.png)

If I don't use a custom css class but I keep the default `swiper-slide-thumb-active` it works like expected

**Comment by kyrvayapierdole** [comment]
the same
