### ISSUE TITLE
When using v-for, slides are not initialized

### ISSUE THREAD

**Issue by Karpig** [nolimits4web/swiper#3830]
Hello, when I try to render slides using a loop, I get the "Cannot read property 'value' of undefined" error. After researching the code, I found the problem in the getChildren function.

When using v-for, vue wraps the slides in Symbol (Fragment), which causes the function to look for slots in the wrong place.

The same problem is observed when using the example from the documentation with virtual slides.

Tested in standard configuration vue-cli and hello-vue3.

ps sorry for my English

**Comment by cbpi** [comment]
i have same problem querySelectorAll of underfined

**Comment by cbpi** [comment]
try v-for on <template>:

```
<swiper ref="mySwiper" :options="swiperOptions">
<template v-for="(item, index) in list" >
           <swiper-slide></swiper-slide>
</template>
</swiper>
```

**Comment by cbpi** [comment]
use` v-if="data.length>1"` on `<swiper>`, then `v-for` on `<swiper-slide v-for="(item, index) in data" :key="key">`
