### ISSUE TITLE
Virtaul Slides + History did not work.

### ISSUE THREAD

**Issue by alexvais** [nolimits4web/swiper#3835]
Please see Fiddlejs

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.2.0
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/2v714nqw/1/

### What you did
Combine Virtual Slides + History to change the url

### Actual Behavior
Error: Uncaught TypeError: Cannot read property 'toString' of null

Seems that history module need all the slides loaded to work.

**Comment by ygj6** [comment]
@alexvais 
The following is the usage guide of the [official website:](https://swiperjs.com/api/#history-navigation)
>Enables history push state where every slide will have its own url. In this parameter you have to specify main slides url like "slides" and specify every slide url using **data-history** attribute.

```
 return '<div class="swiper-slide">Slide ' + slide + '</div>';
```
Add the `data-history` attribute to the code above.
```
return '<div class="swiper-slide" data-history="Slide' + slide + '">Slide ' + slide + '</div>';
````

**Comment by silllli** [comment]
I encountered the same issue today. I guess it’s also what is going on in #3536.

**Comment by silllli** [comment]
> Please see Fiddlejs
> 
> This is a (multiple allowed):
> 
> * [x]  bug
> * [ ]  enhancement
> * [ ]  feature-discussion (RFC)
> * Swiper Version: 6.2.0
> * Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/2v714nqw/1/
> 
> ### What you did
> Combine Virtual Slides + History to change the url
> 
> ### Actual Behavior
> Error: Uncaught TypeError: Cannot read property 'toString' of null
> 
> Seems that history module need all the slides loaded to work.

Could you please fix the issue title (”virtual“) so it can be found when searching? @alexvais
