### ISSUE TITLE
Performance on mobile is really poor

### ISSUE THREAD

**Issue by joebentaylor1995** [nolimits4web/swiper#3841]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: "^6.2.0",
* Platform/Target and Browser Versions: Safari IOS
* Live Link or JSFiddle/Codepen or website with issue: www.joebentaylor.co.uk

### What you did
I just used the react version of swiper. Heres my setup:
```
// Imports
// ------
import React, { useState, useEffect } from 'react';
import anime from 'animejs/lib/anime.es.js';
import TextSlide from './TextSlide';
import loadable from '@loadable/component';
import SwiperCore, { Controller, Pagination, Mousewheel, EffectFade, EffectCoverflow } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';

// Styles
// ------
import 'swiper/swiper.scss';
import 'swiper/components/controller/controller.scss';
import 'swiper/components/effect-fade/effect-fade.scss';

import {
    Jacket,
} from './styles';


// Component
// ------
SwiperCore.use([Controller, Pagination, Mousewheel, EffectFade, EffectCoverflow]);

const ImageSlide = loadable(() => import('./ImageSlide'));

const Slider = ({ content }) => {
    const [controlledSwiper, setControlledSwiper] = useState(null);

    const animationReset = {
        targets: '.swiper-slide .word .char',
        opacity: 0,
        duration: 1
    }

    const animationIn = {
        targets: '.swiper-slide-active .word .char',
        opacity: 1,
        translateY: [100, 0],
        delay: anime.stagger(50),
    }

    const animationOut = {
        targets: '.swiper-slide-active .word .char',
        opacity: 0,
        translateY: -50,
        delay: anime.stagger(50),
    }

    const imageSlider = {
        loop: true,
        speed: 750,
        direction: "vertical",
        slidesPerView: 1,
        grabCursor: false,
        watchSlidesProgress: true,
        effect: "coverflow",
        coverflowEffect: {
            rotate: 120,
            slideShadows: true,
        },
    }

    const textSlider = {
        loop: true,
        slidesPerView: 1,
        speed: 750,
        grabCursor: true,
        watchSlidesProgress: true,
        mousewheel: true,
        direction: 'vertical',
        effect: "fade",
        fadeEffect: {
            crossFade: true
        },
    }

    useEffect(() => {
        const Splitting = require('splitting');
        Splitting({ target: '.title-text' });
    }, []);

    return (
        <>
            <Jacket>
                <Swiper
                    {...imageSlider}
                    className="image"
                    onSwiper={setControlledSwiper}
                    pagination={{ type: 'progressbar' }}
                >
                    {content.featuredWork.map(({ featuredImage }, i) => (
                        <SwiperSlide key={i}>
                            <ImageSlide image={featuredImage.fluid} />
                        </SwiperSlide>
                    ))}
                </Swiper>

                <Swiper
                    {...textSlider}
                    className="text"
                    controller={{ control: controlledSwiper }}
                    onSlideChange={() => anime(animationOut)}
                    onSlideChangeTransitionStart={() => anime(animationOut)}
                    onSlideChangeTransitionEnd={() => anime(animationIn)}
                    onInit={() => setTimeout(() => { anime(animationIn) }, 25)}
                    onReachBeginning={() => anime(animationReset)}
                    onResize={() => anime(animationIn)}
                >
                    {content.featuredWork.map(({ titleLine1, titleLine2, projectLink, featuredImage }, i) => (
                        <SwiperSlide key={i}>
                            <TextSlide first={titleLine1} second={titleLine2} projectLink={projectLink} image={featuredImage} />
                        </SwiperSlide>
                    ))}
                </Swiper>
            </Jacket>
        </>
    );
}

export default Slider;

```

### Expected Behavior
If you view desktop its perfect. Smooth. Just perfect.

### Actual Behavior
On mobile its really janky

**Comment by nolimits4web** [comment]
Just curious if you disable `anime` animations, will it better?

**Comment by joebentaylor1995** [comment]
I managed to fix the issue.
It wasn’t anime, but you’ll be interested...

The height of the calculated slides were constantly wrong and causing the issues, I added a fixed height to the slides and now performance is great again!

Kind regards,

Joe

**Comment by MilesWuCode** [comment]
> I managed to fix the issue. It wasn’t anime, but you’ll be interested... The height of the calculated slides were constantly wrong and causing the issues, I added a fixed height to the slides and now performance is great again! Kind regards, Joe
> […](#)
> On 28 Sep 2020, at 11:08, Vladimir Kharlampidi ***@***.***> wrote: ﻿ Just curious if you disable anime animations, will it better? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

i have 10 swiper components on one page, same issue on iphone when scrolling
vary lag and display slow

fixed height to the slides ? how can i do?

**Comment by MariaLazarenko** [comment]
> > I managed to fix the issue. It wasn’t anime, but you’ll be interested... The height of the calculated slides were constantly wrong and causing the issues, I added a fixed height to the slides and now performance is great again! Kind regards, Joe
> > […](#)
> > On 28 Sep 2020, at 11:08, Vladimir Kharlampidi _**@**_.***> wrote: ﻿ Just curious if you disable anime animations, will it better? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> i have 10 swiper components on one page, same issue on iphone when scrolling
> vary lag and display slow
> 
> fixed height to the slides ? how can i do?

the same problem here
have you found the solution?

**Comment by AndrewBogdanovTSS** [comment]
@MariaLazarenko specify `height` property in options object. You can also provide swiper with elments of a fixed height. If you use images - set width and height on them

**Comment by snimavat** [comment]
i m facing similar issue on mobile, the swipe is jerky. I am using swiper vue component...

@joebentaylor1995 can u add some more details on ur fix

**Comment by roeeyossef** [comment]
adding cssMode: true solved the issue for me.

**Comment by Porpos** [comment]
@roeeyossef 
> adding cssMode: true solved the issue for me.

Saved me ! Thanks man.

**Comment by donmb1** [comment]
We are facing crashes of mobile applications using swiper.js
especially on iPhone Pros we could reproduce it. Non Pro iPhone seem to work fine and no issues on Android. Anyone else having this issue?

**Comment by aaronabf** [comment]
> We are facing crashes of mobile applications using swiper.js especially on iPhone Pros we could reproduce it. Non Pro iPhone seem to work fine and no issues on Android. Anyone else having this issue?

We are as well. We are noticing 100% CPU usage on all Webkit browsers (Safari Desktop, Safari Mobile, Chrome Mobile, etc.)

**Comment by mrjackyliang** [comment]
For me, i used `useSwiperSlide()` and only load the components that is active, isNext, and isPrev. Everything else returns a skeleton.

**Comment by mikegwhit** [comment]
on my end i tried setting `autoHeight: false`, `cssMode: true` as mentioned, but it turned out on iOS (and for some reason only iOS) there was probably a syntax error that probably caused needless re-renders or similar and unfortunately did not cleanly throw (so i had to find it by hand).  when i fixed the bug the slowness disappeared.

if you're having issues like this encourage you to slow down the process and try with basics.

**Comment by n-ii-ma** [comment]
Having the same issue and nothing seems to work.

**Comment by levipadre** [comment]
Same issue here. I need autoHeight but it's flickering when I paginate, it's lagging. cssMode removed the auto height function.

**Comment by dmzebrov** [comment]
Experienced very laggy experience while dragging slides on Android.

I have an image with `height: 100%` and `object-fit: cover` inside slides.

`will-change: transform;` on the Swiper itself fixes the issue.
