### ISSUE TITLE
swiper@6.3.2 is not compatible android 4.4

### ISSUE THREAD

**Issue by treeandgrass** [nolimits4web/swiper#3844]
The reason is  dom7@3.0.0-alpha.9  transform method no `webkitTransform = transform `，but swiper@6.3.2  use  dom7@3.0.0-alpha.9

dom7  version:3.0.0-alpha.9
``` 
function transform(transform) {
  for (var i = 0; i < this.length; i += 1) {
    this[i].style.transform = transform;
  }

  return this;
}
```
 **vs**

dom7@2.1.5

```js
function transform(transform) {
  for (let i = 0; i < this.length; i += 1) {
    const elStyle = this[i].style;
    elStyle.webkitTransform = transform;
    elStyle.transform = transform;
  }
  return this;
}
```

dom7 new

**Comment by nolimits4web** [comment]
Sorry but it is by design, no Android 4 support

**Comment by limuyao1996** [comment]
> Sorry but it is by design, no Android 4 support

hello sir，I would like to know if Swiper supports Android 5/6?
