### ISSUE TITLE
Autoplay does not start after new data (React)

### ISSUE THREAD

**Issue by soerenBoisen** [nolimits4web/swiper#3846]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.2.0
* Platform/Target and Browser Versions: Tested on Firefox, Chrome, Edge / Windows
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
I have a React component that shows a list of bookings inside a Swiper in order to use autoplay feature (it is for an unattendeed display):
```javascript
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Autoplay, Pagination } from "swiper";
// other imports...

SwiperCore.use([ Autoplay, Pagination ]);

function BookingSlide(props) { ... }

export function GenericBookingList({ bookings, childrenPerSlide = 5 }) {
  const slideGroups = bookings.map(function (childData, index) {...});

  const slides = slideGroups.map(function (childData, index) {
    return (
      <SwiperSlide key={index}>
        <BookingSlide>{childData}</BookingSlide>
      </SwiperSlide>
    );
  }

  return (
    <Swiper autoHeight={true} spaceBetween={30} speed={500}
                autoplay={{ delay: 1000, disableOnInteraction: false }}
                pagination={{ clickable: true }}>
      { slides }
    </Swiper>
  );
}
```

The component regularly receives new data from a web service it polls. Bookings are distributed onto slides and the number of slides depends on how many bookings are present for the current day.

### Expected Behavior
I expect autoplay to kick in and start changing slides when I go from rendering 1 slide to several.

### Actual Behavior
Autoplay never starts if at first the component renders only 1 slide.

Notes:
- Pagination correctly shows dots for the added slides, so Swiper sees them, but it never changes slide.
- If first render results in more than 1 slide, autoplay works fine until a later update renders only 1 slide, in which case it stops to never start again.
- This seems to be have been broken for a long time, I upgraded Swiper from 3.4.0 in the project in hopes of fixing this, changing from a custom React integration to the official Swiper React components used above.
- I even tried adding a hack to call swiper.autoplay.start manually (see code in comment below), but that does not fix it.

**Comment by soerenBoisen** [comment]
This is my attempt at a fix using React hooks to manually call autoplay start, but even this does not cause autoplay to start playing:

```javascript
function useSwiperAutoplayFix(slides) {
    const swiperRef = useRef();
    const [autoplay, setAutoplay] = useState(false);
    const shouldAutoplay = slides.length > 1;

    if (autoplay !== shouldAutoplay) setAutoplay(shouldAutoplay);

    useEffect(() => {
        console.log(`Start autoplay if needed [has swiper: ${swiperRef.current != null}, start: ${autoplay}]`);
        if (autoplay) {
            const timer = setTimeout(() => {
                console.log("Calling swiper.autoplay.start");
                swiperRef.current?.autoplay.start();
            }, 3000);
            return () => clearTimeout(timer);
        }
    }, [autoplay]);

    return swiperRef;
}

export function GenericBookingList({ bookings, childrenPerSlide = 5 }) {
    // Same as before...

    const swiperRef = useSwiperAutoplayFix(slides);

    return (
        <Swiper autoHeight={true} spaceBetween={30} speed={500}
                autoplay={{ delay: 1000, disableOnInteraction: false }}
                pagination={{ clickable: true }}
                onSwiper={swiper => swiperRef.current = swiper}>
            { slides }
        </Swiper>
    );
}
```

I see "Calling swiper.autoplay.start" in the console and no errors, but slides do not start playing!

**Comment by huanlirui** [comment]
In react swiper I cant autoplay ，do you have idea ?

**Comment by BinayRajbanshi** [comment]
I had the same issue. Turns out when you fetch data you have to handle your loading state as well. When loading is true at that time you have to render the  more than one "< SwiperSlide >" with some preview like skeleton or random stuff so that autoplay is initiated when the first render happens. Then there won't be any issue with autoplay or navigation or any other modules after data fetching is complete.

```jsx
{isLoading ? (
  <>
    <SwiperSlide>
      <SingleArticleSlider
        slug={''}
        img={'/images/skeleton.png'}
        title={'loading'}
        exitAnimation={exitAnimation}
      />
    </SwiperSlide>
    <SwiperSlide>
      <SingleArticleSlider
        slug={''}
        img={'/images/skeleton.png'}
        title={'loading'}
        exitAnimation={exitAnimation}
      />
    </SwiperSlide>
    <SwiperSlide>
      <SingleArticleSlider
        slug={''}
        img={'/images/skeleton.png'}
        title={'loading'}
        exitAnimation={exitAnimation}
      />
    </SwiperSlide>
  </>
) : (
  <>
    {remainingData &&
      remainingData.length > 0 &&
      remainingData.map((item) => {
        return (
          <SwiperSlide key={item.id}>
            <SingleArticleSlider
              slug={item.slug}
              img={item.featured_image}
              title={item.title}
              exitAnimation={exitAnimation}
            />
          </SwiperSlide>
        );
      })}
  </>
)}

**Comment by Vednus** [comment]
I think if you just add a key and change it if the data changes, then it will keep playing. This also works on a wrapper with the web components if it's wrapped in a react component that you add the key to.

**Comment by bhaveshdaswani93** [comment]
> I think if you just add a key and change it if the data changes, then it will keep playing. This also works on a wrapper with the web components if it's wrapped in a react component that you add the key to.

This worked for I made the key to items length and it got to working. I am getting the Items data from api call and added key attribute to swiper component

`<Swiper key={items.length}></Swiper>`
