### ISSUE TITLE
Issue with Ie 11

### ISSUE THREAD

**Issue by Unknow-max** [nolimits4web/swiper#3847]
Hi!

I recently upgraded my version of swiper from 5.4.3 (something like that) to the last version. But I noticed sadly a small issue. The website now on  Ie 11 Is completly messed up for a js error caused my swiper, It says: "the object doesn't support the the property or the method isNaN". At First Place, I thinked occur  ony in my case, in my website, but after that I goes to swiperjs.com , opened the dev console, and I noticed that the error occurs also there "the object doesn't support the property or the method isNan".

Step to reproduce:

1. Open swiperjs.com website on Ie
2. Read the dev tool console

**Comment by nolimits4web** [comment]
Sorry but it is by design. IE 11 is not supported
