### ISSUE TITLE
slider is disabled after window size change

### ISSUE THREAD

**Issue by mbakker96** [nolimits4web/swiper#3849]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Ionic latest so version is unknown
* Platform/Target and Browser Versions: MacOS / debian (docker)
* Live Link or JSFiddle/Codepen or website with isssue: 

### What you did
I have a slider in my ionic application. That slider makes use of the swiperJS plugin. I first found this bug when running our e2e test. In our e2e test we start chrome in mobile emulation mode. When we start the application the slider is disabled. Then I tried to find a way to reproduce this bug. 

The bug starts when I switch from or to mobile emulation in chrome. sometimes it works, but often it does not work.

### Expected Behavior
I expected the slider to slide. 

### Actual Behavior
Slider is disabled

demo:  https://we.tl/t-GKzqbXAu5k

**Comment by nolimits4web** [comment]
> when I switch from or to mobile emulation in chrome

This behavior is not supported, you need to refresh/reload the window after toggling emulation

**Comment by mbakker96** [comment]
I don't change it when the page is already loaded. I start chrome via capybara with the chrome flag that set the page on a device size. Then I go to to the page where my ionic app is loaded. As you can see on the screenshot, it has the size of a iPhone. 

reloading the page does not work. 

![image](https://user-images.githubusercontent.com/10044261/94920375-7c3f1500-04b6-11eb-898f-d781325e9814.png)
