### ISSUE TITLE
Is there a way of hiding the left/right arrows if not required?

### ISSUE THREAD

**Issue by redrogue** [nolimits4web/Swiper#385]
Great plugin, but I was wondering if there was a way to hide the arrows unless they are needed. 

For example, if you are at the left end (start) of the slider I don't want to show a left arrow as there is nothing to the left. And likewise at the end of the content, I'd like to be able to hide the right arrow.

I've looked everywhere for a solution to this, are you able to help?

**Comment by omarel1** [comment]
Just figured this out!

Add anywhere after you call swiper js.

```
//dont show navigation on one slide if using looped slides
        var swiper__slidecount = mySwiper.slides.length - 2;
        if (swiper__slidecount < 2) {
          $('.swiper-button-prev,.swiper-button-next').remove();
        }
```

or

```
//dont show navigation on one slide if not using looped slides
        var swiper__slidecount = mySwiper.slides.length;
        if (swiper__slidecount < 2) {
          $('.swiper-button-prev,.swiper-button-next').remove();
        }
```

.swiper-button-prev and .swiper-button-next would be the class names of the arrows

**Comment by Raven0us** [comment]
Swiper adds the class `swiper-button-disabled` to controls if they are not needed, for example, when you are on the last slide and you shouldn't have a "next" arrow. You can control that using CSS.

**Comment by omarel1** [comment]
@Raven0us to which container? I dont see that. 

Also are you sure it does that on looped slides, because I don't think swiper recognizes that on sliders that use loop:true

**Comment by defaria** [comment]
I still haven't found a solution to this problem. I would like to hide the arrow if there's nothing to slide, (eg.) this happens when I set my slider to slide at 4 items but only have 3 items at the moments. The problem is that the class "swiper-button-disabled" is also added when you get to the end of a slider (no more slides to see) in this case I don't want to hide the arrow, just disable. So I can't target that class. It would be great if there was a new class to target, or if the slider would not initialize everything if there number of elements available doesn't meet the settings requirements.

**Comment by defaria** [comment]
I fixed my problem by checking **onInit** and **onAfterResize** if the variables **isBeginning** and **isEnd** were both true. As far as I can tell those two variables are both true only when there's nothing to slide either direction. If arrows are not needed I then add a "disabled" class to each arrow element. I use css to hide them, as I will need them again later on mobile.

I used the function below inside the callbacks.

`function needArrows(swiper) {

        if (swiper.isBeginning && swiper.isEnd) {

            $(swiper.prevButton).addClass("disable");
            $(swiper.nextButton).addClass("disable");

        } else {

            $(swiper.prevButton).removeClass("disable");
            $(swiper.nextButton).removeClass("disable");

        }

    }`

**Comment by RachnaChohan** [comment]
How would I get the prev / next to hide when clicking the arrows? Cause when clicking the pagination and/or swiping the slide the disappear depending if its one the first or last slide. But it is not the case when clicking the prev / next buttons

**Comment by pushkar1397** [comment]
Hi there, I want to hide my next button if it is the last slide in swiper. My numberof slides are 3 and I tried calling mySwiper.slides.length but it gives output 0. I want to remove the next button in 3rd slide. Could you please help me out in this. Below is my code : 
var mySwiper = new Swiper ('.swiper-container', {
		    	// Optional parameters
		    	direction: 'horizontal',
				
		    	// Navigation arrows
		    	nextButton: '.swiper-button-next',
		    	prevButton: '.swiper-button-prev',
		    	
			})
			var swiper__slidecount = mySwiper.slides.length;
			alert(swiper__slidecount);

**Comment by hacknug** [comment]
@pushkar1397 why don't you use CSS and target the `swiper-button-disabled` class that gets added to the buttons when user is on the first or last slide?

**Comment by pushkar1397** [comment]
@hacknug I don't want to disable my buttons rather want to hide them.

**Comment by hacknug** [comment]
@pushkar1397 you can set `opacity: 0;` to hide them.
