### ISSUE TITLE
Lazy load issue and image caption doesn't work well with fade effect

### ISSUE THREAD

**Issue by v-hc** [nolimits4web/swiper#3850]
* Swiper Version: swiper-Swiper5-2

### What you did
Hi everyone, based on this swiper, I created a full screen image slider with fade effect, lazy laod and I added image captions to it. I only have basic skills in html, so please bare with me :)

`<html>
	
<head> 
	<style>
        .swiper-container {
        	min-width: 100%;
        	min-height: 100%; }

        .swiper-slide {
        	width: 100vw;
        	height: 100vh;
        	position: relative;
        	background-size: auto;
        	object-fit: cover; }

           .swiper-slide img {
        	width: 100vw;
        	height: 100vh;
        	display: flex; 
        	position: relative;
        	background-size: auto;
        	object-fit: cover;  }

      .image_caption {
             position: absolute;
             left: 40px;
             bottom: 25px;
             z-index: 5; }

	</style>
</head>
	
<body>
	
	<div class="swiper-container">
		<picture alt="" class="swiper-slide">
			
        	<source media="(max-width: 600px)"
        	data-srcset="images/Lorem.jpg"
        	/>
			
            <source media="(max-width: 1024px)"
            data-srcset="images/Lorem_mobile.jpg"
            />
			
            <img class="swiper-lazy"
            data-src="images/Lorem_low-res.jpg"
            />
			
            <div class="image_caption">Lorem Ipsum</div> 
			
        </picture>
	</div>  

 	<script src="js/swiper.js"></script>
	
  	<script>
    		var swiper = new Swiper('.swiper-container', {
        		preloadImages: false,
		       	lazy: true,
        		loop: true,
        		effect: 'fade',
       			autoplay: {
       		 	delay: 3000,
		  	disableOnInteraction: true,
		  	},
       		  	 keyboard: {
        		 enabled: true,
		  	 onlyInViewport: false,
       		  	 },
        		  navigation: {
        		  nextEl: '.swiper-button-next',
        		  prevEl: '.swiper-button-prev',
        		  },
    		});
	</script>
	
</body>	`

### Expected Behavior
A fullscreen slider with image captions that change whenever a new image appears. Also by implementing lazyload I was hoping that the low-res images loads first and is being replaced whenever the actually image is ready. Also image is being replaced for mobile screen

### Actual Behavior
Right now I have 2 issues:
1: The low res images is being loaded first but is not being replaced with the full res image. I am not sure if it might be because of the size of the image? The mobile image is works well though even though I am wondering here how to put a mobile low res image also in there since the image is different to desktop version
2. Image captions are moving with slides but unfortunately are overlapping always a bit due to the fade in effect. When I switch the animation to crossFade for example it works fine. I think the issue is with the Fade in Effect. However I couldn't find a solution how to fix it. I added a screenshot of the image captions overlapping. 
<img width="193" alt="Screenshot_image-caption" src="https://user-images.githubusercontent.com/72252057/94913098-f5377000-04a8-11eb-9d42-51e95202b05b.png">

Id be super grateful if someone of you can help to fix it. Thanks so much.

**Comment by ygj6** [comment]
@v-hc Could you provide the complete test code?

**Comment by claudiopedrom** [comment]
I'm having the same issue with `"swiper": "6.4.9"`. Anyone else?
