### ISSUE TITLE
centeredSlides on thumbs

### ISSUE THREAD

**Issue by denny7** [nolimits4web/swiper#3851]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.2
* Platform/Target and Browser Versions: macOS

### What you did
I'm using Swiper with react. I have main swiper and thumbs for it. I'm trying to center active thumb.

This is the code for main swiper: 
```
<Swiper
    grabCursor
    navigation={{
        nextEl: '.next-btn',
        prevEl: '.prev-btn'
    }}
    onSlideChange={this.handleSlideChange}
    onSwiper={swiper => this.swiper = swiper}
    initialSlide={post.initialSlide}
    threshold={6}
    thumbs={{swiper: this.state.thumbsSwiper}}
>
...
</Swiper>
```
... And this for thumbs: 
```
<Swiper
    onSwiper={thumbsSwiper => this.setState({thumbsSwiper})}
    watchSlidesVisibility
    watchSlidesProgress
    slidesPerView={12}
    spaceBetween={12}
    threshold={6}
    centeredSlides
    centeredSlidesBounds
>
```

### Expected Behavior
Expected active thumb to be centered if slides > slidesPerView.

### Actual Behavior
Now active slide only tries to be visible on screen. It never moves if is visible on screen. It moves only when grabbing.

**Comment by SeshadriKolluri** [comment]
I have the same issue. Any suggestions for a work around ?

**Comment by vltansky** [comment]
@SeshadriKolluri @denny7 demo would be very useful.
You can fork this one: https://codesandbox.io/s/swiper-react-fork-e7nwl

**Comment by JackCA** [comment]
I *beliece* I'm trying to solve the same problem and have recreated it [here](https://codesandbox.io/s/swiper-thumbs-gallery-react-forked-36si1?file=/src/App.jsx).

What I'd like to happen, is that the active thumbnail is always centered (unless it is the first 2 or last 2 in my above example).

Is there a way to natively achieve this?

**Comment by laurabennett** [comment]
Is this plugin still maintained? This is still an issue.
