### ISSUE TITLE
React-Swiper does not render slides on SSR when virtual slides are enabled

### ISSUE THREAD

**Issue by kije** [nolimits4web/swiper#3858]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.2
* Platform/Target and Browser Versions: macOS 10.15.6, Chrome 85.0.4183.121, Node v14.12.0, React 16.13.1.

### What you did
On a page I'm building with React/Gatsby, I've added Swiper React component and enabled the virtual option to virtualize the slides. 

```tsx
import SwiperCore from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import React, { CSSProperties, useCallback, useMemo, useState } from 'react';

export interface SlideData {
  [key: string]: any;

  id: string | number;
  image: UnifiedImage;
  imageAlt?: string | null;
}

export interface ImageSliderProps {
  transitionSpeed: number;
  slides: SlideData[];
}

const ImageSlider: React.FC<ImageSliderProps> = ({ slides, transitionSpeed}) => {
  const [swiper, setSwiperLocal] = useState<SwiperCore | null>(null);

  const swiperParams: Swiper = useMemo(
    () => ({
      allowTouchMove: true,
      grabCursor: true,
      lazy: false,
      longSwipesRatio: 0.38,
      onSwiper: setSwiperLocal,
      parallax: true,
      preloadImages: false,
      roundLengths: true,
      slidesPerView: 1,
      speed: transitionSpeed,
    }),
    [transitionSpeed, setSwiperLocal],
  );

  return (
    <Swiper {...swiperParams} virtual>
      {slides.map((data, index) => (
        <SwiperSlide
          key={data.id}
          virtualIndex={index}
        >
          <ImageSlideItem
            alt={data.imageAlt}
            image={data.image}
            index={index}
          />
        </SwiperSlide>
      ))}
    </Swiper>
  );
};
```

However, when I inspect the html output generated by SSR, no slides are prerendered. The slides get rendered only after rehydration/rerender of the react app, which is not ideal from a SEO/loading performance/UX perspective (the content of slides might not get indexed by search engines, and the browser can only start to download images in the slides after the whole react app has been rehydrated/rerendered. Also no content is shown to the user until the react app has been rehydrated/rerendered).

SSR output:
```html
<div class="hero-slider__SliderRoot-sc-1tlus63-1 bHovIv">
    <div class="swiper-container">
        <div class="swiper-wrapper"></div>
    </div>
</div>
```

### Expected Behavior
Virtualized slides should be rendered during SSR in the same way as they will be rendered on the initial render of the react app in the browser

### Actual Behavior
Virtualized slides don't get rendered during SSR. If I remove the virtualize option, the slides get properly rendered.

**Comment by nolimits4web** [comment]
It is by design, virtual slides feature uses `useEffect` so it won't work with SSR

**Comment by pr1ntr** [comment]
I am running into this issue now and I think in most cases you can just optionally render something like this without SSR upstream. However, many times a slider takes up some static amount of space on a page and if the user has to wait for it to render then it can create FOUC.  How could the module self-correct after the initial DOM is rendered with SSR? Does it care that the initial DOM elements already exist?

**Comment by kije** [comment]
FYI: I have implemented the following workaround for this now in my project:
During SSR, I render the Swiper component with virtual={false} and only the first two slides in it. Then, in the browser I render it with virtual={true} and all slides.

It seems to work, as the HTML that gets emitted during SSR with virtual={false} seems to be the same (or at least close enought) as the HTML that gets generated in the browser with virtual={true} without causing any wierd Rehydration issues. It also enables the browser to discover images and other assets linked in the slide early during page load and correctly layouting the page on the initial render

Nevertheless this solution seem a bit hacky to me

**Comment by pr1ntr** [comment]
no matter what I do, if i set virtual={true} the whole thing just disappears.

**Comment by supriome** [comment]
You can just use `next/dynamic` feature to dynamic import your components, so will not have this ssr problem.

See details on next.js documents [Dynamic Import](https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by dmitryshelomanov** [comment]
@supriome 
with SSR slidesPerView not working
And I see one big image and then slidesPerView
How to fix it ?

**Comment by trietjack** [comment]
@dmitryshelomanov same here, couldn't find a solution for it.

**Comment by Fatou77-spec** [comment]
@dmitryshelomanov, were you able to find a solution to this problem. I am currently having the same issue.
Please assist if you do.

**Comment by guillermodlpa** [comment]
What about this workaround to do SSR and the initial render without virtual, and then switch to virtual mode?

```js
const [virtualSlidesEnabled, setVirtualSlidesEnabled] = useState(false);
useEffect(() => {
  setVirtualSlidesEnabled(true);
}, []);

return (
  <Swiper
    key={virtualSlidesEnabled ? 'virtual' : 'non-virtual'} // key required to change to produce a re-render of the swiper
    modules={[Virtual]}
    virtual={
      virtualSlidesEnabled
        ? {
            enabled: true,
            addSlidesBefore: 1, // this are just example values
            addSlidesAfter: 2,
          }
        : false
    }
  >
    {...}
  </Swiper>
);

```

**Comment by dmitryshelomanov** [comment]
To fix it you need set width/height into css. I no finded another solution

**Comment by Austin1serb** [comment]
The component within the swiper needs to have max-width set. or it will take up the full size of its parent container: 
       ```
{articles.map((article, index) => (
          <SwiperSlide key={article.title + index}>
            <ArticleCard {...article} /
         style={{
                maxWidth: "300px",
              }}
>
          </SwiperSlide>
        ))}
```

Or you can target the Element in a Css file, I think the name of the class is just .swiper, and theres another one .swiper-wrapper.
