### ISSUE TITLE
Re-init instance in resize (custom build)

### ISSUE THREAD

**Issue by ametthey** [nolimits4web/swiper#3859]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 5.4.5
* Platform/Target and Browser Versions: Google Chrome, Firefox, Safari, any browsers
* Live Link or JSFiddle/Codepen or website with isssue: https://albinmetthey.fr/

I have created a slider with swiperjs 
```
let mySwiper = new Swiper ('.swiper-container', {
    direction: 'horizontal',
    mousewheel: {
        forceToAxis: false,
    },
    speed: 900
});
```
I have created a resize event to destroy the slider when it's under 768px 
```
const small = window.matchMedia( '( max-width: 768px )' ); // max-width: 768px;
const big   = window.matchMedia( '( min-width: 769px )' ); // min-width: 769px;
mySwiper.on( 'resize', () => {
    // If window is resize under 768px
    if ( small.matches === true ) {
        console.log('we are small');
        mySwiper.destroy( true, true );
    // If window is resize above 769px
    } else if ( big.matches === true ){
        console.log('we are big');
    }
});
```

I want to re-init swiperjs when we resize "up" meaning if big.matches === true
```
const myResizeSwiper = () => {
    let mySwiper = new Swiper ('.swiper-container', {
        direction: 'horizontal',
        mousewheel: {
            forceToAxis: false,
        },
        speed: 900
    }); 
}

const small = window.matchMedia( '( max-width: 768px )' ); // max-width: 768px;
const big   = window.matchMedia( '( min-width: 769px )' ); // min-width: 769px;
mySwiper.on( 'resize', () => {

    // If window is resize under 768px
    if ( small.matches === true ) {
        console.log('we are small');
        mySwiper.destroy( true, true );

    // If window is resize above 769px
    } else if ( big.matches === true ){
        console.log('we are big');
        myResizeSwiper();
    }
});
```

But it's not working, can you help me out ?

**Comment by nolimits4web** [comment]
You probably need to listen for resize events on window, not on swiper.

Closing as it is more a custom implementation question rather than swiper issue

**Comment by VadimGorbenko** [comment]
Hello,
I have something similar.
I cannot destroy Swiper multiple times.
I call `.destroy (false)`, after that I call `.init ()` aaand I cannot destroy anymore.
demo: https://jsfiddle.net/mrdecoy711/4c2jy7o6/10/

Steps: press EXTERMINATE, then press Init, then press EXTERMINATE again (doesn't work, no errors).
