### ISSUE TITLE
Pinch zoom should work on whole container (not only image)

### ISSUE THREAD

**Issue by yura3d** [nolimits4web/swiper#3860]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.2
* Platform/Target and Browser Versions: Android Chrome 85.0.4183.101, iOS Safari 14.0.1
* Live Link or JSFiddle/Codepen or website with isssue: https://swiperjs.com/demos/400-zoom.html

### What you did
Started to zoom from these positions of my fingers:

![IMG_20201008_111231](https://user-images.githubusercontent.com/10958696/95432391-463ade80-0957-11eb-9317-d56572c911d7.jpg)

### Expected Behavior
Zoom works

### Actual Behavior
Nothing happens

I think pinch zoom should work on whole gallery container like it works in Twitter and many other sites. Double tap zoom in Swiper works when I tap outside of image, so I don't understand why pinch zoom not.

When I start to zoom with 2 fingers on black area (outside of image), pinch zoom also works. So the only situation that should be fixed is when the 1st finger is on the image and the 2nd is out.

**Comment by cody1991** [comment]
have the same problem as you
