### ISSUE TITLE
Swiper React->Thumbs->onSwiper

### ISSUE THREAD

**Issue by FEMotong** [nolimits4web/swiper#3863]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
![](https://ftp.bmp.ovh/imgs/2020/10/d3d53f0c66e68257.png)
### Expected Behavior
Hope to trigger onSwiper event normally.
### Actual Behavior

onSwiper event is not triggered.

**Comment by stkaspar** [comment]
same here.
it won't fire to change the first slider

**Comment by nolimits4web** [comment]
Fixed by #4440
