### ISSUE TITLE
Can't scroll page vertically on horizontal Swiper area iOS

### ISSUE THREAD

**Issue by olso** [nolimits4web/swiper#3865]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.3
* Platform/Target and Browser Versions: iOS
* Live Link or JSFiddle/Codepen or website with isssue: Literally try any on demo swiper website
### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

### Expected Behavior
With horizontal Swiper, I should be able to scroll vertically on the page.

### Actual Behavior
![Screen recording](https://media.giphy.com/media/ctaLCYyO0wKi59oTFi/giphy.gif)

horizontal Swiper prevents vertical page scroll, resulting in horrible UX

https://github.com/kidjp85/react-id-swiper/issues/405

**Comment by olso** [comment]
fixed it with

```jsx
touchReleaseOnEdges
        threshold={5}
        mousewheel={false}
```

**Comment by christian-reichart** [comment]
@olso THANK you so much! This solved the issue for me. Was getting a bug report for "scrolling sometimes not working in app" and couldn't figure out why. In my opinion this is a bug (for iOS) or the threshold should have a default value.
