### ISSUE TITLE
Vertical slider with lazy loading not able to slide

### ISSUE THREAD

**Issue by JordanDDisch** [nolimits4web/swiper#3869]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.3#e0b2e27621c07e789bfa91569b5676e896d18001.

I have a vertical slider with these settings: 
```javascript
{
        Swiper,
        ref: thumbnailSwiperRef,
        modules: [Lazy],
        preloadImages: false,
        lazy: {
            loadPrevNext: true,
            loadPrevNextAmount: 4
        },
        spaceBetween: 20,
        slidesPerView: 'auto',
        direction: 'vertical',
        touchRatio: 0.2,
        loadOnTransitionStart: true,
        updateOnWindowResize: false
    }
```

The `.slideNext()` works fine without lazy loading.

What I can gather is that the maxTranslate set is not updating when I try to get the next image, which loads in via lazy loading.

Rather it remains the height/size of the visible elements.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4076759/95931982-53077880-0e16-11eb-8afa-ee77d0b9c7fe.gif)

<img width="459" alt="Screen Shot 2020-10-14 at 12 08 07" src="https://user-images.githubusercontent.com/4076759/95931998-5ac71d00-0e16-11eb-96a2-20a2168d2847.png">
<img width="461" alt="Screen Shot 2020-10-14 at 12 11 34" src="https://user-images.githubusercontent.com/4076759/95932025-6fa3b080-0e16-11eb-8efd-fcbc87bb90f0.png">

Here is a codepen example breaking without lazy loading:
https://codepen.io/JordanDDisch/pen/mdEeojm

**Comment by ygj6** [comment]
@JordanDDisch  Could you provide the test code with bugs?

**Comment by vltansky** [comment]
@JordanDDisch you forgot to wrap images with `.swiper-slide`
```html
<img class="thumbnailImage-32R" alt="" src="https://sc-staging.4wdsc.com/media/catalog/product/1/8/180731-new_big_daddy-reshoot-resized_13_of_15__1_126_1_1.jpg?auto=webp&amp;format=pjpg" width="180" height="180">
<img class="thumbnailImage-32R" alt="" src="https://sc-staging.4wdsc.com/media/catalog/product/1/8/180731-new_big_daddy-reshoot-resized_13_of_15__1_126_1_1.jpg?auto=webp&amp;format=pjpg" width="180" height="180">
```
should be
```html
<div class="swiper-slide">
  <img class="thumbnailImage-32R" alt="" src="https://sc-staging.4wdsc.com/media/catalog/product/1/8/180731-new_big_daddy-reshoot-resized_13_of_15__1_126_1_1.jpg?auto=webp&amp;format=pjpg" width="180" height="180">
</div>
<div class="swiper-slide">
  <img class="thumbnailImage-32R" alt="" src="https://sc-staging.4wdsc.com/media/catalog/product/1/8/180731-new_big_daddy-reshoot-resized_13_of_15__1_126_1_1.jpg?auto=webp&amp;format=pjpg" width="180" height="180">
</div>
```
see: https://codepen.io/vltansky/pen/VwjqKJP

**Comment by JordanDDisch** [comment]
@vltansky thanks for getting back to me and pointing that out. The example I gave you was not complete. Here is a more complete example using the [react version](https://codesandbox.io/s/black-grass-cdr3f?file=/src/App.js&resolutionWidth=320&resolutionHeight=675), with lazy loading enabled. The problem this time is that lazy loading is not working at all. Images are being fetched on page load. I'm not sure if this is because of the sandbox env or my config, but there was very little documentation on lazy loading for the react version. If my config is incorrect then the documentation is not up to date for the react version.

CC: @ygj6

**Comment by ygj6** [comment]
I tried to play with it, that's what I get:
https://codesandbox.io/s/frosty-frost-45uoh?file=/src/App.js
Is it works as you wanted @JordanDDisch?

**Comment by vltansky** [comment]
@JordanDDisch any news?

**Comment by NekoKetsu** [comment]
try to update swiper with yourSwiper.update() after loading

**Comment by JordanDDisch** [comment]
@vltansky yea, looks like @ygj6 example works fro what I was trying to do, thanks!
