### ISSUE TITLE
Swiper slides don't change

### ISSUE THREAD

**Issue by pgenderson** [nolimits4web/swiper#3874]
This is a (multiple allowed):
* [x] bug

I followed https://swiperjs.com/get-started (using the CDN links) and I see the first image and the arrows on both sides, but the image never changes. The images displayed stacked on top of each other fine before I started playing with sliders. I tried this yesterday so it's with the latest version with Firefox 81.0.2 and Ubuntu 20.04. I asked on StackOverflow and got no reply. [Pastebin](https://pastebin.com/NDjTGn1Y).

**Comment by ygj6** [comment]
@pgenderson The CDN links must be introduced before `new Swiper`.

**You should use it like this:**
```
<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
 <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
 <script>

   var mySwiper = new Swiper('.swiper-container', {
      // Optional parameters
       direction: 'vertical',
         ......
   })

</script>
```
Because the sliding direction is vertical, you can slide the picture up and down.
