### ISSUE TITLE
While loading shows second slide first

### ISSUE THREAD

**Issue by theskillwithin** [nolimits4web/swiper#3875]
(in GatsbyJS React so SSR might be cause)

when loading the page the second slide flashes first because the transform style (`transform: translate3d(-1407px, 0px, 0px); transition: all 0ms ease 0s;`)  isn't applied until later on .swiper-wrapper

once this style is applied after fully loading it then shows properly

**Comment by Ryuurock** [comment]
ssr issue: autoplay not work in my project
