### ISSUE TITLE
Virtual Slides is it possible to implement slidesPerView auto?

### ISSUE THREAD

**Issue by gabrielsze** [nolimits4web/swiper#3877]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I understand this is not the use case as asked here --> https://github.com/nolimits4web/Swiper/issues/2287

But I'm wondering if it is possible to handle this dynamically on the backend of the swiper API.

My use case is that I need the virtual slides, also the responsive nature of `slidesPerView: auto`. It will be really helpful to have such a feature, but I'm open to any potential workarounds if anyone has solutions to this too. Right now I have to handle breakpoints quite tediously if I don't get to use `slidesPerView: auto`.

Also having some troubles with responsively handling breakpoints since my swiper can be vertical as well. (mobile horizontal, desktop vertical)

Thanks in advance!

**Comment by ppbl** [comment]
It's OK for me to use decimals

Use (width of swiper container) / (width of single slide)

For example, here I am about 1.2

![image](https://user-images.githubusercontent.com/33046279/109125296-dce12e00-7786-11eb-911c-d785797cb760.png)
