### ISSUE TITLE
Breakpoints for vertical slider should be in height?

### ISSUE THREAD

**Issue by gabrielsze** [nolimits4web/swiper#3878]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Couldn't find this anywhere around, but won't my responsive `direction: vertical` slider be responsive with height instead of width? The aspect ratio helps but doesn't fully solve the problem. The height breakpoints could be potentially useful for tall screen sizes for vertical sliders.

**Comment by nolimits4web** [comment]
No, it still depends on browser/window width

**Comment by ymebrugts** [comment]
I would think the breakpoints should be vertical when a vertical layout is used. The slider takes more vertical space per added slide or each slide has less space vertically per added slide. In this instance height breakpoints are more useful I think.

**Comment by lmsantanam** [comment]
Hi! for anyone stumbling across this, I managed to set height breakpoints for a vertical slider using "BreakpointObserver" and "BreakpointState"

![image](https://user-images.githubusercontent.com/16975334/180921874-0e1b65a5-728b-4da4-9141-ab8a23dc7fe4.png)

Of course you will need a "SwiperOptions" object for this to work (the this.config element in the screenshot)
