### ISSUE TITLE
The modal closes when swiper is drag outside the container

### ISSUE THREAD

**Issue by hlyst21** [nolimits4web/swiper#3880]
Hello! Hi @nolimits4web ! I love your slider very much, I have been using it for a long time. But there was a problem when using swiper together with a modal. When I drag the slide outside the container, the modal closes. Thought there was a modal issue, but same behavior has been seen on several modal libraries. Please, tell me, maybe I don't see some parameter in the documentation that will allow you not to throw a click event on the modal overlay?

**Comment by nolimits4web** [comment]
Sorry, but have to close it as it is not related to Swiper directly

**Comment by hlyst21** [comment]
@nolimits4web Владимир извините, но проблема есть, и я никак не могу её решить. Если не трудно, можете дать направление, куда смотреть, чтобы решить эту проблему?
