### ISSUE TITLE
Using FreeMode in breakpoints param

### ISSUE THREAD

**Issue by ametthey** [nolimits4web/swiper#3882]
Is it possible to use the freeMode parameter in breakpoints ?

```
let mySwiperVertical = new Swiper( '.swiper-container-vertical', {
        direction: 'vertical',
        freeMode: false,
        navigation: {
            nextEl: '.swiper-button-down',
            prevEl: '.swiper-button-up',
        },
        breakpoints: {
            // when window width is >=599px
            599: {
                freeMode: true
            },
            // when window width is >=768px
            768: {
                freeMode: true
            },
            1440: {
                freeMode: false
            }
        },
        speed: swipeSpeed,
    });
```

it is currently not working for me :(

**Comment by ygj6** [comment]
@ametthey Could you provide the complete test code?

**Comment by ametthey** [comment]
Hello I found a solution !!!! thanks anyway :)

**Comment by vhbazan** [comment]
> Hello I found a solution !!!! thanks anyway :)

Hi @ametthey  can you share your solution please? I'm running into the same issue :) thanks!

**Comment by benben994** [comment]
Not sure if my code would help.
I was trying to let mobile version scroll step by step, and desktop version with scrolling while freeMode `true`.


`var swiper = new Swiper(".mySwiper", {
  scrollbar: {
    el: ".swiper-scrollbar",
  },
  direction: 'horizontal',
  mousewheel: true,
  freeMode: false,
  breakpoints: {
    992: {
      freeMode: {
        enabled: true,
        sticky: false,
      },
    }
  },
});`
