### ISSUE TITLE
[Svelte] - Failed to execute 'setAttribute' on 'Element': '640' is not a valid attribute name.

### ISSUE THREAD

**Issue by lamualfa** [nolimits4web/swiper#3884]
## What you did
I just use `breakpoints` props like this:

```js
<Swiper
    slidesPerView={1.3}
    spaceBetween={15}
    grabCursor
    autoHeight
    breakpoints={{ 640: { slidesPerView: 2.3 }, 768: { slidesPerView: 2.5 } }}>
    {#each data as rootSlide}
      <SwiperSlide>
        <Swiper simulateTouch={false} navigation autoHeight>
          {#each rootSlide.slides as slide}
            <SwiperSlide>
              <AspectRatio class="rounded-md pt-2/1">
                <img
                  src={slide.url}
                  alt="Sample"
                  class="object-cover w-full h-full" />
              </AspectRatio>
            </SwiperSlide>
          {/each}
        </Swiper>
        <h5 class="text-lg font-medium text-gray-900">{rootSlide.title}</h5>
      </SwiperSlide>
    {/each}
  </Swiper>
```

And if you resize the browser, you will get the following error:

![image](https://user-images.githubusercontent.com/39755201/96802481-20700800-1434-11eb-9ed9-864b19dcb495.png)

### Demo

You can go to the demo page, then go to the very bottom of the page titled **Gallery**. This is link of the demo: [Demo Page](https://frontend-ubs-usg-ac-id.lamualfa.vercel.app/)

## Version
- Swiper: `6.3.4`
- Svelte: `3.29.0`

**Comment by vltansky** [comment]
Can you prove a demo on stackblitz/github whenever you can give a source code. I can't reproduce it on localhost, although I can see a bug in your demo page.

**Comment by lamualfa** [comment]
@vltansky the code for the Swiper component is just that. You will find a bug if you resize your browser to the Mobile screen size.

### The Error

![image](https://user-images.githubusercontent.com/39755201/97800011-16d07680-1c64-11eb-8031-5231d845aa83.png)

<hr>

### The swiper component should look like this: (*using Swiper in Vanilla JS version*)

![image](https://user-images.githubusercontent.com/39755201/97800025-41baca80-1c64-11eb-8deb-7fa44815b920.png)

<hr>

### When using the Swiper in Svelte version:

![image](https://user-images.githubusercontent.com/39755201/97800074-bd1c7c00-1c64-11eb-8245-2be5609ed4e7.png)

**Comment by nolimits4web** [comment]
I can't replicate the issue as well

**Comment by nolimits4web** [comment]
I suggest issue is related to whatever in `<AspectRatio` component

**Comment by lamualfa** [comment]
@nolimits4web This following is the code of the `AspectRatio` component:

```svelte
<script>
  import cls from "clsx";

  export let ratioWidth;
  export let ratioHeight;
</script>

<div
  class={cls('relative h-0 overflow-hidden w-full', $$props.class)}
  style="padding-top: {(ratioHeight / ratioWidth) * 100}%">
  <div class="absolute top-0 left-0 w-full h-full">
    <slot />
  </div>
</div>
```
I think there's no problem here.
