### ISSUE TITLE
Now working on iphone 7 plus

### ISSUE THREAD

**Issue by vereskmio** [nolimits4web/swiper#3892]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 6.3.3.
* Platform/Target and Browser Versions: IOS 13.5.1. Browser 
* Live Link or JSFiddle/Codepen or website with isssue: https://obmena.club/catalog

### What you did
On xiaomi slider working https://prnt.sc/v7bvvu, but on ios is not working https://prnt.sc/v7bx7y
It is not compatible with iphone 7 Plus Safari Browser?

**Comment by nolimits4web** [comment]
It works in iOS, there is something on your side, probably with styling
