### ISSUE TITLE
Virtual Slides - Does not work with fade

### ISSUE THREAD

**Issue by pramach** [nolimits4web/swiper#3893]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 6.3.4.
* Platform/Target and Browser Versions: macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ....
* [https://jsfiddle.net/e9Lph4vs/](https://jsfiddle.net/e9Lph4vs/)

### What you did
When using virtual slides on a page with autoplay: true but only 1 slide at the time (slidesPerColumn: 1, slidesPerView: 1,) and using fading parameters
`
// fading effect
effect: "fade",
fadeEffect: { crossFade: true },
`

the result is unexpected ....
Slide 1 is shown, then after time passed slide 2 is shown, then after time passed again slide 3 is moved in and directly moved out, so screen is empty. after time passed by again, exactly same happen with slide 4 and 5 and ....

Issue can be reproduced.

Slider setup used (without fading):
>  $(document).ready(function () {
		//initialize swiper when document ready
		var mySwiper = new Swiper ('.swiper-container', {
			/* parameters with different value than default */
			// Duration of transition between slides (in ms)
			speed: 1400,
			// show hand on image
			grabCursor: true,
			// add visibility class to currently showing image
			watchSlidesProgress: true,
			watchSlidesVisibility: true,
			// continuous loop mode, does not work in virtual slide mode
			loop: false,
			// double click zoom into image
			zoom: false,
			// enable keyboard navigation prev/next
			keyboard: { enabled: true, onlyInViewport: true, pageUpDown: true, },
			// Navigation arrows
			navigation: { nextEl: '.swiper-button-next', prevEl: '.swiper-button-prev', hideOnClick: false, },
			// center image
			centeredSlides: true,
			centeredSlidesBounds: false,
			// autoplay
			autoplay: { delay: 3000, disableOnInteraction: true },
			autoplay: true,
			// virtual slides
			slidesPerColumn: 1,
			slidesPerView: 1,
			virtual: {
				cache: true,
				slides: (function () {
					var slides = [];
          for (var i = 0; i < 600; i += 1) {
            slides.push('Slide ' + (i + 1));
          }
					return slides;
				}()),
			},
		});

Actions done: Removed fading setup items

### Expected Behavior
Show slide 1, wait time passed, show slide 2, wait time passed, **show slide 3**, wait time passed, show slide 4, wait ....

### Actual Behavior
Show slide 1, wait time passed, show slide 2, wait time passed, **show slide 3 and move it out**, wait time passed, **show slide 4 and move it out**, wait ...

**Comment by pramach** [comment]
Btw, I've created a fiddle: [https://jsfiddle.net/e9Lph4vs/](url)

Which is based 1:1 on [https://github.com/nolimits4web/Swiper/blob/master/demos/410-virtual-slides.html#L105](url)
just ...
- enhanced with fade
- enhanced with autoplay
- changed slidesPerView from 3 to 1

And it has exactly same effect as I described above, starting with slide number 3.

**Comment by ygj6** [comment]
@nolimits4web This issue has been resolved. Could you please take some time to review the PR?

**Comment by pramach** [comment]
Checking tonight .... Thanks for fix so far.

**Comment by pramach** [comment]
Sorry but I'm somehow unable to create a slider.js based on DEV package on my own.
When running npm, it fails due to outdated babel, and when update babel to babel-cli it claims that the babel command is not found ....
Therefore I am not able to test ....
