### ISSUE TITLE
Virtual slides - Does not work with <img data-src

### ISSUE THREAD

**Issue by pramach** [nolimits4web/swiper#3894]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 6.3.4
* Platform/Target and Browser Versions: macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ....
* Live Link or JSFiddle/Codepen or website with isssue: not available yet due to clients testing

### What you did
Tried to fill the virtual slide array with something like:
`<div class='swiper-slide' data-title='image text' ><img data-src='my image url and image name small.png' data-srcset='my image url and image name BIG.png 1200w'></div>
`
This does not work.

When filling the array with
`<div class='swiper-slide' data-title='image text' ><img src='my image url and image name small.png'></div>
`
it works.

### Expected Behavior
data-src Image is shown

### Actual Behavior
Image is not shown when using data-src

To be honest I do not now if it is a bug or data-src has just not been implemented. But in API-Docu I did not find anything against. Therefore feel free to change to a feature request please.

**Comment by nolimits4web** [comment]
https://swiperjs.com/api/#lazy
