### ISSUE TITLE
Keyboard navigation with onlyInViewport: true triggers slide change in hidden swiper

### ISSUE THREAD

**Issue by acromatica** [nolimits4web/swiper#3895]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v6.3.4
* Platform/Target and Browser Versions: macOS 10.15.7 Google Chrome 86.0.4240.80
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/acromatica/pen/jOrBeex

### What you did
I added a swiper with enabled keyboard control and onlyInViewport parameter set to true. After that I've hidden the swiper, but I still see slideChange event being triggered when I press arrow keys.

### Expected Behavior
Slides shouldn't change when the swiper is hidden and onlyInViewport parameter set to true.

### Actual Behavior
slideChange event is being triggered when arrow keys are pressed.

**Comment by vltansky** [comment]
fixed by #3922

**Comment by waleedart** [comment]
Dear Sir,
Please unsubscribe me from this list.
Thanks,
Waleed
    On Saturday, January 23, 2021, 09:20:55 PM GMT+4, Vlad Tansky <notifications@github.com> wrote:  
 
 


Closed #3895.
