### ISSUE TITLE
Make a light version of Swiper

### ISSUE THREAD

**Issue by simplenotezy** [nolimits4web/swiper#3901]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Swiper should have a lightweight version. I just checked bundle size on https://bundlephobia.com/result?p=swiper@6.3.4 and it's quite high - 30kb.

Currently we are using Siema, which unfortunately isn't developed on anymore, but it's quite simple and effective, and yet it's only 3 kb (almost 100% less).

Is this in the plans?

**Comment by nolimits4web** [comment]
You can create custom build or use only modules you need https://swiperjs.com/api/#custom-build
