### ISSUE TITLE
Remove arrows outline after pressing the arrow on mobile

### ISSUE THREAD

**Issue by 91DarioDev** [nolimits4web/swiper#3902]
I don't understand why on mobile devices after you press the arrow it gets outlined. Is there some setting to remove it? 
I attach a screenshot.
Thanks 

https://postimg.cc/WDz2yhD6

**Comment by vltansky** [comment]
It's css of your page. Just cancel the outline effect with styles e.g:
```css
.some-class:focus{ outline: none; }
```
See https://css-tricks.com/almanac/properties/o/outline/

**Comment by 91DarioDev** [comment]
Than you !

**Comment by nolimits4web** [comment]
Closing as not really an issue
