### ISSUE TITLE
There is some shivering while flipping in mozila

### ISSUE THREAD

**Issue by Elabbasy00** [nolimits4web/swiper#3903]
Here's a vertical image slide that flips smoothly in Chrome but vibrates most of the time in mozila. Is this a normal bug in Mozilla?
http://ibc-live.herokuapp.com/

**Comment by akashlama1998-icloud** [comment]
Any follow up on this? I'm having the same issue. Works great in Chrome, Safari even Edge 😆  (the old one). But in firefox, swiper just shakes and shivers a lot.
