### ISSUE TITLE
swiper/react: when string instead of number passed to spaceBetween parameter, swiper is not able to change active slide

### ISSUE THREAD

**Issue by MaxKuzya** [nolimits4web/swiper#3908]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.4
* Platform/Target and Browser Versions: Windows Chrome 86.0.4240.111

### What you did

Put string `"12"` instead of the number `12`

```
<Swiper
  spaceBetween="12"
  slidesPerView="auto"
>
  {items.map((item) => (
    <SwiperSlide key={item.slug}>{this.renderItem(item)}</SwiperSlide>
  ))}
</Swiper>
```

### Expected Behavior
Swiper can change active slide OR throw an error/warning

### Actual Behavior
You can drag swiper, but the active slide won't change. Neither via grabbing, nor `swiper.slideTo`, nor `swiper.slideNext` etc methods

**Comment by nolimits4web** [comment]
https://swiperjs.com/api/#parameters

Because it must be a number
