### ISSUE TITLE
Drag issue, scrollbar not working properly either

### ISSUE THREAD

**Issue by Braunson** [nolimits4web/swiper#3910]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: Windows 10 / Chrome latest
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/xa7w2rup/3/

### What you did
Added slider, it drags way before and past the content and stays there. Also scroll bar doesn't work

### Expected Behavior
Shouldn't allow dragging way before or way after (to the point no content is shown in the slider)

### Actual Behavior
Allows dragging before and after the content forever it seems. Scroll bar doesn't work. View the image below:

![Example](https://user-images.githubusercontent.com/577273/97731988-3a50c100-1aac-11eb-86cd-4879e95e3ef9.gif)

**Comment by vltansky** [comment]
Try to remove `centeredSlides: true,` (or make it false) on line 13

**Comment by ygj6** [comment]
@Braunson Change the zoom ratio of the browser and everything will return to normal.

**Comment by Braunson** [comment]
@ygj6 It's not zoomed in? Tried it regardless, same issue.

**Comment by vltansky** [comment]
I can't reproduce it. (latest chrome). Working fine for me without centeredSlides.
https://stackblitz.com/edit/web-platform-c2srbg
![image](https://user-images.githubusercontent.com/5851280/97799134-ba099780-1c34-11eb-8d8f-f265d483b251.png)

**Comment by Braunson** [comment]
@vltansky I've removed `centeredSlides` on jsfiddle and the issue still persists for me https://jsfiddle.net/Braunson/g4t69faz/ I can confirm it persists for many other users as well. It seems to happen intermittently as well.

**Comment by vltansky** [comment]
So you have this bug in stackblitz I've sent too?
https://jsfiddle.net/Braunson/g4t69faz/

**Comment by Braunson** [comment]
@vltansky Yes intermittently. My test method, refresh, drag to right, refresh, drag to right. It'll happen on random refresh's.

**Comment by ygj6** [comment]
@Braunson 
Delete the `hidden` of following code, may work well.

### From
```
" class="relative mx-auto flex flex-row hidden" :class="{ 'hidden' : ! isLoaded }">
```

### To
```
" class="relative mx-auto flex flex-row" :class="{ 'hidden' : ! isLoaded }">
```

**Comment by Braunson** [comment]
@ygj6 You have have resolved it. I've also swapped `hidden` for `invisible` (to hide the content before it renders as it makes the page long and doesn't look great). Thanks!
