### ISSUE TITLE
Feature: Giuhub Action support.

### ISSUE THREAD

**Issue by ygj6** [nolimits4web/swiper#3914]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Does this repository need to add the Github Action?  If need, I could submit a Pull Requests.

**Comment by nolimits4web** [comment]
Thank you, but it is not needed here

**Comment by vltansky** [comment]
@nolimits4web Travis seems slow to me compared to GitHub actions, don't want to try?

**Comment by nolimits4web** [comment]
@vltansky I don't have experience with it. What will it do, I mean how will it be different with Travis?

**Comment by vltansky** [comment]
@nolimits4web almost no difference from the usage perspective. 
I've read that Travis now has a long queue, I saw a lot of OOS projects moving to Github Actions,
https://twitter.com/andrey_sitnik/status/1326872688045023232 - read the comments
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

If you want you can leave Github Actions along with Travis CI for a while to make sure that it works fine. Although it just running `npm test`, not sure it's needed. But it's up to you.

**Comment by nolimits4web** [comment]
Ok, we can try it then
