### ISSUE TITLE
renderNavigation prop needed

### ISSUE THREAD

**Issue by niklasp** [nolimits4web/swiper#3915]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5

### What you did
I tried to render custom navigation arrows in react. Problem is, that classNames like disabled are not passed to the components. I tried setting, the `navigation.nextEl` to a valid css selector, as well as to a react Component.

### Expected Behavior
There are swiper options for `renderBullet`, `renderFraction`, ... that accept classnames in a function. We would need one for `renderNavigation` as well.

**Comment by niklasp** [comment]
related #3855 #3788

**Comment by nolimits4web** [comment]
There is no anything related to rendering navigation. Just pass valid CSS selectors to navigation.nextEl and navigation.prevEl and put corresponding elements inside of the Swiper

**Comment by niklasp** [comment]
It is not working in react. I tried with css selector and with ref. Can you give a working example?
