### ISSUE TITLE
swiper/vue missing type declarations

### ISSUE THREAD

**Issue by honzabilek4** [nolimits4web/swiper#3916]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I see that Swiper has already types for `swiper/react` component included. I would be really cool to add type definitions for `swiper/vue` component as well. This would allow us to integrate swiper in vue.js projects with typescript easier.

<img width="328" alt="Screenshot 2020-11-03 at 8 35 50" src="https://user-images.githubusercontent.com/7890555/97959929-ab47ef80-1db0-11eb-8c2e-dbf5db535452.png">

I'm willing to work on this feature with a little guidance from maintainers.

* Swiper Version: v3.6.5
* Platform/Target and Browser Versions: Typescript

**Comment by GerryWilko** [comment]
If this helps anyone I wrote a skeleton typings file to get it to atleast work with a typescript vue project:

## swiper-t.d.ts
```typescript
declare module 'swiper/vue' {
  import _Vue from 'vue';

  export class Swiper extends _Vue {}

  export class SwiperSlide extends _Vue {}
}
```

**Comment by vltansky** [comment]
@GerryWilko you're welcome to contribute :)

**Comment by GerryWilko** [comment]
@vltansky Apologies I meant to come back to this and create a PR. I just dropped this in as a comment temporarily. I'll raise a PR tomorrow! 😀

**Comment by GerryWilko** [comment]
I've raised a PR for this file. I did a bit of testing and it didn't seem to affect the React typings.

**Comment by NabilFr** [comment]
In the meantime, how we can use swiper in vue 3/typescript project?

**Comment by david50407** [comment]
@NabilFr use this shim:

```typescript
declare module 'swiper/vue' {
  import { DefineComponent } from 'vue'

  export const Swiper: DefineComponent<any, any, any>
  export const SwiperSlide: DefineComponent<any, any, any>
}

```

**Comment by giuliano-oliveira** [comment]
@david50407 I think you should make a PR with this shim :eyes:

**Comment by david50407** [comment]
@giuliano-oliveira this shim only provides simple definition of `swiper/vue` module without details (like props, slots, etc)
IMO, this shim is a workaround, this project still need full type definitions for Vue.

**Comment by nicojmb** [comment]
Please, add full typscript support on vue in future releases.

**Comment by ianoble** [comment]
Was this closed because typescript support was added?

**Comment by MrTimscampi** [comment]
The proper (i.e. more maintainable) way to do this would probably be to convert the component to TypeScript.

Having separate, manually written typings is a recipe for disaster in the long run, imo.

I'd be willing to work on the conversion, if the maintainers are okay with it. I'll do some preliminary exploration on my end, based on how the Angular component builds itself, and report back once I have something.

**Comment by lizy0329** [comment]
Version: "swiper": "7.3.4"
has declare module 'swiper/vue'  shim? No, but if add, it work.

Still error! Type '{ delay: number; }' is not assignable to type 'undefined'.ts(2322).

![image](https://user-images.githubusercontent.com/9499272/147227964-12c9a5da-8e6b-4d0c-8d90-7da490b34256.png)
