### ISSUE TITLE
Does not work in IE10

### ISSUE THREAD

**Issue by rediska1114** [nolimits4web/swiper#3917]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: React, IE10
* Live Link or JSFiddle/Codepen or website with isssue: demos https://swiperjs.com/demos/

### What you did and 
I opened the demo in IE10 and got the error "TypeError: Object doesn't support property or method 'children'"

**Comment by vltansky** [comment]
In README written:

> Swiper - is the free and most modern mobile touch slider with hardware accelerated transitions and amazing native behavior. It is intended to be used in mobile websites, mobile web apps, and mobile native/hybrid apps.
> 
> Swiper is not compatible with all platforms, it is a modern touch slider which is focused only on modern apps/platforms to bring the best experience and simplicity

IE 10 & 11 not supported by default.
You can try adding polyfills: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children
```js
// Overwrites native 'children' prototype.
// Adds Document & DocumentFragment support for IE9 & Safari.
// Returns array instead of HTMLCollection.
;(function(constructor) {
  if (constructor &&
    constructor.prototype &&
    constructor.prototype.children == null) {
    Object.defineProperty(constructor.prototype, 'children', {
      get: function() {
        let i = 0, node, nodes = this.childNodes, children = [];
        while (node = nodes[i++]) {
          if (node.nodeType === 1) {
            children.push(node);
          }
        }
        return children;
      }
    });
  }
})(window.Node || window.Element);
```

But probably you will need more then only this polyfill.

**Comment by rediska1114** [comment]
@vltansky 

I've tried this polyfill before and it doesn't fix the error.(sample code here https://jsfiddle.net/y0b3uv9L/1/) 
The error points to the line
 ```
 $wrapperEl = $el.children("." + swiper.params.wrapperClass);
```
 which uses JQuery. Tell me, is it necessary to additionally include JQuery when using a library in React?

**Comment by vltansky** [comment]
No, you don't need jQuery. Swiper uses `dom7` that is included in the bundle.
Seems like children error coming form dom7. If you're using a webpack try to configure your webpack to transpile to es5.
See: https://github.com/nolimits4web/swiper/issues/3199#issuecomment-531185060
Add this to your webpack:
```js
module: {
  rules: [
    {
      test: /\.(js|jsx)$/,
      use: 'babel-loader',
      include: [
        resolvePath('node_modules/swiper'),
        resolvePath('node_modules/dom7'),
        resolvePath('node_modules/ssr-window'),
      ],
    },
    ...
  ...
}
```
I don't have much experience with react, so it's just a suggestion.
But something similar worked for me in Angular: https://github.com/zefoy/ngx-swiper-wrapper/issues/263#issuecomment-640176258

**Comment by nolimits4web** [comment]
Sorry, had to close it as @vltansky mentioned:

> IE 10 & 11 not supported by default.
