### ISSUE TITLE
Swiper React: Mapping Swiper Slide Not Working When Reload

### ISSUE THREAD

**Issue by muhammadadamfirdaus** [nolimits4web/swiper#3919]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5.
* Platform/Target and Browser Versions: MacOS, Chrome 86.0.4240.111.

### What you did
Hello, when this code load for the first time, Swiper seems doesn't init, must be changed to the other view on developer tools in order to works.
```import React, { useEffect, useState } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, { Navigation, Pagination, EffectCoverflow } from 'swiper';

import 'swiper/swiper-bundle.css';

function HomeSlider(){
  SwiperCore.use([Navigation, Pagination, EffectCoverflow]);

  useEffect(() => {
    HomeHeadlineImages();
  }, []);

  const [movies, setMovies] = useState([]);
  
  const HomeHeadlineImages = async () => {
    const weeklyMovies = await `fetch('https://api.themoviedb.org/3/trending/movie/week?api_key=xxxxxxx');`
    const weeklyRecommendation = await weeklyMovies.json();
    // console.log(weeklyRecommendation.results);
    setMovies(weeklyRecommendation.results);
  }

  const slides = [];
  movies.slice(0,5).map(movie => (
    slides.push(
      <SwiperSlide key={movie.id}>
        <img src={`https://image.tmdb.org/t/p/w500/${movie.backdrop_path}`} alt=""/>
      </SwiperSlide>
    )
  ));

  return (
    <div>
      <div className="headline-home">
        <Swiper id="headline" navigation pagination effect="coverflow">
          {slides}
        </Swiper>
      </div>
    </div>
  )
}

export default HomeSlider;
```
<img width="1022" alt="Screen Shot 2020-11-04 at 00 01 21" src="https://user-images.githubusercontent.com/16989223/98017032-497b9a00-1e31-11eb-87a0-932b408d7be0.png">
<img width="639" alt="Screen Shot 2020-11-04 at 00 04 05" src="https://user-images.githubusercontent.com/16989223/98017155-70d26700-1e31-11eb-9434-33d27dfa9dd1.png">
There's no extra properties like when Swiper worked (prev, active, next, etc).

### Expected Behavior
<img width="631" alt="Screen Shot 2020-11-04 at 00 07 41" src="https://user-images.githubusercontent.com/16989223/98017429-cf97e080-1e31-11eb-9ef8-5625b2a97be6.png">
Worked only when we change window, not first load.

Did I missing something?
Thanks.

**Comment by hackers267** [comment]
Make sure that when you get the new slides  datas you can init a new `Swiper`. For example:
```
return (
    <div>
      <div className="headline-home">
        {
         slieds.length ? (
         <Swiper id="headline" navigation pagination effect="coverflow">
          {slides}
        </Swiper>
         ) : null
        }
      </div>
    </div>
  )
```

**Comment by vltansky** [comment]
@muhammadadamfirdaus still relevant?

**Comment by GuiSelair** [comment]
Same problem

**Comment by marioloncarek** [comment]
Havin the same problem, did anyone managed to fix it? @muhammadadamfirdaus @vltansky @GuiSelair

**Comment by ankurpiparsania** [comment]
We are see this problem still. did you manage to find a soultion?

**Comment by israelcena** [comment]
Same problem

**Comment by Abdulrhman-AL-Samrrae** [comment]
same problem here , the dom tree for the swiper remove all the controls , some time it work like overflow-x scroll and no else work only if reload the page some time it work some time still the same .

**Comment by apolaina-ineat** [comment]
Same problem

**Comment by OmarBakr2020** [comment]
Same Problem

**Comment by mitesh-200228** [comment]
same problem

**Comment by mitesh-200228** [comment]
@OmarBakr2020 issue is still coming after adding observer values

**Comment by OmarBakr2020** [comment]
@mitesh-200228 I haven't looked for another solution for this problem, Mine worked for me, but I'll try to look for another workaround for it

**Comment by OmarBakr2020** [comment]
@mitesh-200228 my solution was to add `observer={true} observeParents={true} pagination={true}` attributes to `<Swiper>` tag

**Comment by mitesh-200228** [comment]
not working for me, but still thank you

**Comment by OmarBakr2020** [comment]
Sorry for that!

**Comment by Sadnan-2019** [comment]
please any one can help time west for us

**Comment by MarcinFilipek** [comment]
I had the same problem. See if you have the same keys in swiper childrens.

**Comment by dev-44** [comment]
Same problem

**Comment by PouryaMontakhab** [comment]
same problem!

**Comment by undefln3d** [comment]
Same problem

**Comment by mayconmesquita** [comment]
Same problem

**Comment by buithanhnhan76** [comment]
this works for me ! thank you very much !

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
