### ISSUE TITLE
Lazy loading / watchSlidesVisibility are not working if swiper is position fixed

### ISSUE THREAD

**Issue by yingban** [nolimits4web/swiper#3921]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.0.
* Platform/Target and Browser Versions: macOS, CHROME.

### What you did
Hi,

I have a Swiper with is toggle and following CSS position:
`{
position: fixed,
left: 0,
top: 0,
width: 100vw,
height: 100vh
}`

and the following options 
` swiperOptions: {
          // Disable preloading of all images
          preloadImages: false,
          // Enable lazy loading
          watchSlidesVisibility: true,
          watchOverflow: true,
          lazy: {
            loadPrevNext: true,
            loadPrevNextAmount: 2
          },
          keyboard: {
            enabled: true,
            onlyInViewport: true,
          },
          autoUpdate: true`
}

### Expected Behavior
I expect that slide 4 image will be lazy loaded

### Actual Behavior
On Chrome, if I resize the window, the slides after n + 2 get loaded, otherwise it seems the watcher is not working well.

Thank you for your help
Regards

**Comment by vltansky** [comment]
@yingban demo would really help :)

**Comment by yingban** [comment]
Hi @vltansky 

Sorry for my late reply. I was staffed on others projects.
Here is the demo https://stackblitz.com/edit/ebdmc3?file=index.html

I just toggle the swiper wrapper style (display and visibility).
I hope it will help.

Regards
