### ISSUE TITLE
pager has no data

### ISSUE THREAD

**Issue by AKclown** [nolimits4web/swiper#3924]
question：
    I added a pager but it has no data . I checked the document and found no solution

Source code：
![image](https://user-images.githubusercontent.com/33648653/98223688-6fb64c80-1f8d-11eb-8c27-644f7aaeec5a.png)

debugging：
![image](https://user-images.githubusercontent.com/33648653/98223778-8eb4de80-1f8d-11eb-8343-2016560413e5.png)

How to solve it? thanks you

**Comment by nolimits4web** [comment]
You don't need `pagination.el` parameter

**Comment by vltansky** [comment]
@AKclown see example:
https://stackblitz.com/edit/react-s5f6wz?file=src/App.js

**Comment by AKclown** [comment]
> @AKclown see example:
> https://stackblitz.com/edit/react-s5f6wz?file=src/App.js

Thanks for your answers. This is useful for me
