### ISSUE TITLE
Swiper lazyload loads images outside viewport

### ISSUE THREAD

**Issue by rhandrade** [nolimits4web/swiper#3928]
I'm using Swiper with lazyload to create rich carousels and improve usability. But I noticed the Swiper loads the first image of slider no matter when or not is visible or in viewport. This creates a strange behavior and is detect by Google Pagespeed / Lighthouse. Images on website footer is loaded together in page load.

This is a: bug.

* Swiper Version: 6.1.2
* Platform: macOS, Windows, iOS, Android on Chrome / Firefox / Edge
* Browser Versions: Chrome, Firefox, Edge, Safari
* JSFiddle: https://jsfiddle.net/gnzqou49/

### What you did
Implements Swiper with lazyload to prevent images outside viewport to impact page load. The code below show options set for Swiper. The code is based on Lazyload example available in Swiper website.

```javascript
var swiper = new Swiper('.swiper-container', {
  preloadImages: false,
  watchSlidesProgress: true,
  watchSlidesVisibility: true,
  lazy: {
    loadOnTransitionStart: true,
  },
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
  },
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },

});
```

### Expected Behavior
Swiper carousel is initiated and just first image (or nexts if enabled) inside viewport / visible is loaded.

### Actual Behavior
Swiper carousel is initiated and  first image (or nexts if enabled) is loaded even not visible or outside viewport.

**Comment by vltansky** [comment]
fixed in #3955
