### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by baldemarch** [nolimits4web/Swiper#393]
I have found very useful for mobile navigation, but also I'm having this issue with an iframe for embeding youtube videos.

I just can't get to work the swipe over the iframe unless I put a pointer-events: none; property on the css but then I can't get to play/pause the video inside the iframe.

I haven't found any solution to this and I'm guessing I'm not the only one having this issue.

So, please, can you help us with this?

We would be very grateful!

**Comment by jcfrancisIII** [comment]
I put the video in a popup outside the slider-wrapper and it was a quick fix. I considered all of the other solutions way too complicated.
