### ISSUE TITLE
Not working with vuejs.

### ISSUE THREAD

**Issue by Venegrad** [nolimits4web/swiper#3930]
![image](https://user-images.githubusercontent.com/9676703/98380767-a8b7f500-2051-11eb-922c-b336189c1426.png)
![image](https://user-images.githubusercontent.com/9676703/98380807-b53c4d80-2051-11eb-988b-1ad09d982663.png)

**Comment by Venegrad** [comment]
![image](https://user-images.githubusercontent.com/9676703/98380875-d604a300-2051-11eb-98d9-0975c1399670.png)

**Comment by nolimits4web** [comment]
https://swiperjs.com/vue/

> Swiper Vue.js components are compatible only with new Vue.js version 3
