### ISSUE TITLE
Slides not ready after initializing swiper after destroying it

### ISSUE THREAD

**Issue by jenemde** [nolimits4web/swiper#3931]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.0 and higher
* Platform/Target and Browser Versions: Independent of platform/browser

### What you did
Initializing the swiper, it works fine. The new a11y options for the slides can be set and they are shown in the DOM.
After destroying the swiper and initializing it again, everything works fine, except the a11y options for the slides. Looking deeper into the code, the array swiper.slides is empty in src/components/a11y/a11y.js:
```
    // Slide
    if (params.itemRoleDescriptionMessage) {
      swiper.a11y.addElRoleDescription($(swiper.slides), params.itemRoleDescriptionMessage);
    }
    swiper.a11y.addElRole($(swiper.slides), 'group');
    swiper.slides.each((slideEl) => {
      const $slideEl = $(slideEl);
      swiper.a11y.addElLabel($slideEl, `${$slideEl.index() + 1} / ${swiper.slides.length}`);
    });
```

This only happens after destroying the swiper using swiper.destroy() and initializing it again with swiper=newSwiper(...) with the same parameters without page reload. All a11y parameters work fine, only the ones for the slides are not applied because the slides are not there. It takes some milliseconds (works with tested timeout of 10 ms for 
```
swiper.a11y.addElRoleDescription($(swiper.slides), params.itemRoleDescriptionMessage);
```
).

Do you have an idea why this happens? Or even better an idea how to fix it?

**Comment by nolimits4web** [comment]
Would be good to see live demo on codepen, codesandbox, etc.

**Comment by jenemde** [comment]
Sorry for my late answer. I tried to reproduce the issue in codesandbox, but the problem does not show up there. So the issue is most likely to be found in our code ...
Please feel free to close this issue :)

**Comment by nolimits4web** [comment]
Thanks for getting back. If you can replicate issue in isolated env, you can create a new one then
