### ISSUE TITLE
vue methods are not loaded when looping

### ISSUE THREAD

**Issue by zababurinsv** [nolimits4web/swiper#3938]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 5.3.8.
* Platform/Target and Browser Versions:  CHROME.

### What you did

```
<swiper>
<component1 />
<component2 />
<component3 />
</swiper>
```

In component3 i create button for run video
Button is all time work except for the transition from the last slide to the first.
But if I move the slide a little the methods start to work

### Expected Behavior
Is it possible to automatically update the slide methods before going from the last slide to the first ?

**Comment by nolimits4web** [comment]
That is due to the nature of how looping works - it duplicates slides in DOM. It is solved in Swiper 6.x Vue plugin
