### ISSUE TITLE
Mouse wheel scroll to page when bounds reached

### ISSUE THREAD

**Issue by strarsis** [nolimits4web/swiper#3939]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

When scrolling using the mousewheel over a swiper slider with mousewheel enabled, 
the page should receive the scroll events when the bounds of slider have been reached (with loop disabled).
E.g. a vertical slider is scrolled upwards using the mousewheel, when the first slide is reached, 
there is no further scrolling of slides possible, then the page should get the scroll events.

**Comment by nolimits4web** [comment]
https://swiperjs.com/api/#mousewheel

releaseOnEdges | boolean | false | Set to true and swiper will release mousewheel event and allow page scrolling when swiper is on edge positions (in the beginning or in the end)
-- | -- | -- | --
