### ISSUE TITLE
Disable extra copies of rendered slides?

### ISSUE THREAD

**Issue by pingram3541** [nolimits4web/swiper#3942]
Is there a way to disable the rendering of extra slides altogether?  

My issue, I have 2 slides, one is basic html and the other is an iframe with a video embed.  When it renders, I have 6 total slides in the underlying html, 3 copies of each and even though only 2 slides are ever shown, when the video in my iframe slide is played, all 3 rendered versions play back at the same time (1 visible, 2 hidden).  

Unfortunately I do not have control over the content originating within the iframe and this slide duplication features causes an undesired user experience in this regard.  Thanks.

**Comment by nolimits4web** [comment]
If you use `loop` then there it works like that, with duplicating.
