### ISSUE TITLE
SlideChange event always fires with prependSlide method

### ISSUE THREAD

**Issue by ali-adlah** [nolimits4web/swiper#3945]
I download the slider images with Ajax then I update the slider with the method mySwiper.prependSlide(slides) but the slideChange event has always fired without changing the current slide

**Comment by vltansky** [comment]
@ali-adlah can you make a demo?

**Comment by nolimits4web** [comment]
It is be design, because active slide (particularly `activeIndex`) actually changes when you prepend slide

**Comment by ali-adlah** [comment]
I can not making a Demo but ich write this code 
getImagesCunks(rsArticleId,targetIndex,-1,chunksLength,iSwipeDirection,draftId).done(function(data){
	//mySwiper.off('slideChange');		
	for(i = data.ARRIMAGESDATA.length - 1; i >= 0; i--){
		var myCounter = data.ARRIMAGESDATA[i].IIDX +1 ;
		mySwiper.prependSlide('<div class="swiper-slide"><div class="swiper-zoom-container"><img class="swImg" 
                        src="'+data.ARRIMAGESDATA[i].URL+'" data-counter="'+ myCounter +'" data-imgid="'+ 
                   data.ARRIMAGESDATA[i]. 
                        IIMGID +'"/></div>\
			<div class="swSubline">' +data.ARRIMAGESDATA[i].SBLN+ '</div></div>');
	}
	mySwiper.update();
	//mySwiper.on('slideChange', slideChangeHandler);
});
