### ISSUE TITLE
[Vue-Swiper] instance destroyed before transition end.

### ISSUE THREAD

**Issue by stephanedemotte** [nolimits4web/swiper#3951]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: OSX / Chrome

### What you did
Create a simple swiper with the "vue" plugin, and use a leave transition

### Expected Behavior
When the leave transition begin, the swiper is destroyed....
So we saw a glitch before the transition finish.

[Video](https://streamable.com/d793fs)

```
<template>
<transition name="MyContainer">
  <div v-if="isActive" class="MyContainer">
    <Swiper>
      <SwiperSlide v-for="n in 10">{{n}}</SwiperSlide>
    </Swiper>
  </div>
</transition>
</template>

<script setup>
export { Swiper, SwiperSlide } from 'swiper/vue'
import { ref } from 'vue'
export const isActive = ref(false)
</script>

<style>
.MyContainer
  transition: opacity 1s
  &-enter-from,
  &-leave-to
    opacity: 0
</style>
```

**Comment by nolimits4web** [comment]
Well, from my understanding, Swiper gets destroyed in correct life cycle in `beforeUnmounted` https://github.com/nolimits4web/swiper/blob/master/src/vue/swiper.js#L317-L321

I see it more as a Vue issue, why it call this hook while components is still supposed to be in DOM for some time

**Comment by ThomasPof** [comment]
I tried to replace this `beforeUnmounted` event by the vue event `onUnmounted`, but it seems that vue fire the `onUnmounted` event before the transition ends...

**Comment by ThomasPof** [comment]
I updated `node_modules/swiper/esm/vue/swiper.js#577` as @nolimits4web did in his commit, it works perfectly on my vue project ! Thanks !!

**Comment by stephanedemotte** [comment]
@nolimits4web could be cool to have a release with this fix, i have to make this change avery time a make a new 'yarn update' :D
