### ISSUE TITLE
How do I use the slideTo method in Vue3.0?

### ISSUE THREAD

**Issue by lzj97** [nolimits4web/swiper#3953]
I would like to use the slideTo method in Vue3.0, but it doesn't seem to be available in Swiper.
Is there any way to achieve it? [https://codesandbox.io/s/interesting-hooks-1jblc?file=/src/App.vue](https://codesandbox.io/s/interesting-hooks-1jblc?file=/src/App.vue)

**Comment by nolimits4web** [comment]
You can retrieve swiper instance in `swiper` event https://swiperjs.com/vue/#swiper-events

**Comment by xjchenhao** [comment]
It seems that the current item cannot be switched by js
