### ISSUE TITLE
 Vue demo is not working.

### ISSUE THREAD

**Issue by ygj6** [nolimits4web/swiper#3956]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
**Execution command：**
```
npm run webpack:vue
```
### Expected Behavior

The command can be executed successfully.

### Actual Behavior
**Error:**
```
App.vue:8571 Uncaught Error: Cannot find module '../build/vue'
```

**Comment by nolimits4web** [comment]
Fixed in #3957
