### ISSUE TITLE
Swiper doesn't work at all on Firefox 

### ISSUE THREAD

**Issue by vipertechofficial** [nolimits4web/swiper#3960]
This is a:
* [x] bug

* Swiper Version: Released on: October 30, 2020
* Platform/Target and Browser Versions: Android and Fedora using Firefox on both
* Live Link or JSFiddle/Codepen or website with isssue: https://vipertech.ch/

### What you did
I integrate two Swiper that are perfectly working on Chrome.

### Expected Behavior
Work on Firefox too.

### Actual Behavior
Doesn't work on Firefox

Before you open an issue, please check if a similar issue already exists or has been closed before.
At one place I found that I could add 
`.swiper-wrapper {
    display: flex;
}
.swiper-slide { 
    display: table;
}`
But it still doesn't work.

You'll quickly see that it work on chrome but not on firefox, it seems like there is no script.

**Comment by vltansky** [comment]
It's not working in firefox not cause of swiper. (try https://swiperjs.com/demos/ with firefox)
See console error on your page:
```
ReferenceError: dialogPolyfill is not defined
```

You're using `<dialog>` element that is not supported by firefox
https://caniuse.com/dialog (also safari and many others).

You should add a polyfill: https://github.com/GoogleChrome/dialog-polyfill
I think this will fix it for you (see https://stackoverflow.com/questions/41334906/material-design-lite-dialog-render-in-safari-desktop-and-phone)

Anyway not related to swiper, so you should close the issue :)

**Comment by nolimits4web** [comment]
@vltansky thanks for checking. Closing as not related to swiper

**Comment by vipertechofficial** [comment]
Thanks, it really was material design lite that wasn't compatible with swiper without the dialog polyfill

**Comment by vltansky** [comment]
> Thanks, it really was material design lite that wasn't compatible with swiper without the dialog polyfill

It's not about compatibility, your js was failing before getting to the line where your init swiper. Try..catch would avoid it:)

**Comment by vipertechofficial** [comment]
> > Thanks, it really was material design lite that wasn't compatible with swiper without the dialog polyfill
> 
> It's not about compatibility, your js was failing before getting to the line where your init swiper. Try..catch would avoid it:)

Yes you're right but I mean, I did believe it would execute swiper js anyway even if the js fail at the polyfill things ^^
