### ISSUE TITLE
Issue with latest dom7 version and swiper

### ISSUE THREAD

**Issue by 719media** [nolimits4web/swiper#3963]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: Chrome 87, also latest Safari

I am unable to reproduce on codepen, because the reproduction only happens in a webpack build.

Basically I noticed that the swiper "EffectFade" stopped working one day. I was able to isolate the problem to the following:

If I was using dom7@3.0.0-alpha.9, it worked
If I was using dom7@3.0.0, it did not. The behavior was such that the 2nd slide in an autoplay would appear, and just suddenly, without using a transition. The autoplay would also stop, without advancing further.

The only way I was able to fix my problem was to pin my package-lock to dom7@3.0.0-alpha.9

**Comment by 719media** [comment]
Additional note, alpha.10 breaks as well, so the breaking change is between alpha.9 and alpha.10 for this problem.

**Comment by 719media** [comment]
I've isolated it down to this change

https://github.com/nolimits4web/dom7/commit/f786ab7f3b885e9fde77126808cd3418be7faa5c

**Comment by ygj6** [comment]
@719media Could you please provide the complete test code with JSFiddle, CodeSandbox, etc?

**Comment by nolimits4web** [comment]
I can't reproduce it

**Comment by ygj6** [comment]
@nolimits4web I agree, so I think [this issue](https://github.com/nolimits4web/swiper/issues/3946) can be closed.

**Comment by 719media** [comment]
The problem was due to not properly importing the effect-fade.scss file. Without this file, the previous version of dom7 still LOOKED like it was running properly because of how the css was using transition vs transitionDuration. Properly importing the effect-fade.scss file fixed the problem
