### ISSUE TITLE
url change when page is swiped

### ISSUE THREAD

**Issue by jakediscovery** [nolimits4web/Swiper#397]
Is there a way to assign hash names for each slide, so that when the page is swiped the url is changed, like www.mysite.com/index.html#example1

would this have to be done with ajax?
a similar question about deep linking has been proposed, would it be possible to do this with http://www.asual.com/jquery/address/

**Comment by zdimaz** [comment]
Добрый день!
Я только начинаю учить скрипты и не могу разобраться, помогите)))
У меня есть Слайдер и к нему Хеш навигация отдельно.
Как мне получить активный слайд и навешать на него класс и менять его при смене слайда ??

**Comment by zdimaz** [comment]
http://prntscr.com/ht9gy7
