### ISSUE TITLE
Combination of ReverseDirection true & WaitForTransition false breaks swiper

### ISSUE THREAD

**Issue by basboy12** [nolimits4web/swiper#3973]
This is a (multiple allowed):
* [x] bug

* Swiper Version: v6.3.5
* Platform/Target and Browser Versions: All
* Live Link or JSFiddle/Codepen or website with isssue: https://gotalent-bf8090.webflow.io/ (before the footer)

### What you did
I'm using Swiper.js to create a two continuous playing horizontal slider, one going left to right, the other right to left. 

For the latter, I've set reverseDirection to true, but I've noticed it breaks the swiper in combination with WaitForTransition set to false; slides dissapear from the viewport. On Mac Safari, on pageload. On Chrome, after one interacts with the swiper.

```
<style>
.swiper--blog__wrapper {
   transition-timing-function: linear !important;
}
</style>

<script>
var blogSliderRev = new Swiper('.swiper--blog__rev__container', {
    wrapperClass: 'swiper--blog__wrapper',
    slideClass: 'swiper--blog__slide',
    touchEventsTarget: 'swiper--blog__wrapper',
    slidesPerView: 'auto',
    direction: 'horizontal',
    spaceBetween: 0,
    touchStartPreventDefault: false,
    freeMode: true,  
    freeModeMomentum: false,
    freeModeMomentumRatio: 0,
    speed: 20000,
    autoplay: {
    	delay: 0,
        disableOnInteraction: true,
        waitForTransition: false,
        reverseDirection: true,
  	},
    loop: true,
    grabCursor: true,
    longSwipes: false,
});

blogSliderRev.on('touchEnd', function() {  
	blogSliderRev.autoplay.start(); 
});
</script>
```

### Actual Behavior
The slides in the swiper dissapear

**Comment by ygj6** [comment]
@basboy12 This problem looks similar to #3893. Maybe it caused by the dependency of dom7, could you please use the newest version of dom7 try again? Or can you provide the complete code to reproduce the problem?

**Comment by basboy12** [comment]
@ygj6 I've created a small codepen: https://codepen.io/basvs/pen/WNGNEBL 

As soon as you uncomment "waitForTransition: false", you'll see the slides disappear.

Ultimately I'm trying to recreate the two sliders at the bottom of [this page](https://asana.com/teams/marketing), if there's another way in achieving that with swiper.js, let me know — I'm just a designer with limited front-end skills (:

**Comment by pramach** [comment]
Is there somewhere already a beta bundle with this new dom available to test ?

**Comment by vltansky** [comment]
@basboy12 @pramach still relevant?

**Comment by basboy12** [comment]
@vltansky Yes, still not working correctly last time I checked.

**Comment by pramach** [comment]
Hi

Sorry, no. For me it works now well with this latest version (December 
2020).

Thanks a lot.
Wolfgang aka pramach


Am 22.01.21 um 11:03 schrieb Vlad Tansky:

**Comment by vltansky** [comment]
@basboy12 can you check with the latest version?

**Comment by basboy12** [comment]
@vltansky I'm using swiper from the CDN listed on the homepage, does that include the latest version?

Just checked it using https://gotalent-site.webflow.io/ on desktop, iPhone and iPad (all safari) — the whole bottom row still disappears as soon you interact with it.

**Comment by vltansky** [comment]
@basboy12 take a look at #2942 
looks related to me? If yes there is a workaround there, give a try and update me please :)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
