### ISSUE TITLE
Swiper is adding 500KB to my bundle

### ISSUE THREAD

**Issue by kylewetton** [nolimits4web/swiper#3976]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5.
* Platform/Target and Browser Versions: Web.

### What you did
Used ts-loader in Webpack to bundle my app with and without swiper imported. 

Without: ~40Kb
With: ~550Kb

I'm using two extensions
`import {Swiper, Pagination, Autoplay} from 'swiper';`

`Swiper.use([Pagination, Autoplay]);`

### Expected Behavior
The file size to be reasonable

### Actual Behavior
My bundle size is unexpectedly big.

**Comment by nolimits4web** [comment]
There is something wrong with your bundler config then. Fully compiled (and transpiled) not minified swiper bundle is 300Kb https://unpkg.com/browse/swiper@6.3.5/
