### ISSUE TITLE
Swiper/Slide Width calculation with box-shadow CSS property

### ISSUE THREAD

**Issue by serajin** [nolimits4web/swiper#3979]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v6.3.5
* Platform/Target and Browser Versions: Windows Chrome / Iphone 11 Pro Safari
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/js-tkinij?file=index.html

### What you did
added a box-shadow/webkit-box-shadow/moz-box-shadow css property to add a dropshadow to a slide.

### Expected Behavior
Should be able to snap the end of the slide to the end of the slider, as normal.

### Actual Behavior
On intialization it works fine. If the browser changes size for any reason a recalculation is done and the 3d transform will now be calculated based on the width of the box including the shadow, which causes slides to no longer line up, and to overshoot the target slide.

![image](https://user-images.githubusercontent.com/10015495/100488157-85c1b380-30da-11eb-9edb-68b5b30ada19.png)

This occurs on chrome in windows by resizing the browser, but more importantly in iOS when scrolling down on a page, as the top/bottom bars hide on scroll making it impossible to avoid this bug.

**Comment by asim-headout** [comment]
Was this fixed?
