### ISSUE TITLE
Navigation Arrows not showing on Chrome or Safari

### ISSUE THREAD

**Issue by james0r** [nolimits4web/swiper#3980]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: Chrome 87.0.4280.67 & Firefox 84.0b5 (64-bit) (to compare)

### What you did
Setup the basic markup provided in Get Started. Everything looks right except I couldn't see the arrows. I tried my best to debug it but it's loading them from glyphs and not sure how to work with these.

Went over to Firefox and they showed up fine.

Safari tested on 14.0.1 also not showing up.

### Expected Behavior
See Arrows

### Actual Behavior
Arrows are not visible.

Arrows only visible on Firefox.

**Comment by AndrewBogdanovTSS** [comment]
@james0r can you provide a repro link?

**Comment by james0r** [comment]
@AndrewBogdanovTSS This might have been fixed on Chrome 88. I'm unable to reproduce now on chrome or Safari (which is still the same version) now. Apologies for not providing providing a link.

**Comment by vltansky** [comment]
@james0r issue can be closed then ?
