### ISSUE TITLE
Code optimization.

### ISSUE THREAD

**Issue by ygj6** [nolimits4web/swiper#3981]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
* [x] optimization

I think the following code can be optimized:

https://github.com/nolimits4web/swiper/blob/84c3f4560cdf98ab6a3b2e5a620fab97cc01cf34/src/components/core/events-emitter.js#L93-L101

**Comment by nolimits4web** [comment]
Merged, thanks!
