### ISSUE TITLE
Different slide with different height

### ISSUE THREAD

**Issue by lawchihon** [nolimits4web/swiper#3984]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.
* Platform/Target and Browser Versions: IOS
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/lawchihon/pen/ZEpYbra

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.
I am trying to set different height on different slide.
Tried to set height as auto or fixed pixel, but either the style get overwritten or behaviour become weird

### Expected Behavior
Allow different height on each slide

### Actual Behavior
Forced to have all slide to have same height

**Comment by ygj6** [comment]
@lawchihon Hi, the following is the author’s opinion, Is this what you want?
> That will break many use cases. I don't really understand the issue. If you need different slide widths/heights this is exactly what slidesPerView: 'auto' mode exist, where it respects slide sizes and doesn't override anything
