### ISSUE TITLE
Delay before execution of autoplay.stop()

### ISSUE THREAD

**Issue by Unknow-max** [nolimits4web/swiper#3986]
Hi, 

* Swiper Version: Swiper 5.4.5
* Platform/Target and Browser Versions: The issue appear in all the browsers tested.

Hi, first thing first, this is my configuration file:

```js
  let integrationsSlider = new Swiper(".js-integrations-slider", {
      direction: "vertical",
      loop: true,
      speed: 4000,
      allowTouchMove: false,
      slidesPerView: 'auto',
      spaceBetween: 60,

      autoplay: {
        delay: 0,
      },

      breakpoints: {

      }

    });
```

As you can see, I have autoplay set on my swiper slider, and on slides hover I want to disable it, to re-start it on mouse out.
So I did something like this:

```js
function integrationsSliders() {
  let slides = document.querySelectorAll(".js-integration-slide");

  slides.forEach(function(slide) {

    slide.addEventListener("mouseover", function() {
// Take the corresponding swiper container
      let slideSwiperContainer = slide.parentElement.parentElement.swiper;
        slideSwiperContainer.autoplay.stop();

    });

  });

}

```

The issue is that the autoplay doesn't stop immediately, it waits sometime before stopping, and this make me crazy. I also tried to reset the speed before calling autoplay.stop() (slideSwiperContainer.params.speed = 0) but without any results.

How I can fix that?

Thank you for reading.

**Comment by nolimits4web** [comment]
Calling autoplay.stop means it will not switch to other slides, but if it is in transition to next slide, it will be finished. It is by design

**Comment by bene-we** [comment]
I was experiencing the same issue, and I found that the following autoplay options in combination with manually triggering `swiperInstance.autoplay.start()` and `swiperInstance.autoplay.stop()` caused the error:

```
[autoplay]="{
    delay: 5000,
    pauseOnMouseEnter: true,
    disableOnInteraction: false
}"
```


I implemented another flag on `(sliderFirstMove)` and when manually triggering a slide change that is set to `true`.
 With that I recognize once the user changes a slide manually for the first time in order to stop autoplay from that time on.

The problem was that after the user changed a slide manually (and `stop()` has been called) and left the swiper area with his mouse, one more slide change has been executed (like it has been queued or something). From listening to `(autoplay)` events I recognized that this slide change after calling `stop()` has been initiated by autoplay.

I solved it by setting `pauseOnMouseEnter` to `false` and call start/stop autoplay programmatically on `mouseenter`/`mouseleave`

Btw I'm using Angular, so don't be confused by the autoplay options or the events. Hope this helps someone.

**Comment by tendaikatsande** [comment]
const swiper = new Swiper('.swiper', {
  // ...
  on: {
    init: function () {
      console.log('swiper initialized');
    },
  },
});

**Comment by EugeneBugor** [comment]
> Calling autoplay.stop means it will not switch to other slides, but if it is in transition to next slide, it will be finished. It is by design

doesn't make sense for freemode

**Comment by dylanmccurry-msft** [comment]
I have the same issue- calling stop() with freemode on an autoplay ... it waits for the transition to complete.  I want it to stop immediately, no matter what slide it's on or how far through the transition it's in... any way to do that?

**Comment by silampawar** [comment]
> I have the same issue- calling stop() on an autoplaying logo reel ... it waits for the transition to complete. I want it to stop immediately, no matter what slide it's on or how far through the transition it's in... any way to do that?

Any luck resolving this mate? I am having the exact same issue, where on click of stop button (when I call swper.autoplay.stop()) it waits until next slide is shown and then stops.

**Comment by dylanmccurry-msft** [comment]
> > I have the same issue- calling stop() on an autoplaying logo reel ... it waits for the transition to complete. I want it to stop immediately, no matter what slide it's on or how far through the transition it's in... any way to do that?
> 
> Any luck resolving this mate? I am having the exact same issue, where on click of stop button (when I call swper.autoplay.stop()) it waits until next slide is shown and then stops.

The best I could come up with is to transition to the first slide over a few ms (I think it was slideTo() or slideToFirst(), can't remember exactly), and then stop.  I'd prefer to just 'pause immediately', but seems that is not possible.

**Comment by lukasavic23** [comment]
Has anyone managed to solve this?

**Comment by JarvisChao** [comment]
> > > I have the same issue- calling stop() on an autoplaying logo reel ... it waits for the transition to complete. I want it to stop immediately, no matter what slide it's on or how far through the transition it's in... any way to do that?
> > 
> > 
> > Any luck resolving this mate? I am having the exact same issue, where on click of stop button (when I call swper.autoplay.stop()) it waits until next slide is shown and then stops.
> 
> The best I could come up with is to transition to the first slide over a few ms (I think it was slideTo() or slideToFirst(), can't remember exactly), and then stop. I'd prefer to just 'pause immediately', but seems that is not possible.

This is how I solved it with Swiper 11.

```typescript
let duration: number;
let distanceRatio: number;
const stopAutoplay = () => {
  // Stop slide at current translate.
  swiper.setTranslate(swiper.getTranslate());

  // Calculating the distance between current slide and next slide.
  // 0.3 is equal to 30% distance to the next slide.
  distanceRatio = Math.abs((swiper.width * swiper.activeIndex + swiper.getTranslate()) / swiper.width);

  // The duration that playing to the next slide
  duration = swiper.params.speed! * distanceRatio;
  swiper.autoplay.stop();
};

let startTimer: ReturnType<typeof setTimeout>;
const startAutoplay = (delay = duration) => {
  if (startTimer) clearTimeout(startTimer);
  startTimer = setTimeout(() => {
    swiper.autoplay.start();
  }, delay + 400);
};

const isPlaying = ref(true);
let clickable = true;
const handleTogglePlay = () => {
  if (!clickable) return;
  clickable = false;

  if (isPlaying.value) stopAutoplay();
  else {
    const distance = swiper.width * swiper.activeIndex + swiper.getTranslate();

    // Avoid distance that is exactly 0
    duration = distance !== 0 ? duration : 0;
    swiper.slideTo(swiper.activeIndex, duration);
    startAutoplay();
  }
  isPlaying.value = !isPlaying.value;
  setTimeout(() => { clickable = true; }, 200);
};
```

**Comment by deleanuradu** [comment]
This is still an issue, why is the autoplay.stop() method taking a few seconds before stopping the autoplay?
autoplay.start() seems to work fine.

**Comment by Breeze8** [comment]
4 years they can not fix that
