### ISSUE TITLE
"slideChange" not emit if spaceBetween is used.

### ISSUE THREAD

**Issue by towry** [nolimits4web/swiper#3987]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: macOS latest, Chrome browser latest.
* Live Link or JSFiddle/Codepen or website with issue: https://stackblitz.com/edit/swiper-demo-11-multiple-slides-per-view-rpjywi?file=index.html

### What you did
Add spaceBetween option, slide to last slide.

### Expected Behavior
`slideChange` event should be emitted, so I can get the active index.

### Actual Behavior
`slideChange` not emitted.

**Comment by towry** [comment]
My current solution to "listen the slide change and get active index" is use `transitionStart` and use `swiper.snapIndex` (`swiper.activeIndex` doesn't change).

**Comment by ygj6** [comment]
@towry Add `centeredSlides: true,` option，"slideChange" will be emitted normally.
