### ISSUE TITLE
Unable to customize swiper-wrapper class with react/vue/svelte implementation

### ISSUE THREAD

**Issue by kaisermann** [nolimits4web/swiper#3988]
Didn't found any issue regarding this behavior, sorry in advance if it's duped.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.2.0

### What you did

Added a `wrapperClass` prop to my `<Swiper>` component as documented on the  [React Props page](https://swiperjs.com/react/#swiper-props) and the [API page](https://swiperjs.com/api/#parameters:~:text=wrapperClass).

> Swiper React component receive **all** Swiper parameters as component props, plus some extra props:

However, after taking a look into the three framework implementations, I noticed that the `swiper-wrapper` class is hardcoded on all of them:

https://github.com/nolimits4web/swiper/blob/master/src/vue/swiper.js#L354

https://github.com/nolimits4web/swiper/blob/master/src/svelte/swiper.svelte#L152

https://github.com/nolimits4web/swiper/blob/master/src/react/swiper.js#L162

Is there a specific reason for this or should we be supporting the `wrapperClass` parameters in these scenarios?

### Expected Behavior

Default wrapper class is replaced with the passed one.

### Actual Behavior

Nothing happens, the default `swiper-wrapper` is kept as it is.

**Comment by nolimits4web** [comment]
This parameter is used in Core version only, and should be used when wrapper has custom class to let Swiper know about it. In Vue/React/Svelte custom class on wrapper is not supported

**Comment by kaisermann** [comment]
Hey @nolimits4web, 👋 

thanks for the quick reply! I understand the reason why you can't change it, but could we at least point that out in the docs? A tiny note would suffice. I'm happy to help with it.

**Comment by nolimits4web** [comment]
@kaisermann PR is welcome https://github.com/nolimits4web/swiper-website

**Comment by maweo-mathis** [comment]
sorry for reopening this thread but how am I able to style as example the wrapper, navigation or pagination with cssModules, when I cant pass classes to the elements?
