### ISSUE TITLE
When the width of slides is set to a specific value, loop+autoplay did not work.

### ISSUE THREAD

**Issue by ygj6** [nolimits4web/swiper#3991]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Master branch.
* Platform/Target and Browser Versions: Windows, CHROME.
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/92ws5erj/52/.

### What you did
When the slide width is set, all slides are displayed in the visible window. Even if the autoplay parameter is set, the slider stops automatically.

**Comment by ygj6** [comment]
As soon as you uncomment "centeredSlides: true",it can work properly.@nolimits4web, Should this scenario describe in the official document or write a demo in this project?

**Comment by vltansky** [comment]
@nolimits4web

**Comment by samslow** [comment]
+1
