### ISSUE TITLE
onKeyPress event doesn't work

### ISSUE THREAD

**Issue by enes-get-local** [nolimits4web/swiper#3992]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.2
* Platform/Target and Browser Versions:  Windows, CHROME,

I created a country picker and need to handle onKeyPress function in order to make search. I will filter options when user click keyboard letters.

 ```
 handleSearch = (e) => {
    console.log(e)
  };

<Swiper
            style={{ height: '100%' }}
            direction={'vertical'}
            slidesPerView={'auto'}
            freeMode
            freeModeMomentumBounce
            keyboard
            mousewheel
            scrollbar
            updateOnWindowResize
            updateOnImagesReady
            onKeyPress={(e) => this.handleSearch(e)}
            wrapperTag="span"
          >
            <SwiperSlide
              onKeyPress={(e) => this.handleSearch(e)}
              onTouchStart={(event) => this.handleTouchStart(event)}
              onTouchMove={(event) => this.handleTouchMove(event)}
              onTouchEnd={(event) => this.handleTouchEnd(event)}
              onTouchCancel={(event) => this.handleTouchCancel(event)}
              onWheel={(event) => this.handleScroll(event)}
              onKeyDown={(e) => this.handleScroll(e)}
              className="picker-scroller"
            >
              {this.renderItems()}
            </SwiperSlide>
          </Swiper>
```

In the above example i added onKeyPress function both Swiper and SwiperSlide components. It has to log to console but nothing happened when click keyboard. Doesn't work handleSearch function.

**Comment by nolimits4web** [comment]
There is no `onKeyPress` event in Swiper, use ref and attach it as DOM event

**Comment by enes-get-local** [comment]
> There is no `onKeyPress` event in Swiper, use ref and attach it as DOM event

![image](https://user-images.githubusercontent.com/70728456/100737328-1226eb80-33e5-11eb-84bd-a1565c4e0d7d.png)

It doesn't allow ref property. How i can use ref ?
