### ISSUE TITLE
The content not visible if it exceed the slide hight, also not able to scroll that content

### ISSUE THREAD

**Issue by ahtisham57** [nolimits4web/swiper#4000]
@vltansky 

Hey,

Hope you are doing great!

I am using your library within my wordpress site. But facing some issue!

Like if a slide exceed its content or hight then the content is not visible/presented exactly I need it to display in the mobile view. If I need to see the content I've to drag it. 

Could you please confirm to me if there is any feature in the library so I can able to add scroll in that slide? I tried to implement the scroll using CSS but that trick not worked for me.

Please check the demo here in the mobile view: http://d8.gotoproject.net/wordpress11/

Your prompt reply would be highly appreciated.

Thanks

**Comment by nolimits4web** [comment]
CSS styles added to swiper-slide:
```css
overflow: auto;
```

**Comment by ahtisham57** [comment]
I've already tried this solution but it is not working for me. Please provide any relevent solution for this one.

Thanks!

**Comment by vltansky** [comment]
Hey @ahtisham57 
first of all @nolimits4web is the author of Swiper :) I'm just helping where I can.
Tried to google your case, looks like this is relevant:

> Ok, here is a pretty nice working solution. Works well on iOS https://jsfiddle.net/8fgphstx/1/
> 
> Here is the JS:

``` js
var swiper = new Swiper('.swiper-container', {
    direction: 'vertical',
});
var startScroll, touchStart, touchCurrent;
swiper.slides.on('touchstart', function (e) {
    startScroll = this.scrollTop;
    touchStart = e.targetTouches[0].pageY;
}, true);
swiper.slides.on('touchmove', function (e) {
    touchCurrent = e.targetTouches[0].pageY;
    var touchesDiff = touchCurrent - touchStart;
    var slide = this;
    var onlyScrolling = 
            ( slide.scrollHeight > slide.offsetHeight ) && //allow only when slide is scrollable
            (
                ( touchesDiff < 0 && startScroll === 0 ) || //start from top edge to scroll bottom
                ( touchesDiff > 0 && startScroll === ( slide.scrollHeight - slide.offsetHeight ) ) || //start from bottom edge to scroll top
                ( startScroll > 0 && startScroll < ( slide.scrollHeight - slide.offsetHeight ) ) //start from the middle
            );
    if (onlyScrolling) {
        e.stopPropagation();
    }
}, true);
```

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/1467#issuecomment-150010090_

I made a demo and it seems to work with the current version of Swiper:
https://stackblitz.com/edit/swiper-demo-9-vertical-slider-scpmex?file=index.html

**Comment by ahtisham57** [comment]
Hi @vltansky 

Sorry for the delay,

The code you have provided above is working perfectly for the simple vertical slider. But this is not working for the [nested slider](https://swiperjs.com/demos/#nested_swipers). 
I have made modifications to the swiper
`var swiper = new Swiper('.swiper-container', {
    direction: 'vertical',
});` 
replace with 
`var swiper = new Swiper('.swiper-containe-vr', {
    direction: 'vertical',
});`
which is the container for vertical slider but the issue still remains the same.

Please suggest any other solution to this problem. Your response will be highly appreciated and helpful.
Thanks in advance.

**Comment by vltansky** [comment]
https://stackblitz.com/edit/swiper-demo-18-nested-swipers-xoz6lu?file=index.html
Take a look at this.

**Comment by ahtisham57** [comment]
Thanks, @vltansky My issue has been resolved!

**Comment by ahtisham57** [comment]
Hi hope you doing great
 http://d8.gotoproject.net/wordpress11/
scroll down works but scroll up does not work when we go to up slide from slide-down

**Comment by ahtisham57** [comment]
![preview-full-image](https://user-images.githubusercontent.com/73220880/101452211-2fad0580-394f-11eb-9105-bf19da4e3657.png)

**Comment by vltansky** [comment]
does it work for you in the stackblitz example?
if yes, what is the difference?
Provide a stackblitz example that doesn't work, not a WordPress website.
