### ISSUE TITLE
Mouse wheel scroll doesn't work

### ISSUE THREAD

**Issue by enes-get-local** [nolimits4web/swiper#4001]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.2
* Platform/Target and Browser Versions: Windows, CHROME

 ```
<Swiper
          style={{ height: '100%', flex: '1 1', display: 'flex', alignItems: 'center' }}
          direction={'vertical'}
          slidesPerView={'auto'}
          freeMode
          freeModeMomentumBounce
          keyboard
          mousewheel={{ releaseOnEdges: true, forceToAxis: true, invert: true }}
          draggable
          scrollbar={{ dragSize: 64 }}
          simulateTouch
          // updateOnWindowResize
          // updateOnImagesReady
          onInit={(swiper) => {
            this.setState({ swiper });
            console.log(swiper.scrollbar);
          }}
          onTransitionEnd={(e) => this.handleTransitionEnd(e)}
          wrapperTag="span"
        >
          <SwiperSlide
            className="picker-slide"
          >
            {this.renderItems()}
          </SwiperSlide>
        </Swiper>
```

Added mousewheel options but it doesn't scroll when tapping mouse wheel. Using in react app.

**Comment by nolimits4web** [comment]
Would be good to see live example, better JSFiddle/CodePen/etc

**Comment by enes-get-local** [comment]
> Would be good to see live example, better JSFiddle/CodePen/etc

https://stackblitz.com/edit/react-ts-ynlpa8?file=Hello.tsx

Sure , it is here.

**Comment by nolimits4web** [comment]
https://swiperjs.com/react/#usage

> By default Swiper React uses core version of Swiper (without any additional components). If you want to use Navigation, Pagination and other components, you have to install them first.
