### ISSUE TITLE
3D Cube with Vertical direction is not working with svelte

### ISSUE THREAD

**Issue by nem95** [nolimits4web/swiper#4002]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Latest.
* Platform/Target and Browser Versions: desktop Brave.

Hello all,

### What you did
I've followed the doc for the svelte implementation of swiper, and tried to add a 3D cube effect (https://swiperjs.com/svelte/#effects) it's working well for the default setting but when I add 

```javascript
<Swiper 
   direction='vertical"
   effect="cube"
>
```
It seems to have good behaviour but doesn't work at all.

### Expected Behavior
3D cube effect with the vertical direction

### Actual Behavior
Each swiper-slide is very tall 4000px and more

Thanks

**Comment by nolimits4web** [comment]
> Each swiper-slide is very tall 4000px and more

Means you have not set swiper's container height, which is must be set for vertical swiper
