### ISSUE TITLE
Module not found: Can't resolve 'swiper/swiper-react'

### ISSUE THREAD

**Issue by wodka** [nolimits4web/swiper#4003]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: Fails on build

```
swiper@^6.3.5:
  version "6.3.5"
  resolved "https://registry.yarnpkg.com/swiper/-/swiper-6.3.5.tgz#7444b680d0fdafe84859825ac3559b5b01bd1916"
  integrity sha512-MZkkVJ+sXukp6G3Z3BlKayhBjRIQuO1TZaTlH7ooI/0qbH0kkmItFMjFo19nOOsJaDXglA32xqyc9KCtmbJv0w==
  dependencies:
    dom7 "^3.0.0-alpha.7"
    ssr-window "^3.0.0-alpha.4"
```

### What you did

```
import { Swiper } from 'swiper/swiper-react'
```

### Expected Behavior

Swiper Component to be useable in tsx

### Actual Behavior
```
wait  - compiling...
error - ./pages/index.tsx:7:0
Module not found: Can't resolve 'swiper/swiper-react'
```

from what I can tell the folder is present and contains a package.json file, but then does not resolve the actual code - I do get the type validation

**Comment by nolimits4web** [comment]
https://swiperjs.com/react/#usage

**Comment by wodka** [comment]
... just wanted to close it - `swiper/react` is the correct import

**Comment by Cyral** [comment]
Any idea what caused this? My IDE (webstorm) also suggested to import it from swiper/swiper-react. Not sure where it gets that from, but it confused me for a bit until I noticed the docs were different. (I also have @types/swiper installed and I'm using TypeScript if that matters)

**Comment by ZhengRui** [comment]
I am having the same issue, even though I am importing from "swiper/react"
