### ISSUE TITLE
Cube Effect - Can you do text overlay over the images?

### ISSUE THREAD

**Issue by doverradio** [nolimits4web/swiper#4008]
Hello,

I asked this question on SO here: [https://stackoverflow.com/questions/65161891/swiper-js-can-you-add-text-to-the-cube-effect-in-react-js](https://stackoverflow.com/questions/65161891/swiper-js-can-you-add-text-to-the-cube-effect-in-react-js)

Do you know if this can be done?

I have checked through the other demos but I did not see a way.

**Comment by ygj6** [comment]
@doverradio  I tried to replace the `p` code with the `img` code so that the text could be displayed.

The code is modified as follows:
```
<SwiperSlide style={{ backgroundPosition: 'center', backgroundSize: 'cover' }}>
  <div style={{ position: 'relative' }}>
    <p style={{ position: 'absolute' }}>T-shirts</p>
    <img style={{ height: '300px', width: '300px' }} src={img1} />
  </div>
</SwiperSlide>
```
Is it works as you wanted?

**Comment by nolimits4web** [comment]
It is just CSS/HTML, sure you can with few extra custom styles and as @ygj6  suggests. Closing as not related to Swiper directly
