### ISSUE TITLE
Mousewheel scroll doesn't work

### ISSUE THREAD

**Issue by enes-get-local** [nolimits4web/swiper#4011]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.2.
* Platform/Target and Browser Versions:  Windows, CHROME
* [https://stackblitz.com/edit/react-ts-ynlpa8?file=Hello.tsx](https://stackblitz.com/edit/react-ts-ynlpa8?file=Hello.tsx)

###  I created basic example
```
SwiperCore.use([Navigation, Pagination, Scrollbar, A11y]);

const renderBody = () => {
  const nodes = [];

  for (let i = 0; i < 50; i++) {
    nodes.push(<p>"Swiper slide Swiper slide"</p>);
  }
  return nodes;
};

const Hello = () => {
  return (
    <div style={{ height: "250px", border: "1px solid gray" }}>
      <Swiper
        className="picker-swiper"
        style={{
          height: "100%",
          flex: "1 1",
          display: "flex",
          alignItems: "center"
        }}
        direction={"vertical"}
        slidesPerView={"auto"}
        freeMode
        freeModeMomentumBounce
        keyboard
        mousewheel={{ releaseOnEdges: true, forceToAxis: true, invert: true }}
        draggable
        scrollbar={{
          dragSize: 64,
          dragClass: "picker-drag"
        }}
        simulateTouch
        wrapperTag="span"
      >
        <SwiperSlide className="picker-slide">{renderBody()}</SwiperSlide>
      </Swiper>
    </div>
  );
};
```
Mouse scroll should be work.

Mousewheel scroll doesn't work in react app. Installed necessary components like Scroll, Navigation...

[There is live example 
](https://stackblitz.com/edit/react-ts-ynlpa8?file=Hello.tsx)

**Comment by nolimits4web** [comment]
> Installed necessary components like Scroll, Navigation...

You didn't install `Mousewheel` component
