### ISSUE TITLE
Slide don't animated when mousewheel scroll

### ISSUE THREAD

**Issue by enes-get-local** [nolimits4web/swiper#4012]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.2
* Platform/Target and Browser Versions: Windows,CHROME
[https://stackblitz.com/edit/react-ts-ynlpa8?file=Hello.tsx](https://stackblitz.com/edit/react-ts-ynlpa8?file=Hello.tsx
)

When scrolling with mouse wheel, slide don't be animated. Transition works only while click drag. There is any option or property active animate ?

[Example](https://stackblitz.com/edit/react-ts-ynlpa8?file=Hello.tsx)

**Comment by nolimits4web** [comment]
It is by design, it scrolls as your mousehweel scrolls
