### ISSUE TITLE
Internal SwiperOptions should be optional: _beforeBreakpoint, _containerClasses, _slideClass and _swiper

### ISSUE THREAD

**Issue by trustthe27** [nolimits4web/swiper#4021]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.0

### What you did
Upgraded from 6.3.5 to 6.4.0

### Expected Behavior
Should build React TypeScript sources without errors.

### Actual Behavior
Terminated with build error, because of new internal events in `swiper-react.d.ts, that aren't optional`:

```
Type '{ children: Element[]; id: string; tag: string; spaceBetween: number; slidesPerView: number; speed: number; pagination: { clickable: boolean; }; loop: boolean; autoplay: { delay: number; disableOnInteraction: boolean; }; }' is missing the following properties from type 'Swiper': _beforeBreakpoint, _containerClasses, _slideClass, _swiper  TS2739
```

**Comment by rzdong** [comment]
![image](https://user-images.githubusercontent.com/19262880/101607537-aa554e00-3a3f-11eb-8da9-bb795a9f78c9.png)

So am I
It should be optional

**Comment by SPWizard01** [comment]
can someone prioritise this? its kind of a breaking change for folks using typescript.

**Comment by trustthe27** [comment]
@SPWizard01: Just go back to 6.3.5 until it's fixed.

```
"swiper": "6.3.5",
```
