### ISSUE TITLE
Orientation change 

### ISSUE THREAD

**Issue by arco71** [nolimits4web/Swiper#403]
Hi,
I am using this for main banner and it's set as responsive style.
The problem is when I change screen orientation, it seems " .swiper-container"  doesn't change it's height.

Image cuts off(overlap by next ul element) when it's on landscape mode and image stays too far (.swiper-container extended)  from the next ul element when it's back from the landscape mode.

Normal View
ooooooooooooo   <-- banner
ooooooooooooo
                            <-- 20px padding
ululululululululul   <-- listview
ululululululululul
ululululululululul

Landscape View
ooooooooooooooooooooooooooo   <-- banner
ulululululululululululululululululululul   <-- listview covered banner
ulululululululululululululululululululul 
ulululululululululululululululululululul 

Back to Normal View
ooooooooooooo   <-- banner
ooooooooooooo   <--container still remains landscape mode height

empty space
empty space
empty space

ululululululululul   <-- listview
ululululululululul
ululululululululul

please advise
Thank you

**Comment by nicroto** [comment]
Sorry to summon this, but I've just had this same issue and fixed it by calling `swiper.update()` on a 50ms timeout (as suggested by @nolimits4web).

Swiper as all iDangerous projects is great. Thanks!
