### ISSUE TITLE
TypeError: Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by curiousdustin** [nolimits4web/swiper#4043]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: "swiper": "^6.3.3".
* Platform/Target and Browser Versions: React Native Web.

### What you did
Within a React Native Web component:
``` js
  componentDidMount() {
    this.swiper = new Swiper(this.swiperContainer, {
      centeredSlides: false,
      slidesPerView: 'auto',
      spaceBetween: 10,
      slidesOffsetBefore: 20,
      slidesOffsetAfter: 20,
      allowTouchMove: false,
      loop: false,
      pagination: {
        el: '.swiper-pagination'
      }
    });
    this.swiper.on('transitionEnd', this.handleSwiperTransitionEnd);
  }

  componentWillUnmount() {
    this.swiper.off('transitionEnd', this.handleSwiperTransitionEnd);

    // Attempt to destroy swiper here.
    // The issue is, if swiper never actually got rendered, this line causes errors.
    this.swiper.destroy();

    this.swiper = null;
  }
```

### Expected Behavior
Calling `swiper.destroy()` should be a safe thing to do at any time, and should not throw an error.

### Actual Behavior
Calling `swiper.destroy()` throws an error, IF swiper never actually got rendered to the DOM. For instance, if the component render method decides not to render the swiper because there is no data for it yet.
``` text
Cannot read property 'removeEventListener' of undefined
```

### Related Issues
There are some related issues, but both are closed without much info. It seems like a method like `destroy()` should fail silently.
https://github.com/nolimits4web/swiper/issues/3559
https://github.com/nolimits4web/swiper/issues/3238

**Comment by vltansky** [comment]
Can you provide relates issues links please ?

**Comment by curiousdustin** [comment]
Oops sorry, I meant to at the end of the post:

**Comment by curiousdustin** [comment]
Oops sorry, I meant to at the end:

https://github.com/nolimits4web/swiper/issues/3559
https://github.com/nolimits4web/swiper/issues/3238

**Comment by asolopovas** [comment]
+1

**Comment by WesWedding** [comment]
A very similar issue has been observed in (non-Native) React context, as well.

I was able to resolve the issue when I realized someone else had defined scrollbars elements that didn't exist.

```
// Defining a scrollbar with elements that don't
// exist will not cause a crash during creation of
// the component, but will crash during destruction/unmount
// of component.
const swiperParams = {
  scrollbar: {
    el: '.does-not-exist',
  }
}
```

Removing the scrollbar parameter solved the problem.

**Comment by CodeAdraas** [comment]
Late to the party but I want to inform that this error also arose to me in Vue3 (Nuxt3) to this date. What I could make out from the error was that the moment the Vue Swiper component tried to cleanup (after it's parent component were to unmount) it failed as the parent component element was already removed from DOM. So for some reason the cleanup process happens to late? My only solution was to ditch the Vue Swiper component and manually create a Swiper instance, which of course is no problem because it works great.

**Comment by nazariisliusarenko** [comment]
@CodeAdraas can you provide the code of your solution ? thank you in advance!


Can you

**Comment by matrixmandeep** [comment]
@CodeAdraas cam you please provide the solution?

**Comment by megFree** [comment]
@CodeAdraas there's a better approach to define Props.
`
import type { SwiperOptions } from 'swiper';
interface Props extends SwiperOptions {}
const $props = defineProps<Props>();
`

**Comment by mostafaznv** [comment]
same here.

Nuxt 3 / Vue 3

**Comment by ZynChroMaTiK** [comment]
I've somehow figured out on my side (**Nuxt** 3.8.1) that **page transitions** are the cause of these errors, especially the **in-out** type. 
Errors happened with both implementations with nuxt-swiper module or swiper/vue imported components and on nuxt@^3.7.

` nuxt.config.ts
app: {
    pageTransition: { name: 'v', mode: 'in-out' }
},
`

**Comment by vhovorun** [comment]
@CodeAdraas Hey, I'm having the same issue with swiper for now, can you please show your solution?

**Comment by vhovorun** [comment]
@nazariisliusarenko
@matrixmandeep 
Can u please guys show your solution?

**Comment by dreitzner** [comment]
same issue with
- nuxt@3.9.1
- swiper@11.0.5

My solution was to wrap all swipers in an error boundary
```vue
<nuxt-error-boundary @error="() => {}">
    <swiper>
        <swiper-slide
            v-for="image in images"
            v-slot="{ isActive }">
            <lazy-atm-asset
                cover
                :data="image"
                :sizes="imageSizes"
                :showCaption="isActive"
                :isFullbleed="style?.size === 'fullbleed'" />
        </swiper-slide>
    </swiper>
</nuxt-error-boundary>
```

**Comment by felixdenoix** [comment]
@C17AN Using the nuxt-error-boundary component works (be careful with [fallthroug attributes](https://vuejs.org/guide/components/attrs) if you use the nuxt-error-boundary at the root of the component). Creating a component and using the base library also works fine. Furthermore, the devs added this warning in the vue doc: 
> Swiper Vue components will likely to be removed in future versions.
So one more reason to implement it yourself !

**Comment by codeflorist** [comment]
> @nazariisliusarenko @matrixmandeep
> 
> Take a look at [this component](https://github.com/CodeAdraas/nuxterplate/blob/main/src/components/util-slider/component.vue). It basically does the same as the existing Vue Swiper component.

@CodeAdraas 

this does not seem to be online anymore. does anyone have an example?

**Comment by tusharbansode** [comment]
export default defineNuxtPlugin((nuxtApp) => {
    
    const testSwiperError = ( error, instance, info ) => {
        return (
            error instanceof TypeError &&
            error.message?.includes("Cannot read properties of undefined (reading 'removeEventListener')") &&
            (error.stack?.includes("swiper-core") || error.stack?.includes("swiper_vue") || error.stack?.includes("swiper/modules"))
        );
    }

    nuxtApp.vueApp.config.errorHandler = (error, instance, info) => {
      
        if (testSwiperError(error, instance, info)) {
            console.warn("[Handled Swiper Error]:", error.message);
            return;
        }
        throw error;
    }
  
    nuxtApp.hook('vue:error', (error, instance, info) => {
        
        if (testSwiperError(error, instance, info)) {

            console.warn("[Handled Swiper Error]:", error.message);
            return;
        }
        
        throw error;
    })
})
