### ISSUE TITLE
Last slide items aren't selectable

### ISSUE THREAD

**Issue by enes-get-local** [nolimits4web/swiper#4046]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version:6.3.2
* Platform/Target and Browser Versions: , Windows, CHROME
[https://stackblitz.com/edit/react-ts-ynlpa8?file=Picker.tsx](https://stackblitz.com/edit/react-ts-ynlpa8?file=Picker.tsx
)

Implemented a picker that options is created as a slide item. Evertying is okay but the last 4 item are not selectable.  it returns to back old translate value when i scroll to the bottom option.

![image](https://user-images.githubusercontent.com/70728456/102077016-af3c4800-3e19-11eb-8844-276b3e1556d0.png)

Please check example and slide to last option

[Example here
](https://stackblitz.com/edit/react-ts-ynlpa8?file=Picker.tsx)

**Comment by vltansky** [comment]
guess this is the same as #4052

**Comment by nolimits4web** [comment]
Not sure what you mean by "selectable", swiper can't slide to them? Swiper can slide to any slide only when `centeredSlides` enabled.

Closing as not related to Swiper, but to implementation.
