### ISSUE TITLE
Calculate dynamic height for each slide

### ISSUE THREAD

**Issue by scooterlord** [nolimits4web/Swiper#405]
Hello,

first of all congratulations on your excellent piece of work!

I am having the following issue: I have different height slides, and some of them have dynamic height content, like expanding accordions, etc.

calculateHeight seems to change swiper-container height according to the highest slide but the changes of slides height in my case vary vastly.

I have already read #162 but haven't been able to implement it properly.

It would be nice for the slider to re-calculate the height dynamically when height changes in slides take place, so that if the first slide has 300px height, the whole container should be 300px height, second slide being 3525px, container height should be the same and if slider content is altered the swiper should reinitialize.

Thanks!

**Comment by thomasaull** [comment]
This worked for me (please note I adapted the code to work with mootools instead of jQuery. If you're using jQuery you have to retranslate it back): 

```javascript
onSlideChangeStart: function(swiper)
		{
			var activeSlide = swiper.slides[swiper.activeIndex]
			var slideHeight = $$(activeSlide).pick().getElement('img').getSize().y;
			
			$$('.swiper-container').pick().setStyle('height', slideHeight);
			$$('.swiper-wrapper').pick().setStyle('height', slideHeight);
		},
```

But what I basically just changed it this line:
```javascript
var activeSlide = swiper.slides[swiper.activeIndex]
```
