### ISSUE TITLE
swiper not init correctly with async data fetch (redux-thunk)

### ISSUE THREAD

**Issue by Elabbasy00** [nolimits4web/swiper#4050]
I made  example on codeanbox with the full code
When launching the procedure and updating the status and passing it to the component swiper, do not read any slides, unless the page size changes or go to a second page and come back

CodeSanBox Link : https://codesandbox.io/s/p3qgs 

try to resize the sanbox preview browser and you will see swiper read slides correctly

**Comment by nolimits4web** [comment]
You need to use Swiper React components or call `swiper.update()` when slides updated
