### ISSUE TITLE
CSS of the swiper is bundled by components for PostCSS users

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nolimits4web/swiper#4053]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 6.4.1
* Platform/Target and Browser Versions: All

### What you did
I use postCSS in the project but still want to benefit from smaller bundle size of the swiper by importing css components that only relate to components I am using such as Pagination, Navigation, Zoom, etc. - similar to how SASS people have it.

### Expected Behavior
CSS of the swiper is bundled by components, not as one monolithic css file

**Comment by AndrewBogdanovTSS** [comment]
@nolimits4web when will it be released?

**Comment by vltansky** [comment]
@AndrewBogdanovTSS its already released in version `6.4.4` 
https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#swiper-644---released-on-december-18th-2020
https://unpkg.com/browse/swiper@6.4.4/components/navigation/navigation.min.css
