### ISSUE TITLE
A swipe should reset the autoplay timeout

### ISSUE THREAD

**Issue by svleeuwen** [nolimits4web/Swiper#406]
I worked around this issue using the onSlideChangeStart hook like this.

onSlideChangeStart: function(swiper){
      // reset autoplay timer
      swiper.stopAutoplay();
      swiper.startAutoplay();
    }

But it could be integrated in the core.

**Comment by pasqualevitiello** [comment]
The issue persists when using (and clicking on) thumbnails. The method showed by @svleeuwen works, but it would be nice if this can be fixed in next release ;)
