### ISSUE TITLE
swiper doesn't support responsive background images and load all images when lazy=true

### ISSUE THREAD

**Issue by sk29110** [nolimits4web/swiper#4071]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 6.4.5
* Platform/Target and Browser Versions: **MacOS Chrome**
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.
**http://skoizumi.com/dev/test.html**

### What you did
**I have set up responsive background image and activate lazyload on swiper** 

preloadImages: false,
lazy: true,

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.
**Only first image will be loaded**

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
**It loads all the images**

**Comment by nolimits4web** [comment]
You are using something else to load lazy images/pictures. This is what supported in Swiper https://swiperjs.com/api/#lazy
