### ISSUE TITLE
When usign backdrop-filter, the filter effect goes away while slider finishes to move

### ISSUE THREAD

**Issue by cyroassis** [nolimits4web/swiper#4073]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Latest, from CDN
* Platform/Target and Browser Versions: Windows (chrome), Android (chrome), iOS (safari)
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/maxbeat/pen/abNBrex

### What you did
```
.slider__item {
  height: 200px;
  margin: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  font: 24px arial;
  background: rgba(255,255,255,0.5);
  backdrop-filter: blur(10px);
}
```

### Expected Behavior
I would like my slides to have the glassmorphism effect, so the slider would blurry the background image on the page.

### Actual Behavior
the backdrop-filter goes away right after I release the mouse button, and comes back after the slider finishes moving.
If I use other effect, like coverflow, it looses even the rotation and depth effect while moving.

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
