### ISSUE TITLE
Not smooth transition after the last slide in Swiper loop mode

### ISSUE THREAD

**Issue by MaxJacobs213** [nolimits4web/swiper#4077]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: macOS 11.1, Windows 10, Chrome 87.0.4280.88
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/swiper-demo-9-vertical-slider-x3g4my

### What you did
I am trying to set a smooth transition for internal content when swiping (transform: scale) in loop mode. I added the required css rule. This works, but after switching the last slide, there is an abrupt scale change. (not smoothly).

In the source code of the library in the file swiper/src/core/loop/loopFix.js I found line number 28:
`const slideChanged = swiper.slideTo(newIndex, 0, false, true);`
From this, I realized that the looping of the slides occurs according to the following principle: after the last slide, we instantly switch to the previous one (speed = 0) and an animation is produced that shows that we have passed the circle.

### Expected Behavior
Smooth transition of content within a slide regardless of the slide index.

### Actual Behavior
When going through a full circle of slides, an abrupt change occurs, due to which transitions within the slide do not work as expected

**Comment by nolimits4web** [comment]
Inspect DOM when loop enabled, it has duplicated slides that you need to consider as well
