### ISSUE TITLE
🎄On Vacation until January 11th

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/swiper#4079]
Dear community, as the maintainer of this project, I have put the repository in "vacation mode" so that I can take a much needed and deserved break without worrying about tasks piling up while I recharge. I hope you can understand the need to take this action and not just "turn off notifications". Anyone who has experienced a company-wide shutdown would understand, that it's much easier to disconnect from work when everyone does at the same time.

Know that your contributions are valuable and appreciated, so please subscribe to this issue and get notified when I'm back and ready to resume actively maintaining this project.

**Comment by yuzhakovvv** [comment]
Happy holidays! 🎄

**Comment by valnub** [comment]
Happy holidays! :-)

**Comment by vltansky** [comment]
Happy holidays, С новым годом ;) 🎄

**Comment by nolimits4web** [comment]
Thank you!
