### ISSUE TITLE
React Swiper Fails when SwiperSlide is not the direct descendent

### ISSUE THREAD

**Issue by tomjn** [nolimits4web/swiper#4084]
Currently Swiper React gets a list of the slides by [inspecting its direct descendents ( 😱 )](https://github.com/nolimits4web/swiper/blob/master/src/react/get-children.js), however, this fails in some situations, such as when those descendents are components that don't have DOM nodes, such as higher order components.

As a result, those components incorrectly appear outside of the wrapper container.

Instead, it would make more sense to allow the use of a context provider, and to then support this context provider in  the `SwiperSlide` component.

https://reactjs.org/docs/context.html

I believe this is also the cause of https://github.com/nolimits4web/swiper/issues/4070 as I get  the same results here.

**Comment by nolimits4web** [comment]
Sorry, but it is strictly by design to use `<SwiperSlide>` in React version as a lot of internals (especially Loop and Virtual) rely on it. If you need to use HOC, put them inside of Slide content, or wrap how Swiper with them

**Comment by tomjn** [comment]
You misunderstand,  we **did**  use `<SwiperSlide>`

**Comment by tomjn** [comment]
Can you share a link to where the decision was made? I'm struggling to understand the reason it was done the way it was done  and the problems it fixes

**Comment by tomjn** [comment]
Also why is this behaviour undocumented?

**Comment by rogerchao-telus** [comment]
Just ran into this issue as well. I use HOC to add additional functionalities to SwiperSlide to have a built in selection functionality as well.

Oddly enough, my implementation was working consistently in Storybook for the longest time. And when I published my package for use within our company, it started to act up again.

Totally weird, been driving my nuts for the past week. Some documentation should be added regarding SwiperSlide's usage.

**Comment by marbiano** [comment]
I have an use case where children of the root element can and cannot be a slide. This requirement for `<SwiperSlide>`s to be a direct child of `<Swiper>` doesn't make much sense, specially when React provides with a primitive like Context that makes this such an artificial constraint. Please reconsider the architectural design here!

**Comment by HRworksJus** [comment]
The only thing that worked for me was
`export const customSlider = observer(({ children, clickable, onClick, ...otherProps }: CarouselItemProps) => {

  return (
    <SwiperSlide {...otherProps}>
      {children}
    </SwiperSlide>
  );
}) as FC<CarouselItemProps>;

customSlider.displayName = 'SwiperSlider';

export default customSlider;
`
The SwiperSlides are the children of my swiper and get mapped somewhere else from the Backend.
`
//other code
<Swiper
            modules={[Navigation, Pagination, Autoplay]}
            slidesPerView={slidesPerView}
            centeredSlides={centeredSlides}
            spaceBetween={spaceBetweenSlides}
            navigation={navigationArrows}
            pagination={pagination ? { clickable: true } : false}
            loop={loop}
            onSlideChange={handleSlideChange}
          >
            {children}
          </Swiper>`

The thing that was missing in my case was the type casting in the Slide File together with setting displayName to 'SwiperSlider'.
But I am still unsure as to why this is necessary with swiper.js - does anyone know why the swiper doesn't recognize children as slides without setting the displayName to 'SwiperSlider'?
