### ISSUE TITLE
Mousewheel swipe doesn't respect swiper.isLocked when watchOverflow + slidesOffsetBefore are set and it fits the screen

### ISSUE THREAD

**Issue by MirekPapirnik** [nolimits4web/swiper#4089]
When slides with offset fits to the screen checkOverflow() sets swiper.isLocked, but mousewheel doesn't respect this lock.

This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v6.4.5 (actual master)
* Platform/Target and Browser Versions: macOS + Chrome (affects all platforms)

### What you did
- set watchOverflow to true
- set slidesOffsetBefore to truthy value
- keep only two slides to fit the screen
- naviagiton arrows and scrollbar are correctly hidden
- issue: you can scroll with touchpad

playground-react/App.jsx
```
/* eslint-disable no-restricted-globals */
import React from 'react';
import SwiperCore, { Navigation, Pagination, Scrollbar, A11y, Mousewheel } from '../build/core';
import { Swiper, SwiperSlide } from '../build/react';

SwiperCore.use([Navigation, Pagination, Scrollbar, A11y, Mousewheel]);

const App = () => {
  return (
    <main>
      <Swiper
        watchOverflow
        slidesOffsetBefore={100}
        onSwiper={(swiper) => (window.swiper = swiper)}
        slidesPerView={3}
        spaceBetween={50}
        navigation
        scrollbar={{ draggable: true }}
        mousewheel={true}
      >
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
      </Swiper>
    </main>
  );
};

export default App;
```

### Expected Behavior
Swipe with touchpad is locked.

### Actual Behavior
Swipe is available.

**Comment by nolimits4web** [comment]
Sorry, but it is by design, `offsetBefore` creates slideable (swappable) area
