### ISSUE TITLE
Weird gap on centeredSlides

### ISSUE THREAD

**Issue by bilalmalkoc** [nolimits4web/swiper#4091]
If slide items don't fill wrapper, swiper is adding weird gap on top.

<a href="https://i.vgy.me/7oNCoh.gif">Preview</a>

```
const thumbGallery = new Swiper('.gallery-nav', {
    slidesPerView: 3,
    centeredSlides: true,
    centeredSlidesBounds: true,
    freeMode: true,
    mousewheel: true,
    spaceBetween: 8,
    scrollbar: {
        el: '.swiper-scrollbar',
        draggable: true,
    },
    breakpoints: {
        470: {
            slidesPerView: 4,
        },
        600: {
            slidesPerView: 6,
        },
        1101: {
            slidesPerView: 4,
            direction: 'vertical',
        },
        1601: {
            slidesPerView: 5,
            direction: 'vertical',
        },
    },
});
```

This is a (multiple allowed):
* [x] bug

* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: Windows 10/Chrome 87

**Comment by vltansky** [comment]
make a demo on stacbklitz / codesandbox, please.

**Comment by bilalmalkoc** [comment]
Sorry. You can check here:
https://stackblitz.com/edit/js-b9vh8l?file=index.js

**Comment by vltansky** [comment]
@bilalmalkoc there is a workaround in https://github.com/nolimits4web/swiper/issues/3431#issuecomment-743454558

https://stackblitz.com/edit/js-ydle4o?file=index.js

**Comment by bilalmalkoc** [comment]
@vltansky thanks but it is not a solution. It can break design. Slides can has fixed width.

**Comment by Ezra-Siton-UIX** [comment]
I think this issue not related to swiper. 

The body element generally has some margin by default in some browsers.

Set the body to:

```
body{
  margin: 0;
}
```
Remove this gap.
