### ISSUE TITLE
watchOverflow doesn't lock swiper when slidesOffsetAfter is set and slidesOffsetBefore is not

### ISSUE THREAD

**Issue by MirekPapirnik** [nolimits4web/swiper#4092]
When watchOverflow is set, slidesOffsetAfter is set and slides with offset fits the screen than swiper is not locked.

https://github.com/nolimits4web/swiper/pull/3291#issuecomment-635500634

This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5 (current master)
* Platform/Target and Browser Versions: macOS + chrome (affects all platforms)

### What you did
- set watchOverflow to true
- set slidesOffsetAfter value
- keep only two slides to fit the screen
- issue: swiper is not locked

playground-react/App.jsx
```
/* eslint-disable no-restricted-globals */
import React from 'react';
import SwiperCore, { Navigation, Pagination, Scrollbar, A11y } from '../build/core';
import { Swiper, SwiperSlide } from '../build/react';

SwiperCore.use([Navigation, Pagination, Scrollbar, A11y]);

const App = () => {
  return (
    <main>
      <Swiper
        watchOverflow
        slidesOffsetAfter={100}
        slidesPerView={3}
        spaceBetween={50}
        navigation
        scrollbar={{ draggable: true }}
      >
        <SwiperSlide>Slide 1</SwiperSlide>
        <SwiperSlide>Slide 2</SwiperSlide>
      </Swiper>
    </main>
  );
};

export default App;
```

### Expected Behavior
Swiper is locked.

### Actual Behavior
Swiper is not locked.
![image](https://user-images.githubusercontent.com/17140919/104310479-152cf580-54d4-11eb-8f96-79dc5a9f0f1d.png)

**Comment by nolimits4web** [comment]
Why it should be locked? It shouldn't. Don't add `slidesOffsetAfter` if there is insufficient slides

**Comment by MirekPapirnik** [comment]
Because the count of slides can be dynamic (e.g. from CMS). If the count exceeds slidesPerView than slidesOffsetAfter is added correctly. But when the width is enough to fit the screen it should be locked as when it fits with slidesOffsetBefore.
src/components/core/check-overflow/index.js:11
should be with OR instead of AND
`  if ((params.slidesOffsetBefore || params.slidesOffsetAfter) && lastSlidePosition) {`
Now property slidesOffsetAfter depends on slidesOffsetBefore to be set and it is not neccesseary. Is it?

**Comment by MirekPapirnik** [comment]
Actual behavior:
watchOverflow + slidesOffsetBefore - works properly
watchOverflow + slidesOffsetAfter - doesn't work properly, requires to add slidesOffsetBefore at least 1 (it breaks design and it is not mentioned in docs that these props are dependent)

**Comment by Iraklikandelaki** [comment]
I can confirm this. Even if you set slidesOffsetAfter to zero watchoverflow completely breaks. 
You can't swipe through it, but the scrollbar and navigation still do.
