### ISSUE TITLE
Click on element in swiper triggers a slide

### ISSUE THREAD

**Issue by matanmoda** [nolimits4web/swiper#4094]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: MacOS Chrome 89.0.4386.0
* Live Link or JSFiddle/Codepen or website with issue: 

### What you did
Implemented a slider to contain some children - images of products with some info.
Using these configs for the slider : 
```speed: 500,
      spaceBetween: remToUnitlessPx(space.map['three-quarter-x']),
      slidesPerView: 2,
      slidesPerGroup: 2,
      preloadImages: true,
      centerInsufficientSlides: true,
      updateOnImagesReady: true,
      navigation: {
        prevEl: prevButtonRef.current || undefined,
        nextEl: nextButtonRef.current || undefined,
        disabledClass: 'SwiperCarousel__navigation--disabled'
      },
      pagination: paginationElementRef.current
        ? {
            el: paginationElementRef.current,
            type: 'bullets',
            clickable: true,
            hideOnClick: false,
            bulletClass: 'SwiperCarousel__bullet',
            bulletActiveClass: 'SwiperCarousel__bullet--active'
          }
        : undefined```
```
### Expected Behavior
On clicking an image I expect the click to work as a click and not a slide

### Actual Behavior
The slider randomly triggers a slide when clicking on one of the images I have inside the slider (the click shows some information about an image as an overlay on the image)

https://user-images.githubusercontent.com/26385540/104374111-61396380-54ef-11eb-8777-2cad7ab1510f.mp4

**Comment by vltansky** [comment]
can you provide live demo?

**Comment by kivatinetz-truelogic** [comment]
What happened with this ticket?

**Comment by matanmoda** [comment]
I closed it since there is a way to fix this by changing the `shortSwipes` to false and the `threshold` to some value greater that 0.

**Comment by banchichen** [comment]
same issue, I set threshold=10, now it's right
