### ISSUE TITLE
If slidesPewView is half the total of slides, navigation breaks

### ISSUE THREAD

**Issue by Gusis93** [nolimits4web/swiper#4097]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: Mac, Chrome 87.0.4280.141
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/swiper-demo-31-thumbs-gallery-with-loop-mode-f1q6fz?file=index.html

### What you did
Create a slider that has N slides and should show N/2 slides as looped thumbs.

### Expected Behavior
The navigation works as expected, I can see the active slide when I click on the navigation arrows

### Actual Behavior
If the number of slidesPerView is exactly **half** of the number of total slides, then the thumbs slider jumps to a slide out of view. If its 1 more or 1 less the behaviour is normal

For example, 10 slides, **slidesPerView** is **5**, when navigating and reaching the fifth slide, the next one active will be out of view.

![swiper-demo-31-thumbs-gallery-with-loop-mode-f1q6fz_-_StackBlitz](https://user-images.githubusercontent.com/5525609/104636960-70154700-56a4-11eb-82eb-d5902c044af6.png)

![swiper-demo-31-thumbs-gallery-with-loop-mode-f1q6fz_-_StackBlitz](https://user-images.githubusercontent.com/5525609/104637020-828f8080-56a4-11eb-91b2-359bd2474589.png)

Note: If I remove the **loop** from the thumbs, the slider behaves half as expected, you get the loop but you don't get a smooth loop, it navigates back to the first slide

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
