### ISSUE TITLE
Silder is rendered as [object Object] when breakpoints is set

### ISSUE THREAD

**Issue by reallifeliver** [nolimits4web/swiper#4098]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: `"swiper": "^6.4.5",` ``
* Platform/Target and Browser Versions: MacOS BigSur v11.1, Chrome v87.0.4280.141
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did

I am using swiper-react in my react app.
and My swiper should be responsive on browser, I set breakpoint like below

```
      <Swiper
        onSwiper={handleInit}
        virtual
        allowTouchMove={false}
        onReachEnd={handleSlideEnd}
        spaceBetween={24}
        slidesPerView={4}
        slidesPerGroup={4}
        breakpoints={{ 1024: { slidesPerView: 6, slidesPerGroup: 6 } }}
      >
```

And this breakpoint works well. But the problem is occured when it default setting not on breakpoint.

As you can see, my default slidesPerView and slidesPerGroup are 4. And in this condition, some slide is rendered like `[object Object]`. This is result below

![image](https://user-images.githubusercontent.com/37332261/104677825-77346780-572d-11eb-82e2-d17fa92e51fb.png)

by the way, If I remove breakpoints props from swiper, This bug is not occur.

what cause this problem? 

### Expected Behavior

all slider should be rendered 

### Actual Behavior

some slider are rendered as `[object Object]`

**Comment by vltansky** [comment]
Make a demo please

**Comment by reallifeliver** [comment]
@vltansky Here is a demo for this bug
https://codesandbox.io/s/gallant-khorana-dqrqd?file=/src/App.js
