### ISSUE TITLE
Chrome Table vertical white lines

### ISSUE THREAD

**Issue by 3dots** [nolimits4web/swiper#4099]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Swiper 6.4.5
* Platform/Target and Browser Versions: Windows 10 Pro. Chrome Version 87.0.4280.141.
* Live Link or JSFiddle/Codepen or website with isssue: [codepen](https://codepen.io/3dot/pen/ExgGVGa)

### What you did
.swiper-container without set width. The width is set by parent container.
A table in the second slide with black background.
Do 110% zoom.

![2021-01-15 10_22_36-Swiper Table white vertical lines  Final](https://user-images.githubusercontent.com/6589306/104745133-bfe32500-571b-11eb-89f5-b5ee9c93181e.png)

### Expected Behavior
The table columns have no white lines.

### Actual Behavior
Strangle white lines appear on zoom.

**Comment by nolimits4web** [comment]
There is no strange lines in Swiper, I can assume it is a rendering bug. Closing as not related to Swiper
