### ISSUE TITLE
Musewheel option dont work if you use a npm package

### ISSUE THREAD

**Issue by OneTube** [nolimits4web/swiper#4100]
This is a bug  ( Not critical ):

* "swiper": "^6.4.5"

Hello everyone. Firstly want to say thanks to developers of this plugin !

I install package with npm (v. 6.4.5.) and try to use mousewheel option, but its not working.
To .swipper-wrapper didnt add the id ( for example - swiper-wrapper-c36eecd13101110eea )
But, if i use the script tag (to use it in my project), than all good !

Thanks you !

**Comment by nolimits4web** [comment]
You need to install Mousewheel module https://swiperjs.com/get-started/
