### ISSUE TITLE
Angular Universal error

### ISSUE THREAD

**Issue by neilhem** [nolimits4web/swiper#4101]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5.
* Platform/Target and Browser Versions: macOS, Windows, iOS, ANDROID, CHROME
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
Create app and run in SSR mode

### Expected Behavior
No render errors

### Actual Behavior
Nodejs render error: `Cannot read property 'swiperSlideIndex' of undefined`

**Comment by vltansky** [comment]
can you provide demo?

**Comment by neilhem** [comment]
> can you provide demo?

Where I can create to render in SSR mode?

**Comment by vltansky** [comment]
Fix will be included in the next release.
@neilhem give an update if it works for you now.

**Comment by neilhem** [comment]
v6.4.6?

**Comment by vltansky** [comment]
@neilhem v6.4.7

**Comment by neilhem** [comment]
Yeah, no more error. Works fine! Thanks
