### ISSUE TITLE
Swiper doesn't stop propagating the click event.

### ISSUE THREAD

**Issue by jvince** [nolimits4web/swiper#4103]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5.
* Platform/Target and Browser Versions: macOS, Windows, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with issue: https://codesandbox.io/s/beautiful-hopper-c4su4

### What you did
Created a horizontal swiper with a click event attached to every slide.

### Expected Behavior
Prevent click propagation if no swipe gesture detected.

### Actual Behavior
Open the code sandbox console. Click in the top region of slide 0. Without releasing the mouse button move to the bottom region of slide 0 keeping the movement vertical as much as possible. Release the mouse button. The console should log `click: 0`.

**Comment by proov** [comment]
It might be a different problem but i have issues when clicking on a link inside a slide. Nobody experience this ? you can try with Chrome on https://swiperjs.com/ by clicking "Get started" or every other links...

**Comment by joebentaylor1995** [comment]
I have this issue on mobile safari

**Comment by tigerchick** [comment]
> It might be a different problem but i have issues when clicking on a link inside a slide. Nobody experience this ? you can try with Chrome on https://swiperjs.com/ by clicking "Get started" or every other links...
> 
> edit: i think it's my Chrome, dunno why i have this behavior. Sry guys for this comment.

I have also have this issue. @proov did you ever find a resolution to it?

**Comment by zeitderforschung** [comment]
I have the issue on mobile chrome.

**Comment by petar-spasov-catenateb** [comment]
I had a problem with links not working with React on Mac and this worked for me:

- update to latest version 9.1.0
- removed `allowTouchMove: false` from my config
- added `threshold: 10000000` so the user still can't move the slides with dragging

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
