### ISSUE TITLE
Swiper terribly laggy with 15+ images and thumbnails

### ISSUE THREAD

**Issue by dpw1** [nolimits4web/swiper#4104]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: Windows 10, Google Chrome, Version 87.0.4280.141 (Official Build) (64-bit)
* Live Link or JSFiddle/Codepen or website with issue: https://ezfycode.myshopify.com/products/multiple-images

Password for the website: ezfy

### What you did
**This happens only when looping is enabled.**

I created a Swiper object wired up with thumbnails, arrows, looping enabled and some other custom features. 

Whenever I swipe on desktop or mobile, the swiping animation freezes for a second and then finally performs the requested action. The thumbnails are also laggy.

### Expected Behavior
Whenever I swipe or click the arrows I want it to be smooth, just like hwo 

### Actual Behavior
Whenever you swipe or click the arrows it takes a fraction of second to change the image.

I have been stuck on this for a few weeks now, please help me if you can. Any help is greatly appreciate,

**Comment by nolimits4web** [comment]
Can not see such issue on your link. Use available technics for optimization:
- lazy loading
- images of appropriate size
