### ISSUE TITLE
Equal Height Slides

### ISSUE THREAD

**Issue by alexryans** [nolimits4web/swiper#4107]
* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: Chrome
* Live Link or JSFiddle/Codepen or website with isssue: https://jsfiddle.net/alexryans/crqu8tvk/9/

### What you did
I am trying to create a slider where each slide is the same width and height, with the exception of a specific type of slide (marked with a class of `.is-year` alongside the `.swiper-slide` class). I have set each slide to have `height: auto;` and also `align-self: stretch`, which has successfully made each slide equal in height, however the main Swiper element is not expanding to take into account the height of each slide and is instead cutting off content (see attached screenshot).

Here is the code driving this behaviour:

**HTML**
```
<div class="swiper-container s-swiper js-timeline">
    <div class="swiper-wrapper">
        <?php while(have_rows('items')): ?>
            <?php the_row(); ?>

            <div class="swiper-slide <?php echo get_sub_field('year') == true ? 'is-year' : ''; ?>">
                <div class="c-timeline__box>
                    <div class="c-timeline__box-title">
                        Box Title
                    </div>
                </div>
            </div>
        <?php endwhile; ?>
    </div>

    <div class="swiper-pagination"></div>
</div>
```

**CSS**
```
.swiper-slide {
    .c-timeline & {
        width: rem-calc(300);
        height: auto;
        align-self: stretch;
    }

    .c-timeline &.is-year {
        width: auto;
    }
}
```

**JS**
```
if($('.js-timeline').length) {
    const contentSlider = new Swiper('.js-timeline', {
        pagination: {
            el: '.swiper-pagination',
            type: 'progressbar'
        },
        slidesPerView: 'auto',
        spaceBetween: 20
    });
};
```

### Expected Behavior
All slides should be equal height and the main Swiper element's height should expand to show the entire height of each individual slide.

### Actual Behavior
Main Swiper element is not being expanded to match the height of each individual slide, meaning content is being cut off.

<img width="1383" alt="Screenshot 2021-01-20 at 1 11 32 pm" src="https://user-images.githubusercontent.com/3007053/105179696-88141d00-5b21-11eb-9e20-95d7196e2c65.png">

**Comment by nolimits4web** [comment]
Sorry, it is not really related to Swiper and more to how CSS works in general. As you can see swiper doesn't set any sizes in your case, so some CSS tweaks should be done on your side
