### ISSUE TITLE
[React] Swiper breaking the width

### ISSUE THREAD

**Issue by rikusen0335** [nolimits4web/swiper#4109]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.5
* Platform/Target and Browser Versions: Anything PC Browsers
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/react-swiper-stciking-out-8e1xs

### What you did
Please look into codesandbox

### Expected Behavior
I expected swiper containers not breaking the width. Like if parent has 1900px (100%), then swiper should have 1900px (100%) width.

### Actual Behavior
Swiper's sticking out of parent width.

**Comment by nolimits4web** [comment]
This is how CSS work, style and set container size as you need. Swiper doesn't do any magic with its sizes
