### ISSUE TITLE
Angular: ngIf inside swiperSlide breaks Swiper (ExpressionChangedAfterItHasBeenCheckedError)

### ISSUE THREAD

**Issue by mxlle** [nolimits4web/swiper#4123]
Me again. Unfortunately yesterday's release broke another place 😢 

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.7
* Platform/Target and Browser Versions: IOS, ANDROID, CHROME
* Live Link or JSFiddle/Codepen or website with isssue: [Reproduced with Stackblitz](https://stackblitz.com/edit/angular-swiper-ngif-issue?file=src%2Fapp%2Fapp.component.html)

### What you did
Using *ngIf inside swiperSlide
````
  <swiper>
    <ng-template swiperSlide *ngFor="let slide of slides">
      <div class="inner-slide">
        <div *ngIf="true">
          {{slide}}
        </div>
      </div>
    </ng-template>
  </swiper>
````

### Expected Behavior
Swiper Slide should allow ngIf in content

### Actual Behavior
Swiper component broken, console shows ExpressionChangedAfterItHasBeenCheckedError

**Comment by mxlle** [comment]
When will this be released?

**Comment by vltansky** [comment]
@mxlle released in `6.4.9`

**Comment by mxlle** [comment]
@vltansky I guess I shouldn't have rushed you 😬  Now it seems even more broken. 
If you check my Stackblitz again: I only updated the dependency, but now it cannot even correctly get the SwiperModule. 

Or did sth change in how to include the Module?

**Comment by vltansky** [comment]
@mxlle if I turn off "enable ivy" in stackblitz project settings it works fine... Not sure why it happens. As you mentioned it works for me on real projects.
