### ISSUE TITLE
Request - How about changing the default crossFade setting for fadeEffect?

### ISSUE THREAD

**Issue by ytk6565** [nolimits4web/swiper#4127]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Swiper Version: 6.4.8
* Platform/Target and Browser Versions: macOS, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: [Demo published on CodePen](https://codepen.io/ytk6565/pen/WNGBaQy)

### What you did
I am Japanese. I am writing English using Google Translate. Please forgive me though it may be difficult to understand.

Images with different aspect ratios were used in `effect: fade`. Inactive slides were supposed to be `opacity: 0;`, active slides and earlier slides are `opacity: 1;`, and slides after the active slide are `opacity: 0;` I was doing it. As a result, images with different aspect ratios overlapped and some of the inactive images were visible.

### Expected Behavior
What are the use cases that require the current default ( `fadeEffect: {crossFade: false}` )? I felt that `fadeEffect: {crossFade: true}` would be more useful in many cases if possible, so I would like to suggest setting it as the default.

### Actual Behavior
Please check the behavior [demo published on CodePen](https://codepen.io/ytk6565/pen/WNGBaQy).

Thank you for reading to the end.

**Comment by nolimits4web** [comment]
Sorry, but it can not be set as default because it will break (or can break) existing integrations

**Comment by ytk6565** [comment]
@nolimits4web 
Thank you for answering!
