### ISSUE TITLE
Angular: Cannot set property 'classNames' of undefined

### ISSUE THREAD

**Issue by LikKirill** [nolimits4web/swiper#4130]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.8
* Platform/Target and Browser Versions: Windows, CHROME
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/angular-swiper-classname?file=src/app/app.component.ts

### What you did
Create new slide after swiper init, by button

### Expected Behavior
Create slide like usual

### Actual Behavior
Slide create, but in console write: Cannot set property 'classNames' of undefined
And the usual slider operation breaks down

**Comment by LikKirill** [comment]
@nolimits4web when release date?

**Comment by vltansky** [comment]
@LikKirill released in `6.4.9`
