### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addClass' of undefined

### ISSUE THREAD

**Issue by j3ll3yfi5h** [nolimits4web/swiper#4157]
- Swiper Version: 6.4.9
- Platform/Target and Browser Versions: macOS, CHROME, SAFARI, etc. (doesn't matter)

## What You Did

I used the version via https://unpkg.com/swiper/swiper-bundle.min.js – it stopped working with todays update.

## Demo

https://swiperjs6.4.9-bug.jelley.fish/

## Expected Behavior

Should be working like before.

## Actual Behavior

Cannot read property 'addClass' of undefined.
![swiperjs-6 4 9-bug-console](https://user-images.githubusercontent.com/6337411/106144574-abb81280-6174-11eb-910b-99bb3ff67332.png)

**Comment by nilskoppelmann** [comment]
I'm having the same issue.

**Comment by j3ll3yfi5h** [comment]
@nilskoppelmann temporary fix: `<script src="https://unpkg.com/swiper@6.4.8/swiper-bundle.min.js"></script>`

**Comment by nolimits4web** [comment]
@j3ll3yfi5h in your example you try to init none existent slider, you shouldn't do it

**Comment by j3ll3yfi5h** [comment]
@nolimits4web "closed" means it is my problem? or are you going to fix it?

**Comment by serdarbasol** [comment]
It was working without any problems until 2-3 hours ago or more, but I solved by removing `{ init: true }` part.

**Comment by misaon** [comment]
Same issue today

**Comment by Mizyan** [comment]
Same issue for me too

**Comment by sbh96** [comment]
same issue me too
