### ISSUE TITLE
6.4.9 update causing numerous conflicts with basic jQuery

### ISSUE THREAD

**Issue by ianjwhitmore** [nolimits4web/swiper#4158]
- Swiper Version: 6.4.9
- Platform/Target and Browser Versions: macOS, Chrome

## What You Did

Bundle update caused instance of Swiper to break custom JS throughout site. 

 https://stackblitz.com/...

## Expected Behavior

This code has worked for months. 

  var swiper = new Swiper('.swiper-featured', {
    slidesPerView: 2.2,
    spaceBetween: 15,
    breakpoints: {
      500: {
        slidesPerView: 4.5,
      }
    }
  });

## Actual Behavior

Most basic jQuery was broken after today's update. Accordions, Toggles and other manipulation with very basic functions all failed as of the update. 

EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

I localized Swiper and rolled back to 6.4.8 and all is well.

**Comment by marispro** [comment]
+1 here, something went wrong, but I am using swiper without jquery
![image](https://user-images.githubusercontent.com/5610414/106203559-dbd6d400-61bb-11eb-8339-28af2faf625e.png)

`Uncaught TypeError: Cannot read property 'addClass' of undefined
    at Swiper.addClasses (addClasses.js?4029:52)`

**Comment by nolimits4web** [comment]
Fixed in https://github.com/nolimits4web/swiper/commit/31aa87a4d948912a855c06740180104a8feb56c7. What until it will be released with next update
