### ISSUE TITLE
Last slide showed only at certain window width with freeMode enabled  (Swiper 6.4.9)

### ISSUE THREAD

**Issue by dangelion** [nolimits4web/swiper#4164]
Enabling `freeMode` the last slide is showed only at certain viewport width.

Here the demo
https://codepen.io/gooogooo/pen/LYbYRYL?editors=1010

**To replicate**: bring the slider at the end and try resizing browser window width. You'll see that at certain width it shows the last slide, at other ones not.

**Comment by nolimits4web** [comment]
Update to 6.4.10

**Comment by dangelion** [comment]
Oh man thanks! I wasted like 3 hours on this! 😫
