### ISSUE TITLE
Fade effect doesn't set opacity correctly on the element

### ISSUE THREAD

**Issue by claudiopedrom** [nolimits4web/swiper#4167]
- Swiper Version: 6.4.9
- Platform/Target and Browser Versions: All

## What You Did

When adding a simple caption to a Slider with the `Fade` effect the sliders captions overlap.

https://stackblitz.com/edit/caption-issue?file=index.html

## Expected Behavior

Only the active slider should have `opacity: 1`(?).

Also, the `Fade` effect should work smoothly without having to set `loop: true`.

## Actual Behavior

Multiple sliders have `opacity: 1`, meaning that content will overlap.

If `loop: true` is not set, the fade transition between the last and the first slide is not always smooth.

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#fade-effect


crossFade | boolean | false | Enables slides cross fade
-- | -- | -- | --

**Comment by claudiopedrom** [comment]
Hey @nolimits4web shouldn't the documentation be updated to be clear that the `crossFade` option should be set to `true`?

I have read that part of the documentation before opening this issue, and at no point, I understood that the `crossFade` was required.

It only mention:
> Be sure to have the effect param set to 'fade' in order for this to work.

Thanks!

**Comment by vltansky** [comment]
@claudiopedrom you are very welcomed to contribute by opening an issue or even better a PR in https://github.com/nolimits4web/swiper-website
