### ISSUE TITLE
[Feature Request] - slidesPerGroup: auto

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nolimits4web/swiper#4168]
- Swiper Version: 6.4.10
- Platform/Target and Browser Versions: All

## What I want to achieve:
I would like to slide per items visible on screen. When slidesPerView is set to 'auto' and each item has a fixed width there is no way to tell how many items there will be on the screen (when swiper has responsive width that is dependent on the fluid parent container) on the given moment, so it would be great if slidesPerGroup could also be set to auto so that when clicking next/prev swiper would scroll on the amount of visible items.

**Comment by nelsondude** [comment]
This would be awesome to have! Wondering if we can tell from swiper the number of slides in the current view and then you could just set that number to slidesPerGroup

**Comment by AndrewBogdanovTSS** [comment]
@nolimits4web I tried setting `slidesPerGroup: 'auto'` in the options using v.6.8.2 but got an error:
![image](https://user-images.githubusercontent.com/2766448/129857472-e5c5f385-bc43-4e30-8a8f-92d5ed5628cf.png)
first I thought that it's related to SSR (I use Nuxt), but the error remains even if I wrap swiper inside <client-only>

**Comment by AndrewBogdanovTSS** [comment]
I also tried combining `{slidesPerView: 'auto', slidesPerGroupAuto: true}`, that didn't produce any errors, but I still have the swiper progress only for 1 item per click

**Comment by nolimits4web** [comment]
@AndrewBogdanovTSS `slidesPerGroupAuto` is a feature of upcoming Swiper7

**Comment by Houtaro** [comment]
Hi, was this ever implemented? 

`slidesPerGroupAuto` doesn't seem to work for me, with the same reason @AndrewBogdanovTSS mentioned. Looks like `slidesPerGroup` and `slidesPerView: auto` doesn't work when used together.

**Comment by lukecharle** [comment]
> Hi, was this ever implemented?
> 
> `slidesPerGroupAuto` doesn't seem to work for me, with the same reason @AndrewBogdanovTSS mentioned. Looks like `slidesPerGroup` and `slidesPerView: auto` doesn't work when used together.

I'm also experiencing this same issue, its completley unusable.
