### ISSUE TITLE
Swiper crashes on mobile only after slide 64

### ISSUE THREAD

**Issue by jlevitas16** [nolimits4web/swiper#4169]
Swiper Version: 6.4.10
Platform/Target and Browser Versions: Android Chrome (Samsung S8 & S9), iPhones, iPads
Development language: php & jQuery 3.5.1

I have slideshows ranging from 131 to 500 slides. Each slide has a background of about 18KB and text or a graphic ranging from 30KB - 60KB.  When the slideshow autoplays, it crashes once it gets to slide 64.  There is a category button and a search feature. They work also up until slide 64. This problem does not exist on a computer, only mobile.

You can see the behavior on these 3 pages:
https://www.wizevents.com/njycamps2020/?id=5175
https://www.wizevents.com/wjcgala2021/?id=5198
https://www.wizevents.com/ohelgala2019/?id=3978

Please advise.

**Comment by jlevitas16** [comment]
Update to above post. It isn't slide 64 that it crashes, it is around slide 66.
It is not happening on an iPhone 8 with Safari or Chrome.
It is not happening on my old Nexus 7 tablet.
It is consistently happening on my Samsung S8 and S9, and a client's iPhone and iPad, but I don't know which versions.

**Comment by dgdb1** [comment]
I think you have problem with fade effect. Can you try different transition effect? I have the same problem when I use fade effect. 

This code help me:

`.swiper-slide {opacity:0;}
.swiper-slide.swiper-slide-active {opacity:1; 
}`

**Comment by jlevitas16** [comment]
Thank you!

**Comment by vltansky** [comment]
@dgdb1 is your solution can be applied globally? If yes PR is very welcomed!

**Comment by vltansky** [comment]
I'm reopening the issue for now.

**Comment by jlevitas16** [comment]
Unfortunately, your reply came after I had to implement another solution (it was a time sensitive issue), so I don't know if what you suggested resolves the issue. I searched throughout your Github issues and Stackoverflow for a solution as well as Google, and found nothing. Perhaps, for future users, this should be documented.

**Comment by lizy0329** [comment]
If you still crash when using lazy loading functional，try this code. It solve my issus

```
.swiper-slide {
    visibility: hidden;
    &.swiper-slide-prev,
    &.swiper-slide-active,
    &.swiper-slide-next {
        visibility: visible;
    }
}
```
