### ISSUE TITLE
Vue 3 virtual not working with :slides-per-view="1" or in combination with cube effect [codesandbox]

### ISSUE THREAD

**Issue by ctwhome** [nolimits4web/swiper#4172]
the effects work perfectly, but the Virtual property does't work.
See full example here;
https://codesandbox.io/s/vue3-component-scoped-scss-forked-8tsr8?file=/src/components/SwiperCube.vue
![image](https://user-images.githubusercontent.com/4195550/106397992-96f7ab00-6410-11eb-8c80-5643919afc33.png)

**Comment by nolimits4web** [comment]
This is what I see in your demo link 
<img width="1480" alt="Снимок экрана 2021-02-01 в 13 11 10" src="https://user-images.githubusercontent.com/999588/106444576-fdbba980-648e-11eb-95d3-fada43d1ed87.png">

**Comment by ctwhome** [comment]
Thanks for taking a look, it does work for me in chrome (MacOS and Ubuntu), even in private mode. Can you please check in chrome?

https://codesandbox.io/s/vue3-component-scoped-scss-forked-8tsr8?file=/src/components/SwiperCube.vue

![image](https://user-images.githubusercontent.com/4195550/106445684-a19d5900-647f-11eb-9398-09bbd8a5c9a5.png)

**Comment by nolimits4web** [comment]
Will be fixed with next update

**Comment by ctwhome** [comment]
wonderful thank you!

**Comment by IlayG01** [comment]
The same happens with react to me

**Comment by HandsomeWolf** [comment]
The same....
