### ISSUE TITLE
Tree Shaking problem with Swiper

### ISSUE THREAD

**Issue by ms-fadaei** [nolimits4web/swiper#4175]
- Swiper Version: 6.4.10
- Platform/Target and Browser Versions: Windows CHROME (I use webpack for bundling)

## What You Did
I use Swiper like this (dynamic importing in webpack)
`const {Swiper, Navigation} = await import("swiper");`
`Swiper.use([Navigation]);`
`const mySwiper = new Swiper(".swiper-container", {...});`

## Expected Behavior
I expect the smaller size in the vendor/swiper (by webpack tree shaking) when I build my project

## Actual Behavior
All of Swiper components are imported to vendor/swiper

![Capture](https://user-images.githubusercontent.com/54557683/106468532-4d13d100-64b3-11eb-82c7-58e81ab7361f.JPG)

**Comment by nolimits4web** [comment]
Change `const {Swiper, Navigation} = await import("swiper");` to `import { Swiper, Navigation } from 'swiper'`

**Comment by nolimits4web** [comment]
And make sure tree shaking configured properly in Webpack config

**Comment by woldtwerk** [comment]
Same Problem in vite. 
As a workaround I created a vite plugin to strip out all the modules, I'm not using:

```ts
{
  name: 'swiper-remove-unused',
  transform(src, id) {
    if (/swiper\.esm\.js$/.test(id)) {
      const code = src.match(/export .* as (Navigation|Swiper|FreeMode).*;/g)?.join('\n') ?? src
      return {
        code,
        map: null
      }
    }
  },
},
```

before:
dist/app-vite/chunks/swiper.esm.63281de0.js   137.86 KiB / gzip: 39.63 KiB

after:
dist/app-vite/chunks/swiper.esm.cb5f9dac.js   68.86 KiB / gzip: 20.75 KiB

I think setting: 
```json
exports: { ".": "./"} 
``` 
to allow importing modules directly would help.
