### ISSUE TITLE
Angular: Unexpected behavior when updating slides if BrowserAnimationsModule is imported

### ISSUE THREAD

**Issue by efteel** [nolimits4web/swiper#4185]
- Swiper Version: 6.4.10.
- Platform/Target and Browser Versions: MacOS, Chrome.

## What You Did

If BrowserAnimationsModule is imported into the application, dynamically replacing the slides leads to unexpected behavior: seemingly empty slides appear at the end, wrong slide count, etc.

Reproduction:
[https://stackblitz.com/edit/angular-swiper-browseranimationsmodule-issue?file=src/app/app.module.ts](https://stackblitz.com/edit/angular-swiper-browseranimationsmodule-issue?file=src/app/app.module.ts)
1. Replace the slides by clicking on the "replace slides" button. 
2. Remove the imported BrowserAnimationsModule in app.module.ts and retry to get the expected behavior.

## Expected Behavior

Update slides properly regardless of the presence of BrowserAnimationsModule.

## Actual Behavior

Empty slides appear at the end (although not in the DOM), the slide count is off, the slides collection in the swiper instance contains more items than expected...

**Comment by BuffyTheCat** [comment]
I have this problem now. PR not helped?
