### ISSUE TITLE
Last slide appearing on top of first slide in compiled code when loop=true

### ISSUE THREAD

**Issue by jonsadka** [nolimits4web/swiper#4186]
- Swiper Version: 
```js
swiper@^6.4.10:
  version "6.4.10"
  resolved "https://registry.yarnpkg.com/swiper/-/swiper-6.4.10.tgz#d2a8bce471717b770d005fcd5e8af42ac630cac6"
  integrity sha512-uNTdbkcVjNQVOwXhr+e8rTB4Uu8QfWHaZQSSptykWJX/QjSBuAPxAUFnHG8IKGQfTljGol9eLv6g8KTwvGjYNA==
  dependencies:
    dom7 "^3.0.0"
    ssr-window "^3.0.0"
```

- Platform/Target and Browser Versions: All platforms on all browsers

## What You Did

- Set `loop` to `true` (see code below)
- Compile the page in a static site generator, like Gatsby.js 
- Load the page in the browsers while disabling JavaScript
```js
<Swiper loop={true} >
    <SwiperSlide>One</SwiperSlide>
    <SwiperSlide>Two</SwiperSlide>
</Swiper>
```

## Expected Behavior

The first slide should appear

## Actual Behavior

The second slide appears above the first slide

## Temporary fix

Leaving a workaround solution for others until we can resolve this bug 

```js
<Swiper loop={typeof window !== 'undefined'} >
    <SwiperSlide>One</SwiperSlide>
    <SwiperSlide>Two</SwiperSlide>
</Swiper>
```

**Comment by vltansky** [comment]
demo: https://codesandbox.io/s/swiper-react-fork-forked-f6rxc?file=/src/App.js

**Comment by vltansky** [comment]
@jonsadka can you make an example in codesandbox or any other online IDE?
Also if you want to contribute - PR is welcomed.

**Comment by mutewinter** [comment]
Also experiencing this issue with Next.js 11 and Swiper 7.

**Comment by Jerome1337** [comment]
@mutewinter Yes still have the same thing with NextJS 11 and Swiper 7

**Comment by jonsadka** [comment]
@nolimits4web @vltansky I'm still experiencing the same behavior. Can we re-open this ticket?

Repro case below https://github.com/jonsadka/swiper-ssr-repro

**Comment by SimonHausdorf** [comment]
we also notices this issue. It loads the last slide first and then replaces it which causes flickering / wrong content if page loads slow
