### ISSUE TITLE
Pagination : renderFraction() does not output the page numbers

### ISSUE THREAD

**Issue by MisterAwesome** [nolimits4web/swiper#4193]
- Swiper Version: 6.4.5
- Platform/Target and Browser Versions: Any

## What You Did

The function renderFraction should allow us to create a custom fraction. If we look at the doc, this is the example.

```
const swiper = new Swiper('.swiper-container', {
  //...
  renderFraction: function (currentClass, totalClass) {
      return '<span className="' + currentClass + '"></span>' +
              ' of ' +
              '<span className="' + totalClass + '"></span>';
  }
});
```  

Reproduction of the issue : [https://swiper-demo-1-default-xhwdwc.stackblitz.io](https://swiper-demo-1-default-xhwdwc.stackblitz.io)

## Expected Behavior

This function should give us four variables to work with: `currentClass`, `totalClass`, `currentNumber`, `totalNumber`. To render a custom fraction.

At least it could use currentClass and totalClass to render the numbers inside their respective html element.

## Actual Behavior

Right now, it only allows us to create a render with dynamic classes, but no way to add pages number. It has therefore no use as a pagination. As we can see in the example, it only outputs two empty spans and and a slash.

**Comment by nolimits4web** [comment]
There is a `formatFractionCurrent` and `formatFractionTotal` params callbacks for this https://swiperjs.com/swiper-api#pagination-parameters

**Comment by MisterAwesome** [comment]
So what is the use of renderFraction() if it only outputs static html without the actual numbers of the fraction?

**Comment by nolimits4web** [comment]
Because pagination is rendered only once

**Comment by tkmin** [comment]
**className** not working
**class** works

https://codesandbox.io/s/swiper-pagination-fraction-react-forked-cvdzvs?file=/src/App.jsx
