### ISSUE TITLE
Yarn images folder

### ISSUE THREAD

**Issue by vinicius98s** [nolimits4web/swiper#4196]
- Swiper Version: 6.4.5 (also tried 6.4.10).
- Platform/Target and Browser Versions: OS: Ubuntu/Browser: Edge

## What You Did

I tried to build a react (with next.js) project and got an error with the production build:
```
ModuleNotFoundError: Module not found: Error: Can't resolve './images/index' in '/home/runner/work/ocl-snitch/ocl-snitch/node_modules/swiper/esm/components/core'
```

I also found [this issue](https://github.com/nolimits4web/swiper/issues/3971) with the exact same problem.
I didn't even had a `.yarnclean` file so I had to run `yarn autoclean --init` to get this file and remove the `images` line, but this didn't work.

Any ideas? I need to get this working asap.

## Expected Behavior

Get the production build working with yarn.

## Actual Behavior

The build is broken.

**Comment by vltansky** [comment]
Looks like the following folder is missing for you: `node_modules\swiper\esm\components\core\images`
in #3971 suggested to run `npm install`, did you try it?

**Comment by nolimits4web** [comment]
Closing as not related to Swiper. There is no any reference to /images in source code
