### ISSUE TITLE
SlidesPerView: "auto" - slides not centered on page load

### ISSUE THREAD

**Issue by ilonikso** [nolimits4web/swiper#4200]
Hi, everyone! I'm creating now a slider and get some bugs with slidesPerView: auto parameter.

When the page is loaded slide move to the left. (20-30px). I noticed that on load, the slider object is reset and it adds extra pixels to virtualSize parameter. The number of added pixels is equal to the number of virtual slides multiplied by spaceBetween parameter.

Through experimentation, I found a way to fix this bug:

1) set spaceBetween to 0,
2) set margin-left/right: (spaceBetween / 2)px in CSS.

 And everything works, it doesn't move left on the page load. 
 I have suffered from this problem for a very long time, I hope my review will be useful)

**Comment by nolimits4web** [comment]
Any reason why you ignore Issue template?

**Comment by ilonikso** [comment]
> Any reason why you ignore Issue template?

It's actually not issue, but I want to show some way how to fix this problem with centered slides.

**Comment by stevepepple** [comment]
> Hi, everyone! I'm creating now a slider and get some bugs with slidesPerView: auto parameter.
> 
> When the page is loaded slide move to the left. (20-30px). I noticed that on load, the slider object is reset and it adds extra pixels to virtualSize parameter. The number of added pixels is equal to the number of virtual slides multiplied by spaceBetween parameter.
> 
> Through experimentation, I found a way to fix this bug:
> 
> 1. set spaceBetween to 0,
> 2. set margin-left/right: (spaceBetween / 2)px in CSS.
> 
> And everything works, it doesn't move left on the page load. I have suffered from this problem for a very long time, I hope my review will be useful)

Thanks for the workaround. Very helpful!
