### ISSUE TITLE
Angular Universal blocked when autoplay it true

### ISSUE THREAD

**Issue by muehle28** [nolimits4web/swiper#4202]
Swiper Version: 6.4.10
Angular Version: 11.1.1

When doing a prerendering of a Angular app, where a swiper with `autoplay=true` is included, the prerendering process blocks for a infinite time without any output. When autoplay is disabled the prerendering works fine.

**Comment by nolimits4web** [comment]
@vltansky I guess Angular version should be reworked in same way as recently happened with React/Vue/Svelte where Swiper initialization happens with 2 steps:

1. Call `swiper = new Swiper` (init swiper) with `init: false` and without `el` parameter (without element)
2. When component mounted (which should happen only on client side), call `swiper.mount(el)` to proceed initialization which is required DOM

**Comment by vltansky** [comment]
Will work on this on weekends

**Comment by eldos777** [comment]
`import { Component, OnInit, Input, ViewChild, PLATFORM_ID, Inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import SwiperCore, {
  Autoplay
} from 'swiper/core';
 constructor(@Inject(PLATFORM_ID) private platformId: Object,) { }
ngOnInit(): void {
if (isPlatformBrowser(this.platformId)) {
      SwiperCore.use([Autoplay]);
    }
}`

I hope this will help you.
