### ISSUE TITLE
Navigation styles missing in custom build scss file

### ISSUE THREAD

**Issue by vaidotas-adf** [nolimits4web/swiper#4203]
- Swiper Version: v6.4.10 (from tag) and latest from master
- Platform/Target and Browser Versions: web

## What You Did

Built custom swiper build with following configuration: 
build-config.js
````
module.exports = {
  components: [
    'virtual',
    'navigation',
  ],
  themeColor: '#007aff',
  colors: {
    white: '#ffffff',
    black: '#000000',
  },
};
````

## Expected Behavior

/package/swiper.scss file should contain navigation styles, e.g. .swiper-button-prev, .swiper-button-next etc.

## Actual Behavior

Navigation styles are missing from swiper.scss and swiper.less files, while swiper-bundle.css file has navigation styles included, as expected.

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#scss-styles

Navigation styles are in `components/navigation/navigation.scss`
