### ISSUE TITLE
Add onMouseEnter event to detect hover

### ISSUE THREAD

**Issue by amankapoor** [nolimits4web/swiper#4204]
**Is your feature request related to a problem? Please describe.**
I want to change the slide when user hovers over a thumbnail.

**Describe the solution you'd like**
Having onMouseEnter event will solve it

**Describe alternatives you've considered**
Unable to think of anything. Tried wrapping thumb swiper in a div and added onMouseEnter to it, but it won't trigger on each thumbnail for obvious reasons

**Additional context**
Visit any amazon.com listing on desktop, and try hovering over the thumbnails. That's the functionality I want.

**Comment by nolimits4web** [comment]
You, for sure, can add mouseenter event listener on your side. Can't see any problem with it. Try adding it to whole swiper container instead.

**Comment by amankapoor** [comment]
Okay, I figured out how to make it work. Thank you.

**Comment by cordial** [comment]
@amankapoor how did u make it work?
