### ISSUE TITLE
Vue: Swipper props: mousewheel, keyboard not working

### ISSUE THREAD

**Issue by MentalGear** [nolimits4web/swiper#4205]
- Swiper Version: 6.4.11
- Platform/Target and Browser Versions: macOS, Windows

## What You Did
First off: Thx for making a vue version!
Issue: mousewheel and keyboard props have no effect on swiper.
I imported the modules as described in the offical guide, yet they don't work.

```
<script lang="ts">
  // Import Swiper Vue.js components
  import {
    Swiper,
    SwiperSlide,
    Keyboard,
    Mousewheel,
    A11y,
    HashNavigation,
  } from 'swiper/vue'
</script>

<template>
  <swiper
    direction="vertical"
    :slides-per-view="1"
    :space-between="50"
    :mousewheel="true"
    :keyboard="true"
    @swiper="onSwiper"
    @slideChange="onSlideChange"
  >
...
```

##  minimal reproduction of the issue
[vue-swiper-repo.zip](https://github.com/nolimits4web/swiper/files/5938886/vue-swiper-repo.zip)

## Expected Behavior
Keyboard, Mousewheel input enabled.

## Actual Behavior
Keyboard, Mousewheel input not working.

**Comment by nolimits4web** [comment]
You did it wrong:
```js
import {
    SwiperCore,
    Keyboard,
    Mousewheel,
    A11y,
    HashNavigation,
  } from 'swiper/vue';
import {
    Swiper,
    SwiperSlide,
  } from 'swiper/vue'

SwiperCore.use([Keyboard, Mousewheel, A11y, HashNavigation]);
```

**Comment by MentalGear** [comment]
Thanks @nolimits4web  However, the code as provided by you didn't work as it. However I took another look at the docs, and indeed the second usage example had the swiper core defined as exported from 'swiper'.
Here's the code that's working for me:
```
  // import Swiper core and required modules
  import SwiperCore, {
    Keyboard,
    Mousewheel,
    HashNavigation,
    A11y,
  } from 'swiper'
  // Import Swiper Vue.js components
  import { Swiper, SwiperSlide } from 'swiper/vue'

  // Import Swiper styles
  import 'swiper/swiper.scss'
  import 'swiper/components/a11y/a11y.scss'

  // extra components
  SwiperCore.use([Keyboard, Mousewheel, A11y, HashNavigation])
```
Again, thank you very much for checking it out - wouldn't have resolved the problem without you!
