### ISSUE TITLE
Bug: Controller/Thumbs feature broken since 6.4.5

### ISSUE THREAD

**Issue by valnub** [nolimits4web/swiper#4206]
## General Info
- Swiper Version: 6.4.11
- Platform/Target and Browser Versions:
  - Safari 14.0.3
  - Chrome 88.0.4324.150
  - macOS Big Sur

## What You Did

Using controlled Swiper like this:
```jsx
<Swiper
  id="main"
  thumbs={{ swiper: thumbsSwiper }}
  controller={{ control: controlledSwiper }}
  navigation
  pagination
  spaceBetween={0}
  slidesPerView={1}
>
  <SwiperSlide>Main 1</SwiperSlide>
  <SwiperSlide>Main 2</SwiperSlide>
  <SwiperSlide>Main 3</SwiperSlide>
  <SwiperSlide>Main 4</SwiperSlide>
  <SwiperSlide>Main 5</SwiperSlide>
  <SwiperSlide>Main 6</SwiperSlide>
  <SwiperSlide>Main 7</SwiperSlide>
</Swiper>

<Swiper
  id="thumbs"
  spaceBetween={5}
  slidesPerView={3}
  onSwiper={setThumbsSwiper}
  watchSlidesVisibility
  watchSlidesProgress
>
  <SwiperSlide>Thumb 1</SwiperSlide>
  <SwiperSlide>Thumb 2</SwiperSlide>
  <SwiperSlide>Thumb 3</SwiperSlide>
  <SwiperSlide>Thumb 4</SwiperSlide>
  <SwiperSlide>Thumb 5</SwiperSlide>
  <SwiperSlide>Thumb 6</SwiperSlide>
  <SwiperSlide>Thumb 7</SwiperSlide>
</Swiper>

<Swiper id="controller" onSwiper={setControlledSwiper}>
  <SwiperSlide>Controlled 1</SwiperSlide>
  <SwiperSlide>Controlled 2</SwiperSlide>
  <SwiperSlide>Controlled 3</SwiperSlide>
  <SwiperSlide>Controlled 4</SwiperSlide>
  <SwiperSlide>Controlled 5</SwiperSlide>
  <SwiperSlide>Controlled 6</SwiperSlide>
  <SwiperSlide>Controlled 7</SwiperSlide>
</Swiper>
```
## Minimal Demo on Codesandbox
https://codesandbox.io/s/swiper-react-fork-forked-nwgnx?file=/src/App.js

## Expected Behavior

- Main swiper and thumbs swiper should sync
- Main swiper and controlled swiper should sync

### Demo Video

<video src="https://user-images.githubusercontent.com/3787662/107147958-f8f46b00-6950-11eb-9040-a9a867488361.mov"></video>

## Actual Behaviour

- When main swiper is changed other swipers do not sync
- When thumbs swiper is changed main swiper doesn't change

### Demo Video

<video src="https://user-images.githubusercontent.com/3787662/107148067-8768ec80-6951-11eb-978c-56bfbe54f448.mov"></video>

## Version info
- The featured worked fine until swiper version 6.0.2
- The issue was first found in swiper version 6.4.5 and still exists in 6.4.11

## Additional reports from other devs:
https://github.com/valnub/swiper-react-demo/issues/4

**Comment by DCitalo** [comment]
I did a research on the topic in my issue, this problem happens with any version after 6.3.0, as you can see in [these issue](https://github.com/nolimits4web/swiper/issues/3852)

**Comment by valnub** [comment]
@DCitalo Hey thanks for pointing at that issue. I didn't know this was already raised. I'll close this ticket then as it's a duplicate.
