### ISSUE TITLE
The swiper container is 35px over the top of the viewport

### ISSUE THREAD

**Issue by to8gal** [nolimits4web/swiper#4210]
- Swiper Version: 6.4.11.
- Platform/Target and Browser Versions: Mac OS Big Sur with latest Safari

Just when the script trigger the top of the swiper container goes 35px above the top of the viewport, to fix it I have to add top:35px to the styling which is ugly

Swiper-container should start at top 0

The behaviour was not there until today, I have been working with it fine until today, perhaps an update on Safari? but the behaviour is on Chrome also

**Comment by vltansky** [comment]
Can you make an example?
Stackblitz / codesandbox?

**Comment by nolimits4web** [comment]
Closing as not related to Swiper, it doesn't do that
