### ISSUE TITLE
1 bullet too many when using slidesOffsetAfter

### ISSUE THREAD

**Issue by xxvii** [nolimits4web/swiper#4211]
- Swiper Version: 6.4.11
- Platform/Target and Browser Versions: Firefox 85.0.2, Windows 10 20H2

## What You Did
Create simple swiper with pagination and use slidesOffsetAfter

https://stackblitz.com/edit/31jbh6?file=index.html

## Expected Behavior
Pagination bullets should be the same number as slides

## Actual Behavior
There's always one bullet more than the number of slides

EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
When slidesOffsetAfter is used, one more bullet is appended to pagination.
It's the same if you use slidesPerView: 'auto', if the slides are 100% wide or a fixed number of pixels.
The bug happens only when you use slidesOffsetAfter.

There is a previous 3 years old issue with the same bug, still unsolved: https://github.com/nolimits4web/swiper/issues/2836

**Comment by nolimits4web** [comment]
Sorry, it is by design, `slidesOffsetBefore/After` creates swipeable/snappable areas
