### ISSUE TITLE
Cannot read property 'append' of undefined with init:false since 6.4.9 release

### ISSUE THREAD

**Issue by textarea** [nolimits4web/swiper#4212]
- Swiper Version: 6.4.9 - 6.4.11
- Platform/Target and Browser Versions: macOS, Chrome 88

## What You Did

Create a simple slider with init:false property. Then programmatically add a new slide
Until 6.4.8 release it worked fine. Since 6.4.9 and later get error.
see https://github.com/textarea/swiper-test

## Expected Behavior

Slider start

## Actual Behavior

Slider stops with error "Cannot read property 'append' of undefined"

**Comment by nolimits4web** [comment]
You can't not use Swiper API until it is initialized, `.appendSlide` requires some DOM manipulation which is not possible before init. If you need to add slide before swiper init, just use native DOM API
