### ISSUE TITLE
Unable to Initialize Swiper with DOM Element

### ISSUE THREAD

**Issue by PivitParkour94** [nolimits4web/swiper#4213]
- Swiper Version: 6.4.11
- Platform/Target and Browser Versions: CHROME

## What You Did

Found that initialising multiple swiper instances on the same page, passing in an element is no longer working. Things were working fine in version 4.4.6.

Example Codepen provided at https://codepen.io/PivitParkour94/pen/Jjbboze

Basically, instead of using a class to initialise the swiper, we were providing a DOM element, which worked back in 4.4.6 but doesn't seem to work anymore.

If it working in 4.4.6 was unintended, then this is a feature request to allow for initialising with either the class or the DOM element.

 

## Expected Behavior

Dynamic widget rendering using each dom element should work

## Actual Behavior

In swiper 4.4.6 that works
In swiper 6.4.11 it does not.

If this isn't intended, how are we supposed to initialise multiple Swiper instances if there is no unique selector for each swiper HTML?

**Comment by PivitParkour94** [comment]
SOLUTION FOUND: Use element directly, not jQuery $(elem)
Although this does seem like an issue. It's like 4.x.x supported jQuery and 6.x.x is now library agnostic or something... 
Happy to close this is there's nothing more to discuss

**Comment by nolimits4web** [comment]
Closing as yes Swiper doesn't support jQuery elements
