### ISSUE TITLE
swiper instance is undefined when swiper is called with init: false

### ISSUE THREAD

**Issue by xxvii** [nolimits4web/swiper#4224]
- Swiper Version: 6.4.9 to 6.4.11
- Platform/Target and Browser Versions: Firefox 85.0.2, Windows 10 20H2

## What You Did

"initialized" swiper with init: false, then tried to get instance to init swiper manually when clicking another element 
Try here, open the console and click the "click me" text: https://stackblitz.com/edit/mja2cx?file=index.html

## Expected Behavior

Get instance and init swiper manually
Until Swiper 6.4.8 the code works, something changed after v6.4.8 and the same code doesn't work anymore in 6.4.9 and newer.

TRY HERE: https://stackblitz.com/edit/mja2cx-xfowan?file=index.html

## Actual Behavior

Instance is undefined

**Comment by nolimits4web** [comment]
Swiper instance will be set on container DOM init only AFTER (during) init. So apparently it won't be there until you call init

**Comment by xxvii** [comment]
Ok, so there was an undocument change in the code between 6.4.8 and 6.4.9 which broke something that was perfectly working before...

Any suggestion on how to achieve a similar behavior (init on manual command)? 

Thanks.
