### ISSUE TITLE
Swiper missing smooth transition

### ISSUE THREAD

**Issue by glassesUSA** [nolimits4web/swiper#4230]
- Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE. 6.4.11
- Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC. Edge - MacOS

## What You Did

EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

https://codepen.io/rsnfreud/pen/ExNWWyy

## Expected Behavior

Smooth transition between elements

## Actual Behavior

One of the elements pops out to the side on the second transition

**Comment by nolimits4web** [comment]
It is because you use `loop`. You also need to consider duplicated slides with your custom logic + its not allowed/supported to change slides widths during transitions
