### ISSUE TITLE
onTouchMove() called on pointermove event

### ISSUE THREAD

**Issue by Burakovivan** [nolimits4web/swiper#4231]
- Swiper Version: 6.4.11
- Platform/Target and Browser Versions:  Win10, Chrome  88.0.4324.150

## What You Did

Having a trouble with performance using an angular version of swiper. I'm not trying to implement some specific stuff behaviour of swiper, just simple `<swiper>...some slides....</swiper>` thats what i need. 

Given: 15 swiper components per page, each of them may have 20-40 slides.

At some point i have noticed that page just not respond at all, i have noticed that console spams me with messages like that
`[Violation] 'pointermove' handler took <N>ms`
So it obviously why page freezes. After little investigation i have found that origin of this are method onTouchMove which are called on each move of mouse AND for each swiper instance.  Once `pointermove` event fired by browser - it makes 15 calls of this method.

You can see some sample below, it does not produce such big problems as it very simple example. But you may open task manager of chrome and you will see what impact to CPU when you move mouse. So accounting this simple case you can imagine how it looks at site where swiper are just a little part.

https://stackblitz.com/edit/pointermove-issue

## Expected Behavior
`onTouchMove()` should be called when it touch and then move, not just move

## Actual Behavior
So it simple, just any move raises execution of `onTouchMove()`

**Comment by nolimits4web** [comment]
@vltansky wondering will it be fixed with your PR #4197 (which is not released yet)?

**Comment by vltansky** [comment]
@nolimits4web pretty sure that yes

**Comment by vltansky** [comment]
Can we make a release?

**Comment by nolimits4web** [comment]
Will do tomorrow

**Comment by Burakovivan** [comment]
Thank you very much for fast reaction, hope soon release will solve an issue

**Comment by nolimits4web** [comment]
Just released 6.4.12, can you check if it is fixed there?

**Comment by vltansky** [comment]
https://stackblitz.com/edit/pointermove-issue-z8rczb?file=src%2Fapp%2Fapp.component.ts

Looks fine to me

**Comment by Burakovivan** [comment]
Yeah! Site are working much more better now! at least part with swiper does not make a troubles. 

Thank you very much!
