### ISSUE TITLE
6.4.12 is broken in Next.js

### ISSUE THREAD

**Issue by yura3d** [nolimits4web/swiper#4242]
- Swiper Version: 6.4.12
- Platform/Target and Browser Versions: Node.js 15.8.0, Next.js 10.0.7 (SSR mode)

## What You Did
Add swiper with yarn to my Next.js app, then add the next strings to my React component:
```
import SwiperCore, { Keyboard, Mousewheel } from 'swiper'
...
SwiperCore.use([Keyboard, Mousewheel])
```
Run the app in SSR mode.

## Expected Behavior

No errors like it was in 6.4.11 and below.

## Actual Behavior

![image](https://user-images.githubusercontent.com/10958696/108114682-2c9a6800-70aa-11eb-915e-17cab5565080.png)

I can provide the whole stacktrace but it contains only webpack-specific things and nothing related to swiper files.

I compared 6.4.12 to 6.4.11 and think that something went wrong in module bundling [here](https://github.com/nolimits4web/swiper/compare/v6.4.11...v6.4.12#diff-a1b8814b71c051b803bbb6aab1231aa580e29f2f5050ce363620404994aa3c11).

**Comment by vltansky** [comment]
Angular demo: https://stackblitz.com/edit/pointermove-issue-z8rczb?file=src%2Fapp%2Fapp.component.ts

**Comment by jamiecounsell** [comment]
I am also having this exact same issue in a react app bundled with webpack (no next.js around). Same function coming up as "is not a function" when called.
