### ISSUE TITLE
Breakpoints based on Container width and not window width with ResizeObserver

### ISSUE THREAD

**Issue by katerlouis** [nolimits4web/swiper#4244]
**Is your feature request related to a problem? Please describe.**
I have a swiper instance with 3 slides. When they all fit inside the container, I want to disable sliding and all controls and just use swiper as a layout. When they don't fit the parent any longer, I want "swiper to be an actual slider with certain swiper settings"

**Describe the solution you'd like**
`containerBreakpoints: {}` property that works just as `breakpoints: {}` does, but using ResizeObserver for width changes and not `window.matchMedia()` or `window.resize()`

**Describe alternatives you've considered**
I guess I could do something similar myself. But I'm too afraid to run into bugs. Swiper is pretty complex and I've run into a lot of issues over the years, when trying fancy stuff with updating settings and killing and re-initializing the instance etc.

**Comment by ettoredn** [comment]
Does this fix https://github.com/nolimits4web/swiper/issues/4019 ?

**Comment by nolimits4web** [comment]
@ettoredn yes, thanks
