### ISSUE TITLE
Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList' after upgrade

### ISSUE THREAD

**Issue by Hirbod** [nolimits4web/swiper#4247]
- Swiper Version: 6.4.14
- Platform/Target and Browser Versions macOS, every browser

## What You Did

EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

Upgraded from 6.4.5 to 6.4.14

## Expected Behavior

EXPLAIN WHAT IS TO BE EXPECTED, HERE.

Since the update, I get a
Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.

## Actual Behavior

Should not throw error

<img width="693" alt="Bildschirmfoto 2021-02-17 um 17 21 13" src="https://user-images.githubusercontent.com/504909/108233953-923b3280-7144-11eb-8c0a-6abe9890c267.png">

**Comment by nolimits4web** [comment]
Would be great to see minimal live demo with the issue

**Comment by Hirbod** [comment]
My application is HUGE. I just updated from 6.4.5 to 6.4.15 and this issue did appear. I have multiple sliders on my page, I will try to isolate the issue.

**Comment by Hirbod** [comment]
@nolimits4web Reverting to 6.4.5 fixed the issue for me so far. I have very limited time to isolate the issue right now, I guess a DOM7 commit had a regression

**Comment by Hirbod** [comment]
@nolimits4web I did a downgrade from 6.4.14 back to 6.4.5 and the issue is gone. Since the error is happening in DOM7, I guess some changes there introduced the regression

**Comment by nolimits4web** [comment]
There were no any changes to Dom7 since then. Still need to see live example (Fiddle/CodeSandbox/...) to see know where it comes frmo

**Comment by Hirbod** [comment]
@nolimits4web the issue is not traceable locally on my development setup but once I deploy in production, it happens. I did few more tests, and even 6.4.12 is working perfectly. The error appears as soon as I upgrade to 6.4.14. It should be easy to trace the differences between the releases to get a clue what has been changed

**Comment by Hirbod** [comment]
@nolimits4web I got the reason now:

I have a ResizeObserver which destroys the swiper if a resize on the container is detected and reinitialize it. And this is breaking since 6.4.14.

```js
  _registerObserver() {
    const ro = new ResizeObserver(() => {
      // this operation is pretty heavy but
      // the recalculation is heavy so we need to reinit
      this.swiper.destroy()
      this._initCarousel()
    })
    ro.observe(this._element.querySelector('.swiper-container'))
  }
```

**Comment by Hirbod** [comment]
Looks like you were faster than me :D

**Comment by chabb** [comment]
Thanks, just got the same issue.
