### ISSUE TITLE
Non-reactive vue props

### ISSUE THREAD

**Issue by MentalGear** [nolimits4web/swiper#4251]
- Swiper Version: 6.4.11
- Platform/Target and Browser Versions: macos safari, chrome

## What You Did

Trying to deactivate mouse wheel control live.

## Code
```js
<swiper
:mousewheel="
      mousewheelActive_swiperFullPages ? { forceToAxis: true } : false
    "
>
```

## Expected Behavior

Deactivated

## Actual Behavior
Swiper prop does not change.  Only full reload changes props.

**Comment by nolimits4web** [comment]
Such things are not reactive, you need to call `swiper.mousewheel.enabled()`/`.disable()` to enable/disable it

**Comment by MentalGear** [comment]
Vue props are expected to be reactive. From the Vue documentation.

> All props form a one-way-down binding between the child property and the parent one: when the parent property updates, it will flow down to the child
> ...
> In addition, every time the parent component is updated, all props in the child component will be refreshed with the latest value. 
https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow

Don't know how hard it is to make it reactive, but it would make it conform to expected Vue props behaviour.
