### ISSUE TITLE
Issues since your refactors started since 6.4.14+

### ISSUE THREAD

**Issue by Hirbod** [nolimits4web/swiper#4258]
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: Web, every browser

## What You Did

I upgraded from 6.4.12 to 6.4.14 and 6.4.15. Downgrading to 6.4.12 resolves issue.
So there must have been a commit inside of your refactores which had a major bc or regression

## Expected Behavior

Shall not break

## Actual Behavior

Since the upgrade (and from my understanding watching the commits) some refactors have taken place. which hardly break my swipers with `slidesPerView: 'auto'`

To make the Issue more understandable, I have two videos, one with v6.4.12 which is working perfectly fine and one with v6.4.15 which is shifting the slideshow, breaking the actually visible index, introduce position jumps while navigating. Something is totally off. I also tried changing parameters, adding "loopedSlides" but nothing fixes the problem.

Full Browser Width (100%) while the first part is reserved for my arrows and the last part for the swiper.

Perfect: (6.4.12)
https://streamable.com/l7hzor

Broken: (6.4.15)
https://streamable.com/3339oz

You can see in the broken link, that the first image is not aligned correctly (like a 30px shift), no opacity effect is kicking in, because the index/first/next classes are set wrong inside the code and the calculation is off + the slideshow jumps around.

I have a even bigger issue on another slideshow with fewer elements, this is actually breaking super hard: (6.5.14)
https://streamable.com/g9m9ov

This is my config, which was working perfectly before the update.
```js
{
      loop: true,
      grabCursor: true,
      // Disable preloading of all images
      preloadImages: false,
      touchStartForcePreventDefault: true,
      touchMoveStopPropagation: true,
      shortSwipes: window.innerWidth <= 768 ? true : false,
      threshold: 15,
      lazy: {
        checkInView: true,
        loadPrevNext: true,
        loadPrevNextAmount: 6,
        watchSlidesVisibility: true,
      },
      pagination: {
        el: this._element.querySelector('.swiper-pagination'),
        type: 'bullets',
        clickable: true,
      },
      watchOverflow: true,
      watchSlidesProgress: true,
      watchSlidesVisibility: true,
      centeredSlides: false,
      spaceBetween: 0,
      loopedSlides: 0,
      navigation: {
        nextEl: this._element.querySelector('.swiper-button-next'),
        prevEl: this._element.querySelector('.swiper-button-prev'),
      },
      slidesPerView: 'auto',
      breakpoints: {
        768: {
          spaceBetween: 0,
        },
      },
    }
```

**Comment by nolimits4web** [comment]
1. Your video links don't work and not too helpful
2. Provide live example with StackBlitz!

**Comment by Hirbod** [comment]
You need to press the play button. I can't sit around and spend hours building live examples when you introduce breaking changes in between minor/bugfix releases. I provided as much information as time allows me to be helpful + my config + videos.

**Comment by nolimits4web** [comment]
> I can't sit around and spend hours building live examples when you introduce breaking changes in between minor/bugfix releases

Same, we can't sit and spend hours trying to replicate each and every issue to understand what was meant and was doesn't work
