### ISSUE TITLE
slidesPerView: auto and loop: true bug

### ISSUE THREAD

**Issue by Hirbod** [nolimits4web/swiper#4262]
Since you closed and subsequently locked my ticket #4258, I am unfortunately forced to open a new ticket. I understand that you receive a lot of requests and error tickets, many of which are user errors. However, I have reported bugs to you repeatedly in the past and all of them were reproducible even without a demo and were mostly fixed by you within a short time. I have the feeling that overall you react very irritated and rude to tickets, that's why I also answered stroppy. I would like to apologize for that. You can also discuss without having to block a post if you do not share the same opinion.

My project is very large and making exact copies to demo is practically impossible. That's why I created videos to show the problems that Swiper no longer aligns correctly to the left edge, suddenly jumps when looping and the active slide is always in the invisible area.

I even did more tests now and in 6.4.14 everything is ok.

I strongly suspect that 
https://github.com/nolimits4web/swiper/commit/67449179b807829234b78029e0ab8034c981ed89 
https://github.com/nolimits4web/swiper/commit/ad64733b26aeebe1e0acc64474c81482742a8b62
https://github.com/nolimits4web/swiper/commit/e319f9e41f34e72dc976ea5a4dd9ad288b5aa0aa

caused the problem, as it is the only major commit between 14 and 15 that I believe introduced the regression.

I spend nearly 2 hours on StickBlitz to create a demo, but I couldn't get the same breaking as on my project when trying to replicate it. At least when you drag and move you see, that it jumps weirdly.

https://stackblitz.com/edit/shetmt

Please have a look at those two videos to understand the difference between both (specially the alignment on the left when the video starts and the missing animation because the active-slide class is invisible, since the position is wrong)

Perfect: (6.4.12)
https://streamable.com/l7hzor

Broken: (6.4.15)
https://streamable.com/3339oz

If the video does not start you need to click on it (streamable play button is weird sometimes)

I hope this one here is more helpful. For now I need to freeze on 6.4.12 because this is the last version which works perfectly fine.

The first image (which is the active one) is only visible 10px.

<img width="1101" alt="Bildschirmfoto 2021-02-23 um 13 44 28" src="https://user-images.githubusercontent.com/504909/108845096-49202e00-75dd-11eb-8560-f98927d1c8b6.png">

**Comment by Hirbod** [comment]
Some more informations and findings:

```scss
  .swiper-slide {
    &[class*="col-"] {
      min-width: 230px;
      max-width: 440px;
        padding-left: 20px;
        padding-right: 20px;
      }
    }
 ```
 
 When I remove padding-left/padding-right, the jumping issues disappear (as said, haven't been an issue in version < 6.4.15.
I tried to remove the padding and set `spaceBetween` instead, but that value stopped working too in 6.4.15

**Comment by nolimits4web** [comment]
Thanks, but your stack blitz doesn't represent the issue, and it is wrong by design as setting different slide widths with `.swiper-slide:nth-child` will make it work wrong anyway because of nature of how loop works.

@vltansky do you understand what is the issue?

**Comment by Hirbod** [comment]
Its a fork from your `slidesPerView: auto` demo. But you are right, it does not represent the issue. I am trying hard to replicate it 1:1

**Comment by Hirbod** [comment]
Ok.. I managed to fix it. It was indeed padding-left and padding-right on `.swiper-slide` with `spaceBetween: 0`.
So I think, paddings are not allowed on the slide anymore since 6.4.15?

I removed the padding and set spaceBetween instead, now its working as expected again

**Comment by Hirbod** [comment]
@nolimits4web feel free to close it, since I have a working solution for me now, but it might be still an issue for other people which have set padding-left and padding-right on the grid-cols inside the slide.
