### ISSUE TITLE
Swipper "eating" the mousedown and mouseup events

### ISSUE THREAD

**Issue by rsofista** [nolimits4web/swiper#4266]
- Swiper Version: 6.3.5
- Platform/Target and Browser Versions: Windows 10, Firefox 86.0 (64-bits)

## What You Did

    document.addEventListener('mousedown', () => {
        console.log('down')
    })

    document.addEventListener('mouseup', () => {
        console.log('up')
    })

 I didn't create a "minimal reproduction" since the situation looks very simple to duplicate.

## Expected Behavior

To not stop the events propagation

## Actual Behavior

The issue really is that I can't know if the user is dragging the swipper or not.
All the following events don't trigger:

    <Swiper
        onDrag={() => console.log('onDrag')}
        onDragCapture={() => console.log('onDragCapture')}
        onDragEnd={() => console.log('onDragEnd')}
        onDragEndCapture={() => console.log('onDragEndCapture')}
        onDragEnter={() => console.log('onDragEnter')}
        onDragEnterCapture={() => console.log('onDragEnterCapture')}
        onDragExit={() => console.log('onDragExit')}
        onDragExitCapture={() => console.log('onDragExitCapture')}
        onDragLeave={() => console.log('onDragLeave')}
        onDragLeaveCapture={() => console.log('onDragLeaveCapture')}
        onDragOver={() => console.log('onDragOver')}
        onDragOverCapture={() => console.log('onDragOverCapture')}
        onDragStart={() => console.log('onDragStart')}
        onDragStartCapture={() => console.log('onDragStartCapture')}
    /Swiper>

So my solution was to get the mousedown and mouseup event, if the user has the mouse pressed then it must be dragging something... at least that the logic.

I'm making something similar to Netflix where if your mouse hovers for a second over one of the the items it shows a preview, but in my case is showing the preview when the user is also dragging so I need the check that.

Not sure if the 'mousedown' or 'mouseup' could be propagated but any workaround would be appreciated, thanks.

**Comment by nolimits4web** [comment]
1. assign events on Swiper element (`.swiper-container`)
2. use `capture` el.addEveltListener('mousedown', () => {}, true)
