### ISSUE TITLE
autoplay doesn't work

### ISSUE THREAD

**Issue by taoqf** [nolimits4web/swiper#4270]
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: Debian+node15+chromium.

## What You Did

https://mmstudio.vercel.app/en-us/components/swiper#basic

## Expected Behavior

swiper should autoplay.

## Actual Behavior

do not play at all, even with prop

```
autoplay={{delay:100}}
```

**Comment by nolimits4web** [comment]
Check documentation, you need to install Autoplay module

**Comment by taoqf** [comment]
Thanks for your replay. but I did not find any doc about this at https://swiperjs.com/react? where can I get the document about autoplay?

**Comment by taoqf** [comment]
Thanks. It is really difficult for uses to use this without any valuable document.
I did this in my code, hoping to help someone else use autoplay in react.

```ts
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, Keyboard, EffectCube, Swiper as Core } from 'swiper';
import 'swiper/swiper.min.css';

function MyComponent(){
	Core.use([Autoplay, EffectCube, Keyboard]);

	return <>
		<Swiper
			spaceBetween={50}
			slidesPerView={1}
			// autoplay={true}
			autoplay={{
				delay: 3000,
				waitForTransition: false,
				reverseDirection: false,
				stopOnLastSlide: false,
				disableOnInteraction: true
			}}
			keyboard={{
				enabled: true,
				onlyInViewport: true,
				pageUpDown: true
			}}
			effect='cube'
			speed={800}
			onSlideChange={() => console.log('slide change')}
		>
			<SwiperSlide><img src="/images/lb1.png" /></SwiperSlide>
			<SwiperSlide><img src="/images/lb1.png" /></SwiperSlide>
			<SwiperSlide><img src="/images/lb1.png" /></SwiperSlide>
			<SwiperSlide><img src="/images/lb1.png" /></SwiperSlide>
			<SwiperSlide><img src="/images/lb1.png" /></SwiperSlide>
			<SwiperSlide><img src="/images/lb1.png" /></SwiperSlide>
		</Swiper>
}
```

**Comment by vltansky** [comment]
@taoqf 
its mentioned here
![image](https://user-images.githubusercontent.com/5851280/109399289-ace28800-794a-11eb-949c-d80815e875b8.png)

Do you have ideas on how to improve docs?

**Comment by taoqf** [comment]
1. I think `you should install them first` should be `you should import and use them first`. `install` means `use yarn/npm to install the module`.
2. It will be better if there is an example in topic `react`, the code example will help users more effectively.
3. Like the example I give, I renamed one of `Swiper`s to `Core`, I did not check the source code, maybe the typescript declaration is not correct, or I think we should rename one of them(after I checked the topic `custom build`, I changed my code and import default in `react/core` so I don't need to rename it).
4. The example in document told me to import `swiper/swiper.scss`, but the file will throw an error said `:root is not a correct css selector` when I use swiper with [next.js](https://nextjs.org/), so I changed to `swiper/swiper.min.css`.

Thanks for your replay, again.

**Comment by vltansky** [comment]
1. You dont need to install modules, only to import and "use"
2. Screenshot if from the react page: https://swiperjs.com/react#usage
3. The example in usage is following:
```js
// import Swiper core and required modules
import SwiperCore, { Navigation, Pagination, Scrollbar, A11y } from 'swiper';
// install Swiper modules
SwiperCore.use([Navigation, Pagination, Scrollbar, A11y]);
```
(see in the end of usage section)
4. Yes we should mention css modules, `min.css` files was added for next.js / nuxt: https://github.com/nolimits4web/swiper/pull/4060

**Comment by qiwang97** [comment]
> ```ts
> Autoplay
> ```

 Thanks a lot. In fact, it's really hard to find what i need in doc.

**Comment by duoluodexiaoxiaoyuan** [comment]
> > ```ts
> > Autoplay
> > ```
> 
> Thanks a lot. In fact, it's really hard to find what i need in doc.多谢了。事实上，在doc中很难找到我需要的东西。

我最近遇到一个问题，有时候我的自动轮播会不生效，关键这种情况是偶发的，我还是没有定位到问题，不知道大佬是否遇到过类似的情况。

**Comment by qiwang97** [comment]
> 

猜测可能是后端数据更新前后轮播组件内部没更新 如果数据只获取一次，那就等数据结束后初始化实现（触发组件销毁重建）

**Comment by qiwang97** [comment]
> > > ```ts
> > > Autoplay
> > > ```
> > 
> > 
> > Thanks a lot. In fact, it's really hard to find what i need in doc.多谢了。事实上，在doc中很难找到我需要的东西。
> 
> 我最近遇到一个问题，有时候我的自动轮播会不生效，关键这种情况是偶发的，我还是没有定位到问题，不知道大佬是否遇到过类似的情况。因为数据是从后端获取的，就是会轮播的过程中突然就中断了

猜测可能是后端数据更新前后轮播组件内部没更新 如果数据只获取一次，那就等数据结束后初始化实现（触发组件销毁重建）
