### ISSUE TITLE
Swiper props are not working on ios safari

### ISSUE THREAD

**Issue by faskade** [nolimits4web/swiper#4272]
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: ios 12.4.8/Safari

## What You Did
I just tried to provide some props to swiper. Even in vue playground from this repo, this bug reproduces.  
For instance, you can just try "npm run vue" and check it on ios. none of the props are working.

## Expected Behavior

Swiper gets the props

## Actual Behavior
Swiper uses default props in any case. 

## How it can be fixed
The reason is that `Object.keys(props)` returns an empty array in function `getParams`. 
I suggest you convert props into a plain object before using `Object.keys()`. 
It could be reached for example by: `plainObj = JSON.parse(JSON.stringify(obj));`
Or: `plainObj = Object.assign({}, obj)`

**Comment by vltansky** [comment]
@faskade would you want to open PR?

**Comment by faskade** [comment]
@vltansky done

**Comment by nolimits4web** [comment]
Fixed in #4273
