### ISSUE TITLE
Disable loop if slides length less when windows size

### ISSUE THREAD

**Issue by pravo-pro** [nolimits4web/swiper#4276]
А как можно решить эту проблему?
Есть ли другой способ?

Было бы лучше, если была такая опция, которая бы отключала `loop`, если все слайды помещаются в экран и при `$(window).resize` проверяля на соответсвию этому условию.

_Originally posted by @bekliev in https://github.com/nolimits4web/swiper/issues/1436#issuecomment-139869944_

Изменилось что либо с этого времени? чет не нашел подобной опции в доках.
Очень нужная опция при настройках slidesPerView: 'auto', когда например крутятся партнеры, а на начальном этапе там 2-3 лого, и они свободно влезают на весь экран.   loop не работает. т.к. даже с добавленными по бокам еще 2-3 через loopedSlides  слайды влезают. а добавить больше чем слайдов есть нельзя.

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
