### ISSUE TITLE
Navigation does not work with<details>

### ISSUE THREAD

**Issue by CrushyChilli** [nolimits4web/swiper#4279]
- Swiper Version: 6.4.15.
- Platform/Target and Browser Versions: Windows 10, Chrome

## What You Did

I am trying to use swiper in `<details></details>` (It is a open/close tab html tag).
Like this:
<details>
<summary>Why?</summary>
Because
</details>
And here is the example about what I am trying to do.

https://stackblitz.com/edit/ddfwbe?file=index.html

## Expected Behavior

It should be able to swipe the images with buttons smoothly.

## Actual Behavior

I cannot use the next/prev btn to swipe the images,
and It swipes "heavily" with mouse dragging.

**Comment by nolimits4web** [comment]
Enable `observer` in swiper parameters

**Comment by CrushyChilli** [comment]
> Enable `observer` in swiper parameters

I tried like you said,
but it still not work...

**Comment by nolimits4web** [comment]
Then you need to call `swiper.update()` when summary opens https://stackoverflow.com/questions/7363117/detecting-the-opening-or-closing-of-a-details-element

Closing as not related to swiper directly
