### ISSUE TITLE
Slider trembles slightly

### ISSUE THREAD

**Issue by tendo14** [nolimits4web/swiper#4284]
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: Codesandbox, Mac, Chrome

## What You Did

We created a slider which shows only four slides. If the width is great enough, you should see all slides and it should not be possible to slide anywhere. 

https://codesandbox.io/s/inspiring-noether-14rr8

## Expected Behavior

We expect that the slider stands fixed.

## Actual Behavior

It works as expected but in certain circumstances the slider slightly trembles. You can see the change inside the `slider-wrapper` of the `transform: translate3d()`.

**Comment by nolimits4web** [comment]
What are the `certain circumstances`?

**Comment by tendo14** [comment]
`certain circumstances` is maybe not the term for it. It moves one or two pixels while dragging. This should not be the case if all items are visible.

**Comment by vltansky** [comment]
@tendo14 I think a video would help

**Comment by tendo14** [comment]
https://user-images.githubusercontent.com/16562781/109514361-3ce91480-7aa6-11eb-8eba-2a3138294bf9.mov

You see it for example in second 3 or 6

**Comment by tendo14** [comment]
@nolimits4web why did you closed this bug?

**Comment by vltansky** [comment]
@tendo14 he closed it with commit

**Comment by tendo14** [comment]
Oh. Great. I haven't see it. Thanks :)

**Comment by hauptrolle** [comment]
@vltansky Thank you for the quick fix. Are there any plans to publish this soon?
