### ISSUE TITLE
Slide width does not include margins

### ISSUE THREAD

**Issue by gjunkie** [nolimits4web/Swiper#429]
If slides have a margin the slider does not act as expected. Active slides are no longer left aligned by default and has jumpy effects when reaching the end of the slider and first slides are cloned/appended to the end.

I suspect this is because Swiper is no accounting for margins when calculating slide widths.
/\* css */
  .swiper-container {
    width: 100%;
  }
  .swiper-container, .swiper-container .swiper-slide {
    height: 235px;
  }
  .swiper-container .swiper-slide {
    margin: 0 10px;
  }

/\* js */
    var options = {
      freeModeFluid: true,
      loop: true,
    };
    var mySwiper = new Swiper('.swiper-container', options);

**Comment by orelero** [comment]
"Just add another div within slide and apply these styles to it"

Does not work either.

**Comment by bintbj** [comment]
So what if the width of slider are different. 
It's not working when using 'cssWidthAndHeight: 'width''.
