### ISSUE TITLE
making even numbers slides to be centered

### ISSUE THREAD

**Issue by ArianHamdi** [nolimits4web/swiper#4290]
- Swiper Version:  6.4.15
- Platform/Target and Browser Versions: macOS / Chrome

## What You Did

I want to show a preview of next and previous slide in a loop slider.
so I used decimal number for slidePerView such as 1.2 or 2.3 and set centeredSlides to true.

here is a sandbox code: https://codesandbox.io/s/swiper-center-mode-udjgu?file=/src/App.js

## Expected Behavior

![Screenshot 2021-03-02 at 8 39 14 AM](https://user-images.githubusercontent.com/59548833/109654108-a6a10700-7b16-11eb-892e-37bef430100f.png)
**for sliderPerView 2.3**

## Actual Behavior

![Screenshot 2021-03-02 at 8 39 31 AM](https://user-images.githubusercontent.com/59548833/109654247-d3551e80-7b16-11eb-9fdd-2626edbb5210.png)

this is not what I want to achieve.
the problem is with even numbers in slidePerView.
it's ok with odd numbers such as 1.2.

**Comment by nolimits4web** [comment]
Such behavior is not supported `centerSlides` always centers 1 currently active slide
