### ISSUE TITLE
Better performance of updating virtual sliders

### ISSUE THREAD

**Issue by sayjeyhi** [nolimits4web/swiper#4293]
In `virtual` mode, there is some code that updates slides when the user applied some changes to the swiper.
I thought if the updating checks if the swiper is animating or not and just update the swiper when user transition is done, it will be so better, especially on large slides.

I mean, in this file:
`https://raw.githubusercontent.com/nolimits4web/swiper/master/src/react/virtual.js`

checking if swiper is animating before this updates:
```js
  swiper.updateSlides();
  swiper.updateProgress();
```

to be like this:
```js
if(swiper.animating) {
  swiper.updateSlides();
  swiper.updateProgress();
}
```
and thanks for this great work. :100:

**Comment by nolimits4web** [comment]
Thanks, Virtual slides already works similar and doesn't do any calculation during animation/transition
