### ISSUE TITLE
dynamic data is loaded into wrong slide

### ISSUE THREAD

**Issue by zhengyu88** [nolimits4web/swiper#4301]
- Swiper Version: swiper@6.4.15 
- Platform/Target and Browser Versions: Windows 10 and CHROME 88.0.4324.190.

## What You Did

I am trying to dynamically load data into slide, however, I find data is loaded in wrong slide since there are slides having same `id`. 

For example, there are three slides with different id:

      <div class="swiper-slide" id='1'></div>
      <div class="swiper-slide" id='2'></div>
      <div class="swiper-slide" id='3'></div>

I construct html code to update slide:

       on: {
            slideChangeTransitionStart: function(){
                construct_slide(this.activeIndex);
            },
        }
       ......
       function construct_slide(activeIndex) {
           ......
           var html_body = '<div class="business-content"><label class="business-title">'+business+'</label>';
           ......
           $('#'+activeIndex).html(html_body);
       }

However, after the web page is loaded, I find there are two same `div` that have same id:

![image](https://user-images.githubusercontent.com/4889114/110088839-53f27400-7dd0-11eb-8789-7c4868501d63.png)

Problems:
1. When I swipe the page to slide 3, it is empty because the first `<div id='3'>` loads data instead of the expected one (the second `<div id='3'>` ). 
2. Since I set `loop` as `true`,  when I swipe from slide 3 to slide 1, slide 1 is also empty, because the second `<div id='1'>` is shown on the screen instead of the first `<div id='1'>`. And I also find the `activeIndex` of the first slide is 4 instead of 1.

Code:  https://stackblitz.com/edit/swiper-demo-1-default-bl99nl?file=index.html

**Comment by nolimits4web** [comment]
This is how `loop` works, in your code you need to consider duplicated slides. Closing as not the issue
