### ISSUE TITLE
swiper + display: grid multirow

### ISSUE THREAD

**Issue by qwave** [nolimits4web/swiper#4307]
- Swiper Version: 6.5.0
- Platform/Target and Browser Versions: Windows, Chrome 88.0.4324.190

## What You Did

Trying to use display: grid multirow with slidesPerView auto

 https://codepen.io/mdxclr/pen/vYyzpdy

## Expected Behavior

The task is to make the every seven child element larger in twice then other. For that the best way is to use display: grid for swiper-wrapper and grid-auto-columns.

## Actual Behavior

Arrow navigation doesn't work - you can't go from 2 page to 1 and if clicking on the last page - "Prev" button - you'r going to second page, but not previous. Also pagination showing wrong count.
Tried also to use `slidesPerGroup` and `slidesPerGroupSkip` param but it doesnt made big change.

**Comment by nolimits4web** [comment]
such layout is not supported by swiper, what is possible to put blocks and divide to slides like so (red box is individual slide):

<img width="1423" alt="ss" src="https://user-images.githubusercontent.com/999588/111442348-5088b200-8719-11eb-8712-ea65ef8145db.png">
