### ISSUE TITLE
Could not find a declaration file for module 'swiper/vue'

### ISSUE THREAD

**Issue by zhjq19660117** [nolimits4web/swiper#4308]
- Swiper Version: 6
- Platform/Target and Browser Versions:  Windows, VSCode.

## What You Did
Magic_swiper.vue
<template>
    <swiper
    :slides-per-view="3"
    :space-between="50"
    @swiper="onSwiper"
    @slideChange="onSlideChange"
  >
    <swiper-slide>Slide 1</swiper-slide>
    <swiper-slide>Slide 2</swiper-slide>
    <swiper-slide>Slide 3</swiper-slide>
  </swiper>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
// import Swiper core and required modules
import SwiperCore, { Autoplay, Navigation, Pagination, Scrollbar, A11y } from 'swiper'
// Import Swiper Vue.js components
import { Swiper, SwiperSlide } from 'swiper/vue'

// Import Swiper styles
import 'swiper/swiper.scss'
SwiperCore.use([Autoplay, Navigation, Pagination])

export default defineComponent({
  name: 'Magic_swiper',
  props: {
    msg: String
  },
  components: {
    Swiper,
    SwiperSlide
  }
})
// 魔方家居图片轮播组件
</script>

 https://codesandbox.io/...

## Expected Behavior

EXPLAIN WHAT IS TO BE EXPECTED, HERE.

## Actual Behavior

EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

**Comment by nolimits4web** [comment]
Use // @ts-ignore, there is no declarations for Swiper Vue components

**Comment by vltansky** [comment]
PR with types: https://github.com/nolimits4web/swiper/pull/4138

duplicate of https://github.com/nolimits4web/swiper/issues/3916
