### ISSUE TITLE
Add a way to disable swiper for some breakpoints

### ISSUE THREAD

**Issue by jf-viguier** [nolimits4web/swiper#4311]
There is an issue here but I should be great to have an enable/disable method instead of managing init or destroy WDYT ?
https://github.com/nolimits4web/swiper/issues/3175

**Comment by cb2004** [comment]
This is the one thing keeping me going full Swiper. Just for reference, what is the best method to achieve this right now?

**Comment by jf-viguier** [comment]
init and destroy at resize time

**Comment by cb2004** [comment]
@jf-viguier I don't suppose there are any working examples, it seems to be the one thing I cant really find a reference to that works successfully, and all my efforts have failed.

**Comment by micka-fdz** [comment]
I think it could be a great feature for a recurring need.
Please add a breakpoint specific parameter (like `disable: boolean`).

**Comment by nolimits4web** [comment]
You can set allowSlideNext/Prev parameters to disable sliding in breakpoints

**Comment by micka-fdz** [comment]
Please have a look to:

- `destroy` parameter on [Splide](https://splidejs.com/options/)
- `disable` parameter on [Tiny Slider](https://github.com/ganlanyuan/tiny-slider)
- `unslick` parameter on [Slick](https://kenwheeler.github.io/slick/)

**Comment by jf-viguier** [comment]
@nolimits4web why do you close the issue without discussion ? It's seems that is a main issue.

**Comment by warudin** [comment]
It's really bugging me that it's quite hard to disable swiper for specific breakpoints.
