### ISSUE TITLE
slideToClickedSlide not working in coverflow mode

### ISSUE THREAD

**Issue by giuliac1989** [nolimits4web/swiper#4316]
- Swiper Version: Swiper 6.5.0
- Platform/Target and Browser Versions: macOS, tested with Firefox 86.0 and Chrome 89.0

## What You Did
Set slideToClickedSlide to true in coverflow mode
https://codesandbox.io/s/swiper-effect-coverflow-forked-0rt8h?file=/index.html

## Expected Behavior

Clicking on a .swiper-slide element, swiper should change the active slide.
## Actual Behavior

Clicking on a .swiper-slide element does not change the active slide. Nothing happens.

**Comment by nolimits4web** [comment]
Works totally fine in Chrome:

https://user-images.githubusercontent.com/999588/110774438-da92cf80-826e-11eb-896d-27e412396896.mov

In FF I see issues, but it is a FF bug then, it doesn't capture clicks on elements translated backwards
