### ISSUE TITLE
Nested Swiper navigation events onPrevClick(e) & onNextClick(e) propagates to parent Swiper causing multiple slide changes

### ISSUE THREAD

**Issue by lauritk** [nolimits4web/swiper#4320]
- Swiper Version: 6.5.0
- Platform/Target and Browser Versions: Windows, latest Chrome

## What You Did

Created multiple slides with individual swipers (nested swipers). See https://stackblitz.com/edit/swiper-demo-1-default-n86ump?file=index.html .

## Expected Behavior

Navigation button events should cause only slide change in the current swiper.

## Actual Behavior

Navigation button events propagates also to parent swiper causing the current and the parent swipers to change slides. Source of the event is not checked nor is propagation stopped.

**Comment by lauritk** [comment]
Duh, solved. Parent swiper binded also to child buttons. My bad.

**Comment by nolimits4web** [comment]
Yes, you need to correctly specify navigation elements:

<img width="430" alt="screenshot" src="https://user-images.githubusercontent.com/999588/110799918-b940dc00-828c-11eb-920d-ffb3e5d37c6e.png">
