### ISSUE TITLE
Tree-shaking broken for Angular 11

### ISSUE THREAD

**Issue by RomanRolginSky** [nolimits4web/swiper#4326]
- Swiper Version: 6.5.0
- Platform/Target and Browser Versions: macOS 11.1

## What You Did

- create app with angular cli ([repro repo](https://github.com/RomanRolginSky/ng-swiper-tree-shaking-test))
- simply add import of Swiper module to app module [commit](https://github.com/RomanRolginSky/ng-swiper-tree-shaking-test/commit/322d7c344654e1ff185304b74be8b302efc4beda)
- `npm run build --prod` and analyze chunks' sizes

ER: bundle not blown away
AR: chunk has increased in size a 500Kb

```
#######__________________First run clean app after Angular CLI generation______________
npm run build --prod --source-map

✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.10 MB
polyfills.js        | polyfills     | 128.78 kB
main.js             | main          |  52.25 kB
runtime.js          | runtime       |   6.15 kB
styles.css          | styles        | 118 bytes

                    | Initial Total |   2.28 MB

Build at: 2021-03-12T14:04:23.336Z - Hash: 0c9c8168f1c744ea2181 - Time: 11490ms

#######__________________Second run with import swiper______________

Compiling swiper_angular : es2015 as esm2015
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.60 MB
polyfills.js        | polyfills     | 128.78 kB
main.js             | main          |  52.51 kB
runtime.js          | runtime       |   6.15 kB
styles.css          | styles        | 118 bytes

                    | Initial Total |   2.78 MB

Build at: 2021-03-12T14:05:44.782Z - Hash: f1c0c3e7f34d3f9967e5 - Time: 6569ms
```
**Vendor** bundle 😩

## Expected Behavior

Chunk shouldn't has all swiper plugins included in chunk

## Actual Behavior

seems like all Swiper modules and core are included in chunk without any usage in app

**Comment by vltansky** [comment]
```
$ ng b --prod
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling swiper_angular : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files               | Names         |      Size
main.59893b965718ebd861de.js      | main          | 204.35 kB
polyfills.94daefd414b8355106ab.js | polyfills     |  35.98 kB
runtime.7b63b9fd40098a2e8207.js   | runtime       |   1.45 kB
styles.09e2c710755c8867a460.css   | styles        |   0 bytes

                                  | Initial Total | 241.79 kB

Build at: 2021-03-14T07:11:09.624Z - Hash: f88e8b936f5f183a0e56 - Time: 29536ms
```

Try running `ng build --prod` or `npm run build -- --prod`

**Comment by RomanRolginSky** [comment]
oh, such a stupid mistyping 😫
thanks @vltansky
so now I get only 90kb of swiper. Is it correct for core swiper functionality without any additional modules? I didn't find such info in [doc](https://swiperjs.com/angular#import-module) - I am suggesting to add it somewhere. 
By the way, my question may relates to [this discussion](https://github.com/nolimits4web/swiper/discussions/4228) about lite swiper, doesn't it?

**Comment by vltansky** [comment]
@RomanRolginSky you are very welcome to open PR in [swiper-website repo](https://github.com/nolimits4web/swiper-website)
This is the relevant file for modifications: https://github.com/nolimits4web/swiper-website/blob/master/src/pages/angular.mdx

90 KB including all components or only core?
I'll close this issue, as you can participate in [Swiper 7 discussion](https://github.com/nolimits4web/swiper/discussions/4228) about bundle size.
