### ISSUE TITLE
Memory leaks when using breakpoints in swiper

### ISSUE THREAD

**Issue by DoronTorangy** [nolimits4web/swiper#4327]
I use swiper in a react project, created a swiper container, with 4 slides inside (just minimal text). I used 4 breakpoints that
change the `slidesPerView` option, and after a few manual page resizes (to see the breakpoints effects) i noticed the page freezes for a few seconds, I opened up the `memory` tab in chrome devtools, and was surprised that my JS heap size is over `1000mb`.
When i removed the breakpoints the problem didnt occur.

![Untitled](https://user-images.githubusercontent.com/41499465/111029231-40649000-8404-11eb-97d9-834a1a0d8142.png)

- Swiper Version: 6.5.0 (react-dom 17.0.1)
- Platform/Target and Browser Versions: Windows 10, Chrome 89.0.4389.82 

## What You Did

Created a swiper container with 3-4 slides and 4 breakpoints. after you resize the page manually you will see the slowness kicks in

[https://codesandbox.io/s/swiper-react-fork-forked-hyz3s](url)

## Expected Behavior

Using breakpoints in swiper should be working smooth without memory leaks

## Actual Behavior

After a few resizes (to trigger the breakpoints), the page incrementally becomes slow (until it is completly frozen)

**Comment by nolimits4web** [comment]
Don't understand why it is happening, but issue is with React.StrictMode, remove it and it will work fine

**Comment by Art2058** [comment]
Same issue!

Next.js `reactStrictMode: false`
It will work fine..

**Comment by Algram** [comment]
We are seeing the same issue with an up to date Swiper version and the latest Next.js version.

**Comment by ClockRide** [comment]
> We are seeing the same issue with an up to date Swiper version and the latest Next.js version.

same

**Comment by JRakin** [comment]
same issue with nextjs 12
