### ISSUE TITLE
Slides-per-view="auto" not work

### ISSUE THREAD

**Issue by SymbolStar** [nolimits4web/swiper#4331]
- Swiper Version: 6.5.0.
- Platform/Target and Browser Versions: IOS, ANDROID, CHROME, ETC.

## What You Did

EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.
The width set by swiper-slide does not work.

Demo https://codesandbox.io/s/empty-water-yfmlu?file=/src/components/HelloWorld.vue

`<template>
  <swiper
    :slides-per-view="auto"
    :space-between="50"
    @swiper="onSwiper"
    @slideChange="onSlideChange"
  >
    <swiper-slide>
      <div class="slide">Slide 1</div>
    </swiper-slide>
    <swiper-slide>
      <div class="slide">Slide 2</div>
    </swiper-slide>
    <swiper-slide>
      <div class="slide">Slide 3</div>
    </swiper-slide>
    <swiper-slide>
      <div class="slide">Slide 4</div>
    </swiper-slide>
    <swiper-slide>
      <div class="slide">Slide 5</div>
    </swiper-slide>
    <swiper-slide>
      <div class="slide">Slide 6</div>
    </swiper-slide>
  </swiper>
</template>
<script>
// Import Swiper Vue.js components
import { Swiper, SwiperSlide } from "swiper/vue";

// Import Swiper styles
import "swiper/swiper.scss";
export default {
  components: {
    Swiper,
    SwiperSlide,
  },
  methods: {
    onSwiper(swiper) {
      console.log(swiper);
    },
    onSlideChange() {
      console.log("slide change");
    },
  },
};
</script>

<style lang="scss">
.slide {
  width: 100px;
  height: 50px;
  background-color: cadetblue;
}

.swiper-slide {
    width: 200px;
    height: 50px;
  .swiper-slide-active {
    width: 200px;
  }
}

//   .swiper-slide {
//     width: 200px;
//     background-color: chartreuse;
//   }
</style>`

![image](https://user-images.githubusercontent.com/24540119/111095006-78401480-8577-11eb-8f45-565809b5653a.png)
![image](https://user-images.githubusercontent.com/24540119/111095028-83934000-8577-11eb-8020-a5ed43e9421f.png)

## Expected Behavior
How many cards are displayed adaptively according to the set space-between value

## Actual Behavior
Only one card is displayed on a page

**Comment by nolimits4web** [comment]
Live example or fiddle or anything?

**Comment by SymbolStar** [comment]
update demo link https://codesandbox.io/s/empty-water-yfmlu?file=/src/components/HelloWorld.vue
I used 5.4.5 version is OK. this element.style doesn't change width 

![swiper5 4 5](https://user-images.githubusercontent.com/24540119/111415026-1371ef00-871c-11eb-8ede-decf5cec67a5.png)

**Comment by nolimits4web** [comment]
It works https://codesandbox.io/s/swiper-vue-fork-forked-0kzgw
And you have a error in your code:
```
:slides-per-view="auto"
```
must be
```
slides-per-view="auto"
```
