### ISSUE TITLE
Permit other Paginations to be "opposite"

### ISSUE THREAD

**Issue by kjrgreen** [nolimits4web/swiper#4332]
**Is your feature request related to a problem? Please describe.**
I needed to implement a carousel using Swiper that had bullet pagination. These bullets needed to look as if the slides were vertical, while the actual slides should progress horizontally. I used this hack to accomplish this: https://stackoverflow.com/a/45380882
Doing this selectively is now cumbersome.

**Describe the solution you'd like**
I want to be able to pass a prop to the component (eg: `<Swiper bulletOpposite={true}>`) so that I may selectively make Swiper components exhibit this behavior.

**Describe alternatives you've considered**
Making the prop more generic, eg paginationOpposite.

**Additional context**
See stackoverflow.

Thank you for your time and consideration :)

**Comment by nolimits4web** [comment]
Nothing cumbersome in adding few lines of CSS to customize it to your needs. Swiper can't cover all possible use cases and design requirements. It is fine to add few lines of code to make it look like required
