### ISSUE TITLE
Impossible to override navigation controls without CSS Selector

### ISSUE THREAD

**Issue by RomanRolginSky** [nolimits4web/swiper#4334]
- Swiper Version: 6.5.0
- Platform/Target and Browser Versions: macOS, Windows, IOS, CHROME

## What You Did

Try to customize navigation controls with elementRef in html template
https://stackblitz.com/edit/swiper-angular-navigation-buttons-issue?file=src%2Fapp%2Fapp.component.html

## Expected Behavior

Default navigation controls should not be available if navigation options contain custom nextEl/prevEl

## Actual Behavior

Default navigation controls are present

Seems like condition for navigation is incorrect and doesn't support element (only string css selector). [Code &#8594;
](https://github.com/nolimits4web/swiper/blob/master/src/angular/src/swiper.component.ts#L165)

**Comment by RomanRolginSky** [comment]
There is a workaround - pass a css selector of next/prev buttons. But it is very limited as 2 swipers should be unique in these selectors

**Comment by nolimits4web** [comment]
> But it is very limited

There is no any limitation with this approach. You can pass unique selectors (based on parent swiper class), plus Swiper first looks for matching selectors inside itself

**Comment by RomanRolginSky** [comment]
@nolimits4web thanks for a ultra-quick answer 😊 

So do you mean I should use some slot (`container-end` for example) for custom navigation? With this nuance _Swiper first looks for matching selectors inside itself_ it can works

But what about initial request? Is it a confirmed bug or incorrect usage? Type definitions have possibility to pass `HTMLElement` but unfortunately with no effect

**Comment by nolimits4web** [comment]
@vltansky should shed the light on this :)

**Comment by RomanRolginSky** [comment]
@nolimits4web 
> There is no any limitation with this approach.

There is one limitation yet: 
As we have to place navigation controls inside `swiper` container that has `oveflow: hidden` property, navigation control cannot be placed somehow outside of content area of `swiper`

Goal: make navigation controls fully visible [Repro](https://stackblitz.com/edit/swiper-angular-example-ueidd6?file=src%2Fapp%2Fapp.component.ts)

**Comment by nolimits4web** [comment]
You can just put it outside of swiper https://stackblitz.com/edit/swiper-angular-example-4qrarx?file=src%2Fapp%2Fapp.component.html
