### ISSUE TITLE
getComputedStyle(...) is null

### ISSUE THREAD

**Issue by bbaki** [nolimits4web/swiper#4337]
Hi,
We get this strange error inside [appSignal](https://appsignal.com/) which I was able to track down as a Firefox bug [see](https://stackoverflow.com/questions/46127213/how-to-fix-typeerror-window-getcomputedstyle-is-null-in-firefox). I was unable to reproduce this issue locally but [this](https://github.com/marcj/css-element-queries/issues/148) seems like a possible solution, that is, replace all `window.getComputedStyle` (found in 2 places: updateSlides.js and utils.js) with this function:
```js
function getComputedStyle(element, prop) {
  if (element.currentStyle) {
       return element.currentStyle[prop];
   } else if (window.getComputedStyle && window.getComputedStyle(element, null)) {
       return window.getComputedStyle(element, null).getPropertyValue(prop);
   } else {
       return element.style[prop];
   }
}
```

Something to point out is that the app uses React `16.8.0` with custom SSR.

## Environment
- Swiper Version: `swiper@^5.2.0` resolved as `version "5.4.5"`
- Some example environments that got that error: Windows 10, Mozilla Firefox 86.0 / Windows 10, Mozilla Firefox 63.0 / Windows 7, Mozilla Firefox 86.0 / Windows 8.1, Mozilla Firefox 86.0 / Linux, Mozilla Firefox 63.0 / Windows 7, Mozilla Firefox 75.0 / Windows 10, Mozilla Firefox 78.0

## Expected Behavior
No error being thrown

**Comment by nolimits4web** [comment]
Swiper a while ago on version 6. Does it happen with Swiper v6?

**Comment by bbaki** [comment]
I would need to update and deploy the latest version to production to be sure but `window.getComputedStyle` is still used inside the codebase so I would assume so. If you want however, I can give it a try.

**Comment by nolimits4web** [comment]
you anyway need to update to v6 because v5 is not maintained anymore
