### ISSUE TITLE
Angular: cannot update slides when using virtual

### ISSUE THREAD

**Issue by wiegell** [nolimits4web/swiper#4338]
- Swiper Version: ^6.5.0
- Platform/Target and Browser Versions: Chrome

## What You Did

[https://stackblitz.com/edit/swiper-angular-virtual-njutzo?file=src/app/app.component.ts](https://stackblitz.com/edit/swiper-angular-virtual-njutzo?file=src/app/app.component.ts)

## Expected Behavior

Virtual slides should be updated when data is changed.
Remove `[virtual]="true"` from stackblitz to get expected behavior.

## Actual Behavior

It does not update. It works fine when virtual is not activated.
I cannot get it to update the new content - i tried:
```
        this.cdr.detectChanges();
        this.swiperRef.updateSlides();
        this.swiperRef.update();
        this.swiperRef.virtual.update(true);
```

And tried getting the ref either from the (swiper) event or viewchild.
Also tried looping in ng-container, ng-template and div.
Tried with both regular data binding and async binding. Neither works. Async binding works without virtual.

**Comment by wiegell** [comment]
is it bc i have not implemented renderExternal()? Not sure how to do that in angular, will give it a try though.

**Comment by wiegell** [comment]
Ok after several hours i got the whole shabang working - _but only with [ngr-swiper-wrapper](https://github.com/zefoy/ngx-swiper-wrapper)_!
I followed the suggestions [here](https://github.com/zefoy/ngx-swiper-wrapper/issues/142#issuecomment-581143712), which makes use of renderExternal().
I've tried several hours to get the same behaviour from the regular swiper, but cannot seem to succeed. I think the problem is that the swiper-angular-component never calls renderExternal() even though supplied in the config?
Please see: https://stackblitz.com/edit/swiper-angular-virtual-jpppq8?file=src/app/app.component.ts
(sorry about the mess, notice that the `console("FIRE")` is never called).
Could anyone confirm my suspicion (and fix? :) ) since ngr-swiper-wrapper has announced EOL in favour of the original package?

**Comment by vltansky** [comment]
Hey, thanks for opening an issue and sorry for the delay. I've opened PR with a fix for this.
And you cant use `renderExternal()`, as this is set by Angular component. Same in react/vue/svelte swiper components.

**Comment by wiegell** [comment]
Ok tried your demo and seems to work well, thanks for the quick fix. So you mean that renderExternal is only usable when using the directive? I don't know vue or react - in what situation would i want to use directive + renderExternal instead of the angular component directly?
Maybe this section could be expanded just a little bit?
https://swiperjs.com/swiper-api#render-external-example

**Comment by vltansky** [comment]
`renderExternal` is usable only if you're using core version. What do you mean by directive?
You're very welcomed to contribute to docs https://github.com/nolimits4web/swiper-website

https://github.com/nolimits4web/swiper-website/blob/master/src/pages/swiper-api.mdx#renderexternal-example

**Comment by chopperdaddy** [comment]
Looks like this is still an issue when using [virtual]="true" in angular. Anyone come up with a fix? I'm trying to force Swiper to re-render the slider with the updated date when `ngOnChanges` fires but no luck..

**Comment by sebafra** [comment]
> Looks like this is still an issue when using `[virtual]="true"` in angular. Anyone come up with a fix? I'm trying to force Swiper to re-render the slider with the updated date when `ngOnChanges` fires but no luck..

Any news about this issue???? Any hack???

**Comment by wiegell** [comment]
> > Looks like this is still an issue when using `[virtual]="true"` in angular. Anyone come up with a fix? I'm trying to force Swiper to re-render the slider with the updated date when `ngOnChanges` fires but no luck..
> 
> 
> 
> Any news about this issue???? Any hack???

I think i got it working in a branch i made, but i haven't been using it in a long time. Check the diff out here:

https://github.com/wiegell/ngx-swiper-wrapper/commit/bd7055c308042d606a580a68f6f51feb05caf5ec

Sorry for the many linter changes. Check out the .component file and .directive file.
