### ISSUE TITLE
Parallax mode not working properly with slidePerView more than 2

### ISSUE THREAD

**Issue by hihahihahoho** [nolimits4web/swiper#4339]
## Expected Behavior

Parallax effect on all 5 of slide

## Actual Behavior

Just 2 first slide get animated

demo: [demo link](https://codesandbox.io/s/swiper-parallax-forked-3y9zu?file=/index.html)

**Comment by nolimits4web** [comment]
This is how it works, parallax progress calculated only in previous, current and next (from active) slides

**Comment by khoait** [comment]
You can achieve this by updating slideProgress on progress event. I'm trying to use Parallax with FreeMode and need parallax effect on all slides background.

Below code snippet will overwrite slideProgress calculation with the current slider progress. You can calculate your own progress and also make sure you adjust images/backgrounds position to be in viewport properly.

```
<Swiper
  modules={[Scrollbar, FreeMode, Parallax]}
  slidesPerView={'auto'}
  scrollbar={{ draggable: true, horizontalClass: 'w-20 left-1/2' }}
  parallax={true}
  freeMode={true}
  onProgress={({ slides }, progress) => {
    slides.each((slide) => {
      slide.progress = progress;
    });
  }}
>
```
