### ISSUE TITLE
Rebuild doesn't work when async data is fetched

### ISSUE THREAD

**Issue by baeharam** [nolimits4web/swiper#4344]
- Swiper Version: 6.5.0
- Platform/Target and Browser Versions: MacOS, Chrome

## What You Did

I fetched infinite list data from server, and height should be auto calculated. However, when I enable `autoHeight` of Swiper props, it doesn't re-render swiper when data-fetching is finished.

Reproduction: https://codesandbox.io/s/swiperjs-flexible-autoheight-zk7qt?file=/src/App.js

In above, you can see height of first slide is 0 but when I click second slide and back to first slide, height become normal.

## Expected Behavior

Rebuild should be occurred when data-fetching is finished

## Actual Behavior

Rebuild doesn't occur

**Comment by nolimits4web** [comment]
Use `swiper.updateAutoHeight()` method when items loaded

**Comment by baeharam** [comment]
> Use `swiper.updateAutoHeight()` method when items loaded

@nolimits4web No, I tried but it doesn't work correctly. Is there any other solution?
