### ISSUE TITLE
Google Chrome White bar when scrolling the site Android

### ISSUE THREAD

**Issue by RaTeNo** [nolimits4web/swiper#4345]
Google Chrome v 89   Android
White bar when scrolling the site

https://user-images.githubusercontent.com/6961843/111463903-2c38cf80-8731-11eb-8181-9235fec9cccc.mp4

https://user-images.githubusercontent.com/6961843/111463958-3d81dc00-8731-11eb-907a-bde39dc1acf2.mp4

<body>
	<div class="wrap">

.wrap {
   overflow:hidden;
}

Overflow breaks the site

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/3527
https://github.com/nolimits4web/swiper/issues/3641
