### ISSUE TITLE
How do I know what triggered the slide change? OR `swiper.touches` does not reset itself

### ISSUE THREAD

**Issue by DerHannes85** [nolimits4web/swiper#4346]
- Swiper Version: latest / v6.5.0 / all?
- Platform/Target and Browser Versions: tested on Windows 10 with Chrome Version 89.0.4389.82 (Official Build) (64-bit)

## What I need

I need to know, if the `slideChange` was triggered by navigation (arrow), pagination (dot) or swipe, because our analytics team wants to differentiate the event tracking on the this user behavior.

## What I Did 

In the `slideChange` event I want to know, if the the slide was changed because of a swipe like described in #1682 (`swiper.touches.diff !== 0`).  But when I have used the touch functionality once to move the slider a bit but I did not change the slide. Then I used on of the navigation arrow elements.

## Expected Behavior

The `swiper.touches` should reset itself or there should be another way to check what triggered the `slideChange`. I know, that this could be because of many events (navigation, pagination, code like `slideTo`, autoplay, ...).

## Actual Behavior

`swiper.touches.diff` is "never" `0` again when the touch functionality was used once. It is always set to the last touch/drag event data.

**Comment by DerHannes85** [comment]
I found one hacky workaround for my initial problem.

1. `touchEventsTarget: 'wrapper'` so that the touch events are not triggered on the navigation or pagination elements
2. log `Date.now()` on `touchEnd` event
3. check that logged `touchEndTime` is not older than 300 ms --> then it should be a swipe
4. Set `click` listeners to the navigation and pagination elements to handle these other triggering types

Here is a little demo: https://codesandbox.io/s/swiper-navigation-forked-3kslz

But I am still interested, if there is any better way or this could be a feature request.

**Comment by jjstanton** [comment]
I ran into a very similar scenario today. Although, I solved the issue in a hacky way using the `touchMove` and `touchEnd` events.

I do agree that if some type of "initiator" property could be set on every `slideChange ` event would solve this issue a lot cleaner.

**Comment by kcrwfrd** [comment]
We have a similar desire for analytics tracking. We have a swiper with autoplay and it would be really nice if we could track slide change events that are specifically triggered by the user.

**Comment by ImantsSkultans** [comment]
If You want to separate slide change by code (for example custom navigation button) and slide change by user interaction, then You can achieve it in such way:
1. For button fire slide change and set third param to "false": swiper.slideToLoop(index, 300, false);
2. Listen to any transition event, for example, 'slideChangeTransitionStart' - this will be fired when slide is changed by native user interaction.
