### ISSUE TITLE
Loop duplicates are not reactive as the originals - Vue 2 (not vue swiper component)

### ISSUE THREAD

**Issue by felix-berlin** [nolimits4web/swiper#4349]
- Swiper Version: 6.5.0
- Platform/Target and Browser Versions: All browsers, but tested on macOS, CHROME

## What You Did

Iam using the core Swiper.js version within Vue.js v2. There i created a slider with reactive elements. The Problem is all duplicated slides created by Swiper.js are not reactive as the original slides. There is another open "Issue" with a similar theme: https://github.com/nolimits4web/swiper/issues/2629#issuecomment-565829863

Seams like the duplicates are "only" a html copy from the original slides.

## Expected Behavior

Duplicates are reactive as the originals.

## Actual Behavior

Duplicates are not reactive. Only a simple html copy.

**Comment by nolimits4web** [comment]
There is an official Swiper Vue components for Vue 3, which works correctly

**Comment by felix-berlin** [comment]
@nolimits4web This is correct but i have to use Vue 2. In my opinion Vue 3 is not really ready for production.

**Comment by nolimits4web** [comment]
With core version of Swiper it is impossible to make duplicated slides reactive

**Comment by mark922** [comment]
Similar issue in Angular 10 as well. Any specific solution or reason behind this behavior?

**Comment by maxkopych** [comment]
wow in era when everything reactive this plugin even not able to do simple deep clone (that jquery was able to do 10 years ago). Real modern slider. I guess back to slick slider
