### ISSUE TITLE
Changing swiper-slide aria-label value

### ISSUE THREAD

**Issue by giuliac1989** [nolimits4web/swiper#4353]
Hi, it's possible to change the swiper-slide aria-label value? I need something like "1 of 5" instead of "1/5".  I didn't find anything in the documentation.
Thank you! Swiper is amazing!

**Comment by vltansky** [comment]
As I understand this is not possible right now:
https://github.com/nolimits4web/swiper/blob/master/src/components/a11y/a11y.js#L170

Something similliar to `params.itemRoleDescriptionMessage` should be added
