### ISSUE TITLE
[swiper react] controller module is not working

### ISSUE THREAD

**Issue by nethalayaswanth** [nolimits4web/swiper#4355]
- Swiper Version:  swiper@6.4.5
- Platform/Target and Browser Versions:Windows, IOS, ANDROID, CHROME, ETC.

## What You Did

 tried to implement two way controller  by controller module using reacthooks

sandbox sample below

https://codesandbox.io/s/swiper-react-fork-forked-4v4we

## Expected Behavior

can control swiper instances mutually

## Actual Behavior

nothing really happening

**Comment by nolimits4web** [comment]
Duplicate of #3852
