### ISSUE TITLE
Extra space at the end with slidesPerView: 'auto' and spaceBetween: 0

### ISSUE THREAD

**Issue by dangelion** [nolimits4web/swiper#4369]
I'm developing a carousel edge-to-edge, inside a container but I need to set slides width and "spaces between" via CSS (not JS), but I get an extra space at the end of carousel (after the last slide). 

**NB**: the UI is fluid so I haven't media queries and I haven't fixed size in px. Here is my code:

**JS**

    $(document).ready(function() {
        new Swiper('.swiper-container', {
          slidesPerView: 'auto',
          spaceBetween: 0,
          grabCursor: true,
          freeMode: true,
          roundLengths: true,
        });
    });

**CSS**

    .carousel {
      --size-container-margin-auto: calc(50vw - 50%);
      --grid-gap-horizontal: 3em; //var(--space-md);
      --grid-column-width: calc( (100% - 11*var(--grid-gap-horizontal)) / 12 );
      --carousel-slide-width: calc( (var(--grid-column-width) * 5) + (5 * var(--grid-gap-horizontal)) );
      
      //
      // 1) Ouside the container, edge to edge carousel
      //
      position: relative;
      overflow: hidden;
      > .swiper-container { overflow: visible; width: 100%; }
    
      // This brings carousel outside container from left and right
      margin-left: calc(-1 * var(--size-container-margin-auto));
      margin-right: calc(-1 * var(--size-container-margin-auto));
    
      // This recreate space at the begin and end of slides
      padding-left: calc(var(--size-container-margin-auto));
      padding-right: calc(var(--size-container-margin-auto));
    
    
      //
      // 2) Set slides width and spacing
      //
      .swiper-slide {
        width: var(--carousel-slide-width);
        padding-right: var(--grid-gap-horizontal);
      }
    }

HTML structure is the basic one of Swiper.
Anyway you could see the thing in action here: https://codepen.io/gooogooo/pen/wvgKXbq

Scroll the carousel to the end and you see an extra space that I don't want, check this screenshot:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/eeGBO.jpg

**Comment by nolimits4web** [comment]
It is `padding-right` you have set on last slide

**Comment by dangelion** [comment]
Yes, I read somewhere on docs that using `margin-right` could cause issues, correct?

Otherwise could I use it to distancing slides without having that extra space? Like this:

    swiper-slide:not(:last-child) {
      margin-right: var(--grid-gap-horizontal);
    }

**Comment by dangelion** [comment]
Tried with the code above, it seems work pretty well but resizing the window every 2-5px I got the situation below:

![Frame 4](https://user-images.githubusercontent.com/4182418/112454186-b8ae4800-8d58-11eb-83bc-0dd7c0738f54.jpg)

Seems like it's calculating wrong at some viewport width. The more I have slides, the more the errore is bigger.
