### ISSUE TITLE
Fast click slides error.

### ISSUE THREAD

**Issue by Venegrad** [nolimits4web/swiper#4370]
If fast click on syncs sliders, click will be prevent, clicks missing, and slides not changed. Chrome and edge-chrome last.

https://user-images.githubusercontent.com/9676703/112477419-a98cc180-8d7b-11eb-965c-64c8c35dc822.mp4

https://user-images.githubusercontent.com/9676703/112509833-86710a80-8d99-11eb-83c8-9679c12830b0.mp4

```
 let galleryThumbs = new swiper(thumbs + " .greed-slider__thumbs-slider", {
        spaceBetween: 8,
        slidesPerView: 5,
        watchSlidesVisibility: true,
        watchSlidesProgress: true,
        centerInsufficientSlides: true,
        touchRatio: 0,
        observer: true,
        observeParents: true,
        navigation: {
          nextEl: thumbs + " .greed-slider__next2",
          prevEl: thumbs + " .greed-slider__prev2",
        },
        breakpoints: {
          0: {
            slidesPerView: 3,
            spaceBetween: 8,
          },
          450: {
            slidesPerView: 3,
            spaceBetween: 8,
          },

          900: {
            slidesPerView: 5,
            spaceBetween: 8,
          },
        },
      });

      let galleryTop = new swiper(slider, {
        spaceBetween: 10,
        slidesPerView: 1,
        observer: true,
        observeParents: true,
        navigation: {
          nextEl: thumbs + " .greed-slider__next",
          prevEl: thumbs + " .greed-slider__prev",
        },
        on: {
          slideChange: () => {
            all_youtube_stop();
          },
        },
        thumbs: {
          swiper: galleryThumbs,
        },
      });
```

real demo of issue http://dev.venegrad.com/dem_46/product.html

**Comment by davidgoldcode** [comment]
I've had this issue persisting as well. Did you ever find any resolution?

**Comment by pierrevdk** [comment]
I've got the same problem here, I can't find any way to prevent it. I believe I tried all the apis parameters, but I can't find anything that solves the problem. I experience it here: https://masteos.webflow.io/cas-concrets-investissements/mehdi (slider below the images).

**Comment by amlichner** [comment]
We have noticed this issue for about a month. Here is a video of our usage https://monosnap.com/file/PZV4lvjAr8q1urWpDenwGnnVCyfo3X

**Comment by Venegrad** [comment]
not solved yet?

**Comment by sheepsteak** [comment]
We managed to fix this issue by setting `threshold` to `2`. It's `0` by default and this means sometimes if you click (or touch) and move your mouse or finger slightly it gets interpreted as a swipe I think.

From https://swiperjs.com/swiper-api:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/1379888/116824569-d609d980-ab82-11eb-8813-b81e99fca2f0.png">

**Comment by jannemecek** [comment]
This solved it for us, not sure how I missed this property. Thanks @sheepsteak !

**Comment by aryanrajcom** [comment]
I also faced this problem with thumbs gallery, https://swiperjs.com/demos#thumbs-gallery, thumbs are clickable but the main image was not showing up with quick clicks. @sheepsteak solution to add `threshold: 2,`  fixed it for me.

**Comment by teq-dungbui** [comment]
> We managed to fix this issue by setting `threshold` to `2`. It's `0` by default and this means sometimes if you click (or touch) and move your mouse or finger slightly it gets interpreted as a swipe I think.
> 
> From https://swiperjs.com/swiper-api: <img alt="image" width="1194" src="https://user-images.githubusercontent.com/1379888/116824569-d609d980-ab82-11eb-8813-b81e99fca2f0.png">

thank you so much, you help my life
