### ISSUE TITLE
Last slide goes outside the container (wrong calc)

### ISSUE THREAD

**Issue by dangelion** [nolimits4web/swiper#4373]
Hi @nolimits4web

Here is my carousel (Swiper v6.5.0):

**JS**

    $(document).ready(function() {
        new Swiper('.swiper-container', {
          slidesPerView: 'auto',
          spaceBetween: 0,
          grabCursor: true,
          freeMode: true,
          roundLengths: true,
        });
    });

**CSS**

```
.carousel {
  --size-container-margin-auto: calc(50vw - 50%);
  --grid-gap-horizontal: 3em; //var(--space-md);
  --grid-column-width: calc( (100% - 11*var(--grid-gap-horizontal)) / 12 );
  --carousel-slide-width: calc( (var(--grid-column-width) * 5) + (5 * var(--grid-gap-horizontal)) );
  
  //
  // 1) Edge to edge carousel: brings carousel outside the container
  //
  position: relative;
  overflow: hidden;
  > .swiper-container { overflow: visible; width: 100%; }

  // This brings carousel outside container from left and right
  margin-left: calc(-1 * var(--size-container-margin-auto));
  margin-right: calc(-1 * var(--size-container-margin-auto));

  // This recreate space at the begin and end of slides
  padding-left: calc(var(--size-container-margin-auto));
  padding-right: calc(var(--size-container-margin-auto));


  //
  // 2) Set slides width and spacing
  //
  .swiper-slide {
    width: var(--carousel-slide-width);
    //padding-right: var(--grid-gap-horizontal);
    &:not(:last-child) {
      margin-right: var(--grid-gap-horizontal);
    }
  }
}
```

HTML structure is the basic one of Swiper.

It works pretty well but on some viewport width the last slide goes outside the swiper-container, see here:

![Frame 4](https://user-images.githubusercontent.com/4182418/112454186-b8ae4800-8d58-11eb-83bc-0dd7c0738f54.jpg)

And here a video while resizing:

https://user-images.githubusercontent.com/4182418/112455085-abde2400-8d59-11eb-8202-dea699b1a476.mp4

Seems like it's calculating wrong at some viewport width (maybe the `transform: translate3d(-.....px, 0px, 0px)` on `swiper-wrapper` element).
The more I have slides, the more the error is bigger.

You could see the thing in action here: https://codepen.io/gooogooo/pen/wvgKXbq

Could you check or help me? Thanks 🙏

p.s.: the UI is fluid so I haven't media queries and I haven't fixed size in px.

**Comment by nolimits4web** [comment]
Can not see such issue. I guess when you set viewport size to larger size, it is just a browser zooming bug. Seems like not related to Swiper
