### ISSUE TITLE
BigCommerce store - Product images on website not loading

### ISSUE THREAD

**Issue by jasonmitchell42** [nolimits4web/swiper#4388]
Our BigCommerce website uses Swiper for the product images and this has recently stopped working.  A suspected cause is something in the recent update pushed out to swiper.  An urgent fix is required please.

Website url: https://abiandjoseph.com.au/endurance-dual-pocket-mid-thigh-tight-black.html

![image](https://user-images.githubusercontent.com/26766269/112938843-c5bea300-916d-11eb-8ff1-0e8aa4743d3e.png)

**Comment by schappim** [comment]
this is not a Swiperjs issue. The issue is within line 79 of history.js . [Most likely the data-history attribute is not being populated](https://files.littlebird.com.au/Shared-Image-2021-03-30-17-03-22-kwNMm.png).

**Comment by nolimits4web** [comment]
Duplicate #4384
