### ISSUE TITLE
noSwiping class not working

### ISSUE THREAD

**Issue by cihadturhan** [nolimits4web/Swiper#439]
I want to create a slider with any touch/drag events disabled. I initialize it with the following snippet

```
var currSwiper = new Swiper(content[0], {
        mode: 'horizontal',
        speed: 500,
        slidesPerView: 1,
        calculateHeight: false,
        initialSlide: 0,
        noSwiping: true,
        noswipingClass: 'swiper-slide',
        centeredSlides: true
    });
```

So, I don't want slide to move with mouse so I make `noswipingClass` the class as `swiper-slide` but it still moves with mouse.

I'm not sure if it's a bugfeature or else.

**Comment by federinik** [comment]
noSwipingClass parameter still not working
