### ISSUE TITLE
Support for SvelteKit?

### ISSUE THREAD

**Issue by danawoodman** [nolimits4web/swiper#4404]
Cannot get this to work with SvelteKit using both the Svelte and Sapper examples (see below for errors)

- Swiper Version: 6.5.4
- Platform/Target and Browser Versions: macOS

## What You Did

Added to a SvelteKit project using both the Svelte and Sapper examples

## Expected Behavior

It to work 🤓

## Actual Behavior

```
1:50:36 PM [vite] Error when evaluating SSR module /node_modules/swiper/swiper.esm.js:
TypeError: Cannot redefine property: __esModule
    at Function.defineProperty (<anonymous>)
    at eval (/node_modules/swiper/swiper.esm.js:56:8)
    at instantiateModule (/Users/path/to/app/node_modules/vite/dist/node/chunks/dep-66eb515d.js:69030:166)
```

**Comment by ibn-akbar** [comment]
Having the same issue with Vite.

**Comment by nolimits4web** [comment]
This should work fine starting from 6.5.5, and follow this guide https://swiperjs.com/svelte#using-with-sapper-and-svelte-kit
