### ISSUE TITLE
Center mode does not work with auto slides

### ISSUE THREAD

**Issue by bigfanjs** [nolimits4web/swiper#4414]
- Swiper Version: 6.5.4
- Platform/Target and Browser Versions: macOS Catalina 10.15.7, CHROME version 89.

## What You Did

I tried to create a center mode slider where the active slide should appear wider than the other slides. but it turns out swiper.js can't maintain centered slides **while sliding** in auto slides.

View it here at codesandbox: https://l0cmj.csb.app/

## Expected Behavior

The expected behavior is that the active slide's centered red line should align with the the centered red line in the bottom:
<img width="503" alt="Screen Shot 2021-04-07 at 10 42 31 PM" src="https://user-images.githubusercontent.com/10690029/113938643-c94bcd00-97f2-11eb-8e94-6a356cd8d679.png">

## Actual Behavior

In the above codesandbox example the active slide's centered red line does not align with the centered red line in the bottom
<img width="515" alt="Screen Shot 2021-04-07 at 10 42 51 PM" src="https://user-images.githubusercontent.com/10690029/113938665-cf41ae00-97f2-11eb-97fa-dda664238f4a.png">

**Comment by nolimits4web** [comment]
It won't work because you are changing width of the slide on the go, it just can't work like that. Such behavior is unsupported, try using Coverflow effect where you can control slides transforms and scaling instead
