### ISSUE TITLE
Custom navigations not working

### ISSUE THREAD

**Issue by Senshi111** [nolimits4web/swiper#4430]
Custom navigation stop working in 
versions
 swiper:  "6.5.6"
angular/cli: "11.2.7"

[https://stackblitz.com/edit/swiper-angular-example-sqynzr?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/swiper-angular-example-sqynzr?file=src%2Fapp%2Fapp.component.html)

**Comment by vdumbrav** [comment]
I have the same problem

**Comment by mkurte** [comment]
Same for me.

**Comment by soares-lu** [comment]
Same issue here...

**Comment by nolimits4web** [comment]
@vltansky can you check?

**Comment by Maksiemens** [comment]
same issue
"swiper": "^6.5.8",
