### ISSUE TITLE
scrollbar and loop: true

### ISSUE THREAD

**Issue by htmlpluscss** [nolimits4web/swiper#4432]
wrong left position and width .swiper-scrollbar-drag

**Comment by htmlpluscss** [comment]
version Swiper 6.5.6

**Comment by caijf** [comment]
you can try this method

```typescript
setTimeout(() => {
  swiper.update();
  swiper.scrollbar.updateSize();
}, 0);
```

**Comment by blinkoliver** [comment]
it seems https://github.com/nolimits4web/swiper/issues/2315 and https://github.com/nolimits4web/swiper/issues/2191
and author said,  scrollbar and loop haven't support in swiper. But I'm have this problem too. I created sandbox and want to up this issue. 
https://codesandbox.io/s/swiper-loop-and-scrolbar-bug-o8byf
mayby somebody have solution
p.s. setTimeout don't work

**Comment by caijf** [comment]
Sorry, I didn't use a loop

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
