### ISSUE TITLE
Toggle between swiper settings on device width resize

### ISSUE THREAD

**Issue by dalalRohit** [nolimits4web/swiper#4434]
I have a Swiper React component. Based on the device width, I'd like to switch between SwiperOptions.

```
const match=useMediaQuery('max-width:600px');
const settings=match ? mobilleSettings : desktopSettings;

<Swiper 
     {...settings}
/>
```

Tried toggling it in `onResize`,  but did not work.

**Comment by cb2004** [comment]
Think a lot of requests are coming in for this just worded differently:

https://github.com/nolimits4web/swiper/issues/4311
https://github.com/nolimits4web/swiper/issues/4321

**Comment by nolimits4web** [comment]
It is not supported. What is supported is the breakpoints https://swiperjs.com/swiper-api where you can configure different params base on swiper/window size

**Comment by dalalRohit** [comment]
> Think a lot of requests are coming in for this just worded differently:
> 
> #4311
> #4321

Did you find a solution for this? To use different settings for different device width.

**Comment by cb2004** [comment]
As far as I am aware there is no official support for say an 'unswipe' on desktop and then allow swiper on tablet/mobile. You would have to out your own JS together to destroy and init.
