### ISSUE TITLE
ARIA accessibility error in Lighthouse

### ISSUE THREAD

**Issue by jaro-io** [nolimits4web/swiper#4435]
Hey there 🌳 🌻 
by default swiper gives the wrapper element a `role="list"` and all of its children slides a `role="group"`. Based on what Lighthouse says, this is not how its supposed to be done. A `role="list"` element should contain at least one children with `role="listitem"`. Please have a look at the [ARIA documentation](https://www.w3.org/TR/wai-aria/#usage_intro).

---

<img width="718" alt="Screenshot 2021-04-12 at 19 33 06" src="https://user-images.githubusercontent.com/20298313/114437435-d851c700-9bc6-11eb-8dce-b467903fa753.png">

---

Would be super lovely if this would be changed. Or am I missing something here?

Thank you @nolimits4web!
🙏🏻

**Comment by nolimits4web** [comment]
>  by default swiper gives the wrapper element a role="list"

not sure where did you find it, but by default Swiper doesn't set any roles to wrapper

**Comment by jaro-io** [comment]
hey @nolimits4web!
thanks for getting back to me. my bad, sorry for the confusion. the `role="list"` was coming from another source. but could it be that by default, swiper gives all slides a `role="group"` attribute? if so, it would be super cool to be able to change that!

because in my case, my wrapper already has the `role="list"` attribute. and my slides already have the `role="listitem"` attribute. but when initialising swiper, the slides roles get overwritten by `role="group"`. and this messes up lighthouse.

thank you for standing by!
🙏🏻

**Comment by geekysaurabh001** [comment]
Is there any way to allow the role="tabpanel" to the wrapper? ARIA is giving the warning as I have tabs present but since I cannot control the wrapper, I cannot give it the tabpanel role.
