### ISSUE TITLE
touch gestures on touchpad? - is this already a feature?

### ISSUE THREAD

**Issue by wallythewebdev** [nolimits4web/swiper#4442]
**Is your feature request related to a problem? Please describe.**

Yes (kinda) - Its become a common expectation in UX that two fingers placed on a touch page will allow for side scrolling - this was made popular in apple but has become expected by windows users as well. 

I was wondering if this was already a feature (as I have not seen a reference to it in the docs as of yet)? 

or if this would need to be manually detected using JavaScript? 

**Describe the solution you'd like**
Placing two fingers on the laptop / desktop touchpad, moving horizontally triggers next slide or prev slide depending on the direction (left or right)

![image](https://user-images.githubusercontent.com/28821463/114677106-e2c4ab80-9d01-11eb-8d21-5752a6773f80.png)

**Additional context**

I would have thought that this feature was native to Swiper, but upon checking the demos using Chrome (windows) none of the demos allow for this features. I have also had feedback from websites that I have used swiper on that have requested this feature to enhance the UX.

**Comment by nolimits4web** [comment]
There is no such feature in JS to detect trackpad and its events. If swiping on trackpad does the same as mouse scrolling (like on Macs) then just enable Mousewheel control https://swiperjs.com/swiper-api#mousewheel-control

**Comment by wallythewebdev** [comment]
I'm going to add to this encase anyone was to come to this later - 

@nolimits4web Amazing thank you for the input, I didn't know that macs used touch gestures to control the scroll wheel or that JS was not able to detect events like that by default, thank you for the info. 

Adding `mousewheel: true` to my swiper init enabled me to horizontally swipe like I had wanted, but I needed to further add `forceToAxis: true`, so that I could keep vertically swiping (code below).

```
 var mySwiper = new Swiper('.swiper-container', {
        mousewheel: {
          forceToAxis: true
        }
        });
```

Thanks again for the info :) 
Wally

**Comment by scerelli** [comment]
hi @wallythewebdev i got the same situation here, but enabling `mousewheel: { forceToAxis }` doesn't solve the problem. Via trackpad if you scroll up/down in an horizontal slider it would scroll the slider in anyway, instead it should just scroll left/right

**Comment by razvaniacob** [comment]
I tried this but is not working for me. Any idea why?

**Comment by SSylvain1989** [comment]
> hi @wallythewebdev i got the same situation here, but enabling `mousewheel: { forceToAxis }` doesn't solve the problem. Via trackpad if you scroll up/down in an horizontal slider it would scroll the slider in anyway, instead it should just scroll left/right

Hello , did you find any solution for this problem. ? Thanks

**Comment by Kcko** [comment]
> There is no such feature in JS to detect trackpad and its events. If swiping on trackpad does the same as mouse scrolling (like on Macs) then just enable Mousewheel control https://swiperjs.com/swiper-api#mousewheel-control

Im trying to solve same problem. Autor of this great plugin moved issue to discussion -> https://github.com/nolimits4web/swiper/discussions/6230

It just doesn't seem to work.  My client tells me that he saw it on some website ;-) (I dont believe that, because i dont know better slider than SWIPER).

**Comment by yenche123** [comment]
i found that we could enable `cssMode` to resolve this issue even if it didn't support to control the speed while scrolling.
https://swiperjs.com/swiper-api#param-cssMode

**Comment by cellar8** [comment]
Here is an example: https://www.apple.com/store - each one of the carousels on this page works with either arrows or two-finger swipe on the trackpad. And it also has easing implemented.  I am a UI designer, so my code skills are rudimentary, but if someone could deconstruct this and post your findings, that would help explain it to my developer.  It appears that it is all touch event code, but not sure if there is anything else.

**Comment by troy351** [comment]
According to apple store example provided by @cellar8 and some investigation, I found it was achieved by pure css.
using [CSS Scroll Snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_snap)

**Comment by niktor76** [comment]
> According to apple store example provided by [@cellar8](https://github.com/cellar8) and some investigation, I found it was achieved by pure css. using [CSS Scroll Snap](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_snap)

Thank you, that helped. Indeed it works with these settings. 
```
mousewheel="true"
force-to-axis="true"
css-mode="true"
```

But it sometimes a little buggy for me. When I scroll horizontally, then sometimes I'm unable to scroll vertically. I need then to move the cursor a little bit to be able to scroll vertically again.
