### ISSUE TITLE
Swiper changes layout when swiper component is destroyed

### ISSUE THREAD

**Issue by orjandh** [nolimits4web/swiper#4443]
- Swiper Version: 6.5.6
- Platform/Target and Browser Versions: Chrome, and others.

## What You Did

I am having some visual glitches in my layout when navigating away from a page containing a swiper component, with transitions. I have isolated the issue to the destroyment of the swiper component and created a minimal reproducible example.

To reproduce: Open the stackblitz example and click the destroy button. Notice how this changes the layout.

 https://stackblitz.com/edit/swiper-angular-example-ptbxfh?file=src%2Fapp%2Fapp.component.html

## Expected Behavior

I expect the layout to be untouched when the component is destroyed. But I do of course expect the swiping functionality to cease to function.

## Actual Behavior

When the swiper component is destroyed, it updates the layout with what seems to be the default configurations. This among other are a slidesPerView of 1.

**Comment by ThierryStaar** [comment]
Hello,
I've got the same problem and it occurs also on theses other plugins I've tried : owl-carousel, slick carousel
