### ISSUE TITLE
Mousewheel vertically not working correctly when scroll by touchpad

### ISSUE THREAD

**Issue by kidqn** [nolimits4web/swiper#4445]
- Swiper Version: Latest
- Platform/Target and Browser Versions: Chrome/Safari

## What You Did

scroll by touchpad with mousewheel feature

## Expected Behavior

Working well as mouse scrolling

Link test: https://swiperjs.com/demos/270-mousewheel-control.html

**Comment by nolimits4web** [comment]
not possible as it is impossible to detect when we touch/release touchpad
