### ISSUE TITLE
Not working with vue2

### ISSUE THREAD

**Issue by nguyenduclong-ict** [nolimits4web/swiper#4450]
I'm use with vue@2.6.12 and get error: 
"export 'computed' was not found in 'vue'
"export 'h' was not found in 'vue'
"export 'onBeforeUnmount' was not found in 'vue'

**Comment by nolimits4web** [comment]
https://swiperjs.com/vue

> Swiper Vue.js components are compatible only with new Vue.js version 3

**Comment by MertvyeDushi** [comment]
Add this to the documentation at https://swiperjs.com/vue because I've spent some time figuring out why it doesn't work.

**Comment by rayfoss** [comment]
Vue 3 backward compatibility with Vue 2 is now stable with configuration. This means your best bet is to update to Vue 3 with Vue 2 support, and then use Swiper 8+ on Vue 3 components.

**Comment by viT-1** [comment]
Vue 2.7 (setup function) [example](https://codepen.io/viT-1/pen/KKELxZj)
