### ISSUE TITLE
slidesPerView & spaceBetween next slide is visible, but shouldn't

### ISSUE THREAD

**Issue by maweo-mathis** [nolimits4web/swiper#4451]
Hello,

with this settings the 4th slide is visible, but shouldn't. The size of the three slides (slidesPerView) should be 100% of the container, shouldn't work this automatically?

How to solve this problem?

```
<Swiper
      className={sliderClasses}
      navigation={displayArrows}
      pagination={displayDots}
      spaceBetween={32}
      slidesPerView={3}
    >
```

![image](https://user-images.githubusercontent.com/78079355/115022269-768ea700-9ebd-11eb-8aba-580405741ee9.png)

**Comment by nolimits4web** [comment]
Please provide live example, otherwise I can just suggest that there is something in your CSS styles that can affect it
