### ISSUE TITLE
Pagination renderBullet putting last bullet in front of other bullets

### ISSUE THREAD

**Issue by Bimmr** [nolimits4web/swiper#4454]
- Swiper Version: Swiper 6.5.7
- Platform/Target and Browser Versions: Windows, Chrome

## What You Did

Using custom pagination renderBullet to use custom pagination so we can define buttons as data attributes in each slide item.

[JSFiddle with Example](https://jsfiddle.net/Bimmr/frjms8op/)

## Expected Behavior

Show custom rendered bullets in correct order

## Actual Behavior

Last custom rendered bullet is being shown first

**Comment by nolimits4web** [comment]
How about more minimal example without extra logic (that could be a root of the problem/issue)?

**Comment by Bimmr** [comment]
> How about more minimal example without extra logic (that could be a root of the problem/issue)?

I'll edit the JS Fiddle, and let you know when it's been minimized

**Comment by Bimmr** [comment]
So while updating the JSFiddle to a more minimal example I found the route of the cause. 

While having loop enabled it looks like the custom bullet render is grabbing the duplicated slide and trying to create a button with that.

**Comment by nolimits4web** [comment]
Everything is correct with pagination render. `index` number it returns in renderBullet is not an index of slide, it is an index of the bullet. And you try to use same index for slide which is wrong, as in `loop` mode there are duplicated slides added
