### ISSUE TITLE
`navigation` changes are not reflected in Swiper instance

### ISSUE THREAD

**Issue by viters** [nolimits4web/swiper#4458]
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: web

## What You Did

Navigation changes are not recognized by swiper component. If you set `navigation: false` and later change to specific HTML element refs, it will not work, even after calling `update` on swiper instance.

## Expected Behavior

When I change props, component does update accordingly.

## Actual Behavior

I change `navigation` and nothing happens, even with forced `update`.

**Comment by nolimits4web** [comment]
navigation nextEl, prevEl doesn't support refs, it accepts HTMLElements or string with CSS selector of elements.

**Comment by viters** [comment]
@nolimits4web 
I did not mean react `Ref` objects. Anyway, it does not matter what you pass to navigation, it is not the concern of this issue.

**Comment by nolimits4web** [comment]
Check this thread https://github.com/nolimits4web/swiper/issues/3855 maybe it has solution for you?

**Comment by viters** [comment]
Sadly, it doesn't. Firstly, it contains workarounds. Anway, I cannot call `sliderInstance?.navigation?.update()` when navigation is initially set to false.

**Comment by nolimits4web** [comment]
As you didn't provide live example, I have no idea what you are doing, but `navigation.update()` is for updating existing navigation, to create it `navigation.init()` should be called instead

**Comment by viters** [comment]
I thought the bug is clear, but as you ask, I've added example.

**Comment by nolimits4web** [comment]
👆fixed, will be available with next update on a days
