### ISSUE TITLE
Widths of swiper-wrapper and fixed-width swiper-slides are too wide

### ISSUE THREAD

**Issue by kayest** [nolimits4web/swiper#4461]
We have non-responsive slides and have them set to a width of 287 pixels, however when viewing the swiper-wrapper and swiper-slide divs in inspector, we're seeing that the widths are much wider than intended. We're trying to configure it so that when scrolling to the right, once you reach the last slide and it's in full view, we need the scrolling to stop. Here's an example of what we're experiencing. The example shows 10 slides, but we're only using four. 

https://codepen.io/Codewalker/pen/xxgyaVZ?editors=1010

**Comment by nolimits4web** [comment]
`slidesPerView` must be set to `auto` if you use custom sizes on slides
