### ISSUE TITLE
Images don't load with Lazy Load activated

### ISSUE THREAD

**Issue by DCStudioProjects** [nolimits4web/swiper#4463]
- Swiper Version: 6.5.7
- Platform/Target and Browser Versions: Windows, ANDROID, CHROME, ETC.

## What You Did

When I'm using lazy load and hooks such as useState and the first definition is not a final array with images, I'm getting this bug. But when I create just a const variable with array of images and don't redefine it everything works ok.

Bug: images are not loading until I touch or swipe slider.

 https://codesandbox.io/s/swiper-react-fork-forked-ubd1t

## Expected Behavior

Images must be loaded

## Actual Behavior

Images are not loading until I touch or swipe slider.

**Comment by kotoyama** [comment]
Why is it closed? This issue is also available in 6.7.0.

**Comment by DwieDima** [comment]
This seems also be an issue with angular, where you have to touch the swiper to see images
