### ISSUE TITLE
Swiper autoplay gets into an infinite loop on rotate

### ISSUE THREAD

**Issue by w3b-dev** [nolimits4web/swiper#4464]
##    Swiper Version: 6.5.7
### What You Did

I am using the autoplay feature of Swiper. But I only want it active on mobile. If I enable it by default and then disable it using the media queries options, the following behaviour occurs. If you rotate the device (in fact going from one to tha other media query) the slides start changing very fast constantly and the only solution is to refresh the tab. I should mention that this problem occurs on a double slider (one slider controlling another using: `instance.controller.control`. However, I tried removing all such functionality and the same behaviour occurs on a normal slider.

Bug: 
 Swiper autoplay gets into an infinite loop on rotate

Expected Behavior:
When you rotate a device from a media with autoplay turned on to one where autoplay is off the slides should stop/start playing.

Actual Behavior
When you rotate a device from a media with autoplay turned on to one where autoplay is off the slides start playing constantly and you have to refresh.

**Comment by nolimits4web** [comment]
Please provide a live example from the template you saw in issue template

**Comment by w3b-dev** [comment]
> 
> 
> Please provide a live example from the template you saw in issue template

Do you want a working demo on codepen or?

**Comment by nolimits4web** [comment]
Yes, working demo on codepen, codesandbox, etc.
