### ISSUE TITLE
initializing after dynamic content is loaded makes my slides disappear...  

### ISSUE THREAD

**Issue by nandoblanco** [nolimits4web/swiper#4470]
- Swiper Version: 6.5.8 
- Platform/Target and Browser Versions: latest Chrome

## What You Did

I'm using jquery to loop over data from a json file and then appending the items as slides to the page. 

You can see this in action at on the Events section right before the footer here: http://webqa.cookman.edu/_example/_pages/Home.html 

## Expected Behavior

The height shouldn't be so tall and the slides should show. 

## Actual Behavior

Once all items have been added to the page, I initialize Swiper and my items are turned into a Swiper slider but they're hidden. The height is long and the inline transform is totally off. 

Any help is appreciated, thanks in advance!

**Comment by nolimits4web** [comment]
You have some basic issues with CSS, don't use your custom classes like "row" for container and `<a>` for slides. Your custom styles override defaults
