### ISSUE TITLE
[Angular] Custom pagination not working

### ISSUE THREAD

**Issue by RombikUa** [nolimits4web/swiper#4480]
When I set HTML element for custom pagination I expect the swiper will use this element to build pagination. But it doesn't happen, a pagination 'el' option is ignored, and swiper use default pagination.

Here is an [example](https://stackblitz.com/edit/angular-ivy-e9mct1?file=src%2Fapp%2Fapp.component.html)

If I did something wrong, please let me know.

**Comment by vltansky** [comment]
duplicate of #4430
