### ISSUE TITLE
Slider Syncing not working properly

### ISSUE THREAD

**Issue by azaitar** [nolimits4web/swiper#4504]
## What I Did

I created three sliders below each other. On [this](https://redesign.3w-group.ch/) website when you scroll down you will se a gallery of which i am talking about.

There are 3 Sliders:
1.) The dots above the gallery
2.) The gallery itself.
3.) The text-captionoverlapping the gallery

Each slider should sync with the other sliders so i used this code: (Dont mind the bottom slider not being in sync when scrolling, i will deactivate the scrolling function on this one so it doesnt matter). This will only trigger if one of the slider above are being scrolled. 

```
    var galleryTop = new Swiper('.gallery-top', {
        spaceBetween: 0,
        slidesPerView: 3,
        // Responsive breakpoints
        breakpoints: {
            // when window width is >= 320px
            320: {
                slidesPerView: 1
            },
            // when window width is >= 480px
            480: {
                slidesPerView: 1
            },
            // when window width is >= 640px
            640: {
                slidesPerView: 2
            },
            // when window width is >= 768px
            992: {
                slidesPerView: 3
            }
        }
    });
    var galleryThumbs = new Swiper('.gallery-thumbs', {
        spaceBetween: 50,
        slidesPerView: 3,
        // Responsive breakpoints
        breakpoints: {
            // when window width is >= 320px
            320: {
                slidesPerView: 1,
                spaceBetween: 20
            },
            // when window width is >= 480px
            480: {
                slidesPerView: 1,
                spaceBetween: 30
            },
            // when window width is >= 640px
            640: {
                slidesPerView: 2,
                spaceBetween: 40
            },
            // when window width is >= 768px
            992: {
                slidesPerView: 3,
                spaceBetween: 50
            }
        }
    });
    var galleryBottom = new Swiper('.gallery-bottom', {
        spaceBetween: 50,
        slidesPerView: 3,
        // Responsive breakpoints
        breakpoints: {
            // when window width is >= 320px
            320: {
                slidesPerView: 1,
                spaceBetween: 20
            },
            // when window width is >= 480px
            480: {
                slidesPerView: 1,
                spaceBetween: 30
            },
            // when window width is >= 640px
            640: {
                slidesPerView: 2,
                spaceBetween: 40
            },
            // when window width is >= 768px
            992: {
                slidesPerView: 3,
                spaceBetween: 50
            }
        }
    });

    galleryThumbs.controller.control = [galleryBottom, galleryTop];
    galleryTop.controller.control = [galleryBottom, galleryThumbs];
```

Now the problem is, that when i scroll through the **dots** (first slider) everything looks synced. But if i scroll through the actual gallery, the **Dots** above and the **Text-Caption** below lose their alignement with the syncing and everything moves to the left until the last Element is reached.

## Expected Behavior

When using .controller.control on multiple sliders they should be in sync and not misalign.

## Actual Behavior
If you slide through the gallery the top and bottom slider lose their alignement.

**Comment by nolimits4web** [comment]
Set `controller.by = 'container'` parameter (https://swiperjs.com/swiper-api#controller) on every Swiper and it should work correctly. Also not sure why you need controller here at all, as basically what you have achievable by single Swiper
