### ISSUE TITLE
Swiper container pointerdown event is blocking mousedown event

### ISSUE THREAD

**Issue by facundocenizo** [nolimits4web/swiper#4505]
- Swiper Version: "^6.4.11".
- Platform/Target and Browser Versions: All platforms and browsers.

## What You Did

I'm attaching a mousedown event to the body from Google Tag Manager using plain JavaScript.

![image](https://user-images.githubusercontent.com/40206031/116697836-10645280-a99a-11eb-8839-04e6fec19674.png)

When I click on the others DOM elements, it returns me the event but when I click on a element contained in the swiper, it does'nt.

I tried to use the solution exposed in this [issue](https://github.com/nolimits4web/swiper/issues/4266) but it didn't work.

I removed the pointerdown event attached to the swiper-container and then the mousedown event started working but I can't do it from GTM, I need another solution..

## Expected Behavior

When I click on a element contained in the swiper it should return me the mousedown event.

## Actual Behavior

Currently, it no returns anything.

**Comment by nolimits4web** [comment]
Because it does `preventDefault` in `pointerdown` event listener.
1. Listen for `pointerdown` event instead (what is the issue with it? it supported by all browsers)
2. Or set `touchStartPreventDefault` Swiper parameter to `false`

**Comment by facundocenizo** [comment]
1. No, pointerdow isn't supported by all browsers, Safari and Safari OS don't support it ([doc](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event)). Mousedown is supported by all browsers ([doc](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event)).
2. How do I set touchStartPreventDefault to false, could you show me an example? Thanks.

**Comment by nolimits4web** [comment]
1. Safari does support pointer events. Swiper uses `touchstart` on iOS
2. It is covered in docs how to configure Swiper and set parameters/props https://swiperjs.com/swiper-api
