### ISSUE TITLE
SWIPER breaks on angular :LEAVE router animation

### ISSUE THREAD

**Issue by ThierryStaar** [nolimits4web/swiper#4506]
- Swiper Version: v6.5.8
- Platform/Target and Browser Versions: ANGULAR 11

## What You Did

Import and put a swiper in an angular component and initialised it.

## Expected Behavior

When a route change, a :LEAVE animation and an :ENTER animation is triggered through the router module and angular/animations 

The component containing the swiper  should execute the animation in both cases. 

## Actual Behavior

Case 1 : ENTER => no problem, the animation plays  while the swiper is initialised.
Case 2 : LEAVE => the swiper is resetted and destroyed as soon as the leaving animation starts, but the animation is well played by its container, the component.

**Comment by nolimits4web** [comment]
Duplicate #4443
