### ISSUE TITLE
Multiple controls - "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by wwwebman** [nolimits4web/swiper#4512]
- Swiper Version: 
```
"react": "17.0.2",
"react-dom": "17.0.2",
"swiper": "6.5.9"
```

- Platform/Target and Browser Versions: 
  - Chrome Version 90.0.4430.85 (Official Build) (64-bit)
  - Ubuntu 18.04 LTS

## What You Did

I want to make 3 sliders controlled by each other. So, the user scrolls one random slider two others scroll in an inverse direction, look below: 
1. Scrolling the 1st swiper to right the 2nd swiper scrolls to the left and 3rd to the right:
![Screenshot from 2021-05-02 15-32-44 (1)](https://user-images.githubusercontent.com/13425833/116815110-523cf680-ab5c-11eb-8bd5-3ae0bb929c34.jpg)
2. Scrolling the 2nd swiper to right both the 1st and 3rd swipers scroll the left:
![Screenshot from 2021-05-02 15-32-44](https://user-images.githubusercontent.com/13425833/116815111-523cf680-ab5c-11eb-83f0-5f13d75fc45d.jpg)
3. Scrolling 3rd swiper to left the 1st scrolls to left and 2nd to right:
![Screenshot from 2021-05-02 15-32-44 (2)](https://user-images.githubusercontent.com/13425833/116815109-510bc980-ab5c-11eb-9a58-b666f0ec3e75.jpg)

It works fine for two instances but doesn't work for three. Having three controllable swipers I can only reach the case when scrolling the first swiper two below get scrolled fine, but when I scroll the second and third the first doesn't move.

Maybe I do something wrong and there is a better way to have the effect described above, but the behavior with 3 controllable swipers seems to be buggy.

Here you can find examples: https://codesandbox.io/s/swiper-react-fork-forked-6wf2u
Note, **to get the error change 'g3_2'  to  'g3_1'  on line 72.**

## Expected Behavior

Prevent "RangeError: Maximum call stack size exceeded" in case of three and more controllable swipers.

It might be related to #1322

**Comment by nolimits4web** [comment]
Basically logic should be the following:
```
swiper1.controller.control = [swiper2];
swiper2.controller.control = [swiper1, swiper3];
swiper3.controller.control = [swiper2];
```
https://codesandbox.io/s/swiper-multiple-controls-rangeerror-maximum-call-stack-size-exceeded-forked-r8n70?file=/src/App.js
