### ISSUE TITLE
Orientation Change Portrait to Landscape Issues on iOS 14

### ISSUE THREAD

**Issue by markhedinger** [nolimits4web/swiper#4515]
ISSUE & REPRODUCTION

When viewing the core demo (https://swiperjs.com/demos/010-default/core.html) on an iphone, and changing orientation to landscape, the slide is offset towards the top. This cuts off the top area of a slide, and instead shows an empty grey area at the bottom. 

This is happening on an iphone 6s - browser: Safari; not sure about other phones. 

I have made my own swipe, with my own slides, according to documentation, but getting the exact same issue. 

EXPECTED BEHAVIOUR

Orientation change aligns & fits slide to screen correctly

Does anybody know how to remedy this issue and move the slides down? straight forwards css did not work for me.

**Comment by nolimits4web** [comment]
And if you disable Swiper, it will be the same, so closing as not related to Swiper, for me more like iOS issue/feature

**Comment by markhedinger** [comment]
Is it though? Please try it on your phone. Your script is changing the html, adding styles to it. I think this may be misaligning your content. We know it is possible to line up content with the bottom of the screen when not using swiper. The fact that it is no longer possible WHEN using swiper suggest that this clearly is a Swiper issue. Please reopen.
