### ISSUE TITLE
slidesPerColumn flex column does not work as expected

### ISSUE THREAD

**Issue by hannesbeere** [nolimits4web/swiper#4516]
- Swiper Version: 5.0.0 and above
- Platform/Target and Browser Versions: all platforms and browsers

## What You Did

When creating a multirow layout that is supposed to be filled by column first, swiperjs renders just one column for all elements.
This works in 4.5.1 (https://codepen.io/jhbx/pen/XWpvgWO) as expected by creating multiple columns and rows, but breaks starting version 5.0.0 and is still not working correctly currently (https://codepen.io/jhbx/pen/bGgXWZW).

## Expected Behavior

Create multiple rows and columns.

## Actual Behavior

Create one column with a row per item.

**Comment by nolimits4web** [comment]
Height must be set on swiper-slide and container https://codepen.io/nolimits4web/pen/PoWMJdN

**Comment by hannesbeere** [comment]
thank you, I feel stupid, sorry
