### ISSUE TITLE
Swiper lazy srcset jumping

### ISSUE THREAD

**Issue by niklasp** [nolimits4web/swiper#4522]
- Swiper Version: 6.5.9
- Platform/Target and Browser Versions: MacOs Firefox, Chrome, Safari Flickers

## What You Did

Create a swiper with lazy loading enabled and `data-src` and `data-srcset` set for images with `swiper-lazy` class. Also using 
```
        on: {
          lazyImageReady: (swiper) => {
            swiper.update();
          }
        }
```
as mentioned by @nolimits4web in several issues (e.g. https://github.com/nolimits4web/swiper/issues/3929#issuecomment-723951321). Swiper slide width and image width is set to `auto` in css.

## Demo
https://codesandbox.io/s/swiper-lazy-load-images-forked-gx254?file=/index.html

## Expected Behavior

No jumping, no flickering, image sizes beeing calculated correctly

## Actual Behavior

The swiper jumps as can be seen in this video:

**Comment by nolimits4web** [comment]
How can it "not jump" if this is how web works in general. image fist loaded, only then its size can be calculated. Don't want to it to jump set image sizes in HTML (in styles), or hide (visibility: hidden) swiper and show it when images loaded
