### ISSUE TITLE
`onSlideChangeTransitionEnd` only works from the second swipe onwards in some weird conditions

### ISSUE THREAD

**Issue by saveman71** [nolimits4web/swiper#4527]
- Swiper Version: 6.5.9
- Platform/Target and Browser Versions: Linux, Firefox and Chrome can reproduce

## What You Did

https://codesandbox.io/s/swiper-react-fork-forked-2uuzq?file=/src/App.js

With 3 conditions, detailed in the codesandbox, I find that `onSlideChangeTransitionEnd` is not called on the first swipe.

* Container needs to be hidden via CSS when there is no slides
* Must call `slideTo(0)`
* Added slides must be 2 level deep of `useEffect`

I know this is so weird. Took me a while to figure out the minimum reproducing example. But it's there.

![Screenshot from 2021-05-06 20-52-07](https://user-images.githubusercontent.com/1615426/117350764-3b283c80-aead-11eb-9707-97cd4da49cbd.png)

On the first page load, it may work; be sure to refresh the sandbox's iframe using the button.

## Expected Behavior

`onSlideChangeTransitionEnd` is called from the first swipe

## Actual Behavior

`onSlideChangeTransitionEnd` only works from the second swipe onwards

**Comment by saveman71** [comment]
It's not related to 301ffb096295017578e9309886686b42dd4b7785 or 

> react: fixed issue with Virtual, Controller and Thumbs when running React.StrictMode

as I can reproduce on 6.5.6

**Comment by saveman71** [comment]
Thank you for having a look at #4528. I tried adding `observer`, and `observeParents` for this issue and I still observe the described behavior.

**Comment by saveman71** [comment]
On such a small code example, it's more obvious that it's indeed nonsense to call `slideTo(0)` if there are no slides, but in a more complex environment, when the parameter is from a variable, etc. this can be much harder to debug and pinpoint the reason why Swiper is in a "bad state".

I expect such invalid calls to either throw (or at least show some sort of error in the console) (agree that is is breaking), or at least to be a noop and not trigger this kind of bug.

What do you think? I'm sorry the use case is very very specific and maybe not worth a bug fix.

**Comment by reothues** [comment]
Having the same issue here. 
Whenever the `initialSlide` is not 0, the `onSlideChangeTransitionEnd` does not fire at the first swipe.
Can hack it with:
 remove `initialSlide` but call `slideTo(x, 1)` at the start;
