### ISSUE TITLE
Broken swiper when initially hidden with CSS

### ISSUE THREAD

**Issue by saveman71** [nolimits4web/swiper#4528]
- Swiper Version: 6.5.9
- Platform/Target and Browser Versions: Linux, Firefox and Chrome can reproduce

## What You Did

Partially found the issue when debugging #4527 locally, initially updating Swiper worked but on codesandbox I found it again and managed to reduce it to a minimal working example:

https://codesandbox.io/s/swiper-react-fork-forked-simhl?file=/src/App.js

## Expected Behavior

Swiper should work, slide nicely

## Actual Behavior

Swiper only responds to mouse drags, doesn't end the transitions.

**Comment by nolimits4web** [comment]
Apparently it is because it was hidden. Use observer parameters to automatically update it
