### ISSUE TITLE
Swiper Vertical slider stuck after slider reach to the end

### ISSUE THREAD

**Issue by henryManektech** [nolimits4web/swiper#4538]
- Swiper Version: Latest version Swiper 6.5.9
- Platform/Target and Browser Versions: IOS, ANDROID

## What You Did

I used a vertical swiper slider with content beneath the slider. On desktop, it works as expected but on a mobile device, it's stuck after the slider reaches the last slide then after you can not move the slider or see the beneath content which is right after the slider. 

Here I create Domo in codepen pls check the demo with mouse drag like we move the slider on mobile with fingers. 
 https://codepen.io/henrymanektech/pen/wvJKroj 

## Expected Behavior

What I need is after the slider complete HTML or Site will continue to move or scroll as per the regular site. 

## Actual Behavior

As I mention in the mobile device slider stuck after the last slide comes to no matter if there is content after the slider section it will not move after the last slide.

**Comment by rubenmeines** [comment]
Hey man, try and search for "touchReleaseOnEdges" in the documentation here: https://swiperjs.com/swiper-api. I have had a similar problem on desktop with scrolling through a vertical slider.

You can make it a bit smoother so you dont scroll directly on the last slide's transition like this:

`productSlider.on('slideChange', function () {              
      setTimeout(function () {
        productSlider.params.mousewheel.releaseOnEdges = false;
      }, 500);
    });

    productSlider.on('reachEnd', function () {           
      setTimeout(function () {
          productSlider.params.mousewheel.releaseOnEdges = true;
      }, 1500);    
    });`
