### ISSUE TITLE
Allow React components to be passed to `appendSlide` and `addSlide`

### ISSUE THREAD

**Issue by ajaypillay** [nolimits4web/swiper#4563]
**Is your feature request related to a problem? Please describe.**
Currently, you can only pass raw HTML to `appendSlide` and `addSlide`.

**Describe the solution you'd like**
If we can import some custom component with some props, and have it such that we can do `appendSlide(<Component prop1={prop1} ... propX={propX} />)` that would be great.

Even better, if this could be done:
```
appendSlide(
  <SwiperSlide>
    {({ isActive }) => (
      <Component isActive={isActive} ... propX={propX} />
    )}
  </SwiperSlide>
)
```

**Describe alternatives you've considered**
There aren't any right now.

**Additional context**
This would be perfect because then we can programatically add slides after the initial render. And we don't have to rely on an array mapping to get a similar functionality.

EDIT: I have just discovered a hack to get this to work **FOR STATIC CONTENT**, by using `renderToStaticMarkup`, but that throws an error about `useLayoutEffect` being used on the server for some reason (even though it executes on the client). There are no event listeners attached and I still haven't figured out how to attach the event listeners to this. If event listeners can be attached successfully then I will post a quick demo of it in action for reference. Regardless, it would be good if this is supported natively.

**Comment by nolimits4web** [comment]
Nope, it is not needed in React. In React you need to manage slides in this case in React-way, e.g. having slides in array, adding slide is basically array's `.push` etc

**Comment by ajaypillay** [comment]
Hi I'd just like to clarify though, if this is managed with an array, there is no way to delete the slides correctly.

You can add via a push but if you delete an item at a certain index, it does not work correctly. I [outline this issue in this discussion](https://github.com/nolimits4web/swiper/discussions/4549#discussioncomment-733626). 

The state of the other components are reset when a an element at a certain index of the array is deleted.

How should this be done correctly?

**Comment by nolimits4web** [comment]
Hey @ajaypillay look at this demo https://codesandbox.io/s/swiper-react-dynamic-slides-forked-b11r7, no any issues

**Comment by ajaypillay** [comment]
Hi @nolimits4web thanks for the demo - but the issue is that the state of the other slides don't need to be saved. I show it [here in this demo](https://codesandbox.io/s/swiper-remove-slides-w4gy3?file=/src/App.js).

If you click add slide, then click randomize state on the new slide, and then delete the slide at index 0, all the other slides will get their states reset. This is the same method as outlined in the demo but these slides have to contain their own state.

How should this be fixed?

**Comment by nolimits4web** [comment]
That has nothing related to Swiper, this is how React works, if you won’t to avoid slide rerendering keep its unique key

**Comment by ajaypillay** [comment]
If that's the case then I can't delete an element in the array right? Because then everything after that element would have a different key. How would you advise that I go about deleting an element from the array without causing a re-render? Appreciate the help, thank you.
