### ISSUE TITLE
Select/Dropdown elements don't work when using virtual slides

### ISSUE THREAD

**Issue by Kraegon** [nolimits4web/swiper#4565]
- Swiper Version: 6.5.9
- Platform/Target and Browser Versions: iOS, Firefox, Chrome, issue occurs in StackBlitz too

## What You Did
I am attempting to use a (material) select HTML element in combination with virtual slides.

An example I quickly put together using the same packages my project has:
https://stackblitz.com/edit/swiper-angular-virtual-select-issue?file=src/app/app.component.html

## Expected Behavior

The Select HTML element should behave the same as when virtual is disabled.

## Actual Behavior

When scrolling to another slide and trying to select something in the dropdown causes the box to show very unexpected behaviour including lag to open, strange positioning, inability to assign the value.
When virtual is turned off, the element behaves as intended.

**Comment by Kraegon** [comment]
Still looking for a resolution for this issue, looking forward to an update

**Comment by vltansky** [comment]
@Kraegon 
looks like it works fine with the latest Swiper and Angular:
https://stackblitz.com/edit/swiper-angular-virtual-select-issue-vb9kjg?file=src%2Fapp%2Fapp.component.html

**Comment by Kraegon** [comment]
Verified it in my use case, the new version is indeed functional.
Thank you very much!
