### ISSUE TITLE
nav buttons not working when loop is false and data is added dynamically in swiper-wrapper

### ISSUE THREAD

**Issue by burhan333** [nolimits4web/swiper#4567]
nav buttons not working when loop is false and data is added dynamically in swiper-wrapper
how ever it is working fine if data is static

My Javascript Code

var swiper_count = 1;

    $("div[class^='swiper-main']").each(function() {

        new Swiper('.swiper-main-' + swiper_count, {

            // Optional parameters
            loop: true,
    
            // Navigation arrows
            navigation: {
            nextEl: '.swiper-btn-'+ swiper_count,
            prevEl: '.swiper-btn-'+ swiper_count,
            },
    
            breakpoints: {
                // when window width is >= 320px
                320: {
                slidesPerView: 1,
                slidesPerGroup: 1,
                spaceBetween: 20
                },
                // when window width is >= 480px
                480: {
                slidesPerView: 1,
                slidesPerGroup: 1,
                spaceBetween: 30
                },
                // when window width is >= 640px
                640: {
                slidesPerView: 2,
                slidesPerGroup: 2,
                spaceBetween: 40
                },
    
                900: {
                    slidesPerView: 3,
                    slidesPerGroup: 3,
                    spaceBetween: 40
                },
    
                1200: {
                    slidesPerView: 4,
                    slidesPerGroup: 4,
                    spaceBetween: 40,
                }
            },
        });
        swiper_count++;
    });

**Comment by nolimits4web** [comment]
call `swiper.update()` after you added data or enable `observer`
