### ISSUE TITLE
slidesOffsetAfter seem not doing anything

### ISSUE THREAD

**Issue by fadhilx** [nolimits4web/swiper#4575]
- Swiper Version: 6.5.7
- Platform/Target and Browser Versions: Windows, Firefox 88.0.1 (64-bit)

## What You Did

https://codesandbox.io/s/swiper-react-centered-auto-forked-z1jqu

## Expected Behavior

the last slide should stick to the right. or `slidesOffsetAfter` should do something(explain to me)

## Actual Behavior

`slidesOffsetAfter` not doing/positioning anything like `slidesOffsetBefore` did

**Comment by nolimits4web** [comment]
There is Discussions for questions https://github.com/nolimits4web/swiper/discussions

**Comment by fadhilx** [comment]
@nolimits4web i've made a discussion for this https://github.com/nolimits4web/swiper/discussions/4585

**Comment by fadhilx** [comment]
@nolimits4web what happen with "discussion"?
