### ISSUE TITLE
ERROR RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Panimaster** [nolimits4web/swiper#4576]
- Swiper Version: 6.6.1
- Platform/Target and Browser Versions: macOS, Angular 11 Server Side Rendering

## What You Did

app.component.html

```
    <swiper
        [navigation]="true"
    >
        <ng-template swiperSlide *ngFor="let card of cards">
          Slide 1
        </ng-template>
        <ng-template swiperSlide>
          Slide 2
        </ng-template>
    </swiper>
```

app.component.ts
```
import SwiperCore, { Navigation } from 'swiper/core';
SwiperCore.use([Navigation]);
```

With the command "npm run dev: ssr" to test server side rendering I get the error  "ERROR RangeError: Maximum call stack size exceeded
    at Array.filter (<anonymous>)" 

The error is only shown in the CLI and has no impact on using the slider (no crash)

I tested different swiper config settings and it seems that it is caused by [navigation]="true". As soon as I set this to false everything works without an error.

**Comment by Panimaster** [comment]
After further research I can confirm that this has something to do with the server side rendering and the client taking over. If hide the carousel first (server side rendered) and just show it when the client takes over (*ngIf) I dont get the error:

app.component.ts

```
public loaded: boolean = false;

constructor(@Inject(PLATFORM_ID) private platformId: number) {
        // nothing to do here
}
    
public ngOnInit(): void {
        if (isPlatformBrowser(this.platformId)) {
            this.loaded = true;
        }
    }
```
    
   app.component.html:
```
<swiper
        [navigation]="true"
        *ngIf="loaded"
    >
        <ng-template swiperSlide *ngFor="let card of cards">
          Slide 1
        </ng-template>
  <ng-template swiperSlide>
          Slide 2
        </ng-template>
</swiper>
```

**Comment by hgsantana** [comment]
Same here.

    **"@angular/core": "^11.0.9",**
    "@angular/platform-browser": "^11.0.9",
    "@angular/platform-browser-dynamic": "^11.0.9",
    "@angular/platform-server": "^11.0.9",
    "@angular/service-worker": "^11.0.9",
    **"swiper": "^6.6.2"**

BTW, I just can't implement swiper with **loop = true** and **observer = true** within a SSR + PWA angular app. Swiper doesn't init when it needs to and it duplicates first and last slides (looping effect?), breaking everything from working the right way.

**Comment by telubeer** [comment]
Similar issue during Stencil.js unit test
```
  console.error
    RangeError: Maximum call stack size exceeded
        at extend ./node_modules/swiper/cjs/utils/utils.js:110:16)
        at extend (.node_modules/swiper/cjs/utils/utils.js:131:13)
        ...
```

Issue rise on swiper version greater than v6.5.0. 
Seems some changes to the core at v6.5.1 may be related to the issue

**Comment by Panimaster** [comment]
After updating to swiper version 6.7.1 I am still getting the error. How about you @telubeer  or @hgsantana?

**Comment by telubeer** [comment]
@Panimaster yes, i can confirm that at 6.7.1 getting error.

**Comment by telubeer** [comment]
seems root of the issue is that `extend` method trying to extend objects contains recursive fields.

**Comment by telubeer** [comment]
I see that exist attempt to black list some field names and object types at extend method implementation, but i propose try to switch to white list approach instead. Swiper should know what options required to operate and should clone only them instead of trying to clone all fields of provided object. But i have not enough experience at Swiper sources so i can guessing only .

**Comment by nullbytesoftware** [comment]
Error still present in 6.7.5
