### ISSUE TITLE
Swiper with Virtual Slides Module Enabled is not in NgZone

### ISSUE THREAD

**Issue by seanwu1105** [nolimits4web/swiper#4588]
- Swiper Version: 6.6.1
- Platform/Target and Browser Versions: web

## What You Did

When I use `SwiperComponent` for Angular with virtual slides module enabled `[virtual]="true"`, all events trigered inside `<ng-template swiperSlide></ng-template>` does not run in NgZone. Since `SwiperModule` is officially and specifically supported for Angular framework, I think it should make sure all interfaces publicly exported should be handled in NgZone by default.

Here is [a minimal sample project](https://stackblitz.com/github/seanwu1105/swiper-ngzone-issue-minimal-sample) to demonstrate the problem. If the Stackblitz live demo does not work, see [this GitHub repo](https://github.com/seanwu1105/swiper-ngzone-issue-minimal-sample) directly.

## Expected Behavior

The demo contains the expected behavior. The navigation with `routerLink` inside `ng-template` should run in NgZone to refresh DOM accordingly.

![Peek 2021-05-20 15-09](https://user-images.githubusercontent.com/14951000/118935173-d1646400-b97d-11eb-8bcf-709bcc25c304.gif)

## Actual Behavior

The navigation with `routerLink` inside `ng-template` does not run in NgZone, which causes the DOM does not refresh correctly. You can see there are warnings regarding the navigation not running in NgZone.

![Peek 2021-05-20 15-12](https://user-images.githubusercontent.com/14951000/118935194-d5908180-b97d-11eb-87f5-3b90c1860041.gif)

**Comment by vltansky** [comment]
@seanwu1105 should be fixed in #4601. You can try it a demo on `master` with `npm run build` and then `ng serve`
