### ISSUE TITLE
swipe and keyboard navigation fires slideChange but it doesn't run in ngZone. causing page not to update

### ISSUE THREAD

**Issue by cragrock8990** [nolimits4web/swiper#4589]
I use slideChange output event to call api to fetch data and show details on the same page. when i use keyboard navigation by pressing right and left arrow keys the slider templates changes and reflects the current selection and fires the slideChange but it doenst trigger the api request and doesnt update the page. when i click anywhere on page api gets called and things start to load on the page.  what i found that if in the slideChange listener function i wrap my api call in ngZone it all seems to work fine. seems like the slideChange event for keyboard and swipe navigation is not called within ngZone. can this be fixed so that slideChange event is fired in zone so that angular can trigger its change detection correctly. following is the snippet of swiper and inputs i am using

```
<swiper
  id="angularswiper"
  slidesPerView="auto"
  centeredSlides="true"
  [spaceBetween]="16"
  (swiper)="onSwiper($event)"
  (slideChange)="onSlideChange()"
  [navigation]="false"
  [keyboard]="{ enabled: true, onlyInViewport: false }"
  [allowSlidePrev]="true"
  [allowSlideNext]="true"
  [allowTouchMove]="true"
>
```

**Comment by nolimits4web** [comment]
I guess root of the issue same as #4588 cc @vltansky

**Comment by cragrock8990** [comment]
i will follow #4588, great thanks :)
