### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/plain

### ISSUE THREAD

**Issue by xBugzilla** [nolimits4web/swiper#4600]
Loading css via cdn
`<link rel="stylesheet" type="text/css" href="https://unpkg.com/swiper/swiper-bundle.min.css" />`

shows warning: 
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://unpkg.com/swiper/swiper-bundle.min.css"

**Comment by nolimits4web** [comment]
Not related to Swiper
