### ISSUE TITLE
Infinite loop failing when an element contains "display: none"

### ISSUE THREAD

**Issue by Jay-Plumb** [nolimits4web/swiper#4608]
- Swiper Version: `Swiper 6.6.2`
- Platform/Target and Browser Versions:  `macOS - CHROME`

## What You Did
I have a sandbox that can be found [here](https://codesandbox.io/s/swiper-inifinite-loop-forked-u6f3g?file=/index.html) (please hit the refresh icon to load the state)

The main callout is that for "Slide 4" I am setting "display:none;":
```html
  <div class="swiper-slide" style="display: none;">Slide 4</div>
```

## Expected Behavior

Ability to infinitely loop when an element has the `display:none` supplied

## Actual Behavior

The loop logic breaks when clicking the right arrow and unable to go past page 5 in the [example](https://codesandbox.io/s/swiper-inifinite-loop-forked-u6f3g?file=/index.html) (please hit the refresh icon to load the state)

**Comment by nolimits4web** [comment]
Slides with "display: none" is not what is supported and probably not going too. Add/remove slides instead

**Comment by Jay-Plumb** [comment]
@nolimits4web thanks for the response. Adding/Removing slides is not a solution for my use-case and is actually performance intensive to update the DOM by adding/removing. 

At a minimum would it be possible to update the documents to call out that `display: none` is not supported so that other developers are aware of the library limitations?
