### ISSUE TITLE
unable use centeredSlides

### ISSUE THREAD

**Issue by ranxiaoli** [nolimits4web/swiper#4611]
const mySwiper = new Swiper(".swiper-container", {
			direction: "horizontal",
			loop: false,
			slidesPerView: "auto",
			centeredSlides: true,
			// centeredSlidesBounds: true,
			spaceBetween: 20,
			// observer: true,
			// observeParents: true
		});

**Comment by vltansky** [comment]
Provide a demo please
https://codesandbox.io/embed/swiper-vue-centered-4q6nr

**Comment by nolimits4web** [comment]
https://codesandbox.io/s/2srof
