### ISSUE TITLE
Cannot use custom component as SwiperSlide

### ISSUE THREAD

**Issue by michelebruno** [nolimits4web/swiper#4624]
## What You Did

It is not possible to use custom components as slides. Such an example will not work:

```
import React, { Children, useRef, useState } from "react";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/swiper.min.css";

import "./styles.css";

function Card({ children }) {
  return <SwiperSlide slot="slide">{children}</SwiperSlide>;
}

export default function App() {
  return (
    <>
      <Swiper className="mySwiper">
        <Card>Slide 1</Card>
        <Card>Slide 2</Card>
        <Card>Slide 3</Card>
        <Card>Slide 4</Card>
        <Card>Slide 5</Card>
        <Card>Slide 6</Card>
        <Card>Slide 7</Card>
        <Card>Slide 8</Card>
        <Card>Slide 9</Card>
      </Swiper>
    </>
  );
}
```

## Expected Behavior
It should work anyway.

## Actual Behavior

This happens because of `getChildren()` functions defined here https://github.com/nolimits4web/swiper/blob/master/src/react/get-children.js. It looks for the displayName to detect child as slide.

```
if (child.type &amp;&amp; child.type.displayName === 'SwiperSlide') {         
   slides.push(child);
}
```

Is it really necessary? For complex projects this may cause issues.

**Comment by nolimits4web** [comment]
Yes it is necessary due to complex rendering logic, you can try to wrap slides with fragment or use custom components inside slides

**Comment by JanderSilv** [comment]
Hi @nolimits4web , thanks for your hard work on this package!

Would it be possible to replace `child.type.displayName === 'SwiperSlide'` with `child.type === SwiperSlide`?

This way, we could pass any displayName to a custom SwiperSlide, and the parent would still recognize it as a child. I don't have sure about this, it's just an idea.
