### ISSUE TITLE
When using looping, slides are not rendered correctly on update.

### ISSUE THREAD

**Issue by santsys** [nolimits4web/swiper#4625]
- Swiper Version: 6.6.2
- Platform/Target and Browser Versions: ALL

## What You Did

```js
<Swiper
          observer={true}
          slidesPerView={5}
          spaceBetween={ContentPadding.Medium}
          autoplay={{ delay: 1500 }}
          centeredSlides={false}
          loop={true}
          onSwiper={setSwiper}
          breakpoints={{
            320: {
              slidesPerView: 2,
              centeredSlides: true,
              spaceBetween: ContentPadding.Small,
            },
            720: {
              slidesPerView: 4,
              centeredSlides: false,
              spaceBetween: ContentPadding.Medium,
            },
          }}
        >
          {props.images.map((image) => (
              <SliderSlide key={image.sys.id}>
                <StyledImg
                  image={image}
                  altText={image.fields.description}
                  lazyLoad={true}
                />
              </SliderSlide>
            ))}
        </Swiper>
```

## Expected Behavior

All slides should be replaced and the loop re-created when the slides are replaced.

## Actual Behavior

With loop mode set, when slides are replaced, the slide indexes are incorrect and all slides are not replaced. You should be able to see in the image below that the indexes (`data-swiper-slide-index`) are off, 0, 1, 1, 3 ... The duplicate index 1 is an old image that is not part of the new dataset (`props.images`). So it appears on update something is skipping/miscalculating the slides and not fully updating/replacing all of the slides in the loop.

![image](https://user-images.githubusercontent.com/1380843/120109522-a072f480-c11e-11eb-9c76-feb3fe81463d.png)

**Comment by nolimits4web** [comment]
Please add live demo example

**Comment by santsys** [comment]
It's strange is I'm unable to replicate this in other projects where the changes are coming from basic routing changes or pure changes to slide content. I'm starting to lean towards this being an issue with nextjs and how it handles routing.

A sample of how things are, and working, is here, https://codesandbox.io/s/mystifying-jepsen-d4823?file=/pages/%5Blang%5D/index.js (view /en or /fr).

In a more complex project, that I unfortunately can not share, the issue happens every time.

**Comment by santsys** [comment]
I think i was able to identify the issue, it appears to be a rendering "bug" in how we were handling object keys in react. Because the parent control that contained the swiper control shared the same key on a route change, react was attempting to do a much more limited re-render, In this case it caused artifacts to remaining in the swiper control. By localizing shared object keys (so they are unique across pages), the issue appears to be resolved.

**Comment by arthurwhite** [comment]
I don't think this issue is to be closed yet.

I actually have the same kind of bug when using the `loop: true` option in combination with `breakpoints: {...}`, with different `slidesPerView` for each breakpoint.

**The situation:**
Inside every `SwiperSlide`, I have an `img` child element.
**Problem:**
These images are oddly shuffled between `SwiperSlide` instances (but only images, not other text divs for example).

I suspect Swiper's way to copy slides doesn't play well with the React virtual DOM, even with keys correctly set.
For the moment, my only workaround is to make multiple Swiper instances (one for each breakpoint) and conditionally hide them with CSS…

**Comment by TheManFromEarth1** [comment]
I have the same bug - with loop: true & breakpoints and on Nextjs. 

swiper.slideNext(); -- everything renders fine
Custom go to slide x -- Also renders fine

swiper.slidePrev(); -- some slides render weird, as in they have missing images or missing data.
