### ISSUE TITLE
Autoplay never starts with disableOnInteraction and pauseOnMouseEnter set to true

### ISSUE THREAD

**Issue by mrleemon** [nolimits4web/swiper#4628]
- Swiper Version: 6.7.0
- Platform/Target and Browser Versions: Windows 10 and Firefox 88

## What You Did

In an app I'm developing, I'm adding a Swiper that is hidden initially and is displayed only if a user clicks on gallery thumbnail:

```
   var swiper = new Swiper( '.swiper-container', {
        loop: true,
        autoHeight: true,
        observer: true,
        autoplay: {
            delay: 3000,
            disableOnInteraction: true,
            pauseOnMouseEnter: true,
        },
        navigation: {
            nextEl: '.swiper-next',
            prevEl: '.swiper-prev',
        },
    });

    document.querySelectorAll( '.gallery-thumbnails a[data-slide]' ).forEach( item => {
        item.addEventListener( 'click', function( e ) {
            e.preventDefault();
            document.querySelector( '.swiper-container' ).style.display = "block";
            var slideno = parseInt( this.getAttribute( 'data-slide' ) );
            swiper.slideTo( slideno + 1, 0, false );
        });
    });

```

As you can see I'm enabling autoplay with both `disableOnInteraction` and `pauseOnMouseEnter` settings to `true`.

## Expected Behavior

The slider should start autoplaying the moment after it's displayed after a user clicks on the gallery thumbnail.

## Actual Behavior

The slider NEVER starts autoplaying the moment after it's displayed after a user clicks on the gallery thumbnail.
If I set `disableOnInteraction` to `false`, autoplay works as expected.

**Comment by nolimits4web** [comment]
Check what docs says https://swiperjs.com/swiper-api#autoplay-parameters 

> When enabled autoplay will be paused on mouse enter over Swiper container. If disableOnInteraction is also enabled, it will stop autoplay instead of pause
