### ISSUE TITLE
Use Vue -> Build, Swiper ->  navigation and pagination disappear，But it's functioning perfectly，There is no error

### ISSUE THREAD

**Issue by edifangyi** [nolimits4web/swiper#4634]
Use Vue -> Build,
Swiper ->  navigation and pagination disappear，But it's functioning perfectly，There is no error.
Demo is same effect.

 
{
  "name": "sss",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "swiper": "^6.7.0",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass-loader": "^8.0.2"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by nolimits4web** [comment]
Closing as not related to Swiper. I suggest there is something with build setup or swiper styles imports. Try to import them from main scss
