### ISSUE TITLE
Inconsistent click events and propagation in chromium browsers

### ISSUE THREAD

**Issue by samuelgoldenbaum** [nolimits4web/swiper#4637]
- Swiper Version: 6.7.0 or latest as per demo page
- Platform/Target and Browser Versions: browser, react

## What You Did

Getting click handling inconsistencies in Chromium browsers--Chrome, Brave etc. I can confirm this viewing the [demos](https://swiperjs.com/demos#thumbs-gallery) in Chrome and Brave. Sometimes, the click triggers the slideto, sometimes it triggers pagination, sometimes it does nothing for several clicks--completely inconsistent. It's fine on Safari, but the latest Chrome (Version 91.0.4472.77) is a problem.

 

## Expected Behavior

Clicking a slide should firing the events consistently.

## Actual Behavior

Sometimes, the click triggers the slideto, sometimes it triggers pagination, sometimes it does nothing for several clicks. It's fine on Safari, but the latest Chrome (Version 91.0.4472.77) is a problem. This happens in my repo as well as all the [demos](https://swiperjs.com/demos#thumbs-gallery).

**Comment by joebentaylor1995** [comment]
I have a similar issue, where using the fade effect, the first time I click a custom next button, it triggers once and never again

**Comment by monaalexandra** [comment]
I can confirm the issues described by joebentaylor1995 – even in the current version. It's really annoying we can't use the fade effect in our project for now :(

**Comment by moshfrid** [comment]
+1

**Comment by TheRealMadMesi** [comment]
+1

**Comment by kosmeln** [comment]
+1 . In addition, when we add a fade effect - we loose the ability to zoom with doubleclick.

**Comment by HIT2022** [comment]
+1. Extremely easily reproduced

**Comment by afbruno** [comment]
+1

**Comment by morisakikeita** [comment]
+1

**Comment by DenyskoD** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
