### ISSUE TITLE
Make type flexible for plugins

### ISSUE THREAD

**Issue by linonetwo** [nolimits4web/swiper#4638]
- Swiper Version: 6.3.5   , "@types/swiper": "^5.4.1",
- Platform/Target and Browser Versions: MacOS Firefox VSCode  "typescript": "3.7.3",

## What You Did

I want to add a new plugin "stackFlow", but when I try dev locally, I get error:

```js
  Types of property 'effect' are incompatible.
    Type '"stackFlow"' is not assignable to type '"slide" | "fade" | "cube" | "coverflow" | "flip" | undefined'.
```

If these types are better, it may encourage 3rd plugin to emerge, and gets publish to npm.

## Expected Behavior

This should allow extended with other plugin types, `| string` maybe.

## Actual Behavior

The type is too fixed, that makes plugin dev very inconvenient.

**Comment by nolimits4web** [comment]
You can `import { SwiperOptions } from 'swiper'` and extend parameters with what is required. Plugin API allows to override any parameters, so it doesn't make much sense to make all other types to all parameters

**Comment by linonetwo** [comment]
How about `Property 'swiperSlideOffset' does not exist on type 'Element'.ts(2339)`

When plugin try to access this?

```
const slideOffset = $slideEl[0].swiperSlideOffset;

And this
/// Property 'slides' does not exist on type '{ setTranslate(this: Swiper & IStackFlow & IDangerousSwiperInternalProps): void; setTransition(duration: number): void; }'.ts(2339)
$slideEl[0].style.zIndex = -Math.abs(Math.round(offsetMultiplier)) + 1;
```

I add some internal types myself

```ts
interface IDangerousSwiperInternalProps {
  slidesSizesGrid: number[];
}
```

for

```ts
setTranslate(this: Swiper & IStackFlow & IDangerousSwiperInternalProps) {
    const { width: swiperWidth, slides, slidesSizesGrid, isBeginning } = this;
```

But this seems very easy to break.

**Comment by linonetwo** [comment]
Well, but this won't be a problem after I contribute code back to this repo.
