### ISSUE TITLE
Swiper js carousel not working with background image set to background-attachment: fixed

### ISSUE THREAD

**Issue by meesfrenkelfrank** [nolimits4web/swiper#4639]
- Swiper Version: 6.6.2
- Platform/Target and Browser Versions:  CHROME.

## What You Did

EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

I try to create a carousel with `fade` effect and background images and set the background to `background-attachment: fixed;`.

I need to have a `<div>` element with a background image inside the `<SwiperSlide>` (because there comes a parallax effect). 

I need the background to be set to: `background-attachment: fixed;`. If I remove `background-attachment: fixed;` it's working fine.

`background-attachment: fixed;` is working fine on the first slide. As soon as you go to second slide it's not detecting the correct position of the image?

See below what I have so far:

https://codesandbox.io/s/swiper-react-background-image-qdwg5

How do I get this to work?

**Comment by nolimits4web** [comment]
This is how bg attachment works in general. There is no actual scrolling in Swiper, it uses CSS transforms, so it won't work.
