### ISSUE TITLE
Allow bulletActiveClass etc to be multiple classnames

### ISSUE THREAD

**Issue by Youhan** [nolimits4web/swiper#4642]
**Is your feature request related to a problem? Please describe.**
For people who use utility CSS like TailwindCSS, it is frustrating to have to work with only one classnames.

**Describe the solution you'd like**
instead of `bulletActiveClass: "one-class"`
allow for : `bulletActiveClass: "bg-gray-800 w-8 h-1 inline-flex rounded-full transition duration-300 ease-in-out"`

**Describe alternatives you've considered**
An alternative solution for me atm is to go back to regular css, one class 😐

**Additional context**
None

**Comment by nolimits4web** [comment]
It is supported

**Comment by lramos33** [comment]
its not working on version 11.0.5

![image](https://github.com/nolimits4web/swiper/assets/87446769/73df93ec-cace-49d7-aa93-81f7e2adabbf)
