### ISSUE TITLE
swiper lazy doesn't show loaded image in swiper/vue

### ISSUE THREAD

**Issue by SandyYsc** [nolimits4web/swiper#4643]
- Swiper Version: 6.6.1
- Platform/Target and Browser Versions: CHROME

## What You Did

import { Swiper } from 'swiper/vue';
import swiperCore, { Navigation, Pagination, Autoplay, Thumbs, Lazy, EffectFade } from 'swiper';

swiperCore.use([Navigation, Pagination, Autoplay, Thumbs, Lazy, EffectFade]);

```
<template>
  <swiper class="mySwiper" lazy="true">
    <swiper-slide>
      <img
        class="swiper-lazy"
        data-src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png"
      />
      <div class="swiper-lazy-preloader"></div>
    </swiper-slide>
 </swiper>
</template>
```

## Expected Behavior

swiper lazy should show lazy loaded image

## Actual Behavior

swiper lazy doesn't show lazy loaded image

**Comment by nolimits4web** [comment]
As you can see it works in this example https://codesandbox.io/s/8yipl?file=/src/App.vue
