### ISSUE TITLE
Change effect based on breakpoint

### ISSUE THREAD

**Issue by meesfrenkelfrank** [nolimits4web/swiper#4647]
- Swiper Version: 6.6.2
- CHROME

## What You Did

I tried the following but it's not working:

```
<Swiper
    effect="fade"
    breakpoints={{
    768: {
      effect: 'slide',
    },
  }}
>
```

In the [docs](https://swiperjs.com/swiper-api#parameters) I read the following:

> Allows to set different parameter for different responsive breakpoints (screen sizes). Not all parameters can be changed in breakpoints, only those which are not required different layout and logic, like slidesPerView, slidesPerGroup, spaceBetween, slidesPerColumn. Such parameters like loop and effect won't work

Is it somehow possible to get this to work?

## Expected Behavior

On desktop I want the `fade` effect and on mobile the `slide` effect.

**Comment by nolimits4web** [comment]
No it is not possible as docs states
