### ISSUE TITLE
How implement stop and start autoplay on hover with Typescript and React

### ISSUE THREAD

**Issue by meesfrenkelfrank** [nolimits4web/swiper#4652]
- Swiper Version: 6.6.2
- Platform/Target and Browser Versions: CHROME, ETC.

## What You Did

I am using React and Typescript.

Following [this post](https://stackoverflow.com/questions/65448980/swiper-js-in-raect-how-to-stop-autoplay-onmouseenter-and-start-it-onmouseleave), I am trying to `stop()` and `start()` autoplay on hover. I need this approach because I have to create some states when hovering the Swiper container. 

**1)** I get a typescript error the `ref` property on my `<Swiper ref={swiperRef}>` component:

> Property 'ref' does not exist on type 'IntrinsicAttributes & Swiper &
> { children?

**2)** how do I get acces to swiper, so I can use `swiper.autoplay.stop();` inside my `handleMouseEnter` function? So I can use like:

```
    const handleMouseEnter = () => {
      swiper.autoplay.stop();
     };
```

or like:

```
    const handleMouseEnter = () => {
     swiperRef.current.swiper.autoplay.stop();
    };
```

This is [the sandbox](https://codesandbox.io/s/swiper-hover-typescript-d1lng) what I have so far.

How do I get this to work using Typescript?

**Comment by nolimits4web** [comment]
There is auyoplay.pauseOnMouseEnter parameter

**Comment by meesfrenkelfrank** [comment]
@nolimits4web thanks, I know that. But I need to 'pause' my progress bullets animation on hover. So it's pausing the autoplay but also the animation. See my question [here](https://stackoverflow.com/questions/67848401/how-pause-swiper-pagination-bullets-progress-bar-on-hover-inside-swiper-react-ca). Or ia there a more simpel solutution?

**Comment by milenig** [comment]
> There is auyoplay.pauseOnMouseEnter parameter

Yes but there are no many options how to setup autoplay and pause. I want to pause on mouse enter, and stop autoplay on interaction (but stop only on interaction not on mouse enter). So I need to implement my own logic, but same issue as @meesfrenkelfrank mentioned. 

- It's not about autoplay, it's about `ref` property

**Comment by nolimits4web** [comment]
To get swiper instance you need to use `onSwiper` callback prop https://swiperjs.com/react#swiper-props

**Comment by milenig** [comment]
> To get swiper instance you need to use `onSwiper` callback prop https://swiperjs.com/react#swiper-props

Is there any way how to separate when autoplay was **stopped** by interaction or **paused** by mouse event? I want to continue autoplay after mouse leave component, but only if was stopped by mouse hover, and not to continue/start over again after interaction with sliders.

**Comment by sjonchhe** [comment]
have you found any solution for this??
