### ISSUE TITLE
Could not find a declaration file for module 'swiper/vue'. 

### ISSUE THREAD

**Issue by ltinerary** [nolimits4web/swiper#4656]
- Swiper Version: 6.7.0
- Platform/Target and Browser Versions: Windows.

## What You Did

I use `npm i swiper` to install the swiper in my vue project.
and when I import the Swiper.
I found  this tips : **Could not find a declaration file for module 'swiper/vue**'.
![image](https://user-images.githubusercontent.com/79144923/121127791-e46fa300-c85c-11eb-9e6a-0d29d507f2f7.png)

**Comment by nolimits4web** [comment]
Duplicate #3916

**Comment by aladinn-io** [comment]
Hi i have the same issue can u tell me how you solve it
