### ISSUE TITLE
Swiper in Material Tab not refreshing after slides update 

### ISSUE THREAD

**Issue by Mac-prof** [nolimits4web/swiper#4657]
I have a simple component presenting a Swiper in the Material Tab (Angular). All works fine until the images array gets updated in Angular. Once it is done and I switch to the Swiper's Material Tab I get never loading blank slide. Only moving right / left the sliders initiates a slider working properly. 

Below is an extract from my TS and HTML files. Importantly - and this is probably the core of a problem - I am not able to add [observer] = "true" attribute to the Swiper component as the following error is shown after component execution:

`**_error NG8002: Can't bind to 'observer' since it isn't a known property of 'swiper'._**`

#TYPESCRIPT COMPONENT FILE:

```
import { Component, ViewEncapsulation, OnInit, AfterViewInit, Input, OnChanges } from '@angular/core';
import { SwiperOptions } from 'swiper';
import Swiper from "swiper";
import 'swiper/swiper-bundle.css';
import { SwiperComponent } from "swiper/angular";
import SwiperCore, {
  Navigation,
  Pagination,
  Mousewheel,
  Keyboard,
  Lazy,
} from "swiper/core";
// install Swiper modules
SwiperCore.use([Lazy, Navigation, Pagination, Mousewheel, Keyboard]);
```

#COMPONENT's HTML FILE
```
<swiper [observeParents]="true" [preloadImages]="false" [lazy]="true" [preloadImages]="false" [navigation]="true"
  [pagination]="{ clickable: true }" [scrollbar]="{ draggable: true }" [mousewheel]="true" [keyboard]="true"
  (swiper)="onSwiper($event)" (slideChange)="onSlideChange()" class="mySwiper">

  <ng-container *ngFor="let slide of slidesArray">
 <ng-template swiperSlide>
        <img attr.data-src={{slide.image}} class="swiper-lazy" />
    </ng-template>
  </ng-container>
</swiper>

```
## Expected Behavior

after Swiper slides are updated outside of a Material tab the Swiper resides and clicking back on Swiper's tab the slides are refreshed.

## Actual Behavior

after Swiper slides are updated outside of a Material tab the Swiper resides and clicking back on Swiper's tab the first slide is not shown and only resize of the window or clicking next slide brings back proper working of a Swiper.

**Comment by vltansky** [comment]
Can you make codeSandBox / stacblitz?

**Comment by Mac-prof** [comment]
Do not really know how to do it. If from the code elements quoted there is no idea where the problem might be then probably issue goes beyond the examplary code. :/

**Comment by nolimits4web** [comment]
Would be good to see the example, you can use one of the templates available when you create an issue. Also `observer` in Angular version is always enabled by default
