### ISSUE TITLE
breakpoints with different slidesPerColumn issue

### ISSUE THREAD

**Issue by Lovor01** [nolimits4web/swiper#4658]
![Untitled](https://user-images.githubusercontent.com/33687174/121207505-9fa63500-c879-11eb-9673-9c91cf6e567a.png)
I have following initalize settings (I use JSON to load inital settings):
```
{
	"pagination": {
		"el": ".swiper-pagination",
		"type": "bullets"
	},
	"autoplay": {
		"delay": 9000
	},
	"breakpoints": {
		"0": {
			"slidesPerColumn": 3,
			"slidesPerView": 2,
			"spaceBetween": 14
		},
		"768": {
			"slidesPerColumn": 2,
			"slidesPerView": 3,
			"spaceBetween": 20
		}
	}
}
```
If page is resized (i.e. mobile orientation changed), and not reloaded, some of margins which were previously set for onte type of layout are not cleared and result in incorrectly shown layout.

More specifically: if screen is above 768px, 4th slide will get margin of 20px on top. However, when changing screen to less than 768px (without reloading), 4th slide will still have margin 20px, although this margin should be cleared, because now it is on top. Other margins are correctly set, it is only a matter of fixing clearing of certain margins when resizing.

- Swiper Version: 6.7.0
- Platform/Target and Browser Versions: Windows, Firefox for developers 90.0, Chrome for developers 93.0

(update) Demo:
https://56n2k.csb.app/

**Comment by nolimits4web** [comment]
Would be good to see the live demo using the template from issue template at first

**Comment by Lovor01** [comment]
Web page is not public yet, and it is password protected, can you give me some contact, to send you details in PM?

**Comment by nolimits4web** [comment]
Please use CodeSandbox or similar to illustrate the issue

**Comment by Lovor01** [comment]
I solved a problem by "hack", inserting clearing margin function on breakpoint event:
```
const fixElements = document.querySelectorAll('.slider-with-title .swiper-slide');
function fixFunction() {
	fixElements.forEach(function(el) {
		el.style.marginTop = '';
	})
}

setttings = {
...
on: {
    breakpoint: fixFunction
}
...
}
```

However, it would be nice to see it properly fixed :)

**Comment by Lovor01** [comment]
Hello, is the demo I provided in comments above adequate? If it is, then you could close "missing demo" issue

**Comment by aashestakov** [comment]
> > Hello, is the demo I provided in comments above adequate? If it is, then you could close "missing demo" issue
> 
> yes, thanks, should be fixed now

Seems bug still exists. We can see problem at resize time: https://uyrrf.csb.app/
Swiper 6.8.0
`<script>
      var swiper = new Swiper(".mySwiper", {
        slidesPerView: 2,
        slidesPerColumn: 1,
        spaceBetween: 30,
        breakpoints: {
          768: {
            spaceBetween: 30,
            slidesPerView: 3,
            slidesPerColumn: 2
          }
        },
        pagination: {
          el: ".swiper-pagination",
          clickable: true
        }
      });
    </script>`
