### ISSUE TITLE
Sides getting cut off from swiper

### ISSUE THREAD

**Issue by glassesUSA** [nolimits4web/swiper#4662]
- Swiper Version: 6.7.0
- Platform/Target and Browser Versions: MacOS

## What You Did

EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

https://stackblitz.com/edit/swiper-demo-1-default-fzdhzn?file=index.html

## Expected Behavior

Slides are shown fully with no side clipping

## Actual Behavior

Side clipping occurs

**Comment by nolimits4web** [comment]
This is CSS issues with you custom styles. Remove custom margin and borders from slides
