### ISSUE TITLE
Angular 12  'swiper' is not a known element

### ISSUE THREAD

**Issue by sathwik77** [nolimits4web/swiper#4669]
- Swiper Version: 6.7.0
- Platform/Target and Browser Versions:  Windows, Edge(Chromium)
- Angular version: 12

## What I Did

Followed exactly the same as mentioned in [swiper angular documentation](https://swiperjs.com/angular)

- Yes, I imported SwiperModule in app.module.ts
- Yes, I imported SwiperComponent from 'swiper/angular' in my component xyz.component.ts
 
component.ts

```
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { SwiperComponent } from "swiper/angular";
import SwiperCore, { Pagination } from "swiper/core";
SwiperCore.use([Pagination]);

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class HomeComponent implements OnInit {
  constructor() { }
  ngOnInit(): void {
  }
}
```

component.html

```
<div class="px-4 py-4">
  <swiper [slidesPerView]="3"
  [spaceBetween]="30"
  [freeMode]="true"
  [pagination]="{
    clickable: true
  }"
  class="mySwiper">
    <ng-template swiperSlide>Slide 1</ng-template>
    <ng-template swiperSlide>Slide 2</ng-template>
    <ng-template swiperSlide>Slide 3</ng-template>
    <ng-template swiperSlide>Slide 4</ng-template>
    <ng-template swiperSlide>Slide 5</ng-template>
    <ng-template swiperSlide>Slide 6</ng-template>
    <ng-template swiperSlide>Slide 7</ng-template>
    <ng-template swiperSlide>Slide 8</ng-template>
    <ng-template swiperSlide>Slide 9</ng-template>
  </swiper>
</div>
```

## Expected Behavior

Swiper to work normally

## Actual Behavior

 'swiper' is not a known element

**Comment by sathwik77** [comment]
Never mind, I am lazy loading my modules, after importing in specified modules I got it working

**Comment by technbuzz** [comment]
Does it means we can't used the swiper as a lazy loaded module. For Instance if I am using swiper for intro page only. For every second visit of my app don't need to load the intro module at all. In that case what should I do?

**Comment by vltansky** [comment]
Just import into the module that you need, not in app.module.ts. It should work just fine.

**Comment by technbuzz** [comment]
Well I followed following steps

1. Created an Intro Modules
2. Imported SwiperModule in Intro Module
3. Used Swiper component inside **Intro Component** _which is a part of _ Intro Module
4. Lazy Loaded the Intro Module in **App Routing **

Guess what **Doesn't Work**

I directly imported **Intro Module** to **App Module** and guess what **Swiper Works**.

I tried to reproduce it via _StackBlitz_ and _Code Sandbox_ but apparently they don't play well with Swiper

**Comment by vltansky** [comment]
Use Stackblitz web container or Codesandbox containers.
You can use swiper demos as a starting point
https://swiperjs.com/demos

**Comment by Cyrus-0101** [comment]
> Never mind, I am lazy loading my modules, after importing in specified modules I got it working

How did you achieve this?

**Comment by sohan-cerotechnology** [comment]
Yes, How did you achieve this?
