### ISSUE TITLE
React: Virtual Slides + Parallax Animation does not always work correctly

### ISSUE THREAD

**Issue by kije** [nolimits4web/swiper#4673]
- Swiper Version: 6.7.0
- Platform/Target and Browser Versions:  macOS, Chrome 91.0.4472.101

## What You Did

I created a Swiper slider with virtual slides & Parallax transition enabled.
Now when using `swiper.slideNext()` or `swiper.slidePrev()` to go to the next/previous slide, the parallax animation sometimes (in fact, most of the time) does not work correctly. Instead of animating both the "outgoing" and the "incoming" slide, it only animates the outgoing slide.

The issue occurs only the first time the *rendered* slide is animated to. E.g. if I transition to the 2nd slide the first time, the animation is broken. If I then transition back to the 1st slide (which was previously rendered), the animation works correctly.

https://codesandbox.io/s/floral-darkness-nqdqr?file=/src/App.js

## Expected Behavior

I would expect that the parallax animation works regardless of which slide the transition is animating to, and regardless of whether virtual slides are used or not.

## Actual Behavior

To better illustrate, I made a screen recording of the code example (see above) showing the issue. 

https://user-images.githubusercontent.com/3481639/121820381-bb9f4180-cc92-11eb-90f5-02c2f6947368.mp4

Some slides are animated correctly (both slides have a parallax animation), but on other slides, only one of the slides is animated. It seems like the issue manly occurs when a slide is first added to the dom and has not yet been animated to/from. If the slide has already been once animated to/from (and in the meantime was not removed from the DOM again due to the "virtual slides" features), the animation is performed correctly.

**Comment by mmd550** [comment]
I still have this issue with cube effect and virtual slides :(
