### ISSUE TITLE
Cannot use string array for wrapperClass since 6.5.9

### ISSUE THREAD

**Issue by mxlle** [nolimits4web/swiper#4680]
- Swiper Version: 6.5.9, probably related to [commit](https://github.com/nolimits4web/swiper/commit/66c5a55b76a5d7e58908bf3fad8866e16361244b)
- Platform/Target and Browser Versions: e.g. macOs Chrome

## What You Did

Setting the default wrapperClass + a custom wrapper class by using an array
`<swiper [wrapperClass]="['swiper-wrapper', 'custom-swiper-wrapper']">`

[Working StackBlitz with version 6.5.8](https://stackblitz.com/edit/angular-swiper-wrapperclass?file=src%2Fapp%2Fapp.component.html)
[Broken StackBlitz with version 6.5.9](https://stackblitz.com/edit/angular-swiper-wrapperclass-issue?file=src/app/app.component.ts)

## Expected Behavior

We want to set an additional wrapper class to apply some custom styling, but also have the default styling of the .swiper-wrapper class. 

This worked by using a string array, but is now broken since version 6.5.9

I realize that this was an undocumented feature, but as it used to work, it would be really great to keep it 😇 

## Actual Behavior

Component broken, several exceptions in console, because classes are not applied correctly.

**Comment by nolimits4web** [comment]
Don't expect something undocumented to work, and not sure why it was working:) You can just pass `['a', 'b'].join(' ')` to wrapperClass to make a string from classes

**Comment by mxlle** [comment]
> Don't expect something undocumented to work, and not sure why it was working:) You can just pass `['a', 'b'].join(' ')` to wrapperClass to make a string from classes

I tried that too, but it doesn't work... To get the wrapperEl you use ```$el.children(`.${swiper.params.wrapperClass}`)``` in your code which will fail. I think this must have changed too, as it was working before. 

Could we maybe tag this as feature request instead then?

**Comment by mxlle** [comment]
Actually for now we can just use `<swiper class="custom-swiper-wrapper">`
My colleague just pointed me to this, that the mentioned commit above actually changed the behaviour to attach the class of the root level to the wrapper div. 

Though this too isn't documented 😕

**Comment by nolimits4web** [comment]
Yeah, that is a bug for sure :) and already removed here https://github.com/nolimits4web/swiper/commit/12851953491155f5f96930355c91110c9a4cf753

**Comment by nolimits4web** [comment]
Add support for this to the core
