### ISSUE TITLE
Swiper not initializing the size correctly resulting in stretched images and slides

### ISSUE THREAD

**Issue by HamedBahram** [nolimits4web/swiper#4685]
Swiper version: 6.5.2
Released on: March 30, 2021
Platform: Windows Google Chrome Browser

## What You Did
Firstly, thanks for this amazing library. I think we have some issue with slides not initializing correctly. I have two kinds of Swiper containers on one page, one is an image carousel and the other one a date picker carousel. I have used the "swiper-container-date" class modifier to differentiate the settings when initializing in JS. I am using ejs templating engine to loop over images to create "swiper-slide" divs.

#### Image Carousel
```html
  <div class="swiper-container rounded-2">
      <div class="swiper-wrapper">
        <% for( let i = 1; i <= 40; i++ ) { %>
          <div class="swiper-slide">
            <img src="https://res.cloudinary.com/nestzoom/image/upload/w_800,h_600,c_fill,g_auto,f_auto/d_misc:no-img_ktlqre.png/repliers/IMG-<%= listing.mls %>_<%= i %>.jpg"
                 class="rounded-2" alt="">
          </div>
        <% } %>
      </div>
      <!-- Pagination -->
      <div class="swiper-pagination show-page"></div>
      <!-- Navigation -->
      <div class="swiper-button-prev show-page"></div>
      <div class="swiper-button-next show-page"></div>
  </div>
```
#### Date picker Carousel
```html
    <div class="swiper-container-date">
        <div class="swiper-wrapper">
            <% for( let i = 0; i <= 14; i++ ) { %>
                <div class="swiper-slide">
                    <div class="flex-grow-1">
                        <input type="radio" class="btn-check" name="showing_date" value="<%= add(new Date(), {days: i}) %>" id="showing-date-radio-<%= i %>" autocomplete="off" <%= i === 0 ? 'checked' : '' %> >
                        <label class="btn btn-outline-secondary w-100" for="showing-date-radio-<%= i %>">
                            <div class="fs-8 text-uppercase"><%= format(add(new Date(), {days: i}), 'EEEE') %></div>
                            <div class="display-4"><%= format(add(new Date(), {days: i}), 'd') %></div>
                            <div class="fs-8 text-uppercase"><%= format(add(new Date(), {days: i}), 'LLL') %></div>
                        </label>
                    </div>
                </div>
            <% } %>
        </div>
        <div class="swiper-button-prev text-info"></div>
        <div class="swiper-button-next text-info"></div>
    </div>
```

### Here is the css I added:
```css
.swiper-container {
    width: 100%;
    height: 400px;
}

@media (min-width: 768px) {
    .swiper-container {
        height: 522px;
    }
}

.swiper-container-date {
    width: 100%;
    height: 100%;
    margin-left: auto;
    margin-right: auto;
    position: relative;
    overflow: hidden;
    list-style: none;
    padding: 0;
    /* Fix of Webkit flickering */
    z-index: 1;
}
```

### Here is JS:
```javascript
const swiper = new Swiper('.swiper-container', {
    speed: 400,
    pagination: {
        el: '.swiper-pagination',
        type: 'fraction',
    },
    navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
    },
})

const date_swiper = new Swiper('.swiper-container-date', {
    speed: 400,
    slidesPerView: 3,
    slidesPerGroup: 3,
    spaceBetween: 5,
    navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
    },
})
```

## Expected Behavior vs Actual Behavior
Here is a screenshot of how the image carousel should look
<img src='https://res.cloudinary.com/dtijo8xha/image/upload/v1623865247/samples/swiper/2021-06-15_3_wbocd0.png' />

Here is how it sometimes renders in Chrome:
<img src='https://res.cloudinary.com/dtijo8xha/image/upload/v1623865245/samples/swiper/2021-06-15_1__LI_xnmoi2.jpg' />

Here is a screenshot of how the date picker carousel should be:
<img src='https://res.cloudinary.com/dtijo8xha/image/upload/v1623865247/samples/swiper/2021-06-15_2_iluynl.png' />

Here is how it sometimes renders in Chrome:
<img src='https://res.cloudinary.com/dtijo8xha/image/upload/v1623865246/samples/swiper/2021-06-15_LI_m2tzkw.jpg' />

**Comment by chihuy105** [comment]
same issue here, any suggestion?

**Comment by HamedBahram** [comment]
> same issue here, any suggestion?

unfortunately not any solid suggestions! I updated swiper to the last version, I'm seeing the problem less but if it continues I'll have to replace swiper with a custom carousel I created.

**Comment by haresh14** [comment]
same issue here, any suggestion?

**Comment by venanciorodrigo** [comment]
Same here 👀
