### ISSUE TITLE
Cannot click anchor tags from within slides oin mobile

### ISSUE THREAD

**Issue by joebentaylor1995** [nolimits4web/swiper#4688]
Hey there.

So i have a weird bug, on desktop everything is fine, but in mobile iOS safari.

Whenever I click a anchor link, I have to click it twice for it to work.

Ive tried the suggested settings:
```
preventClicks: false,
preventClicksPropagation: false,
```

but this only fixes desktop

**Comment by nolimits4web** [comment]
Would be good to see isolated live demo (with the template from issue template)

**Comment by joebentaylor1995** [comment]
This actually was fixed, and maybe a common html bug.

I had an anchor inside a h1, the anchor was only unclickable when inside of it.

🤦🏼‍♂️
