### ISSUE TITLE
The type for bullets and slides of the .d.ts file is not reported correctly in the documentation

### ISSUE THREAD

**Issue by DAnn2012** [nolimits4web/swiper#4694]
The type for `bullets` ( **Dom7Array[]** ) and `slides` ( **any[]** ) currently present in the .d.ts files is not reported correctly in the documentation and is therefore omitted 

https://github.com/nolimits4web/swiper/blob/4eac3e8bf1c7619d28da92e2e8ff0bf268886392/src/types/components/pagination.d.ts#L11-L16

![bullets](https://user-images.githubusercontent.com/1197819/122782321-e9970e00-d2b0-11eb-9989-002df751204b.png)

https://github.com/nolimits4web/swiper/blob/4eac3e8bf1c7619d28da92e2e8ff0bf268886392/src/types/components/virtual.d.ts#L17-L20

![virual-slides](https://user-images.githubusercontent.com/1197819/122784273-9f169100-d2b2-11eb-9323-306cdd34bf7d.png)

https://github.com/nolimits4web/swiper/blob/4eac3e8bf1c7619d28da92e2e8ff0bf268886392/src/types/components/virtual.d.ts#L68-L70

https://github.com/nolimits4web/swiper/blob/4eac3e8bf1c7619d28da92e2e8ff0bf268886392/src/types/components/virtual.d.ts#L74-L79

This is currently reported in the documentation of version 6.6.2:

![doc662](https://user-images.githubusercontent.com/1197819/122783799-2f080b00-d2b2-11eb-9538-8e37bc1ce9f5.png)

and so it was instead reported in the documentation of version 6.3.5:

![doc635](https://user-images.githubusercontent.com/1197819/122783933-4e069d00-d2b2-11eb-8387-9b44376ec1da.png)

Thanks.

**Comment by DAnn2012** [comment]
@nolimits4web After the last changes, the problem seems solved only for the `slides` parameter of **Virtual Slides**.

![virtual-slides-params](https://user-images.githubusercontent.com/1197819/124879768-dd5bc200-dfcd-11eb-8ded-e9716c4c2c7d.png)

But there are still problems with **Virtual Slides**' `slides` method

![virtual-slides-methods](https://user-images.githubusercontent.com/1197819/124880066-2c095c00-dfce-11eb-9df3-8c337c381717.png)

and **Pagination's** `bullets` property.

![bullets2](https://user-images.githubusercontent.com/1197819/124880122-3af00e80-dfce-11eb-8cbd-39b2e8f1812e.png)

Thanks.

**Comment by DAnn2012** [comment]
@nolimits4web Even after the release of version 6.8.0 this situation persists. So you think it's okay as it is?

Thanks.

**Comment by fenyiwudian** [comment]
report another types here.

![image](https://user-images.githubusercontent.com/12799388/129691050-d0af666c-82b3-4a8f-8a4f-760b6147aa51.png)

seems `controller.control` should be `Swiper | Swiper[]` rather than `Swiper` only.

**Comment by DAnn2012** [comment]
Hello @fenyiwudian 

In fact, a few months ago (https://github.com/nolimits4web/swiper/commit/efd95a8b7a86184c93f5a27595d0594b356d0db3) it was only correct in `ControllerOptions`:

https://github.com/nolimits4web/swiper/blob/3faa10dc6987d5309ccda2fa2d90186576d30695/src/types/components/controller.d.ts#L13-L18

and not in `ControllerMethods`:

https://github.com/nolimits4web/swiper/blob/3faa10dc6987d5309ccda2fa2d90186576d30695/src/types/components/controller.d.ts#L3-L9

**Comment by nolimits4web** [comment]
fixed in #4846
