### ISSUE TITLE
Compiler shows 3 warnings for version 6.7.0

### ISSUE THREAD

**Issue by Daijobou** [nolimits4web/swiper#4695]
When I try to create my own minimized version, I get 3 warnings. I used version 6.2.0 before, there was no warning there.

Here https://closure-compiler.appspot.com/ I paste code from https://unpkg.com/swiper/swiper-bundle.js (currently version 6.7.0)

Result are 3 warnings:

```
JSC_USELESS_CODE: Suspicious code. The result of the 'getelem' operator is not being used. at line 3064 character 4
    snapGrid[normalizedSnapGrid.indexOf(normalizedTranslate)];

JSC_USELESS_CODE: Suspicious code. This code lacks side-effects. Is there a bug? at line 9756 character 17
          } else if (newThumbsIndex > currentThumbsIndex && thumbsSwiper.para...

JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 9756 character 102
...umbsIndex > currentThumbsIndex && thumbsSwiper.params.slidesPerGroup === 1) ;
```

First warning is a line that do nothing. Second and third is a "else if" without {} content.

**Comment by nolimits4web** [comment]
unused code is removed, the rest you can just ignore
