### ISSUE TITLE
Trouble with swiper in bootstrap modal window

### ISSUE THREAD

**Issue by IgorSushko1** [nolimits4web/swiper#4696]
- Swiper Version: ^5.4.5
- Platform/Target and Browser Versions: Windows, CHROME 91.0.4472.114.

## What You Did

i puted some swiper into bootstarp modal window, and where i called it, the swiper showed infinite download lazy preloader and slider work with errors on swipe

## Expected Behavior

there must be normal beheavior 

## Answer

so, if you stuck on the same things, just added an watcher with setTimeout and only then bootstrap modal will be opened - fire the swiper script

like this:

```
b-modal#complect-filtered-items(v-model="isItemModalVisible")
  Items(v-if='showItemsModal' )

watch: {   
 isItemModalVisible(val) {
      if (val) {
        setTimeout(() => {
          console.log('is visible')
          this.showItemsModal = true
        }, 500)
      } else {
        this.showItemsModal = false
      }
  }
}

```

**Comment by nolimits4web** [comment]
Have you seen this message when you created issue?

> To expedite issue processing please search open and closed issues before submitting a new one.
Existing issues often contain information about workarounds, resolution, or progress updates.

🔍🔍🔍
https://github.com/nolimits4web/swiper/search?o=desc&p=1&q=bootstrap&s=created&type=issues
