### ISSUE TITLE
Angular 12 - swiper 6.7.0 - iPhone - Chrome - clunky swipe

### ISSUE THREAD

**Issue by heitorb** [nolimits4web/swiper#4698]
I just upgraded from Angular 11 to 12. On an iPhone 12 Pro Max, iOS 14.6, using chrome (latest version), the swiping is clunky. Not smooth like it is with Angular 11. I was using swiper 6.3.5 when I saw this issue. Updated to the latest, which is 6.7.0 right now and I am still seeing it. On iPhone Safari it works smoothly as before.

**Comment by nolimits4web** [comment]
Duplicate https://github.com/nolimits4web/swiper/issues/4493
