### ISSUE TITLE
Swipe-to-top + Deeplink

### ISSUE THREAD

**Issue by charkens** [nolimits4web/Swiper#470]
Hello,

I have questions about the swiper and the HashNavigation-Plugin. I wasn’t able to solve it by myself …

No 1:
I’d try to use the Swiper for pages with different heights. All of them are longer than the viewport. When I’m scrolling down at Slide1 and swipe to Slide2, I’m entering Slide2 on the same height, e.g. at the center of the content. Is it possible to enter the following slide at the top, so I don’t have to scroll up first to get the Introduction of that page?

No 2:
I installed the Hash-Plugin to get a Deeplink for each slide. That is working, but if I enter the URL+Hashtag at the Browser, e.g. www.website.com/swiper.html#slide4, I’m always enter the website at the beginning of the slide-carousel (slide1) and not at slide4. How can I fix this problem?

Many many thanks for your help!
cheers

**Comment by marcoslon** [comment]
Hi! I have the same problem presented by charkens iin the first point, but I can not fix it:
> I’d try to use the Swiper for pages with different heights. All of them are longer than the viewport. When I’m scrolling down at Slide1 and swipe to Slide2, I’m entering Slide2 on the same height, e.g. at the center of the content. Is it possible to enter the following slide at the top, so I don’t have to scroll up first to get the Introduction of that page?

This is the place I 'm working: [link](http://agustinpuente.com/works-all.html)

I hope you can help me.
Thanks.
