### ISSUE TITLE
controller settings on Touch Screen Monitor causing problems with swipe behaviour

### ISSUE THREAD

**Issue by Fanni-Portier** [nolimits4web/swiper#4703]
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: Touch Screen Monitor, BrightSign HD Player

I have two swiper slider.
Swiper 1 is controlling swiper 2.

const swiper2 = new Swiper('.swiper-thumbnails', {
	direction: 'vertical',
	loop: false,
	spaceBetween: 0,
	slidesPerView: 1,
	allowTouchMove: false,
	clickable: false,
});
	
const swiper1 = new Swiper('.swiper-container', {
  direction: 'vertical',
  loop: false,
  spaceBetween: 0,
  slidesPerView: 'auto',
  clickable: true,
  slideToClickedSlide: true,
  centeredSlides: true,
  freeMode: true,
  freeModeSticky: true,
  controller: {
	control: swiper2,
  },
});

As soon as I add the control setting the smooth swipe behaviour is getting lost.
I tried to fix it by using different freeModeMomentum settings but there is no difference.

I must admit - it works in ordinary web browsers.
But I need it to work on a touch monitor with BrightSign player.

Does someone have a solution or a hint for solving my problem?

**Comment by rohit-virkud** [comment]
hey fannie, found any solution i'm facing same issues on mobile devices
