### ISSUE TITLE
In loop mode, some slides are not visible until are active (clear if container is in overflow:visible)

### ISSUE THREAD

**Issue by SilviaElisaAimone** [nolimits4web/swiper#4704]
- Swiper Version: 6.7.1
- Platform/Target and Browser Versions: Windows 10 / Chrome 91

## What You Did

https://codesandbox.io/s/swiper-infinite-loop-forked-gy53l

I took the "Loop" demo on the official website. I changed the css of .swiper-container to be in "overflow:visible" and "width: 50%".

## Expected Behavior

If I click the prev button I should see slide n. 8 standing before n. 9.

## Actual Behavior

When I click the prev button, I see n. 9 (correct) but before it there is a "hole", n. 8 is not visible. It becomes visible only when active, that is to say when I click the prev button again.

**Comment by nolimits4web** [comment]
This is how `loop` works, it dynamically rearrange slides when they are outside of the swiper-container. You can increase `loopedSlides` parameter (for example to `3`) so it will duplicate more slides

**Comment by ttnbtfy** [comment]
Hi @SilviaElisaAimone, I'm having the same problem as yours, have you solved this problem yet? If so, can you share it with me?
Thanks.
