### ISSUE TITLE
Issues on the slider with thumbs on the modal

### ISSUE THREAD

**Issue by yngwieduane** [nolimits4web/swiper#4706]
Here is the button of the modal to open a gallery sliders. Inside the modal I have 3 tabs of interior, exterior and facilities.

![image](https://user-images.githubusercontent.com/18515128/123535870-f21b9880-d737-11eb-9e80-bfcdc13a6de9.png)

Here is the screenshot of the modal being executed. the slider looks working fine. but when you navigate the thumbnails and the sliders. the main slider images are not working and the thumbnails are acting weird and sometimes they will not point you to the right slides. 
![image](https://user-images.githubusercontent.com/18515128/123535880-19726580-d738-11eb-8b1d-561aed49d976.png)

How I do this:
1. I created a dynamic of generating the tabs for each button (because sometimes a project doesnt have interior images).
2. Created also a dynamic of generating a tab content per category (interior, exterior and facilities.)

Here is the actual link if you need a clarification.

abu-dhabi.properties

I am hoping some can help me. Thank you !

**Comment by nolimits4web** [comment]
You need to init/update swiper on modal open. Or enable `observer` and `observeParents` parameters

**Comment by yngwieduane** [comment]
I have it already and still not working well
