### ISSUE TITLE
Looks like a bug on phones on scroll

### ISSUE THREAD

**Issue by DMBPWR** [nolimits4web/swiper#4722]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://do-or-drink.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=120384487505

### Bug description

I have a section with reviews on homepage where I'm using swiper. It have to show 1 full slide with a bit of prev and next slides. So, swiper jumps to rigth a bit when window height changes on mobile. For example, we have top and bottom bars in safari browser and when it's hidding -> swiper jumps. Looks like swiper gives to slides incorrect `transform: translate3d`

To check this bug, you can go to [this site](https://do-or-drink.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=120384487505), open web tools with height of 375px and then change height of window.

### Swiper version

5.4.5 (version upgrading not fixing)

### Platform/Target and Browser Versions

macOS safari, chrome, ios safari, chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
On the link you posted I see you use different slider, not the Swiper
