### ISSUE TITLE
Change slide width for active

### ISSUE THREAD

**Issue by Draghmar** [nolimits4web/swiper#4723]
Hi
Because I don't know if it's possible to achieve I didn't put as a new feature and I don't consider this to be a bug so...a blank issue it is. ;)
I wonder if it's possible to make slider that would work as `slidesPerView: 'auto'`, which prevents Swiper to calculate same size for each slide, and at the same time take into consideration that active slide has different width then non-active one.
To visualize what I mean take a look at this image:
![swiper](https://user-images.githubusercontent.com/275348/123973507-1ab3c480-d9bc-11eb-8c5d-ffa2e9caf70b.png)
Green is active, yellow are within visible area and grey are outside of visible area.

I tried to make this by setting `slidesPerView` to specific number and then trying to change width on events but it didn't move proper amount of pixels. So instead of spending next few hours trying to guess parameters that could work I choose to ask you. :P

**Comment by nolimits4web** [comment]
Blank issues are not allowed. Move it to discussion then
