### ISSUE TITLE
loop does not work nicely with slidesPerView

### ISSUE THREAD

**Issue by helhum** [nolimits4web/swiper#4730]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://helhum.io/swiper-loop-slides.html

### Bug description

When the slider is configured to loop, but the number of slides is less than the number of slides per view, clones are created leading to a overall strange behaviour of the slider, most notably, cloned slides become visible within the container

### Expected Behavior

slider functionality is disabled when number of slides <= slidesPerview and no slide duplicates should be shown

### Actual Behavior

slider functionality is enabled and slide duplicates are shown

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> slider functionality is disabled when number of slides <= slidesPerview and no slide duplicates should be shown

This depends on requirements and not always required. Disable loop or Swiper when number of slides is insufficient
on your side

**Comment by helhum** [comment]
It is a special requirement to not show duplicate slides?

Besides that, neither disabling loop, nor disabling Swiper is straightforward, when considering a responsive scenario, where different slides per view are configured for different view port sizes. 

I implemented this now on my side, but the amount of code and the kind of code that is required for that tells me, that it would be nice to get more support for such scenarios in Swiper itself. 


Or am I missing an easy way to disable looping on a slider instance?

This is what I currently have to do:

1. Listen to breakpoint changes
2. Check current breakpoint against current slides and current loop config, if changes are required then
3. destroy swiper instance
4. re-initialise swiper with new loop config (enabled or disabled)

This works, but is fragile, especially because destroying the Swiper instance inside an event listener leads to JS errors during further event propagation. 

Am I missing something obvious how this can be implemented in a less verbose and less error prone way?
