### ISSUE TITLE
Zoomed images are blurry on mobile due to translate3d

### ISSUE THREAD

**Issue by acromatica** [nolimits4web/swiper#4731]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-zoom-forked-qce1m?file=/index.html

### Bug description

When image is zoomed it gets `transform: translate3d(0px, 0px, 0px) scale(X)` style. Due to `translate3d(0px, 0px, 0px)` part the image is blurry, if translate3d is replaced with `translate(0px, 0px)` the issue is fixed.

`transform: translate3d(0px, 0px, 0px) scale(3)`:
![IMG_5496](https://user-images.githubusercontent.com/13260691/124199216-5b99ff00-daca-11eb-9714-e7d60895291e.PNG)

`transform: translate(0px, 0px) scale(3)`:
![IMG_5497](https://user-images.githubusercontent.com/13260691/124199272-6e143880-daca-11eb-9018-06474d349cc0.PNG)

### Expected Behavior

Zoomed image should look sharp on mobile.

### Actual Behavior

Zoomed image looks blurry on mobile.

### Swiper version

6.7.5

### Platform/Target and Browser Versions

iOS 14.6 Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper will stick with `translated3d` for better performance. The fact image is blurry is more of a browser bug, rather than Swiper's
