### ISSUE TITLE
issue in conjunction with autoplay & fade effect 

### ISSUE THREAD

**Issue by jnz31** [nolimits4web/swiper#4733]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-vue-effect-fade-forked-lcdzm

### Bug description

in conjunction with autoplay the fade effect runs fine in development/serve. but when i build the project, the effect is not appiled. it shows the first slide, then switches to the second slide with no transition and then the autoplay stops. manual transitions are still working fine, they have the proper effect, but autoplay is not working anymore. no errors in console. tested in mozilla and safari.

### Swiper version

6.7.5

### Platform/Target and Browser Versions

macOS High Sierra 10.13.6, Firefox: 89.0.2, Safari: 13.1.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> but when i build the project, the effect is not appiled

I suggest issue with your bundler, seems like fade effects didn't get to the bundle in your case. Check also this https://github.com/nolimits4web/swiper/issues/3777

**Comment by jnz31** [comment]
changing 
`import 'swiper/components/effect-fade/effect-fade.scss'`
to
`require('swiper/components/effect-fade/effect-fade.scss')`
solved the issue
