### ISSUE TITLE
`.swiper-notification` never updated with `button` navigations

### ISSUE THREAD

**Issue by chalkygames123** [nolimits4web/swiper#4734]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-notification-issue-s6v6y

### Bug description

When we use `button` as a navigation element instead of `div` so that we can press it with the space key, the content of `.swiper-notification` is never updated.

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Any platforms with a keyboard

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is kinda by design, when using buttons, next/prev slide message will be set on BUTTON's `aria-label` attribute
