### ISSUE TITLE
Can't access actual slide index when slides are hidden

### ISSUE THREAD

**Issue by michelebruno** [nolimits4web/swiper#4737]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-react-default-forked-ktjgf?file=/src/App.js

### Bug description

Hello everyone,

I have a slider which hides slides on breakpoints with bootstrap d-lg-none class, applied to some of the SwiperSlide components.

My component renders slides from an array and I need to know exactly which slide is active. The onSlideChange event returns only the visible index, instead of the real one.

The index is logged on console.

### Expected Behavior

There should be a propery to access the actual index, based on DOM elements and not only visible ones.

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Anyone

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by michelebruno** [comment]
I've also found a related issue. If I pass a function as `SwiperSlide `child, the passed properties are wrong and isActive is false on an active slide, if it comes after an hidden slide.

I've updated the sandbox to reproduce the issue.

**Comment by nolimits4web** [comment]
Hidden slides are not supported, just don't render  slides (include/exclued from your slides array) you don't to show

**Comment by michelebruno** [comment]
I need to show them on screen breakpoints. I was trying to add an activeDomIndex to solve the problem, but it requires tests for all packages.

Do you think we could work on that?

**Comment by nolimits4web** [comment]
Well, that is for sure will have a lot of side effects to many modules, and even worse to the infinite amount of combination of them :) What I can suggest, if let's say there will be a new `beforeBreakpoint` event, where you can hook to and based on breakpoint that is going to be activated - toggle required slides, will this work?

**Comment by michelebruno** [comment]
I think that would help on conditional rendering for sure. Thank you very much for your work.
