### ISSUE TITLE
"swiper-pagination-bullet-active-main" doesn't move to next slide code when using touchMove.

### ISSUE THREAD

**Issue by seongryeol-han** [nolimits4web/swiper#4738]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/xenodochial-gagarin-i368n?from-embed

### Bug description

When I slides my image to next image, the bullet is stopping on first bullet. 

I searched what happens on code. That is.. "swiper-pagination-bullet-active-main" doesn't move to next slide code.

This bug happened after I add "infinite scroll API" 

My code is

`<script>

    var options={
        autoHeight: true,
        pagination: {
          el: '.swiper-pagination',
          dynamicBullets: true,
        },
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        },
        allowTouchMove: true,
    }

    var swiper = new Swiper('.swiper-container', options);

   
    function renewswiper(){ 

      Swiper('.swiper-container', options);
      
    }
    
    $(document).ready(function () { 
      var list = $('.book-list');
          list.jscroll({
              padding: 1000,
              pagingSelector: '.pagination',
              nextSelector: 'a.next-page:last',
              contentSelector: '.card,.pagination',
              callback: renewswiper,
          });
    });
  </script>
`

![image](https://user-images.githubusercontent.com/80833376/124378943-3a662800-dcef-11eb-8d99-34fdaab5f079.png)

![image](https://user-images.githubusercontent.com/80833376/124378977-684b6c80-dcef-11eb-88ca-78f43ad3af4b.png)

![image](https://user-images.githubusercontent.com/80833376/124378989-7e592d00-dcef-11eb-9558-b1b4f8e7abeb.png)

Like these, bullet doesn't move to next slide.

However, when I slide image on "3" slide, the bullets update to correct slide.

How can I solve this problem?

Thanks. 

### Swiper version

6.7.1

### Platform/Target and Browser Versions

Windows10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Because you tries to init already initialized swiper, you need to destroy it, or call its `.update()` method, or enable observer
