### ISSUE TITLE
Width not calculated correctly for slides when using <picture> element

### ISSUE THREAD

**Issue by ethanclevenger91** [nolimits4web/swiper#4741]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/ethanclevenger91/pen/oNWjgLB

### Bug description

When doing auto-width slides around images that are set up via a `<picture>` element, the width is not calculated correctly for each slide. See demo - be sure to size down the preview to < 768px.

### Expected Behavior

The two demos should match - shouldn't matter if I'm using an `<img>` tag or `<picture>` tag.

### Actual Behavior

Width is mis-calculated.

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Not sure how it is related to Swiper. As you may see, Swiper in your demo doesn't set any sizes to slides, so I would suggest it is some of your CSS styles issue
