### ISSUE TITLE
Prevent hiding of pagination and navigation when clicked on particular elements (while hideOnClick is set to true)

### ISSUE THREAD

**Issue by Fygo** [nolimits4web/swiper#4744]
### Clear and concise description of the problem

Currently, there are two "affected" settings I would like to talk about and let's assume both of them are set to _true_:
pagination's _hideOnClick_
navigation's _hideOnClick_
Both of them now hide/show correctly while ignoring the click on the other (thanks for that fix, btw!).

The issue is that there is currently no way (or is there?) how the hiding could be prevented. Let's assume we have an additional button on the slider (just an absolutely positioned element) or some kind of description box with a button for each slide, etc. Clicking any of these would hide/show pagination/navigation. This is not user-friendly as it is kind of unexpected.

### Suggested solution

1. Implement a "beforeHide" event which when returned false from the handler would cancel the hiding:
_swiper.on('beforePaginationHide', _ => false); // cancel the action_

OR

2. Implement a "suspendHideCheck/resumeHideCheck" method:
Worse than the first one, imho, but I guess it would still work. It would just most likely need to be deferred by the dev.

OR

3. Ignore all button elements, role="button", links, etc. This should probably be an option.

OR

4. Even better: provide an option to pass a selector which elements should not trigger the hide/show (additionally to the built in pagination and navigation elements, of course).

...

### Alternative

None that I know of.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
