### ISSUE TITLE
Swiper affects Lighthouse Accessibility

### ISSUE THREAD

**Issue by AndreBezBirolo** [nolimits4web/swiper#4745]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://andrejbezbirolo.tech/swipper-issue-demo/

### Bug description

When running a check on Google's Lighthouse, it removes 2 accessibility points claiming that inside the listing there is something more than the 'LI' tag. When disabling the swiper this error disappears.

### Expected Behavior

It is expected that when activating the swiper on a listing it does not create any elements inside the UL tag, so there are no accessibility conflicts.

### Actual Behavior

By activating the swiper on a listing, Google's Lighthouse claims that it is creating elements within UL that are not LI.

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Windows, Opera GX, Google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> Google's Lighthouse claims that it is creating elements within UL that are not LI

You can see there is nothing like that in markup, if it matters for you don't use UL/LI. Closing as not really related to Swiper
