### ISSUE TITLE
Swiper with one slide and `loop:true` will `make watchOverflow:true` not work

### ISSUE THREAD

**Issue by dippas** [nolimits4web/swiper#4747]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/dippas/pen/XWRKdZX

### Bug description

I use Swiper with a CMS so a lot of times I don't have the ability to control the amount of slides each slider will have, therefore I'm using `watchOverflow: true` for wherever the reason the number of slides in only one then the navigation/pagination goes away

It works perfectly, Unless the `loop` is set to `true` (which most of the time is requisite of the client), I know I could make a condition on the `loop`, something  like this:

`loop: swiper.slides.length === 1 ? false : true `

But I'd like to see this in the Swiper core

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Windows 10 / Chrome 91 & FireFox 89

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by dippas** [comment]
@nolimits4web  bumping this

**Comment by dippas** [comment]
@vltansky  @nolimits4web  I think this would be a great feature to implement in V7, what you guys think?

**Comment by uskov-dev** [comment]
I support. I would like it if the number of slides is less than or equal to the visible number, it would not be possible to scroll during looping and the control buttons would be hidden.

**Comment by dippas** [comment]
bump @vltansky  @nolimits4web

**Comment by czraptor** [comment]
> I support. I would like it if the number of slides is less than or equal to the visible number, it would not be possible to scroll during looping and the control buttons would be hidden.

This would be nice, we also have this issue. But also it should not duplicate slides like it's doing now, because now we also have more same slides visible because of small number of slides and bigger page.

**Comment by Kipperlenny** [comment]
#2900 and #2621 discussed the same, this is supposed to be a feature and not a bug (*stupid*)

**Comment by Johndo36** [comment]
We found a good solution on [https://www.great-tit.com/swiper-prevent-single-slide-swipe-with-loop-enabled/](url)

the part from their solution that helped us was:
`watchOverflow: true,
 loop: jQuery(".product-slider_main .swiper-slide").length != 1,`

Only thing we did different in our case was to remove the .product-slider_main class so:

`watchOverflow: true,
 loop: jQuery(".swiper-slide").length != 1,`

That did the trick for us.
