### ISSUE TITLE
Getting error in Angular 7 when importing SwiperModule

### ISSUE THREAD

**Issue by tyrandeluna** [nolimits4web/swiper#4749]
I'm using Angular 7 and today I downloaded the last version of Swiper. But when I import SwiperModule inside my app.modules, is throwing this errors:

ERROR in ../node_modules/swiper/angular/fesm2015/swiper_angular.js;
Module not found: Error: Can't resolve '@angular/common' in 'C:\Users\Beatriz\Projetos\Porto-Store\node_modules\swiper\angular\fesm2015';
ERROR in ../node_modules/swiper/angular/fesm2015/swiper_angular.js;
Module not found: Error: Can't resolve '@angular/core' in 'C:\Users\Beatriz\Projetos\Porto-Store\node_modules\swiper\angular\fesm2015';
ERROR in ../node_modules/swiper/angular/fesm2015/swiper_angular.js;
Module not found: Error: Can't resolve 'rxjs' in 'C:\Users\Beatriz\Projetos\Porto-Store\node_modules\swiper\angular\fesm2015';

I followed all the installation steps here https://swiperjs.com/angular
=/

**Comment by nolimits4web** [comment]
Please, don't ignore issue template, it is there for a reason
