### ISSUE TITLE
Wrong container size with flex and max-width on parents 

### ISSUE THREAD

**Issue by ulbrich-media** [nolimits4web/swiper#4753]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/9h6egu2p/35/

### Bug description

Hey, during implementation of swiper as a simple image gallery I encountered an issue in combination with our page layout. 

On top of the page there is a max-width container. Inside there is a flex container with a fix with child (sidebar navigation) and a content child that takes the remaining space. 

Using a swiper slider inside the content child, the swiper-container doesn't match the content childs available space, but the containers max-width. This results in the swiper being far too wide and running into overflow. After resizing the window it gets even more messy (see fiddle). 

I'm not quite sure if this is a swiper bug or some weird browser behaviour. However before initialisation the swiper-container has the right width. 

A simple workaround is to switch to "slidesPerView: 'auto'", but then I need to size the swiper-slides via css. 

### Swiper version

6.7.5

### Platform/Target and Browser Versions

macOS Safari 14.1, Firefox latest 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how CSS works in general. Set something like `min-width: 0` to container
