### ISSUE TITLE
Dependency not found for swiper/swiper-vue

### ISSUE THREAD

**Issue by forchel** [nolimits4web/swiper#4763]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/vue-3-ts-swiper-5swu8

### Bug description

I can not use swiper with Vue 3 + TS.

Even with a new project created with vue-cli it is not possible to use it.
After adding swiper with

yarn add swiper

and using it within a sample Component (see Sandbox above) the build script fails with the following error message:

 ERROR  Failed to compile with 1 error                                                                          17:15:22

This dependency was not found:

* swiper/swiper-vue in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/ts-loader??ref--13-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/HelloWorld.vue?vue&type=script&lang=ts

To install it, you can run: npm install --save swiper/swiper-vue

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The demo link you provided doesn't have anything related to Swiper

**Comment by forchel** [comment]
Sorry, it was my first codesandbox example. I've added a new link which is hopefully working.

**Comment by nolimits4web** [comment]
You have posted the same link without Swiper there

**Comment by tinobino** [comment]
Could you please try again? I've checked the link in a private window and it seems to work now.

**Comment by nolimits4web** [comment]
And where did you get such `swiper/swiper-vue` package name? Check docs https://swiperjs.com/vue

**Comment by forchel** [comment]
Okay, I didn't notice that the import statement was wrong. But this swiper/swiper-vue package name was generated automatically by eslint. By clicking on the import in my IDE, the Swiper/SwiperSlide type definitions defined in swiper-vue.d.ts are resolved. So I didn't think this could be wrong.
I'm sorry.

**Comment by Exlord** [comment]
I am getting the same error importing from `import { Swiper, SwiperSlide } from 'swiper/vue';`

**Comment by Exlord** [comment]
https://codesandbox.io/s/vue-3-ts-swiper-forked-l8p7h

**Comment by Kashterion** [comment]
I can confirm this issue as well, as I have the same problem. Can we do anything to resolve this?
I'm trying to import Swiper in a Component the same wat as it is written in the documentation.

`import { Swiper, SwiperSlide } from 'swiper/vue';`

`
These dependencies were not found:

* swiper/css in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TeaserBoxCarousel.vue?vue&type=script&lang=js&
* swiper/vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TeaserBoxCarousel.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save swiper/css swiper/vue
`

package.json
`
  "dependencies": {
    "@babel/polyfill": "^7.4.4",
    "contentful": "^8.4.2",
    "core-js": "^3.6.4",
    "swiper": "^7.0.3",
    "vue": "^2.6.11",
    "vuetify": "^2.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.2.0",
    "@vue/cli-plugin-eslint": "^4.2.0",
    "@vue/cli-plugin-unit-jest": "^4.1.1",
    "@vue/cli-service": "^4.2.0",
    "@vue/test-utils": "^1.0.0-beta.30",
    "axios": "^0.21.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^25.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.0.1",
    "fibers": "^4.0.2",
    "imagemin-webpack-plugin": "^2.4.2",
    "node-sass": "^4.14.1",
    "postcss-normalize": "^9.0.0",
    "sass": "^1.32.0",
    "sass-loader": "^10.0.0",
    "vue-cli-plugin-vuetify": "~2.4.1",
    "vue-eslint-parser": "^6.0.0",
    "vue-i18n": "^8.15.1",
    "vue-router": "^3.1.3",
    "vue-template-compiler": "^2.6.11"
  },
`
