### ISSUE TITLE
Swiper modules are not installed in SvelteKit

### ISSUE THREAD

**Issue by slava-viktorov** [nolimits4web/swiper#4767]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/eager-archimedes-81jmb

### Bug description

Additional Swiper modules are not installed when using SSR SvelteKit.

Probably, the Swiper component from "swiper/esm/svelte/swiper.svelte" and SwiperCore from "swiper/core" get different objects of the Swiper class (core-class.js).

```javascirpt
  import Swiper from "swiper/esm/svelte/swiper.svelte";
  import SwiperSlide from "swiper/esm/svelte/swiper-slide.svelte";
  import "swiper/swiper.scss";
  import "swiper/components/pagination/pagination.scss";
  import SwiperCore, { Pagination } from "swiper";

  SwiperCore.use([Pagination]);
  
//on:swiper
   const onSwiper = (e) => {
      const [swiper] = e.detail;
      console.log(Object.keys(swiper.prototype.modules).join(', ')); // resize, observer - NOT INSTALL Pagination module
    }
```

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Ubuntu Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate #4705
