### ISSUE TITLE
Spring Effect

### ISSUE THREAD

**Issue by L-Chris** [nolimits4web/swiper#4777]
### Clear and concise description of the problem
`
const swiper = new Swiper('.swiper-container', {
  effect: 'spring',
  springEffect: {
    stiffness: 300,
    damping: 20
  },
});
`

### Suggested solution

use [springer](https://github.com/tannerlinsley/springer) to interpolate translate

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Sorry, but I don't think it will be super useful for everyone, you can implement it by yourself by creating the custom plugin (like other effects work)
