### ISSUE TITLE
bug: isNode judge is inaccurate in server side rendering

### ISSUE THREAD

**Issue by zhangyuang** [nolimits4web/swiper#4787]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/zhangyuang/swiper-bug-isnode

### Bug description

```js
// src/utils/utils.js
function isNode(node) {
  // eslint-disable-next-line
  if (typeof window !== 'undefined') {
    return node instanceof HTMLElement;
  }
  return node && (node.nodeType === 1 || node.nodeType === 11);
}
```

The judge is very inaccurate, in server side render, framework self or users maybe mock a window object in server side is frequent

Maybe there should judge at a deeper level。for example, `window.document`,`window.document.documentElement` or `window.screen`

### Swiper version

6.8.0

### Platform/Target and Browser Versions

macos

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by zhangyuang** [comment]
For the issue， the corresponding pr is https://github.com/nolimits4web/swiper/pull/4788

**Comment by lhtdesignde** [comment]
I updated to 6.8.1 and still seeing this, I guess, related error: `ReferenceError: HTMLElement is not defined`.
This comes up in a mocha/enzyme test.
