### ISSUE TITLE
Bug when use breakpoints with slidesPerView and loop on NextJS

### ISSUE THREAD

**Issue by VictorAssis** [nolimits4web/swiper#4790]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/nextjs-swiper-breakpoint-loop-bug-34hrz

### Bug description

When using "breakpoints" to determine the number of slides per view along with the loop property in NextJS, the HTML attributes of the slides are incorrectly swapped (the href and class from item 1 goes to item 5 for example).

This occurs when loading the page on a screen with a width greater than or equal to the breakpoint, recording in the console the error "Warning: Prop `href` did not match. Server: "#6" Client: "#3"'.

If you load the page on a screen with a width smaller than the breakpoint and, after loading, you resize the window, the error does not occur.

I tried to use the "observer" property as indicated in issues related to NextJs, but no approach was effective in solving the problem. When the screen loads with the error, resizing it doesn't solve it either.

### Expected Behavior

That the page loads with the correct HTML attributes for each item, regardless of screen width.

### Swiper version

6.8.0

### Platform/Target and Browser Versions

Windows 10 / Chrome 91

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is pretty much expected as loop with breakpoints related to window/swiper size, which is apparently different on server and client. As a workaround, use swiper only on client or use core version of Swiper to initialize it only on client (mounted)

**Comment by VictorAssis** [comment]
@nolimits4web thanks for answering. In my case I can't display Swiper on client only because of SEO, so I'm trying to initialize it only on client as you mentioned.

I tried using the property `init={false}` so that it doesn't initialize on the server, but it kept changing the HTML attributes. Can you point me a direction to just initialize it on the client?

**Comment by humbertqz** [comment]
@VictorAssis  i have just run in to this same error, i'm also using nextjs, did you find a solution?

**Comment by VictorAssis** [comment]
> @VictorAssis i have just run in to this same error, i'm also using nextjs, did you find a solution?

My workaround to be able to quickly meet the demand I needed was to render different Swiper components (one for each screen size) and use CSS media queries to display the correct Swiper according to the user screen size.

But this solution is far from the best and I'll come back to this problem as soon as I get some time around here.

**Comment by TomSmedley** [comment]
Yeah I have this issue too, I think it's because the React version of Swiper is just a wrapper and not a true component, I've found it isn't truly reactive and has some issues out of the box, such as breakpoint.

I'll have a look at the best way of correcting this.
