### ISSUE TITLE
AutoHeight issue if slider have Video tag.

### ISSUE THREAD

**Issue by Saqib92** [nolimits4web/swiper#4791]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-angular-pagination-dynamic-forked-o39pw

### Bug description

`[autoHeight]="true"` is not working if the slider have Video tag in first slide. after swiping the slide autoHeight takes effect and works well. 

### Expected Behavior

`[autoHeight]="true"`  not working with Video tag on first Slide. 

### Actual Behavior

`[autoHeight]="true"` should work with Video tags and adjust video height accordingly. 

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Capacitor, Chrome, Ionic, Android, iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please, create a demo without other frameworks and tools, otherwise we can't validate that error is not with something else

**Comment by Saqib92** [comment]
Here is the Demo Link: https://codesandbox.io/s/swiper-angular-pagination-dynamic-forked-o39pw

**Comment by nolimits4web** [comment]
As I see the demo you provided looks and works fine to me, can't see any errors. Anyway, issue can happen if slide's height can't be determined (like video probably won't have size). It is up to you to care about it (by setting video/image element height or call `swiper.updateAutoHeight` when video/image loaded)
