### ISSUE TITLE
Set different width to one slide

### ISSUE THREAD

**Issue by AnthonyZink** [nolimits4web/swiper#4792]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-per-view-forked-brgq1?file=/index.html

### Bug description

I have a swiper like this:

```js
const swiper = new Swiper('.swiper-container', {
    slidesPerView: 1.2,
    centeredSlides: true,
    spaceBetween: 12
});
```

I would like my first slide to be 100% of the screen width and when I move to the second item I get back the centering, the padding and the visible part of the third item.

Is it possible to do that actually or is there a trick ?

### Swiper version

6.1.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is what possible https://codesandbox.io/s/swiper-slides-per-view-forked-1pbbk
