### ISSUE TITLE
Error in function Object.append

### ISSUE THREAD

**Issue by AlmogRnD** [nolimits4web/swiper#4793]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

n/a

### Bug description

Getting the following error  Error in function Object.append

`Error in function Object.append in ../../node_modules/@glidejs/glide/dist/glide.esm.js:1826`

Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
../../node_modules/@glidejs/glide/dist/glide.esm.js:1826

for (var _i2 = 0; _i2 < prepend.length; _i2++) {
       wrapper.insertBefore(prepend[_i2], slides[0]);
     }
```

This happens in development mode when I right-click to inspect the element. It has something to do with Gasby Image not sure what is going on so I thought I would at least report it 

### Expected Behavior

No errors 

### Actual Behavior

Getting error 

### Swiper version

6.5.4

### Platform/Target and Browser Versions

mac 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper is not glide.js
