### ISSUE TITLE
Slider Height not flexible

### ISSUE THREAD

**Issue by NeoMudaly** [nolimits4web/Swiper#48]
I have 

```
<div class='swiper-slide'>
    <div>Image</div>
    <div>Description</div>
</div>
```

Following setup for the responsive Swiper, the height no longer works.
If I set height to 100%, then I get whitespace caused by the slides stacking.
Height:auto , same result. It seems that a pixel value is always set, locking the height.
Am I missing an option or css that allows the height to flex?

**Comment by kalvinmoraes** [comment]
Fixed my problem using the following in "onSlideChangeStart"

```
onSlideChangeStart: (swiper)->
        $(swiper.slides).each ->
          $(this).css height: if $(this).index() != swiper.activeIndex then 0 else 'auto'
```

Setting the "hidden" slides ```height = 0``` and active slide ```height = auto``` on change start should fix the problem.

**Comment by yogesh131jadhav** [comment]
@nolimits4web 

Its really nice slider. I am using this slider.
I have one problem while using this slider with **onSlideChangeStart**.
> I have 2 slides in slider.
> When I shift from one slide to another. Actual the event should fire but its not getting fire.
> While I trying to slider 2 to 3 (3rd slide not present) or trying to slide to before 1st the action raised. 

Please suggest something.
Waiting for response.

Thanks

**Comment by yogesh131jadhav** [comment]
Fixed my problem.
Problem was occurred due to written the function in document.ready()
when I picked that function out problem gets resolved.
```javascript
// Working Code
var mySwiper = new Swiper('.swiper-container',{
   onSlideChangeStart: function(swiper){
       setSwiperHeight();
   }
})
```

```javascript
// Not Working Code
$(document).ready(function(){
  var mySwiper = new Swiper('.swiper-container',{
     onSlideChangeStart: function(swiper){
         setSwiperHeight();
     }
  })
})
```
