### ISSUE TITLE
update realIndex while touching.

### ISSUE THREAD

**Issue by patofet** [nolimits4web/swiper#4801]
### Clear and concise description of the problem

When I start the drag and drop in order to change the slide and trigger ther event sliderMove, the swiper.realIndex doesn't update and the class swiper-slide-active doesn't update.

### Suggested solution

It'd be great to know the actual slide that the user have active updating the swiper.realIndex

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
`watchSlidesProgress: true`
