### ISSUE TITLE
Breakpoints with different slidesPerColumn issue

### ISSUE THREAD

**Issue by aashestakov** [nolimits4web/swiper#4803]
Problem was described at https://github.com/nolimits4web/swiper/issues/4658

Seems bug still exists. We can see problem at resize time: https://uyrrf.csb.app/ - just added **breakpoints** to example with **slidesPerColumn** param.
Swiper 6.8.0
`
      var swiper = new Swiper(".mySwiper", {
        slidesPerView: 2,
        slidesPerColumn: 1,
        spaceBetween: 30,
        breakpoints: {
          768: {
            spaceBetween: 30,
            slidesPerView: 3,
            slidesPerColumn: 2
          }
        },
        pagination: {
          el: ".swiper-pagination",
          clickable: true
        }
      });
`

_Originally posted by @aashestakov in https://github.com/nolimits4web/swiper/issues/4658#issuecomment-890363481_

**Comment by nolimits4web** [comment]
Please don't ignore issue templates, they are there for a reason
