### ISSUE TITLE
Breakpoints with different slidesPerColumn

### ISSUE THREAD

**Issue by aashestakov** [nolimits4web/swiper#4804]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://uyrrf.csb.app/

### Bug description

1. Initialize swiper with **slidesPerColumn** and **breakpoint**s params:
`var swiper = new Swiper(".mySwiper", { slidesPerView: 2, slidesPerColumn: 1, spaceBetween: 30, breakpoints: { 768: { spaceBetween: 30, slidesPerView: 3, slidesPerColumn: 2 } }, pagination: { el: ".swiper-pagination", clickable: true } });`

2. When we hit breakpoint`s size while resizing then slides seems to have not proper position:
before resize: https://i.imgur.com/ZvTQ1Ga.jpg
after resize: https://i.imgur.com/0y0RU7D.jpg

### Swiper version

6.8.0

### Platform/Target and Browser Versions

LinuxMint Chrome Version 90.0.4430.85 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
duplicate #4044
