### ISSUE TITLE
Assigning custom navigation buttons inside a component that uses the Swiper component results in the navigation elements controlling all swiper components

### ISSUE THREAD

**Issue by lsblsb** [nolimits4web/swiper#4810]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-vue-default-forked-j5rqi?file=/src/Slider.vue

### Bug description

A Swiper component is used inside component "B".
Component "B" uses the navigation module and defines custom buttons by using assigning the corresponding class-names.
These custom buttons are not positioned inside the swiper-tag due to design purposes.
Component "A" is using component "B" multiple times.
The custom buttons in each created component "B" are controlling ALL created Swiper instances.

Assigning the corresponding aria-controls value "swiper-wrapper-xxxxxxxxxxxxxxxx" did not help.

### Expected Behavior

Each custom prev and next button should be bound to the corresponding Swiper instance.
At least an option to bind a custom button to a specific swiper instance directly, would help.

### Swiper version

swiper 6.7.5 @ vue 3.0.0

### Platform/Target and Browser Versions

Ubuntu 20.04

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by lsblsb** [comment]
Assigning a unique class-name for each prev- and next-button solves this problem.
However, the question arises whether there is a better way to solve this problem.

**Comment by nolimits4web** [comment]
Use unique CSS selectors or pass HTML elements instead
