### ISSUE TITLE
Unable to set custom class on pagination

### ISSUE THREAD

**Issue by glassesUSA** [nolimits4web/swiper#4815]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

-

### Bug description

When adding a custom class using 
```   
 pagination={{ clickable: true, el: '.test' }}
``` 

The pagination dissapears

### Expected Behavior

Custom class is added

### Actual Behavior

Element is removed from the document

### Swiper version

6.8.1

### Platform/Target and Browser Versions

macOS Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
`el` parameter is for specifying custom pagination element. Setting custom class is not supported
