### ISSUE TITLE
Error showing the sliders in production

### ISSUE THREAD

**Issue by InSight1910** [nolimits4web/swiper#4824]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-swiper-navigation-forked-59kqt?file=/src/components/Carousel.jsx

### Bug description

When I in dev environment, the slider work at 100% but when I make the deploy to github page the slider not work properly.
I let the link where is the deploy InSight1910.github.io .

### Expected Behavior

The swiper is showing all slider, what it produces a horizontal scroll.

### Actual Behavior

I hope to show a slide and the horizontal scrolling disappears

### Swiper version

6.8.1

### Platform/Target and Browser Versions

Windows: Edge and Android: Firefox,

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I clearly see working Swiper on your link
https://user-images.githubusercontent.com/999588/129164709-59a91e89-90ff-496a-a8d4-953ab8a8d55c.mov

**Comment by InSight1910** [comment]
Sorry, my bad but the problem is in the resolution of the mobiles, I am very sorry for not specifying that
