### ISSUE TITLE
Swiper Vertical scroll not works correctly on touchpad 

### ISSUE THREAD

**Issue by Dushyant1295** [nolimits4web/swiper#4829]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/dushyant1295/pen/BaREeOQ

### Bug description

Swiper Vertical scroll not works correctly on touchpad 

some time it slides 2 time and skip the next slide

here is codepen  for this ( use mouse touchpad )

https://codepen.io/dushyant1295/pen/BaREeOQ

### Expected Behavior

By scrolling the vertical slider, it should not skip any slide 

### Actual Behavior

currently, sometime it skips slides or  jump fastly

### Swiper version

6.8.1

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Not sure about what mouse touchpad model you speak, but if it is macOS, then this is how inertia scrolling works there
