### ISSUE TITLE
swiper.controller is undefined

### ISSUE THREAD

**Issue by fenyiwudian** [nolimits4web/swiper#4830]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/fenyiwudian/nobuta/tree/master/backup/client_demo/swiper

### Bug description

1. clone repository of the  reproduction link
2. cd nobuta/backup/client_demo/swiper
3. yarn install
4. yarn start
5. open localhost:5678 in your browser
6. open dev tools console will see 
```
Uncaught TypeError: Cannot set property 'control' of undefined
```

the reproduction demo was migrated from https://codepen.io/ezra_siton/pen/eYOPBPX which use swiper via script tag directly，it seems using swiper via script tag will work，but not when using via es module import。

### Expected Behavior

swiper.controller should exist

### Actual Behavior

Uncaught TypeError: Cannot set property 'control' of undefined

### Swiper version

6.8.1

### Platform/Target and Browser Versions

macOS Big Sur 11.4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/get-started#install-from-npm

> By default Swiper exports only core version without additional modules (like Navigation, Pagination, etc.). So you need to import and configure them too:
