### ISSUE TITLE
Navigation buttons not working with thumb gallery and custom `NavigationOptions`

### ISSUE THREAD

**Issue by PhilippMeissner** [nolimits4web/swiper#4845]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/navigation-not-working-with-thumb-gallery-gwdnf?file=/src/app/app.component.ts

### Bug description

When using a thumb gallery and setting `navigation` to custom `NavigationOptions` rather than a boolean the previous/next buttons are not working anymore.
Eg
```
// not working
navigation: {
  disabledClass: "swiper-button-disabled custom-class"
}
```
vs 
```
/ / working
navigation: true,
```

The only thing left is swiping or *clicking* the thumb gallery items in order to have the main swiper display the correct slide.

### Expected Behavior

I clicked the next/previous button and the main slider did not change to another slide.
Instead I have to click the image of the thumb gallery in order to manipulate the main slide.

### Actual Behavior

When clicking the next/previous buttons nothing happens.

### Swiper version

6.5.0

### Platform/Target and Browser Versions

macOS 14. Latest Chrome, Firefox and Safari.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
Looks like it works fine in Swiper 7
https://codesandbox.io/s/swiper-thumbs-gallery-angular-forked-lj113?file=/src/app/app.component.ts

**Comment by PhilippMeissner** [comment]
> Looks like it works fine in Swiper 7
> https://codesandbox.io/s/swiper-thumbs-gallery-angular-forked-lj113?file=/src/app/app.component.ts

Nope, still the same issue - You can *drag*, but you can not *click* the navigation buttons. At least on my end that has no effect.

**Comment by kurtiev** [comment]
Hi, did you solve this?
I'm using Angular 13, and it also works only with a swipe event but not with the navigation arrows.

**Comment by vltansky** [comment]
https://codesandbox.io/s/swiper-thumbs-gallery-angular-forked-8mluk?file=/src/app/app.component.ts

@kurtiev is this works for you?

**Comment by kurtiev** [comment]
@vltansky yes, it works.

**Comment by vltansky** [comment]
@kurtiev Can you share codesandbox with an example that isn't working for you?

**Comment by kurtiev** [comment]
Sorry, my bad, didn't look well into documentation...

I just added:

`import SwiperCore, { Navigation } from "swiper";
SwiperCore.use([Navigation]);`

and now everything is fine.

Thanks for interest @vltansky

**Comment by PhilippMeissner** [comment]
Thanks a lot 👍
