### ISSUE TITLE
Что-то сломалось 

### ISSUE THREAD

**Issue by lime-sklad** [nolimits4web/swiper#4856]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://siteemil.hostronavt.ru/portfolio/slidertest/slider2.html

### Bug description

Внезапно на всех сайтах где я подключал swiper по cdn перестали работать, насколько я понял после обновления. Хорош, что у меня были копии скриптов локальною Исправьте пожалуйста  

### Swiper version

6,7,1

### Platform/Target and Browser Versions

win 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/migration-guide

**Comment by vltansky** [comment]
Or use 
`https://unpkg.com/swiper@6/swiper-bundle.min.css`
`https://unpkg.com/swiper@6/swiper-bundle.min.js`
