### ISSUE TITLE
v7.0.0 broken display behaviour

### ISSUE THREAD

**Issue by BernhardHeiss** [nolimits4web/swiper#4857]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

www.example.com

### Bug description

Due to the update of a new version all of pages using swiperjs are displayed incorrectly

The bug does not appear in v6.8.4.,nor does  the bug appear before  v7.0.0-alpha.23,. I am certain this was caused by this commit:
https://github.com/nolimits4web/swiper/commit/ad8002c87689936457110350e734766f2fc43dee

### Expected Behavior

Incorrect display of swiper
![image](https://user-images.githubusercontent.com/33829462/130803804-f67fc7fc-7d13-44c2-bd3c-6af992cff2b6.png)

### Actual Behavior

Normal display of the page.
![image](https://user-images.githubusercontent.com/33829462/130804333-4e8bca53-53ef-412d-813e-396c1804ce27.png)

### Swiper version

v7.0.0-alpha.23

### Platform/Target and Browser Versions

chrome,firefox,edge (mobile and browser)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/migration-guide#html-layout
