### ISSUE TITLE
Cannot resolve swiper/react using typescript with swiper@7.0.0

### ISSUE THREAD

**Issue by saidmoya12** [nolimits4web/swiper#4858]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no public link

### Bug description

When I update from "swiper": "6.8.4" to "swiper": "^7.0.0", throw the errors
Module not found: Can't resolve 'swiper' 
Module not found: Can't resolve 'swiper/react' 

Try to solve with 
1. The [documentation](https://swiperjs.com/react) and the [migration guide ](https://swiperjs.com/migration-guide) 
2. I'm working with typescript and I try installing @types/swiper

but doesn't work

### Expected Behavior

Just work with documentation and migration guide from 6 to 7

Can someone help me?

### Actual Behavior

`Module not found: Can't resolve 'swiper' `
`Module not found: Can't resolve 'swiper/react' `

### Swiper version

7.0.0

### Platform/Target and Browser Versions

Chrome, Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
- https://swiperjs.com/migration-guide#node-es-modules
- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
