### ISSUE TITLE
slidesPerView: 'auto' not working when reintroducing on breakpoint - Please look at demo before closing

### ISSUE THREAD

**Issue by curtisburns** [nolimits4web/swiper#4881]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/angry-thunder-8w24b?file=/index.html

### Bug description

When transitioning from slidesPerView: 1 to slidesPerView: auto, the width attributes are not removed from the slides which breaks the carousel.

### Expected Behavior

Remove unnecessary width attributes from slides when transitioning between breakpoints and different configs.

### Actual Behavior

When on slidesPerView: auto on init, no inline styling for width is necessary. When shifting to slidesPerView: 1, inline styling is added to slides for the width, but is never removed when transitioning back to slidesPerView: auto on the breakpoint. Workaround is to manually set width properties in CSS with !important. swiper.update or swiper.updateSize doesn't work.

### Swiper version

7

### Platform/Target and Browser Versions

macOS, Windows, Safari, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by curtisburns** [comment]
Why was it closed this time, Vlad?

**Comment by nolimits4web** [comment]
<img width="444" alt="Снимок экрана 2021-08-30 в 16 39 23" src="https://user-images.githubusercontent.com/999588/131348218-afa6133b-c4dd-41fc-a88f-d6df723ac1cd.png">

👆👆👆👆👆
