### ISSUE TITLE
Vue3 CLI: Can't resolve 'swiper/vue'

### ISSUE THREAD

**Issue by jugurj** [nolimits4web/swiper#4886]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/jugurj/swiper-bug-report

### Bug description

That is the first git issue report in my life therefore I hope I did everything right.
I attempted to use last version of the swiper package in my Vue 3 project created by the Vue CLI tool. I implemented it exactly as it was described on the documentation page's Vue section but got an "Can't resolve 'swiper/vue'" error.

I did not find out what could cause that error but my current solution was to use a previous Swiper 6 version and it seems to work just fine with Vue 3 CLI project. 

### Swiper version

7.0.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look here #4871
