### ISSUE TITLE
Lazy loading images does not work when using grid mode

### ISSUE THREAD

**Issue by MrHaroldA** [nolimits4web/swiper#4889]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#slides-grid

### Bug description

Lazy loading images only works the first row in a grid, the other rows keep showing the preloader.

### Expected Behavior

Lazy loading should work on rows 1+ as well.

### Actual Behavior

Images are never loaded.

### Swiper version

7.0.1

### Platform/Target and Browser Versions

Brave V1.28.106 (Chromium 92.0.4515.159)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The demo link you provided doesn't illustrate the issue
