### ISSUE TITLE
Accessibility attributes of navigation buttons have incorrect values

### ISSUE THREAD

**Issue by vralle** [nolimits4web/swiper#4891]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#navigation

### Bug description

Accessibility attributes for navigation buttons are invalid.

### Actual Behavior

Swiper Navigation Buttons:
```html
<div class="swiper-button-next" tabindex="0" role="button" aria-label="undefined" aria-controls="Next slide" aria-disabled="false"></div>
<div class="swiper-button-prev swiper-button-disabled" tabindex="-1" role="button" aria-label="undefined" aria-controls="Previous slide" aria-disabled="true"></div>
```
Attributes `aria-label` and `aria-controls` are invalid

### Swiper version

7.0.1

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/pull/4884
