### ISSUE TITLE
swiper-bundle.min.js:13 Uncaught TypeError: Cannot read property 'el' of null     at l (swiper-bundle.min.js:13)

### ISSUE THREAD

**Issue by AntonMolchanov** [nolimits4web/swiper#4892]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/yamnyk/slay
https://slay.com.ua/salons/beauty-space/

### Bug description

Swiper.js worked perfectly fine on prod for 4 months but then stopped. I've used Swiper from CDN. 

Now I get the following error in the console: 

swiper-bundle.min.js:13 Uncaught TypeError: Cannot read property 'el' of null
    at l (swiper-bundle.min.js:13)
    at c (swiper-bundle.min.js:13)
    at H.<anonymous> (swiper-bundle.min.js:13)
    at swiper-bundle.min.js:13
    at Array.forEach (<anonymous>)
    at swiper-bundle.min.js:13
    at Array.forEach (<anonymous>)
    at H.emit (swiper-bundle.min.js:13)
    at H.checkOverflow (swiper-bundle.min.js:13)
    at H.updateSlides (swiper-bundle.min.js:13)

There has nothing been changed in the code for 4 months. 
Here is the link I initially used 
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

I've tried changing it to the new one but that didn't work out.
<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

Since there has nothing been changed in the project for such a long time and Swiper was used from CDN, I assume that the issue is not on my side. I would highly appreciate it if you could take a look at the issue.
Thanks a lot

### Expected Behavior

I expect Swiper to swipe the photos.

### Actual Behavior

Swiper doesn't work.

### Swiper version

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

### Platform/Target and Browser Versions

macOS Big Sur; Chrome Version 92.0.4515.159 (Official Build) (x86_64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/migration-guide
