### ISSUE TITLE
mySwiper.params.simulateTouch = false;  

### ISSUE THREAD

**Issue by davy-blavette** [nolimits4web/Swiper#49]
var mySwiper = new Swiper('.swiper-container', { 

```
simulateTouch:true,
onSlideChangeEnd : function() {
    if(mySwiper.activeSlide == 8){
     mySwiper.simulateTouch = false;   
    }else{
      mySwiper.params.simulateTouch = true;  
    }
    }
```

}) 

why do not run ? :/

**Comment by ranonengineer** [comment]
Is this solution still in effect? I tried and it did not work.

mySlider.params.onlyExternal = true;
mySlider.params.simulateTouch = false;

I realized this is almost 5 years old post. I want to check on this solution again. Thank you!
