### ISSUE TITLE
lazy.checkInView option is not working

### ISSUE THREAD

**Issue by Pixelous** [nolimits4web/swiper#4900]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-lazy-load-images-forked-n0wn6?file=/index.html

### Bug description

Hi,

**lazy.checkInView** option is not working.

On the demo see **Image loaded prior to scrolling...** in console.

The fix is actually pretty easy:

In https://github.com/nolimits4web/swiper/blob/master/src/modules/lazy/lazy.js#L244 find

```
    if (swiper.params.lazy.enabled && !swiper.params.loop && swiper.params.initialSlide === 0) {
```
and replace with:

```
    if (swiper.params.lazy.enabled) {
```

In https://github.com/nolimits4web/swiper/blob/master/src/modules/lazy/lazy.js#L263 find

`load();`

and replace with:

```
if (swiper.params.lazy.checkInView) {
  checkInViewOnLoad();
} else {
  load();
}
```
In https://github.com/nolimits4web/swiper/blob/master/src/modules/lazy/lazy.js#L272 find

`load();`

and replace with:

```
if (swiper.params.lazy.checkInView) {
  checkInViewOnLoad();
} else {
  load();
}
```
In https://github.com/nolimits4web/swiper/blob/master/src/modules/lazy/lazy.js#L278 find

`load();`

and replace with:

```
if (swiper.params.lazy.checkInView) {
  checkInViewOnLoad();
} else {
  load();
}
```

That is all) Can you please fix it ASAP?

I am sorry this is partially dublicate of [#4374](https://github.com/nolimits4web/swiper/issues/4374) but it states lazy.checkInView is not working with loop option enabled but mine it is not working at all no matter loop on or off.

### Expected Behavior

When page loads images lazy loading should not starting working until user scrolls down the page when slider becomes visible.

### Actual Behavior

When page loads images lazy loading starts working.

### Swiper version

7.0.1

### Platform/Target and Browser Versions

Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Fixed in #4901
