### ISSUE TITLE
Type issues with Creative effect and translate properties

### ISSUE THREAD

**Issue by mystrdat** [nolimits4web/swiper#4902]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Is obvious

### Bug description

`'creative'` doesn't seem to be an option defined for the `effect` prop.

![Code_5alZr7dDGb](https://user-images.githubusercontent.com/1652895/131660464-1905c2be-cba6-42e2-bddf-f0adff4767df.png)

`translate` types don't seem to include a string in the array.

![Code_mQ9dAg6h3U](https://user-images.githubusercontent.com/1652895/131660621-4690bab4-a353-4fae-a422-60b30bdcf4fc.png)

The resulting code otherwise works as it should. 

### Swiper version

7.0.2

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
Looks like `effect` should be `custom`: https://swiperjs.com/swiper-api#param-creativeEffect

**Comment by mystrdat** [comment]
@vltansky That is not what your documentation and examples show.
https://swiperjs.com/demos#effect-creative
React demo leads here https://codesandbox.io/s/xxhj3 where the `effect={'creative'}` is used.

**Comment by vltansky** [comment]
You're right. Already fixed here https://github.com/nolimits4web/swiper/commit/37dfe9d687911243475e6ea3f3881ccf4a9d405a
Thanks for reporting!
