### ISSUE TITLE
Can not reslove 'swiper/vue'

### ISSUE THREAD

**Issue by df257** [nolimits4web/swiper#4909]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

none

### Bug description

I'm use vue3, and npm i swiper
When I'm npm run serve
![image](https://user-images.githubusercontent.com/7835444/131822786-14abbac1-88cc-4e11-a1f0-b27aa7d0ccd8.png)

### Expected Behavior

none

### Actual Behavior

none

### Swiper version

7.0.2

### Platform/Target and Browser Versions

windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
