### ISSUE TITLE
can't find modules for the swiper even though i reinstalled it many times

### ISSUE THREAD

**Issue by Fighteros** [nolimits4web/swiper#4914]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

didn't push it since the swiper isn't working

### Bug description

when i try to import the swiper react fails to compile and the exception is that's module wasn't found specially css files for the swiper, when i check the folder for the swiper  i didn't find any directory for the css 

### Expected Behavior

import modules 

### Actual Behavior

module not found

### Swiper version

7.0.0

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Lemaro86** [comment]
I have the same issue, but I think that it will be closed, because author think that it normal.

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
