### ISSUE TITLE
Full screen support for swiper

### ISSUE THREAD

**Issue by SatyamKr07** [nolimits4web/swiper#4915]
### Clear and concise description of the problem

It would be great to have a button which when clicked displays the swiper in full screen. It would help see slides contents more clearly. 

### Suggested solution

A button at bottom right corner of swiper/slide like in youtube.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Sorry, but it is definitely out of the Swiper's scope. You can do it by yourself with Full screen API https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
