### ISSUE TITLE
Version 7 issue with css (it seems)

### ISSUE THREAD

**Issue by nba94** [nolimits4web/swiper#4916]
Hi All, having an issue since upgrade from version 6.8.4 to version 7.x.x (having issues since 7)

Apologies, it is my first time posting an issue - hence I may have missed out on some important information - please shout and I will add what's required. 

**Problem overview:**

Previously, the slider would appear as follows:
![image](https://user-images.githubusercontent.com/39912914/132040394-7aff242f-880c-4075-ab87-7d1052052ce3.png)

However after version 7 has been released, the same page started appearing as follows:
![image](https://user-images.githubusercontent.com/39912914/132040264-4a8cfe21-7076-44ca-910f-f4f8b472fb65.png)

I've tried keeping version 6.8.4 on just the CSS files, and it seems like most of the design stays as it should be, the only issue is pagination is missing! Please see the screenshot:
![image](https://user-images.githubusercontent.com/39912914/132040560-dce86550-617c-45c7-b6f2-230efa702370.png)

I tried understanding whether any substantial CSS changes have been made from version 6.8.4 to version 7, but couldn't work it out.

I've decided to stay on version 6.8.4 for the time being, but wondering if anyone else had any issues with CSS since the update?

**Comment by nolimits4web** [comment]
https://swiperjs.com/migration-guide#html-layout
