### ISSUE TITLE
centeredSlidesBounds does not have accurate activeIndex

### ISSUE THREAD

**Issue by JackCA** [nolimits4web/swiper#4917]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-thumbs-gallery-react-forked-ibv3c?file=/src/App.jsx

### Bug description

It appear that when using `centeredSlides` and  `centeredSlidesBounds` the `activeIndex` is incorrect.

I believe this is the same issue as https://github.com/nolimits4web/swiper/issues/4876 which was closed

### Expected Behavior

`activeIndex` should be accurate (or `realIndex`?)

### Actual Behavior

`activeIndex` initializes at `2`

### Swiper version

7.0.0

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by JackCA** [comment]
potentially related to https://github.com/nolimits4web/swiper/issues/3851

**Comment by wallythewebdev** [comment]
This might be related - 

I have just had to fix a site where the width calculations of each element are incorrect: 

![image](https://user-images.githubusercontent.com/28821463/132377818-b0e812bc-b61d-482e-97b5-8445b31ebcdd.png)

This occurs when swiper is placed in a parent which is set to display flex (this might be a one off) - Im trying to revert to an earlier version to be sure
