### ISSUE TITLE
The use of Base64 by swiper-icon violates the CSP security policy

### ISSUE THREAD

**Issue by tomseanmy** [nolimits4web/swiper#4918]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Internal network

### Bug description

hey guys. today I encountered a very painful problem, and swiper will not be available when the website opens CSP. because swiper-icon will introduce a section of base64, but introducing base64 is prohibited in CSP. is there a suitable solution for using swiperjs for CSP? thank you very much

![image](https://user-images.githubusercontent.com/42232933/132129993-34009ad1-e182-4935-b2ea-b0a6a156ecc1.png)

![image](https://user-images.githubusercontent.com/42232933/132130017-fd4a1143-937e-4e5f-9cec-c3dfbd2fb73f.png)

### Swiper version

6.8.2

### Platform/Target and Browser Versions

Win10. Chrome93

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can:
- copy locally font files https://github.com/nolimits4web/swiper/tree/master/src/icons/font
- copy locally swiper-bundle.css https://unpkg.com/swiper@6.8.4/swiper-bundle.css
- replace font src to local files
