### ISSUE TITLE
Automatically switches the selected items when toggle responsive view

### ISSUE THREAD

**Issue by yaoguoba** [nolimits4web/swiper#4924]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-per-view-forked-eh5qt?file=/index.html

### Bug description

Select an item in the last page, such as slider7 or slider8, and then **toggle responsive view**. The selected slider will automatically switch to the latest slider(slider9).

Toggle responsive view:
IOS edge/chrome/safari orientation change.
MacOS edge DevTools toggle device and orientation change.

### Swiper version

7.0.3

### Platform/Target and Browser Versions

IOS edge/chrome/safari new version

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
1. `normalizeSlideInde` should be enabled
2. Swiper active index depends on position, not on click, if you resize window, it changes active index
