### ISSUE TITLE
With cssMode enabled, slide prev/next buttons's doesn't work properly on iOS

### ISSUE THREAD

**Issue by sezemiadmin** [nolimits4web/swiper#4925]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#css-mode

### Bug description

when I click slide-prev/next-buttons on iOS browser (e.g. Safari, Chrome, Firefox) with `cssMode` enabled, focused slide returns to the first. But, this behavior does not happen on PC browser.

https://user-images.githubusercontent.com/13213803/132471717-dc941f40-489d-4826-9738-624086f1e966.MP4

### Expected Behavior

when click slide-prev/next-buttons on iOS browser with `cssMode` enabled, focused slide goes prev/next.

### Swiper version

7

### Platform/Target and Browser Versions

iOS Chrome / Safari / Firefox latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Can't see such issue in iOS 15 safari 

https://user-images.githubusercontent.com/999588/132472795-6645c47c-31f8-413b-a4d9-a9882fd6c7c6.mp4

**Comment by sezemiadmin** [comment]
Oops, it's on iOS 14.7.1 . My apologies.

**Comment by nolimits4web** [comment]
For me, it sounds like Safari bug, let see if someone experience the same

**Comment by aantciferov-codepoint** [comment]
+1, iOS 14.7.1, **both** Chrome and Safari: having the same issue as OP with [this demo](https://swiperjs.com/demos/145-css-mode/core.html).
When `cssMode` is enabled, the navigation buttons always scroll to the 1st slide. Swiping works ok though.
(And I'm using `cssMode` to fix scroll flickering in Chrome/iOS in the 1st place %-)

**Comment by Tejassharma15** [comment]
this is not working on that time not work in buttons what can i do  ??

**Comment by Tejassharma15** [comment]
add a js code but not work
