### ISSUE TITLE
Swiper slide is not displaying in ionic 5.7

### ISSUE THREAD

**Issue by Mahima-22** [nolimits4web/swiper#4929]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/rajneshbiz/swiper 

### Bug description

I have created Ionic-Angular PWA.I have updated the ionic version to 5.7.0. As per this new updation I am trying to replace the ion-slides with swiper-slide as the ion-slides has been deprecated.

swiper : 6.8.4
ionic : 5.7.0
angular : 12.0.2

In my code

app.module.ts

import { SwiperModule } from 'swiper/angular';
@NgModule({
   imports: [SwiperModule],
 })
component.ts

import SwiperCore, { Navigation, Pagination } from 'swiper';
import { IonicSwiper } from '@ionic/angular';

SwiperCore.use([IonicSwiper, Navigation, Pagination]);
export class GenesisPage implements OnInit {
  slideOpts = {
    initialSlide: 0,
    speed: 400,
    loop: true,
    autoplay: {
    disableOnInteraction: false
   },
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
    renderBullet(index, className) {
      const newClass = `${className} myCustomPager`;
      return `<span class="${newClass}"></span>`;
    }
}
};

component.html

<swiper [pagination]="slideOpts.pagination" [initialSlide]="slideOpts.initialSlide"
                [speed]="slideOpts.speed" [loop]="slideOpts.loop" [autoplay]="slideOpts.autoplay">
                <swiper-slide>
                    <div class="image-wrapper">
                        <img loading="lazy" *ngIf="!webp" width="640" height="360"
                            src="assets/images/genesis/launch-slide-1-new.png" class="first" alt="launch slide"
                            useImg />
                        <img loading="lazy" *ngIf="webp" width="640" height="360"
                            src="assets/images/genesis/launch-slide-1-new.webp" class="first" alt="launch slide"
                            useImg />
                    </div>
                    <div class="slide-content-wrap">
                        <h2>DISCOVER</h2>
                        <p>& EXPLORE</p>
                    </div>
                </swiper-slide>
            </swiper>
I am getting the error as below enter image description here

![image](https://user-images.githubusercontent.com/89627228/132514991-1640b2c7-9749-4592-8a63-faf14600371e.png)

Can anyone please help me out for this. Thanks in advance.

### Expected Behavior

It should display slides.

### Actual Behavior

Display error

![image](https://user-images.githubusercontent.com/89627228/132515015-67df45e1-e514-4626-9ecb-a80443bed59c.png)

### Swiper version

6.8.4

### Platform/Target and Browser Versions

Web

**Comment by Mahima-22** [comment]
Reproduction link of issue
https://github.com/rajneshbiz/swiper

**Comment by nolimits4web** [comment]
1. Swiper is on version 7 now, 6.x branch is not maintained anymore
2. Follow official Swiper Angular docs at https://swiperjs.com/angular
3. Check any of Angular demos, e.g. https://codesandbox.io/s/jhxqo
