### ISSUE TITLE
Angular 10 - ee* Error messages

### ISSUE THREAD

**Issue by nathangemis** [nolimits4web/swiper#4930]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

/

### Bug description

Hi,

I just tried to install Swiper in my angular 10 project but I have these error message when I ng serve.

- node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'
- node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'
- static ɵinj: i0.ɵɵInjectorDeclaration<SwiperModule>;

Any solution ?

Thank you,
Have a nice day :)

### Swiper version

7.0.4

### Platform/Target and Browser Versions

macOs google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper 7 compatible with Angular 12 +
