### ISSUE TITLE
Bundle both esm and cjs for compatibility

### ISSUE THREAD

**Issue by nelsondude** [nolimits4web/swiper#4932]
### Clear and concise description of the problem

I work in a codebase where it is too much of a lift to switch to esm just so that we can use this package. It would be great if this package also emitted cjs code so that I can use version 7, which has some props that i need that are not in version 6. 

### Suggested solution

Make the bundling step emit both esm and cjs.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
That is not an option, and dropping CJS modules was an intended move. You still have options to use version, for example by using Babel on it on your side
