### ISSUE TITLE
Virtual + CSS mode

### ISSUE THREAD

**Issue by nikitapilgrim** [nolimits4web/swiper#4933]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-virtual-slides-react-forked-cndm1?file=/src/App.jsx

### Bug description

Can you tell me, as far as I understand from version 7 virtualization should work properly with css mode. Why doesn't the example work? 

core: support for Virtual Slides in CSS Mode [(0e26d52)](https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#:~:text=core%3A%20support%20for%20Virtual%20Slides%20in%20CSS%20Mode%20(0e26d52))

### Swiper version

7.0.4

### Platform/Target and Browser Versions

windows chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Update Swiper to latest, everything works here https://codesandbox.io/s/swiper-virtual-slides-react-forked-vwhn5?file=/src/App.jsx
