### ISSUE TITLE
Having a different width for active slide offsets swiper slides when set to loop: true and centeredSlides: true

### ISSUE THREAD

**Issue by jackkemmish** [nolimits4web/swiper#4934]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codepen.io/jackkemm/pen/YzQZGBw

### Bug description

I am creating a carousel which has a different size active slide to the other slides, but need to use the loop and centeredSlides functionality. My issue is the slides are now offset from the centre, but recentre on browser resize. Ideally I don't want to have to run a window resize event each time the slides change.

### Expected Behavior

I would expect the carousel to still be centred on load and on slide change.

### Swiper version

7.0.4

### Platform/Target and Browser Versions

macOS Big Sur - All browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Changing slides sizes during transition is not supported and never will be
