### ISSUE TITLE
Virtual + CSS mode [Reopen]

### ISSUE THREAD

**Issue by nikitapilgrim** [nolimits4web/swiper#4935]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-virtual-slides-react-forked-j0sb0?file=/src/App.jsx

### Bug description

my old issues [Virtual + CSS mode](https://github.com/nolimits4web/swiper/issues/4933)

> Can you tell me, as far as I understand from version 7 virtualization should work properly with css mode. Why doesn't the example work?

core: support for Virtual Slides in CSS Mode [(0e26d52)](https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md#:~:text=core%3A%20support%20for%20Virtual%20Slides%20in%20CSS%20Mode%20(0e26d52))
![swiper](https://user-images.githubusercontent.com/49089372/132686654-e0d8dc46-f5f7-4581-bd52-069ea98fe7b6.gif)

Please see how it works, the problem is more clearly visible in the emulation of touch devices. 

### Swiper version

7.0.5

### Platform/Target and Browser Versions

windows chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> the problem is more clearly visible in the emulation of touch devices

Emulator is not a real device and not support target. I see it works perfectly fine on real iOS device. Does it work/look broken for you on real mobile device?

**Comment by nikitapilgrim** [comment]
> > the problem is more clearly visible in the emulation of touch devices
> 
> Emulator is not a real device and not support target. I see it works perfectly fine on real iOS device. Does it work/look broken for you on real mobile device?

Thank you! :)
