### ISSUE TITLE
coverflowEffect slideShadows: false doesn't work

### ISSUE THREAD

**Issue by kuhanaklobasa** [nolimits4web/swiper#4936]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-coverflow-forked-c9rhu?file=/index.html

### Bug description

slideShadows effect can't be turned off

### Expected Behavior

I tried to remove slide shadows using
slidesShadows using only slideShadows: false and then also using it in a coverflowEffect: {in here}
it didn't work, as u can clearly see in the code sandbox I provided

### Actual Behavior

Nothing changes,
I also tried removing it with css but it got overwritten or something

### Swiper version

latest

### Platform/Target and Browser Versions

macOS , Safari Version 14.0.3

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The demo you provided is wrong, you have two coverflowEffect props, one overwrite another one
