### ISSUE TITLE
Images not matching up with their content

### ISSUE THREAD

**Issue by glassesUSA** [nolimits4web/swiper#4939]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/vrxw5?file=/package.json

### Bug description

This seems to be an issue with Gatsby or something....

When running the app through the development side, the images are matched perfectly, on build, the images are mismatched

![image](https://user-images.githubusercontent.com/76479522/132720080-6145cc31-4193-42b4-b623-495aa9ee77c3.png)
Build

![image](https://user-images.githubusercontent.com/76479522/132720127-1d290804-c846-4575-a7c4-85ba3fe841b8.png)
Develop

### Expected Behavior

Images should match up

### Actual Behavior

Images are not in order

### Swiper version

6.8.1

### Platform/Target and Browser Versions

macOS Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Few points:
1. The demo you provided doesn't seem to illustrate the issue
2. You opened issue for Swiper 6.x while latest is 7.x
3. Gatsby is doing SSR right? Because of breakpoints it won't work correctly because during SSR there is no way to detect window size, I would just recommend to use [core version](https://swiperjs.com/get-started) instead and move Swiper initialization fully to the client side

**Comment by glassesUSA** [comment]
I'll try that thanks!

**Comment by glassesUSA** [comment]
Just a note... updating to 7.x fixed the images not matching up but broke the width that was set

**Comment by glassesUSA** [comment]
Heya!

Quick update as found something weird... All the data seems to be correct apart from the image url... Somehow it just switches the url around?

**Comment by glassesUSA** [comment]
@nolimits4web This is related to https://github.com/nolimits4web/swiper/issues/3858

The problem is that the solutions listed there have the issue that when virtualisation is set to true it wont appear... Is there a fix?

**Comment by glassesUSA** [comment]
Is it possible to get a fix?

**Comment by filarrro** [comment]
I've the same issue on testimonial slides on Gatsby when loop is on and breakpoints for 1 slide on SM screen, 2 on MD and 3 on large. Only the images are shifted, the rest of the slide renders fine, so I don't think that it's related to SSR...

@mradmilovic solution fixes the issue for me in Chrome and FF, but on Safari additional slides doesn't load proper image once enter the screen 😞 any suggestion someone?

**Comment by glassesUSA** [comment]
@nolimits4web Any update on this?

**Comment by 7iomka** [comment]
@mradmilovic, @nolimits4web I have the same issue when I try to use swiper in Next.js and problem for now only happens with `loop`
I happy to see that workaround with `loopAdditionalSlides={items.length - defaultPerView}`, but that is seems like a hack that a solution

**Comment by g-pex-aerian** [comment]
I think I have figured out another solution for this.

Use this hook to force client side rendering:
```typescript
import React, { useEffect, useState } from "react";

export const useClientSide = () => {
    const [isClientSide, setIsClientSide] = useState(false);

    useEffect(() => {
        setIsClientSide(true);
    }, []);

    return isClientSide;
};
```

Then in your component:

```typescript
const isClientSide = useClientSide();

if(!isClientSide) return null;

return <Swiper 
             // your swiper component
```

**Comment by mark-wff** [comment]
@nolimits4web some Issue here with NextJs. 

Issue only appear with loop enabled. Fix with `loopAdditionalSlides={items.length - defaultPerView}` works fine but seems to be very hacky.

Swiper Version: 8.4.5
NextJs Version: 12.1.0

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
