### ISSUE TITLE
Slides with HTML are dropping spaces (unless &nbsp;)

### ISSUE THREAD

**Issue by tacman** [nolimits4web/swiper#4958]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-forked-m7wts?file=/index.html

### Bug description

Using v7.0.5, when I add HTML to a slide it appears to lose the spacing.

```html
<div class="swiper">
<div class="swiper-wrapper">
  <div class="swiper-slide" >
  Testing <u>Slide</u> <sup>0</sup>
  </div>
</div>
</div>
```

![image](https://user-images.githubusercontent.com/619585/133125810-644fc9c5-abc5-4c43-bc01-bb8e07c5ec8d.png)

If I add &nbsp;, it works as expected, but obviously I don't want to do that.  Should HTML be escaped?  

Same issue with virtual slides:

```js
    virtual: {
        slides: ( () => {
            const slides = [];
            for (var i = 0; i < 17; i += 1) {
                slides.push('Dynamic&nbsp;<b>Slide</b> ' + (i + 1));
            }
            return slides;
        })(),
    },
```

### Expected Behavior

Spaces treated like normal HTML spaces

### Actual Behavior

Spaces stripped

### Swiper version

7.0.5

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is what this custom CSS does in your example (CSS basics):

<img width="403" alt="Снимок экрана 2021-09-13 в 20 11 54" src="https://user-images.githubusercontent.com/999588/133127405-2ca809e8-0992-4d7e-9376-4f8b6508310d.png">
