### ISSUE TITLE
Failed angular build on master

### ISSUE THREAD

**Issue by chrisj-skinner** [nolimits4web/swiper#4963]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

use the current master branch

### Bug description

Failed `npm run angular` build. Cloned the project - run `npm i` then run `npm run angular`

### Expected Behavior

To build a demo

### Actual Behavior

Fails with 
![Screenshot 2021-09-14 at 18 02 03](https://user-images.githubusercontent.com/5794048/133301799-d5aa8a63-ae65-48a9-b2dd-7d484634c52f.png)

### Swiper version

7.0.5

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
run `npm run build:prod` first

**Comment by chrisj-skinner** [comment]
@nolimits4web  thanks. Got the demos working. Now I want to get a demo into my angular app.

Seeing the following when trying to follow the demos approach to adding it to my app. Slightly unsure of the approach though. I just want to use it in one component.

Perhaps I've missed something in the docs. But seeing the following error 

![Screenshot 2021-09-15 at 18 25 45](https://user-images.githubusercontent.com/5794048/133481743-63d8a95c-eea1-471a-8584-c83957b2315b.png)
