### ISSUE TITLE
Can't drag video on Firefox

### ISSUE THREAD

**Issue by crypto-jianyong** [nolimits4web/swiper#4967]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://crypto.com/exchange

### Bug description

Can drag images to slide normally but can't for videos(webm/mp4).
It works on Chrome and Safari.

### Swiper version

6.8.4

### Platform/Target and Browser Versions

MacOS Firefox 92.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can add CSS property `pointer-events: none` to the `<video>` element to fix it
