### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'swiper/react'

### ISSUE THREAD

**Issue by izzetd** [nolimits4web/swiper#4972]
Bug description
In version 7.0.5 when importing import { Swiper, SwiperSlide } from 'swiper/react', compiling fails with:
Module not found: Can't resolve 'swiper/react
If i downgrade to 6.8.4 it works.

Expected Behavior
import { Swiper, SwiperSlide } from 'swiper/react'; to load correct components

Actual Behavior
import { Swiper, SwiperSlide } from 'swiper/react';

Swiper version
7.0.5

Platform/Target and Browser Versions
CentOS 7

Validations
 
- [x] Follow our Code of Conduct
- [x] Read the docs.
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] Make sure this is a Swiper issue and not a framework-specific issue

I have been following the instructions to similar Bug Tickets #4858 , #4861 . My Project is a ESM Project regarding this documentation

https://swiperjs.com/migration-guide#node-es-modules
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by nolimits4web** [comment]
#4871
