### ISSUE TITLE
When I use it in vue3 jsx. A warning will occur on the console

### ISSUE THREAD

**Issue by aesoper101** [nolimits4web/swiper#4974]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/quirky-panini-p4jh1?file=/src/components/SwiperDemo.tsx

### Bug description

When I use it in vue3. A warning will occur on the console；

Warnning:  
    Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
  at <Swiper autoplay=true > 
  at <Anonymous> 
  at <App>

### Expected Behavior

No Warnnings

### Swiper version

7.0.6

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Warning is not the error. And it is actually fine as everything works correctly. Just ignore this warning
