### ISSUE TITLE
Svelte need index.d.ts & index.js for import resolutions

### ISSUE THREAD

**Issue by alfarih31** [nolimits4web/swiper#4975]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Nope

### Bug description

IntelliSense should give you suggestion on import to `swiper/svelte`

![image](https://user-images.githubusercontent.com/36299112/133951956-d145f739-5e2a-44d2-9038-60642108c558.png)

### Expected Behavior

IntelliSense give you this suggestion

![image](https://user-images.githubusercontent.com/36299112/133952070-decfad00-2ad7-4c3e-8f78-1189ec8de0f0.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/36299112/133951956-d145f739-5e2a-44d2-9038-60642108c558.png)

### Swiper version

7.0.6

### Platform/Target and Browser Versions

macOS Brave Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (arm64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Svelte for sure doesn't need it. What needs it is your editor, which seems like doesn't support pure ES modules packages. I am not sure we need to add extra not needed files for some specific text editor

**Comment by hmaesta** [comment]
[Svelte official REPL](https://svelte.dev/repl) would benefit from this. Currently it can't run Swiper.

<img width="492" alt="Screen Shot 2022-01-26 at 13 23 51" src="https://user-images.githubusercontent.com/741969/151203548-e40102b5-99b6-4464-a9fc-4d4340fd0475.png">
