### ISSUE TITLE
Autoplay pause that respects the remaining time of slide to be changed

### ISSUE THREAD

**Issue by Jackky90** [nolimits4web/swiper#4977]
### Clear and concise description of the problem

I was a bit confused, found that there is no way to pause the progress of each slide autoplay. 
**Example:** 
1. We have autoplay setting for 5 seconds
2. After 2 seconds, user make some interaction, api call etc., that pauses the autoplay and then resume
3. After the resume I expect an option to play current slide with only the remaining time (3 seconds), but got slide timer starts from the beginning only

### Suggested solution

I expect an option `resumeAfterPause`, that could be boolean and if set to true - autoplay of current slide will continue respecting the time before interaction/action. And also would be excellent to have a slide property of **autoplayDuration**, like we have **progress** property of each slide. And, of course, I expect to have some methods for it.

The usefull example of implimentation: instagram story-like slider, that have a pagination styled like separate timelines and on every slide you can tap the slide even on the end of it's time but after interaction it will continue just the rest of timeline.

### Validations

- [x] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
