### ISSUE TITLE
slidesPerView set to auto doesn't resize images (fluid)

### ISSUE THREAD

**Issue by toddmotto** [nolimits4web/Swiper#498]
Yo,

Here's my config:

``` js
var mySwiper = $('.swiper-container').swiper({
    slidesPerView: 'auto',
    keyboardControl: true,
    centeredSlides: true,
    calculateHeight: true,
    autoResize: true,
    mode: 'horizontal',
    loop: false
  });
```

Having an issue where when I resize, the images start to stack on top of eachother and will not resize to the viewport width, the dynamically created width remains at `714px` (the image default width).

Is there any setting I am missing that fixes this? If I set the options to `slidesPerView: 'auto'` then the responsive/fluid resize works perfectly - just won't work with `'auto'`.

**Comment by keisersuze** [comment]
I am also interested . Can you post or send me the CSS solution please ?

Thanks.
