### ISSUE TITLE
Swiper v7 on Firefox triggers infinite resize changes when it is added inside an element with display grid

### ISSUE THREAD

**Issue by radum** [nolimits4web/swiper#4993]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/radum/pen/NWdKqde

### Bug description

When adding Swiper inside an element that has `display: grid;` in Firefox it triggers infinite resize calls and doing so depending on the contents or viewport size it continuously changes its size (see the codepen above in FF).

If we disable `resizeObserver` it works ok again but still the slide calculations are off and using the breakpoints to change the slides per view it breaks again.

### Expected Behavior

The carousel should not resize continuously and it should display the correct number of slides per its settings. Also the maximum size of the carousel should not grow outside of its container.

### Actual Behavior

On Firefox the carousel resizes continuously and the slides are bigger pushing the container to create an horizontal scroll.

### Swiper version

7.0.6

### Platform/Target and Browser Versions

macOS Firefox, Windows Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how CSS grid works in general, check also this https://github.com/nolimits4web/swiper/issues/2914
