### ISSUE TITLE
Speed of reversed autoplaying slides increases drastically when visiting and coming back from another browser tab 

### ISSUE THREAD

**Issue by basboy12** [nolimits4web/swiper#4995]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://logo-slider-01e16f.webflow.io/

### Bug description

On website 'X', I've created a logo slider with autoplay and reverseDirection set to true. 

Initially this works, but when I visit another tab in my browser and come back to the tab containing website 'X', the speed of the slider increases drastically. 

I've recorded a short video to illustrate the problem, which is repeatable on both Safari and Chrome for me: https://www.loom.com/share/d7e6f4dc7b024d74a9841ef59709f12c

website: [https://logo-slider-01e16f.webflow.io/](https://logo-slider-01e16f.webflow.io/)

```
// initialize the sliders
let sliderSpeed = 10000;
let sliderDelay = 0;
let loopedSlides = 10;

let logoSliderTop = new Swiper('.swiper-row-1', {
  wrapperClass: 'logo-wrapper',
  slideClass: 'logo-slide',
  slidesPerView: 4,
  direction: 'horizontal',
  spaceBetween: 0,
  speed: sliderSpeed,
  autoplay: {
    delay: sliderDelay,
    disableOnInteraction: false,
  },
  loop: true,
  allowTouchMove: false,
  loopedSlides: loopedSlides,
});

let logoSliderBottom = new Swiper('.swiper-row-2', {
  wrapperClass: 'logo-wrapper',
  slideClass: 'logo-slide',
  slidesPerView: 4,
  direction: 'horizontal',
  spaceBetween: 0,
  speed: sliderSpeed,
  autoplay: {
    delay: sliderDelay,
    disableOnInteraction: false,
    reverseDirection: true,
  },
  loop: true,
  allowTouchMove: false,
  loopedSlides: loopedSlides,
});

```

### Expected Behavior

To keep a consistent speed.

### Actual Behavior

Speed of the swiper is changing.

### Swiper version

7.0.6

### Platform/Target and Browser Versions

MacOS Big Sur, Safari | Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by basboy12** [comment]
Update: It seems to be fixed when defining waitForTransition as true.

**Comment by shady-xia** [comment]
I have the same problem, and set `waitForTransition` to `true` did not work

**Comment by rogoja** [comment]
I have the same problem. Does anyone know how to fix this?

**Comment by pjaws** [comment]
Can we reopen this issue? `waitForTransition` is `true` by default and does not fix the problem. 

Also seeing this occasionally after a browser refresh.

**Comment by eliawk** [comment]
same problem here, waitForTransition: true doesn't fix the problem

**Comment by ogawa-gorilla** [comment]
I am sorry for necroing ancient issue, but have you tried setting initialSlide [latest index]?
This utterly solved my problem.
It seems that index jump to 0 -> [latest index] caused the problem.
