### ISSUE TITLE
Multiple swipers on one page

### ISSUE THREAD

**Issue by patriklund** [nolimits4web/Swiper#50]
Thanks for a great script. 

I have one question. I am trying to implement 2 swipers on my page. The first one works great but when i try copy the same code for my second swiper it wont work.

The 2 swipers should look the same so i use the same css.

So the html for the slider is the same.

This is my jquery code:

var mySwiper = new Swiper('.swiper-container', {pagination:'.pagination-sd'}, {
        speed: 750,
        mode: 'horizontal'
    })

Here is my code: http://m.vasabladet.fi/new/jm/

How can i accomplish this?

**Comment by juliandagaang** [comment]
Hi. I'm using swiper in my angular app. Is there any way I can ngRepeat a swiper instance itself and should display multiple swiper instances? For example, different pictures of fruits under their respective kinds. One instance is pictures of apples, etc.
