### ISSUE TITLE
swiper not found 

### ISSUE THREAD

**Issue by aymanouch** [nolimits4web/swiper#5001]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/nolimits4web/swiper/issues/new?assignees=&labels=React&template=swiper_react_issue.yml

### Bug description

the css folder and swiper components is not founded in swiper and swiper/react pls 

### Swiper version

7.0.0

### Platform/Target and Browser Versions

ubuntu linux firefox 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by soplanstudio** [comment]
https://codesandbox.io/s/friendly-bassi-jfbmj?file=/src/App.js

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
