### ISSUE TITLE
SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export. 

### ISSUE THREAD

**Issue by 2401345934** [nolimits4web/swiper#5002]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://lzomedia.com/blog/error-using-swiperjs-react-the-requested-module-react-is-expected-to-be-of-type-commonjs/

### Bug description

正常引入开发使用  有的人可以运行项目  但是有的人不行    项目运行报错
![image](https://user-images.githubusercontent.com/52618511/134807496-d8d2dacf-cee5-4785-9d25-331b787907dd.png)
请指点

### Swiper version

7.0.2

### Platform/Target and Browser Versions

windows  

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
