### ISSUE TITLE
"Rewind" option

### ISSUE THREAD

**Issue by putnik-projects** [nolimits4web/swiper#5003]
### Clear and concise description of the problem

I want to suggest a new way to loop slider, not with "loop" option. This way is rewind to the first/last slide when it's at the start/end. It would be nice, if swiper had such option. Some examples on other sliders:
- https://glidejs.com/docs/options/#rewind
- https://ganlanyuan.github.io/tiny-slider/demo/#rewind_wrapper

### Suggested solution

I think this should a check in file which defines that it is time to change the slide. And if this is the last slide, go to first slide, if the first slide, go to the last slide, else go to necessary slide.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by jaro-io** [comment]
would be so nice to have this!
