### ISSUE TITLE
Component import error

### ISSUE THREAD

**Issue by lexa18** [nolimits4web/swiper#5004]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/wild-forest-llxqg

### Bug description

Component import error.
In a working project, when I try to import, I get a message.
"SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'react';
const { useEffect, useLayoutEffect } = pkg;"

### Swiper version

7.0.5

### Platform/Target and Browser Versions

windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
