### ISSUE TITLE
renderBullet has unexpected behaviour when using slidesPerView: auto & direction: 'vertical'

### ISSUE THREAD

**Issue by kevinmu17** [nolimits4web/swiper#5012]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-vertical-forked-qwupt?file=/index.html

### Bug description

It seems the renderBullet function is called with every slide change and loops over the slides. Sometimes it's adding an additional index, so i get an 'undefined' bullet. When setting the slidesPerView to 1 it is working as expected but the styling is totally broken with way to slides being way to high. 

So to summarize with some numbers:
5 Slides should render 5 bullets. 
renderBullets returns 6. When sliding it returns sometimes 5, sometimes 6. When trying to add some if statements where renderBullet should return null, it is literally returning 'null' as content into the div of the swiper pagination.

ps: the reproduction link shows nothing at all...

### Expected Behavior

When having 5 slides, it should render only 5 bullets.

### Actual Behavior

It renders sometimes 6, sometimes 5, so inconsistent behaviour is going on.

### Swiper version

7.0.6

### Platform/Target and Browser Versions

macOS 11.5.2 | Chrome 93.0.4577.82

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The demo you have posted doesn't represent the issue. Please update the demo to the one where we can see the issue

**Comment by kevinmu17** [comment]
@nolimits4web just updated the sandbox, now it's reproduced. had to wrap my head around it to get this done.

**Comment by nolimits4web** [comment]
It is because you use autoHeight which is NOT supported with vertical direction. In this case container height changes which along with `slidesPerView: 'auto'` leads to recalculation of snap points which produces different amount of pagination bullets

**Comment by kevinmu17** [comment]
> It is because you use autoHeight which is NOT supported with vertical direction.
Ah, please place this in the docs :) 

Why is it recalculating the pagination? if i have 5 slides it should show 5 bullets, no need to recalculate if you ask me. Or am i missing something here?

Should the function renderBullet render nothing when returning false/null? This way we can at least hack a little bit around this issue like:
```js
renderBullet: function (index, className) {
    if (index !== undefined) {
        return '<div class="' + className + '">' + names[index] + '</div>';
    }
    return false
},
```
