### ISSUE TITLE
Swiper wrapper does not fit on container in Safari

### ISSUE THREAD

**Issue by islamozbek** [nolimits4web/swiper#5022]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-cube-forked-hikko?file=/index.html

### Bug description

Hi all,

Thanks for great plugin.
I'm not sure it is bug from swiperjs or css. I create a button in to the swipe-slide tag and want to be it position top: 0, left: 0. I see this button on the top. But can not click. Because container of button seems another place as you can see on Inspect. I guess the problem because of transform-origin but don't know how can i fix. Also The problem has on both of Macos Safari, IOS Safari. Chrome is working fine.

You can see simple example on codesandbox.

Thanks a lot.

### Swiper version

7.0.6

### Platform/Target and Browser Versions

macOS Safari 15.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is Safari bug with transform-origin, not really related to Swiper

**Comment by kvmsc** [comment]
Hey, Is there any workaround for this issue? 
This issue is not just with Safari, it is happening on iOS Chrome too.

**Comment by bilalmalkoc** [comment]
@kvmsc did you find any solution?
