### ISSUE TITLE
Slider not working inside Swiper Slide

### ISSUE THREAD

**Issue by denny7** [nolimits4web/swiper#5023]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-react-forked-p92mu

### Bug description

Slider events didn't fire inside Swiper Slide. I tried to wrap Slider inside div and call `event.stopPropagation()` and `event.preventDefault()` on click event but nothing works.

### Expected Behavior

Swiper slide not interrupts children events.

### Actual Behavior

Slider's events never fired.

### Swiper version

7.0.7

### Platform/Target and Browser Versions

macOs, Chrome 93.0.4577.82 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Add `swiper-no-swiping` class to the Slider
- https://codesandbox.io/s/swiper-default-react-forked-zklcl?file=/src/App.jsx
- https://swiperjs.com/swiper-api#param-noSwiping

**Comment by denny7** [comment]
Thanks for quick response!
