### ISSUE TITLE
Speed of reversed autoplaying slides increases drastically and slides are not visible when visiting and coming back from another browser tab or resizing

### ISSUE THREAD

**Issue by emin-alizada** [nolimits4web/swiper#5029]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-forked-vm47b?file=/index.html

### Bug description

Reversed directionned autoplay bug on tab change or change of width of tab, when the animation is linear. Whenever you change tab width or change browser tab the slider changes its positon so no slide is visible. There was a similar issue, but the fix there doesn't solve the problem

### Expected Behavior

Slider continues from the place before changing tab width and tab switch

### Swiper version

6.5.2 (code sand box uses latest still no fix)

### Platform/Target and Browser Versions

Windows Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate https://github.com/nolimits4web/swiper/issues/4995 ?

**Comment by emin-alizada** [comment]
That solution doesn't really work, and by default waitForTransition is true, so that does not help. Yes it is same issue but completed more completed. Btw, I didn't add angular label, it's actually problem in core. I tried to find the solution, but couldn't

**Comment by rogoja** [comment]
This problem is also relevant to me.  When autoplay reaches the end, it starts accelerating

**Comment by gormonn** [comment]
haha, I think it's true
if autoplay is done through a virtual swipe event, then such a bug will be the expected behavior, provided that old versions of event-emitter's are not destroyed during resize

**Comment by michaelscimeca** [comment]
Did you ever figure out a solution? Here is example of the issue. https://codesandbox.io/s/swiper-autoplay-forked-iife8v?file=/index.html

**Comment by pjaws** [comment]
This is not limited to changing tabs/resizing the window as demonstrated in the [issue I opened](https://github.com/nolimits4web/swiper/issues/6027) (somehow missed the current issue in my search, sorry!) .

**Comment by mungemach** [comment]
Got the same problem. (in normal web version not angular or any other framework). 
Swiper also starts drastically speeding up until it finished once when the scrollbar gets hidden as well as resizing the window

**Comment by pjaws** [comment]
I was able to work around this issue by disabling `autoplay.pauseOnMouseEnter`. Hopefully this works/is an option for others!

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
