### ISSUE TITLE
Progress event jumps to final value when release

### ISSUE THREAD

**Issue by christosnc** [nolimits4web/swiper#5032]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-forked-cds8u

### Bug description

When attaching a progress event to swiper, you get a smooth progress value as you hold and drag the slider. As soon as you release (and the animation to move to the nearest slide begins) the progress event gives only the final value of the animation.

This becomes really obvious when you use this progress value for something and you see this "jump" when you release.

Just look at the reproduction example and look at the console to see what I'm talking about..

### Expected Behavior

The progress event should also respect the transition animation between slides when you release your finger / mouse instead of jumping to the end-value.

### Swiper version

7.0.7

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
No, it shouldn't. Progress is attached to position/transform, and due to how CSS transitions work, we don't and won't calculate these values
