### ISSUE TITLE
Swiper Zoom function doesn't work well with portrait sized images

### ISSUE THREAD

**Issue by NickdeK** [nolimits4web/swiper#5035]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-zoom-react-forked-swjpg?file=/src/App.jsx

### Bug description

Swiper with Zoom doesn't work well with portrait sized images.

1. On the first slide with a portrait sized image double click to zoom
2. Pan the image up and down multiple times
3. Panning up and down don't work like expected

### Expected Behavior

While zoomed in you should be able to pan the image completely just like with landscape images.

### Actual Behavior

While zoomed in the up and down panning don't work like expected. See following video for a more info: https://d.pr/v/YIJSG8

### Swiper version

7.0.7

### Platform/Target and Browser Versions

macOS, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Would be great to have more clear description of "doesn't work well", what is exactly doesn't work, in your demo I can pan zoomed image up and down, what doesn't work? Some video would probably help

**Comment by NickdeK** [comment]
@nolimits4web Ah right, good point! I've updated my post with this link: https://d.pr/v/YIJSG8 (I can't upload it in this ticket because the video is too big).

**Comment by nolimits4web** [comment]
I don't experience same issue, but panning horizontally doesn't work here because when it is zoomed it is still narrower than swiper container, to avoid it, you can increase the zoom multiplier

**Comment by NickdeK** [comment]
Hmm I get what you are saying. We are experiencing this same issue on mobile in landscape format as well. I think if you don't start with a perfect vertical move, while the picture is not covering the whole screen, the swiper is starting the slide prev/next action and preventing the panning action.

Increasing the zoom multiplier can not always be a solution in cases where a lot of different aspect ratio's are in play. I've tried disabling the prev/next actions when zoomed in, but I can't get that to work. Do you perhaps have a idea on how we could solve this?

**Comment by nolimits4web** [comment]
You can disable swiping when zoom like this:
```js
swiper.on('zoomChange', (_,scale) => {
  if (scale > 1) {
    swiper.allowSlideNext = false;
    swiper.allowSlidePrev = false;
  } else {
    swiper.allowSlideNext = true;
    swiper.allowSlidePrev = true;
  }
})
```

**Comment by nolimits4web** [comment]
Once again, if zoomed imaged is narrower than viewport there will not be any horizontal panning

**Comment by NickdeK** [comment]
I don't want horizontal panning but vertical panning in this case that works, even if you don't make a perfect vertical pointer move. I can reproduce this issue on Chrome (on a Mac) and on a iPhone 13 Pro in landscape. This doesn't seem to be just a user error.

https://user-images.githubusercontent.com/6631170/136024123-87927225-f6bf-4467-8f6f-b9e4706c709f.mp4

https://user-images.githubusercontent.com/6631170/136024609-6cad9530-46ed-46ee-8f56-0ededceacde7.mp4
