### ISSUE TITLE
Next / Prev buttons doesnt enable on first or last item in the slide list

### ISSUE THREAD

**Issue by mikebhart** [nolimits4web/swiper#5036]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://amarula.organic.dev/product/test-limited-edition/

### Bug description

Hi there, Im having a little trouble with this slider.  

The next button doesnt enable on the last slide although its there so i cant move into screen (swiping works).  Same with the previous button on the first slide.

on example link go to bear bottom EXPLORE MORE OUR RANGE

### Swiper version

6.7

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by MikeyJN** [comment]
It's not a bug, you simply need to add **loop: true** in the initializer options:

Example below taken from [https://swiperjs.com/get-started](url)

`const swiper = new Swiper('.swiper', {
  // Optional parameters
  direction: 'vertical',
  loop: true,

  // If we need pagination
  pagination: {
    el: '.swiper-pagination',
  },

  // Navigation arrows
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },

  // And if we need scrollbar
  scrollbar: {
    el: '.swiper-scrollbar',
  },
});`
