### ISSUE TITLE
Can't enable the multirow slider using grid parameters

### ISSUE THREAD

**Issue by vannyle** [nolimits4web/swiper#5037]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-grid-react-forked-ec0pu?file=/src/App.jsx

### Bug description

Hi there! I am trying to enable the multirow slider using [grid](https://swiperjs.com/swiper-api#grid) parameters, but it doesn't work. 

### Expected Behavior

It should work like in the demos https://swiperjs.com/demos#slides-grid.

### Swiper version

7.0.0

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You need to install Grid module in same way as pagination

**Comment by satishkvesteinn** [comment]
I get the same issue.

**Comment by RashidBik** [comment]
I tryed this one but it didn't work for me may some one say what  the problem can be?

**Comment by mgdotjs** [comment]
> @quinhatpy it worked for me.
> 
> ```js
> // import Swiper core and required modules
> import { Navigation, Pagination, Scrollbar, A11y, Grid } from 'swiper';
> 
> import { Swiper, SwiperSlide } from 'swiper/react';
> 
> // Import Swiper styles
> import 'swiper/css';
> import 'swiper/css/navigation';
> import 'swiper/css/pagination';
> import 'swiper/css/scrollbar';
> import 'swiper/css/grid';
> 
> export default () => {
>   return (
>     <Swiper
>       // install Swiper modules
>       modules={[Navigation, Pagination, Scrollbar, A11y, Grid]}
>       spaceBetween={50}
>       slidesPerView={2}
>       navigation
>       pagination={{ clickable: true }}
>       grid = {{
>         rows: 2,
>       }}
>       scrollbar={{ draggable: true }}
>       onSwiper={(swiper) => console.log(swiper)}
>       onSlideChange={() => console.log('slide change')}
>     >
>       <SwiperSlide>Slide 1</SwiperSlide>
>       <SwiperSlide>Slide 2</SwiperSlide>
>       <SwiperSlide>Slide 3</SwiperSlide>
>       <SwiperSlide>Slide 4</SwiperSlide>
>       ...
>     </Swiper>
>   );
> };
> ```

**You must add fill:"row" into the grid.**
grid = {{
  fill: "row",
  rows: 2,
}}
