### ISSUE TITLE
Lazy Loading Parameter 

### ISSUE THREAD

**Issue by Pixelous** [nolimits4web/swiper#5041]
### Clear and concise description of the problem

Currently Lazy Loading Parameter **checkInView: true** Enables to check is the Swiper in view before lazy loading images on initial slides

### Suggested solution

Option to check how many pixels before in view before lazy loading images on initial slides.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 doesn't lazy module anymore. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
