### ISSUE TITLE
Not working with Vue3?

### ISSUE THREAD

**Issue by WadeShuler** [nolimits4web/swiper#5047]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

null

### Bug description

I have a freshly created Vue3 app by using the Vue CLI, and I get the following error after following the docs:

```bash
 ERROR  Failed to compile with 2 errors                                                                                                          12:38:38 PM

These dependencies were not found:

* swiper/css in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/Carousel.vue?vue&type=script&lang=js
* swiper/vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/Carousel.vue?vue&type=script&lang=js

To install them, you can run: npm install --save swiper/css swiper/vue
```

I was initially using Nuxt when I ran into this, then realized Nuxt still uses Vue v2.. bummer.  So I created a new Vue3 app through their CLI to test, and it just doesn't seem to work. I have tried multiple ways/options... I just can't get it to work!

It looks like your demos use Vite for Vue, which doesn't represent an out of the box Vue 3 application. Is there something that is missing or required for us to choose/install/setup on a Vue3 CLI generated app?

I haven't tried to setup Vite, but I assume it works since your demos do. It must have, or configure, something differently than we get with a stock Vue3 or Nuxt setup?

If this is the case, then the Swiper docs are misleading. The docs should specify what/how to install (and pre-requisites) based on a stock/default Vue3 installation. Your installation is for Vite, not a stock Vue 3, there seems to be a difference out of the box. FWIW, it seems the CLI is the preferred way to install Vue3, so the docs should probably be compatible with that as a baseline, or delve deeper.

Thank you.

### Swiper version

7.0.8

### Platform/Target and Browser Versions

Web

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
