### ISSUE TITLE
If even slight mouse movement is detected, click events on slides do not register due to swiper.allowClick

### ISSUE THREAD

**Issue by brodenbrett** [nolimits4web/swiper#5048]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/broden/pen/gOmNdgP

### Bug description

When clicking on a slide, if the mouse is moved even slightly, `onTouchMove()` is triggered and `swiper.allowTouchMove` is set to false.  The slide will not change and the click will not be registered. 

I found this most noticeable on thumbnail carousels, where you have to click slides to trigger a change on the main slideshow.  Try and navigate between different thumbnails quickly and you'll find about 1/3 of your clicks don't register because of your mouse movement.  This is even noticeable on the official swiper docs demo: https://codesandbox.io/s/gbtvt

### Expected Behavior

When clicking the thumbnail, the click event should register even if slight mouse movement is detected.  Maybe there could be some sort of threshold?  Or an additional check if the user is actually dragging/swiping?

### Actual Behavior

When clicking the thumbnail, if the mouse is moved slightly the click fails.

### Swiper version

7.0.8

### Platform/Target and Browser Versions

macOS Chrome 94.0.4606.71

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is a `threshold` parameter to tweak this behaviour https://swiperjs.com/swiper-api#param-threshold
