### ISSUE TITLE
Resistance effect disabled when there's a single slide

### ISSUE THREAD

**Issue by msantana-dev** [nolimits4web/swiper#5051]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/santanamaick/pen/abwgzaa

### Bug description

The 'rubber band' effect isn't enabled when there's only one .swiper-slide
and there's no way to enable it.
This makes for inconsistent behavior between single-slide and multi-slide Swiper instances.

I've never faced this issue with Swiper 6.

### Expected Behavior

I expected the rubber band effect to be present when there's only one slide.
The way it works right now frustrastes user expectations.

### Swiper version

7.0.8

### Platform/Target and Browser Versions

Latest Chrome and Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Set `watchOverflow: false`
