### ISSUE TITLE
Event Emitter type is wrong

### ISSUE THREAD

**Issue by zie-rts** [nolimits4web/swiper#5053]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

(Angular templates are not type-safe in codesandbox)

### Bug description

The core package has a SwiperEvents interface that defines callback functions for all possible events. The callback functions receive the Swiper reference as argument (and additional arguments in some cases).

```
// Swiper Events (Core)
slideChange: (swiper: Swiper) => void;
```

The Angular Swiper Component events are event emitters that use the SwiperEvents interface for the generic type. 
```
// Swiper Component (Angular)
s_slideChange: EventEmitter<SwiperEvents['slideChange']>;
```
The event emitter type is wrong. The event emitter replaces the callback function.
The current type results in an event emitter that emits a callback function instead of emitting the swiper reference directly.

### Expected Behavior

The events should receive the swiper reference:

```html
<!-- ./demo.component.html -->
<swiper (slideChange)="demo($event)"></swiper>
```
```ts
// ./demo.component.ts
export class DemoComponent {
  demo(swiper: Swiper) {}
}
```

### Actual Behavior

The expected behavior works when running in the browser - we receive the swiper reference - but there is a TypeScript error because the type of the event emitter is wrong. With the current type our event handler method would receive a callback function that expects the swiper ref instead.

```html
<!-- ./demo.component.html -->
<swiper (slideChange)="demo($event)"></swiper
```
```ts
// ./demo.component.ts
export class DemoComponent {
  demo(callback: (swiper: Swiper) => void) {
    // No TS error anymore
    // But a callback function would not make sense
    // and we actually receive the swiper reference directly and not a callback function
  }
}
```

Current workaround is to use `$any` in the template:
```html
<!-- ./demo.component.html -->
<swiper (slideChange)="demo($any($event))"></swiper
```
```ts
// ./demo.component.ts
export class DemoComponent {
  demo(swiper: Swiper) {}
}
```

### Swiper version

7.0.5

### Platform/Target and Browser Versions

macOS 11.5.2 / Brave 1.30.86 / TypeScript 4.3.5 / Angular 12.1.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
Hey, thanks for reporting this, and sorry for the delay.
It was actually a huge bug and will need a major release :)

New API will be:
```html
    <swiper (beforeTransitionStart)="testEvent($event)"></swiper>
```

```ts
  testEvent(event: Parameters<SwiperEvents['beforeTransitionStart']>) {
    const [swiper, speed, internal] = event;
    console.log({ swiper, speed, internal });
  }
```

**Comment by haishengXie0712** [comment]
when is the release planned? @vltansky

**Comment by vltansky** [comment]
released in `v8`
