### ISSUE TITLE
Next JS swiper giving Must use import to load ES Module error

### ISSUE THREAD

**Issue by jonrrivera** [nolimits4web/swiper#5056]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://nextjs.org/

### Bug description

this happens when I try t recreate this example:
https://codesandbox.io/s/wij5y?file=/src/App.jsx:473-942 

<img width="1018" alt="Screen Shot 2021-10-05 at 2 14 13 PM" src="https://user-images.githubusercontent.com/18686388/136104053-ef9a3bb7-bf2f-4fad-bae9-a654851f3b4c.png">

### Swiper version

"swiper": "^7.0.0"

### Platform/Target and Browser Versions

chtome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by jonrrivera** [comment]
it's an easy fix, just update to the latest next.js version and enable module support.

https://nextjs.org/blog/next-11-1

**Comment by kodermax** [comment]
I have the same problem on the latest version of Nextjs (12.0.7)
https://stackblitz.com/edit/github-a252xz

![image](https://user-images.githubusercontent.com/590985/144815940-f71cd143-0397-4db5-a61b-495635f5eca5.png)

**Comment by sohammondal** [comment]
Same issue 

![image](https://user-images.githubusercontent.com/34343502/149566697-4e3e31d5-a862-49b5-ac8f-24cfe76dfab0.png)

**Comment by isuke01** [comment]
Same error with NUXT and Swiper `7.4.1` so I think it is common issue now.

**Comment by jamalsoueidan** [comment]
Same problem here? We actually upgraded to latest nextjs, we thought this would fix the problem, but it didn't!

**Comment by jamalsoueidan** [comment]
> it's an easy fix, just update to the latest next.js version and enable module support.
> 
> https://nextjs.org/blog/next-11-1

Does not work, so don't waste your time, even if you enable module support, this is what you get instead.

error - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\...\node_modules\swiper\swiper.esm.js
require() of ES modules is not supported.
require() of C:\...\node_modules\swiper\swiper.esm.js from C:\...\.next\server\pages\products\[...params].js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename swiper.esm.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\...\node_modules\swiper\package.json.

**Comment by RomaSto** [comment]
I get the same error, and there is no require() in my code or swiper.js library, it`s very confusing 

> > it's an easy fix, just update to the latest next.js version and enable module support.
> > https://nextjs.org/blog/next-11-1
> 
> Does not work, so don't waste your time, even if you enable module support, this is what you get instead.
> 
> error - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:...\node_modules\swiper\swiper.esm.js require() of ES modules is not supported. require() of C:...\node_modules\swiper\swiper.esm.js from C:....next\server\pages\products[...params].js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename swiper.esm.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:...\node_modules\swiper\package.json.

I get the same error, and there is no require() in my code or swiper.js library, it`s very confusing

**Comment by jorcelinojunior** [comment]
I get the same error here.

**Comment by Muhammad-Bilal-7896** [comment]
But development team can you please look at it that how can we use it in Next JS I need to use that.

**Comment by kodermax** [comment]
I get the same error when I use custom server like fatsify / express. If you try use native nextjs without custom server, it will works.

**Comment by Muhammad-Bilal-7896** [comment]
but I am also using native Next JS and I am not using custom server.

**Comment by Muhammad-Bilal-7896** [comment]
> I get the same error when I use custom server like fatsify / express. If you try use native nextjs without custom server, it will works.

But its not working with native Next JS as well

**Comment by jamalsoueidan** [comment]
I did new test, on brand new project with nextjs, and swiper, and it works! guys please do so before doing it in your existing project.

**Comment by Muhammad-Bilal-7896** [comment]
Thanks, I'll check it out.

**Comment by Naes0** [comment]
Same problem the only way to fix was to downgrade to 6.X.X

**Comment by codyng** [comment]
don't close this thread because the problem is not fixed

**Comment by Muhammad-Bilal-7896** [comment]
Yes definately.

**Comment by httpiga** [comment]
> I did new test, on brand new project with nextjs, and swiper, and it works! guys please do so before doing it in your existing project.

@jamalsoueidan  would you mind sharing it?

**Comment by Naes0** [comment]
I managed to resolve this issue. 

I updated to Next JS 12 and enabled the experimental.esmExternals: 'loose', [experimental feature](https://nextjs.org/docs/messages/import-esm-externals) in the next.config.js

you will probably have to adjust the import statements to match the correct swiper version. I'm on 8.0.5 now so:

`import { SwiperSlide } from 'swiper/react';` 

This is an experimental feature so I'm unsure of the side effects.

**Comment by jamalsoueidan** [comment]
> > I did new test, on brand new project with nextjs, and swiper, and it works! guys please do so before doing it in your existing project.
> 
> @jamalsoueidan would you mind sharing it?

[swiperjs.zip](https://github.com/nolimits4web/swiper/files/8060695/swiperjs.zip)

**Comment by jamalsoueidan** [comment]
> esmExternals

I tried this didn't work :(

**Comment by Naes0** [comment]
> I tried this didn't work :(

Yep. so I just realised on Next.js 12 ES modules are supported by default, so this is unnecessary.

**Comment by aq-atompoint** [comment]
> Has anyone found a solution.Because still I am unable to use swiper.js in Next JS.

+1

**Comment by aq2630** [comment]
same problem bro. @Muhammad-Bilal-7896

**Comment by eno-tech0** [comment]
Will there be a solution in the near future?

**Comment by ryanfigueiredo** [comment]
i'm the same problem with version swiper >= 8.0
i fix making the downgrade from version 6.8.4, but i have the new problem, becase my slides is not centered in div, solved 50% of problem seting width to 420px, but this not resolved my problem per completed, because in mobile devices the width property is dynamic and the new problem in production: Error: Cannot find module 'swiper/swiper-react.cjs'

**Comment by benistary** [comment]
Same problem with:
- react-id-swiper ^4.0.0
- swiper >= 8.0
- next 12.1.0

**Comment by jamalsoueidan** [comment]
https://splidejs.com/ I used this one 👍

**Comment by irsyadadl** [comment]
Hey @jamalsoueidan, thank you and fuck you!

**Comment by duandzgp** [comment]
This issue needs to be opened again cause it happens every time we bundle our app to `cjs` (vue, react ...).

**Comment by duannx** [comment]
IMO this can only be fixed in the place where we use this package. We have to make CommonJS build for this package.
In my case using Vite as the build tool, adding this package to `ssr.noExternal` to force Vite to make CommonJS build for it.
```
// vite.config.js
...
ssr: {
    noExternal: ["swiper"]
 }
```

**Comment by droidada** [comment]
I still have the same issue

**Comment by awacode21** [comment]
Also an Issue with Vue when using SSR.

```
require() of ES Module /opt/build/repo/node_modules/swiper/swiper.esm.js from /opt/build/repo/dist/server/entry-server.js not supported.
12:29:01 AM: Instead change the require of swiper.esm.js in /opt/build/repo/dist/server/entry-server.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by S4nicBiz** [comment]
Swiper 7 and 8 requires NextJS 12, while Swiper 6 works on NextJS 11, so just match the version of NextJS and Swiper accordingly.

**Comment by koskokos2** [comment]
> Swiper 7 and 8 requires NextJS 12, while Swiper 6 works on NextJS 11, so just match the version of NextJS and Swiper accordingly.

Using Swiper 9 and Next.js 12 and facing the problem. It might caused by me using custom server with Next.js but not sure, tried many things but was not able to make it work.

**Comment by samturrell** [comment]
On nuxt this can be fixed by adding

```
build: {
    transpile: [/swiper/],
},
```

to your nuxt config

**Comment by ingdaeho** [comment]
```
> Build error occurred
Error: Build optimization failed: found page without a React Component as default export in 
```
I solved this error, I move component to "components" folder not "pages" in nextjs directory and used `next/dynamic` to import.

- swiper ^8.2.4
- next 11.1.4

**Comment by Muhammad-Bilal-7896** [comment]
Can you please share a code example.So it will be helpful for others.Not
full example but a piece of lines of code.Thanks.

**Comment by andrespaucar** [comment]
Hi, create component no ssr 😉
![image](https://user-images.githubusercontent.com/35370608/176053752-07c4646a-3b80-4eed-8bad-15d5109c5420.png)
and use in Swiper 😎
![image](https://user-images.githubusercontent.com/35370608/176053720-d43b5887-d6dd-4072-b38b-001fcb1bfa71.png)

**Comment by Muhammad-Bilal-7896** [comment]
Awesome, thanks!

**Comment by Elhilali-hA** [comment]
change require to import:

export.modules  required("module-name");
to :
export.modules  import("module-name");

**Comment by andrespaucar** [comment]
Update Swiper to its latest version, to its latest version now if it can be put without problems in Nextjs 😎

**Comment by monsieurnebo** [comment]
Hi @nolimits4web n

I'm facing the same issue with:
- `next` **v12.2.3**
- `swiper` **v8.3.2**

I see that [you specify](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) the following:
> **I'm having problems with ESM and Next.js**
> You must enable the [experimental support for ESM](https://nextjs.org/blog/next-11-1#es-modules-support).

**The experimental support for ESM is enabled by default in Next v12, so it should work.**

What is happening? Could you give us some infos about this? It seems to impact a lot of people using Swiper.

Best regards,

**Comment by deangibson89** [comment]
I don't understand why this is considered the "best" swiper if they don't even support ES Modules in 2022.
