### ISSUE TITLE
Swiper isn't draggable on the spaces between slides

### ISSUE THREAD

**Issue by dangelion** [nolimits4web/swiper#5057]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/150-freemode/core.html

### Bug description

Swiper with free mode isn't draggable dragging the spaces between slides (from the slides going outside viewport). Here a screen capture that shows well the issue:

https://user-images.githubusercontent.com/4182418/136181026-39ef7ba5-51bc-4c55-8e99-19af646d4b95.mp4

and also on your demo:

https://swiperjs.com/demos/150-freemode/core.html

### Swiper version

7.0.8

### Platform/Target and Browser Versions

macOS Chrome 94.0.4606.61

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4942
