### ISSUE TITLE
Inability to change effect when using Thumbs

### ISSUE THREAD

**Issue by devcustrom** [nolimits4web/swiper#5063]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/devcustrom/pen/jOwgxrO?editors=0010

### Bug description

When destroying two swipers that are linked by the Thumbs module, they cannot be initialized again

### Expected Behavior

When destroying two swipers that are linked by the Thumbs module, they can be initialized

### Actual Behavior

When destroying two swipers that are linked by the Thumbs module, they cannot be initialized again

### Swiper version

from 6.4.1 to 7.0..8

### Platform/Target and Browser Versions

Windows 10 Chrome 94

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by EngHell** [comment]
@devcustrom did you manage to find a fix for this issue? I'm experiencing the same thing

**Comment by devcustrom** [comment]
>  @devcustrom did you manage to find a fix for this issue? I'm experiencing the same thing

No
