### ISSUE TITLE
renderExternal and renderSlide method is not working for virtual slides config

### ISSUE THREAD

**Issue by sushan05** [nolimits4web/swiper#5080]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/swiper-angular-virtual-tcrrbc?file=src/app/app.component.ts

### Bug description

I am trying to render virtual slides with config for virtual as mentioned below and expecting `renderExternal` method to receive call. However, that not happening and hence I could not update my `virtualSlides` data.

```
virtual: {
      slides: this.slides,
      addSlidesBefore: 0,
      addSlidesAfter: -1,
      renderExternalUpdate: true,
      renderExternal: (data) => {
        console.log('checking external slides data ', data);
        this.virtualSlides = data.slides;
      },
      renderSlide: (slide, index) => {
        console.log('checking render slide data ', slide, index);
      },
    }
```

### Expected Behavior

`renderExternal` method to receive call and data.

### Swiper version

7.0.8

### Platform/Target and Browser Versions

Windows / Google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
renderExternal and renderSlide are only for Core version, in Angular it should be done in Angular-way, like in this example
