### ISSUE TITLE
Toggling pagination input doesn't work properly

### ISSUE THREAD

**Issue by ItaiEsquare** [nolimits4web/swiper#5089]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-pagination-angular-forked-xos4i?file=/src/app/app.component.ts

### Bug description

Pagination input doesn't show/hide pagination according to value.

### Expected Behavior

Show pagination whenever input changes to true

### Actual Behavior

When initial value is true, pagination is rendered as expected. When it changes to false, it disappears as expected. from that point, pagination is not always when when toggled to true.
When the initial value is false, the pagination is never shown when input changes to true...

### Swiper version

7.0.8

### Platform/Target and Browser Versions

macOS chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
Thanks for reporting!
