### ISSUE TITLE
iOS Safari 15 resize issue that is not your problem but may need a work around (workaround included)

### ISSUE THREAD

**Issue by bobmagicii** [nolimits4web/swiper#5091]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://twitter.com/bobmagicii/status/1448768770432983043
https://streamable.com/xqq8me

### Bug description

in iOS15, when the address/toolbar "animates" in and out of view by your finger scrolling up and down, this pummels the web app with window viewport resize notifications. Which then pummels the slider with them while you're trying to slide. The result is that if you don't slide perfectly left and right, you will cause the animated toolbar on safari to be stupid, and it will spam the hell out of those resize events. This makes this slider (and anything using touch events) spazzy as hell to use in iOS 15, as the resize events seem to interrupt, cancel, and then restart touch move events. this was **not** a problem in iOS 14.

Additionally in iOS 15, you can tap the [Aa] on the address bar and say "hide toolbar" which stops the animated crap, and also stops the slider from freaking out. Turning it back on then the crap behaviour continues.

In our app I worked around this by hacking the un-minified version of your compiled script to just flat out disable the listening for window resize events, as we have no cases where we care about window resize events. Interestingly enough this did not seem to break the responsiveness breakpoints as I sit here and resize the window, so as far as i am considered, problem solved for today.

![image](https://user-images.githubusercontent.com/881944/137402891-50cfc674-17f3-4b31-986d-bf3b2785ca6a.png)

This prevents the spazzy behaviour caused by iOS 15 safari's animated toolbar crap because you can't catch the events any more. If Apple does not address this soon, perhaps we need an init option for Swiper to work around it, wrapping those resize events with something like, if swiper.params.resizeWindowListen, or something.

### Swiper version

6.5 and 7.0.8

### Platform/Target and Browser Versions

iOS 15 Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by Bumpyshot** [comment]
Hey,
Thank you for noticing this issue, i was looking for someone in my case ! Your workaround is not working on my side... I also notice that the pagination is not working, but it's related I guess...

**Comment by bobmagicii** [comment]
hey there, i attached the copy of the library i hacked that is working on our projects. it is the "ESM" "AIO" version of Swiper downloaded from his Getting Started CDN meaning you have to be doing things like

```js
<script type="module">
import Swiper from "/some/web/path/swiper.js";

let Swinst = new Swiper({ ... });
</script>
```

Only edits are with two lines commented out. 

[swiper.txt](https://github.com/nolimits4web/swiper/files/7369428/swiper.txt)

**Comment by n0ch4t** [comment]
If you remove the resizing event, there is no problem with the slide, but if you use the centralized slide as true,
There is a problem that the center cannot be aligned when changing directions.

**Comment by websuits** [comment]
This issue still persists, scrolling on browser that resize will re-init the slider.
