### ISSUE TITLE
Direction Vertical issues in Svelte and Sveltekit

### ISSUE THREAD

**Issue by belafonte** [nolimits4web/Swiper#5109]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/belafonte/sveltekit-swiper-issue

### Bug description

in Svelte Demos: Setting direction to vertical results in slides not shown correctly ( 4rd on )

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/2737673/137874109-8eeadede-5830-4d02-8276-b1e5c1253c06.png">

Setting direction to vertical in SvelteKit results in wrong calculation of height.

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/2737673/137873769-f4e4f265-6158-420d-8be2-aed2df99ef32.png">

Steps to reproduce:

npm init svelte@next swiper-issue
cd swiper-issue
npm i swiper

add to index.html

```
<script>
	// Import Swiper Svelte components
	import { Swiper, SwiperSlide } from 'swiper/svelte';

	// Import Swiper styles
	import 'swiper/css';
</script>

<Swiper
	spaceBetween={50}
	slidesPerView={3}
    direction="vertical"
	on:slideChange={() => console.log('slide change')}
	on:swiper={(e) => console.log(e.detail[0])}>
	<SwiperSlide>Slide 1</SwiperSlide>
	<SwiperSlide>Slide 2</SwiperSlide>
	<SwiperSlide>Slide 3</SwiperSlide>
	<SwiperSlide>Slide 4</SwiperSlide>
	...
</Swiper>
```

or clone repository

then:

npm run dev 

### Swiper version

7.0.9

### Platform/Target and Browser Versions

macOS, Safari, Chrome, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by w3rafu** [comment]
I run into a similar problem with Sveltekit. When I set direction "vertical", it starts flickering and reloading. 
Adding height fixes this, however, as I didn't want a fixed sized, I set to height null, and autoHeight to true, and fixes the problem. 

According to documentation, "Setting this parameter(height) will make Swiper not responsive".  Perhaps would like to know more about this.
