### ISSUE TITLE
Add onAutoplayPause event

### ISSUE THREAD

**Issue by mystrdat** [nolimits4web/swiper#5112]
### Clear and concise description of the problem

I have a custom UI set up around the Autoplay feature. I need to know when Autoplay pauses due to `pauseOnMouseEnter` option, but currently Swiper doesn't trigger any events indicating as such. (It could also report Autoplay progress, but that's a separate issue)

### Suggested solution

Add a trigger for an `autoplayPause` event

### Alternative

Manually listening for `mouseenter` events on the Swiper container would work, but is hacky and open to implementation issues, it doesn't mirror the actual pause state of autoplay

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by m-dpositiv** [comment]
There appears to be no simple pause() and resume()? Regardless of autoplay or any other options, that would cover most cases.

**Comment by oneclickwebstudio** [comment]
Unfortunately `autoplayPause` not firing. any ideas why?

```
swiper.on('autoplayPause', () => {
      console.log('paused');
});
```

**Comment by mystrdat** [comment]
> Unfortunately `autoplayPause` not firing. any ideas why?
> 
> ```
> swiper.on('autoplayPause', () => {
>       console.log('paused');
> });
> ```

I believe this is still not implemented, this issue was opened to request support for such an event.

**Comment by mystrdat** [comment]
> Unfortunately `autoplayPause` not firing. any ideas why?
> 
> ```
> swiper.on('autoplayPause', () => {
>       console.log('paused');
> });
> ```

Did you enable `pauseOnMouseEnter`?

**Comment by oneclickwebstudio** [comment]
> pauseOnMouseEnter

Thanks for your reply. Yes, I've enabled it

```
config: SwiperOptions = {
    grabCursor: true,
    autoplay: {
      pauseOnMouseEnter: true,
      disableOnInteraction: false,
      delay: 5000
    },
    navigation: {
      enabled: true,
      nextEl: '.stories-slider-button-next',
      prevEl: '.stories-slider-button-prev'
    },
    pagination: {
      enabled: true,
      el: '.stories-slider-pagination',
      renderBullet: (i, className) => {
        return `<div class="${ className } "><span></span></div>`;
      },
      bulletClass: 'stories-slider-pagination-bullet',
      bulletActiveClass: 'active'
    },
  }; 
```
