### ISSUE TITLE
Grid module doesn't work

### ISSUE THREAD

**Issue by d3ntastic** [nolimits4web/Swiper#5116]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-grid-react-forked-p9sfn

### Bug description

Grid module is not working. I took the link from the Swiper demo page and added the module and the CSS, still broken. Also doesn't work in the other versions (Svelte and Vue). Core looks fine. In my own project it also doesn't work.

### Expected Behavior

Grid works like in the swiper core. You can set rows and there is no useless whitespace.

### Actual Behavior

There is a lot of whitespace and the slider doesn't work as expected anymore (not all slider elements are there, pagination changes but no new slides etc.)

### Swiper version

7.0.9

### Platform/Target and Browser Versions

Latest Chrome and Firefox on Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by LinhNguyen1059** [comment]
> In your code sandbox you don't install Grid module

Yes, just add the line `SwiperCore.use([Grid]);` after the import SwiperCore
