### ISSUE TITLE
Incorrect loop behavior using slidesPerView, slidesPerGroup

### ISSUE THREAD

**Issue by quangtho2910** [nolimits4web/swiper#5144]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/nguyen-quang-tho/pen/GRvvWdj

### Bug description

Incorrect loop behavior using slidesPerView, slidesPerGroup when clicking on previous arrow.

### Expected Behavior

Next and Previous arrow should loop the slides continuously
The problem happens only when the number of items cannot be divided by the "slidesPerGroup" / "slidesPerView" and "loop" is set as true.

### Actual Behavior

Clicking on Previous arrow reveals the bug => Could not move to the second page.

### Swiper version

7.2.0

### Platform/Target and Browser Versions

Windows 10, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by AlexProtsak** [comment]
I have the same issue with version 7.2.0

**Comment by MananTank** [comment]
We are also facing the same issue and until this is resolved, we are forced to not use Swiper in our sites.
Any updates on this? @nolimits4web ?

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
