### ISSUE TITLE
Swiper React: adding slides when navigating won't move thumbnails

### ISSUE THREAD

**Issue by robin-pon** [nolimits4web/swiper#5145]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-thumbs-gallery-react-forked-sx18t?file=/src/App.jsx

### Bug description

See [https://codesandbox.io/s/swiper-thumbs-gallery-react-forked-sx18t?file=/src/App.jsx](https://codesandbox.io/s/swiper-thumbs-gallery-react-forked-sx18t?file=/src/App.jsx)

The thumbnails won't slide when you click on the navigation next arrow when we are adding a custom function to `onSlideNextTransitionStart`.

When you select the 2nd thumbnail image, you can click the navigation next arrow. This triggers the function and adds a new slide like expected. We also move one slide to the right like it should go.

This behavior should also happen when the most left thumbnail is selected. A new image should be added to the slides and the thumbnails should move forward.

### Expected Behavior

When clicking on the navigation next arrow, a new slide is added and the thumbnail overview scrolls to the right.

### Actual Behavior

When clicking on the navigation next arrow, a new slide is added **but** the thumbnail overview won't move. This is only the case when the slide most to the left is selected.

### Swiper version

7.2.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by m4olivei** [comment]
Curious if you made any progress on a work around / fix for this? I'd also like to do something very similar. I'm wondering if you need a call to `updateSlides` (https://swiperjs.com/swiper-api#method-swiper-updateSlides) at some point?
