### ISSUE TITLE
React Slides Grid does not work.

### ISSUE THREAD

**Issue by ivanjeremic** [nolimits4web/swiper#5157]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/lz16q

### Bug description

Slides Grid does not work in React the official CodeSandbox is broken too, I can't find what exactly the problem is but the Core demo in CodeSandbox is working fine, but React is broken, even it is the same as Core.

### Expected Behavior

Working Slides Grid in React

### Actual Behavior

https://codesandbox.io/s/lz16q

### Swiper version

7.2.0

### Platform/Target and Browser Versions

All Browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
```
import "swiper/css/grid";
```
