### ISSUE TITLE
Swiper repeatedly resizes narrower and narrower if in a scrolling container with a scrollbar which takes space, in Firefox

### ISSUE THREAD

**Issue by tremby** [nolimits4web/swiper#5162]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/tremby/pen/ExvQbLa

### Bug description

I have a swiper in a scrollable container which has a variable width depending on the viewport width.

In Firefox, if it's displaying a scrollbar, and it's a scrollbar which takes space rather than a floating one like you get on some OSes by default these days, the swiper resizes itself smaller and smaller until it's just the width of the scrollbar itself.

- If I fix the width of the swiper I no longer see this behaviour.
- If I enable floating scrollbars (such as by switching on responsive design mode in Firefox with control-shift-M) I no longer see this behaviour.
- I don't see this issue in Chromium, at least within Codepen.

### Expected Behavior

The swiper has a stable width.

### Actual Behavior

The swiper shrinks repeatedly until it's too narrow to use.

### Swiper version

7.2.0

### Platform/Target and Browser Versions

Firefox 93 (I'm running Linux)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Not a Swiper bug, it is mostly how CSS works, you can also try to disable `resizeObserver` parameter
