### ISSUE TITLE
Swiper with Fade and Vertical options produces Swiper Slides with large heights

### ISSUE THREAD

**Issue by bewards** [nolimits4web/swiper#5171]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-fade-forked-mk9up?file=/index.html

### Bug description

- Swiper component with effect type fade, direction type vertical, and autoHeight flag set to true produces slides that go beyond their naturally desired height.
- The more slides you add, the more the height increases on the swiper-wrapper and swiper-slide(s)

### Expected Behavior

- Expecting the swiper-slide height to be the natural height of the slide, which is 600px maximum.

### Actual Behavior

- content directly below the slider (h2 tag) is pushed down past the page due to the large height set on the swiper component

### Swiper version

latest

### Platform/Target and Browser Versions

windows Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by alejandro** [comment]
Getting the same behavior, out of the box.

**Comment by bewards** [comment]
Wrapping the component initialization on `DOMReady` doesn't help.

**Comment by nolimits4web** [comment]
autoHeight only compatible with `horizontal` direction

**Comment by bewards** [comment]
This doesn't work with `autoHeight` disabled either.
