### ISSUE TITLE
I can't disable the keyboard from code

### ISSUE THREAD

**Issue by hkashlan** [nolimits4web/swiper#5176]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-keyboard-control-angular-forked-9kcop

### Bug description

I can't disable enable the keyboard from code, 
it always take the init value only,

this init to true: so the keyboard always enabled even if I unchecked the checkbox
https://codesandbox.io/s/swiper-keyboard-control-angular-forked-9kcop

this init to false: so the keyboard always disabled even if I checked the checkbox
https://codesandbox.io/s/swiper-keyboard-control-angular-forked-43zej?

### Expected Behavior

to control the keyboard enabled/disabled from code, through the keyboard input or the config.keybaord

### Swiper version

7.2.0

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use Swiper instance keyboard methods to disable/enable it after init https://swiperjs.com/swiper-api#method-swiper-keyboard-disable

**Comment by hkashlan** [comment]
@nolimits4web 
It is working thank you,
but I think other angular developer may end with same issue I had.

for Angular developer it is better to control the component from config/properties rather than calling methods


Thank you again
