### ISSUE TITLE
Dependency not found for swiper/vue

### ISSUE THREAD

**Issue by kyoa** [nolimits4web/swiper#5178]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/vue-3-ts-swiper-forked-l8p7h

### Bug description

I do this as the doc on official website.
https://swiperjs.com/vue

`import { Swiper, SwiperSlide } from "swiper/vue";`

It gives me this error:
`This dependency was not found:

* swiper/vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/test/index.vue?vue&type=script&lang=js

To install it, you can run: npm install --save swiper/vue`

### Swiper version

7.2.0

### Platform/Target and Browser Versions

Vue 3.0+js+compositionAPI & Chrome 95.0.4638.69

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
👉 https://github.com/nolimits4web/swiper/issues/4871
