### ISSUE TITLE
Flickering in iOS/iPhone Safari

### ISSUE THREAD

**Issue by AdrianFahrbach** [nolimits4web/swiper#5180]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://1337camp.adrianfahrbach.com/de

### Bug description

The swiper slides flicker on iOS/iPhone Safari when sliding from one slide to another. This only happens on mobile Safari and I assume that it only effects devices with the new iOS 15 Safari layout (but couldn't confirm this yet). We work quite a lot with swiper and didn't notice this issue before iOS 15.

I think it is related to the iOS navigation bar and the associated change of viewport height.
When scrolling sideways you also scroll up and down a little bit which triggers the navigation bar transition and therefore a change in the viewport height.

You can reproduce this issue with an iPhone on iOS 15 on [this site](https://1337camp.adrianfahrbach.com/de).
Try swiping sideways and up and down on the same time and you will see the flickering. It's especially visible when the navigation bar is present like [this](https://user-images.githubusercontent.com/45072099/141167879-2a538c16-930f-4619-980c-7c76f1ceac56.PNG).
In addition to that there is no flickering when the navigation bar is hidden (like [this](https://user-images.githubusercontent.com/45072099/141168057-c266d51a-2c5a-4bfa-93d0-c9aac1cd371e.PNG)) and you intentionally swipe up while sliding sideways (so that the navigation bar doesn't appear).

This issue could be related to #3527 but the suggested solutions from that issue didn't work for me.

### Swiper version

6.8.4

### Platform/Target and Browser Versions

Mobile Safari 15.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate  #3527
