### ISSUE TITLE
Get the current dragged slide

### ISSUE THREAD

**Issue by aminta** [nolimits4web/swiper#5188]
### Clear and concise description of the problem

We need a method to detect the current dragged / swiped slide. For example it is essential for creating transitions like a slide width that decreases while you're dragging it. If we can't detect the current dragged / swiped slide we can't determine the slide to which apply the desired effect... `transformEl` option is not enough because the effect is applied to the element or to the slide and not on both.

### Suggested solution

I have no hint.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
And what is wrong with pointer/mouse events?

**Comment by aminta** [comment]
> And what is wrong with pointer/mouse events?

They are not useful to detect the current dragged slide, but maybe I'm wrong...
