### ISSUE TITLE
Add option(type) "auto" to parameter "loop"

### ISSUE THREAD

**Issue by Daijobou** [nolimits4web/swiper#5195]
### Clear and concise description of the problem

https://swiperjs.com/swiper-api#param-loop 
> Because of nature of how the loop mode works, it will add duplicated slides.

The option should offer the possibility to activate with the setting "auto" only if there are enough slides. In my case, never should several identical slides appear in view. I would assume that no one wants this. Its look false. If there are not enough slides, then there should be no loop with new setting "auto".

### Suggested solution

There is already a detection for this. Next-button is disabled with this classes
> swiper-button-next swiper-button-disabled swiper-button-lock

if there are not enough slides. In this case parameter loop should reset to "false".

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
