### ISSUE TITLE
Sliding from margin fails from 3rd slide on

### ISSUE THREAD

**Issue by michelcouto** [nolimits4web/swiper#5201]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#slides-per-view

### Bug description

By using the slides per view demo, we can reproduce the issue.
It happens when we have some space between the slides, which is the case there.

So, in order to reproduce the bug, try to slide the view by clicking in the space between the slides (grey region).
If you do that between the slides 1 and 2, or between slides 2 and 3, it works just fine.
But doing that from slides 3 and 4 on, sliding won't work.

### Expected Behavior

The slide would happen no matter where you start it.

### Actual Behavior

The slide does not occur when sliding starts in the space between the slides from the 3rd slide on.

### Swiper version

7.0.0

### Platform/Target and Browser Versions

Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Set [`touchEventsTarget`](https://swiperjs.com/swiper-api#param-touchEventsTarget) to `'container'`
