### ISSUE TITLE
Thumbs gallery loop

### ISSUE THREAD

**Issue by kamal772** [nolimits4web/swiper#5210]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/2xoqw?file=/package.json:359-364

## Thumbs gallery loop in vue
when navigating slides ,  active thumb slide element  is not matching main gallery active slide when navigating slides 
after I go deeply on issue I found out that .. thumbs slides elements not getting active and in active styles despite of its class list contain it , when I try to remove and add mentioned classes again on slide change … it have no effect on these elements as if its not in the Dom

### Expected Behavior

active thumb slide element must match main gallery active slide when navigating next or previous slides 

### Actual Behavior

**Thumbs gallery loop in vue  when navigating slides -  active thumb slide is not matching main gallery active slide element**

### Swiper version

7.0.0

### Platform/Target and Browser Versions

chrome 95.0.4638.69

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by 849189490** [comment]
me too

**Comment by 849189490** [comment]
you can add thumbs both two swiper

**Comment by ADZG** [comment]
me too.Initialization cannot be selected,

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
