### ISSUE TITLE
If you use it with Create React App (or similar env without ES modules support), there is a workaround that might help https://swiperjs.com/react#usage-with-create-react-app

### ISSUE THREAD

**Issue by kyoa** [nolimits4web/swiper#5215]
If you use it with Create React App (or similar env without ES modules support), there is a workaround that might help https://swiperjs.com/react#usage-with-create-react-app

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/4871#issuecomment-952738818_
The problem is I am using ESM and 'import' now and doing what the doc said, it still gives me this error, I'm not sure how to solve this, could you please help me with this?

**Comment by nolimits4web** [comment]
#4871
