### ISSUE TITLE
Swiper vertical css class error

### ISSUE THREAD

**Issue by GabrieleCicconetti** [nolimits4web/swiper#5216]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://ms3.ms3dev.it/

### Bug description

Swiper direction vertical sets the swiper class to `.swiper-verical` not `.swiper-vertical`

### Swiper version

7.3.0

### Platform/Target and Browser Versions

macOS chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
`verical` is what you passed to params on your side
