### ISSUE TITLE
Unable to use with create-react-app

### ISSUE THREAD

**Issue by fvilar** [nolimits4web/swiper#5220]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/react#usage-with-create-react-app

### Bug description

I got #4871 error and following the instructions with create react-app-related in [here](https://swiperjs.com/react#usage-with-create-react-app) got a new error.
```
./node_modules/swiper/swiper.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./node_modules/swiper/swiper.scss)
Cannot find module 'sass'
Require stack:
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\sass-loader\dist\utils.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\sass-loader\dist\index.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\sass-loader\dist\cjs.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\webpack\lib\NormalModule.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\webpack\lib\Compiler.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\webpack\lib\webpack.js
- C:\Users\Kevin\Desktop\Restaurante\client\node_modules\react-scripts\scripts\start.js
```

### Swiper version

7.0.0

### Platform/Target and Browser Versions

Windows, Brave

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is guide in #4871
