### ISSUE TITLE
Continue to rotate and don’t want to re-clock

### ISSUE THREAD

**Issue by minlovehua** [nolimits4web/swiper#5222]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://worktile.com/

### Bug description

The mouse moves in to stop the carousel, and the mouse moves out to continue the carousel. It is hoped that the stay time of continuing the carousel will not be re-timed, but will stay for the remaining time.

### Swiper version

4.5.1

### Platform/Target and Browser Versions

macOS Big Sur 11.6 version

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> ## Swiper version

> 4.5.1

This version is not maintained anymore
