### ISSUE TITLE
Swiper cause next.js can't revalidate.

### ISSUE THREAD

**Issue by hoangvu12** [nolimits4web/swiper#5227]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

I don't know if it possible to reproduce the bug in codesandbox...

### Bug description

So in Swiper v7, it uses ESM Module. Next.js v12 also support it, everything is okay. But when it try to regenerate pages. It cause this error.

![image](https://user-images.githubusercontent.com/68330291/143384465-bf83e490-5410-42d8-b70b-1c2f29a5aa68.png)

### Expected Behavior

Next.js should regenerate pages.

### Actual Behavior

Next.js can't regenerate pages --> It return the cached pages instead.

### Swiper version

7.0.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by moshfrid** [comment]
Ive been experiencing this as well.

**Comment by emilpriver** [comment]
Have the exakt same issue

**Comment by hoangvu12** [comment]
> Ive been experiencing this as well.



> Have the exakt same issue

I fixed this issue by downgrade Swiper to v6.
Here is it's docs: https://swiper6.vercel.app/swiper-api#events

Note: v6's API is kinda different from v7, so be sure to check that out.

**Comment by emilpriverrc** [comment]
@hoangvu12 Do you have problem with revalidation using Swiper 6.7.5 aswell? Or did you fix this by "the old ordinary" way and using 

```
const swiper = new Swiper('.swiper-container', {
  // ...
});
```

I use 6.75 and get this error:
`Error: Cannot find module '../../core'`

**Comment by hoangvu12** [comment]
> @hoangvu12 Do you have problem with revalidation using Swiper 6.7.5 aswell? Or did you fix this by "the old ordinary" way and using
> 
> ```js
> const swiper = new Swiper('.swiper-container', {
>   // ...
> });
> ```
> 
> I use 6.75 and get this error: `Error: Cannot find module '../../core'`

No I used React component and it worked fine.

**Comment by emilpriverrc** [comment]
Hi @hoangvu12 How do you host your setup? Vercel? What Next version do you have? :D

**Comment by hoangvu12** [comment]
> Hi @hoangvu12 How do you host your setup? Vercel? What Next version do you have? :D 
 
I'm hosting on Vercel, Next v12.

**Comment by emilpriverrc** [comment]
What Node version? Sorry if I ask a lot haha.

**Comment by hoangvu12** [comment]
> What Node version? Sorry if I ask a lot haha.

It's v16.13

**Comment by emilpriverrc** [comment]
Ok, So I added a .node-version with 14.17.0 in it which looked like it fixed it.
I now have next 12.0.2 and Swiper 7.4.1

**Comment by moshfrid** [comment]
Bump
