### ISSUE TITLE
Space between not honored when there is not enough space in the container

### ISSUE THREAD

**Issue by Mikilll94** [nolimits4web/swiper#5234]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-fade-forked-0lm7l?file=/index.html

### Bug description

I have set `spaceBetween: 100` but as you see in the CodeSandbox, it is not working.

<img width="685" alt="Screenshot 2021-11-26 at 18 48 05" src="https://user-images.githubusercontent.com/17653648/143616912-8cb74ab0-a4d0-4ba5-8519-2abe03b2a20d.png">

The space between images is definitely less than 100px. I know that there is not enough room in the container but IMO it should clip left and right image to honor the spacing.

### Expected Behavior

`spaceBetween` should be honored. Left and right image should be clipped.

### Actual Behavior

Images are always displayed entirely. Thus `spaceBetween` parameter is not honored.

### Swiper version

7.3.1

### Platform/Target and Browser Versions

macOS Chrome 96.0.4664.55

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
1. transitions and transforms on slides are not permitted, this leads to wrong sizes calculation
2. if you need fixed slide size (e.g. 200px), then `slidesPerView: 'auto'` must be used, otherwise image is narrower than slide

https://codesandbox.io/s/swiper-effect-fade-forked-w6idn?file=/index.html
