### ISSUE TITLE
Issue while switching between multiple navigation tabs

### ISSUE THREAD

**Issue by ashwinikumar01** [nolimits4web/swiper#5235]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/angular-ivy-tdxwgm?file=src%2Fapp%2Fapp.component.ts
https://angular-ivy-tdxwgm.stackblitz.io/

### Bug description

The above stackblitz code doesn't work fine and while clicking on navigation tabs the data is not getting refreshed and the data remains same in all tabs.

As I am using 3 navigation tabs in my application, so as soon as the application gets loaded the cards get shrinked automatically and soon as I start navigating between the tabs the cards get starting more shrinker and and even it doesn't initiate the swiper properly.

### Expected Behavior

Kindly suggest the changes in the above stackblitz code, so that the code works fine in the production environment.

### Swiper version

6.7.5

### Platform/Target and Browser Versions

Chrome, Mozilla Firefox, Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
Hi, take a look here:
https://stackblitz.com/edit/angular-ivy-yry3jk?file=src%2Fapp%2Fapp.component.ts

use `ChangeDetectorRef` or put data with `this.data1 = someVal` instead of `this.data1.push()`.
read https://javascript.tutorialink.com/update-view-when-object-has-been-pushed-into-array-in-angular/

**Comment by ashwinikumar01** [comment]
@vltansky I would like to reopen this issue as the code is still breaking in the stackblitz you shared.
[https://angular-ivy-yry3jk.stackblitz.io/](https://angular-ivy-yry3jk.stackblitz.io/). Kindly open this link and take a look which is generated via yours stackblitz one.

Here are the attached screenshots for your reference -
<img width="960" height="350" alt="image" src="https://user-images.githubusercontent.com/69667369/143974612-37c673fb-9e17-4a61-b4e9-99ed5994bf89.png">
<img width="960" height="350" alt="image" src="https://user-images.githubusercontent.com/69667369/143974717-c7be1e4a-42bd-40f6-bc67-f4a866f73b8c.png">
<img width="960" height="350" alt="image" src="https://user-images.githubusercontent.com/69667369/143974769-569500a2-2602-4d35-94e9-5a8b60fd4752.png">

**Comment by ashwinikumar01** [comment]
@vltansky And not only this, apart from this as soon as I start switching between the multiple tabs or constantly click on single tab, the Swiper Carousel keeps on breaking.
Kindly reopen the issue and have a look into it.

**Comment by vltansky** [comment]
Looks like it switching Swipers parent element from flex fixes the issue:
```html
<div class="row align-items-center">
  <swiper [config]="productList2">
```

to 
```html
<div>
  <swiper [config]="productList2">
```

https://stackblitz.com/edit/angular-ivy-6ukuwt?file=src%2Fapp%2Fapp.component.html

**Comment by ashwinikumar01** [comment]
@vltansky Nopes, still not working. Swiper is still breaking.
My only doubt is that if we update the swiper on nav tabs click, then there would be a chance to solve this.

**Comment by vltansky** [comment]
It works just fine for me.
Sure you checked the new stackblitz link?
stackblitz.com/edit/angular-ivy-6ukuwt?file=src%2Fapp%2Fapp.component.html

**Comment by ashwinikumar01** [comment]
> It works just fine for me. Sure you checked the new stackblitz link? [stackblitz.com/edit/angular-ivy-6ukuwt?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-ivy-6ukuwt?file=src%2Fapp%2Fapp.component.html)

I would suggest to view it in full screen mode. [https://angular-ivy-6ukuwt.stackblitz.io/](https://angular-ivy-6ukuwt.stackblitz.io/). This is the final link generated by yours stackblitz.

**Comment by vltansky** [comment]
ah, I see the problem with the rest 2 tabs. But I focus on the first tab issue with the resize (shrinking).

**Comment by ashwinikumar01** [comment]
> ah, I see the problem with the rest 2 tabs. But I focus on the first tab issue with the resize (shrinking).

Yes, right. I think they are not getting updated.

**Comment by vltansky** [comment]
The thing is that swiper in tab2 and tab3 rendered when tabs are hidden. So it cants calculate its width. As an example adding `*ngIf` on swiper `<swiper [config]="productList2" *ngIf="activeTab === 2">` will solve it.
I'm sure that should be some smarter ways to not reinit the slider each time. Maybe some kind of `initSlider: {tab1:true, tab2: false}` and then switching `tab2` to true when tab2 first time active.

**Comment by ashwinikumar01** [comment]
> The thing is that swiper in tab2 and tab3 initialized when tabs are hidden. So it cants calculate its width. As an example adding `*ngIf` on swiper `<swiper [config]="productList2" *ngIf="activeTab === 2">` will solve it. I'm sure that should be some smarter ways to not reinit the slider each time. Maybe some kind of `initSlider: {tab1:true, tab2: false}` and then switching `tab2` to true when tab2 first time active.

According to me, this thing should be get mentioned in Swiper Angular Docs so as not create any further issues while handling Swiper with tabs.

**Comment by vltansky** [comment]
Happy we found the solution for your issue.
You are very welcomed to open PR to docs if you want - that would help a lot.
https://github.com/nolimits4web/swiper-website

**Comment by vltansky** [comment]
Apparently, there is [observeParents](https://swiperjs.com/swiper-api#param-observeParents) parameter that can solve this without `*ngIf`. Thanks, @nolimits4web for pointing out

**Comment by ashwinikumar01** [comment]
> Apparently, there is [observeParents](https://swiperjs.com/swiper-api#param-observeParents) parameter that can solve this without `*ngIf`. Thanks, @nolimits4web for pointing out

Thanks for informing @vltansky
