### ISSUE TITLE
Thumbs gallery loop

### ISSUE THREAD

**Issue by artpaponov** [nolimits4web/swiper#5243]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-thumbs-gallery-loop-forked-qz7nm

### Bug description

If you set "slidesPerView" / 2 less than total slides then when next or previous slides incorrect index. 

### Swiper version

7.3.1

### Platform/Target and Browser Versions

Windows 10, Chrome 96, FireFox 95

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
