### ISSUE TITLE
TypeError : Cannot read properties of undefined (reading 'autoplay')

### ISSUE THREAD

**Issue by muneebrana414** [nolimits4web/swiper#5244]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

its personal

### Bug description

![Screenshot 2021-11-30 200022](https://user-images.githubusercontent.com/36512513/144071490-b0db3d19-5436-4559-a08c-dbfb7545212d.jpg)

### Swiper version

7.3.1

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by muneebrana414** [comment]
Here I, apply swiper


import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import SwiperCore, { Autoplay } from 'swiper'
SwiperCore.use([ Autoplay ]);

export default function SideSwipe(){
    return(
        <div>
            <Swiper slidesPerView={5} centeredSlides={false} slidesPerGroup={1} spaceBetween={1} loop={true} direction={'vertical'} 
            // autoplay={true} autoplay={{
            //     'delay':2000,
            //     'disableOnInteraction': false
            // }} 
            className="mySwiper mt-2" style={{height:700}}>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
                <SwiperSlide><img src='./img/logo' /></SwiperSlide>
            </Swiper>
        </div>
    );
}

**Comment by muneebrana414** [comment]
@nolimits4web i post my code

**Comment by hackftz** [comment]
i got the same problem, so why close this problem, or give me some advice to handle it?

**Comment by nickycdk** [comment]
@muneebrana414 @hackftz @nolimits4web - Did any of you ever find a solution to this? I'm experiencing the same, primarily when the component is unmounted

**Comment by krystiangryczon** [comment]
In my case I had this line of code:
```js
SwiperCore.use([Controller, Autoplay]);
```

and later in code used swiper like this:
```js       
         <Swiper
          autoHeight
          onSwiper={setSwiper}
          controller={{ control: swiper }}
          onActiveIndexChange={(s) => setActiveIndex(s.activeIndex)}
          modules={[EffectFade, Autoplay]}
          effect="fade"
          autoplay={{
            delay: 5000,
            disableOnInteraction: false,
          }}
        >
```

once I deleted Autoplay from modules inside the Swiper tag - it doesn't error anymore
