### ISSUE TITLE
Reduce footprint of swiper library as dom7 and ssr-window libraries are pulled as dependencies

### ISSUE THREAD

**Issue by tejasdamre** [nolimits4web/swiper#5247]
### Clear and concise description of the problem

I had updated swiper to 6.8 version. There are other things added that increased the footprint of the library.

The old version had a smaller **dist** directory that contained everything needed. Now it even pulled in **dom7** and **ssr-window** as dependencies.

Also, some extra features were added to support other libraries such as vue.js.

### Suggested solution

Instead of a heavy footprint, we can actually do something to reduce the footprint of a library.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
Hey, we recently discussed with @nolimits4web the possibility to split the library to `@swiper/core` ,`@swiper/react`,`@swiper/vue`,`@swiper/angular`, `@swiper/svelte` and even thought about doing this in upcoming swiper major release (v8) caused of the angular breaking changes.

But as v7 was a big release that introduced a lot of breaking changes released only a few months ago it would be a bit annoying to break things again for those who import frameworks components. So better to split it in v9 release with more changes.  

I'm pretty sure that `ssr-window` and `dom7` are necessary dependencies of swiper.
@nolimits4web any ideas / would you want to add something?

**Comment by nolimits4web** [comment]
ssr-window and dom7 was always there, but before they just were integrated into Swiper itself, so they won't be removed. Other frameworks features are only on their own versions and don't add anything to the Core version. If you want less Swiper size - use only modules you need and not the bundle version.
