### ISSUE TITLE
Active pagination bullet in dynamic mode not centered.

### ISSUE THREAD

**Issue by kamilmedrala** [nolimits4web/swiper#5250]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://swiperjs.com/demos/040-pagination-dynamic/core.html

### Bug description

To reproduce type in console: 

> swiper.destroy(1,1);
swiper = new Swiper('.swiper', {
		speed: 300,
	  	slidesPerView: 2,
	  	spaceBetween: 20,
	  	loop: true,
		pagination: {
			el: '.swiper-pagination',
			clickable: true,
			dynamicBullets: true,
			dynamicMainBullets: 3,
		},
	  	breakpoints: {
			576: {
				slidesPerView: 3,
			},
			922: {
				slidesPerView: 4,
			},
	  	}
	});

Active pagination bullet is only in the center when value of dynamicMainBullets is 1.

### Expected Behavior

Would look much better if the active pagination bullet was always in the middle.

### Actual Behavior

Active pagination bullet is not centered.

### Swiper version

7.3.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by kakhelishvili** [comment]
having same issue:(

**Comment by nolimits4web** [comment]
should be fixes with https://github.com/nolimits4web/swiper/commit/3d377c2a23e6267f6e106ca58ca7f3b09ed62fc9

**Comment by Gutfreund** [comment]
Still not working on my slider. Where can I add the changes?

**Comment by bricebou** [comment]
While it works perfectly when on horizontal mode, the problem seems to persist on vertical mode.

Any idea why ?
