### ISSUE TITLE
Flickering issue on android with swiper

### ISSUE THREAD

**Issue by VISHWATEJA-G** [nolimits4web/swiper#5251]
https://user-images.githubusercontent.com/94345292/144246213-5433c18a-c6f2-4fe3-b0e3-24c9641b090a.mp4

### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/wiwd6?file=/src/app/app.component.ts

### Bug description

When I am using swiper component [effect]="'cards'", the overall screen starts flickering when swiping the cards on only android device.
When there are more than 20 cards, then only its starts to flicker other wise it works fine.

### Expected Behavior

When we add 'n' number of cards, it should not flicker.

### Actual Behavior

Flickering after adding more than 20 cards.

### Swiper version

7.0.6

### Platform/Target and Browser Versions

Android

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
try with https://swiperjs.com/swiper-api#param-maxBackfaceHiddenSlides

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
