### ISSUE TITLE
CDN does not work ??

### ISSUE THREAD

**Issue by skater2014** [nolimits4web/swiper#5255]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://kaztokyo.sakura.ne.jp/gallary/

### Bug description

**it does not work for slider  for JS CDN**

<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

 **function.php not readable for js**

//ファイルをキューに登録する関数

add_action('wp_enqueue_scripts', 'dess_theme_imports');

function dess_theme_imports(){

/*Home page and Gallary page for stylesheet and scripts*/

  //wp_enqueue_style( 'google-lato-font', 'https://fonts.googleapis.com/css?family=Lato:300,400,500,700,900' );

//Gallay Page for Slider
  //wp_enqueue_style( 'swiper-style', get_template_directory_uri().'/css/swiper-bundle.css' );
  //wp_enqueue_style( 'slick-theme', get_template_directory_uri() . '/css/slick-theme.css' );

//home page slick navi
  wp_enqueue_style( 'slicknav', get_template_directory_uri().'/css/slicknav.min.css' );

//home page slick slider
  wp_enqueue_style( 'slick-slider', get_template_directory_uri().'/css/slick.css' );

//wordpress 用の　jquery wp-include にある　※基本は、Jquery version 新しく追加しない。
  wp_enqueue_script( 'jquery' );

//gallary page for swiper slider
  //wp_enqueue_script( 'swiper-slider', get_template_directory_uri() . '/js/swiper-bundle.min.js' );

//home page for slick nav responsive nabi menu
  wp_enqueue_script( 'slicknav', get_template_directory_uri() . '/js/jquery.slicknav.min.js' );

//hoem page for Slider 
  wp_enqueue_script( 'slick-slider', get_template_directory_uri() . '/js/slick.min.js' );

//hoem page for  フィルタリングやソート機能、グリッドレイアウトプラグイン
  wp_enqueue_script( 'isotpe', get_template_directory_uri() . '/js/isotope.pkgd.min.js' );

//hoem page for 要素からはみ出したテキストを省略してくれるjQueryプラグイン
  wp_enqueue_script( 'dotdot', get_template_directory_uri() . '/js/jquery.dotdotdot.min.js' );

//hoem page for imagesLoadedを使って画像の読み込みタイミングを管理
  wp_enqueue_script( 'imagesloaded', get_template_directory_uri() . '/js/imagesloaded.pkgd.min.js' );

//hoem page for js below
  wp_enqueue_script( 'js-script', get_template_directory_uri() . '/js/scripts.js' );

//header page 
  //wp_enqueue_script( 'test-js', get_template_directory_uri() . '/js/test.js' );

}

**I tryed to read code below does not read at all** 

	</footer>
		<?php wp_footer(); ?>

	
		
		
		
		
        

	</body>
</html>

### Expected Behavior

//Javascripts
function themebs_enqueue_scripts() {
    wp_enqueue_script( 'bootstrap_min', get_template_directory_uri() . '/js/bootstrap.min.js', array( 'jquery' ) );
}

add_action( 'wp_enqueue_scripts', 'themebs_enqueue_scripts');

//add_action( 'wp_enqueue_scripts', 'themebs_javascript_enqueue_scripts');

//ファイルをキューに登録する関数

add_action('wp_enqueue_scripts', 'dess_theme_imports');

function dess_theme_imports(){

/*Home page and Gallary page for stylesheet and scripts*/

  //wp_enqueue_style( 'google-lato-font', 'https://fonts.googleapis.com/css?family=Lato:300,400,500,700,900' );

//Gallay Page for Slider
  //wp_enqueue_style( 'swiper-style', get_template_directory_uri().'/css/swiper-bundle.css' );
  //wp_enqueue_style( 'slick-theme', get_template_directory_uri() . '/css/slick-theme.css' );

//home page slick navi
  wp_enqueue_style( 'slicknav', get_template_directory_uri().'/css/slicknav.min.css' );

//home page slick slider
  wp_enqueue_style( 'slick-slider', get_template_directory_uri().'/css/slick.css' );

//wordpress 用の　jquery wp-include にある　※基本は、Jquery version 新しく追加しない。
  wp_enqueue_script( 'jquery' );

//gallary page for swiper slider
  //wp_enqueue_script( 'swiper-slider', get_template_directory_uri() . '/js/swiper-bundle.min.js' );

//home page for slick nav responsive nabi menu
  wp_enqueue_script( 'slicknav', get_template_directory_uri() . '/js/jquery.slicknav.min.js' );

//hoem page for Slider 
  wp_enqueue_script( 'slick-slider', get_template_directory_uri() . '/js/slick.min.js' );

//hoem page for  フィルタリングやソート機能、グリッドレイアウトプラグイン
  wp_enqueue_script( 'isotpe', get_template_directory_uri() . '/js/isotope.pkgd.min.js' );

//hoem page for 要素からはみ出したテキストを省略してくれるjQueryプラグイン
  wp_enqueue_script( 'dotdot', get_template_directory_uri() . '/js/jquery.dotdotdot.min.js' );

//hoem page for imagesLoadedを使って画像の読み込みタイミングを管理
  wp_enqueue_script( 'imagesloaded', get_template_directory_uri() . '/js/imagesloaded.pkgd.min.js' );

//hoem page for js below
  wp_enqueue_script( 'js-script', get_template_directory_uri() . '/js/scripts.js' );

//header page 
  //wp_enqueue_script( 'test-js', get_template_directory_uri() . '/js/test.js' );

}

can not read Swiper js at all

### Actual Behavior

wp_head(); ?> 
  
 
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>

    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

</head>

  <body <?php body_class(); ?>>

      <header id="head">

### Swiper version

Swiper 7.3.1

### Platform/Target and Browser Versions

macOS, Windows, Cordova, iOS, Android, Chrome, etc.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
