### ISSUE TITLE
vue3 ts swiper module component props, Type 'true' cannot be assigned to type 'undefined'

### ISSUE THREAD

**Issue by lxfxy** [nolimits4web/swiper#5265]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/friendly-chihiro-nqj9n

### Bug description

```vue
<script setup lang="less">
import { Swiper, SwiperSlide } from "swiper/vue";
import { FreeMode, Scrollbar } from "swiper";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/scrollbar";
</script>

<template>
<Swiper
    :modules="[FreeMode, Scrollbar]"
    freeMode
    scrollbar
>
     // ......
</Swiper>
</template>
```
![code](https://user-images.githubusercontent.com/56082897/144600996-696dbe89-1d8d-4af6-b382-5711a9c1046d.png)

![code-err-msg](https://user-images.githubusercontent.com/56082897/144601179-91e7b870-d794-40f6-a547-b52678cd29bb.png)

### Expected Behavior

`There are some effects. Errors are not reported during development, but errors are reported during build`

![code-err-msg2](https://user-images.githubusercontent.com/56082897/144606230-c6a7fe65-b2c9-4c3d-9da3-89f1b36a8d0c.png)

### Swiper version

7.3.1

### Platform/Target and Browser Versions

chrome  96.0.4664.45

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by zynth17** [comment]
also got the same issues, seems like this happen because the default value of the prop is undefined where as the proptype is ```xxOptions | boolean```
