### ISSUE TITLE
Swiper Angular loop mode cannot be turned off

### ISSUE THREAD

**Issue by pfei5** [nolimits4web/swiper#5269]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/pfei5/angular-swiper-loop-bug

### Bug description

Say I initialize Swiper for Angular with multiple slides and 'loop' mode turned on.
If I then reduce the number of slides to 1, swiper will continue to loop 3 slides that are identical, the one expected slide and the 2 duplicate slides on either end.

### Expected Behavior

I expect swiper to remove duplicate slides when I reduce the number of slides to 1 and set the SwiperComponent's 'loop' property to 'false'.

### Actual Behavior

Swiper loops 3 identical slides instead of resting on the single provided slide.

### Swiper version

7.3.1

### Platform/Target and Browser Versions

macOS 11.5.2 Chrome 96

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
This is not Angular related issue.
Also seems to me this is the way it should work. @nolimits4web thoughts?

**Comment by pfei5** [comment]
@vltansky I disagree. Reducing the number of slides to 1 and turning off loop mode should not loop 3 identical slides, IMHO.

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
