### ISSUE TITLE
Previous navigation not properly working

### ISSUE THREAD

**Issue by AnkitHinglajia** [nolimits4web/swiper#5274]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-loop-bug-forked-ps5t8?file=/index.html

### Bug description

There is a bug Swiper library that creates an odd behavior when clicking on the “prev” navigation button. 

This issue happens when the slider is configured to loop the slides and the total number of slides is not evenly divisible by the number of slides to scroll.

Possible alternative to overcome this bug is [1] Turn off the loop or [2]  turn on "loopFillGroupWithBlank" feature.

As per my requirement I can't enable above two methods. Can I have any solution for this issue?

### Expected Behavior

Expected behavior is previous navigation button should slide to previous slide items when loop true and number of slide can be any.

### Actual Behavior

This issue happens when the slider is configured to loop the slides and the total number of slides is not evenly divisible by the number of slides to scroll.

### Swiper version

7.3.1

### Platform/Target and Browser Versions

Windows/Ubuntu - Firefox 94 ,Chrome 96.0.4664.45 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
