### ISSUE TITLE
Swiper doesn't work with NextJs

### ISSUE THREAD

**Issue by kodermax** [nolimits4web/swiper#5284]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/github-a252xz

### Bug description

ESM support doesn't work in Nextjs

### Swiper version

7.2.0

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It works in Next.js, Swiper website is a Next.js website too where it apparently works, look for issues on your (config) side https://nextjs.org/blog/next-11-1#es-modules-support
