### ISSUE TITLE
SvelteKit deployment issue w/ Swiper

### ISSUE THREAD

**Issue by onderbakirtas** [nolimits4web/swiper#5288]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/onderbakirtas/upo

### Bug description

This package doesn't work well with SvelteKit adapters. I have tried both Vercel and CloudFlare without success. Here is the main issue link from SvelteKit's repo: https://github.com/sveltejs/kit/issues/3015

### Swiper version

7.2.0

### Platform/Target and Browser Versions

Windows 10, All Browswers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by benmccann** [comment]
I wasn't able to test your reproduction since I don't have accounts on Vercel or Cloudflare, but based off the warning messages you get when building, I think this is quite likely to fix it:
- https://github.com/nolimits4web/ssr-window/pull/18
- https://github.com/nolimits4web/dom7/pull/52

**Comment by onderbakirtas** [comment]
Hello. Thanks for the PR and merge. The issue still persists. If you fork the repo and deploy on Vercel, you will encounter the error I'm seeing.

**Comment by onderbakirtas** [comment]
Closing this since the repo is needed.
