### ISSUE TITLE
Swiper slides gets height: 5.36871e+06px; if <!DOCTYPE html> is set

### ISSUE THREAD

**Issue by denismiiix** [nolimits4web/swiper#5289]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

1

### Bug description

When at start of html document <!DOCTYPE html> is placed heights of vertical slides will quickly recalculate to  5.36871e+06px.
HTML example below

```
<!DOCTYPE html>
<head>
  <!-- Link Swiper's CSS -->
  <link href="https://unpkg.com/swiper@7/swiper-bundle.min.css" rel="stylesheet">
  <style>
    .border-right {
      display: inline-block;
      width: 85px;
      height: 300px;
      text-align: center;
      vertical-align: middle;
      background: white; /* Цвет фона */
      outline: 4px solid black; /* Чёрная рамка */
      border: 3px solid white; /* Белая рамка */
      border-radius: 2px; /* Радиус скругления */
      overflow: hidden;
    }

    .swiper-slide{
      transition: all ease-in-out .3s;
      opacity: .2;

      height: 46px;
      line-height: 46px;
      text-align: center;
      font-size: 25px;
      font-style: normal;
      font-weight: bold;
      background: Black;
      border-radius: 3px;
      color: white;
    }
    .swiper-slide-prev,.swiper-slide-next{
      opacity: .5;
    }
    .swiper-slide-active{
      opacity: 1;
    }
  </style>
</head>
<body>
  <div class="border-right">
    <div class="swiper slider-right">
      <div class="swiper-wrapper">
        <div  class="number-block swiper-slide">&nbsp;</div>
        <div  class="number-block swiper-slide">&nbsp;</div>
        <div  class="number-block swiper-slide">&nbsp;</div>
        <div  class="number-block swiper-slide">Let's</div>
        <div  class="number-block swiper-slide">go!</div>
        <div  class="number-block swiper-slide">000</div>
        <div  class="number-block swiper-slide">111</div>
        <div  class="number-block swiper-slide">222</div>
        <div  class="number-block swiper-slide">333</div>
        <div  class="number-block swiper-slide">444</div>
        <div  class="number-block swiper-slide">555</div>
        <div  class="number-block swiper-slide">666</div>
        <div  class="number-block swiper-slide">777</div>
        <div  class="number-block swiper-slide">888</div>
        <div  class="number-block swiper-slide">999</div>
        <div  class="number-block swiper-slide">TTT</div>
        <div  class="number-block swiper-slide">END</div>
        <div  class="number-block swiper-slide">&nbsp;</div>
        <div  class="number-block swiper-slide">&nbsp;</div>
      </div>
    </div>
  </div>

    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
  <!-- Initialize Swiper -->
    <script>
      var swiper = new Swiper(".swiper", {
        direction: "vertical",
        centeredSlides: true,
        slideToClickedSlide: true,
        slidesPerView: 5,
        spaceBetween: 4,
        mousewheel: {
          // sensitivity: 5,
        },
        on: {
          scroll: function(swiper_, ev){
            swiper_.params.speed = 1;
            //console.log(ev);
          }
        },
        speed: 300,
        // autoplay: {
        //   delay: 1000,
        // },
      });
    </script>
</body>
```

### Swiper version

7

### Platform/Target and Browser Versions

windows 11 ME, Android Chrome, iOS Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by denismiiix** [comment]
Eh... if you are not interested in catching bugs, you can safely close this topic =)
Moreover, this problem cannot be reproduced in sandboxes, since <!DOCTYPE html> tags are ignored there.

**Comment by lizy0329** [comment]
This is a bug, when setting "direction:"vertical", please fix it

**Comment by itriplek** [comment]
here is the [demo link](https://codesandbox.io/s/exciting-sunset-uzv7py?file=/index.html)

**Comment by Over-reaction** [comment]
请问一下解决了么 我现在也是这个问题

**Comment by fernandopro** [comment]
Did you fix it? I have the same problem.

**Comment by fernandopro** [comment]
I fixed it with a custom css:

.swiper .swiper-wrapper{
        width: 0 !important;
      }

**Comment by Davi-T** [comment]
I had the same issue and fixed it by removing **_height:fit-content_** for the container that was holding all of the Swiper stuff. I was doing a Swiper update() on resize and was getting this issue when at ~800px high, which is where I have some CSS for activating some fancy scrollbars.

I was getting the same sort of weird combination of numbers, letters, plus sign etc ("1.67772e+07px"). However, Devtools is saying it as one large number without the letters though (so, for me, the height was resolving to something like 16777207, something way too tall).

There's probably some sort of css calculation in the code for updating stuff that isn't resolving to a valid number.

**Comment by Over-reaction** [comment]
我有了一种解决方式给swiper-container设置样式 width: 100%;height: 100%;position: absolute;

**Comment by Mardoxx** [comment]
There's weird stuff with this when you use it in  flexbox. I'm trying to figure it out.

**Comment by Indexo-Git** [comment]
> I fixed it with a custom css:
> 
> .swiper .swiper-wrapper{ width: 0 !important; }

Thanks Fernando, that worked for me
