### ISSUE TITLE
Error in swiper_angular.js in version 7.3.1 or 7.3.2

### ISSUE THREAD

**Issue by julgon2012** [nolimits4web/swiper#5291]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no reproduction link

### Bug description

An error occurs at line 729 (version 7.3.0) when you try to run

if (changedParams.scrollbar) {
                if (this.scrollbar &&
                    typeof this.scrollbar !== 'boolean' &&
                    this.scrollbar.el &&
                    scrollbar &&
                    !scrollbar.el) {
                    this.updateParameter('scrollbar', this.scrollbar);
                    scrollbar.init();
                    scrollbar.updateSize();
                    scrollbar.setTranslate();
                }
                else {
                    scrollbar.destroy();   // -------->  here!
                    scrollbar.el = null;
                }
            }

because the scrollbar object is undefined, but changedParams.scrollbar is true.

This does not happen until version 7.3.0 .-

In my project there are 3 swipers, but none use scrollbar, I don't even read the Scrollbar object from swiper.

### Swiper version

7.3.1 or 7.3.2

### Platform/Target and Browser Versions

Windows 10 Pro, Chrome Versión 96.0.4664.93 (Build oficial) (64 bits)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by orjandh** [comment]
Can confirm this problem was introduced in version 7.3.2.

Additional errors in:

Cannot read properties of undefined (reading 'destroy')
    at swiper_angular.js:721

Cannot read properties of undefined (reading 'prevEl')
    at swiper_angular.js:753

Cannot read properties of undefined (reading 'destroy')
    at swiper_angular.js:721

**Comment by orjandh** [comment]
I think I have managed to isolate the issue to slides that are being populated after initialization.

    import { Component } from '@angular/core';

    @Component({
        selector: 'app-card-strip',
        templateUrl: 'card-strip.html',
        styleUrls: ['./card-strip.scss']
    })
    export class CardStripComponent {

        slides;

        constructor() {
            setTimeout(() => {
                this.slides = [1, 2];
            },0);
        }
    }

.

    <swiper>
        <ng-template swiperSlide *ngFor="let slide of slides;" >
            slide {{slide}}
        </ng-template>
    </swiper>

In my environment, this gives these exact errors in 7.3.2, but not 7.3.1.

**Comment by mihpa** [comment]
Same issue in our project with 7.3.2 version. Temporary fixed by return on 7.3.0.

> Can confirm this problem was introduced in version 7.3.2.
> 
> Additional errors in:
> 
> Cannot read properties of undefined (reading 'destroy') at swiper_angular.js:721
> 
> Cannot read properties of undefined (reading 'prevEl') at swiper_angular.js:753
> 
> Cannot read properties of undefined (reading 'destroy') at swiper_angular.js:721

**Comment by vltansky** [comment]
7.3.3 released with fix
