### ISSUE TITLE
Vite can not resolve path pre-bundling Swiper dependencies

### ISSUE THREAD

**Issue by forchel** [nolimits4web/swiper#5294]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/github/forchel/swiper-test

### Bug description

We use Vue 3 with Typescript support, script setup and Swiper 7.3.2 in a project. 
In our App, we include Swiper Types. If we want to run Vite the following error occurs:

`Pre-bundling dependencies:
  vue
  bootstrap
  vue3-form-validation
  @fortawesome/fontawesome-svg-core
  vue-router
  (...and 15 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/swiper/types/index.d.ts:1:14: error: Could not resolve "./shared"
    1 │ export * from './shared';
      ╵               ~~~~~~~~~~

 > node_modules/swiper/types/index.d.ts:2:34: error: Could not resolve "./swiper-class"
    2 │ export { default as Swiper } from './swiper-class';
      ╵                                   ~~~~~~~~~~~~~~~~

 > node_modules/swiper/types/index.d.ts:3:14: error: Could not resolve "./swiper-events"
    3 │ export * from './swiper-events';
      ╵               ~~~~~~~~~~~~~~~~~

 > node_modules/swiper/types/index.d.ts:4:14: error: Could not resolve "./swiper-options"
    4 │ export * from './swiper-options';
      ╵               ~~~~~~~~~~~~~~~~~~

 > node_modules/swiper/types/index.d.ts:5:14: error: Could not resolve "./modules/public-api"
    5 │ export * from './modules/public-api';
      ╵               ~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 5 errors:
node_modules/swiper/types/index.d.ts:1:14: error: Could not resolve "./shared"
node_modules/swiper/types/index.d.ts:2:34: error: Could not resolve "./swiper-class"
node_modules/swiper/types/index.d.ts:3:14: error: Could not resolve "./swiper-events"
node_modules/swiper/types/index.d.ts:4:14: error: Could not resolve "./swiper-options"
node_modules/swiper/types/index.d.ts:5:14: error: Could not resolve "./modules/public-api"
    at failureErrorWithLog (C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:1493:15)
    at C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:1149:7)
    at C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:1258:14
    at C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\projects\tschingo\vue\node_modules\vite\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)`

### Expected Behavior

No problems resolving path.

### Swiper version

7.3.2

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
reproduction link you provided doesn't replicate the issue

**Comment by forchel** [comment]
Please use this https://codesandbox.io/s/github/forchel/swiper-test or this repo https://github.com/forchel/swiper-test.git

**Comment by nolimits4web** [comment]
for me it looks like issue on the vite(vite-ts) side, in Swiper package files everything is correct and in place, not sure why it can't resolve those types definitions

**Comment by krispekla** [comment]
Add to vite.config 
`  optimizeDeps: {
    exclude: ["swiper/vue", "swiper/types"],
   },`

**Comment by forchel** [comment]
Thank you for your solution. Works for me now.

**Comment by shven** [comment]
I got this error when I added "importsNotUsedAsValues": "error" to my tsconfig.json and resolved it by importing the swiper types as type.
`import type { Swiper as SwiperClass } from 'swiper/types';`
There's no need to exclude swiper in vite.config

**Comment by Luckyfella73** [comment]
> I got this error when I added "importsNotUsedAsValues": "error" to my tsconfig.json and resolved it by importing the swiper types as type. `import type { Swiper as SwiperClass } from 'swiper/types';` There's no need to exclude swiper in vite.config

Thanks to your post I could resolve the same type of error (path resolve issue) in my no-typescript-js :)
Using vite-js and regular modules I had the same issue. Choosing a different name as `Swiper` when importing fixed the path-issue for me. I guess the _export default_ in _swiper.ems.js_ makes this possible.

```
import FadeSwiper, { Autoplay, EffectFade } from 'swiper';

const SwiperInstance = new FadeSwiper(selectorSwiper, {
    // ...options here
});
```

**Comment by lucastanger** [comment]
> I got this error when I added "importsNotUsedAsValues": "error" to my tsconfig.json and resolved it by importing the swiper types as type. `import type { Swiper as SwiperClass } from 'swiper/types';` There's no need to exclude swiper in vite.config

I spent some hours now figuring out why this kept failing. Apparently my auto-fix .eslintrc was configured to use inline-type-imports.
`"@typescript-eslint/consistent-type-imports": [
                    "error",
                    {
                        "fixStyle": "inline-type-imports"
                    }
                ]`

It appears it is required to convert the whole import to type as you just did.

Failing:
`import { type Swiper } from 'swiper/types';`

Working:
`import type { Swiper } from 'swiper/types';`
