### ISSUE TITLE
Dynamic main bullets are not centered when loop

### ISSUE THREAD

**Issue by fmatzy** [nolimits4web/swiper#5304]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-pagination-dynamic-forked-teq17

### Bug description

When `dynamicBullets: true` and `loop: true` are set, and `dynamicMainBullets` is set to a value greater than 1, the main bullets are not centered and move strangely. This is especially obvious when moving the page in the backwards direction.

I investigated the pagination module, and I found that the index shift caused by `swiper.loopedSlides`  is not considered when calculating the `dynamicBulletIndex`.

https://github.com/nolimits4web/swiper/blob/5466df697934d1632c8c574c05964c02d95dcf9a/src/modules/pagination/pagination.js#L110

### Expected Behavior

When `loop: false`, the main bullets will always be in the middle, and the same looks would be preferable when `loop: true`.

![dynamic-bullets-without-loop](https://user-images.githubusercontent.com/30208309/146702824-d30aa7e7-1409-48a9-8b29-48dc4ec0d76b.gif)

### Actual Behavior

In the case of forward pagination, the main bullets will shift to the left at the end of the pagination.

![invalid-main-bullets-forward](https://user-images.githubusercontent.com/30208309/146702857-74a76808-e69e-4138-9699-c90ce3cc409b.gif)

In the case of backward pagination, strange movements like going forward and backward can be seen.

![invalid-main-bullets-backward](https://user-images.githubusercontent.com/30208309/146702868-2fb4cc9f-f545-4b70-9df4-5359648b2cf9.gif)

### Swiper version

7.3.3

### Platform/Target and Browser Versions

macOS 11.6.1, Chrome 96.0.4664.110

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by Amalykyarima** [comment]
has this been fixed?

**Comment by zecka** [comment]
This seems still an issue
https://stackblitz.com/edit/swiper-demo-4-pagination-dynamic-bullets-onb81qfr?file=index.html
