### ISSUE TITLE
Maximum update depth exceeded.

### ISSUE THREAD

**Issue by wibed** [nolimits4web/swiper#5310]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/romantic-pascal-p42hp?file=/src/index.js

### Bug description

initializing swiper updates the component, which makes uses as seen in the example difficult.
is there a way i can utilize swiper in that way without lifting the state up to its parent?

### Expected Behavior

for it to work

### Actual Behavior

Error
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### Swiper version

latest; 7.3.3

### Platform/Target and Browser Versions

any browser/platform, tested in safari and firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Update there is mandatory, you can use core version of Swiper instead (by calling new Swiper on required HTML element when component did mount)
