### ISSUE TITLE
A link in the CHANGELOG.md file is not working correctly

### ISSUE THREAD

**Issue by DAnn2012** [nolimits4web/swiper#5311]
### Clear and concise description of the problem

@nolimits4web 

I point out that in the CHANGELOG.md file there is a broken link:

https://github.com/nolimits4web/swiper/blame/master/CHANGELOG.md#L8

Thanks.

### Suggested solution

https://github.com/nolimits4web/swiper/pull/5296#pullrequestreview-836214645

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I removed that link
