### ISSUE TITLE
hover effect after mousewheel not working until mouse move

### ISSUE THREAD

**Issue by Fanni-Portier** [nolimits4web/swiper#5321]
### Check that this is really a bug

- [ ] I confirm

### Reproduction link

https://codepen.io/brilliant-coding/pen/JjrrpoW

### Bug description

If the mouse cursor is above the slider while loading - and not moving.
And then I use the mousewheel to navigate through the slider.
Slider is stopping - but the mouse hover effect is not working immediately.
Not until I move the mouse.

The problem is, the slider will be fullsize and you don't have to move the mouse before using it.

### Swiper version

7.3.4

### Platform/Target and Browser Versions

macOS Firefox, Chrome, Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Sorry, but Swiper doesn't do anything with it, this is how browser handles it
