### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by hoangtrung99** [nolimits4web/swiper#5322]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-react-forked-pvf6p?file=/src/App.jsx

### Bug description

I had this problem with nextjs@^12.0.7 and react@^18.0.0-rc.0
![Screen Shot 2021-12-23 at 17 37 47](https://user-images.githubusercontent.com/29956745/147228488-fed326b9-cdc4-45f4-b508-71b55faea0da.png)

### Swiper version

7.3.4

### Platform/Target and Browser Versions

MacOS BigSur

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You are using wrong createRoot React's API
```js
const root = ReactDOM.createRoot(document.getElementById("app"));
root.render(<App />);
```

**Comment by sanderkooger** [comment]
@hoangtrung99 did you manage to find a sollution? I just ran into the same issue. 

@nolimits4web When using vanilla nextjs@latest and react@next  this problem pops up? even when concurrent is not enabled.

**Comment by hoangtrung99** [comment]
@sanderkooger Hmmm, i downgraded the version ^17.0.2 :(

**Comment by sanderkooger** [comment]
@onair-lena This is our bug ;)

**Comment by sanderkooger** [comment]
@hoangtrung99 we did that too... Shame tho... we are trying to work our code into cuncurrent mode

**Comment by hoangtrung99** [comment]
There is no other way, I was lazy to recreate the project, so this issue is closed.

**Comment by sanderkooger** [comment]
@hoangtrung99 did you notice it only bugs out in development but you can still build and run production ?
