### ISSUE TITLE
Grid does not work on React lib, discussion not works

### ISSUE THREAD

**Issue by f-laino** [nolimits4web/swiper#5323]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/vigilant-worker-uyzxk

### Bug description

Same as https://github.com/nolimits4web/swiper/issues/5256

Discussion https://github.com/nolimits4web/swiper/discussions/5257 not helped

### Expected Behavior

Working Slides Grid in React

### Actual Behavior

One slide per row

### Swiper version

7.3.4

### Platform/Target and Browser Versions

Linux Ubuntu - Chrome 96

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
search through issues also doesn't work? https://codesandbox.io/s/swiper-slides-grid-react-forked-sgqul?file=/src/styles.css
