### ISSUE TITLE
When mousewheel enabled content on slide won't scroll

### ISSUE THREAD

**Issue by 8shaks** [nolimits4web/swiper#5324]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-mousewheel-control-react-forked-rz66o?file=/src/App.jsx

### Bug description

I have a div on a swiper slide that is set to scroll vertically for overflowed content. However, since mouse wheel is enabled it scrolls to the next section instead. Is it possible so that if a user's cursor is inside the div with the text, it scrolls within that div instead of moving to the next page?

### Swiper version

7.0.0

### Platform/Target and Browser Versions

macOS Safari 14.1, Chrome 96

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by prantaDutta** [comment]
@8shaks did you solve this problem?

**Comment by Kaizodo** [comment]
i am having same issue with angular

**Comment by gusicadnan** [comment]
I had the same issue with Table component. I wanted the table to be scrollable when cursor was inside.
So I created a TableWrapper component like this:

```
import React, { useEffect } from 'react';
import styled from 'styled-components';

interface Props {
  children: React.ReactNode;
}

const TableWrapper: React.FC<Props> = ({ children }) => {
  useEffect(() => {
    document.querySelectorAll('.table-wrapper').forEach((item) => {
      item.addEventListener(
        'wheel',
        (event: Event) => {
          event.stopPropagation();
        },
        { passive: false }
      );
    });
  }, []);

  return <Outer className="table-wrapper">{children}</Outer>;
};

export default TableWrapper;

const Outer = styled.div`
  height: 100%;
  background-color: ${(props) => props.theme.colors.black20};
  border-radius: 20px;
  padding: 10px 10px 10px 10px;
`;
```
It worked without any problem. Hope this helps.

**Comment by gusicadnan** [comment]
Or maybe cleaner using ref:

```
import React, { useEffect, useRef } from 'react';
import styled from 'styled-components';

interface Props {
  children: React.ReactNode;
}

const TableWrapper: React.FC<Props> = ({ children }) => {
  const tableRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const stopPropagation = (e: Event) => e.stopPropagation();

    if (tableRef && tableRef.current) {
      tableRef.current.addEventListener('wheel', stopPropagation, {
        passive: false,
      });
    }

    return () => {
      tableRef.current?.removeEventListener('wheel', stopPropagation);
    };
  });

  return <Outer ref={tableRef}>{children}</Outer>;
};

export default TableWrapper;

const Outer = styled.div`
  height: 100%;
  background-color: ${(props) => props.theme.colors.black20};
  border-radius: 20px;
  padding: 10px 10px 10px 10px;
`;
```

**Comment by yuting816** [comment]
I have the same problem with react hooks V18 on mac. But the same code works fine on windows, perhaps some issue with IOS system. I finally solved this problem using method mentioned above:

`   const Scene5 = () => {
    const swiperInstance = useSwiper()

    useEffect(()=>{
        const outerEl = document.getElementById('mycontainer');
        const el = document.getElementById('myscroll');

        outerEl.addEventListener('wheel', allowScroll)
        el.addEventListener('wheel',  handleScroll)

        return ()=>{
            // 组件销毁时清除事件监听
            outerEl.removeEventListener('wheel', allowScroll)
            el.removeEventListener('wheel',  handleScroll)
        }
    }, [])

    // 解决swiper库滚动不兼容mac问题
    const allowScroll = (event) => {
        event.stopPropagation()
    }

    // 手动添加向上滚动翻页
    const handleScroll = debounce((event)=>{
        const el = document.getElementById('myscroll');
        if (event.wheelDelta > 0 && el.scrollTop == 0) {
            // console.log('scrolll111', el.scrollTop);
            // 向上滑动，上一页
            swiperInstance.slidePrev()
        }
    }, 300) 

    return (
        <div className={styles.scene5Container} id="mycontainer">
            <div id="myscroll" className={styles.overflow}>
                 ....
            </div>
        </div>
    )
}

export default Scene5`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
