### ISSUE TITLE
Swiper in popup

### ISSUE THREAD

**Issue by somegooser** [nolimits4web/swiper#5329]
### Clear and concise description of the problem

I know this is not the place for this but i really like your codework and would like to use more / integrate swiper into modal windows. Like swiping through image galleries in an window popup.

### Suggested solution

Can you create something like Fancybox with the features of Swiper in it?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
You can already use swiper inside modals, want to share your codesandbox / stackblitz ?

**Comment by somegooser** [comment]
Yeah i know, but my questions is if you could also create the modal via swiper of just another plugin of your awesome work!

**Comment by sovetski** [comment]
Any news here?
