### ISSUE TITLE
spaceBetween issue while using data attributes

### ISSUE THREAD

**Issue by pixibuex** [nolimits4web/swiper#5330]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/elemis/pen/BawJPRX

### Bug description

I'm working on setting swiper options with data attributes. All parameters work properly except spaceBetween, when I want assign the spaceBetween value using a data attribute Swiper breaks. But if I use JSON instead, it works properly. 

Could you please help me figure out what is wrong or missing with my approach with data attributes when it comes to spaceBetween?

[The pen](https://codepen.io/elemis/pen/BawJPRX) shows two scenarios. First one has the data attribute for spaceBetween and swiper is broken, while the second one has beforeInit with JSON and everything works properly there. Please note that if I add spaceBetween data attribute with beforeInit it still doesn’t work.

### Swiper version

7.4.1

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
How is your custom implementation is Swiper's issue? data- attributes values return strings while those parameters must be passed as numbers, so convert them to numbers
