### ISSUE TITLE
Multi direction swipes

### ISSUE THREAD

**Issue by Saqib92** [nolimits4web/swiper#5332]
### Clear and concise description of the problem

I want to have multidirectional Swiper for Example:
I have a Story Slider where on First Slide it says `Go Up` means user can swipe down to go upside (Vertical swipe) and then on that slide it says go Right (user can swipe left to go to right side(Horizontal swipe). 
i have searched about Nested Swipe but it not working as per requirements. 
Is there a way to change swiper direction on Slide change?? Mean i can detect next slides direction n previous slide change event to show up on down arrows and same for right and left arrow depends on slide data. 

### Suggested solution

There should be a slider direction update option to change slider direction on slide change event. 

### Alternative

i tried using `hammer.js` to detect swipes and show arrows based on data and then swipe in that direction but its not smooth and causing many issues for image loading and other. 

### Additional context

Multi direction Swiper to go up down left right based on data. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#method-swiper-changeDirection
