### ISSUE TITLE
Change direction (LTR or RTL) dynamically

### ISSUE THREAD

**Issue by ahmedhrayyan** [nolimits4web/swiper#5334]
### Clear and concise description of the problem

Currently, I can change the direction of Swiper horizantally or vertically but cannot change the direction LTR or RTL?!!!!!!

I hope that there is any easy solution I could change toggle rtl mode dynamically without fully reload the page (or reinit swiper)

### Suggested solution

Making swiper update method check for dir change and behave based on that.

### Alternative

Adding new changeDir method.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by vltansky** [comment]
A demo would be very useful here
And of course, you are very welcome to open PR.

**Comment by ahmedhrayyan** [comment]
Apologies for the delayed response, can you reopen the issue or  should I open new one and referencing this one within it ?

I have created a CodeSandobx demonstrating the issue, you can find it [here](https://codesandbox.io/s/compassionate-bardeen-plxjs?file=/src/App.tsx).
As you will notice, changing the direction on the fly cause problems in Swiper.

**Comment by nolimits4web** [comment]
@ahmedhrayyan https://codesandbox.io/s/awesome-glade-knvqv?file=/src/App.tsx

**Comment by ahmedhrayyan** [comment]
It works, thanks a lot @nolimits4web

**Comment by vltansky** [comment]
@nolimits4web maybe worth adding `toggleDirection`/`setDirection` to the core? it's not obvious

**Comment by ahmedhrayyan** [comment]
> @nolimits4web maybe worth adding `toggleDirection`/`setDirection` to the core? it's not obvious

It would be better, specially that I have also to init the pagination via  `swiper.pagination.init()` if the pagination module was used.

**Comment by ahmedhrayyan** [comment]
> @ahmedhrayyan https://codesandbox.io/s/awesome-glade-knvqv?file=/src/App.tsx

Unfortunately, the solution also causes problem if `spaceBetween` is used

**Comment by atefBB** [comment]
@ahmedhrayyan Hey Bro! Did you solve this issue?!
