### ISSUE TITLE
Virtual append/prepend/*pend not working at all.

### ISSUE THREAD

**Issue by methaqualon** [nolimits4web/swiper#5335]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/28spe

### Bug description

Hey! I like SwipeJS at all, but have some problems. It is link (reproduction link) from your own website. It works perfectly with vanilla js, but on reactjs it just do not appending or prepending slides, just jumps to i's (i is how much you want to *pend). Just compare it with just yours vanilla https://codesandbox.io/s/pjzkg . I think it can be a bug. How just should I manage my virtual slides if it is not a bug? I need to append a slide when swipe event is touched on reactjs. You may think that reproduction link is my example is needed to fix if it is not a bug. Thank you!

### Expected Behavior

prepending and appending slides like on "Core" version

### Actual Behavior

it just jumps onto another slide

### Swiper version

Actual from your own website

### Platform/Target and Browser Versions

macOS 11.2.3 Safari 14.0.3 but it looks like not browser-dependent

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by MarcinCebula** [comment]
Hey @methaqualon 

Did you manage to resolve this issue?

**Comment by methaqualon** [comment]
@MarcinCebula Hey! Well, it seems like virtual slides in all versions have some bugs ... Product is hard to develop, I think so.
I don't have enough skills to try with myself to repair ReactJS version of it, so I turned to Vanilla version, where I have to do a few things to make it work properly. On this version prepending were somewhy moving user up for one slide, and swiping to prepended slides works without my animations and so a little bit ugly. But this all could be only my problem because of my special styles, sandboxes with oficial examples on the website works good enough.

Counting all this things my project is a very little project, and it doesn't require much of things of swiperjs. I think in my situation is easier to pass a task to any freelancer to clone needed functionality into working reactjs components without a bugs, but it all will be when I have enough resources (:

**Comment by nolimits4web** [comment]
In React version, it should be done by manipulating with slides array/data/source in your react component, not by using Virtual Slides methods, which are basically only for Core Swiper
