### ISSUE TITLE
Allow nesting of styles (SASS)

### ISSUE THREAD

**Issue by dpucher** [nolimits4web/swiper#5340]
### Clear and concise description of the problem

As a developer using Swiper I want to nest swiper styles (SASS) so that they have a higher specificity and can be encapsulated.

Nesting the whole [swiper.scss](https://github.com/nolimits4web/swiper/blob/master/src/swiper.scss) will break because it includes a font definition which results in invalid syntax.

### Suggested solution

Use `@at-root` rule in [swiper.scss](https://github.com/nolimits4web/swiper/blob/master/src/swiper.scss)

```
@import 'swiper-vars.scss';

@at-root {
  @font-face {
    font-family: 'swiper-icons';
    src: url('data:application/font-woff;charset=utf-8;base64, d09GRgABAAAA...Zo5IPrmUn0hGA0AO8EFTQAA')
      format('woff');
    font-weight: 400;
    font-style: normal;
  }
}

@import './core/core';
```

### Alternative

Expose more granular scss files e.g.: 

- `font.scss`: contains only the `@font-face` rule
- `core.scss`: exposed existing file [core.scss](https://github.com/nolimits4web/swiper/blob/master/src/core/core.scss)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by winsy-fstln** [comment]
The suggested solution, I think should move code `:root {
  --swiper-theme-color: #{$themeColor};
}` into `@at-root {}`
```
@import 'swiper-vars.scss';

@at-root {
  @font-face {
    font-family: 'swiper-icons';
    src: url('data:application/font-woff;charset=utf-8;base64, d09GRgABAAAA...Zo5IPrmUn0hGA0AO8EFTQAA')
      format('woff');
    font-weight: 400;
    font-style: normal;
  }
  :root {
    --swiper-theme-color: #{$themeColor};
  }
}

@import './core/core';
```
