### ISSUE TITLE
Module not found: Error: Package path ./swiper.less

### ISSUE THREAD

**Issue by HejieShao** [nolimits4web/swiper#5347]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no link

### Bug description

I use Create React App to create program, the webpack version is 5.65.0, node version is v14.16.0
import like this
`import { Navigation, Pagination, Autoplay } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react/swiper-react.js';
import "swiper/swiper.less";
import "swiper/modules/navigation/navigation.less";
import "swiper/modules/pagination/pagination.less";`

when I build, it shows the error `Module not found: Error: Package path ./swiper.less is not exported from package /Users/xxx/Documents/work/xxx/node_modules/swiper (see exports field in /Users/xxx/Documents/work/xxx/node_modules/swiper/package.json)`. 

I don't know What causes this error and how to fix it.

### Swiper version

7.4.1

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look at less imports https://swiperjs.com/swiper-api#less-styles
