### ISSUE TITLE
Blazor Server/WASM Module

### ISSUE THREAD

**Issue by TheAtomicOption** [nolimits4web/swiper#5348]
### Clear and concise description of the problem

Blazor is a web development framework similar to React, Angular, Vue etc ([see comparison article here](https://www.angularminds.com/blog/article/comparison-between-blazor-vs-angular-vs-react-vs-vue.html)). As I recently mentioned in ([this swiper discussion thread](https://github.com/nolimits4web/swiper/discussions/5328)), Blazor would require a module similar in concept to these frameworks in order to make effective use of Swiper. 

### Suggested solution

This proposal is for the creation of a module (and likely also a nuget package) to make usage of the Swiper library possible in both Blazor Server and Blazor WASM apps.

### Alternative

Blazor uses an incremental DOM, similar in some ways to React's Virtual DOM. Due to this feature Swiper's addition and removal of DOM elements is in conflict with Blazor's ability to incrementally update the DOM.

I naively attempted to make a JSInterop module for Blazor which calls `.destroy()` on instances of swiper any time Blazor intends to make a DOM update, and then reinitializing a new swiper instance afterwards. Besides the performance and feature downsides of recreating Swiper instances this way, my attempted solution caused errors within the minified swiper bundle indicating that this approach still leaves some conflict I haven't found between Blazor and Swiper. 

### Additional context

I've been unable to find any library for the Blazor Server app I'm creating at my work with performance and features similar to Swiper, or indeed sufficient to our needs.

I think I could write the module I'm proposing here if someone could offer a thorough introduction to the Swiper codebase. or I could offer support from the C# and Blazor angle, to someone else writing the module. However in attempting to move forward without that support, understanding the internal layout of Swiper's codebase, and framework-interaction modules well enough to either adapt their ideas to an independent Blazor library, or write the module proposed in here myself, has proven daunting. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Do not think it worths implementing, and there is new [Swiper Web Components](https://swiperjs.com/element) in v9 supposed to be used in any other frameworks
