### ISSUE TITLE
Duplicated slides in loop mode lose all dynamism

### ISSUE THREAD

**Issue by eden-omb** [nolimits4web/swiper#5359]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-svelte-forked-kj1iz?file=/App.svelte-kj1iz?file=/App.svelte

### Bug description

Duplicate slides lose all dynamism, i.e. event handlers, [Svelte class directives](https://svelte.dev/docs#template-syntax-element-directives-class-name), etc. There's #4261, but it's for Swiper 6.4.15 and from almost a year ago; more importantly, it's marked as a feature request. My reproduction link demonstrates clearly broken behavior.

My example shows an `on:click` event handler. This can still be achieved for duplicate slides by using the [Swiper event](https://swiperjs.com/swiper-api#event-click); however, though usually I could simply have a specific handler per clicked slide, here I have to rely on Swiper's `clickedSlide` and `clickedIndex` to associate the slide with my specific data item. And still I can't think of any way to e.g. reapply dynamic classes.

### Expected Behavior

I expect the event handlers and directives applied to elements in `SwiperSlide`s to be copied over or otherwise be usable on duplicated slides as well as the originals.

### Actual Behavior

Event handlers and directives are only ever applied to the original slides, and duplicated slides are missing critical behavior.

### Swiper version

7.4.1

### Platform/Target and Browser Versions

Vivaldi on Ubuntu, useragent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.113 Safari/537.36'

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate  #4261
