### ISSUE TITLE
When looping with "slidesPerGroup" it will not correctly update the loop groups when click on Previous navigation button

### ISSUE THREAD

**Issue by chamikabm** [nolimits4web/swiper#5363]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-centered-react-forked-b8gw3?file=/src/App.jsx

### Bug description

When clicking on the Previous button it will stuck on the same set of group instead of looping through the elements.

### Expected Behavior

It should loop through the groups as it behaves when we click on the Next button.

### Swiper version

7.0.0

### Platform/Target and Browser Versions

macOS - Chrome Version 97.0.4692.71

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
