### ISSUE TITLE
cant use react routers <Link> in swiper

### ISSUE THREAD

**Issue by sinapirani** [nolimits4web/swiper#5372]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/xl42w

### Bug description

i cant use <Link> tag in or out if the a swiper slide.
when i use this tag in the swiperslide the slide be hide

### Swiper version

7.0.0

### Platform/Target and Browser Versions

windows10 chrome last

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by vltansky** [comment]
Your codesandbox don't have a Link example.
