### ISSUE TITLE
Once the mobile keypad is appear then Swiper slide goes out of screen or disturb the slides.

### ISSUE THREAD

**Issue by suyogn** [nolimits4web/swiper#5376]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

(https://codesandbox.io/s/swiper-scrollbar-forked-un05j?from-embed=&file=/index.html)

### Bug description
**Mobile behavior**
In the Swiper, the slide added an input text box. Once I tried to type something in the textbox then a **mobile keypad** appears but that slide is out of the screen or behind the above slide. It is behave something wired.
**I have added the textbox in the 3rd slide at the bottom.**
### Expected Behavior

Once the keypad appears the slide should adjust the area and the textbox be focused in a visible area 

### Swiper version

6.7

### Platform/Target and Browser Versions

Android, iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by suyogn** [comment]
> Hello @suyogn. Please provide a online reproduction by [codesandbox](https://codesandbox.io/) or a minimal GitHub repository. You can fork one of our [demos](https://swiperjs.com/demos) in codesandbox to get start. Issues labeled by `missing demo` will be closed if no activities in 3 days.

Please check the reference link
https://codesandbox.io/s/swiper-scrollbar-forked-un05j?from-embed=&file=/index.html

Mobile behavior
In the Swiper, the slide added an input text box. Once I tried to type something in the textbox then a mobile keypad appears but that slide is out of the screen or behind the above slide. It is behave something wired.
I have added the textbox in the 3rd slide at the bottom.

**Comment by nolimits4web** [comment]
Can't see the bug https://user-images.githubusercontent.com/999588/150158036-5fff9b01-41aa-4566-8f3a-ec1f23b4239b.MOV

**Comment by suyogn** [comment]
Thanks for quick reply. 

Once we click on the input box then the slide goes out of the screen. We have to scroll down manually. If precisely to say you then we can see this behavior on 0:01 - 0:02 in the video clip
Expected Behavior: Once we click on the input box then that text field should be visible (Not required to pull down manually). 

I hope, you understood the exact problem. 
Thanks in Advance

**Comment by suyogn** [comment]
I am trying from setTranslate() but it wont work.
How to use this swiper.scrollbar.setTranslate()
