### ISSUE TITLE
change dot position

### ISSUE THREAD

**Issue by weber77** [nolimits4web/swiper#5384]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-vertical-react-forked-60pum

### Bug description

Want the swiper dots to be aligned on the left in vertical swiping mode instead of the right

<img width="721" alt="Screen Shot 2022-01-22 at 11 38 25 AM" src="https://user-images.githubusercontent.com/44323398/150635134-93593e04-23cc-4d7d-a7ee-745f35c2906d.png">

### Expected Behavior

dots on left 

### Actual Behavior

dots on right

### Swiper version

^6.8.4

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
```css
.swiper-pagination-vertical.swiper-pagination-bullets{
    left: 10px;
    right: auto;
}
```

**Comment by weber77** [comment]
Thanks I actually got it working. Forgot to close the issue. But I’ve
another one, I’m trying to put embed tweets in slider but it doesn’t work.
How can I do that?
