### ISSUE TITLE
Bug on use Grid

### ISSUE THREAD

**Issue by hugofabricio** [nolimits4web/swiper#5386]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-swiper-grid-w5n08

### Bug description

When use Grid module on React App, is not rendered as in the demo version. Slides not wrap in wrapper.

### Expected Behavior

https://codesandbox.io/s/mxyiz
<img width="557" alt="Captura de Tela 2022-01-23 às 12 12 57" src="https://user-images.githubusercontent.com/425678/150685240-f568605b-726b-4080-9198-4f2084015ce6.png">

### Actual Behavior

<img width="554" alt="Captura de Tela 2022-01-23 às 12 17 17" src="https://user-images.githubusercontent.com/425678/150685440-75d75e02-f2b3-4020-bb2a-dafbaaa7d418.png">

### Swiper version

7.4.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by rtabulov** [comment]
just set .swiper height
```css
.swiper {
  height: 600px; // or 100% if parent has a set height
}
```

**Comment by strongphoenix** [comment]
@nolimits4web 
I have one question in here.
I understand I should set slider height like this `height: calc((100% - 30px) / 2) !important;`.
But when items have different heights, how can I set height?
![image](https://github.com/nolimits4web/swiper/assets/80874362/5e25547e-01cd-48f6-822c-4af6773b85f7)
