### ISSUE TITLE
Swiper does not play well with table-cell

### ISSUE THREAD

**Issue by jesperveldhuizen** [nolimits4web/Swiper#539]
First of all: great work with the Swiper, best one around I think!

Is it a known issue that the Swiper isn't working well with table cells? 

I'm using a DIV with 'display: table' (100% width). In this DIV I have three columns (all DIV) with 'display: table-cell' (34%, 33%, 33%).

In the first column I have a Swiper, but for some reason it's showing all over the page instead of just in the column (34% width).

Please see this page (and source):

http://data.baansportfansite.nl/test/

Any suggestions?

**Comment by yumyo** [comment]
Thanks

**Comment by carlosnpz** [comment]
Saved my life, thanks!

**Comment by icbd** [comment]
if the height of picture is smaller than the div.table-cell , how can i fill the div.table-cell ? thanks
