### ISSUE TITLE
There's no way to change a config item after Swiper created

### ISSUE THREAD

**Issue by jakeparis** [nolimits4web/swiper#5393]
### Clear and concise description of the problem

I am looking for a method that will allow me to change _any_ swiper config item after it's been initialized. So for example, let's say I initialize Swiper like so:
```js
const sw = new Swiper('#sw', {
    keyboard: true,
}
```

and later I want to change the option to be `keyboard: false`.

### Suggested solution

I would like to have a new method on Swiper core instance something like:
```js
const sw = new Swiper('#sw', {
    keyboard: true,
}

// later, change the option (for example, turn keyboard support off).
sw.setConfig( 'keyboard', false );
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There are methods to toggle keyboard control https://swiperjs.com/swiper-api#keyboard-control-methods

**Comment by jakeparis** [comment]
Maybe that was a bad example. I am interested in modifying _any_ config item. So, how about `autoHeight` or `slidesPerView`? I would like a generic method to change any config, for example 
```js
swiper.setConfig( 'slidesPerView', 5 );
swiper.setConfig( 'autoHeight', false );
```

**Comment by nolimits4web** [comment]
update swiper.params object and call swiper.update()

**Comment by jakeparis** [comment]
Great, thank you!

**Comment by yasin7044** [comment]
I am not getting swi[pe.update method i am using swiper element in vue js

**Comment by hassaan-glowfish** [comment]
I want to change the Grid rows on state change but its not working. Tried using ref and also with swiper instance but still it does not update.

```
  swiperRef.current.swiper.params.grid.rows =  rows
  swiper?.update()
```
