### ISSUE TITLE
[Svelte] SwiperSlide slot data always `false`

### ISSUE THREAD

**Issue by hmaesta** [nolimits4web/swiper#5395]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/sveltekit-swiper-7-coq4t?file=/src/routes/index.svelte

### Bug description

[Documentation](https://swiperjs.com/svelte#swiper-slide-slot-data) shows that `<SwiperSlide>` can return the current slide status (`isActive`, `isVisible`, etc) with `let:data` – but all returns are `false`.

### Expected Behavior

- When the current slide is visible, `data.isVisible` should be `true`
- When the current slide is active, `data.isActive` should be `true`

### Actual Behavior

- When the current slide is visible, `data.isVisible` is `false`
- When the current slide is active, `data.isActive` is `false`

<img width="737" alt="Screen Shot 2022-01-26 at 13 42 03" src="https://user-images.githubusercontent.com/741969/151207071-3ece2938-0dd6-473e-aafc-5fb3f1667e21.png">

### Swiper version

7.4.1

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
fixed in https://github.com/nolimits4web/swiper/commit/89f14ab5c07d0d8ab8fa7b0a40d4fb29dcdc99de
