### ISSUE TITLE
Virtual doesn't work with loop: true

### ISSUE THREAD

**Issue by nazarpelekh** [nolimits4web/swiper#5407]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-virtual-slides-react-forked-dprg9?file=/src/App.jsx

### Bug description

Loop: true doesn't work with virtual slides

### Swiper version

7.4.1

### Platform/Target and Browser Versions

macOS, Windows, Cordova, iOS, Android, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#virtual-slides

> Note that according to Virtual Slides realization it doesn't work with loop mode
