### ISSUE TITLE
using gird + enabled loop not working as expected

### ISSUE THREAD

**Issue by Melikano** [nolimits4web/swiper#5408]
### Check that this is really a bug

- [ ] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-grid-react-forked-zinob?file=/src/App.jsx

### Bug description

when using `grid={ { rows: 2 } }` along with `loop`, the loop mode is just working in one side of the swiper and the other side is not sliding anymore when it reaches the end.

### Expected Behavior

swiper slides infinitely from both sides

### Actual Behavior

swiper slides infinitely from only one side

### Swiper version

7.3.1

### Platform/Target and Browser Versions

Chromium 96.0.4664.93 Arch Linux

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by icy-meteor** [comment]
I can confirm this is happening even on the latest version - 8.0.6

**Comment by xieyt203** [comment]
same bug too

**Comment by zuevpavel** [comment]
I have the same problem, is there a solution? "swiper": "8.0.7"

**Comment by yogarasu** [comment]
Me too  "swiper": "^8.4.4"

**Comment by yogarasu** [comment]
Document says it doesn't work.

```
rows > 1 is currently not compatible with loop mode (loop: true)
```

https://swiperjs.com/swiper-api

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
