### ISSUE TITLE
when build with vite-ssg  Unknown file extension ".scss" or ".css"

### ISSUE THREAD

**Issue by leosin** [nolimits4web/swiper#5409]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-mpqpqd?file=src/App.vue

### Bug description

when i use vite-ssg plugin to build html

it return some error

(node:20) UnhandledPromiseRejectionWarning: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/projects/vitejs-vite-mpqpqd/node_modules/swiper/swiper.min.css

until i comment this line, vite-ssg works
// import 'swiper/css';

### Swiper version

7.4.1

### Platform/Target and Browser Versions

macOS Microsoft Edge 97

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
