### ISSUE TITLE
Weird behaviour with multiples Swiper's instances 

### ISSUE THREAD

**Issue by aresrioja10** [nolimits4web/swiper#5410]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://nintenduo.com/analisis-danganronpa-decadence-nintendo-switch/

### Bug description

While trying to use multiples Swiper instances in a page they have a strange behaviour. Some of them don't work, some of them starts with the second of third slide.

This is the code:

```
<script type="module">
  import Swiper from 'https://unpkg.com/swiper@7/swiper-bundle.esm.browser.min.js';

  setTimeout(() => {
    const swiperThumbs = new Swiper('.js-block-gallery-thumbs-{{$block['id']}}', {
      spaceBetween: 12,
      slidesPerView: 4,
      freeMode: true,
      watchSlidesProgress: true,
      breakpoints: {
        700: {
          slidesPerView: 7,
          spaceBetween: 12,
        },
      },
    });

    const swiper = new Swiper('.u-swiper-container-{{$block['id']}}', {
      slidesPerView: 'auto',
      loop: false,
      autoHeight: false,
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      thumbs: {
        swiper: swiperThumbs,
      },
      pagination: {
        el: '.swiper-pagination',
        type: 'fraction',
      },
      keyboard: {
        enabled: true,
        onlyInViewport: true,
      },
    });
  }, 1000);
</script>

<div class="c-block-gallery">
  <div class="c-block-gallery__main swiper js-block-gallery u-swiper-container-{{$block['id']}}" data-id="{{$block['id']}}">
    <div class="swiper-wrapper">
      @foreach($gallery as $image)
        @php
          $imageSrc = $image['url'];
          $alt = $image['alt'];
          $height = $image['height'];
          $width = $image['width'];

        @endphp
        <div class="swiper-slide">
          <picture class="c-block-gallery__image js-object-fit">
            <img
                src="{{ $imageSrc }}"
                alt="{{ $alt }}"
                loading="lazy"
                height="{{ $height }}"
                width="{{ $width }}"
            >
          </picture>
        </div>
      @endforeach
    </div>

    <div class="swiper-button-prev c-block-gallery__arrow">
      @include('icons.arrow-slider')
    </div>

    <div class="swiper-button-next c-block-gallery__arrow">
      @include('icons.arrow-slider')
    </div>

    <div class="swiper-pagination c-block-gallery__pagination"></div>
  </div>

  <div thumbsSlider="" class="c-block-gallery__thumbs swiper js-block-gallery-thumbs-{{$block['id']}} u-margin--top-sm">
    <div class="swiper-wrapper">
      @foreach($gallery as $image)
        @php
          $imageSrc = $image['url'];
          $alt = $image['alt'];
          $height = $image['height'];
          $width = $image['width'];

        @endphp
        <div class="swiper-slide">
          <div class="c-block-gallery__thumb__overlay">
            <picture class="c-block-gallery__thumb js-object-fit">
              <img
                  src="{{ $imageSrc }}"
                  alt="{{ $alt }}"
                  loading="lazy"
                  height="{{ $height }}"
                  width="{{ $width }}"
              >
            </picture>
          </div>
        </div>
      @endforeach
    </div>
  </div>
</div>
```

### Swiper version

7.4.1

### Platform/Target and Browser Versions

macOS Chrome 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Would be good to see isolated example using CodeSandbox, right now your website works really slow for me, and I am not sure it is related to swiper or some other scripts

**Comment by junaidahmed501** [comment]
> ### Check that this is really a bug
> * [x]  I confirm
> 
> ### Reproduction link
> https://nintenduo.com/analisis-danganronpa-decadence-nintendo-switch/
> 
> ### Bug description
> While trying to use multiples Swiper instances in a page they have a strange behaviour. Some of them don't work, some of them starts with the second of third slide.
> 
> This is the code:
> 
> ```
> <script type="module">
>   import Swiper from 'https://unpkg.com/swiper@7/swiper-bundle.esm.browser.min.js';
> 
>   setTimeout(() => {
>     const swiperThumbs = new Swiper('.js-block-gallery-thumbs-{{$block['id']}}', {
>       spaceBetween: 12,
>       slidesPerView: 4,
>       freeMode: true,
>       watchSlidesProgress: true,
>       breakpoints: {
>         700: {
>           slidesPerView: 7,
>           spaceBetween: 12,
>         },
>       },
>     });
> 
>     const swiper = new Swiper('.u-swiper-container-{{$block['id']}}', {
>       slidesPerView: 'auto',
>       loop: false,
>       autoHeight: false,
>       navigation: {
>         nextEl: '.swiper-button-next',
>         prevEl: '.swiper-button-prev',
>       },
>       thumbs: {
>         swiper: swiperThumbs,
>       },
>       pagination: {
>         el: '.swiper-pagination',
>         type: 'fraction',
>       },
>       keyboard: {
>         enabled: true,
>         onlyInViewport: true,
>       },
>     });
>   }, 1000);
> </script>
> 
> <div class="c-block-gallery">
>   <div class="c-block-gallery__main swiper js-block-gallery u-swiper-container-{{$block['id']}}" data-id="{{$block['id']}}">
>     <div class="swiper-wrapper">
>       @foreach($gallery as $image)
>         @php
>           $imageSrc = $image['url'];
>           $alt = $image['alt'];
>           $height = $image['height'];
>           $width = $image['width'];
> 
>         @endphp
>         <div class="swiper-slide">
>           <picture class="c-block-gallery__image js-object-fit">
>             <img
>                 src="{{ $imageSrc }}"
>                 alt="{{ $alt }}"
>                 loading="lazy"
>                 height="{{ $height }}"
>                 width="{{ $width }}"
>             >
>           </picture>
>         </div>
>       @endforeach
>     </div>
> 
>     <div class="swiper-button-prev c-block-gallery__arrow">
>       @include('icons.arrow-slider')
>     </div>
> 
>     <div class="swiper-button-next c-block-gallery__arrow">
>       @include('icons.arrow-slider')
>     </div>
> 
>     <div class="swiper-pagination c-block-gallery__pagination"></div>
>   </div>
> 
>   <div thumbsSlider="" class="c-block-gallery__thumbs swiper js-block-gallery-thumbs-{{$block['id']}} u-margin--top-sm">
>     <div class="swiper-wrapper">
>       @foreach($gallery as $image)
>         @php
>           $imageSrc = $image['url'];
>           $alt = $image['alt'];
>           $height = $image['height'];
>           $width = $image['width'];
> 
>         @endphp
>         <div class="swiper-slide">
>           <div class="c-block-gallery__thumb__overlay">
>             <picture class="c-block-gallery__thumb js-object-fit">
>               <img
>                   src="{{ $imageSrc }}"
>                   alt="{{ $alt }}"
>                   loading="lazy"
>                   height="{{ $height }}"
>                   width="{{ $width }}"
>               >
>             </picture>
>           </div>
>         </div>
>       @endforeach
>     </div>
>   </div>
> </div>
> ```
> 
> ### Expected Behavior
> _No response_
> 
> ### Actual Behavior
> _No response_
> 
> ### Swiper version
> 7.4.1
> 
> ### Platform/Target and Browser Versions
> macOS Chrome
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
> * [x]  Read the [docs](https://swiperjs.com/swiper-api).
> * [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
> * [x]  Make sure this is a Swiper issue and not a framework-specific issue
> 
> ### Would you like to open a PR for this bug?
> * [ ]  I'm willing to open a PR

Facing a similar issue in swiper-angular

**Comment by nolimits4web** [comment]
Swiper v9 doesn't lazy module anymore. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
