### ISSUE TITLE
Can't resolve 'swiper/angular' 

### ISSUE THREAD

**Issue by Sergiobop** [nolimits4web/swiper#5414]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

none

### Bug description

After upgrading to swiper 8.0.0, i can't serve my project

### Swiper version

8.0.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Sergiobop** [comment]
I'm sorry to bother you @nolimits4web , but i think the fix introduced a new bug. Now the app is stuck when i enter the page where the swiper is.

**Comment by nolimits4web** [comment]
cc @vltansky

**Comment by brhoomjs** [comment]
After updating to 8.0.1

I got these warning causing page to freeze 

```js
 ./node_modules/Swiper/angular/fesm2015/swiper_angular.mjs - Warning: There are multiple modules with names that only differ in casing.
[ng] This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
[ng] Use equal casing. Compare these module identifiers:
```

**Comment by hheexx** [comment]
yea compilation is ok but when you open page it hangs the browser

**Comment by BernhardBehrendt** [comment]
On my machine the same. 
It crashes in a way actually that it's not possible anymore this top recording a performance dump in devtools.

**Comment by JamesIves** [comment]
Also seeing this issue ^

**Comment by hudzenko** [comment]
For us swiper completely crash browser when angular app starts. Weird

**Comment by Kent0810** [comment]
Yeah, occurring the same bug, do you guys know how to downgrade SwiperJs CDN, mine I think is stuck at 8.0.1

**Comment by hheexx** [comment]
8.0.2 looks ok....

**Comment by wplit** [comment]
Thanks for fixing this so quick. I had just been testing v8.0.1 and couldn't figure it out. All is fixed in v.8.0.2 from what I can tell.
