### ISSUE TITLE
Froze my page when using Swiper through CDN

### ISSUE THREAD

**Issue by Kent0810** [nolimits4web/swiper#5417]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://kent0810.github.io/Netflix_Clone/

### Bug description

My Netflix_Clone is working fine for while but after the 8.0.1 update to SwiperJs, my page started freezing after logging in, can you guys check it out (I'm using SwiperJs through CDN not npm install). Thank You  

### Expected Behavior

Freeze the entire page

### Actual Behavior

Load All Slide in the same time at DOM

### Swiper version

8.0.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by hudzenko** [comment]
Same happens from bunch of people in thread here: https://github.com/nolimits4web/swiper/issues/5414

Weird.

**Comment by nolimits4web** [comment]
duplicate #5414
