### ISSUE TITLE
LOOPING SLIDES 1>2>3>4>3>2>1>2>3>4 ...  BOUNCE ORDER ?

### ISSUE THREAD

**Issue by lordloadalot** [nolimits4web/swiper#5423]
### Discussed in https://github.com/nolimits4web/swiper/discussions/5293

<div type='discussions-op-text'>

<sup>Originally posted by **lordloadalot** December 14, 2021</sup>
Hi Vladimir!

 I want to loop my slides with a bounce order effect:  
actually the loop goes : 1 > 2 > 3 > 4 > 1 > 2 > 3 > 4 ...  
I would want: 1 > 2 > 3 > 4 > 3 > 2 > 1 > 2 > 3 > 4 > 3 > 2 >  1 ...
Is there a way ?
If not – can you make this possible ?

THANK YOU !!!</div>

**Comment by vltansky** [comment]
see https://swiperjs.com/swiper-api#param-rewind

**Comment by ttsoares** [comment]
`<Swiper
        spaceBetween={30}
        loopedSlides={3}
        centeredSlides={true}
        autoplay={{
          delay: 2500,
          disableOnInteraction: false,
        }}
        rewind={false}
        pagination={{
          clickable: false,
        }}
        navigation={false}
        modules={[Autoplay, Pagination, Navigation]}
        className="mySwiper"
      >`
Even though the loop sequence is:  1 > 2 > 3 > REWIND TO 1 > 2 > 3.
I would like: 1 > 2 > 3 > 1 > 2 > 3
