### ISSUE TITLE
Swiper Skips Slides Containing Fullscreen Videos

### ISSUE THREAD

**Issue by RodoMedical** [nolimits4web/swiper#5425]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/Josh0531/vr16b8np/5/

### Bug description

When displaying fullscreen videos in consecutive slides (at least 3 consecutive and videos must be playing/have been played), and when mousewheel is enabled, scrolling by using the mousewheel through a page with a fullscreen video will skip/scroll past through the  consecutive fullscreen slides.

### Expected Behavior

Scrolling with mousewheel will scroll responsively to how much I've scrolled.
It should stop at the slide I stopped scrolling at.

### Actual Behavior

After landing on the slide, it automatically scrolls on to the next slide (depending on which direction was scrolled in).

### Swiper version

7

### Platform/Target and Browser Versions

Safari, Chrome, macOS, Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Can not see such bug on macOs and Chrome
https://user-images.githubusercontent.com/999588/152324335-77a09cca-0b85-4daa-b051-9d753c923f6c.mov

**Comment by RodoMedical** [comment]
> Can not see such bug on macOs and Chrome
> 
> * https://user-images.githubusercontent.com/999588/152324335-77a09cca-0b85-4daa-b051-9d753c923f6c.mov
> * https://www.dropbox.com/s/x6qk2tbz2wkpdzh/swiper-mousewheel.mov?dl=0

I forgot to mention that this only happens when scrolling with the trackpad.

**Comment by nolimits4web** [comment]
This is what I did, video captured on MacBook with trackpad scrolling

**Comment by RodoMedical** [comment]
That's odd. Then why does it keep happening on the MacbookPro, Lenovo Thinkpad, and Lenovo Ideapad that I am using?

Maybe I coded the fiddle wrong, as it works in this video.
https://user-images.githubusercontent.com/98857122/152420638-f633a685-c50e-4f0d-96d3-e5cb82c806e6.mp4
Here is a video of it occurring on my Lenovo Thinkpad.
For clarity, every time my cursor leaves the frame, it means that the swiper scrolled by itself, not from me scrolling.

Could you please retry on this JSFiddle?
https://jsfiddle.net/Josh0531/vr16b8np/24/

Also, after some more testing, I found that it only occurs if your cursor is in the swiper frame, is unaffected by mousewheel sensitivity, and it takes a moment to activate. So far, the only way I've been able to mitigate this effect is by scrolling softly.
I don't think it has anything to do with mousewheel inertia  as it doesn't work on any of the regular slides. 

Please let me know if this is not a problem with Swiper.

**Comment by gunesbizim** [comment]
> That's odd. Then why does it keep happening on the MacbookPro, Lenovo Thinkpad, and Lenovo Ideapad that I am using?
> 
> Maybe I coded the fiddle wrong, as it works in this video. https://user-images.githubusercontent.com/98857122/152420638-f633a685-c50e-4f0d-96d3-e5cb82c806e6.mp4 Here is a video of it occurring on my Lenovo Thinkpad. For clarity, every time my cursor leaves the frame, it means that the swiper scrolled by itself, not from me scrolling.
> 
> Could you please retry on this JSFiddle? https://jsfiddle.net/Josh0531/vr16b8np/24/
> 
> Also, after some more testing, I found that it only occurs if your cursor is in the swiper frame, is unaffected by mousewheel sensitivity, and it takes a moment to activate. So far, the only way I've been able to mitigate this effect is by scrolling softly. I don't think it has anything to do with mousewheel inertia as it doesn't work on any of the regular slides.
> 
> Please let me know if this is not a problem with Swiper.

I was experiencing same issue with the SwiperJS but in my case it seemed like if the html video element overflows its parent container I believe somehow swiper identifies object as out of viewport and scrolls to next slide as it tries to fit object inside a slide. This only happens for me if I use full page sliders. Another weird behaviour for me was this issue wasn't reproducible while developer console open.   But I wasn't able to reproduce the issue on the fiddle that you shared.
