### ISSUE TITLE
Disabling swiper on element

### ISSUE THREAD

**Issue by rodionbgd** [nolimits4web/swiper#5429]
### Clear and concise description of the problem

I faced difficulties, trying to disable scroll event on the particular element.

### Suggested solution

What about adding the following property
disableSwiper: HTMLElement[]? 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-noSwiping
