### ISSUE TITLE
Grid not working properly when nested in any HTML element

### ISSUE THREAD

**Issue by legonzian** [nolimits4web/swiper#5430]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-grid-forked-ggtny

### Bug description

When the Swiper is nested in any HTML element, the grid doesn't work anymore. When you remove the outer most div element, the grid is working again as expected.

### Expected Behavior

Grid should still working when Swiper is nested in a HTML Element

### Actual Behavior

Wrapping Swiper in a HTML Element breaks grid view

### Swiper version

7.4.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
How about some CSS basics, setting:
```
position: relative;
height: 100%;
```
on that element in that demo solves the issue
