### ISSUE TITLE
how to use panorama slider, how to use panorama plugins

### ISSUE THREAD

**Issue by Bugslogger** [nolimits4web/swiper#5433]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://panorama-slider.uiinitiative.com/

### Bug description

i am not able to use panorama swiper plugins

### Actual Behavior

panorama not imported as module

### Swiper version

8.0.2

### Platform/Target and Browser Versions

browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please don't use Swiper issues for UI Initiative support. Contact account you support (Framework7 of Swiper) on Patreon and through Patreon messages
