### ISSUE TITLE
Regression: missing 'lock' @output in Angular (again)

### ISSUE THREAD

**Issue by xumepadismal** [nolimits4web/swiper#5439]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/nolimits4web/swiper/pull/5225/files#diff-bfa627463b910d30122bd97c77f46167402610e987ac7922fb67145fb0104525L398

### Bug description

It seems that after merging https://github.com/nolimits4web/swiper/pull/5225 the `@Output('lock')` was removed by a mistake

### Swiper version

8.0.3

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
Wow, that's awkward :)
Thanks for reporting!
