### ISSUE TITLE
Loop problem

### ISSUE THREAD

**Issue by wtorsi** [nolimits4web/Swiper#544]
Hello,  i have a strange issue,
if scroll swiper to the last slide ( here http://intech-sport.ru/ ),  there will be the end of the slider (empty area), while the loop option is set to true.  When i call resizeFix method, everything becomes fine. 

Do you have any solutions for this?

**Comment by fdamore1984** [comment]
Hi i got  the same problem and i do not understand how to fix, even if i add loopAdditionalSlides or loopedSlides i always got an empty area on the last slide. It appen only when i slide on right direction, to the left the loop works good
