### ISSUE TITLE
Virtual Slide Performance is reduced with large dynamic data set in Ionic Android Platform

### ISSUE THREAD

**Issue by vimalkumar015** [nolimits4web/swiper#5446]
I am using Swiper js with ionic-angular + Capacitor js mobile app. In some scenario my app need to show more than 6000 slides. which slides data will be fetched dynamically. I use Virtual module to show slides.

In ios and web there is no performance lag. But in Android after 6000 slides loaded app is getting laggy and gets crashed.

HTML:

        <swiper id="StkSlider" #StkSlider [config]="VerSlideOpts" (slideChange)="stockSetClock($event)" [virtual]="true">

          <ng-template swiperSlide *ngFor="let item of copySrcData; index as i">

            <div class="swiper-slide-wrapper">
              <p class="StkName">{{name}}</p>
              <p class="StkTicker">({{item.ticker}})</p>
              <p class="StkScore" [ngStyle]="{'color': getmedcolor(item.score)}">{{item.val.toFixed(1)}}</p>
              <div class="StkPriceWrapper" *ngIf="price">
                <p class="StkPriceLabel">Stock Price</p>
                <p class="StkPrice">{{item.currency}} {{item.price.toFixed(1)}}</p>
              </div>
              <div class="StkWeightWrapper" *ngIf="price">
                <p class="StkWeightLabel">Weight</p>
                <p class="StkWeight">{{weight}}%</p>
              </div>
            </div>

          </ng-template>

        </swiper>

swiper config:

     VerSlideOpts: SwiperOptions = {
    slidesPerView: 1,
    direction: 'vertical',
    loop: false,
    observeParents: true,
    observer: true,
    observeSlideChildren: true,
    followFinger: false,
    allowTouchMove: false,
    passiveListeners: true,
    slideToClickedSlide: true,
    init: true
  }

[angular Demo](https://codesandbox.io/s/swiper-virtual-slides-angular-forked-d6184?file=/src/app/app.component.ts)
[Ionic Demo](https://codesandbox.io/s/epic-gwen-hi8dv)

Need better solution ASAP to over come this challenge. 
Any Advice would be very helpful.

_Originally posted by @vimalkumar015 in https://github.com/nolimits4web/swiper/discussions/5445_

**Comment by vimalkumar015** [comment]
[angular Demo](https://codesandbox.io/s/swiper-virtual-slides-angular-forked-d6184?file=/src/app/app.component.ts)
[Ionic Demo](https://codesandbox.io/s/epic-gwen-hi8dv)

**Comment by aftabkhalid** [comment]
The swiper is not working with `longSwipes: false,`

**Comment by GRDtechlab** [comment]
> [angular Demo](https://codesandbox.io/s/swiper-virtual-slides-angular-forked-d6184?file=/src/app/app.component.ts) [Ionic Demo](https://codesandbox.io/s/epic-gwen-hi8dv)

Can You please see why in stackblitz I am getting error `Can't find package:swiper_angular` here is demo in stackbliz link. Thanks!

https://stackblitz.com/edit/angular-ivy-gqpzhp?file=src%2Fapp%2Fapp.module.ts

**Comment by vimalkumar015** [comment]
> > [angular Demo](https://codesandbox.io/s/swiper-virtual-slides-angular-forked-d6184?file=/src/app/app.component.ts) [Ionic Demo](https://codesandbox.io/s/epic-gwen-hi8dv)
> 
> @vimalkumar015 Can You please see why in stackblitz I am getting error `Can't find package:swiper_angular` here is demo in stackbliz link. Thanks!
> 
> https://stackblitz.com/edit/angular-ivy-gqpzhp?file=src%2Fapp%2Fapp.module.ts

@GRDtechlab 
i checked your demo. it seems stackbltiz works only upto swiper@6.4.15 version.

Solution:

1. in stack blitz package name add `swiper@6.4.15` instead of `swiper`.
2. remove `import 'swiper/angular';` from app.module.ts
3. in style.css just add `@import "~swiper/swiper-bundle";`

**Comment by vimalkumar015** [comment]
Hello everyone and @nolimits4web ,
In order to resolve this issue, i tried to dug little deeper. I think this will be the cause of the problem.

Even though slider `[virtual]:true` and element only showing 2/3 available elements, because of 
`angular *ngfor, n number of ng-template` has been getting created and memory also getting allocated for it.


![Screenshot 2022-02-17 at 3 44 10 PM](https://user-images.githubusercontent.com/19769860/154457331-7512ad40-5a9a-4f72-a5c9-a081769eb8a3.png)


in the above image i have created 7000 slides with swiperjs. you can see memory holds 7015 TemplateRef (including tabs and other pages).

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
