### ISSUE TITLE
ControllerOptions control does not work when passed an array of Swiper[]

### ISSUE THREAD

**Issue by smileypop** [nolimits4web/swiper#5459]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/smileypop/wordy

### Bug description

I have 3 swipers with two-way controls setup.
- Swiper 1 controls Swiper 2
- Swiper 2 controls Swiper 1
- Swiper 3 controls an array [Swiper 1, Swiper 2]

`ControllerOptions` allows control to be defined as either a single instance of Swiper or an array of Swipers.

However, during actual usage the controller only functions when assigning a single instance, not an array.

Here is the implementation:

```
export interface ControllerOptions {
  /**
   * Pass here another Swiper instance or array with Swiper instances that should be controlled
   * by this Swiper
   */
  control?: Swiper | Swiper[];

  /**
   * Set to `true` and controlling will be in inverse direction
   *
   * @default false
   */
  inverse?: boolean;

  /**
   * Defines a way how to control another slider: slide by slide
   * (with respect to other slider's grid) or depending on all slides/container
   * (depending on total slider percentage).
   *
   * @default 'slide'
   */
  by?: 'slide' | 'container';
}
```

### Expected Behavior

- Swiper 1 controls Swiper 2 (OK)
- Swiper 2 controls Swiper 1 (OK)
- Swiper 3 controls an array [Swiper 1, Swiper 2] (OK)

### Actual Behavior

- Swiper 1 controls Swiper 2 (OK)
- Swiper 2 controls Swiper 1 (OK)
- Swiper 3 controls an array [Swiper 1, Swiper 2] (Not OK)

### Swiper version

8.0.5

### Platform/Target and Browser Versions

macOS 12.1 Chrome 97.0.4692.99

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by thplat** [comment]
The same happens for Vue

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Svelte components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
