### ISSUE TITLE
Virtual slides ignore initialSlide in the beginning

### ISSUE THREAD

**Issue by Serg-Mois** [nolimits4web/swiper#5463]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/nolimits4web/swiper/issues/2755

### Bug description

https://github.com/nolimits4web/swiper/issues/2755

Hell, the problem is still relevant.

### Swiper version

8.0.5

### Platform/Target and Browser Versions

Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
As you don't provide up to date live example and other details, I assume there is no such issue, as you can see it works here perfectly https://codesandbox.io/s/swiper-virtual-slides-forked-zsdwq
