### ISSUE TITLE
Virtual slides ignore initialSlide in the beginning

### ISSUE THREAD

**Issue by Serg-Mois** [nolimits4web/swiper#5466]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-fade-angular-forked-n2ycd?file=/src/app/app.component.ts

### Bug description

https://github.com/nolimits4web/swiper/issues/5463

Hell, the problem is still relevant.

You provided code here - https://codesandbox.io/s/swiper-virtual-slides-forked-zsdwq, but it's not working with angular 
see:
https://codesandbox.io/s/swiper-effect-fade-angular-forked-n2ycd?file=/src/app/app.component.ts

Settings virtual slides as in your example: :
 virtual {
  slides: ...
}
doesn't display slides at all.

when I set slides using ngFor and swiperSlide directive - they are displayed, but the problem with initialSlide is relevant.

### Swiper version

8.0.5

### Platform/Target and Browser Versions

Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by snimavat** [comment]
Here's an example with vuejs https://github.com/nolimits4web/swiper/issues/6454

**Comment by donaldxdonald** [comment]
I've encountered the same issue and I've set up a reproduction.

https://codesandbox.io/p/sandbox/angular-swiperjs8-virtual-initial-slide-30v8w8?file=%2Fsrc%2Fapp%2Fapp.component.html
