### ISSUE TITLE
Getting error "class constructors must be invoked with 'new'"

### ISSUE THREAD

**Issue by akashrwx** [nolimits4web/swiper#5467]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Unable to provide

### Bug description

I installed swiper using the guide at the website. But after running the code I am getting this error, **class constructors must be invoked with 'new'**

I am using "gatsby": "^4.6.2", "react": "^17.0.1",

https://www.awesomescreenshot.com/image/22166623?key=6af1f523f435087c812b3223946d2e7d

Getting error on even on default example

`<Swiper
            spaceBetween={50}
            slidesPerView={3}
            onSlideChange={() => console.log('slide change')}
            onSwiper={(swiper) => console.log(swiper)}>
            <SwiperSlide>Slide 1</SwiperSlide>
            <SwiperSlide>Slide 2</SwiperSlide>
            <SwiperSlide>Slide 3</SwiperSlide>
            <SwiperSlide>Slide 4</SwiperSlide>
          </Swiper>`

### Swiper version

8.0.6

### Platform/Target and Browser Versions

Windows 10, Firefox and chrome

### Validations

- [x] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by qiwang97** [comment]
same error here

**Comment by Fuadissa** [comment]
I don't understand your solution am having the same problem.
Am importing swiper from swiper react from the example shown in the swiper J's website
