### ISSUE TITLE
Autoplay option to start when swiper in view port

### ISSUE THREAD

**Issue by mbcod3** [nolimits4web/swiper#5469]
### Clear and concise description of the problem

Swiper autoplay starts after page load even though its not in view port.

You can see here autoplay starts just after page loads and keeps going:

https://gsgs1y.sse.codesandbox.io/

### Suggested solution

 It would be great if there was option to add checkInView parameter for autoplay so that it pauses autoplay when swiper container is not in viewport and starts autoplay when it  is in view port. This way user scroll down to the swiper container it starts autoplay, user scroll down further autoplay pauses.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
