### ISSUE TITLE
Jumps slides when scrolling via touchpad

### ISSUE THREAD

**Issue by marius-jopen** [nolimits4web/swiper#5471]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://andrebato.com/films

### Bug description

I use SwiperJS as fullscreen slider for vertical scrolling.
When using the mouse-wheel, it nicely changes the slides.
But when using the touchpad on a Macbook, it jumps slides. 
I have a feeling, that it gets triggered many times, when you stay with your fingers on the touchpad.

`````
<Swiper
	modules={[Navigation, Mousewheel,Pagination, Scrollbar, A11y]}
	slidesPerView={1}
	spaceBetween={0}
	mousewheel="{true}" 
	pagination={{ clickable: true }}
	direction={"vertical"}
	speed= {350}
	parallax = "{true}"
	navigation={{
		nextEl: ".swiper-button-next",
		prevEl: ".swiper-button-prev",
	}}
	scrollbar={{ draggable: true }}
	bind:swiper={mySwiper}
	on:beforeTransitionStart={slideChange}
	on:reachBeginning={reachBeginning}
	on:reachEnd={reachEnd}
	>
	{#each sortedFilms as { data, slugs }, projectIndex}
		{#if data.thumbnail_vimeo[0]}
			<SwiperSlide>
				<a href="/films/{slugs[0]}" sveltekit:prefetch class="block item relative status-{status} previous-{previous} next-{next}">
						<video playsinline poster="{data.image.Big.url}" autoplay loop muted class="w-screen object-cover h-screen">
							<source src={data.thumbnail_vimeo[0].text} type="video/mp4" />
							Your browser does not support the video tag.
						</video>

						<div class="px-7 absolute bottom-6 z-20 text-5xl font-bold">
							{data.title[0].text}

							<br />

							{#if data.teaser[0]}
								{data.teaser[0].text}
							{/if}
						</div>
					</a>
				</SwiperSlide>
			{/if}
		{/each}
	</Swiper>
`````

### Expected Behavior

When using the touchpad on a Macbook, it jumps the slides multiple times.

### Actual Behavior

When using the touchpad on a Macbook, I would like to change the slide once and not multiply times.

### Swiper version

7.2.0

### Platform/Target and Browser Versions

macOS Chrome /Z Brave

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Already discussed here many times, there is no way to detect trackpad and differentiate it from mousewheel, and there is no perfect way to detect inertia scrolling. If you want perfect control with trackpad, use/enable `cssMode`
