### ISSUE TITLE
Two joined swipers occasionally vanish when transition with buttons

### ISSUE THREAD

**Issue by BenGenPub** [nolimits4web/swiper#5472]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://paslay-group.flywheelsites.com/team/colleen-von-hoene/

### Bug description

whenever you press the previous or next buttons, the slides vanish, but can appear again if you manually drag or press the previous or next button again

### Expected Behavior

For the slides to not vanish

### Actual Behavior

Slides occasionally vanish

### Swiper version

8

### Platform/Target and Browser Versions

Chrome on WIndows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The link you provided doesn't illustrate the issue (at least I can't see it), would be good to see live isolated example with the issue in CodeSandbox
