### ISSUE TITLE
Display problem when number of slides is less then specified in slidesPerView

### ISSUE THREAD

**Issue by Psytanium** [nolimits4web/swiper#5473]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.woodandgas.com/index_all.php

### Bug description

Hello,

I have multiple sliders in 1 page, the number of slides is dynamic to reflect the number of categories and sub categories.

Some sliders have only 3 slides, while others have more than 10.

The slidesPerView is set to 4.5.

All sliders are displayed very well, unless the sliders with number of slides less then 4, the display is wrong and not working.

To make sure the problem is the number of slides, I changes the slidesPerView to 2.5, and the slider is displayed properly.

### Expected Behavior

When number of slides is less than specified in the slidesPerView, the slides should appear properly similar to the other sliders.

### Actual Behavior

When number of slides is less than specified in the slidesPerView, the slides box is small, floated to the right, and do not rotate (Slide).

### Swiper version

7.0.8

### Platform/Target and Browser Versions

Firefox 97.0 (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The link you provided doesn't illustrate the issue (at least I can't see it), would be good to see live isolated example with the issue in CodeSandbox

**Comment by Psytanium** [comment]
Hello, 

While trying to reproduce the problem on a clean demo, i found the problem is fixed by adding this missing css :

<style>
.swiper {
    width: 100%;
    height: 100%;
}
</style>

Thank you and sorry for my lack of attention.

Btw, i really like the abilities of this slider. For example we can insert decimal numbers in slidesPerView to show half slide per screen.

**Comment by Abdulateef-Muhammad** [comment]
have you open a PR yet?
cuz this issue it should be fixed, 
and I faced recently
