### ISSUE TITLE
Events don't get fired in Swiper Vue

### ISSUE THREAD

**Issue by matevegh** [nolimits4web/swiper#5480]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-vue-forked-kxbq7b?file=/src/App.vue

### Bug description

The documentation states the following:

Swiper component supports all [Swiper events](https://swiperjs.com/api/#events), including additional `swiper` event that returns swiper instance as soon as possible. For example:

```vue
<swiper @swiper="..." @slideChange="..." @reachEnd="..." ...></swiper>
```

I tested multiple events this way and none of them gets fired, but the additional `swiper` event. In the [reproduction](https://codesandbox.io/s/swiper-default-vue-forked-kxbq7b?file=/src/App.vue) I used the example from the [Swiper Vue documentation](https://swiperjs.com/vue#usage) to make sure the issue is not caused by something else.

### Swiper version

8.0.6

### Platform/Target and Browser Versions

macOS Chrome 98

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by matevegh** [comment]
Hold on... I am new to CodeSandbox and was expecting to see the logs in the console, but they didn't appear. However, I just opened the app in a new window and it works like a charm. I need to further investigate the possible cause of this issue in my own project. I will update this issue soon.

**Comment by matevegh** [comment]
I found out that the issue is in the documentation. Instead of `@slideChange` it should be `@slide-change`. I have just submitted a PR to [swiper-website](https://github.com/nolimits4web/swiper-website).

**Comment by matevegh** [comment]
I have just revisited my reproduction in CodeSandbox and it seems that both `@slideChange` and `@slide-change` works there, but not in my project. I'll do some further investigation later to find the difference.

**Comment by nolimits4web** [comment]
That is definitely something on your side, everything is correct with events and they work as it stated in docs https://codesandbox.io/s/swiper-default-vue-forked-u3hkik?file=/src/App.vue

**Comment by matevegh** [comment]
Yeah, you are right. I found out the problem was that I am running Vue on prerendered HTML and the browser automatically changes uppercase characters in attribute names to lowercase, so `@slideChange ` became `@slidechange`. That is why only the `@slide-change` syntax works in my case. Sorry for the false alarm. And thanks for your work! ❤️
