### ISSUE TITLE
Swiper not working as expected in Angular 13

### ISSUE THREAD

**Issue by woozhanwei** [nolimits4web/swiper#5486]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-angular-example-forked-ssfkdp?file=/package.json

### Bug description

Hi there,
I am referencing the code from:
[swiper-angular-codesandbox.io](https://codesandbox.io/s/swiper-angular-example-9edj9)
which is taken from https://swiperjs.com/angular page.
However, I try to update all the angular related dependencies to the latest version which is v13, the code breaks and can't show the swiper correctly.

Can you help me on this?

### Expected Behavior

the expectation is the display showed in the 
https://codesandbox.io/s/swiper-angular-example-9edj9 which is taken from https://swiperjs.com/angular page 
should be same with 
https://codesandbox.io/s/swiper-angular-example-forked-ssfkdp?file=/package.json even after angular is updated from v12 to v13

### Actual Behavior

Showing only first header of the html after update angular related dependencies inside the package.json to v13

![image](https://user-images.githubusercontent.com/32919949/154993213-19a37de0-cb4c-47f0-8b2c-4d1d472bc4f8.png)

### Swiper version

7.0.0

### Platform/Target and Browser Versions

Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vltansky** [comment]
https://codesandbox.io/s/swiper-angular-example-forked-hb8ypr?file=/package.json

works for me

**Comment by woozhanwei** [comment]
> https://codesandbox.io/s/swiper-angular-example-forked-hb8ypr?file=/package.json
> 
> works for me

Hi vltansky,
Can you open the rendered page in new chrome tab?

Thank you.

**Comment by woozhanwei** [comment]
Hi there,
I will close this issue since I don't see it anymore.

Just realise I need to add this to **src/styles.css** in order to make it work in my local app.

@import "~swiper/swiper-bundle.css";
body,
html {
  padding: 0;
  margin: 0;
  position: relative;
  height: 100%;
}

.swiper {
  width: 100%;
  height: 300px;
  margin: 50px auto;
}

.swiper-slide {
  background: #f1f1f1;
  color: #000;
  text-align: center;
  line-height: 300px;
}

Thank you.
Best Regards,
Woo Zhan Wei
