### ISSUE TITLE
BUTTON tag inside slide snaps to next slide on click

### ISSUE THREAD

**Issue by teleskop150750** [nolimits4web/swiper#5490]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-per-view-forked-pnqu3l?file=/index.html

### Bug description

when I use button tag inside a slide when I do a click on the tag it slide without animation to the next slide.

### Expected Behavior

nothing

### Actual Behavior

slides to the next slide without animating

### Swiper version

8.0.6

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [x] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by silasbispo01** [comment]
Same problem

**Comment by johnozbay** [comment]
Found the answer here : https://github.com/nolimits4web/Swiper/issues/3149#issuecomment-1044631964
Setting `watchSlideProgress` to `true` fixed the problem for our use case.

---

Also possibly related to #5437

**Comment by andreylc** [comment]
confirm the problem

**Comment by kwastaras1337** [comment]
have the same problem.......

**Comment by joelthorner** [comment]
same here

**Comment by maxbronnikov10** [comment]
same problem

**Comment by maxbronnikov10** [comment]
> Found the answer here : [#3149 (comment)](https://github.com/nolimits4web/swiper/issues/3149#issuecomment-1044631964) Setting `watchSlideProgress` to `true` fixed the problem for our use case.
> 
> Also possibly related to #5437

omg need to set `watchSlidesProgress` to `true`.  `watchSlideProgress` doesnt exist...

**Comment by mediaformat** [comment]
> > Found the answer here : [#3149 (comment)](https://github.com/nolimits4web/swiper/issues/3149#issuecomment-1044631964) Setting `watchSlideProgress` to `true` fixed the problem for our use case.
> 
> omg need to set `watchSlidesProgress` to `true`. `watchSlideProgress` doesnt exist...

@nolimits4web True story! Seems to have slide out of the code
![Screen Shot 2023-02-22 at 1 38 53 PM](https://user-images.githubusercontent.com/2895351/220754480-c9c49832-3ff2-4483-9e61-7b2ec1ed9cd1.png)
