### ISSUE TITLE
Direct focusable children of swiper slide cannot be clicked when they are in previous or next slide on tablet and mobile when slidesPerView is not a whole number

### ISSUE THREAD

**Issue by Danogot516** [nolimits4web/swiper#5494]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-forked-4dpsk7?file=/index.html

### Bug description

When using slidesPerView with a float number (2.5, 3.2 etc.) and the direct child of the swiper slide is a focusable element (`<a>, <button>, <div tabindex="0">`) a click event doesn't register on that link, instead swiper changes the clicked slide to be the active slide. This only happens on mobile and tablet touch devices.

### Expected Behavior

When clicking on the focusable element inside the slide to have a click register.

### Actual Behavior

Clicking on any slide other than the active one while using tablet or mobile results in that slides snapping to the active position and becoming the active slide without a click event registering on the link.

### Swiper version

8.0.6

### Platform/Target and Browser Versions

Android, iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Krajenn** [comment]
Same problem

**Comment by silasbispo01** [comment]
Same problem
