### ISSUE TITLE
`freeMode` in `cssMode`

### ISSUE THREAD

**Issue by nathanng312** [nolimits4web/swiper#5499]
### Clear and concise description of the problem

Please see this [gist](https://gist.github.com/nathanng312/c175cee292a8feba1400724eb552472f) as a reference on what I am trying to do, you can view it by copying this file to `./playground/react` in the repo. There are two workarounds inside the `onSwiper` callback. You can try uncommenting them to see the undesired outcome.

As a developer using Swiper I want to fulfil the followings:
1. users can scroll horizontally using their magic trackpads, where they are [two-finger events in safari](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW8)
  i. must use `cssMode` (`freeMode` is not working)
2. users can scroll freely without snapping to a slide
  i. similar to `{sticky: false}` in `freeMode`
3. during `onReachEnd()` with `slidesPerView = <floating point number> | 'auto'`, it can fetch and add dynamic content without snapping back to the previous active slide
  i. without using `freeMode`, [here](https://github.com/nolimits4web/swiper/blob/b4cdea842207f12603d09cbfa2828c66062273c3/src/core/core.js#L376) will call `slideTo()` and snap back to previous active slide. Hence, it would appear there is a flickering when loading more data in `onReachEnd()`.

### Suggested solution

In module `FreeMode` we could simply set `scroll-snap-type: none` if `{sticky: false}`. Other parameters (e.g. momentum) are ignored in `cssMode`.

In this way, I can simply call swiper with
```jsx
<Swiper
  ...
  cssMode={true}
  freeMode={{sticky: false, enable: true}}
  ...
>
  ...
</Swiper>
```

### Alternative

Extract the `sticky` option out from `FreeMode` to `Core`

In this way, I can simply call swiper with
```jsx
<Swiper
  ...
  cssMode={true}
  sticky={false}
  freeMode={{ enable: true }}
  ...
>
  ...
</Swiper>
```

### Additional context

I attached the gist above

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
What is the issues with just setting `scroll-snap-type: none` in CSS to wrapper?
