### ISSUE TITLE
IE10 throws error when appending slides

### ISSUE THREAD

**Issue by patrickmallahan** [nolimits4web/Swiper#550]
When I try to append slides dynamically to a swiper, I'm getting an error as follows:

```
"Error: Invalid argument.\n   at insertAfter (http://localhost/Scripts/Child/idangerous.swiper-2.4.js:285:17)\n   at append (http://localhost/Scripts/Child/idangerous.swiper-2.4.js:254:17)\n   at Anonymous function (http://localhost/Scripts/Child/page_setup.js:96:9)\n   at each (http://localhost/Scripts/jquery-1.10.2.js:665:6)\n   at setupSwipers (http://localhost/Scripts/Child/page_setup.js:94:5)\n   at Anonymous function (http://localhost/Sales/DSR:215:21)\n   at fire (http://localhost/Scripts/jquery-1.10.2.js:3048:5)\n   at fireWith (http://localhost/Scripts/jquery-1.10.2.js:3160:7)\n   at ready (http://localhost/Scripts/jquery-1.10.2.js:433:3)\n   at completed (http://localhost/Scripts/jquery-1.10.2.js:104:4)"
```

The code at the insertAfter function that's causing the error is:

```
_this.wrapper.insertBefore(el, beforeSlide);
```

The error is occurring because when insertAfter is being called, the 'index' parameter isn't a number.  In my case, I'm getting NaN because in the append function, it's calculating the index that gets passed as follows:

```
el.insertAfter(_this.slides.length - _this.loopedSlides)
```

_this.slides.length is equal to zero as this is currently the first pass.  _this.loopedSlides is equal to NaN which I believe to be the source of my problem.  Why would _this.loopedSlides be equal to NaN?

**Comment by frey1esm** [comment]
AngularJS / Ionic `ng-repeat` throws error `"TypeError: Cannot read property 'insertBefore' of null"` when the source array is updated:

        <div class="swiper-container">
            <div class="swiper-wrapper">
                
                <div class="swiper-slide" ng-repeat="slide in files"> 
                  <img data-ng-src="{{slide.filename}}"> 
                </div>
            </div>
        </div>
