### ISSUE TITLE
Vue useSwiper() instance is undefined

### ISSUE THREAD

**Issue by braincomb** [nolimits4web/swiper#5505]
Bug recreated in Stackblitz:

https://stackblitz.com/edit/vue-ncpxdr?file=src/App.vue

### Discussed in https://github.com/nolimits4web/swiper/discussions/5504

<div type='discussions-op-text'>

<sup>Originally posted by **braincomb** February 28, 2022</sup>
I'm trying to use the new `useSwiper` context hooks in Vue, but it's returning undefined:

```js
<script setup lang="ts">
import { Swiper, SwiperSlide, useSwiper } from 'swiper/vue/swiper-vue.js';

const swiper = useSwiper();

swiper.value.update();
</script>
```

`Uncaught TypeError: swiper is undefined`

Using v8.0.6, what am I doing wrong?

Wanted to ask here before opening issue,  @nolimits4web @vltansky any ideas?
</div>

**Comment by coda-fandom** [comment]
Same error occured when I use in react 

```
function CuratorPage() {

  const swiper = useSwiper();

  const dispatch = useDispatch();

  return (
    
        <div className={classes.swiperWrapper}>
          <div className={classnames(classes.swiperNav, classes.swiperNavPrev)} onClick={() => {
            swiper.slidePrev()
          }}>
            <Icon type="arrow-left" size={42} ></Icon>
          </div>
          <Swiper
            modules={[Navigation,]}
            slidesPerView={5}
            centeredSlides={true}
            spaceBetween={50}
            navigation={false}
            className="mySwiper">
            <SwiperSlide className={classes.swiperItem}>1</SwiperSlide>
            <SwiperSlide className={classes.swiperItem}>2</SwiperSlide>
            <SwiperSlide className={classes.swiperItem}>3</SwiperSlide>
          </Swiper>
          <div className={classnames(classes.swiperNav, classes.swiperNavNext)} onClick={() => {
            swiper.slideNext()
          }}>
            <Icon type="arrow-right" size={42} ></Icon>
          </div>
        </div>
      </section>
```
![image](https://user-images.githubusercontent.com/99392875/156124838-a526d8a2-fd01-4045-9bda-64626baae837.png)

**Comment by nolimits4web** [comment]
Apparently these hooks must be used in components which are inside of the Swiper

**Comment by BiscuitCoder** [comment]
I had the same problem in vue3，^8.0.7

**Comment by luojiong** [comment]
hi guys  have you solved this problem? I'm in **Vue 3.0** encountered the same error。

**Comment by alexcvcoelho** [comment]
I had a same problem and solved with this

```html 
<swiper class="swiper">
```

on use swiper ref:

``` javascript 
const swiper = document.querySelector(".swiper").swiper;
swiper.slideNext();
```

**Comment by hemengke1997** [comment]
```
const swiperRef = ref()

swiperRef.value.$el.swiper.slideNext()
```

**Comment by lzdml** [comment]
<img width="1005" alt="image" src="https://github.com/nolimits4web/swiper/assets/137750167/1544d08c-75f3-4991-99a5-590be5f80d49">
<img width="866" alt="image" src="https://github.com/nolimits4web/swiper/assets/137750167/04de84d9-44f5-412a-aaab-780c874b7e79">

![image](https://github.com/nolimits4web/swiper/assets/137750167/a4c987ff-95ab-4857-9a20-6ff3358491e7)

If it is written like this, it is printed out or empty
