### ISSUE TITLE
Scroll Multiple Slides at once using next/prev buttons

### ISSUE THREAD

**Issue by jellohouse** [nolimits4web/swiper#5508]
### Clear and concise description of the problem

Say I have 3 slides per view. I want that when I press next navigation button, it slides 3 slides at once. 
So that now the first slide I see would be the 4th.

Because right now I would have to press the next button 3 times to get the 4th slide in that position I want.

### Suggested solution

Add a property like `slidesPerClick={3}`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is a slidesPerGroup parameter for this

**Comment by SerzhanHelena** [comment]
Hi there. I'm trying to use slidesPerGroup parameter for the same purpose as described above, but if slidesPerView = 3 and slides length is 4, it doesn't work as expected
