### ISSUE TITLE
Thumbs model not work

### ISSUE THREAD

**Issue by shuiche-it** [nolimits4web/swiper#5511]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/c4f0q?file=/src/App.vue

### Bug description

Thumbs model not work

### Swiper version

8.0.6

### Platform/Target and Browser Versions

macOS chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by shuiche-it** [comment]
success code:

```
let thumbsSwiper = ref(null)
function setThumbsSwiper (swiper) {
    thumbsSwiper.value = swiper
}
const modules2 = [FreeMode, Navigation, Thumbs]
```

**Comment by Vlada650** [comment]
> success code:
> 
> ```
> let thumbsSwiper = ref(null)
> function setThumbsSwiper (swiper) {
>     thumbsSwiper.value = swiper
> }
> const modules2 = [FreeMode, Navigation, Thumbs]
> ```

Thank you so much!!!!!!!!!

**Comment by Choumode** [comment]
> success code:
> 
> ```
> let thumbsSwiper = ref(null)
> function setThumbsSwiper (swiper) {
>     thumbsSwiper.value = swiper
> }
> const modules2 = [FreeMode, Navigation, Thumbs]
> ```
It's useful!!!!! Thanks!
