### ISSUE TITLE
Radio input inside swiper slide

### ISSUE THREAD

**Issue by DarkRaveN85** [nolimits4web/swiper#5513]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/adasdad/pen/OJOaGZd

### Bug description

Hi,

Swiper 8.0.6
If you add radio inputs inside the slide (and any form elements - buttons, checkboxes, text inputs, etc.) and for example click on the radio in the 4th slide, then the carousel "jumps" and makes the slide in which you checked the input active and moves it to the first position.
Before that, I used Swiper 6.6.2 of the swiper and there was no such problem.

### Swiper version

8.0.6

### Platform/Target and Browser Versions

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by DarkRaveN85** [comment]
> I have the same problem with the Select tag

I could not solve it, I returned to v6.6.2

**Comment by RomkaGall** [comment]
Yes, on 6.8.4 it is working. Thank you!

**Comment by davide93** [comment]
#5524

**Comment by Blacklightdesign** [comment]
I have a solution that mobile touch on ui elements like links or select fields no longer makes the slide jump to first place. Touch events also trigger a focus event. I added a condition to check that the focus event was not triggered by touch.
#6139

**Comment by AhmedNasser1010** [comment]
also same issue in v10.2.0

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
