### ISSUE TITLE
Clicks inside Swiper not working

### ISSUE THREAD

**Issue by peach-inzn** [nolimits4web/swiper#5514]
### Check that this is really a bug

- [X] I confirm

### Bug description

Clicks inside of my Swiper are not registered, although my code is as follows: 
```
<Swiper
  slidesPerView={1}
  loop={true}
  allowTouchMove={false}
  preventClicks={false}
  preventClicksPropagation={false}
>
```
Mouse events are working perfectly, just clicks not. I found a bug discussion about `preventClicks` and `preventClicksPropagation` but setting those to false does not change anything, clicks still don't fire.

### Reproduction 
[CodeSandbox](https://codesandbox.io/s/swiper-default-react-forked-mc8ccc?file=/src/App.jsx)
### Swiper version

8.0.6

### Platform/Target and Browser Versions

macOS Safari 15.3

### Validations

- [x] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by peach-inzn** [comment]
> Hello @peach-inzn. Please provide a online reproduction by [codesandbox](https://codesandbox.io/) or a minimal GitHub repository. You can fork one of our [demos](https://swiperjs.com/demos) in codesandbox to get start. Issues labeled by `missing demo` will be closed if no activities in 3 days.

[CodeSandbox](https://codesandbox.io/s/swiper-default-react-forked-mc8ccc)

**Comment by EduardoBreton** [comment]
I found out by disabling simulateTouch, you can use the mouse events on the children inside the Swiper.

**Comment by linedup** [comment]
We are seeing issues with <a> tags in the sliders being intermittently non-responsive in Chrome osx and sometimes needing multiple clicks to open the simple <a> link. This was corrected by using simulateTouch: false but is not an ideal solution.

**Comment by peach-inzn** [comment]
Hey @EduardoBreton, @linedup, thanks for both of your replies! Unfortunately, I cannot get it to work even with `simulateTouch` set to `false`.

[CodeSandbox](https://codesandbox.io/s/swiper-default-react-forked-mc8ccc?file=/src/App.jsx)

**Comment by nolimits4web** [comment]
```
document
  .querySelector(".mySwiper .mySlide")
  .addEventListener("onclick", function () {
    console.log("clicked");
  });
```

there is no such event like `oclick`
