### ISSUE TITLE
Support for lazy loading video with source tags.

### ISSUE THREAD

**Issue by Antimated** [nolimits4web/swiper#5518]
### Clear and concise description of the problem

I'd like to have the option to lazy load videos inside a swiper instance with support of `source` tags.

I have a swiper that accepts videos AND images. Lazy-loading images is no problem but lazy-loading videos is kinda an issue.

In my example code I lazyload a video (which for some reason works just fine). The issue I'm having is that there is no official support for lazy loading video's, thus there is also no support for the `source` tag to be lazy-loaded. Because of that some browsers (especially chrome on android devices) do play my video's (which is strange because I'm using mp4's in h264 format). Anyway... The only solution would be to serve the video's in `mp4` and `webm` formats and the only way to do that is to use `sources` for my videos.

**HTML:**

```html
<div class="swiper-slide">
     <video width="960" height="540" data-src="video.mp4" preload="none" autoplay="autoplay" muted="muted" playsinline="" loop="loop" class="swiper-lazy">
          Your browser does not support the video tag.
     </video>
</div>
```

**JS:**
Note: my slider accepts images as well as video's.

```javascript
new Swiper(swiperEl, {
    modules: [Lazy],
    slidesPerView: "auto",
    speed: 700,
    centeredSlides: true,
    loop: true,
    preloadImages: false,
    watchSlidesProgress: true,
    lazy: {
        checkInView: true,
        loadPrevNext: true,
    },
});
```

### Suggested solution

I would suggest a html layout looking something like this

Note: maybe it would be nice if we could ommit the `data-src` property on the video tag itself.

```html
<div class="swiper-slide">
     <video width="960" height="540" data-src="video.mp4" preload="none" autoplay="autoplay" muted="muted" playsinline="" loop="loop" class="swiper-lazy">
          <source data-src="video.webm" type="video/webm">
          <source data-src="video.mp4" type="video/mp4">
          Your browser does not support the video tag.
     </video>
</div>
```

### Alternative

An alternative would be to support the [lazysizes](https://github.com/aFarkas/lazysizes) library inside swiper (which I'm using to lazyload my videos and images on the rest of the site)

I use the following code to ensure my videos and images are getting lazyloaded:

```javascript
import lazySizes from 'lazysizes';
import 'lazysizes/plugins/unveilhooks/ls.unveilhooks'; // Needs to be imported separately so video preloading also works.

lazySizes.init();
```

If there are ANY alternatives that work well with swiper I would be glad to hear them

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 doesn't lazy module anymore. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
