### ISSUE TITLE
Method slideTo doesn't work on initially hidden swipers that are controlled by each other

### ISSUE THREAD

**Issue by MKJAY** [nolimits4web/swiper#5520]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/gifted-water-7jjdz2?file=/index.html

### Bug description

**Background of the situation**
I have two sections. The first section contains two swipers (A1 and A2) and the second section contains one swiper (B). Only one section can be visible at a time. A button is used as a switch to make one section visible and the other section hidden using the CSS rule `display: none`. Swiper A1 and A2 are also controlled by each other using the controller property. The second section is visible on page startup. When I change the slide (i.e. the current index) of the visible swiper(s), I want to change the slide of the hidden swiper(s) to that changed index.

**Issue**
Steps to reproduce
1. After page startup, change the slide of swiper B from `B #1` to `B #2`
2. Press the button to switch the section visibility

Expected:
Swipers A1 en A2 are updated to the slides `A1 #2` and `A2 #2` respectively.

Actual behaviour:
Swipers A1 en A2 are not updated and still show their initial slides `A1 #1` and `A2 #1` respectively.

When I remove the code that makes swiper A1 and A2 controlled by each other, then everything works as expected.

Note that once swipers A1 and A2 have been shown, everything works as expected. 

Steps to reproduce:
1. After page startup, press the button to switch the section visibility
2. Press the button to switch the section visibility again
3. Change the slide of swiper B from `B #1` to `B #2`
4. Press the button to switch the section visibility

Swipers A1 en A2 are correctly updated to slides `A1 #2` and `A2 #2` respectively.

I've already tried using the properties `observer: true` and `observeParens: true` on swiper A1 and A2 because they are hidden on initialization, but without success.

I could just link all three swipers together using their controller properties instead of A1 and A2 only, but this is not an option since I need to use some custom logic in the `slideChange` event handler that decides which index of the hidden swiper(s) should be displayed.

I'm new to this library, so please correct my mistakes and misunderstandings.

Any solutions, workarounds or ideas that I can try out are very welcome.
Thank you for your time!

### Swiper version

8.0.7

### Platform/Target and Browser Versions

macOS Chrome 98.0.4758.109

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is intended, invisible Swiper can’t work correctly. Call slideTo when they become visible
