### ISSUE TITLE
SwiperSlide isActive prop not behaving correctly when navigation direction changes

### ISSUE THREAD

**Issue by amyyaling** [nolimits4web/swiper#5528]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-navigation-react-forked-ve36zj?file=/src/App.jsx

### Bug description

SwiperSlide's `isActive` prop is correct when navigating in one direction however when the navigation direction changes to go backward, it seems to not accurately update the active slide. 
Demo shows a simple example

### Expected Behavior

isActive should be true when the actual active slide is active

### Actual Behavior

When changing navigation direction is going backwards, isActive is not accurate

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Chrome 99

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The code and logic kinda looks weird to me, by calling `setCur` within render function in each slide causes re-render of whole component, potentially can go into infinite loop. To get the active slide of the Swiper, use `swiper.activeIndex` prop in main Swiper instance
