### ISSUE TITLE
cards effect not support RTL

### ISSUE THREAD

**Issue by efraimKroizer** [nolimits4web/swiper#5534]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/0ywsmxf5/1/

### Bug description

when a swiper with cards effect shown on rtl, not the direction of next/prev slides is correct, and the swipe behavior is opposite the swipe direction.
i try to fix it in source code, with edit this row in effect-dards.js file

`const progress = Math.min(Math.max(slideProgress, -4), 4) * (rtl ? -1 : 1);`

it help for direction of slides and to swipe direction, but the behavior of the prev/next slides z-index and scaling is not consistently.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

windows chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by dangelion** [comment]
Please is there a solution to this?

**Comment by efraim-icreate** [comment]
thanks for your fixing
