### ISSUE TITLE
iOS Safari Flashing Issue MatDialog Fixed Scrolling

### ISSUE THREAD

**Issue by coding-tech-guy** [nolimits4web/swiper#5538]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-virtual-slides-angular-forked-1d80fn

### Bug description

When a number of Swiper instances are on the screen, you scroll down part way move a slide and then open up a matDialog, the swiper instances will flash sometimes on open and always on close.

The MatDialog applies a fixed position to the html tag of the document to prevent scrolling, the adding and removing of this appears to cause the flash as its not present if the fixed position isn't applied.

You can test this in the codesandbox by enabling and disabling the scrollStrategy on the openDialog function

Is there solution for this to stop the flashing?

https://user-images.githubusercontent.com/56171951/157663134-e504d7db-d107-4555-8ae6-daa49b46204a.mp4

### Swiper version

8.0.7

### Platform/Target and Browser Versions

iOS Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
