### ISSUE TITLE
Thumbs property error when using TypeScript

### ISSUE THREAD

**Issue by kamilmedrala** [nolimits4web/swiper#5548]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-thumbs-gallery-loop-vue-forked-eu064t?file=/src/App.vue

### Bug description

Reproduction link is compiling even with lang="ts" set so it is just for representation of my swipers declaration.
The same problem also happens with other props, such as :scrollbar or :mousewheel, and all of them disappear when script lang is set to js, not ts.

### Actual Behavior

![image](https://user-images.githubusercontent.com/81763542/157927830-8e38a146-0271-48fc-9000-b3b9e5745c34.png)

Temporary solution: 
```
        initIconsSwiper(swiper:any){
            this.iconsSwiper = swiper;
            this.optionsSwiper.thumbs.swiper = this.iconsSwiper;    
        },

        initOptionsSwiper(swiper:any){
            this.optionsSwiper = swiper;
            this.optionsSwiper.mousewheel.enable();
        },
```

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by luvejo** [comment]
I'm seeing the same TypeScript error with the **`autoplay`** prop while using **Swiper 8.1.1** and **`swiper/vue`**:

```
(property) autoplay?: undefined
Type '{ delay: number; }' is not assignable to type 'undefined'.ts(2322)
```

Here is a very simple demo: https://github.com/luvejo/swiper-ts-issue

## Steps to reproduce
1. Clone the repo and open it with VS Code.
2. Make sure you have [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) installed.
3. Open `app.vue` and you'll see the error at **line 13**.

## Platform/Target and Browser Versions
- OS: Ubuntu 21.10

**Comment by Enzodtz** [comment]
I'm having the exact same problem in react with typescript...

**Comment by Enzodtz** [comment]
Seems that there's this `.destroyed` property that must be checked... the following line worked for me (react):
`thumbs={{swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null}}`

ref: https://stackoverflow.com/questions/73046820/swiper-react-cannot-convert-undefined-or-null-to-object

**Comment by vicasas** [comment]
I have the same problem. But the above solution worked for me.

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
