### ISSUE TITLE
Using Ionic, and on Windows desktop, any manually added mousedown/mouseup events are ignored completely when rendered inside of the <swiper> component.

### ISSUE THREAD

**Issue by ntorrey** [nolimits4web/swiper#5549]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/ntorrey/swiper-ripple-bug

### Bug description

Using Ionic, any manually added mousedown/mouseup events are ignored completely when rendered inside of the `swiper` component. I opened this issue over at Ionic, but after testing they said it had to do with swiper and not Ionic (https://github.com/ionic-team/ionic-framework/issues/24931)

### Expected Behavior

Manually added mousedown/mouseup events should not be ignored when rendered inside of the `swiper` component.

### Actual Behavior

I discovered this while using an `ion-item` with a `button` attribute applied to it . The desired ripple effect is not triggered when inside a `swiper` component. 

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by ntorrey** [comment]
I just wanted to underline, that this only happens on the desktop (because the mouse events aren't detected). It seems to work fine in mobile - at least it works in chrome when "mobile mode" is active in developer tools.

**Comment by DocCaliban** [comment]
Same issue when using react and windows, I haven't looked at mobile but I suspect the same behavior there.

**Comment by nullart2** [comment]
Same issue here. 

Does it have to do with NgZone not being run when clicking ionic components inside <swiper>?

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
