### ISSUE TITLE
Can't drag in space between (some) elements

### ISSUE THREAD

**Issue by smerriman** [nolimits4web/swiper#5559]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#slides-per-view

### Bug description

With the default setting for touchEventsTarget, you cannot drag the carousel if you start from the space between slides (with a couple of exceptions).``

### Expected Behavior

See the Slides Per View demo on your site. Using a mouse (haven't tested touch events, but would guess it's similar), you should be able to drag the slider no matter where your drag starts from.

### Actual Behavior

If you click and drag in the space between slides 1 + 2, or slides 2 + 3, everything works fine. If you click and drag in the space between any other slides, the carousel does not swipe.

Setting touchEventsTarget to wrapper does somewhat mitigate this problem. However, it's not ideal; for example, I like to reposition the pagination to be underneath the swiper, rather than overlaid on top, and I don't want all of the area around the pagination swipable (especially when grabCursor is on).

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Windows Firefox 98.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It can be `wrapper` or `container` and this is how it suppose to work
