### ISSUE TITLE
Problem to click into button or link into swiper-slide

### ISSUE THREAD

**Issue by latifur** [nolimits4web/swiper#5560]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/latifur/pen/mdpeJPK

### Bug description

I am trying to create a product carousel with swiperjs. There have a button on every slide but when i am trying to click on the button it is moving left suddenly and click is not working

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Google Chrome Version 99.0.4844.51 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Krajenn** [comment]
I have similar problem :/

**Comment by silasbispo01** [comment]
:+1: Me too ;(

**Comment by HandHugs** [comment]
also having this problem, tried reverting to v7 but its still an issue sometimes depending on minute mouse movements between mouse down and mouse up.

**Comment by elemis** [comment]
Have the same issue :(

**Comment by latifur** [comment]
> also having this problem, tried reverting to v7 but its still an issue sometimes depending on minute mouse movements between mouse down and mouse up.

thank you. I have rollback to v7 and it resolve the issue.

**Comment by elemis** [comment]
Rolling back to an earlier version is not a real solution though. Shouldn't this be investigated and addressed in upcoming versions? Wish this issue wasn't closed.

**Comment by 144mdgross** [comment]
I also have this same issue on v6. We cannot migrate to v7 due to our NextJs version.

**Comment by JSMengLingqi** [comment]
我也有这个问题，单击时常不生效，会莫名的触发onTouchMove，然后需要点击好几下才能触发点击事件 v8.1.1

**Comment by silasbispo01** [comment]
> I also have this same issue on v6. We cannot migrate to v7 due to our NextJs version.

Add "watchSlidesProgress: true" in Swiper config to resolve
