### ISSUE TITLE
The  Navigation Events not working

### ISSUE THREAD

**Issue by nunowar** [nolimits4web/swiper#5564]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/nuno360/pen/MWOPgVB

### Bug description

The  Navigation Events [navigationHide](https://swiperjs.com/swiper-api#event-navigationHide) [navigationShow](https://swiperjs.com/swiper-api#event-navigationShow) not working.

### Expected Behavior

Events navigationHide and navigationShow trigger when slider isEnd or isBeginning.

### Swiper version

v8.0.7

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Richard-08** [comment]
@nunowar Hi! navigationHide and navigationShow trigger when navigation HIDE or SHOW.  In order for events to work, you need to define listeners for swiper. And add hideOnClick property for navigation. For exmaple:
`const swiper = new Swiper(".swiper", {
  initialSlide: 0,
  loop: false,
  spaceBetween: 24,
  slidesPerGroup: 2,
  slidesPerView: 'auto',
  navigation: {
    nextEl: ".swiper-button-next",
    prevEl: ".swiper-button-prev",
    hideOnClick: true,
  },
  on: {
    navigationHide: function () {
      console.log(this);
    }, 
    navigationShow: function () {
      console.log(this);
    }
  }
});`

**Comment by nunowar** [comment]
@Richard-08 thanks!
