### ISSUE TITLE
loop and pagination are not updated

### ISSUE THREAD

**Issue by sowjanyakasam** [nolimits4web/swiper#5573]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-angular-forked-l7d1hu?file=/src/app/app.component.ts

### Bug description

I am adding Updateparameter for loop and navigation but it is not working. Please let me know is the way I am using is correct

### Expected Behavior

Apply navigation and pagination on updateparameter

### Actual Behavior

https://codesandbox.io/s/swiper-default-angular-forked-l7d1hu?file=/src/app/app.component.ts

### Swiper version

7.4.1

### Platform/Target and Browser Versions

All Browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
