### ISSUE TITLE
realIndex and activeIndex in useSwiper is not change when slider change

### ISSUE THREAD

**Issue by Aryan-mor** [nolimits4web/swiper#5577]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-react-forked-omsh30

### Bug description

useSwiper is not called use effect or re-render the component

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by dohomi** [comment]
I experienced this as well. Due to the fact that its not possible to have custom React components in the `customRender` of `pagination` or `navigation` I thought I could use the `useSwiper` hook, but the hook is not reactive. I think for most cases a `useActiveIndex` would be great to expose for making customisation easier for users.

**Comment by nolimits4web** [comment]
Yes, it is not reactive, it updated only on Swiper instance set, otherwise it could lead to too many re-rendering, use events to get the actual information about slide changes

**Comment by dohomi** [comment]
@nolimits4web would you consider implementing a `useActiveIndex` into the library as a feature request?

**Comment by abhagsain** [comment]
> It is surprising that `useSwiper` does not result in a re-render when the swiper state changes. This makes the hook pretty much useless, no?

Yes. Needed external controls and wanted to enable/disable arrow. `swiper.isBeginning` and `swiper.isEnd` also don't get the updated value :(

**Comment by abhagsain** [comment]
Added re-rendering using Events and Local State.


```tsx

const SliderNavigation = () => {
  const [slideConfig, setSlideConfig] = useState({
    isBeginning: true,
    isEnd: false,
  });
  const swiper = useSwiper();

  useEffect(() => {
    swiper.on("slideChange", (swipe) => {
      setSlideConfig({ isBeginning: swipe.isBeginning, isEnd: swipe.isEnd });
    });
  }, [swiper]);

  const activeStyles =
    "flex items-center justify-center w-8 h-8 transition-all duration-200 rounded-full cursor-pointer text-primary-800";
  const inactiveStyles = "opacity-80 cursor-not-allowed text-gray-400";
  return (
    <div className="flex items-center ml-auto space-x-2">
      <div
        className={cx(activeStyles, {
          [inactiveStyles]: slideConfig.isBeginning,
          "hover:bg-primary-300 text-primary-800": !slideConfig.isBeginning,
        })}
        onClick={() => swiper.slidePrev()}
      >
        <ChevronLeftIcon className={cx("w-4 h-4")} />
      </div>
      <div
        className={cx(activeStyles, {
          [inactiveStyles]: slideConfig.isEnd,
          "hover:bg-primary-300 text-primary-800": !slideConfig.isEnd,
        })}
        onClick={() => swiper.slideNext()}
      >
        <ChevronRightIcon className="w-4 h-4" />
      </div>
    </div>
  );
};

```

**Comment by lennartschoch** [comment]
I was dealing with this issue today (eventually came up with a solution similar to the one by @abhagsain) and I totally agree with @DennisRosen. While reactive variables will cause re-renders, they will only do so if the value (or a value that depends on the reactive var) actually has an impact on the rendered HTML, React is pretty smart about that. Having to rely on event listeners works, but not only does it impact readability, but it's also easy to introduce bugs when trying to manage the state yourself.

@nolimits4web I'd love to create a PR to fix this, let me know in case that's desired :)

**Comment by cojoclaudiu** [comment]
To get the reactive index you can setState onSlideChange and this will trigger a re-rerender
```ts
const SwiperImageFooter = ({ count }: SwiperImageFooter) => {
	const swiper = useSwiper();

	return (
		<div className={styles.swiperFooterContainer}>
			<span className={styles.imageCount}>{`${swiper.activeIndex + 1} / ${count}`}</span>

			<div className={styles.navigationButtonsContainer}>
				<button className={styles.navigationButton} onClick={() => swiper.slidePrev()}>
					<ChevronSolid direction='left' height={9.87} width={17.26} />
				</button>

				<button className={styles.navigationButton} onClick={() => swiper.slideNext()}>
					<ChevronSolid direction='right' height={9.87} width={17.26} />
				</button>
			</div>
		</div>
	);
}; 
```

**Comment by oytuneyucel** [comment]
imho this hook needs to be renamed or rewritten as the name suggests its reactive and the documentation doesn't provide this step to manually update a state in the component wrapper to properly update the fetched values. I honestly don't see the value proposition of `useSwiper` if a working Swiper can only be constructed by updating the swiper ref every single time and passing them to the sub-components as props 🤔

**Comment by DRFR0ST** [comment]
Guess it's a little late and most of you came up with some idea already, but in case someone has this issue, I'm leaving this little hook here that seems to work fine for me:
```tsx
import { useEffect, useState } from 'react';
import { useSwiper } from 'swiper/react';

/**
 * Hook to get the swiper instance in a reactive way.
 * This is useful when you need to get the active index of the swiper on every slide change.
 * @returns {Swiper} swiper
 */
export const useSwiperReactive = () => {
  const swiper = useSwiper();

  // State to force a rerender.
  const [, setSignal] = useState({});
  const forceRerender = () => setSignal({});

  useEffect(() => {
    if (swiper)
      swiper.on('slideChange', forceRerender);
  }, []);

  return swiper;
};
```

Use it this way:
```tsx
const swiper = useSwiperReactive(); // Instead of useSwiper();

console.log(swiper?.activeIndex); // <- Will update on every slide change.
```

**Comment by SteveLin99** [comment]
> Guess it's a little late and most of you came up with some idea already, but in case someone has this issue, I'm leaving this little hook here that seems to work fine for me:
> 
> ```tsx
> import { useEffect, useState } from 'react';
> import { useSwiper } from 'swiper/react';
> 
> /**
>  * Hook to get the swiper instance in a reactive way.
>  * This is useful when you need to get the active index of the swiper on every slide change.
>  * @returns {Swiper} swiper
>  */
> export const useSwiperReactive = () => {
>   const swiper = useSwiper();
> 
>   // State to force a rerender.
>   const [, setSignal] = useState({});
>   const forceRerender = () => setSignal({});
> 
>   useEffect(() => {
>     if (swiper)
>       swiper.on('slideChange', forceRerender);
>   }, []);
> 
>   return swiper;
> };
> ```
> 
> Use it this way:
> 
> ```tsx
> const swiper = useSwiperReactive(); // Instead of useSwiper();
> 
> console.log(swiper?.activeIndex); // <- Will update on every slide change.
> ```

hi, may I know what the variable signal is for? I don't see it used in your code.

**Comment by tiansial** [comment]
> Guess it's a little late and most of you came up with some idea already, but in case someone has this issue, I'm leaving this little hook here that seems to work fine for me:
> 
> ```tsx
> import { useEffect, useState } from 'react';
> import { useSwiper } from 'swiper/react';
> 
> /**
>  * Hook to get the swiper instance in a reactive way.
>  * This is useful when you need to get the active index of the swiper on every slide change.
>  * @returns {Swiper} swiper
>  */
> export const useSwiperReactive = () => {
>   const swiper = useSwiper();
> 
>   // State to force a rerender.
>   const [, setSignal] = useState({});
>   const forceRerender = () => setSignal({});
> 
>   useEffect(() => {
>     if (swiper)
>       swiper.on('slideChange', forceRerender);
>   }, []);
> 
>   return swiper;
> };
> ```
> 
> Use it this way:
> 
> ```tsx
> const swiper = useSwiperReactive(); // Instead of useSwiper();
> 
> console.log(swiper?.activeIndex); // <- Will update on every slide change.
> ```

This worked for me, but I had to add swiper as a dependency for the useEffect:

```javascript
import { useEffect, useState } from "react";
import { useSwiper } from "swiper/react";

/**
 * Hook to get the swiper instance in a reactive way.
 * This is useful when you need to get the active index of the swiper on every slide change.
 * @returns {Swiper} swiper
 */
export const useSwiperReactive = () => {
  const swiper = useSwiper();

  // State to force a rerender.
  const [, setSignal] = useState({});
  const forceRerender = () => setSignal({});

  useEffect(() => {
    if (swiper) {
      swiper.on("slideChange", forceRerender);
      return () => {
        swiper.off("slideChange", forceRerender);
      };
    }
  }, [swiper]);

  return swiper;
};

```

**Comment by DRFR0ST** [comment]
> > Guess it's a little late and most of you came up with some idea already, but in case someone has this issue, I'm leaving this little hook here that seems to work fine for me:
> > ```
> > import { useEffect, useState } from 'react';
> > import { useSwiper } from 'swiper/react';
> > 
> > /**
> >  * Hook to get the swiper instance in a reactive way.
> >  * This is useful when you need to get the active index of the swiper on every slide change.
> >  * @returns {Swiper} swiper
> >  */
> > export const useSwiperReactive = () => {
> >   const swiper = useSwiper();
> > 
> >   // State to force a rerender.
> >   const [, setSignal] = useState({});
> >   const forceRerender = () => setSignal({});
> > 
> >   useEffect(() => {
> >     if (swiper)
> >       swiper.on('slideChange', forceRerender);
> >   }, []);
> > 
> >   return swiper;
> > };
> > ```
> > 
> > 
> > Use it this way:
> > ```
> > const swiper = useSwiperReactive(); // Instead of useSwiper();
> > 
> > console.log(swiper?.activeIndex); // <- Will update on every slide change.
> > ```
> 
> Hi, may I know what the variable signal is for? I don't see it used in your code.

@SteveLin99 We are only using the setter here (setSignal, returned from useState). There is no `signal` variable declared. The state is used only to force a rerender by setting an object as the next value when `forceRerender` is called. `useState` does only shallow comparison, so when we're setting an object, it will trigger a rerender.
As result, the component using the hook `useSwiperReactive` should rerender every time the event "slideChange" is triggered.

---

> > Guess it's a little late and most of you came up with some idea already, but in case someone has this issue, I'm leaving this little hook here that seems to work fine for me:
> > ```
> > import { useEffect, useState } from 'react';
> > import { useSwiper } from 'swiper/react';
> > 
> > /**
> >  * Hook to get the swiper instance in a reactive way.
> >  * This is useful when you need to get the active index of the swiper on every slide change.
> >  * @returns {Swiper} swiper
> >  */
> > export const useSwiperReactive = () => {
> >   const swiper = useSwiper();
> > 
> >   // State to force a rerender.
> >   const [, setSignal] = useState({});
> >   const forceRerender = () => setSignal({});
> > 
> >   useEffect(() => {
> >     if (swiper)
> >       swiper.on('slideChange', forceRerender);
> >   }, []);
> > 
> >   return swiper;
> > };
> > ```
> > 
> > 
> > Use it this way:
> > ```
> > const swiper = useSwiperReactive(); // Instead of useSwiper();
> > 
> > console.log(swiper?.activeIndex); // <- Will update on every slide change.
> > ```
> 
> This worked for me, but I had to add swiper as a dependency for the useEffect:
> 
> ```js
> import { useEffect, useState } from "react";
> import { useSwiper } from "swiper/react";
> 
> /**
>  * Hook to get the swiper instance in a reactive way.
>  * This is useful when you need to get the active index of the swiper on every slide change.
>  * @returns {Swiper} swiper
>  */
> export const useSwiperReactive = () => {
>   const swiper = useSwiper();
> 
>   // State to force a rerender.
>   const [, setSignal] = useState({});
>   const forceRerender = () => setSignal({});
> 
>   useEffect(() => {
>     if (swiper) {
>       swiper.on("slideChange", forceRerender);
>       return () => {
>         swiper.off("slideChange", forceRerender);
>       };
>     }
>   }, [swiper]);
> 
>   return swiper;
> };
> ```

@tiansial Right, if `swiper` is undefined on mount, the "slideChange" event won't be subscribed to, however you should probably make sure that `swiper.on` is called only once. Great job adding the cleanup too 👍🏻

**Comment by MarlonPassos-git** [comment]
> > Guess it's a little late and most of you came up with some idea already, but in case someone has this issue, I'm leaving this little hook here that seems to work fine for me:
> > ```tsx
> > import { useEffect, useState } from 'react';
> > import { useSwiper } from 'swiper/react';
> > 
> > /**
> >  * Hook to get the swiper instance in a reactive way.
> >  * This is useful when you need to get the active index of the swiper on every slide change.
> >  * @returns {Swiper} swiper
> >  */
> > export const useSwiperReactive = () => {
> >   const swiper = useSwiper();
> > 
> >   // State to force a rerender.
> >   const [, setSignal] = useState({});
> >   const forceRerender = () => setSignal({});
> > 
> >   useEffect(() => {
> >     if (swiper)
> >       swiper.on('slideChange', forceRerender);
> >   }, []);
> > 
> >   return swiper;
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Use it this way:
> > ```tsx
> > const swiper = useSwiperReactive(); // Instead of useSwiper();
> > 
> > console.log(swiper?.activeIndex); // <- Will update on every slide change.
> > ```
> 
> This worked for me, but I had to add swiper as a dependency for the useEffect:
> 
> ```js
> import { useEffect, useState } from "react";
> import { useSwiper } from "swiper/react";
> 
> /**
>  * Hook to get the swiper instance in a reactive way.
>  * This is useful when you need to get the active index of the swiper on every slide change.
>  * @returns {Swiper} swiper
>  */
> export const useSwiperReactive = () => {
>   const swiper = useSwiper();
> 
>   // State to force a rerender.
>   const [, setSignal] = useState({});
>   const forceRerender = () => setSignal({});
> 
>   useEffect(() => {
>     if (swiper) {
>       swiper.on("slideChange", forceRerender);
>       return () => {
>         swiper.off("slideChange", forceRerender);
>       };
>     }
>   }, [swiper]);
> 
>   return swiper;
> };
> ```

a little contribuation for this hook i have adding the forceRerender when the swiper changes, because when i try to acess swiper.slidesGrid or  swiper.slides the value has missing 

```
// ....
useEffect(() => {
    if (swiper) {
      forceRerender();
      swiper.on("slideChange", forceRerender);
      return () => {
        swiper.off("slideChange", forceRerender);
      };
    }
  }, [swiper]);
// ....
```

**Comment by voinik** [comment]
Good solutions! However, if you use that hook in multiple components, you will cause the `setSignal` function to be triggered once for each component using it. And the effect that sets up the event listeners will also be run for each component using that hook.

The most optimal solution (imo) is to use React context to set up the effect once to expose the swiper instance in the context. Then, to make sure all components subscribed to the context actually rerender when the `slideChange` event happens (the original issue), add a counter to the context that is mutated on each slide change. We use the counter just for rerendering purposes, nothing else. A counter is better than creating an empty object, as a number takes up 8 bytes whereas an empty object takes up 56 bytes. (Ideally, I would use a boolean, which takes up 4 bytes, but since the `slideChange` event is called twice when going back a slide for some reason, it would go from `true` to `false` and back to `true`, so a counter will have to do).

 Building on top of your solutions, here's a React 19 client component:

```tsx
"use client";

import { createContext, use, useEffect, useState } from "react";
import { SwiperClass, useSwiper } from "swiper/react";

/**
 * Hook to get the swiper instance in a reactive way.
 * This is useful when you need to get the active index of the swiper on every slide change.
 * @returns {Swiper} swiper
 */
export function useSwiperReactive() {
  const swiperCtx = use(ReactiveSwiperContext);

  if (!swiperCtx) {
    throw new Error("No ReactiveSwiperContext found!");
  }

  const { swiper } = swiperCtx;

  return swiper;
}

export const ReactiveSwiperContext = createContext<{
  swiper: SwiperClass;
  v: number;
} | null>(null);
export function ReactiveSwiperContextProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const swiper = useSwiper();

  if (!swiper) {
    throw new Error("No Swiper context found!");
  }

  const [v, setSignal] = useState(0);
  const forceRerender = () => {
    setSignal((c) => {
      return c + 1;
    });
  };

  useEffect(() => {
    if (swiper) {
      swiper.on("slideChange", forceRerender);
    }

    return () => {
      swiper.off("slideChange", forceRerender);
    };
  }, [swiper]);

  return (
    <ReactiveSwiperContext.Provider value={{ swiper, v }}>
      {children}
    </ReactiveSwiperContext.Provider>
  );
}
```

And you can use it the same way in your components as the previous solutions.
