### ISSUE TITLE
`Swiper.slides` property type is not `Dom7Array`

### ISSUE THREAD

**Issue by ybiquitous** [nolimits4web/swiper#5578]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/loving-kowalevski-cuxf8q

### Bug description

The `Swiper.slides` property type should be a `Dom7Array` type,

https://github.com/nolimits4web/swiper/blob/803b9ad41aab0087bc07b2b117c225b2c118855d/src/types/swiper-class.d.ts#L74-L77

but actually, it is an `Array` type. See the following screenshot on the reproduction:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/473530/160096112-77ff98ac-9f95-44aa-a819-d89ecb8d9855.png">

### Expected Behavior

The `Swiper.slides` property should be `Dom7Array`.

### Actual Behavior

The `Swiper.slides` property is `Array`.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

macOS Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is `Dom7Array` and there is no `hide` method used in Swiper Dom https://github.com/nolimits4web/swiper/blob/master/src/shared/dom.js

**Comment by ybiquitous** [comment]
@nolimits4web 

I see. Then, what if creating a customized `Dom7Array` type like this?

```ts
// types/shared.d.ts
import { Dom7Array } from 'dom7';
export type CustomDom7Array = Pick<Dom7Array,
  'addClass' |
  'removeClass' |
  // ...
>
```

```diff
// types/swiper-class.d.ts
-import { Dom7Array } from 'dom7';
+import { CustomDom7Array as Dom7Array } from './shared';
```

I'm glad to create a pull request to do it if needed.
