### ISSUE TITLE
when i play an audio in a component, the swiper will update constantly

### ISSUE THREAD

**Issue by kingstarstar** [nolimits4web/swiper#5585]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/adoring-scott-b3xuuf?file=/pages/index.vue

### Bug description

i use swiper in my nuxt project，and the version is under below:
"swiper": "^5.4.5",
"vue-awesome-swiper": "^4.1.1"
when i play play an audio,the swiper will destory and create constantly,and pause audio  it will stop
it cause the image reload and the swiper class、style recomputed constantly;
you could see the porject in codesandbox,and inspect the element
you will see it 
here is the codesanbox url:[https://codesandbox.io/s/adoring-scott-b3xuuf?file=/pages/index.vue](https://codesandbox.io/s/adoring-scott-b3xuuf?file=/pages/index.vue)

### Expected Behavior

when i play play an audio,the swiper will not computed constantly

### Swiper version

5.4.5

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by JohnMica** [comment]
a few things to keep in mind @kingstarstar 

- use `client-only` instead of `no-ssr`
- you are using a different wrapper for swipper  - `"vue-awesome-swiper": "^4.1.1"`
- try to bind your `slideChange` function  on the swiper itself for the event emitted
```
 <swiper ref="mySwiper" :options="swiperOptions" @slideChange="slideChange">
          <!-- eslint disable next-line -->
          <swiper-slide v-for="url in coverList" :key="getUUid()">
            <img :src="url" />
            <!-- {{url}} -->
          </swiper-slide>
        </swiper>

...

methods:{
 slideChange() {},
}
```
