### ISSUE TITLE
Even if allowTouchMove is set to false, mobile users can touch drag slides.

### ISSUE THREAD

**Issue by KeremArdicli** [nolimits4web/swiper#5589]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://plazaevent.com.tr/kayit/sayader2022/

### Bug description

In swiper options, allowTouchMove is set to false.
Yet Mobile Users can still touch drag between slides.

### Expected Behavior

Slides should not be draggable if option is set to false.

### Actual Behavior

Slides do touch drag

### Swiper version

swiper@8

### Platform/Target and Browser Versions

Android 12 / Chrome and Samsung Internet

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Can't see the issue, on mobile it is not draggable on your demo

**Comment by KeremArdicli** [comment]
Cause i found a workaround.

If cssmode is enabled, it does drag. If not, it does not. With cssmode
enabled lots of thing are easier to do.

**Comment by nolimits4web** [comment]
With cssmode enabled it can not be prevented, this is how `overflow: auto` in CSS works

**Comment by KeremArdicli** [comment]
Ok got it. Then it could be good to add such a notice on the documentation. I have seen so many people on the internet searching for the issue.

**Comment by MAGNUM81** [comment]
I bumped into this issue - allowTouchMove doesn't do anything for me, and I have cssMode enabled.

> With cssmode enabled it can not be prevented, this is how `overflow: auto` in CSS works

I will attempt to put overflow: hidden on my swiper-wrapper and report back. This might just be the solution, because I cannot afford to disable cssMode.
