### ISSUE TITLE
Swiper freemode causes Error "onTouchEnd"

### ISSUE THREAD

**Issue by webdesign2be** [nolimits4web/swiper#5591]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/magical-hypatia-eckqgu?file=/src/app/app.component.ts

### Bug description

When the "Freemode" option is enabled you will get the following error when you swipe in any direction:
`Cannot read properties of undefined (reading 'onTouchEnd')`

Second Example: https://codesandbox.io/s/stupefied-tess-mlecd3?file=/src/App.tsx

Same behavior with the basic swiper implementation in our Stencil Project (Private)

### Expected Behavior

Swiping should not cause any error.

### Actual Behavior

`Cannot read properties of undefined (reading 'onTouchEnd')` when swiping.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

macOS 12.3, Chrome 100.0.4896.60

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
don't see that you have enabled/installed `FreeMode` module

**Comment by cipsicko** [comment]
Hi @webdesign2be if you activate the freemode on your demo the issue is face in. 
I've the same bug.

hope someone fix this

**Comment by below9k** [comment]
This issue happens when you use enumerated properties for freeMode, like `freeMode: {enabled: true, sticky: false}`, but doesn't happen if you use `freeMode: true`

**Comment by myoung919** [comment]
"FreeMode" is an imported module.

Use:
```
import Swiper, { Navigation, FreeMode } from 'swiper';

Swiper.use([Navigation, FreeMode]);
...
```

or

```
import Swiper, { Navigation, FreeMode } from 'swiper';

const swiper = new Swiper('.swiper', {
  // configure Swiper to use modules
  modules: [Navigation, FreeMode],
  // Optional parameters
  freeMode: {
       enabled: true,
       sticky: true,
       momentumBounce: false,
       momentumVelocityRatio: 0.5
   }, 
  ...
});
```

**Comment by JesperBalslev** [comment]
@myoung919's solution did not quite work for me.
The code below worked just fine (using Angular).

```
// import Swiper core and required modules
import SwiperCore, { FreeMode } from "swiper";

// install Swiper modules
SwiperCore.use([FreeMode]);
```
