### ISSUE TITLE
Mouseweehl enabled, not correclty suported in types

### ISSUE THREAD

**Issue by edgar0011** [nolimits4web/swiper#5594]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/nolimits4web/swiper/blob/master/src/types/modules/mousewheel.d.ts#:~:text=export%20interface%20MousewheelOptions%20%7B

### Bug description

SwiperCore.use([Navigation, Keyboard, Mousewheel])

new Swiper(swiperRef.current as unknown as HTMLDivElement, {
      resizeObserver: true,
      slidesPerView: 'auto',
      spaceBetween: 20,
      simulateTouch: true,
      a11y: {
        prevSlideMessage: 'Previous slide',
        nextSlideMessage: 'Next slide',
      },
      keyboard: {
        enabled: true,
        onlyInViewport: false,
        pageUpDown: true,
      },
      mousewheel: {
        enabled: true,
      },
      grabCursor: true,
      centeredSlides: true,

      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    })

### Expected Behavior

types will correclty export mousewheel with enabled?: boolean

### Actual Behavior

 Type '{ enabled: true; }' is not assignable to type 'boolean | MousewheelOptions | undefined'.
  Object literal may only specify known properties, and 'enabled' does not exist in type 'MousewheelOptions'.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
