### ISSUE TITLE
Grid is not working

### ISSUE THREAD

**Issue by ErkanKabil** [nolimits4web/swiper#5597]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/frosty-mopsa-n80t4l?file=/package.json

### Bug description

I use Swiper 8.0.7. When i tried use grid, is not working as it should. I create codesandbox and try it same as this example https://codesandbox.io/s/20p7zs?file=/src/App.jsx but it didn't work either

### Swiper version

8.0.7

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is definitely working as you can see here https://codesandbox.io/s/20p7zs?file=/src/App.jsx
