### ISSUE TITLE
NVDA screen reader  - Non - Interactive Element showing as Clickable

### ISSUE THREAD

**Issue by DeepaRagavan0609** [nolimits4web/swiper#5604]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/030-pagination/core

### Bug description

![SwiperJS](https://user-images.githubusercontent.com/26297434/161552174-dbb5061e-bdc1-420c-b1f8-b2a2bfe801a1.jpg)

Non InteractiveElement like Label, Static text & etc - Clickable in NVDA
Interactive Element like button, link & etc - Clickable in NVDA

### Expected Behavior

Non InteractiveElement like Label, Static text & etc -Not Clickable in NVDA 
Interactive Element like button, link & etc - Clickable in NVDA

### Swiper version

3

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
