### ISSUE TITLE
Swiper repor error in Volar

### ISSUE THREAD

**Issue by adinvadim** [nolimits4web/swiper#5606]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-laapp8?file=.stackblitzrc

### Bug description

If you put `true` to the prop "pagination" (or another props, that have default value `undefined`), you got error in Volar `Type 'true' is not assignable to type 'undefined' :pagination="true"`

Screenshot from demo.
<img width="591" alt="Снимок экрана 2022-04-04 в 21 27 29" src="https://user-images.githubusercontent.com/8646071/161608040-ccfdc0ce-0133-4daa-93e2-3a31d430fb8e.png">

Maybe this is also problem of Volar

### Expected Behavior

Without throwing error, because paginations type it is not `paginatiton:? undefined`, it is `paginatiton:? PaginationOptions | boolean`

### Actual Behavior

Volar think that paginatiton is `paginatiton:? undefined` and throwing error.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Volar

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by adinvadim** [comment]
^ @johnsoncodehk

May be this is Volar bug, thats why I tag you. Sorry if not

**Comment by johnsoncodehk** [comment]
@adinvadim I don't have this error, please check you are using the latest vue-tsc version.
<img width="491" alt="螢幕截圖 2022-04-06 11 58 49" src="https://user-images.githubusercontent.com/16279759/161893004-caa9e860-e9cb-4f9c-b4b0-d600741e2dad.png">
