### ISSUE TITLE
Swiper with React 18  causes TypeError: Cannot read properties of undefined (reading 'slideClass')

### ISSUE THREAD

**Issue by cizz3007** [nolimits4web/swiper#5613]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

none

### Bug description

TypeError: Cannot read properties of undefined (reading 'slideClass')

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/32691294/161885101-5075d3ab-a6b0-4af8-9cb8-a585bf17a5fe.png">

### Actual Behavior

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/32691294/161885118-c90b0fd6-a4cd-4724-b022-8ca98a76cd56.png">

### Swiper version

8.0.7

### Platform/Target and Browser Versions

macOs Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cizz3007** [comment]
I Guess It was caused by React Strict Mode

**Comment by yogarasu** [comment]
Due to React18, there was a problem that you could not specify className for SwiperSlide.

To avoid that I downgraded to React 17.

**Comment by yogarasu** [comment]
I tried debugging the code briefly,
but It seems that the handling of VFC and FC has changed with React 18, so that may be the cause.

**Comment by Muhammad-Zeshan-Tufail** [comment]
Due to React18, there was a problem that you could not specify className for SwiperSlide.
you can use a new div between the SwiperSlide and there use your classes

**Comment by dottodot** [comment]
I'm having this issue when used with nextjs but just tried to replicate with a basic example on codepen and I'm not getting the error, so there must be something else in my setup causing it. https://codesandbox.io/s/swiper-default-react-forked-3y14np

**Comment by raphaelsaunier** [comment]
Running into this issue as well with Next.js 12.1.5 + React 18.0.0; at one point `getSlideClasses` gets called on a destroyed Swiper instance and this causes the exception:

![image](https://user-images.githubusercontent.com/170256/164652405-b1566165-337a-46fb-8b1d-88ae25525d2e.png)

@Muhammad-Zeshan-Tufail's workaround seems to work; if the `SwiperSlide` component doesn't have a `className`, no exception is thrown

I'll try to create codesandbox reproduction; @nolimits4web what's your preferred workflow for issues that were closed with the `missing demo` label? Will you reopen this issue if I post a repro here or shall I create a new issue?

**Comment by nolimits4web** [comment]
@raphaelsaunier better create a new one

**Comment by jordanlambrecht** [comment]
Upgrading to ^8.2.2 seemed to fix it for me without needing to switch strict mode to false

**Comment by DongwonTTuna** [comment]
To solve this problem, you need to update swiper to latest version.

try this command to update your swiper to latest version.
'''
npm install swiper@latest
'''

or

'''
yarn add swiper@latest
'''

I hope it can help you.

**Comment by evgeniy28** [comment]
> 
Latest swiper don't work for me. 
I fix this problem only downgrade swiper to latest 8 version:
```diff
"next": "13.1.5",
"react": "18.2.0",
"react-dom": "18.2.0",
- "swiper": "9.0.2",
+ "swiper": "8.4.7",
```

**Comment by TFMahabub** [comment]
> > 
> 
> Latest swiper don't work for me. I fix this problem only downgrade swiper to latest 8 version:
> 
> ```diff
> "next": "13.1.5",
> "react": "18.2.0",
> "react-dom": "18.2.0",
> - "swiper": "9.0.2",
> + "swiper": "8.4.7",
> ```

how did you install "swiper": "8.4.7" with yarn?

**Comment by mamal72** [comment]
It's still there on `9.0.2`. The downgrade to `8.4.7` was the only way.

**Comment by mahadidev** [comment]
If you are using Nextjs Image component inside the slide them replace the <Image /> with html element <img />.

**Comment by diginikkari** [comment]
@mahadidev could you elaborate more what should be replaced when using nextjs image component?

**Comment by dertuman** [comment]
@diginikkari what he means is to use the standard img html element instead of the Image from next.js. I did this and I think as of today is the best solution

**Comment by mahadidev** [comment]
> 



> @mahadidev could you elaborate more what should be replaced when using nextjs image component?

I have updated my comment. please check it out.

**Comment by tronglongphung** [comment]
@dertuman The latest version worked without using a regular img HTML element

**Comment by techclubr** [comment]
downgrading to swiper version 8.4.7 worked for me

**Comment by dertuman** [comment]
> @dertuman The latest version worked without using a regular img HTML element

Okay I'll give it a shot! Ty.

**Comment by DongwonTTuna** [comment]
Thanks to guys who defined this bug is occured when we add <Image /> in Next.js.

The latest version is works for me in below codes.

Difference of my code is
`slideClass="swiper-slide"`
in the <Swiper>


`
    <Swiper
      slidesPerView={1}
      loop={true}
      slideClass="swiper-slide"
      lazy="false"
    >
        {photos.map((src, index) => {
            return (
              <SwiperSlide key={`sl${index}`} className="h-full">
                <Image
                  src={src}
                  style={{ objectFit: "cover", height: "100%" }}
                  alt="slidesImg"
                />
              </SwiperSlide>
            );
          })
        }
    </Swiper>
`

I hope It works in your case.

**Comment by tahericode** [comment]
> > 
> 
> Latest swiper don't work for me. I fix this problem only downgrade swiper to latest 8 version:
> 
> ```diff
> "next": "13.1.5",
> "react": "18.2.0",
> "react-dom": "18.2.0",
> - "swiper": "9.0.2",
> + "swiper": "8.4.7",
> ```

I also had the problem with wrapperClass, and by updating swiper to the latest version, my problem was solved

**Comment by Hachikoi-the-creator** [comment]
I really don't think removing the Image Next componet is a good approach since it'll remove it's image optimization features, downgrading swiper to 8.4.7 worked for me as well, even made me able to use the `loop={true}` prop with no problems!

**Comment by Hachikoi-the-creator** [comment]
> > 
> 
> Latest swiper don't work for me. I fix this problem only downgrade swiper to latest 8 version:
> 
> ```diff
> "next": "13.1.5",
> "react": "18.2.0",
> "react-dom": "18.2.0",
> - "swiper": "9.0.2",
> + "swiper": "8.4.7",
> ```

I really don't think removing the Image Next componet is a good approach since it'll remove it's image optimization features, downgrading swiper to 8.4.7 worked for me as well, even made me able to use the loop={true} prop with no problems!

**Comment by fresonn** [comment]
**Still relevant!**
I don't want to disable strict mode.

```javascript
onSwiper={(swiper) => {
    const el = swiper.el
    el.addEventListener('mouseenter', () => {
      swiper.autoplay.stop()
    })

    el.addEventListener('mouseleave', () => {
      swiper.autoplay.start()
    })
 }}
```

Error: `TypeError: Cannot read properties of undefined (reading 'stop' | 'start')`
