### ISSUE TITLE
Safari vertical scroll issue

### ISSUE THREAD

**Issue by Farzin-Firoozi** [nolimits4web/swiper#5621]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://user-images.githubusercontent.com/52259209/162573054-ade51db7-a42a-4987-9d98-ad23f3fb7271.gif

### Bug description

Safari vertical scroll issue on old devices (e.g. iPhone 8)

<img src="https://user-images.githubusercontent.com/52259209/162573054-ade51db7-a42a-4987-9d98-ad23f3fb7271.gif" width="400px" />

### Expected Behavior

Vertical scroll should keep working like other places.

### Actual Behavior

Vertical scroll is not working while you scroll on a Swiper horizontal list.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Old safari mobile devices such as iPhone8

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by leandrocrs** [comment]
Still happening on iPhone 11 + iOS 16.2
