### ISSUE TITLE
When total item is not a multiple of items-per-group and loop is true. Prev button stay on the same group. 

### ISSUE THREAD

**Issue by Baben01** [nolimits4web/swiper#5624]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/dazzling-ramanujan-zv5nby?file=/src/App.vue

### Bug description

I got a problem when the number of `swiper-slide` is not a multiple of item-per-group parameter Number. (For example I have 8 swiper-slide and item-per-group is equal to 5) and loop is set to true.

When I try to go to previous using navigation, it's looping on the same group. 

### Expected Behavior

Should succeed to go to the previous slide group.

### Actual Behavior

Stay on the current slide group.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Chrome / Vue

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by DeiFro** [comment]
Bug still exists in 8.2.4

Code pen:
https://codepen.io/deifro/pen/eYVoOoY - duplicate swiper slides are in a different colour

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
