### ISSUE TITLE
Unexpected behavior when right clicking on a link

### ISSUE THREAD

**Issue by Grumvol** [nolimits4web/swiper#5625]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#slides-per-view

### Bug description

Right-clicking on a link in a slide will move to the next slide. To reproduce the error, the slide must not be the first in a row.

![QIP Shot - Screen 1287](https://user-images.githubusercontent.com/20611667/162740983-024636c5-2c88-4da8-b237-054b1619241f.png)

### Expected Behavior

Context menu open

### Actual Behavior

Move to the next slide and context menu open

### Swiper version

8.1.0

### Platform/Target and Browser Versions

Windows 10, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by robizzt** [comment]
Can confirm, same happening to me. If slide is not on the first position, right click will move that slide to the first position.

**Comment by ThatWebCo** [comment]
Same happening here. Only seems to happen when slidesPerGroup is a different number to slidesPerView.

**Comment by Grumvol** [comment]
Same behavior on smartphones after touch. That is, it is impossible to follow the link if it is inside the slide. This is a very annoying bug, only for this reason I can't use version 8.

**Comment by mohamadsinane** [comment]
Hello, i got the same issue.
It seams that adding `watchSlidesProgress: true,` to my default config fixes the issue.

**Comment by Grumvol** [comment]
> watchSlidesProgress: true

Thanks

**Comment by dijkermans** [comment]
> Hello, i got the same issue. It seams that adding `watchSlidesProgress: true,` to my default config fixes the issue.

Yes but I noticed it's CPU intensive. I hope there's a better solution.

**Comment by Superhands89** [comment]
This is now fixed for desktop but this is still an issue on mobile/touch devices in version 8.4.2

**Comment by Blacklightdesign** [comment]
I have a solution that mobile touch on ui elements like links or select fields no longer makes the slide jump to first place. Touch events also trigger a focus event. I added a condition to check that the focus event was not triggered by touch.
#6139
