### ISSUE TITLE
swiper-bundle.min.js and other files are missing from package.json "exports"

### ISSUE THREAD

**Issue by Roffild** [nolimits4web/swiper#5629]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/

### Bug description

swiper-bundle.min.js and other files are missing from package.json "exports".

https://github.com/evanw/esbuild/issues/2180

### Swiper version

8.1.0

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
because these files are not intended to be used with imports, use `import Swiper from 'swiper/bundle'` instead
