### ISSUE TITLE
swiper instance: Cannot read properties of undefined (reading 'slideChange') with React 18

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [nolimits4web/swiper#5635]
### Check that this is really a bug

- [X] I confirm

### Reproduction link
**upd**: https://github.com/b-novikov-ipersonality/swiper-react18-bug

### Bug description

After initializing swiper instance by passing `<Swiper>` component `setState` function, when using any of the swiper instance events, for  example

```js
swiper.on('slideChange', (swiper) => ...)
```
or any other, I get runtime error: `TypeError: Cannot read properties of undefined (reading 'activeIndexChange')`
<details>
<summary>error img</summary>

![image](https://user-images.githubusercontent.com/89237497/163666187-937d8e1b-66d7-4782-a361-b122fa56e449.png)

</details>

Note that Swiper has many problems with React 18, among them #5613 #5630 #5609 so it's probably some form of incompatibility with react 18. Maybe until the fix is released you should make Swiper require react <18.0.0? 

Steps to reproduce: 
1. create new react app
2. paste following code into component

```js
export default function Home() {
  const [swiper, setSwiper] = useState(null);
  const [currentSlide, setCurrentSlide] = useState(0);
  useEffect(() => {
    if (swiper) {
      swiper.on('activeIndexChange', (swiper) => {
        setCurrentSlide(swiper.realIndex);
      })
    }
  }, [swiper])
  return (
        <>
          <h1>CURRENT SLIDE: {currentSlide}</h1>
          <Swiper draggable className={styles.swiper} onSwiper={setSwiper}>
            <SwiperSlide>1</SwiperSlide>
            <SwiperSlide>2</SwiperSlide>
            <SwiperSlide>3</SwiperSlide>
            <SwiperSlide>4</SwiperSlide>
            <SwiperSlide>5</SwiperSlide>
          </Swiper>
        </>
  );
}
```
3. use component somewhere in your app 
4. experience error and sorrow

### Expected Behavior

I can use event listeners on swiper instances without error

### Actual Behavior

When using event listeners on swiper instance error `TypeError: Cannot read properties of undefined (reading 'event_name')` occur where `event_name` is the name of the used event

### Swiper version

"^8.1.1"

### Platform/Target and Browser Versions

linux, chrome Version 100.0.4896.88 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Would be good to see live example with the issue (without Next, as it could be a problem), so far I couldn't replicate it

**Comment by b-novikov-ipersonality** [comment]
@nolimits4web I updated repository that is in reproduction link

`git clone git@github.com:b-novikov-ipersonality/swiper-react18-bug.git`
`cd swiper-react18-bug`
`yarn`
`yarn start`

**Comment by nolimits4web** [comment]
Would be still good to see issue in code sandbox as you can see all works correctly here https://codesandbox.io/s/swiper-default-react-forked-wxrchz?file=/src/App.jsx, try also to remove React.StrictMode

**Comment by b-novikov-ipersonality** [comment]
@nolimits4web, problem is only reproducible with Strict mode enabled. But in my opinion removing strict mode shouldn't be a permanent solution because strict mode helps here and there in development.

**Comment by b-novikov-ipersonality** [comment]
@nolimits4web I'm still having this problem, can you reopen the issue please?

**Comment by vandreleal** [comment]
Hi @b-novikov-ipersonality , were you able to address this issue without disabling strict mode?

**Comment by b-novikov-ipersonality** [comment]
@vandreleal hey. It was fixed by @nolimits4web. 
If it still does not work for you, the workaround was provided by @MaksimAmelchenko:

replace `thumbs={{ swiper: thumbsSwiper }}` to `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

**Comment by krystiangryczon** [comment]
for me there was slightly different error of `TypeError: Cannot read properties of undefined (reading 'cssMode')`, and actually it was the Cookiebot interfering with this somehow, [check out here](https://support.cookiebot.com/hc/en-us/community/posts/360005072140-error-when-Cookie-blocking-mode-at-auto)

**Comment by riccardolardi** [comment]
> for me there was slightly different error of `TypeError: Cannot read properties of undefined (reading 'cssMode')`, and actually it was the Cookiebot interfering with this somehow, [check out here](https://support.cookiebot.com/hc/en-us/community/posts/360005072140-error-when-Cookie-blocking-mode-at-auto)

@krystiangryczon have you found a workaround or solution?
