### ISSUE TITLE
Using / for division outside of calc() is deprecated

### ISSUE THREAD

**Issue by spostad7** [nolimits4web/swiper#5636]
#### DEPRECATION WARNING: 
```Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.```

<br />
This is deprecation warning on building web app with swiper in following files:

```src/styles/partials/swiper-button.module.scss```

#### Recommendation: 

```math.div(-$arrow-size, 2) or calc(-$arrow-size / 2)```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is no such file here `src/styles/partials/swiper-button.module.scss` and there is no references to `$arrow-size` as well, not sure what you are using

**Comment by spostad7** [comment]
@nolimits4web :
sorry, I just check the code and confirm that this is in my local file
Thanks for your response
