### ISSUE TITLE
[React] `slideToClickedSlide` and `loop` not working

### ISSUE THREAD

**Issue by vicasas** [nolimits4web/swiper#5637]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-slidetoclickedslide-and-loop-not-working-l54wm8?file=/src/App.js

### Bug description

activating `slideToClickedSlide` and `loop` breaks the loop. This can be seen when you click on the next slide and when you go back to position `0` no more slides appear.

### Expected Behavior

I hope that by having both options activated, the feature of each one is fulfilled, being able to click on the slide that follows with the loop effect.

### Actual Behavior

Nowadays clicking on the next slide and reaching position `0` breaks the loop effect.

### Swiper version

8.1.0

### Platform/Target and Browser Versions

macOs bigsur Chrome lastest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vicasas** [comment]
This may be related to #3171 being closed due to inactivity.

**Comment by vicasas** [comment]
closes in favor of #5642

**Comment by vicasas** [comment]
same problem as in #5642 but now with `slideToClickedSlide ` enabled and using the previous solution `loopedSlides` or `loopAdditionalSlides`

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
