### ISSUE TITLE
Slides do not switch smoothly

### ISSUE THREAD

**Issue by dimitr0960** [nolimits4web/swiper#5639]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-css-mode-react-forked-b2nori

### Bug description

cssMode is good work, but need without cssMode
video link:
https://ru.files.fm/f/tcxmnkycb

and link code
https://codesandbox.io/s/swiper-css-mode-react-forked-b2nori

### Expected Behavior

Slides switch smoothly like cssMode

### Swiper version

6.8.1

### Platform/Target and Browser Versions

IOS v15.4.1 and Chrome v100.0.4896.85

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I am on the same iOS and Chrome version, everything is smooth. It related to some system or Chrome settings on your device
