### ISSUE TITLE
Swiper not usable with Vue & SSR - ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by awacode21** [nolimits4web/swiper#5640]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-snxrnn?file=package.json&terminal=build

### Bug description

See reproduction link. When running build and preview it results in this error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/projects/vitejs-vite-snxrnn/node_modules/swiper/swiper.esm.js from /home/projects/vitejs-vite-snxrnn/dist/server/entry-server.js not supported.
Instead change the require of swiper.esm.js in /home/projects/vitejs-vite-snxrnn/dist/server/entry-server.js to a dynamic import() which is available in all CommonJS modules.
```

I am not able to find a workaround. Please fix or help.

### Expected Behavior

SSR should not have any problems with the swiper import. I would expect no errors.
As i am using a jamstack page, the problem completely prevents me from building successfully

### Actual Behavior

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/projects/vitejs-vite-snxrnn/node_modules/swiper/swiper.esm.js from /home/projects/vitejs-vite-snxrnn/dist/server/entry-server.js not supported.
Instead change the require of swiper.esm.js in /home/projects/vitejs-vite-snxrnn/dist/server/entry-server.js to a dynamic import() which is available in all CommonJS modules.
```

### Swiper version

8.1.1

### Platform/Target and Browser Versions

all platforms, all browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by drivedemon** [comment]
I have the same issue in vue3 (it's working on normal page without swiper)
`Error [ERR_REQUIRE_ESM]: require() of ES Module /home/project/node_modules/swiper/vue/swiper-vue.js from /home/project/public/js/ssr.js not supported.
Instead change the require of swiper-vue.js in /home/project/public/js/ssr.js to a dynamic import() which is available in all CommonJS modules.`

this is ssr js file
```
import { createSSRApp, h } from 'vue';
import { renderToString } from '@vue/server-renderer';
import { createInertiaApp } from '@inertiajs/inertia-vue3';
import createServer from '@inertiajs/server';
import route from 'ziggy';

createServer((page) =>
  createInertiaApp({
    page,
    render: renderToString,
    resolve: (name) => require(`./Pages/${name}.vue`),
    setup({ app, props, plugin }) {
      return createSSRApp({ render: () => h(app, props) })
        .use(plugin)
        .mixin({
          methods: {
            route: (name, params, absolute) => {
              return route(name, params, absolute, {
                ...page.props.ziggy,
                location: new URL(page.props.ziggy.url),
              });
            },
          },
        });
    },
  })
);
```

and this ssr mix file
```
const mix = require('laravel-mix');
const webpackNodeExternals = require('webpack-node-externals');

mix.js('resources/js/ssr.js', 'public/js')
  .vue({
    version: 3,
    useVueStyleLoader: true,
    options: { optimizeSSR: true },
  })
  .alias({
    '@': 'resources/js',
    ziggy: 'vendor/tightenco/ziggy/dist/index',
  })
  .webpackConfig({
    target: 'node',
    externals: [webpackNodeExternals()],
  });

```

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
