### ISSUE TITLE
`loop` does not work as expected

### ISSUE THREAD

**Issue by vicasas** [nolimits4web/swiper#5642]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-slidetoclickedslide-and-loop-not-working-l54wm8?file=/src/App.js

### Bug description

when the `loop` effect is activated it breaks the loop. This can be seen when you start to slide to the next/previous slide.

e.g.

[0, 1, 2, 3, 4]

case 1: When sliding to the fourth position, position 0 is not visible.

case 2: When sliding to position 0 if position 4 is displayed but when sliding to 4 position 3 is not displayed

### Expected Behavior

I expect that having the loop option active behaves as expected.

e.g.

[0, 1, 2, 3, 4]

case 1: When I slide to position 4 it has to show me slide 0

Case 2: When I slide to position 0 it has to show me position 4 on the left side and if I slide to 4 it has to show me position 3.

### Actual Behavior

Today doing the above examples breaks the looping effect.

### Swiper version

8.1.0

### Platform/Target and Browser Versions

macOs bigsur Chrome lastest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is because you added padding, use `loopAdditionalSlides` or `loopedSlides` params in addition
