### ISSUE TITLE
Chrome/Firefox responsive test via device toolbar is detected as Safari – Cube is smaller

### ISSUE THREAD

**Issue by MatzeKitt** [nolimits4web/swiper#5651]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-cube-forked-jb7g2k?file=/index.html

### Bug description

If I use the device list in Chrome/Firefox to test a cube in different devices, it is sometimes detected as Safari with the following user agent:

Chrome:
```
mozilla/5.0 (ipad; cpu os 13_3 like mac os x) applewebkit/605.1.15 (khtml, like gecko) crios/87.0.4280.77 mobile/15e148 safari/604.1
```

Firefox:
```
mozilla/5.0 (ipad; cpu os 14_7_1 like mac os x) applewebkit/605.1.15 (khtml, like gecko) version/14.1.2 mobile/15e148 safari/604.1
```

The problem here is that at least for the cube there is [an additional calculation](https://github.com/nolimits4web/swiper/blob/2041b518c32be414cc113f63af33ce402014a909/src/modules/effect-cube/effect-cube.js#L144-L150) for the `transform3d` for Safari. Since Chrome doesn’t need that, the cube is smaller than it should be.

### Expected Behavior

Chrome/Firefox in the device list is recognized as Chrome, not as Safari.

We could just check for `crios` and `mobile` in the user agent in the function `isSafari()` to fix this.

### Actual Behavior

Chrome gets some styling specific for Safari and thus the cube is smaller than it should be.

See also the screenshots of the demo. You can see it on the position of the navigation dots, which should always be in the same place.
<img width="445" alt="Bildschirmfoto 2022-04-21 um 09 21 36" src="https://user-images.githubusercontent.com/1018979/164400480-83952cee-cc00-449c-b48b-b0ecc7dc43ab.png">
<img width="445" alt="Bildschirmfoto 2022-04-21 um 09 21 52" src="https://user-images.githubusercontent.com/1018979/164400507-6421ff08-738f-4f95-9475-165a10221265.png">

### Swiper version

8.1.3

### Platform/Target and Browser Versions

macOS Chrome 100, macOS Firefox 99.0.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
because it doesn't replicate actually safari, in safari the cube is ok, there is a special fix only for safari

**Comment by MatzeKitt** [comment]
Hm, than I don’t understand this:
https://github.com/nolimits4web/swiper/blob/2041b518c32be414cc113f63af33ce402014a909/src/modules/effect-cube/effect-cube.js#L144-L150

There is a check for Safari and WebView and then there is a different `translate3d`. If you remove this code, the Cube is much larger than it should be.
