### ISSUE TITLE
Prepend function automatically showing first slide 

### ISSUE THREAD

**Issue by arjuntraj** [nolimits4web/Swiper#566]
HI i need to append and  prepend slides dynamically , ie next and prev slide append working fine. if i prepend a new slide when i am on second slide (slide index 1) immediately   slider goes to new prepended slide why.. i need same functionality while appending new slide never change slide while prepend occur.

**Comment by 3zzy** [comment]
I have the same issue, was this ever fixed?

**Comment by SlimSavernake** [comment]
У меня такая-же проблема. Изначально у меня один слайд. Если добавить к нему слайд слева, а потом добавить слайд справа, то все нормально - ничего не происходит, но если сначала добавить правый слайд а потом левый, то сразу после появления левого слайда происходит перелистывание на правый слайд.
