### ISSUE TITLE
ref not exposed to us as prop

### ISSUE THREAD

**Issue by ivanjeremic** [nolimits4web/swiper#5668]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

nope

### Bug description

```js
<Swiper ref={someRef}>
 ...
</Swiper>
```
We can't do this but we should have the option.

### Swiper version

all

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
what do you expect `ref.current` to return?

**Comment by ivanjeremic** [comment]
It works now was an issue with an other hook I guess.

**Comment by 7iomka** [comment]
> ivanjeremic

How you found a workaround for this?

```tsx
 const swiperRef = useRef(null);

// ...
<Swiper ref={swiperRef}
   ... >
</Swiper>

```
gives me
```
Property 'ref' does not exist on type 'IntrinsicAttributes & SwiperProps & { children?: ReactNode; }'
```

Why? Swiper is exported as component with `forwardRef` and types needed to contain `ref`, for example with helper type `React.ForwardRefExoticComponent<SwiperProps & {...}>`

Another issue - I want to have a type of this ref. Currently swiper types not contain type of SwiperClass, but that is what we need.
What do you think? @nolimits4web 

This flow is required for control swiper instance outside.

Thanks.

**Comment by ivanjeremic** [comment]
> > ivanjeremic
> 
> How you found a workaround for this?
> 
> ```tsx
>  const swiperRef = useRef(null);
> 
> // ...
> <Swiper ref={swiperRef}
>    ... >
> </Swiper>
> ```
> 
> gives me
> 
> ```
> Property 'ref' does not exist on type 'IntrinsicAttributes & SwiperProps & { children?: ReactNode; }'
> ```
> 
> Why? Swiper is exported as component with `forwardRef` and types needed to contain `ref`, for example with helper type `React.ForwardRefExoticComponent<SwiperProps & {...}>`
> 
> Another issue - I want to have a type of this ref. Currently swiper types not contain type of SwiperClass, but that is what we need. What do you think? @nolimits4web
> 
> This flow is required for control swiper instance outside.
> 
> Thanks.

If I remember correctly it started working even though the error was there I have no access to the project anymore but this is what I remember.

**Comment by 7iomka** [comment]
In that case, we'll have to wait for a response from @nolimits4web because this is a bug with wrong exported types

**Comment by shotforsky** [comment]
I agreed with the ref proposal~
For now using the `onSwiper` props can help with getting the swiper instance.

Here is my code snippets, for someone might need this:
``` typescript
import { Swiper } from 'swiper/react';
import type { Swiper as SwiperType } from 'swiper';

const swiperRef = useRef<SwiperType | null>(null);

return (
<Swiper
  onSwiper={(swiperInstance) => {
    swiperRef.current = swiperInstance;
  }}
>
...
</Swiper>)
```

BTW, this is based on swiper@8.4.2.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
