### ISSUE TITLE
Usage of breakpoints and loop together leads to hydration mismatch in SSR (Vite/Vue3/Swiper)

### ISSUE THREAD

**Issue by awacode21** [nolimits4web/swiper#5673]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/vite-vue3-ssr-swiper-mismatch?file=src/App.vue

### Bug description

The combined use of breakpoints & loop in SSR project leads to hydration mismatch between Server and Client:
<img width="1043" alt="Bildschirmfoto 2022-04-26 um 01 36 53" src="https://user-images.githubusercontent.com/30939926/165191429-f98e76f0-89dc-465e-bf6c-351c69877cc2.png">

When using only breakpoints without loop it works fine.
When using only loop without breakpoints it works fine.

Using both together ends in hydration mismatch.

See reproduction link: https://stackblitz.com/edit/vite-vue3-ssr-swiper-mismatch?file=src/App.vue (check dev tools console)

Setup: vite, vue3, swiper

### Expected Behavior

No hydration mismatches

### Actual Behavior

Getting hydration mismatches

### Swiper version

^8.1.4

### Platform/Target and Browser Versions

MacOs, Google Chrome Version 100.0.4896.127 (Offizieller Build) (arm64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by awacode21** [comment]
<img width="1916" alt="Bildschirmfoto 2022-04-26 um 01 44 06" src="https://user-images.githubusercontent.com/30939926/165192061-d1738b99-53d5-4084-af35-4b7e7200a79b.png">

**Comment by nolimits4web** [comment]
expected as it is impossible to detect browser window on SSR resulting in different amount of duplicated slides, use `loopedSlides` parameter or init it only on client side

**Comment by awacode21** [comment]
I don't understand how to use loopedSlides, can you please explain?

**Comment by awacode21** [comment]
works, thanks!

**Comment by awacode21** [comment]
@nolimits4web how exactly should the logic of loopedSlides work? because when i use it, swipe back to left really is endless loop, but swipe to right is not. After some images the right button seems to be disabled, as there would be no more images on the right, even if set to loop. you can see what i mean on this stackblitz: https://stackblitz.com/edit/vite-vue3-ssr-swiper-playground?file=src/App.vue

slide to the right, until it stops. no endless loop to the right.
so to be honest i don't understand loopedSlides. Can you please explain me how it works and which behaviour i should expect?
