### ISSUE TITLE
WatchSlidesProgress does not work when SwiperSlide is a multiple of slidesPerView  

### ISSUE THREAD

**Issue by f2283916660** [nolimits4web/swiper#5675]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-thumbs-gallery-loop-react-forked-lt7lcm?file=/src/App.jsx

### Bug description

slidesPerView={5}
SwiperSlide  length = 10
Switch to the sixth , ThumbsSwiper's sixth is not in the visible area

### Expected Behavior

Can display normally

### Actual Behavior

ThumbsSwiper does not display the current item properly

### Swiper version

8.1.4

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by joelthorner** [comment]
I have the same bug :(

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
