### ISSUE TITLE
Swiping on iOS 15.2 in latest Chrome Version slow

### ISSUE THREAD

**Issue by pirata99** [nolimits4web/swiper#5679]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

www.google.es

### Bug description

Hi, I'm using this Swiper's library, which version is 8.1.3 and with Chrome the swiping is clunky. On iPhone Safari it works smoothly as before. With Android also works. Any suggests?

Thanks in advance!!

### Expected Behavior

Swiper working smoothly

### Actual Behavior

swiping is clunky in iOS version 15.2, Chrome latest version.

### Swiper version

8.1.3

### Platform/Target and Browser Versions

15.2 iOS, chrome latest version

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
