### ISSUE TITLE
hide next or prev when on first or last slide

### ISSUE THREAD

**Issue by alfiem** [nolimits4web/Swiper#568]
Hi,

Is it possible to hide next or previous pagination buttons when they have no function, i.e. on first and last slide of slideshow that doesn't loop?

Thanks.

**Comment by RachnaChohan** [comment]
How would I get the prev / next to hide when clicking the arrows? Cause when clicking the pagination and/or swiping the slide the disappear depending if its one the first or last slide. But it is not the case when clicking the prev / next buttons
