### ISSUE TITLE
Multiple Sliders and pagination

### ISSUE THREAD

**Issue by tonioseiler** [nolimits4web/swiper#5682]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://dev.embru.ch/produkte/altorfer-hocker

### Bug description

When having multiple sliders with different option son one page and both of the have a pagination with the same selector, the pagination disapears on all sliders. It seems as if the selector for the pagination element must be unique (its not contextualised)

### Expected Behavior

One slideshow has a pagination and one not...

### Actual Behavior

Pagination disapears on both slideshows

### Swiper version

8.0.3

### Platform/Target and Browser Versions

macOS Firefox, Chrome, Safarai

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by tonioseiler** [comment]
same with the arrows...

**Comment by FlorisSchippers** [comment]
Hi @tonioseiler your reproduction link is behind a login, can you make it publicly accessible?

Dear @nolimits4web do you have any plans to support multiple sliders with pagination on the same page?

**Comment by nolimits4web** [comment]
@FlorisSchippers it was always supported

**Comment by FlorisSchippers** [comment]
@nolimits4web in that case I think we can reopen this issue since I am also experiencing this bug :(

When I have 1 slider my pagination works perfectly, when there are 2 sliders, neither of them have generated pagination elements

**Comment by FlorisSchippers** [comment]
@nolimits4web I debugged your code and figured out that the `init()` function of the `/modules/pagination/pagination.js` file is not capable of differentiating between pagination elements that share a common classname. I had to provide unique classnames to each pagination element in order to generate pagination elements.

@tonioseiler FYI if you still need a solution
