### ISSUE TITLE
`fadeEffect` prop requires `'FadeEffectOptions | undefined'` type. Passing `undefined` causes error

### ISSUE THREAD

**Issue by b-novikov-ipersonality** [nolimits4web/swiper#5683]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/magical-leftpad-19t4jz?file=/src/Carousel.tsx

### Bug description

When you pass `false` value to `fadeEffect` prop, typescript error occurs, but the carousel works as expected

<details>
<summary>typescript error</summary>

```javascript
Type 'false | { crossFade: true; }' is not assignable to type 'FadeEffectOptions | undefined'.
  Type 'false' is not assignable to type 'FadeEffectOptions | undefined'.
```
</details>

When you pass `undefined` value to `fadeEffect` prop, no typescript error occurs, but on page refresh runtime error occurs 

<details>
<summary>runtime error</summary>

```javascript
Cannot read properties of undefined (reading 'crossFade')
```
</details>

### Expected Behavior

When I pass `undefined` as value to `fadeEffect` prop, no error occur on page refresh, carousel works as expected
**OR**
Passing `false` doesn't cause typescript error

### Actual Behavior

When I pass `undefined` as value to `fadeEffect` prop, runtime error occur on page refresh

Passing `false` causes typescript error

### Swiper version

8.1.4

### Platform/Target and Browser Versions

linux, chrome Version 100.0.4896.88 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
