### ISSUE TITLE
bug in core js version 8

### ISSUE THREAD

**Issue by mdesignfa** [nolimits4web/swiper#5689]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://barghijaat.ir/

### Bug description

hellow to the swiper js front-end developer team!
Thanks a lot for your precious and free Slider library
I've used Swiper to develop a wordpress plugin named wooslider (wooslider.ir) and at the begining i used the current verison (i guess ver 7.4.1) everything runned good and without any bugs
my plugin creates products slider (woocomerce) with the power of swiper.js and many options, controlls etc...  with Elementor Widget and wordpress core Shortcodes API..
<<<ISSUE>>>
when i upgraded to the version 8.1.4 i found a bug in the mobile and tablet Touch devices when i click on the LEFT swiper-slide blocks inside my slider the swiper move the slider to the next slide instead of open the link of the product but the RIGHT block works correctly i also tested the Swiper.js Demoes but i could'nt see the same problem!
when i used the JS file with the older verison 7.4.1 the problem that i countered faded away!!

thanks i hope I was able to mentioned the problem in the best way 
YOU can test the problem here ---   https://barghijaat.ir/    --- in the main-page

### Expected Behavior

open the Link of the product inside the div.swiper-slide

### Actual Behavior

move the whole slider to the next slide!

### Swiper version

8.1.4

### Platform/Target and Browser Versions

Android/mobile & Tablet

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
