### ISSUE TITLE
Vue 3 typecheck fails on `:navigation` because it doesn't recognize the type

### ISSUE THREAD

**Issue by stijn-gravity** [nolimits4web/swiper#5693]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

...

### Bug description

```
<template>

<swiper
  slides-per-view="auto"
  :space-between="40"
  :navigation="{
    nextEl: `.swiper-next-${id}`,
    prevEl: `.swiper-prev-${id}`
  }"
  :modules="swiperModules"
>

</template>


```

This component causes the following typescript error when ran with `vue-tsc`

```
Type '{ nextEl: string; prevEl: string; }' is not assignable to type 'undefined'.

55             :navigation="{
```

Something must be wrong with how the `:navigation` type is set. Other properties are recognized with no issues.

### Expected Behavior

There should not be a typescript error since the data matches the expected type, and type `unknown` should not be the type of the prop.

### Actual Behavior

With the prop having type `unknown` it is impossible to match any values with it when you have a strict ts implementation.

### Swiper version

8.1.4

### Platform/Target and Browser Versions

Node 16

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by lucassimines** [comment]
I'm experiencing the same.

When I use `<Swiper :pagination="{ clickable: true }">`, throws an error `Type '{ clickable: true; }' is not assignable to type 'undefined'.ts(2322)`

**Comment by lucassimines** [comment]
@stijn-gravity thanks for the help! I also found another way:
I created a file named `shim-vue.d.ts` and placed in the root directory of the project with the following code:

```
declare module 'swiper/vue' {
  import { DefineComponent } from 'vue';
  export const Swiper: DefineComponent;
  export const SwiperSlide: DefineComponent;
}
```

**Comment by iamzzm** [comment]
> 

Thanks! IT WORKS!

**Comment by iamzzm** [comment]
> @stijn-gravity thanks for the help! I also found another way: I created a file named `shim-vue.d.ts` and placed in the root directory of the project with the following code:
> 
> ```
> declare module 'swiper/vue' {
>   import { DefineComponent } from 'vue';
>   export const Swiper: DefineComponent;
>   export const SwiperSlide: DefineComponent;
> }
> ```

Thanks! IT WORKS!

**Comment by AhmedMuhsingez** [comment]
Is there a similar solution for Next...?

**Comment by LeandroMoura3** [comment]
This problem not was solved.

I have faced this issue right now.

**Comment by LeandroMoura3** [comment]
The swipper-vue.d.ts don't sounds correct.
A fix that simply change the pagination attribute to: pagination?: PaginationOptions | boolean;
