### ISSUE TITLE
SwiperJS Crashes Inside Modal/Popup

### ISSUE THREAD

**Issue by nosisky** [nolimits4web/swiper#5699]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://pjn3nv.csb.app/

### Bug description

Add swiper js inside of a modal, it crashes and the page refreshes. reproduced on IOS 14 upward. 

### Expected Behavior

The expected behaviour is that Swiperjs should work fine inside of a modal without crashing.

### Actual Behavior

SwiperJS crashes when you initialize inside of a modal and the page refreshes.

### Swiper version

7.3.0

### Platform/Target and Browser Versions

IOS Chrome, Safari Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I can not see anything crashes here
https://user-images.githubusercontent.com/999588/167115430-29d1c132-0232-42bd-b26a-05c71bfdbe25.mp4

**Comment by nosisky** [comment]
@nolimits4web  What I am building is a module that can be added on different websites, I noticed when I added it on some sites, the modal closes and the page refresh when Swiperjs is opened, I am guessing this is an issue with memory usage. Any idea how to reduce memory usage on SwiperJS especially on webkit mobile browsers.

**Comment by nosisky** [comment]
What I did to resolve the issue:
1. I reduced image size.
2. Enabled virtual 
3. Removed some unnecessary animations
