### ISSUE TITLE
Vue : loop and centered-slides cant use together

### ISSUE THREAD

**Issue by callmejm** [nolimits4web/swiper#5700]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-centered-vue-forked-869mqm?file=/src/App.vue

### Bug description

First slide empty space, when start dragging, then only it appear 

### Expected Behavior

First slide should be display the duplicate slide to avoid empty space

### Swiper version

6.8.4

### Platform/Target and Browser Versions

Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
swiper 6.8.4 is not maintained anymore, in latest version I see it works correctly https://codesandbox.io/s/swiper-centered-vue-forked-ue5s7i?file=/src/App.vue
