### ISSUE TITLE
Possibility to remove z-index

### ISSUE THREAD

**Issue by osj2507** [nolimits4web/swiper#5704]
### Discussed in https://github.com/nolimits4web/swiper/discussions/5697

<div type='discussions-op-text'>

<sup>Originally posted by **osj2507** May  5, 2022</sup>
If I load your example here
https://swiperjs.com/demos/020-navigation/core
The navigation elements are loaded after the the wrapper element
<div swiper-wrapper></div swiper-wrapper>
<div swiper-navigation-prev></div>
<div swiper-navigation-next></div>

But loading it via React
https://codesandbox.io/s/v8xmc3?file=/src/App.jsx:367-408
the elements are loaded reversed
<div swiper-navigation-prev></div>
<div swiper-navigation-next></div>
<div swiper-wrapper></div swiper-wrapper>

In the first example that actually means that the z-index can be unset and the arrows will still be shown on top of the images and not interfere with other elements.

Could they be moved below in the react implementation, so it is possible to style your way out of getting z-indexes, because then they will just follow proper HTML indexing behavior and there is no need to set it specifically.

I am suggesting this, because on my site it will interferer with other elements on the page when setting z-index.</div>

**Comment by nolimits4web** [comment]
fixed in https://github.com/nolimits4web/swiper/commit/2d3255fe3fdc12344fbac6b6979473258f9c66a8

**Comment by osj2507** [comment]
That was a quick fix, thank you, can't wait to check if it is working as intended
