### ISSUE TITLE
Swiper moves out of screen, when clicking on slides slightly out of view

### ISSUE THREAD

**Issue by OliverOKoenig** [nolimits4web/swiper#5713]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slideintoviewbug-36sq34?file=/src/app/app.component.ts

### Bug description

**Description:**

In case slides are focusable and we focus a slide slightly or fully out of screen, the focused element will be scrolled into view by browser behavior. This scrolling is not recognized by swiperjs. In effect, the user cannot swipe with mouse-grab actions. This occurs on all screen sizes, but is efficiently reproducible on a window of 420px width or smaller; used was a Chrome 100.0.4896.127.

**State:**

Run the example angular component or the simple html+js.
[index.zip](https://github.com/nolimits4web/swiper/files/8668103/index.zip)
Reduce window width to 420px.
The third and the fourth input should be at least partially out of the screen.

**Reproduce:**

Use tab zu set focus on fourth input.
The input is scrolled into view.
Grab the swiper with the mouse and try to bring the first input into view.

**Questions:**

What is the recommended way of action here? 

### Expected Behavior

You should be able to swipe back manually.

### Actual Behavior

The complete swiper is moved to the left with the issue, that the first swiper-item can't come back into view.

### Swiper version

8.1.4

### Platform/Target and Browser Versions

Chrome 100.0.4896.127 + several mobile devices like iOS, Android and Firefox on PC, too

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
