### ISSUE TITLE
autoplay infinite slider a small flicker occurs

### ISSUE THREAD

**Issue by ErenYalcn** [nolimits4web/swiper#5714]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-shift-6z5jk1?file=/index.html

### Bug description

While 4 sliders appear on the screen (the number does not matter), a small slide appears after watching for a while. I changed all the settings, but I couldn't move forward. What causes the problem and how can we fix it?

### Expected Behavior

should slide smoothly

### Actual Behavior

stuttering/slipping and shaking occurs

### Swiper version

Swiper 8.1.0

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by aaharbaugh** [comment]
Experiencing a similar issue as well on macOS Chrome. 

I have a mobile sized slider and desktop sized slider. It seems to be much more visible on the desktop sized slider. 

As the next slide is sliding in it will move smoothly then jump forward 50-100 pixels 1 or 2 times and creates a glitchy appearance.

**Comment by ErenYalcn** [comment]
@aaharbaugh Did you find any solution or a way to fix it?

**Comment by aaharbaugh** [comment]
@ErenYalcn unfortunately not. Sometimes its less noticable. 

I am going to attempt to shorten transition speed, effects, & parallax and see if that helps.

**Comment by ErenYalcn** [comment]
I changed many settings. However, I did not get a result, there may be something I missed;( if you reach a result, can you share it with me here?

**Comment by ErenYalcn** [comment]
@nolimits4web Could you please review the issue?

**Comment by hmp136838** [comment]
I have the same problem. I raised this issue in [**stackoverflow**](https://stackoverflow.com/questions/72424396/why-in-the-infinite-loop-the-sliders-in-swiper-js-jump-when-the-loop-ends) but have not received any response

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
