### ISSUE TITLE
Autoplay and resizing browser while sliding stops play?

### ISSUE THREAD

**Issue by mattpass** [nolimits4web/Swiper#574]
The Swiper at http://plplondon.com/ is set up to autoplay: 5000, you can resize the browser when slides are static and it works fine, slides the next slide in on time.

However, resize the browser _while_ slides are moving and the slide jumps to it's final position and the autoplay seems to stop.

Is this correct? I can't restart them manually by setting:
`<body onresize="mySwiper.reInit();mySwiper.resizeFix();mySwiper.startAutoplay()">`

**Comment by fritzmg** [comment]
This bug seems to happen again. I have a Swiper similar to this fiddle on a page: https://jsfiddle.net/u4oezjnz/1/

Whenever I resize the browser a lot, or if I switch to or from the responsive view mode in FireFox for example, the Swiper just stops autoplaying, with no possibility of resuming.

In the fiddle, just switch to the responsive view mode in FireFox for example to reproduce the problem.

**Comment by Fetzner** [comment]
const text_panel = {
      loop: true,
      speed: 500,
      autoplay: {
        delay: 1000
      },
      centeredSlides: true,
      on: {
        init: function(){
        },
        onAfterResize: function(){
          this.startAutoplay()
        }
      }
    }

this works for me

**Comment by DanDvoracek** [comment]
Yep, it looks like the issue is back, any idea how to restart the swiper after a resize event?

Tried something in those lines without success..

```
...
on: {
  resize: function () {
    // console.log('swiper resize!', this);  --> this is fired
    // this.updateSize(); --> seems to have no effect at all
    // this.updateSize(); --> seems to have no effect at all
    // this.updateSlides(); --> seems to have no effect at all
    // this.updateProgress(); --> seems to have no effect at all
    // this.updateSlidesClasses(); --> seems to have no effect at all
    slider.autoplay.start(); --> NOT RESTARTING
  }
...
}
```
