### ISSUE TITLE
Vertical direction doesn't work

### ISSUE THREAD

**Issue by Arimanecro** [nolimits4web/swiper#5742]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/exciting-ritchie-zizuec?file=/Button.svelte

### Bug description

Vertical direction doesn't work.
See link:
https://codesandbox.io/s/exciting-ritchie-zizuec?file=/Button.svelte

### Swiper version

8.1.6

### Platform/Target and Browser Versions

Window

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Example you posted doesn't have anything related to swiper
