### ISSUE TITLE
Choppy transitions between slides on mobiles

### ISSUE THREAD

**Issue by AbsurdePhoton** [nolimits4web/swiper#5743]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

none

### Bug description

Choppy transitions between slides, but it depends upon the browser used.
Tested with effects : cube, coverflow, flip
Tested with browsers : all major browsers including Safari on IOS - latest versions

### Expected Behavior

Fluid swipe/transition between slides

### Actual Behavior

coverflow and cube effects are the most choppy
flip behaves a bit faster, but it is a simpler effect!

These browsers are very slow, sometimes unresponsive with cube or coverflow effect:
- Firefox
- Opera Mini

Choppy:
- Chrome
- Brave
- Opera

A bit more fluid:
- Kiwi
- Samsung Internet
- Safari on IOS

Maybe a clue: I noticed on my desktop under Linux, with Chrome and Firefox, that the CPU usage becomes a bit high when swiperjs is active : about 26% for the isolated process !!! My computer is a lot faster than any mobile device, so effects are fluid of course. But swiperjs consumes too much CPU to be honest.

Here is the configuration I used :

				  // Optional parameters
				  preloadImages: false,
				  lazy: { // lazysizes not enabled here so use swiperjs lazyload instead
				     enabled: true,
				     loadPrevNext: true,
				  },
		        speed: 1000,
				  loop: true,
				  grabCursor: false,
				  preventInteractionOnTransition: true, // strange interactions on iphone without that
				  effect: "coverflow",
		        coverflowEffect: {
		          rotate: 50,
		          stretch: 1,
		          depth: 100,
		          modifier: 1,
		          slideShadows: false,
		        },
		        autoplay: {
		          delay: 4000,
		          disableOnInteraction: false,
		        },
		        pagination: {
		          el: ".swiper-pagination",
		          clickable: true,
		        },
				  // Navigation arrows
				  navigation: {
				 	 nextEl: '.swiper-button-next',
				 	 prevEl: '.swiper-button-prev',
				  }

### Swiper version

latest v8

### Platform/Target and Browser Versions

android, ios, linux

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by mindpixel-labs** [comment]
I am experiencing this issue as well on iOS 15.1 Chrome.

**Comment by madebyfabian** [comment]
I am experiencing this as well.
- Chrome iOS v102: Works fine
- Safari iOS 15.5: Choppy Slide Transitions

**Comment by madebyfabian** [comment]
Safari:
https://user-images.githubusercontent.com/32813692/175529996-92c5db5e-6a5e-4495-8bf7-29547e355b4f.mp4

Chrome:
https://user-images.githubusercontent.com/32813692/175530061-862932ab-c9b8-4209-95cc-30d8f6596e9d.MP4

**Comment by madebyfabian** [comment]
Though it seems like this is only an issue on iPhones with the ProMotion (120hz) Display. Can you confirm that? @AbsurdePhoton

**Comment by markky21** [comment]
I also experiencing this problem.

Chrome iOS v103: Choppy
Edge iOS v102: Choppy
Safari iOS 15.5: Almost smooth transition

I'am using modules: Lazy, Navigation, Pagination, A11y, Keyboard, Zoom, History
React version.

Is there a plan to fix this problem?

**Comment by sofly** [comment]
Any news?

**Comment by peterbruins** [comment]
In my case, this issue was be resolved by setting option `cssMode: true`.

Note that this seems to change the way Swiper works drastically, and also disables some features.

https://swiperjs.com/swiper-api#param-cssMode

**Comment by AlexanderBredun** [comment]
same problem

chrome ios 16.2 iphone 14 - Choppy
safari ios 16.0 iphone xs max - Choppy
chrome ios 16.0 iphone xs max - works fine

are you going to fix this? its kind of a big deal

**Comment by nolimits4web** [comment]
Want best performance, use `cssMode`
