### ISSUE TITLE
[Vue warn]: injection "swiper" not found. With useSwiper()

### ISSUE THREAD

**Issue by leosin** [nolimits4web/swiper#5744]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-d4cq6o?file=src/App.vue

### Bug description

I want to control the slide with a new button

so i use this hook `useSwiper` from 
https://swiperjs.com/vue#use-swiper

**the vue tip warn `injection "swiper" not found. `**

<img width="767" alt="image" src="https://user-images.githubusercontent.com/3676670/170561432-5745b59e-8bfa-4bde-a0e9-4293ba325c73.png">

**What am I doing wrong?**

```vue
<script>
// Import Swiper Vue.js components
import { Swiper, SwiperSlide, useSwiper } from 'swiper/vue';

// Import Swiper styles
import 'swiper/css';
import './style.css';

export default {
  components: {
    Swiper,
    SwiperSlide,
  },
  setup() {
    const swiper = useSwiper();
    return {
      swiper,
    };
  },
};
</script>
<template>
  <button @click="swiper.slideNext()">Slide to the next slide</button>
  <swiper class="mySwiper">
    <swiper-slide>Slide 1</swiper-slide>
    <swiper-slide>Slide 2</swiper-slide>
    <swiper-slide>Slide 3</swiper-slide>
    <swiper-slide>Slide 4</swiper-slide>
  </swiper>
</template>

<style></style>
```

### Swiper version

8.1.6

### Platform/Target and Browser Versions

macOS Edge 101

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/vue#use-swiper

> Swiper Vue provides useSwiper hook to easliy get the Swiper instance in components inside of Swiper
