### ISSUE TITLE
Slide completed progress

### ISSUE THREAD

**Issue by Marcelhozeman** [nolimits4web/swiper#5749]
### Clear and concise description of the problem

Make it possible to determine how far a slide is dragged/moved to its next position. So for example request this value with 'swiper.slides[0].fractionalProgress'. So if the slide isn't moving / snapped, this value is always 0. But if the slide moves (manual by dragging or automatically) to its next position then this value will increase slowly from 0 (start position) to 1 (end position). So this means this value will be a floating fractional value like 0.304 or something. Also see this illustration for more details:

<img src="https://user-images.githubusercontent.com/9194881/170954096-0dc0bbcf-786b-4dd3-8d5a-4e1ceaef6b93.png" />

The documentation states that the slide progress can be requested with the property 'progress' when 'watchSlidesProgress' is enabled. But this value doesn't give me the desired results.

**My Swiper uses the following configuration:**

:slides-per-view="1"
:space-between="30"
centeredSlides
loop
:navigation="{
  nextEl: '.swiper-button-next',
  prevEl: '.swiper-button-prev',
}"
:pagination="{ el: '.swiper-pagination', clickable: true }"
@slideChange="onSlideChange"
class="slideshow"
:breakpoints="breakpoints()"

**Use case:**

I want to make the title of the first (previous) slide a color between black and white. So the value 0 should be completely white and 1 is completely black. The values in between determine how far the color deviates to white/black.

### Suggested solution

Add another property to the slides like 'swiper.slides[0].fractionalProgress'. See the explanation in the description above.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
