### ISSUE TITLE
Custom pagination in the loop

### ISSUE THREAD

**Issue by SoulDesignerTom** [nolimits4web/swiper#5754]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://tomb.pl/projects/spotless-water/

### Bug description

This is more like a question than a bug, but i don't think here is place for questions so i ask it as a bug.
If you scroll down the website to the section with '69' number that is counting up - you'll see there is a swiper with custom pagination. Swiper is in the loop (so the slides are duplicated) but - not the pagination - if you scroll to the end pagination will go back to the begining. My code for custom pagination is pretty much like this:

```
new Swiper('.swiper', {
  loop:true,
  pagination: {
    el: '.pagination',
    clickable: true,
    renderBullet: function (index, className) {
      return `<span class="dot swiper-pagination-bullet">${index}</span>`;
    },
  },
});
```

And it works flawlessly - except the pagination isn't in the loop as the swiper itself.
Is there some simple and elegant solution to solve this?

### Expected Behavior

Custom pagination should be in the loop

### Actual Behavior

Custom pagination is not in a loop

### Swiper version

8.2.0

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
