### ISSUE TITLE
swipe to next or prev slides when user's cursor is on the right or left side of the swiper slider

### ISSUE THREAD

**Issue by abdullahtkxel** [nolimits4web/swiper#5768]
### Clear and concise description of the problem

Hi, 

I did google and tried different ways to achieve this but did not succeed.

I'm working on a feature which is when user takes the cursor to the right or the left corner of the slider and holds the cursor for a second then swiper should automatically detect the cursor position if it is on the right side then swiper should swipe to next slide just like the autoplay with delay of specific time and same with if user takes the cursor to left side then swiper should swipe to prev slides.

thanks

### Suggested solution

Hi, 

I did google and tried different ways to achieve this but did not succeed.

I'm working on a feature which is when user takes the cursor to the right or the left corner of the slider and holds the cursor for a second then swiper should automatically detect the cursor position if it is on the right side then swiper should swipe to next slide just like the autoplay with delay of specific time and same with if user takes the cursor to left side then swiper should swipe to prev slides.

thanks

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
