### ISSUE TITLE
swiper.autoplay.timeout change from 6 version

### ISSUE THREAD

**Issue by KGMDev** [nolimits4web/swiper#5770]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsitor.com/bYz-mQ5fo

### Bug description

Hi, I've tried to figure in changelog but I can't found nothing.

Seems that from Swiper v7 something change in autoplay.timeout and this script (for example) don't work properly:

https://jsitor.com/bYz-mQ5fo

There is a new event name for retrieve the same value?

Regards

### Swiper version

8.2.2

### Platform/Target and Browser Versions

Edge Chromium

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
