### ISSUE TITLE
Grid - rows > 1 + fill: 'row' + slidesPerView: 'auto' causes the swiper to go crazy

### ISSUE THREAD

**Issue by mmanista-bynd** [nolimits4web/swiper#5781]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-grid-react-forked-5brvjl?file=/src/App.jsx

### Bug description

I am trying to do a 2-row Swiper with `slidesPerView: 'auto'` and a grid setup, so it looks a bit like a very basic Masonry layout: 
![image](https://user-images.githubusercontent.com/84510160/172604127-8609c307-e188-49ac-872d-aa6a3f46285f.png)

With the following setup, Swiper goes crazy and does not seem to have a consistent number of rows, even though I've specified them to be 2. As a rough example, in my case, for 25 items it collapses into 3 rows (and is not horizontally swipe-able - the width of `.swiper-wrapper` is not calculated properly), but for 100 items it stays in 2 rows, which kind of works.

### Expected Behavior

`.swiper-wrapper`'s width is calculated properly, the items stay in 2 rows (or whatever is specified in `grid.rows` parameter)

### Actual Behavior

`.swiper-wrapper`'s width is not calculated properly (it's less than 100% of the container's width), the items are wrapping into a new line too early, which makes them go into more rows than specified in `grid.rows` param

### Swiper version

7.4.1 (reproduced on 8.2.2 in a codepen)

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
