### ISSUE TITLE
Using breakpoints option in Next JS causes Hydration error

### ISSUE THREAD

**Issue by Sakkhor909** [nolimits4web/swiper#5784]
### Discussed in https://github.com/nolimits4web/swiper/discussions/5776

<div type='discussions-op-text'>

<sup>Originally posted by **Sakkhor909** June  7, 2022</sup>
First of all, thank you for this amazing library.

Everything works fine until I use breakpoints
```
import { Swiper, SwiperSlide } from "swiper/react";
import Image from "next/image";

 <Swiper

        slidesPerView={1}

        breakpoints={{
          1024: {
            slidesPerView: 3,
          },
        }}
 
      >
        {Data.images.map((imgSrc, index) => {
          return (
            <SwiperSlide>
              <Image src={imgSrc} alt={Data.name + index} layout="fill" />
            </SwiperSlide>
          );
        })}
      </Swiper>
```

The error is shown on the next js page
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```
</div>

**Comment by AbdushukurRasulov** [comment]
Than same issue with me also

**Comment by Jared0430** [comment]
Same here

**Comment by iampawan31** [comment]
Using `slidesPerView="auto"` fixed the issue for me.

**Comment by Sakkhor909** [comment]
> Using `slidesPerView="auto"` fixed the issue for me.
> 
> Sample Code for reference
> 
> ```js
> <Swiper
>         spaceBetween={10}
>         slidesPerView="auto"
>         breakpoints={{
>           320: {
>             slidesPerView: 1,
>             spaceBetween: 30,
>           },
>           640: {
>             slidesPerView: 1,
>             spaceBetween: 10,
>           },
>           768: {
>             slidesPerView: 2,
>             spaceBetween: 20,
>           },
>           1024: {
>             slidesPerView: 3,
>             spaceBetween: 30,
>           },
>         }}
>       >
>               <SwiperSlide>Slide one</SwiperSlide>
>       </Swiper>
> ```

Thank you for the solution. It works.

**Comment by Sakkhor909** [comment]
At the moment, No

**Comment by AbdushukurRasulov** [comment]
```
<div className="relative w-full lg:mx-auto lg:max-w-7xl">
          <Swiper
            slidesPerView={3}
            spaceBetween={20}
            breakpoints={{
              768: {
                slidesPerView: 4,
                spaceBetween: 20,
              },
              1024: {
                slidesPerView: 5,
                spaceBetween: 10,
              },
              1280: {
                slidesPerView: 6,
              },
              1440: {
                slidesPerView: 7,
              },
            }}
          >
            {[...Array(7).keys()].map((item) => (
              <SwiperSlide key={item}>
                Slide {item}
               </SwiperSlide>
            ))}
          </Swiper>
        </div>
```
This is my solution. I have used Tailwind CSS, and wrapped `Swiper` with one more div, and gave `width: 100%`.
it works ok

**Comment by laurenskling** [comment]
Just want to clarify here, `slidesPerView="auto"` is not a fix, it's a workaround.

**Comment by moinulmoin** [comment]
`slidesPerView="auto"` also resolved my issue. thanks @iampawan31

**Comment by vicasas** [comment]
If you decide to use `slidesPerView="auto"` you have to take into account that you have to control the **CLS** (Web Vitals) since doing this causes the images to move, in the first render they will be loaded automatically while in the next one it will exist a design change.

**Comment by MuharremGonel** [comment]
> Using `slidesPerView="auto"` fixed the issue for me.
> 
> Sample Code for reference
> 
> ```js
> <Swiper
>         spaceBetween={10}
>         slidesPerView="auto"
>         breakpoints={{
>           320: {
>             slidesPerView: 1,
>             spaceBetween: 30,
>           },
>           640: {
>             slidesPerView: 1,
>             spaceBetween: 10,
>           },
>           768: {
>             slidesPerView: 2,
>             spaceBetween: 20,
>           },
>           1024: {
>             slidesPerView: 3,
>             spaceBetween: 30,
>           },
>         }}
>       >
>               <SwiperSlide>Slide one</SwiperSlide>
>       </Swiper>
> ```
Thank you for the solution. It works.

**Comment by sandrinjoy** [comment]
Is anyone still getting hydration error even after using slidesperview ="auto" ?

```
<Swiper
          spaceBetween={50}
          slidesPerView="auto"
          loopedSlides={3}
          pagination={{
            el: ".my-custom-pagination-div",
            clickable: true,
            renderBullet: (index, className) => {
              return '<span class="' + className + '">' + "</span>";
            },
          }}
          navigation={true}
          loop={true}
          centeredSlides={true}
          breakpoints={{
            992: {
              slidesPerView: 2,
            },
          }}
          onSlideChange={(swiperCore) => {
            const { activeIndex, snapIndex, previousIndex, realIndex } =
              swiperCore;
            setActiveApp(realIndex);
          }}

          // left and right carousels should be half
          // width of the slide
        >
          {data.map((item, index) => {
            return (
              <SwiperSlide key={index}>
                <DataCard
                  visits={visits}
                  item={item}
                  active={activeData === index}
                />
              </SwiperSlide>
            );
          })}

          {isDesktop && (
            <>
              <PrevOverlay />
              <NextOverlay />
            </>
          )}
        </Swiper>

```

**Comment by jakeprins** [comment]
> Is anyone still getting hydration error even after using slidesperview ="auto" ?
> 
> ```
> <Swiper
>           spaceBetween={50}
>           slidesPerView="auto"
>           loopedSlides={3}
>           pagination={{
>             el: ".my-custom-pagination-div",
>             clickable: true,
>             renderBullet: (index, className) => {
>               return '<span class="' + className + '">' + "</span>";
>             },
>           }}
>           navigation={true}
>           loop={true}
>           centeredSlides={true}
>           breakpoints={{
>             992: {
>               slidesPerView: 2,
>             },
>           }}
>           onSlideChange={(swiperCore) => {
>             const { activeIndex, snapIndex, previousIndex, realIndex } =
>               swiperCore;
>             setActiveApp(realIndex);
>           }}
> 
>           // left and right carousels should be half
>           // width of the slide
>         >
>           {data.map((item, index) => {
>             return (
>               <SwiperSlide key={index}>
>                 <DataCard
>                   visits={visits}
>                   item={item}
>                   active={activeData === index}
>                 />
>               </SwiperSlide>
>             );
>           })}
> 
>           {isDesktop && (
>             <>
>               <PrevOverlay />
>               <NextOverlay />
>             </>
>           )}
>         </Swiper>
> ```

Yes

**Comment by kentakunkentakun** [comment]
> Is anyone still getting hydration error even after using slidesperview ="auto" ?
> 
> ```
> <Swiper
>           spaceBetween={50}
>           slidesPerView="auto"
>           loopedSlides={3}
>           pagination={{
>             el: ".my-custom-pagination-div",
>             clickable: true,
>             renderBullet: (index, className) => {
>               return '<span class="' + className + '">' + "</span>";
>             },
>           }}
>           navigation={true}
>           loop={true}
>           centeredSlides={true}
>           breakpoints={{
>             992: {
>               slidesPerView: 2,
>             },
>           }}
>           onSlideChange={(swiperCore) => {
>             const { activeIndex, snapIndex, previousIndex, realIndex } =
>               swiperCore;
>             setActiveApp(realIndex);
>           }}
> 
>           // left and right carousels should be half
>           // width of the slide
>         >
>           {data.map((item, index) => {
>             return (
>               <SwiperSlide key={index}>
>                 <DataCard
>                   visits={visits}
>                   item={item}
>                   active={activeData === index}
>                 />
>               </SwiperSlide>
>             );
>           })}
> 
>           {isDesktop && (
>             <>
>               <PrevOverlay />
>               <NextOverlay />
>             </>
>           )}
>         </Swiper>
> ```
I had a similar situation, but solved it by limiting Swiper calls to client-side. It may be a bit of a messy solution....
↓
```
const [isClient, setIsClient] = useState(false)
const createSwiper = () => {
  if (isClient) {
    return <SlideShowContainer />
  } else {
    <></>
  }
}
useEffect(() => {
  setIsClient(true)
}, [])

// use createSwiper()
const SwiperContainer = () => {
 return {createSwiper()}
}

// Define Swiper
const SlideShowContainer = () => {
 return (
  <Swiper
   .....>
  </Swiper>
}
```

**Comment by kentakunkentakun** [comment]
> Is anyone still getting hydration error even after using slidesperview ="auto" ?
>
> ```
> <Swiper
>           spaceBetween={50}
>           slidesPerView="auto"
>           loopedSlides={3}
>           pagination={{
>             el: ".my-custom-pagination-div",
>             clickable: true,
>             renderBullet: (index, className) => {
>               return '<span class="' + className + '">' + "</span>";
>             },
>           }}
>           navigation={true}
>           loop={true}
>           centeredSlides={true}
>           breakpoints={{
>             992: {
>               slidesPerView: 2,
>             },
>           }}
>           onSlideChange={(swiperCore) => {
>             const { activeIndex, snapIndex, previousIndex, realIndex } =
>               swiperCore;
>             setActiveApp(realIndex);
>           }}
>
>           // left and right carousels should be half
>           // width of the slide
>         >
>           {data.map((item, index) => {
>             return (
>               <SwiperSlide key={index}>
>                 <DataCard
>                   visits={visits}
>                   item={item}
>                   active={activeData === index}
>                 />
>               </SwiperSlide>
>             );
>           })}
>
>           {isDesktop && (
>             <>
>               <PrevOverlay />
>               <NextOverlay />
>             </>
>           )}
>         </Swiper>
> ```
I had a similar situation, but solved it by limiting Swiper calls to client-side. It may be a bit of a messy solution....
↓
```
const [isClient, setIsClient] = useState(false)
const createSwiper = () => {
  if (isClient) {
    return <SlideShowContainer />
  } else {
    <></>
  }
}
useEffect(() => {
  setIsClient(true)
}, [])

// use createSwiper()
const SwiperContainer = () => {
 return {createSwiper()}
}

// Define Swiper
const SlideShowContainer = () => {
 return (
  <Swiper
   .....>
  </Swiper>
}
```

**Comment by kentakunkentakun** [comment]
> Is anyone still getting hydration error even after using slidesperview ="auto" ?
>
> ```
> <Swiper
>           spaceBetween={50}
>           slidesPerView="auto"
>           loopedSlides={3}
>           pagination={{
>             el: ".my-custom-pagination-div",
>             clickable: true,
>             renderBullet: (index, className) => {
>               return '<span class="' + className + '">' + "</span>";
>             },
>           }}
>           navigation={true}
>           loop={true}
>           centeredSlides={true}
>           breakpoints={{
>             992: {
>               slidesPerView: 2,
>             },
>           }}
>           onSlideChange={(swiperCore) => {
>             const { activeIndex, snapIndex, previousIndex, realIndex } =
>               swiperCore;
>             setActiveApp(realIndex);
>           }}
>
>           // left and right carousels should be half
>           // width of the slide
>         >
>           {data.map((item, index) => {
>             return (
>               <SwiperSlide key={index}>
>                 <DataCard
>                   visits={visits}
>                   item={item}
>                   active={activeData === index}
>                 />
>               </SwiperSlide>
>             );
>           })}
>
>           {isDesktop && (
>             <>
>               <PrevOverlay />
>               <NextOverlay />
>             </>
>           )}
>         </Swiper>
> ```
I had a similar situation, but solved it by limiting Swiper calls to client-side. It may be a bit of a messy solution....
↓
```
const [isClient, setIsClient] = useState(false)
const createSwiper = () => {
  if (isClient) {
    return <SlideShowContainer />
  } else {
    <></>
  }
}
useEffect(() => {
  setIsClient(true)
}, [])

// use createSwiper()
const SwiperContainer = () => {
 return {createSwiper()}
}

// Define Swiper
const SlideShowContainer = () => {
 return (
  <Swiper
   .....>
  </Swiper>
}
```

**Comment by Helius01** [comment]
> Using `slidesPerView="auto"` fixed the issue for me.
> 
> Sample Code for reference
> 
> ```js
> <Swiper
>         spaceBetween={10}
>         slidesPerView="auto"
>         breakpoints={{
>           320: {
>             slidesPerView: 1,
>             spaceBetween: 30,
>           },
>           640: {
>             slidesPerView: 1,
>             spaceBetween: 10,
>           },
>           768: {
>             slidesPerView: 2,
>             spaceBetween: 20,
>           },
>           1024: {
>             slidesPerView: 3,
>             spaceBetween: 30,
>           },
>         }}
>       >
>               <SwiperSlide>Slide one</SwiperSlide>
>       </Swiper>
> ```

it does not worked for me .
it seems the `breakepoints' section working with `window` object and its not accessible on **Hydration** .
so is there solution?

**Comment by Helius01** [comment]
I don't know is it dirty or not? but i fixed it by the code :
```
  const [customSwiperOptions, setCustomSwiperOptions] = useState<SwiperOptions>();

  useEffect(() => {
    const options: SwiperOptions = {
      breakpoints: {

        320: {
          slidesPerView: 1,
        },
        640: {
          slidesPerView: 2,
        },
        768: {
          slidesPerView: 3,
        },
        1024: {
          slidesPerView: 4,
        },
        1280: {
          slidesPerView: 5,
        },
        1536: {
          slidesPerView: 6
        }
      }
    }
    setCustomSwiperOptions(options);
  }, [])

 {
          customSwiperOptions &&
          <Swiper modules={[Navigation, Pagination, Scrollbar, A11y]}
            spaceBetween={20}
            navigation
            breakpoints={customSwiperOptions.breakpoints}
            pagination={{ clickable: true }}
            scrollbar={{ draggable: true }}>
            {
              myItems.map((x) => {
                return <SwiperSlide key={x.id} className='p-2'> <Item data={x}></Item></SwiperSlide>
              })
            }
          </Swiper>
}
```

**Comment by sandrinjoy** [comment]
Even if we keep swiper client side isn't it causing a huge CLS ?

**Comment by pieeee** [comment]
> Using `slidesPerView="auto"` fixed the issue for me.
> 
> Sample Code for reference
> 
> ```js
> <Swiper
>         spaceBetween={10}
>         slidesPerView="auto"
>         breakpoints={{
>           320: {
>             slidesPerView: 1,
>             spaceBetween: 30,
>           },
>           640: {
>             slidesPerView: 1,
>             spaceBetween: 10,
>           },
>           768: {
>             slidesPerView: 2,
>             spaceBetween: 20,
>           },
>           1024: {
>             slidesPerView: 3,
>             spaceBetween: 30,
>           },
>         }}
>       >
>               <SwiperSlide>Slide one</SwiperSlide>
>       </Swiper>
> ```

That works, Thanks!!

**Comment by ajmaurya99** [comment]
Thanks it worked for me. :)

**Comment by kaidezen** [comment]
> 

Thank you for this, I feel like this is the best solution on this thread

**Comment by kaidezen** [comment]
> I don't know is it dirty or not? but i fixed it by the code :
> 
> ```
>   const [customSwiperOptions, setCustomSwiperOptions] = useState<SwiperOptions>();
> 
>   useEffect(() => {
>     const options: SwiperOptions = {
>       breakpoints: {
> 
>         320: {
>           slidesPerView: 1,
>         },
>         640: {
>           slidesPerView: 2,
>         },
>         768: {
>           slidesPerView: 3,
>         },
>         1024: {
>           slidesPerView: 4,
>         },
>         1280: {
>           slidesPerView: 5,
>         },
>         1536: {
>           slidesPerView: 6
>         }
>       }
>     }
>     setCustomSwiperOptions(options);
>   }, [])
> 
>  {
>           customSwiperOptions &&
>           <Swiper modules={[Navigation, Pagination, Scrollbar, A11y]}
>             spaceBetween={20}
>             navigation
>             breakpoints={customSwiperOptions.breakpoints}
>             pagination={{ clickable: true }}
>             scrollbar={{ draggable: true }}>
>             {
>               myItems.map((x) => {
>                 return <SwiperSlide key={x.id} className='p-2'> <Item data={x}></Item></SwiperSlide>
>               })
>             }
>           </Swiper>
> }
> ```

Thank you for this, I feel this is the best solution on this thread!

**Comment by bandesha101** [comment]
this is nice
