### ISSUE TITLE
Touch only works after page is refreshed

### ISSUE THREAD

**Issue by dmcgrew** [nolimits4web/swiper#5788]
I am having a frustrating issue with Swiper (I've tried version 5.3.1 and 8.2.2) and I have no idea what is causing it. It happens in Chrome and Firefox (haven't tested any other browsers). When I go to my page for the first time the touch feature does not work. When I try to swipe the entire document looks like it is being dragged within the browser window. When I refresh the page it works perfectly. I can only make this happen by using the inspector and use simulated touch. It also seems to only happen when I open the page locally and not through a web server. The project I'm working on is a kiosk that runs the HTML locally Chrome in kiosk mode.

Here is a screen recording that shows what I'm talking about...
https://www.youtube.com/watch?v=4ovSRigd7zQ

Here's a link to the project: https://www.marketspaceagency.com/beta/sae-touch-5/

Here is the code that sets up the Swiper instance..

```
prezNav = new Swiper('.'+section+'.bios_screen .nav_area .swiper-container', {
            slidesPerView: 13,
            spaceBetween: 30,
            freeMode: true,
            centeredSlides: true,
            freeModeSticky: true,
            slideToClickedSlide: true,
            freeModeMomentumRatio: 0.5,

            init: false,
            navigation: {
                nextEl: '.button-next',
                prevEl: '.button-prev',
            },
            //freeModeMomentum: false
            //freeModeMomentumVelocityRatio: 0.5
        });

$(".bios_screen."+section).fadeIn(function(){

            console.log(prezNavStarted);
            if(prezNavStarted === false) {
                prezNav.on("init", function(){
                    console.log("init");

                    gsap.to(".nav_area", {opacity:1, duration:1});

                    prezNavStarted = true;

                });
                prezNav.init();
            }

            console.log("nav number:"+navNumber);
            prezNav.slideTo(navNumber);

            //$(".president_content").show();

            navigating();

        });
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
