### ISSUE TITLE
Broken Navigation with a specific configuration

### ISSUE THREAD

**Issue by chili-fe** [nolimits4web/swiper#5793]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-react-forked-5kpc2j?file=/src/App.jsx:486-500

### Bug description

The Swiper navigation is broken when using these configurations together:

- loop = true
- Breakpoints
  - A decimal **slidesPerView** value (e.g. 4.17)
  - **slidesPerGroup** > 1 (e.g. 4)

### Expected Behavior

- the Navigation start from the first slide
- by clicking to the next or back arrow it moves by _slidesPerGroup_ slides 

Example: 
slidesPerGroup: 4
slidesPerView: 4.4
current slide: 1
expected slide after right arrow click: 5

![image](https://user-images.githubusercontent.com/55757191/173395490-6f67f32b-4148-4ee9-ab9f-4aa33c12ad89.png)
![image](https://user-images.githubusercontent.com/55757191/173395526-37327c59-01e2-4b55-8866-4f7b1703c3d9.png)

### Actual Behavior

- the Navigation start from the last slide
- if you click the right or left arrow, the swiper doesn't shift the given number of slides (slidesPerGroup)

Example: 
slidesPerGroup: 4
slidesPerView: 4.4
current slide: last slide
actual slide after right arrow click: a fraction of the first slide

![image](https://user-images.githubusercontent.com/55757191/173395814-8b01a091-1eae-4f4b-b494-5748afd459f0.png)
![image](https://user-images.githubusercontent.com/55757191/173395833-acd909b0-64b8-48e6-8549-e3e8b76179a8.png)

Removing the loop = true, or the slidesPerGroup works as expected.

### Swiper version

8.0.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
