### ISSUE TITLE
Missing slices navigating with previous button and multiple slidePerView

### ISSUE THREAD

**Issue by chili-fe** [nolimits4web/swiper#5798]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-react-forked-ifmjh6?file=/src/App.jsx

### Bug description

The Swiper navigation miss slices when using these configurations together:

- loop = true
- Breakpoints
  - A  **slidesPerView** value equal to a  **slidesPerGroup** (e.g. 8)

and navigating two page left from the starting position.

### Expected Behavior

- the Navigation with prev button should show every slice of the carousel
- by clicking to the prev arrow it moves by _slidesPerGroup_ slides 

Example: 
total slides: 20
slidesPerGroup: 8
slidesPerView: 8
current slide: 0

refresh the page (initial visible slides 0-1-2-3-4-5-6-7)
click previous-button two times (two pages left)
expect to view slides: 4-5-6-7-8-9-10-11

### Actual Behavior

slices shown are 0-1-2-3-4-5-6-7 (not 4-5-6-7-8-9-10-11) and user misses 8-9-10-11 slices view 

Example: 
total slides: 20
slidesPerGroup: 8
slidesPerView: 8
current slide: 0

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
