### ISSUE TITLE
Typescript error with `SwiperSlideProps` interface and `@types/react@18`

### ISSUE THREAD

**Issue by francescocaveglia** [nolimits4web/swiper#5799]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/francescocaveglia/swiper-test

### Bug description

The `SwiperSlideProps` interface is not compatible with `@types/react@18`

(the error is solved with `"skipLibCheck": true` but I would prefer to avoid it)

### Expected Behavior

no typescript error

### Actual Behavior

`tsc` command returns this error:
```sh
error TS2430: Interface 'SwiperSlideProps' incorrectly extends interface 'HTMLAttributes<HTMLElement>'.
  Types of property 'children' are incompatible.
    Type 'ReactNode | ((slideData: SlideData) => ReactNode)' is not assignable to type 'ReactNode'.
      Type '(slideData: SlideData) => ReactNode' is not assignable to type 'ReactNode'.

427 interface SwiperSlideProps {
```

### Swiper version

8.2.4

### Platform/Target and Browser Versions

Node

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by edkimmel** [comment]
Seeing this as well.
```
  Type 'ComponentClass<any, any>' is not assignable to type 'ReactNode | ((slideData: SlideData) => ReactNode)'.
```

**Comment by sangmin802** [comment]
Is it resolved?

**Comment by sangmin802** [comment]
Is it solved??

**Comment by dschueller-cs** [comment]
I was able to work around this by removing the react types from my dev dependencies.

`
    "@types/react": "xx.xx.xx",
    "@types/react-dom": "xx.xx.xx",
`

**Comment by dschueller-cs** [comment]
I ended up having to downgrade to React 17 to resolve this.
