### ISSUE TITLE
Safari v16 black flickering on right slide of almost all sliders (proof by video)

### ISSUE THREAD

**Issue by DanielOberlechner** [nolimits4web/swiper#5800]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#infinite-loop

### Bug description

I own a Macbook Pro 16" with macOS Ventura which uses Safari v16.0 .
Many slider's don't work correctly and if you switch slide a black flicker happens.

This can get reproduced on the swiperjs website.

I even made a short clip to describe the issue better:
https://user-images.githubusercontent.com/10922763/173672756-56845390-1d5b-4fee-b998-447c49ef14f3.mov
https://youtu.be/HpTp97CuoLY
Kind regards,
thanks for this code,
Daniel Oberlechner

### Expected Behavior

No flickering while switching slides ...

### Actual Behavior

Black flickering on the right side of the slider.

### Swiper version

8.2.4

### Platform/Target and Browser Versions

macOS Ventura first day patch, Safari 16

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by mhedengren** [comment]
I've got the same issue!
