### ISSUE TITLE
Cursor Grap only works in fist view of slides

### ISSUE THREAD

**Issue by babakfp** [nolimits4web/swiper#5802]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#slides-per-view

### Bug description

https://user-images.githubusercontent.com/44144724/173856945-56557455-1132-4404-9259-d73d4e64d75e.mp4

In the first view of slides, gaping and scrolling with the mouse works fine, but in other slides, it doesn't.

### Would you like to open a PR for this bug?

I'll try 🤷‍♂️.

### Swiper version

8.2.2

### Platform/Target and Browser Versions

Google Chrome - Version 102.0.5005.115 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
you need to change `touchEventsTarget` parameter to have it on everything
