### ISSUE TITLE
Coverflow effect not working

### ISSUE THREAD

**Issue by balramxyadav** [nolimits4web/swiper#5806]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/935sdv?file=/src/App.jsx:181-218

### Bug description

slide always remains 100% of the relative element and if I change the width of the component inside the slide then there is always some space on the right side when slidesPerView is set to auto and when it is set to another number then it continuously varies and I have tried almost every version of swiper but nothing seems to work but it is working on other frameworks

### Expected Behavior

<img width="538" alt="Screenshot 2022-06-18 at 1 59 15 PM" src="https://user-images.githubusercontent.com/104265791/174429694-8b2f59d1-900b-4f67-9f0a-cc00dfd9279e.png">

### Actual Behavior

<img width="474" alt="Screenshot 2022-06-18 at 1 59 54 PM" src="https://user-images.githubusercontent.com/104265791/174429681-afd1b7c9-5cee-447c-b1a7-b160fbfe0921.png">

### Swiper version

latest

### Platform/Target and Browser Versions

firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Error on your side with overwriting styles, it works https://codesandbox.io/s/swiper-effect-coverflow-react-forked-nfou3i?file=/src/main.jsx
