### ISSUE TITLE
Multiple slides per view - Clicking links on mobile (or right click/scroll wheel click on desktop) jumps the clicked element to first position instead of opening the link

### ISSUE THREAD

**Issue by IonutG22** [nolimits4web/swiper#5814]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/Ionut2022/pen/rNJEOgx

### Bug description

In sliders with mutliple elements visible that contain a link, clicking on a slide on a mobile device (simulating touch with browser DevTools also works - refresh page after resizing the window), or right clicking/scroll wheel clicking an slide, jumps the clicked slide to the first position instead of opening the link.

The link opens correctly only when the slider is at the last slide, or clicking the first slide of the current view.

Edit: The problem appeared since version 8.0.0
Version 7.4.1 is the last version that works correctly: https://codepen.io/Ionut2022/pen/ZErdJEb

### Expected Behavior

Clicking a slide that contains a link on a mobile device opens the link.
On desktop, scroll wheel clicking on a slide with a link, opens the link in new tab.

### Actual Behavior

Clicking a slide with a link on a mobile device (other then the first slide in the current view), jumps the clicked slide to the first position and does not open the link.
Scroll wheel clicking a slide with a link, does not open the link and jumps the clicked slide to the first position.

### Swiper version

8.2.4

### Platform/Target and Browser Versions

Android Chrome / Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by romain25** [comment]
Hi everyone, I have the same issue.

**Comment by voran** [comment]
+1

**Comment by MasterProvider** [comment]
add target="_blank" in the inside of your a tag to open a new tab

**Comment by dijkermans** [comment]
"or right clicking/scroll wheel clicking an slide, jumps the clicked slide to the first position instead of opening the link."

seems to be related with: https://github.com/nolimits4web/swiper/issues/5625

**Comment by laurenskling** [comment]
Thanks @nolimits4web , just tested in and fixes the bug! Much appreciated

**Comment by Superhands89** [comment]
This is still an issue on mobile/touch devices in version 8.4.2

**Comment by Blacklightdesign** [comment]
I have a solution that mobile touch on ui elements like links or select fields no longer makes the slide jump to first place. Touch events also trigger a focus event. I added a condition to check that the focus event was not triggered by touch.
#6139
