### ISSUE TITLE
Wrong behaviour on Angular with A11y

### ISSUE THREAD

**Issue by Takkuz** [nolimits4web/swiper#5815]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/Takkuz/IssueReport-SwiperJS-A11y

### Bug description

Seems that swiperSlide directive doesn't bind correctly A11y properties.

Even adding different A11y label within configuration object they're not recognized.

### Expected Behavior

- Every slide page should have his own description;
- Pagination bullet should be selectables and clickable with proper values;
- Changing between content of pages should make a full slide 

### Actual Behavior

- Doesn't read slide page;
- Doesn't get on pagination bullet;
- Doesn't has a full slide with inline content (as you can see in the example provided) 

### Swiper version

8.2.4

### Platform/Target and Browser Versions

Android Chrome 102

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
