### ISSUE TITLE
Svelte access to API could be more idiomatic

### ISSUE THREAD

**Issue by brunnerh** [nolimits4web/swiper#5820]
### Clear and concise description of the problem

Currently in Svelte access to the Swiper API is done via an event:

```svelte
<script>
  let swiper;
</script>

<Swiper on:swiper={e => swiper = e.detail[0]}>...</Swiper>
```

### Suggested solution

In Svelte this usually should be done via a property, which then can just be bound.

```svelte
<script>
  let swiper;
</script>

<Swiper bind:swiper>...</Swiper>
```

An event could still be used in addition to this, though I would name it `init` instead.

Having the event is not strictly necessary as a reactive statement can be used like this:

```js
let swiper;
$: if (swiper) {
  // Executed after the API becomes available
}
```

### Alternative

The component could also export all API methods directly, then `bind:this` could be used instead.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Svelte components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
