### ISSUE TITLE
Constant height with virtual slider

### ISSUE THREAD

**Issue by Zellerich** [nolimits4web/swiper#5833]
### Clear and concise description of the problem

Currently when you are using the virtual option on the slider it has the height of the hightest slide currently in the DOM. When you change slides and a highter slide is loaded into the DOM, the height of the slider changes. The same thing happens for when the hightest slide is removed from the DOM.

### Suggested solution

The virtual slides parameters should have an option that allows you to use the hight of the hightest slide even if it isn't in the DOM. 

For example: 
`<Swiper
          ...
          virtual={{
                    enabled: true,
                    addSlidesAfter: 2,
                    constantHeight: true
}}>`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> should have an option that allows you to use the hight of the hightest slide even if it isn't in the DOM

And how it should know the height if it is not in DOM? Use CSS to make its height fixed then
