### ISSUE TITLE
Autoheight does not work correctly with Virtual Slides

### ISSUE THREAD

**Issue by anton017** [nolimits4web/swiper#5846]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-virtual-slides-forked-b3i0vf?file=/index.html:2413-2423

### Bug description

In Chrome browser but error in all browsers.
Autoheight does not work correctly with Virtual Slides
Height 'swiper-wrapper' is not equal to slider content height.

### Expected Behavior

The height of 'swiper-wrapper' is equal to the height of the slide.
Height should be 100px.

### Swiper version

8.2.6

### Platform/Target and Browser Versions

All browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is the CSS you need to override:
```
.swiper-autoheight, .swiper-autoheight .swiper-slide {
    height: auto;
}
```

**Comment by anton017** [comment]
These styles did not solve the problem - https://codesandbox.io/s/swiper-virtual-slides-forked-von84l
