### ISSUE TITLE
slidesPerView and centeredSlides with loop mode

### ISSUE THREAD

**Issue by Aftershave** [nolimits4web/Swiper#586]
Hello,

Swiper: 2.4
wordpress: 3.8

I am using Swiper to build some carousels.
I have some issues and i am wondering if this could be due to the *slidesPerView* and *loop* options. You can see an example on this sample page: [here](http://www.tomiotee.com/dev/?page_id=2284).

I use this code:

    var $lifestreamswiper = $lifestream.swiper({
    wrapperClass: 'lifestream-slides',
    slideClass: 'lifestream-slide',
    slideElement: 'li',
    grabCursor: true,
    mode: 'horizontal',
    mousewheelControl: false,
    calculateHeight: true,
    centeredSlides: true,
    slidesPerView: ($lifestream.data('items') > $slides.length) ? $slides.length : $lifestream.data('items'),
    loop: true
    });
    // Prev button
    jQuery('#lifestream').find('.lifestream-prev').click(function (e) {
    $lifestreamswiper.swipeNext();
    });
    // Next button
    jQuery('#lifestream').find('.lifestream-next').click(function (e) {
    $lifestreamswiper.swipePrev();
    });

When i change *slidesPerView* to:
- **1** (first carousel): the active slide is not centered into the carousel. Maybe it's due to the css style.
- **2** (second carousel): the active slide is well centered, but the height of the container is not adjusted.

Nevertheless, in the both example, the last slide of the wrapper is not shown inline like the other. I think it's due to the padding applied to the wrapper. Is there a way to solve it?

For information, i try to put *slidesPerView* to auto without success.

Thank you in advance for your help,
jB

**Comment by Uranbold** [comment]
Hello,

This issue is still coming ;)

How do we resolve this?

Demo -> http://themes.themewaves.com/centura/

Check the main slider and end of the loop there has an White Space is there and it comes end of the loop of slider.

Thanks.
