### ISSUE TITLE
using loop mode, accessbility(screen-reader) not work

### ISSUE THREAD

**Issue by HongsCode** [nolimits4web/swiper#5864]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-react-forked-jjeldf?file=/src/App.jsx

### Bug description

Hi 

Problem occurs when using loop mode(enable AutoPlay) in Swiper and turn on Accessbility(Android:talkback, iOS:VoiceOver).

I've used 'tabIndex', but there's still a problem.

### Expected Behavior

When a screen gesture, VoiceOver should move on to the next topic.

### Actual Behavior

The swiper breaks.
The component sounds twice.

first page 
![image](https://user-images.githubusercontent.com/24826568/177888495-6c78698f-f459-4cd4-97c6-78054bac498c.png)

when using screen gesture, move next component
![image](https://user-images.githubusercontent.com/24826568/177888910-3a74f33b-588e-4f5a-bbbe-dde2c07e91e0.png)

### Swiper version

6.8.4

### Platform/Target and Browser Versions

iOS 15.5, android 12

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by jacobmcfarland** [comment]
Im experiencing the same issue as well. 

@HongsCode did you come up with a fix.

**Comment by HongsCode** [comment]
okl
