### ISSUE TITLE
Add className to react/swiper element

### ISSUE THREAD

**Issue by andershagbard** [nolimits4web/swiper#5866]
### Clear and concise description of the problem

I want to be able to add a class on the React Swiper element.

```jsx
<Swiper className="custom-class">
```

### Suggested solution

Merge className prop with default class "swiper"

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://codesandbox.io/s/10st98?file=/src/App.jsx

**Comment by andershagbard** [comment]
> https://codesandbox.io/s/10st98?file=/src/App.jsx
@nolimits4web 

My bad. I meant the SwiperWrapper element.

**Comment by sima-ziyaei** [comment]
@andershagbard did you fix that problem? cause i have the same

**Comment by andershagbard** [comment]
Reopened here: https://github.com/nolimits4web/swiper/issues/6149
