### ISSUE TITLE
Return the remaining time from autoplay function

### ISSUE THREAD

**Issue by baseplate-admin** [nolimits4web/swiper#5871]
### Clear and concise description of the problem

Hi there,

Thanks for making swiperjs.

Now is it possible to get the remaining time for autoplay function ?

For example I have a SwiperJS component that is like this (using `react`)

```typescript

<Swiper
    modules={[AutoPlay]}
    autoplay={{
         delay: 10 * 1000 // 10 seconds in miliseconds 
    }}
>
    {data.map((item, index) => (
        <SwiperSlide key={index}>
            .....
        </SwiperSlide>
    ))}
</Swiper>

```

I want the remaining time to update a slider's progress. 

For example with something like :

```typescript
console.log(swiper.autoplay.remainingTime)
```

The best solution ( for my particular use case ) would be to return autoplay progress as a percent value ( but getting internal timer values will be sufficient for me ) :

For example:

```typescript
console.log(swiper.autoplay.progress) // 70%
```

It is needed in my case so that the user will know when the slide is about to switch.

Is it possible to implement this in swiper core ?

### Suggested solution

Swiper instance should return the internal timer values.
Specifically: 
https://github.com/nolimits4web/swiper/blob/6e947010f065dbaedf3fd00b936a95926d414503/src/modules/autoplay/autoplay.js#L7

### Alternative

Use an external timer and switch the slides manually. Which defeats the purpose of autoplay.

Example (using `react`) :

``` typescript
const [sliderProgress, setSliderProgress] = useState<number>(0);


useEffect(() => {
  const interval = setInterval(() => {
      if (sliderProgress === 100) {
          setSliderProgress(0);
          swiper.slideNext();
      } else {
          setSliderProgress(sliderProgress + (100 / (10 * 1000)) * 200);
      }
  }, 200);
  return () => clearInterval(interval);
}, [sliderProgress, swiper]);

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR ( I can try to get this fixed  but i cant guarantee anything )

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
