### ISSUE TITLE
Swiper is crashed when first sliding on Mobile Devices.

### ISSUE THREAD

**Issue by mwogates** [nolimits4web/Swiper#5872]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://heligram.com/

### Bug description

Swiper is working well on desktop. But if I try to slide on iPhone, it is crashing. I'm not sure what happens here. I'm using Nuxt 3.

Would be great if you can check the link and let me know what you think about it. To check the site, you need to have invite code after siginup. Please email me if you need invite code. Email address: michaelwonggates@gmail.com

https://heligram.com/

### Swiper version

^8.2.6

### Platform/Target and Browser Versions

iOS Chrome, and Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by LiamKarlMitchell** [comment]
Same here, suspect duplicate of another issue.
In Capacitor dev mode with vue 3 it crashes, in Prod mode it worked on iPhone however, very confusing.
Also the first time I use it it works, but breaks when navigating to another page that uses the slider.
I'm using Quasar.

**Comment by Semvrij** [comment]
Did you fix this issue?
