### ISSUE TITLE
focusableElements with allowTouchMove doesn't work

### ISSUE THREAD

**Issue by yasurev86** [nolimits4web/swiper#5878]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/brave-kilby-rfulow

### Bug description

focusableElements: false with allowTouchMove: false
do not work together

### Expected Behavior

when you click on the button in the slide, the prescribed handler is triggered

### Actual Behavior

the slide is changed, after which the button becomes available for clicking

### Swiper version

8.3.0

### Platform/Target and Browser Versions

Windows Chrome, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by Blacklightdesign** [comment]
I have a solution that mobile touch on ui elements like links or select fields no longer makes the slide jump to first place. Touch events also trigger a focus event. I added a condition to check that the focus event was not triggered by touch.
#6139

**Comment by Sefibrah** [comment]
This is how I solved this issue in my Angular project, hopefully, it's replicable in other scenarios. Instead of providing the swiper container ```allowTouchMove``` directly in the template as such:

```
// this DOESN'T WORK (for me at least)
<swiper-container [allowTouchMove]="false"> 
  // stuff
</swiper-container>
```

Instead, I did the following. In my home.component.ts I added an options variable:
```
@Component({ .. })
export class HomeComponent {
  mySwiperOptions: SwiperOptions = {
      allowTouchMove: false,
      // other swiper options
  }
}
```

And provided this variable to the swiper container in my home.component.html like so:
```
<swiper-container [options]="mySwiperOptions"> 
  // stuff
</swiper-container>
```

Hopefully, this helps someone 😁
