### ISSUE TITLE
Pagination events

### ISSUE THREAD

**Issue by point111** [nolimits4web/swiper#5879]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-responsive-breakpoints-forked-euusp9?file=/index.html

### Bug description

Pagination events "paginationShow / paginationHide" not working.

### Expected Behavior

When the screen width is changed and pagination appears, a message is displayed in the console

### Actual Behavior

no messages in console

### Swiper version

8.3.1

### Platform/Target and Browser Versions

win10, firefox 102.0.1 64 bit,  Chrome 103.0.5060.114 64 bit

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This events are intended to be fired as a result of [hideOnClick](https://swiperjs.com/swiper-api#param-pagination-hideOnClick) this parameter, not by breakpoints
