### ISSUE TITLE
Pagination issue with infinite loop and grid

### ISSUE THREAD

**Issue by caroline-iordache** [nolimits4web/swiper#5882]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-grid-forked-jzezb1

### Bug description

When I add the infinite loop option when I use grid, the pagination is miscalculated. Pagination are calculated like if there was no grid.

### Expected Behavior

Have the good number of dots in the pagination

### Actual Behavior

Too many dots

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Chrome 103.0.5060.114

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
