### ISSUE TITLE
Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by indraraj26** [nolimits4web/swiper#5888]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/indraraj26/storage-boolean-issue/tree/swiper-error

### Bug description

Getting error in console related to updateSlideClass and this error will go away if I remove isSekeltonShow `ngIf`
html
```
<ion-content *ngIf="isSkeletonShow">
<swiper [config]="slideMultiMobile" >
  <ng-template swiperSlide *ngFor="let test of [1,2,3,4,5,6]; let i = index">
    <div>
        HELLO
    </div>
  </ng-template>
</swiper>
</ion-content>
```
ts
```
export class HomePage {
  isSkeletonShow = true;
  slideMultiMobile = {
    slidesPerView: 1.2,
    spaceBetween: 10,
    loop: true,
  };

  // eslint-disable-next-line @angular-eslint/use-lifecycle-interface
  async ngOnInit() {
    setTimeout(() => {
      this.isSkeletonShow = false;
    }, 3000);
  }
}

```

![image](https://user-images.githubusercontent.com/23274631/179529403-f294245c-aa5d-4449-bfb8-61503195c291.png)

### Expected Behavior

It should not throw error

### Swiper version

8.3.0

### Platform/Target and Browser Versions

Chrome 103.0.5060.114

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
cc @vltansky can you take a look?

**Comment by vltansky** [comment]
The problem is `ion-content` with loop mode and decimal `slidePerView`

```html
<ion-content>
  <swiper [loop]="true" [slidesPerView]="1.2">
    <ng-template swiperSlide> 1 </ng-template>
    <ng-template swiperSlide> 2 </ng-template>
  </swiper>
</ion-content>
```
Reproduction in react:
https://codesandbox.io/s/ionic-react-animated-carousel-slider-forked-84mkvz?file=/src/pages/Home.tsx

**Comment by nolimits4web** [comment]
I can't see something like this with with loop mode and decimal slidePerView https://codesandbox.io/s/swiper-infinite-loop-with-slides-per-group-react-forked-uh5fgv?file=/src/App.jsx, i assume problem is somewhere else not related to Swiper.

@indraraj26 would be good to see isolated issue in code sandbox

**Comment by indraraj26** [comment]
Thank you @nolimits4web , Looks like it is related to Ionic, Just opened [25671](https://github.com/ionic-team/ionic-framework/issues/25671).
