### ISSUE TITLE
swipe will not work after instant resize window

### ISSUE THREAD

**Issue by indraraj26** [nolimits4web/swiper#5889]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/indraraj26/storage-boolean-issue/tree/swiper-test

### Bug description

Swipe is not working after instant resize from mobile to desktop. You will have to interact with pagination to make it swipe to work again. 

As you can see in below video or download the video by clicking on more 
![image](https://user-images.githubusercontent.com/23274631/179532594-b0439581-e559-4e65-a055-d4adc22b2760.png)

https://user-images.githubusercontent.com/23274631/179532091-06d0bbbe-f2d7-43b9-9cde-aa995fd6fb45.mp4

### Expected Behavior

It should not stuck

### Swiper version

8.3.0

### Platform/Target and Browser Versions

Chrome 103.0.5060.114

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is because you changed the device, where different events are used, which is not real world usage
