### ISSUE TITLE
Swiper Lazy loads same image twice 

### ISSUE THREAD

**Issue by hoektoe** [nolimits4web/swiper#5894]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/370-lazy-load-images/core

### Bug description

SwiperJS triggers a request for lazy loaded images twice. One via loadimage.js and one from dom7. This behavior can be seen on chrome. 

Strangely on firefox, the dom7 request uses the cached image from the first request of loadImage.js

This behavior can be seen on the swiperJS official demo for lazy loading images core.

Having a look at the network tab, you can clearly see it is not optimal. 

Chrome
![image](https://user-images.githubusercontent.com/2276054/179934665-59ca57c4-927c-48da-8eb5-85e477c74422.png)

Firefox Developer Edition
![image](https://user-images.githubusercontent.com/2276054/179936036-9787b464-7199-4432-9fde-e92d7dc68e6d.png)

### Expected Behavior

Only load the image once, worst case second request should use the cached image

### Actual Behavior

Moving to a new slide lazy loads the image twice for exactly the same image

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Windows 10 Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Untick "Disable cache" in dev tools

**Comment by derWebdesigner** [comment]
One hint: Unticking "Disable Cache" obviously solves this issue, but it still feels weird that there are multiple requests. When you put the image into a picture-tag this won't happen anymore by the way, so this is how I "solved" it.
