### ISSUE TITLE
slideChange can fire twice when slidesPerView is set on 'auto'

### ISSUE THREAD

**Issue by 4dr1en** [nolimits4web/swiper#5898]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/4dr1en/pen/GRxmXxN

### Bug description

When slidesPerView is set on 'auto' the slide change twice between the first and the second slide.

This break the width changing animation of the active slide.

### Expected Behavior

I expect the slide to change to only happen once when we click on the next button.

### Actual Behavior

The animation between the first and the second slide is broken because of this double events.

### Swiper version

8.3.1

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by NairiAreg** [comment]
Same issue, BTW the prev button works but not the next
