### ISSUE TITLE
Cannot change slider direction to vertical

### ISSUE THREAD

**Issue by oelbaga** [nolimits4web/swiper#5899]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-js-react-vertical-qudlqi?file=/src/App.js

### Bug description

In Swiper React package you can change the attribute of the direction to vertical and then the slides move vertically. With the Swiper React package if you change to vertical it doesn't work and the slider breaks. There is no way to add the event from the API.

### Expected Behavior

The expectation is that when you change direction to vertical the slider will work and slides will move vertically instead of horizontally.

### Actual Behavior

Slider breaks and slides are not moving in a vertical direction. There isn't a clear way to add the event from the API

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Safari, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Because you didn't speciy its height anywhere https://codesandbox.io/s/swiper-js-react-vertical-forked-qz2vzd?file=/src/App.js
