### ISSUE TITLE
Virtual module makes swiper to crash

### ISSUE THREAD

**Issue by Profesor08** [nolimits4web/swiper#5900]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-virtual-slides-react-forked-tc8fvh?file=/src/App.jsx

### Bug description

If I try to use virtual module, I get this error in console: **Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.**

It happens there, `slide[0]` is not an `Element`: 
https://github.com/nolimits4web/swiper/blob/574572cb3250283800ca5de5c6f76b72adcd5c8e/src/core/update/updateSlides.js#L99

May be it is related to [issues/3786](https://github.com/nolimits4web/swiper/issues/3786), but it is old and without reproduction example

### Expected Behavior

Slider to work and not to crash

### Actual Behavior

Slide is crashing

### Swiper version

8.3.1

### React version

react: 17.0.1
react-dom: 17.0.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

**Comment by Elistratovnik** [comment]
I have the same problem (

**Comment by nolimits4web** [comment]
Have you seen this red note in Virtual slides docs?

<img width="1092" alt="ss" src="https://user-images.githubusercontent.com/999588/180425054-cbe0432e-a483-4749-b405-ac2f02c04031.png">
