### ISSUE TITLE
Swiper 8 - the spaceBetween "GAP" is not swipeable between all slides

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [nolimits4web/swiper#5906]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/ezra_siton/pen/MQgYxV

### Bug description

The spaceBetween "GAP" is not scrollable.

![image](https://user-images.githubusercontent.com/16711871/180893387-0f43e6a3-5777-4b5c-8956-b2ffe26bda88.png)

Official demo for example:
https://swiperjs.com/demos/110-slides-per-view/core
![image](https://user-images.githubusercontent.com/16711871/180895283-d7004785-7399-4da8-9d4c-761ce92fa563.png)

### Expected Behavior

The spaceBetween "GAP" is not scrollable.

### Actual Behavior

The spaceBetween "GAP" also should be scrollable.

### Swiper version

8.3.1

### Platform/Target and Browser Versions

All devices

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
you can change `touchEventsTarget` to `container` to make it work

**Comment by Ezra-Siton-UIX** [comment]
THANKS a lot!!
