### ISSUE TITLE
Swiper jumps to last slide when adding slides dynamically in observer mode

### ISSUE THREAD

**Issue by Givized** [nolimits4web/swiper#5908]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-per-view-forked-zmly8r?file=/index.html

### Bug description

**Setup:**
Multiple slides per view
Adding new slides, when end is reached
Adding slides dynamically, using observer mode

**Issue**
When new items are added, swiper jumps to last added slide, and doesn't maintain current position (active slide index).

So, in the example there are initially 5 slides. When we scroll to last slide (that is when slides 3-4-5 are displayed), 5 new slides are "loaded" and added to the end. When they are appended, Swiper immediately jumps to last slides (8-9-10), not maintaining it's current position, while it is expected that it stays on slides 3-4-5.

### Expected Behavior

When dynamically adding slides to the end, if Swiper is currently on last slide, active index shouldn't change and no horizontal "scrolling" should occur

### Actual Behavior

When dynamically adding slides to the end, if Swiper is currently on last slide, it jumps to the last slide that was just added

### Swiper version

8.2.5

### Platform/Target and Browser Versions

macOS Chrome 103.0.5060.114

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
