### ISSUE TITLE
Swiper beforeSlideChangeStart event fires only once at first move

### ISSUE THREAD

**Issue by dannyarty** [nolimits4web/swiper#5913]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/dannyarty/pen/yLKzYqN

### Bug description

Swiper **beforeSlideChangeStart** event fires only once on first slide change. Same issue with similar events like beforeTransitionStart, slideChange, slideChangeTransitionEnd, slideChangeTransitionStart, slideNextTransitionEnd, slideNextTransitionStart etc.

### Expected Behavior

Fire everytime before/after active slide changed

### Actual Behavior

Fires only once after first active slide changed

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Windows Chrome 103.0.5060.134 64-bit

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by davejtoews** [comment]
I'm seeing this issue on v10.3.0

**Comment by dliebner** [comment]
Seeing this on v11.0.3

**Comment by darQrrR** [comment]
Seeing this on v.11.1.1

**Comment by burzaburzynski** [comment]
Same problem on 11.2.8
