### ISSUE TITLE
Keyboard should not control all swipers on page

### ISSUE THREAD

**Issue by s2danii** [nolimits4web/swiper#5916]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-keyboard-control-react-forked-5ntkuu?file=/src/App.jsx

### Bug description

The keyboard control seems to be based on `document.keydown` (see [code](https://github.com/nolimits4web/swiper/blob/master/src/modules/keyboard/keyboard.js#L116)) so it's controlling all Swipers on the page within the viewport. It's pretty common to have multiple carousels on one page and they should all be able to be controlled via keyboard independently. I think this should also include an update to make Swiper bodies or its default next buttons keyboard tabbable for a fully accessible keyboard experience.

### Expected Behavior

Can keyboard tab to focus on a carousel, press left/right arrows to navigate through swiper, tab out of carousel and not have arrows continue to control the swiper when not in focus

### Actual Behavior

Pressing left/right arrows anywhere in document controls all visible swipers at once. Cannot tab to a specific swiper - keyboard skips right over them.

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by braianxde** [comment]
Please review it guys! It doesn't seems right to control all the swipers at once using keyboard navigation, I'm currently having this issue and I need to do a work around somehow to not have this behavior.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
