### ISSUE TITLE
Event.path is deprecated

### ISSUE THREAD

**Issue by younes-alouani** [nolimits4web/swiper#5925]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/310-thumbs-gallery-loop/core

### Bug description

Warning in shown in google devtools issues : 
Event.path is deprecated and will be removed. Please use Event.composedPath() instead.

### Swiper version

8.3.2

### Platform/Target and Browser Versions

Chrome : Version 103.0.5060.134

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by dijkermans** [comment]
https://chromestatus.com/feature/5726124632965120

It will be removed in version 109. Current version: 103.

Existing pages may use the following polyfill to keep functions:

if (!Event.prototype.path) {
  Object.defineProperty(Event.prototype, 'path', {
    get() { return this.composedPath(); }
  });
}
