### ISSUE TITLE
Rows property in breakpoints is not used

### ISSUE THREAD

**Issue by tom-combet** [nolimits4web/swiper#5928]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/embed/swiper-grid-forked-p9p94k?fontsize=14&hidenavigation=1&theme=dark

### Bug description

Rows property in breakpoints is not used.

### Expected Behavior

I expect to be able to change rows count depending on screen size.

### Actual Behavior

Swiper use only the original rows count value, not the one in breakpoint.

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is no `rows` parameter in Swiper, in breakpoints it must be set in same way: 
```
320: {
  grid: {
    rows: 3,
  }
}

**Comment by tom-combet** [comment]
My bad, thanks for your work.
