### ISSUE TITLE
The swiper scroll-container example code for React is not working in codesandbox

### ISSUE THREAD

**Issue by eye-c** [nolimits4web/swiper#5935]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/eu83dh?file=/src/App.jsx

### Bug description

The scroll container does not scroll in codesandbox. Does the code example need to be updated?

### Expected Behavior

scrollable container

### Actual Behavior

not scrollable and overflow is hidden

### Swiper version

"swiper": "^8.0.0"

### Platform/Target and Browser Versions

linux Chromium and firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
```css
.swiper-slide {
  height: auto !important;
}
