### ISSUE TITLE
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'

### ISSUE THREAD

**Issue by btakita** [nolimits4web/swiper#5943]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/btakita/wholly-trinity/tree/swiper-solid-issue

### Bug description

The compiled solid-js component does not seem compatible with the current version of solid-start.

### Expected Behavior

Successful import of solid-js component.

### Actual Behavior

```
file:///home/brian/work/stargate/wholly-trinity/node_modules/.pnpm/swiper@8.3.2/node_modules/swiper/solid/loop.js:2
import { effect as _$effect } from "solid-js/web";
         ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
```

### Swiper version

8.3.2

### Platform/Target and Browser Versions

Arch Linux all browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by btakita** [comment]
A [similar issue](https://github.com/nolimits4web/swiper/issues/4013) occurred with the svelte components.

The solution was to [include the *.svelte files](https://github.com/nolimits4web/swiper/pull/4014).

**Comment by jchatard** [comment]
I can confirm the bug, @btakita how did you solve the problem with Solid?

**Comment by btakita** [comment]
I ended up not using a slider for the project...but will like to use this swiper with solidjs someday. I had a similar issue w/ the sveltejs integration. To solve that issue, the *.svelte components were distributed in the npm package. Many solidjs developers will be using `solid-start`, which uses `vite`, rollup, & webpack. Ideally, the *.jsx/*.tsx files would be distributed, but nodejs + esm does not seem to be able to load jsx/tsx without it being transpiled.

**Comment by EliBates** [comment]
Just ran into this issue using Astro trying to implement Swiper in Solid.

**Comment by jagu-sayan** [comment]
@nolimits4web It is possible to do a new release ? Thanks for your awesome library.

**Comment by timothyallan** [comment]
My build fails now with the release of 8.4.0, using Vite 3.0.9
```
Error: Build failed with 2 errors:
../node_modules/swiper/solid/swiper-slide.js:71:4: ERROR: The JSX syntax extension is not currently enabled
../node_modules/swiper/solid/swiper.js:210:4: ERROR: The JSX syntax extension is not currently enabled
```

Trying to enable the syntax extension causes more errors elsewhere. Anyone got a quick fix?

**Comment by tweenietomatoes** [comment]
same issue with astro.
