### ISSUE TITLE
Can't swipe between slides after the 1st view.

### ISSUE THREAD

**Issue by ritwaldev** [nolimits4web/swiper#5948]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/9ctd84?file=/index.html

### Bug description

Click and holding to swipe works only between slides in the first view. 

In other words, if you have:
```js
spaceBetween= {25}
slidesPerView= "3"
```
You can click and hold between the 1st and second slide to swipe, same goes for the space between 2nd and 3rd slides, after that, swiping doesn't work in between slides. 

This is mainly because `.swiper-wrapper` is translated to the left and no longer catch click events in the current view.

You can see the bug in the official demos: https://swiperjs.com/demos/150-freemode/core

***Note*** This is not limited to `Freemode`, happens with with any `slidesPerView`.

If you swipe in between the 1st and 2nd slide, or 2nd and 3rd slide, it will work. After that, if you try to swipe in between 3rd and 4th slide you will probably end up highlighting text on the 3rd slide instead of swiping. This goes on for the rest of the slides.

This causes issues because after the 3rd slide swiping becomes buggy as people try to swipe and end up scrolling the screen up and down on mobile devices, or just highlighting stuff on PCs .

### Expected Behavior

`.swiper-wrapper` should either not translate or extend to cover all slides so it can capture click from spaces between all slides, not just those in the first view.

### Swiper version

8.32

### Platform/Target and Browser Versions

Safari iPhone, Chrome and Firefox Desktop

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by ritwaldev** [comment]
This issue was bypassed by setting  ` setWrapperSize={true}`.

**Why is this not the default behavior?**

Without `setWrapperSize={true}`, `swiper-wrapper` will have `width: 100%`,  which only cover the 1st view and not the width of all slides.

Also, from documentation:

> Enabled this option and plugin will set width/height on swiper wrapper equal to total size of all slides. Mostly should be used as compatibility fallback option for browser that don't support flexbox layout well.

The wording makes it sound like a compatibility thing, and that the behavior would be the same in modern browsers, while in fact, that is not true. Without `setWrapperSize={true}`, `swiper-wrapper` won't cover the width of all slides and hence won't capture click events on those after the first view.

**Comment by nolimits4web** [comment]
Please use issues search before posting new one
