### ISSUE TITLE
freemode.momentum false causes autoplay to stop.

### ISSUE THREAD

**Issue by andershagbard** [nolimits4web/swiper#5952]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/andershagbard/pen/wvmxjdz

### Bug description

Initially when you open the page, autoplay is working. When you start dragging, it won't start playing again.

### Expected Behavior

I would expect the autoplay to start again.

### Actual Behavior

Autoplay stops after drag.

### Swiper version

8.3.2

### Platform/Target and Browser Versions

MacOS Chrome 104

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by tylermcrobert** [comment]
I have additional context to add to this. This isn't using freemode.momentum false but it is using free mode and I am having the same issue: https://codesandbox.io/s/swiper-autoplay-bug-u5xqci?file=/src/App.jsx

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
