### ISSUE TITLE
lazyoad skips image when using fractional slidePerView and watchSlidesProgress

### ISSUE THREAD

**Issue by dijkermans** [nolimits4web/swiper#5955]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/dijkermans/pen/vYRzzLb

### Bug description

Hi,

The slider skips a lazy load image in this case; in below example "image04.jpg" is not preloaded but e.g. image05 is preloaded:

https://snipboard.io/BlRwkW.jpg

looks like "watchSlidesProgress:true" is causing the issue but I need it because of the "right click on link resets slider"-bug: https://github.com/nolimits4web/swiper/issues/5814

Regards.

### Expected Behavior

lazy images preloaded, respecting loadPrevNextAmount

### Actual Behavior

image04 skipped from preloading which results in loading-flicker

### Swiper version

8.3.2

### Platform/Target and Browser Versions

win10 / chrome 104

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 doesn't lazy module anymore. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
