### ISSUE TITLE
Tabbing through links in swiper shifts scrollbar out of view

### ISSUE THREAD

**Issue by aferguson64** [nolimits4web/Swiper#596]
In the following example, click a cover and then press the TAB key a number of times.  The scrollbar shifts to the left and eventually off the screen.  I only tested this with the latest Chrome and Firefox browsers on PC.

http://www.theuserfocus.com/mag_browse/cover_test.html

This code will be refactored, but I just wanted to quickly experiment with this swiper.  Any insight into the problem would be much appreciated.

**Comment by hutrang** [comment]
yes, the solution works! thanks!
