### ISSUE TITLE
error "slidesPerColumn" in react 18

### ISSUE THREAD

**Issue by masoud-Tesna** [nolimits4web/swiper#5960]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/ffbzxy

### Bug description

hello i use swiper 8.3.2 in react 18 but get error:

Warning: React does not recognize the `slidesPerColumn` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `slidespercolumn` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

How do I fix it?

### Swiper version

8.3.2

### Platform/Target and Browser Versions

ubuntu - firefox

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check dos, there is no such parameter

**Comment by masoud-Tesna** [comment]
@nolimits4web:
in docs: https://swiperjs.com/demos#slides-per-column

**Comment by GeonwooShin** [comment]
I have a same issue.
