### ISSUE TITLE
defining loop option for different breakpoints breaks the app

### ISSUE THREAD

**Issue by rahanet-ict** [nolimits4web/swiper#5961]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-infinite-loop-react-forked-rofdsy

### Bug description

I faced the issue when I tried to have the slider to be looped on mobile devices. for that when I set loop option in breakpoints, I raised this I issue.

setting loop option inside breakpoints option breaks the application

### Expected Behavior

I expected the slider to be as regular on resolutions more the 1000 and to loop infinitely on resolutions below 500

### Swiper version

8.3.2

### Platform/Target and Browser Versions

Firefox 103.0.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
