### ISSUE TITLE
Accessibility issue: Focusing on input forces slider to jump

### ISSUE THREAD

**Issue by wisniowski** [nolimits4web/swiper#5962]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/embed/swiper-slides-per-view-forked-n8pht9?fontsize=14&hidenavigation=1&theme=dark

### Bug description

Hello,

everything works just great in 99% of scenarios, although I found an odd bug that causes the slider to roughly jump once the input field gets focused - it doesn't even swipe, it simply instantly jumps to another section.

### Expected Behavior

When input/textarea gets focused, swiper should stay.

### Actual Behavior

When input/textarea gets focused, swiper jumps oddly (it doesn't even swipe).

### Swiper version

8.3.2

### Platform/Target and Browser Versions

All

### Validations

- [x] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by conniesmits** [comment]
I have also encountered this problem so hopefully this will be fixed soon, because now we are forced to use an old version of swiper in our project.

**Comment by ntbrown** [comment]
@conniesmits @wisniowski @nolimits4web Likely relevant: https://allyjs.io/tutorials/focusing-in-animated-ui.html

**Comment by mo3az96** [comment]
to workaround disable accessibility (if you don't need accessibility feature) by adding
a11y: {
    enabled: false,
},
to your swiper options

**Comment by Blacklightdesign** [comment]
I have a solution that mobile touch on ui elements like links or select fields no longer makes the slide jump to first place. Touch events also trigger a focus event. I added a condition to check that the focus event was not triggered by touch.
#6139

**Comment by davidmarquis** [comment]
The more appropriate workaround if you don't want to completely disable all accessibility options is to set the `scrollOnFocus` option specifically:

```
a11y: {
scrollOnFocus: false,
},
```
