### ISSUE TITLE
Button on slideable menu doesn't align well

### ISSUE THREAD

**Issue by bensonOSei** [nolimits4web/swiper#5966]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/430-slideable-menu/core

### Bug description

When the menu button is clicked instead of swiped, it doesn't form a perfect cross. It also doesn't allign proper when it is clicked to close the side bar

### Expected Behavior

The bars in the button should rotate to form an `x` shape. And when clicked again to close, it should form straight lines. It should work for both clicks and swipes

### Actual Behavior

The button works only for swipes and not when clicked

### Swiper version

8.3.2

### Platform/Target and Browser Versions

Android (Chrome)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> doesn't form a perfect cross

Tweak it according for your needs, it just for a demo purpose here
