### ISSUE TITLE
Swiper Thumbs Gallery Loop - making issue for thumbs & onSwiper

### ISSUE THREAD

**Issue by dhavalveera** [nolimits4web/swiper#5977]
Hello,

```js
<Swiper loop={true}  spaceBetween={10} autoplay={{ delay: 3000 }} rewind={true} thumbs={{ swiper: thumbsSwiper }} modules={[Autoplay, FreeMode, Thumbs]} className="mySwiper2" >
     <SwiperSlide>...</SwiperSlide>
</Swiper>
```
```js
<Swiper loop={true} slidesPerView={3} spaceBetween={25} freeMode={true} watchSlidesProgress={true} modules={[ Autoplay, FreeMode, Navigation, Thumbs ]} className="mySwiper" autoplay={{ delay: 3000 }} rewind={true} >
    <SwiperSlide>...</SwiperSlide>
</Swiper>
```

then in my Nextjs Web App, it's following the below error.

![image](https://user-images.githubusercontent.com/32231977/185613002-9f0a7045-f8c9-4218-afec-a727dcae48b0.png)

please help me

**Comment by aso1datov** [comment]
This is because `thumbsSwiper` has not been initialized yet.

Try this: 
```
thumbs={thumbsSwiper ? { swiper: thumbsSwiper } : undefined}
```

**Comment by dhavalveera** [comment]
@aso1datov  == Thanks, your solution is working now...

I've one more thing to ask when an Image is active on both the sliders, then in the Thumbs Slider (2nd slider) I want to show some Icon on the Image for one which one is active/selected, can you able to help me how it's possible?

**Comment by aso1datov** [comment]
Try this:
```css
.swiper-slide-thumb-active img  {
    /* your styles */
}
```

**Comment by dhavalveera** [comment]
as I am using in Next.js, so that'll be in global CSS, right?

**Comment by dhavalveera** [comment]
@aso1datov  - I tried but it's not working...

**Comment by aso1datov** [comment]
Check if your styles are overwritten by inline css

**Comment by dhavalveera** [comment]
NO, I am not overriding any CSS Codes for `<Swiper>` as well as for `<SwiperSlide>`

in your case, as in `.thumbnails` for CSS, inside of `.thumbnais {}` you're writing global, so that's with CSS3 or with SCSS/SASS?

**Comment by aso1datov** [comment]
It's [css-modules feature](https://github.com/css-modules/css-modules#exceptions)

**Comment by dhavalveera** [comment]
@aso1datov  --- the CSS code you wrote above, I tried the same here in my local, but it's not working

**Comment by Chandra-Sekhar-Korni** [comment]
@aso1datov ---- I am using a thumb swiper slider, my requirement is I have 30 images and I click the 3rd Image and the 3rd Image has to display without sliding other Images. I am stuck with an issue can you Help us?

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
