### ISSUE TITLE
Mousewheel not scrolling youtube embeds in carousel

### ISSUE THREAD

**Issue by liorPiggy** [nolimits4web/swiper#5980]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-mousewheel-control-react-youtube-issue-twk5w1

### Bug description

When putting youtube embed links they are being rendered in an iframe, when the the cursor is on those iframes, Swiper does not scroll when trying to use the mousewheel.

### Expected Behavior

Scrolling with mousewheel works no matter where the cursor is present and what element it's hovering on.

### Actual Behavior

when cursor is on top of youtube embed, theres no scrolling and the event disappears.
checked another use case where iv'e put the embed outside of a Swiper and tried scrolling when cursor is on it and it scrolls with no issue.

### Swiper version

8.3.2

### Platform/Target and Browser Versions

macOs any browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
this is how iframes work
