### ISSUE TITLE
Loop with coverflow not displaying the last item (as previous item) when first showing the page, when using Array.map

### ISSUE THREAD

**Issue by NathanC** [nolimits4web/swiper#5989]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-coverflow-react-forked-dxbz2f?file=/src/App.jsx

### Bug description

I'm using Swiper with React, with a coverflow effect and `loop` enabled. Settings are as follows:

```tsx
<Swiper
          effect={"coverflow"}
          grabCursor={true}
          centeredSlides={true}
          slidesPerView={"auto"}
          coverflowEffect={{
            rotate: 50,
            stretch: 0,
            depth: 100,
            modifier: 1,
            slideShadows: true,
          }}
          pagination={true}
          modules={[EffectCoverflow, Pagination, Navigation]}
          className="mySwiper"
          navigation
          loop

          loopedSlides={3}
          loopAdditionalSlides={3}
          >
```

When I first render the page, it doesn't show any previous item. When I go through the loop (by clicking right) and eventually loop back to the first item, it *does* show the last item as the previous item.

I attempted to duplicate it with a code sandbox, but was unable to, even though I'm using the exact same swiper settings and imports (I copy and pasted them) and same react and swiper version.

Any idea what could be causing this?

**edit: I've found out that this only happens when I generate my SwiperSlides using `Array.map`, it doesn't happen if I manually add each slide as a child (which I can't do in practice, since it needs to be dynamic). I've updated the code sandbox, but I'm still not able to reproduce it**

### Expected Behavior

The last item should show up as the previous item (on the left in the coverflow) when rendering.

### Actual Behavior

The swiper shows no previous item in the coverflow, though it does show a left navigation arrow.

### Swiper version

8.3.2

### Platform/Target and Browser Versions

Firefox, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by NathanC** [comment]
I inspected elements, and it looks like the first slide is the first slide in the "swiper-wrapper" container, the last slide is not before it.

**Comment by NathanC** [comment]
some additional info: when I click "next", the expected previous slide appears and is visible for a brief second during transitioning.

**Comment by nolimits4web** [comment]
Would be good to see the demo on codesandbox with the issue, right now i can't see issues there

**Comment by wulifangy** [comment]
so, how  to do
