### ISSUE TITLE
Possibly two bugs with Loop and centeredSlides

### ISSUE THREAD

**Issue by onigetoc** [nolimits4web/swiper#5995]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/netflix-vue-swiper-forked-9k3fq2?file=/src/components/HomePage.vue

### Bug description

1. centeredSlides & loop bug.

In my example, i made the active slider bigger. if i'm in mode `loop: false,` and `centeredSlides: false,`
It will not go to the last few elements and the active stop before reaching the last few element and i need the active to make a 
action event later. 

You can use the keyboard arrow to test (To make it work, be sure that the cursor is not stuck in the edition mode then triple click on the result view but outside the Swiper to disable the cursor from the edit).

I want it to look like Fire TV or most Smart TV and the last few slides should go the extreme left too.

Everything is ok in `centeredSlides: true,` mode or `loop: true,`.

2. But there's a second bug the i can't explain.

If you hold the left or right keyboard Arrow  <-   -> in `loop: true,` it will go slower, but it go faster on `loop: false,` mode.
If it got fixed, it may be cool to have a keyboard Arrow hold speed option.

Also, if you click on the left or right arrow very fast repeatedly, it will go as fast as you go on the keyboard in `loop: false,` mode but not in `loop: true,`.

These bugs are the same on every framework like vue or without any external framework.

https://codesandbox.io/s/netflix-vue-swiper-forked-9k3fq2?file=/src/components/HomePage.vue

### Expected Behavior

1. On `loop: false,`, the last few slides should go the extreme left too.
2. Speed option on keyboard arrow and same speed in `loop: false,` or `loop: true,`

### Actual Behavior

1. On `loop: false,`, the last few slides stop in the middle and do not reach the left and are not active slider anymore.
2. Slider speed are not the same in `loop: false,` or `loop: true,` and on keyboard on fast tap on arrow keyboard or on arrow hold too.

### Swiper version

7.0

### Platform/Target and Browser Versions

Cordova

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
