### ISSUE TITLE
Pinch zoom not zooming in correct pinched area

### ISSUE THREAD

**Issue by skysoft-peter** [nolimits4web/swiper#6007]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#zoom

### Bug description

When I pinch zoom on an image, it does not zoom in on the area where I pinched. 
It does not center on the part between the two fingers.
Tested the demo site on an iPhone in Safari and integrated a Swiper Component in an Ionic Capacitor App I'm building.

### Expected Behavior

I expect the pinch zoom to work similar to the pinch zoom on iOS when browsing single photo.
The zoom focuses on the part between the fingers.

### Actual Behavior

When I pinch zoom on an image, it does not zoom in on the area where I pinched. 
It does not center on the part between the two fingers.

### Swiper version

8.3.2

### Platform/Target and Browser Versions

IOS 15.6.1, Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by skysoft-peter** [comment]
I would rely appreciate any feedback...

**Comment by skysoft-peter** [comment]
Never mind. Implemented another component instead of swiperjs

**Comment by j4hangir** [comment]
I confirm this on iOS + vue.

**Comment by mikeyamashita** [comment]
same problem for me as well, ios 16 + angular

**Comment by j4hangir** [comment]
As this isn't resolved, could you please reopen this issue?

**Comment by Julius6599** [comment]
I confirm this on IOS + React.

**Comment by amityweb** [comment]
Is there a solution to this yet please?

**Comment by kevindarm** [comment]
This is still an issue. The zoom seems to go towards the center of the image rather than the point between your fingers.
