### ISSUE TITLE
onInit(), onBeforeInit(), onAfterInit() doesn't work

### ISSUE THREAD

**Issue by VaheMin** [nolimits4web/swiper#6012]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos

### Bug description

Hi, i want to create custom navigation arrows, but when i want to initialize my custom buttons it is not work correctly, then i find that my Swiper component don't call onInit(), onAfterInit(), onBeforeInit() functions, i test it in Chrome and Safari browsers, try it after reinstalling node_modules
` <Swiper
                        slidesPerView={2}
                        spaceBetween={10}
                        slidesPerGroup={1}
                        loop={true}
                        loopFillGroupWithBlank={false}
                        initialSlide={zoomedImg}
                        pagination={{
                            clickable: true,
                        }}
                        navigation={{
                            prevEl: '.button-prev',
                            nextEl: '.button-next',
                        }}
                        modules={[Pagination, Navigation]}
                        className="mySwiper"
                        onInit={(swiper: any) => {
                            debugger
                            setSlideForDownload(zoomedImg)
                        }}
                        onAfterInit={(swiper: any) => {
                            debugger
                            setSlideForDownload(zoomedImg)
                        }}
                        onBeforeInit={(swiper: any) => {
                            debugger
                        }}
                        onSlideChange={(swiper: any) => {
                            setSlideForDownload(swiper.realIndex)
                        }}
                    >`

### Swiper version

8.3.2

### Platform/Target and Browser Versions

MacOS last version Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
how the custom buttons related to these events, would be good to see full example of what you have tried
