### ISSUE TITLE
loop + fractional `slidesPerView`, e.g., 1.3 has several problems => Wrong first slide, bullet index is off, missing next slide

### ISSUE THREAD

**Issue by jakobadam** [nolimits4web/swiper#6024]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-centered-auto-angular-forked-fo69uk?file=/src/app/app.component.ts

### Bug description

Loop mode doesn't work as expected in Angular. Setting `slidesPerView` to a fractional number breaks several things.

```
<swiper
      [slidesPerView]="1.3"
      [centeredSlides]="true"
      [loop]="true"
...
```
1. Wrong first slide + 2. bullet index off
![image](https://user-images.githubusercontent.com/139791/188107561-e338ecbf-3b36-4ff0-82f5-292329cd73f5.png)

3. Missing next slide (occurs circa after one round)
![image](https://user-images.githubusercontent.com/139791/188107840-8655b2ec-51d4-4fb9-8fb1-d75057c9a378.png)

### Expected Behavior

Like it does in React, https://codesandbox.io/s/swiper-centered-auto-react-forked-9sx5pe?file=/src/App.jsx

### Swiper version

8.0.6

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
