### ISSUE TITLE
Sliding in a carousel becomes broken when using loop with hashNavigation

### ISSUE THREAD

**Issue by siminn-arniag** [nolimits4web/swiper#6025]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/embed/exciting-blackburn-p21yuq?fontsize=14&hidenavigation=1&theme=dark

### Bug description

When using HashNavigation with loop={true} in React

The precondition is that:
- slidesPerView is more than 1.
- slidesPerGroup matches slidesPerView.
- Remainder of slides for last view is less than slidesPerView/slidesPerGroup

Example:
- There are 3 slides 
- slidesPerView and slidesPerGroup are 2

The bug is reproduced by
- Clicking next slide arrow button
- Clicking next slide arrow button again
- Clicking previous slide arrow button
- Clicking next slide arrow button
It then becomes broken

### Expected Behavior

It should not become broken :) sliding between views should work.

### Actual Behavior

Sliding between views freezes.

### Swiper version

8.3.2

### Platform/Target and Browser Versions

Windows chrome 104.0.5112.102

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
