### ISSUE TITLE
Speed of reverseDirection autoplay slides increases dramatically on hover/other interactions

### ISSUE THREAD

**Issue by pjaws** [nolimits4web/swiper#6027]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/crimson-currying-mjmfhy?file=/src/App.js

### Bug description

When `reverseDirection` is `true` in a Swiper instance with `autoplay` the slides will often start spinning "out of control".

The easiest way to reproduce this is to refresh the page, then hover over the slides with `reverseDirection`. However, this also occasionally happens on a page refresh without hovering and when switching tabs.

This issue has also been mentioned [here](https://github.com/nolimits4web/swiper/issues/4995), but the reporter thought they fixed it by setting `waitForInteraction` to `true` (which is the default behavior and does not actually fix this problem).

My reproduction link uses `swiper/react`, but it sounds like this is a core issue.

### Expected Behavior

Instances where `reverseDirection` is true should move at the speed set in the settings.

### Actual Behavior

See bug description

### Swiper version

8.3.2

### Platform/Target and Browser Versions

macOS Chrome 104, macOS Firefox 104, Windows Chrome 104

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vburlak** [comment]
+1 `reverseDirection` is broken:
- while switching between browser tabs
- resizing windows size including reverse autoplay swiperjs

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
