### ISSUE TITLE
Click "swiper item" on the mobile terminal, and the automatic rotation cannot be resumed

### ISSUE THREAD

**Issue by MrChenYZ** [nolimits4web/swiper#6040]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://uctest.anta.com:9000/pop-app/pages/home/custom?appTemplateId=56

### Bug description

I have implemented a seamless scrolling configuration, but I found that as long as I `click` one of the `swiper-item`, swiper will stop scrolling, and I can't use `swiper. autoplay. run()` or `swiper. autoplay.start()` to scroll again, and try to modify the values of `running` and `paused` in the past when calling one of these two methods, but both are invalid.
```javascript
    swiperConfig: {
            observer: true,
            loop: !uni.$ca.isDargPage,
            freeMode: true,
            preventClicksPropagation: true,
            speed: 10000, 
            autoplay: {
                delay: 0,
                pauseOnMouseEnter: false,
                stopOnLastSlide: false,
                disableOnInteraction: false
            },
            slidesPerView: 'auto',
            spaceBetween: 14,
            loopedSlides: 6,
            modules: [Autoplay, FreeMode]
        }
```

### Swiper version

8.2.2

### Platform/Target and Browser Versions

Windows Google Chrome 105.0.5195.52

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
