### ISSUE TITLE
You should consider to better curate swiper performance on firefox

### ISSUE THREAD

**Issue by stratboy** [nolimits4web/swiper#6058]
### Clear and concise description of the problem

I'm facing several issues on firefox. It seems it doesn work very well with how swiper is built. 
No troubles in all other browsers.
And for example, some UI Initiative demos do not work very well on Firefox. So you're having the same issues too.

I know firefox is not a main stream browser, but it has a better share than Edge, for example. So please curate it too.

### Suggested solution

Curate swiper performance and especially rendering on firefox.
For example, if I'm applying a css fx to swiper-slide-active, it will work when going to the next slide, but it won't when going back. Same code works perfectly on chrome and safari. That's some sort of firefox rendering problem due to how swiper is built, I guess.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Apparently problem is in Firefox, not Swiper, you should open issue for FireFox asking them to make it perform better
