### ISSUE TITLE
Importing less files are not found

### ISSUE THREAD

**Issue by florinpavel22** [nolimits4web/swiper#6062]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

I don't have one yet

### Bug description

**To reproduce:**
1. Create a new project folder.
2. Run `npm init -y`.
3. Install `less` and `swiper`.
4. Create a `main.less` file in the root/src folder.
5. Create a build script that runs `lessc (src/)main.less output/styles.css`.

Add these lines in the `main.less` file.
```less
@import (less) 'swiper/less';
@import (less) 'swiper/less/navigation';
@import (less) 'swiper/less/pagination';
```

### Expected Behavior

Should have outputted the CSS. Not sure if this is because swiper is using `exports` in their package.json file.
From reports I heard at work, this works fine on Mac.

### Actual Behavior

The build script fails with the following error.

```
FileError: 'swiper/less' wasn't found. Tried - path\swiper-package\swiper\less.less,path\swiper-package\swiper\less.less,npm://swiper\less,npm://swiper\less.less,swiper\less.less in path\swiper-package\main.less on line 1, column 1:
1 @import (less) 'swiper/less';
```

### Swiper version

8.3.2

### Platform/Target and Browser Versions

Windows 10/11 x64

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
issue is on less/node side in your case if it can't detect exports path, try using direct paths to less files in package instead
