### ISSUE TITLE
Issue with 8.4.0 due to PR #5954

### ISSUE THREAD

**Issue by fiveable-jferg** [nolimits4web/swiper#6064]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Will create a repro if needed.

### Bug description

The code in https://github.com/nolimits4web/swiper/pull/5954/files#diff-88a223b4c7649642379e3d1da5338dc2432bbe32b5787cfcda0b484fce3e3786 is causing me issues because there is a circumstance where `displayName` is null, and since there is no check for `&& child.type.displayName` in the if statement, I'm getting a `Cannot read property 'includes' of undefined` when that situation is encountered.   

### Expected Behavior

Check succeeds without error.

### Actual Behavior

TypeError: Cannot read property 'includes' of undefined

### Swiper version

8.4.0

### Platform/Target and Browser Versions

React

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by serdarjan1995** [comment]
I can confirm the issue is valid, as quick workaround we had to use swiper 8.3.2 version.

**Comment by jablonski** [comment]
Same problem here... 

`TypeError: e.type.displayName is undefined`

**Comment by fiveable-jferg** [comment]
Thanks for the quick response!
