### ISSUE TITLE
swiper slide loop start from half of width

### ISSUE THREAD

**Issue by viki-ramesh** [nolimits4web/swiper#6073]
### Discussed in https://github.com/nolimits4web/swiper/discussions/6072

<div type='discussions-op-text'>

<sup>Originally posted by **viki-ramesh** September 17, 2022</sup>
![Screenshot (3)](https://user-images.githubusercontent.com/22514919/190845154-58fbd3a3-0b7c-4f45-b12c-1fb1e91bac17.png)
above image showing how swiper slide loop working. when i manually slide then loop working perfectly as below image show.
![Screenshot (4)](https://user-images.githubusercontent.com/22514919/190845185-4bfed7ab-25cd-4bb2-8007-a8fb492f25c5.png)

video link: https://drive.google.com/file/d/129zRK2VYyzqRmlJ1pz1ER_2IOWR3rvRF/view?usp=sharing

data coming from server.

`function TrendingIGO({ trIGO, loading }) {

    const [state, setState] = useState({
        dataISNull: false,
        isLoading: true
    })

    const swiperSlide = useSwiperSlide();

    const [data, setData] = useState([])
    useEffect(() => {
        setState(prev => {
            return {
                ...prev,
                isLoading: loading
            }
        })

        if (!state.isLoading) {

            trIGO.data !== null ? setData(trIGO.data.filter(igo => igo.trending < 6).sort((a, b) => a.trending - b.trending))
                : setState(prev => {
                    return {
                        ...prev,
                        dataISNull: !prev.dataISNull
                    }
                })

        }

    }, [trIGO, loading])

    const onSwiperStart = (swiper) => {

    }

    return (
        <div className='Trending-IGO title-mrgn'>
            <h1 className='home-title'>TRENDING IGO</h1>
            <div className='ctn-mrgn'>

                {
                    state.isLoading
                        ? state.dataISNull ? <NoData msg={"No Trending IGO"} /> : <div className='trigo-skl-live'><TrIgoSkeleton count={1} /></div>
                        : state.dataISNull ? <NoData msg={"No Trending IGO"} /> :
                            <div className='tr-igo-swiper-wraper'>
                                <Swiper
                                    className='trending-igo-slider'
                                    onSwiper={(swiper => onSwiperStart(swiper))}
                                    initialSlide={0}
                                    spaceBetween={30}
                                    effect={"coverflow"}
                                    grabCursor={true}
                                    centeredSlides={true}
                                    slidesPerView={"auto"}
                                    coverflowEffect={{
                                        rotate: 0,
                                        stretch: 0,
                                        depth: 150,
                                        modifier: 1,
                                        slideShadows: false,
                                    }}
                                    pagination={false}
                                    modules={[EffectCoverflow]}
                                    loopedSlides={data.length > 0 ? data.length : 5}
                                    loop={true}
                                    breakpoints={{
                                        1080: {

                                            spaceBetween: 50,
                                        },
                                    }}
                                >
                                    {
                                        data.map((igo, index) => {
                                            return (
                                                <SwiperSlide key={index}  >
                                                    <IgoLayout igo={igo} />
                                                </SwiperSlide>
                                            )
                                        })
                                    }
                                </Swiper>
                            </div>
                }
            </div>
        </div>
    )
}`</div>

**Comment by nolimits4web** [comment]
Why do you post the same in issues and discussions?
