### ISSUE TITLE
v5.3.6 breakpoints weird behavior

### ISSUE THREAD

**Issue by mapsmarketing** [nolimits4web/swiper#6074]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/mapsmarketing/pen/oNdBOjo

### Bug description

v5.3.6 behaves weird, to say the least

See: https://codepen.io/mapsmarketing/pen/oNdBOjo

```
const swiper = new Swiper('.swiper', {
  slidesPerView: 4,
  breakpoints: {
    767: {
      slidesPerView: 1,
    },
    1024: {
      slidesPerView: 2,
    },
    1600: {
      slidesPerView: 3,
    }
  },
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },
});
```

I expected Swiper breakpoints to work in a similar way as Slick Slider breakpoints: https://kenwheeler.github.io/slick/

Could anyone shed some light on this one?

### Expected Behavior

Please see the above example code.

In a perfect world scenario, the slider should:
- `slidesPerView: 4` window is > `1600px`
- `slidesPerView: 3` window is <= `1600px`
- `slidesPerView: 2` window is <= `1024px`
- `slidesPerView: 1` window is <= `767px`

### Actual Behavior

Please see the above example code.

It's doing the following:
- `slidesPerView: 4` is completely ignored
- `slidesPerView: 3` window is > `1600px`
- `slidesPerView: 2` window is > `1024px`
- `slidesPerView: 1` window is > `767px`

### Swiper version

5.3.6

### Platform/Target and Browser Versions

macOS Chrome Latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Sorry, but 5.3.6 is not maintained anymore

**Comment by mapsmarketing** [comment]
@nolimits4web that's fair enough. Is there any solution for the above released broken version of Swiper?
