### ISSUE TITLE
Slide in closest direction when in loop mode

### ISSUE THREAD

**Issue by infusion** [nolimits4web/swiper#6077]
### Clear and concise description of the problem

Hi,

when sliding to a specific index, one can run `swiper.slideTo(ndx)`. However when having the loop mode enabled, the swiper should have the option to slide in the closest direction to the desired index. For example when being on slide 10 and attempting to go to slide 1, it will go over all slides on the left instead of going one step to the right when having 10 slides in total.

### Suggested solution

Either this becomes the default behavior of `slideTo()` when in loop mode or an option to enable that behavior.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by infusion** [comment]
Just found the `slideToLoop()` method, but the behavior is the same as with `slideTo()`, without going in the closest direction.

**Comment by dijkermans** [comment]
Nice option. I prefer to follow the shortest path of slides you've actually seen. So if you're on slide 8/10 and you haven't seen 9 and 10, and you want to go to 1/10, then I prefer to go back, to the left.

**Comment by jmattiace** [comment]
My workaround for this when in loop mode: 

```
const mySlides = [...] //represents the content in each slide
const nextIndex = 0 //updated when navigating to another slide

...

 if (swiper.realIndex === mySlides.length - 1 && nextIndex === 0) {
    swiper.slideNext()
} else {
    swiper.slideToLoop(nextIndex)
}
```

**Comment by RicardoMoraisPOR** [comment]
+1

i'm having the same issue with 7 slides, 4 showing each time.
if i navigate from slide 6 to slide 1, it scrolls backwards.

@jmattiace that workaround only works if you navigate 1 by 1, if you want to navigate, let's say, from index 1 to index 4, that doesn't work.

**Comment by infusion** [comment]
Any progress on this? Having the same problem on a new project now

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
