### ISSUE TITLE
[vite-node] [ERR_INVALID_URL_SCHEME] /node_modules/swiper/core/core.js

### ISSUE THREAD

**Issue by waysagency** [nolimits4web/swiper#6090]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

/

### Bug description

![image](https://user-images.githubusercontent.com/76130749/191957934-d6aa911d-e6b4-41e8-9844-676a3f373a9e.png)

### Expected Behavior

Importing modules

### Actual Behavior

I try to use the latest swiper (V8.4.2) with nuxt 3 (V3.0.0-rc.11). When I try to import a module (e.g. Navigation), the error will pop up.

```vue
<template>
  <swiper
    :modules="[Navigation, A11y]"
    slides-per-view="1"
    :space-between="20"
    :breakpoints="{
      640: {
        slidesPerView: 2,
      },
      1280: {
        slidesPerView: 3,
      },
    }"
  >
    <swiper-slide v-for="index in 8" :key="index"> Slide {{ index }} </swiper-slide>
  </swiper>
</template>

<script setup>
// import Swiper core and required modules
import { Navigation, A11y } from "swiper";

// Import Swiper Vue.js components
import { Swiper, SwiperSlide } from "swiper/vue";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
</script>
```

```json
{
  "private": true,
  "scripts": {
    "dev": "npx nuxi dev -o --https --ssl-cert localhost.pem --ssl-key localhost-key.pem",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/image-edge": "^1.0.0-27719579.87dcdf2",
    "@nuxtjs/tailwindcss": "^5.3.3",
    "@tailwindcss/forms": "^0.5.3",
    "nuxt": "3.0.0-rc.11",
    "sass": "^1.55.0",
    "sass-loader": "^13.0.2"
  },
  "dependencies": {
    "@storyblok/nuxt": "^4.3.0",
    "swiper": "^8.3.1"
  }
}
```

### Swiper version

8.4.2

### Platform/Target and Browser Versions

Windows, Chrome 105.0.5195.127

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You should open this issue on Nuxt i think

**Comment by wzc520pyfm** [comment]
you can refer to this issue with nuxt, hope to help
https://github.com/nuxt/framework/issues/5348
