### ISSUE TITLE
Do not duplicate slides in loop when effect is fade

### ISSUE THREAD

**Issue by kubiqsk** [nolimits4web/swiper#6091]
### Clear and concise description of the problem

There is no reason to duplicate slides when we use loop together with fade effect for transition.
Duplicated slides can create multiple problems - duplicated titles (bad for SEO?), videos (play/pause sync problems), etc...
It would be great to minimize usage of duplicated slides and I think that this is exactly the case when they are not needed, but still generated

### Suggested solution

Do not duplicate slides in loop when effect is fade

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Then use `rewind` instead https://swiperjs.com/swiper-api#param-rewind
