### ISSUE TITLE
Broken and buggy Autoplay 

### ISSUE THREAD

**Issue by tylermcrobert** [nolimits4web/swiper#6092]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-bug-u5xqci?file=/src/App.jsx

### Bug description

Hello everyone, I'm on my first project using Swiper, so please forgive me if I'm missing something, but I don't believe I am. I am trying to have an autoplaying swiper controlled by mousewheel and drag but `disableOnInteraction: false` does not seem to be working and autoplay in general seems to be pretty buggy. 

### Expected Behavior

Issue 1: In the example above, I should be able to drag the Swiper and have the momentum of the autoplay keep going
Issue 2: I should be able to scroll with `mousewheel: true` and have the autoplay continue

### Actual Behavior

Issue 1: Dragging changes the speed of the autoplay. I can drag the swiper to a stop, and then a second or so later, it begins again
Issue 2: Autoplay stops and then either starts over or resumes a second later.

Both issues: Dragging to a stop will sometimes completely start the swiper over. It looks as if the component is maybe unmounting 

### Swiper version

8.4.2

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
