### ISSUE TITLE
Some '.js' file should use ‘.jsx’ to avoid Bundler Error

### ISSUE THREAD

**Issue by KonghaYao** [nolimits4web/swiper#6098]
I used Vite to bundler swpier, but it failed, because the file in swiper used jsx in js file! 🙂

![image](https://user-images.githubusercontent.com/68177907/192471440-9ed9742f-1714-44a3-9212-fc10896d0ba8.png) 

Some Source Code In This File.

https://github.com/nolimits4web/swiper/blob/0f1e5dd29e9ec2c83f7eefebcfc6ba6f32709eac/src/solid/swiper-slide.js#L71-L97

**Comment by KonghaYao** [comment]
I fixed it used alias and Link File to redireact and rewrite the project file, but It doesn't a good way to share with my partners. 😀

**Comment by KonghaYao** [comment]
I make a demo in stackblitz. Because codesandbox hasn't reappear this problom.

https://stackblitz.com/edit/vitest-dev-vitest-fi8wj7?file=package.json

![image](https://user-images.githubusercontent.com/68177907/192656363-22db88f8-c45e-4cce-99be-bb24201edc8e.png)

**Comment by linkb15** [comment]
Facing this issue in newly created solid js app with vite and installed swiperjs on it and run the example in docs.. cant run pnpm dev.. same like screenshot above about JSX not enabled in vite i think

**Comment by KonghaYao** [comment]
@linkb15 
I rebundle the package (solid-js version) and put it in npm. It has the same method. So I didn't write readme. 

https://www.npmjs.com/package/@cn-ui/swiper

**Comment by skreutzberger** [comment]
I am having the same issue with Solidjs and the Swiper/Solid demo. Here is a vanilla Solidjs repo with Swiper demonstrating the problem: https://github.com/skreutzberger/solidjs-swiper-issue-demo

**Comment by skreutzberger** [comment]
why was it closed? was there a PR which fixed it?
