### ISSUE TITLE
Swiper doesn't work with scrollable div inside until page reload

### ISSUE THREAD

**Issue by scsebuel** [nolimits4web/swiper#6104]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/friendly-river-h24oo1?file=/index.html&resolutionWidth=320&resolutionHeight=675

### Bug description

I tried to create some sort of wallet with swipe functionality inspired by modern wallet apps (e.g. [Google Wallet](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPUGcXapsQkGGerFgbUraO6Il6v0FZEvGeB2jSGtRJf9lg9xyN5_NE25Lr9x812lXp2wdupyugip5puRtjqcvCZZGcoUeDhia09slKOnLKFta9oPVaAcjOAhIHu051uc4mpoUAw9lbWSoOCTjRrmfP9oaUH7ud06BOdjo5kmhqUGjKp49f-Rk6PyFq/s1695/grouping-passes-demo.gif)). If the height of the wallet item exceeds its container, the `div` should be scrollable. There is a bug that on first page load swiper is not working until I refresh. In my project I use Angular and Ionic, but I tried to recreate the behaviour with Swiper Core in the codesandbox linked above. 

### Expected Behavior

Slides should be swipeable.

### Actual Behavior

Initial slide is not swipeable.

### Swiper version

6.8.4, 7.4.1, 8.4.2

### Platform/Target and Browser Versions

macOS Chrome 105.0.5195.125

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by scsebuel** [comment]
Might be an issue related to Chrome. I started the linked Codesandbox in Safari and Firefox, and there it works without the need for refreshing the browser tab.

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
