### ISSUE TITLE
Generate commonjs modules and export them vie export conditionals

### ISSUE THREAD

**Issue by floriangosse** [nolimits4web/swiper#6105]
### Clear and concise description of the problem

Right now it's only possible to import the library from an ESM module or via `import()`. This prevents many applications from using this great library. The problems of importing swiper is quite hard solve as soon as you do things like SSR or SSG where modules often are resolved via Node.js and so there is not proper way of changing the resolution mechanism so that an CommonJS file will be loaded.

I myself stumbled across the problem when I was using swiper in a Next.js application and the module resolution failed on the server side. And we already know about the [problem the people have with using it in Create React App](https://swiperjs.com/react#usage-with-create-react-app).

### Suggested solution

The solution that works for all platforms has two steps:

1. Provide CommonJS files with `.cjs` as file extension
	This follows the specifications of the Node.js module resolution mechanism which defines that CommonJS file have to have the file extension `.cjs` if `"type": "module"` is set in `package.json`
1. Define conditional exports `import` and `require` for the exports defined in `package.json`
	Example:
	```json
	{
		"exports": {
			".": {
				"import": "./swiper.esm.js",
				"require": "./swiper.cjs.cjs"
			}
		}
	}
	```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Since Swiper 7 it was moved to ES modules only by intention
