### ISSUE TITLE
Vue 2 swiper-slide rendered outside swiper-wrapper

### ISSUE THREAD

**Issue by dtrethewey** [nolimits4web/swiper#6118]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/vue-2-swiper-bug-hacky-fix-jbx8l8

### Bug description

In Vue 2 the `swiper-slide` components end up outside the `swiper-wrapper` div and the instance therefore fails to work.

In the linked codesandbox example by default the instance is broken.

If you then go into `src/components/HelloWorld.vue` and uncomment the `wrapper-start` slot wrapper around the swiper-slide items it works fine.

This is a proper hacky fix, but it shows that the latest version of the Vue component can work fine in Vue 2. I'm still not entirely sure if you guys are supporting Vue 2 as I've seen conflicting statements from third parties. I don't see anything in the docs (https://swiperjs.com/vue) that indicate you DON'T support Vue 2. Either way, something is failing when detecting the child elements and not putting them in the correct wrapper element. If they are forced there, e.g. prepending them to the wrapper via the slot hack above, swiper works fine.

I've seen similar issues posted like https://github.com/nolimits4web/swiper/issues/3808 and https://github.com/nolimits4web/swiper/issues/4413 so it seems like it might be a recurring issue.

### Expected Behavior

The `swiper-slide` rendered divs should be inside the `swiper-wrapper` div

### Actual Behavior

The `swiper-slide` rendered divs are OUTSIDE the `swiper-wrapper` div

### Swiper version

8.4.2

### Platform/Target and Browser Versions

Chrome 105

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Vue 2 is not supported

**Comment by dtrethewey** [comment]
Fair enough if you aren't supporting Vue 2, although it would be useful to have that on the documentation page.

I'll have to go with the wrapper-start prepend hack as described to get it working for now. Unfortunately we can't upgrade to Vue 3 right now as we are waiting on Vuetify 3 to be released as stable and even then we can't move over until they have updated all components, which might be fairly deep into 2023.

Vue 2 is still supported until the end of 2023 and https://github.com/surmon-china/vue-awesome-swiper is just too out of date to be considered. If I get some time I might have a look at forking this project and adding what I hope is a small tweak to the `getChildren()` function, which is all it seems to be preventing it from working.

**Comment by joaopedrodcf** [comment]
Following the idea of `wrapper-start` I made this codesanbox example of it working for those who also come here in the future: https://codesandbox.io/s/vue-2-7-working-with-swiper-uwk4m4?file=/src/components/HelloWorld.vue

It's using vue 2.7 and swiper-vue

**Comment by JamshidKHudoyberdiyev** [comment]
> This is quite old but but unfortunate that didn't worked for you

thanks bro it worked
