### ISSUE TITLE
Swiper Types not working

### ISSUE THREAD

**Issue by ocdejong** [nolimits4web/swiper#6122]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/youthful-turing-yof0hu?file=/src/App.vue

### Bug description

While working with Swiper (vite, vue, typescript), I found that many of the - sometimes very basic - types did not work. In a few cases the importing of types caused internal errors that I could not fix (run `npm run dev` in CodeSandbox example), in other cases the expected type showed not sufficient to type the object (the Navigation options object can not be typed by type NavigationOptions).

### Expected Behavior

typing the swiper object with the Swiper type, and all other typings described above should work without errors or warnings.

### Actual Behavior

Objects and types that are matched intuitively throw (internal) errors. It is clear that types are not supported by Swiper, even though it states otherwise.

### Swiper version

8.4.2

### Platform/Target and Browser Versions

macOS Monterey 12.5 - Chrome 105.0.5195.125

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by naimkhalifa** [comment]
_(the Navigation options object can not be typed by type NavigationOptions)._
I confirme that statement. This is very annoying and I still have to find a somehow clean workaround.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
