### ISSUE TITLE
hashNavigation is not compatible with mousewheel

### ISSUE THREAD

**Issue by mmestiyak** [nolimits4web/swiper#6125]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/swiper-demo-32-hash-navigation?file=index.html

### Bug description

```
  const swiper = new Swiper('.swiper', {
      mousewheel: {
        releaseOnEdges: true,
      },
      hashNavigation: {
        watchState: true
      },
    });
```

hashNavigation pushes state to history and pops state when only i slide with grabbing mouse but when use mouse wheel just like scroll down and up, hash navigation functionality doesn't work 

### Swiper version

8.0.0

### Platform/Target and Browser Versions

Chrome Latest Version

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The link you provided doesn't illustrate the issue
