### ISSUE TITLE
onNavigationHide and other navigation events doesn't work

### ISSUE THREAD

**Issue by dimahalaiskiy** [nolimits4web/swiper#6137]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/relaxed-silence-vzkrox

### Bug description

When I increase width of viewport navigation is hide and shows when the viewpor width decrease. Event 'onNavigationHide' or 'onNavigationShow' doesn't work.

### Expected Behavior

Event 'onNavigationHide' or 'onNavigationShow' works when viewport size changes.

### Actual Behavior

Event 'onNavigationHide' or 'onNavigationShow' doesn't work when viewport size changes.

### Swiper version

^8.4.2

### Platform/Target and Browser Versions

macOS, Mozilla Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
These events are for `hideOnClick` functionality
