### ISSUE TITLE
HREF links do not always work when simulateTouch: true

### ISSUE THREAD

**Issue by jonathan-davies-linedup** [nolimits4web/swiper#6143]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://finisterre.com

### Bug description

This is a very intermittent bug, but when **simulateTouch: true** on non-touchscreen devices (e.g. desktops), sometime the HREF links on slides do not work. The user does not navigate to the intended URL.

This is not currently deployed to production.

### Expected Behavior

HREF links should take you to the correct web-page.

### Actual Behavior

No response

### Swiper version

8.2.2 and above

### Platform/Target and Browser Versions

macOS Chrome 105 (and more generally)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Increase `threshold` parameter

**Comment by jonathan-davies-linedup** [comment]
Thank you - we are not currently using threshold, so I am unclear how much to "increase" it by, as we have no baseline. I have chosen 10, as a bit of a random choice. Please advise?
