### ISSUE TITLE
Swiper autoplay stop when vue-router has keep-alive 

### ISSUE THREAD

**Issue by JongHyeonSong** [nolimits4web/swiper#6144]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://adorable-griffin-dd9d31.netlify.app/

### Bug description

with basic vue and vue-router app and keep-alive option like
```vue
  <RouterView v-slot="{Component}">
    <KeepAlive>
      <component :is="Component" />
    </KeepAlive>
  </RouterView>
```

1. at first, "/" page i add autoplay option and it works well
2. i click About link "/about" and then scroll little bit(not too small)
3. go back to "/" with browser back button
4. swiper autoplay stopped
5. but i swiped it with mouse, then it run autoplay well again

https://github.com/JongHyeonSong/v2.git (source file)

### Expected Behavior

when go back with browser back autoplay should work well

### Actual Behavior

when go back with browser back autoplay stopped

### Swiper version

8.4.4

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper can't work correctly when it is not in DOM. Use Swiper APIs to pause/continue autoplay

**Comment by xiaotiandada** [comment]
> Swiper can't work correctly when it is not in DOM. Use Swiper APIs to pause/continue autoplay

I encountered a similar problem when using autoplay, according to the answer I used v-if to deal with it。

I hope it will be helpful to future students

```ts
const showSwiper = ref<boolean>(false)

watch(
  () => router name,
  (newValue) => {
    if (newValue === 'router name') {
      showSwiper.value = true
    } else {
      showSwiper.value = false
    }
  },
  { immediate: true }
)


<div v-if="showSwiper">...</div>
```
