### ISSUE TITLE
slidesPerView not working for creative effect

### ISSUE THREAD

**Issue by MaxLeven** [nolimits4web/swiper#6147]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slidesperview-creative-usb6jd

### Bug description

If set the slidesPerView more than 1 it is not working as expected for creative effect. I need to get two slides visible and the other transformed. But I always get active with only one slide and the other transformed. May be Swiper have no options to do it? I need some thing like this https://share.cleanshot.com/Kbgf6R.

### Swiper version

8.4.4

### Platform/Target and Browser Versions

macOS Chrome 106.0.5249.119

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is suppose to work only with 1 slidePerView

**Comment by spacedev75** [comment]
Could this be supported for many slides per view ?
