### ISSUE TITLE
Swiper autoplay sets index wrong after last slide

### ISSUE THREAD

**Issue by SergiuT** [nolimits4web/swiper#6148]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://1xus0k.csb.app/

### Bug description

I made a simple swiper carousel and set the loop to true

Whenever the carousel reaches the end it goes back to the first slide, but the active index is set to `index + 1` not to 1 as it was supposed to

You can check out this sandbox I've put

### Expected Behavior

After the slide reaches the end and it goes back to the first slide, it should set the slide index to 1

### Swiper version

8.4.4

### Platform/Target and Browser Versions

macOs Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
