### ISSUE TITLE
Using an undefined css variable in .scss

### ISSUE THREAD

**Issue by damdlani** [nolimits4web/swiper#6151]
Hi,
I am using Swiper.js in my project but due to its configuration and current settings I am not able to import styles directly to the React Component. Because of that, as a temporary workaround, I imported the styles as a path from `node_modules`, so I can adapt them to my needs. 
However during the deployment process an `Out of memory error` occurred and seemed to occur only when importing styles.

What I've found was that in `swiper.scss` there are 4 usages of undefined css variables without a fallback: `--swiper-centered-offset-before`, `--swiper-centered-offset-after`. It turned out that it was causing the out of memory error when connected with the known issue of linter not showing error when usage of undefined variable occurs. 

I know there may not be many of cases like mine but please define the variables and provide a fallback for that usages.

Best regards

**Comment by nolimits4web** [comment]
Using undefined variables is a totally valid case
