### ISSUE TITLE
Swipe transition animation is not working on IOS-Chrome

### ISSUE THREAD

**Issue by malidzhikov** [nolimits4web/swiper#6154]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#pagination-custom

### Bug description

Open the reproduction link with an Iphone and Chrome. Then try switching pages. Notice that the animation is not there. Compare it with Android device or Iphone with Safari it is working as expected. 

### Expected Behavior

A smooth transition between slides as in the example with browser.

### Actual Behavior

The transition animation is nonexistent.

### Swiper version

8.4.4, and older

### Platform/Target and Browser Versions

IOS 16.0 Iphone 12 / Chrome Version 106.0.5249.92

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by heekyu-pu** [comment]
I have same issue

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
