### ISSUE TITLE
On change swiper slide it dissapears.

### ISSUE THREAD

**Issue by DannyLemoo** [nolimits4web/swiper#6155]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://titanstudio.000webhostapp.com/MokeOS

### Bug description

On change swiper slide some content dissapears from it.

### Expected Behavior

To not dissapear because the content is important.

### Actual Behavior

While I change a slide on the swiper content from a slide dissapears and when I re-slide, it appears like nothing.

### Swiper version

8.4.4

### Platform/Target and Browser Versions

Windows Firefox 105.0.3

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The link you have provided doesn't illustrate the issue
