### ISSUE TITLE
Swiper height 0 for lazy images while devtools are open

### ISSUE THREAD

**Issue by lubaskinc0de** [nolimits4web/swiper#6161]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/gallant-joana-3pzsxt

### Bug description

Hello, I noticed that with open devtools, display: block on images, lazy load, swiper-wrapper is given a height of 0 when loading the page, respectively, the image is not visible, with display: inline, there is no such problem.

![Снимок экрана (493)](https://user-images.githubusercontent.com/100635212/197391590-379e8e62-c2ae-473e-bb55-07a4153c21a0.png)

https://user-images.githubusercontent.com/100635212/197393411-40410994-e597-4348-a8fe-3ae9a20501c7.mp4

### Expected Behavior

Normal image height

### Actual Behavior

0 image height

### Swiper version

8.4.4

### Platform/Target and Browser Versions

Windows 11 Opera

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is because of cache
