### ISSUE TITLE
Unable to autoplay videos on iOS as no user gesture is detected,.

### ISSUE THREAD

**Issue by jmattiace** [nolimits4web/swiper#6162]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-video-example-lf9ovm

### Bug description

I am using Swiper to give me "TikTok" like functionality for viewing videos: when the user swipes to the next slide, the video contained within that slide will autoplay. I am properly using the html5 video api to play/pause/mute videos, and when the user unmutes 1 video, all subsequent videos should be unmuted. This works on all browsers except for iOS, which will not allow my application to autoplay off of mute because of the error:

```
The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

This error means that the browser does not yet have the criteria it needs to be able to autoplay off of mute. One of the criteria that enables autoplay off of mute is a user gesture, meaning that if the user interacts with the webpage (by taking any action besides simply scrolling), then autoplaying off of mute is allowed.

I am reporting this here as an issue with Swiper because if I use any other implementation outside of Swiper I am able to properly autoplay subsequent videos off of mute. I'm wondering if anyone has any ideas why:
1. The browser might not be detecting swiping to the next slide as a user gesture
2. The browser might not be detecting unmuting a video in 1 slide as a user gesture to enable autoplaying across all slides 

Reproduction:
[Codesandbox of reproduced issue with Swiper](https://codesandbox.io/s/swiper-video-example-lf9ovm)
[Codesandbox of working example without Swiper](https://codesandbox.io/embed/swiper-video-display-none-ebmi7h?codemirror=1)

### Expected Behavior

When unmuting a video within one slide and then swiping to the next slide, a video in that next slide should autoplay off of mute on iOS based browsers.

### Actual Behavior

When unmuting a video within one slide and then swiping to the next slide, a video in that next slide will only autoplay on mute.

### Swiper version

8.4.2

### Platform/Target and Browser Versions

iOS Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The https://www.tiktok.com/ is made with Swiper actually (if you check it from your mobile), so not the Swiper issue

**Comment by jmattiace** [comment]
The issue is that Swiper's `slideChanged` event essentially listens for a `touchend` event, after a `touchmove`, which is the gesture registered when swiping. But this is not registered as a user gesture allowing autoplay on iOS.

User gestures that _should_ allow autoplay are defined in the [spec][1]. Through my testing, I have identified that the only user gestures that allow autoplaying include `click`, `pointerup`, and `mouseup`. `touchend` also works when fired after a `click`, but not after a `touchmove`.

It's also important to understand how to handle user gestures properly as [defined by the Safari team][2]:

> A note about the user gesture requirement: when we say that an action must have happened “as a result of a user gesture”, we mean that the JavaScript which resulted in the call to video.play(), for example, must have directly resulted from a handler for a touchend, click, doubleclick, or keydown event. So, button.addEventListener('click', () => { video.play(); }) would satisfy the user gesture requirement. video.addEventListener('canplaythrough', () => { video.play(); }) would not.


  [1]: https://html.spec.whatwg.org/multipage/interaction.html#user-activation-processing-model
  [2]: https://webkit.org/blog/6784/new-video-policies-for-ios/
