### ISSUE TITLE
Reinitialise swiper instance with new settings on window.resize

### ISSUE THREAD

**Issue by owzzz** [nolimits4web/Swiper#617]
I'm looking to change my responsive horizontal swiper carousel at different media queries.

* on Mobile the swiper has 1 slidesPerView.
* on Tablet the swiper has 3 slidesPerView.
* on Desktop the swiper has 5 slidesPerView.

Is this something that can be achieved with the current codebase?

I was hoping on window resize I could matchmedia the current width with a media query and then reinitialise the swiper with the correct slidesPerView at that break point.

Is this possible currently?

**Comment by asim-coder** [comment]
Hi,

I am getting the error "Error: mySwiper.reInit is not a function". I can change the params successfully though. (I couldn't find the function in docs too. Is there a replacement for the reInit?)

**Comment by nolimits4web** [comment]
> I am getting the error "Error: mySwiper.reInit is not a function". I can change the params successfully though. (I couldn't find the function in docs too. Is there a replacement for the reInit?)

It is now `mySwiper.update()`

**Comment by truemed** [comment]
Swiper has the option `breakpoints` as a parameter.  Take a look at [the example in the docs of how to specify breakpoints](http://idangero.us/swiper/api/#parameters).  It really is the best slider.

**Comment by kotkaaa** [comment]
If you need to change the swiper orientation (eg: from "horizontal" to "vertical"), you must force change the swiper-container's orientation subclass on specified breakpoint (it must be also specified in swiper's params) and then call update function. Example:

```
var Slider = new Swiper(".my-slider",{
    slidesPerView: 5,
    direction: 'vertical',
    breakpoints: {
        960: {
            direction: 'horizontal'
        }
    }
});
$(window).on("resize orientationchange", function(){
    var ww = document.documentElement.clientWidth
        $el = $(Slider.$el);
    if (ww > 960) $el.removeClass("swiper-container-horizontal").addClass("swiper-container-vertical");
    else $el.removeClass("swiper-container-vertical").addClass("swiper-container-horizontal");
    Slider.update();
});
```
