### ISSUE TITLE
First duplicate slide doesn't display initially when using cssMode & loop together

### ISSUE THREAD

**Issue by danbohea** [nolimits4web/swiper#6182]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-centered-vue-forked-0f46ij?file=/src/App.vue

### Bug description

When setting both `cssMode` and `loop` to `true` the the duplicate slide to the left of slide 0 does not display initially. As soon as you interact with the carousel, it appears. Setting `cssMode` back to `false` everything appears to behave as expected.

### Expected Behavior

Duplicate slide to the left of slide 0 appears straight away.

### Actual Behavior

Duplicate slide to the left of slide 0 doesn't appear until you interact with the carousel.

### Swiper version

8.4.4

### Platform/Target and Browser Versions

Linux/Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
