### ISSUE TITLE
Swiper lags when changes slides (only iOS Chrome)

### ISSUE THREAD

**Issue by sofly** [nolimits4web/swiper#6185]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos

### Bug description

There is a lag when the swiper animates slides by swiping, clicking on pagination, clicking on the prev, next buttons, or use swiper API.

https://user-images.githubusercontent.com/9013581/199789757-4a32c812-fd93-4734-bfef-994321276789.mp4

### Expected Behavior

Swiper must animate slides smoothly

### Swiper version

8.4.4

### Platform/Target and Browser Versions

iOS 16.1,  Chrome 107.0.5304.66 (stable)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is a Chome's issue

**Comment by z4o4z** [comment]
@nolimits4web do you have more info, could you point out the issue in the chrome bugtracker system?

**Comment by paveltyk** [comment]
According to global stats, Chrome is the most-used browser: 65% in October 2022. Optimizing the library to perform well on Chrome is probably a top priority when you claim your library to be a **_modern mobile touch slider with hardware accelerated transitions and amazing native behavior_** (quote from the library description).

:)
