### ISSUE TITLE
Allow custom transition in call of slideTo

### ISSUE THREAD

**Issue by 13hannes11** [nolimits4web/swiper#6195]
### Clear and concise description of the problem

I would like to be able to trigger a different kind of transition when calling slideTo then the one defined in the constructor.

### Suggested solution

I'd suggest adding some method that allows calling slideTo with a custom effect and direction something along the lines of:
```Javascript
swiper.slideToCustom(index, effect, direction, speed, runCalbacks)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is unfortunately impossible to do on slide basis
