### ISSUE TITLE
Add an ability to use JSX syntax when customizing/configuring slider Pagination for React version of Swiper

### ISSUE THREAD

**Issue by JJoestar2** [nolimits4web/swiper#6210]
### Clear and concise description of the problem

As a developer that using Swiper with React JS I want to be able use JSX syntax to customize /configure pagination more efficient and easier.

### Suggested solution

Create an another module/component based on exisiting Pagination module and expand his functionality so devs can be able to customize/configure pagination items with jsx. Or expand existing Pagination module to be able use jsx for pagination items. 

Also will be great if we could retrieve additional props such as status of the bullet active, prev,  next. Also retrieve the default click handler function that is used if user indicates clickable:true, can be usefull.

Example of desired pagination configuration for more clearness: 

....some code here
const pagination = {
  "clickable": true,
  "dynamicBullets": true,
  "renderBullet": (index, className, isActive, onClickHandler) => (
<button onClick={isActive ? myFunc : onClickHandler}>
    <span className={className}> {index} </span>
</button>
),
}
.... swiper slider

### Additional context

For now we can customize pagination items (bullets)
like this: 

const pagination = {
  "clickable": true,
  "renderBullet": function (index, className) {
    return '<span class=\"' + className + '\">' + (index + 1) + '</span>';
  }
}

<Swiper
pagination={pagination}
modules={[Pagination]}
className="mySwiper"
>
{...slides}
</Swiper>

But we can't write like this:

const pagination = {
  "clickable": true,
  "renderBullet": (index, className) => (
    <span className={className}> {index} </span>
),
}

In this case, inside of the html markup [object Object] will be rendered instead of customized bullet markup. Also we can't to attach own click handler for active bullet in this case to.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
