### ISSUE TITLE
Safari 13.1 Only show first slide 

### ISSUE THREAD

**Issue by emmalevesque** [nolimits4web/swiper#6211]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://ejg-els.vercel.app/editorial/cjr

### Bug description

Website App running:
Swiper @ 8.4.4
Next.js @ 13.0.3

Browser:
Safari @ 13.1

I have a swiper instance that is experiencing a bug in Safari 13. I've been unable to reproduce it in any other browser and seems to work across all devices running the latest software.

Upon loading a page of my app with a Swiper gallery, the first slide loads perfectly but none of the other slides in the tree load. 

Inspecting the console I don't notice any errors, the image requests were all successful, correctly sized, and no css is preventing the slides from displaying in the browser.

I also have a gallery index page and when viewing the index you can click a thumbnail and it will move the slider to the corresponding Swiper slide. When I click a thumbnail the slide is visible for a fraction of a second before disappearing.

I'm not sure if this is a Swiper bug or a Safari bug but I'm wondering if anyone has experienced something similar and has any idea how to work around this older version of Safari.

Below is my Swiper Component Instance

```jsx
<Swiper
					rewind
					initialSlide={initialSlide}
					onSwiper={setSwiper}
					onSlideChange={handleSlideChange}
					slidesPerView={1}
					speed={1}
					modules={[Keyboard, Navigation, Lazy]}
					keyboard
					// updateOnImagesReady
					preloadImages
					allowTouchMove={false}
					grabCursor={false}
					allowSlidePrev={
						photos?.find((photo) => photo?.panoramicSlides?.length > 0)
							? swiper?.activeIndex != 0
							: swiper?.activeIndex != 0
					}
				>
                                                         <SwiperSlide key={index}>
								{({ isActive, isNext }) => (
									<Photo
										key={String(index)}
										target={index}
										index={`photo-${index}`}
										photo={photo}
										priority={
											isActive ||
											isNext ||
											Math.abs(swiper?.activeIndex - index) < 4
										}
									/>
								)}
							</SwiperSlide>
                                              </Swiper>
```

Ty for any insight you can provide!

### Swiper version

Swiper @ 8.4.4

### Platform/Target and Browser Versions

macOs Safari 13.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by aman1792** [comment]
+1

**Comment by levonsargsyan1990** [comment]
+1

**Comment by BeginnerDone** [comment]
+1

**Comment by mmodler** [comment]
+1

**Comment by bbambery** [comment]
+1

**Comment by bbambery** [comment]
Found a fix, for safari. Seems its firing before domcontentloaded....
  function runOnStart() {
    new Swiper(".swiper", {
      loop: true,
      slidesPerView: 1,
      spaceBetween: 0,
      autoplay: {
        delay: 5000,
      },
    });
  }
  if (document.readyState !== "loading") {
    runOnStart();
  } else {
    document.addEventListener("DOMContentLoaded", function () {
      runOnStart();
    });
  }

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
