### ISSUE TITLE
 slidesPerView: 'auto', variableWidth: true, 

### ISSUE THREAD

**Issue by lea-x** [nolimits4web/swiper#6215]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.jadedeshayes.com/

### Bug description

Hi, i'm new to Github so sorry if the problem has already been asked (I digged but haven't found a proper solution). I have a swiper with  slidesPerView: 'auto', variableWidth: true, that stops at one point when sliding. I did add freemode: true, but somehow the swiper filled its end with infinite blank. I don't know what I'm doing wrong. Is there a solution? Thank you very much for your wonderful work @nolimits4web 

```

  var mySwiper = new Swiper(".swiper-container", {
    keyboard: true,
    loopFillGroupWithBlank: false,
    slidesPerView: 'auto',
     /*freeMode: true,*/
     releaseOnEdges: true,
     observer: true, 
     initialSlide: 0,
  observeParents: true,
     variableWidth: true,
      simulateTouch: true,
      watchSlidesProgress: true,
     direction: "horizontal",
     watchSlidesProgress: true,
     slidesOffsetAfter: 0,
    //roundLengths: true,
    mousewheel: true,
    speed: 600,
    mousewheel: {
    sensitivity: 1,
    releaseOnEdges: true,
    },
```

### Swiper version

8

### Platform/Target and Browser Versions

macOS, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is no such `variableWidth` parameter. You need to update Swiper when images are loaded:
```js
document.querySelector('.swiper').addEventListener('load', () => {
  const swiper = document.querySelector('.swiper');
  swiper.update();
}, {capture: true});
```

**Comment by lea-x** [comment]
My console is saying that the swiper.update isn't a function. (_Uncaught TypeError: swiper.update is not a function at document.querySelector.addEventListener.capture_)
`

  ```
var mySwiper = new Swiper(".swiper-container", {
    keyboard: true,
    loopFillGroupWithBlank: false,
    slidesPerView: 'auto',
     freeMode: true,
     releaseOnEdges: true,
     observer: true, 
     initialSlide: 0,
  observeParents: true,
      simulateTouch: true,
      watchSlidesProgress: true,
     direction: "horizontal",
     watchSlidesProgress: true,
     slidesOffsetAfter: 0,
    mousewheel: true,
    mousewheel: {
    sensitivity: 1,
    releaseOnEdges: true,
    },

    on: {
      slideChangeTransitionStart: function () {
          var swiper = this;

          var slideTitle = $(swiper.slides[swiper.activeIndex]).attr("data-title");
          var slideSubtitle = $(swiper.slides[swiper.activeIndex]).attr("data-subtitle");
          var slideNum = $(swiper.slides[swiper.activeIndex]).attr("data-num");
          var slideIndex = $(swiper.slides[swiper.activeIndex]).attr("data-index");
          $(".slide-captions").html(function() {
            return slideTitle ;
          });
          $(".slide-captions__indexnum").html(function() {
            return slideNum + "/" + slideIndex ;
          });



          },
  
        }



    });

document.querySelector('.swiper').addEventListener('load', () => {
  const swiper = document.querySelector('.swiper');
  swiper.update();
}, {capture: true});

  
 })
````

**Comment by lea-x** [comment]
It seems that the lazyLoading option blocks the swiper to calculate the slides progress and their offsets... (like in this issue, #3405).
