### ISSUE TITLE
Swiper don't work with Controlled module

### ISSUE THREAD

**Issue by Niemir** [nolimits4web/swiper#6216]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/late-butterfly-ir90dt?file=/src/App.js

### Bug description

When trying to create [Controlled](https://swiperjs.com/react#controller) swiper component, with following swiper react docs it shows the error message:
`Cannot read properties of undefined (reading 'length')`

I was trying that with Vite 3.2.3 and react 18.2.0, also tried with latest Next.js 13 - on both had the same problem. 

On link to Codesandbox i replicated it with example from swiper docs. 
Error is also appearing when i tried to create two-way control Swiper.
I was trying replace null with empty useState but didn't recived expected result.
`const [controlledSwiper, setControlledSwiper] = useState();`

What is weird it worked good with Solid.js

### Expected Behavior

At least two working Swipers where one can controll another.

### Swiper version

8.4.4

### Platform/Target and Browser Versions

Windows 11, Chrome 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by onezeno717** [comment]
hope this help, this your code :
`const [controlledSwiper, setControlledSwiper] = useState(null);`
change to this :
`const [controlledSwiper, setControlledSwiper] = useState({});`

I dont know why but I have same problem, and thats work.

**Comment by Niemir** [comment]
Yes actually it helped, it's weird, so probably it should be changed in docs. I tried to downgrade react to v17 and it worked good with null as initial value, so it's probably related to some new changes which came up with new react.
