### ISSUE TITLE
A error occurred when using controller in swiper in React 18

### ISSUE THREAD

**Issue by ddhp** [nolimits4web/swiper#6222]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/hungry-margulis-7lpem8

### Bug description

following the doc [here](https://swiperjs.com/react#controller) to setup controller but got an `Cannot read properties of undefined (reading '2')` error

the error is from [here](https://github.com/nolimits4web/swiper/blob/master/src/modules/controller/controller.js#L61), parameter `c` is undefined

It's working with React 17

### Swiper version

8.4.4

### Platform/Target and Browser Versions

OSX 12.5, Chrome 107

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by ddhp** [comment]
`<Swiper>` would mount twice(unmount and mount again), and maybe there is a race condition that the first unmount makes second mount destroyed?

**Comment by ddhp** [comment]
managed to get it work and here is the reference
https://codesandbox.io/s/modern-hill-ec9pcu
need to make sure swiperInstance exists and it's not destroyed

**Comment by TomSmedley** [comment]
I'm unsure if this should be closed, while you have found a workaround, this is definitely an issue.
