### ISSUE TITLE
JS error "swiper.a11y is undefined" when destroying swiper after click in slide

### ISSUE THREAD

**Issue by dpxgit** [nolimits4web/swiper#6223]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no reproduction link

### Bug description

I hope this description will show the problem I'm having difficulties to create a codesandbox.

In my vue project including the swiper (core, not vue) I have the problem getting an error message since v8.4.3 when clicking on a linked element in a slide:
`Uncaught TypeError: swiper.a11y is undefined in a11y.js:195`

I have to use the method `beforeDestroy()` to call `swiper.destroy(deleteInstance, cleanStyles)` with cleanStyles=`false`. But if the swiper is destroyed, `swiper.a11y.clicked` can't be set to `false`, because it is undefined after destruction.

As a workaround I am setting `swiper.a11y = {}` after calling `swiper.destroy(deleteInstance, cleanStyles)`.

I suggest adding a check if swiper.destroyed is not true in src/modules/a11y/a11y.js:

  ```
  const handlePointerUp = () => {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        if (!swiper.destroyed)
        swiper.a11y.clicked = false;
      });
    });
  };
  ```

### Expected Behavior

No javascript error when swiper is destroyed after clicking a link within a slide.

### Actual Behavior

Receiving error message in console after clicking a link within a slide and destroying the swiper:
`Uncaught TypeError: swiper.a11y is undefined in a11y.js:195`

### Swiper version

8.4.3

### Platform/Target and Browser Versions

Windows Chrome 107

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by ScorpAL** [comment]
Same happened for react version

React 18
Swiper 8.4.4
Chrome Version 107

Receiving error message in console after clicking a link within a slide and destroying the swiper:
```
Uncaught TypeError: Cannot set properties of undefined (setting 'clicked')
at a11y.js:195:21
```
