### ISSUE TITLE
Swiper examples for Qwik

### ISSUE THREAD

**Issue by Nefcanto** [nolimits4web/swiper#6232]
### Clear and concise description of the problem

We use Swiper React inside Next.js projects and it's perfect. The examples are amazing and the docs are very good.

Now we want to migrate to Qwik. We tried Swiper React and it didn't work. We tried the Vanilla version of the Swiper and it still does not work.

It's amazing if we can have examples on how to use it inside Qwik projects.

### Suggested solution

I think there are two possible solutions.

1- Creating a library for Qwik
2- Using vanilla js version

In both cases, having examples in the docs is very useful.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by Mohmmad-Miras** [comment]
Hello, I was able to use swiper in qwik this is the example that I prepared, I hope it can help you
https://github.com/Mohmmad-Miras/Swiper-Qwik.git

**Comment by Nefcanto** [comment]
@Mohmmad-Miras thank you so much for that example. We solved the issue [here](https://stackoverflow.com/questions/74519742/how-can-i-use-swiperjs-inside-qwik). But we still think that a formal example on the Swiper website is necessary.

**Comment by nolimits4web** [comment]
There won't be Swiper version for Quick, use JS version or Swiper Web Components
