### ISSUE TITLE
Swiper TS definitions not well supported inside <Swiper> component.

### ISSUE THREAD

**Issue by RikiVallen** [nolimits4web/swiper#6233]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/szcoqb?file=/src/App.vue

### Bug description

Please don't remove, I understand this is technically a duplicate issue but I come offering a solution.

Almost every property you could add to the <Swiper> tag inside <Template> would throw warnings that the incorrect type was being used. The code sandbox provided is infact the official Vue navigation demo, which you can see has errors appearing when defining :modules and :navigation. 

This issue is more widespread than that however. Perusing the issues for this project I came across the following which are all running into variations of this issue.

#6136
#6122
#5548
#5265

I have a working patch file I have been using, but I would rather have this implemented inside the official repo so I can do away with it. (Plus give back to such an awesome library).

### Expected Behavior

There should be no warnings when adding any property supported by Swiper as indicated within its documentation. It should also be utilising the power of TS to auto-suggest values based on the property being used.

### Actual Behavior

Warnings and no typed auto-suggestions on most <Swiper> props.

### Swiper version

<= 8.4.5

### Platform/Target and Browser Versions

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by RikiVallen** [comment]
Looks like types have been fixed as of 9.0

**Comment by TLovers** [comment]
it doesn't seem to have been repaired
