### ISSUE TITLE
There are so many [Vue warn] when I use swiper in Nuxt3 framework

### ISSUE THREAD

**Issue by rondout** [nolimits4web/swiper#6234]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://www.vantrontech.us

### Bug description

I use the Nuxt3 SSR framework to develop a website, and I used the swiper component(version:8.4.5), but when i deployment my website by PM2, there's a lot [Vue warn] when check pm2 logs, such as :
```bash
[Vue warn]: onBeforeUpdate is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
[Vue warn]: onUpdated is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
```
I confirm that these warning are all caused by swiper component, so is that a bug or what should i do to avoid these warnings?

### Expected Behavior

there should not be these warnings

### Actual Behavior

there are lots of warnings

### Swiper version

8.4.5

### Platform/Target and Browser Versions

server:Ubuntu@22.04

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
