### ISSUE TITLE
autoplay.stop() method working strange

### ISSUE THREAD

**Issue by GulomovCreative** [nolimits4web/swiper#6237]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/agitated-dream-e37pmx?file=/index.html

### Bug description

Let's imagine a case, we need a slider with autoplay, that pauses on hover, but if the user clicks navigation button autoplay is turns off.

```javascript
const swiper = new Swiper(".mySwiper", {
  loop: true,
  navigation: {
    nextEl: ".swiper-button-next",
    prevEl: ".swiper-button-prev"
  },
  autoplay: {
    delay: 1000,
    pauseOnMouseEnter: true,
    disableOnInteraction: false
  },
  on: {
    navigationNext: swiper => swiper.autoplay.stop(),
    navigationPrev: swiper => swiper.autoplay.stop()
  }
});
```

And it seems logical, but in practice it isn't obvious. If you run this code, the slider will work as it should. Every second slide changes. After hovering it pauses. But if you click navigation button the most interesting thing begins, formally autoplay will stop, but every time if you hover the slider, slide will change.

_Sorry for my bad English_

### Expected Behavior

I think, swiper autoplay needs disable, enable and/or destroy methods. Or maybe divide autoplay.disableOnInteraction into autoplay.disableOnHover and autoplay.disableOnIteraction.

### Swiper version

8.4.5

### Platform/Target and Browser Versions

Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
