### ISSUE TITLE
slidesPerColumn not working as expected

### ISSUE THREAD

**Issue by blerim-r** [nolimits4web/swiper#6238]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/badblakesmith/pen/aPXNxv

### Bug description

I have this local configuration but I could reproduce it even in the default examples of the library documentation

`
            let slidePerView, slidesPerColumn, columnCount;

            // The $columnCount is a PHP variable; 

            columnCount = <?= $columnCount ?>;

            if(window.innerWidth <= 420) {
                slidePerView = 2;
                slidesPerColumn = 4;
            } else if(window.innerWidth <= 768) {
                slidePerView = 2;
                slidesPerColumn = 4;
            } else if (window.innerWidth < 1200) {
                slidePerView = 3;
                slidesPerColumn = 2;
            } else if (window.innerWidth < 2560) {
                slidePerView = columnCount <= 7 ? 3 : 4;
                slidesPerColumn = 2;
            } else {
                slidePerView = 4;
                slidesPerColumn = 2;
            }

            var swiper = new Swiper(".mySwiper-4--<?= $elementId ?>", {
                slidesPerView: slidePerView,
                slidesPerColumn: slidesPerColumn,
                spaceBetween: 20,
                slidesPerColumnFill: 'row',
                pagination: {
                    el: ".swiper-pagination",
                    clickable: true,
                },
                navigation: {
                    nextEl: ".swiper-button-next--<?= $elementId ?>",
                    prevEl: ".swiper-button-prev--<?= $elementId ?>",
                },
                preloadImages: false,
                lazy: true,
            });`

On the desktop is working pretty well, the problem is on mobile;

I have 10 images and on mobile, (slidePerView = 2 and slidesPerColumn = 4) the result is this:
<img width="383" alt="Screenshot 2022-11-24 at 4 13 45 PM" src="https://user-images.githubusercontent.com/51121238/203817359-dc0c7a7f-7131-40d9-bce0-0dc8dae3d3ec.png">

There are shown only 7 images instead of 8 because I have 10 images available.

Note that this issue is present in the official codepen of the library

<img width="384" alt="image" src="https://user-images.githubusercontent.com/51121238/203834371-6e1ccef9-9ebb-438d-a215-c1f19f0196f3.png">

### Expected Behavior

I have 10 images in total and on mobile I see only 7.
Must be shown 8 images instead.

### Actual Behavior

The last image at the bottom is missing.
<img width="383" alt="Screenshot 2022-11-24 at 4 13 45 PM" src="https://user-images.githubusercontent.com/51121238/203818033-4885e660-85a6-4f98-94a9-43995ae04572.png">

### Swiper version

 6.8.1

### Platform/Target and Browser Versions

Version 107.0.5304.110 (Official Build) (x86_64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Latest Swiper version is 8.x
