### ISSUE TITLE
"Cannot convert undefined or null to object" error when testing Swiper with Jest

### ISSUE THREAD

**Issue by hoi4** [nolimits4web/swiper#6239]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/hoi4/swiper-jest-issue

### Bug description

I am using the latest version of `swiper/angular` (8.4.5) and ran into the following issue when testing a component that includes a swiper with jest. 

```
Cannot convert undefined or null to object
```

The cause of the issue is that `Swiper.defaults` ([code](https://github.com/nolimits4web/swiper/blob/7b48b016d82d958d128800dc6dcd3f65e55ef90d/src/angular/src/utils/get-params.ts#L13)) and `Swiper.extendedDefaults` ([code](https://github.com/nolimits4web/swiper/blob/7b48b016d82d958d128800dc6dcd3f65e55ef90d/src/angular/src/utils/get-params.ts#L14)) are `undefined`. 

This issue is exactly the issue reported in [#5630](https://github.com/nolimits4web/swiper/issues/5630#issuecomment-1318411121), but as it is a very different context (and it is closed), I though it made sense to create a new issue.

As ESM support for jest is still experimental, I have configured Jest to properly transform swiper by using jest's `transformIgnorePatterns` and `modulePaths` config options (see repo). 

When using swiper@7 (version 7.4.1), my test works (with an additional configuration of `moduleNameMapper` for `swiper_angular` in `jest.config.ts`)

### Expected Behavior

I would expect swiper to work with jest

### Actual Behavior

Swiper does not work with jest

### Swiper version

8.4.5

### Platform/Target and Browser Versions

Jest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
