### ISSUE TITLE
Inconsistent behavior across browsers

### ISSUE THREAD

**Issue by nodoze** [nolimits4web/Swiper#624]
Hi,

I've been scouring the web but could not find any resolution to my
problem. 

We love the swiper and are using it in a variety of ways. In some case we're embedding one or more instance of jwplayer on indiviudal slides but on certain browser in particular on the mac, the video player does not properly initialize/show when we embed it in the
swiper. The behavior varies from browser to browser and depending on whether a player is initially visible or hidden.

This link demonstrates the problem:
http://prod.cellmobs.com/player/testjw.html

It has 3 slides with one player each.
1 ­ a youtube video
2 ­ an mp4 video
3 ­ a youtube video

I wonder if you could point us to a solution to this problem. We've contacted jwplayer support as well but they didn't have any quick solution to this problem. 

Here¹s the basic behavior breakdown:

Windows 7/8
FF: works overall
IE: works, although IE seems to fallback to html for Youtube videos and
ignore the image in that case.
Safari/Chrome: works for non-Youtube video when the player is initially
visible, the player is black and cannot be clicked when it is initially
hidden for both YouTube and mp4s.

MAC OSX
FF: only works when the player is initially visible. Black for all
subsequent swipes/slides even though the player's onReady event fires
correctly.
Safari/Chrome: works only for non-Youtube videos. Youtube videos show the
player and the custom image but the player ui is not clickable.

It would be great if you could take a quick look at the above referenced
link to see if you might have some pointers for us for how to address the problem.

Thanks in advance.

**Comment by fetis** [comment]
Maybe it's not actual anymore, but I had similar problem with JWPlayer. Setting `simulateTouch: false` helps me figure out the problem. It looks like slider catch the mouse events and doesn't propagate them on level where player can handle it.
