### ISSUE TITLE
Transition fade breaks lazy loading. 

### ISSUE THREAD

**Issue by sanderkooger** [nolimits4web/swiper#6242]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-fade-react-forked-gl6shs?file=/src/App.jsx

### Bug description

On out website the moment i enable lazy and transition fate together, lazy loading breaks. 

I have troubleshooted by removing the transition and with the slide animation, lazy loading does work correctly. 
https://thisisfashion.tv/collections/shiatzy-chen/2022/ss-23/looks/01

### Expected Behavior

Epecting lazy loading to not break

### Actual Behavior

Lazy loading breaks

### Swiper version

latest

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 doesn't lazy module anymore. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
