### ISSUE TITLE
Some events are not working after init swiper

### ISSUE THREAD

**Issue by Kcko** [nolimits4web/swiper#6244]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/Kcko/4z5xqdj7/

### Bug description

1) This always works 

```
var swiper = new Swiper('.swiper-container',
 {
  on: {
  	afterInit: function(swiper) {
    console.log('afterInit', swiper)
	  }
  }
}
);
```
```
var swiper = new Swiper('.swiper-container');

swiper.on('afterInit', function(swiper) {
 console.log('init', swiper)
});
```

### Expected Behavior

Should be work both ways. 

It doesnt work because im using old version? (6.8.4).

I read info about events https://swiperjs.com/swiper-api#events but i dont understand if it means that some events must be in object with first initialization and some can be binded after.

Thx for clarification.

PS. Out of the question, is there any way how check if swiper can be moved? I have own implementation of arrows (prev/next), and i dont know rule how check  that arrows can be visible or not (I have different numbers of slides for a few breakpoints and it means that in large BP,  slider may not have pagination / arrows but on mobile yes, how to detect it?)

### Swiper version

6.8.4

### Platform/Target and Browser Versions

Windows 10, Google chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> Should be work both ways.

No, it shouldn't

**Comment by Kcko** [comment]
> And I don't want to look rude, but your answer does not clarify anything on this point.
I totally agree.
