### ISSUE TITLE
When user drags mouse vertically on a horizontal swiper on PC, the animation stops in the middle.

### ISSUE THREAD

**Issue by jhcarl0814** [nolimits4web/swiper#6253]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-forked-tli8jv

### Bug description

When user drags mouse vertically on a horizontal swiper **on PC**, the animation stops in the middle.
https://github.com/nolimits4web/swiper/issues/1288
https://github.com/nolimits4web/swiper/issues/1425
https://github.com/nolimits4web/swiper/issues/2104
![swiper bug 20221204 when user drags mouse vertically on a horizontal swiper on PC, the animation stops in the middle](https://user-images.githubusercontent.com/5171262/205473109-a9b5351f-4a75-44ce-afa9-ce6a3574fffc.gif)

the fix:
node_modules\swiper\core\events\onTouchMove.js:
1. disable scroll in touch-move event **on PC** (we scroll by scrolling mouse's wheel, not by touching and moving vertically **on PC**) (1024 breakpoint is chosen for the website I'm currently working on specifically)
change from:
```js
  if (typeof data.isScrolling === 'undefined') {
    let touchAngle;

    if (swiper.isHorizontal() && touches.currentY === touches.startY || swiper.isVertical() && touches.currentX === touches.startX) {
      data.isScrolling = false;
    } else {
      // eslint-disable-next-line
      if (diffX * diffX + diffY * diffY >= 25) {
        touchAngle = Math.atan2(Math.abs(diffY), Math.abs(diffX)) * 180 / Math.PI;
        data.isScrolling = swiper.isHorizontal() ? touchAngle > params.touchAngle : 90 - touchAngle > params.touchAngle;
      }
    }
  }
```
to:
```js
  if (typeof data.isScrolling === 'undefined') {
    let touchAngle;

    if(window.innerWidth<1024)
    {
      if (swiper.isHorizontal() && touches.currentY === touches.startY || swiper.isVertical() && touches.currentX === touches.startX) {
        data.isScrolling = false;
      } else {
        // eslint-disable-next-line
        if (diffX * diffX + diffY * diffY >= 25) {
          touchAngle = Math.atan2(Math.abs(diffY), Math.abs(diffX)) * 180 / Math.PI;
          data.isScrolling = swiper.isHorizontal() ? touchAngle > params.touchAngle : 90 - touchAngle > params.touchAngle;
        }
      }
    }
    else
    {
      data.isScrolling=false;
    }
  }
```

2. make `diff == 0` impossible (`diff` affects many things (I don't know what those are), but the code that follows only deals with `diff > 0` and `diff < 0` missing `diff == 0`.
change from:
```js
  let diff = swiper.isHorizontal() ? diffX : diffY;
  touches.diff = diff;
```
to:
```js
  let diff = swiper.isHorizontal() ? diffX : diffY;
  if(Math.abs(diff)<1)diff=1;
  touches.diff = diff;
```

### Swiper version

8.4.5

### Platform/Target and Browser Versions

Chrome Version 108.0.5359.73 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
seems to be fixed in v9
