### ISSUE TITLE
Any plausible solution for Lazy Loading?

### ISSUE THREAD

**Issue by re2005** [nolimits4web/Swiper#626]
I'm searching for this solution for a while, but didn't figure out how to implement a smart simple lazy loading using the brilliant Swiper library.

The simple request is whenever the IMG is inside the view port we switch the data-src and inject as src="img.xxx"

Once for all visible slides you're already adding the class "swiper-slide-visible" wouldn't be easy also set the data-src as a src and make it perfect?

Any other solution direction will be very appreciated!

Once again many thanks for share the Swiper!

**Comment by MobileMon** [comment]
So whats the real solution for lazy loading? I went to present it like 200 image url and have it lazy load each one on swipe (left right center scheme)

**Comment by ShaheedLegion** [comment]
I'm having the same issue, has this been resolved yet?
