### ISSUE TITLE
Huge number of virtual slides

### ISSUE THREAD

**Issue by Skygraphy** [nolimits4web/swiper#6262]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/ancient-butterfly-be1h1o?file=/index.html:291-424

### Bug description

I have to create about 50000 slides using the virtual module. It works perfectly with version 4.3.5 but not with version 8.

### Expected Behavior

Smooth transitions

### Actual Behavior

Jerky transitions

### Swiper version

8

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
improved in v9
