### ISSUE TITLE
Navigation Arrow flickering

### ISSUE THREAD

**Issue by derWebdesigner** [nolimits4web/swiper#6266]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/github/chltjdgus/next-swiper-error/main?file=%2FREADME.md

### Bug description

When you pull the first slide just a tiny bit to the right, the effect is visible quite well. The left navigation arrow shortly gets the enabled state and therefore is flickering. I think this is a bug especially because it draws the attention of the user to this arrow although there is nothing to the left.

### Expected Behavior

Change the state when slide 2 is active. When I pull the slide a bit to the side, it still doesn't make sense to enable the navigation arrow because there is still nothing to the left. There is only a left option when slide 2 is active.

### Actual Behavior

Navigation arrow gets enabled based on the position of the current slide instead of the active slide. The current behavior would be perfect for lazy loading to immediately load slide 2, but for the navigation arrow I don't think it makes sense.

### Swiper version

8.4.5

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by derWebdesigner** [comment]
Hint for others experiencing this issue as well: Adding a `transition: opacity .6s ease-in-out;` to `.swiper-button-next, .swiper-button-prev` will reduce this issue by a lot because the opacity needs some time to change.

**Comment by mightyplow** [comment]
I experience the same when using the swiper in CSS-Mode. When clicking the next-button, the swiper gets the end flag set immediately. While the swiper  then scrolls to the last slide, the flag is reset and at the end then set again. This leads to the flickering. My workaround also is to work with some opacity and a transition to hide the flickering.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
