### ISSUE TITLE
Unique 'key' prop warning when rendering SwiperSlide next to the result of mapping over array items and displaying with SwiperSlide. 

### ISSUE THREAD

**Issue by ogaguinaga** [nolimits4web/swiper#6269]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-infinite-loop-with-slides-per-group-react-forked-scyy78?file=/src/App.jsx

### Bug description

When rendering a `SwiperSlide` next to the result of mapping over array items and displaying them with `SwiperSlide` the following React warning is thrown, despite all components inside `Swiper` having a 'key' prop.

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Swiper`. 
```

### Expected Behavior

Not get a React key prop warning when the 'key' prop is passed to the `SwiperSlide` component.

### Actual Behavior

Getting a React key prop warning when the 'key' prop is passed to the `SwiperSlide` component.

### Swiper version

^8.0.0

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by saostad** [comment]
Your code had an extra line that caused the problem.
here is a fixed version:
```js
import React from "react";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

import "./styles.css";

// import required modules
import { Pagination, Navigation } from "swiper";
const slides = [
  "Slide 1",
  "Slide 2",
  "Slide 3",
  "Slide 4",
  "Slide 5",
  "Slide 6",
  "Slide 7",
  "Slide 8",
  "Slide 9",
];

export default function App() {
  return (
    <>
      <Swiper
        slidesPerView={3}
        spaceBetween={30}
        slidesPerGroup={3}
        loop={true}
        loopFillGroupWithBlank={true}
        pagination={{
          clickable: true,
        }}
        navigation={true}
        modules={[Pagination, Navigation]}
        className="mySwiper"
      >
        {slides.map((slide) => {
          return <SwiperSlide key={slide}>{slide}</SwiperSlide>;
        })}
      </Swiper>
    </>
  );
}

```

**Comment by ogaguinaga** [comment]
I understand, but that's the issue I'm reporting. I would like to add that line. I have a specific case where I need to loop over an array to display it's properties inside the Slider but also have a component that should be a part of the slider but does not come from the original array.

**Comment by saostad** [comment]
Then use a key value you are sure does not exist in your array.

**Comment by ogaguinaga** [comment]
It does have a unique key that does not exist in my array and the problem persists.

**Comment by saostad** [comment]
Maybe this is not the solution you are looking for, but how about adding the extra slide in the array instead of adding it in the jsx?

**Comment by ogaguinaga** [comment]
For this example that would work but in my real world case the objects inside of the array are very different and displayed using a component that would not fit the extra item. It also just feels like something that should work.

**Comment by abe1272001** [comment]
Facing the same issue too, I assume that is the "loopFillGroupWithBlank" cause this issue. You can try to remove it, error will gone.

**Comment by nolimits4web** [comment]
seems to be fixed in v9
