### ISSUE TITLE
swiper-slide-prev, swiper-slide-duplicate-prev, swiper-slide-next, swiper-slide-duplicate-next classes not accurate

### ISSUE THREAD

**Issue by rsepierre** [nolimits4web/swiper#6270]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-infinite-loop-with-slides-per-group-forked-hm1lf6?file=/index.html

### Bug description

When loop mode is enabled, the appliance of `slideNextClass`, `slidePrevClass`, `slideDuplicateNextClass` and `slideDuplicatePrevClass` is unreliable and I believe is not working according to spec :

**Documentation :**
[slidePrevClass](https://swiperjs.com/swiper-api#param-slidePrevClass)
[slideDuplicatePrevClass](https://swiperjs.com/swiper-api#param-slideDuplicatePrevClass)

[slideNextClass](https://swiperjs.com/swiper-api#param-slideNextClass)
[slideDuplicateNextClass](https://swiperjs.com/swiper-api#param-slideDuplicateNextClass)

`.swiper-slide-prev` and `.swiper-slide-duplicate-prev` classes are applied on slides that are neither the previous slide or a duplicate of the previous slide.

`.swiper-slide-next` and `.swiper-slide-duplicate-next` classes are applied on slides that are neither the next slide or a duplicate of the next slide.

### Expected Behavior

I would expect the .swiper-slide-next and .swiper-slide-duplicate-next class to only be applied to slides who would be the actual next slide of a copy of the next slide.

I would expect the same thing for .swiper-slide-prev and .swiper-slide-duplicate-prev

### Actual Behavior

Reproduction link : 
https://codesandbox.io/s/swiper-infinite-loop-with-slides-per-group-forked-hm1lf6?file=/index.html

Steps to reproduce (and test) : 
Press "t" on the keyboard (or run the `print();` command in console manually) and watch console log history.

Each of the three slides has been attributed a `data-hash` attribute : "slide 1", "slide 2" and "slide 3"

The testing function will log the `data-hash` of the first found element for each of the following classes : `swiper-slide-prev`, `swiper-slide-duplicate-prev`, `swiper-slide-next`, `swiper-slide-duplicate-next`.

The `print()' test function also takes care of using running the `updateSlidesClasses()` method before testing just in case. After printing the results in the console, it's sliding to next slide with the `slideNext()` method.

When tested, the hash corresponding to the slidePrevClass is not necessarily equal to the hash corresponding to slideDuplicatePrevClass. Same thing goes for slideNext and slideDuplicateNext. Sometimes, slideNext and slidePrev and/or slideDuplicateNext and slideDuplicatePrev have the same hash value (which should not be possible in a setup with three slides).

(example console log)
![image](https://user-images.githubusercontent.com/6746875/208495844-90b1398b-bf1a-4e14-8e51-72c1c4c23a70.png)

### Swiper version

8.4.2 and 8.4.5

### Platform/Target and Browser Versions

Chrome 108.0.5359.125 (64 bits) on Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
