### ISSUE TITLE
`slidesPerGroupAuto: true` is ignored in pagination

### ISSUE THREAD

**Issue by benface** [nolimits4web/swiper#6274]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-infinite-loop-with-slides-per-group-forked-u0dex0?file=/index.html

### Bug description

When using `slidesPerGroupAuto: true`, the number of bullets in the pagination doesn't change the same way it does when using `slidesPerGroup` with a fixed amount of slides (even if that fixed amount is the same as the dynamic amount that ends up getting used with `slidesPerGroupAuto`).

### Expected Behavior

In the example provided, there should be 3 bullets in the pagination, since there are 3 groups of 3 slides.

### Actual Behavior

In the example provided, there are currently 7 bullets in the pagination.

### Swiper version

8.4.5

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
