### ISSUE TITLE
Last bullet navigation is never active when centeredSlides and centeredSlidesBounds are true

### ISSUE THREAD

**Issue by emely-webit** [nolimits4web/swiper#6277]
### Code language and versions
**Svelte** version: 3.0.0
**Vite** version 4.0.2
**Typescript** version 4.9.4
**Swiper** version 8.4.5
**Node** version 16.15.1

### Description

I think there are a bug when using the combination of `centeredSlides={true}`, `centeredSlidesBounds={true}` and setting `slidesPerView` to a decimal number (2.2, 3.2 etc.). 
When navigating the **second** and the **last** bullet they are not marked as active. I guess it has something to do with the centered slide is the active one.

### How to reproduce

1. Copy the code below into a svelte project with everything needed installed
2. Try using the navigation, either swipe or use the arrows, and see that the **second** and **last** is not set as active

### Code: 

 ```
<script lang="ts">
  // import Swiper JS
  import { Swiper, SwiperSlide } from "swiper/svelte";  // import Swiper styles
  import { Navigation, Pagination } from "swiper";
  // import the default css for swiper
  import 'swiper/css';
  import 'swiper/css/navigation';
  import 'swiper/css/pagination';
</script>

<div>
  <Swiper 
      pagination={true}
      modules={[Pagination, Navigation]} 
      navigation={true} 
      class="mySwiper" 
      slidesPerView={3.2}
      spaceBetween={20} 
      centeredSlides={true}
      centeredSlidesBounds={true}>
        <SwiperSlide>
            slide 1
        </SwiperSlide>
        <SwiperSlide>
            slide 2
        </SwiperSlide>
        <SwiperSlide>
            slide 3
        </SwiperSlide>
        <SwiperSlide>
            slide 4
        </SwiperSlide>
        <SwiperSlide>
            slide 5
        </SwiperSlide>
        <SwiperSlide>
            slide 6
        </SwiperSlide>
        <SwiperSlide>
            slide 7
        </SwiperSlide>
        <SwiperSlide>
            slide 8
        </SwiperSlide>
    </Swiper>
</div>
```

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Svelte components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
