### ISSUE TITLE
Unable to drag with spaceBetween

### ISSUE THREAD

**Issue by warudin** [nolimits4web/swiper#6278]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/DQIPijnenburg/pen/bGjddoy

### Bug description

When spaceBetween has a value, I am unable to drag the slider anymore.

### Expected Behavior

Use `spaceBetween` to add space between draggable slides.

### Actual Behavior

The space is added between the slides, but the slider is no longer draggable.

### Swiper version

8.4.5

### Platform/Target and Browser Versions

Safari 16.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Do search the issues before opening the new one
