### ISSUE TITLE
Swipercore.use imports all modules in main bundle

### ISSUE THREAD

**Issue by drtobal** [nolimits4web/swiper#6291]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/dkqfem?file=/src/app/app.module.ts

### Bug description

Hi (sorry about my english) I don't know how to put this build issue in codesandbox,
I am using swiper in angular 15 and installing modules via Swipercore.use,
Different modules in different lazy loaded pages, but then at build bundle, all modules are imported in main .js file for all routes, like this, this is main js file used in all routes

<img width="563" alt="Captura de Pantalla 2023-01-17 a la(s) 01 15 00" src="https://user-images.githubusercontent.com/3515447/212809300-01582f7c-6b13-4150-9def-ce02327e9c86.png">

But in index component of any route I am installing like this, different modules for different routes:

Index component in Home Module
<img width="586" alt="Captura de Pantalla 2023-01-17 a la(s) 01 17 01" src="https://user-images.githubusercontent.com/3515447/212809391-03e2fce4-b251-4bb4-b70d-98f093ba91ef.png">

Index component inExample Module
<img width="517" alt="Captura de Pantalla 2023-01-17 a la(s) 01 16 46" src="https://user-images.githubusercontent.com/3515447/212809392-48558001-f19a-4827-ba1d-d2915ae04b22.png">

And the router is like this:
<img width="746" alt="Captura de Pantalla 2023-01-17 a la(s) 01 17 46" src="https://user-images.githubusercontent.com/3515447/212809454-9920b8be-dcc2-4181-87d1-2420f542c4b4.png">

(There are other pages that are not showed in the example)
Thanks for your help.

### Expected Behavior

I would like to import different modules only in the route module that is used to avoid to generate an oversized main bundle file, and get correctly split code for child routes.

### Actual Behavior

All modules are included in the main js file

### Swiper version

1.8.x

### Platform/Target and Browser Versions

Any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by drtobal** [comment]
I just noticed that is becouse of the import methods

When you use
`import { Thumbs, Keyboard, Lazy, Virtual } from 'swiper';`

on lazy loaded modules, then the js files appears on the `main.js` file bundle

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
