### ISSUE TITLE
Swiper slides buggy when using Virtual module with vertical scrolling & css mode enabled

### ISSUE THREAD

**Issue by harshbaz** [nolimits4web/swiper#6292]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Repo: https://github.com/harshbaz/swiper-svelte-virtual-vertical-css
Stackblitz: https://stackblitz.com/github/harshbaz/swiper-svelte-virtual-vertical-css
(Sorry for no codesandbox link, it doesn't work for some reason)

### Bug description

In the reproduction there are three pages:

- `http://localhost:xxxx/`: the root or index page is without any vertical module and how it should behave with virtual module as well. Basically it's a reference to what I'm trying to do with the `Virtual` module.
- `http://localhost:xxxx/virtual`: `/virtual` page is with the `Virtual` module. The data array is first initialised with one element. After the array is updated the swiper modules does not reflect the change. You can check the logs in the console.
- `http://localhost:xxxx/virtual-key`: `/virtual-key` page is with the `Virtual` module and `Swiper` component is wrapped in `#key`  which reinitialises the component when the data array is updated which at least allows scrolling. After the reinitialization, on some scrolling the `slideChange` event emits starts emitting continuously with different `realIndex` values. The `from` value from virtualData also keeps changing. Here's a video:

https://user-images.githubusercontent.com/106158714/212871846-14c16a73-915e-4c14-b5f3-8e355b0e25f7.mp4

### Expected Behavior

There are 2 problems:

1. Updating the array should append the slides to swiper (on `/virtual` page)
2. On scrolling in virtual mode the `slideChange` event should emit the correct index value.

### Actual Behavior

Described above 

### Swiper version

8.4.5

### Platform/Target and Browser Versions

macOS Chrome 109

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Svelte components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
