### ISSUE TITLE
On new ios version, 3D transition cannot fill viewport

### ISSUE THREAD

**Issue by ApalloAltoBluck** [nolimits4web/swiper#6293]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-gbrjrg?file=README.md

### Bug description

On Safari 16.2 on ios, the cube transition causes the swiper slides to only render in 80% of the area. 

I've noticed on WebKit that Swiper JS applies a sort of hack that makes the clickable area of the cube appear larger than it is, likely because of an issue that was fixed this latest patch.

https://webkit.org/blog/13591/webkit-features-in-safari-16-2/

Since Stackblitz doesn't allow you to use the preview on mobile, I went ahead and hosted the sandbox repo on vercel to test on devices on the latest OS.

https://repro-swiper.vercel.app/

### Expected Behavior

Fill the entire container

### Actual Behavior

Fills only a portion of the container

### Swiper version

@latest

### Platform/Target and Browser Versions

IOS Safari 16.2 & Previous versions

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by TomasCarlson** [comment]
Seems to be an issue with Webkit 16.2 ?

[Could be this. 
](https://webkit.org/blog/13591/webkit-features-in-safari-16-2/)
`Fixed perspective: 0 behavior.`

I know the view kinda overcorrects for zoom (some elements are offset in webkit). Could this just be the fix negating swiper's workaround?
