### ISSUE TITLE
missing slidesPerColumn props

### ISSUE THREAD

**Issue by GeonwooShin** [nolimits4web/swiper#6299]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/loving-chaum-v4f94w?file=/src/App.js

### Bug description

 I use swiper 8.4.5 in react 18 and typescript.
I have to show three items vertically in one slide.
official document of react swiper says to use slidesPerColumn Props.
But when I attempt to use the prop as shown in the attached codeSandBox link.

An error occurs: `Property 'slidesPerColumn' does not exist on type 'IntrinsicAttributes & RefAttributes<SwiperRef> & SwiperProps'.`

In my vscode, it looks like this.
![image](https://user-images.githubusercontent.com/79186378/213514268-c28e5dc0-e32e-4fd4-87ea-42d025759068.png)

How to do I fix it?

### Expected Behavior

Three items vertically in one slide.

### Actual Behavior

`Type '{ children: Element[]; slidesPerColumn: number; }' is not assignable to type 'IntrinsicAttributes & RefAttributes<SwiperRef> & SwiperProps'.`

`Property 'slidesPerColumn' does not exist on type 'IntrinsicAttributes & RefAttributes<SwiperRef> & SwiperProps'.`

### Swiper version

8.4.5

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is no such property in documentation
