### ISSUE TITLE
Autoplay stops working if the Swiper element is cloned / changes

### ISSUE THREAD

**Issue by MKaidan** [nolimits4web/swiper#6300]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-forked-wfgym1?file=/index.html

### Bug description

When cloning a `new Swiper()` element in the DOM (via jQuery in this instance), the slider stops working completely.

In the reproduction link, please wait 10 seconds to notice it breaking at slide 3 of 5.

I believe this was the issue brought up in #2436

### Expected Behavior

I expected Swiper to automatically detect the new (cloned) Swiper slider.

### Actual Behavior

The new Swiper slider is just static and not connected to the `new Swiper()` in any way.

### Swiper version

8.4.6

### Platform/Target and Browser Versions

Windows 11 Edge Chromium v109

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by MKaidan** [comment]
The temporary workaround I've found is to re-init the Swiper by calling `createSwiper()` in `setInterval()`

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked autoplay module. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
