### ISSUE TITLE
Gaps in swiperSlider on auto-play loop mode when given max-widths to swipers

### ISSUE THREAD

**Issue by Kamasah-Dickson** [nolimits4web/swiper#6305]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/Kamasah-Dickson/Cinema_TypeScript

### Bug description

 on loop mode when I give **max-widths** to the swipers, ! encounter blank swipers  on page reload unless I click the next arrow keys  multiple times. I removed  **max-widths** on the swipers  everything  works fine but I never like the intrisic width of the swipers. It  seems  there is a bug in the calculation of the swiper width when given max-widths  therefore it leaves some gaps in the swiper especially at the end of a loop.
![Vite + React + TS - localhost](https://user-images.githubusercontent.com/86136379/214218075-67721dcd-336e-4b7d-beae-3bbda018b8ad.jpg)
![Vite 2+ React + TS - localhost](https://user-images.githubusercontent.com/86136379/214218078-e10b67ab-c09f-4eef-8ffe-46859bff7282.jpg)

### Expected Behavior

Swiper JS should be able to calculate the modified widths of swipers  to be able to determine the end of a loop to prevent **gaps** before another loop occur.

- Below everything works fine when I don't modify the widths of swipers.

![Screene22222222 Capture 036 - Vite + React + TS - localhost](https://user-images.githubusercontent.com/86136379/214219185-caef3170-34cb-4b46-b033-7220852e9de4.jpg)

### Swiper version

v8.4.6

### Platform/Target and Browser Versions

windows chrome/all browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Mayuresh0072** [comment]
@nolimits4web Hello, I want to work and contribute on this issue, please assign me this issue. Thanks.

**Comment by nolimits4web** [comment]
Swiper v9 comes with fully reworked and now different loop functionality. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
