### ISSUE TITLE
SwiperSlideDirective isDuplicate is incorrect in loop mode 

### ISSUE THREAD

**Issue by twinssbc** [nolimits4web/swiper#6308]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-angular-forked-icze6o?file=/src/app/app.component.ts

### Bug description

Below code created a three slides in loop mode and display the isActive and isDuplicate value.
As below screenshot, the div having only class "swiper-slide-active" displays the **isDuplicate** as true instead of false.
···
<swiper [loop]="true" class="mySwiper">
    <ng-template swiperSlide let-data>Slide 1, Active: {{ data.isActive }}, Dup: {{ data.isDuplicate }}</ng-template>
    <ng-template swiperSlide let-data>Slide 2, Active: {{ data.isActive }}, Dup:{{ data.isDuplicate }}</ng-template>
    <ng-template swiperSlide let-data>Slide 3, Active: {{ data.isActive }}, Dup:{{ data.isDuplicate }}</ng-template>
  </swiper>
···
![Screenshot 2023-01-29 at 08 34 41](https://user-images.githubusercontent.com/3329841/215297553-41d55b1f-d32f-4e1e-9582-012fe1052aad.png)

### Expected Behavior

The expected behavior is the active slide in loop mode should have isDuplicate as false instead of true.

### Actual Behavior

The actual behavior is the active slide in loop mode has isDuplicate as true instead of false.

### Swiper version

8.4.6

### Platform/Target and Browser Versions

macOS, Safari 16.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
New Swiper v9 doesn't have Angular components anymore, it is recommended to use new [Swiper Web Components](https://swiperjs.com/element) instead.
