### ISSUE TITLE
Multiple background images with lazy loading and data-background (lazy module)

### ISSUE THREAD

**Issue by brahima** [nolimits4web/swiper#6309]
### Clear and concise description of the problem

Hello all,

Currently the lazy module gives the option to use the data-background attribute to lazy load image.
This data-background attribute is transformed into a [background-image](https://github.com/nolimits4web/swiper/blob/master/src/modules/lazy/lazy.js#L70) property with the loaded image.

However the [CSS background-image property](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) gives the possibility [to specify multiple images](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image#examples) (specifying several urls separated by commas). These images are all loaded and overlayed.

Unfortunately the lazy module does not give the options to specify several images to load via the data-background / background-image property.

### Suggested solution

The idea is to add the ability to pass an array of urls to the data-background attribute.

Concerned portion of code is located around those lines.
https://github.com/nolimits4web/swiper/blob/master/src/modules/lazy/lazy.js#L54

If a simple string is passed, the backward compatibility should be maintained.
If an array is passed, we call swiper.loadImage on every of these images before calling the «cleaning callback».

Regarding the loadImage callback, the following line should be updated and done for every loaded image :

From here in [the lazy module code](https://github.com/nolimits4web/swiper/blob/master/src/modules/lazy/lazy.js#L54), we should have some modifications, Mainly :

- data-background provided by user
 `const background = $imageEl.attr('data-background');` 
It can now return a string or an array

_Side note_ : I noticed that the last version of the dom7 library have a .data method that can return array. (The current version of swiper / 8.4.6 depends on an old version of dom7 / ^4.0.4 that does not contain the data method)

- Images loading and callback ..

`$imageEl.css('background-image', `url("${background}")`);`

instead we should now return / update the Dom with :

`$imageEl.css('background-image', `url("${background1}"), url("${background2}"), url("${backgroundN}") `);`

- Maybe the background image processing should have its own loop to load the images.
 
The code needs to be restructured to potentially load multiple images in case of data-background containing an array.
Also, that could be a good idea to add a [loadImages method to loadImage.js](https://github.com/nolimits4web/swiper/blob/master/src/core/images/loadImage.js)

- Interaction with lazy options
I think that this feature would not impact the way lazy options work (loadPrevNext, loadPrevNextAmount ...) but may be worth to check.
Indeed, even if a data-background contains multiple urls, that still concerns one slide so the lazy loading logic here is maintained.

I'm willing to contribute and propose a PR if you think that this feature makes sense. 
Any guidance / alternatives are welcome

Thanks

### Alternative

Not quite sure yet :
- Disable preloading of swiper and use another mechanism to lazy load images

Overlaying can be done easily via css ... but the lazy module seems to be the better place for image loading and synchronization with swiper.

I can't think of a good way to maintain the lazy loading feature useful in my case without adapting the swiper lazy module.

### Additional context

I'm using swiper to preview like 40/50 slides, each one containing 2 images.

Each slide contains one image that will be quickly got from cache for all users but the second overlayed image will be user dependant and generated on the fly so the lazy feature is mandatory in my case.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v9 doesn't lazy module anymore. If you have similar issues in Swiper 9, open a new issue with a CodeSandbox showing the issue.
