### ISSUE TITLE
Swiper sample does not work with Next 13 out of the box

### ISSUE THREAD

**Issue by Nefcanto** [nolimits4web/swiper#6312]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/Nefcanto/SwiperNext13Problem

### Bug description

Swiper does not work with Next 13. The default React example of Swiper + `'use client'` at the top of the page does not work.

Steps to reproduce:

Use this command to create a bare-bone Next 13 app:

`npx --yes create-next-app next --use-npm --js --eslint --no-src-dir --experimental-app --import-alias @/*`

Then remove the global style from `layout.js`.

Then replace the entire `page.js` content with Swiper's default example for react.

Add `'use client'` to the top of `page.js`

Now run using `npm run dev`.

You should see that slides are stacked one above the other.

### Expected Behavior

Swiper should work. Especially the default react example should work just by adding a simple `'use client'` line to the top of the page.

### Actual Behavior

It does not work. It stacks slides one above the other.

### Swiper version

8.4.6

### Platform/Target and Browser Versions

Next 13.1.6

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Reproduction link you have posted doesn't have anything related to Swiper

**Comment by Nefcanto** [comment]
@nolimits4web please tell me why it has nothing to do with Swiper?

You have a basic example for React. And Nexr.js is the most popular React meta-framework.

So, either your example should work if we copy it verbatim, or it should contain a note regarding the possible solution.

I think it's not fair you you closed this issue without investigation.

**Comment by nolimits4web** [comment]
because your Reproduction link doesn't contain Swiper nor illustrates the issue, it just Next clean install. Provide a correct link, ideally code sandbox
