### ISSUE TITLE
[v9.0.0] swiper web component: loop + fractional slidesPerView, e.g., 1.3 has several problems => Wrong first slide, can't go slide 3 

### ISSUE THREAD

**Issue by jakobadam** [nolimits4web/swiper#6313]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/angular-apuupy?file=src/main.ts

### Bug description

I previously reported the bug for Swiper Angular: https://github.com/nolimits4web/swiper/issues/6024

Now, I'm reporting it for Swiper web-components. I'm using it from Angular.

`loop=true` + `slide-per-view="1.3"` causes several issues:

1. Pagination bullets doesn't follow along
2. Starts on slide 2
3. Can't go to slide 3 when navigating forwards. 
4. Rescaling browser window also has issues.
5. Works almost for left navigation - sometimes previous slide is not shown.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/139791/216070434-937726a4-fcb9-4235-9509-20e261de3425.png">

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/139791/216070547-92d018a4-75ad-4ce7-abcc-c7d20c5a5f23.png">
 

### Expected Behavior

Like it does for React:
https://codesandbox.io/s/swiper-centered-auto-react-forked-9sx5pe?file=/src/App.jsx

### Swiper version

9.0.0

### Platform/Target and Browser Versions

macOs Safari 15.5 also Chrome has issues

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/migration-guide-v9#loop-mode

> It comes with new limitation. Amount of slides in loop mode should be at least 2x of slidesPerView value.

In your case there are actually 3 slides in view, so more slides is required in order to work it properly

**Comment by jakobadam** [comment]
Thanks. Added more slides (8 in total).

https://stackblitz.com/edit/angular-jjqcu6?file=src%2Fmain.ts

https://angular-jjqcu6.stackblitz.io

Remaining issues:
* starts on slide 2
* pagination bullets stops working
* sometimes previous slide is empty
* I can get the slider to crash by hitting navigation a lot (in Safari at least, haven't tested others)

kind regards,
Jakob
