### ISSUE TITLE
Cannot read properties of undefined (reading 'slideClass') when use nextjs Image

### ISSUE THREAD

**Issue by nuintun** [nolimits4web/swiper#6322]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-nextjs-bugs-g9e7pq?file=%2Fpages%2Findex.tsx

### Bug description

`Cannot read properties of undefined (reading 'slideClass')` when use nextjs `Image`

![image](https://user-images.githubusercontent.com/1730277/216276621-1cc3cde5-4dd5-454b-b4f0-0a46183d331a.png)

![image](https://user-images.githubusercontent.com/1730277/216276809-3a6bb680-cebd-415f-b422-02155e80b57c.png)

### Expected Behavior

No error

### Actual Behavior

Throw error

### Swiper version

9.0.0

### Platform/Target and Browser Versions

Windows11, Chome 109

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Altroo** [comment]
I confirm, same thing i have, just by switching inspect from web to mobile, then back to web & i got it.

**Comment by nolimits4web** [comment]
Reproduction link you have provided doesn't illustrate the issue

**Comment by nuintun** [comment]
@nolimits4web [swiper-nextjs-bugs](https://codesandbox.io/p/sandbox/swiper-nextjs-bugs-g9e7pq?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A22%7D%5D)

**Comment by gkpo** [comment]
Same here :(

**Comment by Altroo** [comment]
why is this issue closed ? it's still there, and we can reproduce it.
