### ISSUE TITLE
Pagination dots don't work correctly (only the first and last dot works)

### ISSUE THREAD

**Issue by martinhellwagner** [nolimits4web/swiper#6329]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.karriere.at/blog

### Bug description

We recently noticed a problem with the pagination dots of Swiper. When viewing the page https://www.karriere.at/blog on a mobile device, the slider dots in between the first and last dot don't work. I've already tried updating the Swiper NPM Package on our Stage (from 7.4.1 to 9.0.1), but to no avail.

Currently, our sliders get initialised like this (because we sometimes have more than one slider on a page). Even if I only initialise one slider on a page, the pagination dots don't work as expected.

```
  init(sliders) {
    sliders.forEach((slider) => {
      const sliderConfig = JSON.parse(slider.dataset.swiperConfig);
      const destroyBreakpoint = slider.dataset.swiperDestroyBreakpoint;

      let swiper;
      const initSwiper = () => {
        swiper = new Swiper(slider, {
          modules: [Navigation, A11y, Scrollbar, FreeMode, Keyboard, Pagination],
          ...sliderConfig,
        });
        swiper.init();
      };

      initSwiper();
    });
  }
```

### Expected Behavior

All pagination should work (i.e. are filled when the respective slide is selected).

### Actual Behavior

Only the first and last pagination dot work.

### Swiper version

7.4.1

### Platform/Target and Browser Versions

Chrome 109

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
As you can see it works here https://swiperjs.com/demos#pagination. Look for issue on your side or provide a link to the codesanbox with the issue

**Comment by martinhellwagner** [comment]
@nolimits4web

Turns out the problem was related to the `resize` event listener being called on multiple sliders: https://github.com/nolimits4web/swiper/issues/2915#issuecomment-918232676
