### ISSUE TITLE
Swiper sample does not work with Next 13 out of the box

### ISSUE THREAD

**Issue by Nefcanto** [nolimits4web/swiper#6332]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/Nefcanto/SwiperNext13Problem/blob/main/app/page.js

### Bug description

This is related to https://github.com/nolimits4web/swiper/issues/6312. But since you limited that conversation, I had to open another issue.

Please look inside the `app` directory. There you will find `page.js` which is the home page. Inside that, you'll see your default Swiper example taken from your site.

Please don't limit the conversation and let other people talk to you. If you had not limited the other issue, I would simply show that `page.js` to you there.

### Swiper version

8.4.6

### Platform/Target and Browser Versions

Next 13.1.6

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I can't see problems with Swiper there, everything works. You mean there is no styles? It is because CSS imports don't work in pages. Read Next docs to learn how to import CSS correctly. I see Swiper itself works correctly

**Comment by beamercola** [comment]
I'm a little lost as well.  Is there a bug in Next 13?  I can't get "swiper/css" to import in server or client component.

Did you ever figure this out @Nefcanto?

**Comment by Nefcanto** [comment]
@beamercola You should import CSs differently than their example. It's because the maintainers of this repo are too proud to add a single line to their help docs so that hundreds of developers like me and you won't spend hours in agony finding out why their sample examples do not work out of the box in Next 13.

I think you should import like this:

```
import 'swiper/swiper.min.css';
import '/node_modules/swiper/modules/pagination/pagination.min.css';
```
Though, I'm not sure to be honest.

**Comment by MasterProvider** [comment]
in order to work swiperjs style in nextjs 13 in experimental mode or AppDir you need to import the swiper styles in global css

//global.css
```
@import 'swiper/css';
@import 'swiper/css/navigation';
@import 'swiper/css/pagination';
```

//layout.js
```
import './globals.css';

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head />
      <body>
             {children}
      </body>
    </html>
  )
}
```

**Comment by beamercola** [comment]
@MasterProvider this worked awesome
