### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by NanciWu** [nolimits4web/swiper#6333]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/fnw0gf?file=%2Fsrc%2FApp.vue

### Bug description

when I use version 9.0.1, and add **Autoplay** module. this warning will appear 
`Component emitted event "autoplayTimeLeft" but it is neither declared in the emits option nor as an "onAutoplayTimeLeft" prop.`
![image](https://user-images.githubusercontent.com/101085643/216505878-3f78d969-7b5e-4525-a28e-4bd3447d8913.png)

### Swiper version

9.0.1

### Platform/Target and Browser Versions

Google Chrome 108.0.5359.124 for macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by boxjohn** [comment]
metoo

**Comment by kurosang** [comment]
metoo

**Comment by daidai-perfect** [comment]
![image](https://user-images.githubusercontent.com/73699236/217470256-0a18fd86-f1b5-4317-b297-68d0bebbd131.png)

**Comment by daidai-perfect** [comment]
![image](https://user-images.githubusercontent.com/73699236/217470499-1755dae3-df43-4278-9580-f0f5c5c7f3d4.png)
