### ISSUE TITLE
Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by muuvmuuv** [nolimits4web/swiper#6335]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/musing-chaum-tx84zk?file=/src/app/app.component.html

### Bug description

I can't reproduce it actually. The code is the same. Just the application arround it is bigger.

The error is that it says above error when using thumbs. I debugged it and can see that it gets the correct Swiper instance but the slides array does not update or update too late.

### Expected Behavior

Perhaps a check if the thumbs instance is fully initialized before using instance props

### Actual Behavior

```
thumbs.js:98 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at update (thumbs.js:98:51)
    at Swiper.<anonymous> (thumbs.js:172:5)
    at events-emitter.js:92:24
    at Array.forEach (<anonymous>)
    at events-emitter.js:91:37
    at Array.forEach (<anonymous>)
    at Swiper.emit (events-emitter.js:84:17)
    at resizeHandler (resize.js:13:5)
    at resize.js:35:11
```

> https://github.com/nolimits4web/swiper/blob/master/src/modules/thumbs/thumbs.js#L115

### Swiper version

9.x

### Platform/Target and Browser Versions

latest macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by ser-shant** [comment]
keep getting this error in 9.3.2 !!!

 at init (thumbs.js:68:1)
    at Swiper.<anonymous> (thumbs.js:167:1)
    at events-emitter.js:92:1
    at Array.forEach (<anonymous>)
    at events-emitter.js:91:1
    at Array.forEach (<anonymous>)
    at Swiper.emit (events-emitter.js:84:1)
    at Swiper.init (core.js:459:1)
    at mountSwiper (mount-swiper.js:24:1)
    at swiper.js:118:1

**Comment by Frallen** [comment]
Small solution for vue/nuxt developers

#### Use ref insted useState

I pass the value of `swiper` directly to `ref`

    <Swiper  @swiper="e=>slider=e" :thumbs="{ swiper: thumbsSwiper }"></Swiper>

    //thumbs
    <Swiper @swiper="e=>thumbsSwiper=e"></Swiper>

    const slider = ref<null>();
    let thumbsSwiper = ref<null>();

I didn't need `ClientOnly`

**Comment by Love-Becca** [comment]
read developers check this for solution

**Comment by Love-Becca** [comment]
React developer check this for solution

**Comment by Love-Becca** [comment]
React developers check this article for solution.  https://medium.com/@0l4m1de/troubleshooting-swiper-js-error-cannot-read-properties-of-undefined-reading-classlist-5064cae037e7

**Comment by IvanAdmaers** [comment]
Is the Swiper team gonna do something about this bug? Or they don't care when an issue is created not by their sponsors?
