### ISSUE TITLE
Click (touch) events blocked for a short time after swiping

### ISSUE THREAD

**Issue by kubagp1** [nolimits4web/swiper#6355]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-default-forked-u7yty5?file=%2Fsrc%2FApp.jsx

### Bug description

When quickly after swiping to change a slide, click events on elements not related to the swiper are not registered. This only happens when using touch input (emulated or real).

https://user-images.githubusercontent.com/37304664/217113994-b803b66c-4c4d-4a30-ac83-2e5f91843eee.mp4

### Expected Behavior

Click events on external elements should work as usual.

### Actual Behavior

Click events on external are not triggered when clicking on them shortly after swiping the swiper.

### Swiper version

9.0.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The link you have provided uses Swiper 7, latest version is 9

**Comment by kubagp1** [comment]
> The link you have provided uses Swiper 7, latest version is 9

Sorry for that, after posting I wanted to quickly check if I can just use previous version of Swiper and I didn't realise it would change for you too. At the time of recording the included video it was set to "^9.0.0" as in your demos. I reverted it back to "^9.0.0" now.

**Comment by kubagp1** [comment]
@nolimits4web should I open a new issue for that?
