### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:

### ISSUE THREAD

**Issue by pramudithaSJ** [nolimits4web/swiper#6356]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

9

### Bug description

9

### Expected Behavior

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Konekt\Projects\Konekt-Dev\parkfinda-website-test\node_modules\swiper\react\swiper-react.js
require() of ES modules is not supported.
require() of D:\Konekt\Projects\Konekt-Dev\parkfinda-website-test\node_modules\swiper\react\swiper-react.js from D:\Konekt\Projects\Konekt-Dev\parkfinda-websi
te-test\.next\server\pages\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js
 files in that package scope as ES modules.
Instead rename swiper-react.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Konekt\Projects\Konekt-Dev\parkfi
nda-website-test\node_modules\swiper\package.json.

### Actual Behavior

.next\server\pages\index.js (1:0) @ Object.swiper/react

> 1 | module.exports = require("swiper/react");;

### Swiper version

9

### Platform/Target and Browser Versions

Chrome,

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
