### ISSUE TITLE
slideToClickedSlide not working with Thumbs module

### ISSUE THREAD

**Issue by lolikana** [nolimits4web/swiper#6358]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-thumb-546j2k?file=/src/index.js:326-345

### Bug description

Hi everyone, 

I am trying to use `slideToClickedSlide` but it's not working.  
If I remove `thumbs` parameter from sliderParams, `slideToClickedSlide` actually works but it's remove the link between both sliders.
So I tried to use `Controller` instead (see image below if you want to try). 
 `slideToClickedSlide` works but the top-slides and thumbnail-slider are not in the same order anymore and the [default class](https://swiperjs.com/swiper-api#param-thumbs-slideThumbActiveClass) given by `Thumbs` module is not applied.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/78587037/217184447-3f5f0b48-d29d-44a5-9eb1-8832583c0f5f.png">

thank you in advance

### Expected Behavior

When click on the next (or prev) slide, should be center the active one. 

### Actual Behavior

The slide is active but not centered

### Swiper version

9.0.3

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Yes, it is by design, `slideToClickedSlide` will be overwritten to `false` on thumbs swiper

**Comment by adriben** [comment]
What if you add the thumb controller beahvior to the slider when you declare it at the end of the code?

`
new Swiper(".mySwiper2", sliderParams).controller.control = thumbs;
`

By adding `.controller.control = thumbs;` to the slider would align both elements behavior

**Comment by lolikana** [comment]
@nolimits4web 
> Yes, it is by design, `slideToClickedSlide` will be overwritten to `false` on thumbs swiper

I see, thank you. Will this behavior be changed in the future?



@adriben 
> By adding `.controller.control = thumbs;` to the slider would align both elements behavior

Almost there. On the first try, seems working but no more loop. Also, when I click until the last slide, then grab the gallery thumbnail, things start to act weird, slides order change. 
I might try to use only `controller` or parameter `on` for event handlers.  I found this slider which is closed enough of the result I want. 
[https://codepen.io/intotheprogram/pen/PowvWeX](url)

**Comment by lukecharle** [comment]
Seems this is an issue on the latest version of Swiper `10.2.0`. `slideToClickedSlide` is getting set to `false` when using thumbs. Sorry if I've missed but is there a solution for this?

**Comment by cfxd** [comment]
You can add two event handlers to the _main_ swiper init (_after the thumbnail swiper init_) to get this working...

```javascript
  on: {
    afterInit: (swiper) => {
      swiper.thumbs.swiper.params.slideToClickedSlide = true;
      swiper.thumbs.swiper.update();
    },
    realIndexChange: (swiper) => {
      swiper.thumbs.swiper.slideToLoop(swiper.realIndex);
    },
  },
```

Working codepen @ https://codepen.io/cfxd/pen/vYvyqoM
