### ISSUE TITLE
Mobile: Horizontal Swiper and overflow-y scrolling

### ISSUE THREAD

**Issue by ntorrey** [nolimits4web/swiper#6363]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-default-forked-n88p3j?file=%2Findex.html&selection=%5B%7B%22endColumn%22%3A47%2C%22endLineNumber%22%3A86%2C%22startColumn%22%3A47%2C%22startLineNumber%22%3A86%7D%5D

### Bug description

In mobile, with a horizontal swiper, if a swiper-slide has overflow-y set on it, the horizontal swipe event is buggy. Maybe this is impossible to fix because of the nature of scrolling on mobile? I'm looking for a solution that wouldn't require using another swiper component using freemode because I prefer the native scrollbar in mobile.

### Expected Behavior

I expect to be able to swipe side-to-side (in a horizontal swiper) even when the slide has `overflow-y: auto` set on it.

### Actual Behavior

The swiper doesn't swipe when I have `overflow-y: auto` set on it.

### Swiper version

9

### Platform/Target and Browser Versions

Chrome on windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Add this CSS rule:

```css
.swiper-slide {
  touch-action: pan-y;
}
```

**Comment by ntorrey** [comment]
@nolimits4web 
Thank you - that did the trick!

**Comment by paulocheque** [comment]
They close this issue https://github.com/nolimits4web/swiper/issues/6458 so I can't reply there.

This css doesn't work for me, but playing with the touch-action property in your html structure may work. 

Best

**Comment by Ushlerdop** [comment]
> They close the issue #6458 so I can't reply there.
> 
> This css doesn't work for me, but playing with the touch-action property in your html structure may work.
> 
> FYI @Ushlerdop
> 
> Best

Yes, it does. TY a lot for your

**Comment by Ushlerdop** [comment]
> They close the issue #6458 so I can't reply there.
> 
> This css doesn't work for me, but playing with the touch-action property in your html structure may work.
> 
> FYI @Ushlerdop
> 
> Best

Yes it does. Thank you for your activity here.

My best to you

**Comment by trickstival** [comment]
In case anyone struggles with that: applying it to inner scrolls also seems to work:
```
.inner-scroll-container {
  touch-action: pan-y;
}
```

**Comment by Ambrise** [comment]
@nolimits4web

Thank tou very much !!
