### ISSUE TITLE
TS error while using WebComponent in Next (v9.0.3 )

### ISSUE THREAD

**Issue by drMonro** [nolimits4web/swiper#6364]
### Discussed in https://github.com/nolimits4web/swiper/discussions/6362

<div type='discussions-op-text'>

<sup>Originally posted by **drMonro** February  7, 2023</sup>
Trying transfer to WebComponent i got [TS error](https://prnt.sc/JLEvLcvN-lor)

How can I fix it?</div>

**Comment by nolimits4web** [comment]
https://coryrylan.com/blog/how-to-use-web-components-with-typescript-and-react
