### ISSUE TITLE
WebComponent does not work in Ionic Angular

### ISSUE THREAD

**Issue by muuvmuuv** [nolimits4web/swiper#6367]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/headless-pine-lrnpui?file=/src/app/home/home.page.html

### Bug description

I am using the bundled WebComponent version and have issues using it in Angular with Ionic. The Swiper object is destroyed, has no properties to access and does not swipe initially. When loading the page it never reaches a state where I can slide, which is weird, because it has contents. An `.update()` is not possible, due to its ViewChild beeing undefined for some reason.

I will continue trying to create a repl for it just need to set it up as similar as our codebase.

```html
<swiper-container #swiper
                  slides-per-view="1"
                  threshold="6"
                  speed="500"
                  autoplay="true"
                  autoplay-pause-on-mouseenter="true"
                  autoplay-delay="5000">

  <ng-container *ngFor="let slide of slides">
    <ng-container *ngIf="slide && slide.children">
      <swiper-slide [attr.id]="slide.htmlId || null"
                    [ngClass]="slide.className"
                    [style.background-image]="slide.file | backgroundImageFileUrl">
					.... Contents here
      </swiper-slide>
    </ng-container>
  </ng-container>

</swiper-container>
```

### Actual Behavior

![Bildschirm­foto 2023-02-08 um 09 15 07](https://user-images.githubusercontent.com/11534760/217472891-20e3cbcb-6d5e-4691-92ee-4d412d2c88da.png)

![Bildschirm­foto 2023-02-08 um 09 17 09](https://user-images.githubusercontent.com/11534760/217472974-bc9cc81b-d610-42e3-8cab-160ee13062cd.png)

### Swiper version

9.x

### Platform/Target and Browser Versions

macOS and Brave

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by muuvmuuv** [comment]
Ok, it is something with Ionic and its routing.

**Comment by digaus** [comment]
Same issue here. Tried to migrate to swiperjs because with Ionic 7 the `ion-slides` is removed

**Comment by muuvmuuv** [comment]
It is something with Ionic, upvote there, so we can get this fixed asap :D

→ https://github.com/ionic-team/ionic-framework/issues/26722

**Comment by yigsvnsla** [comment]
> It is something with Ionic, upvote there, so we can get this fixed asap :D
> 
> → [ionic-team/ionic-framework#26722](https://github.com/ionic-team/ionic-framework/issues/26722)

post guide 💯 #6384
