### ISSUE TITLE
Support for angular missing in version 9.0.3

### ISSUE THREAD

**Issue by Mani-VD** [nolimits4web/swiper#6368]
### Clear and concise description of the problem

I installed swiper module for my ionic app. As per their documentation, I tried importing SwiperModule from 'swiper/angular'. But angular support was removed.
Reference https://ionicframework.com/docs/angular/slides

### Suggested solution

Add angular support to swiper that you have removed. Currently I downgraded to 8.4.7

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by muuvmuuv** [comment]
Nowhere in the docs is Angular anymore, where did you find that? Angular is no longer supported in that way, Swiper is now a native WebComponent which "just works" in Angular.

https://swiperjs.com/migration-guide-v9

**Comment by EliezerB123** [comment]
@muuvmuuv And by that you mean,  "just doesn't work" in Angular?

For anyone else who comes here, stackoverflow came to the rescue.

https://stackoverflow.com/questions/75326426/how-to-use-swiper-9-with-angular
