### ISSUE TITLE
loop next doesn't work

### ISSUE THREAD

**Issue by drdah123** [nolimits4web/swiper#6372]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/gracious-firefly-ozni6j?file=%2Fsrc%2FApp.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A41%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A41%7D%5D

### Bug description

navigation of the next doesn't work at the end of slides in the loop mode with slidesPerView

### Expected Behavior

to loop

### Actual Behavior

stop at the end of slides

### Swiper version

9.0.3

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/migration-guide-v9#loop-mode
> Amount of slides in loop mode should be at least 2x of slidesPerView value.
