### ISSUE TITLE
v9: slidePrev() stops working after some calls (in loop mode)

### ISSUE THREAD

**Issue by petrot** [nolimits4web/swiper#6383]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-virtual-slides-forked-0v06ns?file=%2Findex.html

### Bug description

When we use slidePrev/slideNext for navigating in loop mode, slidePrev randomly (?) stops working.

To reproduce, open my link, then click to "Next" button 4-5 times, then click to "Prev" button 2-3 times. Backward navigation stops working.

### Expected Behavior

slidePrev works normal

### Actual Behavior

slidePrev randomly (?) stops working.

### Swiper version

9.0.4

### Platform/Target and Browser Versions

macOs, Chrome  109.0.5414.119  (arm64) 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nahidhasan141400** [comment]
Me also get this same problem

**Comment by wiseaidev** [comment]
Same here. I noticed that when Dependabot upgraded to V9: 

- [Demo](https://deploy-preview-4--hill-climb-thirdweb.netlify.app/)
- [Dependabot PR](https://github.com/hill-climb/landing-page/pull/4)

**Comment by leonace924** [comment]
I got the same issue, slidePrev doesn't work and loop mode is different from v8

**Comment by Officialibn1** [comment]
I'm encountering the same error too, in my console it tells me 'swiper is null'
