### ISSUE TITLE
Swiper element with Svelte causes glitching when scrolling.

### ISSUE THREAD

**Issue by harshbaz** [nolimits4web/swiper#6387]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/sveltejs-kit-template-default-1tbqpx?file=src%2Froutes%2F%2Bpage.svelte&terminal=dev

### Bug description

Adding more slides to swiper container causes glitching when scrolling vertically. Also, I'm not able to figure out how to exactly use virtual scrolling where each slide is complex  with events and nested components and hence cannot be "appended" as HTML to swiper container's `virtual.appendSlide` method

### Expected Behavior

In v8, this used to work fine without flickering.

### Swiper version

v9.0.4

### Platform/Target and Browser Versions

macOS Chrome 109

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by harshbaz** [comment]
Still isn't solved with 9.2.0

**Comment by nolimits4web** [comment]
It is because your `on:slidechange={handleChange}` where you during transition changes the slides and scrolling apparently does something wrong. You should add slides probably within a `reachend` event
