### ISSUE TITLE
Infinite loop with slidesPerView more than half of available slides

### ISSUE THREAD

**Issue by DannyKr43mer** [nolimits4web/swiper#6395]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-per-view-auto-forked-6n2gdu?file=/index.html

### Bug description

When using a fixed slidesPerView for example 5, but you have only less than 10 slides available you cannot loop. In my projects there is often a case where I have only 5 slides, and I want to show them all but still loop through them. This is not possible with the new loop functionality.

### Expected Behavior

When the amount of slides is less than douple the slidersPerView value you should still be able to infinitely loop.

### Actual Behavior

The loop is not working when the amount of slides is less than the slidesPerView value. Even if I have just one slide and want to loop it infinitely swiper should duplicate slides and loop them. 

### Swiper version

9.0.5

### Platform/Target and Browser Versions

Browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by DannyKr43mer** [comment]
Okay. But that makes the loop mode actually worse than in version 8. Showing slides in an infinite loop even if they are not doubled the slidesPerView value is a use case that is encountered often. So the swiper is basically useless for a lot of use cases in this state.

**Comment by stevepsharpe** [comment]
I second this sentiment. I've dropped down to v8 because loop mode doesn't seem to work in v9. It works going previous, but not next.

**Comment by cesarmiquel** [comment]
We had this same issue. Downgrading to v8.
