### ISSUE TITLE
Centered slides + loop or rewind makes it start at the last slide

### ISSUE THREAD

**Issue by azerroth11** [nolimits4web/swiper#6400]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://azerroth11.github.io/BasileMinster/photography.html

### Bug description

It's an issue that's been present for the past few generations (at least v7 and v8) and despite the loop apparently being reworked, it still is there. 
The slideshow starts on the last slide when swiper-slide has a width of fit-content. 
But it is the only way I have found to have the images at 100% height and correct apect ratio for the width while touching each other. 
InitialSlide has no effect. 

My swiper HTML code: 
.swiper {
  height: 100%;
  width: 100%;
}
.swiper-wrapper {
  width: 100%;
}
.swiper-slide {
  width: fit-content; <- It seems to be causing the issue. 
}
.swiper-slide img {
  max-height: 100%;
  height: 100vh;
}

My swiper JS code: 
const swiper = new Swiper('.swiper', {
          slidesPerView: 'auto',
          centeredSlides: true,
          grabCursor: true,
          rewind: true,
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          },
          pagination: {
            el: '.swiper-pagination',
            clickable: true,
          },

### Expected Behavior

I expect the slideshow to begin on the first slide and swipe to the left.

### Actual Behavior

It starts on the last slide and then rewinds to the first one.

### Swiper version

v9

### Platform/Target and Browser Versions

Windows 11 Firefox 109.0.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by caiminghan** [comment]
same problem. Is it a bug ?

**Comment by LStienon** [comment]
yep same problem here, i hope one day i can understand what we're doing wrong T.T
