### ISSUE TITLE
【BUG】`onTransitionEnd` event will be fired during swiper transition.

### ISSUE THREAD

**Issue by AlexBai1991** [nolimits4web/swiper#6402]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/rqfg38?file=%2Fsrc%2FApp.jsx&selection=%5B%7B%22endColumn%22%3A28%2C%22endLineNumber%22%3A50%2C%22startColumn%22%3A28%2C%22startLineNumber%22%3A50%7D%5D

### Bug description

* `onTransitionEnd` event will be fired during swiper transition

### Expected Behavior

xx

### Actual Behavior

xx

### Swiper version

9.0.5

### Platform/Target and Browser Versions

macos chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The link demo link you posted doesn't illustrate the issue
