### ISSUE TITLE
Custom elements register without global styles breaks slides initialization.

### ISSUE THREAD

**Issue by konclave** [nolimits4web/swiper#6405]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/xenodochial-water-5qrwep?file=/src/App.js

### Bug description

I'm using Swiper custom elements inside React component which is rendered then inside other custom element. 
Because of that, I can't insert Swiper styles globally and use `register(false)` for custom elements registration to prevent styles been inserted into document head and provide styles with the `injectStylesUrls` param. 

In that case `swiper-slides` stop been properly initialized. No width, attributes, classes are set in `swiper-slide` nodes anymore.

### Expected Behavior

Slides initialization works the same way if `register()` called without `false` argument.

### Swiper version

9.0.5

### Platform/Target and Browser Versions

MacOS, Chrome 109

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check docs https://swiperjs.com/element#injecting-styles, you also need to add styles to the document
