### ISSUE TITLE
Create an overflow: hidden wrapper only above swiper-slides components

### ISSUE THREAD

**Issue by konclave** [nolimits4web/swiper#6406]
### Clear and concise description of the problem

Now overflow:hidden is set on `swiper-container` element. That doesn't allow to move element it contains out of its borders. 
For instance, I want to add offset to the next/prev buttons out of the container to make half of the button go outside the container. Now it's not possible.
The same about the container-start and container-end slots.

### Suggested solution

Add a new wrapper with overflow:hidden around `swiper-slides` only and remove overflow: hidden from `swiper-container`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
you can easily overwrite it in your CSS
