### ISSUE TITLE
Swiper conflict with KnockoutJS

### ISSUE THREAD

**Issue by tschleuss** [nolimits4web/Swiper#641]
I have two elements inside the swiper:
- Span that receive a text value
- Input that receive a value

```
<div class="container">
	<span data-bind="text: title"></span>
	<input type="text" data-bind="value: count" />
</div>
```

That span tag, with "text" bind works well, but the input tag with "value" bind, don't work. Seems that knockout can't insert value in that input. When i disable swiper, all works well.

Example: http://jsfiddle.net/tschleuss/VdZZL/2/
If comment the method call 

```
runSwiper();
```

it will work.

If invert the order of calls, swiper before and knockoutjs after,
it works, but i want to know why it happen. How can i fix that calling in the original order.

**Comment by tangdaizheng** [comment]
@WanjaStier your setTimeout solution works well while i put swiper's slide in the foreach attributes of knockout evoking conflicts
