### ISSUE TITLE
Swiper stops sliding in iphone

### ISSUE THREAD

**Issue by smohadjer** [nolimits4web/swiper#6414]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://slaven.de/camp/ueberblick.html

### Bug description

When I try to swipe photos in my slider on iPhone very often sliding stops before new photo is completely in view.

### Swiper version

Latest version

### Platform/Target and Browser Versions

Safari in iPhone 8

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by smohadjer** [comment]
![Uploading 7DB80EA8-7191-4B8F-866C-133D704A4466.jpeg…]()

**Comment by guillermodlpa** [comment]
I noticed this as well today, when upgrading the version `swiper` in my project. I've confirmed that it was working fine in version `8.4.7`. The issue starts happening in `9.0.0` and is still happening now with `9.0.5`

**Comment by dpmango** [comment]
Downgrade to 8.4.7 helps. 
Something gets wrong with 9.x

Got flickering behaviour on android devices when trying to swipe

```
    this.swiperInstance = new Swiper('.js-swiper-stories', {
      modules: [Pagination, Autoplay],
      slidesPerView: 1,
      spaceBetween: 0,
      autoplay: {
        delay: 6000,
      },
      pagination: {
        el: '.swiper-pagination',
        type: 'progressbar',
      },
    });
```

**Comment by shaibrown5** [comment]
+1

**Comment by afewyards** [comment]
+1

**Comment by smohadjer** [comment]
Fix is now released: https://github.com/nolimits4web/swiper/releases/tag/v9.1.0

Thanks

**Comment by virendra-koloapp** [comment]
> I noticed this as well today, when upgrading the version `swiper` in my project. I've confirmed that it was working fine in version `8.4.7`. The issue starts happening in `9.0.0` and is still happening now with `9.0.5`

Better but not 100% ❤️
