### ISSUE TITLE
Swiper Sensitivity fails in Safari

### ISSUE THREAD

**Issue by liamcrean** [nolimits4web/swiper#6418]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/270-mousewheel-control/core

### Bug description

Mousewheel / touchpad sensitivity parameters in Safari (latest build v16.2) do not have any effect. 

### Expected Behavior

Would expect the same touchpad responsiveness between Chrome, Firefox, Edge and Safari. 

### Actual Behavior

The swiper remains overly sensitive often skipping slides slides with mousewheel or touchpad swipe.

### Swiper version

8.4.6 and 9.0.3

### Platform/Target and Browser Versions

OSX Safari 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This parameter is mostly for freeMode where it has effect, without it sensitivity doesn't do anything

**Comment by liamcrean** [comment]
Thanks @nolimits4web 

Is there a way to desensitise trackpad/mousewheel sensitivity then? I see skipping slides mostly in Safari.

Thanks, Liam
