### ISSUE TITLE
autoplay loop issue

### ISSUE THREAD

**Issue by vinayraghavendra** [nolimits4web/Swiper#642]
loop in autoplay works fine but when it reaches end all slides will come back to initial slide and start over again. it can be visible. what i need is it should loop to starting slide instead of coming back. and also I need FadeIn or FadeOut effect during transition of slides. can we achieve this? if yes how?.

if i give loop:true. autoplay ends at last slide.

**Comment by bmance** [comment]
Just use php to keep track of the index and loop it back begining.
