### ISSUE TITLE
Incorrect count of dots: grid and loop enabled

### ISSUE THREAD

**Issue by scubacube** [nolimits4web/swiper#6420]
### Check that this is really a bug

- [ ] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-grid-forked-zqd419?file=%2Fsrc%2FApp.jsx&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A20%7D%5D

### Bug description

I want to use a grid with 2 rows (each row has 1 slide) and loop=true but in this case a count of dots is not correct

### Expected Behavior

if the total number of slides is 6 and there are 2 slides under each other on each view, the sum of the dots is 3

### Actual Behavior

Too many dots (it equals total count of slides, 6)

### Swiper version

9.0.5

### Platform/Target and Browser Versions

Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Same as #6351
