### ISSUE TITLE
Coverflow with "loop" and only 3 slide bug?

### ISSUE THREAD

**Issue by timinformatica** [nolimits4web/swiper#6424]
Hello
I tested the code from: https://swiperjs.com/demos#effect-coverflow

From the above code I only kept 3 images and in the initialization script I added/modified:
```
slidesPerView: 3,
loops: true,
```
and this is the entire scritp:
```

    var swiper = new Swiper(".mySwiper", {
      effect: "coverflow",
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 3,
      loop: true,
      coverflowEffect: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows: true,
      },
      pagination: {
        el: ".swiper-pagination",
      },
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
    });
```

but when the images are sliding they are not seen and position correctly.

I don't have an account on codesandbox, but for testing I used this:
https://codepen.io/berettatim/pen/qBMZyzz

These are the version I used:
https://cdnjs.cloudflare.com/ajax/libs/Swiper/9.0.5/swiper-bundle.min.js

**Comment by nolimits4web** [comment]
when loop enabled amount of slides must be >= slidesPerView * 2
