### ISSUE TITLE
Error using Pagination in Swiper 9 Elements

### ISSUE THREAD

**Issue by ThePlatinum** [nolimits4web/swiper#6427]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-element-pagination-c9pth1?file=%2Fsrc%2FApp.jsx&selection=%5B%7B%22endColumn%22%3A12%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A12%2C%22startLineNumber%22%3A7%7D%5D

### Bug description

An attempt to use pagination in Swipper 9 elements (React) gives this error or similar.

```
Uncaught TypeError: Cannot use 'in' operator to search for '14' in [object Object]
    at Swiper.setBreakpoint (setBreakpoint.js:19:32)
    at Swiper.init (core.js:445:14)
    at new Swiper (core.js:180:14)
    at SwiperContainer.initialize (swiper-element-bundle.js:130:19)
    at SwiperContainer.connectedCallback (swiper-element-bundle.js:150:10)
    at appendChildToContainer (react-dom.development.js:11069:16)
    at insertOrAppendPlacementNodeIntoContainer (react-dom.development.js:23875:7)
    at insertOrAppendPlacementNodeIntoContainer (react-dom.development.js:23881:7)
    at commitPlacement (react-dom.development.js:23855:9)
    at commitReconciliationEffects (react-dom.development.js:24591:7)
  ```

### Expected Behavior

The sizing of the swiper slides suppose to be corresponding to the set breakpoint values

### Actual Behavior

With this error, the whole wipper does not work.

### Swiper version

9.0.0

### Platform/Target and Browser Versions

Ubuntu, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by alexcavender** [comment]
Experiencing the same thing, I tested removing the breakpoints and it seemed to fix it. Not sure exactly why yet, getting this console error:
setBreakpoint.js:19 Uncaught TypeError: Cannot use 'in' operator to search for '14' in [object Object]

**Comment by ThePlatinum** [comment]
Yes, that's exactly it.

Removing the breakpoint fixes it... Putting it reproduces it.

**Comment by i7N3** [comment]
I am experiencing the same thing with Svelte.

We should fix the documentation if HTML elements can't accept objects in attributes.
https://swiperjs.com/element#usage-with-svelte

**Comment by ThePlatinum** [comment]
I interprete @nolimits4web response as "We are not fixing it"

**Comment by JouanDeag** [comment]
Sadly, it seems I have to find a different library then.
Not being able to make the carousel responsive is a dealbreaker for me.
