### ISSUE TITLE
"preventClicks" causes unclickable links on slides in Chrome

### ISSUE THREAD

**Issue by lkaisers** [nolimits4web/swiper#6429]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://crm.itdesign.de/

### Bug description

We encountered that the preventClicks functionality causes unclickable links on slides. This bug occured only in Chrome, not f.e. in Firefox. That is why we think it is a bug. It appeared mostly on Windows devices and couldn't be reproduced in Ubuntu Chrome for example.

We propose that the issue will be either fixed or the `preventClicks` / `preventClicksPropagation` parameters are set to `false` by default since this can break things and I think it should be a nice-to-have feature but not the default behaviour.

Please note: We are currently setting the `preventClicks` parameters to `false` so the **Reproduction link** won't be showing the issue for long from now on. But it's easy to reproduce I guess.

### Expected Behavior

Click on a link opens the target URL.

### Actual Behavior

Nothing is happening. It seems the link behaviour is prevented by JavaScript (`e.preventDefault`).

### Swiper version

9.0.5

### Platform/Target and Browser Versions

Windows / Chrome 110

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I can't see such issue, all works correctly in Chrome for me. Plus, the link you have provided doesn't illustrate the issue
