### ISSUE TITLE
Vue 2 -- looping Swiper -- allow us to render the duplicates so they stay reactive

### ISSUE THREAD

**Issue by dev-abota** [nolimits4web/swiper#6430]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/nolimits4web/swiper/issues/4349#issuecomment-802038357

### Bug description

Following up on this https://github.com/nolimits4web/swiper/issues/4349#issuecomment-802038357

We could actually make it work if:
 - we would be able to render the duplicates ourselves via Vue, 
 - and mark them as `swiper-slide-duplicate` and set the `data-swiper-slide-index`
 - Swiper would have to pick them up and use them directly. (`swiper.createLoop()` would be a no-op)

Then:
 - looping would work
 - reactivity in the duplicated slides would work

Is this something that could be considered?

### Swiper version

8.0.0

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper doesn't support Vue 2

**Comment by Vitomir2** [comment]
Strange to know that, @nolimits4web . I am using the Swiper in my Vue2 app. However, I am facing a small problem. I have made the slides in a loop, but when the array is updated, the slides are not updated accordingly. Let's say that the swiper has started with 2 elements (slides) in the array and I have an option to add a new one, then it should show the 3rd one, too, but it does not appear to be updated.

```js
<template>
	<ion-app>
		<ion-content class="ios">
			<swiper
				class="poll"
				:allow-touch-move="false"
				:navigation="true"
				:modules="modules"
				@swiper="onSwiper"
				@slideChange="slideChange"
			>
				<div class="swiper-wrapper">
					<swiper-slide v-for="question in selectedQuestions" :key="question._id">
						<div class="q-wrapper">
							<question
								:language-code="question.question[$i18n.locale] ? $i18n.locale : 'bg'"
								:data="question"
								:poll-style="input.style"
							></question>
						</div>
					</swiper-slide>
				</div>
			</swiper>

			<ion-button
				slot="fixed"
				class="navigation next"
				shape="round"
				fill="outline"
				:color="'primary'"
				:disabled="!canNext"
				@click="navigate('next')"
			>
				<ion-icon slot="icon-only" :name="icons.chevronForward"></ion-icon>
			</ion-button>

			<ion-progress-bar v-if="selectedQuestions.length > 1" slot="fixed" class="progress" :value="progress"></ion-progress-bar>
		</ion-content>
	</ion-app>
</template>

<script>
	import { Swiper, SwiperSlide } from 'swiper/vue/swiper-vue.js'
	import { Navigation } from 'swiper'
	import 'swiper/swiper.min.css'

	export default {
		name: 'PollPreview',
		components: {
			MobileHeader,
			QuestionClosed,
			QuestionOpen,
			QuestionRating,
			CountdownTimer,
			Swiper,
			SwiperSlide
		},
		props: {
			selectedQuestions: {
				type: Array,
				default: new Array()
			}
		},
		data() {
			return {
				questionIndex: 0,
				swiper: {},
				history: [],
				modules: [Navigation]
			}
		},
		watch: {
			input: {
				handler() {
					this.questionIndex = 0
					this.$store.commit('setAnswers', {})
					this.history = []

					if (this.swiper && !this.swiper.destroyed) this.swiper.slideTo(0)
				},
				deep: true
			}
		},
		methods: {
			onSwiper(swiper) {
				this.swiper = swiper
			},
			slideChange() {
				if (this.swiper.activeIndex > this.swiper.previousIndex) this.history.push(this.swiper.previousIndex)
				this.questionIndex = this.swiper.activeIndex
			}
	}
}
</script>
```

All works good, the `selectedQuestions` is changing properly and the progress bar is increase when selecting a new one, however, I am not able to go to it, because it is missing from the swiper.slides array.
