### ISSUE TITLE
Mousewheel control

### ISSUE THREAD

**Issue by Kawan-edres** [nolimits4web/swiper#6434]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/2i6lzk?file=%2Findex.html

### Bug description

When I use the Mouse wheel control in the vertical slider  it works fine with the mouse wheel but when I want to change slides with my touchpad with two fingers to scroll down it immediately changes 2 or 3 sometimes 4 slides altogether I don't know why but it is so weird  

### Expected Behavior

it should change one slide when you want to change slides with two fingers using your touch pad .

### Actual Behavior

it has a weird behavior it changes two or three sometimes 4 slides together 

### Swiper version

v9.0.5

### Platform/Target and Browser Versions

every browsers 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
this is how touchpad works, was discussed here numerous times
