### ISSUE TITLE
loop is not working

### ISSUE THREAD

**Issue by naveedshahzadofficial** [nolimits4web/swiper#6440]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://z4q4dx.csb.app/

### Bug description

when pass the parameter **loop: true** then left side arrow looping is working but right side arrow looping is not working in navigation links.
event right side touch is not working.

### Swiper version

9.0.5

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Amount of slides in loop mode in v9 must be >= slidesPerView * 2

**Comment by maxval1** [comment]
> Amount of slides

How does this problem need to resolve in responsive mode?
When e have in desktop 3 and for table 2, mobile 1, it would be difficult to clone/remove items

**Comment by ArianHamdi** [comment]
> Amount of slides in loop mode in v9 must be >= slidesPerView * 2

How does it work with `slidesPerView : auto` ?
