### ISSUE TITLE
Getting Hydration failed because the initial UI does not match what was rendered on the server error when using Swiper Element on NextJs

### ISSUE THREAD

**Issue by xvnds** [nolimits4web/swiper#6443]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/dreamy-benz-et8xf6?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A2%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A2%2C%22startLineNumber%22%3A9%7D%5D

### Bug description

Using ```<swiper-container>``` returns the error:

```Error: Hydration failed because the initial UI does not match what was rendered on the server.```

This error is from the dev console:
![image](https://user-images.githubusercontent.com/20581804/221857382-f2ce9d04-270f-4b38-a2f3-f1328a913093.png)
Refer to: https://nextjs.org/docs/messages/react-hydration-error

As seen in the example on codesandbox, there is no ```<span>``` element anywhere in the source code. But apparently, one ```<span>``` element is automatically added inside ```<swiper-container>``` when rendered.

![image](https://user-images.githubusercontent.com/20581804/221858216-0e99abab-1593-44d3-98c7-4c80f75b9a83.png)

Is there a way to disable this ```<span>``` element from being rendered or to change the element <span> to a different element just to avoid this issue?

### Swiper version

9.0.5

### Platform/Target and Browser Versions

macOS, Windows, Google Chrome 110.0.5481

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can disable a11y

**Comment by alimokhlsi** [comment]
I'm having the same issues here, it happens when I pass both of the `breakpoints` and `loop` props.
by deleting any of those props, the problem does not show anymore.

**Comment by hsnmrd** [comment]
I'm having the same issues here, it happens when I pass both of the breakpoints and loop props.
By deleting any of those props, the problem does not show anymore.

**Comment by nachtfunke** [comment]
> I'm having the same issues here, it happens when I pass both of the `breakpoints` and `loop` props. By deleting any of those props, the problem does not show anymore.

I am having this _exact_ issue. Did you ever find a way to get it to work without having to remove `breakpoints` and/or `loop`?

**Comment by adarshaacharya** [comment]
@nachtfunke you can actually check if dom is loaded or not and render swiper package accordingly.

Example : 


```tsx
const Index = () => {
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);

  return (
    <>
      {domLoaded && (
        <Swiper>
          <div>Test</div>
        </Swiper>
      )}
    </>
  );
};

export default Index;
```


Reference : [Stackoverflow answer](https://stackoverflow.com/a/72318597/9851444)

**Comment by marcelo-albuquerque** [comment]
> @nachtfunke you can actually check if dom is loaded or not and render swiper package accordingly.
> 
> Example :
> 
> ```tsx
> const Index = () => {
>   const [domLoaded, setDomLoaded] = useState(false);
> 
>   useEffect(() => {
>     setDomLoaded(true);
>   }, []);
> 
>   return (
>     <>
>       {domLoaded && (
>         <Swiper>
>           <div>Test</div>
>         </Swiper>
>       )}
>     </>
>   );
> };
> 
> export default Index;
> ```
> 
> Reference : [Stackoverflow answer](https://stackoverflow.com/a/72318597/9851444)

Works perfect in Next.JS!!! Thanks
