### ISSUE TITLE
Swiper Element breaks touch events

### ISSUE THREAD

**Issue by Paso** [nolimits4web/swiper#6450]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/Tattoo4861/pen/eYLvwjO

### Bug description

When using Swiper Element all touch events on the page are broken. Swiper takes over touch and pointer events and re-emits a invalid touchStart event that is missing many expected attributes, such as TouchEvent.touches (see https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event).

In the reproduction codepen we listen to touchStart which should have a touches attribute. When loading swiper the event is missing touches (among other things). If one removes the swiper script-tag the event works as expected again.

The code that is responsible for this is:
 1. https://github.com/nolimits4web/swiper/blob/2533493de8cb776a8965096f021cddfdb7d088b8/src/core/events/onTouchStart.js#L141
 2. https://github.com/nolimits4web/swiper/blob/2533493de8cb776a8965096f021cddfdb7d088b8/src/core/events/index.js#L22

Swiper should
 1. not create events does not exist, such as touch-events from pointer-events
 3. if emitting a touchStart event make sure it is a valid TouchEvent

### Swiper version

9

### Platform/Target and Browser Versions

Win10+Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Paso** [comment]
Why was it closed? It is clearly a bug that prevents swiper from being used together with other libraries that listens to touch events (such as MUI).

**Comment by tulies** [comment]
Yes, I need to touch events on Android 5. x/6. x。Touch Events is not supported。

**Comment by ferhado** [comment]
I have the same issue.
Adding pointer-events: none; to the elements inside swiper-slide solves the issue but isn't ideal for clickable content:

```css
swiper-slide > * {
  pointer-events: none;
}
```
