### ISSUE TITLE
Pagination, loop, centeredSlides, and slidesPerView - Not always loading prev and next slides

### ISSUE THREAD

**Issue by Bimmr** [nolimits4web/swiper#6451]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/Bimmr/ta0zn215/3/

### Bug description

- If you use Pagination and to go to slide 4, it doesn't load the next image
- If you use Pagination and to go to slide 5, it loops backwards and doesn't load the previous slide
- If you use the navigation and click next to get to slide 6, then use pagination to go to slide 2 it doesn't load the previous slide

### Expected Behavior

Load the previous and next slides to be seen with slidesPerView and centeredSlides. By changing loopedSlides to something like 3 it does start to perform differently but still doesn't always load the previous and next slides

### Actual Behavior

It looks like it's not adding the previous slide or next slide for loop when jumping around slides.

### Swiper version

9.1.0

### Platform/Target and Browser Versions

Microsoft Edge Version 110.0.1587.57

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Fausto-Payano-Axomic** [comment]
> ### Check that this is really a bug
> * [x]  I confirm
> 
> ### Reproduction link
> https://jsfiddle.net/Bimmr/ta0zn215/3/
> 
> ### Bug description
> * If you use Pagination and to go to slide 4, it doesn't load the next image
> * If you use Pagination and to go to slide 5, it loops backwards and doesn't load the previous slide
> * If you use the navigation and click next to get to slide 6, then use pagination to go to slide 2 it doesn't load the previous slide
> 
> ### Expected Behavior
> Load the previous and next slides to be seen with slidesPerView and centeredSlides. By changing loopedSlides to something like 3 it does start to perform differently but still doesn't always load the previous and next slides
> 
> ### Actual Behavior
> It looks like it's not adding the previous slide or next slide for loop when jumping around slides.
> 
> ### Swiper version
> 9.1.0
> 
> ### Platform/Target and Browser Versions
> Microsoft Edge Version 110.0.1587.57
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
> * [x]  Read the [docs](https://swiperjs.com/swiper-api).
> * [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
> * [x]  Make sure this is a Swiper issue and not a framework-specific issue
> 
> ### Would you like to open a PR for this bug?
> * [ ]  I'm willing to open a PR

A member of my team experienced this bug earlier today. We can confirm that it is active in 9.1.0.

**Comment by sumshare** [comment]
+1， it works well at 8.4.4 but fail in 9.1.0

**Comment by shaunsama** [comment]
Add more slides, it works.

**Comment by msobkyy** [comment]
still not working in 11.0.3

**Comment by Bimmr** [comment]
> still not working in 11.0.3

They marked it fixed back in April, but never actually fixed it. I've since moved forward just not using it...

**Comment by hamzaejaz787** [comment]
I have the same issue

**Comment by marcincyboran** [comment]
Same...

**Comment by michaelbourne** [comment]
Still an issue in 11.1.7.

`loop` combined with `centeredSlides` will leave a gap at the end of the slides (depending on the direction of travel) before rendering in the next slide.

https://jsfiddle.net/p3Lk91c8/2/
