### ISSUE TITLE
Slide failed when custom width and infinity loop in react only right way.

### ISSUE THREAD

**Issue by PeterJSung** [nolimits4web/swiper#6453]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/awesome-mclaren-9rgm5q?file=/src/App.tsx

### Bug description

i have swiper with dynamic width and infinity loop. also i already set loopedSlides. 

I made a nice swiper with a fixed width

The problem is that the slider in the left direction works without problems, but in the case of the slider in the right direction, sliding does not work after a certain index.

this is gif of my sandbox link.
left direction
![left](https://user-images.githubusercontent.com/14996546/222604410-c40f9547-ec26-47e4-828a-b5e6b6c9713b.gif)

Everything looks good and there are no issues.

but, in right direction
![right](https://user-images.githubusercontent.com/14996546/222604505-0dee4c7d-5f94-4105-aa4f-a3020c493c93.gif)
A few slides are successful, but after that it doesn't work.

Maybe I'm using it in the wrong way?  Thanks a lot

### Expected Behavior

slide correctly right

### Actual Behavior

Sliding from a specific index fails.

### Swiper version

9.1.0

### Platform/Target and Browser Versions

chrome in mac os

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by dottodot** [comment]
I'm seeing the same issue, seems to be when slidesPerView is set to anything other than 1

**Comment by martinkosmela** [comment]
Same issues occured to me using latest version of Swiper

**Comment by nolimits4web** [comment]
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one
