### ISSUE TITLE
Blank slides after few swipes with virtual slides and custom renderExternal

### ISSUE THREAD

**Issue by snimavat** [nolimits4web/swiper#6454]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

For swiper element : https://codesandbox.io/p/sandbox/frosty-rgb-cgkc94
For swiper core : https://codesandbox.io/p/sandbox/adoring-violet-r8lbqu

### Bug description

When using virtual slider with renderExternal and using vueJS to render the slides
Initial few slides are visible, and works fine, but after few swipes, slides goes blank even though the slides exists in dom.

Also 
- the space between the slides starts acting weird
- setting `initialSlide` doesnt work

### Expected Behavior

- Expect to slide till the end of the slides, and have each slide display properly as user swipe from slide to slide
- Expect to honour `initialSlide` : renderExternal should pass. the slides from `renderExternal` in data.slides so that vuejs can render it from the given slide number

### Actual Behavior

Slides becomes invisible after few swipes

### Swiper version

"^9.0.5"

### Platform/Target and Browser Versions

macOS firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by snimavat** [comment]
If this is not a bug, and renderExternal needs to be implemented differently, thn we definitely need an example with any of the popular framework so that users know how is it supposed to be implemented.

**Comment by snimavat** [comment]
Looks like it is the problem with `transform: translate3d` on swiper-wrapper
where it calculated wrong

**Comment by Smilefounder** [comment]
Yes, facing the same issue.

**Comment by Smilefounder** [comment]
I found the way to fix the issue by:

For vertical:

```
<li class="slideItem swiper-slide" style={`top: ${offset}px`}>
...
</li>
```
For default:

```
<li class="slideItem swiper-slide" style={`left: ${offset}px`}>
...
</li>
```

**Comment by andrei-gheorghiu** [comment]
It's not a bug. You're not assigning `swiperOpts` properly. See my answer [here](https://stackoverflow.com/a/75747601/1891677).

**Comment by snimavat** [comment]
@andrei-gheorghiu Your example renders all the slides initially, doesnt seem to be rendering slides using renderExternal. I can comment renderExternal in ur example and still it displays slides just fine.

See 
<img width="915" alt="Screenshot 2023-03-15 at 10 42 54 PM" src="https://user-images.githubusercontent.com/623295/225388883-bb4b0d5d-1566-42cf-ad30-6bd20d6b4687.png">

**Comment by snimavat** [comment]
@Smilefounder couldnt get tht working either with swiper element

**Comment by andrei-gheorghiu** [comment]
You're right. Vue and Swiper seem to trip each other over rendering the slides. I tried using `renderSlide` function and not provide any initial slides in DOM, without much success.

**Comment by snimavat** [comment]
The problem is with calculation of `translate3d` for slides as i mentioned above

**Comment by andrei-gheorghiu** [comment]
Not sure if this helps, but I was able to achieve the functionality you seem to be after using Swiper's vue components: https://codesandbox.io/p/sandbox/bitter-moon-e49yyr?file=%2Fsrc%2FApp.vue

**Comment by snimavat** [comment]
Swiper's vue component works, but that is deprecated and swiper docs recommends using swiper element or swiper core
I wanted to use swiper element

**Comment by nolimits4web** [comment]
Each slide must have a unique `key` + correct `data-swiper-slide-index` is required. Here is the working example https://codesandbox.io/p/sandbox/throbbing-star-180wet?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A56%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A56%7D%5D

**Comment by andrei-gheorghiu** [comment]
> Each slide must have a unique `key` + correct `data-swiper-slide-index` is required. Here is the working example https://codesandbox.io/p/sandbox/throbbing-star-180wet?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A56%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A56%7D%5D

Thanks for that, Vladimir. Any idea how to make `initialSlide` work? Should it be asked as a separate issue?

**Comment by andrei-gheorghiu** [comment]
@nolimits4web 

I know you wrote it and accept your answer as such. 
Curiously enough, though, it looks like it's the `:left` prop that makes it work, not `:data-swiper-slide-index`. 
Otherwise [this wouldn't work](https://codesandbox.io/p/sandbox/jovial-wind-4hhzvl?file=%2Fsrc%2FApp.vue), would it?

**Comment by snimavat** [comment]
@nolimits4web have u noticed another bug. In ur example above, when you slide reverse (eg slide from 1 to six, and thn slide back from 6 to 1) you will see the "space between slides" is broken.

**Comment by kama1i** [comment]
slidesPerView="auto"
worked for me
