### ISSUE TITLE
Can't run npm run build with Swiper in Nuxt 3 - Rollup failed to resolve import "swiper/vue"

### ISSUE THREAD

**Issue by Kev2d** [nolimits4web/swiper#6456]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/nolimits4web/swiper/issues/new?assignees=&labels=Vue&template=vue_issue.yml

### Bug description

0

I am using Swiper for Vue and It is working in my project which is fine but as I am trying to build my project I am getting this error.

 ERROR  [vite]: Rollup failed to resolve import "swiper/vue" from ".../components/Testimonials/TestimonialsCarousel.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (node_modules/vite/dist/node/chunks/dep-ca21228b.js:44792:19)
  at onwarn (node_modules/vite/dist/node/chunks/dep-ca21228b.js:44562:13)
  at Object.onwarn (node_modules/rollup/dist/es/shared/node-entry.js:24922:13)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:23605:26)
  at node_modules/rollup/dist/es/shared/node-entry.js:23565:26
I've tried to add this to my nuxt.config.ts but this doesn't work

  build: {
    transpile: ['swiper']
  }
I also tried this to add this to my nuxt.config.ts. After this I could build but I am getting a new error in my localhost.

 vite: {
    build: {
      rollupOptions: {
        external: /^swiper/,
      },
    },
  },
The error I am getting

Cannot find package 'swiper' imported from /mydomain/.output/server/chunks/app/_nuxt/index-2fdde020.mjs
Has anyone had similar problem using Swiper for Vue 3 and Nuxt 3?

Cheers

### Expected Behavior

I am expecting to build my project

### Actual Behavior

I cannot built because of rollupOptions.external

### Swiper version

9.0.5

### Platform/Target and Browser Versions

All of them

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
address this question to Nuxt/Rollup/Vite
