### ISSUE TITLE
Swipes are broken for slides with 'overflow: scroll'  

### ISSUE THREAD

**Issue by Ushlerdop** [nolimits4web/swiper#6458]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-default-forked-un577x?file=%2Fsrc%2Fstyles.css

### Bug description

If I add an `overflow: scroll;` rule to slide (or any wrapper-element inside `.swiper-slide`), the touch swipes stop working

### Expected Behavior

the `overflow: scroll;` doesn't affect the ability to swipe using touch screen

### Actual Behavior

the `overflow: scroll;` breaks the ability to swipe using touch screen

### Swiper version

9.1.0

### Platform/Target and Browser Versions

Windows 10, Chrome 110 / iOS Safari14 / iOS Safari 16 / Android 13 Chrome 110

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by paulocheque** [comment]
This happens without React too. It appears to be a bug in the Core. I removed the overflow and it worked fine, but my scrolling stop working.

**Comment by gaollard** [comment]
i meet the same problem...

**Comment by nolimits4web** [comment]
Solution here https://github.com/nolimits4web/swiper/issues/6363
