### ISSUE TITLE
Ipad air safari browser switch stuck

### ISSUE THREAD

**Issue by rick-liruixin** [nolimits4web/swiper#6465]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.balenciaga.cn/categories/women/rtw.html

### Bug description

safari browser switch stuck
Model: Ipad air fifth generation
Software version: 15.6
Online link: 
https://www.balenciaga.cn/categories/women/rtw.html
https://www.swiper.com.cn/demo/index.html

### Swiper version

v8.4.7

### Platform/Target and Browser Versions

safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
v8 is not maintained anymore
