### ISSUE TITLE
Provide Typescript definition for Element

### ISSUE THREAD

**Issue by chrisgwgreen** [nolimits4web/swiper#6466]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

N/A

### Bug description

According to https://swiperjs.com/react, it is recommended to work with Swiper Element vs Swiper React as it's likely to be removed in the future. However, there are no typescript definitions causing web components e.g. `<swiper-container>` to fail.  

### Swiper version

9.1.0

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by SanderCokart** [comment]
Yes we need this!

**Comment by hu-tu-yi-shi** [comment]
same here

**Comment by markcnunes** [comment]
I see there is a TS definition but the Element is a simple HTMLElement.

https://github.com/nolimits4web/swiper/blob/master/src/element/swiper-element.d.ts

Will it be extended with the Swiper kebab-case attributes?

See below the workaround for React if anyone is blocked because of this missing type definition, however, have in mind I don't fully know these types and I could be wrong about this type declaration but it has worked fine for me so far.

```tsx
import { ReactNode, RefObject, useRef } from 'react';
import Swiper, { SwiperOptions } from 'swiper';
import { register } from 'swiper/element/bundle';
import { SwiperSlideProps } from 'swiper/react';

/**
 * When you import Swiper custom elements from node modules, we need to manually register them.
 * It should be done only once and it registers Swiper custom elements globally.
 */
register();

type Kebab<
  T extends string,
  A extends string = '',
> = T extends `${infer F}${infer R}`
  ? Kebab<R, `${A}${F extends Lowercase<F> ? '' : '-'}${Lowercase<F>}`>
  : A;

/**
 * Helper for converting object keys to kebab case because Swiper web components parameters are available as kebab-case attributes.
 * @link https://swiperjs.com/element#parameters-as-attributes
 */
type KebabObjectKeys<T> = {
  [key in keyof T as Kebab<key & string>]: T[key] extends Object
    ? KebabObjectKeys<T[key]>
    : T[key];
};

/**
 * Swiper 9 doesn't support Typescript yet, we are watching the following issue:
 * @link https://github.com/nolimits4web/swiper/issues/6466
 *
 * All parameters can be found on the following page:
 * @link https://swiperjs.com/swiper-api#parameters
 */
type SwiperRef = HTMLElement & { swiper: Swiper };

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'swiper-container': SwiperContainerAttributes;
      'swiper-slide': SwiperSlideAttributes;
    }

    interface SwiperContainerAttributes extends KebabObjectKeys<SwiperOptions> {
      ref?: RefObject<SwiperRef>;
      children?: ReactNode;
    }
    interface SwiperSlideAttributes extends KebabObjectKeys<SwiperSlideProps> {}
  }
}

const Carousel = () => {
  const carouselRef = useRef<SwiperRef>(null);

  return (
    <div>
      <swiper-container ref={swiperRef} slides-per-view={2}>
        <swiper-slide>Slide 1</swiper-slide>
        <swiper-slide>Slide 2</swiper-slide>
        <swiper-slide>Slide 3</swiper-slide>
      </swiper-container>
      <button onClick={() => swiperRef.current?.swiper.slidePrev()}>
        Previous
      </button>
      <button onClick={() => swiperRef.current?.swiper.slideNext()}>
        Next
      </button>
    </div>
  );
};
`;
```

**Comment by ser-shant** [comment]
dow not work for me either, and seem to be a blocker so far as it fails on compilation stage to find swiper-container. Has someone solved that?

**Comment by sean-perkins** [comment]
It would be great if this was provided by the library directly, but here is the type definition if you want to roll your own in the interim:

`swiper.d.ts`

```tsx
import React from "react";

import type { SwiperSlideProps, SwiperProps } from 'swiper/react';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "swiper-container": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement> & SwiperProps,
        HTMLElement
      >;
      "swiper-slide": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement> & SwiperSlideProps,
        HTMLElement
      >;
    }
  }
}
```

In your `tsconfig.json` update the `include` to contain the path to this custom type definition:
```
{
  "compilerOptions": {
    ...
  },
  "include": ["src", "swiper.d.ts"],
```

This will fix type warnings in JSX/React and provide intellisense features:

![CleanShot 2023-03-21 at 15 44 35](https://user-images.githubusercontent.com/13732623/226723590-34c64e2a-a03b-46fa-b0da-7a9391e3d536.png)

**Comment by prodbygoss** [comment]
> 

Thank you for this. This worked well to clear out most of my errors.
Any ideas to account for this?

<img width="507" alt="CleanShot 2023-03-24 at 18 42 25@2x" src="https://user-images.githubusercontent.com/82852973/227679060-863bcd50-f26d-497b-bf20-c091ec091779.png">

I am iterating over an array and rendering the `swiper-slide` components.

**Comment by oidualc** [comment]
> According to https://swiperjs.com/react, it is recommended to work with Swiper Element vs Swiper React as it's likely to be removed in the future. However, there are no typescript definitions causing web components e.g. <swiper-container> to fail.

Yes, this is not ideal at all, it's probably best to remove the warning in the documentation until this issue is resolved, otherwise the suggested action to migrate to Swiper Element leads to a sub-optimal developer experience in a context that is super widely adopted, React + TypeScript. Meanwhile of course, Swiper React shouldn't be removed.

**Comment by sshmaxime** [comment]
@sean-perkins With your code i manage to get the typings right, I'm no longer getting Typescript issues so thanks for that. That being said, I'm now having issues with setting parameters to Swiper's component. With your solution the types given are `slidersPerView` however when set that doesn't work but it's instead `slides-per-view`. Any solution for that ?

**Comment by monsty** [comment]
> ```tsx
> iperRef.current?.swiper.sl
> ```

Pretty bad if there is no SSR compatibility...

**Comment by reslear** [comment]
@sean-perkins for Vue with volar?

**Comment by marcelo-albuquerque** [comment]
> It would be great if this was provided by the library directly, but here is the type definition if you want to roll your own in the interim:
> 
> `swiper.d.ts`
> 
> ```tsx
> import React from "react";
> 
> import type { SwiperSlideProps, SwiperProps } from 'swiper/react';
> 
> declare global {
>   namespace JSX {
>     interface IntrinsicElements {
>       "swiper-container": React.DetailedHTMLProps<
>         React.HTMLAttributes<HTMLElement> & SwiperProps,
>         HTMLElement
>       >;
>       "swiper-slide": React.DetailedHTMLProps<
>         React.HTMLAttributes<HTMLElement> & SwiperSlideProps,
>         HTMLElement
>       >;
>     }
>   }
> }
> ```
> 
> In your `tsconfig.json` update the `include` to contain the path to this custom type definition:
> 
> ```
> {
>   "compilerOptions": {
>     ...
>   },
>   "include": ["src", "swiper.d.ts"],
> ```
> 
> This will fix type warnings in JSX/React and provide intellisense features:
> 
> ![CleanShot 2023-03-21 at 15 44 35](https://user-images.githubusercontent.com/13732623/226723590-34c64e2a-a03b-46fa-b0da-7a9391e3d536.png)

Perfect solution!!!

**Comment by evertjr** [comment]
It's very heartbreaking seeing Swiper deprecating react components and at the same time introducing such a massive DX downgrade, I understand the challenges of supporting many frameworks but you'd think the most popular one would get first class support... I was about to start a new project relying on Swipe but it doesn't feel safe anymore. I'll try Embla Carrousel since it's the only one just as smooth.

**Comment by SanderCokart** [comment]
You could also use an older version. And its not deprecated yet. I don't
it's prone to security issues

**Comment by e111077** [comment]
- Can it be possible for Swiper Element to use export a React definition using [`@lit-labs/react`](https://www.npmjs.com/package/@lit-labs/react)? It is not specific to Lit and works on all Web Components. It simply provides idiomatic React conveniences for Custom Elements. Additionally it is moving out of labs and into stable in early September

**Comment by notflip** [comment]
> 

Did you find a solution to get TS working with the new element version?

**Comment by HelaGone** [comment]
In my case I addd this to the `global.d.ts` conf file:

```
declare namespace JSX {
  interface IntrinsicElements {
    'swiper-container': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
      navigation: string;
      // Add more properties
    };
    'swiper-slide': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
      lazy: string;
      // Add more properties
    };
  }
}
```

I hope it helps

**Comment by zacswolf** [comment]
Any updates on this?

**Comment by patilanz** [comment]
news?
