### ISSUE TITLE
Tap delay after swipe

### ISSUE THREAD

**Issue by bahrynowskijakub** [nolimits4web/swiper#6467]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/mvjbdm

### Bug description

On mobile (testing on 4 different devices, both Android and IOS and Chrome DevTools responsive mode) the delay before click event mentioned here: https://github.com/nolimits4web/swiper/issues/3045 seems to still persist. 

### Expected Behavior

No delay between swiping and clicking navigation button.

### Actual Behavior

After swiping, navigation buttons don't work for a while.

### Swiper version

9.1.0

### Platform/Target and Browser Versions

Android, IOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by m345054** [comment]
This also seems to occur in Chrome DevTools when you have a mobile device selected. After you swipe click events won't fire for a few miliseconds.

**Comment by franckdsf** [comment]
@m345054, I also found this issue when upgrading from 8.4.6 to 9.2.3.
I will keep upgrading from 8.4.6 to find when the bug started occurring.

**Comment by franckdsf** [comment]
Update: 
Couldn't really test above 8.4.7 because version 9.0.0+ brings NextJS error until version 9.1.1 that already has this bug occurring.
