### ISSUE TITLE
Module not found: Error: Can't resolve './images/index.js'

### ISSUE THREAD

**Issue by 372598420** [nolimits4web/swiper#6468]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

/

### Bug description

When building, this problem will occur. How to solve it?

### Swiper version

8.4.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
V8 is not maintained anymore
