### ISSUE TITLE
Lazy loading images not working at all 

### ISSUE THREAD

**Issue by ErikParso** [nolimits4web/swiper#6470]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

lazy loading demo not working

### Bug description

Lazy loading of images in not working. I am using version 9.1.0 and if I understand correctly Lazy module is not supported in this version also a cannot set lazy property to true it does not exist. So I have to rely only on loading property on img element but its not working. All images in gallery are loaded immediately. 

Also demo in sandbox is outdated and not working

### Swiper version

9.0.0

### Platform/Target and Browser Versions

Chrome, Firefox pretty much everywhere 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I see it is working here https://swiperjs.com/demos/370-lazy-load-images/core
