### ISSUE TITLE
loop mode and autoplay stops on last slide

### ISSUE THREAD

**Issue by in-session** [nolimits4web/swiper#6471]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-loop-autoplay-error-6ux6k4?file=/index.html

### Bug description

We have just noticed that the loop mode and autoplay from version 9 is causing problems. As soon as both areas are active, the slide after the last item is not prefixed. V8 works well.

### Swiper version

9.1.0

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by fjaeker** [comment]
I also just encountered the problem. Then found the following note in the "Migration Guide to Swiper 9":

"It comes with new limitation. Amount of slides in loop mode should be at least 2x of slidesPerView value."

If you take this into account, it works.

**Comment by in-session** [comment]
thanks in fact that fixes the problem but is also really not practical. If for example 4 slidesPerView in the loop with 6 pieces would not work at all. Here it would indeed make more sense to copy all slides until the minimum is met. So at 6 slides clone to 12 to exceed the number of 8.

**Comment by in-session** [comment]
@nolimits4web 
Wouldn't it be better to say clone all slides until the double of slidesPerView is reached?

**Comment by nolimits4web** [comment]
It states in docs about this new requirement https://swiperjs.com/swiper-api#param-loop

**Comment by in-session** [comment]
@nolimits4web
We noticed that too, yet it's not that practical.
For example if you have 6 slides. Mobile 2 and desktop 4 so there would be no loop within the desktop.

**Comment by picobots** [comment]
Having to manually double the slides is definitely impractical. I'm reverting my projects to Swiper 8 for now. If Swiper 9 looping works requires 2x slidesPerView, I think there should be a Swiper option to automatically double (or triple) all of the slides to reach the necessary minimum count, for example:

```
{
    // This will automatically duplicate slides to reach the minimum slide count necessary for Swiper looping
    forceLoop: true
}
```

**Comment by cseeger** [comment]
This limitation renders `loop` unusable. Arbitrary slide count needs to be considered.

**Comment by miguelgisbert** [comment]
I've make loop: true work using double swiper-slides than slidpesPerView as said but I have the problem that the looped slides take a bit to load and create a white space on the carousel. Anybody has fixed also that? 

Thanks a lot!

**Comment by miguelgisbert** [comment]
Sorry to say that, but I solve it very easy and very quick with owl-carousel

**Comment by gleenk** [comment]
Still not working for me, v 9.4.1.
Imported Autoplay module, 2 slides and loop true

**Comment by tuhuynhnek** [comment]
> Still not working for me, v 9.4.1. Imported Autoplay module, 2 slides and loop true.
> 
> It works on 8.4.7

thank you in advanced, I spent almost 3 day to fix that bug, really dont know why nobody don't get that, that's a serious bug to make Swiper really very impractical. Hope to see Swiper team fix it, and now I downgrade the version to 8.4.7

**Comment by prismspecs** [comment]
Confirming this is not broken in 8.4.7

**Comment by dmudro** [comment]
as many others, we struggled with the new loop and eventually downgraded Swiper to v8 as a temp fix. downgrading a lib is usually not the best long term strategy but seemed like the only option.

now with Swiper v10 we are falling further behind. in React, the strict mode does not work with v8.

I do not see us manually duplicating slides to meet the "new loop introduced in v9". this is a wrong design. will probably migrate away.
