### ISSUE TITLE
Diagonal Swipes 

### ISSUE THREAD

**Issue by selcuk-sahin** [nolimits4web/swiper#6478]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/

### Bug description

on iOS devices (tested with Safari & Brave), swiping horizontally also triggers a vertical scroll. 
This was not the case with Swiper version ^8. 

It seems like the transition ends immediately.
Please check the screen recordings.

### Expected Behavior

I should be either swiping horizontally or scrolling vertically, but not both. 
Here's an example from macOS Brave (Chromium)

https://user-images.githubusercontent.com/71325531/224348667-cc139c64-19ff-451a-8bce-facd328f027c.mov

### Actual Behavior

When I scroll slightly vertically, the swiper.js slide transition starts but almost immediately ends. From there, I start to scroll vertically. 

https://user-images.githubusercontent.com/71325531/224347648-757377b4-239d-4a22-95f8-09309bd7f243.mp4

### Swiper version

9.1.0

### Platform/Target and Browser Versions

ios, Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by selcuk-sahin** [comment]
> Are you on iOS 16.2?

I'm on iOS 16.1.1

**Comment by nolimits4web** [comment]
Try on 16.2

**Comment by selcuk-sahin** [comment]
> Try on 16.2

Yes, the issue persists on iOS 16.2 and 16.3 too.

**Comment by DzmitryShamal** [comment]
15.5 also

**Comment by dkornilove** [comment]
ios 15.7.9
v.10.2.0
the issue persists

**Comment by epetousis** [comment]
Swiper 11.0.4 works near perfectly for me. I managed to trigger one single diagonal swipe but I cannot replicate it no matter how much I try.
