### ISSUE TITLE
when I use autoplay.stop()，the transition don‘t stop immediately

### ISSUE THREAD

**Issue by ru8lq0005** [nolimits4web/swiper#6481]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/

### Bug description

 I want to achieves a effect，let some images can infinite swipe with no time out。so I set
```
options:{
                    loop : true,
                    speed : 5000,
                    direction: 'vertical',
                    freeMode: true,
                    autoplay: {
                        delay: 0,
                        disableOnInteraction: true, 
                        reverseDirection:true,
                        waitForTransition:false 
                    },
}
```
```
this.swiper.el.onmouseover = ( )=>{
                    this.swiper.autoplay.stop();
                    console.log("stopAutoPlay");
                }
```
and set these css property:
```
.swiper-wrapper {
            -webkit-transition-timing-function: linear !important;
            -moz-transition-timing-function: linear !important;
            -ms-transition-timing-function: linear !important;
            -o-transition-timing-function: linear !important;
            transition-timing-function: linear !important;
}
```
But it's working strange.when I hover the images,it always wait some seconds for the transition end.It can't stop immediately.

### Expected Behavior

When I used autoplay.stop(),the transition also stop immediately.

### Swiper version

9.1.0

### Platform/Target and Browser Versions

Edge 106

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how transitions work. You can manually calculate current ftranslate and overwrite it

**Comment by ablupi** [comment]
I also met this problem, may I ask if you finally solved it? If you have solved it, please teach me.

**Comment by ru8lq0005** [comment]
> I also met this problem, may I ask if you finally solved it? If you have solved it, please teach me.

国人啊，那我就中文回答了，亏我还写了一大堆英文，才看见你头像。。。
我最终还是放弃用swipejs去做这个东西了，我的需求是实现一个无限匀速滚动的图片列表，然后因为有鼠标停留则立即停止滚动的要求，所以才提了这个issue，我最后是用css写的，直接animate滚动两组拼接的列表，来实现双方向列表外都不会出现留白。浮动的时候触发hover，然后给animation-play-state暂停就完事了，其实没太复杂，但不知道你是不是类似的要求，我的qq 137158095，如果有需要 可以加我 我给你看下实现效果。

**Comment by JarvisChao** [comment]
This is how I solved it.

```typescript
let duration: number;
let distanceRatio: number;
const stopAutoplay = () => {
  // Stop slide at current translate.
  swiper.setTranslate(swiper.getTranslate());

  // Calculating the distance between current slide and next slide.
  // 0.3 is equal to 30% distance to the next slide.
  distanceRatio = Math.abs((swiper.width * swiper.activeIndex + swiper.getTranslate()) / swiper.width);

  // The duration that playing to the next slide
  duration = swiper.params.speed! * distanceRatio;
  swiper.autoplay.stop();
};

let startTimer: ReturnType<typeof setTimeout>;
const startAutoplay = (delay = duration) => {
  if (startTimer) clearTimeout(startTimer);
  startTimer = setTimeout(() => {
    swiper.autoplay.start();
  }, delay);
};

const isPlaying = ref(true);
let clickable = true;
const handleTogglePlay = () => {
  if (!clickable) return;
  clickable = false;

  if (isPlaying.value) stopAutoplay();
  else {
    const distance = swiper.width * swiper.activeIndex + swiper.getTranslate();

    // Avoid distance that is exactly 0
    duration = distance !== 0 ? duration : 0;
    swiper.slideTo(swiper.activeIndex, duration);
    startAutoplay();
  }
  isPlaying.value = !isPlaying.value;
  setTimeout(() => { clickable = true; }, 200);
};
```

**Comment by kam1kazy** [comment]
@JarvisChao (づᴗ _ᴗ)づ♡

**Comment by Antoanyabo** [comment]
> This is how I solved it with Swiper 11
> 
> ```ts
> let duration: number;
> let distanceRatio: number;
> const stopAutoplay = () => {
>   // Stop slide at current translate.
>   swiper.setTranslate(swiper.getTranslate());
> 
>   // Calculating the distance between current slide and next slide.
>   // 0.3 is equal to 30% distance to the next slide.
>   distanceRatio = Math.abs((swiper.width * swiper.activeIndex + swiper.getTranslate()) / swiper.width);
> 
>   // The duration that playing to the next slide
>   duration = swiper.params.speed! * distanceRatio;
>   swiper.autoplay.stop();
> };
> 
> let startTimer: ReturnType<typeof setTimeout>;
> const startAutoplay = (delay = duration) => {
>   if (startTimer) clearTimeout(startTimer);
>   startTimer = setTimeout(() => {
>     swiper.autoplay.start();
>   }, delay);
> };
> 
> const isPlaying = ref(true);
> let clickable = true;
> const handleTogglePlay = () => {
>   if (!clickable) return;
>   clickable = false;
> 
>   if (isPlaying.value) stopAutoplay();
>   else {
>     const distance = swiper.width * swiper.activeIndex + swiper.getTranslate();
> 
>     // Avoid distance that is exactly 0
>     duration = distance !== 0 ? duration : 0;
>     swiper.slideTo(swiper.activeIndex, duration);
>     startAutoplay();
>   }
>   isPlaying.value = !isPlaying.value;
>   setTimeout(() => { clickable = true; }, 200);
> };
> ```

Greate . It works

**Comment by JarvisChao** [comment]
> This is how I solved it with Swiper 11
> 
> ```ts
> let duration: number;
> let distanceRatio: number;
> const stopAutoplay = () => {
>   // Stop slide at current translate.
>   swiper.setTranslate(swiper.getTranslate());
> 
>   // Calculating the distance between current slide and next slide.
>   // 0.3 is equal to 30% distance to the next slide.
>   distanceRatio = Math.abs((swiper.width * swiper.activeIndex + swiper.getTranslate()) / swiper.width);
> 
>   // The duration that playing to the next slide
>   duration = swiper.params.speed! * distanceRatio;
>   swiper.autoplay.stop();
> };
> 
> let startTimer: ReturnType<typeof setTimeout>;
> const startAutoplay = (delay = duration) => {
>   if (startTimer) clearTimeout(startTimer);
>   startTimer = setTimeout(() => {
>     swiper.autoplay.start();
>   }, delay);
> };
> 
> const isPlaying = ref(true);
> let clickable = true;
> const handleTogglePlay = () => {
>   if (!clickable) return;
>   clickable = false;
> 
>   if (isPlaying.value) stopAutoplay();
>   else {
>     const distance = swiper.width * swiper.activeIndex + swiper.getTranslate();
> 
>     // Avoid distance that is exactly 0
>     duration = distance !== 0 ? duration : 0;
>     swiper.slideTo(swiper.activeIndex, duration);
>     startAutoplay();
>   }
>   isPlaying.value = !isPlaying.value;
>   setTimeout(() => { clickable = true; }, 200);
> };
> ```

Full example of the code
https://codepen.io/jarvis73045/pen/rNgwbNJ
