### ISSUE TITLE
Loop and virtual issue for less than 4 Swiper slides

### ISSUE THREAD

**Issue by sarevok89** [nolimits4web/swiper#6487]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/elastic-banzai-e5g6b2?file=/src/App.js

### Bug description

Hi, I have a problem with using both 'loop' and 'virtual' in the latest version of Swiper. For more than 3 slides everything works as expected while for 3 or fewer I receive the `Encountered two children with the same key` React warning and the slider gets bugged. Currently, as a workaround, I conditionally add the 'virtual' mode if there are more than 3 items to be displayed but it doesn't seem to be a proper solution.

To make the code example work as expected simply add another item to the array.

### Expected Behavior

There are no warnings/errors and slides change with no issues.

### Actual Behavior

I receive React duplicated key warning, the slider gets bugged and slides disappear

### Swiper version

9.1.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by artur-pipchenko** [comment]
Hi, I have the same issue in Vue, where having `loop` with `virtual` leads to key duplication and rendering lots of copied DOM elements

**Comment by aezur** [comment]
This is still an issue in v11.1.7 using react. Everything works fine with >3 items. Duplicate key with <=3 items.

**Comment by say8425** [comment]
```tsx
const totalCount = 10;
const loop = true;
const virtual = true;

return (
  <Swiper
    loop={loop}
    virtual={virtual ? totalCount >= 4 : false}
  >
    // everything
  </Swiper>
)
```

Even if both loop and virtual are true, the total number of slides must be at least 4 for virtual to be true.
