### ISSUE TITLE
Swiper Element - Data Breakpoints error

### ISSUE THREAD

**Issue by okzea** [nolimits4web/swiper#6488]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/okzea/heqodu1z/5/

### Bug description

Hey there, I'm trying to setup breakpoints in web component attributes but I'm having this error:
![image](https://user-images.githubusercontent.com/10658943/222433007-880f535e-d250-44ed-80b9-bf1da24567ee.png)

Here's the html snippet:
`<swiper-container slides-per-view="1" breakpoints="{768: {slidesPerView: 3}}">`

Does anyone have an idea of what I'm doing wrong or if that's just a bug?

Thanks 🙏

### Swiper version

9.1.0

### Platform/Target and Browser Versions

all recent browsers / platforms

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You need to use params as props https://swiperjs.com/element#parameters-as-props

**Comment by Pt4r** [comment]
@nolimits4web would you mind giving an example on how to give the breakpoint parameter as a property in Angular?

I've tried the following:
`
breakpoints-1200-slides-per-view="4"
`
`
breakpoints="1200:{slidesPerView:4}"
`
`
breakpoints="1200:{slides-per-view:4}"
`
