### ISSUE TITLE
Swiper Element + loop=“true” + slides-per-view=“auto” flickering

### ISSUE THREAD

**Issue by ThinkingAbout** [nolimits4web/swiper#6489]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/fiurboy/pen/ExevaBW

### Bug description

<swiper-container id="swiper-1" loop="true" slides-per-view="auto"> Loop mode not working properly with slides per view "auto" and variable width slides.

### Expected Behavior

No jumps or flickerings are expected;

### Actual Behavior

Once the user drag to the "loop point" the carousel jumps/flickr to the wrong position.
It is even more visible with relative units; 

Some flickering can happen even while dragging before reach the "loop point".

### Swiper version

https://cdn.jsdelivr.net/npm/swiper@9/swiper-element-bundle.min.js

### Platform/Target and Browser Versions

MacOS Chrome 111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Slides get rearranged in DOM, so the `swiper-slide:nth-of-type(odd)` rule won't work as expected here

**Comment by ThinkingAbout** [comment]
Hi @nolimits4web ,
sorry but I am totally stuck since 2 weeks, please clarify me if it is a CSS problem of my implementation or if is not possible to obtain a properly working `<swiper-element>` with variable width `<swiper-slide>`, `loop: true` and `slidesPerView: "auto"` (I added inline with to my reproduction but the flickering is still there); 
Thank you!
