### ISSUE TITLE
In version 8.2.2, when running unit tests Cannot find "swiper/css" 

### ISSUE THREAD

**Issue by mrfour44** [nolimits4web/swiper#6492]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/

### Bug description

Using swiper in React, you can npm run start, but when running unit tests, error "Cannot find module 'swiper/css'"
The unit tests used react-testing-library. Jest has configured moduleNameMapper as "identity-obj-proxy". 
Besides reducing the swiper version, is there any way I can solve it? thank you！

### Swiper version

8.2.2

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
v8 is not maintained anymore
