### ISSUE TITLE
Pagination/loop jump bug

### ISSUE THREAD

**Issue by lukecharle** [nolimits4web/swiper#6504]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

N/A

### Bug description

FYI I tried creating a codesandbox but it wasn't able to save files to show.

You can view it on the following [link](https://luke-theme-dev.myshopify.com/) though (password is 'luke') 

Anyway, on first load, if I click on a pagination bullet it just jumps and doesn't transition to the slide, aswell as not activating that clicked bullet. Upon second click it will then transition to the slide and the bullet will become active.

It appears this happens when using `loop: true`

I have screen recorded:

https://user-images.githubusercontent.com/115987937/226101716-d23181e3-f006-48a1-a526-1580b0b8fd0a.mp4

I have used the following config for the pagination object (with tailwind classes on)

```
{
  clickable: true,
  bulletClass:
    'w-2.5 h-2.5 bg-gray-300 rounded-full cursor-pointer active:bg-gray-600',
  bulletActiveClass: 'active',
  el: this.querySelector('[data-carousel-pagination]'),
  renderBullet: (index, className) => {
    return `
      <button class="${className}">
        <span class="sr-only">Slide ${index + 1}</span>
      </button>
    `
  }
}
```

### Expected Behavior

Swiper should transition to the appropiate slide and the bullet should receive the active class on first click

### Actual Behavior

Swiper jumps to the slides and doesn't give the selected bullet the class.

### Swiper version

9.1.1

### Platform/Target and Browser Versions

macOS Ventura 13.0.1 (22A400) / Firefox 110.0.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate 6472
