### ISSUE TITLE
Controller controling multiple swipers - wrong calculation

### ISSUE THREAD

**Issue by mroz123** [nolimits4web/swiper#6506]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-multiple-swipers-forked-dcg4xm?file=%2Findex.html&selection=%5B%7B%22endColumn%22%3A29%2C%22endLineNumber%22%3A65%2C%22startColumn%22%3A29%2C%22startLineNumber%22%3A65%7D%5D

### Bug description

When one swiper with controller module controls multiple swipers with different widths it calculates their progress wrong.

I believe the problem is in https://github.com/nolimits4web/swiper/blob/8f48d7f3df9a70801527afaf1df73fc6402391f1/src/modules/controller/controller.js#L62

which saves the interpolation values based on the dimensions of the first controlled swiper which can't be used for another one with different dimensions because it messes up the progress calculation. 

I believe it should be enough to remove the condition on line 62 which would allow the swiper.controller.spline to regenerate for every controlled swiper and allow for correct progress calculation. 

It is not really very clear from comment in the code why this condition was added so I am not sure if it won't break anything else.

### Expected Behavior

When the progress of the swiper with controller is 0.5, the progress of every controlled swiper should also be 0.5.

### Actual Behavior

When the progress of the controlling swiper is 0.5 , the progress of the first controlled swiper is correct but the progress of other swipers is based on the size of the first one so the progress values are wrong which causes them to move with wrong speed.

### Swiper version

9.1.0

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Thank you for the tip! Fixed now
