### ISSUE TITLE
TouchMove does not run on Safari 11: slider is not draggable

### ISSUE THREAD

**Issue by zberno** [nolimits4web/swiper#6510]
### Check that this is really a bug

- [x] I confirm

### Reproduction link
https://swiperjs.com/demos/010-default/core

### Bug description
When I try to drag a slider from Safari 11, the slider has not be dragged.

### Expected Behavior
When I try to drag a slider from Safari 11 with mouse or finger, the slider will be dragged, to the next/prev slide with or without followfinger.

### Actual Behavior
Instead of being dragged the text inside the slide is selected (1st demo example)

### Swiper version
9.1.1

### Platform/Target and Browser Versions
MacOS HighSierra, Safari 11.1.2 (BrowserStack)

### Validations
 
- [x] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
 
- [x] Read the [docs](https://swiperjs.com/swiper-api).

- [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

- [x]  Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ]  I'm willing to open a PR

**Comment by zberno** [comment]
Sorry, i've see now browserslist
IOS >= 13
Safari >= 13
last 5 Chrome versions
last 5 Firefox versions
Samsung >= 12

**Comment by nolimits4web** [comment]
Yes, Safari 11 is not the target browser to support
