### ISSUE TITLE
Mouse Swipe does not trigger any swiper change events

### ISSUE THREAD

**Issue by kujain** [nolimits4web/swiper#6514]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://preprod.wondercade.com/

### Bug description

I have a carousel set up on the top of the page linked a above. The text content below is updated on the`slideChangeTransitionEnd` event. But I am seeing two issues:
- the swipe action (dragging a slider across the screen) does not trigger ANY of the swiper events and so I cannot update the text content below as the slides are swiped see video 1 below). I have tried most of the events from https://swiperjs.com/swiper-api#events but none get triggered. I have a filter that changes the active slide to color, which does fire, so I know swiper knows that the active slide has changed. But no event is triggered when this happens, from what I can find. But when I use my custom previous/next buttons (the fingers), it works perfectly (see video 2 below).

- When swiping starts, the slides go off-center for some reason. Only by using the paginators, the proper snapping  works.

I have not found any discussion on this anywhere so I am recording this as a bug.

**Video 1: Showing the actual behaviour:**
https://user-images.githubusercontent.com/120631/226775511-3f3f00dd-84bb-429c-9d18-3236d61a47f8.mp4

**Video 2: showing the correct behaviour when using the previous/next buttons:**
https://user-images.githubusercontent.com/120631/226775544-5e2ebee3-dc84-4b96-8b63-907a909488f1.mp4

Here's my JS code, if helpful:
```
		const container = $('.home-grid-slider .swiper-container');
		let args = {
			spaceBetween: 0,
			init: false,
			slidesPerView: 'auto',
			centeredSlides: true,
			grabCursor:1,
			loop: false,
			autoHeight: true,
			shortSwipes: false,
			longSwipesRatio: 0.15,
			longSwipesMs: 100,
			watchSlidesVisibility: true,
			navigation: {
				nextEl: '.swiper-button-next',
				prevEl: '.swiper-button-prev',
			},
			breakpoints: {
				768:{
					autoHeight: false,
				},
				1024: {
					slidesPerView: 2,
					spaceBetween: 32,
					autoHeight: true,
				}
			}
		};

		if ( container.attr('data-loop') && container.attr('data-loop') == 'true' ) {
			args.loop = true;
			args.loopAdditionalSlides = 3
		}
		const mySwiper = new Swiper(container[ 0 ], args);

		mySwiper.init();

		// on change
		mySwiper.on('slideChangeTransitionEnd', function (event) {
			// update static desc block for gallery templates only
			if ( container.find( '.hero-overlap' ) ) {
				// get slide description
				let slider_title = container.find('.swiper-slide-active > .slide-meta .slide_link h3').html();
				let slider_label = container.find('.swiper-slide-active > .slide-meta .label').html();
				let slider_url = container.find('.swiper-slide-active > .slide-meta .slide_link').attr('href');
				let slider_description = container.find('.swiper-slide-active > .slide-meta .sub').html();
				container.parent().find('.hero-overlap .label').html( slider_label );
				container.parent().find('.hero-overlap .sub').html( slider_description );
				container.parent().find('.hero-overlap h3').html( slider_title );
				container.parent().find('.hero-overlap .slide_link').attr( 'href', slider_url );
			}
		});
```

### Expected Behavior

As the swiper action is registered, an event should fire allowing me to build an action to update the text content appropriately. 
The action gets triggered only on clicking the previous/next buttons.

### Actual Behavior

No action is triggered during mouse swiping and hence I cannot hook any action into that movement. Also, mouse swiping does not snap the active slide to the center.

### Swiper version

Swiper 8.4.7

### Platform/Target and Browser Versions

macOS Chrome 111.0.5563.64

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v8 is not maintained anymore
