### ISSUE TITLE
Pagination bullets behave strangely, with loop option

### ISSUE THREAD

**Issue by Kota-M** [nolimits4web/swiper#6518]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/wild-water-9gz8ej?file=/index.html

### Bug description

If "loop" option is true, the slider behaves strangely with clicking the pagination bullets. These things may happen (not always);

- The images slide jumpy.
- The highlighted bullet is not sync with the displayed image.
- The images are not moved with clicking one of the bullets.

I found these issues occur between version 9.0.0 and the latest (9.1.1), but it works well with ver 8.4.7.

### Swiper version

9.0.0-9.1.1

### Platform/Target and Browser Versions

Firefox 111.0.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Kota-M** [comment]
No, not yet. The strange behaviour problem has not resolved.

**Comment by electrodrel** [comment]
I have a similar issue. Initially, the pagination dots look and behave fine. Then, after the first loop, they start to shift to the left side, jumping back to the centre at the end of the loop. It looks like the calculation of the `left` offset is incorrect in the loop mode. 

https://user-images.githubusercontent.com/3395183/232162269-edfe71e1-53b8-453c-a399-d495abecce6a.mov
