### ISSUE TITLE
swiper.activeIndex and onActiveIndexChange behave buggy on swiper@9

### ISSUE THREAD

**Issue by QzCurious** [nolimits4web/swiper#6520]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-pagination-custom-forked-l38eiu?file=%2Fsrc%2FApp.jsx&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A20%7D%5D

### Bug description

Logging the `swiper.activeIndex` whenever `onActiveIndexChange` fires.

```jsx
<Swiper
  onActiveIndexChange={(swiper) => {
      console.log(swiper.activeIndex)
    }}
/>
```

**After swiper loop**, it gives me weird `swiper.activeIndex` value

Here is a quick demo

https://user-images.githubusercontent.com/38932402/227431623-d31da284-e6b4-4fcd-90cf-25a8c634d6e2.mp4

### Expected Behavior

As of swiper@8, `swiper.activeIndex` is correct.

### Swiper version

9

### Platform/Target and Browser Versions

windows Chrome 111.0.5563.65

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nikwins** [comment]
Can confirm, I have the exact same problem in Vue.

**Comment by catsmeatman** [comment]
This problem is confirmed in all Swiper builds: Core/Vue/React/Element
