### ISSUE TITLE
Nuxt 3. Failed to resolve component. Hydration node mismatch

### ISSUE THREAD

**Issue by alexovn** [nolimits4web/swiper#6524]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-ctjmny?file=app.vue

### Bug description

I tried to use new Swiper Element API(WebComponents) in Nuxt 3 project and got Vue warnings in terminal/console. Everything is working so, but I don't think that it is a normal behaviour.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/64487090/227731101-255e1325-1624-4098-bee1-80b0b4e149a5.png">

### Expected Behavior

No warnings

### Actual Behavior

Warnings

### Swiper version

9.1.1

### Platform/Target and Browser Versions

macOS Chrome 111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [ ] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by mobinvoltro** [comment]
I'm facing the same issue. I'm using Quasar CLI with Vite + Vue 3. Any solution to get rid of this warning?

**Comment by nolimits4web** [comment]
Error message clearly states what needs to be done
