### ISSUE TITLE
Loop problems when the number of slides is less than slidesPerView * 2

### ISSUE THREAD

**Issue by miralkashiwagi** [nolimits4web/swiper#6527]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://deep-space.blue/testing/js-example/swiper/report-for-github-2023-03-28.html

### Bug description

There is a problem with behavior when `loop:true, slidesPerView:3` is set and the number of slides is 4 or 5.

- When I click `swiper-button-next`, pagination does not move to the last slide, and after one or two clicks, it does not work.
- When `swiper-button-prev` is clicked, pagination moves to the next slide instead of the previous one. (when there are 4 slides)
- When `swiper-button-prev` is clicked, it moves to the previous two slides. (when there are 5 slides)

### Expected Behavior

I am aware that the loop specification has changed since v8, but a method needs to be provided to make it behave as in v8 below when the number of slides is 4 or 5.
https://deep-space.blue/testing/js-example/swiper/card-v8.html

### Swiper version

9.1.1

### Platform/Target and Browser Versions

Windows Chrome 111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Docs clearly states the requirement
