### ISSUE TITLE
Missing "./css/lazy" export in "swiper" package

### ISSUE THREAD

**Issue by d-strygwyr** [nolimits4web/Swiper#6532]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/io4q09?file=%2Fsrc%2FApp.jsx

### Bug description

cant implement lazy module on swiper

### Swiper version

"swiper": "^9.0.0"

### Platform/Target and Browser Versions

windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Read docs, there is no lazy module in v9
