### ISSUE TITLE
Problem with slider looop, doesn´t show next slide on centeredSlides: true

### ISSUE THREAD

**Issue by zzseba78** [nolimits4web/swiper#6536]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/zzseba78-the-reactor/pen/zYJXbGV

### Bug description

There is a problem with Swiper when there are few items.

In this example, there are 4 slides, with loop, and 3 slides visible per view. 

The 3rd slide doesn´t show, and while you navigate the loop seems that 1 is missing.  Since this carrousel is moved by a cms content, i don´t know how many slides will be in, so i would like that they show correctly whatever items are avaiblable.

The code pen is the simplest example.

<img width="1293" alt="Captura de pantalla 2023-03-29 a la(s) 17 59 18" src="https://user-images.githubusercontent.com/5558563/228666151-2feb92d0-bdae-4abf-9b76-bfafb283673c.png">

### Expected Behavior

Slides show without problem

If not a bug, is there a workaround for this? Thanks.

### Actual Behavior

3rd item doesnt show, and same with the next slider if 4 visible and 5 available.

### Swiper version

latest

### Platform/Target and Browser Versions

macOs, Chrome, Firefox, Safari.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2
