### ISSUE TITLE
Not loading previous or next slides in time

### ISSUE THREAD

**Issue by luuklinc** [nolimits4web/swiper#6540]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-prev-next-slides-dmmvog?file=/index.html

### Bug description

When using the following settings:

```
slidesPerView: 1,
spaceBetween: 24,
speed: 300,
watchOverflow: true,
grabCursor: true,
centeredSlides: true,
loop: true
```

the previous and/or next slides don't show in time.
I need the `overflow: visible` on the swiper container for design purposes.

### Expected Behavior

Previous/next slides appearing in time.

### Actual Behavior

Previous/next slides not appearing in time.

### Swiper version

9.1.1

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Try setting `loopedSlides: 2` parameter
