### ISSUE TITLE
Lazy loading doesn't working

### ISSUE THREAD

**Issue by vadympetryshyn** [nolimits4web/Swiper#6541]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/io4q09?file=%2Fsrc%2FApp.jsx

### Bug description

When try to add Lazy module `<Swiper ... modules={[Lazy, FreeMode, Navigation, Thumbs]} />` getting the error `TypeError: mod is not a function`. You can check it in sandbox example from documentation, it's broken as well. 

### Swiper version

9.1.1

### Platform/Target and Browser Versions

chrome all versions

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Where do you see Lazy module in swiper 9 docs?
