### ISSUE TITLE
iOS Swipers are out of bounds

### ISSUE THREAD

**Issue by Garrett-Gizen** [nolimits4web/swiper#6542]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.biktrix.com

### Bug description

Only on IOS, all swipers are not working with the bounds and can be extended. This is fine on all other devices. 
![2023-03-30 11-16-44 High Res Screenshot](https://user-images.githubusercontent.com/81773543/228915089-eab3adc3-3744-47d4-a8b6-71240ab3d33e.png)

### Expected Behavior

Boundary is overflown: hidden and not pushed out of bounds.

### Actual Behavior

Boundary is non existent and client can scroll through the overflow. This is for all Swipers that are present on the site. 

### Swiper version

v9.1.1

### Platform/Target and Browser Versions

iPad IOS 16.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look for issues on your side
