### ISSUE TITLE
Looping carousel breaks if number of slides is less than double the value of `slidesPerView`

### ISSUE THREAD

**Issue by joshuahamilton** [nolimits4web/swiper#6548]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-slides-per-view-forked-860t0o?selection=%5B%7B%22endColumn%22%3A51%2C%22endLineNumber%22%3A60%2C%22startColumn%22%3A51%2C%22startLineNumber%22%3A60%7D%5D&file=%2Findex.html

### Bug description

When given the following configuration and less than 6 slides, clicking the previous button will jump 2 slides at a time. Clicking next works as expected until the last slide is reached, then it will not loop around to the first slide.

```javascript
var swiper = new Swiper(".swiper", {
  loop: true,
  slidesPerView: 3,
  spaceBetween: 10,
  // Navigation arrows
  navigation: {
    nextEl: ".swiper-button-next",
    prevEl: ".swiper-button-prev",
  },
});
```

### Expected Behavior

Clicking next/previous will move the carousel the expected number of slides in the appropriate direction, forever.

### Swiper version

9.1.1

### Platform/Target and Browser Versions

macOS Safari 16.3, macOS Chrome 111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is the requirement in v9 and it stated in docs
