### ISSUE TITLE
Click event is emitted twice

### ISSUE THREAD

**Issue by de-dan** [nolimits4web/swiper#6549]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/de-dan/swiperjstest

### Bug description

Click events are emitted twice on the <swipe-container> element, resulting in unexpected behavior. This issue is consistently reproducible on multiple web browsers and devices.

Steps to reproduce:

Open a web page that uses the swiperjs library.
Click on the <swipe-container> element.
Observe that the click event is emitted twice.

### Expected Behavior

One mouse click on the <swipe-container> element should emit only one event.

### Actual Behavior

The <swipe-container> element emits the click event twice on a single mouse click, causing unexpected behavior.

Additional information: A repository has been created with sample code to reproduce the issue. The expected behavior is for one mouse click to emit one event.

### Swiper version

9.2.0

### Platform/Target and Browser Versions

macOS Chrome 111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by bitrxjs** [comment]
@de-dan Can you please create a stackblitz or codesanbox

**Comment by nolimits4web** [comment]
You may want to use `events-prefix` as described here http://localhost:3000/element#events
