### ISSUE TITLE
Using slideToLoop and changing slideshow visibility breaks controls

### ISSUE THREAD

**Issue by maxackerman** [nolimits4web/swiper#6550]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/violetoffice/pen/ExeBNvL/5a85676c17eddc7c4e04683518acdbcc

### Bug description

I have multiple swiper instances on a page, but only one is visible at a time. I have interactions on the page that toggle the visibility of the swipers and advance them to specific slides using `slideToLoop`. The links above is a simplified version of the interaction to highlight the issue. To replicate the bug, follow these steps:

1. Advance first slideshow (1.1 -> 1.2) using a swipe or the navigation buttons.
2. Click toggle button. This hides the first slideshow and reveals the second.
3. Click toggle button again. This hides the second slideshow and reveals the first.
4. Try advancing the slideshow (1.1 -> 1.2) with the navigation button.

### Expected Behavior

Slideshow should advance when navigation button is clicked.

### Actual Behavior

The navigation buttons no longer work.

- Removing`swipers[uid].slideToLoop(0)` resolves the problem, so this seems to be caused by the combination of changing the visibility of the swiper and using slideToLoop. 
- I've trued using `observeParents: true` and `observer: true`
- I've tried using .update() to reinitialize the navigation 

### Swiper version

9.2.0

### Platform/Target and Browser Versions

macOS 12.5, latest chrome and firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
`swipers[uid].slideToLoop(0, 0)`
