### ISSUE TITLE
Swiper works on development but not after deployed

### ISSUE THREAD

**Issue by IlirEdis** [nolimits4web/swiper#6551]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/dank-meadow-7wtly8?file=%2Fpages%2Fslider.tsx&selection=%5B%7B%22endColumn%22%3A56%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A56%2C%22startLineNumber%22%3A22%7D%5D

### Bug description

**Please go to /slider page in codesandbox since the index page is for another issue**

Im using Nextjs and want to build a slider with Swiper which works fine in development mode in localhost and codesandbox but it appears broken after i deploy to Vercel (I cant provide a link to the deployed site but you have the same code in codesandbox).
The slides are cut on the right side and the navigation not working almost at all. 
Also AutoPlay not working in none of the environments.

Heres a screenshot from the deployed site:
<img width="1284" alt="Screenshot 2023-04-01 at 21 24 49" src="https://user-images.githubusercontent.com/128377763/229310533-6132bd0a-5fde-4fb0-af0c-98276d374683.png">

and here's the one from localhost: 

<img width="1220" alt="Screenshot 2023-04-01 at 21 29 30" src="https://user-images.githubusercontent.com/128377763/229310559-41b28057-36a8-46ef-a8ed-d94640cedc6d.png">

### Swiper version

9.1.0

### Platform/Target and Browser Versions

macOS Brave Version 1.49.120 Chromium 111.0.5563.64

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by IlirEdis** [comment]
Anyone having the same issue, i found out that this fixed it:

```
".swiper-wrapper": {
    boxSizing: "border-box",
  }
```

**Comment by kimkyeseung** [comment]
> Anyone having the same issue, i found out that this fixed it:
> 
> ```
> ".swiper-wrapper": {
>     boxSizing: "border-box",
>   }
> ```

whice file to write that code?

**Comment by avishek999** [comment]
Why do you have Reproduction link??
