### ISSUE TITLE
Loop sliding issues when sledesPerView:3 and has 4 or 5 slides.

### ISSUE THREAD

**Issue by dodevski** [nolimits4web/swiper#6556]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/60amf947/1

### Bug description

When the slider is configured to be in loop and has 3 slides per view and 4 or 5 slides at all, has issues with sliding:

1. No looping on the next arrow navigation, stop on the last slide.
2. Not working properly on the previous arrow navigation, mix and reorder slides.

With the same configuration but when there has more then 5 items (slides) work as well.

https://jsfiddle.net/60amf947/1

This issue comes with 9.0.0, before works ok.

### Swiper version

9.0.0

### Platform/Target and Browser Versions

win10 Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Carguyrocky** [comment]
Workaround:

I stumbled upon this bug also. However, I noticed, that general rule of thumb for the slider is to have at least + 3 more slides than you declare in the "slidesPerView" prop. In my case, I had 5 items I wanted to loop while displaying 3 per view and it was stopping at the end of the loop. I added one more item and it fixed the problem.

**Comment by dodevski** [comment]
I know, but however it's issue, you have 3 "slidesPerView" but you have 1 "slidesPerGroup" by default and need to work properly.

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2
