### ISSUE TITLE
Adding loop to auto slidesPerView and centeredSlides breaks slide positioning

### ISSUE THREAD

**Issue by simonkuran** [nolimits4web/swiper#6559]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-centered-auto-forked-po4oq6?file=%2Findex.html

### Bug description

I have a slider with slides of differing widths and I want it centered. When I try to loop the slider it gets glitchy when changing slides, active slide eventually stops being centered, occasional flickering slides, occasional odd jumping between slides, slider scrolling the wrong way when using pagination. Adding `loopedSlides` doesn't seem to help either.

The following params plus slides of different widths (set with % or px) will break.
```
swiperParams = {
    slidesPerView: 'auto',
    centeredSlides: true,
    loop: true
}
```

I forked the Element "Centered auto" demo (I have the same issue with Core too) and only added `loop="true"`. To recreate this bug use the [linked CodeSandbox](https://codesandbox.io/p/sandbox/swiper-centered-auto-forked-po4oq6?file=%2Findex.html) and change slides with the pagination several times.

This does not seem to be an issue [with Swiper v8.4.7](https://codesandbox.io/p/sandbox/9nrt0e?file=%2Findex.html).

I see in the [Migration Guide to Swiper 9 under Loop Mode](https://swiperjs.com/migration-guide-v9#loop-mode) "_It comes with new limitation. Amount of slides in loop mode should be at least 2x of slidesPerView value._" With `slidesPerView` set to `auto` it's not clear what 2x of that would be. The number of slides I've tested is well over 2x the number of slides that are in view at any point.

### Expected Behavior

Advancing slides to work consistently and keep the active slide centered.

### Actual Behavior

Active slide eventually stops being centered, occasional flickering of slides, occasional odd jumping between slides, slider scrolling the wrong way when using pagination.

### Swiper version

9.2.0

### Platform/Target and Browser Versions

Chrome v111.0.5563.146 on MacOS v13.2.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Sandros94** [comment]
I was discussing this in a [nuxt-swiper issue](https://github.com/cpreston321/nuxt-swiper/issues/51) too but then decided to test swiper itself and yes, currently enabling loop with slidesPerView on auto brakes the positioning quite easily.

This is the [reproduction link](https://stackblitz.com/edit/nuxt-starter-jfogjs?file=components%2Fcontent%2Fslide-show.vue), for screenshots you can visit the issue I've linked.

**Comment by Sandros94** [comment]
Small sidenote:
While I was testing `rewind` and `mousewheel` I've noticed that the last scroll of the mouse wheel doesn't actually trigger a rewind. Is this intentional?

**Comment by dnlmzw** [comment]
+1

**Comment by ArianHamdi** [comment]
In general, `SlidesPerView : auto` does not work with `loop`.
And this is annoying.

**Comment by PegeDev** [comment]
slidesPerView =3 same bug

**Comment by nolimits4web** [comment]
because these CSS rules:
```css
swiper-slide:nth-child(2n) {
      width: 40%;
    }

    swiper-slide:nth-child(3n) {
      width: 20%;
    }
```
 won't work for loop mode because slides are rearranged in DOM, specify widths explicitly for slides
