### ISSUE TITLE
Swiper does not work in production, and it does not show any error

### ISSUE THREAD

**Issue by Nefcanto** [nolimits4web/swiper#6562]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/Nefcanto/QwikSwiperBuild

### Bug description

I"m using Swiper JavaScript version in my Qwik projects.

It works in the development mode. But when I deploy it to the production, it does not work.

I also reported this problem to the [Qwik team](https://github.com/BuilderIO/qwik/issues/3665).

I don't know if it's your bug or their bug. I can't find out. Thus I posted to both teams.

### Expected Behavior

Swiper JavaScript version works in the production environment, or gives a descriptive error on why it does not work

### Actual Behavior

Swiper JavaScript version does not work in production build and it prints no error

### Swiper version

9.2.0

### Platform/Target and Browser Versions

Debian 11, Qwik 0.100.0, Chrome 111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by OsirisFrik** [comment]
Hi, I have a same problem

Here are my test with get started steps: https://codesandbox.io/s/swiper-test-82167s

Don't show any error on logs... so I thing it's a bug

**Comment by bitrxjs** [comment]
@OsirisFrik 
Check this example
https://codesandbox.io/s/swiper-test-forked-n2qmgo

**Comment by bitrxjs** [comment]
> ### Check that this is really a bug
> * [x]  I confirm
> 
> ### Reproduction link
> https://github.com/Nefcanto/QwikSwiperBuild
> 
> ### Bug description
> I"m using Swiper JavaScript version in my Qwik projects.
> 
> It works in the development mode. But when I deploy it to the production, it does not work.
> 
> I also reported this problem to the [Qwik team](https://github.com/BuilderIO/qwik/issues/3665).
> 
> I don't know if it's your bug or their bug. I can't find out. Thus I posted to both teams.
> 
> ### Expected Behavior
> Swiper JavaScript version works in the production environment, or gives a descriptive error on why it does not work
> 
> ### Actual Behavior
> Swiper JavaScript version does not work in production build and it prints no error
> 
> ### Swiper version
> 9.2.0
> 
> ### Platform/Target and Browser Versions
> Debian 11, Qwik 0.100.0, Chrome 111
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
> * [x]  Read the [docs](https://swiperjs.com/swiper-api).
> * [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
> * [x]  Make sure this is a Swiper issue and not a framework-specific issue
> 
> ### Would you like to open a PR for this bug?
> * [ ]  I'm willing to open a PR

Looks like issue from Qwik on how they attach event listeners

**Comment by heejin617** [comment]
Any updates? I upgraded Swiper version from 6 to 9.2.4 because of the centered pinch focus when zooming in and out, and it perfectly works in local but not works only in production without any runtime errors.

**Comment by damilola1ade** [comment]
Did anyone solve this?

**Comment by MadonisP** [comment]
I have the same problem too. it works in local but not works in production.

**Comment by damilola1ade** [comment]
> I have the same problem too. it works in local but not works in production.

I needed up using nuka-carousel. You should check it out
