### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by ibrahim-990** [nolimits4web/swiper#6565]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no repo

### Bug description

![image](https://user-images.githubusercontent.com/65185082/230884089-ef45634f-14fd-45a3-b577-e0780aa53fb6.png)

### Swiper version

https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#using-js-modules
