### ISSUE TITLE
Autoplay + slidesPerView="auto" & loop isn't working simultaneously.

### ISSUE THREAD

**Issue by vipindigiqt** [nolimits4web/swiper#6571]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/wd986i?file=%2Fsrc%2FApp.jsx

### Bug description

I've a few slides having fixed width, I've added `slidesPerView="auto` and `loop` but Autoplay doesn't seem to be working here after the slides reach to the end.

### Swiper version

9.2.0

### Platform/Target and Browser Versions

Windows 11, 113.xx.xx.xx

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by bitrxjs** [comment]
@vipindigiqt 
its working fine in demo

**Comment by martisj** [comment]
> @vipindigiqt its working fine in demo

What do you mean? the `slidesPerView=auto` is not present in the demo 🤷 Which demo are you referring to? This one: https://codesandbox.io/p/sandbox/wd986i?file=%2Fsrc%2FApp.jsx

**Comment by nolimits4web** [comment]
Closing as demo provided doesn't illustrate the issue
