### ISSUE TITLE
Using Element combined with vue to inject invalid values into the injectStyles attribute

### ISSUE THREAD

**Issue by xhc-code** [nolimits4web/swiper#6578]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no

### Bug description

I used the swiper-container to customize the web component through the Element method, and found that the injectStyles property was aligned and injected through the Vue method. This is a problem that the dom is bound to a string, and the style value of the array is passed.

For testing purposes, I set the array value directly to the injectStyles property, and the strings spliced ​​by commas are bound on the dom.

I'm pretty sure this is a problem with swiper's handling of this attribute when defining the Element component. Through the official demo, there is no problem with the cdn import method used, but the swiper installed through npm has this problem.

```vue setup
// In this example, view the properties bound by dom through the browser, and the result is
// el.injectStyles="1,2,3,4,5"
<swiper-container :inject-styles="[1,2,3,4,5]">
 …
</swiper-container>


```
At present, only the attribute injectStyles has been found to be problematic, and others have not been found yet.

The official website explains how to use it: https://swiperjs.com/element#usage-with-vue

### Expected Behavior

normal injection style

### Actual Behavior

cannot inject styles

### Swiper version

9.2.0

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by xhc-code** [comment]
The speed is so fast, that is to say, the current level of support for Element's web components is not enough?

**Comment by nolimits4web** [comment]
Sorry, what?

**Comment by xhc-code** [comment]
> Sorry, what?

It's okay, it's great
