### ISSUE TITLE
lazy loading doesn't work with fade effect

### ISSUE THREAD

**Issue by hypersonic64** [nolimits4web/swiper#6582]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/370-lazy-load-images/core

### Bug description

Lazy loading seems not to work with fade effect. If I modify the working demo (see reproduction link) and add effect:'fade' to the swiper initialization then all images are loaded immediately. 

### Expected Behavior

Images should only be loaded when they are to be displayed also when effect is set to "fade".

### Actual Behavior

All images are loaded when effect is set to "fade".

### Swiper version

9.2.0

### Platform/Target and Browser Versions

Windows Firefox 112, Chrome 112

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how browser handles it, you probably can set `visiblity: hidden` on slides that are not prev,active,next
