### ISSUE TITLE
Not working since the latest release of 14 April, my site is down because of that

### ISSUE THREAD

**Issue by EdoardoEntusiasta** [nolimits4web/swiper#6584]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

missing demo - private project

### Bug description

Guys I've been getting this error for an hour, the swiper that always worked now doesn't work anymore

`caught TypeError: Cannot redefine property: injectStyles
    at Function.defineProperty (<anonymous>)
    at 0:9514:14
    at Array.forEach (<anonymous>)
    at 0:9509:33
    at 0:13:1`

`caught TypeError: swiperEl.initialize is not a function
    at main.js:54:12`

In my chrome console I can see as well this error string: "Could not load content for https://cdn.jsdelivr.net/npm/swiper@9/0 (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)"

My site is down because of that. I can't give you the link as it's a company's project.

### Swiper version

9.2.1

### Platform/Target and Browser Versions

Chrome 112.0.5615.49

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by acharyabidhan** [comment]
same problem
