### ISSUE TITLE
`slideToLoop` produces the flip through effect between neighbouring slides after at least one loop is finished

### ISSUE THREAD

**Issue by electrodrel** [nolimits4web/swiper#6592]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/electrodrel/pen/MWPeQdQ

### Bug description

When switching to a slide using `slideToLoop` method, there is this 'flipping through all the slides in the slider' effect. it is intended to show up only between the last and the first slide to indicate the end of the loop. However it happens between two neighbouring slides if they have been rearranged in loop navigation.

### Expected Behavior

No matter how many times a user swipes through the slides in the infinite loop, there should not be any flipping slide effect between two neighbouring slides, unless they are the last and the first slides in the slider.

https://user-images.githubusercontent.com/3395183/232592216-4b295370-e6af-48fd-8db3-771d37014ecb.mp4

### Actual Behavior

After at least one loop is over, there is the flipping effect between two neighbouring slides (not the last and the first ones).

https://user-images.githubusercontent.com/3395183/232592338-acad4c14-4f42-4a93-b20b-e65a08416cdb.mp4

### Swiper version

9.2.3

### Platform/Target and Browser Versions

macOS, Chrome, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one
