### ISSUE TITLE
Flickering in a flex container

### ISSUE THREAD

**Issue by 3nematix** [nolimits4web/swiper#6593]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

I've provided all the details below

### Bug description

I've been trying to make a responsive flex container to display the slider and few other images in a row, but I've noticed an issue when I have placed a slider inside the flex row. 

In the top you can see the slider working just fine and in the bottom left side the image represents the slider that not works as expected.

![image](https://user-images.githubusercontent.com/46891372/232627093-0c129363-fe7f-497b-b9da-44954b571b2d.png)

For some reason the slider just keeps "flicking"? and does not render as it should. I've noticed that when you give the swiper parent fixed width it then works fine, but I'd love to keep it responsive

https://user-images.githubusercontent.com/46891372/232628119-9b58b62e-9b78-4381-8b58-c1c57afc2b07.mp4

HTML:

FYI: The `<b component="...">` is just a way that we render our components globally.

```

<b component="ImageSlider" image_urls='{{ property_view.image_urls|tojson }}'></b>

 <div class="flex flex-wrap gap-5">
    <div class="basis-[500px] grow-[9999] max-h-[30rem]">
        <b component="ImageSlider" image_urls='....'></b>
         <!-- <img class="w-full h-full object-contain cursor-pointer rounded-2xl" alt="house" src="demo_img"> -->
     </div>
                
     <div class="basis-[370px] grow hidden lg:block max-h-[30rem]">
         ....
     </div>
</div>
```

Swiper (Svelte):
```
<div class="relative border-white rounded-2xl w-full h-full">
    <Swiper
        on:swiper={(e) => swiper = e.detail[0]}
        loop={true}
        spaceBetween={0}
        slidesPerView={1}
        navigation={true}
        keyboard={{enabled: true}}
        pagination={{dynamicBullets: true}}
        modules={[Pagination, Navigation, Keyboard, Lazy]}
        lazy={{loadPrevNext: true, preloaderClass: "spinner-backdrop"}}
    >
        {#each image_urls as image_url}
            <SwiperSlide>
                <img class="w-full max-h-[20rem] rounded-2xl object-contain cursor-pointer swiper-lazy lg:max-h-[33rem]" data-src={image_url} alt="house">
                <div class="spinner-backdrop grid place-items-center bg-[#f6f6f6] h-full w-full top-0 absolute">
                    <i class="fas fa-circle-notch fa-spin fa-2xl text-blue"></i>
                </div>
            </SwiperSlide>
        {/each}
    </Swiper>
</div>
```

### Swiper version

8.4.4

### Platform/Target and Browser Versions

Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [x] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
1. latest version of Swiper is 9.x
2. impossible to say anything here without live example
