### ISSUE TITLE
Web component: Add parts

### ISSUE THREAD

**Issue by strarsis** [nolimits4web/swiper#6594]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/strarsis/pen/qBJNJzv

### Bug description

The [Swiper Element](https://swiperjs.com/element) (Web Component) does not have `parts` for its sub-components, as its pagination (pagination button (normal / active)), navigation, etc.
This makes styling those elements unnecessarily hard, as selecting those elements in shadow DOM by CSS is not directly possible from the outside.

### Expected Behavior

All sub-components should be parts, so that styling is very easy and efficient, 
it also leverages the strengths of such web components.

### Actual Behavior

No parts are available.

### Swiper version

9.2.3

### Platform/Target and Browser Versions

Chrome (latest stable at 18.04.2023) on Windows 10 x64

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Customization must be done through CSS properties, if there are not enough CSS properties, you can open another feature request suggesting what to add.

**Comment by nolimits4web** [comment]
Added
