### ISSUE TITLE
swiper slide got stuck when there inner one slide have some scroll event 

### ISSUE THREAD

**Issue by jingleiaf** [nolimits4web/swiper#6607]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

mobile. 

### Bug description

Hello,

I had one issue with swiper, since i implemented in my page, which have three component, so one slide is one component, but when inside on component, when there is some vertical scroll event, it will got stuck when swipe from left to right...

![image](https://user-images.githubusercontent.com/123410196/233355729-b69d4fa0-123b-49bf-915e-51955baaecf1.png)

### Swiper version

9

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Vadi4** [comment]
If I get you right, i find the solution. For me it's was .scrolling-container { touch-action: pan-x; } or touch-action: pan-y;
