### ISSUE TITLE
SwiperSlide don't work if I extract it into a component.

### ISSUE THREAD

**Issue by oscar-romero-silva** [nolimits4web/swiper#6609]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/determined-wing-61o46l?file=/src/Carousel.tsx

### Bug description

I'm trying to extract the `SwiperSlide` to an external component to give my personal props, but when I use it as a children from the `Swiper` it doesn't render as espected. See example

### Swiper version

9.1.1

### Platform/Target and Browser Versions

Ubuntu

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please, use issues search before posting a new one
```
Slide.displayName = "SwiperSlide";
```
