### ISSUE TITLE
Problem with swiper slider with gl shader slicer transition.

### ISSUE THREAD

**Issue by 2tech-development** [nolimits4web/swiper#6610]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://k-raheja-realty.vercel.app/slider

### Bug description

Swiper GL effect with the Shader Slicer effect is showing all shader transitions in the mix, instead of only the Slicer transition. The code is made directly into SwiperJS Studio.  I'm using the slider in my NextJS project.
![image](https://user-images.githubusercontent.com/68319585/233607183-63db6df5-322a-4497-83b7-aa0e5a4e5da4.png)

### Expected Behavior

The slider should work with only one GL transition, which is the slicer transition.

### Actual Behavior

All the GL transitions are shown in mix format which is the default. My settings are not working.

### Swiper version

9.2.3

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use official support for this slider, not here
