### ISSUE TITLE
Property 'swiper-container' does not exist on type 'JSX.IntrinsicElements'.ts(2339) "swiper": Unknown word.

### ISSUE THREAD

**Issue by vaynevayne** [nolimits4web/swiper#6614]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/element#usage-with-react

### Bug description

```jsx
import {useEffect, useRef} from "preact/hooks"

export const MyComponent = () => {
  const swiperElRef = useRef(null)

  useEffect(() => {
    // listen for Swiper events using addEventListener
    swiperElRef.current.addEventListener("progress", (e) => {
      const [swiper, progress] = e.detail
      console.log(progress)
    })

    swiperElRef.current.addEventListener("slidechange", (e) => {
      console.log("slide changed")
    })
  }, [])

  return (
    <swiper-container
      ref={swiperElRef}
      slides-per-view="3"
      navigation="true"
      pagination="true"
    >
      <swiper-slide>Slide 1</swiper-slide>
      <swiper-slide>Slide 2</swiper-slide>
      <swiper-slide>Slide 3</swiper-slide>
      ...
    </swiper-container>
  )
}
```

### Swiper version

9.2.4

### Platform/Target and Browser Versions

macos

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by MurDev** [comment]
This issues is closed but the bug still occurs

**Comment by iamharshad** [comment]
@MurDev Agree, Today I used and it's happening

@nolimits4web Any update?

**Comment by HelaGone** [comment]
Same issue here! Is it possible use this library in typescript at all? 
how do I declare the type in the JSX.IntrinsicElements? 
I tried this but it does not work: 
```
declare namespace JSX {
  interface IntrinsicElements {
    "swiper-container": any;
  }
}
```

**Comment by vaynevayne** [comment]
web-component package is bad, suggest use swiper-react

**Comment by gryzzly** [comment]
is there no specific type for swiper web-component provided by swiperjs? so that we could do 

```
declare namespace JSX {
  interface IntrinsicElements {
    'swiper-container': SwiperContainerProps,
    'swiper-slide': SwiperSlideProps,
}
```

?
