### ISSUE TITLE
custom pagination is not work 

### ISSUE THREAD

**Issue by vaynevayne** [nolimits4web/swiper#6615]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-pagination-custom-forked-pc6bmn?file=%2Findex.html&selection=%5B%7B%22endColumn%22%3A41%2C%22endLineNumber%22%3A54%2C%22startColumn%22%3A41%2C%22startLineNumber%22%3A54%7D%5D

### Bug description

nothing happened

### Swiper version

latest

### Platform/Target and Browser Versions

mac

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
On the example link you have provided everyhting works
