### ISSUE TITLE
Events not firing correctly in loop

### ISSUE THREAD

**Issue by beyondtheline** [nolimits4web/swiper#6623]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/element

### Bug description

When I use a loop, the events are not fired correctly after the first cycle. This happens in autoplay and manual operation.

I have an eventlistener and output the activeIndex on the event 'slidechange'.
```
swiperElRef.current.addEventListener('slidechange', (event) => {
  console.log('activeIndex: ', event.detail[0].activeIndex);
});  
```

This produces a wrong sequence:
![image](https://user-images.githubusercontent.com/1230459/234497090-0b9c32c7-880b-4d03-b4de-10cee680be77.png)

The correct sequence should look like this:
```
activeIndex: 0
activeIndex: 1
activeIndex: 2
activeIndex: 3
activeIndex: 0
activeIndex: 1
activeIndex: 2
activeIndex: 3
activeIndex: 0
activeIndex: 1
activeIndex: 2
activeIndex: 3
```

### Swiper version

9.2.4

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Everything is correct, you need to use realIndex

**Comment by beyondtheline** [comment]
thank you! that's it
