### ISSUE TITLE
Swiper navigation not working properly (skipping slides)

### ISSUE THREAD

**Issue by timjuedemann** [nolimits4web/swiper#6624]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/timjuedemann/swiper-testing

### Bug description

In a page I’m working on, I have a lightbox component I am populating dynamically with either a single image or a group of related images, the latter being displayed as a swiper instance in said lightbox. The contents of the lightbox are removed upon closing the lightbox. The HTML markup looks as follows.

````
<div class="lightbox-swiper">
    <div class="swiper-wrapper">
    </div>
    <div class="swiper-controls">
        <button class="lightbox-swiper-button-prev" data-action="prev"></button>
        <button class="lightbox-swiper-button-next" data-action="next"></button>
    </div>
</div>
````

If an image within a component called 'contact-sheet' is clicked, it dynamically populates the swiper-wrapper with all images of the contact-sheet instance the clicked image belongs to and sets the clicked image as the initialSlide. My JavaScript looks as follows:

````
import $ from "cash-dom";
import Swiper, { EffectFade, Manipulation, Navigation } from "swiper";
Swiper.use([EffectFade, Manipulation, Navigation]);

/**
 * Initialize contextual slider
 */
$('.layout-contact-sheet [data-action="enlarge"]').on("click", function (_e) {
    var container = $(_e.target).closest(".contact-sheet")[0];
    var index = $(_e.target).closest(".contact-sheet-image").attr("data-index");
    var slides = $(container).find(".contact-sheet-image");
    var buttonPrev = $(".lightbox-swiper-button-prev")[0];
    var buttonNext = $(".lightbox-swiper-button-next")[0];
    var swiper = new Swiper(".lightbox-swiper", {
        effect: "fade",
        initialSlide: parseInt(index),
        loop: false,
        slidesPerView: 1,
        modules: [EffectFade, Manipulation, Navigation],
        navigation: {
            nextEl: buttonNext,
            prevEl: buttonPrev,
        },
    });

    slides.each(function () {
        var html = $(this).find(".image-element").html();
        swiper.appendSlide(`<div class="swiper-slide">${html}</div>`);
    });

    swiper.update();

    $(".lightbox").addClass("is-visible").removeClass("no-pointer");

    $("button[data-action='close-lightbox']").on("click", function (e) {
        $(".lightbox")
            .removeClass("is-visible")
            .addClass("no-pointer")
            .find(".lightbox-static, .lightbox-swiper .swiper-wrapper")
            .html(null);
    });
});
````

I am experiencing the following problems:
- The swiper instance doesn’t respect the value passed to the initialSlide parameter and always displays the first slide instead. If I manually navigate to the slide-index passed to initialSlide using slideTo(index), it works properly.
- Clicking the next button doesn’t skip one but *two* slides ahead. If I completely rewrite the navigation logic using eventListeners which trigger the slideNext() and slidePrev() functions, it works properly.

What could be causing these problems?

### Expected Behavior

Swiper instance displays the slide the initialSlide value is set to when opened. Navigation works properly i.e. only navigating one slide back/ahead.

### Actual Behavior

Swiper instance ignores value of initialSlide and always displays the first slide when opened. Navigation doesn’t work, always moving two slides back/ahead instead of one.

### Swiper version

9.1.1

### Platform/Target and Browser Versions

OS X 10.15.7, Chrome 112

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by timjuedemann** [comment]
Hello @nolimits4web, I just provided a minimal repository that shows the problem. The JavaScript file only contains the cash-dom library and swiper as well as my custom code containing the configuration on the swiper instance (the latter being at the very end of the file)

**Comment by nolimits4web** [comment]
I would like to see the issue demo in CodeSandbox forked from on of the demos, otherwise it is more likely issue is caused by your code

**Comment by timjuedemann** [comment]
Forking a CodeSandbox from one of the demos doesn’t seem viable because none of the demos shows what I am trying to achieve (dynamically populating an empty swiper-wrapper). I created a CodeSandbox with only the JavaScript code relevant to my problem (barely 75 lines). I’d really appreciate if you could take a look. Thanks very much in advance:

https://codesandbox.io/s/competent-platform-nuzfvn?file=/index.html

**Comment by nolimits4web** [comment]
You need to add slides to the DOM BEFORE you Init Swiper (new Swiper). Even better if you init Swiper right AFTER lightbox becomes visible

**Comment by timjuedemann** [comment]
@nolimits4web Thanks for looking into this. I followed your advice but it turns out that the error was caused by me calling ```Swiper.use([EffectFade, Manipulation, Navigation]);``` at the top of my module and then again ```modules: [EffectFade, Manipulation, Navigation],``` while initializing the swiper instance. Just commenting out the ```modules``` parameter ended up doing the trick. Great library!

**Comment by RaulMazilu** [comment]
@timjuedemann thanks for this, I had the exact same issue and nothing seemed to solve it!

**Comment by tushar33** [comment]
@nolimits4web Do we need to upgrade package to resolve this issue? I am using   "swiper": "~8.4.2",
