### ISSUE TITLE
nuxt3 autoplay stops

### ISSUE THREAD

**Issue by Ischafak** [nolimits4web/swiper#6627]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/pensive-chatterjee-fj4uix?file=%2Fcomponents%2FTutorial.vue&selection=%5B%7B%22endColumn%22%3A9%2C%22endLineNumber%22%3A87%2C%22startColumn%22%3A9%2C%22startLineNumber%22%3A87%7D%5Dhttps://codesandbox.io/p/sandbox/pensive-chatterjee-fj4uix?file=%2Fcomponents%2FTutorial.vue&selection=%5B%7B%22endColumn%22%3A9%2C%22endLineNumber%22%3A87%2C%22startColumn%22%3A9%2C%22startLineNumber%22%3A87%7D%5D

### Bug description

I want and infinite autoplay without delay. But after this comes to slide 6 it stops automatically. 

### Expected Behavior

It should be infinite autoplay without stop at any point

### Swiper version

8.4.7

### Platform/Target and Browser Versions

macos chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
v8 is not maintained anymore
