### ISSUE TITLE
nuxt3 autoplay stops

### ISSUE THREAD

**Issue by Ischafak** [nolimits4web/swiper#6628]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/pensive-chatterjee-fj4uix?file=%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A4%7D%5D

### Bug description

I want and infinite autoplay without delay. But after this comes to slide 4 it stops automatically.

i cant comment the old issue that i created so i created this one

### Expected Behavior

It should be infinite autoplay without stop at any point

### Swiper version

9.2.4

### Platform/Target and Browser Versions

macos chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Ischafak** [comment]
it stops like this 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/13226879/234821291-bdccf140-c284-4f95-a3b6-0576fcdd1cae.png">

**Comment by nolimits4web** [comment]
First of all https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2

loopedSlides should be removed as well
