### ISSUE TITLE
 Adding loop to auto slidesPerView and centeredSlides breaks slide positioning - even with px width slides

### ISSUE THREAD

**Issue by simonkuran** [nolimits4web/swiper#6631]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-centered-auto-forked-b6vfnm

### Bug description

@nolimits4web I think #6559 needs to be reopened.

[You said "specify widths explicitly for slides"](https://github.com/nolimits4web/swiper/issues/6559#issuecomment-1511543785).

[I switched from percentage based widths to pixel widths for the slides](https://codesandbox.io/p/sandbox/swiper-centered-auto-forked-b6vfnm) and it reduces the glitches somewhat, but it doesn't take many slide changes to see something weird happening. What needs to change to fix this? Do you have a working demo of this functionality?

### Swiper version

9.2.4

### Platform/Target and Browser Versions

Chrome v112.0.5615.137 on MacOS v13.2.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
And you still use nth-child selectors which give you what you have. Look at the DOM in loop mode
