### ISSUE TITLE
Nuxt3 autoplay pauses after I manually swipe the slideshow

### ISSUE THREAD

**Issue by JustinJsn** [nolimits4web/swiper#6632]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-b6j2mx?file=app.vue

### Bug description

Autoplay pauses after I manually swipe the slideshow.

### Expected Behavior

After I manually swipe the slideshow, autoplay continues at the current position.

### Actual Behavior

Autoplay pauses after I manually swipe the slideshow.

### Swiper version

9.2.4

### Platform/Target and Browser Versions

windows chrome 112.0.5615.138

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
What do you mean by "manually" pause it?

**Comment by JustinJsn** [comment]
> 

You can see the demo.When autoplay at "Slide 2" card,then use mouse slide to next，the autoplay will not work.

**Comment by nolimits4web** [comment]
See disableOnInteraction parameter
