### ISSUE TITLE
Link inside `SwiperSlide` can't swipe for space between slides

### ISSUE THREAD

**Issue by vkruglikov** [nolimits4web/swiper#6633]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-slides-per-view-forked-kug0q9?file=%2Fsrc%2FApp.jsx

### Bug description

If I put inside SwiperSlide link and set `spaceBetween` to any value above zero, for example 30, I can't swipe the slider for space between slides

### Expected Behavior

Be able swipe slider for space between slides

### Swiper version

latest

### Platform/Target and Browser Versions

macOS Chrome Версия 112.0.5615.137  (arm64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please use issues search before posting a new one, it is related to touchEventsTarget parameter
