### ISSUE TITLE
Bug on version 9+

### ISSUE THREAD

**Issue by caof19** [nolimits4web/swiper#6635]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/falling-butterfly-tbiym7?file=/index.html

### Bug description

When you are on the first slide, you go to 3, then back to 1, try to go to 2, but it goes to 3. This error only occurs when there are 3 items. If there are 4, everything works as it should. And only when the number of slides is not an integer. On version 8 this code also works as it should. Maybe there is a temporary solution?

### Swiper version

9.2.4

### Platform/Target and Browser Versions

Chrome, Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2
