### ISSUE TITLE
Adding loop to auto slidesPerView and centeredSlides breaks slide positioning - even with px width slides set via class

### ISSUE THREAD

**Issue by simonkuran** [nolimits4web/swiper#6636]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-centered-auto-forked-b6vfnm

### Bug description

Any chance you could reopen #6631? I'm still having trouble. [I've removed the use of nth-child](https://codesandbox.io/p/sandbox/swiper-centered-auto-forked-b6vfnm) and set the widths of the slides to pixel values via a class. Am I missing something? Is some part of this not supported by v9? I even created a version where are the slides are the same width and [it's still buggy](https://codesandbox.io/p/sandbox/swiper-centered-auto-forked-qc17re).

It would be great to use the same issue until this is resolved. Once this is solved I'm happy to create a pull request to help document how this desired outcome is configured. Thanks for your help!

### Swiper version

9.2.4

### Platform/Target and Browser Versions

Chrome v112.0.5615.137 on MacOS v13.2.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Criiis** [comment]
Hey @simonkuran, on my understanding, I do not think that the position of the slides is broken. I actually think is it working as expected, let's have a look at it.

You explained that the swiper is centred,->  which means that the "focus slide" is centred, (when the page loads the 1st element is centred). 💯 
then we have an auto loo -> meaning the slider will have a loop around the slides (before the 1st slide (centred), u will have the last slide) 💯 

So having these 2 points in mind the combination of both ( centred and loop) will make the 1st slide (centred) with space on the left and with the loop that last space will be fulfilled with the last element so the slider loops over and over.

I'm guessing u need to remove the loop from you're code and try to find a way to send the user back to 1st slide when reach the last slide, maybe u find something in the demos page of SwiperJS.
https://swiperjs.com/demos 

I hope this makes sense 👍🏼

**Comment by nolimits4web** [comment]
This is what is see in your codesandbox, everything looks correct to me:


https://user-images.githubusercontent.com/999588/236763804-6afdc94e-e072-4410-96c1-06313c4dc5b7.mov
