### ISSUE TITLE
scrollbar bug

### ISSUE THREAD

**Issue by newyhj** [nolimits4web/swiper#6639]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/keen-ganguly-375o56?file=/index.html

### Bug description

when scrollbar html not exists,runt it error. please visit reproduction link

### Swiper version

9.2.4

### Platform/Target and Browser Versions

windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
And why do you specify the element that doesn't exist?
