### ISSUE TITLE
Nested slider is not working in loop mode

### ISSUE THREAD

**Issue by alexovn** [nolimits4web/swiper#6642]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/vue-j4w3xb?file=src/components/VueSlider.vue

### Bug description

Nested slider is not working in loop mode. It seems like nested slider completely turns off if you use loop mode on main slider.

### Expected Behavior

Nested slider is fully working in loop mode. You can swipe it, use navigation and etc.

### Swiper version

9.2.4

### Platform/Target and Browser Versions

macOS Chrome 112.0.5615.137

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look for issues on your side https://codesandbox.io/p/sandbox/swiper-default-forked-6pemeo

**Comment by alexovn** [comment]
I've checked your example and there is an issue so. Try to click on navigation in looped nested slider. It's not working. And yet I can't use init="true" attribute on sliders, 'cause there will be a hydration error if you use SSR. So I initialize swiper in mounted hook only and looped slides still not working
