### ISSUE TITLE
Autoplay, loop and slidesPerView="auto" starts at end and not is looping

### ISSUE THREAD

**Issue by MikeyS2002** [nolimits4web/swiper#6644]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/wd986i?file=/src/App.jsx

### Bug description

In this video you see that the first slider start at the end, even though it has the loop enabled. The second slider has the same values as the first one the only difference is that the second has centeredSlides added to it. (Second slider works as expected).

https://user-images.githubusercontent.com/59363396/235718097-cf6d6e75-296c-40ce-a7d4-d6a150865e7d.mp4

```
allowTouchMove={false}
spaceBetween={15}
slidesOffsetBefore={15}
autoplay={{
  delay: 2000,
  disableOnInteraction: false,
}}
breakpoints={{
  768: {
    allowTouchMove: true,
    spaceBetween: 20,
  },
  }}
speed={500}
loop={true}
modules={[Autoplay]}
grabCursor
slidesPerView={"auto"}
className="pointer-events-none swiper2 unveilTransition lg:pointer-events-auto"
```

### Expected Behavior

The slider autoplay and will never end.

### Actual Behavior

It starts at the end and, it doesn't autoplay or loop. It only loops when you go back and it look very buggy.

### Swiper version

^9.2.4

### Platform/Target and Browser Versions

macOS Google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Criiis** [comment]
With the code and the sandbox provided, I couldn't replicate the issue u are having 👎🏼

**Comment by nolimits4web** [comment]
Provided demo doesn't illustrate the issue

**Comment by danielangebrand** [comment]
I have the same issue. My (5) slides have loop functionality if i go back, but not if i go next.

**Comment by MrSeaWave** [comment]
> Provided demo doesn't illustrate the issue

@nolimits4web  I have the same issue, And I have found a similar question: https://github.com/nolimits4web/swiper/issues/6559, You can use this [codesandbox](https://codesandbox.io/p/sandbox/swiper-react-autoplay-forked-dsvzlr?file=%2Fsrc%2FApp.jsx%3A6%2C21) to reproduce ~

![loop](https://github.com/nolimits4web/swiper/assets/21967852/0c03ffa7-a17e-4040-9e72-788f84b26419)

**Comment by mhlv** [comment]
getting same behaviour with the same params
