### ISSUE TITLE
Version 9.3.0 won't compile with Angular 16 & Typescript 5

### ISSUE THREAD

**Issue by b416** [nolimits4web/swiper#6657]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/cpr2lq?file=%2Fpackage.json%3A1%2C1

### Bug description

The latest version 9.3.0 throws the following error when compiling :

TS2430: Interface 'SwiperContainerEventMap' incorrectly extends interface 'HTMLElementEventMap'.
  Types of property '"click"' are incompatible.
    Type 'CustomEvent<any>' is missing the following properties from type 'MouseEvent': altKey, button, buttons, clientX, and 20 more.

The previous version 9.2.4 compiles just fine.

### Expected Behavior

Compile without errors.

### Actual Behavior

The compiler throws the error above.

### Swiper version

9.3.0

### Platform/Target and Browser Versions

Linux, any browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by allanpoppe** [comment]
I'm also having the same issue.

> "@angular/core": "^16.0.0",
> "typescript": "^5.0.4"

**Comment by GRDtechlab** [comment]
I am also facing same issue. I am using swiper version 9.3.0 with angular 15.2.8 and same error coming when compiling angular project using ng serve -o. I have also created a [stackoverflow question here ](https://stackoverflow.com/questions/76215651/angular-swiper-gives-error-when-compiling-error-ts2430-interface-swipercontain)

Inside tsconfi.json file if I set skipLibCheck : true then it will work but this is not recommended either as per the typescript it will bypass this type checking system.

Please give solution for this. We did not find many content related to angular by visiting official swiper docs. Please add angular related contents too. Thanks.

**Comment by GRDtechlab** [comment]
> > Please give solution for this
> 
> Just install previous version of Swiper until this problem is fixed. npm install swiper@9.2.4

Yes. This is working with swiper version 9.2.4
