### ISSUE TITLE
Virtual mode and loop mode don't work properly together

### ISSUE THREAD

**Issue by RubenZx** [nolimits4web/swiper#6658]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-swiper-virtual-loop-iopxbg

### Bug description

After enabling virtual mode with loop mode activated, changing slides doesn't play well. It doesn't start in the correct `initialSlide` and after changing slides there is a weird flash/zoom-out in the carousel.

The `realIndex` is also wrong. You can check in the sandbox that it goes as follows: "0 1 0 1 2 3 ...", instead of "0 1 2 3 ...".

https://github.com/nolimits4web/swiper/assets/36533775/dc0a42e6-4e59-4271-9386-1562c56fa1f9

### Swiper version

9.3.0 and below

### Platform/Target and Browser Versions

macOS Chrome 112.0.5615.137

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#virtual-slides

<img width="1064" alt="ss" src="https://github.com/nolimits4web/swiper/assets/999588/e0d93258-dc08-4df6-8d0f-7d5001f7899f">
