### ISSUE TITLE
prop `init: false` not working

### ISSUE THREAD

**Issue by rutgerbakker95** [nolimits4web/swiper#6661]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/duz6bq?file=%2Fsrc%2FApp.vue

### Bug description

`<swiper :init="false"></swiper>` is still initializing.. I need to initialize the swiper manually.

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.3.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `vite`, `modules`, `tailwindcss`, `runtimeConfig`, `build`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.7`
- Build Modules:    `-`

### Swiper version

9.3.0

### Platform/Target and Browser Versions

macOS Ventura Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [ ] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is by design, if you need to init it manually for whatever reason, just do not render it before that, or use core version of swiper

**Comment by rutgerbakker95** [comment]
@nolimits4web thanks. I fixed it by using the core version of Swiper 👍
