### ISSUE TITLE
Swiper does not function correctly with child elements having overflow:auto in Chrome in Mobile View

### ISSUE THREAD

**Issue by Adnan-Oezsarigoel** [nolimits4web/swiper#6663]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://50bcdq.csb.app/

### Bug description

I've encountered an issue with SwiperJS where, if a child element within a Swiper slide has overflow:auto, it prevents the swiping action on Chrome browsers on mobile device or mobile mode on desktop (Press F12).

Here is a simplified example of the issue:

html
```
<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <div class="table-container" style="overflow:auto;">
        <!-- Content -->
      </div>
    </div>
    <!-- More slides -->
  </div>
</div>
```

In this setup, the swiping action on the Swiper does not work correctly in Chrome.

I found that adding touch-action:pan-y; to the .table-container CSS solves the issue and allows the Swiper to function correctly:

css
```
.table-container {
  touch-action: pan-y;
}
```

While this workaround resolves the issue, I wanted to bring this to your attention as it may indicate a deeper problem within SwiperJS's interaction with Chrome's handling of overflow:auto on child elements.

I hope this information is helpful, and I appreciate your attention to this issue.

### Swiper version

9.3.1

### Platform/Target and Browser Versions

Chrome (Android) and Chrome (Windows - mobile mode/F12)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how touch-action works in browser, Swiper can't know what elements you use, so that custom style is required
