### ISSUE TITLE
Add a parameter `centeredActiveSlide`

### ISSUE THREAD

**Issue by Capricair** [nolimits4web/swiper#6668]
### Clear and concise description of the problem

![image](https://github.com/nolimits4web/swiper/assets/6244446/1e6d0a0c-a989-488f-99e7-03f133926f25)
for example, there are 10 slides, and the thumbs displays 5, when active slide is 3 to 8, the active thumb slide are centered

### Suggested solution

add a parameter `centeredActiveSlide`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is already `centeredSlides` parameter
