### ISSUE TITLE
[v9.3.1] swiper web component: Starts on wrong slide + pagination bullets off + previous slide missing 

### ISSUE THREAD

**Issue by jakobadam** [nolimits4web/swiper#6679]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://angular-dvgzz3.stackblitz.io

### Bug description

I previously, submitted a bug https://github.com/nolimits4web/swiper/issues/6313 that was closed a bit too early.

Some bugs have been fixed. Thanks for that:) However, there are still some issues:
- Starts on slide 2 (In Safari)
- pagination bullets stop working after bullet 6
- previous slide is empty on load (In Chrome, see screenshot)

![image](https://github.com/nolimits4web/swiper/assets/139791/d4eec309-6933-43b0-80b1-8b23cf085a44)

Tested in Chrome Version 113.0.5672.93 + Safari (newer version)

https://stackblitz.com/edit/angular-dvgzz3?file=src%2Fmain.ts

kind regards,
Jakob

### Swiper version

9.3.1

### Platform/Target and Browser Versions

Windows Chrome / Safari iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is something more likely on Angular side, same config all works good https://codesandbox.io/p/sandbox/swiper-navigation-forked-fd3upz?file=%2Fpackage.json%3A1%2C1

**Comment by jakobadam** [comment]
So to conclude something is wrong with the Angular to web-component integration. 

I've updated the example demonstrating the bug - added Swiper instance outside Angular also.

Maybe consider leaving this issue open, as the issues mentioned remains when Swiper is used from inside Angular.
