### ISSUE TITLE
Compiler module resolution "bundler" missing types

### ISSUE THREAD

**Issue by filipbekic01** [nolimits4web/swiper#6682]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

- Init Vue and try installing and importing Swipe (no link).

### Bug description

When using TypeScript configuration with compilerOptions.moduleResolution set to "bundler", compiler can not find swiper types.

Issue is present with latest Vue installation since they use  that "bundler" option. Issue is not Vue related but that's the easiest way to reproduce it. Just initialize fresh Vue project.

### Expected Behavior

There should be no import type errors.

### Actual Behavior

It's failing to find types on import.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Linux

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate https://github.com/nolimits4web/swiper/issues/6685

**Comment by BrettHoutz** [comment]
This issue should be reopened. Workarounds to disable type definitions for swiper are suggested in #6685, but no actual solution to fix the types has been implemented.
