### ISSUE TITLE
Could not find a declaration file for module 'swiper'

### ISSUE THREAD

**Issue by ben4d85** [nolimits4web/swiper#6685]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

n/a

### Bug description

Fresh installation of Vite with React and TypeScript using Swiper version 9.3.2. I am getting the following error:

```
Could not find a declaration file for module 'swiper'. 

'/.../node_modules/swiper/swiper.esm.js' implicitly has an 'any' type.

There are types at '/.../node_modules/swiper/swiper.d.ts', but this result could not be resolved when respecting package.json "exports".

The 'swiper' library may need to update its package.json or typings.ts
```

Here's my code:

```tsx
// Swiper modules
import { Keyboard } from "swiper"; // This is the problem

// Swiper React components
import { Swiper, SwiperSlide, SwiperRef, SwiperClass } from "swiper/react"; // This is fine

// Swiper styles
import "swiper/css"; // This is fine
```

### Expected Behavior

Types should just work without error.

### Actual Behavior

Type error.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Cryptoplasm** [comment]
I've got the same issue. Did you manage to find a way to fix it?

**Comment by azeranex** [comment]
> I've got the same issue. Did you manage to find a way to fix it?

Please check this PR: https://github.com/nolimits4web/swiper/pull/6626
You need to change exports in swiperjs's package.json. I tried and it's working fine now.

**Comment by salvadoregunacci** [comment]
Solution:
1. Create a swiper.d.ts file in your application folder
2. Inside the file, place the following line of code:
`declare module 'swiper'`

**Comment by paras1729kori** [comment]
Thank you so much @salvadoregunacci for the solution.
But how should one fix a bug when deploying the website ? I am getting a build error of the same on vercel. How should I fix it ?

`[[22:53:22.811] Running build in Washington, D.C., USA (East) – iad1
[22:53:22.880] Cloning github.com/paras1729kori/nft-landing-page (Branch: main, Commit: 690fc67)
[22:53:23.167] Previous build cache not available
[22:53:24.145] Cloning completed: 1.265s
[22:53:24.281] Running "vercel build"
[22:53:24.805] Vercel CLI 29.3.6
[22:53:25.372] Installing dependencies...
[22:53:29.487] 
[22:53:29.487] added 258 packages in 4s
[22:53:29.488] 
[22:53:29.488] 51 packages are looking for funding
[22:53:29.488]   run `npm fund` for details
[22:53:29.511] Detected `package-lock.json` generated by npm 7+...
[22:53:29.511] Running "npm run build"
[22:53:29.825] 
[22:53:29.825] > nft-landing-page@0.0.0 build
[22:53:29.825] > tsc && vite build
[22:53:29.825] 
[22:53:31.359] src/components/TrendingNFTs.tsx(4,43): error TS7016: Could not find a declaration file for module 'swiper'. '/vercel/path0/node_modules/swiper/swiper.esm.js' implicitly has an 'any' type.
[22:53:31.359]   There are types at '/vercel/path0/node_modules/swiper/swiper.d.ts', but this result could not be resolved when respecting package.json "exports". The 'swiper' library may need to update its package.json or typings.
[22:53:31.385] Error: Command "npm run build" exited with 2
[22:53:31.678] BUILD_UTILS_SPAWN_2: Command "npm run build" exited with 2`

**Comment by paras1729kori** [comment]
Thank you so much @salvadoregunacci for the solution.
But how should one fix a bug when deploying the website ? I am getting a build error of the same on vercel. How should I fix it ?

![image](https://github.com/nolimits4web/swiper/assets/61196454/8b71f478-bc51-42a4-85a5-e742bd05953f)

**Comment by salvadoregunacci** [comment]
@paras1729kori
You can try this solution:
in your `tsconfig` file add the following code
```
"compilerOptions": {
"noImplicitAny": false
}
```

P.S it's not the best option, but it might come in handy

**Comment by paras1729kori** [comment]
Thanks a bunch @salvadoregunacci. It worked.

**Comment by qp0kycHuk** [comment]
It helps for me:
"strict": true   ->   "strict": false

in your tsconfig.json

**Comment by Ahl-am** [comment]
what worked for me in Next.js 13 was using swiper instead of swiper/module that was written in the documentation.
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";

**Comment by alipalvane** [comment]
if use next.js, you can use this:
`import { Navigation, Pagination } from 'swiper';`

**Comment by vovka8101** [comment]
I had the same problem in my React TypeScript project initialized with Vite.
I fixed that error by removing `"noUncheckedSideEffectImports": true` from my `tsconfig.app.json` file

**Comment by lien-dkseo** [comment]
cc https://github.com/nolimits4web/swiper/discussions/6103

**Comment by Rick-Phoenix** [comment]
Another solution is to import the css modules from a .css file instead of a JSX/TSX file:
```
@import "swiper/css/pagination";
@import "swiper/css/scrollbar";
@import "swiper/css";
@import "swiper/css/effect-coverflow";
```

**Comment by Olfdev** [comment]
Issue is still happening as of today. Basically, the very first step of the Getting Started is broken as doing:

import 'swiper/css';

throws this error: Cannot find module 'swiper/css' or its corresponding type declarations.

**Comment by igudy** [comment]
I'm still facing the same issue even today after installing swiper.

**Comment by jayeh001** [comment]
I can't get this to work even after creating swiper.d.ts file, declaring it. docs aren't even updated. I'm just going to delete this package and use something else, too much time spent on this.
