### ISSUE TITLE
Vertical slider stuck after slider reach to the end IOS (releaseOnEdges is true)

### ISSUE THREAD

**Issue by nastassiadanilova** [nolimits4web/swiper#6691]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-mousewheel-control-forked-yhuwc3?file=%2Fsrc%2FApp.jsx%3A39%2C32

### Bug description

When the slider reaches the end on mobile (IOS chrome, safari) it doesn't allow to scroll down to the rest of the page

```
<Swiper
      effect="fade"
      slidesPerView={1}
      direction="vertical"
      mousewheel={{
        thresholdTime: 500,
        releaseOnEdges: true,
      }}
      pagination={{
        clickable: true
      }}
      modules={[Pagination, Mousewheel]}
    >
```

### Expected Behavior

slider allows go to the rest page content

### Actual Behavior

slider stucks

### Swiper version

9.3.1

### Platform/Target and Browser Versions

IOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
#6381
