### ISSUE TITLE
Swipe stops working after the context menu appears when touching a picture

### ISSUE THREAD

**Issue by Eld3rt** [nolimits4web/swiper#6692]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/9y2bpk?file=%2Findex.html%3A1%2C1

### Bug description

On iOS devices, using Chrome Browser, if you press and hold your finger on the picture in the slider (to call the browser context menu), then after closing this menu, the swipe stops working.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

iOS 16.5, Chrome 113.0.5672.69

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by s-debnath** [comment]
We ended up running into this too.
