### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by iamjhay** [nolimits4web/swiper#6698]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/vjme97?file=%2Fsrc%2FApp.jsx%3A5%2C24

### Bug description

Using the thumb effect with Swiper, I realized that the thumbs parameter as thumbsSwiper and onSwiper as setThumbsSwiper continuously gave the error "Cannot convert undefined or null to object". But if the onSwiper property is removed code runs but the thumb effect doesn't work. I would love it if the team look this up asap. thanks!

import React, { useState } from "react";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";

import "./ListingSwiper.scss";

// import required modules
import { FreeMode, Navigation, Thumbs } from "swiper";

export default function ListingSwiper({ singleProduct }) {
  const [thumbsSwiper, setThumbsSwiper] = useState(null);

  return (
    <>
      <Swiper
        style={{
          "--swiper-navigation-color": "#fff",
          "--swiper-pagination-color": "#fff",
        }}
        loop={true}
        spaceBetween={10}
        navigation={true}
        thumbs={{ swiper: thumbsSwiper }}
        className="mySwiper2"
        pagination={{
          clickable: true,
        }}
        modules={[Thumbs, Navigation, FreeMode]}
      >
        {singleProduct.subProducts.images?.map((img, i) => (
          <SwiperSlide key={`img-${i}`}>
            <img
              src={img}
              alt={`img-${i}`}
              className="object-cover w-full h-full"
            />
          </SwiperSlide>
        ))}
      </Swiper>
      <Swiper
        onSwiper={setThumbsSwiper}
        grabCursor={true}
        loop={true}
        spaceBetween={10}
        slidesPerView={1}
        freeMode={true}
        watchSlidesProgress={true}
        modules={[FreeMode, Navigation, Thumbs]}
        className="mySwiper"
      >
        {singleProduct.subProducts.images?.map((img, i) => (
          <SwiperSlide key={`img-${i}`}>
            <img
              src={img}
              alt={`img-${i}`}
              className="object-cover w-full h-full"
            />
          </SwiperSlide>
        ))}
      </Swiper>
    </>
  );
}

### Swiper version

I tried in all feature, even downgrading my version to as low as 8.3

### Platform/Target and Browser Versions

Windows, chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by claritise** [comment]
same issue

**Comment by soupJian** [comment]
same issue

**Comment by stijnwesterhof** [comment]
same issue
