### ISSUE TITLE
activeSlide not being updated when used with touchevents.

### ISSUE THREAD

**Issue by nexflo** [nolimits4web/Swiper#67]
activeSlide gets updated on all events, but when using the slider with touch gestures (or emulated mouse gestures) activeSlide does not get updated to the current active slide

**Comment by joeyma** [comment]
Hi Guys, @nolimits4web i would like first to say your plugins are amazing. Now, i am using swiper and i would like to have a call back function on slide complete and do some really simple function to animate some elements in the active slide. For example
```
var pages = $('.swiper-pages').swiper({
        cssWidthAndHeight: true,
        grabCursor: true,
        mousewheelControl: true,
        hashnav: true,
        keyboardControl: true,
        onSlideChangeEnd: function (check for active slide here){
         $('h1').slideUp();
         $('.revealDiv').slideDown(2000);             
    }); 

```

The above method would be great for a general method which would apply for all the slide but also i was thinking if i could also check for the active slide index to call a function it would be a bit more versatile. Any efforts would be appreciated. Thanks

**Comment by joeyma** [comment]
I have tried this
```
var pages = $('.swiper-pages').swiper({
        cssWidthAndHeight: true,
        grabCursor: true,
        mousewheelControl: true,
        hashnav: true,
        keyboardControl: true,        
        onSlideChangeEnd : function(swiperHere) {
            $('h1').slideDown();
        }     
    });
But this doesn't check for the completed slide, it slide down all the h1's in other slides as well. I need to only animated the h1 in the current active slide.
```

**Comment by nolimits4web** [comment]
var pages = $('.swiper-pages').swiper({
        cssWidthAndHeight: true,
        grabCursor: true,
        mousewheelControl: true,
        hashnav: true,
        keyboardControl: true,        
        onSlideChangeEnd : function(swiper) {
            $('.swiper-slide').eq(swiper. activeIndex).find('h1').slideDown();
        }     
    });

**Comment by joeynimu** [comment]
Thank you @nolimits4web but it seems you have missed something. The h1 now doesn't slide down at all. Trying to figure out whatsup

**Comment by joeynimu** [comment]
I am not sure this is the best way of doing it but it works at the moment.
```javascript
var pages = $('.swiper-pages').swiper({
        cssWidthAndHeight: true,
        grabCursor: true,
        mousewheelControl: true,
        hashnav: true,
        keyboardControl: true,        
        onSlideChangeEnd : function(swiper) {
            // $('.swiper-slide').eq(swiper.activeIndex).find('h1').addClass('slide-down');
            // $('.swiper-slide-active').find('h1').slideDown();
            $('.swiper-slide-active').each(function(){
                 tl.from('.swiper-slide-active h1', 1, {opacity: 0, top: '-20px', right: '-100px'});
            });
            console.log(swiper.activeIndex); 
        }          
    });
```

**Comment by CorySchulz** [comment]
I'm having a similar issue with touch events not working. Even if I have a basic console.log('hello') in the onSlideChangeEnd function I won't see anything in the console. Haven't had any issues with this plugin in the past. Only happens when triggered by touch. Very strange.
