### ISSUE TITLE
Unable to resolve path to module 'swiper/element/bundle'

### ISSUE THREAD

**Issue by subhasish-smiles** [nolimits4web/swiper#6702]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

localhost

### Bug description

Using swiper with next js. 
I'm writing this code

```
import { register } from 'swiper/element/bundle';

register();

function MySwiper() {
  return (
    <swiper-container navigation="true" pagination="true">
      <swiper-slide class="blue-slide">Slide 1</swiper-slide>
      <swiper-slide class="yellow-slide">Slide 2</swiper-slide>
      <swiper-slide class="green-slide">Slide 3</swiper-slide>
    </swiper-container>
  );
}

export default MySwiper;
```

But it gives me import error
`Unable to resolve path to module 'swiper/element/bundle'`

Not sure what I'm doing wrong. Thanks in advance!

### Expected Behavior

It should import properly as I'm doing as per official doc only

### Actual Behavior

Gives me error

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Ubuntu 18.04 - Chrome 113

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871
