### ISSUE TITLE
Slide with a `overflow-y: scroll` break swipers horizontal touch events (on touch device)

### ISSUE THREAD

**Issue by konsultaner** [nolimits4web/swiper#6705]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiper-slider-js-rdjos8.stackblitz.io

### Bug description

If a swiper slide contains a div with the style `height: 100%` and an `overflow-y: scroll` or `overflow-y: auto` the regular horizontal touch swipe is not working anymore. I use it to have scrollable content within the swiper slides. It used to work when I used the ionic6 swiper module for angular, but since you need to integrate swiper yourself in ionic7, i got this issue. 

It seems that this is a pure css issue. When I remove:

```css
.swiper-horizontal {
    touch-action: pan-y;
}
```

I can swipe again, but not vertically scroll. I can get either or not both.

### Expected Behavior

Swiping should work as expected.

### Actual Behavior

Horizontal swipe breaks. only the touch start event is fired and one touch move but not more.

### Swiper version

9.x.x

### Platform/Target and Browser Versions

Chrome 113, XPS17 with touch screen, or android 13 browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate. (#6363 doesn't work for the stackblitz I have)
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please do the issues search first, it is related to touch-actions CSS

**Comment by konsultaner** [comment]
solved by not using a nested element then https://github.com/nolimits4web/swiper/issues/6363 will work
