### ISSUE TITLE
Looping with slidesPerView: auto does not work with variable size images

### ISSUE THREAD

**Issue by simonhrogers** [nolimits4web/swiper#6711]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-centered-auto-forked-y1pnir?file=%2Fsrc%2FApp.jsx%3A25%2C1

### Bug description

As described in issue https://github.com/nolimits4web/swiper/issues/6559 and https://github.com/nolimits4web/swiper/issues/6700 it is not possible to use looping with slidesPerView: auto unless all images are the same size.

Both these issues were closed and locked without really addressing the user’s question – will the documentation be updated to reflect this limitation, or will the issue be addressed in a future release?

It would be really good if different width images could be supported but if it’s beyond the scope of the project then it would still be super helpful to have documented as something that is unfeasible.

Thanks so much for your work on this.

### Expected Behavior

The slides should start centered and transitions between slides should not be jittery / mis-aligned. 

### Actual Behavior

The animations are frequently choppy post- one or two slides which have different widths, its as-if Swiper gets confused and loses the ability to animate the correct distances so slides start jumping from an incorrect animation start point. 

### Swiper version

9.3.2

### Platform/Target and Browser Versions

All browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Where is the issue? I open the link you have provided (the one i posted previously), and this is what i see:


https://github.com/nolimits4web/swiper/assets/999588/9cb4a303-06ea-4bc0-9b2d-18069083b210

**Comment by simonhrogers** [comment]
It looks like this in Chrome, Version 113.0.5672.126 (Official Build) (x86_64) on macOS 12.3.1. 

https://github.com/nolimits4web/swiper/assets/12583581/9e089a38-193c-4d79-a6dd-fa6301dad4f4

**Comment by simonhrogers** [comment]
And Safari Version 15.4 (17613.1.17.1.13)

**Comment by simonhrogers** [comment]
@nolimits4web Would you be willing to reopen this based upon the above? As it is clearly an issue most recent and older versions?

**Comment by simonhrogers** [comment]
@nolimits4web do you have any best guesses on what might be causing this if we were to look into it for you?

**Comment by simonhrogers** [comment]
(This jumping behaviour shown in the video above still occurs in 9.4.0: https://codesandbox.io/p/sandbox/swiper-react-centered-auto-forked-3sf2jp?file=%2Findex.html%3A1%2C1)

**Comment by nolimits4web** [comment]
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one
