### ISSUE TITLE
Initialization slidesPerView wrong

### ISSUE THREAD

**Issue by maxtotheguenther** [nolimits4web/swiper#6712]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Can provide if needed!

### Bug description

Hey Guys,

im having a nasty flickering issue on my website. I tried everything, but nothing seems to fix this issue. 
In the initalization process swiper renders only 1 slidesPerView instead of the configured 7 slidesPerView.
When the intializiation process is finished (within ms) swiper renders the configured 7 slidesPerView. But the user experiences a pretty bad flickering.

**While initializing:**
![image](https://github.com/nolimits4web/swiper/assets/35257419/28062221-1ffd-4bc5-94aa-a16e07f47cc6)

**When done initializing:**
![image](https://github.com/nolimits4web/swiper/assets/35257419/282f68de-fa27-473c-ad8e-4420930e116a)

### Code

```jsx
 <section>
    <div className="mx-auto max-w-screen-2xl px-4 sm:px-6 lg:px-8">
      <div>
        <h2 className="text-xl font-bold text-gray-900 dark:text-gray-50">
          Categories
        </h2>
      </div>
      <Carousel>
        {props.subcategories.map((subcategory) => (
          <SwiperSlide key={subcategory.id}>
            <CategoryCard
              href={`/${props.category.slug}/${subcategory.slug}`}
              category={subcategory}
            />
          </SwiperSlide>
        ))}
      </Carousel>
    </div>
  </section>
```

**Carousel Component**

```ts
const defaultBreakpoints = {
  max: 2.5,
  640: 3.5,
  768: 4.5,
  1024: 7.5,
};
type Breakpoint = keyof typeof defaultBreakpoints;
type Breakpoints = typeof defaultBreakpoints;

export const Carousel = (
  props: SwiperProps & {
    children: ReactNode;
    breakpoints?: Breakpoints;
  }
) => {
  const breakpoints = props.breakpoints || defaultBreakpoints;
  const [{ reachedStart, reachedEnd }, setReached] = useState<{
    reachedStart: boolean;
    reachedEnd: boolean;
  }>({ reachedStart: true, reachedEnd: false });
  const slidesLength = React.Children.count(props.children);

  return (
    <Swiper
      autoHeight
      className={cn("select-none", props.className)}
      spaceBetween={2}
      onRealIndexChange={({ activeIndex, currentBreakpoint }) => {
        const breakpoint: Breakpoint = currentBreakpoint as Breakpoint;
        const slidesPerView = breakpoints[breakpoint];
        setReached({
          reachedStart: activeIndex === 0,
          reachedEnd: slidesLength - slidesPerView + 0.5 === activeIndex,
        });
      }}
      breakpoints={{
        280: {
          slidesPerView: breakpoints.max,
          slidesPerGroup: 3,
        },
        640: {
          slidesPerView: breakpoints[640],
          slidesPerGroup: 3,
        },
        768: {
          slidesPerView: breakpoints[768],
          slidesPerGroup: 3,
        },
        1024: {
          slidesPerView: breakpoints[1024],
          slidesPerGroup: 3,
        },
      }}
    >
      {!reachedStart && <PrevHandle />}
      {props.children}
      {!reachedEnd && <NextHandle />}
    </Swiper>
  );
};

```

You can experience the similar behaviour if you use the demo https://swiperjs.com/demos#slides-per-view and a plain NextJs Project.

### Swiper version

9.3.1

### Platform/Target and Browser Versions

macOS, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by peipei818** [comment]
I also have this problem, how to fix it?

**Comment by nolimits4web** [comment]
Don't expect breakpoints to work on server side - it is impossible so apparently you have flickering. You can hide or make slider transparent until it initialized on client

**Comment by vicasas** [comment]
@nolimits4web Here I also have the same problem, with or without breakpoints the same thing happens.

In my case I only have the prop `slidesPerView='auto'` but in the first render you always see 1 slide for a few seconds and in the second render it just looks normal.
