### ISSUE TITLE
Swiper changes index when I update number of slides or resizing when `centeredSlides` and `centeredSlidesBoundary`

### ISSUE THREAD

**Issue by Jeysef** [nolimits4web/swiper#6713]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-centered-auto-forked-1q3mh2?file=%2Fsrc%2FApp.jsx%3A62%2C12

### Bug description

When Swiper is firstly rendered the first slide (with index 0) is fully visible, correctly, but when items change, the swiper moves itself and the first slide is not completely visible. Also, the onSlideChange function is called with changed index

### Expected Behavior

The index should be the initial index (0), and the onSlideChange function should not be called when just updating items.

### Actual Behavior

The index is automatically set to any index, not always 0. the  onSlideChange is called on resize or updated items.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Windows, Chrome, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how centeredSlidesBounds works, on certain screen size, for example it prevents slide 2 to be centered, so it moves the slider to the closest possible position.
