### ISSUE TITLE
Free Mode - Android - Two Fingers to scroll

### ISSUE THREAD

**Issue by brian-open** [nolimits4web/swiper#6715]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://nationalleprechaunmuseum.flywheelsites.com/story/

### Bug description

When scrolling on android devices the user must use two fingers to move left or right.
Swiper has been set to freeMode to allow the user to explore the areas in the slide.

### Expected Behavior

User should be able to scroll left or right using one finger. On iOS the user only needs to use one finger to scroll left or right.

### Actual Behavior

On android it is very jittery and the swiper slide barely moves when attempting to scroll left or right.

### Swiper version

8.4.7

### Platform/Target and Browser Versions

Android 12, Android 13 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper doesn't require 2 fingers to scroll https://swiperjs.com/demos/150-freemode/core
