### ISSUE TITLE
Swiper 9 out of sync if loop mode is enabled

### ISSUE THREAD

**Issue by wpsoul** [nolimits4web/swiper#6720]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/igor-sunz/pen/ExdByLm

### Bug description

If you enable Loop and sync between two sliders, everything goes crazy and out of sync. In the same time, on swiper 6, everything is working 

[https://codepen.io/italosimpli1/pen/VwmPYoR](url)

### Expected Behavior

Slides are synced with each other

### Actual Behavior

Everything is broken and out of sync, weird jumping to wrong slide

### Swiper version

9.3.2

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use Thumbs module for that

**Comment by wpsoul** [comment]
This is not a solution. I made codepen just to show issue, but I need controller because it works as synchronization between slides. While Thumbs module is working only on click. Currently, as temporal solution I built custom function for slideChange, but I hope that controller with loop will be fixed in future
