### ISSUE TITLE
Lazy loading css import Not working

### ISSUE THREAD

**Issue by spirituelle** [nolimits4web/swiper#6728]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/kd3yur?file=%2Fsrc%2FApp.jsx%3A1%2C1

### Bug description

while i try to import lazy loading css by: import 'swiper/css/lazy';
i get this error in next js: "react": "next": "^13.4.3", "18.2.0", "swiper": "^9.3.2",
Package path ./css/lazy is not exported from package

### Swiper version

9.3.2

### Platform/Target and Browser Versions

macOs chrome Version 114.0.5735.90 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Do you see such lazy css anywhere in docs?
