### ISSUE TITLE
Syntax error in swiper.scss

### ISSUE THREAD

**Issue by YOKAICODE** [nolimits4web/swiper#6729]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io

### Bug description

Syntax error in swiper.scss
Line number 33, class selector character is missing,
```
.swiper,
swiper-container
```

```
.swiper,
.swiper-container
```

### Expected Behavior

```
.swiper,
.swiper-container {
  margin-left: auto;
  margin-right: auto;
  position: relative;
  overflow: hidden;
  list-style: none;
  padding: 0;
  /* Fix of Webkit flickering */
  z-index: 1;
  display: block;
}
```

### Actual Behavior

```
.swiper,
swiper-container {
  margin-left: auto;
  margin-right: auto;
  position: relative;
  overflow: hidden;
  list-style: none;
  padding: 0;
  /* Fix of Webkit flickering */
  z-index: 1;
  display: block;
}
```

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by EliezerB123** [comment]
@YOKAICODE 

Working as intended, isn't it? 

Swiper-container isn't a class, it's a tag. Therefore it shouldn't have a .
