### ISSUE TITLE
Virtual mode adding to many slides to the dom when used alongside the loop mode

### ISSUE THREAD

**Issue by rameauv** [nolimits4web/swiper#6731]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-lazy-load-images-forked-5ic8zb?file=%2Findex.html%3A66%2C24

### Bug description

Preconditions:

Initial slide at index 0
virtual: true
loop: true

Like when the loop mode is not enabled, only 3 slides should be present in the dom (active, previous, next), but there is actualy 4.

This can be problematic in situation where there is heavy contents in the slides and only the minimum amount of slides should be added to the dom.

### Expected Behavior

Like when the loop mode is not enabled, only 3 slides should be present in the dom (active, previous, next), but there is actualy 4.

### Actual Behavior

Only 3 slides should be added to the dom

### Swiper version

9.3.2

### Platform/Target and Browser Versions

macOS 13.0.1 (22A400) intel, chrome 113.0.5672.77 (Official Build) (x86_x64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Can't even imagine a situation when 1 extra slide in DOM can be problematic. In loop it requires 1 more additional slide
