### ISSUE TITLE
Swiper z-index position superimposed.

### ISSUE THREAD

**Issue by mifeex** [nolimits4web/swiper#6736]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://beonix.art

### Bug description

Hi!
We faced with bug when swiper z-index position superimposed. I.e. we see all slides at one screen but first slide is over the second second is over third etc. You can see this bug at the picture I've attach.

![image](https://github.com/nolimits4web/swiper/assets/60233967/7c035127-7fe6-4758-8c8b-c49553232a11)

The code which we use to setup the swiper is:
`
const options: SwiperOptions = {
    allowTouchMove: true,
    autoplay: {
      delay: 8000,
      disableOnInteraction: false,
    },
    autoHeight: true,
    effect: 'fade',
    fadeEffect: {
      crossFade: true,
    },
    loop: true,
    pagination: {
      bulletClass: slider('bullet'),
      bulletActiveClass: slider('bullet-active'),
      horizontalClass: slider('horizontal'),
    },
    slideToClickedSlide: true,
    observer: true,
    modules: [Autoplay, EffectFade, Navigation, Pagination],
  }
`

slider.css `
.slider {
    width: 100%;
    overflow: visible;

    &__bullet {
      display: inline-block;
      width: 8px;
      height: 8px;
      margin: 0 11px;
      background: var(--transparent-background-3);
      filter: blur(2px);
      border-radius: var(--border-radius-circle);
    }

    &__bullet-active {
      width: 12px;
      height: 12px;
      background: var(--transparent-background-2);
    }

    &__horizontal {
      width: 100%;
      position: absolute;
      display: flex;
      top: 13px;
      align-items: center;
      justify-content: center;
      text-align: center;
      transition: 0.3s opacity;
      transform: translate3d(0, 0, 0);
      z-index: 1;

      @media (--desktop-s) {
        top: 26px;
      }
    }

    img {
      width: 100%;
      height: 100%;
    }
  }
`

Do you have any ideas?

### Swiper version

^9.2.0

### Platform/Target and Browser Versions

macOS Chrome, Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The issue demo link doesn't contain issue, so seems to be resolved

**Comment by sedx** [comment]
Faced same issue. Swiper version 10.0.4.

Fixed as recommenced:

```
<Swiper
  {...options}
  {...props}
  onSlideChange={(swiper) =>
    isNaN(swiper.realIndex) && swiper.slideTo(0)
  }
>
```

BTW Reproduction link has issue ;)
