### ISSUE TITLE
A period seems to be missing in swiper-bundle.min.css.

### ISSUE THREAD

**Issue by tt-uonuma-js** [nolimits4web/swiper#6739]
A period seems to be missing in swiper-bundle.min.css.

![swiper-container](https://github.com/nolimits4web/swiper/assets/135770400/9b65d422-5a0a-4f06-b002-f16c9322dd15)

This is the 1st time for me to post an issue on GitHub. Please forgive me if I am rude.

**Comment by nolimits4web** [comment]
It is not, it is declaration for web component

**Comment by tt-uonuma-js** [comment]
Thanks a lot. I didn't know web component. Sorry for taking up your time.
