### ISSUE TITLE
The "opacity: 0;" property does not apply to slides.

### ISSUE THREAD

**Issue by nineNnine** [nolimits4web/swiper#6740]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/nineNnine/pen/zYMYKJw

### Bug description

Yesterday I spent ALL day solving a problem where `opacity: 0;` is not applied to slides when the slider is set to `effect: fade`.
Finally, I solved this problem by prescribing the following:

<img width="292" alt="sublime_text_0ew4YHXHR8" src="https://github.com/nolimits4web/swiper/assets/127664719/9c0611a9-3a29-41fc-aa63-1ae3215f286d">

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Windows Microsoft Edge 114.0.1823.37

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is a crossFade parameter for that

**Comment by jongbonga** [comment]
> There is a `crossFade` parameter for that

even with crossfade on, I'm experiencing the same issue. The only difference is that I have virtual slides

**Comment by Jones-S** [comment]
I have the same problem.
Even without setting any effects.
Weirdly I have only the third image that is set to opacity:0;

If I have two items per view, it is my 4th item that remains in opacity:0; mode.

I can like the original post suggests override with !important, but this is a bit hacky.

I would like to understand why the opacity is set to 0 in the first place. Is it because of some lazy loading?
(Although I have not set this option to true)...

Thanks for any hints.

**Comment by Jones-S** [comment]
Also I realize that this
`transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 48, 0, 1);` is set. This shifts my image a bit to the bottom, so I would have to override this too.

Swiper seems to set these transforms and opacity for items which are further away from the initial image. But I don't know how I can either reset these properties upon appearance on screen or override it without `!important;`

**Comment by Jones-S** [comment]
Never mind. In my case it was some reveal animation that was set within the component. It had nothing to do with swiper. Sorry about that!
