### ISSUE TITLE
removeAllSlides not working

### ISSUE THREAD

**Issue by kubiqsk** [nolimits4web/swiper#6748]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-infinite-loop-forked-x3d92r?file=%2Findex.html%3A82%2C7-82%2C29

### Bug description

`removeAllSlides` throws errors `Uncaught TypeError: Cannot read properties of undefined (reading 'swiperSlideSize')` when swiper is has `slidesPerView: 'auto'` and `centeredSlides: true` and `loop: true`

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Was fixed in 36ef2e608843b4c83a5dc7ecde30aa71794f639e
