### ISSUE TITLE
TypeError: undefined is not an object(evaluating swiper.freeMode.onTouchMove)

### ISSUE THREAD

**Issue by hirbod** [nolimits4web/swiper#6751]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Nope

### Bug description

9.4.0 introduced this bug. I am not using freeMode, just Swiper virtual
The issue happens when I want to use my finger to slide.

Downgrading back to 9.3.2 fixed the issue.

```tsx
            <Swiper
              modules={[Virtual, Keyboard, Mousewheel]}
              height={windowHeight}
              width={windowWidth}
              keyboard
              initialSlide={clamp(initialScrollIndex, 0, data.length - 1)}
              virtual={{
                enabled: true,
                addSlidesBefore: 1,
                addSlidesAfter: 2,
                cache: false,
              }}
              direction="vertical"
              onRealIndexChange={onRealIndexChange}
              onReachEnd={fetchMore}
              threshold={isMobileWeb() ? 0 : 25}
              noSwiping
              noSwipingClass="swiper-no-swiping"
              mousewheel={{
                noMousewheelClass: "swiper-no-swiping",
                sensitivity: 1.1,
                thresholdTime: 800,
              }}
            >
              {data.map((item, index) => (
                <SwiperSlide key={item.nft_id} virtualIndex={index}>
                  <ItemKeyContext.Provider value={index}>
                    <FeedItem nft={item} itemHeight={windowHeight} />
                  </ItemKeyContext.Provider>
                </SwiperSlide>
              ))}
            </Swiper>
```

### Expected Behavior

Being able to swipe up and down (single item, full height like tiktok)

### Actual Behavior

TypeError: undefined is not an object(evaluating swiper.freeMode.onTouchMove)

### Swiper version

9.4.0

### Platform/Target and Browser Versions

iOS 16.4.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by ikangjie** [comment]
I also encountered this issue:
Uncaught TypeError: Cannot read properties of undefined (reading 'onTouchMove') at Swiper.onTouchMove

**Comment by ikangjie** [comment]
version: 9.4.0
![9 4 0](https://github.com/nolimits4web/swiper/assets/48464397/29726099-73d8-4fbf-8179-6c915307f0c9)

**Comment by adrocodes** [comment]
Encountering the same error. Next `v13.4.4`, Swiper `v9.4.0`. Nothing special props wise, other than using the `EffectCoverflow` module.

Downgrading to `v9.3.2` fixed the issue for me.
Unless you need something in `v9.4.0` @beyourahi maybe downgrade for now.
