### ISSUE TITLE
Click (touch) events blocked for a short time after swiping

### ISSUE THREAD

**Issue by kubagp1** [nolimits4web/swiper#6754]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-default-forked-u7yty5?file=%2Fsrc%2FApp.jsx

### Bug description

When clicking somewhere quickly after swiping to change a slide, click events on elements not related to the swiper are not registered. This only happens when using touch input (emulated or real).

https://user-images.githubusercontent.com/37304664/217113994-b803b66c-4c4d-4a30-ac83-2e5f91843eee.mp4

NOTE: I opened the same issue (#6355) once, but after posting tried few things out in the codesanbox  like changing Swiper version to 7. When @nolimits4web reviewed my previous issue I forgot to revert those changes and my issue was closed (due to version 7 being used) without a solution or fix. I apologize for my mistake. The issue is still valid.

### Expected Behavior

Click events on external elements should work as usual.

### Actual Behavior

Click events on external are not triggered when clicking on them shortly after swiping the swiper.

### Swiper version

9.4.0

### Platform/Target and Browser Versions

Chrome 114.0.5735.110 (Windows 10)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by kubagp1** [comment]
Additional information: i used monitorEvents() to check what events are passed to the external element. Normally it looks like this: 
![image](https://github.com/nolimits4web/swiper/assets/37304664/04806e79-47e7-4fe8-a221-7a1e3355e433)
but when i click (touch) quickly after swiping the swiper some are missing:
![image](https://github.com/nolimits4web/swiper/assets/37304664/404c7194-d6f5-4260-9fdb-26a34ac4b314)
All of the events after `touchEnd` are not there.

**Comment by kubagp1** [comment]
Additional information: based on my debugging attempts, my touch gets captured by `#document.touchstart` (that's what Chrome Devtools says after breaking on touch event) and runs `function dummyEventListener() {}`. I guess(!) that's what stops propagation.
![image](https://github.com/nolimits4web/swiper/assets/37304664/b6779925-c19d-4c0c-afc9-5253d5a5e4ee)

**Comment by kubagp1** [comment]
This problem doesn't occur with `cssMode: true`, but `cssMode` doesn't support many important features.

**Comment by iharshspatel** [comment]
@kubagp1 did you find any workaround for this?

**Comment by kubagp1** [comment]
> @kubagp1 did you find any workaround for this?

Nope. I'm using a different carousel library until this is fixed.

**Comment by nolimits4web** [comment]
Not a Swiper bug, it is browser's bug or feature related to handling touch-action CSS prop. It can be replicated on any simple element such as `<div style="touch-action: pan-y; height: 200px; width: 100%; background-color: blue;">Test</div>`

**Comment by kubagp1** [comment]
Then why it's only present in Swiper? Any other library i tested didn't have this behaviour.
