### ISSUE TITLE
Can't scroll in ios 12 safari by Swiper version 9

### ISSUE THREAD

**Issue by JOECHAN890** [nolimits4web/swiper#6756]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/010-default/core

### Bug description

Can't scroll in ios 12 safari by Swiper version 9

### Swiper version

9.4.1

### Platform/Target and Browser Versions

ios 12.5.7 safari 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
No support for ios 12
