### ISSUE TITLE
Web Element - Migration - styling of swiper-wrapper

### ISSUE THREAD

**Issue by LefterisL** [nolimits4web/swiper#6761]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

/

### Bug description

Hello all,

I am trying to migrate from Swiper v5 to Swiper v9 and to use the Web Component version of it.

We have a great dependency and multiple usages across our project on Swiper (via Vue).

I've hit a wall however because in our current implementations we have a great deal of CSS in place that "messes" with the `swiper-wrapper` div.

The only thing that I came CLOSE to making it work is by injecting a CSS file which will then "override" and apply whichever style is needed. Tried injecting the styles but it just won't work since we have multiple of variables and a bit of complex SCSS which makes it practically impossible.

One thing I've tried was to create another "wrapper" with the class `swiper-wrapper` around the slide components.
This works amazingly well (my guess is since this div is not part of the shadow element) BUT the problem here is that it kind of bricks the behavior of the swiper. Everything is rendered nice but no events, cannot swipe nothing.

My main question is am I missing something ? What would be the most optimal way to transition to the Web Component version when it comes to CSS part here ?

### Swiper version

9.3.2

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It has part="wrapper" in v10
