### ISSUE TITLE
TypeScript Error with onSwiper Prop in Vite, TSX, and React

### ISSUE THREAD

**Issue by CodePhilanthropist** [nolimits4web/swiper#6771]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/CodePhilanthropist/swiper-issue

### Bug description

Environment:

Vite Version: 9.4.1
React Version: 18.2.0
Swiper JS Version: 9.4.1
TypeScript Version: 5.0.2
Browser: Microsoft Edge Version 114.0.1823.51 (Official build) (64-bit)
Operating System: Windows 11

**Issue:**
While using Swiper JS within a Vite, React, and TypeScript (TSX) environment, I encountered a TypeScript error related to the onSwiper prop. I am attempting to pass the setThumbsSwiper function (from React's useState hook) to onSwiper to get the Swiper instance.

### Expected Behavior

I expect to be able to pass the setThumbsSwiper function to the onSwiper prop without any TypeScript errors, as it should be used to set the state of the thumbsSwiper to the Swiper instance.

### Actual Behavior

TypeScript throws an error, indicating that the type 'Dispatch<SetStateAction<null>>' is not assignable to type '(swiper: Swiper) => void'.

Additional Information:
This appears to be a type incompatibility issue between the expected type for the onSwiper prop in Swiper and the setThumbsSwiper function returned from React's useState hook.

### Swiper version

9.4.1

### Platform/Target and Browser Versions

Microsoft Edge Version 114.0.1823.51  

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by R3flector** [comment]
Same problem:

`Type 'Dispatch<SetStateAction<null>>' is not assignable to type '(swiper: Swiper) => void'.
  Types of parameters 'value' and 'swiper' are incompatible.
    Type 'Swiper' is not assignable to type 'SetStateAction<null>'.
      Type 'Swiper' provides no match for the signature '(prevState: null): null'.ts(2322)
swiper-react.d.ts(23, 3): The expected type comes from property 'onSwiper' which is declared here on type 'IntrinsicAttributes & RefAttributes<SwiperRef> & SwiperProps'`

**Comment by R3flector** [comment]
I tried on pure nextjs without typescript:

Unhandled Runtime Error
TypeError: can't convert undefined to object

**Comment by CodePhilanthropist** [comment]
Thank you for the hint, @R3flector. However, when I build my app, it doesn't work because it is written in TypeScript. This is a TypeScript typing issue.

**Comment by J0T0S0** [comment]
Could not find a declaration file for module 'swiper'.

**Comment by gabrielgatu** [comment]
For me updating typescript to latest version (5.1.6) resolved the issue

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
