### ISSUE TITLE
Fully visible slides

### ISSUE THREAD

**Issue by Craigy-** [nolimits4web/swiper#6773]
### Clear and concise description of the problem

If I use the 'watchSlidesProgress' option - swiper adds a class 'swiper-slide-visible' to the visible slides.
But it works if slide is visible at least for 1 pixel.

For me it will be very useful to get slide if it is fully visible - for its entire width or height.

### Suggested solution

Add something like a new class 'swiper-slide-fullyvisible'.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by lleeeuuuuanchik** [comment]
♥

**Comment by evgenyshev** [comment]
This feature is very necessary!

**Comment by Craigy-** [comment]
Thank you very much!
