### ISSUE TITLE
bug after 9.3: swiper does not initialize until window is resized on some resolutions

### ISSUE THREAD

**Issue by hheexx** [nolimits4web/swiper#6775]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

///

### Bug description

Swiper does not initialize until window is resized on some resolutions

9.2 works 
9.3 & 9.4 broken

### Expected Behavior

swiper should initialize

### Swiper version

9.3.0

### Platform/Target and Browser Versions

windows && mac   chrome && firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
No live example
