### ISSUE TITLE
bug after 9.3: swiper does not initialize until window is resized on some resolutions

### ISSUE THREAD

**Issue by hheexx** [nolimits4web/swiper#6776]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stage.cx.rs/prodaja-nekretnina/beograd/57264/jednoiposoban-stan-internacionalnih-brigada-vracar

### Bug description

Swiper does not initialize until window is resized on some resolutions

9.2 works
9.3 & 9.4 broken

Swiper is used for main gallery.
Problem happens only on larger resolutions, I would say larger then full HD and not on all machines.
It could be race condition?

As there are no lot of changes in 9.3 I hope this is enough info to hint you at right direction....

### Expected Behavior

should work

### Actual Behavior

does not work

### Swiper version

9.3.0

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Would be good to see codesanbox,  otherwise it looks to me as implementation issue

**Comment by hheexx** [comment]
> Would be good to see codesanbox, otherwise it looks to me as implementation issue

9.2 works good we tried multiple times. So it is clearly regression on your part.
I can debug more in 1-2 weeks timeframe.

Have you succeeded reproducing the problem on url provided? 


any hints on what change in 9.3 could be causing this?

**Comment by nolimits4web** [comment]
No I can't see issue in that page

**Comment by cb2004** [comment]
When I go to your link using my large desktop the Swiper is not initialised, on browser resize it is then initialised. If you post a code example then the issue (if it exists) will be easier to find.

**Comment by hheexx** [comment]
@cb2004 thanks for confirmation.

Here is code that initializes the swiper:

    var enableThumbs = window.outerWidth >= 1200;
    // this may not be needed but it lools like its fixing rare bug when changing properties swiper breaks.
    if (this.swiperPlugin) {
      this.swiperPlugin.destroy();
      this.swiperPlugin = null;
    }
    if (this.thumbSwiperPlugin) {
      this.thumbSwiperPlugin.destroy();
      this.thumbSwiperPlugin = null;
    }

    if (enableThumbs) {
      this.thumbSwiperPlugin = new Swiper(this.swiperThumb.nativeElement, {
        modules: [Navigation, Controller, FreeMode, Thumbs],
        centeredSlides: true,
        slidesPerView: 'auto',
        touchRatio: 0.2,
        slideToClickedSlide: true,
        // centerInsufficientSlides: true,
        spaceBetween: 10,
        freeMode: true,
        watchSlidesProgress: true,
      });
    }

    this.swiperPlugin = new Swiper(this.swiperBig.nativeElement, {
      modules: [Navigation, Controller, FreeMode, Thumbs],
      spaceBetween: 10,
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      thumbs: { swiper: this.thumbSwiperPlugin },
    });

    if (enableThumbs) {
      this.swiperPlugin.controller.control = this.thumbSwiperPlugin;
    }`
