### ISSUE TITLE
hashNavigation broken

### ISSUE THREAD

**Issue by elibarzilay** [nolimits4web/swiper#6789]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/quiet-dew-4nc59v?file=/index.html

### Bug description

I've tried multiple ways to get `hashNavigation` to work, with either the current 9.4.1 or a build of `next`, and none of these work.

I've put the minimized example in that codesandbox, but it's pretty short and should be self contained, so also included here:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
  <!-- <link rel="stylesheet" href="lib/swiper-bundle.min.css" /> -->
</head>

<body>
  <div class="swiper">
    <div class="swiper-wrapper">
      <div class="swiper-slide">
        Foo
      </div>
      <div class="swiper-slide">
        Bar
      </div>
    </div>
  </div>
</body>

<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<!-- <script src="lib/swiper-bundle.min.js"></script> -->
<script>
  const swiper = new Swiper(".swiper", {
    keyboard: { enabled: true, pageUpDown: false },
    hashNavigation: { enabled: true, replaceState: true, watchState: true },
  });
</script>

</html>
```

### Expected Behavior

Get proper numbers in the URL hash fragment

### Actual Behavior

Usually gets to a broken `#null`

### Swiper version

9.4.1, 10.0.0-beta.5

### Platform/Target and Browser Versions

Win 11, MSEdge / Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please, check documentation and demos
