### ISSUE TITLE
Handling missing `data-hash`

### ISSUE THREAD

**Issue by elibarzilay** [nolimits4web/swiper#6791]
### Clear and concise description of the problem

When there are only some slides with a `data-hash`, getting to one without it will put a `#null` in the URL.  The effect on user interaction is harmless, but for people who'd pay attention to the URL it looks like a bug, and it's also a likely bug on the slideshow author's side.

(This is indirectly related to #6789 -- sorry about the noise there, I somehow messed things up with running into a problem that was probably solved in 69acab4.)

### Suggested solution

It would be better if such slides would just drop the `#null` from the URL, which IIUC, would make the overall interaction the same.

### Alternative

Alternatively, it could assign an ordered integer to these slides, or a hash based on the slide contents.  This would have the added benefit of making `hashNavigation: true` work immediately without adding the data attributes to slides.

(It's easy to just add `document.querySelectorAll("div.swiper-slide").forEach((d, n) => d.dataset.hash = n + 1);`, but why not make it possible to do so automatically...?)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Why do we need to support when it missing, data-hash is a requirement for it work. You can add data hashes on your side with JS
