### ISSUE TITLE
Mobile/touch swiping issue with v9.0+

### ISSUE THREAD

**Issue by GashyDev** [nolimits4web/swiper#6793]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://slidingwardrobes.discoveryecommerce4.co.uk/

### Bug description

Sliding motion on touch devices getting "stuck"

### Expected Behavior

Full sliding motion, no sticking

### Actual Behavior

Since the shift to `9.0.0`, I have noticed sliding issues when it comes to some form of touch input or on mobile, it's as if it doesn't do a complete swipe and the user gets stuck on the slide.

It seems to happen in Chromium's inspect element "device toolbar" under a device that has a touch input, but is fine on a non-touch one (I've attached a video).

This issue also occurs on a physical device but seemingly only on my Android (Samsung galaxy s8+), but works completely fine on my boss's iPhone.

https://github.com/nolimits4web/swiper/assets/34476863/fcd5827b-49f0-4ee6-8618-2676dbadab36

I feel it is a bug, because if I roll back to `8.4.7`, the expected behaviour is fulfilled both in the simulated device and physical.

https://github.com/nolimits4web/swiper/assets/34476863/edabf474-a6a8-4ee9-ab22-7cad71feaaaa

### Swiper version

v9.4.1 (anything v9.0.0+)

### Platform/Target and Browser Versions

MacOS (13.4.1) Brave browser, Samsung Galaxy s8 (latest update) Chrome + Samsung Internet

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look for issues on your side. Ad you see it works perfectly fine in all official demos
