### ISSUE TITLE
Vertical thumbs issue

### ISSUE THREAD

**Issue by ttnbtfy** [nolimits4web/swiper#6801]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/notrealdev/pen/oNQwbQY

### Bug description

The vertical thumbs slider can't calculate the height

### Swiper version

9.4.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
because it doesn't have any height set in your styles
