### ISSUE TITLE
Coverflow effect doesn't work on MacOS Safari 16.5

### ISSUE THREAD

**Issue by ivo0126** [nolimits4web/swiper#6802]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/funny-framework-69yj35?file=/index.html

### Bug description

Creating a simple carousel with Swiper Element works on Chrome and Safari 16.1, but not on Safari 16.5

### Expected Behavior

<img width="1728" alt="image" src="https://github.com/nolimits4web/swiper/assets/23344502/95211169-414f-4c27-abfe-b41133852519">

### Actual Behavior

<img width="1728" alt="image" src="https://github.com/nolimits4web/swiper/assets/23344502/d1c66d8f-0336-4073-8560-3589f083a43e">

### Swiper version

9 (https://cdn.jsdelivr.net/npm/swiper@9/swiper-element-bundle.min.js)

### Platform/Target and Browser Versions

MacOS Safari 16.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate #6650
