### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by GiyoMoon** [nolimits4web/swiper#6803]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/GiyoMoon/swiper-modules-error

### Bug description

Importing modules since v10 doesn't work as expected when using typescript.
- Importing from `swiper` gives a runtime error. E.g `import { Navigation } from 'swiper';`
- Importing from `swiper/modules` gives a typescript error. E.g `import { Navigation } from 'swiper/modules';`

### Expected Behavior

I expect that the import from `swiper` either doesn't work anymore, or no runtime error is being thrown.
Also, the import from `swiper/modules` shouldn't give a typescript error.

### Actual Behavior

I'm having issues while trying to import modules. It looks like that the modules have to be imported from `swiper/modules` since v10, but this gives a typescript error:
```typescript
import { Navigation } from 'swiper/modules';
```
^ gives: `Cannot find module 'swiper/modules' or its corresponding type declarations.`

Importing from `swiper` directly works at first sight, but then a runtime error is thrown:
```typescript
import { Navigation } from 'swiper';
```
^ gives this error when trying to render the swiper:
![image](https://github.com/nolimits4web/swiper/assets/36984337/dae16366-e1df-487a-a450-785d92b792d6)

### Swiper version

10.0.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by RobinKamps** [comment]
ran into the same error - quick fixed by `import { SwiperOptions, Swiper } from './types/index.d';` (without `.ts`)

**Comment by RobinKamps** [comment]
Thank you very much - 10.0.2 imports are working again.

**Comment by GiyoMoon** [comment]
Thanks! works again
