### ISSUE TITLE
Swiper element conflict with other library on touch events

### ISSUE THREAD

**Issue by giodum** [nolimits4web/swiper#6805]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/8h4zgd?file=%2Findex.html

### Bug description

Hi everybody, I am facing a very frustrating problem while using inside my Nuxt 3 project: there are some conflict problems with Swiper.js (I am using version 9.3.2 - element bundle) and other libraries that listen to touch events (like p5.js in my case).
It seems that Swiper.js triggers in a messy way some touch events (touchStart, touchMove and touchEnd), and this leads to conflicts and console errors.

In order to see the problem it is just necessary to open the console and move to the next slide. Errors will be generated on the console.

### Expected Behavior

Swiper should not conflict with other libraries such as p5.js.

### Actual Behavior

Swiper have an event called `touchStart` (note uppercase S) which is perfectly fine and does not clash with native `touchstart`, however in `onAny` part on `initialize()` method of `swiper-element-bundle.js`, the name of the event is coerced to be lower case with `name.toLowerCase()` which means now the `touchStart` event becomes `touchstart` which is not allowed, generating conflicts.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

MacOSX - Ventura 13.0.1 (but checked even on other computers)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
use `events-prefix` https://swiperjs.com/element#events
