### ISSUE TITLE
Isn't making minimum IOS 16 overkill?

### ISSUE THREAD

**Issue by XEngine** [nolimits4web/swiper#6806]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

There is none rn.

### Bug description

It seems the first issue I find is making .swiper class overflow: clip seems too much overkill since not everyone using the latest iOS and many users are still using ios 13.

According to [caniuse](https://caniuse.com/?search=overflow%3Aclip) webpage overflow clip supported since safari 16.

Is it okay to adapt Swiper v10 to latest browsers this early?

### Expected Behavior

I guess it should have a fallback to overflow:hidden

### Swiper version

10+

### Platform/Target and Browser Versions

macOS or iOS 13+

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Weird, last time i checked i was sure it was safari 15. Will add fallback in next update

**Comment by XEngine** [comment]
https://github.com/nolimits4web/swiper/pull/6807#issue-1786552151 I have opened this tiny PR
