### ISSUE TITLE
Custom navigation button not working in Angular

### ISSUE THREAD

**Issue by sharathdaniel** [nolimits4web/swiper#6808]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/wandering-cdn-scfkfx

### Bug description

 I'm using this in **Angular**, I want to use custom buttons to navigate swiper, but the below code doesn't work. I don't want to pass these parameters in .ts file.

```
<swiper-container
  navigation="{
    nextEl: '.button-next',
    prevEl: '.button-prev'
  }"
  pagination="false"
  slides-per-view="2"
>
  <swiper-slide>Slide 1</swiper-slide>
  <swiper-slide>Slide 2</swiper-slide>
  <swiper-slide>Slide 3</swiper-slide>
  <swiper-slide>Slide 4</swiper-slide>
</swiper-container>

<button class="button-prev">Prev</button>
<button class="button-next">Next</button>
```

### Expected Behavior

Clicking on the buttons should move the slides

### Actual Behavior

Nothing happens

### Swiper version

10

### Platform/Target and Browser Versions

Windows: Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
you try to pass object in HTML attribute, you need to use Angular's data-binding syntax
