### ISSUE TITLE
Modules are not exported in `swiper.mjs`

### ISSUE THREAD

**Issue by nachtjasmin** [nolimits4web/swiper#6809]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

[not provided]

### Bug description

If I'm trying to import [additional modules as per the documentation](https://swiperjs.com/swiper-api#using-js-modules), the build of my Hugo webpage (which is using esbuild under the hood) is failing. I'd like to submit a codesandbox link, but for some reason, it won't let me login with my GitHub account.

This is the JavaScript snippet which I am using. It was working fine with v9.

```js
import Swiper, { Navigation, A11y } from "swiper";
new Swiper(".swiper", {
	loop: true,
	centeredSlides: true,
	slidesPerView: 1,
	initialSlide: initialSlide,
	navigation: {
		nextEl: ".swiper-button-next",
		prevEl: ".swiper-button-prev",
	},
	modules: [Navigation, A11y],
});
```

### Expected Behavior

The build should succeed.

### Actual Behavior

The following error appears in the logs.

> Error: error building site: JSBUILD: failed to transform "js/main.js" (text/javascript): "/Users/jasminoster/repos/gwdg-website-v2/assets/js/components/swiper.js:1:17": No matching export in "node_modules/swiper/swiper.mjs" for import "Navigation"

This error is correct, as the `swiper.mjs` is only exporting the `Swiper`, not any of the modules:

```js
/**
 * Swiper 10.0.3
 * Most modern mobile touch slider and framework with hardware accelerated transitions
 * https://swiperjs.com
 *
 * Copyright 2014-2023 Vladimir Kharlampidi
 *
 * Released under the MIT License
 *
 * Released on: July 3, 2023
 */

export { S as Swiper, S as default } from './shared/swiper-core.mjs';
```

### Swiper version

10.0.3

### Platform/Target and Browser Versions

macOS Ventura 13.4.1, Firefox 114.0.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
import them from 'swiper/modules'. Docs updated

**Comment by Alexerson** [comment]
For your information, I believe the docs are still wrong here:
https://swiperjs.com/swiper-api#param-modules
