### ISSUE TITLE
Unable to Set Vertical Offset / Overflow Visible

### ISSUE THREAD

**Issue by altechzilla** [nolimits4web/swiper#6811]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

N/A

### Bug description

We're prototyping a slider that has some elements with shadows inside. Due to the .swiper element having an overflow hidden, we can't make those shadows visible. And because .swiper's styles are in a shadow DOM, we can't customize those styles either.

So we tried to use the slidesOffsetBefore and After to add some extra spacing. Works horizontally, but not vertically. What's the best way to make this slider have a vertical padding inside the .swiper element so that it doesn't cut off the content shadows?

Tried styling the swiper-slide / swiper-container but it won't work. I'd really appreciate some help. Thanks!

**Config**
```
const swiper = Object.assign(ref.current, {
	mousewheel: true,
	freeMode: true,
	spaceBetween: 15,
	slidesOffsetBefore: 25,
	slidesOffsetAfter: 25,
	slidesPerView: 3.75,
	grid: {
		fill: 'row',
		rows: 2
	}
});

swiper.initialize();
```

**Demo**
<img width="839" alt="Screenshot 2023-07-04 at 9 01 09 PM" src="https://github.com/nolimits4web/swiper/assets/8274669/5536cf9a-2701-4c47-aee5-53bd8cc69f26">

### Swiper version

Latest

### Platform/Target and Browser Versions

Any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You should check what is ::part in CSS and check the ones in Swiper
