### ISSUE TITLE
Cannot read properties of null (reading 'removeEventListener')

### ISSUE THREAD

**Issue by altechzilla** [nolimits4web/swiper#6812]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

N/A

### Bug description

When a swiper gets unmounted from inside of a popup (an element that mounts/unmounts its content from the DOM), this error gets thrown to the browser.

**Error:**
<img width="977" alt="Screenshot 2023-07-04 at 9 08 56 PM" src="https://github.com/nolimits4web/swiper/assets/8274669/a0d803c3-d4af-4fce-8838-937a80d4bbee">

**Config:**
```
const swiper = Object.assign(ref.current, {
	mousewheel: true,
	freeMode: true,
	spaceBetween: 15,
	slidesOffsetBefore: 25,
	slidesOffsetAfter: 25,
	slidesPerView: 3.75,
	grid: {
		fill: 'row',
		rows: 2
	}
});

swiper.initialize();
```

### Swiper version

10.0.3

### Platform/Target and Browser Versions

Chrome 114.0.5735.198 (Official Build)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You shouldn't ignore reproduction link filled in issue template
