### ISSUE TITLE
slidesPerView  slidesPerGroup  loop    bug

### ISSUE THREAD

**Issue by mannymu** [nolimits4web/swiper#6813]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/web-platform-kw2jkc?file=index.html

### Bug description

You can swipe to the left all the time, and you can only swipe to the right once. This bug is normal in 8.x version.

### Swiper version

10.x 、9.x

### Platform/Target and Browser Versions

macos chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by cb2004** [comment]
I have had the same issues as well:

https://stackblitz.com/edit/web-platform-te2jzm?file=index.html

I added another slide and changed slidesPerView and slidesPerGroup to 3 to demonstrate the issue I am having on a site.

**Comment by MaryWylde** [comment]
I have the same issue. The loop stops working when I add 4 for slidePerView, but with a smaller quantity, it works fine. Also, it seems like Loop has an issue with working with the grid (e.g. grid with 3 rows on mobile view)

**Comment by cb2004** [comment]
As mentioned in my comment, I think this is more of a restriction than an issue.

**Comment by mannymu** [comment]
<img width="1284" alt="image" src="https://github.com/nolimits4web/swiper/assets/15630104/d8b28d1b-f200-4b06-ac68-f103acfe98b1">

**Comment by idesignzone** [comment]
I had slidesPerView: 2.6 working in v8 but it in v9 and 10 it doesn't.

**Comment by niklasp** [comment]
I have the same problem. see:

https://codesandbox.io/p/sandbox/swiper-navigation-forked-ldqywv?file=%2Findex.html%3A74%2C20

please address this

**Comment by nanna-dk** [comment]
@nolimits4web Would you consider changing this feature back to the way it was before v9 or changing it so that number of slides >= slidesPerView * 2 isn't a requirement for loop to work? 
I love your Swiper project, and always recommend it to others as I think it's one of the best sliders, but this just doesn't make sense in normal use cases.
Thanks a lot.

**Comment by kosh89** [comment]
It's stop working in v9 because of new feature of this version -- "Loop mode without slides duplication". 
Wait for fix. I use rewind option as compromise.

**Comment by eno-tech0** [comment]
I have the same problem with loop: true and slidesPerView: "auto". This combination worked fine in version 6.6.1. Is there any chance that this will be fixed soon?

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2
