### ISSUE TITLE
Version 10 cannot use @import '~swiper/swiper-bundle.css'; in Ionic/Angular global.scss file

### ISSUE THREAD

**Issue by kinggolf** [nolimits4web/swiper#6816]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/kinggolf/pop-slide

### Bug description

I have an Ionic/Angular application using Swiper. For Swiper version 9, the following import statement in the `global.scss` file works: `@import '~swiper/swiper-bundle.css';`.

When upgrading to version 10 I get the following error:
```
./src/global.scss - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
 Error: Can't resolve '~swiper/swiper-bundle.css' in '/Users/larry/projects/pop-slide/src'
 
 ./src/global.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
 HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
 Error: Can't resolve '~swiper/swiper-bundle.css' in '/Users/larry/projects/pop-slide/src'
```

### Expected Behavior

Same import statement should work on version 10 like it does on version 9.

### Actual Behavior

I get the above error message and the app does not compile.

Clone the above repo, install dependencies, and run `ionic serve`. The app will compile and run in browser properly. This is set up with Swiper 9.4.1.

- Then upgrade to Swiper 10.0.3 and rerun the app. This is when I see the error message.

### Swiper version

10.0.3

### Platform/Target and Browser Versions

macOS Chrome 114.0.5735.198

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Read documentation for available exports
