### ISSUE TITLE
swiper-container has no extra classes (i.e. swiper-initizialed) when using the web component

### ISSUE THREAD

**Issue by hanoii** [nolimits4web/swiper#6818]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/8h4zgd

### Bug description

The default element sandbox showcases it, no swiper-* classes on the element.

### Swiper version

10.0.3

### Platform/Target and Browser Versions

macOS Brave v1.52.129

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Yes, it is by design in v10

**Comment by hanoii** [comment]
@nolimits4web ok, can you elaborate a bit more on why this is now by design and what would be the alternative,backward compatible way of doing it?

Bear in mind that the other Demos still seems to add this:

https://codesandbox.io/p/sandbox/dnfw9v (react, not element).

Or is this by design only on web components?

**Comment by nolimits4web** [comment]
It is only for web component. Need that classes, add manually hooking to swiper events
