### ISSUE TITLE
Module not found, package path is not exported

### ISSUE THREAD

**Issue by imanz7** [nolimits4web/swiper#6819]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

NA

### Bug description

Error: Module not found: Error: Package path ./element/bundle is not exported from package

### Expected Behavior

Tried to install swiper using `npm install swiper`, however after installed the package and imported the register in the app.component.ts, the error is found.

### Swiper version

9.5.0

### Platform/Target and Browser Versions

iOS, Android

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Latest version 10+
