### ISSUE TITLE
Flicker on load when using swiper element in react with useEffect()

### ISSUE THREAD

**Issue by hanoii** [nolimits4web/swiper#6820]
### Check that this is really a bug

- [X] I confirm

### Reproduction links

- https://codesandbox.io/p/sandbox/lucid-moser-75vdwr (init on useEffect, flicker)
- https://codesandbox.io/p/sandbox/quizzical-lehmann-kxhm3v (straight element, no useEffect(), no flicker)

### Bug description

I am trying to make a proper use of swiper element with a next js site. I need custom parameters as per 

- https://swiperjs.com/blog/using-swiper-element-in-react#parameters
- https://swiperjs.com/element#usage-with-react

I noticed there's a flicker (swiper gets re-rendered causing the image to be reloaded again).

On my actual site the flicker is even more noticeable, specially if throttling the speed I can really see it in action and the image gets loaded twice (slow 3g).

I wonder if there's a way around this, I haven't been able to figure out yet. Without use effect shows a warning (probably related to some react timing rendering) as reported on #6821 

### Swiper version

10.0.3

### Platform/Target and Browser Versions

macOS Brave v1.52.129

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how JavaScript works in general, try using `useLayoutEffect`
