### ISSUE TITLE
Swiper element on react: Warning: Extra attributes from the server: style,role,aria-label,class

### ISSUE THREAD

**Issue by hanoii** [nolimits4web/swiper#6821]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

- https://codesandbox.io/p/sandbox/quizzical-lehmann-kxhm3v (straight element, warning)
- https://codesandbox.io/p/sandbox/lucid-moser-75vdwr (init on useEffect, no warning)

### Bug description

Just adding the element as per the docs shows this warning, on npm run build it works OK. I know it's a warning but maybe it's an issue and related to #6820, where I am using the same sandboxes for what I am reporting.

However, if I use useEffect, the warning is not there.

### Swiper version

10.0.3

### Platform/Target and Browser Versions

macOS Brave v1.52.129

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You better to address this question to Next, swiper doesn't have and set such attributes

**Comment by MangoMarcus** [comment]
@hanoii Did you get to the bottom of this one? I've suppressed it with `supressHydrationWarning` for now
