### ISSUE TITLE
Swiper slide elements not being initialized correctly with *ngFor

### ISSUE THREAD

**Issue by StephanBis** [nolimits4web/swiper#6824]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Should be pretty obvious

### Bug description

We are using the web component version of Swiper in our Ionic 7 and Angular 16 app.

We have a generic Swiper implementation which receives an array of Angular components. Swiper slides are being generated by using *ngFor on the component array and we can see the actual DOM being generated correctly. However, it seems that the slides aren't being hydrated properly. 

HTML:
```
  <swiper-container>
    <swiper-slide *ngFor="let component of components">
      Dynamic component: {{ component.name }} <!-- Simplified -->
    </swiper-slide>
  </swiper-container>
```

TS:
```
  components: any[] = [
    WizardRecipeComponent,
    WizardStepsComponent,
    WizardTurnOnComponent,
    WizardBluetoothOnComponent,
    WizardConnectComponent
  ];

```

### Expected Behavior

That the slides would get hydrated correctly, so that simple methods like .slideNext() work as expected.

### Actual Behavior

E.g. .slideNext() only works for hardcoded slides or slides getting generated from a simple string array.

HTML:
```
  <swiper-container>
    <swiper-slide>
      I'm slide 1
      <ion-button (click)="doNext()">Next</ion-button>
    </swiper-slide>
    <swiper-slide>
      I'm slide 2
      <ion-button (click)="doNext()">Next</ion-button>
    </swiper-slide>
    <swiper-slide *ngFor="let item of test">
      I'm slide {{ item }}
      <ion-button (click)="doNext()">Next</ion-button>
    </swiper-slide>
    <swiper-slide *ngFor="let component of components">
      I'm slide x
      <ion-button (click)="doNext()">Next</ion-button>
    </swiper-slide>
  </swiper-container>
```
TS:
`test: string[] = ['1', '2', '3'];`

Generated HTML:
![image](https://github.com/nolimits4web/swiper/assets/10954823/1a671416-dec5-4a23-bb32-43eb9d80aaa5)
As you can see the last couple of slides aren't being hydrated correctly. You cannot swipe or slide to these ones.

### Swiper version

10.0.3

### Platform/Target and Browser Versions

Android

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by StephanBis** [comment]
After more trial & error we found the error. We had to add and *ngIf to the container of the swiper container so that it only gets initialized when the components array is filled with data.

**Comment by zqzy** [comment]
you  can  tell me  to  do ?

**Comment by StephanBis** [comment]
> you can tell me to do ?

For example. 
```
<div *ngIf="users && users.length > 0">
  <swiper-container>
    <swiper-slide *ngFor="let user of users">
      {{ user.fullName }}
      <ion-button (click)="goNext()">Next</ion-button>
    </swiper-slide>
  </swiper-container>
</div>
```
