### ISSUE TITLE
onClick slider start

### ISSUE THREAD

**Issue by mizandevms** [nolimits4web/swiper#6832]
### Clear and concise description of the problem

when we click a photo from a list it should open in a slider and the number of the slider will be that number which was clicked.

### Suggested solution

![2](https://github.com/nolimits4web/swiper/assets/54883567/bc09a14e-cf01-4919-96fa-cb6e11389108)
![1](https://github.com/nolimits4web/swiper/assets/54883567/76158386-1dfd-4134-ad0a-2e8ecbd46499)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is out of Swiper scope
