### ISSUE TITLE
[Swiper 10] Cannot drag an image when it's zoomed 

### ISSUE THREAD

**Issue by petrot** [nolimits4web/swiper#6847]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/8vmgzn?file=%2Findex.html%3A1%2C1

### Bug description

With Swiper 10, the images aren't dragable/movable, when we zoom-in on a slide. We just drag the whole slide, instead of moving the image. With Swiper 9, we was able to drag the images while it was zoomed.

You can check this behaviour on your own demo (what I linked in the reproduction info)

### Expected Behavior

The images are draggable and only move the slides, when we are on the edges of the image.

### Actual Behavior

The images aren't draggable, with dragging them, the whole slide moves.

### Swiper version

10.0

### Platform/Target and Browser Versions

Chromium 114

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by esiRonaldo** [comment]
have the same issue in V 11

**Comment by SergeyTrushin** [comment]
@esiRonaldo @petrot @nolimits4web 

The same issue in V11.0.7

Here's the crutch for the fix in React Js.
` 
const lastZoomPhotoCoordinateX = useRef(0);
const lastScale = useRef(scale);
const lastPageX = useRef(0);

const onTouchStart = e => {
        const {x} = e.target.getBoundingClientRect() || {};
        const {pageX} = e.changedTouches?.[0] || {};

        lastZoomPhotoCoordinateX.current = x;
        lastScale.current = scale;
        lastPageX.current = pageX;
    };

    // eslint-disable-next-line complexity
    const onTouchEnd = e => {
        if (scale !== 1 && lastScale.current === scale) {
            const {width} = e.target.getBoundingClientRect() || {};
            const {pageX} = e.changedTouches?.[0] || {};
            const threshold = 7;

            if (
                Math.round(lastZoomPhotoCoordinateX.current) === 0 &&
                lastPageX.current + threshold < pageX
            ) {
                onEdgeSwipeLeft();
            }

            if (
                Math.round(lastZoomPhotoCoordinateX.current) ===
                    -Math.round((width / scale) * (scale - 1)) &&
                lastPageX.current - threshold > pageX
            ) {
                onEdgeSwipeRight();
            }
        }
    };`
