### ISSUE TITLE
lazy无法正常使用

### ISSUE THREAD

**Issue by chunyangyang** [nolimits4web/swiper#6855]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-lazy-load-images-forked-79vxww?file=%2Fsrc%2FApp.jsx

### Bug description

打开官方示例加载报错，自己使用也报错
![image](https://github.com/nolimits4web/swiper/assets/20843521/001ee3a4-0353-497e-8705-fbe001a7ab48)

### Swiper version

10.0.0

### Platform/Target and Browser Versions

 Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is on lazy css in v10
