### ISSUE TITLE
custom slider component not work

### ISSUE THREAD

**Issue by Mini-ghost** [nolimits4web/swiper#6865]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-csqnfx?file=src%2FApp.vue

### Bug description

Sometimes, we need to create a custom slide component for the Swiper component because it requires specific styles or logic within each slide. However, in the current version of the Swiper Vue component, if we use a custom slide component instead of directly using `<SwiperSlide>`, it gets pushed into a slot named `container-end`.

While this behavior might not be considered a bug, it appears as though something is broken. It could be improved to make it more intuitive.

### Expected Behavior

A possible solution would be to introduce a new slot named `slides`, where we can place custom slide components. For example:

```vue
<template>
  <CustomSwiper>
    <template #slides>
      <CustomSwiper />
      <CustomSwiper />
      <CustomSwiper />
    </template>
  </CustomSwiper>
</template>
```

Additionally, the slot should support using `<SwiperSlide>` elements as well:

```vue
<template>
  <CustomSwiper>
    <template #slides>
      <SwiperSlide />
      <SwiperSlide />
      <SwiperSlide />
    </template>
  </CustomSwiper>
</template>
```

This enhancement would provide users with more flexibility when working with custom slide components within the Swiper component.

### Swiper version

10.0.4

### Platform/Target and Browser Versions

macOS / Chrome 116

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use name: 'SwiperSlide' in your component

**Comment by Mini-ghost** [comment]
You are right. I understand that we can use `SwiperSlide` as the name of the custom component, but have you considered creating a slot named `slides`? This approach would not only ensure forward compatibility but also make the template structure more intuitive and clear.

Implementing this modification would enhance the user experience, allowing us to conveniently use custom `slide` components within the `Swiper` component. Thank you for your suggestion!
