### ISSUE TITLE
Zoomed image can not move when only one swiper-slide

### ISSUE THREAD

**Issue by eblazeix** [nolimits4web/swiper#6875]
Hi,

First of all, **thanks for your amazing package** !

I am using Swiper JS on an **Ionic 7 Angular 16** project. I use the version **10.0.4**.

The package works fine and I managed to set the maximum ratio with the zoom parameter object. The only issue is that I have **only one image** (which is actually a canvas, but for this example I will use an image, which behaves exactly the same way).

Here is the code from the template :
```
<swiper-container
    #swiper
    [zoom]="{maxRatio: 6, toggle: true}"
    (click)="editPoint($event)"
  >
    <swiper-slide>
      <div class="swiper-zoom-container">
        <img src="assets/test-img/photo.jpg" />
      </div>
    </swiper-slide>
  </swiper-container>
```

And here is the result :

<img width="445" alt="image" src="https://github.com/nolimits4web/swiper/assets/57865012/b0570612-acaf-4a8a-8e91-31973485abae">

I can not move the image when the full image is displayed to fit the screen size, and this is perfect for me. But, **when I zoom in**, i can not **move** the image to the left, to the right, to the top or to the bottom :

<img width="473" alt="image" src="https://github.com/nolimits4web/swiper/assets/57865012/2d58a131-5e8c-47c3-b31f-d51f97c87633">

When i try to add another swiper-slide, there is no problem and I can **move** the image (even when the zoom is at his minimum because swiper prepares the transition with the next slide).

I searched in your great API documentation, I tried a lot of parameters, but I didn't find one that let me move the zoomed image when there is only one image (or one slide). For example, I tried to add hidden slides, I tried to set the loop parameter of swiper-container to true, but this is not working with only one slide (which is totally normal).

Did I miss something ?

Thanks a lot !

Emmanuel

**Comment by eblazeix** [comment]
> Hello @eblazeix. Please provide a online reproduction by [codesandbox](https://codesandbox.io/) or a minimal GitHub repository. You can fork one of our [demos](https://swiperjs.com/demos) in codesandbox to get start. Issues labeled by `missing demo` will be closed if no activities in 3 days.

Hi, I already put a code reproduction in my initial message. I think this code is enough to reproduce the behavior. Thanks

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
