### ISSUE TITLE
slideToLoop should loop

### ISSUE THREAD

**Issue by robertpainsi** [nolimits4web/swiper#6877]
### Clear and concise description of the problem

I wasn't sure if this is a bug or a feature depending on the expected behavior of `slideToLoop`.

- Check out my [codesandbox.io example.](https://codesandbox.io/p/sandbox/swiper-slide-to-loop-not-looping-l9qsm8?file=%2Findex.html).
- Note that `loop` is `true`.
- Click on the _next_ button until you're on the last slide, _Slide 4_.
- Now click on the _next_ button again.
- `slideToLoop` with `index` `0` is called and the swiper scrolls back to the first slide, passing all slides in between (_Slide 2_ and _Slide 3).

### Suggested solution

Since `loop` is `true` and you're on the last slide, calling `slideToLoop(0)` should behave like calling `slideNext()`.

If you're not on the last slide, maybe `slideToLoop` should scroll left or right depending on the shortest path.
However, since slides could load content asynchronously, maybe the shortest path isn't the best solution…

Note that in my example `slidesPerView` is `1`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how this method is designed to work

**Comment by robertpainsi** [comment]
I see.

Since it's a feature request :wink:, I guess there are no plans to add that behavior? (It doesn't need to be the `slideToLoop` method)

I'm currently having two swipers that are connected. One swiper is for images and the other one is for the caption of the images. So if the user slides to another image slide, the caption slider should also automatically slide to the new index. If the user loops in the image swiper, the caption swiper should also loop the same way. Otherwise it looks… meh :smile:

I hope you get my case. That's also why I initially thought the `slideToLoop` method would loop. Maybe the documentation should be improved here? Maybe it was just me who misunderstood that :smile:

My current solution that kinda works in most cases but only if `slidesPerView` is `1` (maybe it's helpful to others or others have a better solution):
```javascript
if ( Math.abs( imageSwiper.realIndex - captionSwiper.realIndex ) > 1 ) {
  if ( imageSwiper.realIndex === 0 && captionSwiper.realIndex === imageSwiper.slides.length - 1 ) {
    captionSwiper.slideNext();
  } else if ( captionSwiper.realIndex === 0 && imageSwiper.realIndex === imageSwiper.slides.length - 1 ) {
    captionSwiper.slidePrev();
  } else {
    captionSwiper.slideToLoop( imageSwiper.realIndex );
  }
} else if ( imageSwiper.realIndex < captionSwiper.realIndex ) {
  captionSwiper.slidePrev();
} else if ( imageSwiper.realIndex > captionSwiper.realIndex ) {
  captionSwiper.slideNext();
} else {
  captionSwiper.slideToLoop( imageSwiper.realIndex )
}
```

**Comment by Scoutzknifez** [comment]
+1 on this
