### ISSUE TITLE
Single click zoom

### ISSUE THREAD

**Issue by Nickonimus** [nolimits4web/swiper#6882]
### Clear and concise description of the problem

Zoom images in a single click could be more pleasant experience in some cases.

### Suggested solution

Add parameter to choose preferable zoom type in double or single click.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can easily do it by your self by calling swiper.zoom.toggle within click handler

**Comment by Nickonimus** [comment]
Actually i tried this first, but it zooming in center of the image, not to the cursor position. Am i missing something?

projectPage.on('click', function () { this.zoom.toggle(); });

**Comment by JihengNie2** [comment]
I noticed that if I used swiper.zoom.toggle with click handler, it will only zoom into the center of the image instead of where my mouse is. Where as with the built in double click, the zoom is at the location of the mouse. Is there a way to account for this wth single click?

**Comment by chrisolof** [comment]
@JihengNie2, passing the click event into [swiper.zoom.toggle(event)](https://swiperjs.com/swiper-api#method-swiper-zoom-toggle) zooms to where the mouse click occurred.
