### ISSUE TITLE
Issue with slideNext() using the latest version of Swiper in an Angular/Ionic project

### ISSUE THREAD

**Issue by yisusDev76** [nolimits4web/swiper#6886]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/yisusDev76/issure-swiper-10-angular

### Bug description

In my Angular/Ionic project, I'm experiencing an issue when calling this.swiper!.slideNext(); after updating to the latest version of Swiper. I receive the following error message: TypeError: Cannot read properties of undefined (reading 'speed').

**Steps to reproduce:**

Create a new Angular/Ionic project.
Install the latest version of Swiper ("swiper": "^10.0.4").
Set up a component with a Swiper and a button that calls swiper.slideNext() on click.
Run the application and click on the button.

If you change to the previous version of swiper (9.4.1), the app works without problems
`npm uninstall swiper
`
`npm install swiper@9.4.1`

[here a live preview app with the issure](https://dashboard.ionicframework.com/preview/ea491581/csz6cd39i3)

### Expected Behavior

That when pressing the button change to the next slides

### Actual Behavior

ERROR TypeError: Cannot read properties of undefined (reading 'speed')
    at Swiper.slideNext (swiper-core.mjs:1507:25)
    at Tab1Page.next (tab1.page.ts:29:18)
    at Tab1Page_Template_ion_button_click_11_listener (tab1.page.html:19:30)
    at executeListenerWithErrorHandling (core.mjs:15786:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15819:22)
    at HostElement.<anonymous> (platform-browser.mjs:665:17)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25998:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25998:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)

### Swiper version

10.0.4

### Platform/Target and Browser Versions

Ubuntu 22.04.2 LTS with Google Chrome Version 115.0.5790.102 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Would be good to see Stack Blitz or Codesandbox with the issue

**Comment by malua** [comment]
Hey, so slideNext is working with Angular + Ionic and Swiper 10. 
https://stackblitz.com/edit/stackblitz-starters-vrde3v?file=src%2Fmain.ts

It even works in your demo when you select the swiper-container in the DOM Inspector and call `$0.swiper.slideNext()` in the console.

It's probably due to a different problem in your setup. Unfortunately swiper is currently quite buggy when used with Angular and Ionic specifically.

**Comment by yisusDev76** [comment]
Hello, I appreciate all your suggestions and help so far. I've attempted to replicate the issue with my Ionic project on StackBlitz following your instructions. However, due to some technical limitations related to the 'swiper' module and possibly others, I'm unable to get the project up and running in the StackBlitz environment.

I understand that Ionic projects may not work flawlessly on platforms such as StackBlitz due to their browser-based execution environment. Nevertheless, I will keep working locally, taking into account your valuable feedback and suggestions.

I will implement the solution proposed by the user @malua  and if it does not work I will use swiper 9 for a long time


Thank you for your understanding and patience.
