### ISSUE TITLE
can't i use on ios12.x.x ??

### ISSUE THREAD

**Issue by dhsimpson** [nolimits4web/swiper#6887]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://mobile.m.11st.co.kr/

### Bug description

The slide doesn't work when I touch the swiper area and try to slide it on the iPhone.
(Reproduction link is not available because i have issue in my development environment. and cannot expose for public.)

i saw https://github.com/nolimits4web/swiper/commit/96a4e7e50a430d70817d90916c8412adfbc33f74 , is it means that i can't use swiper-react on ios version under 15??

### Swiper version

^9.2.4

### Platform/Target and Browser Versions

IOS12.1.3

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
can't

**Comment by Jasmine26z** [comment]
I met the problem too,  any solutions for the problem that some versions for ios cannot slide ?

**Comment by dhsimpson** [comment]
> I met the problem too in swiper 10.12.0, any solutions for the problem that some versions for ios cannot slide ?

Hello. I've downgraded swiper version to 6.8.4.

I checked many banches and https://github.com/nolimits4web/swiper/blob/v6/.browserslistrc helped me.

**Comment by Jasmine26z** [comment]
> > I met the problem too in swiper 10.12.0, any solutions for the problem that some versions for ios cannot slide ?
> 
> Hello. I've downgraded swiper version to 6.8.4.
> 
> I checked many banches and https://github.com/nolimits4web/swiper/blob/v6/.browserslistrc and https://www.npmjs.com/package/swiper?activeTab=versions helped me.

thanks!
