### ISSUE TITLE
real index is wrong, not the same as active dom element

### ISSUE THREAD

**Issue by alex-ading** [nolimits4web/swiper#6891]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-vue-centered-forked-vwkzzh?file=%2Fsrc%2Fstyle.css%3A16%2C14

### Bug description

When drag swiper to move very slow or fast, and the cursor is out the swiper container, this will occur: the `realIndex` not return the real active index in dom, as class `swiper-slide-active` wraps.

![image](https://github.com/nolimits4web/swiper/assets/57172863/f1fd22c0-c123-401b-b381-a834d5f34fc7)

Here is my config:
```
 <swiper
    :slidesPerView="3"
    class="custom-swiper"
    :centeredSlides="true"
    :loop="true"
    @slideChange="handleSlideChange"
    :slidesPerGroup="1"
    :grabCursor="true"
>
</swiper>
```

### Swiper version

9.2.0

### Platform/Target and Browser Versions

macOS Chrome 114

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
v9 is not maintained anymore. If same issue happens in v10, open new issue and provide updated demo
