### ISSUE TITLE
hide the right/left side  of coverflowEffect

### ISSUE THREAD

**Issue by eyeswrong36** [nolimits4web/swiper#6892]
### Clear and concise description of the problem

I want to hide the right side of coverflowEffect to make it looks like a stack card left

### Suggested solution

Additional props to hide right/left side in coverflowEffect would be nice feature to add

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There are different effects for this
