### ISSUE TITLE
Autoplay pauseOnMouseEnter not working properly when speed was set

### ISSUE THREAD

**Issue by eric-weya** [nolimits4web/swiper#6896]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-autoplay-progress-forked-qjnwvh

### Bug description

When use default speed, It worked(pause on mouseEnter everytime), but if speed was set, swiper will not pause(not everytime).
```
new Swiper(".mySwiper", {
      spaceBetween: 30,
      slidesPerView: 3,
      speed: 3000,   // not working properly
      autoplay: {
        delay: 3000,
        disableOnInteraction: false,
        pauseOnMouseEnter: true,
      },
    });
```

### Expected Behavior

should pause on mouseEnter everytime

### Actual Behavior

not pause everytime.

### Swiper version

9.4.1, 10.0.4

### Platform/Target and Browser Versions

macOS Chrome 115.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by 3biubiu** [comment]
https://github.com/nolimits4web/swiper/assets/63720467/f2ccf6cc-0364-4739-bbaa-7db78c8ade1c

When the two silde switches, move the mouse in, pauseOnMouseEnter not working

**Comment by zhangxinyong12** [comment]
Have you solved it?

**Comment by 3biubiu** [comment]
> Have you solved it?

use mouseenter/leave

**Comment by eric-weya** [comment]
yes, i just use mouse event to control it.

**Comment by 3biubiu** [comment]
is animation bug LOL



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 25, 2023 20:13 PM
To: ***@***.***&gt;;
Cc: "biu ***@***.******@***.***&gt;;
Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896)




 
yes, i just use mouse event to control it.

**Comment by zhangxinyong12** [comment]
When I switch the data, the animation stops

**Comment by 3biubiu** [comment]
> When I switch the data, the animation stops

I didn't understand your question,  when mouseenter/leave  use swiper.autoplay.stop()/start()

**Comment by zhangxinyong12** [comment]
> > When I switch the data, the animation stops
> 
> I didn't understand your question, when mouseenter/leave use swiper.autoplay.stop()/start()

I already took care of it. The dynamic length of my data is not fixed. I destroyed it and reinitialized it.

**Comment by 3biubiu** [comment]
别销毁或者重置它&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 28, 2023 15:02 PM
To: ***@***.***&gt;;
Cc: "biu ***@***.******@***.***&gt;;
Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896)




   
When I switch the data, the animation stops
  
I didn't understand your question, when mouseenter/leave use swiper.autoplay.stop()/start()
  
I already took care of it. The dynamic length of my data is not fixed. I destroyed it and reinitialized it.

**Comment by lllUnoxx** [comment]
兄弟，我也遇到同样的问题了。。。解决了吗？

**Comment by 3biubiu** [comment]
手写一个鼠标事件去手动暂停，不用自带的配置



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 18, 2023 23:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896)




 
兄弟，我也遇到同样的问题了。。。解决了吗？

**Comment by lllUnoxx** [comment]
> 手写一个鼠标事件去手动暂停，不用自带的配置
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Dec 18, 2023 23:01 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896) 兄弟，我也遇到同样的问题了。。。解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

swiper对象能打印出来，但是swiper.autoplay.stop is not a function。。。

**Comment by wangyilan98** [comment]
> > 手写一个鼠标事件去手动暂停，不用自带的配置
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Mon, Dec 18, 2023 23:01 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896) 兄弟，我也遇到同样的问题了。。。解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> swiper对象能打印出来，但是swiper.autoplay.stop is not a function。。。

你解决这个问题了吗

**Comment by 3biubiu** [comment]
> > > 手写一个鼠标事件去手动暂停，不用自带的配置
> > > […](#)
> > > ---Original--- From: _**@**_._**> Date: Mon, Dec 18, 2023 23:01 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896) 兄弟，我也遇到同样的问题了。。。解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > swiper对象能打印出来，但是swiper.autoplay.stop is not a function。。。
> 
> 你解决这个问题了吗

看你的swiper版本以及是否正确获取实例

**Comment by wangyilan98** [comment]
> > > > 手写一个鼠标事件去手动暂停，不用自带的配置
> > > > […](#)
> > > > ---Original--- From: _**@**_._**> Date: Mon, Dec 18, 2023 23:01 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896) 兄弟，我也遇到同样的问题了。。。解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > > 
> > > 
> > > swiper对象能打印出来，但是swiper.autoplay.stop is not a function。。。
> > 
> > 
> > 你解决这个问题了吗
> 
> 看你的swiper版本以及是否正确获取实例

我在swiper组件标签里写@swiper="onSwiper"；在swiper组件的上一层div中添加了 @mouseenter="handleSwiperMouseEnter"
        @mouseleave="handleSwiperMouseLeave"；const swiperInstance=ref(null)
const onSwiper = (swiper)=>{
  swiperInstance.value = swiper
}
const handleSwiperMouseEnter=()=>{
  swiperInstance.value?.autoplay.stop();
}。打印 swiperInstance.value?.autoplay倒是有stop这些方法。但是不起作用；代码提示类型never上不存在属性autoplay

**Comment by 3biubiu** [comment]
> > > > > 手写一个鼠标事件去手动暂停，不用自带的配置
> > > > > […](#)
> > > > > ---Original--- From: _**@**_._**> Date: Mon, Dec 18, 2023 23:01 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [nolimits4web/swiper] Autoplay pauseOnMouseEnter not workingproperly when speed was set (Issue #6896) 兄弟，我也遇到同样的问题了。。。解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > > > 
> > > > 
> > > > swiper对象能打印出来，但是swiper.autoplay.stop is not a function。。。
> > > 
> > > 
> > > 你解决这个问题了吗
> > 
> > 
> > 看你的swiper版本以及是否正确获取实例
> 
> 我在swiper组件标签里写@swiper="onSwiper"；在swiper组件的上一层div中添加了 @mouseenter="handleSwiperMouseEnter" @mouseleave="handleSwiperMouseLeave"；const swiperInstance=ref(null) const onSwiper = (swiper)=>{ swiperInstance.value = swiper } const handleSwiperMouseEnter=()=>{ swiperInstance.value?.autoplay.stop(); }。打印 swiperInstance.value?.autoplay倒是有stop这些方法。但是不起作用；代码提示类型never上不存在属性autoplay

试试通过 ref 的方式 直接获取实例组件内部的`autoplay`相关方法
