### ISSUE TITLE
[ios][bug] swiper doesn't work on safari

### ISSUE THREAD

**Issue by codeblockhead** [nolimits4web/swiper#6897]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/zgdjjq?file=%2Fsrc%2FApp.vue%3A1%2C1

### Bug description

When I tried to swipe left at the edge of Safari's screen, the browser's forward feature triggered, and the swiper stopped working if I was returning to the current page. This only happens on ios

https://github.com/nolimits4web/swiper/assets/66559869/f95df2bf-52ea-4fa1-9ac4-406a41258b2c

### Expected Behavior

swiper still works after trigger forward

### Swiper version

10.0.4

### Platform/Target and Browser Versions

ios 15.6

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Jeonghyeonuk** [comment]
i have same issue
