### ISSUE TITLE
Cards effect: translate3d not working properly in Safari on swiper element.

### ISSUE THREAD

**Issue by greg-md** [nolimits4web/swiper#6898]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/ppvng9?file=/index.html

### Bug description

The `tz` positioning for `translate3d` doesn't have any effect on slides if they are in a shadow dom element. I am not sure if it is a swiper issue or a Safari issue.
<img width="434" alt="Captură de ecran din 2023-08-02 la 12 16 46" src="https://github.com/nolimits4web/swiper/assets/10551984/f315f65d-cbfe-4f9c-b1ec-bcd9a83d570d">

### Expected Behavior

`translate3d` should move slides back based on `perspective`.

### Actual Behavior

The `tz` parameter of `translate3d` doesn't have any effect.

### Swiper version

10.1.0

### Platform/Target and Browser Versions

MacOS Ventura 13.3.1 (a), Safari 16.4 (18615.1.26.110.1)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/blog/swiper-slider-in-webflow

**Comment by greg-md** [comment]
@nolimits4web is it possible to use the lazy loading with the slots? I tried `<div class="slide-content" slot="slide-3" lazy="true">` and it didn't work.
