### ISSUE TITLE
Breakpoints with slidesPerView: auto do not work correctly

### ISSUE THREAD

**Issue by eno-tech0** [nolimits4web/swiper#6902]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-breakpoints-perview-d7xlkm

### Bug description

I use a wrapper for React on web components.
When setting slidesPerView: "auto" in root settings and slidesPerView: 1 (or any other number) in breakpoints, the slider does not behave as expected. In breakpoints everything works fine, but where it should be "auto" - one slide is displayed at a time. Without breakpoints settings, specifying slidesPerView: "auto" works correctly.

### Swiper version

10.1.0

### Platform/Target and Browser Versions

Windows, Google Chrome 115.0.5790.111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> but where it should be "auto" - one slide is displayed at a time

When you use `auto` you need to specify slide width in CSS, it is 100% by default

**Comment by eno-tech0** [comment]
> When you use `auto` you need to specify slide width in CSS, it is 100% by default

It didn't work

**Comment by eno-tech0** [comment]
@nolimits4web Were you able to do this with the example I provided above?

**Comment by nolimits4web** [comment]
> @nolimits4web Were you able to do this with the example I provided above?

The example you have provided doesn't have slide widths specified in CSS for auto mode

**Comment by eno-tech0** [comment]
@nolimits4web I have defined widths for the swiper-slide component and for the slide (picture) itself, but it doesn't give any result. Have you tried fixing the code in the example I attached so that it works as it should?

**Comment by nolimits4web** [comment]
there is no point to define width using `style` attributes here, it will be overwritter, as in my first comment, it must be done in CSS

**Comment by eno-tech0** [comment]
@nolimits4web Ok, I overridden the width in the css file. But other problems appeared:
1. spaceBetween for a screen larger than 375px should be 32px, but it displays 16px
2. When scrolling the slider to the right until the end, a large white space appears
3. When you swipe the slider to the left, the slides in it start to shift and it "jerks".

None of these problems occur if you don't change the parameters in breakpoints.

**Comment by nolimits4web** [comment]
> spaceBetween for a screen larger than 375px should be 32px, but it displays 16px

I see everything is correct

2 and 3 - see the docs for `loop` mode requirements https://swiperjs.com/swiper-api#param-loop

**Comment by eno-tech0** [comment]
@nolimits4web In the Google Chrome browser 115.0.5790.171 on Windows, I have the wrong slide spacing displayed in the settings for breakpoints
![image](https://github.com/nolimits4web/swiper/assets/60596033/958ee3ca-49bc-4ba5-a2d3-da51bf1a6ee4)


There are slider settings that work correctly:
const sliderParams = {
    slidesPerView: "auto",
    spaceBetween: 32
    grabCursor: true,
    loop: true,
  };

But I need these settings to apply only for desktop and different settings for mobile devices, so I use the breakpoints parameter to change the settings:
const sliderParams = {
    slidesPerView: 1,
    grabCursor: true,
    spaceBetween: 16,
    loop: true,
    breakpoints: {
      375: {
        slidesPerView: "auto",
        spaceBetween: 32
      }
    }
  };
And already such settings give the problems I described above. I don't quite understand what documentation has to do with it, if everything works correctly without breakpoints.

**Comment by eno-tech0** [comment]
@nolimits4web Should I create a separate issue for this or does it not count as an issue?

**Comment by eno-tech0** [comment]
@nolimits4web Or maybe we should reopen this issue?

**Comment by eno-tech0** [comment]
@nolimits4web Is there any chance to continue the discussion?

**Comment by eno-tech0** [comment]
@nolimits4web I really need help with this. Can you give me a hint how to fix it if what I described is not a bug?

**Comment by nolimits4web** [comment]
Please create a new issue with full correct CodeSandbox example
