### ISSUE TITLE
Parallax does not work in swiper element.

### ISSUE THREAD

**Issue by DeepKumbhare85** [nolimits4web/swiper#6910]
Hello, 

I am working on a project where I require swiper with parallax.I am using swiper element.I also checked out swiper element demo for parallax. In demo image is not sliding. parallax is working properly in vue & react demo.but is not working in element demo.Here is a link for swiper element demo: https://codesandbox.io/p/sandbox/swiper-parallax-forked-j6jpnf?file=%2Findex.html%3A11%2C7

Is there any mistake with implementation or this is a bug ??

_Originally posted by @DeepKumbhare85 in https://github.com/nolimits4web/swiper/discussions/6906_

**Comment by nolimits4web** [comment]
You already have the answer in that discussion
