### ISSUE TITLE
Slides disappearing on nested virtual sliders

### ISSUE THREAD

**Issue by Razunter** [nolimits4web/swiper#6912]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-virtual-slides-forked-zgw8xd

### Bug description

Slides get removed in nested swiper of swiper with virtual slides if you change `swiper.virtual.slides` array.
Nested slider doesn't have to be initialized for this bug.

It's a very old issue: #2377

### Expected Behavior

Nested slides stay in place

### Actual Behavior

Nested slides disappear from DOM

`<div class="swiper"><div class="swiper-wrap"></div></div>`

### Swiper version

10.0.4

### Platform/Target and Browser Versions

Windows, Firefox 116.0.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
[v](https://codesandbox.io/p/sandbox/swiper-virtual-slides-forked-j2n8fn?file=%2Findex.html%3A90%2C43)

**Comment by nolimits4web** [comment]
https://codesandbox.io/p/sandbox/swiper-virtual-slides-forked-j2n8fn?file=%2Findex.html%3A90%2C43

**Comment by Razunter** [comment]
OK, disabling cache helps... But it's not obvious and still feels like a bug. At least should be noted in docs.

**Comment by Razunter** [comment]
Changing nested slides class helps as a workaround.
