### ISSUE TITLE
UI flickering on swiping with loop set to true

### ISSUE THREAD

**Issue by barksploit** [nolimits4web/swiper#6914]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/barksploit/pen/JjeVwxJ

### Bug description

Loop mode causes flicker between slides.

Supposedly fixed in #6673 bf298437039168611853cc7b7f92624f5f2726c6 but still an issue latest version

### Expected Behavior

No flicker

### Actual Behavior

Flickers between slides as DOM elements are switched out

### Swiper version

10.1.0

### Platform/Target and Browser Versions

Any browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
issue is related to controller

**Comment by drheavymetal** [comment]
The problems is also present without the loop set to true, with it as false also occurs.  Is there any workaround?
My full swiper config:
`effect: 'cards',
grabCursor: true,
centeredSlides: true,
loop: false,
maxBackfaceHiddenSlides: 2`

If doesn't occurs at the first slides, the flickering starts after 20 or 25 slides, any idea?

**Comment by nolimits4web** [comment]
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one
