### ISSUE TITLE
use slideToLoop in loop mode, a slide disappear

### ISSUE THREAD

**Issue by alex-ading** [nolimits4web/swiper#6915]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-loop-bug-wh9mky?file=%2Fsrc%2FApp.vue%3A44%2C7

### Bug description

In loop mode, `slideToLoop` to a specific index, the previous slide is missing, like this, slide 4 is missing:
![image](https://github.com/nolimits4web/swiper/assets/57172863/f3d9289a-1ac5-4b49-9d3e-4b9b2305edf5)

the reproduction link can show this every time.

### Swiper version

10.0.0

### Platform/Target and Browser Versions

macOS chrome 115

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://codesandbox.io/p/sandbox/swiper-loop-bug-forked-xt5lwk?file=%2Fsrc%2FApp.vue%3A42%2C25

**Comment by gablittledevshop** [comment]
@nolimits4web can you explain your comment a bit more or why this is closed? I'm having the same issue as @alex-ading , but it doesn't show anything new that I can tell. e.g. In your code sandbox, if you change `e.slideToLoop(4, 0);` to `e.slideToLoop(6, 0);`, there will be missing slides.

**Comment by nolimits4web** [comment]
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one
