### ISSUE TITLE
`slidesOffsetAfter` and `slidesOffsetBefore` are breaking the `slidesPerView`

### ISSUE THREAD

**Issue by michalvadak** [nolimits4web/swiper#6916]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-slides-per-view-forked-9sg53p?file=%2Fsrc%2FApp.jsx%3A8%2C1

### Bug description

Setting the `slidesOffsetAfter` and `slidesOffsetBefore` breaks the `slidesPerView`. 

### Expected Behavior

When I have 3 slides and set `slidesPerView: 3` with `slidesOffsetAfter: 96` and `slidesOffsetBefore: 96` I expect to see 3 slides with offset without the ability to swipe them.

### Actual Behavior

The slides are slideable and I don't see the whole 3 slides.

### Swiper version

10.1.0

### Platform/Target and Browser Versions

macOS 13.5 (22G74) / Chrome - 115.0.5790.170 (arm64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how it works. What you are trying to achieve should be done with setting paddings on swiper container

**Comment by WesselKroos** [comment]
For the ones who want to use (patch) this feature (design bug) in their project:

```javascript
const {
  slidesOffsetBefore: _1,
  slidesOffsetAfter: _2,
  ...patchedOptions
} = options;
const swiper = new Swiper('.swiper', patchedOptions);
swiper.el.style.overflow = 'visible';
if (options.slidesOffsetBefore) {
  swiper.el.style.marginLeft = `${options.slidesOffsetBefore}px`;
}
if (params.slidesOffsetAfter) {
  swiper.el.style.marginRight = `${options.slidesOffsetAfter}px`;
}
if (options.slidesOffsetBefore || options.slidesOffsetAfter) {
  swiper.el.style.width = 'auto';
}
```
