### ISSUE TITLE
how to reset zoom focus?

### ISSUE THREAD

**Issue by wccd** [nolimits4web/swiper#6918]
### Clear and concise description of the problem

When I use the double-click zoom function, the zoom center stays at the clicked position, and then call swiper.zoom.in() by other button, and the zoom center still stays at the last clicked position.

### Suggested solution

1. Provide a reset zoom focus function
2. Provide the web side to disable the double-click zoom function

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
```
$('.swiper').swiper.zoom.out(); $('.swiper').swiper.zoom.in();
```
