### ISSUE TITLE
Inject slides also to the beginning of the stack on the loop mode

### ISSUE THREAD

**Issue by ilterugur** [nolimits4web/swiper#6920]
### Clear and concise description of the problem

Hello. I use loop mode and centeredSlides mode together. Also, I use z-index with some CSS positioning tricks to make cards seem hierarchical.

It basically looks like this:
![Screenshot 2023-08-10 at 18 17 49](https://github.com/nolimits4web/swiper/assets/2822708/2b0ac286-bf08-4578-bab6-fece0998432a)

The problem here is when I swipe the stack until I reach the end, the first card on the stack turns into centered card and it seems buggy like this:
![Screenshot 2023-08-10 at 18 20 26](https://github.com/nolimits4web/swiper/assets/2822708/a3c34d5f-02cb-43c7-b968-a5e5c1cd7883)

When I react to the end of the slides, I need the stack to seem like the first screenshot, I mean it needs to appear the same as its own initial state.

### Suggested solution

We can have a prop to also insert slides at the beginning on loop mode so it won't look like the second screenshot. I believe I can monkeypatch it on node_modules with some monkey-patching packages on npm but it shouldn't be the only solution to this.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by hrvstr** [comment]
I have created a demo for this issue. Disable `autoplay` to see the desired behavior. Enable it to see unwanted behavior.

[Codesandbox](https://codesandbox.io/p/sandbox/t22lp2?file=%2Findex.html%3A132%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clst3ngiq00073b6h8c51o1hx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clst3ngip00033b6hrbw0v2l3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clst3ngip00043b6h7twvjxtw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clst3ngip00063b6hipirplw2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B62.93162926701055%252C37.06837073298945%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clst3ngip00033b6hrbw0v2l3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clst3ngip00023b6hp55muf7s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A132%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A132%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clst3ngip00033b6hrbw0v2l3%2522%252C%2522activeTabId%2522%253A%2522clst3ngip00023b6hp55muf7s%2522%257D%252C%2522clst3ngip00063b6hipirplw2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clst3ngip00053b6hp5n2qrhe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clst3ngip00063b6hipirplw2%2522%252C%2522activeTabId%2522%253A%2522clst3ngip00053b6hp5n2qrhe%2522%257D%252C%2522clst3ngip00043b6h7twvjxtw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clst3ngip00043b6h7twvjxtw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

When using the cards effect in a centered loop mode new slides are always pushed to the end of the stack when switching slides. So, there are always slides left and right to the active slide.

https://github.com/nolimits4web/swiper/assets/4610008/67d8bcea-3f46-4a8a-92e1-8ee198de4917

However, when enabling `autoplay` new slides are not pushed to the end of the stack, so you end up with this weird-looking effect.

https://github.com/nolimits4web/swiper/assets/4610008/01135a59-cade-45ae-a482-ad2f0a76fbee

I think it would be nice to get an option to push new slides to the end of the stack (same as when you move the slides manually) so there are always slides on both sides when the swiper is centered and looped.

**Comment by EtienneGuillet** [comment]
@hrvstr by any chance did you find a fix?
