### ISSUE TITLE
The direction of the slider is sometimes out of whack

### ISSUE THREAD

**Issue by jiayinya** [nolimits4web/swiper#6929]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-autoplay-forked-ns4qqk?file=%2Fsrc%2FApp.jsx%3A1%2C1

### Bug description

I have swiper with infinity loop and autoplay, at first, It's completely normal. 
However, after a while, when I clicked on the pagination button, a problem occurred.

I am currently on the 2nd page,  I click on the pagination button to navigate to the 4th page. I hope slide out from the right. However, I found that it slide out from the left. Furthermore, I noticed that the order of the left and right sliding is very chaotic when I click on the pagination buttons.

### Swiper version

^10.0.4

### Platform/Target and Browser Versions

chrome in mac os

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how loop mode works, as slides rearranged in DOM
