### ISSUE TITLE
Set slidesPerView via data attributes 

### ISSUE THREAD

**Issue by krisMoca** [nolimits4web/swiper#6930]
### Clear and concise description of the problem

No option to set different slidesPerView parameter per swiper object when multiple swiper objects loaded on a single page.

### Suggested solution

![image](https://github.com/nolimits4web/swiper/assets/86084360/4af9ec83-f8e2-4592-9fe4-20efad0fca03)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use API or Swiper web component
