### ISSUE TITLE
Parallax effect is not smooth

### ISSUE THREAD

**Issue by Bludator** [nolimits4web/swiper#6933]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/Bludator/pen/zYMgJKM?editors=1000

### Bug description

The parallax effect is skipped and the elements are transformed without animation when I use autoplay or the arrows, the touch / drag&drop is ok. In the demo I have used big speed to make it more visible. 

---

BTW the demo in the [docs](https://swiperjs.com/swiper-api#parallax) is also a bit broken - it flickers, but that is firefox only issue

### Swiper version

10.1.0

### Platform/Target and Browser Versions

Windows 11 - Chrome 115 / Firefox 116

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
265e466a043efc750964c397d262736923e58040

**Comment by Bludator** [comment]
already fixed last week 😲? you are the best.
