### ISSUE TITLE
moveTouch event is missing the touches property

### ISSUE THREAD

**Issue by pjc2007** [nolimits4web/swiper#6935]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/pjc2007/swiper-touchevent-issue

### Bug description

I have another component which also hooks into touches events.

When I swipe the swiper, we get a `touchmove` event that looks like the following...

```
 event: CustomEvent
    isTrusted: false
    fixed: true
    originalTarget: swiper - container.observations - swiper
    target: swiper - container.observations - swiper
    bubbles: true
    cancelBubble: false
    cancelable: true
    composed: false
    currentTarget: document
    defaultPrevented: false
    detail: (2)[Swiper, PointerEvent]
    eventPhase: 1
    returnValue: true
    srcElement: swiper - container.observations - swiper
    timeStamp: 1125130.800000012
    type: "touchmove" [
        [Prototype]
    ]: CustomEvent
```

Now this other component has code that look like....

```
if (type.startsWith("touch") && event.touches.length) {
```

So they are accessing the `touches` property, which we can see is not there. They claim the event is not following the specifications (eg see ttps://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event, https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) so it does appear that we should expect a **touches** property?

### Expected Behavior

The touch events to include the touches property

### Actual Behavior

We do not have this property, so other code that may expect it always can crash

### Swiper version

10.1.0

### Platform/Target and Browser Versions

Chrome Version 115.0.5790.171 (run ios device emulation) Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use `events-prefix` https://swiperjs.com/element#events
