### ISSUE TITLE
[Swiper Element] pagination.el value is ignored

### ISSUE THREAD

**Issue by Maximaximum** [nolimits4web/swiper#6938]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiperjs-element-pagination-el-bug-tm9z5s

### Bug description

When I use Swiper Element, the `pagination.el` value seems to be ignored. Pagination controls are simply rendered inside the default `div.swiper-pagination.swiper-pagination-bullets.swiper-pagination-horizontal` element.

_NOTE: This seems to be a purely **Swiper Element** bug, not a **Swiper Core** one. However, there is no github bug template for **Swiper Element** bugs._

### Expected Behavior

I would expect the pagination controls to be rendered inside the element passed to swiper as the `pagination.el` parameter value. 

### Actual Behavior

The pagination controls are rendered inside the default `div.swiper-pagination.swiper-pagination-bullets.swiper-pagination-horizontal` element inside the `swiper-container`

### Swiper version

10.1.0

### Platform/Target and Browser Versions

Windows Chrome v116

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://codesandbox.io/p/sandbox/swiperjs-element-pagination-el-bug-forked-f37t2c?file=/index.html:58,41

**Comment by Chen-Michael** [comment]
> https://codesandbox.io/p/sandbox/swiperjs-element-pagination-el-bug-forked-f37t2c?file=/index.html:58,41

404 not found
