### ISSUE TITLE
Github: missing template for Swiper Element issues

### ISSUE THREAD

**Issue by Maximaximum** [nolimits4web/swiper#6939]
### Clear and concise description of the problem

Currently when trying to create an issue at the swiper github project, only the given bug templates are provided:

- New feature proposal
- 🐞 Swiper Core Issue
- 🐞 Swiper React Issue
- 🐞 Swiper Vue Issue
- 🙏 Open Collective
- 📃 Documentation Issue

Therefore, a template for a **Swiper Element** Issue is missing. 

### Suggested solution

A **🐞 Swiper Element Issue** template needs to be defined and added to the list of available templates

### Alternative

Currently people are just opening Swiper Element - related issues using random issue templates (personally I've used Swiper Core issue template).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [x] I'm willing to open a PR

**Comment by Maximaximum** [comment]
Issues that should have used a Swiper Element template:
- #6940
- #6938

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/pull/6941
