### ISSUE TITLE
[Swiper Element] pagination container [part] attribute is missing after delayed pagination initialization

### ISSUE THREAD

**Issue by Maximaximum** [nolimits4web/swiper#6940]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-pagination-forked-lm48kq?file=%2Findex.html%3A40%2C22

### Bug description

If pagination is initialized via:
-  `swiper.pagination` property (like `document.querySelector("swiper-container").pagination = true;`) 
or
-  `setAttribute()` method (like `document.querySelector("swiper-container").setAttribute("pagination", true)`), 
 
the `[part]` attribute is missing on the pagination container.

This is inconsistent with what happens if pagination is initialized during swiper creation (via `<swiper-container pagination="true"></swiper-container>`)

_NOTE: This seems to be a purely **Swiper Element** bug, not a **Swiper Core** one. However, there is no github bug template for **Swiper Element** bugs._

### Expected Behavior

Pagination container should look like:

```
<div part="pagination" class="swiper-pagination swiper-pagination-bullets swiper-pagination-horizontal"></div>
```

### Actual Behavior

Pagination container looks like:

```
<div class="swiper-pagination swiper-pagination-bullets swiper-pagination-horizontal"></div>
```

### Swiper version

10.1.0

### Platform/Target and Browser Versions

Windows Chrome v116

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please do search previous issues before posting new one

**Comment by Maximaximum** [comment]
https://github.com/nolimits4web/swiper/issues/6899

Indeed, didn't notice that one, sorry. 😅
