### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by meotimdihia** [nolimits4web/swiper#6943]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/dtj5mc?file=/index.html:52,22

### Bug description

The bug happen with the official example too:

https://github.com/nolimits4web/swiper/assets/300961/5434ce92-d97c-463a-a496-d54dd88c7e28

### Swiper version

^10.1.0

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by HinnHabib** [comment]
We are facing the same issue.
