### ISSUE TITLE
Zoomed images are blurry on ios mobile due to translate3d

### ISSUE THREAD

**Issue by liangskyli** [nolimits4web/swiper#6953]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-zoom-forked-qce1m?file=/index.html

### Bug description

the same as #4731
detail see  #4731

Using translate3d causes problems to occur，
Changing to using matrix can solve the problem！
After using matrix in the ImageViewer implementation of ant design mobile, there will be no issues. It is recommended to update the implementation plan. Thank you!
see ImageViewer: https://ant-design-mobile.antgroup.com/zh/components/image-viewer

example use: transform: matrix(3, 0, 0, 3, 14, 64);

### Expected Behavior

expect not blurry!
Because some business scenarios require enlarged images, blurry images are a serious problem.

### Actual Behavior

Zoomed images are blurry on ios mobile !

### Swiper version

any

### Platform/Target and Browser Versions

ios mobile safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Translated3d is required for better performance, using matrix will have same effect. Blury images is a question to device/browser
