### ISSUE TITLE
reverseDirection: false is not working properly

### ISSUE THREAD

**Issue by ValchanOficial** [nolimits4web/swiper#6954]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/festive-rain-kgx5v5?file=/src/Carousel/index.jsx

### Bug description

When reverseDirection is set as false and its last item appear, it just stop to scrool

Codesandbox: https://codesandbox.io/s/festive-rain-kgx5v5?file=/src/Carousel/index.jsx:2466-2482

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2
