### ISSUE TITLE
Swiper slides suddenly disappear during swipe

### ISSUE THREAD

**Issue by matinkg** [nolimits4web/swiper#6962]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-default-forked-jrk5wg?file=%2Fsrc%2FApp.jsx%3A13%2C1

### Bug description

When swiping slides, slides become invisible suddenly. (Maybe if the swipe distance is a little long).

### Steps to reproduce:
1. Open the sandbox: https://codesandbox.io/p/sandbox/swiper-react-default-forked-jrk5wg?file=%2Fsrc%2FApp.jsx%3A13%2C1
2. Swipe slider from right to left (it should be a little long swipe)
3. Slides suddenly disappear

![ezgif-1-e1017b43a9](https://github.com/nolimits4web/swiper/assets/47145617/06ef0ff6-6632-47d4-9aab-ab3397ea08ec)

### Expected Behavior

Slides shouldn't become invisible during the swipe.

### Actual Behavior

Slides become invisible suddenly.

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Windows Chrome 116.0.5845.97 / Windows Firefox 116.0.3 (32-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You need to have more slides https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2

**Comment by matinkg** [comment]
> You need to have more slides https://swiperjs.com/swiper-api#param-loop
> 
> > Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2

It seems it's not working. I created many more slides but the problem is still exist without any changes.
