### ISSUE TITLE
When slides per view and loop are used together, loop becomes invalid

### ISSUE THREAD

**Issue by gswy** [nolimits4web/swiper#6963]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-vue-autoplay-progress-forked-n3673m?file=%2Fsrc%2FApp.vue%3A3%2C3

### Bug description

When using slides per view and loop together, the array should be repeatedly loaded to the end after the last element is displayed. However, in reality, after the rotation to the last element, there is no subsequent filling, which cannot achieve the purpose of looping

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by thomaswre** [comment]
I can only concur that this combination is also troublesome in Core. SlidesPerView more than 1 (I use 3) and loop creates erratic behavior where the pagination skips images in a not consequent way.

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-loop

> Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2

**Comment by XionGuo37** [comment]
same issue
