### ISSUE TITLE
If set loop: true and centeredSlidesBounds: true, fraction pagination active slide shows NaN on screen resize

### ISSUE THREAD

**Issue by sleepmanserg** [nolimits4web/swiper#6967]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/jovial-morning-wfl6l9?file=/index.html

### Bug description

If set `loop: true` on mobile only from 320 to 768 breakpoint and `centeredSlidesBounds: true` by default, when you resize screen from 768 to smaller, fraction pagination active slide shows NaN and Navigation stops working.
If you will refresh page everything is working as expected.

### Expected Behavior

Show active slide in fraction pagination on screen resize as it works on page load.

### Actual Behavior

Active slide shows NaN in fraction pagination on screen resize.

### Swiper version

10.0.4

### Platform/Target and Browser Versions

macOS, Firefox 116.0.3, Chrome 114.0.5735.198

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by m345054** [comment]
I have this issue too
