### ISSUE TITLE
Zoom two fingers on iPhone is broken

### ISSUE THREAD

**Issue by JanPavlin234** [nolimits4web/swiper#6969]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/400-zoom/core

### Bug description

Video: https://photos.app.goo.gl/DPUcJyqQAk7M2jRL8

After few seconds browser send event **pointercancel** and zooming stop work. On Android is all ok.
I dont find any solution.

### Swiper version

10.1.0

### Platform/Target and Browser Versions

iPhone 13 (iOS 16.3.1) Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by JanPavlin234** [comment]
I found solution.
Add to CSS:

.swiper-slide { 
    touch-action: none;
}

**Comment by nolimits4web** [comment]
Should be fixed in v11
