### ISSUE TITLE
Mousewheel option on safari casually jumps 2 slides

### ISSUE THREAD

**Issue by kalimantos** [nolimits4web/swiper#6979]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/270-mousewheel-control/core

### Bug description

Scrolling casually make swiper jump 2 slides instead of 1 on safari (i'm using a trackpad)

https://github.com/nolimits4web/swiper/assets/4092865/7b425781-6a79-4be5-ba9d-3542ede988a1

### Swiper version

10.2.0

### Platform/Target and Browser Versions

macOS Ventura 13.3.1 - Safari Version 16.4 (18615.1.26.110.1)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use issues search
