### ISSUE TITLE
SwiperOptions missing [config] parameter

### ISSUE THREAD

**Issue by marshall86** [nolimits4web/swiper#6980]
### Clear and concise description of the problem

Swiper Version 10 for Angular (swiper element) doesn't have the [config] parameter to initialize the slider with a custom SwiperConfig object. It would be nice and easier to upgrade from version 8+ if you would be able to make this possible.

### Suggested solution

Add config parameter in the swiper-container to allow a SwiperOptions object.

### Alternative

Make it clear how to implement a custom configuration in the controller

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is no Swiper Angular in v10

**Comment by marshall86** [comment]
swiper element is the one you suggest in your doc to use in ionic and angular...

**Comment by nolimits4web** [comment]
Yes and you can use manual init to pass the whole object

**Comment by marshall86** [comment]
yes... What i'm asking here is to make it possible with a dynamic configuration from the controller instead of the html. Thanks

**Comment by EliezerB123** [comment]
@marshall86 We're actually considering moving to v8 , because we're hoping it has better Angular support than v10. (And because the Shadow Dom swiper 10 uses is godawful to make custom CSS modifications to.)

Any chance you happened to know where we can find the API documentation for Swiper v8?

**Comment by marshall86** [comment]
> @marshall86 We're actually considering moving to v8 , because we're hoping it has better Angular support than v10. (And because the Shadow Dom swiper 10 uses is godawful to make custom CSS modifications to.)
> 
> Any chance you happened to know where we can find the API documentation for Swiper v8?

If they moved to v10 they should provide good support for all the frameworks/libraries they say they support.. downgrading, in my opinion, it's not an option because with the time it might stop working or not being compatible with some devices or browsers..
