### ISSUE TITLE
slidesPerView is decimal and loop is true

### ISSUE THREAD

**Issue by ZemanJiri** [nolimits4web/swiper#6981]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-navigation-forked-rl3258?file=/src/App.jsx:31,27

### Bug description

I used Swiper `8.4.7`. I decided to upgrade to the latest version (`10.2.0`). But i have problem with `slidesPerView`. If i set it on decimal value and my second props `loop` is `true`. The slider jump from first to last. But it only does it when I have 3 items.

### Expected Behavior

Old right behaviour is here: https://www.koop.cz/likvidace-pojistnych-udalosti
Looking for https://snipboard.io/C5Skuh.jpg

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Linux 22.04.3 LTS, Chrome 115.0.5790.170

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check requirements for loop mode in documentation

**Comment by ZemanJiri** [comment]
`loopedSlides` is way.
