### ISSUE TITLE
Disabling swiper does not disable it

### ISSUE THREAD

**Issue by xApep** [nolimits4web/swiper#6985]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-slides-per-view-forked-nvxxns

### Bug description

If you set `enable: false` all  navigation elements, interactions, appending inline styles still works; you can also swipe it. 

See at codesand link that when screen is larger then 1024px, nothing even happens with disabling it (take a look at inspection; html code).

```
var swiper = new Swiper(".mySwiper", {
  slidesPerView: 1.5,
  spaceBetween: 30,
  breakpoints: {
    768: {
      slidesPerView: 2.5,
    },
    1024: {
      enable: false,
    },
  },
  pagination: {
    el: ".swiper-pagination",
    clickable: true,
  },
});
```

### Expected Behavior

It should disable swiper functionality and also no inline style should not be appended to swiper elements.

### Swiper version

10.2.0

### Platform/Target and Browser Versions

macOS chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check docs, there is no `enable` parameter

**Comment by xApep** [comment]
@nolimits4web and what is this then? https://swiperjs.com/swiper-api#param-enabled

**Comment by nolimits4web** [comment]
@xApep maybe a hint for you that you have a typo in your example?

**Comment by xApep** [comment]
@nolimits4web one of that embarrassing  moments when you want to hide under the rock.

Thank you!!
