### ISSUE TITLE
SwiperJs conflict with jetmenu on mobile with iOS 16

### ISSUE THREAD

**Issue by fbracci71** [nolimits4web/swiper#6988]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.visitmontaione.com/it/shop

### Bug description

Opening the link https://www.visitmontaione.com/it/shop you can see that the jetmenu (clicking on hamburger icon) stop working after 8/10 seconds.
This bug can't be reproduced on inspection/console of the browser and selecting the mobile device, but only on a real device.
Of course if I disable the sliderjs on the page, jetmenu works properly.
This issue is present on iphone with iOS 16. **The issue is NOT present on Android systems.**

### Swiper version

Don't know

### Platform/Target and Browser Versions

iOS 16

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Unfortunately i can not see swiper on the link you have provided. The link with the issue must be in codesandbox, otherwise issue may be in another library or your implementation
