### ISSUE TITLE
Bug when using the TAB key on sliders with forms

### ISSUE THREAD

**Issue by steph643** [nolimits4web/Swiper#699]
How to reproduce:
1- Open Chrome  v33.0.1750.154 m
2- Go to http://www.idangero.us/sliders/swiper/demo-apps/simple/index.html
3- Press the TAB key -> it goes to the slide with the form, but the slide position is not right

Under Firefox and IE, the above link seems to work fine. However, I got other samples that produce the same bug.

Workaround : disable sequential focus navigation in forms by using tabIndex="-1" (more here: http://stackoverflow.com/questions/457070/how-do-i-disable-tabs-for-a-tag)

**Comment by stefankutko** [comment]
The following css rules seem to work well for me: 

 .swiper-slide {
    visibility: hidden;
  }

 .swiper-slide.swiper-slide-active {
  visibility: visible;
 }
