### ISSUE TITLE
Zoomed image can not move when only one swiper-slide image in an Ionic project

### ISSUE THREAD

**Issue by eblazeix** [nolimits4web/swiper#6992]
Hi,

First of all, thanks for your amazing package !

I am using Swiper JS on an Ionic 7 Angular 16 project. I use the version 10.0.4.

The package works fine and I managed to set the maximum ratio with the zoom parameter object. The only issue is that I have only one image (which is actually a canvas, but for this example I will use an image, which behaves exactly the same way).

Here is an example. I can not move the image when the full image is displayed to fit the screen size, and this is perfect for me :

![image](https://github.com/nolimits4web/swiper/assets/57865012/c0fa186e-3d9f-4488-a685-4cf27e52d0fb)

But, when I zoom in, i can not move the image to the left, to the right, to the top or to the bottom :

![image](https://github.com/nolimits4web/swiper/assets/57865012/47619d90-11dc-4659-937a-060cc240347e)

When i try to add another swiper-slide, there is no problem and I can move the image (even when the zoom is at his minimum because swiper prepares the transition with the next slide).

I searched in the API documentation, I tried a lot of parameters, but I didn't find one that let me move the zoomed image when there is only one image (or one slide). For example, I tried to add hidden slides, I tried to set the loop parameter of swiper-container to true, but this is not working with only one slide (which is totally normal).

When I try it with the sandbox with only Swiper JS, the behavior is not the same and the image can be moved when zoomed in.

Here is a repository to reproduce the behavior : https://github.com/eblazeix/test-swiper-single-slide-zoom

Thanks a lot !

Emmanuel

**Comment by nolimits4web** [comment]
1. Update Swiper to latest
2. Provide a codesandbox with the issue using Swiper Element

**Comment by eblazeix** [comment]
Thanks a lot for your quick answer : I have installed the new version **10.2.0** of Swiper, and the problem is **solved** ! Swiper lets me now move the image, even when only one zoomed image ! Thanks again for this great package
