### ISSUE TITLE
Virtual Slides Parameters doesn't work with Swiper Element

### ISSUE THREAD

**Issue by meotimdihia** [nolimits4web/swiper#6994]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-virtual-slides-forked-vtmwzm?file=/src/App.jsx:38,18-42,11

### Bug description

Virtual Slides Parameters don't work for Swiper Element.
https://swiperjs.com/swiper-api#virtual-slides-parameters
I tried with these options:
```ts
    <swiper-container
      ref={swiperElRef}
      zoom={true}
      virtual={{
        enabled: true,
        addSlidesBefore: 2,
        addSlidesAfter: 2
      }}
     >
```
![image](https://github.com/nolimits4web/swiper/assets/300961/bac2b155-6594-4210-b255-f10550083c88)

### Swiper version

^10.2.0

### Platform/Target and Browser Versions

Chrome, macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/blog/using-swiper-element-in-react

**Comment by meotimdihia** [comment]
> https://swiperjs.com/blog/using-swiper-element-in-react

It looks like downgrade O_O I tried and can't get this to work.

**Comment by meotimdihia** [comment]
I guess you haven't implemented it yet => created a feature request... https://github.com/nolimits4web/swiper/issues/6993
This is not as easy as it looks.
