### ISSUE TITLE
codesandbox vue demos are broken

### ISSUE THREAD

**Issue by dreitzner** [nolimits4web/swiper#6999]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/5d5gng?file=/src/App.vue

### Bug description

We need to provide a Reproduction link with each issue.
It is reccomended to fork one of the demos.

> You can fork one of our [demos](https://swiperjs.com/demos) in codesandbox to get start.

Both vue demos for Thumbs gallery are broken, which makes a reproduction a lot harder.
Here are the links taken from the demo pages:
- https://codesandbox.io/p/sandbox/tlpzmp?file=/src/App.vue
- https://codesandbox.io/p/sandbox/5d5gng?file=/src/App.vue

I would love to create a bug ticket, but I'm blocked by the demo not working, which is sad....

### Expected Behavior

The vue demos work

### Actual Behavior

The vue demos do not work, so forking them does not make sense.

### Swiper version

^10.0.0

### Platform/Target and Browser Versions

codesandbox on windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
1. Those demos supposed to be fixed
2. This issue is not related to Swiper but to website
3. You should be able to create your own fiddle
