### ISSUE TITLE
SwiperJS doesn't work with certain numbers of slides

### ISSUE THREAD

**Issue by prismspecs** [nolimits4web/swiper#7001]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/prismspecs/7fgyq6Lj/6/

### Bug description

Notice that with 6 slides and showing 4 at a time it does not work. Then, reducing the number to showing 3 at a time it works fine.

### Expected Behavior

Works

### Actual Behavior

Doesn't work, skips around, can't progress beyond final slide, etc.

### Swiper version

latest

### Platform/Target and Browser Versions

macOS FF, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please do search for issues before opening new one and read docs for loop mode requirements
