### ISSUE TITLE
Navigation buttons dislocate when tabbing between slides (slide = input element)

### ISSUE THREAD

**Issue by mor-stampli** [nolimits4web/swiper#7002]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/thirsty-minsky-k7h72z?file=/src/App.js

### Bug description

I have a swiper component that all slides contains input element.
when user click tab and gets to the swiper edge,
the navigation buttons lose their position.

** i checked also without my custom navigation buttons
and the issue occurs with the native navigation buttons as well.

i saw that all swiper demos doesn't include interactive elements.
any idea how to deal with this issue?

https://github.com/nolimits4web/swiper/assets/141311053/f96075b5-3242-46d5-8e95-d49f1d984d84

### Expected Behavior

i expect that when clicking tab the swiper will behave as usual and will simulate navigation click.

### Actual Behavior

clicking tab leads to a weird behavior and the navigation buttons are dislocated.

### Swiper version

9.4.1

### Platform/Target and Browser Versions

latest macOs latest chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
V9 is not maintained anymore. If your issue happens with v10, create a new one

**Comment by mor-stampli** [comment]
@nolimits4web i will check your recommendation thanks !
