### ISSUE TITLE
Swiper/React - SwiperProps interface doesn't include SwiperOptions (Typescript 4.8)

### ISSUE THREAD

**Issue by arodik** [nolimits4web/swiper#7003]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-10-2-interface-problem-vwn9g5

### Bug description

I've updated Swiper to the latest (10.2) version and have a problem. My typechecker fails because it doesn't see some properties such as `modules` in Swiper component's props. We use Typescript 4. Everything is ok on TS5, but unfortunately, we can't upgrade right now.

For some reason SwiperProps interface doesn't include fields from SwiperOptions, despite it extends from it.
https://github.com/nolimits4web/swiper/blob/master/src/swiper-react.d.ts

You can reproduce the issue in the linked codesanbox. Run `npm run tsc` and you'll see the error.

### Expected Behavior

All fields from `SwiperProps` are accessible, including fields from `SwiperOptions`

### Actual Behavior

Only fields from `SwiperProps` interface are available, `SwiperOptions` fields are missing

### Swiper version

10.2

### Platform/Target and Browser Versions

Typescript 4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Thank you, but Swiper TS definitions are done to support TS v5, this PR can break `esnext` module resolution. Consider upgrading to TS v5
