### ISSUE TITLE
Textlink to swipe to layer

### ISSUE THREAD

**Issue by elEglon** [nolimits4web/Swiper#701]
Hello all,
I want to be able to navigate via Textlink from the first slide to the 2nd, third, ... nth slide. Would you please be that kind and tell me what script is needed for the link?

Thank you
Eglon

Solved! Thank you Vladimir!

(Slides are counted beginning from 1)

`<a onclick="mySwiper.swipeTo(2)" href="#">klick</a>`

**Comment by Tank-y** [comment]
Hello!
I'm working on my portfolio using your slider. Very nice plugin!

I'm experiencing the same issue.
I can't make those text links work and I don't know why.
It would be great if you could help me.

I've made a fiddle.
They usually work but this time, I dont know why, it doesn't. (works fine on my laptop but not online…)
It's like it doesn't load your plugin.

http://jsfiddle.net/Tanky/wL5vgLz2/1/

**Comment by garethhorner** [comment]
How can I achieve the above mentioned solution using text links in a div outside the swiper? 
Any help will be greatly appreciated.
