### ISSUE TITLE
Overflow: clip does not work well on Firefox

### ISSUE THREAD

**Issue by mateuswetah** [nolimits4web/swiper#7017]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/agitated-moon-tjg9tt?fontsize=14&hidenavigation=1&theme=dark

### Bug description

As discussed here:
https://github.com/nolimits4web/swiper/pull/6738#issuecomment-1701016975

The recently introduced `overflow: clip` instead of `overflow: hidden` in the `.swiper-wrapper` class has introduced some issues. When using a carousel inside a flex container, the overflow `hidden` worked equally in any browser. Now, in Firefox, the Carousel ends up expanding more than it should.

### Expected Behavior

The linked provided for reproduction offers a comparison of the  strategies:
https://codesandbox.io/s/agitated-moon-tjg9tt?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js

Both carousels should be equal.

### Actual Behavior

This screnshot shows how things are in Firefox on the linked provided for reproduction:
https://user-images.githubusercontent.com/1184874/264720125-3fe75889-d0a7-4efd-bdcd-3df12cac8606.png

### Swiper version

10.0.0

### Platform/Target and Browser Versions

Linux Ubuntu 20.04, Firefox 117

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
But that is a Firefox bug, not with Swiper. You should open an issue there. In Swiper 11 default overflow will be back to the "hidden"

**Comment by mateuswetah** [comment]
Wait, but why will it be back? Would you have a release date planned?

I considered that it might be specific to Firefox, but I'm not sure if it is some kind of CSS specification interpretation that may be "correct" on Firefox and misunderstood on Chrome...

**Comment by nolimits4web** [comment]
> Wait, but why will it be back? Would you have a release date planned?
> 
> I considered that it might be specific to Firefox, but I'm not sure if it is some kind of CSS specification interpretation that may be "correct" on Firefox and misunderstood on Chrome...  

Because it produces more issues and problems than goodies :) Seems to be not many know how it works and what is it for. And if anyone needs "clip", it can be easily set with one line of custom CSS
