### ISSUE TITLE
swiper.virtual.removeSlide has a bug

### ISSUE THREAD

**Issue by xiayejinchen** [nolimits4web/swiper#7020]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/nolimits4web/swiper.git

### Bug description

When using  swiper.virtual.removeSlide to delete a cached virtual slide, for example, if 4 slides have been cached and slide 2 is deleted, two slides 3 will appear.

Because virtual.cache is an object, just delete key of virtual.cache，for example 2，virtual.cache will be equal to {1：'slide 1', 3: 'slide 3', 4: 'slide 4'}. And After swiper.virtual.update, virtual.cache will be equal to {1：'slide 1', 2:'slide 3',  3: 'slide 3', 4: 'slide 4'}

### Swiper version

8b7386450e006f2b335b0f8e272f59f3d40a8d9f

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by xiayejinchen** [comment]
you can see the demo in `https://github.com/xiayejinchen/test.git`

**Comment by nolimits4web** [comment]
Why not create CodeSandbox?

Kind regards,
Vladimir Kharlampidi
________________________________

**Comment by xiayejinchen** [comment]
You can see the demo at `https://6lxtmm.csb.app/`。

After you see the 'slide 4', then delete 'slide 3', you will see two 'slide 4'
