### ISSUE TITLE
Swiper 'resize' event bubble to window

### ISSUE THREAD

**Issue by RealOFF** [nolimits4web/swiper#7030]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/beautiful-keldysh-l45r5q?file=/src/index.html

### Bug description

**Description:**
Swiper dispatch ‘resize’ event if swiper-container was resized. The 'resize' event bubble to window because in onAny method swiper create instance of CustomEvent with bubble true. By web specification the ‘resize’ event on window should be called only if size of window was changed. But swiper dispatch 'resize' on container resize and this event bubble to window. The behaviour that different from web standard can lead to unexpected things because all libs focus on the standard. Thus unexpected ‘resize’ event of window can lead to bugs and unnecessary rerenders in app.

**Example in my app:**
 This ‘resize’ events also dispatched if swiper-container or swiper-container parent change display value to ‘none’. This happening when we switch from activated route. It’s mechanism from ionic-router. The ionic-router may not unmount page from DOM and just set this page display: none. It turns out that a resize event is dispatched when a route is switched if a swiper exists on that page. And this dispatch will be invoked on window because this event bubbling.    For example now if user switch from activated route with swiper and cdk-virtual-scroll-viewport then all list in cdk-virtual-scroll-viewport will be rerendered and this will call unnecessary calculation in `@angular/cdk/scrolling module`. This occurs because cdk-virtual-scroll-viewport subscribes to the window ‘resize’ event and causes the viewport to be recalculated each time the resize event is called. But it expects the event to be fired only when the window size has changed, which is what it should be according to the specification.
 
 **Codesandbox description:**
At the my codesandbox example you can see that after switching the swiper-container wrapper display to "none", the 'resize' event will be fired on the window. It will not call 'resize' event on widow after display: block because swiper not call 'resize' event if old height is zero.

### Expected Behavior

Swiper should not dispatch 'resize' event with bubbles: true.

### Actual Behavior

Swiper dispatch 'resize' event with bubbles: true.

### Swiper version

10.0.4

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use events-prefix to avoid it
