### ISSUE TITLE
Swiper does not work properly with loop and virtual enabled

### ISSUE THREAD

**Issue by Fakamatony** [nolimits4web/swiper#7032]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-react-virtual-slides-forked-lylft8?file=/src/App.jsx

### Bug description

If you put virtualization and endless slides, then if you scroll forward, there will be such an order "Slide 1, Slide 1, Slide 2, Slide 3 ..." it should be naturally different.

### Expected Behavior

The order of the slides should be "Slide 1, Slide 2, Slide 3, Slide 4..."

### Actual Behavior

The order of the slides at the moment is "Slide 1, Slide 1, Slide 2, Slide 3..."

### Swiper version

10.0.0

### Platform/Target and Browser Versions

Windows 10 Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by torchsmith** [comment]
Maybe related to https://github.com/nolimits4web/swiper/issues/6351

**Comment by Fakamatony** [comment]
> Может быть связано с #6351

If you roll back to version 8.4.5, it starts to work incorrectly, but in a different way

**Comment by nolimits4web** [comment]
This is what i see in your codesandbox, can't see the issue
https://github.com/nolimits4web/swiper/assets/999588/17e72c68-b5cc-4fa8-9640-c739555420a1
