### ISSUE TITLE
Autoplay with delay 0 still delayed

### ISSUE THREAD

**Issue by Ivan-dev-RED** [nolimits4web/swiper#7033]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-delay-0-ngdzxy

### Bug description

I want the smoothest and most uninterrupted scrolling possible, but for some reason, with a `delay: 0`, **it still sets the minimum delay.**

### Expected Behavior

At delay 0, scrolling is not interrupted.

### Actual Behavior

At delay 0, scrolling is interrupted with the minimum delay.

### Swiper version

^10.2.0

### Platform/Target and Browser Versions

Browser Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Ivan-dev-RED** [comment]
I also checked `onAutoplayTimeLeft `and was surprised that it flies at great speed and the parameters have rather strange values.

```
onAutoplayTimeLeft={(s, time, progress) => {
   console.log("time:", time, "progress:", progress);
 }}
```

![image](https://github.com/nolimits4web/swiper/assets/104828301/41fdca5a-d543-4f51-9135-6a42e7258532)

**Comment by nolimits4web** [comment]
The delay for amount of requestAnimationFrame will be applied anyway
