### ISSUE TITLE
Swiper blocks browser zoom (pinch)

### ISSUE THREAD

**Issue by stupkad** [nolimits4web/swiper#7035]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos

### Bug description

When using swiper within an mobile application, it actually blocks the browsers default zoom behaviour. In the swiper demo page, zooming does work in areas of headings and descriptions, but not where the swiper component is placed.

### Expected Behavior

Zoomin the application by pinch should work. The whole application (together with the swiper) should be zoom-able.

### Actual Behavior

Zoomin the application by pinch does not work.

### Swiper version

10.2

### Platform/Target and Browser Versions

Mobile Safari, Mobile Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It works

**Comment by stupkad** [comment]
@nolimits4web Hmm, it **does not work** when you start pinching with both fingers within the swiper component.
