### ISSUE TITLE
Clickable pagination does unexpected behavior

### ISSUE THREAD

**Issue by ChristopherPHolder** [nolimits4web/swiper#7043]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-pagination-forked-wv6st4?file=/index.html

### Bug description

The clickable pagination bullets do not work properly when using the following swiper options: 

      var swiper = new Swiper(".mySwiper", {
        loop: true,
        navigation: true,
        autoplay: true,
        pagination: {
          clickable: true,
          el: ".swiper-pagination"
        },
        slidesPerGroup: 3,
        slidesPerView: 3
      });
      
 And when using 8 slides. 

### Expected Behavior

If there are 3 pagination bullets and i click one it should show as activated and should no longer be clickable.

An example of the the expected behaviour for the activated bullet is visible with the auto-play. It is changing the activated bullet correctly or as expected. 

### Actual Behavior

The activated bullet (highlighted with css) is not the same as the one i click. 

Reproducible interactions:

swiper is nuly initiliyed and is on the first slide. 

If i click on the second (middle) bullet, it  highlights  and changes the slides it as expected. 

If i now select the third (right) bullet, it changes the slides but does not highlight it. If i click on it again nothing happens. 

If i know click on the middle bullet which is highlighted, it highlights the first (left) bullet and changes the slides. 

![swiper-js-bug](https://github.com/nolimits4web/swiper/assets/40126819/a84cba7f-51d6-4968-a96a-887c6c824d5b)

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You have slidesPerGroup: 3 and only 8 slides which is not even to 3. It is required for loop mode to work correctly. Rather disable loop or add empty slide to the end

**Comment by ChristopherPHolder** [comment]
I understand its a bit weird but i can see the arrow navigations work and so do the autoplay.  

Maybe this is a question of having the virtual set to true.

Group 1 [ Slide 1, Slide 2, Slide 3 ] 
Group 2 [ Slide 4, Slide 5, Slide 6 ]
Group 3 [ Slide 7, Slide 8, Slide 1 ]

It seems like this is the behaviour used in swiper ^8.4.7

If this does not seem like it is the behaviour expected, do you have a suggestion on how i can achieve this result?

**Comment by ChristopherPHolder** [comment]
> You have slidesPerGroup: 3 and only 8 slides which is not even to 3. It is required for loop mode to work correctly.

But the loop works fine if i do not navigate using the clickable pagination bullets. 
Can we not have the same behaviour there? @nolimits4web

**Comment by ChristopherPHolder** [comment]
@nolimits4web Sorry to be persistent, i just want to be sure that i should attempt to implement this behavior on my own. 
Since this was the behaviour in v8, the app needs it when updating to v10.
