### ISSUE TITLE
Swiper and Vue problem with focus and click

### ISSUE THREAD

**Issue by schirrel** [nolimits4web/swiper#7044]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-vue-default-forked-dpnw4x?file=/src/App.vue

### Bug description

When using swiper with combobox or autocomplete component such as for vuetify, the click inside the component seems to be intercepted by swiper and is no triggering the component behavior of open the floating list.

It does happens to sometimes the list opening, but most of the time is not

Code for reproduction
https://codesandbox.io/s/swiper-vue-default-forked-dpnw4x?file=/src/App.vue

Video of the strange behavior

https://github.com/nolimits4web/swiper/assets/6757777/9256e7ba-a644-4ae9-8309-561a9a2adc82

### Expected Behavior

When click on the combobox it open its floating list like on the playground:
https://play.vuetifyjs.com/#eNrVVE1v2zAM/SuCTi3gjzUtisFIg+6jh+2wDdtudQ6KzaRqZdmQ5DRFkf8+inISx1nX3IYeilp8FPneI5XbZ25NkX5ommTZAs/42EHVKOFgkmvGxsu4EKak73CqtRNSg2Fz1coNQJCpH7fHLlcx/LNXOT8b5bwHdnA1q2f1qh9mbBlXdQkK7yyFaiHn+3AmkZ+vSP+HqBIzuvoZ5qJVbh+ejNNd0z5TCqv/zb0EbaV7QhiLz2vjxEwdlNgI/PRSylsS2YhiMKI9gYfwseL8ebeNAe3WNmy1j4S1Hqe9fcejLYxsHGXBqkGLkTLtEnsO1UrhRMZOTtnVhJ10MUZaM3Y7ithFxC4j9j5iZ++mUYDJp4yNuuP6lD7WvnnXjkdcSf1gk3tba3yEVBc9smgglg33cn7nXGOzNC1KjZk4BLk0iQaX6qZK8fk6OX+6Pk/Ok7PLtJTWbWIxumoTquZLTXO9xo6y8vriSjSDtgGg1p1AnLWfdPYah2tMS02rnawgLuuKyFwELr1wAraKZzghCwaL5Lxzhtp4wke0elUu9jionWLDJZjYgC7BgDlW0uBaX9YAOpDWjdob7iyu4VwuhlPGVZcKzPfGyVrv2y6Uqh+/UsyZFrZaijsoHv4Sv7eroOmHAWLW0++EWQC+KA/f/PoGK/zegvimW/9b8g/wJ9hatZ5jSPvY6hJp9/KI7RfaHqkXv+3Nyvn33onyRMkNyqd5+Ff+kvQdXXR76+I64mQ+2hkmz6d/AJnbDoI=

### Actual Behavior

When clicking on the combobox the list dont get triggered and open.

ps. i event tried `touch-start-prevent-default` but no success

### Swiper version

10.0.0

### Platform/Target and Browser Versions

MacOS 13.4.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
:touch-start-prevent-default="false"

**Comment by schirrel** [comment]
@nolimits4web thanks for the response, but  i think you may havent read the hole issue description because i've add that i tried it and havent worked at all (the reproduction link has it also)

**Comment by schirrel** [comment]
Hi @nolimits4web thanks a lot.
  Also i am facing the same issue using the html element without vue, in this case i tried to use `touch-start-prevent-default="false"` and also only `touch-start-prevent-default`, but no success. In this case i shall use thru javascript directly or has another (and correct) way to use as html attribute?
