### ISSUE TITLE
Loop bug, the number of slides is less than 5 and the width is less than 36%, the loop fails.

### ISSUE THREAD

**Issue by stefan-hui** [nolimits4web/swiper#7046]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slides-per-view-auto-forked-hy629w?file=/index.html

### Bug description

Scrolling to the end doesn't work when loop is turned on and slidesPerView is auto.
After experimentation, the trigger conditions are the following.

1. the number of slides is less than or equal to 5.
2. slides width is less than or equal to 36%.
3. open loop.
4. slidesPerView is auto.

### Swiper version

10.2.0

### Platform/Target and Browser Versions

macOS Chrome 116.0.5845.179

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/swiper-api#param-loop
