### ISSUE TITLE
Problem when combine slidesPerView and CenteredSlides. First and last item can't be selected

### ISSUE THREAD

**Issue by srodriguezomatech** [nolimits4web/swiper#7049]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/timeitem-7fn8zp

### Bug description

I combined several parameters in swiper, the most prominent are slidesPerView:3, centeredSlides:true and direction: "vertical", I'm trying to simulate a "native clock" from iOs to web. The thing is that although I add the property "centeredSlidesBound:true" what happens is that the first item and the last one of the array are visible but they can't be selected/activated.

Example: 

```
  const swiperOptions = {
      height: 150,
      slidesPerView: 3,
      centeredSlides: true,
      spaceBetween: 0,
      centeredSlidesBounds: true,
      direction: 'vertical'
  }

<Swiper onSlideChange={handleSlideChange} {...swiperOptions}>
      {data.map((item, index) => (
        <SwiperSlide key={index}>
          <TimeItem time={item.time} isSelected={index === activeIndex} />
        </SwiperSlide>
      ))}
</Swiper>
```

### Expected Behavior

it should be possible to activate the first and last items of the array.

### Actual Behavior

The first and last items are visible, but cannot be activated.

### Swiper version

9.4.1

### Platform/Target and Browser Versions

macOs Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You need to disable centeredSlidesBounds, it won't let to set active slides on slides before /after slidesPerView/2
