### ISSUE TITLE
Navigation and thumbnails don't work correctly after hiding some slides.

### ISSUE THREAD

**Issue by noiseymur** [nolimits4web/swiper#7054]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/

### Bug description

According to the documentation, calling `swiper.update()` after any manual DOM changes should update it accordingly.  It does, but not well enough. For example, I have a slider with thumbnails. I hid some slides by adding `display: none`, to them and updated the swiper instance. But when navigating through the main slider, thumbnails do not get active accordingly.

### Expected Behavior

I expect it to fully ignore the hidden slides. But seems like it still tries to activate them in thumbnails slider.

### Swiper version

9.3.2

### Platform/Target and Browser Versions

Windows 11 Chrome 116.0.5845.188

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Sorry but hidden slides are not supported, you should remove them from dom
