### ISSUE TITLE
watchOverflow doesn't work with centeredSlides: true parameter

### ISSUE THREAD

**Issue by q4crm** [nolimits4web/swiper#7056]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/t09xe6da/

### Bug description

watchOverflow doesn't work with centeredSlides: true parameter.

You can see the issue here.  https://jsfiddle.net/t09xe6da/1/

I also drew attention to another problem. If the parameter **centeredSlides: true** and **loop: true**, the loop does not work on a forward slide, but does work on a backward slide.

Sorry for bad English.

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Windows, Yandex Browser 23.7.5.739

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
watchOverflow disables sliding when there is no sliding available which is not the case for centeredSlides. As for loop mode see documentation for loop mode and its requirements
