### ISSUE TITLE
Swiper CSS property causes Google to flag the page as unusable on mobile

### ISSUE THREAD

**Issue by jokerisgod** [nolimits4web/swiper#7057]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://search.google.com/test/mobile-friendly/result

### Bug description

Swiper slider CSS property for .swiper { overflow: clip; } causes Google mobile friendly test to fail at https://search.google.com/test/mobile-friendly/result

This change was done in recent versions.

With the overflow: hidden; the usability tool marks the slider as usable on mobile. This is very significant for SEO/indexing.

.swiper {
  margin-left: auto;
  margin-right: auto;
  position: relative;
  overflow: hidden;
  **overflow: clip;   <-------------- causes the issue**
  list-style: none;
  padding: 0;
  /* Fix of Webkit flickering */
  z-index: 1;
  display: block;
}

### Swiper version

10.3.0

### Platform/Target and Browser Versions

Chrome, Ubuntu 20.04

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can change it on your side

**Comment by Kapitan-Nemo** [comment]
@jokerisgod THANK YOU. Really.
