### ISSUE TITLE
autoplay with disableOnInteraction true broken in 10.3.0

### ISSUE THREAD

**Issue by cduff** [nolimits4web/swiper#7059]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-autoplay-broken-z4ptfx

### Bug description

`autoplay` seems broken in the recent 10.3.0 release. Where `disableOnInteraction` is `true` (the default) it stops on the 2nd slide.

See my reproduction link, which is Swiper's own `autoplay` example with just the `disableOnInteraction: false` line commented out.

### Swiper version

10.3.0

### Platform/Target and Browser Versions

Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by simonhrogers** [comment]
Also `10.2.0`, I have downgraded to `10.1.0` which works for now.

**Comment by cduff** [comment]
> Also `10.2.0`, I have downgraded to `10.1.0` which works for now.

10.2.0 working fine for me. My reproduction link above also works fine if you target 10.2.0.

**Comment by cduff** [comment]
Fixed for me in 10.3.1. 👍
