### ISSUE TITLE
Broken loop swipe with slidesPerView 4 and slidesPergroup 3 and total amount of slides 8 

### ISSUE THREAD

**Issue by vvsmg** [nolimits4web/swiper#7064]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/swiper-demo-21-loop-mode-with-multiple-slides-per-jahhuy?file=index.html

### Bug description

Infinite swiping stops at last slide, next arrow is still clickable, but nothing happens, previous arrow works as slidesPerGroup: 1. Amount of slides 8, which follows requirement total number of slides must be >= slidesPerView * 2.

slidesPerView: 4
slidesPerGroup: 3
loop: true

### Expected Behavior

Swiping to the right continuous infinitely according to option slidesPerGroup: 3, same as swiping to the left.

### Actual Behavior

Infinite swiping stops at last slide, next arrow is still clickable, but nothing happens, previous arrow works as slidesPerGroup: 1.

### Swiper version

9.x 10.x

### Platform/Target and Browser Versions

macOS, Windows, Chrome, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by benwallis** [comment]
Loop mode rarely works properly if slidesPerView is more than 1

**Comment by Daayon** [comment]
I don't understand why all issues are being closed when some critical options are (still) not working. Like for example: continious autoplay or loop functionality. 

I am considering to use the Splide library because of this.

**Comment by HonzaVrkota** [comment]
I Have same problem. 
With sliderPerView >= 3
next button slide only once and then is stuck.
Touchgin slide is also bugged
Downgrade to v10.3.0 works.

**Comment by iksent** [comment]
Everything works like a charm in v7 and upgrading to v10 totally breaks loops for me.

**Comment by dmts17** [comment]
I'm also having a similar issue, I even tried to downgrade to the versions mentioned above but the issue persisted. Is there another possible solution?

**Comment by Djolhan1** [comment]
Same issue here, to reproduce, simple.
Just add 4 slide or 5 slides on a 3 row. Loop will not work. 6 slides on a 3 row will works.

https://codesandbox.io/s/swiper-centered-forked-trvzxq

**Comment by nolimits4web** [comment]
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one
