### ISSUE TITLE
Overflow breaks swipe slide change on touch devices

### ISSUE THREAD

**Issue by marcfal** [nolimits4web/swiper#7065]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-scroll-container-forked-r5ffrg?file=/index.html

### Bug description

Hi,

I have noticed a weird behavior on touch devices. The easiest way to reproduce is in the reproduction sample :

- two slides
- set overflow-y: auto; on swiper slides.
- try to swipe on a touch device

Please note that in order to reproduce the bug, you must open the demo in a separate tab and **emulate a touch device** (I used Chrome), **or use a real touch device**

I was not able to reproduce this bug using a desktop browser.

### Expected Behavior

To be able to swipe to change slides.

### Actual Behavior

Swiping seems broken, most of the time the slide doesn't move, and when it does, it does not "follow" the finger position.
I've noticed different behavior on Chrome desktop (emulating a mobile) than my Android phone (both running Chrome)

- On chrome desktop, the slides either don't move at all or change "without following the gesture"
- On the real mobile, the swipe seems to be blocked mid-way and stays blocked until I touch the screen again

### Swiper version

10.3.0

### Platform/Target and Browser Versions

Windows, Chrome 116.0.5845.188. Android, Chrome 117.0.5938.60

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your need to correctly set touch-action css property

**Comment by marcfal** [comment]
Thanks for the reply.

For the record, in case anyone has the same issue, `touch-action: none;` did the trick.
