### ISSUE TITLE
Swiper is not sliding in some situations

### ISSUE THREAD

**Issue by hakanyener** [nolimits4web/swiper#7068]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/

### Bug description

The scrolling operation is successfully from the area I marked in red. But scrolling is not possible outside the red area. I wonder what is the reason? I am using Ionic 7

[Screenshot](https://hizliresim.com/dvglgm0)

When I set the height to 100%, the scroll feature does not work.

[Screenshot 2](https://hizliresim.com/55hjhmb)

`<swiper-container style="height: 100% !important;" #swiper (slidechange)="swiperSlideChanged($event)" (afterinit)="swiperReady()">
    <swiper-slide">
    </swiper-slide>
    <swiper-slide>
    </swiper-slide>
  </swiper-container>

swiper-container {
  --swiper-pagination-bullet-inactive-color: var(--ion-color-step-200, #cccccc);
  --swiper-pagination-color: var(--ion-color-primary, #3880ff);
  --swiper-pagination-progressbar-bg-color: rgba(var(--ion-text-color-rgb, 0, 0, 0), 0.25);
  --swiper-scrollbar-bg-color: rgba(var(--ion-text-color-rgb, 0, 0, 0), 0.1);
  --swiper-scrollbar-drag-bg-color: rgba(var(--ion-text-color-rgb, 0, 0, 0), 0.5);
}

swiper-slide {
  position: relative;
  flex-direction: column;
  flex-shrink: 0;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  font-size: 18px;
  box-sizing: border-box;
}`

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Android Tablet

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Screenshots are not useful, need a codesandbox.io demo with Swiper only and not other libs
