### ISSUE TITLE
Loopedslides only appear after manual slide

### ISSUE THREAD

**Issue by janein** [nolimits4web/swiper#7069]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-forked-5nx488?file=/index.html

### Bug description

The loopedSlides only appear after I swiped. I also can't create a workaround with sliding programmatically.

In the codesandbox I created a swiper width overflow visible (my usecase to fake centering). In versions < 9 this worked just fine with loopAdditionalSlides.
The slides spans over the pink area - everything else is just visible because of the `overflow: visible`.

### Expected Behavior

There should be slides visible on the left hand side initially. The state should be the same as after swiping left and right.

### Actual Behavior

No slides are visible left to the initial slide.

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Chrome / Ubuntu

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
In v9+ loop works in a different way and has extra requirements (check docs)

**Comment by janein** [comment]
I am aware of this and checked the docs. But as I was trying to figure out how to get our components working with the new version I encountered the inconsistend behavior mentioned above.
