### ISSUE TITLE
Provide Typescript definition for Element when using SolidJs

### ISSUE THREAD

**Issue by PaulOst** [nolimits4web/swiper#7073]
### Clear and concise description of the problem

According to https://swiperjs.com/solid, it is recommended to use Swiper Element since Swiper Solid has been removed. However, there are no typescript definitions causing type errors in vscode. e.g., <swiper-container>. What used to be a great DX is not good now.

### Suggested solution

Add typescript definitions for Swiper Elements.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://www.unpkg.com/browse/swiper@10.3.1/swiper-element.d.ts
