### ISSUE TITLE
displaying conditional swipers inside each other bugs

### ISSUE THREAD

**Issue by Yassin-Samir** [nolimits4web/swiper#7077]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://github.com/Yassin-Samir/redux-asyncThunkPractice

### Bug description

phones.js `<Swiper
      loop={true}
      navigation={true}
      pagination={paginationConfig}
      modules={[Pagination, Navigation]}
      observer={true}
      observeParents={true}
      className={`mainPhoneSwiper ${Loading ? "skeleton" : ""}`}
    >
      {Loading ? (
        <SwiperSlide>
          <Phone skeleton={true} />
        </SwiperSlide>
      ) : (
        phones &&
        phones?.products?.map((phoneObj) => (
          <SwiperSlide key={phoneObj.id}>
            <Phone {...phoneObj} />
          </SwiperSlide>
        ))
      )}
    </Swiper>`

phone.js ` <div className={`phone ${skeleton ? "skeleton" : ""}`}>
      <div className={`header ${skeleton ? "skeleton" : ""}`}>
        <strong className={skeleton ? "skeleton" : ""}>{title}</strong>
        <span className={skeleton ? "skeleton" : ""}>{category}</span>
      </div>
      <div className="imgSlider">
        <Swiper
          loop={true}
          navigation={true}
          pagination={paginationConfig}
          modules={[Pagination, Navigation]}
          className="phoneSwiper"
          observer={true}
          observeParents={true}
        >
          <SwiperSlide>
            <img src={thumbnail} loading="lazy" />
          </SwiperSlide>
          {images &&
            images.map((img, ind) => (
              <SwiperSlide key={ind + 1}>
                <img src={img} loading="lazy" />
              </SwiperSlide>
            ))}
        </Swiper>
      </div>
      <div className={`price ${skeleton ? "skeleton-text" : ""}`}>
        <p>{!skeleton ? "$" + price : null}</p>
        <p>{!skeleton ? stock : null}</p>
        <p>{!skeleton ? `rating :${rating}` : null}</p>
      </div>
    </div>` the swiper in phone js doesn't work

### Swiper version

10.3.1

### Platform/Target and Browser Versions

chrome canary windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper v11 comes with reworked and update loop mode. If your issue is replicated with v11, create a new one
