### ISSUE TITLE
getting error on swiper compoent

### ISSUE THREAD

**Issue by Saqib92** [nolimits4web/swiper#7079]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/ionic7-label-test-cxdtvy?file=src%2Fapp%2Fapp.component.css

### Bug description

Getting this error in console when a component with swiper loads

![Screenshot 2023-10-04 at 3 02 13 PM](https://github.com/nolimits4web/swiper/assets/7135885/02b9537c-717d-4ad5-b3df-802d795e24d8)

### Expected Behavior

There should be no error in console. because of this error my other code stops working. 
I am using Element APi for my Angular 16 project. 

### Actual Behavior

There is the Error in console only on first load. but swiper is working.

### Swiper version

10.3.1

### Platform/Target and Browser Versions

chrome, safari, android, ios, firefox, Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
The link you posted doesn't illustrate the issue
