### ISSUE TITLE
[React] Screen shakes on mobile

### ISSUE THREAD

**Issue by vicasas** [nolimits4web/swiper#7081]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/github/vicasas/swiper-issue-screen-shakes/main

### Bug description

The screen starts shaking when you resize the screen to resolutions between 460 to 476 pixels.

   Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2
      swiper: 10.3.1

View Demo, using 480 px: https://hw8xyx-3000.csb.app/
Repository: https://github.com/vicasas/swiper-issue-screen-shakes

Here in the video the problem is shown on a smaller scale, but in person the shaking is stronger.

https://github.com/nolimits4web/swiper/assets/57921784/49fbc0d4-ced9-4ba3-afd1-c29cb9921c6b

### Expected Behavior

I would hope that when resizing the graphics window the screen would not shake

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Window 11 with WSL/Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
That is not related to Swiper

**Comment by vicasas** [comment]
Why is it not related? The problem only occurs when using the Swiper component.
