### ISSUE TITLE
Swiper not initially registering click directly after swipe on mobile view.

### ISSUE THREAD

**Issue by V3JohanM** [nolimits4web/swiper#7082]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/stackblitz-starters-jug7uq

### Bug description

I have encountered a problem with Swiperjs. When using it on mobile or in a mobile browser view, there seems to be an issue when swiping between slides. Specifically, when the next slide becomes visible and I immediately attempt to interact with any input element (e.g., clicking it), the initial click event does not register properly. However, if I wait for a brief moment after the next slide appears before clicking any input element, it allows me to select the input with a single click. It appears as if the animation is causing a delay in registering the initial click when performed immediately.

### Expected Behavior

Single click needed to activate any input after swiping.

### Actual Behavior

Delay needed to activate any input after swiping.

### Swiper version

10.3.1

### Platform/Target and Browser Versions

IOS/Android/Browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by yeoweizheng** [comment]
Hi @V3JohanM I'm facing the same issue on the React version of SwiperJS as well, and have used a workaround for the specific component affected by using `onTouchStart()` and `onTouchEnd()` events, and registering the "click" as long as the change in X, Y position is less than 20px, and duration is less than 500ms. The specific numbers are configurable.

Click-detection code below:
```
const defaultTouchRef = () => {
  return {x: 0, y: 0, timeStamp: 0};
};

const registerTouch = (event, ref) => {
  ref.current = {
      x: event.changedTouches[0].clientX,
      y: event.changedTouches[0].clientY,
      timeStamp: event.timeStamp
  }
}

const handleTouch = (event, ref, callback) => {
  let thresholdPx = 20;
  let thresholdMs = 500;
  if (
    Math.abs(event.changedTouches[0].clientX-ref.current.x) <= thresholdPx 
    && Math.abs(event.changedTouches[0].clientY-ref.current.y) <= thresholdPx 
    && event.timeStamp-ref.current.timeStamp <= thresholdMs {
      callback();
    }
  ref.current = defaultTouchRef();
}
```

In the affected component:
```
const touchRef = React.useRef(defaultTouchRef());

<Button
  onClick={() => handleClick()} 
  onTouchStart={(e) => registerTouch(e, touchRef.current)} 
  onTouchEnd={(e) => handleTouch(e, touchRef.current, () => handleClick()} 
/>
```

Hope this helps.

**Comment by nolimits4web** [comment]
There was a big thread here (use search in issues/discussions)
