### ISSUE TITLE
Negative timeLeft and percentage in autoplayTimeLeft after autoplay stop then start

### ISSUE THREAD

**Issue by DrawThree** [nolimits4web/swiper#7084]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/c2px7m

### Bug description

After stopping autoplay, waiting for a number of seconds longer than the delay time, then starting autoplay, the timeLeft and percentage values in the autoplayTimeLeft event are negative.

### Expected Behavior

The timeLeft and percentage should accurately reflect the time left before transition to the next slide and percentage of that time related to autoplay delay.

### Actual Behavior

Using the reproduction link, run swiper.autoplay.stop(), wait for 5-10 seconds, then run swiper.autoplay.start().

The autoplayTimeLeft event will get negative numbers for timeLeft and percentage, and the progress countdown UI element will reflect this.

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Windows Chrome 117.0.5938.132

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by VijayMeena701** [comment]
there is still issue in this.
rather than negative now it sends progress value very high values like it should range from 0 to 1 but now it gives values above 1 like way higher above 10. it occurs when you stop or pause the autoplay. here is the code for reference.


const CarouselPagination: React.FC<CarouselPaginationProps> = ({ bullets }) => {
	const swiper = useSwiper();

	useLayoutEffect(() => {
		// Cache DOM elements
		const bullets = Array.from(document.querySelectorAll<HTMLElement>(".swiper-pagination-bullet"));

		const handleSlideChange = (s: SwiperType) => {
			bullets.forEach((bullet, index) => {
				if (index < s.activeIndex) {
					bullet.style.opacity = "1";
					bullet.style.background = "rgba(255, 255, 255, 1)";
				} else {
					bullet.style.opacity = "1";
					bullet.style.background = "rgba(255, 255, 255, 0.4)";
				}
			});
		};

		const handleProgress = (s: SwiperType, _: number, progress: number) => {
			bullets.forEach((bullet, index) => {
				if (index === s.activeIndex) {
					bullet.style.opacity = "1";
					bullet.style.background = `linear-gradient(to right, #FFF ${(1 - progress) * 100}%, rgba(255, 255, 255, 0.4) ${(1 - progress) * 100}%)`;
				}
			});
		};

		swiper.on("slideChange", handleSlideChange);
		swiper.on("autoplayTimeLeft", handleProgress);

		return () => {
			swiper.off("slideChange", handleSlideChange);
			swiper.off("autoplayTimeLeft", handleProgress);
		};
	}, [swiper, bullets]);

	return (
		<Box
			sx={{
				position: "absolute",
				bottom: 0,
				left: 0,
				right: 0,
				zIndex: 12000,
				background: "linear-gradient(180deg, rgba(20, 20, 20, 0.01) 0%, rgba(20, 20, 20, 0.8) 100%)",
				height: 36,
				display: "flex",
				justifyContent: "center",
				alignItems: "center",
				gap: 0.5,
				p: 2,
			}}
		>
			{bullets.map((_, index) => (
				<Box
					component="span"
					key={index}
					className={`swiper-pagination-bullet swiper-pagination-bullet-${index}`}
					sx={{
						flex: 1,
						height: 2,
						background: "#FFF",
						borderRadius: 0,
					}}
				/>
			))}
		</Box>
	);
};

**Comment by Sgouws** [comment]
Same issue here. It appears to be directly related to having different delay values set for each slides.

In my instance when I removed the `data-swiper-autoplay` from each slide, and set a single value in the config, the issue appears to be resolved.
