### ISSUE TITLE
Swiper autoplay flicker on breakpoints

### ISSUE THREAD

**Issue by marioatbahasa** [nolimits4web/swiper#7085]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/bug-autoplay-responsive-c7hqly

### Bug description

I have an app that wants to have different autoplay behavior on mobile and in desktop. In desktop, I want it to be disabled, but on mobile, I want it to be autoplay.

But, there is a catch where if I change my (simulated) phone from potrait to landscape, or just swiftly change breakpoints from `autoplay:true` to `autoplay: false`, the autoplay behavior start to break(?)

Here's the demo of how it breaks:

https://github.com/nolimits4web/swiper/assets/144311627/b920cb61-8b9c-4c2a-9527-2cc70765dc1f

### Expected Behavior

The autoplay is not broken when I change from `autoplay: true` to `autoplay: false`

### Actual Behavior

The autoplay is broken when I change from `autoplay: true` to `autoplay: false`

### Swiper version

10.3.1

### Platform/Target and Browser Versions

macOS Chrome 117.0.5938.132

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Autoplay can't be enabled/disabled in breakpoints, use autoplay.start/stop methods instead
