### ISSUE TITLE
Styles import order in head

### ISSUE THREAD

**Issue by nat-davydova** [nolimits4web/swiper#7089]
### Clear and concise description of the problem

When I install swiper as a package and import styles from `js` file like that

```js
import Swiper from "swiper";
import { Navigation, Pagination, Autoplay } from "swiper/modules";
// import Swiper and modules styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

const swiper = new Swiper(".hero-swiper", {
  // configure Swiper to use modules
  modules: [Navigation, Pagination, Autoplay],
});
```

all the `<style>` files of swiper are automatically put to the very end of `head` tag, after custom stylesheets which are already in header.

That's why it's tricky to customize styles from this custom stylesheets: we should either use a higher specifity (like ugly `.classname.classname.classname`) or use `!important`.

It will be much better if swiper style files appear before other css-files in the head.

(on the screenshot #1 is my custom css file import, #2 - automatically added swiper files)
<img width="589" alt="image" src="https://github.com/nolimits4web/swiper/assets/52240221/1588d390-8c02-45f6-81ef-4fb270e33724">

So to over-ride a 2-classes chain in the swiper styles, we shoul produce 3-classes chain or `!important`, and that's not good
<img width="260" alt="image" src="https://github.com/nolimits4web/swiper/assets/52240221/e289c657-a0d0-4200-8b32-40314d0e7474">

### Suggested solution

An alternative - find in the head a topmost `style` tag and insert swiper styles above it

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Closing as not related to Swiper. Do the styles imports in correct place of your app
