### ISSUE TITLE
Failed to execute 'add' on 'DOMTokenList' for Scrollbar dragClass option

### ISSUE THREAD

**Issue by themagickoala** [nolimits4web/swiper#7096]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-dragclass-issue-nhyjzt

### Bug description

When using Tailwind with class fields on e.g. Scrollbar's dragClass option, Swiper is assuming a single classname. This should be split on spaces and passed to classList.add as an array.

### Expected Behavior

We should be able to pass multiple classes to this, as per #6344 and other related issues.

### Actual Behavior

See codesandbox:
```
Failed to execute 'add' on 'DOMTokenList': The token provided ('left-0 top-0 relative w-full h-full rounded-xl bg-font-tertiary') contains HTML space characters, which are not valid in tokens.
```

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Chrome 117.0.5938.149

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by David-Tsui** [comment]
@themagickoala It seems [a line of code](https://github.com/nolimits4web/Swiper/compare/v10.3.1...v11.0.0#diff-c8b54ef9ca51b1789693c3a5a21c51e36fde09c0704161428e711668824b6e8aR266) was missed when `11.0.0` was launched.
