### ISSUE TITLE
parameter "on" not working

### ISSUE THREAD

**Issue by blueooh** [nolimits4web/swiper#7106]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/lucid-robinson-z734gx?file=/App.svelte

### Bug description

- registered event function is not working
- not printed console log in init function and other events too.

### Expected Behavior

- console log printed when swiper component initialized

### Actual Behavior

not printed console log when swiper component initialized

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Chrome 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use events as events, e.g. `on:slidechange={...}`
