### ISSUE TITLE
Swiper completely bugs out when (loop && numberOfSlides > 1 && numberOfSlides > slidesPerView && numberOfSlides < slidesPerView*2)

### ISSUE THREAD

**Issue by dmts17** [nolimits4web/swiper#7110]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/js-2amhdw?file=index.html

### Bug description

If you have loop enabled, and the number of slides is greater than the number of slidesPerView but less than slidesPerView*2, nothing will work properly. You will only be able to slide right until the last slide is visible; Swiping left will always skip 1 slide; After swiping left, you can only swipe right 1 time.

Steps to reproduce:
slidesPerView: 4
slidesPerGroup: 1
loop: true
numberOfSlides: >4 && <8

You can also reproduce the bug using the Swiper Studio

### Expected Behavior

Swiping in any direction should only slide 1 slide at a time and infinitely loop.

### Actual Behavior

- You can only swipe right until the last slide (no looping). 
- Swiping left will skip every other slide, and afterwards you will only be able to swipe right 1 time before it stops.

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Chrome, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> If you have loop enabled, and the number of slides is greater than the number of slidesPerView but less than slidesPerView*2, nothing will work properly

This requirement is stated in docs
