### ISSUE TITLE
Swiper is not defining via cdn install to webflow 

### ISSUE THREAD

**Issue by AtakanBacaksiz** [nolimits4web/swiper#7111]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/atakan-webflow-lds8lv?file=/swiper.js

### Bug description

![Screenshot 2023-10-13 203149](https://github.com/nolimits4web/swiper/assets/32418624/100e12d7-c5f7-403c-bc0d-1f2b40ec1038)
![Screenshot 2023-10-13 163239](https://github.com/nolimits4web/swiper/assets/32418624/8c297986-92d7-4d28-abdc-c11f62085df4)

### Swiper version

 v10.3.1

### Platform/Target and Browser Versions

Windows, Chrome 117

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by AtakanBacaksiz** [comment]
Ah, https://www.atakan.design/project/smartcoach forgot this. This is my website that I've tried swiper.

**Comment by nolimits4web** [comment]
You are asking some super basic stuff, GitHub issues is not for questions. 5 seconds to look at your code to see that you include Swiper from CDN AFTER your custom script
