### ISSUE TITLE
Swiper does not work correctly with a model of three slides

### ISSUE THREAD

**Issue by DigitalExtent** [nolimits4web/swiper#7113]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-vue-autoplay-forked-thcdxp?file=%2Fsrc%2FApp.vue%3A13%2C23

### Bug description

Swiper skips the second slide, with a model of three slides. If you make centerSlides="true", slidesPerView=""auto" and the swiper-slide width to 66.6% it does not show the second slide after the first.

### Swiper version

10.2.0

### Platform/Target and Browser Versions

Chrome 118.0.5993.70, Firefox 118.0.2 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check loop requirements in docs
