### ISSUE TITLE
Swiper not swiping properly on mobile touch when an element has an inner div with overflow-y:auto|scroll 

### ISSUE THREAD

**Issue by abdurrahmanseyidoglu** [nolimits4web/swiper#7115]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-forked-qdcz62

### Bug description

Swiper works fine on Mouse dragging but behaves weirdly when switching to a mobile touch screen when there is a div that has an overflow-y : auto | scroll inside it  
here is a video for further demonstration : https://imgur.com/a/9xlAcCM

### Expected Behavior

The slider should slide properly when dragging to the left or right inside the element that has an overflow-y scroll | auto on-screen touch just like on mouse drag

### Actual Behavior

it's flickering when dragging it right or left 

### Swiper version

10.3.1

### Platform/Target and Browser Versions

windows10 Chrome Version 118.0.5993.71 (Official Build) (64-bit) 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
please use issues search
