### ISSUE TITLE
Added event listeners no longer work (v. 11)

### ISSUE THREAD

**Issue by zarko-tg** [nolimits4web/swiper#7131]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-default-forked-z448qz?file=/index.html

### Bug description

One can add event listeners such as shown here: https://swiperjs.com/element#events

This no longer works with v. 11.

### Swiper version

11.0.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I think it worths reading what is new in v11 first
