### ISSUE TITLE
Error when using "rtl" attribute with "loop"

### ISSUE THREAD

**Issue by arb195** [nolimits4web/swiper#7133]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-infinite-loop-forked-fsw669?welcome=true

### Bug description

When I use the rtl attribute along with loop in Swiper, I encounter an error. When Swiper attempts to render loop elements, it throws an error.

### Expected Behavior

I should be able to run Swiper with rtl and loop without any errors, and loop elements should render correctly.

### Swiper version

10.2.0

### Platform/Target and Browser Versions

macOS mozilla firefox 118.0.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Link you provided doesn't illustrate the issue, can't see any errors there

**Comment by arb195** [comment]
My intention was not to refer to an error within the swiper, but rather to indicate that there is a disruption in this situation, which I have displayed in the video below


https://github.com/nolimits4web/swiper/assets/73616022/48dfff32-e12f-42c9-9875-7ebdae96f8d9

**Comment by INOCcent-afk** [comment]
+1, same problem
