### ISSUE TITLE
Navigation with `slideToLoop` produces the flip through effect between neighbouring slides after at least one loop is finished

### ISSUE THREAD

**Issue by aa-ndrej** [nolimits4web/swiper#7134]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/electrodrel/pen/MWPeQdQ

### Bug description

Original issue by @electrodrel: #6592
This issue is still happininng in `v11.0.2`. You need to adjust the swiper version in the CodePen since it is the one from the original issue.

When switching to a slide using `slideToLoop` method, there is this 'flipping through all the slides in the slider' effect. it is intended to show up only between the last and the first slide to indicate the end of the loop. However it happens between two neighbouring slides if they have been rearranged in loop navigation.

### Expected Behavior

No matter how many times a user swipes through the slides in the infinite loop, there should not be any flipping slide effect between two neighbouring slides, unless they are the last and the first slides in the slider.

### Actual Behavior

After at least one loop is over, there is the flipping effect between two neighbouring slides (not the last and the first ones).

### Swiper version

11.0.2

### Platform/Target and Browser Versions

macOS: Chrome, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is expected so far, as loop rearrange the slides (check the DOM)

**Comment by aa-ndrej** [comment]
Yes, but the slides could be rearranged in a different way after the first loop iteration. The current slide could always be positioned somewhere in the middle of the other slides (in the DOM). That way the slides would always take the shortest path while navigating with `scrollToSlide`.
This would be my expected behavior.

**Comment by zhaivoronok** [comment]
This is huge problem that remains for years. Always hope for fix but it's like 5 new versions since I face the problem and no solutions.
