### ISSUE TITLE
Swiper Direction vertical is not working in React

### ISSUE THREAD

**Issue by rizvithedeveloper** [nolimits4web/swiper#7146]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/silent-star-xzkpdl?file=/src/Test.js

### Bug description

Swiper is not functioning correctly in the vertical direction; all slides are being displayed simultaneously. It appears that CSS and JavaScript components necessary for Swiper's vertical functionality may be missing. I've attempted to use an older version, like Swiper 10, but the issue persists. Unfortunately, I am uncertain about the root cause of this problem.

### Swiper version

11.0.3

### Platform/Target and Browser Versions

macOS 11.7.10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://codesandbox.io/s/hg3fpj
