### ISSUE TITLE
Navigation config is impossible due to lowercase attribute restriction

### ISSUE THREAD

**Issue by Paul-MEGAVERSAL** [nolimits4web/swiper#7147]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-navigation-forked-3gfqrz?file=/index.html

### Bug description

Using element attributes:
e.g.
      navigation-prevEl="prevBtn"
      navigation-nextEl="nextBtn"

is impossible. The property require an upper-case letter. HTML only supports lower-case letters.

<img width="488" alt="image" src="https://github.com/nolimits4web/swiper/assets/149427688/1028c047-5397-47d6-831f-7de03687202a">

Properties cannot be merged this way.

Here is the spec https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute

### Expected Behavior

Property case is ignored when using swiper element configuration.

### Actual Behavior

Property is ignored.

### Swiper version

10.3.1

### Platform/Target and Browser Versions

Windows, Chome, Firefox, Opera

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
navigation-next-el
