### ISSUE TITLE
Make 'virtual' compatible with 'Cards Effect'

### ISSUE THREAD

**Issue by MagnusBrzenk** [nolimits4web/swiper#7159]
### Clear and concise description of the problem

At the moment, if you apply the [cards effect](https://swiperjs.com/demos#effect-cards) AND the [virtual property](https://swiperjs.com/demos#virtual-slides), then the cards-effect CSS gets messed up. Would be nice to have a very large/dynamic pack of cards. Thanks.

### Suggested solution

Might be an easy CSS clash/fix. Dunno.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
World be good to see how it doesn't work with the example

**Comment by MagnusBrzenk** [comment]
Here's an [example](https://codesandbox.io/p/sandbox/swiper-react-effect-cards-forked-46mszq?welcome=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clohl91e700073b6inp2kk3dc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clohl91e600033b6i80yc4g9x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clohl91e700053b6inrnk29ms%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clohl91e700063b6i2axdcvpw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clohl91e600033b6i80yc4g9x%2522%253A%257B%2522id%2522%253A%2522clohl91e600033b6i80yc4g9x%2522%252C%2522activeTabId%2522%253A%2522clohl9zq100f53b6iag2xi07b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clohl91e600023b6ici4xizda%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522id%2522%253A%2522clohl9zq100f53b6iag2xi07b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clohl91e700063b6i2axdcvpw%2522%253A%257B%2522id%2522%253A%2522clohl91e700063b6i2axdcvpw%2522%252C%2522activeTabId%2522%253A%2522clohl9az500by3b6imo541fj2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clohl9az500by3b6imo541fj2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clohl91e700053b6inrnk29ms%2522%253A%257B%2522id%2522%253A%2522clohl91e700053b6inrnk29ms%2522%252C%2522activeTabId%2522%253A%2522clohl98xo00ac3b6izr1nlldy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clohl91e700043b6ipptpeatv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clohl91nz000aedgvfto0ahem%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clohl98xo00ac3b6izr1nlldy%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

If you comment-out "virtual" and "Virtual", and keep the number of cards small (<100), then it works great. If you increase the cards to e.g. 1000, then animation slows down. If you add in "virtual" and "Virtual", then performance returns, but there is a CSS flicker as you drag and let go. (Also, you get an occasional glitch whereby the whole pack shifts, but that is rare, and I dont know what triggers that.

**Comment by leeeisok** [comment]
@MagnusBrzenk 
hi, magnusbrzenk
I have also encountered this problem. Have you currently resolved it? Or are there any other solutions?
