### ISSUE TITLE
Can't swipe on slides containing HTML5 video with controls

### ISSUE THREAD

**Issue by dliebner** [nolimits4web/swiper#7162]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-pagination-progress-forked-4py7r2?file=/index.html

### Bug description

On slides containing HTML5 video, attempting to swipe over the `<video>` element fails to move the carousel.

### Expected Behavior

Ideally, you should be able to swipe over the `<video>` element to move the carousel, unless you're dragging the video timeline slider. All video controls should work, and dragging while over a video control (such as play/pause) should not trigger the control.

### Actual Behavior

Video controls all work, but you can't swipe over the `<video>` to move the carousel.

### Swiper version

11.0.3

### Platform/Target and Browser Versions

FireFox, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by dliebner** [comment]
The only workaround I've found for this so far is to completely cover the video in your own layer of controls combined with `noSwipingSelector` to prevent swiping on specific controls (i.e. the bottom control bar).

**Comment by nolimits4web** [comment]
We can not do this, as Video controls are not really elements. Use custom Video player, or combination of `noSwipingSelector` and `swipeHandler` options
