### ISSUE TITLE
slidechange event does not fire when using the events-prefix attribute

### ISSUE THREAD

**Issue by pjc2007** [nolimits4web/swiper#7163]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/pjc2007/swiper-touchevent-issue

### Bug description

In the above application I have a `(slidechange)="slideChanged($event)`, and as it is, this does not fire.

Now if we remove the `events-prefix="swiper-"` it then works.

So appear the `events-prefix` attribute interferes with the `slideChanged` event

### Expected Behavior

For `slidechange` to fire when we use the `events-prefix` attribute

### Actual Behavior

 `slidechange` does not fire when we use the `events-prefix` attribute

### Swiper version

10.0.1

### Platform/Target and Browser Versions

Chrome 118.0.5993.120, Windows 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Apparently the event name becomes `swiper-slidechange` with even prefix
