### ISSUE TITLE
Control transition duration of autoplay

### ISSUE THREAD

**Issue by LucasWongC** [nolimits4web/swiper#7168]
### Clear and concise description of the problem

I want to control the transition duration when swiper autoplays.

### Suggested solution

I think it would be good to add a new pair in autoplay interface options so that users can set transition duration

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can use `speed` parameter for transition duration, or you can set its custom value within `autoplay` event
