### ISSUE TITLE
Coverflow-Effect not working with Swiper-Element and Safari

### ISSUE THREAD

**Issue by ttober** [nolimits4web/swiper#7169]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/49s6c3

### Bug description

The Example of the Coverflow-Effect is not working in Safari on both mobile and desktop.

https://swiperjs.com/demos#effect-coverflow

### Expected Behavior

I expected it to work like the Core-Version of swiper:

https://codesandbox.io/s/p3f7rh

### Actual Behavior

The Slides don't get tilted and the images are flat and stretched.

### Swiper version

11.0.2

### Platform/Target and Browser Versions

Safari 16.4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/blog/slide-slots-in-v10-1-0
