### ISSUE TITLE
slideTo doesn't work after a full loop

### ISSUE THREAD

**Issue by mlaigre** [nolimits4web/swiper#7171]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-default-forked-shzysd

### Bug description

Hello,

I just found that after doing a full loop the slideTo function doesn't work anymore: it's slide to a wrong slide

Reproduction pretty simple :
- at start all "Slide to" buttons work normally
- then slide enough to do a loop
- now all "Slide to" buttons slide to a wrong slide

I hope the description and CodeSandbox are explicit enough

### Swiper version

11.0.3

### Platform/Target and Browser Versions

Chrome 118 / macOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You need to use slideToLoop

**Comment by mlaigre** [comment]
Hi @nolimits4web,

Many thanks! It works indeed. It also allowed me to discover realIndex vs activeIndex.

Sorry I shouldn't have bothered you with this, but I couldn't find this solution despite a few hours of searching in the documentation and issues.

Have a good day
