### ISSUE TITLE
Coverflow-Effect：The number of slides on both sides of the activated slide is inconsistent

### ISSUE THREAD

**Issue by MrMJY** [nolimits4web/swiper#7172]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/zai-xian-dai-ma-bian-ji-qi-forked-xvqcvx?file=/src/index.js

### Bug description

The number of slides on both sides of the activated slide is inconsistent.
After sliding a little distance, the sildes on the left will move to the right,

![image](https://github.com/nolimits4web/swiper/assets/49824922/78825e03-53d5-4f85-9c11-6b1080e1a1d8)

### Expected Behavior

![image](https://github.com/nolimits4web/swiper/assets/49824922/c87bae7c-d6f0-4b4a-b614-6959e7149ba1)

### Swiper version

11.0.3

### Platform/Target and Browser Versions

Windows Chrome  

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how loop works, increase loopAdditionalSlides/slidesPerView

**Comment by MrMJY** [comment]
> This is how loop works, increase loopAdditionalSlides/slidesPerView

I want both sides to be the same amount after dragging, but now it's not

**Comment by MatthewTt** [comment]
Have you solved the problem?

**Comment by dingkai031** [comment]
Hello i"m encounter this problem too. I already increase the number of slide, its still showing different amount I'm using version 11.

**Comment by loueradun** [comment]
Fork of coverflow demo with loop enabled:
https://codesandbox.io/p/sandbox/swiper-effect-coverflow-forked-pgmlfv

**Comment by smfFabu** [comment]
Hello, Has anyone found a solution/workaround to this?

**Comment by asaadmahmood** [comment]
Please fix this! @nolimits4web

**Comment by smfFabu** [comment]
> Hello, Has anyone found a solution/workaround to this?
> 
> @nolimits4web The issue is that the loop function sometimes does not get triggered if the user only drags a drop, for some reason, it's enough to move next or prev into now being active(for the Coverflow-Effect ) however, it does not trigger loop to remove and add a component in some cases,
> 
> From what it sounds to me, the Coverflow-Effect is transitioning before the loop, and the loop, for some reason, does not execute; the expected behavior would be to first trigger the loop, then transition to the Coverflow-Effect.

after debugging this further, there are clearly some events that are not being fired,  see https://codesandbox.io/p/devbox/szqj2p you could clearly see on a normal event, there are at least 2 loop calls, on these short drag that are causing issues there is only 1 
![2024-09-23_11h14_22](https://github.com/user-attachments/assets/46e6a76c-bed5-4bc1-af0d-78d71da5f67f)

**Comment by smfFabu** [comment]
I think I found the problem. It has to do with the active index not updating properly, and I think I have a temporary workaround; see https://codesandbox.io/p/devbox/szqj2p for more details.

But there is clearly a bug here.

**Comment by shanyi-front** [comment]
I have same problem。

**Comment by robson-rp** [comment]
I encountered the same issue where the number of slides on both sides of the activated slide was inconsistent. I resolved it by increasing the value of the `loopAdditionalSlides` parameter. This ensures that there are enough slides preloaded on both sides to maintain consistency in the Coverflow effect.
