### ISSUE TITLE
Create gallery for zoom function with slides

### ISSUE THREAD

**Issue by asimongm** [nolimits4web/swiper#7189]
### Clear and concise description of the problem

Hello,
I discover the zoom function of Swiper that is really good, like a lightbox, but It would be even more nice if you could add the feature "gallery" to this function. So we could navigate between slides images in the lightbox.

Thank you ! 

### Suggested solution

Like Fancybox, for exemple, by adding a specific data (like data-gallery="myslidergallery") on slides div, it will create a gallery in the zoom box, with next and previous arrows to see all our slides in the zoom space. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by eduardoperez2151** [comment]
could you add Zoom in mouseover ?
