### ISSUE TITLE
swiper loop not repeating slides to fill in black space when reaching the end

### ISSUE THREAD

**Issue by houtaro** [nolimits4web/swiper#7191]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://drive.google.com/file/d/1CfZ1Zg4HZMz31ctKcS7tkGUPbCB2Hw3a/view

### Bug description

Swiper does not repeat the first slides to "fill in" the remaining blank slides/space in a group.

I have a total of 9 slides. This is my Swiper configuration:

slidesPerView: auto
slidesPerGroup: 4
loop: true
spaceBetween: 30

I don't have `loopAddBlankSlides` set in my config, which should default to `false`. I've also tried to to explicitly set
`loopAddBlankSlides: false` in my config but to no avail.

I've read the docs to check for a property/parameter that could potentially achieve this behavior but I can't find it.

### Expected Behavior

I was expecting for the first 3 slides (Slide 1, Slide 2, Slide 3) to appear after the 9th Slide, in a single group.

### Actual Behavior

Only the 9th slide was shown in the last group.

### Swiper version

11.0.3

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by jankohlbach** [comment]
@houtaro how did you solve this?

**Comment by houtaro** [comment]
@jankohlbach Explicitly setting `loopAddBlankSlides` to `false` did the trick for me. 

I didn't put it in my config at first since it already defaults to `false`, but after I put it, it solved my problem.
