### ISSUE TITLE
Swiper Set up error in angular

### ISSUE THREAD

**Issue by rakeshbaral92** [nolimits4web/swiper#7195]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/rldv3x?file=/index.html

### Bug description

Error: node_modules/swiper/types/modules/index.d.ts:1:35 - error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing '../shared.js' instead.

### Swiper version

11.0.4

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
update TS to latest
