### ISSUE TITLE
Can't change --swiper-navigation-size variable

### ISSUE THREAD

**Issue by fandresh7** [nolimits4web/swiper#7196]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-navigation-forked-9dszfd?file=%2Findex.html%3A1%2C1-76%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp5sju2000083b6abj0rkxw3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp5sju2000043b6aevogt5ky%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp5sju2000053b6ati5wyb89%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp5sju2000073b6ajq5cjzoo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp5sju2000043b6aevogt5ky%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp5sju2000033b6axry93wdn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clp5sju2000043b6aevogt5ky%2522%252C%2522activeTabId%2522%253A%2522clp5sju2000033b6axry93wdn%2522%257D%252C%2522clp5sju2000073b6ajq5cjzoo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp5sju2000063b6afo6z40j8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clp5sju2000073b6ajq5cjzoo%2522%252C%2522activeTabId%2522%253A%2522clp5sju2000063b6afo6z40j8%2522%257D%252C%2522clp5sju2000053b6ati5wyb89%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clp5sju2000053b6ati5wyb89%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Bug description

The attempt to modify the --swiper-navigation-size variable within the CSS cascade is unsuccessful. Despite setting the variable within the :root selector, inspection reveals that the --swiper-navigation-size property is struck through, indicating an inability to apply the intended changes.

### Expected Behavior

The size of navigation buttons should change

### Actual Behavior

the size of navigation buttons don't change

### Swiper version

11.0.4

### Platform/Target and Browser Versions

MacOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
In Swiper Element, props must be specified on Swiper Element not on the `:root`

**Comment by tuananhzippy** [comment]
I also had a similar problem when changing the size of the navigation button. Demo: [https://stackblitz.com/edit/stackblitz-starters-nvsj9j?file=src%2Fstyles.scss](url)

Please help me!

**Comment by fandresh7** [comment]
Hi, the only thing that worked for me was injecting the css in swiper
options. Hope this helps :)

{
slidesPerView: 1,
centeredSlides: false,
spaceBetween: 20,
navigation: true,
injectStyles: [
`.swiper-button-next, .swiper-button-prev {
width: 20px !important;
height: 20px !important;
color: #000000 !important;
top: 0;
bottom: 0;
margin: auto;
}
.swiper-button-next {
right: 0 !important;
}
.swiper-button-prev {
left: 0 !important;
}`
]
}
