### ISSUE TITLE
Vue 3 swiper creative effect doesn't apply to swiper.

### ISSUE THREAD

**Issue by cpreston321** [nolimits4web/swiper#7208]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-ibufkx?file=app.vue

### Bug description

When applying the creative effect to swiper element using vue 3 binding it doesn't apply correct 

### Expected Behavior

It applies the creative effect to the swiper instance

### Actual Behavior

Doesn't apply it at all

### Swiper version

11.0.5

### Platform/Target and Browser Versions

Mac OS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is a question to Nuxt i think on why it doesn't pass properties to Swiper, otherwise use manual init as in examples
