### ISSUE TITLE
Slides in infinite loop with smaller width than the swiper slide

### ISSUE THREAD

**Issue by XhaniManolisTrungu** [nolimits4web/swiper#7210]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/stackblitz-starters-stnvid?file=src%2Fmain.ts

### Bug description

Use Case: 

I want to have a carousel with two slides. 
Each slide should have a width of total : width = calc(100% - 4rem); and a margin-right: 5px; 

Configuration: 
loop="true" 
navigation="true" 
slidesPerView="auto"

On the initial load the slides are correctly shown on the carousel. 

The first slide, and right before the end I can see the next slide (due to the smaller width of the slide) .
When I try to go to next slide then only one is shown. 

It seems to work properly when going back though, clicking the previous button. 

![swiper-demo-next-button-clicked](https://github.com/nolimits4web/swiper/assets/128612451/24947d04-8373-4ac9-95e9-8d52733227ff)
![swiper-demo-initial-load](https://github.com/nolimits4web/swiper/assets/128612451/96a5bdd9-adb6-4ade-8d85-180cdc4b8b9c)

### Expected Behavior

The expected behaviour should be the same as when clicking previous button on navigation. Meaning, the slide 1 should be shown in complete and a portion of the next slide too in the viewport.

### Actual Behavior

The actual behavior is when clicking next on navigation after first load, we can see only one slide, and not both and the latter only a portion of it in the viewport.

### Swiper version

11.0.3

### Platform/Target and Browser Versions

Windows 11 Version 119.0.6045.160

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
See the loop requirements in docs

**Comment by XhaniManolisTrungu** [comment]
So if I understand correctly it won't work as expected with 2 slides on the case I mentioned.

**Comment by nolimits4web** [comment]
slidesPerGroup can't be less than 1 and more than slidesPerView
