### ISSUE TITLE
Slide disappears when clicking on pagination in a certain order

### ISSUE THREAD

**Issue by adgdadgd** [nolimits4web/swiper#7212]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://djw.jp/test/swiper/

### Bug description

Slide disappears when clicking on pagination in a certain order.
( loop: true, slidesPerView: 7, centeredSlides: true )
In Reproduction link, click #6 then #1, slidename[4] disappears.
Below is the code (only essential part) .
```
<div class="swiper">
	<div class="swiper-wrapper">
		<div class="swiper-slide">[1]</div>
		<div class="swiper-slide">[2]</div>
		<div class="swiper-slide">[3]</div>
		<div class="swiper-slide">[4]</div>
		<div class="swiper-slide">[5]</div>
		<div class="swiper-slide">[6]</div>
		<div class="swiper-slide">[7]</div>
		<div class="swiper-slide">[8]</div>
	</div>
	<div class="swiper-pagination"></div>
</div>
```
```
const swiper = new Swiper('.swiper', {
	loop: true,
	pagination: {
		el: '.swiper-pagination',
		clickable: true,
	},
	slidesPerView: 7,
	centeredSlides: true,
});
```

### Expected Behavior

Slide to not disappear.

### Actual Behavior

Slide disappears.

### Swiper version

11.0.5

### Platform/Target and Browser Versions

macOS 13.5.2, Chrome 119.0.6045.159

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Beauseph** [comment]
I think this is the same problem as this: https://github.com/nolimits4web/Swiper/issues/7167
