### ISSUE TITLE
Horizontal swiping is still causing a vertical page moving

### ISSUE THREAD

**Issue by pedroshift** [nolimits4web/swiper#7231]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos

### Bug description

A few months ago this error was reported, but considered resolved after the release of iOS 16!

I am afraid that iOS 16.x was not 100% of the problem here!
Indeed it got a bit less sensitive on iOS 16, but it still happening and affecting negatively the UX. 
The bug is still reproducible even in the demos on oficial website.

I have SwiperJS running on my website + framework7 on my app, and testing on iOS 16.x and 17.x (on different iPhones versions) the swiper horizontal still scrolling page up and down depending on the diagonal direction in which the finger swipe is made!

In most swipers or even in the browsers' native scrollbar, vertical movement is completely prevented, but using swiperJS any inclination above 20 degrees in lateral swiping causes vertical movement... which is very little tilt.
In my app the situation is even worse... it is impossible to use the scroll without having the screen jumping up and down all the time :(

Can someone help me please?

### Expected Behavior

Page should not scroll up and down when the horizontal swipe is running!

### Actual Behavior

It is impossible to have a natural swipe effect without having the page jumping up and down :(

### Swiper version

10+

### Platform/Target and Browser Versions

iOS browsers and applications (mac and iphone)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Update to Swiper 11

**Comment by pedroshift** [comment]
@nolimits4web thanks for your answer!
On web, it works perfectly !!! 
But on my Framework7 App it still buggy due to the dependency version loaded: "^10.2.0"

How can it be fixed? Or do you expect release an update to framework7 soon?
