### ISSUE TITLE
Swipper is breaking after 65th slide

### ISSUE THREAD

**Issue by manojcloudodyssey** [nolimits4web/swiper#7234]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-vertical-forked-64kjc3?file=%2Findex.html

### Bug description

I added image inside swiper. I have 100 slider. Swiper is breaking after 65th slide.
Tested device: Chrome responsive Iphone SE.

### Expected Behavior

Swiper should support unlimited number of slider.

### Actual Behavior

Swiper is breaking at 65th slide

### Swiper version

11

### Platform/Target and Browser Versions

chrome 119.0.6045.200 Responsive Iphone SE

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use virtual slides
