### ISSUE TITLE
progress or sliderMove events are not fully triggered

### ISSUE THREAD

**Issue by interk0t** [nolimits4web/swiper#7238]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/mg9ssk?file=%2Findex.html

### Bug description

Since I need to know the progress of the slide, I first tried to use events such as progress and sliderMove. But I noticed that events only fire at the moment while the user’s mouse button is pressed on the slide, when the button is released and the slide is still in motion, the event no longer fires and the progress value, for example 0.8, suddenly changes to 1, making it impossible to use the value for smooth rendering of the style. For example. I also tried other Events but no results. If this is not a bug or flaw, then tell me , please, how to solve this problem.
![image](https://github.com/nolimits4web/swiper/assets/110355982/e6a9d3d9-1d7e-40ff-ab1d-cac0d554483f)

### Expected Behavior

changing value throughout the slide animation

### Actual Behavior

the value change stops after the user releases the button, but the slide animation continues

### Swiper version

11.0.5

### Platform/Target and Browser Versions

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how css transitions work. Try using cssMode
