### ISSUE TITLE
Memory leak when changing browser tabs

### ISSUE THREAD

**Issue by cwe-spb** [nolimits4web/swiper#7246]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/110-slides-per-view/core

### Bug description

On any version of the package, if you open it in any browser (checked on ios + safari \ chrome), let's say https://swiperjs.com/demos/110-slides-per-view/core it will work perfectly. The swipes will be smooth. If you try to switch to another tab and go back to the swiper demo, you will see that there is a noticeable degradation of the scroll animation. There is a direct dependence on the complexity of the site where you switch to and the strength of the scroll swipe degradation

### Expected Behavior

I have seen that tickets are being closed with information that there is a leak inside swiper, but the expected behavior is the absence of degradation

### Actual Behavior

obvious, visible problems with the smoothness of animation

### Swiper version

8-9-10-11

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cwe-spb** [comment]
i founded just 1 slider without this bug. 
https://naver.github.io/egjs-flicking

i think trouble into swiper core

**Comment by cwe-spb** [comment]
I found the differences between the sliders. [flicking ](https://naver.github.io/egjs-flicking/Demos)followed the path of smoothly changing the transform parameter to js. Sniper's animation is implemented via translate3D with instant value change and translate-duration

**Comment by nolimits4web** [comment]
Can not replicate it whatever i try
