### ISSUE TITLE
V8: Website scrolls when swiping diagonally

### ISSUE THREAD

**Issue by lschirl** [nolimits4web/swiper#7251]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-slides-per-view-forked-fqm9yx

### Bug description

It is a quite similiar bug as in https://github.com/nolimits4web/Swiper/issues/6382. When swiping with my right-hand thumb on a android phone in a firefox browser the whole website slides a litte bit up or down. It seems as the browser gets a horizontal und vertical user input and tries to do both at the same time. So if you use the slider on an android device in Firefox and swipe - the whole website scrolls a litte bit up or down. I do not have this issue in Chrome.

I tested this issue for example on Samsung S23+, Samsung S20+ and a Windows Phone. On iPhone SE in Firefox I could not reproduce this issue. 

URL to view sandbox directly on mobile phone: https://fqm9yx.csb.app/

### Expected Behavior

If I use the slider with my thumb on an android device and in firefox I want only the slider to slide and not the whole website.

### Actual Behavior

If I swipe with my thumb and have a diagonal user input, then the slider slides and the whole website toggles up or down.

### Swiper version

8.4.4

### Platform/Target and Browser Versions

Samsung S20+ Safari, Samsung S23+ Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use latest version of Swiper
