### ISSUE TITLE
swiper-container miscalculates width when placed in flex or grid container

### ISSUE THREAD

**Issue by zerbusdetroy** [nolimits4web/swiper#7256]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-default-forked-yrjzkg?file=%2Findex.html%3A67%2C8

### Bug description

When the swiper-container is placed within a flex or grid container, it appears to incorrectly calculate its width, resulting in an excessively large container (e.g., 3.35544e+07px in my case). This issue does not occur with the core component.

I managed to work around the issue by setting `display: grid` on the swiper-container.

### Expected Behavior

The Swiper slider should take the full remaining width of its parent flex container.

### Actual Behavior

The swiper-container takes an excessively large size.

### Swiper version

11

### Platform/Target and Browser Versions

macOS Chrome / Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how cas grid/flex works. Use issues search first
