### ISSUE TITLE
Uncaught error when unmounting Swiper with loop on window resize

### ISSUE THREAD

**Issue by LeoDanielsson** [nolimits4web/swiper#7265]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/error-when-unmount-swiper-on-resize-693vwm

### Bug description

When unmounting a Swiper with `loop={true}` on a window resize event the following error is thrown by Swiper: 

` Uncaught TypeError: Cannot read properties of undefined (reading 'slidesPerGroupSkip')
    at _Swiper.slideTo`

### Expected Behavior

No uncaught errors should be thrown when unmounting Swiper.

### Actual Behavior

An uncaught error is thrown when unmounting Swiper.

### Swiper version

11.0.5

### Platform/Target and Browser Versions

macOS, Windows, iOS, Android, Safari, Chrome, Edge, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by joebentaylor1995** [comment]
I have this issue too, causing my swiper to not work on mobile

**Comment by husanGuru** [comment]
still have this issue with swiper element on window resize
