### ISSUE TITLE
touchReleaseOnEdges not working on Mobile

### ISSUE THREAD

**Issue by chromaticstudio** [nolimits4web/swiper#7267]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://metaleapcreative.webflow.io/case-study/byfaith

### Bug description

Once the swiper reached the last slide on the page, the swiper should release and allow normal scroll behavior. It works as expected on desktop with `this.params.mousewheel.releaseOnEdges = true;` However, on mobile `params.touchReleaseOnEdges = true;` does not allow normal scroll behavior

### Expected Behavior

on mobile, when the last slide is reached, I should be able to scroll to the bottom of the page with normal scroll behavior

### Actual Behavior

I am frozen on the last slide and cannot scroll down.

### Swiper version

10

### Platform/Target and Browser Versions

Chrome iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Update to Swiper 11
