### ISSUE TITLE
Problem displaying swiper in the details block.

### ISSUE THREAD

**Issue by Bital2509** [nolimits4web/swiper#7275]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-in-the-details-block-s7w98w?file=%2Fsrc%2Findex.html%3A21%2C44&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqkuea710007356buzltk8n8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqkuea710002356bov5xvyii%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqkuea710004356bn47fdq8u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqkuea710006356bah1cmy3v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.5224821349886%252C35.47751786501139%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqkuea710002356bov5xvyii%2522%253A%257B%2522id%2522%253A%2522clqkuea710002356bov5xvyii%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqkuea710006356bah1cmy3v%2522%253A%257B%2522id%2522%253A%2522clqkuea710006356bah1cmy3v%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqkuea710005356b6d866o3l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A1234%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqkuea710005356b6d866o3l%2522%257D%252C%2522clqkuea710004356bn47fdq8u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqkuea710003356b3grvfkjf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clqkuea710004356bn47fdq8u%2522%252C%2522activeTabId%2522%253A%2522clqkuea710003356b3grvfkjf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Bug description

There are two examples of swiper in the codesandbox editor.
The first one is in the details block, where the swiper display is incorrect (If you click on swiper-button-next or swiper-button-prev, swiper does not work correctly).
The second one is just swiper, it works as it should.

### Swiper version

11.0.5 and 7.4.1

### Platform/Target and Browser Versions

Chrome 120.0.6099.179

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your `.details div {` CSS rule breaks it
