### ISSUE TITLE
Images are not loaded correctly

### ISSUE THREAD

**Issue by Domtaholic** [nolimits4web/swiper#7282]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://sorry_no_link_avail.able

### Bug description

Images are not loaded correctly after the first full cycle of the swiper.

https://github.com/nolimits4web/swiper/assets/3584433/bb7fda47-45cd-4dd9-b881-512cea8c5008

My Setup:

 initReferencesSwiper: function(){
        const swiper = new Swiper('.swiperReferences', {
            direction: 'horizontal',
            loop: true,
            spaceBetween: 35,
            slidesPerView: "auto",
            freeMode: false,
            autoplay: {
                delay: 2500,
            },
            centeredSlides: true,
            breakpoints: {
                320: {
                    slidesPerView: 2,
                },
                768: {
                    slidesPerView: 3,
                },
                992: {
                    slidesPerView: 'auto',
                }
            }
        });
    },

### Swiper version

11.0.5

### Platform/Target and Browser Versions

Chrome - latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check `loop` requirements in the docs, or at least live link with the issue is required!
