### ISSUE TITLE
In Creative Effect autoplay does not work after second slide

### ISSUE THREAD

**Issue by uditvishnoi2** [nolimits4web/swiper#7285]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/live/d4f2a4c6-dc05-44ed-9f57-05d16e2d2ba3

### Bug description

It appears that there is a concern with the autoplay functionality in the Swiper.js library when used with React, specifically within the context of a Creative Effect. The problem manifests itself as the autoplay feature ceasing to function properly after the transition to the second slide. 

### Swiper version

11.0.5

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Can't replicate the issue, and the link you have provided leads to the "404 not found" page

**Comment by uditvishnoi2** [comment]
Sorry @nolimits4web  , can you try this link 

https://codesandbox.io/p/devbox/bold-varahamihira-hsjx8v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrrppqqs0007356gtd7z65lc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrrppqqs0003356g4hjfee91%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrrppqqs0004356gd5zgzeoc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrrppqqs0006356gp1anhxy5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrrppqqs0003356g4hjfee91%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrrppqqs0002356g9p51hufb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A1%257D%255D%257D%252C%257B%2522id%2522%253A%2522clrrr09mn0002356fwkhnx2eu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrrppqqs0003356g4hjfee91%2522%252C%2522activeTabId%2522%253A%2522clrrr09mn0002356fwkhnx2eu%2522%257D%252C%2522clrrppqqs0006356gp1anhxy5%2522%253A%257B%2522id%2522%253A%2522clrrppqqs0006356gp1anhxy5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clrrpw9560051356flxv79cbv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrrpw9560051356flxv79cbv%2522%257D%252C%2522clrrppqqs0004356gd5zgzeoc%2522%253A%257B%2522id%2522%253A%2522clrrppqqs0004356gd5zgzeoc%2522%252C%2522activeTabId%2522%253A%2522clrrpw5lc003f356fd88i2hy7%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clrrpw5lc003f356fd88i2hy7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A14.947916666666671%257D

**Comment by uditvishnoi2** [comment]
@nolimits4web  do you mean this 

 autoplay={{
          delay: 2500,
          disableOnInteraction: false,
          waitForTransition: true,
        }}

**Comment by nolimits4web** [comment]
it needs to be `false` as you don't use transitions

**Comment by uditvishnoi2** [comment]
ok @nolimits4web , it is till stuck on second slide 
 
```
  grabCursor={true}
        effect={"creative"}
        loop={true}
        autoplay={{
          delay: 2500,
          disableOnInteraction: false,
          waitForTransition: false,
        }}
```
 
![image](https://github.com/nolimits4web/swiper/assets/19321734/97ca5186-ad09-4557-aea3-332701c3cc7f)
