### ISSUE TITLE
swipper carousel CoverFlow Effect 

### ISSUE THREAD

**Issue by TayyabAli204** [nolimits4web/swiper#7286]
https://github.com/nolimits4web/swiper/assets/76638159/330538ab-bf5d-4f8c-a947-54b98fed2b6a

I have facing an issue related to swipper carousel I have attacted an Video also . Kindly fix this issue because i have user this carousel in project  I have need that . 
ISSUE:
When  I have Click on Next  Button the Carousel the Images sides by sides not proper work  but in case of i have click  on Previous button the work proper.

**Comment by nolimits4web** [comment]
Please don't ignore issue template
