### ISSUE TITLE
Incorrect slide displayed with slideTo

### ISSUE THREAD

**Issue by es-ki** [nolimits4web/swiper#7296]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/56rls4

### Bug description

Pressing a slide thumbnail, I would like to display a slider with the slide corresponding to the thumbnail active.
However, as shown in the video below, the expected slide is not displayed.

https://github.com/nolimits4web/swiper/assets/48976713/3f1c92dc-f76f-4869-884a-a8c4a50020ca

The active slide changes depending on the order in which the thumbnails are pressed and the number of times the slide is executed.

### Expected Behavior

When a thumbnail is clicked, the slider should display the corresponding slide as the active slide.

For example:

If thumbnail C is clicked, the slider should display slide C as the active slide.
After closing the dialog after swiping through multiple slides on the displayed slider, if thumbnail B is clicked, the slider should display slide B as the active slide.

### Actual Behavior

Depending on the order in which the thumbnails are pressed and the number of times the slides are executed, the active slide in the slider that appears when the dialog is opened will change.

### Swiper version

11.0.5

### Platform/Target and Browser Versions

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check the slideToLoop method instead
