### ISSUE TITLE
Virtual slides in combination with "auto" slides per view crashes

### ISSUE THREAD

**Issue by thomasowow** [nolimits4web/swiper#7301]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-vue-virtual-slides-forked-h3ddkv

### Bug description

When using the virtual slides feature in combination with a `slidesPerView` of `'auto'` something in the `updateSlides` call fails. To be precise the following line throws "getComputedStyle: Argument 1 is not an object":
https://github.com/nolimits4web/swiper/blob/fc308b377deee8cbbeb3c5cd41b1da710b82da8e/src/core/update/updateSlides.mjs#L101
Which indeed is true, `slide` is `undefined` here.

After some debugging I figured out that there is a mismatch between `slides` and `slidesLength`. `slides` is an empty array whereas `slidesLength` is a number above the expected `0`.

### Expected Behavior

It is expected that while using the virtual module, the `updateSlides` method will not throw when there are no slides yet.

### Actual Behavior

It crashes when there are no slides yet.

### Swiper version

11.0.6

### Platform/Target and Browser Versions

Ubuntu 23.04, Firefox 121.0 (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check documentation for virtual slides please
