### ISSUE TITLE
Add ability to double tap to zoom on mobile

### ISSUE THREAD

**Issue by broox** [nolimits4web/swiper#7305]
### Clear and concise description of the problem

The Zoom module's `toggle` parameter adds the ability to zoom in/out by double tapping on a slide. This works on desktop, but not mobile (tested on iOS, chrome).

### Suggested solution

Add the ability to double tap to zoom on mobile.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It works on mobile, if it is an issue then it should be created as issue correctly filling the issue form
