### ISSUE TITLE
Lagging while scrolling by touch gesture on mobile, depending on the elements inside the slide

### ISSUE THREAD

**Issue by sergdev777** [nolimits4web/swiper#7313]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://sample.wdd.co.il/hvh

### Bug description

Strange **lagging while scrolling the slides by touch sliding on mobile** (tested on galaxy note 10+ & s8), **its depending on the elements which inside the slide**, mostly I noticed as much the elements have **CSS text-shadow** / **filter: drop shadow()** - the more the slides are lagging.
Even if only one element with increased shadow like this `text-shadow: 0 0 10px black, 0 0 10px black, 0 0 10px black, 0 0 10px black, 0 0 10px black;` enhances the lagging.
This doesn't happen while scrolling in laptop touch screen nor in DevTools.

Using Swiper ver 4.5.1, because the slides are not work properly in newer versions.

**I tried all the solutions that described here: https://github.com/nolimits4web/swiper/issues/3728
Not one resolved the issue!**

(Sorry if my English is terrible)

### Swiper version

4.5.1

### Platform/Target and Browser Versions

Chrome latest versions

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
No support for such old devices
