### ISSUE TITLE
Swiper v 9.4.1 doesn't work properly on Samsung devices (Samsung browser)

### ISSUE THREAD

**Issue by NataliiaZhurbenko** [nolimits4web/swiper#7314]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

![Screenshot (190)](https://github.com/nolimits4web/swiper/assets/17195080/8f09a0d2-2a46-4bfb-be71-7b7aa2a186d2)

### Bug description

Hi guys! Please take a look!
I have the type error _e.matches is not a function_
![Screenshot (190)](https://github.com/nolimits4web/swiper/assets/17195080/8f09a0d2-2a46-4bfb-be71-7b7aa2a186d2)

### Expected Behavior

it should work as in any other browser

### Actual Behavior

totally broken on Samsung devices 

### Swiper version

9.4.1

### Platform/Target and Browser Versions

Samsung Internet

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper 9.x is not maintained anymore
