### ISSUE TITLE
Keyboard navigation prevents default action in case of web components

### ISSUE THREAD

**Issue by madman-maverick** [nolimits4web/swiper#7322]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-keyboard-control-forked-fhfl5h

### Bug description

Swiper library reacts to keyboard events even when not in focus, thus preventing default action on native input.

### Expected Behavior

When the swiper element is not in focus, it should not react to keyboard events.

### Actual Behavior

When a native input is present inside a shadow root, then default action of arrows keys is prevented by the swiper library. In the linked sandbox, click inside the input so that focus is in the input, then type something and press left or right arrow key. The cursor does not move, instead, the slides get swiped.

### Swiper version

https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js

### Platform/Target and Browser Versions

Observed for Chrome Version 121.0.6167.185. Should be reproducible for other browsers as well

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
your demo link is not working. Swiper reacts to keyboard when it is in view
