### ISSUE TITLE
Virtual Slides doesn't work with Coverflow effect

### ISSUE THREAD

**Issue by joshkalsi** [nolimits4web/swiper#7332]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/dreamy-chebyshev-6yh6sc

### Bug description

When using virtual slides, the coverflow animation breaks and the whole swiper moves when changing elements, rather than just the individual slides

### Expected Behavior

The coverflow animation is smooth and elements slide across as expected - the animation is fine using the core API, see https://codesandbox.io/p/sandbox/swiper-virtual-slides-forked-sy8zhv

### Actual Behavior

When you try and change slides via the pagination buttons or by drag + flick, the whole slider moves from the left or right depending on direction. This does not happen if you click and drag the slide fully into position.

### Swiper version

11

### Platform/Target and Browser Versions

macOS Chrome 121

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by nolimits4web** [comment]
update Swiper to latest verions
