### ISSUE TITLE
Expose utils to create a custom effect

### ISSUE THREAD

**Issue by lavolpecheprogramma** [nolimits4web/swiper#7336]
### Clear and concise description of the problem

Hi all, thanks for your hard works!
Can it be possible to expose the shared folder with all the utils that can be used to create a custom effect easily?
Watching the effects code, seems that can be very useful to have some functions like import "effectInit", "effectTarget" and "getSlideTransformEl".

### Suggested solution

In the package.json, expose the shared folder.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by mrleblanc101** [comment]
This doesn't seem to be documented, is there some exemple about custom effects ?
