### ISSUE TITLE
Loop Swiper slide is removed after loop

### ISSUE THREAD

**Issue by ghost** [nolimits4web/Swiper#734]
Hey,

i use your swiper to create an app store like slider for featured content. I have set the options for the swiper div like in your demo-apps/appstore example  added the loop options (loop : true,loopAdditionalSlides : 3,loopedSlides : 3,). When i now slide through the slides i have at the "end of the loop and begin" the problem that the first slide will be removed and added when i start sliding again. I hope you can figure out my problem ;)

thanks

![bildschirmfoto 2014-04-16 um 20 02 43](https://cloud.githubusercontent.com/assets/3233781/2723212/6300a768-c591-11e3-83df-2a0007fc9e02.png)

**Comment by tejasacquaintsoft** [comment]
On More Question regarding the same.

I have created 2 sliders one is horizontal and one is vertical. I have added vertical slider inside the horizontal slider. But the slideTo() method is not working for the vertical slider. However slideTo() is working fine for the horizontal slider. Can you help me to sort out this issue?

**Comment by tejasacquaintsoft** [comment]
I am getting TypeError: swiperV.slideTo is not a function error for vertical slider. The same is working fine for the horizontal parent slider. Vertical is child one.. 

Thanks,
Tejas
