### ISSUE TITLE
If the swiper is inside of an iframe it does not appear to recognize external mouseup events

### ISSUE THREAD

**Issue by anthrokatie** [nolimits4web/swiper#7345]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-responsive-breakpoints-jo2ri?file=%2Findex.html

### Bug description

If the swiper is inside of an iframe, click and hold (mousedown) inside of the iframe, then move the mouse outside of the iframe and release the click (mouseup) outside of the iframe. Moving the mouse/cursor back into the iframe means the swiper then sticks to the cursor and is only released on another physical mouse click.

This only appears to be an issue on desktop on Chrome, this does not appear to occur on Firefox or Edge.

I believe the following issue may have also been referring to this bug but has since been closed without a resolution (from what I can tell): https://github.com/nolimits4web/swiper/issues/7278

### Expected Behavior

The swiper should be released from the mouse/cursor when a mouseup event is fired and should not stick to the mouse when it moves back into the iframe.

### Actual Behavior

The swiper sticks to the mouse/cursor once the mouse moves back inside of the iframe (and the cursor stays set as grabbed) if the click has been released outside of the iframe.

### Swiper version

11.0.6

### Platform/Target and Browser Versions

Windows Chrome (Version 121.0.6167.189)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
it is a browser limitation, no access to parent window events
