### ISSUE TITLE
Swiper Options centeredSlides centeredSlidesBounds, slidesPerView: auto prevent initialSlide to be 0

### ISSUE THREAD

**Issue by ckefalianou** [nolimits4web/swiper#7347]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/sleepy-sky-5pyk3y?file=%2Fsrc%2Fcomponents%2FSwiperSlider.vue%3A14%2C9

### Bug description

When using the following settings together:

centeredSlides: true
centeredSlidesBounds: true
loop: false,
sliderPerView: 2 or 'auto' along with max-width on swiper-slide,
pagination: true

the **initialSlide** (the active slide) is always the second one and it can not be overridden to 0.

### Expected Behavior

1. Initially to have, 2 slidesPerView, left-aligned, no loop, no partial slides, and the **first** pagination bullet to be the active one.
2. After the first slideChange, I want the slides to be centered-aligned. Also, I want to partly see the previous and the next slide.
3. On the last scroll, I want the slides to be right-aligned, and see only the last 2 slides (no partials).

### Swiper version

^9.4.1

### Platform/Target and Browser Versions

Linux Ubuntu, All browsers

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by peterleilei86** [comment]
im having this issue as well!  what's the fix?

**Comment by KIICHISUDO** [comment]
me too. at ver11.1.15

**Comment by KIICHISUDO** [comment]
my same problem is fixed with "normalizeSlideIndex=false". (ver 11.1.15)
