### ISSUE TITLE
Zoom: Panning broken if zoom in svg 

### ISSUE THREAD

**Issue by antokhio** [nolimits4web/swiper#7352]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-zoom-forked-klg4gh?file=%2Fsrc%2FApp.jsx%3A36%2C26

### Bug description

Panning broken if i zoom in an svg. Looks like with img tag everything works perfect...

### Expected Behavior

Panning works whatever is zoomed 

### Swiper version

11.0.6

### Platform/Target and Browser Versions

chrome latest windows 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper
