### ISSUE TITLE
Virtual slides ignore initialSlide in the beginning

### ISSUE THREAD

**Issue by m345054** [nolimits4web/swiper#7353]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/bqv2137n/11/

### Bug description

When using initialSlide setting together with virtual, there is extra computing happening. Despite the value of initialSlide, Swiper currently always calls renderSlide with 0&1 indexes before rendering initialSlide slide. This is costly, when my createSlide() function is heavy.

--

Copied from #2755
This error still exists in v11.0.7

### Expected Behavior

Console Output:

Slide 4
Slide 5
Slide 6

### Actual Behavior

Console Output:

Slide 0
Slide 1
Slide 4
Slide 5
Slide 6

### Swiper version

v11.0.7

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by matichouraider** [comment]
@nolimits4web This doesn't work with React.

**Comment by creolio** [comment]
I'm also using react and have the same issue
