### ISSUE TITLE
Slide Indexing with loop is not working after last slide

### ISSUE THREAD

**Issue by ArtemOstapov** [nolimits4web/swiper#7357]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-infinite-loop-forked-34sp8c?file=%2Fsrc%2FApp.jsx

### Bug description

There is no docs about the loop indexing. There is only your official demo with the loop.
I have added printing slide indexes to your demo, and after last slide indexes are broken.
Here is a console log of it:
processSlideChange 1
processSlideChange 2
processSlideChange 3
processSlideChange 4
processSlideChange 5
processSlideChange 6
processSlideChange 7
processSlideChange 8
processSlideChange 7
processSlideChange 8
processSlideChange 7
processSlideChange 8

### Expected Behavior

indexing of slides should be the next:
processSlideChange 1
processSlideChange 2
...
processSlideChange 7
processSlideChange 8
processSlideChange 1
processSlideChange 2
...
processSlideChange 7
processSlideChange 8

### Actual Behavior

Here is a console log of broken indexing:
processSlideChange 1
processSlideChange 2
processSlideChange 3
processSlideChange 4
processSlideChange 5
processSlideChange 6
processSlideChange 7
processSlideChange 8
processSlideChange 7
processSlideChange 8
processSlideChange 7
processSlideChange 8

### Swiper version

11.0.7

### Platform/Target and Browser Versions

windows/Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Check realIndex
