### ISSUE TITLE
onSlideChange api called twice with diff real indexes after a loop

### ISSUE THREAD

**Issue by ArtemOstapov** [nolimits4web/swiper#7360]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-infinite-loop-forked-34sp8c?file=%2Fsrc%2FApp.jsx%3A36%2C15

### Bug description

I'm trying to do some code with certain slides in a loop. First loop is OK and realIndex is working fine in onSlideChange api and as expected.
But after a loop onSlideChange api is called twice for one SlideChange with different realIndex numbers.

Here is a console log of it:
processSlideChange 1
processSlideChange 2
processSlideChange 3
processSlideChange 4
processSlideChange 5
processSlideChange 6
processSlideChange 7
processSlideChange 8
processSlideChange 8
processSlideChange 0
processSlideChange 0
processSlideChange 1
processSlideChange 1
processSlideChange 2
processSlideChange 2
processSlideChange 3
...

tell me plz how can I use realIndex only once in onSlideChange after a loop without any additional hacking/crutch ?
tnx in advance

### Expected Behavior

indexing of slides should be the next:
processSlideChange 1
processSlideChange 2
...
processSlideChange 7
processSlideChange 8
processSlideChange 0
processSlideChange 1
processSlideChange 2
...
processSlideChange 7
processSlideChange 8
...

### Actual Behavior

processSlideChange 1
processSlideChange 2
...
processSlideChange 7
processSlideChange 8
processSlideChange 8
processSlideChange 0
processSlideChange 0
processSlideChange 1
processSlideChange 1
processSlideChange 2
processSlideChange 2
processSlideChange 3

### Swiper version

11.0.7

### Platform/Target and Browser Versions

windows/Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by nolimits4web** [comment]
This how loop works (check the DOM) and issues is not the place to ask how to do things
