### ISSUE TITLE
Swiper can't drag from space between slides

### ISSUE THREAD

**Issue by LoranRendel** [nolimits4web/swiper#7362]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#slides-per-view-auto

### Bug description

When start dragging from space between slides it's work only on first screen.

### Expected Behavior

Dragging is working on any screen

### Actual Behavior

When we try do drag slides and touch/click the space between cards, the dragging doesn't work.
It happens because of flex layout and width 100%. the items out of 100% width can be dragged, but not the space between.

### Swiper version

11.0.7

### Platform/Target and Browser Versions

windows chrome etc

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
