### ISSUE TITLE
grabCursor state doesn't get updated on breakpoint changes

### ISSUE THREAD

**Issue by Hasan-Mir** [nolimits4web/swiper#7364]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-grabcursor-bug-n6p2r5?file=%2Fsrc%2FApp.js%3A11%2C26

### Bug description

If we want to have different behavior for `grabCursor` for some breakpoints like this:
```js
<Swiper
  ref={sliderRef}
  slidesPerView={3}
  spaceBetween={10}
  breakpoints={{
    350: { slidesPerView: 1.2, grabCursor: false },
    420: { slidesPerView: 1.5, grabCursor: false },
    480: { slidesPerView: 2, grabCursor: false },
    560: { slidesPerView: 3, grabCursor: true },
    850: { slidesPerView: 3.5, grabCursor: true },
    1000: { slidesPerView: 4, grabCursor: true },
  }}
/>
```
When the breakpoint changes, Swiper doesn't update the `grabCursor` state until the slider is swiped. However this only happens for `false -> true` state transition not `true -> false`. I mean if the `grabCursor` state is `true` and we resize the window to a breakpoint in which the `grabCursor` is set to `false`, it won't get updated even after the user's swipe.

https://github.com/nolimits4web/swiper/assets/62181905/3492fc69-303c-4e4b-b982-68288ef9d228

### Actual Behavior

The `grabCursor` state should get updated immediately when the breakpoint changes.
Additionally, it would be beneficial if Swiper could merge breakpoint parameters (not just `grabCursor`) from one breakpoint to the next.

For example in this code:
```js
<Swiper
  breakpoints={{
    350: { slidesPerView: 1.2, grabCursor: false },
    420: { slidesPerView: 1.5, grabCursor: false },
    480: { slidesPerView: 2, grabCursor: false },
    560: { slidesPerView: 3, grabCursor: true },
    850: { slidesPerView: 3.5, grabCursor: true },
    1000: { slidesPerView: 4, grabCursor: true },
  }}
/>
```
As you can see, from `350` breakpoint onwards, the `grabCursor` is set to `false` and from `560` breakpoint onwards, the `grabCursor` is set to `true`. To avoid redundancy, I prefer to omit the repeated property and write it as follows:
```js
<Swiper
  breakpoints={{
    350: { slidesPerView: 1.2, grabCursor: false },
    420: { slidesPerView: 1.5},
    480: { slidesPerView: 2},
    560: { slidesPerView: 3, grabCursor: true },
    850: { slidesPerView: 3.5},
    1000: { slidesPerView: 4},
  }}
/>
```

### Swiper version

11.0.7

### Platform/Target and Browser Versions

Chrome 122.0.6261, Firefox 123.0.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper
