### ISSUE TITLE
On window resize with slider previous partial slide disappears until you scroll interact with the slider. 

### ISSUE THREAD

**Issue by houtaiwong-toast** [nolimits4web/swiper#7376]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-infinite-loop-forked-wqfvh4?file=%2Findex.html%3A92%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltrl0f6r00063b6gafl7ybsb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltrl0f6q00023b6ga7vhlxef%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltrl0f6q00033b6gthif8mmj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltrl0f6q00053b6gdlpsw20p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltrl0f6q00023b6ga7vhlxef%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltrl0f6q00013b6gp87ahazc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A92%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A92%252C%2522endColumn%2522%253A36%257D%255D%257D%255D%252C%2522id%2522%253A%2522cltrl0f6q00023b6ga7vhlxef%2522%252C%2522activeTabId%2522%253A%2522cltrl0f6q00013b6gp87ahazc%2522%257D%252C%2522cltrl0f6q00053b6gdlpsw20p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltrl0f6q00043b6gzi0evcsx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltrl0f6q00053b6gdlpsw20p%2522%252C%2522activeTabId%2522%253A%2522cltrl0f6q00043b6gzi0evcsx%2522%257D%252C%2522cltrl0f6q00033b6gthif8mmj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltrl0f6q00033b6gthif8mmj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Bug description

When slidesPerView is something other than a whole number (i.e 1.25) and centeredSlides is true. On window resize the previous partial slide does not show up until I interact with the slider. I've added a gif of the reproduction of this issue. 

![ScreenRecording2024-03-14at2 54 50PM-ezgif com-video-to-gif-converter](https://github.com/nolimits4web/swiper/assets/55763151/70545695-683a-458b-a2af-52df70f98bc1)

### Expected Behavior

I expect the partial slides to always show .25 of the next and previous slides.

### Actual Behavior

The previous partial slide disappear on window resize. 

### Swiper version

11.0.7

### Platform/Target and Browser Versions

MacOS Chrome 122

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by houtaiwong-toast** [comment]
Want to add some more color here. This only happens when the amount of slides is less than or equal to 4. I've also tried to add the property loopAdditionalSlides to the the amount equal to the slides I have. Which fixes the resize, but on init the next slide does not partially show. 

<img width="1726" alt="image" src="https://github.com/nolimits4web/swiper/assets/55763151/4b0da5e0-fd15-46e5-9f81-e3e3a0c0aa08">

**Comment by alicarbon** [comment]
I'm having the same issue
