### ISSUE TITLE
Slides in the module Creative Effect are not duplicated

### ISSUE THREAD

**Issue by Oleksandr07** [nolimits4web/swiper#7395]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/Oleksandr07/pen/poBRVZL

### Bug description

When you go to the last slide, the next slide will not be displayed

![2024-03-19_17 32 19](https://github.com/nolimits4web/swiper/assets/11850595/42bf5ad8-94ca-4cd4-bb9b-940f6667c950)

### Expected Behavior

It is necessary to make the next two slides, after the active slide, visible

### Swiper version

11.0.7

### Platform/Target and Browser Versions

Chrome 121

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
creative effect works as with slides Per view 1 and behaves in the same way, try to play with loop parameters
