### ISSUE TITLE
The Swiper is throwing an error at runtime: "el.matches is not a function".

### ISSUE THREAD

**Issue by bowstone** [nolimits4web/swiper#7398]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/nice-sunset-7w6sdx?file=%2Fsrc%2FApp.tsx

### Bug description

Version：10.3.0
Error log：Uncaught TypeError: el.matches is not a function
![image](https://github.com/nolimits4web/swiper/assets/3377755/530d02b2-e3dd-4041-82d8-b4deb74bd069)
Code location：
![image](https://github.com/nolimits4web/swiper/assets/3377755/55ba2d08-ce97-462d-b628-593b60d25e62)
Babel compile ES2015 spread to ES5，output：`[].concat(element.children).filter(el=>el.matches(selector))`
In JavaScript, attempting to use `[].concat(element.children)` to convert a collection of an element's child elements into a real array may not work as expected because element.children is an HTMLCollection, not an actual array.
My Babel version：
    @babel/core@7.24.1 
    @babel/plugin-transform-spread@7.24.1

### Swiper version

10.3.0

### Platform/Target and Browser Versions

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
