### ISSUE TITLE
Swiper gets in a infinite loop when placed in a grid container

### ISSUE THREAD

**Issue by Ebeldev** [nolimits4web/swiper#7402]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/Ebeldev/pen/oNOZxVZ

### Bug description

When you place a swiper in a grid container. If you don't set a specific width, swiper will loop and flickers. 

Let's say you have a grid container inside you have 2 divs. One been a sidebar and the other one a swiper-container. 

You have to specify a fixed width to the swipe container. But if you do this, you loose the responsiveness of the resize window and the benefit of having fullyresponsive div's.

### Swiper version

11

### Platform/Target and Browser Versions

mac Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use issue search before posting a new one
