### ISSUE TITLE
When 'previous/next slide' buttons are inside slider and if clicked on next slide button, the slider is moving to previous slide on tab/window switch

### ISSUE THREAD

**Issue by eswar-janjanam** [nolimits4web/swiper#7405]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-css-mode-forked-4qc5hv?file=%2Findex.html%3A57%2C58

### Bug description

When the buttons for moving the slides back and forth are inside the slider and the user clicks on the button for moving to next or previous slide, the slide is moving to next or previous slide accordingly. But after the slide is changed, if the user switches browser tab / browser window and coming back to the tab/window containing swiper, the slider is moving back to previous slide from where the button is clicked.

Steps to reproduce:
1. Click on 'Next' button in Slide 1. The slider will go to Slide 2.
2. Do a tab switch / window switch and come back to the swiper tab.
3. Observe the slide number. It is coming back to Slide 1 from where the button is clicked.
4. Similarly, click on 'Next' button in Slide 1.
5. In Slide 2, click on 'Previous' button. It will go to Slide 1.
6. Do a tab switch / window switch and observe the slide number.
7. It should be on Slide 1, but it is moving to Slide 2 from where the button is clicked.

### Expected Behavior

The slider should stay in the same slide instead of moving to previous slide on tab/window switch.

### Actual Behavior

The slider is moving to previous slide instead of staying in the same slide on tab/window switch.

### Swiper version

11.0.3

### Platform/Target and Browser Versions

macOS chrome 122.0.6261.129

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Demo link posted doesn’t work
