### ISSUE TITLE
swiper/react: lazy loading doesn't work, even in your own demo link

### ISSUE THREAD

**Issue by kotoyama** [nolimits4web/swiper#7407]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-lazy-load-images-rllglc?file=%2Fsrc%2FApp.jsx

### Bug description

Lazy loading feature for React isn't working, even in your own demo link provided from the official docs.

If you look into the network tab, you'll see this for yourself:
<img width="613" alt="image" src="https://github.com/nolimits4web/swiper/assets/26006369/de863b40-7d92-47c0-9260-3480eec8d511">

Swiper version from reproduction link is 10.0.0, but this is the same in higher versions.

### Expected Behavior

Each image should be loaded as you swipe.

### Actual Behavior

All the images are loaded at once.

### Swiper version

11.0.7

### Platform/Target and Browser Versions

macOS Chrome 122.0.6261.94

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
you must do a production build
