### ISSUE TITLE
IgnoredEventCancel : intervention: Ignored attempt to cancel a touchmove event with canclable=false

### ISSUE THREAD

**Issue by chonlatit-tpit** [nolimits4web/swiper#7415]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

-

### Bug description

Hi,

We use swiper in our project and we occasionally found the error from error monitoring tools (datadog).
The error is come form /swiper/esm/components/scrollbar/scrollbar.js (see attached files).

We try to reproduced the bug but cant. We used to have the same bug in other parts of our code and we solve this with

if (e.cancelable) {
   e.preventDefault();
}
In this case, Is it possible to create pull requests for fixed this one.

Our project used

nextjs (v.12.2)
swiper (v.6.8.4)

<img width="1176" alt="313533780-26c9eba0-240e-44a3-9ca2-f64b3b243ac5" src="https://github.com/nolimits4web/swiper/assets/79088614/4ec12286-5d3c-4918-b022-f96fb847066b">

### Expected Behavior

Should not show error in any browser.

### Actual Behavior

Error shown up in some error. (We found from monitoring tool)

### Swiper version

6.8.4

### Platform/Target and Browser Versions

Android/Chrome Mobile

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by chonlatit-tpit** [comment]
@nolimits4web Hi, do you need more information ?

**Comment by chonlatit-tpit** [comment]
@nolimits4web 
Thanks for fixed the code on master branch
I'm not sure is it possible to update on version `6.8.5` ?
