### ISSUE TITLE
TypeError : Cannot read properties of undefined (reading 'speed')

### ISSUE THREAD

**Issue by chonlatit-tpit** [nolimits4web/swiper#7416]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

-

### Bug description

Hi,

We use swiper in our project and we occasionally found the error from error monitoring tools (datadog).
The error is come form /swiper/esm/components/core/slide/slideNext.js (see attached files).

We try to reproduced the bug but cant. We used to have the same bug in other parts of our code and we solve this with

speed = this?.params?.speed
In this case, Is it possible to create pull requests for fixed this one.

Our project used

nextjs (v.12.2)
swiper (v.6.8.4)

<img width="1552" alt="Screen Shot 2023-10-09 at 11 39 25 AM" src="https://github.com/nolimits4web/swiper/assets/79088614/5817fbc1-2f34-43a7-b78b-faf8786c91dc">

### Expected Behavior

Should not show error in any browser.

### Actual Behavior

Error shown up in some error. (We found from monitoring tool)

### Swiper version

6.8.4

### Platform/Target and Browser Versions

macOS/Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by chonlatit-tpit** [comment]
@nolimits4web Hi, do you need more information ?

**Comment by zainali225** [comment]
Did you try to pass second argument of speed.In my case, it solved the issue
textSwiper.slideTo(imageSwiper.activeIndex, 0);

**Comment by chonlatit-tpit** [comment]
Hi, we didn't use .slideTo method but we use autoplay options.
The error occur when we use autoplay options then we change page and swiper try to slideNext (from autoplay option).

Our website use Next.js and we change with next router (change page without refresh)

**Comment by chonlatit-tpit** [comment]
@nolimits4web 
Thanks for fixed the code on master branch
I'm not sure is it possible to update on version `6.8.5` ?
