### ISSUE TITLE
Swiper Coverflow Effect is broken on initial load, then it is fixes itself after few seconds

### ISSUE THREAD

**Issue by avuji31** [nolimits4web/swiper#7420]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-effect-coverflow-6pxf4v?file=%2Fsrc%2FApp.jsx%3A10%2C23

### Bug description

Hello I am using next 14.1.0. I have problem with Swiper Coverflow effect. It is not just Coverflow effect, I also tested it on Cube effect and I have simmular problem.

When I refresh the page, swiper with coverflow effect is not applied, but after few seconds coverflow effect is applied.
Same situation is for Cube effect.

I thought the problem might be with my data which is prefecthed on server, but I also tried it with hardcoded values, and I have same problem. 

In this link is video of what is happening. I have copied code from reprocuction link in my next 14.1.0 app. 
https://streamable.com/e08hl8
Everything else is same.

### Expected Behavior

It should apply Coverflow effect on initial loading.

### Actual Behavior

It does not apply Coverflow effect on initial loading.

### Swiper version

11.0.7

### Platform/Target and Browser Versions

mac OS Google Chrome,  Safari , Brave

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by nolimits4web** [comment]
Probably related to how next initializes Swiper, try using the core version of Swiper, and your demo link is not working

**Comment by sagrawal31** [comment]
We are also facing this when using it in an overlay. Made sure that the Swiper initialises after view fully loaded. Then doing `$0.swiper.update()` manually fixes it.

**Comment by sagrawal31** [comment]
We are also facing this when using it in an overlay. Made sure that the Swiper initialises after view fully loaded. Then doing $0.swiper.update() manually fixes it.

<img width="1899" height="942" alt="Image" src="https://github.com/user-attachments/assets/f4407a58-1d17-4afa-bff2-5404fc4d839a" />

Configuration:

```
this.isMobile = false;

this.swiperOptions = {
    direction: this.isMobile ? 'vertical' : 'horizontal',
    effect: this.isMobile ? 'slide' : 'coverflow',
    slidesPerView: 'auto',
    initialSlide: 2,
    centeredSlides: true,
    spaceBetween: 0,
    coverflowEffect: {
        rotate: 0,
        stretch: 175,
        depth: 100,
        modifier: 1,
        scale: 0.7,
        slideShadows: false,
    },
    mousewheel: {
        enabled: !this.isMobile,
        invert: false,
        thresholdDelta: 20,
    },
};
```

After I manually update it via console-

<img width="1901" height="938" alt="Image" src="https://github.com/user-attachments/assets/e348d455-d4d5-4864-9932-8e0f2b051777" />
