### ISSUE TITLE
ThumbsOptions incorrect types

### ISSUE THREAD

**Issue by dvdmlln** [nolimits4web/swiper#7421]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

-

### Bug description

I'm using Vue with Swiper Element and define SwiperOptions in my vue setup using `SwiperOptions` Type form `swiper/types`. Then I use v-bind to pass the attributes as props.
`thumbs.swiper` requires the type `Swiper | null`, so passing a CSS Selector obviously throws the following type error: `Type 'string' is not assignable to type 'Swiper'.`, but the thumbs do work.
So the `thumbs.swiper` type should be  `Swiper | string | null` instead.
This may also effect other options.

### Swiper version

11.0.6

### Platform/Target and Browser Versions

all

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper
