### ISSUE TITLE
Next/Prev buttons not working when navigation via keyboard

### ISSUE THREAD

**Issue by kdgraham3** [nolimits4web/swiper#7423]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-navigation-forked-yw4g5x?file=%2Findex.html

### Bug description

Next/Prev navigation buttons (.swiper-button-prev and swiper-button-next) don't work when keyboard is used to navigate.   This is needed to navigate the swiper carousel for Accessibility - currently keyboard/assistive tech users can't access the carousel.

To replicate, go to the Reproduction link (this is direct fork of navigation demo, no adjustments), use keyboard "tab" key to focus swiper arrow, once in focus press keyboard "Enter/Return" key.

Affected code is shown here:
<img width="821" alt="Screenshot 2024-03-27 at 1 21 14 pm" src="https://github.com/nolimits4web/swiper/assets/88119121/7193080b-4c5c-4d76-ba05-da3f871756f0">

Small tweak to code fixes the issue...
<img width="745" alt="Screenshot 2024-03-27 at 1 10 13 pm" src="https://github.com/nolimits4web/swiper/assets/88119121/9679ba12-c9c0-4e39-847e-3f321682e195">

### Expected Behavior

Pressing Enter key when next/prev arrows are in focus should trigger the carousel to slide.

### Actual Behavior

Pressing Enter key when next/prev arrows are in focus does nothing.

### Swiper version

11.0.7

### Platform/Target and Browser Versions

MacOS Chrome 122.0.6261.139

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by olsp** [comment]
Kind of related to this issue: I'm wondering why the div-element is used (as "recommended" in the docs) for the navigation buttons instead of the button-element? Wouldn't it be semantically correct to use the button-element? It may be beneficial for accessibility.
