### ISSUE TITLE
Virtual Slides + History bug

### ISSUE THREAD

**Issue by dmaus** [nolimits4web/swiper#7425]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-vue-virtual-slides-history-rmghlx?file=%2Fsrc%2FApp.vue%3A13%2C18

### Bug description

When jumping to a virtual slide (click a button under the slider) it throws an error:
`runtime-core.esm-bundler.js:221 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')`
It's not able to get the attribute "data-history" from the slide in the history code.

History changes only show in preview mode: https://rmghlx-5173.csb.app/

### Expected Behavior

Showing the history of the slide in the browser url

### Actual Behavior

Not changing the history, because it does not get the attribute "data-history"

### Swiper version

11.0.7

### Platform/Target and Browser Versions

macOS Chrome 121.0.6167.184 (Official Build) (x86_64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Vue version is not maintained, use core version or web component
