### ISSUE TITLE
Breakpoint not working reliably when having a min-width configured on any parent element e.g. body

### ISSUE THREAD

**Issue by Ruben-check24** [nolimits4web/swiper#7451]
### Check that this is really a bug

- [X] I confirm

### Bug description

Breakpoints work fine but as soon as I add a `min-width` to any parent Element of the swiper and its greater or equal to the `breakpoint`, it doesn't work reliably anymore when the window gets resized (slowly).
I added a `min-width` of `1024px` on a `div` above the swiper (common thing to do on desktop is to have such `min-width` on the `body`) and on the swiper I have a breakpoint at `1024px` to show 5 slides. The effect/bug is even more noticeable/occurs more often when the `min-width` of the `div` is greater than the `breakpoint`. You have to resize the window pretty fast for swiper to react to it correctly. With `breakpointBase="container"` it seems to work perfectly fine.

Similar Demo in react with different values which makes it more noticeable. `min-with` is much higher than the `breakpoint`: [codesandbox](https://codesandbox.io/p/devbox/swiper-react-responsive-breakpoints-forked-fkf7tr?file=%2Fsrc%2FApp.jsx%3A20%2C22&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clumfqs8w00083b6khrwzvlsk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clumfqs8w00033b6kq9ivp7jo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clumfqs8w00053b6kgq1xajqp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clumfqs8w00073b6kpamcsmyg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clumfqs8w00033b6kq9ivp7jo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumfqs8w00023b6kfqndv02r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A22%257D%255D%257D%255D%252C%2522id%2522%253A%2522clumfqs8w00033b6kq9ivp7jo%2522%252C%2522activeTabId%2522%253A%2522clumfqs8w00023b6kfqndv02r%2522%257D%252C%2522clumfqs8w00073b6kpamcsmyg%2522%253A%257B%2522id%2522%253A%2522clumfqs8w00073b6kpamcsmyg%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522clurenr8q00tp3b6io4llqufi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clurenr8q00tp3b6io4llqufi%2522%257D%252C%2522clumfqs8w00053b6kgq1xajqp%2522%253A%257B%2522id%2522%253A%2522clumfqs8w00053b6kgq1xajqp%2522%252C%2522activeTabId%2522%253A%2522cluremisb00r33b6ippcgez94%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumfqs8w00043b6kc44cwxt6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cluremisb00r33b6ippcgez94%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluremiug0kbndhi8gkjd8pof%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Demo VIdeo

https://github.com/nolimits4web/swiper/assets/92583338/41c8a874-0f6c-4276-8d58-4074de183279

### Expected Behavior

No matter the "resize speed", breakpoint should be handled correctly and reliably when a parent element has a 'min-width' set

### Actual Behavior

When a parent Element has a min-width that is equal or larger than the breakpoint, the breakpoint does't trigger reliable anymore

### Swiper version

11.1.0

### Platform/Target and Browser Versions

macOS Chrome, Firefox, Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by nolimits4web** [comment]
Swiper uses ResizeObserver to trigger the resize logic (for better performance), so if its size not changed it will do nothing. You can disable `resizeObserver` parameter or use `container` as a breakpoints base

**Comment by Ruben-check24** [comment]
thanks for looking into it and I get the rational behind it. I think it would be helpful to document this behaviour in the description for `breakpoints` and `breakpointsBase`
