### ISSUE TITLE
Edge Recoil and Custom Zoom Area Behavior on Mobile Zoom

### ISSUE THREAD

**Issue by SerhiiStepanenko** [nolimits4web/swiper#7452]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/eager-leakey-3tll5r?file=%2Fsrc%2FModalSlider.js

### Bug description

While using the Swiper's zoom feature on a mobile device, I've encountered an issue where the image slightly recoils from the edge of the display as it approaches it during a pinch-to-zoom action. This unintended behavior results in a less smooth zoom experience. Additionally, I am interested in customizing the zoom feature to enable zooming into the specific area where the user applies the pinch gesture, rather than the current functionality that zooms into the image's center regardless of where the user pinches.

https://github.com/nolimits4web/swiper/assets/58136678/de674b9f-1a7a-4f0d-86fe-4094fab5527d

### Expected Behavior

When zooming in on an image, the expected behavior is for the image to seamlessly zoom towards the edges without recoiling. For a more intuitive user experience, zooming should focus on the area between the user's fingers, allowing for precise control over the zoomed area.

### Actual Behavior

Currently, as the image approaches the edge of the screen during zoom, it slightly recoils away from the edge before continuing to zoom in normally. Moreover, the zoom functionality is centered on the image rather than the area pinched by the user, limiting the user's ability to zoom into specific parts of the image.

### Swiper version

6.8.4

### Platform/Target and Browser Versions

iOS, Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper 6.8.4 is not maintenance anymore
