### ISSUE TITLE
Pagination innerHTML setter violates Content Security Policy

### ISSUE THREAD

**Issue by cherie-xf** [nolimits4web/swiper#7459]
### Clear and concise description of the problem

Our project has issue when set up the Contnet Security Policy.
The Swiper pagination violates the CSP directive: control the data passed to DOM XSS sink functions, like Element.innerHTML setter 

![image](https://github.com/nolimits4web/swiper/assets/8013454/bd37ed55-c9a7-4d8d-b0c4-12e5cef18068)

### Suggested solution

could createElement and appendChild

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Updates your CSP or use custom pagination instead
