### ISSUE TITLE
Straightforward Angular Integration

### ISSUE THREAD

**Issue by cyberiumabc** [nolimits4web/swiper#7471]
### Clear and concise description of the problem

Swiper@8 had smooth angular wrapper. Sadly that is no more there for past many version and the v11 is also the same. Is there a plan to make Swiper seamless with Angular's latest versions like 17 or 18?

### Suggested solution

Create a providermodule of Swiper for SSR friendly integration.

### Alternative

Currently there are too many hoops to jump, create standalone component, directive and Custom-schema.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
There is no plans to provide an Angular component
