### ISSUE TITLE
Swiper slide width is rounded if `roundLengths` disabled

### ISSUE THREAD

**Issue by abachyla** [nolimits4web/Swiper#7473]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-default-forked-r4p4yq

### Bug description

When a Swiper container has a fractional width, each slide has a rounded width, even when [roundLengths](https://swiperjs.com/swiper-api#param-roundLengths) is set to `false`. In the playground, the slide width is more than a container width and a part of a slide is hidden (the slide should have right 1px border):
![Screenshot 2024-04-15 at 15 58 31](https://github.com/nolimits4web/swiper/assets/10487250/4e94cb24-38ff-4d4a-bd4a-b9fc9fc136fc)

Container width - 303.5px:
![Screenshot 2024-04-15 at 16 00 18](https://github.com/nolimits4web/swiper/assets/10487250/e5c89e5a-a35b-4a00-b552-e578d95588e4)

Slide width - 304px:
![Screenshot 2024-04-15 at 16 00 28](https://github.com/nolimits4web/swiper/assets/10487250/cf2cc402-af6c-496d-98dd-1fcc9c4699da)

Could be related to https://github.com/nolimits4web/swiper/issues/7248

### Expected Behavior

Swiper slide should have the same width as a container in this case.
![Screenshot 2024-04-15 at 16 11 20](https://github.com/nolimits4web/swiper/assets/10487250/7f83de67-cecf-46bc-851f-0f32247e725c)
![Screenshot 2024-04-15 at 16 11 11](https://github.com/nolimits4web/swiper/assets/10487250/d17d888f-6661-4c38-9852-687c5eb0ecd6)

### Actual Behavior

Swiper slide width is more than a container width and a slide is partially hidden.

### Swiper version

11.1.1

### Platform/Target and Browser Versions

macOS 14.4.4 Chrome v123.0.6312.107, Windows 11 Chrome v123.0.6312.123

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use slidesPerView as auto
