### ISSUE TITLE
swiper should init rtl based on document dir

### ISSUE THREAD

**Issue by Farbdose** [nolimits4web/swiper#7479]
### Clear and concise description of the problem

When creating a swiper it always assumes direction = "ltr" unless told otherwise either through the usage of the dir property or through calling the changeLanguageDirection function.

### Suggested solution

On creation the [main init function](https://github.com/nolimits4web/swiper/blob/49ac977de936e1f34fd45b309a1e1657da3f69ed/src/core/core.mjs#L562) could check for the overall document direction and set it accordingly. The behavior could be controlled by providing "auto" as dir attribute on the swiper:

```
if (swiper.dir == "auto") {
    swiper.changeLanguageDirection(document.documentElement.getAttribute("dir"));
}
```

### Additional context

Dynamic changes of the language direction can be handled by the developer based on concrete implementation.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It already checks document and element direction https://github.com/nolimits4web/swiper/blob/master/src/core/core.mjs#L545
