### ISSUE TITLE
Change the Swiper gesture direction for transformed containers

### ISSUE THREAD

**Issue by Vamoss** [nolimits4web/swiper#7482]
### Clear and concise description of the problem

When the container is rotated 180o, the gestures does not follow the container transformation.

### Suggested solution

Make possible to change the gesture direction in case the container is transformed (rotated 180o).

### Alternative

Intercept all events so we can change values before apllied.

### Additional context

I have a touchscreen where I mirror the interface in half of the screen.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Not an option sorry
