### ISSUE TITLE
Swiper init incorrectly determining RTL when inside ion-content 

### ISSUE THREAD

**Issue by Farbdose** [nolimits4web/swiper#7483]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/angular-ywh4p1-vza2cj?file=src%2Fapp%2Fapp.component.html

### Bug description

When placing a swiperjs.com swiper inside an ion-content (and rendering it with a delay) the swiper doesn't recognize the surrounding dir="rtl". Only happens with ion-content.

I'm not sure if this is a swiperjs problem or an ionic problem but ionic asked me to create an issue here too: https://github.com/ionic-team/ionic-framework/issues/29368#issuecomment-2069581280

### Expected Behavior

rtl should propagate through ion-content regardless of when the component is rendered.

### Actual Behavior

1. create a div with dir="rtl"
2. put a swiper inside an ion-content inside the div and render it a few ticks later using ngIf
3. try swiping
4. swiper doesn't swipe

See linked stackblitz, first swiper works on clean page load but breaks after stackblitz livereload, second swiper doesn't work at all, 3rd and 4th work.

### Swiper version

11

### Platform/Target and Browser Versions

macOS Chrom 124

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Farbdose** [comment]
Based on what I've seen so far it looks like the swiper init runs before the swiper element itself is fully integrated in the dom making it not recognize the surrounding style rules as it's still floating somewhere in the deep dark shadow dom. 

Get Computed Style reports ltr while theoretically inside the diff with RTL and only switches to RTL a few ticks later.

**Comment by liamdebeasi** [comment]
Wanted to cross post my findings regarding this issue: https://github.com/ionic-team/ionic-framework/issues/29368#issuecomment-2075776241

This was originally reported as an Ionic Framework issue, but the root cause appears to be related to how inheritance works with slotted content.

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by nolimits4web** [comment]
I am not sure what else we can do here on Swiper side. It is already initialized only within a connected callback. And here is the example of when it is placed inside of the multiple custom elements components  https://codepen.io/nolimits4web/pen/eYwvObb. Everything works as expected
