### ISSUE TITLE
Swiper Elements isn't working with register function in Stenciljs 

### ISSUE THREAD

**Issue by mhdalhanbali** [nolimits4web/swiper#7499]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no Reproduction link

### Bug description

When i try to implement Swiper Elements with register function inside my project using Stencil JS it's not working  but when i use the CDN links everything works fine. I found this open issue in [Stackoverflow](https://stackoverflow.com/questions/77105640/import-swiper-js-in-a-stencil-js-web-component) with the same issue. Any suggestion on how could this issue be solved ? thanks 

// import function to register Swiper custom elements
import { register } from 'swiper/element/bundle';
// register Swiper custom elements
register();

### Expected Behavior

The register function should work with no need for a cdn link

### Actual Behavior

Register function isn't working, when i try to use it instead of cdn link nothing works and nothing is logged to the consol 

### Swiper version

11.1.1

### Platform/Target and Browser Versions

Macos chrome,Macos Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> no Reproduction link
