### ISSUE TITLE
Custom Navigation with Pagination

### ISSUE THREAD

**Issue by NeoMudaly** [nolimits4web/Swiper#75]
I have 2 methods for navigation: swiper and pagination.

I can't work out how to pass the active class for the active slide to the pagination button.
The method I used involves assigning the class to the button that is clicked, but can the active class be passed to the button when swiping?

Here's a <a href='http://jsfiddle.net/Neo360/9VBha/13/'>link to the fiddle</a>

**Comment by sordespilosus** [comment]
nolimits4web, why your solution doesn't work in Swiper v3.4.0 ?

thank you

**Comment by Barh** [comment]
@sordespilosus ,

The current API: http://idangero.us/swiper/api/

The events are now set as follows: **mySwiper.on('slideChangeStart'**, function (swiper) {});
Property: swiper.activeSlide now **swiper.activeIndex**

It is more **correct** to customize the buttons of the slider, with these properties:
**Pagination**, **paginationElement**, **bulletClass**, **bulletActiveClass**, **paginationBulletRender**

Read the API: http://idangero.us/swiper/api/

There is everything you need. Very accessible and convenient!

**Comment by gosh34** [comment]
Hello guys,
this is great, thanks to NeoMudaly and especially to Nolimits4web.
I looked at the Fiddle, and my question here is, can it run without jQuery, I have downloaded even the smallest now ( http://code.jquery.com/jquery-3.2.1.slim.min.js ), but it is still 68KB?

I could live with it, but initially I was so happy when I sow the 19KB "idangerous.swiper-1.8.min.js".

Thanks in advance!
IRK
