### ISSUE TITLE
Pressing middle mouse button opens the link in a new tab

### ISSUE THREAD

**Issue by dijkermans** [nolimits4web/swiper#7512]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-default-hyperlink-v2fp7j

### Bug description

When pressing the scrollwheel button (middle mouse button), it opens the hyperlink in a new tab.

### Expected Behavior

Scroll lock, as in the demos, or: opening the link in the same tab (target _self).

### Actual Behavior

it opens the hyperlink in a new tab.

### Swiper version

11.1.1

### Platform/Target and Browser Versions

Windows 10 / Chrome 124 / Logitech MX518

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Closing as not related to Swiper
