### ISSUE TITLE
Inconsistently manual scrolling when autoplay with delay 0, regression in 9 version

### ISSUE THREAD

**Issue by alkorlos** [nolimits4web/swiper#7515]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-9-autoplay-delay-0-f29fh3

### Bug description

Create a creeping line, applying the following parameters: `speed: 3500` and `autoplay-delay 0`.

Visually, it looks like what need, but there is a bug with manual scrolling. The `transition-duration` of the `swiper-wrapper` should reset to 0 during manual scrolling. Starting from version 9, this happens inconsistently. Attaching a video for reference.
[2024-05-03 12-21-21_1.webm](https://github.com/nolimits4web/swiper/assets/14668230/fa288644-352a-41db-b23c-a1a876ab659f) During the first manual scroll, the `transition-duration` doesn't reset to 0; however, during the second manual scroll, it works correctly.

With  `autoplay-delay 1000` work correct.

In version 8.4.7 [work correct](https://codesandbox.io/p/sandbox/swiper-8-autoplay-delay-0-2h39hn?file=%2Findex.html).

### Expected Behavior

`transition-duration` reset to 0 with manual scrolling.

### Actual Behavior

`transition-duration` not reset to 0 with manual scrolling.

### Swiper version

from 9.4.1, including 11.1.1

### Platform/Target and Browser Versions

macOS Chrome 124, Windows Chrome 124

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by alkorlos** [comment]
Thank you!
