### ISSUE TITLE
Svelte - Swiper Hydration Issue / Bug

### ISSUE THREAD

**Issue by eftichis0202** [nolimits4web/swiper#7520]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/hg2ydd

### Bug description

Using swiper in svelte 5, i have the following bug:

<img width="1789" alt="image" src="https://github.com/nolimits4web/swiper/assets/110816063/27274077-c9bb-47d2-8b24-42a9f78ef5b1">

### Swiper version

"swiper": "^11.1.1"

### Platform/Target and Browser Versions

macOs Google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by eftichis0202** [comment]
still unresolved, closing this as i stopped using the package due to this

**Comment by MentalGear** [comment]
same, and svelte 5 will soon be released.
