### ISSUE TITLE
Autoplay keeps refresh my react app (only on iPhone)

### ISSUE THREAD

**Issue by giacomosx** [nolimits4web/swiper#7523]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://epicode-react-git-issueswiper-giacomosxs-projects.vercel.app/

### Bug description

With Autolay only on mobile (iPhone) everytime a slide change refresh is triggered without a reason.

### Expected Behavior

Whole app shouldn't be refreshed

### Swiper version

11.1.1

### Platform/Target and Browser Versions

iOS Chrome, iOS Safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Please provide a link to a codesandbox/jsfiddle

**Comment by azeos** [comment]
Sorry for writing on an old bug, but a client is reporting me the same behavior with v11.2.6. It only happens with iOS.
Did you find any solution?

I will try to make a demo, but I don't have an iPhone so I need someone to confirm the behavior.
