### ISSUE TITLE
Initial slide indexes producing inconsistent slides

### ISSUE THREAD

**Issue by alexrichardsweb** [nolimits4web/swiper#7527]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-vue-default-forked-w6nq9d?file=%2Fsrc%2FApp.vue%3A7%2C28

### Bug description

I have utilised Swiper to create a date slider, where each slide is a day of the current month, and the initial slide is set to today. So today I should expect to see 10th May.

As seen in the reproduction, when I set the initial slide to `10`, it displays the 11th slide, which seems correct as the 11th slide would be at index `10` - however if the initial slide is set to `11` it is also sets slide 11 as active, and when I set it to `9` it’s the 9th slide, and `8` to the 8th slide etc…

The same issue occurs when the initial slide is set to `20`, it sets slide 21 as active. It seems that any initial slide index ending with 0, including `0` itself, sets the index to itself + 1

### Expected Behavior

The initial slide indexes should be set consistently

### Actual Behavior

Initial slide indexes ending with 0 produce behaviour inconsistent with those not ending with 0

### Swiper version

10.5.0

### Platform/Target and Browser Versions

MacOS Chrome, also occurs in Firefox 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by nolimits4web** [comment]
It is because you use slidesPerGroup, as active index must be even to slidesPerGroup
