### ISSUE TITLE
swiper.destroy() not working when createElements is enabled

### ISSUE THREAD

**Issue by samzabala** [nolimits4web/swiper#7530]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-stupid-38lq4g?file=%2Findex.html

### Bug description

swiper.destroy() not working when createElements is enabled. wrapperEl is created dynamically when set to true, but destroy breaks scripts and returns fatal error when this is the setup

Error:
`0:4290 Uncaught TypeError: Cannot read properties of undefined (reading 'removeAttribute')`

Demo:
https://codesandbox.io/p/sandbox/swiper-stupid-38lq4g?file=%2Findex.html

Offending line was found ion the destroy method :

```
wrapperEl.removeAttribute('style');
```

could be fixed if there is a condition to check if it exists first

```
if(wrapperEl) wrapperEl.removeAttribute('style');
```

please help. thank

### Expected Behavior

destroy the slider

### Actual Behavior

destroys the site

### Swiper version

~11.0.5 - 11.1.1 and 11.1.2 checked

### Platform/Target and Browser Versions

Chrome/Edie/Webkit Mac OS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper
