### ISSUE TITLE
Swiper Scrollbar has false width

### ISSUE THREAD

**Issue by SYN-JS** [nolimits4web/swiper#7534]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://4lbhg2i5oc4j0l7e-66678718765.shopifypreview.com/products/kijimea-reizdarm-pro

### Bug description

The scrollbar width has the false value because --swiper-scrollbar-size, var(--swiper-scrollbar-top,auto) and the other scrollbar css variable are not defined.

### Swiper version

11

### Platform/Target and Browser Versions

Windows Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by SYN-JS** [comment]
![image](https://github.com/nolimits4web/swiper/assets/147045577/1de3b4ed-8de3-40dc-ae3b-62f23016e3d7)

**Comment by SYN-JS** [comment]
Here my code:

`<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
>

<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<div class="reviews-pdp-static">
  <h2 class="headline review-headline">{{ section.settings.headline }}</h2>
  <div class="swiper reviewsSwiper">
    <div class="swiper-wrapper">
      {% for block in section.blocks %}
        <div class="swiper-slide">
          <div class="stars">
            {% assign num = block.settings.reviewstars %}
            {% assign minusnum = 5 | minus: block.settings.reviewstars %}
            {% assign range = (1..num) %}
            {% assign rangeminus = (1..minusnum) %}
            {% for stars in range %}
              {% render 'icon-star-yellow-border' %}
            {% endfor %}
            {% for stars in rangeminus %}
              {% render 'icon-star-grey-border' %}
            {% endfor %}
          </div>
          <div class="review-text intend">
            {{ block.settings.review }}
          </div>
          <div class="review-author">
            {{ block.settings.reviewName }}
          </div>
        </div>
      {% endfor %}
      <div class="swiper-scrollbar"></div>
    </div>
  </div>
  <a class="reviews-button" href="#wrapper-abtest">{{ section.settings.buttontext }}</a>
</div>

<script>
  var swiper = new Swiper('.reviewsSwiper', {
    slidesPerView: 1,
    scrollbar: {
      el: '.swiper-scrollbar',
      draggable: true,
      snapOnRelease: true,
      dragSize: 'auto',
    },
    grabCursor: true,
    breakpoints: {
      777: {
        slidesPerView: 4,
        spaceBetween: 20,
      },
    },
  });
</script>`

**Comment by nolimits4web** [comment]
Your code is wrong. See docs https://swiperjs.com/swiper-api , scrollbar must be a child of the container

**Comment by SYN-JS** [comment]
Thank you very much!
My bad!
