### ISSUE TITLE
Cannot read properties of undefined (reading 'touchId')

### ISSUE THREAD

**Issue by luke-rogers** [nolimits4web/swiper#7538]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Unsure on reproduction steps

### Bug description

Cannot read properties of undefined (reading 'touchId') - occurring from [here](https://github.com/nolimits4web/swiper/blob/master/src/core/events/onTouchEnd.mjs#L12) when data is undefined. 

Happy to raise a PR to protect against `data` being undefined however I'm unsure if that's just covering up another issue.

```javascript
let e = event;
if (e.originalEvent) e = e.originalEvent;
let targetTouch;
const isTouchEvent = e.type === 'touchend' || e.type === 'touchcancel';
if (!isTouchEvent) {
    if (data.touchId !== null) return; // return from pointer if we use touch 
    // ^^ error here when data is undefined
    if (e.pointerId !== data.pointerId) return;
    targetTouch = e;
} else {
    targetTouch = [...e.changedTouches].filter(t => t.identifier === data.touchId)[0];
    if (!targetTouch || targetTouch.identifier !== data.touchId) return;
```

### Expected Behavior

No error occurs when data is undefined

### Actual Behavior

Cannot read properties of undefined (reading 'touchId')

### Swiper version

11.1.3

### Platform/Target and Browser Versions

We can see reports in Sentry for the following Chrome versions:
- Chrome 101.0.4951
- Chrome 102.0.5005
- Chrome 86.0.4240
- Chrome 104.0.0
- Chrome 103.0.5060
- Chrome 100.0.4896

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Repro steps are required as i can't imagine a situation when that touchEventsData is undefined

**Comment by luke-rogers** [comment]
I don't have reproduction steps right now, just a handful of reports in Sentry. 

We are looking at implementing session replay soon so I will have to come back when I have a reproduction.

**Comment by fredericDelaporte** [comment]
Same here, our Sentry logs are quite polluted by this error. But replays show nothing significant, no visible bugs on screen, no action on swipers, no idea what causes this. Excepted, each times some modal popin-like overlay is showing over the page having swipers. But when attempting to repro, no luck.

The stats of the errors show that is mostly, if not only, occurring with Chrome or "Chrome like" (Samsung Internet), 40% on Android, 38% under Windows, 22% under Mac OS X. Nothing under iOS, understandably if that is a Chrome specific issue.
