### ISSUE TITLE
creativeEffect not working ? - Nextjs - webComponent

### ISSUE THREAD

**Issue by KatuGT** [nolimits4web/swiper#7543]
### Check that this is really a bug

- [ ] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-creativeeffect-test-error-zrz7vf?file=%2Fapp%2Fpage.tsx%3A42%2C10

### Bug description

I am trying to implement this effect 
https://codesandbox.io/p/sandbox/swiper-effect-creative-forked-272t82?file=%2Findex.html%3A138%2C18-138%2C26 but as you can see in my reproduction, the "cards" just dont overlap

### Expected Behavior

I need it to work just like in the example, the cards should overlap

### Swiper version

11.0.6

### Platform/Target and Browser Versions

Chrome, Brave. Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You also need to set `init="false"` on `swiper-container` if you initilalize it manually
