### ISSUE TITLE
slidesPerView: "auto" doesn't work property (slidesPerView: "auto" == slidesPerView: 1)

### ISSUE THREAD

**Issue by pablo-miralles** [nolimits4web/swiper#7547]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/pablomiralles/pen/abrNoxd

### Bug description

As the title says, slidesPerView auto doesn't do anything by default, it's the same that using slidesPerView 1.

### Expected Behavior

I think the expected behaviour should be the same as what happens when you add .swiper-slide {width: auto} in my example, not being 100% by default.

It works perfect because when it's not slidesPerView auto, the .swiper-slide width is an inline JS style, so the specificity is higher.

### Actual Behavior

The actual behaviour is giving swiper-slide element a width: 100%

### Swiper version

11.1.3

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You must set slide's sizes in CSS
