### ISSUE TITLE
Get accessibility parameters from markup

### ISSUE THREAD

**Issue by alkorlos** [nolimits4web/swiper#7548]
### Clear and concise description of the problem

Currently, changing the default values of accessibility parameters is only possible with JavaScript API.

### Suggested solution

When using custom markup, it would be much more convenient to change aria attributes through the attribute value.

When setting
```js
navigation: {
  nextEl: '.swiper-button-next',
  prevEl: '.swiper-button-prev',
}
```
the accessibility parameters on the elements `.swiper-button-next` and `.swiper-button-prev` change the default values.

```html
<button class="swiper-button-next" aria-label="Siguiente diapositiva"></button>
```

### Alternative

Use JavaScript API
```js
navigation: {
  nextEl: '.swiper-button-next',
  prevEl: '.swiper-button-prev',
},
a11y: {
  nextSlideMessage: 'Siguiente diapositiva',
  prevSlideMessage: 'Diapositiva anterior'
},
```

With custom markup, specifying aria attributes in HTML will be more straightforward and easier to maintain.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
These values are also used in notification area, so we will stick with JS option
