### ISSUE TITLE
Dynamic bullets are reset in loop mode when the last slide reached

### ISSUE THREAD

**Issue by abachyla** [nolimits4web/swiper#7549]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-pagination-dynamic-forked-grl65r

### Bug description

When loop mode and pagination dynamic bullets are activated, if a user swipes from the last slide to the first, the dynamic bullets reset to their original state. This might cause confusion because it looks like the last slide has no next slides, and similarly, it's not evident on the first slide that swiping right to the last slide is possible.

![ScreenRecording2024-05-22at12 48 27-ezgif com-video-to-gif-converter](https://github.com/nolimits4web/swiper/assets/10487250/847543b5-c2e5-4d18-8785-aea2334601b5)

### Expected Behavior

Dynamic bullets should not reset.

![ScreenRecording2024-05-22at12 51 52-ezgif com-video-to-gif-converter](https://github.com/nolimits4web/swiper/assets/10487250/8d4128a1-e1f6-4135-b5e4-0cb84fcfce07)

### Actual Behavior

Dynamic bullets are reset.

### Swiper version

11.1.3

### Platform/Target and Browser Versions

Chrome/Safari/Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
This is how pagination works in general in Swiper. Otherwise, there is no really any sense to use here then if it always shows the same "picture"
