### ISSUE TITLE
First image not loading initially in Swiper with dir="rtl" in Next.js

### ISSUE THREAD

**Issue by shadizohari** [nolimits4web/swiper#7555]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/shadizohari/next-swiper

### Bug description

When using Swiper in a Next.js project with dir="rtl", the first image in the slider does not load initially. However, when i navigate to the next slide and then return to the first slide, it loads. This problem is resolved by setting loading="eager", but this approach sacrifices image optimization.
![screen-capture-_2_](https://github.com/nolimits4web/swiper/assets/54976879/77e16bb1-0d7f-4f64-adef-82542b2a7836)

### Expected Behavior

The first image in the Swiper slider should load when the component is rendered, even with dir="rtl".

### Actual Behavior

The first image does not load initially in the Swiper slider with dir="rtl.
Reloading occurs when returning to the first image after navigating to other slides.
Setting loading="eager" resolves the initial loading issue but sacrifices image optimization.

### Swiper version

11.1.3

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Search issue first before opening a new one
