### ISSUE TITLE
maxBackfaceHiddenSlides parameter doesn't work when given less than 10

### ISSUE THREAD

**Issue by rajagemini** [nolimits4web/swiper#7558]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/xctr65

### Bug description

When updating a swiper based with the new slides getting the Back Face slides even if we provide value to the Param maxBackfaceHiddenSlides to 0 or 1. This doesn't work when the value given for maxBackfaceHiddenSlides is less than 10.

### Expected Behavior

Back face should not display when updating the slides in the swiper.

### Swiper version

9.4.1 also happen with latest 10 and 11 version

### Platform/Target and Browser Versions

macOS chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
- Latest swiper version is 11.x
- Your demo link doesn't demonstrate the issue
