### ISSUE TITLE
Coverflow Effect Issue on new iOS Devices

### ISSUE THREAD

**Issue by ph7do6** [nolimits4web/swiper#7560]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/xsx2h9?migrateFrom=y57q8f

### Bug description

I called up the CodeSandbox "Element" via the [official demo page](https://swiperjs.com/demos#effect-coverflow), forked it and only set the depth parameter to 1000.
The Coverflow effect appears correctly on all devices except Apple devices (tested with iPhone and iPad) with iOS 17.4.1 and higher. Previously, it worked as expected under iOS 16.2, for example.

### Expected Behavior

The Coverflow effect should display as expected across all devices.
![expected_behavior](https://github.com/nolimits4web/swiper/assets/82054110/fce555b5-b238-4a74-a712-8ff5dcbd9f86)

### Actual Behavior

The Coverflow effect is displayed correctly on all devices except Apple devices with iOS 17.4.1 and higher.
![actual_behavior_on_iPhone](https://github.com/nolimits4web/swiper/assets/82054110/a39a8dcc-56df-4343-8477-09f4e5927662)

### Swiper version

11.1.3

### Platform/Target and Browser Versions

iPhone and iPad Safari iOS 17.4.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/6650
