### ISSUE TITLE
`slidesPerView: "auto"` and virtual slides support

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [nolimits4web/swiper#7561]
### Clear and concise description of the problem

From [virtual slides docs](https://swiperjs.com/swiper-api#virtual-slides)
> Note that according to Virtual Slides realization it doesn't work with Grid module and `slidesPerView: 'auto'`

Are there any plans to make the virtual module work with the `slidesPerView` property set to `"auto"`? I would like to be able to use these two things together.

### Suggested solution

I haven't looked at the source code, so I don't have any suggestions, sorry :slightly_frowning_face: 

### Alternative

In my project, I won't use virtual slides for now, because using a fixed `slidesPerView` value would change the width of my slides (I don't want larger gaps between slides on wider screens).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> Are there any plans to make the virtual module work with the slidesPerView property set to "auto"?

There is no such plans
