### ISSUE TITLE
Can't swipe when swiper slides are clickable elements

### ISSUE THREAD

**Issue by donghoon-song** [nolimits4web/swiper#7566]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-slides-per-view-auto-forked-tygvg2?file=%2Findex.html%3A64%2C39

### Bug description

I can't swipe slides which have only buttons.

### Expected Behavior

I can swipe slides.

### Actual Behavior

I can't swipe.

### Swiper version

11

### Platform/Target and Browser Versions

Chrome 125.0.6422.113

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Duplicate #7585
