### ISSUE TITLE
Loop mode leaves empty space after the last slide

### ISSUE THREAD

**Issue by Yaro77** [nolimits4web/swiper#7584]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-centered-forked-hxxxwj?file=%2Findex.html%3A87%2C27

### Bug description

How to get rid of empty space after the last visible slide? Forked "infinite loop" example.

![image](https://github.com/nolimits4web/swiper/assets/1245827/2aaabd5d-a2a6-4873-8177-edb19391d14c)

### Expected Behavior

No empty space, Next slide renders.

### Actual Behavior

Empty space. Last visible slide is actually the last child of .swiper-wrapper in the DOM.

### Swiper version

swiper@11

### Platform/Target and Browser Versions

windows 11, chrome 126.0.6478.63

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by shaobeichen** [comment]
I met same question，I used swiper 11 web component

**Comment by shaobeichen** [comment]
![image](https://github.com/nolimits4web/swiper/assets/18715564/a6952761-a7ea-4be1-95c2-f83945e7bec2)
I find a temp method, I observed call swiper.loopFix can resolve it in swiperslidechange method, but can't use it in swiperslidechange, because it would recursion, so I use loopFix in watch effect，watch effect have cache, so it can avoidance recursion.

**Comment by shaobeichen** [comment]
@Yaro77

**Comment by michaelbourne** [comment]
Can confirm on my end too. Any combination with 'loop: true` and 'centeredSlides: true` will cause this.

**Comment by 0x74h51N** [comment]
Hello @nolimits4web,

Unfortunately, the 11.1.9 update caused this issue in my Next.js project. I've tried different approaches but couldn't fix it. When I manually move the slides, it creates a space or causes the first slide to disappear. I also tested different versions, and 11.1.8 is very stable for me. Any suggestions on how to resolve this?

Thank you.

Related code:
````typescript
'use client';
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore from 'swiper';
import { EffectCoverflow, Autoplay } from 'swiper/modules';
import { memo, useEffect, useMemo, useRef, useState } from 'react';
import useDragHandler from '@/hooks/useDragHandler';
import { PortfolioItemProps } from '@/schemas';
import SlideMaker from './SlideMaker';

SwiperCore.use([Autoplay, EffectCoverflow]);

const CarouselSlider = ({ slides }: { slides: PortfolioItemProps[] }) => {
  const filteredSlides = useMemo(
    () => slides.filter((slide) => !slide.catalogue),
    [slides],
  );
  const swiperRef = useRef<SwiperCore | null>(null);
  const [activeIndex, setActiveIndex] = useState(() => {
    return 0;
  });

  const { hoverStart, hoverEnd } = useDragHandler();

  const onSlideChange = (swiper: any) => {
    setActiveIndex(swiper.realIndex);
  };

  const breakPoints = useMemo(
    () => ({
      0: {
        slidesPerView: 1.2,
      },
      640: {
        slidesPerView: 1.5,
      },
      1020: {
        slidesPerView: 2,
      },
    }),
    [],
  );
  useEffect(() => {
    if (swiperRef.current) {
      swiperRef.current.update();
    }
  }, [breakPoints]);
  const carouselSlides = useMemo(
    () =>
      filteredSlides.map((slide: PortfolioItemProps, index: number) => (
        <SwiperSlide key={index + 1}>
          <SlideMaker index={index} activeIndex={activeIndex} slide={slide} />
        </SwiperSlide>
      )),
    [filteredSlides, activeIndex],
  );

  return (
    <div
      onMouseEnter={hoverStart}
      onMouseLeave={hoverEnd}
      className="overflow-visible z-50"
    >
      <Swiper
        onInit={(swiper) => (swiperRef.current = swiper)}
        effect="coverflow"
        centeredSlides
        breakpoints={breakPoints}
        spaceBetween={0}
        loop
        coverflowEffect={{
          rotate: 0,
          stretch: 0,
          depth: 150,
          modifier: 3,
          slideShadows: false,
        }}
        onSlideChange={onSlideChange}
        autoplay={{
          delay: 6000,
          disableOnInteraction: false,
          pauseOnMouseEnter: true,
        }}
        speed={1500}
        className="cursor-none "
      >
        {carouselSlides}
      </Swiper>
    </div>
  );
};
export default memo(CarouselSlider);
````

**Comment by will-yellowpeach** [comment]
I'm still getting this issue. Presumably still a known problem?

**Comment by 0x74h51N** [comment]
I figured it out after reviewing 11.1.9 update [related change](https://github.com/nolimits4web/swiper/commit/4847fcba5dbe34caa91ea23b0bb72c8d40da0e63). It's about the slides' length. For example, if you show 4 slides per view (centered & loop) and the total length is 5, it will cause empty space after the last slide. You can fix it by duplicating the slides. @will-yellowpeach

**Comment by will-yellowpeach** [comment]
We've got 'slidesPerView' set to 'auto' but have duplicated the number of items x3 to ensure that it's not a number of slides issue, but it still persists - video here: https://github.com/user-attachments/assets/424f07bd-b827-4af4-b821-671d74e720d7

It seems to occur any time we use centeredSlides: true and loop:true together. If we set centeredSlides to false, the issue goes away and it handles it fine

**Comment by 0x74h51N** [comment]
I just figured out my issue with the length, but which version are you using? There’s another fix related to loop in the 11.1.10 [update](https://github.com/nolimits4web/swiper/pull/7690/files), but I’m not sure if it’s connected to this. Good luck..

**Comment by hipig** [comment]
This issue exists throughout the entire v11 version, why haven't we seen any fixes

**Comment by michaelbourne** [comment]
I haven't had this problem since [v11.1.11](https://github.com/nolimits4web/swiper/releases/tag/v11.1.11). Do any of you have a sandbox with the latest Swiper version where this can be replicated?

**Comment by dngraphisme** [comment]
Why is this issue closed @nolimits4web ? Loopmode on V11 is really complicated... I have exactly the same problem and can't patch it correctly....

**Comment by lilyreadmoo** [comment]
I also meet the same issue `"swiper": "^12.1.3"`
