### ISSUE TITLE
I can't swipe on a swiper slide with button.

### ISSUE THREAD

**Issue by donghoon-song** [nolimits4web/swiper#7585]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-default-forked-y9mnvz?file=%2Fsrc%2FApp.jsx%3A13%2C36

### Bug description

I can't swipe on a swiper slide with button.

https://github.com/nolimits4web/swiper/assets/32301380/5591fd01-eed4-40c9-a5e0-edf09414d9bd

same with swiper element.

https://codesandbox.io/p/sandbox/swiper-default-forked-fvs5t9?file=%2Findex.html%3A50%2C9

### Expected Behavior

I can swipe.

### Actual Behavior

I can't swipe.

### Swiper version

11.1.4

### Platform/Target and Browser Versions

Chrome 126.0.6478.63

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
t0ggles-create swiper

**Comment by nolimits4web** [comment]
You need to remove `button` from `focusableElements` parameter
