### ISSUE TITLE
Disable Slide

### ISSUE THREAD

**Issue by pensan** [nolimits4web/Swiper#76]
Hi,

is there a way to disable a slide? For example I don't want a user to be able to swipe to the last slide. The slide will be visible, but not in the center. So swiping forward should be disabled on the slide before the last.

Thank you in advance, pensan

**Comment by Moidul** [comment]
it is too late. but it may help others.
I had a similar issue.
Issue/Problem: I have [x] no of slides and [n] number of slide disabled. (x>n)
Expected behavior: user can see the disabled slide number in the pagination section but not able to click or see those disabled slides.

Solution:
File: Swiper.js
Define two new classes under the default parameters setting
1. bulletDisabledClass: 'swiper-pagination-bullet-disabled'
2. slideDisabledClass: 'swiper-slide-disable',
Update the updatePagination function (Line No: 938) 
instead of using numberOfBullets count all the slides including disabled by adding following line

s.updatePagination = function () {
            if (!s.params.pagination) return;
            if (s.paginationContainer && s.paginationContainer.length > 0) {
                var bulletsHTML = '';
                //var numberOfBullets = s.params.loop ? Math.ceil((s.slides.length - s.loopedSlides * 2) / s.params.slidesPerGroup) : s.snapGrid.length;
                //re-calculate 
                var allSlides = s.wrapper.children('.' + s.params.slideClass + ',.' + s.params.slideDisabledClass);

                for (var i = 0; i < allSlides.length; i++) {
                    var slide = allSlides[i];
                    if ($(slide).hasClass(s.params.slideClass)) {
                        if (s.params.paginationBulletRender) {
                            bulletsHTML += s.params.paginationBulletRender(i, s.params.bulletClass);
                        }
                        else {
                            bulletsHTML += '<' + s.params.paginationElement + ' class="' + s.params.bulletClass + '"></' + s.params.paginationElement + '>';
                        }
                    } else {
                        bulletsHTML += s.params.paginationBulletRender(i, s.params.bulletDisabledClass);
                    }
                }
                s.paginationContainer.html(bulletsHTML);
                s.bullets = s.paginationContainer.find('.' + s.params.bulletClass + ',.' + s.params.bulletDisabledClass);
                if (s.params.paginationClickable && s.params.a11y && s.a11y) {
                    s.a11y.initPagination();
                }
            }
        };


i did not test all the possible scenarios but served my purpose. Enjoy!!

**Comment by genjerdotcom** [comment]
just do like this man..
'
var swiper = new Swiper('.the-quiz', {
            pagination: '.swiper-pagination',
            paginationClickable: false,
            touchMoveStopPropagation:false,
            simulateTouch : false, 
            allowSwipeToNext: true, 
            allowSwipeToPrev: true,
            allowPageScroll: "auto ",
            nextButton: '.swiper-button-next',
            prevButton: '.swiper-button-prev'
        }).disableTouchControl();
'

**Comment by LucaBn** [comment]
I was able to prevent a user to swipe after a certain slide using this code:

// Example: I have n slides and I want to prevent SlideNext after the 5th slide

mySwiper.on('slideNextTransitionStart', function () {
	var stop_at = 5;
	var ri = swiper.realIndex;

	if (ri == stop_at) {
		this.allowSlideNext = 0;
	} else {
		this.allowSlideNext = 1;
	}
});

mySwiper.on('slidePrevTransitionEnd', function () {
	// If you go back to the prev slide, you'll be able again to swipe to the next slide
	this.allowSlideNext = 1;
});

**Comment by LucaBn** [comment]
I was able to prevent a user to swipe after a certain slide using this code:

// Example: I have n slides and I want to prevent SlideNext after the 5th slide

mySwiper.on('slideNextTransitionStart', function () {
var stop_at = 5;
var ri = swiper.realIndex;

if (ri == stop_at) {
  this.allowSlideNext = 0;
} else {
  this.allowSlideNext = 1;
}
});

mySwiper.on('slidePrevTransitionEnd', function () {
  // If you go back to the prev slide, you'll be able again to swipe to the next slide
  this.allowSlideNext = 1;
});
