### ISSUE TITLE
The switchover does not work properly

### ISSUE THREAD

**Issue by meikang123** [nolimits4web/swiper#7611]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-pagination-custom-forked-pnh6lk?file=%2Fsrc%2FApp.jsx%3A23%2C5

### Bug description

The UI does not display correctly

### Swiper version

10.0.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Link is not working, Swiper 10.0.0 is not maintained
