### ISSUE TITLE
Swiper "Coverflow" Effeect doesn't work on Android 

### ISSUE THREAD

**Issue by UzyOrg** [nolimits4web/swiper#7615]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Is just if the effect property has "none", it doesn't have an effect

### Bug description

I use Braze to send InApps to a native app, with html, css and js vanilla, I just copied the coverflow demo effect and the effect doesn't work on Android, but it worked fin on IOS.

### Expected Behavior

The 3D effect with the coverflow effect, it makes the centered card would have a higher z-index making this 3D effect

### Actual Behavior

The coverflow effect makes the centered card a z-index higher, making a 3D effect, but in Android every card is in the same level, there is no effect

### Swiper version

11

### Platform/Target and Browser Versions

Braze InApps 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look for issue on your side, it works on Android
