### ISSUE TITLE
Broken swiper core bundle via npm package

### ISSUE THREAD

**Issue by Group24Steven** [nolimits4web/swiper#7617]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/broken-swiper-bundle-q4fg4f?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clykhmoa100063j6i9d2na02d%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clykhmoa100023j6i5w0lqhf2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clykhmoa100043j6ilqjulizl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clykhmoa100053j6ivfym5mbo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clykhmoa100023j6i5w0lqhf2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clykhmoa100013j6ihofciwpm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clykhmoa100023j6i5w0lqhf2%2522%252C%2522activeTabId%2522%253A%2522clykhmoa100013j6ihofciwpm%2522%257D%252C%2522clykhmoa100053j6ivfym5mbo%2522%253A%257B%2522id%2522%253A%2522clykhmoa100053j6ivfym5mbo%2522%252C%2522activeTabId%2522%253A%2522clykiz0vz00bv3j6iuezwuhqn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A46017%252C%2522id%2522%253A%2522clykiz0vz00bv3j6iuezwuhqn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clykhmoa100043j6ilqjulizl%2522%253A%257B%2522id%2522%253A%2522clykhmoa100043j6ilqjulizl%2522%252C%2522activeTabId%2522%253A%2522clykhnmx1004u3j6iajw3odjv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clykhmoa100033j6ig9x6rakj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clykhnmx1004u3j6iajw3odjv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clykhnq1b003pdblx8h738j9p%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Bug description

Whenever importing the swiper bundle instead of using divided imports which provide functionality, swiper breaks. Instead, currently I am forced to use all children imports to get it working at all, no matter what I try to achieve building with swiper.
Maybe this is also important to mention - I am also using the typescript type definitions package ("@types/swiper" v6.0.0) because I was unaware of if this is already integrated inside the npm package called "swiper" or not. 

Framework usage? Astro.js, although this clearly shouldn't be an astro related mistake due to the fact that astro is quite a lightweight framework and as already descibred, it works using just the children imports...
I know that the sandbox link is based on angular environment, this is because it was the easiest for me to quick setup with the npm packages I am using in combination with swiper... However this shouldn't really matter but just proof that it's not an astro.js related error. 
Also, I was importing inside the reproduced code sample only the working imports because the bundle couldn't be found there at all. However, inside my astro project it could be found but it didn't work. So it seems like either in version v11.1.4 respectively the types version v6.0.0 either that bundle-package doesn't even exist, or it's broken...
Other information:
npm version - 10.8.2
node version - 22.4.1
nvm version - 0.39.7

### Expected Behavior

Should work flawlessly by just making one import statement with the bundle which should import all children bundles such as modules, stylesheets, etc.

### Actual Behavior

Currently it doesn't work and the functionality of the initialized swiper instances isn't working at all, no matter if declaring the modules inside the instances or not.

### Swiper version

11.1.4

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look for issue on your side, bundle there is fine
