### ISSUE TITLE
2 way control not working (swiper element)

### ISSUE THREAD

**Issue by philippbuerger** [nolimits4web/swiper#7628]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/philipp-buerger/pen/bGPeVpG

### Bug description

I have 2 swiper elements on one page. I want to do a 2 way control. Only the controlling from the second to the first is working.

### Expected Behavior

The sliders control each other

### Actual Behavior

Only the second slider controls the first

### Swiper version

11.1.5

### Platform/Target and Browser Versions

macOS, Chrome / Safari / Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by leegyusung** [comment]
In Our business, We're using two swipes, We're matching the two swipes through a function called thumbs.

However, At the version of 11.1.6
When I clicked swipe thumbnail that was matched through thumbs functions, then I clicked the swipe Slide of subordinate element. finally click event is not working how can i solve this problem?

**Comment by philippbuerger** [comment]
Hi @nolimits4web its still not working as expected for me. The 2 way control does not working initially. Only if the second slider is moved minimum 1 slide the sync seems to work.

**Comment by philippbuerger** [comment]
It seems that the cdn is not updated yet so the reproduction link has the old behavior. It tested it in my local env
