### ISSUE TITLE
swiper.extendDefaults is not a function

### ISSUE THREAD

**Issue by VIPStephan** [nolimits4web/swiper#7634]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://jsfiddle.net/Lnbxozus/

### Bug description

Running `swiper.extendDefaults();` according to the [API](https://swiperjs.com/swiper-api#method-swiper-extendDefaults) causes the error “swiper.extendDefaults is not a function”

### Expected Behavior

It should do something. It’s not really documented very well but I would expect that I can add new options, like:
```
swiper.extendDefaults({
	pagination: {
		el: '.swiper-pagination'
	}
});
```

### Actual Behavior

Nothing is happening but in the JS console the above mentioned error is printed.

### Swiper version

11.1.5

### Platform/Target and Browser Versions

macOS, Firefox 128

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It must be called on class `Swiper.extendDefaults` not on a swiper instance

**Comment by VIPStephan** [comment]
I’m not sure I understand. Is the API doc wrong, then? Because it clearly states

> After we initialize Slider we have its initialized instance in variable (like `swiper` variable in example above) with helpful methods and properties:

and it lists that method in the table there. Or am I misunderstanding something here? How is it called on the class?
