### ISSUE TITLE
Zoom, thumbs and grab scroll don't work anymore

### ISSUE THREAD

**Issue by DanielHelios** [nolimits4web/swiper#7636]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/hjrcp2

### Bug description

The functionalities for zoom, thumbnails, and grab scroll have stopped working. Specifically:

- Zoom Functionality: The zoom feature, which allows users to zoom in and out on images or slides, is no longer operational. This means that interactions to pinch or use zoom controls are ineffective.

- Thumbnails: The thumbnail navigation is not functioning. Clicking on thumbnails does not change the main slide view.

- Grab Scroll: The grab scroll feature, which enables users to click and drag the slide to navigate through the carousel, is also malfunctioning. Users are unable to click and drag to scroll through the slides as expected.

### Expected Behavior

- Zoom should work smoothly, allowing zooming in and out on slides.
- Thumbnails should be clickable to change the main slide.
- Grab scroll should allow users to click and drag to scroll through the slides.

### Actual Behavior

- Zoom does not respond to touch gestures or controls.
- Thumbnails do not change the main slide view or may not be displayed at all.
- Grab scroll is unresponsive to clicking and dragging.

### Swiper version

11.1.6

### Platform/Target and Browser Versions

Windows, Firefox 128

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by OSMANCAKlR** [comment]
Got the same problem here. All sites using swiperjs is not working anymore

**Comment by LowisSpross** [comment]
I still got the same problem.

**Comment by luangjokaj** [comment]
> I still got the same problem.

just upgrade to the latest version, it is fixed!

`"swiper": "^11.1.7"`

**Comment by michaelbourne** [comment]
New release isn't on jsdeliver yet, but 11.1.7 does indeed fix the issue.

**Comment by kyrylo-soulandwolf** [comment]
> > > I still got the same problem.
> > 
> > 
> > just upgrade to the latest version, it is fixed!
> > `"swiper": "^11.1.7"`
> 
> HI Thank you. I am using swiper per CDN right now.
> 
> Cool
> 
> <script src="https://cdn.jsdelivr.net/npm/swiper@11.1.7/swiper-bundle.min.js"></script>
> is working,
> 
> <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
> doesn't.
> 
> I assumed that the latter would automatically update to the latest minor version :)

It does update but it is aslo cached. When you notice this discrepancy, you can purge the latest version cache [here](https://www.jsdelivr.com/tools/purge).

**Comment by ariefurtado** [comment]
Hi!

I'm confused with a fuction and maybe I'm not seing the whole picture here, but in the `elementIsChildOf` function it references an `element` variable that doesn't exist in the block scope. Maybe it was meant to be `el` instead of 'element' ?

```js
// ...

function elementIsChildOf(el, parent) {
  const isChild = parent.contains(el);
  if (!isChild && parent instanceof HTMLSlotElement) {
    const children = [...element.assignedElements()];
    return children.includes(el);
  }
  return isChild;
}
```
