### ISSUE TITLE
Upgrade swiper

### ISSUE THREAD

**Issue by everfu** [nolimits4web/swiper#7642]
### Clear and concise description of the problem

Hi, swiper team update version to 11.1.7
https://cdnjs.com/libraries/Swiper

### Suggested solution

Hi, swiper team update version to 11.1.7
https://cdnjs.com/libraries/Swiper

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Ask CDN owners, not me
