### ISSUE TITLE
In Loop mode, when the length of swiperlist matches slidesPerView，the  image on the right will disappear.

### ISSUE THREAD

**Issue by StarsLeopard** [nolimits4web/swiper#7691]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos

### Bug description

In Loop mode, when the length of swiperlist matches slidesPerView and centeredSlides: true is set, the carousel image on the far right will disappear.

Below is the options

![image](https://github.com/user-attachments/assets/e26dd90b-5c74-4c0a-b633-b82e9f13ffdb)

https://github.com/user-attachments/assets/a4022146-cf9c-46b8-a451-f196bd4a4455

### Expected Behavior

shows the right image

### Actual Behavior

the right image disappear

### Swiper version

11.1.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Read docs for the loop mode please
