### ISSUE TITLE
Swiper is not working when grabbing in gaps between slides

### ISSUE THREAD

**Issue by VladyslavPolushyn** [nolimits4web/swiper#7692]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-freemode-6psx54

### Bug description

Swiper is not working when I try to grab in the space between the slides.
It works good for the first 2-3 slides and then bug occurs.
Real issue when you need a huge gap between the slides.

https://github.com/user-attachments/assets/528d1844-7b95-46e8-8f95-d994c04be6bc

### Expected Behavior

Swiper must works correctly when you grabbing in any place of it.

### Actual Behavior

Swiper is not working when I try to grab in the space between the slides.

### Swiper version

11.1.9

### Platform/Target and Browser Versions

macOS Chrome 127.0.6533.100

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Search existing issues first
