### ISSUE TITLE
Params set in beforeInit() are overwritten when breakpoints are set

### ISSUE THREAD

**Issue by cyberhouse-packages** [nolimits4web/swiper#7694]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-default-forked-tjtmyr

### Bug description

When setting params in beforeInit() they are overwritten in the Swiper core init(). Breakpoints have to be set, and the screen needs to be in smallest size (< ~sm).

As I see in the expend() function from the setBreakpoint() in init():

### Expected Behavior

The beforeInit should also be able to set params. It is convient since the swiper instance is already available.

### Actual Behavior

The params (e.g. slidesOffsetBefore) are overwritten when set in beforeInit.

### Swiper version

11.0.5

### Platform/Target and Browser Versions

macOS Chrome 127.0.6533.120 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can use `swiper.originalParams` instead
