### ISSUE TITLE
There is a significant performance issue on mobile devices (iPhone 15 pro)

### ISSUE THREAD

**Issue by NirBenjano-TripActions** [nolimits4web/swiper#7698]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/hopeful-artem-6f5wv2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm05krd2s00063b6igatiuzzn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm05krd2s00023b6iq5jix3wp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm05krd2s00033b6i8ogbu4mc%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm05krd2s00053b6ib1x6m4jv%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm05krd2s00023b6iq5jix3wp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm05krd2s00013b6i5odznadg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522cm05krd2s00023b6iq5jix3wp%2522%252C%2522activeTabId%2522%253A%2522cm05krd2s00013b6i5odznadg%2522%257D%252C%2522cm05krd2s00053b6ib1x6m4jv%2522%253A%257B%2522id%2522%253A%2522cm05krd2s00053b6ib1x6m4jv%2522%252C%2522activeTabId%2522%253A%2522cm05krfxo000r3b6iw6vpkobk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm05krd2s00043b6iyx6psfaw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm05krfxo000r3b6iw6vpkobk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm05krd2s00033b6i8ogbu4mc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm05krd2s00033b6i8ogbu4mc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Bug description

We installed SwiperJs version 11.1 in our project and it looks great. However, when I open the site on real device, iPhone 15 pro, I saw a significant performance issue in other elements of the page.

On mobile view, we show 5 checkbox above the fold and render SliderJs below the fold. On mobile device, there is a delay when clicking on those checkboxes. If I remove SwiperJs the delay is gone.

We tried to downgrade to version 10.3.1 and the problem was gone. Therefore, I believe there is a significant performance issue on version 11+ on real mobile devices.

To confirm the bug, I opened your playground site - https://studio.swiperjs.com/play and clicked on the toggles very fast. I saw the same performance issue that we had on our website.

We also tried to use the web component version, which has the same problems. Therefore, we think it is a core issue.

### Expected Behavior

The screen should be interactive without and delays.

### Actual Behavior

The user cannot check all checkboxes fast on mobile device.

You can try https://6f5wv2.csb.app/ 

### Swiper version

11.1.10

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Thanks for the demo, but i don't see any performance issues on it when viewing the link from an iPhone Safari

**Comment by NirBenjano-TripActions** [comment]
Open on chrome.

**Comment by Xenossolitarius** [comment]
@NirBenjano-TripActions can you update your Chrome browser and try it out now? I've noticed significant performance drop also and....now it seems to be gone. If it's because of Chrome release I'll pull my hair out. Lost 2 days on this for it suddenly to start working out of the blue

**Comment by nolimits4web** [comment]
So closing as not related to Swiper
