### ISSUE TITLE
Swiper core will dispatch all event listeners on resize

### ISSUE THREAD

**Issue by odedsh3** [nolimits4web/swiper#7700]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/g5pgrj

### Bug description

Event listeners like:
.on('transitionStart'
.on('transitionEnd'
.on('reachEnd'

will be triggered on resize event.

The way to reproduce the issue is just to add one of the listeners on a full-size swiper and just change the window size constantly while and after the transition.

### Expected Behavior

event should be triggered only when specified by the docs

### Actual Behavior

event triggered in a loop

### Swiper version

11

### Platform/Target and Browser Versions

macOS chrome browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by michalpawlowski34** [comment]
Also experienced that. What makes it more interesting is that it bugs also when zooming in/out in Chrome.
Generally speaking resizing does not cooperate well with the SwiperJS. 

Another weird case I experienced when resizing: #7579

**Comment by nolimits4web** [comment]
It is by design as during resize swiper translates/transitions to another position, plus your demo doesn't illustrate the issue
