### ISSUE TITLE
SwiperJS Fade (+Cross) Effect: Previous Slide Transition Broken

### ISSUE THREAD

**Issue by saas786** [nolimits4web/swiper#7709]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/saas/pen/yLdqjwN

### Bug description

I've typically relied on the slide effect for most of my projects because the fade effect has never worked smoothly for me.

I finally took the time to investigate the issue, but I couldn't pinpoint the exact problem. 

Here’s the gist:

When I enable the fade or cross-fade effect, the next slide transitions smoothly with the fade effect, but the previous slide does not. 

This issue arises because I compensate for another problem I frequently encounter—sliders of variable sizes that reveal slides behind the active slide. To address this, I apply `visibility: hidden` to all non-active slides.

Now, I’m stuck in a dilemma: I can either avoid using the fade effect altogether, use it but with broken transitions (which isn't ideal), or enable the fade effect while revealing other slides unnecessarily.

### Expected Behavior

When I apply the fade or cross-fade effect, it should work seamlessly for both next and previous slide transitions.

Additionally, with variable-sized images, the slider should only display the active image without revealing any others.

### Actual Behavior

When I apply the fade or cross-fade effect, it fails to work seamlessly for the previous slide transition.

Additionally, with variable-sized images, the slider reveals images other than the active one, which should not happen.

### Swiper version

11.1.11

### Platform/Target and Browser Versions

Windows

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I don't get what is the issue? Here everything works correctly https://codepen.io/nolimits4web/pen/QWXBBQQ Why do you need to set `visibility: hidden`? Not active slides are already hidden by opacity

**Comment by saas786** [comment]
@nolimits4web 

Please check it now. You can test it both with and without `visibility: hidden`.
