### ISSUE TITLE
TypeError when Swiper instance is destroyed right after zooming

### ISSUE THREAD

**Issue by Heptonius** [nolimits4web/swiper#7722]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-react-zoom-pqy2gq

### Bug description

On a project we have an image gallery build on top of Swiper. We have the zoom functionality enabled. On mobile we have a functionality in place that checks whether or not you have swiped the image in the vertical direction (gallery set to horizontal mode) and we close the gallery when this happens. However, both things - zooming + swiping (onTouchStart - onTouchEnd) - can happen at the same time. This means there are cases in which the swiper gallery is closed right after the zoom happens.

During zooming, there is a `setTimeout` call with callback that invokes the `allowTouchMove`
https://github.com/nolimits4web/swiper/blob/d0b6abd74805398ac3cbf41aeebf141a805ec64b/src/modules/zoom/zoom.mjs#L249

However, the asynchronous nature of `setTimeout` in our use case makes it happen after the instance is destroyed. Which leads to TypeErrors:

```
../../node_modules/swiper/modules/zoom.mjs in allowTouchMove at line 216:1

TypeError
Cannot set properties of undefined (setting 'preventTouchMoveFromPointerMove')
```

Reproduction link note: Our setup to reproduce this issue is quite complex and unreliable, but I think the issue is hopefully described/obvious enough. If not, I can try to setup a proper repro sandbox.

### Expected Behavior

No errors are thrown after the Swiper instance is destroyed right after zooming.

### Actual Behavior

Unreliably the error is thrown after the Swiper instance is destroyed right after zooming.

### Swiper version

11.1.4

### Platform/Target and Browser Versions

Android Chrome 128

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Fixed by https://github.com/nolimits4web/swiper/pull/7723
