### ISSUE TITLE
Parallax with transition timing function work incorrect

### ISSUE THREAD

**Issue by Lenetta** [nolimits4web/swiper#7731]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/Lenetta/pen/zYVmLem

### Bug description

Hi!
Thanks for the cool slider.
Unfortunately, I have a problem.
I would like to be able to add transition-timing-function to prallax slides, but when adding it to the example, prallax behaves very strangely.
I tried to set it both to the element where prallax is located and to slide-wrapper, but nothing helped.
Is there a way to add such a function? Or tell me how to implement such behavior

P.S. In the example, transition-timing-function is commented out

### Expected Behavior

When switching to the next slide, the slide is layered on the current one using the transition timing function

### Actual Behavior

With the transition timing function set in styles and switching, slides disappear/appear from different sides and the prallax effect disappears

### Swiper version

7.4.1

### Platform/Target and Browser Versions

Windows 10, Chrome 128.0.6613.120

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
I have uncommented the transition-timing-function and everything works fine for me https://codepen.io/nolimits4web/pen/gONEyyb. Can't see the issue, also note the latest Swiper version is 11.x.x

**Comment by Lenetta** [comment]
This is amaizing, thank you!
You uncommented both swiper-wrapper and slide-bgimg and it works as expected, but I did it with either the first element or the second and the effect was completely different.
