### ISSUE TITLE
Web element component not working in Vue

### ISSUE THREAD

**Issue by milanAtCognishine** [nolimits4web/swiper#7732]
### Check that this is really a bug

- [ ] I confirm

### Reproduction link

https://stackblitz.com/edit/vitejs-vite-yve9m8?file=src%2FApp.vue

### Bug description

When using swiper-container and swiper-slide components in Vue.js with the provided code, web elements are not behaving as expected. Additionally, CSS often fails to load correctly, causing layout and style issues. The issue occurs intermittently and occasionally triggers console errors related to Swiper's rendering.

I want know if i am missing something in configuration.

## NOTE
I was using node@16 in my project then i switched to v20 and it started to break like css file path is correct but can't import it onto TS or SCSS file.
![Screenshot 2024-09-11 at 6 30 22 PM](https://github.com/user-attachments/assets/03a041e7-c89f-4dac-9364-165960d41307)

### Expected Behavior

The swiper-container should render with proper CSS styles and spacing between slides.
Swiper's built-in navigation and pagination should function without errors.
Event listeners for swiperprogress and swiperslidechange should trigger appropriately.

### Actual Behavior

CSS styles for the Swiper component do not load consistently.
Sometimes console errors are thrown, and the Swiper component does not initialize properly.
Slides render incorrectly, or the Swiper is not fully functional.

### Swiper version

11.1.12

### Platform/Target and Browser Versions

MacOS / Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Not sure where it comes from as i don't see such error in console and in your demo. Probably something related to Vuejs/Vite miss configation
