### ISSUE TITLE
Pagination variables not defined

### ISSUE THREAD

**Issue by clubside** [nolimits4web/swiper#7734]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://hulkercafe.com/swiper/

### Bug description

None of the relevant variables for placing the navigation items are defined:

--swiper-navigation-sides-offset
--swiper-pagination-bottom
--swiper-pagination-top

So only the first slide has the navigation elements visible, they disappear after changinging slides.

### Expected Behavior

When navigating between slides the previous and next buttons and pagination dots should remain in the same place.

### Actual Behavior

Navigation elements disappear after navigating to another slide.

### Swiper version

11.1.12

### Platform/Target and Browser Versions

Windows 10, Chrome latest

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You should follow correct HTML layout in order to achieve that https://swiperjs.com/swiper-api#swiper-full-html-layout . It has nothing todo with the variables
