### ISSUE TITLE
Swiper pagination attributes not working in version 11

### ISSUE THREAD

**Issue by DwieDima** [nolimits4web/swiper#7756]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-pagination-custom-forked-699cxl?workspaceId=71f9cf4f-2658-4dd2-bdd0-72a5185c26f3

### Bug description

Pagination-related attributes (pagination="true", pagination-clickable="true", and pagination-el=".custom") that functioned correctly in SwiperJS version 9 are no longer working in SwiperJS version 11.

Just swap out in `https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js` to `swiper@9` to see a working result.

### Expected Behavior

Swiper Elements with with pagination on version 11 should also work like in version 9

### Actual Behavior

pagination bullets are not rendered

### Swiper version

11

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by studiohic** [comment]
Having exactly the same issue...

**Comment by nolimits4web** [comment]
Swiper Element styles are incapsulated now. If you use custom elements you need to provide styles for them
