### ISSUE TITLE
Swiper React dir prop doesn't update dynamically

### ISSUE THREAD

**Issue by rasecaccedo** [nolimits4web/swiper#7760]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/infallible-https-5lp72t

### Bug description

Reading the documentation and the samples (https://codesandbox.io/p/sandbox/infallible-https-5lp72t) it seems that the directionality is handled using the `dir` setting/prop
![Screenshot 2024-10-09 at 12 35 32](https://github.com/user-attachments/assets/29cc49ad-eed6-4229-9284-f3e80a87df7c)

Considering this, I'm using such a prop to handle directionality based on an internal prop/state on the usage of the component.

The issue is that the `dir` prop on the Swiper component doesn't work when such prop/state is updated dynamically.

As an example, you can see the linked [CodeSandbox](https://codesandbox.io/p/sandbox/infallible-https-5lp72t) which uses a button and a React state to change such value on the inner prop of the Swiper, which changes the Slides positioning, but not the Arrows/Navigation cases.

This is due to the inner classNames list not updating to add/remove the `swiper-rtl` class

<img width="472" alt="Screenshot 2024-10-09 at 12 40 11" src="https://github.com/user-attachments/assets/0fb4e1ec-9829-4463-9b2c-6bd81f53ecb5">

### Expected Behavior

Changing the `dir` Swiper option/prop should update all the related Swiper directionality to allow such directionality change to be applied to:
- Slides
- Arrows/Navigation
- Pagination
- ...

### Actual Behavior

Changing the `dir` Swiper option/prop should update the Slides, but not the Arrows/Navigation styles/behaviour

### Swiper version

11.1.14

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Swiper won't support changing dir property. You need to re initialize it after you change it
