### ISSUE TITLE
swiper(freemode)  in ios safari browser, sliding is not smooth

### ISSUE THREAD

**Issue by feibi8597** [nolimits4web/swiper#7766]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/150-freemode/core

### Bug description

Please test this case in ios safari browser and android browser.
In the ios safari browser, When swiping to the right, the swiper will first have a displacement to the left and then slide to the right, which visually has a feeling of stuttering. But in the android browser，sliding is very smooth , doesn't have the situation like in ios safari browser

### Expected Behavior

Whether it's on Android or iOS, Swiper needs a smooth swipe

### Actual Behavior

https://github.com/user-attachments/assets/6fb938ec-fe39-4dde-916c-025e20d0141f (ios safari video)

https://github.com/user-attachments/assets/d8c785a6-7e97-4520-b7d0-96c35d291905 (android video)

### Swiper version

11.1.14

### Platform/Target and Browser Versions

iphone safari 17

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by t596502** [comment]
+1

**Comment by nolimits4web** [comment]
Can't see such issue
