### ISSUE TITLE
Property 'slidesEl', 'slidesGrid', 'slidesSizesGrid' does not exist on type 'Swiper'

### ISSUE THREAD

**Issue by davindev** [nolimits4web/swiper#7767]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/property-slidesel-slidesgrid-slidessizesgrid-does-not-exist-on-type-swiper-vckw95

### Bug description

I am using Swiper in a React + TypeScript environment.
To access the properties of the Swiper instance, I am importing the type as shown below:
```ts
import { Swiper as SwiperType } from 'swiper';
```
While using various properties of the instance, I encountered the following type errors:
```
Property 'slidesEl' does not exist on type 'Swiper'.ts(2339)
Property 'slidesGrid' does not exist on type 'Swiper'.ts(2339)
Property 'slidesSizesGrid' does not exist on type 'Swiper'.ts(2339)
```
When checking the instance using `console.log()`, I was able to confirm that these values are present.
However, it seems that these types are missing from the Swiper type definitions.

(There is a similar issue [here](https://github.com/nolimits4web/swiper/issues/7605), but since type errors are also occurring with the `slidesEl` and `slidesSizesGrid` properties in addition to `slidesGrid`, I have created a new issue.)

### Expected Behavior

The properties `slidesEl`, `slidesGrid`, and `slidesSizesGrid` are displayed as part of the Swiper interface.

### Actual Behavior

When accessing the `slidesEl`, `slidesGrid`, and `slidesSizesGrid` properties, the following type errors occur:
```
Property 'slidesEl' does not exist on type 'Swiper'.ts(2339)
Property 'slidesGrid' does not exist on type 'Swiper'.ts(2339)
Property 'slidesSizesGrid' does not exist on type 'Swiper'.ts(2339)
```

### Swiper version

11.1.4

### Platform/Target and Browser Versions

All

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
fixed in https://github.com/nolimits4web/swiper/pull/7768
