### ISSUE TITLE
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0

### ISSUE THREAD

**Issue by grygork** [nolimits4web/swiper#7771]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/zf6kxq

### Bug description
![Zrzut ekranu 2024-10-18 o 09 12 49](https://github.com/user-attachments/assets/59351f7d-a246-4d33-8eda-742e2a65be23)

Deprecation Warning on line 13, column 9 of node_modules/swiper/swiper.scss: 
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

### Expected Behavior

Compatibility with Dart Sass 3.0.0.

### Swiper version

11.1.14

### Platform/Target and Browser Versions

Dart Sass 3.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR 

You can check PR here: https://github.com/nolimits4web/swiper/pull/7772

**Comment by Swineherdd** [comment]
same stuff mate

**Comment by Lovely-Ruby** [comment]
how to solve it? my console has so many warning like this. i use `quietDeps = true` but not useful.
![image](https://github.com/user-attachments/assets/654aa44f-bacb-4d60-9624-f2ee5bddd89c)

**Comment by poconri** [comment]
same here

**Comment by sshiling** [comment]
same here

**Comment by TimurNazarov** [comment]
Change @import to @use
https://sass-lang.com/documentation/at-rules/use/

**Comment by knakamura13** [comment]
> Change @import to @use https://sass-lang.com/documentation/at-rules/use/

I know this comment is getting downvoted, but I found this while trying to migrate from `@import` to `@use` and thought I'd share how to properly migrate it yourself:

Change this:
```scss
@import 'stylesheet.scss'
```

to this:
```scss
@use 'stylesheet.scss' as *;
// or `@use 'stylesheet.scss' as stylesheet;`
// which can then be used like `font-size: stylesheet.$font-size;`
```

**Comment by heyrian** [comment]
same here

**Comment by Maxssobolev** [comment]
@knakamura13 , i've changed, but warnings still in console
![image](https://github.com/user-attachments/assets/828c3b75-52e8-4630-9c51-a64613afc714)

**Comment by Vladislav-096** [comment]
Is it necessary to use @use instead of @import now? I added `css: {
    preprocessorOptions: {
      scss: {
        api: 'modern-compiler',
      },
    },
  }`
  also to my vite.config, but i still see warning

**Comment by SirH3nry** [comment]
What are my options if I've got (S)CSS properties in the files I want to import globally as well, and not just "variables, mixins, and functions".

**Comment by Strateg81** [comment]
Watch message in console! 
 "... More info: https://sass-lang.com/d/legacy-js-api" . 
"... You can use [the Sass migrator](https://github.com/sass/migrator#readme) to automatically update your stylesheets to use the module system.

$ npm install -g sass-migrator
$ sass-migrator module --migrate-deps your-entrypoint.scss

($ sass-migrator module --migrate-deps <path/to/style.scss>)

I done it - and it works! 
But at the end I'got message in console: 'Nothing to migrate!'

**Comment by Beanmommo** [comment]
> > Change @import to @use https://sass-lang.com/documentation/at-rules/use/
> 
> I know this comment is getting downvoted, but I found this github thread while trying to migrate from `@import` to `@use` and thought I'd share how to properly migrate it yourself:
> 
> Change this:
> 
> ```css-scss
> @import 'stylesheet.scss'
> ```
> 
> to this:
> 
> ```css-scss
> @use 'stylesheet.scss' as *;
> // or `@use 'stylesheet.scss' as stylesheet;`
> // which can then be used like `font-size: stylesheet.$font-size;`
> ```

After changing to @use it shows a Deprecation Warning 
![image](https://github.com/user-attachments/assets/9cbf489c-3121-4fa7-9306-691859e4e3e6)

**Comment by Strateg81** [comment]
> After changing to @use it shows a Deprecation Warning ![image](https://private-user-images.githubusercontent.com/106414531/382178046-9cbf489c-3121-4fa7-9306-691859e4e3e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDUwODAsIm5iZiI6MTczMDQ0NDc4MCwicGF0aCI6Ii8xMDY0MTQ1MzEvMzgyMTc4MDQ2LTljYmY0ODljLTMxMjEtNGZhNy05MzA2LTY5MTg1OWU0ZTNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNzA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q0MTQ0OTg2ZDM1Y2JhY2NiY2RkNWZiZTM1MmNiNDFkZjNkY2UyNWJmNTA5N2E4ZmJkNmQwZjIwMTYwZTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QZ2XGmaqU3YvfrzyoGQTc221bno_P4N9LLXbU9CkUWg)

Yes, I got too! U must change your js-files.

**Comment by felixxxxxs** [comment]
While it's necessary for everyone to update their own stylesheets to use `@use` and `@forward` instead of `@import`, this issue is about the Swiper stylesheets still using `@import`.
Fixing my own stylesheets will not remove the deprecation warnings coming from the Swiper stylesheets. The Swiper stylesheets need to be updated accordingly. Or am I missing something? 🤔

**Comment by ohabash** [comment]
sass used to be the best part of my job.

**Comment by suxscribe** [comment]
So no way to use global variables now without having to import them in each and every scss component?

**Comment by martinille** [comment]
Downgrading sass to ~1.32.0 helped me.

**Comment by headless-kjh** [comment]
this one is helpful 
`@include meta.load-css("style.scss");`

**Comment by Roozenlz** [comment]
> Downgrading sass to ~1.32.0 helped me.

I use ~1.77.5 helped me.

**Comment by DJHONATANFN** [comment]
VUE CLI 3, BOOTSTRAP 5.3.3 Y SASS 1.77.5 me funciona perfecto...

`const { defineConfig } = require('@vue/cli-service');
module.exports = defineConfig({
	transpileDependencies: true,
	css: {
		loaderOptions: {
			scss:{
				additionalData: `@import '~@/assets/scss/index.scss';`
			}
		}
	}
});`

**Comment by hiepduc24089** [comment]
try to change @import to @use but you need to reference variables with the namespace if you use variables

**Comment by fabpico** [comment]
Downgrade. `npm install sass@1.79`.

**Comment by IvanLudvig** [comment]
this is why web development sucks

**Comment by hammermaxmann** [comment]
SASS should be renamed SUS

**Comment by darckex** [comment]
Dowgrading to 
`npm i sass@1.77.1` also removes the warning
Deprecation Warning: The legacy JS API is deprecated and will be removed in 
Dart Sass 2.0.0.

**Comment by exrhizo** [comment]
Ran into this here: https://github.com/palantir/blueprint/pull/7251

library doesn't have a long term plan, one of those things where people depend on the api in ways you don't want perhaps

I also downgraded to `~1.77.5`

**Comment by MGeurts** [comment]
I also downgraded to ~1.77.6

**Comment by scissorstail** [comment]
To prevent users from encountering difficulties, it may be beneficial to provide clear downgrade instructions in the official documentation as a contingency for urgent cases.

**Comment by pmagunia** [comment]
I was able to fix errors like these with the SASS Migrator module:

`npm install -g sass-migrator`
`sass-migrator module --migrate-deps _sass/jekyll-theme-prologue.scss`

**Comment by gormov1122** [comment]
For crying out loud, Sass, how much longer will you keep making developers' lives miserable... It looks like only complete removal will free us from the problems of this currently useless preprocessor.

**Comment by joeskeen** [comment]
For others in this boat - I noticed one of my library imports were using `@use` instead. I converted all my `@import`s with `@use` with no other changes and the warnings went away.

**Comment by davidAtInleague** [comment]
What is the correct way to translate this kind of usage of `@import`?

```
.scope3rdPartyRules {
  @import '3rd-party-rules';
}
```
