### ISSUE TITLE
Pagination shows incorrect number of bullets or slides count for type "fraction" when `slidesPerView` != 1

### ISSUE THREAD

**Issue by polarbirke** [nolimits4web/swiper#7775]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/polarbirke/pen/zYgdReX

### Bug description

Swiper's Pagination Module uses the internal `snapGrid` Array to calculate the total of Pagination steps. The Array is subsequently used determine either [the total number of bullets](https://github.com/nolimits4web/swiper/blob/40a705e5bcadf2ee2ee90591ff9ed95c1aaf9026/src/modules/pagination/pagination.mjs#L287-L289) (`type: 'bullets'`) or [the total number of slides](https://github.com/nolimits4web/swiper/blob/40a705e5bcadf2ee2ee90591ff9ed95c1aaf9026/src/modules/pagination/pagination.mjs#L120-L122) (`type: 'fraction'`).

If `slidesPerView` is set to a number =! 1, the snapGrid Array will correctly determine the amount of swipe steps needed, but its length will no longer reflect the actual number of slides. This is especially noticeable if Pagination type "fraction" is used (see example). I first encountered this with partial slides (`slidesPerView: 2.75`), but as is shown in the reproduction link, it also happens with `slidesPerView` set to integers and also if the slides total is evenly divisible by the factor.

<img width="1728" alt="Bildschirmfoto 2024-10-21 um 09 42 49" src="https://github.com/user-attachments/assets/b1e7ecd5-bc11-472a-ab08-0388ad5d6fdc">

### Expected Behavior

I would expect the number of bullets as well as the total displayed for type "fraction" to reflect the **actual number of slides**.

### Actual Behavior

The number of bullets and the total displayed for type "fraction" **do not** reflect the actual number of slides.

### Swiper version

11.1.14

### Platform/Target and Browser Versions

macOS Firefox 113, macOS Chrome 129

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is based on the amount in slidesGrid, as the total number is the amount of "slide" points, it won't have much sense to show something like 7/9 on the last slide and user won't be able to slide next.

**Comment by Badlapje** [comment]
> It is based on the amount in slidesGrid, as the total number is the amount of "slide" points, it won't have much sense to show something like 7/9 on the last slide and user won't be able to slide next.

Is there a way of overriding it so the amount of bullets matches the amount of slides?  Users are getting confused over this.  I get that it shows slide points now, but users don't.

**Comment by anthonygoodandproper** [comment]
In case this helps anyone in the future setting "slidesPerGroup" option to the same as "slidesPerView" works a bit nicer as it moves multiple slides at once so the bullets make a bit more sense.
