### ISSUE TITLE
Slide disappear when using loop and centeredSlides

### ISSUE THREAD

**Issue by cristianfierro** [nolimits4web/Swiper#792]
Hi,

I'm having a problem when using swiper with centeredSlides and loop. I have a slider with 3 slides. I click the next button twice to go to the third slide and then click the previous button to go back to the second slide, and the previous slide (the first one) from the actual active slide disappears, is like the loop brokes for some reason and the duplicated slide is not visible since in the html the duplicated slides exists

Here is my code:

```
mainSliderSwiper = new Swiper('.main-slider .swiper-container',{
      slidesPerView: 'auto',
      centeredSlides: true,
      speed: 600,
      loop: true,
      loopedSlides: 2,
      pagination: '.pagination',
      paginationClickable: true,
      cssWidthAndHeight: true,
      initialSlide: 0
    });
    $('.main-slider .swiper-controls .swiper-prev-area').on('click',function(){
      mainSliderSwiper.swipePrev();
    });
    $('.main-slider .swiper-controls .swiper-next-area').on('click',function(){
      mainSliderSwiper.swipeNext();
    });
  }
```

The captures from firbug of the html:

Initial State
![00 initial state](https://cloud.githubusercontent.com/assets/750394/3069741/665cbeac-e2a0-11e3-98d8-015741934fc7.png)

After clicking next once (second slide centered):
![01 next clicked once second slide visible](https://cloud.githubusercontent.com/assets/750394/3069744/665e09ba-e2a0-11e3-9c2a-a5899b7e4c39.png)

After clicking next twice (third slide centered):
![02 next clicked twice third slide visible](https://cloud.githubusercontent.com/assets/750394/3069742/665cb9d4-e2a0-11e3-99cf-4d2be6c7496d.png)

After clicking previous once to return to second slide ( second slide centered  and first slide disappears):
![03 previous clicked once second slide visible first slide disappears](https://cloud.githubusercontent.com/assets/750394/3069743/665cc578-e2a0-11e3-8bc0-3e6fe990c4c2.png)

**Comment by daniellucindo** [comment]
thank you :+1:
