### ISSUE TITLE
Implementation swiper slider in bootstrap tabs, resizeFix, reInit()

### ISSUE THREAD

**Issue by juraa09** [nolimits4web/Swiper#817]
I am beginner front-end developer. I have little problem with sliders in tabs. My sliders work but while i switch to second slider I can't see it. slider lost width and height If I resize site by responsive tools of firefox slider generates width and height. I used resizeFix()' and 'reInit()' but doesn't work

Could you help me http://stackoverflow.com/questions/24142330/resizefix-reinit-sliders

**Comment by 91Abdullah** [comment]
Thankyou very much you saved my life ^__^ 

May happiness be with you always! :)
