### ISSUE TITLE
Lagging movement while swiping/dragging on Android

### ISSUE THREAD

**Issue by lutvianes** [nolimits4web/Swiper#824]
I use Google Chrome in Nexus 4. While swiping on Android, there was a lag movement. The animation itself is smooth, but when I touch and start dragging, the slide stopped for a while and then it slide. It happened when there were images & long text in one slider. But using "mySwiper.swipeNext()" result in smooth animation.

I used progress plugin, but without plugin also does same lag movement. I also found out that using option 'watchActiveIndex: true' make things worse. It lags even more.

Here is my code:

	var mySwiper = new Swiper('.swiper-container', {
	    progress: true,

	    onProgressChange: function(swiper){
	        for (var i = 0, len = swiper.slides.length; i < len; i++){
	            var slide = swiper.slides[i];
	            var progress = slide.progress;
	            var translate, boxShadow;
	            if (progress<=0) {
	                translate = progress*swiper.width;
	                boxShadowOpacity = 0;
	            } else {
	                translate=0;
	                boxShadowOpacity = 1 - Math.min(Math.abs(progress),1);
	            }
	            $(slide).css({
	                boxShadow: '0px 0px 10px rgba(0,0,0,1)'
	            });
	            swiper.setTransform(slide,'translate3d('+(translate)+'px,0,0)');
	        }
	    },
	    onTouchStart:function(swiper) {
	        for (var i = 0, len = swiper.slides.length; i < len; i++){
	            swiper.setTransition(swiper.slides[i], 0);
	        }
	    },
	    onSetWrapperTransition: function(swiper, speed) {
	        for (var i = 0, len = swiper.slides.length; i < len; i++){
	            swiper.setTransition(swiper.slides[i], speed);
	        }
	    },
	});

**Comment by danschumann** [comment]
I notice this too.  I'm using mostly all defaults.  Is the easing function very slow to start?  It would be nice if it started at the same velocity when the touch is released.  I'm going to roll my own quick since I only need simple stuff mimicking a home screen anyway.
