### ISSUE TITLE
Multiple sliders

### ISSUE THREAD

**Issue by gnnpls** [nolimits4web/Swiper#840]
I have a problem with swiper slider. I create an html page which dynamically change images according to an entry which is viewed. I have one slider and when i double click on image a new slider with different name is opened. When I close with fadeOut the "Zoomed Image" the previous slider does not respond. What is more if I double click again on the image and try to go back (i hide actually the zoomed div), i get an error of undefined 'browser' on the script of idangerous. on line 59 (version 2-1-min.js)

Any help appreciated.

**Comment by studiowebmarker** [comment]
$('.swiper').each(function (index){

			var swiper = new Swiper($(this)[0],{
				pagination: $(this).find('.swiper-pagination')[0],
				paginationClickable: true,
				nextButton: $(this).find('.next')[0],
		        prevButton: $(this).find('.prev')[0],
				//effect: 'fade',
				grabCursor: true,
				triggerOnTouchEnd:false,
				loop: true,
			});
		})
