### ISSUE TITLE
Visibility API with loop is broken

### ISSUE THREAD

**Issue by mhoyer** [nolimits4web/Swiper#841]
We would like to use Swiper in a similar way like your *Slides Visibility API* [demo](http://www.idangero.us/sliders/swiper/demos.php). 

But if we also enable the `loop: true` feature the cycling seems to reinitialize or calculates wrong.

You can check this Plunkr for reproduction: http://plnkr.co/edit/PtDQFcpflMiI5t8XOgcq (see line 151). The plunkr is based on https://github.com/nolimits4web/Swiper/blob/ce80e25/demos/16-visibility-api.html

**Comment by bb** [comment]
Is this fixed now or won't fix? What's the status?

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/Swiper/issues/1092
