### ISSUE TITLE
loop: true, clones slides

### ISSUE THREAD

**Issue by danielocdh** [nolimits4web/Swiper#865]
I'm working on a project where I will have custom resizer functions applied to elements (triggered by window resize), all the elements are referenced on a variable that has the element reference and the type of resize along with other data.

Everything works perfect when using loop:false, but when using loop:true the referenced elements become invisible to jQuery (':visible' selector), and I can't get the height of the elements. Also I'm using ids inside the slides, if I need to do something on an item by id I probably will run into problems.

I'm showing only one slide at a time, and will have 3 or more so I don't think I need the duplicates anyway.

Is there any workaround for this, or some approach I should take?

**Comment by quoctiennguyen** [comment]
@nolimits4web you can't say that (most of developers...) in many case we need to use id, like working will old project, working with google ad...
I think when duplicate, api should change the id

**Comment by denditang** [comment]
@nolimits4web  I think it can be considered without dulipcate to achieve loop.
ids in most project is must ，In particular reference to the third party components
