### ISSUE TITLE
loop: true destroys all data and eventHandlers

### ISSUE THREAD

**Issue by MichielDeMey** [nolimits4web/Swiper#874]
Looking through the API, I've noticed that you can set data associated with the slide using the `swiper.setData('key', value)` function.

This works when you don't set it in loop mode.

Though, when you do set loop mode, looking at the code (`_this.createLoop`) you build the HTML, concatenating a whole bunch of HTML strings and dumping it into the wrapper.

In the process destroying anything that could have been attached to that slide, such as eventHandlers and data set through `swiper.setData('key', value)`.

Any reason that you are not using deep clones to build the loop?
Deep clones will maintain eventListeners and other custom properties/data associated with the DOM node.

Here's an example:

```javascript
var swiper = new Swiper(element, {
  loop: true,
  onSlideClick: clickHandler
});

function clickHandler(swiper) {
  var item = swiper.clickedSlide.getData('itemObject');
  // will log 'undefined' because this data is destroyed
  console.log(item);
}

// Populate the swiper with the slides
for (var i = 0; i < items.length; i++) {
  var item = items[i];
  var slideDOM = swiper.createSlide('', 'swiper-slide', 'div');

  slideDOM.setData('itemObject', item);

  // Append the slide to the swiper component
  slideDOM.append();
}

``` 

This example will print undefined when attempting to log the `itemObject` associated with the slide.
It will work however if you disable loop mode.

**Comment by MichielDeMey** [comment]
Has this issue been addressed?

**Comment by nolimits4web** [comment]
@MichielDeMey https://github.com/nolimits4web/Swiper/issues/1092
