### ISSUE TITLE
First slide not centered

### ISSUE THREAD

**Issue by kleewan** [nolimits4web/Swiper#886]
When I load the page, first slide is not centered; I can see 17 pixels of the previous slide on the left side. However, as soon as I start sliding, everything works correctly. That's a very strange behavior. I've set a very basic example here:

https://dl.dropboxusercontent.com/u/78441873/swiper/index.html

Original css is left untouched. I've only added
img {
	max-width: 100%;
	height: auto;
}
and I've set up the slider with the calculateHeight option set to true, so the slider is fully responsive. From what I can see, slides' width and height are calculated correctly, I can't find the problem.

![issue](https://cloud.githubusercontent.com/assets/8401264/3866474/2e97e40e-1fd3-11e4-8b7a-7ffe84d90315.jpg)

**Comment by JacobDB** [comment]
For anyone coming to this more recently, do `mySwiper.update()` instead. I've also had success putting the swiper initialization inside of a `window.onload = function () { ... }`.
