### ISSUE TITLE
Variable Width / Height Slides in a Multi-Slide View

### ISSUE THREAD

**Issue by davidmcooper** [nolimits4web/Swiper#891]
Is there any built-in functionality allowing the swiper to display a multi-slide container with variably-sized slides?  I'm interested in something similar to what's shown in this screen-shot:

![image](https://cloud.githubusercontent.com/assets/867436/3890896/a3c1b3e2-2224-11e4-8b83-415774faedfe.png)

Each swipe would advance the container to the start of the next slide.

**Comment by fdamore1984** [comment]
the link is broken and i didnt find this demo in the documentantion in http://idangero.us/swiper/demos/

i got the same issue, i tried to set slidesPerView:'auto' but it doesnt work

**Comment by jacardarelli** [comment]
@fdamore1984 I found the demo, it's called "Centered Slides + Auto Slides Per View" and here is the updated link: http://idangero.us/swiper/demos/08-centered-auto.html
