### ISSUE TITLE
Connected swipers

### ISSUE THREAD

**Issue by MAXiDROME** [nolimits4web/Swiper#921]
How to make the same?
http://sorgalla.com/jcarousel/examples/connected-carousels/

With navigation buttons it is simple, just calling bigpics.swipeNext();smallpics.swipeNext(); in one event.
But when I try to handle slide event it becomes unaligned.

**Comment by tangien** [comment]
Bit late on this post, but that might help:

    <div id="gallery_thumbs">
    <img src="demo/products/1/medium/1.jpg" class="img-fluid" alt="">
    <img src="demo/products/1/medium/2.jpg" class="img-fluid" alt="">
    <img src="demo/products/1/medium/3.jpg" class="img-fluid" alt="">
    <img src="demo/products/1/medium/4.jpg" class="img-fluid" alt="">
    <img src="demo/products/1/medium/5.jpg" class="img-fluid" alt="">
    <img src="demo/products/1/medium/6.jpg" class="img-fluid" alt="">
  </div>
  <div class="swiper-container" id="gallery_main">
    <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="demo/products/1/large/1.jpg" class="img-fluid" alt=""></div>
      <div class="swiper-slide"><img src="demo/products/1/large/2.jpg" class="img-fluid" alt=""></div>
      <div class="swiper-slide"><img src="demo/products/1/large/3.jpg" class="img-fluid" alt=""></div>
      <div class="swiper-slide"><img src="demo/products/1/large/4.jpg" class="img-fluid" alt=""></div>
      <div class="swiper-slide"><img src="demo/products/1/large/5.jpg" class="img-fluid" alt=""></div>
      <div class="swiper-slide"><img src="demo/products/1/large/6.jpg" class="img-fluid" alt=""></div>
    </div>
    
    <div class="swiper-button-next swiper-button"></div>
    <div class="swiper-button-prev swiper-button"></div>
  </div>


<script>
var galleryThumb = $( "#gallery_thumbs img" );
var galleryMain = $( "#gallery_main" );

var galleryTop = new Swiper(galleryMain, {
	spaceBetween: 10,
	navigation: {
		nextEl: '.swiper-button-next',
		prevEl: '.swiper-button-prev',
	},
	on: {
		slideChange: function () {
			var index = galleryTop.activeIndex;
			galleryThumb.removeClass('active');
			galleryThumb.eq(index).addClass( "active" );
		},
		init: function() {
			galleryThumb.eq(0).addClass( "active" );
			galleryThumb.on('click mouseover', function() {
				var index = galleryThumb.index( this );
				galleryTop.slideTo(index, 0);
			})
		}
	}
});
</script>
