### ISSUE TITLE
Active index goes to the duplicate slides.

### ISSUE THREAD

**Issue by parijatsardesai** [nolimits4web/Swiper#959]
I am initializing the carousel before any slides are added and then adding the slides with the help of an Ajax call.
The problem which i am facing is that the active index goes to the first duplicate slide. 
If i try manually moving it to the 0th slide it shows a transition effect on load for the safari on  MAC. firefox seems to be working ok with this. But surely need to figure out a way in which the focus should stay on the actual first slide on creation of new slides.

**Comment by zwlcoding** [comment]
@nolimits4web 

How to destroy it? Re-init?
I use removeAllSlides and reInit， but it does not work correctly
