### ISSUE TITLE
Sliding can get stuck in between slides when tapped.

### ISSUE THREAD

**Issue by X4arms** [nolimits4web/Swiper#98]
I found that if you swipe then quickly tap the swiped slide, sometimes the slide animation will stop mid-slide and be "stuck" in between slides instead of always snapping to either the next or original slide. Any way to avoid this? (I tested using the default swiper demo)

**Comment by ivanberry** [comment]
Sorry to bother  this day.  but what's the params or things I should do to fix this? I got this problem in latest Swiper. Yeah, I tried set 'freeModeMomentum' to false. but the experience is weird. Thanks!
