### ISSUE TITLE
Auto play not working

### ISSUE THREAD

**Issue by ikixxx** [nolimits4web/Swiper#988]
I'm trying to start the slider playing immediately, but i can't get it to work. I've tried with and without `onFirstInit` callback.
```javascript
            var defaultData = {
            mode: 'horizontal',
            loop: true,

            slidesPerView: 2,
            roundLengths: true,
            autoPlay:2000,
            keyboardControl: true,
            onFirstInit:function(swiper)
            {                
                swiper.startAutoplay();
            },
            onInit: function (swiper) {
                var num = ($(window).width() < 800) ? 2 : 4;
                swiper.params.slidesPerView = num;
            }
        };
```
Also, unrelated, I've noticed that `onInit` is fired on every `window resize` event. You might want to optionally debounce that.

**Comment by pat-sullivan** [comment]
I know this is old, but in case anyone else finds themselves here. Change "autoPlay" to "autoplay" in the parameters, and it should fix the issue.
