### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toFixed' of undefined.

### ISSUE THREAD

**Issue by marianbodisteanu** [nolimits4web/Swiper#989]
Hello. I have configured a demo like this one: 14-different-widths.html

When there is one item and I call swiper.swipePrev(); everything is ok, when I call swiper.swipeNext(); I get this error: Uncaught TypeError: Cannot read property 'toFixed' of undefined.
It happens here:
_this.swipeNext = function (runCallbacks, internal) {
        if (typeof runCallbacks === 'undefined') runCallbacks = true;
        if (!internal && params.loop) _this.fixLoop();
        if (!internal && params.autoplay) _this.stopAutoplay(true);
        _this.callPlugins('onSwipeNext');
        var currentPosition = _this.getWrapperTranslate().toFixed(2);
        var newPosition = currentPosition;
        if (params.slidesPerView === 'auto') {
            for (var i = 0; i < _this.snapGrid.length; i++) {
                if (-currentPosition >= _this.snapGrid[i].toFixed(2) && -currentPosition < _this.snapGrid[i + 1].toFixed(2)) {

I dont think anyone will need a carousel with one item, just letting you know.

**Comment by marcelboettcher** [comment]
Hey,
I got the same error using this options when dragging the slides very far out of the left view port. It should snap back to the last slide, but all slides are outside the view and this error is throw on line: 

`` if (-currentPosition >= _this.snapGrid[i].toFixed(2) && -currentPosition < _this.snapGrid[i + 1].toFixed(2)) ``


```
	swiperOptions = {
		slidesPerView: 'auto',
		watchActiveIndex: true,
		centeredSlides: false,
		resizeReInit: true,
		keyboardControl: false,
		noSwiping: false,
		offsetPxAfter: 1000
	};
```

I think option offsetPxAfter is related to this error as lowering that value depending on the window width avoids the error.

Please tell me if you need more information or help fixing it. Thx
Marcel

**Comment by marcelboettcher** [comment]
ok, I digged into it. The problem is using i+1 in the loop. The correct solution should look like this (untested!):

```
        var currentPosition = _this.getWrapperTranslate().toFixed(2);
        var newPosition = currentPosition;
        if (params.slidesPerView === 'auto') {
        	new foundNewPosition = false;
            for (var i = 0; i < _this.snapGrid.length-1; i++) {
                if (-currentPosition >= _this.snapGrid[i].toFixed(2) && -currentPosition < _this.snapGrid[i + 1].toFixed(2)) {
                    newPosition = -_this.snapGrid[i + 1];
                    foundNewPosition = true;
                    break;
                }
            }
            //not found as it's just one slide or currentPosition is greater than last slide
            if(!foundNewPosition) {
            	newPosition = -_this.snapGrid[_this.snapGrid.length-1];
            }
```

Scenarios:
- for loop need to the last but one slide
- if there is just one slide, use that one
- if the currentPosition is out of range use the last slide

I guess the previous function should be checked for the same error as well.

Looking forward for you fix, thanks a lot!

**Comment by mantismamita** [comment]
Hello, I'm wondering what happened to this fix. I have to use v2 of swiper because of IE compatability another possibility would be:
```
if (params.slidesPerView === 'auto') {
            for (var i = 0; i < _this.snapGrid.length; i++) {
                if (_this.snapGrid[i + 1] !== undefined){
                    if (-currentPosition >= _this.snapGrid[i].toFixed(2) && -currentPosition < _this.snapGrid[i + 1].toFixed(2)) {
                        newPosition = -_this.snapGrid[i + 1];
                        break;
                    }
                }
            }
        }
```
I could do a PR if it would help.
