### ISSUE TITLE
How to use swiper with meteor 1.0?

### ISSUE THREAD

**Issue by solderzzc** [nolimits4web/Swiper#994]
I need swipe horizontally with dynamic data in meteor, but it still not simply working, any idea?
    <template name='gallery'>
      <div class="swiper-container" id="swiper-container1">
         <div class="swiper-wrapper">
          <div class="swiper-slide">
            {{#each gallery_images}}
              <div style="background-image:url(data:image/png;base64,{{base64encoded}})"></div>
            {{/each}}
          </div>
         </div>
      </div>
    </template>

    Template.gallery.helpers({
      gallery_images: function(){
        return Images.find();
      }
    });
	Meteor.startup(function(){
      
        console.log('Initial Swiper');
        var swiper = new Swiper('.swiper-container',{
            resistance : '100%',
            createPagination:false,
            loop: false
        });
        swiper.reInit();
        function onDeviceReady() {
            getAllPhotos();
        }
        document.addEventListener("deviceready", onDeviceReady, false);
    });

**Comment by lukemt** [comment]
I'm sure Swiper works very well with Meteor 1.0. Try using Template.gallery.redered() instead of Meteor.startup(). If that doesn't help, consider asking on StackOverflow.
I recommend to close the Issue.

**Comment by solderzzc** [comment]
Thanks, let me close this issue.

**Comment by lukemt** [comment]
i played around with it a little bit, but it's indeed tricky once you need reactivity. Do you still need it? I plan to write a little tutorial about this. Maybe I'll make a package too.

**Comment by solderzzc** [comment]
Thanks for your attention.
I finally integrated swiper with meteor through the _uihook and rendered
event. The research costed me days...
It will be very nice to have such hack things out of box.

**Comment by lukemt** [comment]
indeed!

Using _uihook is fine art.  Would you mind sharing some of your code?
The current hackpad solution I have uses a dirty setInterval :)

Here is what i've got so far:
MeteorPad - Swiper with reactive data - Draft
http://meteorpad.com/pad/Lg8r8Xdwzk7Q93yfc/Swiper%20with%20reactive%20data

Current issues:
- Neither the swiper instance nor the setInterval instance will ever be destroyed. 
- setInterval might be the wrong approach, better use _uihooks
- using the loop option of swiper will not work very well

**Comment by solderzzc** [comment]
I just reviewed my code and my memory. _uihook is needed when the reinit is
not fully supported likes masonry, so it can't be data driven.
_uihook is DOM driven. The trouble is browsers may destroy elements for
memory or whatever reason when triggered. So my following code on masonry
is not done...

  var hooks = {

    // the only document I found here
https://github.com/percolatestudio/transition-helper/blob/master/transition-helper.js#L4

    insertElement: function(node, next) {

      console.log('Inserted node id is ' + node.id);

      $(node)

      .insertBefore(next);

      Deps.afterFlush(function(){

        var alreadyHave = false;

        var nodeID = node.id;

        for(var i = 0;i < masonryItemList.length;i++){

          if(masonryItemList[i]===nodeID){

            alreadyHave = true;

            break;

          }

        }

        if(alreadyHave !== true){

          $(node).width();

          var $container = $('#pin_container');

          if(!!$container.data('masonry')){

            $container.masonry( 'appended', node );

            $('.item img').lazyload({

                effect: 'fadeIn',

                threshold : 200

            });

          } else {

            masonize(function(){});

          }

        }

      });

    },

  }

  Template.article.rendered = function(){

    if (this.firstNode.parentNode._uihooks !== hooks){

      this.firstNode.parentNode._uihooks = hooks;

    }

  }


For my project used swiper, since the reinit support is very good, I then
implement with data driven(Deps.autorun) to get rid of DOM maintain trouble.


This is very simple:

JS:

    Template.gallery.helpers({

      gallery_images: function () {

        return allImages

      },

      count:function(){

        return allImages.fetch().length;

      }

    });




    onGetThumbnailsSuccess=function(data){

      this.thumbnails = data;


      for(var i = 0;i<data.length;i++){

        if(data[i]){

          Images.insert(data[i]);

        }

      }

    }

    KindOfAJAXFunction(onGetThumbnailsSuccess);


    Deps.autorun(function(){

      allImages = Images.find();


      if(mySwiper){

        mySwiper.reInit();

      }

      console.log('Images number changed to ' + allImages.fetch().length);

    });


    Template.gallery.rendered = function(){

      console.log('Initial for gallery rendered');

      mySwiper = new Swiper('.swiper-container',{

        slidesPerView: 2

      });

      //mySwiper.reInit();

    }


HTML(Template):


<template name='gallery'>

  <div><h2>{{count}}</h2></div>

  <div class="swiper-container">

    <div class="swiper-wrapper">

        {{#each gallery_images}}

        <div class="swiper-slide">

          <img alt="Embedded Image"
src="data:image/png;base64,{{base64encoded}}" />

        </div>

        {{/each}}

    </div>

  </div>

</template>

**Comment by lukemt** [comment]
thanks a lot!

**Comment by jaredtmartin** [comment]
So, I'm a little lost here.  Does this work? solderzzc's code is very hard to read. Is there a working version of this on meteorPad?

**Comment by lukemt** [comment]
Hi @jaredtmartin,

only the version I posted above. As long as you do not need the loop-option (of swiper.js) you can go with it until something more holistic comes up, or improve on it and share the code.
I do actually plan making a swiper-package. 

[MeteorPad 1 - Swiper simple static](http://meteorpad.com/pad/Fp4KzKR4u2Xe69TFj/Swiper)
[MeteorPad 2 - Swiper with reactive data](http://meteorpad.com/pad/Lg8r8Xdwzk7Q93yfc/Swiper%20with%20reactive%20data)
