### ISSUE TITLE
Trying to use scrollContainer get Uncaught TypeError: Cannot read property 'getWidth' of undefined 

### ISSUE THREAD

**Issue by DebPenny** [nolimits4web/Swiper#997]
Trying to use swiper to just scroll a div horizontally.  When I use scrollContainer I see this error in console:
Uncaught TypeError: Cannot read property 'getWidth' of undefined 

I have tried many settings to no avail.  What am I doing wrong?

var mySwiper = new Swiper('.swiper-container', {

scrollContainer:true,
        cssWidthAndHeight:true,
        autoResize : true,
        freeMode : true,
        freeModeFluid:true,
        simulateTouch:true,
        resizeReInit: true

     });

**Comment by busla** [comment]
getting the same error on my VPS but not localhost. Here is my jsFiddle (although it´s not working for some reason)

http://jsfiddle.net/81deowgy/
